### ISSUE TITLE
(Easy Install) Subliminal Not Working

### ISSUE THREAD

**Issue by Tobyyyy** [SynoCommunity/spksrc#1028]
First i would like to say thank you very much i have waited with great anticipation for the packages to be up on easy install and i hope this is the right place to post this.

I have installed python and subliminal from synocommunity repo and rebooted but subliminal is not downloading any subtitles. Nothing happens after the specified time or when i click "Scan" manually and i have several files that is not 7 days old.

Im on a DS214Play and the settings are as shown below:
![pic1](https://cloud.githubusercontent.com/assets/3637736/3139022/3c1c6b14-e8c3-11e3-8bf3-8abc2cb382cc.PNG)
![pic2](https://cloud.githubusercontent.com/assets/3637736/3139023/3c2f7c04-e8c3-11e3-9170-a4f08c6ee7ab.PNG)

I tried adding a directory directly to where episodes are stored (the boardwalk empire), if it was a problem of depth, but that was not the case either.

**Comment by Exellent1988** [comment]
i have a prob with subl. its not loading at all ( in dsm-webgui) it says loading ... and the app loading hover thingy... any ideas?

**Comment by robbaman** [comment]
I have a problem with the scheduler. After installing Subliminal on my Synology and pointing it to the download folder it will not automatically download items. When clicking the manual 'Scan' button it'll download whatever subs are missing, but when setting the task to run at a specific time nothing happens.

The log file only gets one line added:
MM/dd/yyyy hh:mm:ss:INFO:root:Running scan

And then nothing. Anyone have any ideas? Like I said, clicking the scan button manually does work.

**Comment by Dr-Bean** [comment]
The Subliminal package has been updated. I'll be closing this issue, because a lot of different things are discussed here. If you run into problems with the package, please open a new issue.

**Comment by JanOonk** [comment]
I have installed v0.6.4-10 for more than a year now. Never worked. Then I noticed this thread about people having the same issue and that there's a long awaited update. So I thought I would give it a try.

But the first thing I noticed is that on the main page https://synocommunity.com/packages
the latest version is listed as v0.6.4-10. But when you go to the details of the package https://synocommunity.com/package/subliminal it says v.0.7.5-11.
Synology Package Center also reports v0.6.4-10 as the latest??

Nonetheless I would give it a try and I uninstalled and reinstalled but it keeps installing v.0.6.4-10. I already had added the repo http://packages.synocommunity.com/ (amongst some others).
Also after my reinstall I can't start Subliminal anymore.

I am using DSM 5.1-5022-Update 4.

**Comment by rockisdead** [comment]
i installed subliminal 0.8.0-dev with python 2.7.9-13 . But it has no dsm gui. i run it with scripts.
installation is simple, 
1-) download subliminal-master from https://github.com/Diaoul/subliminal
2-) download setuptools from https://pypi.python.org/packages/source/s/setuptools/setuptools-15.1.tar.gz#md5=10407f6737d8dc37e5310e68c1f1f6ec
3-) install python 2.7.9-13 from synocommunity
4-) Extract tar.gz file. In command line, you can type "tar xvf setuptools-15.1.tar.gz"
5-) In the setuptools folder, type "python setup.py install"
6-) extract subliminal-master.zip
7-) in the subliminal-master folder type "python setup.py install"
Subliminal is in /usr/bin/
my script as an example=
#!/bin/sh
/usr/bin/subliminal -l tr -s -p opensubtitles -c /volume1/pool/script/cache/a.txt -v /volume1/video/Sub-bin
