### ISSUE TITLE
SABNZBD Cannot create directory

### ISSUE THREAD

**Issue by Flynsarmy** [SynoCommunity/spksrc#1031]
It seems a frenshly installed SABNZBD from the newly working Synocommunity repo on a DS1813+ doesn't work correctly. When opening SAB I get warnings

>  ERROR: Cannot create directory /volume2/path/to/downloads

The path is owned by admin:users and has the permissions drwxrw----. Is the SABNDB app not part of the users group? I notice when clicking Browse in Config - Folders - Temporary Download Folder it can see /volume2/files (owned by root:root - created with Control Panel - Shared Folder) but can't see any subfolders (all owned by admin:users).

**Comment by wickedwally** [comment]
Hi everyone,

First and foremost, thank you to all the people responsible for helping to bring Sabnzbd and all the various other goodies to Synology.  Special thanks to DrBean, & Diaoul who's names have come up across many forums regarding Synology.

Although this topic has been closed, it seems the most relevant to the issue I am having; Sab and CP not being able to create or view folders through their respective GUI despite being able to see them in DSM GUI.  After reading a number of posts, I believe it is an issue that has to do with permissions.

I am running 1815+ (DSM 5.1) and have previously been able to install Sab, CP, & SB on a 1511+.  Although I ran into a few issues with the 1511, they have been relatively trivial.

Admittedly, I am a newb so please excuse any rudimentary questions and statements but I have a strong will and a desire to learn.  To date, I have relied mostly on the DSM GUI and have had VERY little experience with ssh.

Having said that, I wanted to turn to you all before attempting to ssh into my 1815 in fear that I may cause more damage than good.

I appreciate any direction and guidance you may be able to provide!

**Comment by Diaoul** [comment]
Try to set permissions for the users group in DSM to the problematic
directories.

To give a little background, Synology changed their default setting for
their shares with DSM 5.0 and did not provide packagers a way to circumvent
permission issues. We have some pending work with dedicated group creation
for Syncthing, that's still a workaround but it works. I'm still waiting
for a response from Synology that doesn't make sabnzbd and others run as
root for obvious security reasons.

**Comment by wickedwally** [comment]
Thanks Diaoul!  I deleted my post because I ended up trying to SSH into the Synology and i chmod 777 /volume1/downloads/

Although I am glad that works, I'm going to try and figure out how to set up a group for SAB, SB, CP, etc so that only those programs will have RW access to necessary folders.  It just seems more secure that way.

Heartfelt thank you again for your reply!

**Comment by fvdm** [comment]
Fwiw, I've been puzzeling with this problem the last couple of days and the solution of @Dr-Bean fixed it for me:

`> synoacltool -add test/testfolder group:users:allow:rwxpdDaARWc--:fd--`

SABnzbd 0.7.20 (SynoCommunity)
DSM 5.2-5592 Update 1

**Comment by Dr-Bean** [comment]
For the record, @fvdm, you can give the `users`group the necessary permissions via the DSM web interface. There's no need to use the CLI for that - unless you prefer to use it over the interface of course ;)

**Comment by fvdm** [comment]
@Dr-Bean yes normally the UI is fine, but for sabnzd only running `synoacltool` fixed the problem.

**Comment by Dr-Bean** [comment]
I think I disagree :) Anyway, good that you solved your issues.

**Comment by lc-tknoop** [comment]
I fixed it by setting the following permissions via DSM:

![image](https://cloud.githubusercontent.com/assets/7056445/9727601/20b66c1a-5633-11e5-8499-18f02f3d85c8.png)
