### ISSUE TITLE
SSLH Will not allow an admin to configure the application

### ISSUE THREAD

**Issue by bladehawk** [SynoCommunity/spksrc#1052]
I've installed SSLH on my DS410 and it seems to be running.  If I launch the app it says, "Please login as admin first, before using this webpage".  I've logged into the admin account and it continues to give this message. 

Attempts to connect to port 443 with SSH fail.

**Comment by KiefDelicious** [comment]
@Dr-Bean Hello, as I can install the package (as Beta) on my Synology, does that means you activated it again? Because the bug is still in there ;)

**Comment by Dr-Bean** [comment]
Thanks for the info, it was reactivated by accident.
As an FYI: when PR #1212 gets merged, the web interface will be removed. Even with the access issues removed, the interface itself is too buggy to leave it there.

**Comment by bladehawk** [comment]
I didn't do anything. 

On February 7, 2015 10:18:51 AM PST, KiefDelicious <notifications@github.com> wrote:
>@Dr-Bean Hello, as I can install the package (as Beta) on my Synology,
>does that means you activated it again? Because the bug is still in
>there ;)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SynoCommunity/spksrc/issues/1052#issuecomment-73375906

-- 
Sent from a mobile device. please forgive errors in spellingn grammar, or punctuation.

**Comment by bladehawk** [comment]
You got my hopes up that it was back 
☺

On February 7, 2015 10:27:19 AM PST, Dr-Bean <notifications@github.com> wrote:
>Thanks for the info, it was reactivated by accident.
>As an FYI: when PR #1212 gets merged, the web interface will be
>removed. Even with the access issues removed, the interface itself is
>too buggy to leave it there.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SynoCommunity/spksrc/issues/1052#issuecomment-73376268

-- 
Sent from a mobile device. please forgive errors in spellingn grammar, or punctuation.

**Comment by Dr-Bean** [comment]
sslh 1.17-2 has been published on the repository. Note: there's no web interface. Configuration of sslh can be done via editing `/usr/local/sslh/var/sslh.cfg`
