### ISSUE TITLE
promote synocommunity on facebook

### ISSUE THREAD

**Issue by ssbarnea** [SynoCommunity/spksrc#1055]
Promote synocommunity on facebook, i created a page for synocommunity and I will take care of this part. 

Please tell we who should I add as managers for this page. 

https://www.facebook.com/synocommunity?ref=hl
##

**Comment by ssbarnea** [comment]
For twitter I think that the option is to share credentials but on facebook is much better as we can add admins.
I would be happy to add at least two admins to the facebooks page.

**Comment by Safihre** [comment]
Closing due to age. Seems this is no longer relevant.
