### ISSUE TITLE
[Syncthing] can't start service via web interface

### ISSUE THREAD

**Issue by MStrecke** [SynoCommunity/spksrc#1060]
I hope this is the correct place for this bug report.

I've installed syncthing via the cytec.us repo.
The installation went fine, however, I can't **start** the service via the package center of the synology web gui.
I can however start, stop and query the status via the command line using `/var/packages/syncthing/scripts/start-stop-status`.

Once started, I can stop syncthing via the synology web gui.
If I stop syncthing via the command line, the web gui reflects the status change.

The attempt to **start** it via the package center produces the following errror message in `/var/log/messages`:

```
PkgMan.cgi: pkgtool.cpp:2809 Failed to query package status, syncthing
```

Once startet, syncthing seems to work as expected.

System: DS 1812+, DSM 4.0

**Comment by safersurfing** [comment]
I have a NAS Synology DS715 and Syncthing 0.12.8-7 installed. My issue may relate to the above comments.

I start Syncthing (run syncthing via the package center, but it stops straight away. The only logs I have found are following.
Any idea?

2016/03/04 06:33:37	start syncthing: begin to start version 0.12.8-7
2016/03/04 06:33:37	start syncthing: start version 0.12.8-7 successfully, result 0


Mar  4 06:33:42 DiskStation php: Failed to delete keys [F3ECC2A519CA01C85D04EDA6D0C2F18694A0B88E].
Mar  4 06:33:42 DiskStation php: DeleteOtherKeyServer failed.

**Comment by safersurfing** [comment]
I managed to start it now, no problem, but cannot reach the Web UI. Any ideas?
