### ISSUE TITLE
[REQUEST] package for GitBlit

### ISSUE THREAD

**Issue by penenkel** [SynoCommunity/spksrc#1063]
In my search for a git (or hg) repository management solution, if have now found http://gitblit.com. GitBlit is a java web application (servlet). It provides a clear web interface that allows the creation, visualization and access rights management of git repositories.

The servlet can either be hosted via a existing webserver that has a servlet container (e.g. Tomcat, Jetty) or one can use the included webserver (Jetty) for a standalone solution. (as the official Tomcat package is not avalible for my DS213+, I went with the standalone version)

Under Windows I have managed to get it working without any trouble. 
On my Diskstation I have managed to start it via ssh console. Unfortunately disconnecting ssh also terminates the application :(
I have tried the following commands:
cd %gitbitfolder%
sh ./gitbit.sh
That launches the webserver but blocks the ssh console 

nohup sh ./gitblit.sh > out.log 2> err.log &
This launches the webserver and leaves the console responsive while writing the two streams into files. Unfortunately it still terminates the server with the console.

All in all I don't think it would be to difficult to make a robust package out of this (provided one is somewhat familiar with both *nix shells and Synology packages, both of which I'am decidedly not)

PS: obviously this requires java on the DS (I used the java package by MissleHugger)
##

**Comment by BenoitFreslon** [comment]
Any news?

**Comment by cytec** [comment]
@BenoitFreslon afaik nobody is working on it atm. But in general i think that running java based software on NAS devices isn't the best choice, so im out too sorry
