### ISSUE TITLE
debian-chroot 7.4-4  "can't change root"

### ISSUE THREAD

**Issue by davparker** [SynoCommunity/spksrc#1064]
I've installed the debian-chroot package on my Synology DS213j. When I try to chroot, I get an error. See following info:

DiskStation> ls  /volume1/@appstore/debian-chroot
app    env    share  var

DiskStation> ls /bin
ash            false          ls             rmdir          usleep
busybox        fgrep          mkdir          run-parts      vi
cat            get_key_value  mknod          sed            zcat
catv           getopt         more           sh             zcmp
chgrp          grep           mount          sleep          zdiff
chmod          gunzip         mv             stat           zegrep
chown          gzexe          netstat        stty           zfgrep
cp             gzip           ntfs-3g        su             zforce
date           hostname       ntfs-3g.probe  sync           zgrep
dd             ip             pidof          synodd         zless
df             ipcalc         ping           tar            zmore
dmesg          kill           ping6          touch          znew
dnsdomainname  killps         ps             true
echo           ln             pwd            umount
egrep          login          rm             uname

DiskStation> chroot /volume1/@appstore/debian-chroot /bin/ash
chroot: can't change root directory to /volume1/@appstore/debian-chroot: Operation not permitted
DiskStation>

Can someone help me with this error?

Thanks,
David

**Comment by michaelgross** [comment]
I get the same error @davparker was getting when I enter
`/var/packages/debian-chroot/scripts/start-stop-status chroot`

This happens regardless of what user I'm logging in with. 

`chroot: can't change root directory to /volume1/@appstore/debian-chroot: Operation not permitted`

**Comment by rosarch** [comment]
I had the same output.

try sudo /var/packages/debian-chroot/scripts/start-stop-status chroot

**Comment by chenchen119** [comment]
@michaelgross ssh into synology box as root (same password as admin)
