### ISSUE TITLE
sslh : change test authentication user admin to group administrators request

### ISSUE THREAD

**Issue by tuxlagaffe** [SynoCommunity/spksrc#1065]
Hello all,

As some other people I've disable admin account to security issue, so is it possible to replace in *.cgi script :
if ($user ne 'admin')
by something like this :
@requires_auth(groups=['administrators'])

Thanks in advanced for your return 

Best Regards

**Comment by Dr-Bean** [comment]
sslh 1.17-2 has been published on the repository. Note: there's no web interface. Configuration can be done via editing `/usr/local/sslh/var/sslh.cfg`
