### ISSUE TITLE
Port xbmcsalud to an SPK (XBMC headless to update mysql db)

### ISSUE THREAD

**Issue by piejanssens** [SynoCommunity/spksrc#1118]
Scanning for new movies/shows/episodes can be a pain (takes ages with large libraries, especially on small devices like the Raspberry Pi.

Third party applications such as CouchPotato, HeadPhones, SickBeard and others can notify XBMC to scan the library or even add a specific new file to the library without a full scan. This of course requires at least one XBMC instance to be (always) on.

The idea for this package is to have a small XBMC version running on DSM that updates the MySQL library. unRAID users have such a solutions under the name of 'xbmcsalud' and the source is available!
- Forum topic: http://lime-technology.com/forum/index.php?topic=27545.0
- unRAID plugin source: https://github.com/bobbintb/unRAID
- Build a headless XBMC bin for xbmcsalud: http://lime-technology.com/forum/index.php?topic=27545.msg276305#msg276305
- Generic instructions to build a headless XBMC bin: http://bootlegninja.awardspace.com/xbmc-server/

**Update**
Other post on building headless XBMC (Gotham): http://cyanlabs.net/tutorials/guide-headless-xbmc-server-for-linux
##

**Comment by chrom3** [comment]
Any progress on this?
