### ISSUE TITLE
`make arch-armadaxp` fails for python due to missing terminal_interface-curses-trace.ads

### ISSUE THREAD

**Issue by krichter722** [SynoCommunity/spksrc#1140]
after installation of prerequisites and and setup as described in REAMDE.md, I get the following errow building python with `make arch-armadaxp`:

    terminal_interface-curses-trace.adb:42:39: file "terminal_interface-curses-trace.ads" not found
    gnatmake: "/home/richter/sources/spksrc/spk/python/work-armadaxp/ncurses-5.9/Ada95/src/terminal_interface-curses-trace.adb" compilation error
    make[7]: *** [../lib/libAdaCurses.a] Fehler 4

Things I've tried so far:

  * `sudo apt-get install libncursesada2-dev` and ` cp /usr/share/ada/adainclude/ncursesada/terminal_interface-curses-trace.ads work-armadaxp/ncurses-5.9/Ada95/src/` causes 

        terminal_interface-curses-trace.ads:42:34: "Terminal_Interface.Curses.Trace (body)" depends on "Terminal_Interface.Curses.Trace (spec)"
        terminal_interface-curses-trace.ads:42:34: "Terminal_Interface.Curses.Trace (spec)" depends on "Terminal_Interface.Curses (spec)"
        gnatmake: "/home/richter/sources/spksrc/spk/python/work-armadaxp/ncurses-5.9/Ada95/src/terminal_interface-curses-trace.adb" compilation error
        make[7]: *** [../lib/libAdaCurses.a] Fehler 4`
    I didn't investigate further because I don't know anything about it...

occured with 7b3fab7660110137ee3b968254d711950ec4c78a on Ubuntu 14.04

**Comment by Dr-Bean** [comment]
Closing, see previous message.
