### ISSUE TITLE
Flexget not working (1.2.129-1)

### ISSUE THREAD

**Issue by SimyriK** [SynoCommunity/spksrc#1143]
After last update (1.2.129-1) flexget not working. In the web interface I can't get anything saved or execute: Internal sever error. Packages center's log (try execute flexget with options -h in webui): 
![2014-07-12 07-48-38 synologydiskstation-diskstation](https://cloud.githubusercontent.com/assets/3501572/3560002/44009be4-0956-11e4-855b-99daee6153c3.png)

**Comment by Dr-Bean** [comment]
I've just published a new package (20150206-3), but the web interface is still broken. Nothing we can do about that from here: it might be a while until the Flexget devs get to fixing it, if at all. I'll close this issue for now.
