### ISSUE TITLE
Transmission 2.84-7 & znc 1.4-7

### ISSUE THREAD

**Issue by michael-a** [SynoCommunity/spksrc#1148]
Hello.

I have just updated transmission and znc (2.84-7 / 1.4-7 respectively) from synocommunity repo, and I'm experiencing some difficulties :
- trackers using ssl become unreachable (could not connect to tracker)
- irc servers using ssl connections become unreachable (SSL routines:SSL3_READ_BYTES:sslv3 alert bad record mac synology)

I suppose the root cause is the same..

I have the latest version of DSM for my syno (DS 211j)

What can I do to solve this problem ?

Thanks in advance

**Comment by asmith-localphone** [comment]
Just tried to install transmission on a DS215J from the synocommunity repo but it is failing to install I think it is due to DSM6
