### ISSUE TITLE
Tvheadend-testing 3.9.952

### ISSUE THREAD

**Issue by olehumborstad** [SynoCommunity/spksrc#1149]
Hi,

This very well could just be me but tvheadend-testing just stops after a while..

Never could get the post processing working either, so I've cleared that away so it shouldn't be that causing problems.

Thought i'd check the log file, and to my discovery that was now 43GB ??

Is there some setting I have messed around with here or is this a issue with the repository?

I just emptied the content of the file because i couldn't open it because of the file size.
(cat /dev/null > tvheadend.log it sure took a while...)

Maybe this is related to the package just stopping? Where do I go about setting the max file size on the log file if so?

**Comment by PiterEL** [comment]
Hello jdierkse
How i can contact with you ?
I write email to j.dierkse@madeo.nl but nothing respond. I need your help.
