### ISSUE TITLE
Cannot upgrade/repair TTRSS

### ISSUE THREAD

**Issue by sciurius** [SynoCommunity/spksrc#1172]
Upgrade TTRSS to 1.13-6 fails with a meaningless "Error" and a repair button. View log shows no information.
Repair fails also.
NAS is DS413 with DSM 4.3-3827 Update 4.

Probably relevant message from /var/log/messages:

PkgMan.cgi: pkgtool.cpp:1845 Can't find conf folder /var/packages/tt-rss/conf

**Comment by Dr-Bean** [comment]
Fixed with https://github.com/SynoCommunity/spksrc/commit/a4dd10c21fb7eb08076a4587edba365578232ef7
