### ISSUE TITLE
[REQUEST] NCDC - an textbased DC++ Client

### ISSUE THREAD

**Issue by WebBuddha** [SynoCommunity/spksrc#1210]
I've seen that you guys created an P2P-Client for the Soulseek Network and there is also an DC++ Client called NCDC -> http://dev.yorhel.nl/ncdc which works fine.
It would be great if you are able to implement those client via the packagemanager.

Thanks in advance
WebBuddha
##

**Comment by WebBuddha** [comment]
any further updates at this time?

**Comment by Dr-Bean** [comment]
@sirjeannot I noticed your PR currently has several packages in it, not just ncdc. If you're still working on it, could you split separate packages up into separate PR's please? That makes reviewing and merging a whole lot easier.
