### ISSUE TITLE
Node.js package: npm does not work - (Synology DS212, DSM 5.0)

### ISSUE THREAD

**Issue by erikusaj** [SynoCommunity/spksrc#1223]
**Conditions:**
* Synology DS212	
* Marvell Kirkwood mv6282 1.6Ghz ARM (Marvell ARMADA 300)	
* 16-bit@DDR3, 256MB of RAM
* DSM 5.0-4493 Update 4
* *syno bootstrap* and *ipkg* installed, based on instructions on: http://www.gridshore.nl/2011/04/04/installing-node-js-on-my-new-synology/
* OpenSSL 1.0.1i-fips 6 Aug 2014
* node.js package from community channel

**Repo steps:**
1. installed *node.js* package form community channel http://packages.synocommunity.com
2. configured PATH
*note: would be easier if there were some instructions in the package itself about its install location*
3. tested if node works by running it 
4. created a new dolder and *package.json* file - with express package
5. tried running *npm install*

**Observed:**
```
npm ERR! Error: 1073880192:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:../deps/openssl/openssl/crypto/rsa/rsa_pk1.c:100:
npm ERR! 1073880192:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:../deps/openssl/openssl/crypto/rsa/rsa_eay.c:721:
npm ERR! 1073880192:error:1408D07B:SSL routines:SSL3_GET_KEY_EXCHANGE:bad signature:../deps/openssl/openssl/ssl/s3_clnt.c:1831:
npm ERR! 
npm ERR!     at SlabBuffer.use (tls.js:234:18)
npm ERR!     at CleartextStream.read [as _read] (tls.js:454:29)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:340:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:368:25)
npm ERR!     at doWrite (_stream_writable.js:225:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:215:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
npm ERR!     at write (_stream_readable.js:601:24)
npm ERR!     at flow (_stream_readable.js:610:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:642:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32.12
npm ERR! command "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install"
npm ERR! cwd /root/node
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/node/npm-debug.log
npm ERR! not ok code 0
```

*Note: by searching online I found this open issue https://github.com/npm/npm/issues/5983*

**Workaround:**
```
npm config set strict-ssl false
npm config set registry http://registry.npmjs.org/
```

**Comment by Dr-Bean** [comment]
I think we'll close this one. Node has been updated to 12.0 recently, thanks to @wind-rider, but unfortunately is no longer available for ARMv5 arches (DS212 etc). 

The arches that Node v12 doesn't support should still have an older version of Node available: 10.36 via the Synology repo, or 10.31 via the SynoCommunity repo if I'm not mistaken.
