### ISSUE TITLE
DS415+ , DS1515, DS1815 support (Avoton toolchain/x64 support)

### ISSUE THREAD

**Issue by Rido** [SynoCommunity/spksrc#1251]
I'm trying to add the SynoCommunity package source but I'm getting the error "invalid location".

If I visit http://packages.synocommunity.com/ in the browser I get "400 Bad request".

Maybe some important information: I'm using the Synology DS415+

**Comment by gwgr** [comment]
Thanks for all your work.  Just got Transmission running on my 415+.  Was wondering if Flexget was able to be compiled?  Don't see it in my community package list.  Many thanks

**Comment by Dr-Bean** [comment]
@gwgr: Thanks for the info. The Flexget package for Avoton is on the server, but not visible in the catalog for some reason. We'll look into it.

**Comment by Dr-Bean** [comment]
@gwgr, You do have the beta channel enabled, right?

**Comment by gwgr** [comment]
Ah maybe that's my problem, will look when I get home. Thx

**Comment by ThanksEveryone1234** [comment]
I just signed up here to post a thank you to everyone! I bought a 1515+ before Christmas and was quite angry to see I was unable to setup my fav apps on the box (going from 212J to 1515+)

I soon found this page, and began reading and using some of the self compiled apps. I truly appreciate the effort of everyone to get everything compiled and working again so quick. I see the syno community repo has loads of apps for avoton now.

Again, thanks!

**Comment by gwgr** [comment]
Thanks Dr-Bean, I didn't have the Beta package flag checked.  I can see Flexget now.  Just got to figure out the Python dependency

**Comment by Jaspur** [comment]
Had it to work last week. Now destroyed it by accidentally updating Python to 2.7.8-11. Now CouchPotato, Sabnzbd and Sickbeard aren't working anymore.

**Comment by kalmiya** [comment]
Works here with Python 2.7.8-11 - never installed any "modified" packages though.

**Comment by almograve** [comment]
@gwgr same here. I had to rebuild most of it. I've only been able to restore my files and settings with sickbeard...hours of work...good luck

**Comment by LithiumGrim** [comment]
Some extra info I found out. I have a DS415+ and sickbeard just stopped after the python upgrade. Did all I could find here but still it would not start... But I got it working again. My way:

1. Backup the /volume1/@appstore/sickbeard/var and other programms using Python 2.7.x (like sabnzbd)
2. Stop Sickbeard and other programms using python.
3. Remove ALL Python packages and then sickbeard (and sabnzbd if applicable)
4. Reinstall with synocommunity packages starting with python and then sickbeard/sabnzbd/ etc
5. Go to sickbeard and it will tell you it has never been updated. so UPDATE!!!!
6. Stop sickbeard in the DSM
7. Recover the backed up /var directory from sickbeard and restart sickbeard from your DSM

If you do not update sickbeard first after install and before restoring of your settings it will keep crashing at startup as the sickbeard.db is incompatible with the older packaged version.

**Comment by almograve** [comment]
Yes, I believe step 6 is key here. Starting SB once before stopping it and
then restoring/replacing files,

almograve

2015-01-08 20:03 GMT+01:00 LithiumGrim <notifications@github.com>:

> Some extra info I found out. I have a DS415+ and sickbeard just stopped
> after the python upgrade. Did all I could find here but still it would not
> start... But I got it working again. My way:
>
>    1. Backup the /volume1/@appstore/sickbeard/var and other programms
>    using Python 2.7.x (like sabnzbd)
>    2. Stop Sickbeard and other programms using python.
>    3. Remove ALL Python packages and then sickbeard (and sabnzbd if
>    applicable)
>    4. Reinstall with synocommunity packages starting with python and then
>    sickbeard/sabnzbd/ etc
>    5. Go to sickbeard and it will tell you it has never been updated. so
>    UPDATE!!!!
>    6. Stop sickbeard in the DSM
>    7. Recover the backed up /var directory from sickbeard and restart
>    sickbeard from your DSM
>
> If you do not update sickbeard first after install and before restoring of
> your settings it will keep crashing at startup as the sickbeard.db is
> incompatible with the older packaged version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SynoCommunity/spksrc/issues/1251#issuecomment-69230308>
> .
>



-- 
Cedric MARTIN
almograve@gmail.com

**Comment by adprom** [comment]
Does this mean that these packages will also work for the DS2415+ when it is released? It also uses an Intel Atom C2538

**Comment by almograve** [comment]
Yes, all these updated packages will work with this intel architecture.
Including a future 2415+

2015-01-18 13:44 GMT+01:00 adprom <notifications@github.com>:

> Does this mean that these packages will also work for the DS2415+ when it
> is released? It also uses an Intel Atom C2538
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SynoCommunity/spksrc/issues/1251#issuecomment-70406950>
> .
>



-- 
Cedric MARTIN
almograve@gmail.com

**Comment by TonioFr** [comment]
Hi all!
I have a ds415+ and cannot see HAproxy in the package list available when refreshing the synocommunity list.
Is there a manual package that should be added ?
Thanks in advance!

**Comment by piwi82** [comment]
There are no manual packages.
See issue #1452, or http://synocommunity.com/.

**Comment by Jeradin** [comment]
You can use this till for now: http://synocommunity.com/packages/haproxy/16/

**Comment by TonioFr** [comment]
Thanks a lot !

**Comment by unofr** [comment]
Hi all 
I would like to use and install ps3netserv on my DS415+
I try some tuto but can not mount anything 
Thanks

**Comment by ylacaute** [comment]
Hi,
<b>I have a DS415+ and I still can't add synoCommunity packages (08/03/2015).</b>
http://packages.synocommunity.com/  =>  bring me an 'invalid location'
(I can add other source location)

I don't see any opened issue : https://github.com/SynoCommunity/spksrc/issues?q=is%3Aopen+ds415%2B

So, I suppose the avoton arch is now fully supported but it still don't work for me. I waited a week to be sure the problem was not due to a synoCom server temporary maintenance.

Maybe I could check the logs to what is the problem but I have no idea where to find them.

Please help !

**Comment by adprom** [comment]
@ylacaute I have the DS2415+ and it works fine for me.

Does your 415+ have pen access to the internet? DNS configured properly in it so it can resolve the address?

**Comment by cyrus1977** [comment]
My ds415+ is working aswell

**Comment by ylacaute** [comment]
I didn't configured the DNS but I think the base configuration is working fine (I added cphub without any problem, I can ping synocommunity.com, name is resolved).
When I try to add http://packages.synocommunity.com, I have to wait around 10 seconds before having an invalid location, usually when you have a bad location address the error is almost immediate.

I suspect a global configuration conflict/problem. Where I can find the logs ?

Generally, I have some difficulties to find files on the NAS (with the ash) since I can't use 'locate' command, 'find' and 'grep' command don't work correclty, it's very hard to investigate by myself... If you have some tips/good sites please tell me :)
Thanks

**Comment by ylacaute** [comment]
It seems its a DNS update problem (for some reasons, my ISP DNS is not up to date), using the Google DNS 8.8.8.8 allowed me to add the synocommunity package location.
That said, I now see nothing new in the package center !! I was expected to see new application icons :'(

**Comment by ylacaute** [comment]
It seems to be a DNS update problem (for some reasons my ISP DNS is not up to date). Adding the Google DNS server allowed me to add the syno community package.
I know see community package, in the "community" section in package center :)
Be aware these community packages don't appear in package center in the view "ALL".

**Comment by Dr-Bean** [comment]
@ylacaute #1538 is an open issue, covering the issue you had with DNS. Might make sense to follow/comment there :)

**Comment by ylacaute** [comment]
Ok, thanks :)

**Comment by Ferlez** [comment]
I just wanna ask, i have a 213j atm, using it for SickRage, Transmission and Couchpotato. I kinda works, its slow as hell and crashes alot. Meaning to switch to 1515+ and add PMS. Will it run smoothly? 
I plan on seeding 50+ torrents, atm if I DL a large file (at 5MB/s) the unit crashes. Will I experience this with the 1515+? Does it have the juice? thanks

**Comment by thenriques** [comment]
It does, no problem. I have the 1815+, which is basically the same, and I get 8MBps. I've never seen a crash. 

Tiago Henriques

No dia 25/05/2015, às 20:18, Ferlez <notifications@github.com> escreveu:

**Comment by Ferlez** [comment]
What about "multitasking" dowloading torrents and streaming with plex, while copying some files something like that...

Thanks for the info

**Comment by thenriques** [comment]
Not a problem. You can always upgrade the memory another 4gb if you feel strained. 

Tiago Henriques

No dia 25/05/2015, às 22:18, Ferlez <notifications@github.com> escreveu:
