### ISSUE TITLE
Let installation routine of rutorrent create a system group rutorrent to improve torrent creation

### ISSUE THREAD

**Issue by krichter722** [SynoCommunity/spksrc#1269]
If the installation routine for rutorrent (3.6-6) would create a system group `rutorrent` which is gid of the `rutorrent` process, it would be easier to manage directories where files can be stored to be accessible for the owner and rutorrent only. This would improve security for torrent creation. Currently the directory to search for torrent files have to be world readable.

**Comment by Dr-Bean** [comment]
Group `sc-download` is enabled for rutorrent 3.7-8.
