### ISSUE TITLE
NZBget 13 - PostScript - missing scripts when trying to Choose

### ISSUE THREAD

**Issue by antakar** [SynoCommunity/spksrc#1271]
When in Extension Scripts, or under Categories, i try to choose what post scripts i want to be run, i click at Choose button.
Under there, i used to have a list of prost scripts, now, the list is empty.
I havent done anything to the config since last configuration. How can i fix it?
![bug](https://cloud.githubusercontent.com/assets/9038046/4574671/bfa9a7ac-4f9e-11e4-8b14-a1c756aeb2d3.jpg)

**Comment by antakar** [comment]
I have this problem again, not all the scripts in script directory are listed.
Please see the screenshots, the script DeleteSamples.py is not listed, but is present in the ScriptDir:
![delete_samples](https://cloud.githubusercontent.com/assets/9038046/10636498/09b3cada-77f8-11e5-9805-02d4355ec698.jpg)

![scripts list](https://cloud.githubusercontent.com/assets/9038046/10636502/14a315b8-77f8-11e5-82bd-92a8e4727946.jpg)

**Comment by Dr-Bean** [comment]
@antakar That doesn't look like our package, but more like a Qnap package. We build packages for Synology devices...
