### ISSUE TITLE
Cannot stop MantisBT

### ISSUE THREAD

**Issue by ebw44** [SynoCommunity/spksrc#1279]
On a synology running DSM 5.0-4493 Update 5, I cannot upgrade MariaDB, because I cannot stop mantisBT. I've try the DSM interface (package manager and in Control Panel/Info Center/Services) and the script
/var/packages/mantisbt/scripts/start-stop-status
But the script seems to do nothing. The other scripts in the same folder are using the installer script. Is there a way to use one of this to stop MantisBT (and start it again after MariaDB upgrade without losing any data) ?

**Comment by Dr-Bean** [comment]
@Diaoul Did you receive a response to that report you made to Synology? Thanks ;)

**Comment by Diaoul** [comment]
nope, no response to that email, I chased up.

**Comment by Dr-Bean** [comment]
Seems that upgrading is possible when `startable=no` is set (tested with DSM5.2 latest, it may already have been implemented in previous versions though, never checked). 
Stopping MariaDB is not possible. I've asked Synology to reconsider that too, but that's a different matter.
All in all, I think we can close this one.
