### ISSUE TITLE
node.js - 'npm' global flag isn't working

### ISSUE THREAD

**Issue by tjmoore** [SynoCommunity/spksrc#1285]
With the the **node.js** package installed (0.10.31-2 installed from DSM Package Center), I cannot run the **npm** command with the **-g** (global) option.

It's working fine running the **node** and **npm** commands under a local context.

e.g. I can run `npm install mypackage` and it installed it under the current directory.

However if I use the **-g** flag with *npm* to install a package globally it just hangs (e.g. `npm install mypackage -g`).

It sits where doing nothing with no sign of any package downloaded and installed. I've tried *--verbose* but nothing happens either and no verbose output at all, also tried *-d*, *-dd*, *-ddd*, which are the same as (and also tried) *--loglevel info*, *--loglevel verbose*, *--loglevel silly*

I would like to install the *forever* package to handle running node.js apps in the background basically but this must be installed globally (https://github.com/nodejitsu/forever).

This would seem to be something not configured quite right when **node.js** is installed perhaps, or an issue with the Synology or BusyBox environment ?

**Comment by Dr-Bean** [comment]
Node has been updated to 12.0 recently, thanks to @wind-rider, so for x86-based arches, it should be available on the repo.
If you want/need to, you can update to that version, and report back if the issue persists (please open a new issue for that). Otherwise, I think there's a workaround...;)
