### ISSUE TITLE
Mise à disposition d'un nouveau package MyReadings

### ISSUE THREAD

**Issue by hugoheitz** [SynoCommunity/spksrc#1293]
Bonjour,

SBDomo a mis à disposition une interface MyReadings pour présenter le contenu présent dans une bibliothèque calibre hébergée par exemple sur un NAS Synology.
Ceci permet d'avoir une expérience utilisateur sympa avec une tablette type ipad ou samsung.
C'est donc une amélioration de COPS sur laquelle l'interface est basée.
Ca fonctionne bien sur NAS Synology.

Avec un ami, j'ai créé un 1er jet du package MyReadings pour Synology #

Il a été testé dans un XPenology / Virtualbox.

Pour construire ce package : 
reprise du package de COPS dans spksrc et j'ai juste changé ce qu'il fallait pour que ca pointe vers la bonne URL, le bon format (.zip) etc..etc..

Comment vous envoyer le package pour l'améliorer éventuellement et le publier sur synocommunity ?
version 0.4.3 et pas la version GIT car la 0.4.3 est compilée et donc plus rapide.

Comme c'est basé sur le package de COPS, il demande le repository Calibre juste apres l'install
En principe, ca sert pas, mais dans le doute, rentre la bonne valeur, ca coute pas plus cher.
Ensuite, il suffit de cliquer sur le lien, et la.... t'as rien, puisqu'il faut configurer :
http://@ip-de-mon-na...dings/admin.php

Se créer un compte d'admin et rajouter le repository Calibre dans la conf MyReadings.

cordialement,
Hugoheitz

**Comment by Dr-Bean** [comment]
If you don't mind, I'll respond in English, as my French is abysmal.
@phil0u has been working on a PR for MyReadings over here: #1362, and we might as well use #1429 to keep track of people interested in the completed package.
So I'll close this issue, but thanks for the suggestion and the work you've put into it :)
