### ISSUE TITLE
new OScam release available?

### ISSUE THREAD

**Issue by rako123** [SynoCommunity/spksrc#1300]
Hello,

I use OScam on the synology from source http://dslub.synology.me/spkrepo/index.php/spkrepo/packages

Version on the feed is 1.2 r9785. 
Will there be a newer version soon?

Best regards for your support, rako123
##

**Comment by pazante** [comment]
Hello!
Did anybody find another way or some way to get oscam working 
I am looking to get it working on my ds415+
If somebody could make a real newbie guide howto compile and make oscam into an spk maybe i can make it by myself or maybe it´s not that easy

**Comment by nmsaraujo** [comment]
Can someone help?
