### ISSUE TITLE
rutorrent 3.6-6 don't work in my naps

### ISSUE THREAD

**Issue by macbookalu** [SynoCommunity/spksrc#1303]
Hello, i have a ds214se. i installed rutorrent from synocomunity's repo, the app installs ok but when i run it, the app stops a few seconds later.

I followed the steps explained here: http://www.youritromp.nl/2014/06/rtorrent-seedbox-on-a-synology-nas, and edit the rtorrent.rc file but the apps can't work.

The web interface (rutorrent) works perfectly but says that can't connect with rtorrent.

Can anyone help me?

thanks a lot

**Comment by uryupinsk** [comment]
Hello, I'm on a DS213 and I've got the exact same problem.

Please help.

**Comment by Dr-Bean** [comment]
Closing. This issue is quite old, and a new package has been released. Please open a new issue if the problem still exists.
