### ISSUE TITLE
Debian Chroot - Menu icon missing in DSM 5.1

### ISSUE THREAD

**Issue by xdanik** [SynoCommunity/spksrc#1323]
Hi,

After recent update to DSM 5.1 (DS213j - DSM 5.1-5004) the red "Debian Chroot" icon in main menu disappeared.
Chroot is still working fine (I am able to SSH to it, and Apache is running).
In Packages Center is Debian Chroot marked as started.

Does anyone know where can be problem?

Thanks

**Comment by bolzerrr** [comment]
Thanks for the hint i run into the same issue. Is it maybe possible to add an exception to apparmor?

**Comment by Dr-Bean** [comment]
This issue seems to have disappeared, at least for me. I still have an icon for Debian-Chroot while AppArmor is running, on DSM5.2. @xdanik, @bolzerrr can you confirm this?
