### ISSUE TITLE
[REQUEST] mono package

### ISSUE THREAD

**Issue by akafester** [SynoCommunity/spksrc#1343]
Is it possible to get the newest mono version (3.10) on the synocommunity repo?

**Comment by Dr-Bean** [comment]
Mono v3.10.0-2 has just been published on the repository.

**Comment by Diaoul** [comment]
@Dr-Bean: can you compile mono properly? I have errors: 

```
tar -cpf - -C /spksrc/spk/mono/work-x64-5.1/../../../native/mono/work-native/install/usr/local/lib . | tar -xpkf - -C /spksrc/spk/mono/work-x64-5.1/staging/lib
tar: ./libmonoboehm-2.0.a: Cannot open: File exists
```

Same error for all archs... (building on docker)

**Comment by Dr-Bean** [comment]
@Diaoul I'll clean and rerun. You were using the current Mono 3.10 code, right?

**Comment by Diaoul** [comment]
Yes

**Comment by Dr-Bean** [comment]
88f6281 completed successfully (all-archs-latest is running, I'll check on it later). Would the docker setup on your end be causing it somehow?

**Comment by Diaoul** [comment]
I've compiled a HAProxy and Python without issue and I published them, no issue reported so far so I think it works fine. Maybe there is something special about mono's configure that triggers on my environment.
Can you test compiling it on docker? I'll publish some instructions on the readme in a short while.

**Comment by Dr-Bean** [comment]
Sure, I'll test the instructions you've got, see how it works. It might take a bit, I've just run out of disk space again. In the meantime, the remaining arches compiled successfully.

Btw, that empty PR queue looks great...maybe do the same with the open issues? :P

**Comment by Diaoul** [comment]
Well, if I can blame GitHub for it that's OK for me :)

**Comment by Dr-Bean** [comment]
@Diaoul Yep ;) Had a response from Github yet?

On the Docker stuff: I set up a new spksrc VM (Jessie 64b) with Docker on top. First off, I cannot get `native/mono` built with Docker, somewhere along the way it quits with a large number of errors. I can build it directly on Jessie, as you'd usually do.
After that, building `spk/mono` fails with the same set of errors as you have: the files already exist, and that's actually true. Strange, because the dir should just have been made, so I'd think those would be empty. I've just started building it directly, maybe see if the dirs start off empty or not.

**Comment by Dr-Bean** [comment]
Must've scrolled past this at least a couple times...The lines in https://github.com/SynoCommunity/spksrc/blob/master/spk/mono/Makefile#L45-L50 are being duplicated in both `cross/mono/Makefile` and `spk/mono/Makefile`, but seems to me that's unnecessary: only the cross package would need to contain those lines. @maxrogers, does that make sense?

**Comment by Diaoul** [comment]
Nice catch, I didn't check yet because you were unable to reproduce the
issue.

**Comment by Dr-Bean** [comment]
Weird though. I believe I built/published the current packages on the repo...no issues with it. I'm sure maxrogers did the exact same thing on his side.

**Comment by maxrogers** [comment]
@Dr-Bean, I removed duplicate lines in ``spk/mono/Makefile`` Thank you!

Yes, I didn't have any errors creating the packages with spksrc. Here is the pull request:
https://github.com/SynoCommunity/spksrc/pull/1605

Does removing the duplicated lines solve the errors @Diaoul?

**Comment by Dr-Bean** [comment]
The error is gone, so that's good. For some reason, Docker doesn't want to produce a working package though, so I'm currently retesting by building the package directly.
