### ISSUE TITLE
[haproxy] Help and howto link in package center is not live

### ISSUE THREAD

**Issue by piejanssens** [SynoCommunity/spksrc#1344]
I was glad to see a "help and howto" link for this package because I want to setup reverse proxy using this tool, but the link is not active: https://synocommunity.com/help/haproxy

**Comment by wind-rider** [comment]
the help is now at http://htmlpreview.github.io/?https://github.com/SynoCommunity/spksrc/blob/master/spk/haproxy/src/app/help/enu/index.html

**Comment by wind-rider** [comment]
@Diaoul why was this one closed? the original question (why does the help link not work) was not resolved

**Comment by Dr-Bean** [comment]
#1037, or any of the other issues pertaining to the help not working. The html preview link was just an example, you could just as well read the raw file.
