### ISSUE TITLE
ejabberd admin password can't contain special characters

### ISSUE THREAD

**Issue by sebastiendamaye** [SynoCommunity/spksrc#1348]
Hi,
It seems that the admin password defined during the installation of ejabberd (screen asking login, password and domain) can't contain special characters. The installation won't fail but you then won't be able to authenticate against the admin interface (http://yourdomain.tld:5280/admin).

**Comment by Dr-Bean** [comment]
This is an `ejabberdctl` limitation, from what I can tell. I think the only thing we can do is add the restriction to the wizard's description.

**Comment by stevenwalton** [comment]
Would you kindly do that, as well as add that you need to have admin@domain to login. It took me a while to figure out why I could not login, both because of my use of special characters and domain. It'd be nice to know the limitations when installing.

**Comment by Dr-Bean** [comment]
To be fair, your second point is documented, whereas the first is not. See http://docs.ejabberd.im/admin/guide/installation/#post-install-operations.
Setting `HELPURL = http://docs.ejabberd.im/admin/guide` should cover that, imo.

**Comment by Dr-Bean** [comment]
Although...might as well do both ;)

**Comment by stevenwalton** [comment]
Might as well. Would save the hunting that users have to do. I'm still hunting how to do my ssl certificate correctly and everything seems to be right... server fine, just can't connect with my client.

**Comment by Dr-Bean** [comment]
Done with https://github.com/SynoCommunity/spksrc/commit/6dbbd9259c767aace1a14bb4f4a1cc7ad74212c3. Not releasing a new package atm, as I'm doing some research to get ejabberd updated to a maintained version...but that might take a while.
