### ISSUE TITLE
NAS DS-213+, qoriq arch

### ISSUE THREAD

**Issue by NightFalcon650** [SynoCommunity/spksrc#1353]
Ubuntu 14.10 and spksrc installed
NAS: DS-213+
Arch: Qoriq

I'm trying to cross compile node.js for my nas but i get the message that it's not supported.

Why isn't my nas supported?
And when would it be supported or could someone make a work around so it's possible to install on my nas???

Hereś the readout:

markv@AcerLinux-PC:~$ git clone http://github.com/SynoCommunity/spksrc.git
Cloning into 'spksrc'...
remote: Counting objects: 15750, done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 15750 (delta 42), reused 123 (delta 39)
Receiving objects: 100% (15750/15750), 5.76 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (8269/8269), done.
Checking connectivity... done.
markv@AcerLinux-PC:~$ cd spksrc/
markv@AcerLinux-PC:~/spksrc$ make setup
Creating local configuration "local.mk"...
Setting default toolchain version to DSM-4.3
markv@AcerLinux-PC:~/spksrc$ cd spk/node
markv@AcerLinux-PC:~/spksrc/spk/node$ make arch-qoriq-5.0
===> Building package for arch qoriq-5.0
make[1]: Map '/home/markv/spksrc/spk/node' wordt binnengegaan
===> Set up toolchain 
===> Downloading files for syno-qoriq
wget http://sourceforge.net/projects/dsgpl/files/DSM%205.0%20Tool%20Chains/PowerPC%20QorIQ%20Linux%202.6.32/gcc4374_eglibc2874_qoriq-GPL.tgz
2014-11-23 18:20:11 URL:http://netcologne.dl.sourceforge.net/project/dsgpl/DSM%205.0%20Tool%20Chains/PowerPC%20QorIQ%20Linux%202.6.32/gcc4374_eglibc2874_qoriq-GPL.tgz [187703061/187703061] -> "gcc4374_eglibc2874_qoriq-GPL.tgz.part" [1]
===> Verifying files for syno-qoriq
===> Checking sha1sum of file gcc4374_eglibc2874_qoriq-GPL.tgz
===> Checking sha256sum of file gcc4374_eglibc2874_qoriq-GPL.tgz
===> Checking md5sum of file gcc4374_eglibc2874_qoriq-GPL.tgz
/home/markv/spksrc/toolchains/syno-qoriq-5.0/../../distrib/gcc4374_eglibc2874_qoriq-GPL.tgz
===> Extracting for syno-qoriq
tar -xzpf /home/markv/spksrc/toolchains/syno-qoriq-5.0/../../distrib/gcc4374_eglibc2874_qoriq-GPL.tgz -C /home/markv/spksrc/toolchains/syno-qoriq-5.0/work 
===> Patching for syno-qoriq
===> Fixing libtool files for syno-qoriq
===> Processing dependencies of node
make[2]: Map '/home/markv/spksrc/cross/node' wordt binnengegaan
Makefile:19: **\* qoriq is not a supported architecture. Gestopt.
make[2]: Map '/home/markv/spksrc/cross/node' wordt verlaten
../../mk/spksrc.depend.mk:44: recept voor doel 'depend_target' is mislukt
make[1]: **\* [depend_target] Fout 2
make[1]: Map '/home/markv/spksrc/spk/node' wordt verlaten
../../mk/spksrc.spk.mk:333: recept voor doel 'arch-qoriq-5.0' is mislukt
make: [arch-qoriq-5.0] Fout 2 (genegeerd)
markv@AcerLinux-PC:~/spksrc/spk/node$

**Comment by buttonsrtoys** [comment]
This is an old thread, but I'm trying to install Node.js on my qoriq DS413 and desperately need advice. I had thought it was just going to be a bit of work, but after reading this thread -- is it not possible to compiled Node.js on a qoriq device? The route I was taking was trying to install gcc 4.8 or later (which nodejs requires) and then doing a native complie of Node.js. Am I wasting my time? E.g., I'm currently stuck on getting gcc 4.8 installed. (ipkg will only install 3.4.6).

**Comment by knut-forkalsrud** [comment]
If you refer to the V8 issue I referred to above you'll find that "there are 117 locations in the code that need to be changed to make this work (if we disable crankshaft)". This is to work around missing instructions in the CPU.
