### ISSUE TITLE
SynoCommunity not available for DS215J?

### ISSUE THREAD

**Issue by ferdyz** [SynoCommunity/spksrc#1374]
Hi all, 

Yesterday I have bought a DS215J. I didn't thought it through that the package from SynoCommunity was not available due to the new processor of the DS215J. Is there a timeline when the release of the package will be? Days/weeks/months? It would be great to use this package on my NAS. 

Thanks in advance,

**Comment by Dr-Bean** [comment]
You're welcome. I guess it's time to close this issue too :)
