### ISSUE TITLE
SABNZBD is reporting an update to 0.7.20

### ISSUE THREAD

**Issue by phybersplice** [SynoCommunity/spksrc#1376]
Hi;

SABNZBD is reporting an update is available to 0.7.20.
Will a new version be incoporated into Synocommunity's .spk installer?

**Comment by tomnewton** [comment]
I don't see it in my Package Center. DS415play on latest DSM software.

**Comment by Dr-Bean** [comment]
@tomnewton Should be there. Refresh Package Center?

**Comment by tomnewton** [comment]
Got is sorted. Thank you! Uninstalled and reinstalled.
