### ISSUE TITLE
[Request] Monit: Easy proactive monitoring

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#1392]
I was wondering if we could package this for our NAS systems?

I know it's possible to cross compile it but not sure if it will run on every system or what dependencies it needs.

Monit is a small Open Source utility for managing and monitoring Unix systems. Monit conducts automatic maintenance and repair and can execute meaningful causal actions in error situations.

http://mmonit.com/monit/

**Comment by cytec** [comment]
@elRadix update looks pretty good :) i hope i can have a look on that later today.
about your push notifications like stated here: http://mmonit.com/wiki/MMonit/PushoverNotification (bottom of the page) you should do an extra `.sh` file with those arguments and call it

**Comment by cytec** [comment]
@elRadix just updated monit spk to 5.11 :)

**Comment by elRadix** [comment]
great, thank you !!!

@cytec  - regarding the push notifications, thats for pushover, I am look for pushBullet solution - https://www.pushbullet.com/

Pushover is not free vs Pushbullet which totally free ;-)

**Comment by cytec** [comment]
yeah but that makes no difference... put it in a `.sh` file and call that file ... monit cant handle curl commands directly...

**Comment by elRadix** [comment]
tried it with the following but it does send the variables monit host/service populated, just received this as a notification: $MONIT_HOST $MONIT_SERVICE - $MONIT_DESCRIPTION - instead the real data

This is the script:

```curl -u <your_access_token_here>: -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type: application/json' --data-binary '{"type": "note", "title": "$MONIT_HOST", "body": "$MONIT_SERVICE - $MONIT_DESCRIPTION"}'```

I am calling the script is as follows - push.sh
```
  check host MyNaS  with address localhost
     if failed port 80 protocol http then exec /volume1/scripts/push.sh
```

**Comment by cytec** [comment]
@Dr-Bean Still thinking about adding some basic configuration files for some "much used" services... also i didn't have the time to check if there are any problems if there are services added which are not installed/available

anyone tested this yet?
also what would be some default services one would like to have installed?

i was thinking about: SickBeard, Couchpotato, (maybe Custom too?) NZBget, Sabnzb, Transmission... 
and think basic checks/actions like check pid and ping port / restart if down... if someone wants some more advanced stuff (like memory checking etc) he could easily change the default files.

also i was thinking about adding some kind of "expand basics" file like @elRadix did here https://github.com/SynoCommunity/spksrc/issues/1392#issuecomment-67330845 cause if you change the main config it will be overwritten on each update...

@Dr-Bean, @Diaoul Any thoughts on that?

**Comment by carlomazza** [comment]
@elRadix The solution to the environment variables is here
http://superuser.com/questions/835587/how-to-include-environment-variable-in-bash-line-curl
In short write " ' " (double quote single quote double quote) to expand the variables correctly. It works for me.

**Comment by cytec** [comment]
closing this as monit is available for a while now

**Comment by Dr-Bean** [comment]
Monit 5.13-7 has been published on the repo. @cytec Assuming no issues pop up with this (and I don't expect any), I think the beta tag can be removed with the next release.

**Comment by cytec** [comment]
Yeah! :) still running fine for me... didn't even notice i still had it running  :D
