### ISSUE TITLE
Additional install step in synocommunity.com for trust level

### ISSUE THREAD

**Issue by grseko** [SynoCommunity/spksrc#1396]
I just set up my first Synology box, DS214play and got interested in third party packages. I set up the source for new packages, and they are displayed in the Community tab. I can download all of them properly, I'll get the popup with information about the package I am about to install, click "Apply" and... It ALWAYS says "Failed to install X." (X of course being the package name) on every one of them. However, installing any official packages works flawlessly.

Details about the box:
DS214play, DSM 5.1-5021

**Comment by Dr-Bean** [comment]
I was about to close it when I noticed that the Python3 Evansport package indeed wasn't signed yet (just did). 
@Diaoul Is that still an open action?

**Comment by Dr-Bean** [comment]
Closing. Trust level description is added on the site, so that's solved. As for missing signatures, there will be packages without a signature, and we'll fix those along the way when they are reported.
