### ISSUE TITLE
Darkstat not available, is this package still archived somewhere?

### ISSUE THREAD

**Issue by ghost** [SynoCommunity/spksrc#1403]
The Darkstat package was declared "unmaintained" and removed from the git library and the package repository in 2013.

I thought i had kept a copy of this package, but I didn't, or have lost it. Is the SPK file still available somewhere? Specifically, the version for the Marvel Kirkwood mv628x units, such as DS111, DS211, DS213, etc.

Edited because my title didn't reflect my question.

**Comment by Dr-Bean** [comment]
An up-to-date version of DarkStat has just been (re)published on the SynoCommunity repository.
