### ISSUE TITLE
[Request] TestDisk 

### ISSUE THREAD

**Issue by cytec** [SynoCommunity/spksrc#1407]
seems like there is already a compiled binary for ds 211:
http://www.cgsecurity.org/wiki/TestDisk_Download

**Comment by BenjV** [comment]
Would be great to have such software available for all architectures.

**Comment by cytec** [comment]
so today i was able to access my build box for a few tests and it seems to build on most (if not all arches) testing on my DS 1513+ (cedarview) went well and i'm uploading some test spks to my repo now.

**Comment by Dr-Bean** [comment]
TestDisk has just been published on the SynoCommunity repository. Thanks @cytec :)
