### ISSUE TITLE
ruTorrent DS214play

### ISSUE THREAD

**Issue by orishi** [SynoCommunity/spksrc#1411]
Hello,

I'm trying to install rtorrent+rutorrent on 214play. However, after enabling webserver, downloading the package, choosing download directory, the installation goes without any errors but the service won't start. In Log there is nothing there.

Screenshot: http://i.imgur.com/TU8avpH.png

Any ideas what am I doing wrong? Or is this package even compatible with my Synology? Thanks.

**Comment by uryupinsk** [comment]
Hello, I'm on a DS213 and I've got the exact same problem on ruTorrent 3.6-6.

Please help.

**Comment by Dr-Bean** [comment]
Closing. This issue is quite old, and a new package has been released. Please open a new issue if the problem still exists.
