### ISSUE TITLE
ruTorrent v3.6 (svn $Rev: 2404 $) - settings

### ISSUE THREAD

**Issue by wedge15151** [SynoCommunity/spksrc#1412]
Running ruTorrent v3.6 (svn $Rev: 2404 $) on a synology DS-1812+ and it seems that it loses the settings such as upload / download caps and ports when you manually set them. Not sure if there's another way I should be setting these other than with the webgui settings options
##

**Comment by sunbiker** [comment]
i have the same, can´t save the settings and i can´t select a folder where i want to donwload.
Https rss feed don´t work too.

**Comment by sachse** [comment]
Has anyone figured this one out yet?

**Comment by Oleekae** [comment]
what code need to write on **rtorrent.rc** to save the upload / download stafs?  My stats is lost every time I restart the rtorrent service, how can I fix this? TIA folks
