### ISSUE TITLE
midnight commander and DS414

### ISSUE THREAD

**Issue by fridgeraster** [SynoCommunity/spksrc#1419]
Hi there

I've found problem installing midnight commander on my DS414.
It starts with download, then displays setting confirmation window.
If I click 'Apply' button, it comes back with message: Failed to install "Midnight Commander".
I would be gratefull for any help.

Regards
Fridge

**Comment by Dr-Bean** [comment]
I've signed the packages. Could you retry please?

**Comment by darylo** [comment]
Hi, 
I am having the same is issue with an install attempt today. 
I trying to install::

Midnight Commander 4.8.10-2 from Synocommunity.

I have a DS412+ and I am running DSM 5.1-5021 update 2

There is no indication given other than a dialogue box stating "Failed to install Midnight Commander". 

I have not previously installed the applicaiton.
