### ISSUE TITLE
midnight commander - segfault on moving large files or many directorys

### ISSUE THREAD

**Issue by hirnwunde** [SynoCommunity/spksrc#1420]
i plugged in a USB-Disk to move many files/directorys to my DS214se and sometimes i get a segfault when i move a large bunch of it.

when i move directory by directory or only copy (a bunch of it) it works.
##

**Comment by Diaoul** [comment]
That's weird. I suggest you report this to midnight commander as this seems to be an issue upstream. I think.

**Comment by hirnwunde** [comment]
how can I investigate this behavior in more detail to give this information to the mc developer(s)?

**Comment by Diaoul** [comment]
It would require to have a debugger available and mc compiled with debug symbols I guess. We don't have a gdb package but for mc with debug symbol you could recompile mc without stripping rule and that should do it.

For now just ask mc developer(s) and provide reproduce steps. Maybe that's a know issue or limitation.
