### ISSUE TITLE
Trying to install Python ds214play

### ISSUE THREAD

**Issue by DrPips** [SynoCommunity/spksrc#1425]
Hi All,

Just had my new 214play delivered and I'm trying to install Python.  I have added the SynoCommunity as a source of packages, but when I try to install Python I get the message "failed to install 'Python'.  This package is not published by Synology Inc,  

Any ideas on what I'm doing wrong?

Thanks

**Comment by Dr-Bean** [comment]
Package Center settings > Set trust level to the second option. It's currently set to the first option, and that limits you to installing only Synology packages.

**Comment by DrPips** [comment]
Legend! Thanks so much for the swift response!  As you replied so quickly and obviously know you're stuff, maybe you could help me with another problem I'm having.

I'm migrating everything from my old WD MybookLive (adding remote folder in file station) but I'm only getting 3.5MB/s speeds.  Anything I can do to speed it up?

Thanks again,

**Comment by Dr-Bean** [comment]
Well, communication speed depends on a lot of things: the connection between the two (wired vs wireless, 10/100/1000mbps?), the protocol used to communicate (SMB, NFS, other), and whether or not you're maxing out the performance of either device (with regards to CPU etc). It's possible that this is the best you can get.
If you're not familiar with how to investigate the above suggestions, I'd say leave it be for now, and start experimenting with it later :)
