### ISSUE TITLE
Consider making the rTorrent screen session shared

### ISSUE THREAD

**Issue by denkristoffer** [SynoCommunity/spksrc#1431]
I would like to be able to access the screen session with rTorrent, which I sometimes prefer to the web UI of ruTorrent. I can think of two ways to do this, one is obviously to make the screen session shared. The other is to give terminal access to the rutorrent user, log in as root, `su` to rutorrent and then access the session. I think the first way is preferable.

As far as I know all it takes is something like `-S rtorrent` in [dsm-control.sh](https://github.com/SynoCommunity/spksrc/blob/1b0b17b3ede434ea28a7f3a11a9a05b8d1c593a1/spk/rutorrent/src/dsm-control.sh#L18)
##

**Comment by Diaoul** [comment]
Have you tested this solution?

**Comment by sachse** [comment]
Seems it's not as simple as I thought it was if you want to share between different user accounts:
The `/usr/local/rutorrent/bin/screen` binary needs `suid` root and you then have to add `multiuser on` and `acladd user2,user3` to .screenrc. It seems you can't share with a user group but have to add the usernames like that.
