### ISSUE TITLE
Setting up SABnzbd on DS214play

### ISSUE THREAD

**Issue by DrPips** [SynoCommunity/spksrc#1432]
Hi All,

I'm trying to set up SAB on my new ds214play.  What I'd like to be able to do is add nzbs to be downloaded from nzb.su  I already have an account and everything that I've been using for a while.  At present, if I download an nzb it will automate to the localhost version of SAB on my laptop.  Is there anyway of making it automatically download with the NAS version of SAB?

Thanks

**Comment by Dr-Bean** [comment]
The SABnzbd manual or the SABnzbd forums are better places for questions like this.
Two methods off of the top of my head: use a blackhole or watchfolder to put nzb files in after downloading them, or look for a plugin for your browser to push the nzb directly to SAB.
