### ISSUE TITLE
[Request] Recoll, cross-compile

### ISSUE THREAD

**Issue by dsheyp** [SynoCommunity/spksrc#1433]
Hi,
I'm trying to cross-compile 'recoll', a cool linux search tool, which has also a web-ui.
I managed to compile xapian, a prerequisite of recoll. However now i'm stuck with some compile errors in recoll. Maybe someone knows what to do with this:

/home/jpp/src/spksrc/toolchains/syno-cedarview-5.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-g++  -I/home/jpp/src/spksrc/cross/recoll/work-cedarview-5.1/install//usr/local/include  -I. -I../aspell -I../bincimapmime -I../common -I../index -I../internfile -I../rcldb -I../unac -I../utils  -Wall -Wno-unused -I/usr/local/lib/../include   -DRECOLL_DATADIR=\"/usr/local/share/recoll\" -fPIC -DPIC -DHAVE_CONFIG_H -D_GNU_SOURCE  -c ../utils/pathut.cpp
../utils/pathut.cpp: In function ‘bool fsocc(const string&, int*, long int*)’:
../utils/pathut.cpp:70:19: error: aggregate ‘fsocc(const string&, int*, long int*)::statfs buf’ has incomplete type and cannot be defined
../utils/pathut.cpp:71:34: error: invalid use of incomplete type ‘struct fsocc(const string&, int*, long int*)::statfs’
../utils/pathut.cpp:70:12: error: forward declaration of ‘struct fsocc(const string&, int*, long int*)::statfs’
make[3]: *** [pathut.o] Fehler 1
make[3]: Leaving directory `/home/jpp/src/spksrc/cross/recoll/work-cedarview-5.1/recoll-1.20.1/lib'
make[2]: *** [all] Fehler 2
make[2]: Leaving directory `/home/jpp/src/spksrc/cross/recoll/work-cedarview-5.1/recoll-1.20.1'
make[1]: *** [compile_target] Fehler 2
make[1]: Leaving directory `/home/jpp/src/spksrc/cross/recoll'
make: [arch-cedarview-5.1] Fehler 2 (ignoriert)

From the author of recoll i found this as an answer to a similar problem:
https://bitbucket.org/medoc/recoll/issue/216/building-recoll-gets-stuck-during#comment-13765357

The file where the error occurs on line 70 can be viewed here:
https://fossies.org/linux/recoll/utils/pathut.cpp

I don't know how to proceed, to resolve the problem with spksrc.
Here is what i did so far:
- I added CONFIGURE_ARGS = --includedir=/usr/include, but it did not change anything.
- for another compile-error (g++ didn't find -lxapian and -lz) i added the line ADDITIONAL_CFLAGS = LD_LIBRARY_PATH. It fixed the compile error, but i don't know if it is the correct way to do it.

-------------------------------------------------------------------------------------------------------------

PKG_NAME = recoll
PKG_VERS = 1.20.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.lesbonscomptes.com/recoll
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/zlib cross/xapian cross/python

HOMEPAGE = http://www.lesbonscomptes.com/recoll/
COMMENT  = A full-text search tool.
LICENSE  =

GNU_CONFIGURE = 1
CONFIGURE_ARGS = --includedir=/usr/include --disable-qtgui --disable-x11mon
ADDITIONAL_CFLAGS = LD_LIBRARY_PATH= ${LD_LIBRARY_PATH}:/home/jpp/src/spksrc/cross/xapian/work-cedarview-5.1/install/usr/local/lib

#CONFIGURE_TARGET = nope
#INSTALL_TARGET = nope
#PRE_INSTALL_TARGET = nope

#TEST:
#       @echo $(PKG_DIST_NAME)

include ../../mk/spksrc.cross-cc.mk
-------------------------------------------------------------------------------------------------------------

Thanks for any suggestion.

**Comment by dsheyp** [comment]
Hi

I'm still working on building recoll. it compiles now if python module creation is disabled. What i did so far is on github:
https://github.com/dsheyp/spksrc

 My question ist:

how does a "python setup.py build" need to be called in the spksrc crosscompile environment?

the setup.py can be found here:
https://fossies.org/linux/recoll/python/recoll/setup.py.in

Thanks for any help.

**Comment by Dr-Bean** [comment]
@dsheyp I think you already noticed the answer to the setup.py build question: use `WHEELS` in the spk/Makefile to build a Python module. If cross-compiling is needed for the module, create a cross package for that module, and add a `BUILD_DEPENDS` in the spk/Makefile, see over [here](https://github.com/SynoCommunity/spksrc/blob/develop/spk/syncserver/Makefile#L7).
However, if it's a compile-time dependency, that probably won't work with cross-compiling...you might end up having to patch setup.py.
