### ISSUE TITLE
Couldn't install mylar

### ISSUE THREAD

**Issue by Brontoloo** [SynoCommunity/spksrc#1434]
Today I tried to install mylar on my ds215j(running DSM 5.1 update2), but I'm getting the error "Impossible to install Mylar"(or something similar, I'm not using dsm in english).
I've already installed the python(not python3) package from synocommunity.

This is my first nas, so I don't know where to get logs. If you need other infos just let me know.

**Comment by richard77** [comment]
I have the same issue installing Debian Chroot on ds212j (running latest DSM 5.1)
Download is succesful, but installation fails with the message 'cannot install Debian Chroot'. The actual english message might be different as I'm not using the english version as well. Hope someone knows how to solve this.

**Comment by Dr-Bean** [comment]
Thanks for reporting. I just signed the mylar and debian-chroot packages, which should solve this issue That means that you can put the trust level back to the second option to install these packages.

Fyi, not all packages have been signed yet, that will happen automatically with the next update of spkrepo/packages are reuploaded.
