### ISSUE TITLE
Synology Crontab How to 

### ISSUE THREAD

**Issue by RustyPixel** [SynoCommunity/spksrc#1435]
Not an issue just a simple how to use you can use the crontab in etc/
In you start_stop_staus file you add
1. path to the .sh file

```
CRONJOB_1="/usr/local/yourpackge/sbin_or_bin/your_script.sh"
```
1. This line to install the crontab setting to your script file

```
# crontab setup
SetCrontab()
{
    # CRONJOB_1 
    if ! grep -q "${CRONJOB_1}" "/etc/crontab"; then
        cat "/etc/crontab" > "/etc/crontab.$$"
        echo "* *   *   *   *   root    ${CRONJOB_1}" >> "/etc/crontab.$$"
        mv "/etc/crontab.$$" "/etc/crontab"
        /bin/kill -HUP `/bin/cat "/var/run/crond.pid"`
    fi
}
```
1. This line to install the crontab setting to your script file

```
# remove the crontab settings. 
UnSetCrontab()
{
    # CRONJOB_1
    if grep -q "${CRONJOB_1}" "/etc/crontab"; then
        grep -v "${CRONJOB_1}" "/etc/crontab" > "/etc/crontab.$$"
        mv "/etc/crontab.$$" "/etc/crontab"
        /bin/kill -HUP `/bin/cat "/var/run/crond.pid"`
    fi
}
```
1. Under the section for `start_daemon ()` just add `SetCrontab` at the end.
2. Under the section for `stop_daemon ()` just add `UnSetCrontab` at the end

You can adjust the the \* in  
`echo "*  *   *   *   *   root    ${CRONJOB_1}" >> "/etc/crontab.$$"`

remember there must tab spacing between " and ". In you .sh file there is no need to put sleep=? as crontab take care of it.

Crontab syntax :

```
*     *     *   *    *        command to be executed
-     -     -   -    -
|     |     |   |    |
|     |     |   |    +----- day of week (0 - 6) (Sunday=0)
|     |     |   +------- month (1 - 12)
|     |     +--------- day of        month (1 - 31)
|     +----------- hour (0 - 23)
+------------- min (0 - 59)
```
##

**Comment by Diaoul** [comment]
Too bad there's no crontab.d directory, that would've made editing safer.

Thanks for sharing :) Maybe you can create a wiki page with this?
