### ISSUE TITLE
Cannot start Midnight Commander

### ISSUE THREAD

**Issue by sushi171** [SynoCommunity/spksrc#1436]
I just installed Midnight Commander on a DS110j (DSM version 5.1-5021).
The installation runs smooth but when I try to run the package it says "Status: Stopped" and in the pulldown menu above I only get the option to uninstall the package again.

Trust level has been set to allow installation by any publisher.

![screen](https://cloud.githubusercontent.com/assets/10419691/5629429/44632e56-95ee-11e4-9c31-1e916b710137.png)

**Comment by G1zm0** [comment]
This package doesn't need to run. It is more some sort of library you're using.
It will work if you type "mc" from the terminal

**Comment by RustyPixel** [comment]
The problem is with the start_stop_status which doesn't send back a status to the package center, i have said about it before #1114 that these lines where at fault and where missing 

```
PACKAGE_DIR="/var/packages/${PACKAGE}"
FILE_ENABLE="${PACKAGE_DIR}/enabled"
```
and 
```
    status)
	 if [ -f "${FILE_ENABLE}" ]; then
		exit 0
	 fi
		exit 1
	 ;;
```

and was give a negative response even thou i got the idea from the official mailstation package at lines 5,6 87-89, 98-100 and 109 to 114 in there start-stop-status

**Comment by Diaoul** [comment]
@RustyPixel: This trick was necessary for old versions of DSM that does not support the STARTABLE flag in INFO file.

@G1zm0 is right, package doesn't actually "run" it makes available mc in command line.

**Comment by RustyPixel** [comment]
@Diaoul  another package that has  it

```
package="Perl"
version="5.18.4-0019"
maintainer="Perl.org"
maintainer_url="http://www.perl.org/"
distributor="Synology Inc."
distributor_url="http://www.synology.com/"
arch="x86 bromolow cedarview avoton"
firmware="5.0-4356"
dsmappname="SYNO.SDS.Perl"
startable="no"
support_center="yes"
silent_install="yes"
silent_uninstall="yes"
thirdparty="yes"
```
start_stop_status
```
#!/bin/sh
# Copyright (C) 2000-2013 Synology Inc. All rights reserved.

. `dirname $0`/common

case $1 in
	start)
		DO_LINK
		exit 0
		;;
	stop)
		exit 0
		;;
	status)
		if [ -e "/usr/bin/perl" ]; then
			exit 0
		else
			exit 150
		fi
		;;
	killall)
		;;
	log)
		exit 0
		;;
esac
```

if you change  the status to match that of MC

```
	status)
			exit 1

		;;
```

 it will show as stopped in the package center, and all the perl install does is add perl to the command line

**Comment by Dr-Bean** [comment]
Imo, it's a matter of an personal preference, not a matter of right or wrong.

Synology prefers to show a `started` status for their packages, regardless of whether a process is actually running, by basing the status on the existence of a (in some cases arbitrary) file.
We have a different point of view: packages like mc do not 'run' (not as as a service anyway), so showing a `running` status is inaccurate, and it serves no practical purpose to implement it.

**Comment by RustyPixel** [comment]
But from a end user point it stop them asking the question at the start of this issue. Not all end users are the same when it come to click and play.

**Comment by mrxxxxxx** [comment]
Hello Guys,

sorry for my bad english.
I have a Problem with Midnight Commander 4.8.x.x
If i start with commando mc the blue screen of Midnightcommander is not visible. I see only a little blue corner of the MC in the right Top of Screen and at the Bottom the Status/Commando Line.
MC dont response on any Key.
See Screenshoot please
![image](https://cloud.githubusercontent.com/assets/15039827/14763719/4441e050-099e-11e6-8c10-62bea76fa322.png)
