### ISSUE TITLE
[REQUEST] MiniDLNA (ReadyMedia)

### ISSUE THREAD

**Issue by bbsixzz** [SynoCommunity/spksrc#1437]
Hey,

The standard Synology Media Server would be wonderful if it indexed torrents downloaded with Transmission/ruTorrent properly. I've used serviio in the past but the Java dependency is annoying and so I've finally come to MiniDLNA; unfortunately the latest version is only compiled for the Armada 370 and there is only older versions for my Armada 300 (DS211+) which works but sorts terribly due to a setting that has been corrected in later versions.

Please consider compiling this for the older models, it's a great little tool.

Cheers
##

**Comment by SirWayne** [comment]
Hey, is there a minidlna package for Armada375?

**Comment by rewozz** [comment]
Yep.

http://forum.synology.com/enu/viewtopic.php?f=40&t=95346
http://forum.qnap.com/viewtopic.php?t=100843

**Comment by SirWayne** [comment]
Thanks :) i will try it or is there a spk too?
here it is no longer accessible http://forum.synology.com/enu/viewtopic.php?f=190&t=87856&start=15

**Comment by rewozz** [comment]
There was but I no longer know where, I'm a lot happier with qnapware now though. I also learnt a lot more about UNIX thanks to this :)

**Comment by SirWayne** [comment]
Ok thanks it works, but now i have two appstore folder.
The @appstore and the created Apps folder :D

**Comment by Dr-Bean** [comment]
This tracker is not a discussion platform for optware, so please discuss your problems with it elsewhere :)

MiniDLNA is not available as a SynoCommunity package, which is why this request is still open. PR's are welcome.
