### ISSUE TITLE
HTPC manager - "Can't install"

### ISSUE THREAD

**Issue by batmanraid** [SynoCommunity/spksrc#1440]
Hi everyone,

I'm trying to install HTPC manager from the Package center.

It seems that the download is ok, starts the installer, but after a few seconds it says "Can't install".

Synology DS413j
DSM 5.1-5021 Update 2
Python 2.7.8-11 installed and running.

**Comment by Dr-Bean** [comment]
I signed the package. Make sure the Package Center allows trusted publishers (second option), and try again please.
