### ISSUE TITLE
DS415+ - Fresh install of ZNC errors

### ISSUE THREAD

**Issue by SuperRoach** [SynoCommunity/spksrc#1445]
Hi all, just tried to use ZNC. On installing it, first run gives a failed to launch package error on the gui. 

Logging in as admin, and running the command to manually start it:

bigbox> /var/packages/znc/scripts/start-stop-status start
Starting ZNC ...
Password:
Segmentation fault

https://github.com/SynoCommunity/spksrc/issues/1427 Seems to have a similar problem, although they got further than me in getting to run it.

**Comment by Dr-Bean** [comment]
ZNC 1.4-10 has just been published on the repository. Please remove and reinstall ZNC, and report back if your issue persists. It does seem likely it's a local issue on your side, seeing as the package in itself does not segfault for others with a 415+.
