### ISSUE TITLE
[SOLVED] Transmission 2.84-10 installation failed

### ISSUE THREAD

**Issue by castorfou** [SynoCommunity/spksrc#1447]
It is a fresh Nas (215j).

I do next, next, next in the installation wizard, and in the last screen I click Apply.
A popup says : Failed to install "transmission".
I don't see anything in logs (in /var/log)

Any ideas ?

**Comment by castorfou** [comment]
In the package center settings you need to set the "Trust Level" to equal "Any Publisher".

**Comment by Diaoul** [comment]
Synology and Trusted publishers should be enough.

**Comment by Boogmeister** [comment]
Having exact same issue with a DS414 with 5.1-5022 Update 5.

Was working before i reinstalled DS firmware for other issues and now it won't install with the same error as above.

Where do i need to look for more info?

**Comment by skabaas** [comment]
Should be, but isn't. Just had the same issue. This solved it.
