### ISSUE TITLE
[REQUEST] user priority setting ans settings export/import (backup)

### ISSUE THREAD

**Issue by zollux** [SynoCommunity/spksrc#1448]
Hi!

In case of multiple clients using the TVHeadEnd server, there would be useful to priorize users. When there is only one tuner. It's anoying, when I want to watch the "master" tv, then I cannot change to cannels on other multiplex, while lower priority users watching something. 
If I could priorize users, the lower priority user's playback would stop, similar way, as the timed recording forces to stop playback, if the recorded program is on another multiplex.

Also a settings export / import would be nice: i had to reconfigure everything after the recent update. (Only 10 DVB-T channels, so not too much time) (After the update, the server didn't started: I had to uninstall and reinstall the app, which caused the reset of prev. version's settings. I tryed to backup manually the "tvheadend_test/var" directory, but when I copyed back, the tvheadend didn't started. Its sureley sensitive to settings files.) So the Import/export can can solve this.

The most recent build 3.9.2334 runs well on Synology DS with Armada XP processor (Tuner: Realtek RTL2832 DVB-T - ASUS My Cinema-U3100Mini Plus V2)  

Nice job, and much thanks for it!
Regards, Zollux

**Comment by Dr-Bean** [comment]
Not sure, but is this related to #931? TVHeadend-Testing is discussed there.

**Comment by Dr-Bean** [comment]
Please report your ideas and findings to https://github.com/SynoCommunity/spksrc/pull/931, that might help the development of the package to go forward. I'll close this one.
