### ISSUE TITLE
Failed to install "bitorrent Sync"

### ISSUE THREAD

**Issue by ohdude** [SynoCommunity/spksrc#1450]
I get this message
![btsync](https://cloud.githubusercontent.com/assets/6848396/5743922/c88d4d40-9c1c-11e4-97a5-938a9c26d8ca.png)

**Comment by CyrilGips** [comment]
I am getting the same message when trying to install Sickbeard Custom.

**Comment by CyrilGips** [comment]
Found the answer, it seems the new dsm has a trust setting in the package center. Changing that allowed me to install third party packages again.

**Comment by Dr-Bean** [comment]
Visit https://synocommunity.com/#easy-install, and follow the instructions on how to correct the Package Center settings.
