### ISSUE TITLE
Help with picking correct repo for synology

### ISSUE THREAD

**Issue by jbbrenner90** [SynoCommunity/spksrc#1455]
Hey everyone can you help me with what i need. My nzb drone no longer works as with that whole thing that happend and i need to update it. I can not because the synocommunity is down. So i am manually trying to update mono and nzb drone but not sure what one i need exactly. 

Here is my synology info.
https://www.dropbox.com/s/4m3hg7iy1r89p03/Screenshot%202015-01-25%2017.16.58.png?dl=0

Here is the packages im looking at for mono and nzb drone.

https://www.dropbox.com/s/xjsq9ceafko9u9b/Screenshot%202015-01-25%2017.17.30.png?dl=0

https://www.dropbox.com/s/baesi2exnt9530u/Screenshot%202015-01-25%2017.17.58.png?dl=0

Thank you

**Comment by bjakobs** [comment]
I believe you would want the X86 ones.

**Comment by Dr-Bean** [comment]
You can look up your device model on this page: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model, and check for the architecture. 1513+ would be a cedarview arch.

If you cannot get it to work, I'd suggest waiting until the repo is back up and running. See #1452.
