### ISSUE TITLE
Problem with TestDisk package

### ISSUE THREAD

**Issue by ilmaestro82** [SynoCommunity/spksrc#1456]
I'm just installed Testdisk but i have a problem to run it.

After instaling the package on my proliant hp server with dsm 5.0
- I go to my testdisk folder (cd PATH/mytestdiskfolder)
- I try to run testdisk.sh (sh testdisk)
but I have this error : 
Syntax error: “(” unexpected

I'm doing something wrong. It's the first time I use telnet.

Thank to help me

**Comment by Dr-Bean** [comment]
I assume you installed the package provided on @cytec's repository?
I just did a quick check, but shouldn't you be running the command like this: 
`/usr/local/testdisk/bin/testdisk`
and just follow instructions as they come?

**Comment by cytec** [comment]
@Dr-Bean is right... 
i don't know any testdisk.sh file getting installed with the SPK so just call the binary and then choose your options like you would do normally on any machine.

**Comment by ilmaestro82** [comment]
Thank you! You are helpful! I just called the binary as root user : 

ssh root@mystation
/usr/local/testdisk/bin/testdisk

**Comment by Dr-Bean** [comment]
Perfect. Let's close this issue then :)
