### ISSUE TITLE
[Request] Update BicBucStriim

### ISSUE THREAD

**Issue by JuergenBY** [SynoCommunity/spksrc#1458]
There is an issue with Moonreader+ and OPDS Requests. The Author of BicBucStriim fixed this. When could we expect an Update Package through SynoCommunity?

Update: https://github.com/rvolz/BicBucStriim/commit/2a1882b12fd098c724be38ac4445e0bae6cdc847

**Comment by Dr-Bean** [comment]
Could you ask when the author plans to release a new version on http://projekte.textmulch.de/bicbucstriim/downloads/? That's where the official releases of BBS are posted, and it would make sense to wait for an official release.

**Comment by JuergenBY** [comment]
He is working on it, just some small changes left...

**Comment by Dr-Bean** [comment]
See #1762.
