### ISSUE TITLE
ZNC Install Fails on DS215j without some tinkering

### ISSUE THREAD

**Issue by TriggerAu** [SynoCommunity/spksrc#1461]
I followed the default instructions and basically found that it would not start the package on the NAS. Hopefully this is the right place to throw this, I couldn't find a forum as such to place it specifcally

DS215j with DSM 5.1-5022 Update 1

The below steps are the ones I used to get it working

### 1. Install from web console
```
> tail /var/log/synopkg.log
2015/01/31 21:00:02     install znc 1.4-9: run postinst  ret=[0]
2015/01/31 21:00:02     znc stderr:     su: can't run /sbin/nologin: No such file or directory

2015/01/31 21:00:02     install znc 1.4-9 successfully
```

### 2. Start it from web console
```
> tail /var/log/synopkg.log
2015/01/31 21:04:23     start znc: begin to start version 1.4-9
2015/01/31 21:04:23     stop znc: begin to stop version 1.4-9
2015/01/31 21:04:23     stop znc: stop version 1.4-9 successfully, result 0
2015/01/31 21:04:23     start znc: start version 1.4-9 failed, result 263
```

### 3. Run from Shell as root
```
> /var/packages/znc/scripts/start-stop-status start
Starting ZNC ...
su: can't run /sbin/nologin: No such file or directory
```

### 4. Change /etc/passwd to have znc user using /bin/sh shell
I'm not a linux guy so I wasnt sure how to install /sbin/nologin to the system

### 5. Run from web console
````
> tail /var/log/synopkg.log
2015/01/31 21:19:25     start znc: begin to start version 1.4-9
2015/01/31 21:19:26     stop znc: begin to stop version 1.4-9
2015/01/31 21:19:26     stop znc: stop version 1.4-9 successfully, result 0
2015/01/31 21:19:26     start znc: start version 1.4-9 failed, result 263
````

### 6. Run from Shell as root
```
> /var/packages/znc/scripts/start-stop-status start
Starting ZNC ...
[ .. ] Checking for list of available modules...
[ >> ] ok
[ .. ] Opening config [/usr/local/znc/var/configs/znc.conf]...
[ >> ] ok
[ ** ] Found old config from ZNC < 0.203. Saving a backup of it.
[ .. ] Creating a config backup...
[ !! ] File exists
[ .. ] Loading global module [webadmin]...
[ >> ] [/usr/local/znc/lib/znc/webadmin.so]
[ .. ] Binding to port [8250]...
[ >> ] ok
[ .. ] Binding to port [+8251]...
[ !! ] Unable to locate pem file: [/usr/local/znc/var/znc.pem]
[ ?? ] Would you like to create a new pem file? (yes/no) [yes]: yes
[ .. ] Writing Pem file [/usr/local/znc/var/znc.pem]...
[ >> ] ok
[ .. ] Binding to port [+8251]...
[ >> ] ok
[ ** ] Loading user [zncadmin]
[ .. ] Forking into the background...
[ >> ] [pid: 27193]
[ .. ] Writing pid file [/usr/local/znc/var/znc.pid]...
[ >> ] ok
[ ** ] ZNC 1.4 - http://znc.in
```

### 7. Run from web console
```
> tail /var/log/synopkg.log
2015/01/31 21:21:24     start znc: begin to start version 1.4-9
2015/01/31 21:21:24     start znc: start version 1.4-9 successfully, result 0
```

**Comment by Dr-Bean** [comment]
Please check open issues first, #1427. I'll probably release an updated package in the next day or so.

**Comment by TriggerAu** [comment]
apologies @Dr-Bean , I searched ZNC first and somehow missed that one. found the other one that references it though :(

Was going to add another issue for the ZNC App Icon not opening the web interface too once I dig a bit - I dont see that in there anywhere - am I missing it too?

**Comment by Dr-Bean** [comment]
No problem :)

On the icon topic, you mean there is an icon in the menu, but it doesn't do anything? That'll be solved with the new release too.
The reason is the icon currently relies on the (Synology) Perl package, and you probably don't have Perl installed. I've removed the dependency from the updated package, so that'll be part of the updated package too.

**Comment by TriggerAu** [comment]
Yep thats the one and yep no perl yet - only started today and this was the first app I needed.
Thanks for the info, and patience, I know its annoying when you get double issues

**Comment by Dr-Bean** [comment]
ZNC 1.4-10 has been released, fixing the issues you've encountered.
