### ISSUE TITLE
Questions about OwnCloud

### ISSUE THREAD

**Issue by romu70** [SynoCommunity/spksrc#1462]
Hi,
I've successfully installed OwnCloud on my DS1513, really easy, so first, thank you!

I've now some questions about this installation:
1. Is there a way to add my own certificate for this OwnCloud? I use such a certificate for the DSM, I've seen OwnCloud is also available with secured protocols but with a self-signed certificate.

2. OwnCloud can crypt files, and I do NOT want this feature as I've lost data in the past because of this mess. The OwnCloud for Synology installation is so easy we can't see this feature in the installation procedure, and I want to be sure it is not activated. If it is, how can I disable it?

Thanks.

**Comment by Dr-Bean** [comment]
The certificate you have configured in DSM (Control Panel/Security/Certificate) is used for all communication over SSL, including web interface and client app.

As for the file encryption, check out the Owncloud documentation (here)[http://doc.owncloud.org/server/7.0/user_manual/files/encryption.html]. You have to enable it manually, and it doesn't look like you can do that by accident.

**Comment by romu70** [comment]
Perfect, thanks a lot for all of those useful information.
