### ISSUE TITLE
ps3netsrv on DS415+

### ISSUE THREAD

**Issue by unofr** [SynoCommunity/spksrc#1464]
Hi all,

I hope this is the godd process to obtain help?
I do not know this kind of blog community and how it works.
I am also n00b with NAS so hope you will improve my skill

Does ps3netsrv work on DS415+?
Indeed I have tried to follow another tuto but I have an error @ the end
Everything is ok between my PS3 and my PC but KO when I wnat to compile PS3netsrv on my NAS DS415+ 
http://www.synology-wiki.de/index.php/Welchen_Prozessortyp_besitzt_mein_System%3F
The DS415+ has a Intel ATOM C2538

And this tuto with modification of directories for x86 does not work (post @ the end but modified for X86 directories)
http://www.ps3hax.net/showthread.php?t=64811&p=693133&viewfull=1#post693133

Perhaps because the IPKG is not OK for ATOM C2538
http://ipkg.nslu2-linux.org/feeds/optware/syno-i686/cross/unstable/syno-i686-bootstrap_1.2-7_i686.xsh

On mys NAS I have 4HDD of  4To and would like to use the second slot only for PS3 ISO with this Directory :
PS3/PS3ISO
and would like to have the service PS3netsrv always on

I have use this tuto

"Here's how I did it on my Synology DS212+

Step #1:
For synology NAS users, you will have to bootstrap your NAS drive, use this guide here to do it the easy way (follow the guide so the last thing you do is ipkg update):

Once done - reboot the synology NAS.

Step #2:
Download a small program called WinSCP - this will let you easily copy files to the NAS and create folders.
You can get this here: hxxp://winscp.net/eng/download.php

Once done run winSCP - choose scp as the file protocol
Hostname: the ip address of your nas
username:root
Password:the admin password of the NAS

Go to the root folder and inside this create another folder called - ps3netsrv
Extract the zip file from the fisrt post of this thread - ps3netsrv.zip, then drag all the extracted files into the ps3netsrv folder (set the permissions of these to 0755)

you created by dragging and dropping them on the winSCP program's right window pane.

STEP #3:
Use putty - hxxp://www.chiark.greenend.org.uk/~sgtatham/putty/download.html to issue the following commads to the NAS:
(Make sure SSH is enabled on the NAS - control panel/terminal/enable SSH service)

In putty type the following: (some steps take a while)

ipkg install gcc
ipkg install make
ipkg install sudo
mkdir /opt/arm-none-linux-gnueabi/lib_disabled
mv /opt/arm-none-linux-gnueabi/lib/libpthread* /opt/arm-none-linux-gnueabi/lib_disabled
cp /lib/libpthread.so.0 /opt/arm-none-linux-gnueabi/lib/
sudo ln -s /usr/lib/libstdc++.so.6 /usr/lib/libstdc++.so
cd /opt/arm-none-linux-gnueabi/lib/
ln -s libpthread.so.0 libpthread.so
ln -s libpthread.so.0 libpthread-2.5.so
cd /
cd /root/ps3netsrv
make

(Once done you can go back to step #2 and delete all the files you put into the ps3netsrv folder you created - just leave the pr3netsrv file you just made.)

Now in putty issue the following command:

./ps3netsrv/ps3netsrv /volume1/ps3

If you look at the above command it expects that in Volume1 of the NAS you have a shared folder called ps3 - inside this folder you

should have your PS3ISO folders etc.

Now on the ps3 - you should be good to go 

Thanks for your help

**Comment by Dr-Bean** [comment]
Unfortunately, no, this is not the correct place to discuss optware/ipkg. We build our packages with spksrc and cross-compilation.
