### ISSUE TITLE
Domoticz now in repository, but not all arch's use the working package

### ISSUE THREAD

**Issue by jorikcaljouw** [SynoCommunity/spksrc#1468]
I think I found 2 issues, but both can probably resolved at once.

It seems that Domoticz is now published on SynoCommunity's repository. When I look here:
https://synocommunity.com/package/domoticz

I see that these three arch's are available: alpine armada375 avoton

However for my DS411+II (x86) arch I was prompted to update my own built package with the 281-1 package. I did try "updating" the package (I was curious to see what it would do, but unfortunately this is the old package that never worked). Now, I am unable to install one of the newer package: DSM things that port 8084 is already in use by a service, but nothing is currently listening on this port (telnet on port 8084) and the same package could be installed previously.
![screen shot 2015-02-03 at 22 54 35](https://cloud.githubusercontent.com/assets/7646814/6030428/aca511f4-abf7-11e4-97b5-d5c9a94186a6.png)

**Comment by jorikcaljouw** [comment]
Ah I understand the port error. The older package did not use the servicetool to register and unregister the firewall configuration. So I just had to run this manually:
/usr/syno/bin/servicetool --remove-configure-file --package domoticz.sc

Still I don't think the old package should be available in the repository, so this remains an open issue.

**Comment by Dr-Bean** [comment]
That's easily handled though ;) I'll upload the up-to-date versions of Domoticz to the repo, I already have those compiled. Might be tomorrow until you see them show up.

**Comment by jorikcaljouw** [comment]
Thanks!

**Comment by SynoUser-NL** [comment]
After downloading the package my DS1513+ displays a message that the package does not contain a digital signature. The package will not install. Is there a solution for this issue?

**Comment by jorikcaljouw** [comment]
DS1513+ has x64 architecture. Which version of this package is DSM trying to install? If it is different from:
v2.0.2112-5 I would not try to install it, since it will then be nonfunctional. It will be updated as mentioned by @Dr-Bean.

If you are trying to install v2.0.2112-5, then you can allow unsigned packages. This is a setting in Package Manager. I'm not sure how packages need to be signed, but that may also be possible.

**Comment by Dr-Bean** [comment]
I just deactivated the old packages, no use in providing those if they are broken anyway.
Let me finish uploading the remaining packages: those will be signed, so then you don't need to allow unsigned packages anymore.

**Comment by Dr-Bean** [comment]
Domoticz 2.0.2112-5 is published for all archs. Thanks for the notice ;)
