### ISSUE TITLE
http://packages.synocommunity.com/ Down

### ISSUE THREAD

**Issue by stacimail** [SynoCommunity/spksrc#1470]
Just wanted to report the site is down today and see if there's an ETA on a fix. Thanks!

**Comment by waylonwang** [comment]
the response from site :

Bad Request

The browser (or proxy) sent a request that this server could not understand.

**Comment by Diaoul** [comment]
Works for me. Report again if this is not fixed.

**Comment by stacimail** [comment]
Still not working, other sources added and functioning fine on my DS414J

**Comment by stacimail** [comment]
![screen shot 2015-02-06 at 8 25 01 am](https://cloud.githubusercontent.com/assets/10871411/6080751/adb97df8-add9-11e4-8a2c-62ada81d1e27.png)

**Comment by Diaoul** [comment]
Can be an ipv6 issue. I'll take a look at this this evening.

**Comment by stacimail** [comment]
Thank you! :+1:

**Comment by stacimail** [comment]
Looked into the network settings and set manual DNS addresses, now it works perfectly fine. Strange that other sources added but the issue was in my settings. Thanks again!

**Comment by Diaoul** [comment]
I changed the DNS entries when server was down to display a page. That was more than a week ago so your DNS server had outdated entries IMO.
