### ISSUE TITLE
Missing parent directories cause make failure

### ISSUE THREAD

**Issue by krichter722** [SynoCommunity/spksrc#1473]
`make` fails due to some missing (parent) directories, e.g. `spk/newznab/work/staging`, `spk/sabnzbd/work/staging` in a fresh checkout. Directories are not tracked in `git`, e.g. checkout/fetch doesn't create empty directories.

**Comment by Dr-Bean** [comment]
Work directories are created when needed, e.g. when running `make`. They are not supposed to be tracked by git.
So, the failure has a different reason. Could you provide the command, and the output that you're getting with it?

**Comment by Dr-Bean** [comment]
Closing as not a bug. Let us know if you still need a hand.
