### ISSUE TITLE
Custom orrent providers in Couchpotato do not work

### ISSUE THREAD

**Issue by simistef** [SynoCommunity/spksrc#1479]
Hi there,

custom torrent providers for couchpotato does not work.

For example https://github.com/outkastm/Filelist.ro i've added the files in a folder and does not show up

Same problem with other custom providers.

Anyone know why this is not working ?

thanks

**Comment by Dr-Bean** [comment]
Not much we can do, we only package the software. This should probably be posted on the [CouchPotato tracker](https://github.com/RuudBurger/CouchPotatoServer), or on the CouchPotato forums.
If you open an issue, make sure you follow the [rules](https://github.com/RuudBurger/CouchPotatoServer/blob/develop/contributing.md#issues)
