### ISSUE TITLE
[ownCloud] Can't uninstall with empty root password

### ISSUE THREAD

**Issue by mad93** [SynoCommunity/spksrc#1482]
I can't remove ownCloud package from my system since the removal process requires a password for mysql root user, and in this system I don't have any password. Shouldn't be the password optional since later is performed a validation check?

**Comment by Dr-Bean** [comment]
I was under the impression that it was impossible to create a database without having a password set. Apparently, that's not the case :/

A short term solution for you is to set a password for mysql/MariaDB. On longer term, I guess we'll re-release the affected packages to correct that.

**Comment by Dr-Bean** [comment]
Fixed with c6522d5f47ee198c02214c281ce611cfdc568b7a. Not sure yet if we'll release new packages specifically to cover this issue.

**Comment by Dr-Bean** [comment]
Fixed: Owncloud 8.0.2-6 has been published. 

Sidenote for people noticing similar issues with other packages: Set a password for MySQL/ MariaDB. It adds security, and for at least MariaDB, you can do that via the DSM GUI.
