### ISSUE TITLE
http://packages.synocommunity.com/  bad 400

### ISSUE THREAD

**Issue by houpdelta** [SynoCommunity/spksrc#1483]
Hi, 

I have a problem, the link is wrong "error 400"

A@

**Comment by Diaoul** [comment]
Just put this URL in your NAS, it's not browsable.

**Comment by houpdelta** [comment]
![erreur](https://cloud.githubusercontent.com/assets/10964021/6153869/e779cca8-b227-11e4-9d57-ee2cc95593ca.png)

**Comment by Diaoul** [comment]
See #1476
