### ISSUE TITLE
"Subliminal" package can not be installed - Does not have a signature?

### ISSUE THREAD

**Issue by ambreswe2** [SynoCommunity/spksrc#1486]
"Subliminal" package can not be installed - Does not have a signature apparently, why? :)
![2015-02-13 12_58_24-ds1](https://cloud.githubusercontent.com/assets/10994889/6190140/2c03de1c-b3a0-11e4-9758-4b9505305d0c.png)

**Comment by Dr-Bean** [comment]
Signature is added, thanks for reporting :)

**Comment by ambreswe2** [comment]
Cheers :)
