### ISSUE TITLE
rTorrent/ruTorrent config

### ISSUE THREAD

**Issue by boardwarp** [SynoCommunity/spksrc#1489]
Here's the story:
Decided to switch from Transmission to ruTorrent/rTorrent on my Synology after trying it out on a seedbox.
Wanted to rename download dir from "Transmission Downloads" to "Torrent Downloads"
Made "Torrent Downloads" dir, moved everything over, then began adding existing torrents to ruTorrent.
When adding multiple torrents, only the first 20 are received by ruTorrent, the rest are dropped (no big deal)
Expected all torrents to show 100% completion and resume seeding after force recheck.
Had forgotten that several torrents were saved in non-default dirs. Tried using Save To... option from context menu.
Done % would creep up to 100, then drop back to zero. Path would not appear changed in torrent details.
Instead tried downloading torrent again, removing from ruTorrent, then adding again specifying correct dir.
Done % reaches 100, begins seeding. If ruTorrent is stopped and started, torrent reverts to 0%.

I was quite tired/frustrated when attempting this. Can't recall all the steps or order they were attempted, but this is what I've done today:

Added line to basedir:
:/usr/local/rutorrent/share/rutorrent/conf/:/usr/local/rutorrent/share/rutorrent/php/:/usr/local/rutorrent/share/rutorrent/

Log appears empty:
DiskStation> cat var/rtorrent.log
DiskStation>

Added /usr/bin/* entries to rutorrent.conf
All executables present in /usr/bin
DiskStation> which php
/usr/bin/php
DiskStation> /usr/bin/php -v
PHP 5.5.19 (cli) (built: Jan  7 2015 14:36:29)

Unable to edit default path in .rtorrent.rc, desired path has space.

I believe I still need to do some more configuration for ruTorrent to work as expected, but I'm totally lost at this point.

**Comment by Dr-Bean** [comment]
Closing. Please open a new issue if the problem still exists with the new package. Note that if you can't provide reproducable steps, we can't help.
Try upgrading your current package to the new release. If that doesn't work, do a clean install of the package and check again. 

If the problem still exists/returns, please document what you see and what you have done in a new issue.
