### ISSUE TITLE
Can not connect to synocommunity repo from my nas

### ISSUE THREAD

**Issue by patafrom** [SynoCommunity/spksrc#1490]
Hi, I can not connect to the synocommunity repo from my nas. Dns is fine and do return 176.31.184.40.

what should I do ? Ant suggestions ?

thanks

**Comment by piwi82** [comment]
Have you tested the name resolution through SSH on your NAS ?

**Comment by jimbo72** [comment]
Hi, I have the same problem. I tried to add http://packages.synocommunity.com/ as package repo, but I get an error "bad location" if I translate properly.
I have tried as suggested to see if name resolution, then ssh as root:
DiskStation> ping www.packages.synocommunity.com
PING www.packages.synocommunity.com (176.31.184.40): 56 data bytes
64 bytes from 176.31.184.40: seq=0 ttl=55 time=42.582 ms
64 bytes from 176.31.184.40: seq=1 ttl=55 time=43.587 ms
64 bytes from 176.31.184.40: seq=2 ttl=55 time=44.345 ms

=> seems ok no ?

Any help would be appreciated

**Comment by Dr-Bean** [comment]
Check #1476 for info and a possible workaround. 
@jimbo72: looks like you're pinging a different URL than you want to add as a repo, so that's not very indicative of anything really ;)

**Comment by Diaoul** [comment]
Closing this in favor of #1476

**Comment by jimbo72** [comment]
Sorry, and thank you I was pinging a wrong URL.
#1476 was very useful, I changed the DNS to google one (8.8.8.8) and I am able now to add  http://packages.synocommunity.com/ as package repo.
Thanks a lot
