### ISSUE TITLE
BTSync compilation broken

### ISSUE THREAD

**Issue by tmarkwardt** [SynoCommunity/spksrc#1492]
Hi,

i can't compilation the spk btsync. on make the script checked all files on digest and not found libraries with unused architectures ...

Regards,
Torsten

**Comment by tmarkwardt** [comment]
here a solution:
file: spksrc.checksum.mk
modification: select only $(DIST_FILE) filename from file digist to validate checksum

--- mk/spksrc.checksum.mk_orig	2015-02-16 16:20:25.649627628 +0100
+++ mk/spksrc.checksum.mk	2015-02-16 18:52:43.450749911 +0100
@@ -41,7 +41,9 @@
 checksum_target: $(PRE_CHECKSUM_TARGET)
 	@if [ -f $(DIGESTS_FILE) ] ; \
 	then \
-	  cat $(DIGESTS_FILE) | (cd $(DISTRIB_DIR) && while read file type value ; \
+	  distfile=$(DIST_FILE) ; \
+	  distfilename=$${distfile##*/} ; \
+	  cat $(DIGESTS_FILE) | grep "^$${distfilename}" | (cd $(DISTRIB_DIR) && while read file type value ; \
 	  do \
 	    if [ ! -f $$file ] ; \
 	    then \

**Comment by Dr-Bean** [comment]
Or download all the packages (either manually, or do a `make all-archs && make clean` in cross/btsync. BTSync is a one-off that has this issue.

Overall, I wouldn't mind seeing the functionality implemented, but I'm not sure I like the way this looks. Maybe compare $(DIST_FILE) to $$file would make sense?

Sidenote: please put your code between backticks (`), that preserves the formatting.

**Comment by tmarkwardt** [comment]
on `$(DIST_FILE)` the file is with path and a match or compare is needed. 
the alternate is the loop over all entries without filtering and a additional compare ...
i think, the filter of file is more efficient.
only a little security set: `grep "^$${distfilename} "` with a space on end on filename.

**Comment by Diaoul** [comment]
@Dr-Bean: is there any pending action here?

**Comment by Dr-Bean** [comment]
@Diaoul It's essentially the todo item here: https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.checksum.mk#L9. We've managed without it for a while though ;) What do you think of @tmarkwardt's solution?

**Comment by Diaoul** [comment]
Well if it works as expected and is backward compatible that's all that matters for me.

**Comment by Diaoul** [comment]
We'll wait a bit and remove btsync from spksrc. I disabled the packages on the repository as the official app is released.

**Comment by Dr-Bean** [comment]
For the record, I was looking into this a couple days ago, and I figured out why it didn't feel right. The solution proposed here isn't complete: if DIST_FILE isn't in digests, it should stop with a message instead of ignoring it.
