### ISSUE TITLE
[request] salt-minion

### ISSUE THREAD

**Issue by jaymcconnell** [SynoCommunity/spksrc#1494]
Any chance of getting this as a standalone package? in our use case we don't need master/halite, but have a tonne of devices in the field that would benefit from being managed by salt.
##

**Comment by Diaoul** [comment]
Yes, that's the plan. But there is no support for Synology devices in Salt stable (yet).

**Comment by evaryont** [comment]
I think this is no longer the case. With https://github.com/saltstack/salt/issues/20778 being merged in, salt should be able to detect Synology/DSM now.

**Comment by hgy59** [comment]
implemented with PR  #4119
