### ISSUE TITLE
LazyLibrarian fails to install

### ISSUE THREAD

**Issue by rosterloh** [SynoCommunity/spksrc#1495]
On my DS215j LazyLibrarian fails to install with the error
```
Failed to install "LazyLibrarian". This package does not contain a digital signature.  
```

**Comment by Dr-Bean** [comment]
Package is signed now, give it another try :)

**Comment by rosterloh** [comment]
Perfect. Thanks.

**Comment by ramasjang** [comment]
I am having the same issue now:
Failed to install "LazyLibrarian". This package does not contain a digital signature.

Thanks

**Comment by Dr-Bean** [comment]
@ramasjang Rechecked, but there's only one LL package. I signed that, and it's still signed. You sure you're looking at the SynoCommunity package, not a package from a different package source?
