### ISSUE TITLE
Git installs with user 1000 and group 1000?

### ISSUE THREAD

**Issue by codered3** [SynoCommunity/spksrc#1496]
Hi,

I installed the SynoCommunity package of Git and noticed that the user and group are set to "1000". This is the only SynoCommunity package that has installed with permissions like this. Normally both user and group are set to root.

![screen shot 2015-02-18 at 13 12 05](https://cloud.githubusercontent.com/assets/11060179/6247716/c4b3e512-b76f-11e4-89ab-a4e486349b89.png)

Anything to be concerned about? Why 1000?

Thanks

**Comment by Dr-Bean** [comment]
Nothing to be concerned about. We don't set specific permissions for this package, as there's no need for that with this package.
