### ISSUE TITLE
Incorrect location Xpenology

### ISSUE THREAD

**Issue by philou15** [SynoCommunity/spksrc#1497]
Hye 

I Have up my xpenology to dsm 5.0.4528 update 2 and now i have an error

http://packages.synocommunity.com/ : invalid location.

Sorry for english i'm french.

If they have a solution ? 

tks

**Comment by piwi82** [comment]
Have you tried changing your DNS servers ?

**Comment by philou15** [comment]
ok i have put google dns 

its work

tks
