### ISSUE TITLE
BT sync 2.0 for synology

### ISSUE THREAD

**Issue by vhanacek** [SynoCommunity/spksrc#1503]
Is there a package btsync 2.0 for synology NAS?
Thanks.

**Comment by piwi82** [comment]
I am not sure BTsync 2.0 has been publicly released.
Do you have a link where it could be downloaded ?

**Comment by piwi82** [comment]
Got it : http://forum.bittorrent.com/topic/33930-new-sync-beta-build-2051-with-community-testing-task-3/#entry98627

**Comment by Dr-Bean** [comment]
Well, that text isn't very reassuring. It looks like it's a testing version of a beta version...

**Comment by piwi82** [comment]
I totally agree. Even if all enterprise features are available in this version, the compatibility between 2.x versions is often broken.
But you can try it without having a package (manual installation).

**Comment by hurik** [comment]
btsync 2.0 was released: https://www.getsync.com/
In the free version you can only share 10 folders.
Should I make an separate package for the 2.0 version?

**Comment by piwi82** [comment]
There are official packages available for a manual installation : http://help.getsync.com/customer/portal/articles/1888507-synology

Should we release a package ?

**Comment by Diaoul** [comment]
The official package should hit the official repository of Synology in March from what BTSync developers told me so I'd rather not to.

**Comment by piwi82** [comment]
Could you update BitTorrent Sync 1.4.110 (current) to <a href="http://forum.bittorrent.com/topic/34316-latest-14-beta-desktop-build-14111/">1.4.111</a> ?

**Comment by hurik** [comment]
Yep ... will do it.

**Comment by hurik** [comment]
Done: https://github.com/SynoCommunity/spksrc/pull/1523

**Comment by hurik** [comment]
Also made an BitTorrent Sync FAQ Wiki page: https://github.com/SynoCommunity/spksrc/wiki/BitTorrent-Sync-FAQ

**Comment by Dr-Bean** [comment]
BTSync 1.4.111-11 is published on the repository. 

Since a btsync 2.0 won't be released by us, let's close this issue.
