### ISSUE TITLE
Cannot install BT Sync on DS213

### ISSUE THREAD

**Issue by maho1979** [SynoCommunity/spksrc#1504]
I try to instrall BT sync on DS 213.
The Package Center says in German "Bit Torrent Sync konnte nicht installiert werden"
My translation: "Can not install Bit Torrent Sync"

**Comment by Dr-Bean** [comment]
Please check the instructions on https://synocommunity.com/#easy-install, particularly step 1.

**Comment by maho1979** [comment]
Thank you for your help. I forgot the first points with the trusted servers.
sorry for the ticket
