### ISSUE TITLE
squidguard 1.5-1 fails on DS214+

### ISSUE THREAD

**Issue by transistorgit** [SynoCommunity/spksrc#1505]
I was able to install and start with no probs. But clicking the main menu icon, as I wanted to configure it, resulted in a page not found message. The web address was 
www.ds.local:5000/webman/3rdparty/squidguard/squidguardmgr.cgi
and look Ok for me.

best regards Bernd

**Comment by Dr-Bean** [comment]
Check if Perl is installed. Then, check here, because the package might not work correctly on DSM5+: https://github.com/SynoCommunity/spksrc/issues/1442

**Comment by transistorgit** [comment]
Installed Perl, followed the hint in #1442, works now.
and I love when things work.
Thank you very much.
Bernd.
