### ISSUE TITLE
Errors each that Get_iPlayer used

### ISSUE THREAD

**Issue by Rich14** [SynoCommunity/spksrc#1506]
I get errors each time I use Get_iplayer and a report is sent off.

get_iplayer 2.91-ppa21, Copyright (C) 2008-2010 Phil Lewis
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.

Although I can and do download many progs OK

Please could you tell me how to correct these errors.

Ubuntu 12.04  2 Gb Ram

**Comment by Rich14** [comment]
Although I can and do download many progs OK

**Comment by Dr-Bean** [comment]
I think you're posting your question at the wrong place? The is an issue tracker for Synology packages, and `Get_iplayer` is currently not a package provided by SynoCommunity (there's PR, but it's not done yet, afaik)

**Comment by Rich14** [comment]
Thank you for your response Dr-Bean.
As I am very new to this site could you kindly point me in the right direction  to get information on Get_iPlayer.

Thank you again
Richard

**Comment by Dr-Bean** [comment]
Googling `get_iplayer` leads me to this page: http://www.infradead.org/get_iplayer/html/get_iplayer.html. Take a look at the "Help / Development" section on that page.
