### ISSUE TITLE
Salt-master login not working

### ISSUE THREAD

**Issue by Martijn085** [SynoCommunity/spksrc#1509]
It seems that salt-master can`t login. It should be useing the synology admin account, but this doesn`t work.

**Comment by Dr-Bean** [comment]
Yep, it doesn't. @Diaoul, I think we're missing `synoauth`...is that a missing file/module that needs to be added to the package?

**Comment by Diaoul** [comment]
The binary synoauth should be at `/usr/syno/bin/synoauth`, is that the case @Martijn085?
You can edit the config file `/usr/local/salt-master/etc/master` and adjust as you which. I put my own username there and it works fine.

**Comment by Martijn085** [comment]
@Diaoul the binary /usr/syno/bin/synoauth is present. When i edit the config file is work fine, thank for the workaround.

**Comment by Dr-Bean** [comment]
Should be good to close then?
