### ISSUE TITLE
[request] Cura SPK

### ISSUE THREAD

**Issue by Decipher** [SynoCommunity/spksrc#1510]
Cura/CuraEngine is a slicing tool used by OctoPrint (#1480); This addition would mean simple 3d printing without the need of a desktop/laptop.

Relevant projects:
- https://github.com/daid/Cura (Python GUI)
- https://github.com/Ultimaker/CuraEngine (C++ engine)

**Comment by Decipher** [comment]
Not 100% sure about the patch, as I had to re-roll some C++11 for loops for C++0x, but it does compile and run on my initial test. Would be grateful for someone to eyeball the patch.

**Comment by Decipher** [comment]
Delved into this a bit more, tried compiling Cura but it has some wheels that wouldn't compile. Ideally I'd like to bypass Cura completely as OctoPrint is moving that way, but you need to use the devel branch of OctoPrint to do that and I was unable to compile the devel branch of OctoPrint as it also had wheels that wouldn't compile :|

**Comment by Diaoul** [comment]
Which wheels?

**Comment by Decipher** [comment]
It seems to be related to Atlast/Scipy/Numpy

* Atlas (http://math-atlas.sourceforge.net/) libraries not found.
* Blas (http://www.netlib.org/blas/) libraries not found.
* Lapack (http://www.netlib.org/lapack/) libraries not found.

And many more errors.

Note that I do have what I believe all the relevant requirements are in requirements.txt, and Atlas is definitely there and run before these errors show up, so I suspect this is a cross-compile related issue where it wants something to exist natively. Would love to proceed further with this one as OctoPrint w/Cura support could be quite nice on Syno.

**Comment by Dr-Bean** [comment]
curaengine 15.04-1 has been published on the repo.
