### ISSUE TITLE
[request] update firefox sync server to 1.5

### ISSUE THREAD

**Issue by sp0di** [SynoCommunity/spksrc#1515]
upgrade current 1.1 sync server to the 1.5 release.  purpose is to support firefox browsers newer than 29.

https://docs.services.mozilla.com/howtos/run-sync-1.5.html

Thanks!

**Comment by Dr-Bean** [comment]
See #567. By the way, it can't be upgraded, 1.5 is backwards incompatible, so it'll be a separate package.
