### ISSUE TITLE
[request] create phpipam 1.1.010 package

### ISSUE THREAD

**Issue by jayhaegele** [SynoCommunity/spksrc#1516]
Not sure if this would work, but it would be the cat's meow if it did.  

phpipam is a nice web frontend to manage ip addresses on a network.  This scales GREAT and very useful for small/mid offices to keep track of ip addresses.  

http://phpipam.net/
##

**Comment by piwi82** [comment]
There are PHP extensions missing in DSM like <code>gmp</code> and <code>pcntl</code>.
Have you tried to install it on your NAS by following http://phpipam.net/documents/installation/ ?
