### ISSUE TITLE
error 400 on http://packages.synocommunity.com/

### ISSUE THREAD

**Issue by meganerd** [SynoCommunity/spksrc#1517]
Is this the correct place to report issues with the web front end?  If so then when connecting the following error is returned:

Bad Request
The browser (or proxy) sent a request that this server could not understand.

**Comment by Dr-Bean** [comment]
http://packages.synocommunity.com is for your NAS. Use https://synocommunity.com in your browser.

**Comment by meganerd** [comment]
I should have been more specific, the NAS was failing to update so I checked the URL with a browser.  This was ongoing for several days.  It now seems to be working again.  Next time I will capture NAS request via tcpdump and provide more meaningful detail.

Is it possible to host our own mirror internally (something like apt-mirror)?

**Comment by Dr-Bean** [comment]
Not a mirror as such, because that functionality simply does not exist, but you can compile your own packages (see the readme), and run a local package server (spkrepo, sspks).
