### ISSUE TITLE
-ash python3 : not found

### ISSUE THREAD

**Issue by refactoredjello** [SynoCommunity/spksrc#1518]
After installing python3 synocmmunity package I can't run it. I've tried the commands python3.4, python3. But neither work. When I run those commands from the installation directory I still get the same error message -ash python3 : not found. I've tried to run this in usr/bin as well. 

I have the official python2 package installed(pythonModule) and previously had the original python3 package installed. I uninstalled the official python3 package before installing the community version. 

I'm running a DS213j with DSM 5.1-5022 Update 2.

**Comment by Dr-Bean** [comment]
` /usr/local/python3/bin/python3` is the command you should use.

**Comment by refactoredjello** [comment]
Thank you dr. I feel like an idiot.

**Comment by Dr-Bean** [comment]
We all have moments like that, don't worry ;)
