### ISSUE TITLE
http://packages.synocommunity.com/ Not Available

### ISSUE THREAD

**Issue by hideadesign** [SynoCommunity/spksrc#1519]
Hi

The repo is not available, when add the repo in DSM it says invalid location

whne i try to ping http://packages.synocommunity.com/ it says "unknown host"

Any idea ?

**Comment by piwi82** [comment]
https://github.com/SynoCommunity/spksrc/issues/1452#issuecomment-76514992

**Comment by hideadesign** [comment]
Indeed it worked, thank !
