### ISSUE TITLE
SPK for Gogs possible?

### ISSUE THREAD

**Issue by Snipe3000** [SynoCommunity/spksrc#1522]
Would it be possible to create a SPK for Gogs for install in Diskstation?
http://gogs.io/
##

**Comment by cytec** [comment]
found that toll myself a few days ago...
afaik it only depends on git and mysql/sqlite/pgsql so it should be doable.

sadly i have very limited time atm, so don't know if and when i can take a closer look

**Comment by Snipe3000** [comment]
No problem, please let me know if you ever get around to looking at it.

**Comment by Decipher** [comment]
It requires [Go](http://golang.org/), so until there is a SPK for that, I can't imagine this would be possible.

**Comment by cytec** [comment]
I've made a native golang package to make cross compiling go code easier. You don't need to have go installed on your DS, it's just needed for compiling the code :)

as far as i can tell from the website, it only depends on git (for which a spk is present already) and MySQL/PostgreSQL/SQLite (sqlite has also a makefile) so it _should_ run i think... still have a lot of stuff around and was not really able to take a closer look :(

**Comment by cytec** [comment]
@Decipher @Snipe3000 good news! had some time to dive into it. I got it working on my DS1513+ (cedarview) i haven't tried any other platforms yet nor did i managed to create a SPK makefile for automation (due to lack of time sadly) but it compiles and after being copied to my DS it runs and installs :) 

So it's only a matter of time till there will be a SPK ready

**Comment by Decipher** [comment]
I also tried to ge t it running myself last night, and also managed to compile a binary that partially ran on my XPEnology, but I did encounter a few issues. I also found that Golang doesn't currently support PPC which my physical NAS is, so it's somewhat less priority for me at the moment... With that said though, if you @cytec commit your work is be happy to help finish it (time permitting).

**Comment by Snipe3000** [comment]
Awesome, sounds like its coming along nicely.

**Comment by cytec** [comment]
@Decipher i've just pushed what i have done so far: https://github.com/cytec/spksrc/commit/b9e21e271b4f2f7cef6caed7b546046e19758b2b

NOTE: i use the `bin/custom/conf` directory for the configuration file due to debugging and testing purpose... in the final SPK this should be moved to the `var` folder to preserve it througout SPK updates. there is a ENV variable called `GOGS_CONFIG` to provide a custom config path, see: https://github.com/gogits/gogs/issues/145

**Comment by Decipher** [comment]
Cheers, will try to take a look at it this evening.

**Comment by cytec** [comment]
finally got some time to make some progress on this one... but sadly i currently don't have access to my Synology so all of those packages are UNTESTED

@Snipe3000 can you test? 
http://cytec.us/syno/test-spk/gogs/

**Comment by mbirth** [comment]
FYI: The new DSM will bring Docker support and with that it's as easy as installing [codeskyblue/docker-gogs](https://registry.hub.docker.com/u/codeskyblue/docker-gogs/) to install a working Gogs.

**Comment by Diaoul** [comment]
The new DSM will bring Docker *for the NASes that support it* and the list is short ATM (x86/amd64 only)

**Comment by cytec** [comment]
i'm aware of that but like @Diaoul said, docker supports only for x64 arches atm...

**Comment by Decipher** [comment]
@cytec I tried installing the Bromolow package on my XPEnology VM, but no luck; **Failed to run the package service.**

**Comment by MarvinMenzerath** [comment]
@cytec I tried installing your `gogs_armada375-5.1_0.6.1-1.spk`-package on my Synology DS215j but the service did not start: `Der Paketdienst konnte nicht ausgeführt werden.` / `Failed to run the package service.` Also no log files were created.

**Comment by cytec** [comment]
@MarvinMenzerath yup currently there is no `start-stop-status` file.. just the binaries for testing manual execution through terminal... working on that but don't know when i have the time to finish this...

**Comment by sardigital** [comment]
@cytec All working fine! please build start-stop service ^_^

**Comment by nurtext** [comment]
I wouldn't recommend using Gogs in the current situation. There's a lot of chattering going on in their repo, as their main developer is currently studying in the US and another dev seem to be willing to overtake the project using his fork called "Gitea".

See:
https://github.com/gogits/gogs/issues/1304

**Comment by tboerger** [comment]
> I wouldn't recommend using Gogs in the current situation. There's a lot of chattering going on in their repo, as their main developer is currently studying in the US and another dev seem to be willing to overtake the project using his fork called "Gitea".
> 
> See:
> gogits/gogs#1304

Something like that... The maintainer of gogs rejects to accept more people with write access and accepts only rarely contributions. So 2 other peaople of this organization started the fork Gitea which will get more contributions and already have a lower bus factor. Hopefully we will get a first release out of the door pretty soon, including pull requests and wikis... I think after the vacation time :)

**Comment by tboerger** [comment]
Gogs is alive again and it makes sense to build this package ;)

**Comment by Solido** [comment]
+1 on this feature, it's a mess to setup git on a synology.
Providing a SPK can make it widely use as maybe the de facto solution.

**Comment by devjan** [comment]
+1 Would be great to hear some good news on this

**Comment by clemorphy** [comment]
+1 I would love to be able to install Gogs easily on a DS215j and a DS214+

**Comment by BenoitFreslon** [comment]
+1. Hit @clemorphy  :)

**Comment by strahlc** [comment]
+1 for Supporting DS212+

**Comment by tdehaeze** [comment]
+1 :)

**Comment by micharuss** [comment]
+1

**Comment by rkubik** [comment]
+1

**Comment by mageo** [comment]
+1

**Comment by jackjackk** [comment]
+1

**Comment by jackjackk** [comment]
Any update on the issue? It would be a great addition.

**Comment by sardigital** [comment]
use gogs on docker

**Comment by jmeischner** [comment]
Unfortunately this is not possible for all DiskStations I Think?

**Comment by burgerga** [comment]
@sardigital docker is only available for Diskstations with Intel CPUs

**Comment by cytec** [comment]
theoretically the SPK i've started on working a while ago should be a good starting point to pick up... most stuff should still work the same but i think we need some kind of `WIIZARD_UI` files to provide some basic install options like choosing where the repos should be stored and which Database type one would prefer.

The SPK i've started on working had those hardcoded to sqlite and a fixed repo path inside the SPK's var Folder which may produce a really long update time once there are a few repos... also there still is an open issue about DSM 6 user creation here: https://github.com/SynoCommunity/spksrc/issues/2216 so i don't know if it makes sense to pick up work on this before the DSM 6 thing is fixed

**Comment by torrentalle** [comment]
I have published a PR https://github.com/SynoCommunity/spksrc/pull/2533 with Gogs v0.9.97 build from source

**Comment by jmeischner** [comment]
Very Cool, thank you. I hope I will have time to test it during the next days.

**Comment by flipswitchingmonkey** [comment]
Just as an FYI, https://github.com/go-gitea/gitea (Gogs Fork) published their 1.0 as various ARM binaries as well, which run fine on my DS116.

**Comment by meffect** [comment]
does gogs need golang installed or no?

**Comment by cytec** [comment]
@meffect only on the host you use for compiling

**Comment by flipswitchingmonkey** [comment]
The gogs binaries are compiled statically, afaik. So you should not need anything.

**Comment by meffect** [comment]
awesome ty

**Comment by Solido** [comment]
Confirmed to have Gitea working on 214+

**Comment by henjue** [comment]
+1

**Comment by ymartin59** [comment]
For information: https://github.com/flipswitchingmonkey/gitea-spk
See also #3670
