### ISSUE TITLE
Bittorent Sync 2.0 not working (no transfer of files)

### ISSUE THREAD

**Issue by AZimmerhofer** [SynoCommunity/spksrc#1527]
Hello,

I installed qoriq on my 213+ - without problems. But the transfer of files failed. After syncing folders are empty.

See also here: http://forum.bittorrent.com/topic/34404-synology-nas-isnt-working/ or http://forum.bittorrent.com/topic/34438-synology-2-of-3-nas-dont-transfer-files/ 

Similar but QNAP: http://forum.bittorrent.com/topic/34294-sync-20-qnap-package-doesnt-work/

Regards

Alex

**Comment by Dr-Bean** [comment]
We haven't published a 2.x version of btsync, and I don't think we ever will: they seem to be maintaining their own packages now.
So, best thing is to report it on the btsync forums.

**Comment by GunsAkimbo** [comment]
They don't maintain packages for all syno-architectures, namely the qoriq architecture (DS213+ & DS413):
http://forum.bittorrent.com/topic/38132-powerpc-and-powerpc-qoriq-support/
Any chance to change your mind? :)

**Comment by Dr-Bean** [comment]
Even if we did, that's not going to help.
BTSync is not open source. We don't have access to their source code, and we've always had to use their binaries. That's fine if all the needed architectures are available in binary form.

However, the main problem seems to be that the devs don't want to/can't support PPC/Qoriq for whatever reasons.
Consequently, they don't release binaries for that platform, and we can't package what doesn't exist ;)

So, you can stick with their last package for PPC (assuming that's still available), stick with 1.4.111, available on our repo, or ditch BTSync and move to another product.
