### ISSUE TITLE
Invalid location using DSM 4.3

### ISSUE THREAD

**Issue by nlamirault** [SynoCommunity/spksrc#1530]
i try to add syo community with this url : http://packages.synocommunity.com/
I've got this error : Invalid location

**Comment by romu70** [comment]
Same for me with both http://packages.synocommunity.com/ and http://synocommunity.com/packages with both http and https.

**Comment by Dr-Bean** [comment]
Let's use #1538 to track progress. With the changes Diaoul made up, I expect things should be working now.
