### ISSUE TITLE
nzbget crashes during download

### ISSUE THREAD

**Issue by alsdfjldafsjalsfjk** [SynoCommunity/spksrc#1531]
As per this topic: http://nzbget.net/forum/viewtopic.php?f=4&t=1837

hugbug said: "There was a bug causing program crashes during download when article cache is active (it is active by default on Windows). The bug was fixed in r1207 (.....) Nonetheless it's worth updating."

**Comment by alsdfjldafsjalsfjk** [comment]
seems setting writeBuffer to 32 solved this for me, but download speed suffers.. ohwell

**Comment by alsdfjldafsjalsfjk** [comment]
that didnt last very long, crashes are still there

**Comment by Dr-Bean** [comment]
Looking at the [release notes](http://nzbget.net/History_%28ChangeLog%29#nzbget-14.2_-_15_Feb._2015), NZBGet 14.2 seems to fix this. Not sure if there's an open PR for it, otherwise I might take a look over the next couple days.

**Comment by alsdfjldafsjalsfjk** [comment]
Nice, thx!

**Comment by Dr-Bean** [comment]
NZBGet 14.2-15 has been published on the repository
