### ISSUE TITLE
[request] Update owncloud to v8.0.0

### ISSUE THREAD

**Issue by Wookai** [SynoCommunity/spksrc#1532]
A new major version of owncloud was released on Feb 9th 2015, it would be great if you could upgrade the synocommunity package.

**Comment by romu70** [comment]
Indeed you can easily update by yourself. 1. Download the OC8 zip. 2. Shutdown OC from DSM. 3. Erase the content of /web/owncloud on the nas except the data and config folders. 4. Extract the OC8 zip in /web/owncloud (take care of hidden files like .htaccess). 5. Start OC. 6. Connect the OC page, it will warn about the upgrade, proceed, enjoy!

**Comment by mirweb** [comment]
Make a pull request for update to 8.0.2 #1556

**Comment by flitschbirne** [comment]
Hi.

I made the steps described by romu70 and now the only categories I see are files, activities and pictures. Contacts and calendar are missing?!?

**Comment by romu70** [comment]
Yes, Contact and Calendar are installed but not activated by default. And some applications haven't ported to OC8 yet.

**Comment by uwew** [comment]
I tried following the steps romu70 suggested (replace everything in my /web/owncloud directory except data and cofig folders) but I am stuck with the .htaccess error:
".htaccess file has the wrong version. Please upload the correct version. Maybe you forgot to replace it after updating?"

What am I missing here? 

Thanks,

- Uwe

**Comment by flitschbirne** [comment]
Did you also replace the old .htaccess file with the new .htaccess file?

**Comment by romu70** [comment]
Yes, that's probably the issue, take care of showing hidden files in your browser to make the update.

**Comment by Githarp** [comment]
Actually, not always. Followed the instructions to the T. Faced the same issue as @uwew .
Compared both .htaccess files. Couple of changes here and there.
But right at line 1, sat this
> \# Version: 8.0.2

Added this line into retained .htaccess – ownCloud accepted and upgraded.

This was on a *fresh install* of ownCloud.

**Comment by uwew** [comment]
Just wanted to let you know that this time I used wget to get the new version and indeed, it had a .htaccess file - so, folloing your advise worked like a charm. On question though: How can I update my package center info that I am now using version 8.2 of owncloud, rather then 7.03-5 -- just a small thing but I had to ask:)

Again, thank @romu70 and everybody for all your help,

- Uwe

**Comment by Githarp** [comment]
I'm not aware of any method to change the Package Center information but I usually just ignore it. 
In a similar scenario, there was another package I had installed and manually updated through app. The time came when SynoCommunity updated their package and I just safely updated it. Though I had to do some config changes here and there (*nothing Google can't help with*).

**Comment by Dr-Bean** [comment]
Owncloud 8.0.2-6 has been published on the repository

**Comment by flitschbirne** [comment]
Sorry I know it's a closed issue but just FYI to warn anybody:

I had 8.0.2 installed manually like "romu70" suggested above and now I updated again through DMS and it killed my data folder. Running backup now...

**Comment by Dr-Bean** [comment]
Don't put your data folder inside the web folder.

**Comment by flitschbirne** [comment]
Thanks. I thought it had to be this way...
