### ISSUE TITLE
Bitlbee won't start

### ISSUE THREAD

**Issue by GoOz** [SynoCommunity/spksrc#1533]
Hey, 

I just installed Bitlbee (3.2.2-9) on my DS315J (armada370) and when i try to start the service, its status remains stopped.

Nothing appears in the journal, no message what so ever.
I thought it could be an issue about a closed port on my switch conf but it would start anyway, wouldn't it?

**Comment by Dr-Bean** [comment]
Bitlbee actually does start, it just doesn't show it in Package Center.

Seems that DSM5.1 can't handle [`dsmuidir="app"`](https://github.com/SynoCommunity/spksrc/blob/develop/spk/bitlbee/Makefile#L5) in INFO, if the corresponding dir in the package doesn't exist.

Until an update of the package is released, you can remove that line from `/var/packages/bitlbee/INFO`, that should do it.

**Comment by GoOz** [comment]
Indeed, it works that way. Thanks a lot, i wouldn't have find it myself.

**Comment by Dr-Bean** [comment]
Before I forget and for future reference, fixed with 765ca6f04b3417a5b7dce07ba1e93e55eeb4c5eb. So, should be fixed with the next package release (not sure exactly when yet)

**Comment by Dr-Bean** [comment]
As an fyi, Bitlbee 3.2.2-10 has been released on the repository.
