### ISSUE TITLE
"Community" Repository not showing in DSM 5.1-5022 Update 3

### ISSUE THREAD

**Issue by chirogocki** [SynoCommunity/spksrc#1534]
Hi,

According to this issue https://github.com/SynoCommunity/spksrc/issues/948 I experienced the same problem. I'm unable to add syno community package in DSM : "emplacement incorrect" in french.
Could be translate as "unknown location"

**Comment by Dr-Bean** [comment]
See #1538, it should be fixed (or at least underway). I'll close this one, no use in having multiple open issues on the same subject :)
