### ISSUE TITLE
HOw to manage compiling with lpthread

### ISSUE THREAD

**Issue by jfpucheu** [SynoCommunity/spksrc#1536]
Hello, Im trying to compile my package with spksrc, but I have pb to use lptread lib, I didn't found any documentation about this. And is there a solution to use mysql lib too ?

make arch-x86-5.1
...

home/jeff/Dev/spksrc/toolchains/syno-x86-5.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -w -Wall -I/usr/include/mysql -DBIG_JOINS=1  -fno-strict-aliasing   -g -I/home/jeff/Dev/spksrc/cross/mydombox/work-x86-5.1/install//usr/local/include   -L/home/jeff/Dev/spksrc/cross/mydombox/work-x86-5.1/install//usr/local/lib -Wl,--rpath-link,/home/jeff/Dev/spksrc/cross/mydombox/work-x86-5.1/install//usr/local/lib -Wl,--rpath,/usr/local/lib  -o mydombox mydombox-mydombox.o mydombox-mdb_config_reader.o mydombox-mdb_soapserver.o mydombox-mdb_tools.o mydombox-mdb_rfxtrx433.o mydombox-mdb_thermostat.o mydombox-mdb_decode_messages.o mydombox-mdb_encode_messages.o mydombox-mdb_log.o mydombox-mdb_mysql.o mydombox-mdb_dvn.o mydombox-mdb_rpidom.o -L/usr/lib/i386-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl -lpthread lib/gsoap/stdsoap2.c lib/gsoap/soapC.c lib/gsoap/soapServer.c -lcurl 

/home/jeff/Dev/spksrc/toolchains/syno-x86-5.1/work/x86_64-pc-linux-gnu/bin/../lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/libmysqlclient.so when searching for -lmysqlclient
/home/jeff/Dev/spksrc/toolchains/syno-x86-5.1/work/x86_64-pc-linux-gnu/bin/../lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/libmysqlclient.a when searching for -lmysqlclient
/home/jeff/Dev/spksrc/toolchains/syno-x86-5.1/work/x86_64-pc-linux-gnu/bin/../lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lmysqlclient
/home/jeff/Dev/spksrc/toolchains/syno-x86-5.1/work/x86_64-pc-linux-gnu/bin/../lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/libpthread.so when searching for -lpthread
/home/jeff/Dev/spksrc/toolchains/syno-x86-5.1/work/x86_64-pc-linux-gnu/bin/../lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/i386-linux-gnu/libpthread.a when searching for -lpthread
collect2: error: ld returned 1 exit status
make[2]: *** [mydombox] Erreur 1
make[2]: quittant le répertoire « /home/jeff/Dev/spksrc/cross/mydombox/work-x86-5.1/mydombox-0.5.0-dev/src »
make[1]: *** [all-recursive] Erreur 1
make[1]: quittant le répertoire « /home/jeff/Dev/spksrc/cross/mydombox/work-x86-5.1/mydombox-0.5.0-dev »
make: *** [compile_target] Erreur 2

MakeFile:

PKG_NAME = mydombox
PKG_VERS = 0.5.0-dev
PKG_EXT = zip
PKG_DIST_SITE = http://192.168.64.15/mydombox-mobile/
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = native/glib cross/openssl cross/curl

HOMEPAGE = http://www.mydombox.com
COMMENT  = Home Automation
LICENSE  =

GNU_CONFIGURE = 1
CONFIGURE_ARGS = cross_compiling=yes

include ../../mk/spksrc.cross-cc.mk

**Comment by Diaoul** [comment]
If you want additional libs you need to compile them too. spksrc currently does not support building with built-in libraries on the NAS.
