### ISSUE TITLE
CozyCloud [Request]

### ISSUE THREAD

**Issue by Nonobis** [SynoCommunity/spksrc#1537]
Hi,

i don't know if this apps could be packaged ... but it could be really great on a nas :) better than owncloud for me !

https://cozy.io/en/

their git page : => https://github.com/cozy/cozy-setup

Could one of the great packager tell me if this could be possible ?

thx by advance.
##

**Comment by romu70** [comment]
+1

**Comment by Nonobis** [comment]
hum, i have installed 5.2. Docker seem great ... and i saw cozycloud docker file, i will try it if i got time ...

**Comment by romu70** [comment]
Problem is Cozy images on the Docker public hub are far from being up to date. Think we have to create Docker files from fresh elements.

**Comment by romu70** [comment]
Join and participate to the discussion on the Cozy forum: https://forum.cozy.io/t/cozy-on-synology-with-docker/387

**Comment by romu70** [comment]
I've successfully installed CozyCloud on my DS1513 + DSM 5.2. Everything runs fine, I used the Docker recipe just provided by Cozy, here: https://github.com/cozy-labs/cozy-docker.

2 last remaining steps for me:
- map the user data folder to the host
- use my own certificate and domain to access CozyCloud from the outside.

I'll post updates as soon as possible.
