### ISSUE TITLE
"Invalid location" whatever DSM version

### ISSUE THREAD

**Issue by romu70** [SynoCommunity/spksrc#1538]
Since few days, the repository is totally out of service. This has been reported with different DSM version:
https://github.com/SynoCommunity/spksrc/issues/1534
https://github.com/SynoCommunity/spksrc/issues/1530

I'm upgraded my DS1513 from DSM 4.3 to DSM 5.1, and same problem.

So whatever the DSM run on our nas, the synocommunity repository is ko.

**Comment by piwi82** [comment]
Make sure synocommunity.com is correctly resolved as IP addresses <code>176.31.184.40</code> and  <code>2001:41d0:52:100::82e</code>.
Force IPv4 (disable IPv6 in DSM) as I think there are some issues with IPv6.

**Comment by Diaoul** [comment]
The repository is up and running but DNS entries are outdated for some unknown reason.

**Comment by Diaoul** [comment]
I temporarily switched the DNS entry, will wait until the change propagates to Google's DNS servers and switch back to the correct entry.
Hopefully this will fix this weird DNS propagation issue.

**Comment by sshaikh** [comment]
Neither 176.31.184.40 or 5.51.3.145 appear to work. Is there an IP address we can use in the meantime?

**Comment by sshaikh** [comment]
I tell a lie - it took a refresh in Syno and all is well again. Thanks.

**Comment by romu70** [comment]
Also works for me. Thanks to the team.

**Comment by guryushika** [comment]
Hi, I didn't understand what resolved the issue.
I have a similar issue, "invalid location" on my DS413 DSM5.1u3 only and no problem adding synocommunity to my DS414 DSM5.1u3.
I can add any other repository on my DS413 except for Synocommunity (wich is actually the only repository I use, others were added only to try).

I've already restarted, I've already checked the /usr/syno/etc/packages/feeds for errors, I deleted to try to re-add and then "invalid location" so I added it manually by editing the file and it showed up in the list but no packages even after a lot of refreshes only for synocommunity :cry: 

It was working fine on my DS413, I'm using BTSync a lot, but as it will limit the number of directories to 10 as for version 2.0, I'm switching to SyncThing (thank a lot for adding it btw! :+1: ). No problem installing SyncThing on my DS414 of course.

So I updated my DS414 to 5.2 and no problem adding synocommunity repo, deleting it and re-adding it…etc
Shall I try 5.2 on my DS413 ? Shall I wait a few days ? If it was a DNS issue I shouldn't be able to add it at all on all the NASes, right ? Is DS413 not supported anymore ?
Thanks and keep up the good work :smile:

**Comment by romu70** [comment]
That's really annoying when it's happen, sorry for you.

I don't know if there is a way to flush the dns cache from the nas, but that's what I would try.

**Comment by guryushika** [comment]
Thanks I'll search in that direction. Also I forgot to mention that my NASes are not on the same internet connection. DS413 is remote (but not far). Shall I try to move physically the DS413 and try on another connection ? or would you assume it's an issue related to the DS413 itself ?

**Comment by guryushika** [comment]
Ah and last thing, I've noticed that my DS414 has a certificat for SynoCommunity and my DS413 doesn't, could it be related ?

**Comment by romu70** [comment]
No related to certificate for sure, but to DNS, so the network used is critical. That explains why one can reach synocommunity and the other can't. Move it if you can, flush the dns cache and it should work.

**Comment by Dr-Bean** [comment]
Change the DNS servers that your device uses, see https://github.com/SynoCommunity/spksrc/issues/1476#issuecomment-73540178.

**Comment by romu70** [comment]
Yes, that's even a better solution. Set the google dns server: 8.8.8.8.

**Comment by guryushika** [comment]
OMG I've just learnt my lesson ! Whaoooo that's so simple…
So I didn't reboot my router, because people are using it right now, so I told myself alright let's try to put the Google DNS…worked instantly !
Thanks to all of us for your answers and time. Thanks to SynoCommunity for your awesome and constant work. It's so good to be able to install softwares with so much ease.

**Comment by guryushika** [comment]
hahaha now that it's working I just realized that there is no SyncThing package for the DS413 and its ppc :laughing:

**Comment by Diaoul** [comment]
I changed the DNS servers to trigger a cache refresh but it doesn't seem to have any effect. I really don't know what's going on, maybe a DNS caching issue specifically for the Package Center in DSM ?

If someone affected with the problem with more knowledge can troubleshoot this it would be really helpful.

**Comment by Dr-Bean** [comment]
@Diaoul If anything, I'd try switching the `packages` record to an A-type instead of a CNAME, to force refetching specifically that record. Or maybe you tried that already?

As for the DNS caching in Package Center, then I don't think e.g. Guryushika above wouldn't see an immediate effect by switching to a different DNS server. Otoh, I don't have a better explanation at hand either...

**Comment by Diaoul** [comment]
No I didn't try that, just change the A record to a different IP on synocommunity.com. I'll give it a shot.

**Comment by nlamirault** [comment]
Thanks. It works now. I just add the Google DNS.

**Comment by Diaoul** [comment]
So I did just as @Dr-Bean suggested and switched from CNAME to A record. Also I set default timeout to 60. Let me know if there are any improvements.

**Comment by guryushika** [comment]
Tried, 2 hours ago, the default DNS, not working. Back de Google DNS :)

**Comment by Diaoul** [comment]
*sight*

**Comment by Dr-Bean** [comment]
Well, it's possible the record hasn't expired yet (the timeout was set to 24h before, right?), so wait just a bit longer ;) 

First one is OVH's ns100, which is what I'd expect. Second and third are Google's and OpenDNS'  servers, which seem to be using the old CNAME record. Point is, if Google and OpenDNS are still using the old CNAME, then it wouldn't be surprising that other DNS servers haven't refetched the record yet.
```
NAS> nslookup packages.synocommunity.com 213.251.128.144
Server:    213.251.128.144
Address 1: 213.251.128.144
Name:      packages.synocommunity.com
Address 1: 176.31.184.40

NAS> nslookup packages.synocommunity.com 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com
Name:      packages.synocommunity.com
Address 1: 176.31.184.40 synocommunity.com

NAS> nslookup packages.synocommunity.com 208.67.222.222
Server:    208.67.222.222
Address 1: 208.67.222.222 resolver1.opendns.com
Name:      packages.synocommunity.com
Address 1: 176.31.184.40 synocommunity.com
```

**Comment by Dr-Bean** [comment]
The output from Synology's `nslookup` command as in my previous comment shows a different result then it should apparently, so it's not a good indicator.
Anyway, testing on a normal Debian setup with `-type=a` shows that Google, OpenDNS, as well as my own provider are correctly resolving the new record.
So, that's an indication that the record is being expired and refetched correctly.

**Comment by Dr-Bean** [comment]
It's been quiet in here ;) That could mean it's solved, or everyone with the issue switched over to manually entering a DNS server. Anyone willing to test perhaps? Otherwise we'll close the issue.

**Comment by romu70** [comment]
To me, it's fixed. I've just switched back my provider DNS, and synocommunity.com is correctly resolved.

**Comment by guryushika** [comment]
Just tried it back with default DNS: it's working !!! ;)
