### ISSUE TITLE
Midnight Commander and Z shell cannot be started on DS414

### ISSUE THREAD

**Issue by mstockled** [SynoCommunity/spksrc#1540]
I've installed both Midnight Commander 4.8.10-2 and Z shell 5.0.7-2 on my DS414, which runs the latest DSM 5.1-5022 Update 3 on a MARVELL Armada XP MV78230.

Package Center reports that both have been successfully installed and I can see both listed under the Installed tab. Both show status "Stopped".

If I select either of them, the only available entry under Action is "Uninstall" - there is no "Run".

Did I do something wrong (problem in front of screen)?

Thanks,
Martin.

**Comment by Dr-Bean** [comment]
Both packages are command-line based packages (MC mentions console-based in the description, same thing). There's no service to start, hence no reason to have a `Run` command in Package Center.

To use the packages, log in via SSH and run `/usr/local/mc/bin/mc` for Midnight Commander, or `/usr/local/zsh/bin/zsh` for Z-Shell.
