### ISSUE TITLE
[Nzbget 14.1-14] Split of a few scripts from nzbToMedia to another repository

### ISSUE THREAD

**Issue by typhoe** [SynoCommunity/spksrc#1541]
Hi,

a few post-processing scripts have been remove in the last update of nzbToMedia (v10.8 in the actual spk Nzbget 14.1-14).

From the changelog ( https://github.com/clinton-hall/nzbToMedia/blob/master/changelog.txt ):
V10.8 15/12/2014
Removed "stand alone" scripts DeleteSamples and ResetDateTimes. 
These are now in https://github.com/clinton-hall/GetScripts

More on that subject in a post from the author:
http://nzbget.net/forum/viewtopic.php?f=8&t=1634

To add them back on the actual installation of Nzbget, you can input from the command line (this supposes you have the git spk already installed):
su - nzbget -c "/usr/local/git/bin/git clone git://github.com/clinton-hall/GetScripts.git /usr/local/nzbget/share/nzbget/scripts/GetScripts"
And reload nzbget configuration.

Can you add these scripts back in the nzbget spk?
Thank you!

**Comment by Diaoul** [comment]
What's the problem with using non-standalone scripts?

**Comment by typhoe** [comment]
None at all.

It's just that these scripts were previously included in the nzbget package and aren't anymore...

I searched a little bit myself why my previous configuration was not working anymore before realizing that the scripts were no more in the spk.

So if the nzbToMedia scripts are included in the nzbget spk, I just ask if it's possible to also add the GetScripts one also (to re-add the previously removed scripts).

Thank you.

**Comment by Diaoul** [comment]
OK so just to be clear there is no feature-loss due to this upgrade right? One just has to adapt to the new way to do it, correct?

**Comment by typhoe** [comment]
Well, I'm not sur I'm perfectly clear, so I'll try to explain.

In previous versions of the Nzbget spk ( < v14) from Synocommunity, the version of the nzbToMedia scripts included at least two scripts named DeleSamples (use to delete *-sample.* files) and ResetDateTimes (use to set files creation time like the release date of the media ex: movie from 2007 would have file creation time set to 2007).

In the last version, these two scripts are not included anymore. So Nzbget will not delete *-sample.* files anymore for exemple and Kodi by default will not ignore theses files. In result, it add a movie twice (once for <movie>.mkv and a second time for <movie>-sample.mkv).

So, for my part, I think that it's a loss of feature... and even if it's possible to add these scripts again like I did, I think it would be easier to have them included directly in the Nzbget spk.

**Comment by Dr-Bean** [comment]
Are you using a device with an Avoton, Alpine or Armada375 arch? The other arches should still contain the scripts, because the packages were created before the split happened.

**Comment by typhoe** [comment]
Hi Dr-Bean,

yes indeed a new Avoton model. I recently changed my old DS411+II. And that's then that I noted the removal of theses scripts.

**Comment by Dr-Bean** [comment]
Ok, let's add that in, similar to the current nzbtoMedia approach then. We needed to update both NZBGet packages anyway, so I'll prepare those changes.

**Comment by typhoe** [comment]
Perfect,

thank you very much!

**Comment by Dr-Bean** [comment]
Fixed in NZBGet with 486a575117915b3751eabb15d360ec8ecd314c78. Note: packages are not yet released, will happen when I get to it, need to sort the issue below first.

@Diaoul `busybox 1.23.1` seems to have an issue with creating users via the installer script for some reason. Reverting to `1.22.1` restores the functionality. It doesn't look like a local issue on my side, but maybe you can confirm the behavior?

**Comment by Dr-Bean** [comment]
@Diaoul To fix the adduser issue, we should add `CONFIG_LAST_ID=999` in `cross/busybox/configs/usrmng` (or you can put it in spksrc_defconfig, but the above mimics the `CONFIG_LAST_SYSTEM_ID` behavior). I'll push it later.

**Comment by Diaoul** [comment]
Thanks @Dr-Bean for investigating this. So if I understand correctly the config option has been renamed right?

**Comment by Dr-Bean** [comment]
It's apparently a new option, next to `CONFIG_LAST_SYSTEM_ID` (although I haven't looked into the functional differences: as long as it works...;)).
Here's a link to the mailing list where I got it from: http://lists.busybox.net/pipermail/busybox-cvs/2014-January/034370.html

**Comment by Dr-Bean** [comment]
NZBGet 14.2-15 has been published on the repository.
