### ISSUE TITLE
Beta 5.2

### ISSUE THREAD

**Issue by willuk2010** [SynoCommunity/spksrc#1551]
Quick question, is it safe to update to beta 5.2?

Will it break my installed SynoCommunity packages?

Cheers,

**Comment by Dr-Bean** [comment]
At your own risk: it's a beta after all. 
However, as far as I know, there's no major changes that would cause issues, and some people have already reported that things are running smoothly.

**Comment by willuk2010** [comment]
Cheers Dr-Bean!

ill give it a go :)

**Comment by Decipher** [comment]
I moved to Beta 5.2 yesterday and haven't encountered any issues yet. I have encountered disappointment though as my NAS doesn't have the hardware requirements for the Docker support :|

**Comment by nong-fa** [comment]
Like

**Comment by piwi82** [comment]
@Decipher : Maybe we could build Docker for missing architectures ?

https://github.com/docker/docker

**Comment by Nonobis** [comment]
@Piwi : if it can help, i have tested deluge with docker, it's working
perfectly on my ds1812+.

2015-03-16 10:04 GMT+01:00 Piwi <notifications@github.com>:

> @Decipher <https://github.com/Decipher> : Maybe we could build Docker for
> missing architectures ?
>
> https://github.com/docker/docker
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SynoCommunity/spksrc/issues/1551#issuecomment-81516872>
> .
>



-- 
Cordialement / Kind regards,
Arnaud Dartois.

[image: Image]

Email    : nonobis@gmail.com
Website: http://www.itoo.me

**Comment by Dr-Bean** [comment]
Seeing as we haven't seen any real issues related to 5.2 beta: Thanks Synology! ;)
Let's wait for the final to come out, see if our luck continues...In the meantime, I'll close this one.
