### ISSUE TITLE
Umurmur Configured on Synology but Mumble Can't Connect

### ISSUE THREAD

**Issue by thommerlin** [SynoCommunity/spksrc#1571]
I need help trying to figure out what I have done wrong. I have configured the Umurmur Config appropriately to what I have followed by other setup guides and google. The server starts and runs with the configuration. But when I try to connect to my Umurmur/Mumble I get connection error "Server Connection failed: Connection refused"

**Comment by Diaoul** [comment]
I can't reproduce this. I installed uMurmur and could connect my server without any change to the configuration.
I suggest you check your firewall setup to open the appropriate ports.
