### ISSUE TITLE
GateOne installation on Synology

### ISSUE THREAD

**Issue by fume711** [SynoCommunity/spksrc#1573]
On Synology DSM 5.1-5022, DS1513+, trying to install GateOne from SynoCommunity. I installed SynoCommunity's Python 2.7.9-12 and that successfully installed. Than installed GateOne 1.1-4 and that successfully installed, BUT it doesn't run. When I click "Run", it just tries to load, than goes back to "stopped". Anyone else having issues getting GateOne running?

Thanks!

**Comment by Dr-Bean** [comment]
Right. We need to release a new version of the packages that used pybundles until recently, because Python 2.7.9-12 dropped support for pybundles. Fyi, @Diaoul, I believe I mentioned something along those lines somewhere.

**Comment by fume711** [comment]
Ah, thanks. Thought I was the only one having this issue since I couldn't find another thread on it. Thanks for the help! There's Python 3.4.1-3 availabl on the SynoCommunity but GateOne doesn't recognize it, and others have posted that you need to use the Python 2.7.9-12 version to get GateOne to download and install.

**Comment by Dr-Bean** [comment]
The current version of GateOne works with a SynoCommunity Python between 2.7.7-3 and 2.7.8-11, but you're not able to get those from our repository with the new Python package released.
You can expect an updated package of the GateOne package in the next couple days, that should fix things.

**Comment by fume711** [comment]
Ah thanks for the additional details.

**Comment by Diaoul** [comment]
Hmm, sorry about that. I think there's a PR for GateOne anyway right?

**Comment by Dr-Bean** [comment]
Ah, that's where I mentioned the pybundle comment too. Haven't tested the updated package, but I assume publishing a package with the current state should do it. 
We should set `SPK_DEPENDS = "python>=2.7.8-10` for all those packages to be sure we cover all angles though.

**Comment by Oxize** [comment]
Any release yet? I need some SSH emulator through synology, but gateone is the only one which is still active, but not working yet on Syno. Hope you guys can make a fix soon please.

**Comment by Dr-Bean** [comment]
GateOne 20150311-5 has been published on the repository.

**Comment by Oxize** [comment]
True, but still not working...

**Comment by PiterEL** [comment]
I have installed GateOne on my DS713+ and it some days ago works ok. But not when i try open the page not show. Please help me.
