### ISSUE TITLE
DevOps

### ISSUE THREAD

**Issue by Diaoul** [SynoCommunity/spksrc#1574]
I'm looking for someone willing to invest some time in devops stuff and monitoring.
The goal is to have spkrepo "Dockerized" in a clean way (with links and such) and an easy deployment solution with CM (Salt) and monitoring (Kibana).

If anyone is willing to help please let me know :) That includes you too @SynoCommunity/developers  ;)
##

**Comment by evaryont** [comment]
I'm a new to the project, but have used Salt and the ELK stack extensively before. I'd be happy to help, if you'd accept it. Where would someone start?

**Comment by Safihre** [comment]
Closing due to age (unfortunately).. Also part of #2991 a bit.
