### ISSUE TITLE
SABnzbd cannot be started after update: /scripts/ folder is empty

### ISSUE THREAD

**Issue by Marcoevich** [SynoCommunity/spksrc#1578]
After updating SABnzbd from 0.7.18-10 to 0.7.20-13 I cannot run SABnzbd anymore.

The reason for this is, I believe, the fact that this folder is now empty: /var/packages/sabnzbd/scripts/

For the previous version this is where the startstop-status file and nummerous others where located. 

I have removed the package entirely and reinstalled it, but that didn't help.

Any suggestions?

Thanks!

**Comment by Dr-Bean** [comment]
Well, the current package was created around the beginning of the year, so I can't really see a relationship there. 
It seems very unlikely that you're the first person to discover that a package is broken after almost three months, which leads me to believe it's a local issue on your device.

Can you at least provide some info, such as device model or DSM version? Can you provide the content in `/usr/local/sabnzbd`, `/volumeX/@appstore` (where X is the volume your `@appstore` is located) and `/var/packages/sabnzbd` (use `ll /usr/local/sabnzbd` and so on via Putty or another terminal program)

**Comment by Marcoevich** [comment]
Yes ofcourse. I have a DS214Play, with DSM 5.1-5022 Update 4.

/user/local/sabnzbd/: no such file or directory. (the folder is there, it's a link to /volume1/@appstore/sabnzbd/ The contents of that folder are as follows:

drwxr-xr-x    7 sabnzbd  root          4096 Mar 22 14:53 .
drwxrwxrwx   26 root     root          4096 Mar 22 14:53 ..
drwxr-xr-x    3 sabnzbd  root          4096 Dec 31 15:46 app
drwxr-xr-x    2 sabnzbd  root          4096 Mar 22 14:54 bin
drwxr-xr-x    5 sabnzbd  root          4096 Mar 22 14:54 env
drwxr-xr-x    4 sabnzbd  root          4096 Dec 31 15:46 share
drwxr-sr-x    4 sabnzbd  root          4096 Mar 22 14:54 var

/volume1/@appstore/:

drwxrwxrwx   26 root     root          4096 Mar 22 14:53 .
drwxr-xr-x   22 root     root          4096 Mar 22 16:06 ..
drwxrwxrwx   10 root     root          4096 Mar 13 07:05 AntiVirus
drwxrwxrwx   13 root     root          4096 Dec 16 16:02 AudioStation
drwxrwxrwx   10 root     root          4096 Dec 16 16:02 CloudStation
drwxrwxrwx   12 root     root          4096 Dec 26 02:08 DownloadStation
drwxrwxrwx    8 root     root          4096 Mar 13 07:04 Git
drwxrwxrwx    4 root     root          4096 Nov 19 15:47 Init_3rdparty
drwxrwxrwx    7 root     root          4096 Mar 22 14:45 MariaDB
drwxrwxrwx   12 root     root          4096 Nov  8 06:43 MediaServer
drwxrwxrwx    5 root     root          4096 Mar 13 07:04 MediaWiki
drwxrwxrwx   10 root     root          4096 Jan 23 10:23 PhotoStation
drwxrwxrwx    6 root     root          4096 Mar 22 14:44 SVN
drwxrwxrwx   12 root     root          4096 Feb 25 18:37 VideoStation
drwxrwxrwx    5 apps     users         4096 Jun 11  2014 couchpotatoserver-custom
drwxr-xr-x    4 root     root          4096 Nov 19 15:50 cronjobeditor
drwxr-xr-x    7 root     root          4096 Jan 10  2014 git
drwxrwxrwx    6 apps     users         4096 Jun 11  2014 headphones
drwxrwxrwx    6 maraschi root          4096 Mar  7 14:47 maraschino
drwxrwxrwx    8 apps     users         4096 Apr 22  2014 nzbget
drwxrwxrwx    4 root     root          4096 Dec 16 16:02 phpMyAdmin
drwxrwxrwx    7 root     root          4096 Jun 11  2014 python
drwxr-xr-x    7 sabnzbd  root          4096 Mar 22 14:53 sabnzbd
drwxrwxrwx    6 apps     users         4096 Jun 11  2014 sickbeard
drwxr-xr-x   13 root     root          4096 May  9  2014 spotweb
drwxrwxrwx    7 sublimin root          4096 Jun  2  2014 subliminal

/volume1/@appstore/sabnzbd/:


drwxr-xr-x    4 root     root          4096 Mar 22 14:54 .
drwxr-xr-x   25 root     root          4096 Mar 22 14:53 ..
-rw-r--r--    1 root     root         16080 Mar 22 14:53 INFO
drwxr-xr-x    2 root     root          4096 Dec 31 15:46 WIZARD_UIFILES
lrwxrwxrwx    1 root     root            30 Mar 22 14:53 etc -> /usr/syno/etc/packages/sabnzbd
drwxr-xr-x    2 root     root          4096 Dec 31 15:46 scripts
lrwxrwxrwx    1 root     root            26 Mar 22 14:53 target -> /volume1/@appstore/sabnzbd

**Comment by Marcoevich** [comment]
I have updated above comment, for if you read via email.

**Comment by Dr-Bean** [comment]
Looks okay from here (in the last set of your output: I assume you meant to say `/var/packages/sabnzbd/` as the header, not `/volume1/@appstore/sabnzbd/`, otherwise it wouldn't make sense).
 
The package for your model looks fine, and I've retried it with the same package, only for my arch: no issue. 
You're positive that there's no content in `/var/packages/sabnzbd/scripts`, e.g. doing a `/var/packages/sabnzbd/scripts/start-stop-status start` as root actually states `:not found`? If so, no idea what caused it, and it doesn't look package related.

Maybe the logs prove to be helpful, who knows ;) Anyway, check `/var/log/messages` and `/var/log/synopkg.log`.

**Comment by Marcoevich** [comment]
It does not say :not found. Instead I get this:

DiskStation> /var/packages/sabnzbd/scripts/start-stop-status start
Starting SABnzbd ...
DiskStation>

But the package doesn't actually start.. Still has status stopped.

DiskStation> /var/log/messages
-ash: /var/log/messages: Permission denied
DiskStation>

DiskStation> /var/log/synopkg.log
-ash: /var/log/synopkg.log: Permission denied
DiskStation>

**Comment by Diaoul** [comment]
Lot as root, not admin

**Comment by Marcoevich** [comment]
I am logged in as root

**Comment by Marcoevich** [comment]
http://piclair.com/data/yppjs.jpg

**Comment by Diaoul** [comment]
If you want to see the file add `cat` or `tail` before the file path.

**Comment by Marcoevich** [comment]
This is basically all there is about SAB in the logs:

2015/03/22 14:48:28     upgrade sabnzbd: Uninstall 0.7.18-10 successfully
2015/03/22 14:48:42     upgrade sabnzbd 0.7.20-13: run postinst  ret=[0]
2015/03/22 14:48:42     sabnzbd stderr: adduser: user 'sabnzbd' in use

2015/03/22 14:48:42     upgrade sabnzbd from 0.7.18-10 to 0.7.20-13 successfully
2015/03/22 14:49:02     start sabnzbd: begin to start version 0.7.20-13
2015/03/22 14:49:05     stop sabnzbd: begin to stop version 0.7.20-13
2015/03/22 14:49:05     stop sabnzbd: stop version 0.7.20-13 successfully, result 0
2015/03/22 14:49:05     start sabnzbd: start version 0.7.20-13 failed, result 263
2015/03/22 14:49:10     start sabnzbd: begin to start version 0.7.20-13
2015/03/22 14:49:11     stop sabnzbd: begin to stop version 0.7.20-13
2015/03/22 14:49:11     stop sabnzbd: stop version 0.7.20-13 successfully, result 0
2015/03/22 14:49:11     start sabnzbd: start version 0.7.20-13 failed, result 263
2015/03/22 14:50:42     uninstall sabnzbd: Uninstall 0.7.20-13 successfully
2015/03/22 14:53:51     install sabnzbd 0.7.20-13: run preinst  ret=[0]
2015/03/22 14:53:51     sabnzbd stderr: sh: Downloads/: unknown operand

2015/03/22 14:54:02     install sabnzbd 0.7.20-13: run postinst  ret=[0]
2015/03/22 14:54:02     sabnzbd stderr: chgrp: /volume1/Public/SABNzbd: No such file or directory
chgrp: Downloads/: No such file or directory
chmod: /volume1/Public/SABNzbd: No such file or directory
chmod: Downloads/: No such file or directory

**Comment by Marcoevich** [comment]
Can one of you guys post the contents of your /var/packages/sabnzbd/scripts/ somewhere? I think that I only need that folder, and then It may work again.. The rest of the package seems complete

**Comment by Diaoul** [comment]
From the log files it seems you don't provide the correct file path in the
wizard. Check again with a different path

**Comment by Marcoevich** [comment]
That doesn't seem to make any difference. I even have created the default folder it suggests "volume1/downloads" but that doesn't work.

In the logs I get messages about the preinstall script failing to run:

DiskStation entry.cgi_SYNO.Core.Package.Installation[1].install[21301]: pkginstall.cpp:405 Failed to run preinst script for sabnzbd, [1]

**Comment by Diaoul** [comment]
I think you have a space in your path or some special characters. Please try another path (/volume1/downloads)

**Comment by Marcoevich** [comment]
I have tried that. See comment above

**Comment by Diaoul** [comment]
In your comment you are missing the leading `/` and you don't show the relevant log files

**Comment by Marcoevich** [comment]
Adding the leading `/` didn't make a diff.

Log from `/var/log/messages`:

Mar 27 12:05:51 DiskStation entry.cgi_SYNO.Core.Package.Control[1].start[24108]: pkgstartstop.cpp:182 Failed to start package sabnzbd, [2]

Log from `/var/log/synopkg.log`:

2015/03/27 12:05:11     uninstall sabnzbd: Uninstall 0.7.20-13 successfully
2015/03/27 12:05:47     install sabnzbd 0.7.20-13 successfully
2015/03/27 12:05:48     start sabnzbd: begin to start version 0.7.20-13
2015/03/27 12:05:51     stop sabnzbd: begin to stop version 0.7.20-13
2015/03/27 12:05:51     stop sabnzbd: stop version 0.7.20-13 successfully, result 0
2015/03/27 12:05:51     start sabnzbd: start version 0.7.20-13 failed, result 263
DiskStation>

**Comment by Dr-Bean** [comment]
Can you provide"
- the content of `/usr/local/sabnzbd/var/config.ini` (strip accountnames, passwords and API keys)
- the contents of /usr/local/sabnzbd/logs/sabnzbd.log` and `sabnzbd.error.log` (second one only if there's content in it)
Upload them on pastebin, or gist.github.com, instead of pasting here if you could.
Also, provide the output of `ll /var/packages/sabnzbd/scripts` (while logged in as root).

I'd also second the suggestion of @Diaoul, to create a new shared folder called `downloads`, provide read/write access to the `users` group via the DSM interface, and just follow the Sab installation wizard with that.

**Comment by Dr-Bean** [comment]
Anything to report, @Marcoevich? Otherwise we'll end up closing the issue.

**Comment by Marcoevich** [comment]
Hi Dr-Bean,

Yeah I'm not at home right now but I'll post the details you asked for tomorrow. Sorry to keep you waiting :)

**Comment by Dr-Bean** [comment]
While you're at it, run the following command as well, and provide the output here:
```
su sabnzbd -c "PATH=/usr/local/sabnzbd/bin:/usr/local/sabnzbd/env/bin:/usr/local/python/bin:${PATH} /usr/local/sabnzbd/env/bin/python /usr/local/sabnzbd/share/SABnzbd/SABnzbd.py -f /usr/local/sabnzbd/var/config.ini --pidfile /usr/local/sabnzbd/var/sabnzbd.pid -d"`

**Comment by Marcoevich** [comment]
Thx guys I run NZBget now. I'd give it a try and it worked right out of the box. So this fix is no longer needed :)

**Comment by Dr-Bean** [comment]
Thanks for the info :)
