### ISSUE TITLE
subliminal cannot be ran on DSM 5.1-5022 Update 3

### ISSUE THREAD

**Issue by mbenoit** [SynoCommunity/spksrc#1582]
Hi,
I upgraded DSM on my DS414 to DSM 5.1-5022 Update 3.
I installed subliminal 0.6.4-10 package from SynoCommunity repository.
The installation went fine but I can't run it, when I try I have the following error:
"Failed to run the package service"

Do you what the problem is ?

![capture d ecran 2015-03-22 a 23 03 44](https://cloud.githubusercontent.com/assets/2492402/6771730/c6b7c478-d0e7-11e4-8a88-1ce4bd60abcc.png)

**Comment by Dr-Bean** [comment]
The current Subliminal package isn't compatible with the current Python package: the Subliminal package needs an update. 
Progress is in #1572, but it'll be at least a couple days before I get to finishing that.

**Comment by rockisdead** [comment]
same problem here... with new 2.7.9-13 python update. Subliminal installed but i can't run it.

**Comment by Neejoh** [comment]
Just bought a Synology, installed some awesome SynoCommunity packages but couldn't get this one to work either. (DSM 5.1-5022 Update 4 with Python 2.7.9-13)
Can't wait to get this to work too. So thanks in advance @Dr-Bean

**Comment by jgaraizar** [comment]
Hi! @Dr-Bean do you have any update on this issue? Will there be an update os the subliminal package?  thank you very much in advance for your work on this!!

**Comment by Dr-Bean** [comment]
There will be an update of the package eventually, after I have completed the work started in #1572.

**Comment by R0GGER** [comment]
Still not working... 
![knmblo](https://cloud.githubusercontent.com/assets/8298741/7105563/f930503a-e11f-11e4-81b2-8958b622582f.png)

**Comment by Dr-Bean** [comment]
A beta package of Subliminal 0.7.5-12 has been published on the repository. For people willing to test this version, enable `Yes, I want to see beta versions!` on the beta tab of the Package Center settings.

Note that due to changes in Subliminal, this package is not backwards compatible. You need to uninstall the previous version first.

Please leave feedback in #1561.

**Comment by d3smo** [comment]
Issue of not launching solved with this new beta version

**Comment by Lennartm** [comment]
Having the same problem with DSM 5.2-5565, Python 2.7.10-14. 
Failed to run the package service.

**Comment by Diaoul** [comment]
I'm currently working on subliminal 0.8.0 and I hope I'll be able to release it within a month. Hopefully this version should solve a lot of issues.

**Comment by arminioa** [comment]
Any news on this update.
Thanks

**Comment by bitomule** [comment]
Any update on this? Subliminal doesn't work for me.

**Comment by Lennartm** [comment]
Doesn't work here either. Keeps on loading the 'parameters' window..
Running 0.7.5-12

**Comment by meyerbro** [comment]
Not working here too...

**Comment by cooperdk** [comment]
Not working (still!!!!???)

I even had to post-install a lot of python modules to even make it start. I get a 500 server error in CLI.

**Comment by ymartin59** [comment]
@cooperdk Sorry but it is useless to comment on an issue closed since years. And I guess your DSM is no longer 5.1 version. Please follow #2357 and #3490. By the way there are other tools out there to download subtitles.
