### ISSUE TITLE
sabnzbd : Failed to run the package service

### ISSUE THREAD

**Issue by Hemie143** [SynoCommunity/spksrc#1594]
Hello, 

Here's my setup:
Synology DS112+
DSM 5.1-5022 Update 4
SABnzbd 0.7.20-13
Python 2.7.9-13

Since the upgrade to Python 2.7.9-12, SABnzbd refuses to start. I have read several of the issues that were more or less related to a similar but nothing helped. 

I have uninstalled everything (Python, SABnzbd, Sickbeard, CoucPotato, ...) rebooted and re-installed, but that didn't work either. 

The folder /var/packages/sabznbd/scripts is populated. The log from the GUI is empty. Not sure, but I think that the log file should be in /usr/local/sabnzbd/var/logs/sabnzbd.log. However, I didn't find any /usr/local/sabnzbd/var/logs/ folder, so I created one. The restart didn't work better and the folder remains empty. 

When I launch the script start-stop-status start, it says "Starting SABnzbd" and nothing else. There is no sabnzbd process.

Content of /usr/local/sabnzbd:
drwxr-xr-x    3 sabnzbd  root          4096 Dec 31 15:08 app
drwxr-xr-x    2 sabnzbd  root          4096 Mar 23 23:14 bin
drwxr-xr-x    5 sabnzbd  root          4096 Mar 23 23:14 env
drwxr-xr-x    4 sabnzbd  root          4096 Dec 31 15:08 share
drwxr-sr-x    4 sabnzbd  root          4096 Mar 23 23:14 var

Content of  /volume1/@appstore/:
drwxrwxrwx    9 root     root          4096 Mar 12 22:45 AntiVirus
drwxrwxrwx   13 root     root          4096 Jan  1 23:28 AudioStation
drwxr-xr-x   10 root     root          4096 Mar 17 16:17 CloudSync
drwxrwxrwx    9 root     root          4096 Mar 12 22:38 DNSServer
drwxrwxrwx   12 root     root          4096 Jan  1 23:18 DownloadStation
drwxrwxrwx    7 root     root          4096 Mar 12 23:54 MariaDB
drwxrwxrwx   11 root     root          4096 Dec 12 21:42 MediaServer
drwxrwxrwx    4 root     root          4096 Dec 12 21:44 Perl
drwxrwxrwx   10 root     root          4096 Jan 23 15:26 PhotoStation
drwxrwxrwx   12 root     root          4096 Feb 26 01:16 VideoStation
drwxrwxrwx    5 root     root          4096 Mar 12 22:37 Webalizer
drwxrwxrwx    8 root     root          4096 Mar 12 22:46 iTunesServer
drwxrwxrwx    4 root     root          4096 Jan  1 23:21 phpMyAdmin
drwxrwxrwx    7 root     root          4096 Mar 23 18:19 python
drwxr-xr-x    7 sabnzbd  root          4096 Mar 23 23:14 sabnzbd

Content of  /volume1/@appstore/sabnzbd:
drwxr-xr-x    3 sabnzbd  root          4096 Dec 31 15:08 app
drwxr-xr-x    2 sabnzbd  root          4096 Mar 23 23:14 bin
drwxr-xr-x    5 sabnzbd  root          4096 Mar 23 23:14 env
drwxr-xr-x    4 sabnzbd  root          4096 Dec 31 15:08 share
drwxr-sr-x    4 sabnzbd  root          4096 Mar 23 23:14 var

Content of  /var/packages/sabnzbd:
-rw-r--r--    1 root     root         16078 Mar 23 23:14 INFO
drwxr-xr-x    2 root     root          4096 Dec 31 15:08 WIZARD_UIFILES
lrwxrwxrwx    1 root     root            30 Mar 23 23:14 etc -> /usr/syno/etc/packages/sabnzbd
drwxr-xr-x    2 root     root          4096 Dec 31 15:08 scripts
lrwxrwxrwx    1 root     root            26 Mar 23 23:14 target -> /volume1/@appstore/sabnzbd

Content of /var/log/messages:
Mar 23 23:10:52 DiskStation entry.cgi_SYNO.Core.Package.Control[1].start[7054]: pkgstartstop.cpp:182 Failed to start package sabnzbd, [2]
Mar 23 23:14:52 DiskStation entry.cgi_SYNO.Core.Package.Control[1].start[9165]: pkgstartstop.cpp:182 Failed to start package sabnzbd, [2]

Content of /var/log/synopkg.log
2015/03/23 23:14:44     install sabnzbd 0.7.20-13 successfully
2015/03/23 23:14:45     start sabnzbd: begin to start version 0.7.20-13
2015/03/23 23:14:52     stop sabnzbd: begin to stop version 0.7.20-13
2015/03/23 23:14:52     stop sabnzbd: stop version 0.7.20-13 successfully, result 0
2015/03/23 23:14:52     start sabnzbd: start version 0.7.20-13 failed, result 263

Any help is welcome. 

Cheers, 

Hemie143

**Comment by Dr-Bean** [comment]
The SAB package needs an new release due to some changes in the way Python works. We'll get to that as soon as we can.

**Comment by Hemie143** [comment]
Great. Thanks for the confirmation. I couldn't find any confirmation of this issue anywhere and couldn't understand what was wrong in my setup. 
I'm looking forward to this new SAB release.

**Comment by bmcharg** [comment]
Same issues seen here since the update. Is there an eta on a patch / release? Or am I better to roll back to previous versions of both Python and SabNZBD?

**Comment by Hemie143** [comment]
Actually, I tried to rollback Python, but couldn't find the correct URLs for the packages.

**Comment by Hemie143** [comment]
Just for tests, I rolled back on the Python release (3f8ddf1) and compiled it for my platform. Same for SABnzbd but it isn't working better. SABnzbd hasn't changed in the last 3 months and the update to Python 2.7.9 is only 11 days old. Where's my mistake ?

**Comment by Dr-Bean** [comment]
Because you didn't go back far enough. It's not an incompatibility with Python 2.7.9 in particular, it's because of one of the modules that Python uses, which was updated with 4536951fd50bfb20556f9826f17ca74971f91b8a

**Comment by Hemie143** [comment]
Ow, nice. Thanks for the tip. I will try from that commit then. I'm fully aware that's not the safest solution, but I still wanna try... and I'm at least learning some stuff.

**Comment by Dr-Bean** [comment]
You'll want to use the commit _before_ that one then ;) Pip should be version 1.5.x, not 6.x.x.

**Comment by Hemie143** [comment]
Yes, indeed. I meant that. I saw that the commit before that refers to pip 1.5.6. Let's cross the fingers. I'll try to compile the packages this this evening. Thanks for your prompt replies.

**Comment by Hemie143** [comment]
Mmmh, there must be something. After compilation, the SABnzbd package still fails to start. 
The /var/log/messages now contains this: 
Mar 30 18:40:51 DiskStation entry.cgi_SYNO.Core.Package.Control[1].start[21035]: pkgstartstop.cpp:182 Failed to start package sabnzbd, [1]

Content of /var/log/synopkg.log
2015/03/30 18:38:03     install python 2.7.8-11 successfully
2015/03/30 18:40:49     install sabnzbd 0.7.20-13: run postinst  ret=[0]
2015/03/30 18:40:49     sabnzbd stderr: adduser: no uids left
chown: unknown user/group sabnzbd:root

2015/03/30 18:40:49     install sabnzbd 0.7.20-13 successfully
2015/03/30 18:40:51     start sabnzbd: begin to start version 0.7.20-13
2015/03/30 18:40:51     stop sabnzbd: begin to stop version 0.7.20-13
2015/03/30 18:40:51     stop sabnzbd: stop version 0.7.20-13 successfully, result 0
2015/03/30 18:40:51     start sabnzbd: start version 0.7.20-13 failed, result 263

**Comment by Dr-Bean** [comment]
Ah, right. That's the busybox upgrade which was updated with https://github.com/SynoCommunity/spksrc/commit/89e31bff09dbe90fb30746309558501e9fd0a912. Because you did the checkout just before pip was updated, you're missing the fix implemented with https://github.com/SynoCommunity/spksrc/commit/81d894546842c3996e59244f5465d8ee2d8dcdc4.
So, either go back to the commit before the busybox upgrade, or add the fix manually.

**Comment by Hemie143** [comment]
Sorry, something is still missing. I checked out with the commit before 89e31bf and applied the fix manually, as in 81d8945.

Content of /var/log/synopkg.log
2015/03/31 00:56:13     install python 2.7.8-11 successfully
2015/03/31 01:04:38     install sabnzbd 0.7.20-13 successfully
2015/03/31 01:04:39     start sabnzbd: begin to start version 0.7.20-13
2015/03/31 01:04:45     stop sabnzbd: begin to stop version 0.7.20-13
2015/03/31 01:04:45     stop sabnzbd: stop version 0.7.20-13 successfully, result 0
2015/03/31 01:04:45     start sabnzbd: start version 0.7.20-13 failed, result 263

I have no idea how to retrieve more information about the error.

**Comment by Dr-Bean** [comment]
Run this command via the command line on your Synology, see what it tells you:
```
su sabnzbd -c "PATH=/usr/local/sabnzbd/bin:/usr/local/sabnzbd/env/bin:/usr/local/python/bin:${PATH} /usr/local/sabnzbd/env/bin/python /usr/local/sabnzbd/share/SABnzbd/SABnzbd.py -f /usr/local/sabnzbd/var/config.ini --pidfile /usr/local/sabnzbd/var/sabnzbd.pid -d"

If it starts, the sabnzbd log might also contain some info: `/usr/local/sabnzbd/var/logs/sabnzbd.log`

**Comment by Hemie143** [comment]
I tried that earlier already and this didn't produce any output. Also, I have the /usr/local/sabnzbd/var/logs/ folder, but no sabnzbd.log in it. I "touched" it, but it remains empty. 
The file and folder are owned by the user sabnzbd. 

I don't understand what's happening and I don't know enough to gather more information.

**Comment by Dr-Bean** [comment]
Ok, then try this:
```
su sabnzbd -c "PATH=/usr/local/sabnzbd/bin:/usr/local/sabnzbd/env/bin:/usr/local/python/bin:${PATH} /usr/local/sabnzbd/env/bin/python /usr/local/sabnzbd/share/SABnzbd/SABnzbd.py -f /usr/local/sabnzbd/var/config.ini --pidfile /usr/local/sabnzbd/var/sabnzbd.pid"
```
You should see a whole lot of text scrolling by, ending in something like this:
```
2015-04-02 01:36:36,328::INFO::[SABnzbd:1597] Starting SABnzbd.py-0.7.20
2015-04-02 01:36:36,334::INFO::[dirscanner:277] Dirscanner starting up
2015-04-02 01:36:36,338::INFO::[urlgrabber:77] URLGrabber starting up
```
Paste the output you're getting on gist.github.com or pastebin, and provide the link here (or maybe take a screenshot, but make sure it's legible...)

**Comment by Hemie143** [comment]
OK, starting the process but not in daemon mode.

Then the error showed up immediately, sabnzbd couldn't edit the config.ini file. I can't understand why but the owner wasn't the user sabnzbd anymore, but root and the permissions weren't correct either. 
So, I just corrected that and restarted sabnzbd without any issue now. It's working again. Thanks for the advice !
My setup is still based on sabnzbd 0.7.20, but I'm using a python package I compiled from 78ef640. If there are requests for the python packages, I can maybe post them somewhere. 

Thanks for your support.

**Comment by Dr-Bean** [comment]
Looks like your configuration has been reset to original, or is corrupt. No changes should be needed to the first line of the script, if you start the package via Package Center/the start-stop-status script.
I'd recommend a clean installation of the package.

As for the Python packages, no need to share them. I've verified that both packages work correctly with each other. If you have issues with running the current SAB package with the current Python package: it's a local issue.

**Comment by Hemie143** [comment]
How do make sure that you have a clean install ? I guess it's not simply uninstalling the packages from the GUI.

**Comment by Dr-Bean** [comment]
Well, it usually is. However, in you case, manual changes to the setup might mean things will be left behind after uninstalling. 
So, before installing the packages, make sure that `/usr/local/{package}` does not exist (for both Python and SABnzbd), that should usually be enough.

**Comment by Dr-Bean** [comment]
If the problem still exists after reinstalling, feel free to report it. Until then, let's close this :)
