### ISSUE TITLE
Update of Debian Chroot needed due to broken pybundle support

### ISSUE THREAD

**Issue by PiterEL** [SynoCommunity/spksrc#1595]
Hello
I reinstalled my synology and it download new version Python 2.7.9-13 After this instalation and after install Debian Chhroot 7.4-4 , my Debian Chroot not run automatic on startup Synology DS713+ and on Debian Chroot i have installed TVHeadend. And have big problem becuase when i install TVHeadend on Debian Chroot it run ok but when i try open WEB GUI Tvheadend it open not full and dead. After restart is still the same. Before download update python works ok... on version older 2.7.8. How or where i can download older version 2.7.8 spk to test it to my DS713+ cedarview? Please help me begause i am begginer user linux.

**Comment by Dr-Bean** [comment]
Let me fix that title for you.

**Comment by Dr-Bean** [comment]
See title, the Debian-Chroot package needs an update to work correctly with out latest Python package.

**Comment by PiterEL** [comment]
Ok but how i can update debian chroot ? On spk is latest avaible 7.4-4

Maybe can send me old Python in version 2.7.8 for cedarview ?

**Comment by Dr-Bean** [comment]
There are two options available to you: Wait, until we update the Debian-Chroot package on the repository, or build the Debian-Chroot package yourself.

**Comment by PiterEL** [comment]
But how i can build ?

Maybe can you send me old python 2.7.8 ?Please

**Comment by Dr-Bean** [comment]
Build Debian-Chroot the same as any other package, although you need root permissions to build debian-chroot, due to the way it's built. 
So, `cd /path-to-your-spksrc/spk/debian-chroot`, `sudo make arch-cedarview-5.1`.

Fyi, this is going to be my last message in this issue, unless I post here to say that the package is updated on the repository.

**Comment by PiterEL** [comment]
But if they do it will build the same parcel as it is available.

I can not cope as well as with a python. Can someone provide me with Python 2.7.8 for Cedarview?

**Comment by PiterEL** [comment]
Ok i build as you describe new spk for debian chroot. I install it and then i try RUN but i can not run. Still have info STOPED.

**Comment by PiterEL** [comment]
I tested and tested and tested and probably not start automatic Debian CHroot is cause that it not work on DSM 5.2 beta. Tomorrow i back to DSM 5.1 and test.

**Comment by PiterEL** [comment]
Hello
I have installed clear new system DSM 5.1 with update 4. After that i install python 2.7.9-13 and then Debian Chroot from SynoCommunity. After install i have a info: Failed to start the service package.

I try install from SPK oldest Python 2.7.8-11 and then Debian Chroot. But is the same problem. Please help me. My system DSM 5.1 is clear.


Maybe anybody help me.... please. For what package whichc not working ?

**Comment by PiterEL** [comment]
on 1000% problem is probably with python. When i add file S99debian.sh to path:
/usr/syno/etc.defaults/rc.d/

and in this file S99debian.sh have this:

#!/bin/sh

su - root -s /bin/sh -c "/bin/sh /var/packages/debian-chroot/scripts/start-stop-status start"
su - root -s /bin/sh -c "/bin/sh /var/packages/debian-chroot/scripts/start-stop-status status"


after reboot DSM Synology , Debian-Chroot run ok on start and shou ok status RUNNING....

Maybe someone correct it in package ?

**Comment by zeldhaking** [comment]
Hello, i have updated my DSM to 5.1-5022 Update 4 and PYTHON to 2.7.9-13.
Now it is impossible to start DEBIAN 7.4-4.

I try /var/packages/debian-chroot/scripts/start-stop-status start
but it give me:
Starting Debian Chroot ...
Traceback (most recent call last):
  File "/usr/local/debian-chroot/app/start.py", line 2, in <module>
    from application.direct import Services
  File "/volume1/@appstore/debian-chroot/app/application/direct.py", line 1, in <module>
    from pyextdirect.configuration import create_configuration, expose, LOAD, STORE_READ, STORE_CUD
ImportError: No module named pyextdirect.configuration

Impossible to run debian, it give me:
-ash: debian: not found

An idea?

**Comment by Dr-Bean** [comment]
Debian-Chroot 7.4-5 has been published on the repository.

**Comment by zeldhaking** [comment]
Nice! It works for me...
