### ISSUE TITLE
Calendar keeps spinning

### ISSUE THREAD

**Issue by Digialex** [SynoCommunity/spksrc#1596]
8.0.2 OC install. Tasks works beautifully and so do files and the PC client for files. But when I login on my PC and go to calendar the "gear" in the center keeps spinning and spinning and nothing appears. I deleted the calendar app from the apps file then enable it. But still spinning!

How do I fix this?

**Comment by Dr-Bean** [comment]
We don't have an Owncloud 8.x version released, so can't help you there. 
Try using the official, unmodified Owncloud 7.0.3-5 that SynoCommunity provides. Otherwise, check with Owncloud support/forums/what have you, see if they can help.

**Comment by Digialex** [comment]
Any idea as to whether there will be a release in the near future that works with 8.x?
