### ISSUE TITLE
[OwnCloud] download bug xsendfile

### ISSUE THREAD

**Issue by burnacid** [SynoCommunity/spksrc#1597]
When using the package I wasn't able to download any files out of the webportal of OC.
After searches and logs reviewing this is what it fixed it. Can you include that to the package?

https://forum.owncloud.org/viewtopic.php?f=29&t=26674#p82956

all you need to know is that you need to change the following file:
/etc/httpd/conf/extra/mod_xsendfile.conf-user

to include:

XSendFilePath /path/to/OC/data/folder

For example: XSendFilePath /volume1/web/owncloud/data

**Comment by Dr-Bean** [comment]
We use a slightly different method to set it up, and I don't have the issue: https://github.com/SynoCommunity/spksrc/blob/master/spk/owncloud/src/installer.sh#L64. 
Can you check that file is there on your device?

**Comment by Dr-Bean** [comment]
Closing, no response.
