### ISSUE TITLE
Build SPK Python 2.7.8-11 Cedarview   HELP

### ISSUE THREAD

**Issue by PiterEL** [SynoCommunity/spksrc#1598]
Hello
I want to build spk for platform CEDARVIEW for my DS713+. I want build Python in version 2.7.8-11. When i build i have an error:

![error](https://cloud.githubusercontent.com/assets/4134018/6798207/110d2cd8-d20b-11e4-9751-09f5093cfdf6.jpg)

Please help me or maybe can share me building spk in this version for cedarview because i don know what is an error because i am begginer user.

Please please help me

**Comment by Dr-Bean** [comment]
Great that you're trying. However, you're going to have to be more specific, because with just this output, we can't help. 
What did you do _before_ you arrived at this point? Which commands did you use, which files did you change (if any)?

**Comment by Dr-Bean** [comment]
Btw, if it's just about getting the Debian-Chroot package running, it would probably make more sense to just compile that, right?

**Comment by PiterEL** [comment]
I do step by step as in manuall:

download git and checkout to commit 3f8ddf1e8af6197ff500158f867937fb5d471463
then cd spksrc
change default dsm in Makefile to 5.1
then 
make setup
cd spk/python
make arch-cedarview

copying build/lib/easy_install.py -> build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/ssl_support.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/windows_support.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/site-patch.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/lib2to3_ex.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/py31compat.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/script.tmpl -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/package_index.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/__init__.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/compat.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/unicode_utils.py -> build/bdist.linux-i686/egg/setuptools
creating build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/bdist_wininst.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/test.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/install_egg_info.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/register.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/alias.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/easy_install.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/setopt.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/__init__.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/install_scripts.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/build_ext.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/bdist_rpm.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/develop.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/sdist.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/upload_docs.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/build_py.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/install_lib.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/egg_info.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/bdist_egg.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/saveopts.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/install.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/command/rotate.py -> build/bdist.linux-i686/egg/setuptools/command
copying build/lib/setuptools/archive_util.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/utils.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/script (dev).tmpl -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/extension.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/sandbox.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/dist.py -> build/bdist.linux-i686/egg/setuptools
creating build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_packageindex.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_msvc9compiler.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_find_packages.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_develop.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/environment.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/script-with-bom.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_upload_docs.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_sandbox.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_easy_install.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_egg_info.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_bdist_egg.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_sdist.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/__init__.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/contexts.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_test.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/fixtures.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_dist_info.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_build_ext.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_windows_wrappers.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/textwrap.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/py26compat.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_markerlib.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/test_integration.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/tests/server.py -> build/bdist.linux-i686/egg/setuptools/tests
copying build/lib/setuptools/py26compat.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/version.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/py27compat.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/msvc9_support.py -> build/bdist.linux-i686/egg/setuptools
copying build/lib/setuptools/depends.py -> build/bdist.linux-i686/egg/setuptools
creating build/bdist.linux-i686/egg/_markerlib
copying build/lib/_markerlib/markers.py -> build/bdist.linux-i686/egg/_markerlib
copying build/lib/_markerlib/__init__.py -> build/bdist.linux-i686/egg/_markerlib
creating build/bdist.linux-i686/egg/pkg_resources
creating build/bdist.linux-i686/egg/pkg_resources/_vendor
creating build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging
copying build/lib/pkg_resources/_vendor/packaging/_compat.py -> build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging
copying build/lib/pkg_resources/_vendor/packaging/__init__.py -> build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging
copying build/lib/pkg_resources/_vendor/packaging/specifiers.py -> build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging
copying build/lib/pkg_resources/_vendor/packaging/__about__.py -> build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging
copying build/lib/pkg_resources/_vendor/packaging/_structures.py -> build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging
copying build/lib/pkg_resources/_vendor/packaging/version.py -> build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging
copying build/lib/pkg_resources/_vendor/__init__.py -> build/bdist.linux-i686/egg/pkg_resources/_vendor
copying build/lib/pkg_resources/__init__.py -> build/bdist.linux-i686/egg/pkg_resources
creating build/bdist.linux-i686/egg/pkg_resources/tests
copying build/lib/pkg_resources/tests/test_resources.py -> build/bdist.linux-i686/egg/pkg_resources/tests
copying build/lib/pkg_resources/tests/__init__.py -> build/bdist.linux-i686/egg/pkg_resources/tests
copying build/lib/pkg_resources/tests/test_pkg_resources.py -> build/bdist.linux-i686/egg/pkg_resources/tests
byte-compiling build/bdist.linux-i686/egg/easy_install.py to easy_install.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/ssl_support.py to ssl_support.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/windows_support.py to windows_support.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/site-patch.py to site-patch.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/lib2to3_ex.py to lib2to3_ex.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/py31compat.py to py31compat.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/package_index.py to package_index.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/compat.py to compat.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/unicode_utils.py to unicode_utils.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/bdist_wininst.py to bdist_wininst.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/test.py to test.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/install_egg_info.py to install_egg_info.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/register.py to register.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/alias.py to alias.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/easy_install.py to easy_install.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/setopt.py to setopt.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/install_scripts.py to install_scripts.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/build_ext.py to build_ext.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/bdist_rpm.py to bdist_rpm.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/develop.py to develop.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/sdist.py to sdist.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/upload_docs.py to upload_docs.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/build_py.py to build_py.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/install_lib.py to install_lib.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/egg_info.py to egg_info.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/bdist_egg.py to bdist_egg.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/saveopts.py to saveopts.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/install.py to install.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/command/rotate.py to rotate.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/archive_util.py to archive_util.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/utils.py to utils.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/extension.py to extension.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/sandbox.py to sandbox.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/dist.py to dist.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_packageindex.py to test_packageindex.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_msvc9compiler.py to test_msvc9compiler.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_find_packages.py to test_find_packages.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_develop.py to test_develop.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/environment.py to environment.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/script-with-bom.py to script-with-bom.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_upload_docs.py to test_upload_docs.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_sandbox.py to test_sandbox.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_easy_install.py to test_easy_install.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_egg_info.py to test_egg_info.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_bdist_egg.py to test_bdist_egg.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_sdist.py to test_sdist.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/contexts.py to contexts.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_test.py to test_test.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/fixtures.py to fixtures.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_dist_info.py to test_dist_info.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_build_ext.py to test_build_ext.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_windows_wrappers.py to test_windows_wrappers.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/textwrap.py to textwrap.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/py26compat.py to py26compat.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_markerlib.py to test_markerlib.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/test_integration.py to test_integration.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/tests/server.py to server.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/py26compat.py to py26compat.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/version.py to version.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/py27compat.py to py27compat.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/msvc9_support.py to msvc9_support.pyc
byte-compiling build/bdist.linux-i686/egg/setuptools/depends.py to depends.pyc
byte-compiling build/bdist.linux-i686/egg/_markerlib/markers.py to markers.pyc
byte-compiling build/bdist.linux-i686/egg/_markerlib/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging/_compat.py to _compat.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging/specifiers.py to specifiers.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging/__about__.py to __about__.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging/_structures.py to _structures.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/_vendor/packaging/version.py to version.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/_vendor/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/tests/test_resources.py to test_resources.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/pkg_resources/tests/test_pkg_resources.py to test_pkg_resources.pyc
creating build/bdist.linux-i686/egg/EGG-INFO
copying setuptools.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying setuptools.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying setuptools.egg-info/dependency_links.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying setuptools.egg-info/entry_points.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying setuptools.egg-info/requires.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying setuptools.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying setuptools.egg-info/zip-safe -> build/bdist.linux-i686/egg/EGG-INFO
creating dist
creating 'dist/setuptools-14.3.1-py2.7.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing setuptools-14.3.1-py2.7.egg
Removing /root/spksrc/native/python/work-native/install/usr/local/lib/python2.7/site-packages/setuptools-14.3.1-py2.7.egg
Copying setuptools-14.3.1-py2.7.egg to /root/spksrc/native/python/work-native/install/usr/local/lib/python2.7/site-packages
setuptools 14.3.1 is already the active version in easy-install.pth
Installing easy_install script to /root/spksrc/native/python/work-native/install/usr/local/bin
Installing easy_install-2.7 script to /root/spksrc/native/python/work-native/install/usr/local/bin

Installed /root/spksrc/native/python/work-native/install/usr/local/lib/python2.7/site-packages/setuptools-14.3.1-py2.7.egg
Processing dependencies for setuptools==14.3.1
Finished processing dependencies for setuptools==14.3.1
Searching for pip==1.5.6
Best match: pip 1.5.6
Processing pip-1.5.6-py2.7.egg
pip 1.5.6 is already the active version in easy-install.pth
Installing pip script to /root/spksrc/native/python/work-native/install/usr/local/bin
Installing pip2.7 script to /root/spksrc/native/python/work-native/install/usr/local/bin
Installing pip2 script to /root/spksrc/native/python/work-native/install/usr/local/bin

Using /root/spksrc/native/python/work-native/install/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg
Processing dependencies for pip==1.5.6
Finished processing dependencies for pip==1.5.6
Downloading/unpacking cffi==0.8.6
  Downloading cffi-0.8.6.tar.gz (196kB): 196kB downloaded
  Running setup.py (path:/tmp/pip_build_root/cffi/setup.py) egg_info for package cffi
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found

Downloading/unpacking pycparser (from cffi==0.8.6)
  Downloading pycparser-2.10.tar.gz (206kB): 206kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pycparser/setup.py) egg_info for package pycparser

Installing collected packages: cffi, pycparser
  Running setup.py install for cffi
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    building '_cffi_backend' extension
    /root/spksrc/toolchains/syno-cedarview-5.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/root/spksrc/spk/python/work-cedarview-5.1/install//usr/local/python/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/root/spksrc/spk/python/work-cedarview-5.1/install//usr/local/python/include -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/root/spksrc/native/python/work-native/install/usr/local/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-i686-2.7/c/_cffi_backend.o
    In file included from /root/spksrc/native/python/work-native/install/usr/local/include/python2.7/Python.h:58:0,
                     from c/_cffi_backend.c:2:
    /root/spksrc/native/python/work-native/install/usr/local/include/python2.7/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
    error: command '/root/spksrc/toolchains/syno-cedarview-5.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc' failed with exit status 1
    Complete output from command /root/spksrc/native/python/work-native/install/usr/local/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-quN3zl-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

Package libffi was not found in the pkg-config search path.

Perhaps you should add the directory containing `libffi.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libffi' found

running install

running build

running build_py

creating build

creating build/lib.linux-i686-2.7

creating build/lib.linux-i686-2.7/cffi

copying cffi/lock.py -> build/lib.linux-i686-2.7/cffi

copying cffi/model.py -> build/lib.linux-i686-2.7/cffi

copying cffi/commontypes.py -> build/lib.linux-i686-2.7/cffi

copying cffi/gc_weakref.py -> build/lib.linux-i686-2.7/cffi

copying cffi/api.py -> build/lib.linux-i686-2.7/cffi

copying cffi/verifier.py -> build/lib.linux-i686-2.7/cffi

copying cffi/cparser.py -> build/lib.linux-i686-2.7/cffi

copying cffi/backend_ctypes.py -> build/lib.linux-i686-2.7/cffi

copying cffi/__init__.py -> build/lib.linux-i686-2.7/cffi

copying cffi/ffiplatform.py -> build/lib.linux-i686-2.7/cffi

copying cffi/vengine_cpy.py -> build/lib.linux-i686-2.7/cffi

copying cffi/vengine_gen.py -> build/lib.linux-i686-2.7/cffi

running build_ext

building '_cffi_backend' extension

creating build/temp.linux-i686-2.7

creating build/temp.linux-i686-2.7/c

/root/spksrc/toolchains/syno-cedarview-5.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/root/spksrc/spk/python/work-cedarview-5.1/install//usr/local/python/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/root/spksrc/spk/python/work-cedarview-5.1/install//usr/local/python/include -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/root/spksrc/native/python/work-native/install/usr/local/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-i686-2.7/c/_cffi_backend.o

In file included from /root/spksrc/native/python/work-native/install/usr/local/include/python2.7/Python.h:58:0,

                 from c/_cffi_backend.c:2:

/root/spksrc/native/python/work-native/install/usr/local/include/python2.7/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."

c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory

compilation terminated.

error: command '/root/spksrc/toolchains/syno-cedarview-5.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /root/spksrc/native/python/work-native/install/usr/local/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-quN3zl-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cffi
Storing debug log for failure in /root/.pip/pip.log
make[3]: *** [myPostInstall] Błąd 1
make[3]: Opuszczenie katalogu `/root/spksrc/native/python'
make[2]: *** [depend_target] Błąd 2
make[2]: Opuszczenie katalogu `/root/spksrc/cross/python'
make[1]: *** [depend_target] Błąd 2
make[1]: Opuszczenie katalogu `/root/spksrc/spk/python'
make: [arch-cedarview] Błąd 2 (zignorowany)
root@OUM-GLPI:~/spksrc/spk/python#

**Comment by PiterEL** [comment]
I need this version to my Debian Chroot. Because i am running on debian chroot TVHeadend and probably after install Python 2.7.9-13 my Tvheadend not working correct. WEBUI open and after one second dead. And not responding... before work OK.

**Comment by Dr-Bean** [comment]
I don't see how a Python version would interfere with running TVHeaded in a chroot, but that could be me :) Would be interesting to know if you can indeed solve it with Python 2.7.8.

As for your problem, you're doing it right, but something seems broken. 
How about this: Go to the `/native/python` dir, and do `make clean && make`. If it completes without errors, go to the `/spk/python` dir, and do `make clean && make`.

**Comment by PiterEL** [comment]
Ok i done this:
Firts command all succesfull
Second have an error:
![err](https://cloud.githubusercontent.com/assets/4134018/6798841/316449de-d211-11e4-801d-af9f5413cb63.jpg)


Yesterday i have installed Debian Chroot 7.4.-4 and Python 2.7.8-11
On debian i have TVHeadend... I think maybe i update openssl. Have 1.0.1j and i try install 1.0.1k... After this my Tvheadend open for a second and then not responding. I do thi by install libssl-dev  from sid. When i want come back to version 1.0.1j i check it by apt-cache policy libssl-dev but the is no version 1.0.1j. I have lastes 1.0.1e and newest 1.0.1k. I delete all Debian Chroot i try from beggin to install all with TVHeadend.  Try on libssl-dev version 1.0.1e and 1.0.1k and on all version when i type in web browser http://address_ip:9981 page open sometime full sometimes half and after about second not responding. I dont know what is it... I try open on other devices , smartphone , tablet and PC.

**Comment by Dr-Bean** [comment]
Oh wait, my bad. In `spk/python`, do `make clean && make arch-cedarview-5.1`.

**Comment by PiterEL** [comment]
Ok do
You read me what i do yesterday with my TVHeadend ?

**Comment by Dr-Bean** [comment]
Yes, but I don't think I can help with that. I don't use TVHeadend myself, let alone in a chroot. Maybe someone else has some input on that.

**Comment by PiterEL** [comment]
Oki
maybe you can build me SPK 2.7.8-11

And i have a problem because after reinstall debian chroot , it not start automaticaly with DSM. I must run manuall. Before reinstall starting auto with DSM. I reinstall Debian Chroot more than one and still the same problem not start.

**Comment by Dr-Bean** [comment]
One thing at a time, please, otherwise you're going to make things more difficult for everyone involved.
First, build the Python package. Then install it. After that, remove Debian-Chroot, and do a clean install. That's your starting point for further investigation.

**Comment by PiterEL** [comment]
After do thi:
 In spk/python, do make clean && make arch-cedarview-5.1.

![re](https://cloud.githubusercontent.com/assets/4134018/6799195/fdfcc758-d213-11e4-9ceb-775275923aef.jpg)

**Comment by Dr-Bean** [comment]
Yep, that can happen: that file isn't available anymore. You need to apply https://github.com/SynoCommunity/spksrc/commit/27aab035d3a0eedbc2920f98e87ca7d6c59a9307 and https://github.com/SynoCommunity/spksrc/commit/867a4825ed8c5a2e9442ce5d37af427a6a5bbe3f

**Comment by PiterEL** [comment]
And again do In spk/python, do make clean && make arch-cedarview-5.1. ?

**Comment by Dr-Bean** [comment]
It's probably the easiest for you.

**Comment by PiterEL** [comment]
But in thgis patch i have data to version 1.0.2....?

**Comment by Dr-Bean** [comment]
You might have missed my edit, but that's correct. That's what the second commit was for.

**Comment by PiterEL** [comment]
Sorry i dont understand...:(

**Comment by Dr-Bean** [comment]
The second commit (https://github.com/SynoCommunity/spksrc/commit/867a4825ed8c5a2e9442ce5d37af427a6a5bbe3f) fixes the digests file for libsodium 1.0.2. If you check now, you'll see that it still contains the checksums for 1.0.1, and that's causing your error.

**Comment by PiterEL** [comment]
oki i delete 1.0.1 and try again.

**Comment by PiterEL** [comment]
But why my debian chroot not start with DSM automatic ?

**Comment by Dr-Bean** [comment]
As I said, let's fix one issue first, then go on to the next...Compile and install your Python 2.7.8 package, then remove and reinstall Debian-Chroot. See if the issue still occurs after doing that (and yes, there's a specific reason I'm telling you to do it like this)

**Comment by PiterEL** [comment]
now i have error that i have to old version automake. I have 1.11.6 but is needed 1.14. But when i type apt-get update
apt-cache policy automake 

i have only available version 1.11.6

**Comment by PiterEL** [comment]
But why Debian Chroot not start automatic after start DSM ? I test it with python 2.7.9-13....

**Comment by Dr-Bean** [comment]
Well, that's where #1595 comes in...As I said, there's a specific reason as to why I'm asking you to not combine separate issues into one big problem.

As for the automake issue, are you're running something else than Debian for your spksrc build environment?

**Comment by PiterEL** [comment]
Not i am running only debian to build spk.

But i dont understand why Debian Chroot not run with my DSM. 

Two days ago when all work for me ok Debian Shroot start auto. But after reinstall not start.

**Comment by PiterEL** [comment]
Ok problem with dead TVHeadend was in TVHeadend. I buil with new revision and works ok. 

But still fight with not running auto Debian Chroot. After restart DSM i must do to Package Center in DSM and manual run Debian Chroot. Please help me resolved this problem.

**Comment by PiterEL** [comment]
Ok. I format my synology and reset DSM and install again. Then install Python 2.7.9 and Debian Chroot 7.4-4
After manual run Debian Chroot, then restart Synology. Aftter restart i must run Debian Chroot again manual. When i have Some days ago Python 2.7.8 with Debian Chroot 7.4.-4 , after restart Synology Debian start automaticaly.

**Comment by Dr-Bean** [comment]
If you want to focus on Debian-Chroot behavior, please continue in #1595.
