### ISSUE TITLE
Horde issue - Database migration files not found. Please check PEAR's data_dir configuration setting.

### ISSUE THREAD

**Issue by sebastiendamaye** [SynoCommunity/spksrc#1601]
Hi,

When installing Horde from the package, the installation is successful but the Horde admin interface is showing the following error message:

    Database migration files not found. Please check PEAR's data_dir configuration setting.

The data_dir parameter is set to /var/packages/PEAR/target/data:

    syno> /volume1/@appstore/horde/bin/pear -c /volume1/@appstore/horde/etc/pear.conf -c horde config-show | grep data_dir
    PEAR data directory            data_dir         /var/packages/PEAR/target/data

Any idea what could be wrong?

**Comment by Dr-Bean** [comment]
Could you check if this works? Create the following file: 
`/etc/httpd/sites-enabled-user/com.synocommunity.packages.horde.conf`
, and put the following in it:
`SetEnv PHP_PEAR_SYSCONF_DIR /usr/local/horde/etc `

Then, restart Apache, or maybe easier: reboot.

**Comment by sebastiendamaye** [comment]
It's working. Thank you!
