### ISSUE TITLE
DSM5.1 Big Problem Debian Chroot-not start

### ISSUE THREAD

**Issue by PiterEL** [SynoCommunity/spksrc#1602]
Hello
I have installed clear new system DSM 5.1 with update 4. After that i install python 2.7.9-13 and then Debian Chroot from SynoCommunity. After install i have a info: Failed to start the service package.

I try install from SPK oldest Python 2.7.8-11 and then Debian Chroot. But is the same problem. Please help me. My system DSM 5.1 is clear.

**Comment by Diaoul** [comment]
Duplicate #1595

**Comment by zeldhaking** [comment]
Where can we find the oldest Python 2.7.8-11?
