### ISSUE TITLE
BitTorrent Sync v1.4.111-11 vs. 2.0.93

### ISSUE THREAD

**Issue by erikusaj** [SynoCommunity/spksrc#1610]
I've noticed that the BitTorrent Sync App available on SynoCommunity is outdated **v1.4.111-11** ?

http://help.getsync.com/customer/portal/articles/1888507-synology

Lists packages with: **Sync 2.0.93**

Download
Sync 2.0.93:
88f628x   
alpine
armada370
armada375
armadaxp
avoton
bromolow
cedarview
evansport
x86
x64
Last Updated: Mar 19, 2015 11:56AM PDT

**Comment by piwi82** [comment]
As the BotTorrent team now provides official BTsync packages, no update will be provided by SynoCommunity.
Synology will probably add these packages to the official repository.

**Comment by erikusaj** [comment]
Unfortunately the BT sync package provided by BitTorrent does not work - or has some something miss-configured.

**Comment by Dr-Bean** [comment]
Well, you can either use our 1.4 package, or ask support from BitTorrent for the issues you have with their package. There's not much use in providing an additional BTSync 2.0 package with our name on it, better let them fix theirs, right?

**Comment by erikusaj** [comment]
Agree. Both are valid options.

Figured out what was causing this issue. By comparing your and BitTorrent package config files.
In configuration file 
/var/packages/bittorentsync/target/var/sync.conf 
"webui" port for "listen" was miss-configured, changing it and stopping and re-starting the package fixed the issue.
There is another "port" setting in /var/packages/bittorentsync/target/app/config
I think this one is the one used for what is opened from launcher.
