### ISSUE TITLE
Transmission 2.84-10 Permission Error

### ISSUE THREAD

**Issue by rormc** [SynoCommunity/spksrc#1611]
Hi There

I recently tried the Transmission .spk from here on my DS415play and everything went along fine until i tried downloading or seeding at which point i get permissions errors. I have looked around and most of the information on this issue are from quite a while ago or on different packages from different repo's. 

Basically i have tried unsuccessfully to give transmission the permissions it needs from the various googling i have done, can anyone help me out here? It would be much appreciated. Thank you!

I am trying to set transmissions download folder to something like volume1/files/torrents/ . 

Thanks again!

**Comment by Dr-Bean** [comment]
Set read/write permissions for the `users` group in DSM. Do that for both the `files` directory, and the `torrents` directory.

**Comment by rormc** [comment]
Wow thanks very much! Cant believe it was that easy.. Really am very grateful!

Perhaps a note on the installation page about this would be good as well?

Thanks again.

**Comment by Dr-Bean** [comment]
We'd prefer to change the package so that those permissions are set automatically, but that's not implemented atm.
The current package does work when you only use one level (like `/volume1/files`, for instance), but the installer doesn't handle the second level, hence the manual stuff.

**Comment by rormc** [comment]
Ah that makes sense! Really appreciate your work and quick response. Keep it up!

**Comment by rormc** [comment]
Hello again!

Thanks for your help with the permission denied issue. I have now come across a new issue i was hoping someone could help with. 

By granting the 'users' group permission to my torrent folder i can no longer control who has access to that folder.

 Is there anyway of there being just a transmission user that i can grant read/write access to?

Thanks in advance.

**Comment by Dr-Bean** [comment]
No, not at the moment. See my previous message. As a perfectly valid alternative, set 'No access' for the accounts you don't want to have access on those folders.
