### ISSUE TITLE
Sonarr won't start after Mono update

### ISSUE THREAD

**Issue by jerroen** [SynoCommunity/spksrc#1613]
Hi,

Not sure if this is the right place.

I updated Mono to 3.10.0-3 today and now Sonarr won't start up anymore. I tried rebooting and re-installing both packages but to no avail. I can't provide any logs since the log directory does not exist (makes sense after a reinstall).

Running "/var/packages/nzbdrone/scripts/start-stop-status start" from Terminal returns "Starting Sonarr ..." but nothing happens.

I'm running DSM 5.1-5022 Update 4

**Comment by Dr-Bean** [comment]
@maxrogers You did rebuild all the packages you uploaded after the last PR, right? ;)
Do you happen to know if there's a good way to troubleshoot Mono? A quick search lead me to the `Running Mono` section over here: http://pointbeing.net/weblog/2009/01/getting-started-with-mono-on-linux.html, but there might be a better way (since it presumably doesn't test the native libraries)

@jerroen Which model are you running?

**Comment by maxrogers** [comment]
@Dr-Bean, yes and I updated mine from the repo and confirmed. However, that does sound suspicious. @jerroen, what model?

**Comment by jerroen** [comment]
Sorry forgot to mention, I'm using a Synology DS215j

**Comment by Dr-Bean** [comment]
Package is the right size, it seems (without the libs, it was about 7MB, this one's 91,7MB).

**Comment by maxrogers** [comment]
@jerroen, try running this and let us know what you get

```su nzbdrone -c "env PATH=/usr/local/mono/bin:/usr/local/nzbdrone/bin:${PATH} LD_LIBRARY_PATH=/usr/local/nzbdrone/lib /usr/local/mono/bin/mono --debug /usr/local/nzbdrone/share/NzbDrone/NzbDrone.exe"```

**Comment by jerroen** [comment]
@maxrogers "The file /usr/local/mono/lib/mscorlib.dll is an invalid CIL image"

**Comment by maxrogers** [comment]
@jerroen, can you try this package? Let me know if it works.

https://www.dropbox.com/s/l8tr535l84xiffw/mono_armada375-5.1_3.10.0-3.spk?dl=0

**Comment by jerroen** [comment]
@maxrogers That seems to have done the trick, it is up and running now.

**Comment by Diaoul** [comment]
I just published an update to the repo, 3.10.0-4. Let me know if that works for you @jerroen.

**Comment by jerroen** [comment]
Everything is running smooth again, perfect. Thank you for the quick support everyone!

**Comment by maxrogers** [comment]
Thanks @Diaoul! The package I made for @jerroen also worked. We will be good from here on out!
