### ISSUE TITLE
mosquitto 1.4

### ISSUE THREAD

**Issue by timoline** [SynoCommunity/spksrc#1615]
Can you please update mosquitto to 1.4 ???
http://mosquitto.org/

thank you very much in advance

**Comment by timoline** [comment]
or the latest version (currently 1.4.1)

**Comment by kalanda** [comment]
It would be nice because websockets support is added with 1.4.x

**Comment by adamotte** [comment]
:+1:

**Comment by timoline** [comment]
And off course.....please with websockets enabled

**Comment by marcelrv** [comment]
@Diaoul first of all, thanks again for your great contribution. I really like that mosquitto is now available on the synology, it allowed me to move it away from my RPI and has been rock stable from day 1 I installed it.

indeed would great if websockets support could be enabled, as that's the only reason I have still a 2nd instance running on the RPI

**Comment by Diaoul** [comment]
See #1723
