### ISSUE TITLE
a few build/depend questions

### ISSUE THREAD

**Issue by cytec** [SynoCommunity/spksrc#1623]
as i just try to compile chromaprint for all supported archs i was wondering if there is a solution for some things i came across:

1. bundle arches by type... currently in some make files there is something like: `ifeq ($(findstring $(ARCH),xyz,$(ARCH))` wouldn't it be nice to have this in a global place? so that not all make files have to be updated everytime a new arch pops up?
2. there is `make all-archs-latest` but is there something like `make all-archs-5.1` to only build with that specific version of the toolchains?
3. is there any way i can depend on a minimum version of the toolchain in compile time? some stuff seems to need at least 5.x to compile and `make all-archs-latest` tries to compile with 4.x too, which fails

@Diaoul @Dr-Bean maybe you can enlighten me a little bit on those issues :)

**Comment by cytec** [comment]
to clear 1. up a little bit:

in `debian-chroot` or `syncthing` there are if's like this:

	ifeq ($(findstring $(ARCH),88f6281),$(ARCH))
		DEBIAN_ARCH = armel
	endif
	ifeq ($(findstring $(ARCH),armada370 armadaxp armada375 alpine),$(ARCH))
		DEBIAN_ARCH = armhf
	endif
	ifeq ($(findstring $(ARCH),bromolow cedarview evansport x86 avoton x64),$(ARCH))
		DEBIAN_ARCH = i386
	endif
	ifeq ($(findstring $(ARCH),qoriq),$(ARCH))
		DEBIAN_ARCH = powerpc
	endif
	ifeq ($(strip $(DEBIAN_ARCH)),)
		$(error Arch $(ARCH) not supported)
	endif

and i was thinking making it something like this:

	ifeq ($(findstring $(ARCH),$ARM_ARCHES),$(ARCH))
		DEBIAN_ARCH = armel
	endif
	ifeq ($(findstring $(ARCH),$ARM7_ARCHES),$(ARCH))
		DEBIAN_ARCH = armhf
	endif
	ifeq ($(findstring $(ARCH),$386_ARCHES),$(ARCH))
		DEBIAN_ARCH = i386
	endif
	...

so that `$ARM7_ARCHES` contains `armada370 armadaxp armada375 alpine` in a more global place and must only be edited once... also that would clear things up a little as i had some struggle to find out where to put `alpine` and had to look for a spk already referencing it

**Comment by Dr-Bean** [comment]
1: That's not implemented currently. It's be a one-time thing when a new toolchain comes along, so I don't mind too much. (although I wouldn't mind having the functionality either, for that matter) 
Note that there might be exceptions to the rule when a particular SPK cannot compile a particular arch for whatever reason.
2: I believe so. `all-archs-5` or `all-archs-5.1` should both work (or at least, they did when I implemented it, but I expect it's not used very often, see answer 3)
3: set `REQUIRED_DSM = 5` in your Makefile (or `5.1`, should work too iirc). Supported in both cross and spk.

**Comment by Dr-Bean** [comment]
2: Make that `all-toolchains-5` and `all-toolchains-5.1`...

**Comment by cytec** [comment]
yes im aware that there my be some exceptions for some particular SPK's for those lists. but i think most of them should come along with those `defaults` if not there is still the way it's currently done... Just thought something like that would be nice to have as a fallback/starting point 

aaahh... i see thought `all-toolchains-%` was for only setting up the toolchains itself. i'll give that a try. Thanks :)

**Comment by cytec** [comment]
@Dr-Bean would `spksrc.common.mk` be the correct file to put those `_ARCHES` variables in?

**Comment by Dr-Bean** [comment]
I think that's the only place we can put it, really, unless I'm forgetting something. 
Maybe set up a PR, so we can take a look at it?

Btw, what do you think of replacing `386_ARCHES` with `x86_ARCHES` (evansport) and `x64_ARCHES` (cedarview/bromolow/etc)?

**Comment by cytec** [comment]
i'm fine with that too.

**Comment by cytec** [comment]
@Dr-Bean done... i've also split `ARM_ARCHES` in arm5 and arm7...

**Comment by Dr-Bean** [comment]
Closing, seeing as #1635 was merged :)
