### ISSUE TITLE
TT-RSS Install if MariaDB root user deleted

### ISSUE THREAD

**Issue by ziltoidtheomiscient** [SynoCommunity/spksrc#1627]
Hi dear SynoCommunity !

As always when I do a fresh install of a MySQL-like DB, I delete de root user and create my own admin account for security reinforcement...

The issue is that the tt-rss installer ask for the root password, not for the root login, so I can't install it with this great package...

I did install it manually, but I would prefer have all my favorite apps packaged...

Do you have any clue on what I should do ?

Thank you !

**Comment by Dr-Bean** [comment]
Our packages rely on the root user being available when adding databases to MariaDB. I don't think we're going to change that: adding the notion of which account to use could easily confuse less experienced users, and it's a very rare use-case imo.

So, my suggestion would be to put the user back.

**Comment by ziltoidtheomiscient** [comment]
Ok I understand, no problem :)

I looked at "tt-rss/src/installer.sh" but I can't find where you are activating daemon, it's the only issue I still have on my manual installation :/

**Comment by ziltoidtheomiscient** [comment]
Oh it's ok I see, it's in "dsm-control.sh" :)

Thank for your time and answer !
