### ISSUE TITLE
Syncthing doesn't work after upgrade

### ISSUE THREAD

**Issue by cie007** [SynoCommunity/spksrc#1628]
Hello 

I've upgraded syncthing via package center (v 0.9.4.2 to 0.10.30) and when I click on run, it won't run. 
I't has the status "stopped"
I can't find any log what is wrong so I can't tell more. 

I have uninstalled and installed again, but it won't execute. 

via putty this is what I get:
ds212> "/var/packages/syncthing/scripts/start-stop-status" start
Starting Syncthing ...
ds212> "/var/packages/syncthing/scripts/start-stop-status" status
Syncthing is not running

Is it possible to turn back the previuos version? (v0.9.4.2)

edit: Added Putty

**Comment by Dr-Bean** [comment]
@cytec ARMv5 is broken. The actual error is this: `runtime: this CPU has no floating point hardware, so it cannot run this GOARM=6 binary. Recompile using GOARM=5.`
https://github.com/golang/go/wiki/GoArm has some details on that.

**Comment by cie007** [comment]
A question, Do I have to move this thread to #1011  ?

**Comment by Dr-Bean** [comment]
Nah, it's more likely that #1011 will get closed in the near future, I actually considered doing that after publishing the current package, but forgot to do so.

**Comment by sdkent** [comment]
@Dr-Bean If this helps, I have the same error message on a DS413j with a MARVELL Kirkwood 88F6282 (ARMv5TE), although I had the same behavior before the upgrade. (I didn't check for the floating point hardware error message with the older version, but syncthing never started.)  Is the problem something as simple as the GOARM=5  flag wasn't set?

**Comment by sebtic** [comment]
I found a solution waiting for an update. Just replace the binary at /var/packages/syncthing/target/bin/ by the official binary from https://github.com/syncthing/syncthing/releases/download/v0.10.30/syncthing-linux-arm-v0.10.30.tar.gz. It works like a charm on my DS413j.

**Comment by cie007** [comment]
It works!!!!!!!!! Thank you very much.

**Comment by sdkent** [comment]
Hey, thank you very much, @sebtic !  It worked for me, too.

**Comment by gpopesc** [comment]
thank you. it works for me either.

**Comment by cytec** [comment]
@Dr-Bean thanks i'll have a look at that tomorrow
