### ISSUE TITLE
airsonos

### ISSUE THREAD

**Issue by scottcawley** [SynoCommunity/spksrc#1630]
Hello all, I wonder if anyone would be interested or able to help with my interest in airsonos - which allows your Sonos devices to appear as Apple AirPlay devices on your network. People have managed to get airsonos running on their Synology boxes (link below) but I am a complete Linux novice and have no clue when it comes to following the instructions others have left. Would there be any interest in adding airsonos to the package centre? It could potentially be a great addition. Hopeful thanks for any help in advance!

(Airsonos on Synology info: https://github.com/stephen/airsonos/issues/22 )
##

**Comment by LongChair** [comment]
I would second that request, AirSonos is a great addition for sonos xpeakers and having a package on SynoCommunity for this would be really awesome. As of now the documented install procedure is quite tricky and requires some advanced skills to install.

**Comment by SteffenCL** [comment]
Thumbs up for that request! An airsonos package for synology NAS would be a great addition!

**Comment by hanssens** [comment]
Definitely +1 on this

**Comment by deluxestyle** [comment]
I like

**Comment by caracturus** [comment]
Great idea!

**Comment by Shigoru** [comment]
A Synology package would be awesome!!! Please inform me if there is something on the way!

**Comment by carukc** [comment]
It would be fantastic to have this on our Synology!  +1 here!

**Comment by Shigoru** [comment]
I found a discription on a german synology forum
http://www.synology-wiki.de/index.php/AirSonos

**Comment by kanturi** [comment]
Thumbs up for that request! An airsonos package for synology NAS would be a great addition!!!!

**Comment by FpazHn** [comment]
Totally agree!!! Ive been trying to make airsonos work but have given up!

**Comment by Bender82** [comment]
Yep that would be a great idea !

**Comment by Shigoru** [comment]
is there a way to get this on kickstarter?

**Comment by carukc** [comment]
bounty source: https://www.bountysource.com/ might be better

**Comment by MarcoBischero** [comment]
Would be a great idea!

For anyone that couldn't install airsonos on synology nas I suggest this: https://github.com/stephen/airsonos/issues/22

**Comment by KaZaAnova** [comment]
Yes please!
