### ISSUE TITLE
Synocumminy Server DOWN ?

### ISSUE THREAD

**Issue by topper2830** [SynoCommunity/spksrc#1633]
sinds today my synocommunity page is empty
iwas checking my sickbeard and couchpotato version.
I readded the with link http://packages.synocommunity.com

for a moment the library was back and then 5 min later again empty ?
what's going on ? server update ?

**Comment by anchor-detail** [comment]
I'm having some trouble downloading FlexGet for the first time. I was hoping I could install from a package. Website says that it's included but it doesn't appear in Package Center. I was able to get Python installed (and other packages) and restarted Synology afterwards, but FlexGet still not there.

**Comment by Dr-Bean** [comment]
The repo is up and running, so it seems to me to be a local issue on your side. Refresh Package Center, wait a minute, then check again.

@anchor-detail: Did you notice Flexget is only available via the beta channel? If our other packages do appear in your Package Center, it's unrelated anyway.

**Comment by anchor-detail** [comment]
Thanks @Dr-Bean I didn't realize there was a separate channel. Does that mean that FlexGet isn't fully supported? Like can I get a stable version through SynoCommunity?

**Comment by Dr-Bean** [comment]
Upfront: I'll answer the question, but I'd prefer that you open a separate issue if you want to continue this discussion as it's off topic.
Currently, there's only a beta version of the Flexget package. One of the things that helps getting packages moved to stable is sufficient feedback, especially if we (maintainers) don't use the package ourselves.

You can switch over to the beta channel quite easily via the Package Center settings, it's not a separate repository.
In doing that, it means accepting the risks applicable to running a beta package: it might break under certain conditions, or be broken. Feedback on (beta) packages is welcome, so the problems you run into can be fixed (in due time, please be patient if we don't fix your problem right then and there), or you can help us out by opening a Pull Request with your improvements.

**Comment by anchor-detail** [comment]
Got it! Thanks for your help. I'm installing it now and I'll be happy to provide beta feedback.

**Comment by topper2830** [comment]
repo is back up , thnx
