### ISSUE TITLE
ldap library not installed for OwnCloud

### ISSUE THREAD

**Issue by romu70** [SynoCommunity/spksrc#1637]
Hi,
I've activated the Synology Directory Server module to connect applications. And the first one I would like to connect is OwnCloud. Problem is I can't activate the OwnCloud's "LDAP user and group backend" because of an unsatisfied dependency : "the ldap library is not available".

Any idea how to fix this? Thanks.

**Comment by Dr-Bean** [comment]
5 second search: Enable `ldap` in the PHP extensions.
Note that we're not going to help you with configuring it...

**Comment by romu70** [comment]
Sorry, thought it could be related to the integration in the Syno repo. Another question, I guess the last one, as we can install OwnCloud with a single click, how can I change the php extensions?

Thanks.

**Comment by Diaoul** [comment]
In DSM, Web Services.

**Comment by romu70** [comment]
Great, thanks.
