### ISSUE TITLE
Flexget Package, Python and Pyload

### ISSUE THREAD

**Issue by dontomasini** [SynoCommunity/spksrc#1640]
Hi!
When trying to install the Flexget package from synocommunity it requires the user to install Python from there to. However, if you do so, the webserver of Pyload is not reachable anymore (Using a DS215J, but other users have reported the same issue with different ds).
Given that python 2.7.9 is already installed on the ds, why does the package even require to install Python (again) from synocommunity?

**Comment by Martijn085** [comment]
Because the package is only made for the Python version from SynoCommunity. Other python versions use other paths and will not work correctly.

The web interface has been removed in the latest update, more information about this you can find here https://github.com/SynoCommunity/spksrc/issues/1508

**Comment by dontomasini** [comment]
Thanks for your answer.
I meant the pyload web interface. It is not working anymore after installing the python package from SynoCommunity. After uninstalling the Python package and rebooting the pyload web interface works again.

**Comment by Dr-Bean** [comment]
I don't know how you installed pyLoad, and we can't provide support on non-SynoCommunity packages. As a suggestion, check that you specifying the correct Python executable (always use the full path) when starting pyLoad.
When #1603 is merged, we'll provide a pyLoad package on the repository.

As for why we release our own Python package, iirc SynoCommunity had a Python package before Synology...
Apart from that, Synology's package is way too limited and outdated to do anything useful for us, it's missing a lot of modules and libraries that we rely on, so we add those ourselves.

**Comment by dontomasini** [comment]
I installed the only available pyload package (to my knowledge) for my DS from http://spk.unzureichende.info/ 
Thanks for your detailed and helpful answer!

**Comment by Dr-Bean** [comment]
Heh, that package actually includes it's own Python. The problem is, it doesn't actually use it...
