### ISSUE TITLE
znc sslv3 handshake failure

### ISSUE THREAD

**Issue by doucheymcdoucherson** [SynoCommunity/spksrc#1641]
A server I connect to (that used to work) is refusing to handshake with sslv3:

````[Apr 10 / 06:16 PM] <*status> Disconnected from IRC (error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure). Reconnecting...````

I believe this is due to security hardening on the server side. They have probably disabled sslv3 due to security vulnerabilities like POODLE. According to ZNC release notes in 1.6, sslv3 is disabled, and you can specify the protocols you want to enable in config. http://wiki.znc.in/Configuration - see the "SSLProtocols" section. 

Can ZNC be upgraded to 1.6 in the repo?

**Comment by Dr-Bean** [comment]
See #1457, upgrading ZNC to 1.6.0 is already being discussed. It's on hold right now, until we figure out how to handle it.
