### ISSUE TITLE
Error while updating Gate One to latest package revision

### ISSUE THREAD

**Issue by Zarek999** [SynoCommunity/spksrc#1642]
Hello SynoCommunity,

This morning I see an update for the Gate One package (version 20150311-5), so I try to install it.
Unfortunatly this won"t install, I have an error "Failed to update package [Gate One].".

I don't know where to obtain more infos on the error. If you tell me where to find these detailed infos, I can provide more infos to you.

I am on a DS411 with the last firmware : DSM 5.1-5022 Update 4.

Thanks for all your great works :-)
##

**Comment by Dr-Bean** [comment]
It should have told you that the new GateOne package isn't backwards compatible, and that you have to uninstall the previous version before installing the new one (and manually migrate your config over to the new package). Didn't it show that information?

**Comment by Zarek999** [comment]
Sorry but no it doesn't show me this message. I only see the error messagein the DSM notifications.

**Comment by Dr-Bean** [comment]
I see what you mean...it seems that behavior is somewhat broken if you install via Package Center: It shows the message very briefly, and in the wrong place. It does work when you install the package manually.
@Diaoul I think `"qupgrade": true` causes that. Could that be turned off for a bit? We need to figure out a way to properly implement it in the framework anyway, but this does make it more difficult :/

Anyway, @Zarek999, to upgrade to the latest version of Gateone, uninstall/reinstall the package, that's what the message would say if it was shown ;)

**Comment by Zarek999** [comment]
Thanks for your help.

I've been able to install the new version with uninstall/reinstall the package.

**Comment by Diaoul** [comment]
It should be implemented in spkrepo. I'll check what's going on.

**Comment by Dr-Bean** [comment]
I thought it was a database field, but after looking at the code, it's not. That might make it a bit more difficult to test then :)
