### ISSUE TITLE
Unable to change port Gate One

### ISSUE THREAD

**Issue by DcR-NL** [SynoCommunity/spksrc#1643]
I've changed the **port** variable inside **/var/packages/gateone/target/var/conf.d/10server.conf** to **44444**, but after restarting the package it still uses the default port (8271). I'm sure it's loading the config because I also changed the **url_prefix** value.

Am I missing something? Gate One or package error?

**Env:**
Version: 20150311-5
NAS: DS713p
DSM: 5.2-5532 Update 1

**Changed config values:**
```
            "port": 44444,
            "url_prefix": "/something/",
```

**Full startup log (debug):**
```
[I 150411 20:37:02 server:4172] Gate One License: AGPLv3 (http://www.gnu.org/licenses/agpl-3.0.html)
[I 150411 20:37:03 server:4181] Imported applications: Terminal
[I 150411 20:37:03 server:4333] Version: 1.2.0 (20150205214929)
[I 150411 20:37:03 server:4334] Tornado version 4.1
[I 150411 20:37:03 server:4354] Connections to this server will be allowed from the following origins: '*'
[W 150411 20:37:03 server:4383] Logging is set to DEBUG.  Be aware that this will record the keystrokes of all users.  Don't be evil!
[I 150411 20:37:03 server:3671] No authentication method configured. All users will be ANONYMOUS
[I 150411 20:37:03 server:3752] Loaded global plugins: gateone.plugins.editor, gateone.plugins.help
[I 150411 20:37:03 server:4475] Listening on https://*:8271/
[W 150411 20:37:03 server:4503] Multiprocessing is disabled.  Performance will be sub-optimal.
[I 150411 20:37:03 server:4528] Process running with pid 15103

```

**Comment by Dr-Bean** [comment]
I'd simply search for all occurrences of `8271`, see what comes up. 
Take a look at `90custom.conf`: that might overrides the settings in `10server.conf`.

**Comment by DcR-NL** [comment]
Oops, sorry, changing it inside ```90custom.conf``` fixed it. Thank you!
