### ISSUE TITLE
how to precompile "netifaces" python-module?

### ISSUE THREAD

**Issue by wind-rider** [SynoCommunity/spksrc#1644]
I'm trying to install https://home-assistant.io/. It is a promising home automation server.

It depends on netifaces which is usually installed by pip3. However, DSM lacks gcc and therefore the module cannot be compiled on the NAS.

I found that @Diaoul recommended to precompile it and put it in the SPK:
http://www.nas-forum.com/forum/topic/33743-python-synocommunity/

@Diaoul, could you explain how to do that?

**Comment by Diaoul** [comment]
The same way it's done by other python modules. Wheel or built in python
SPK. Check out the source code.

**Comment by wind-rider** [comment]
It is not entirely clear to me what you meant. My goal was to make a package not only for the precompiled module, but for the whole application.

Do I need to follow the examples of e.g. flexget / octoprint that seem to make wheels out of the modules? (Python packaging is new to me and some explanation is very welcome :) )

**Comment by cytec** [comment]
to make a SPK for it check out `flexget` and other python based SPK's to include a compiled version of the module you'll have to use `wheels` (like flexget does)

**Comment by Dr-Bean** [comment]
Netifaces contains C-code. Take a look at the Mercurial package, the way that's setup is quite similar then.

**Comment by wind-rider** [comment]
Thank you for the hints, I'll continue trying next weekend :) this week is a busy one for me

**Comment by Dr-Bean** [comment]
Did a quick test, creating a wheel works.
