### ISSUE TITLE
group permisisons for /dev/ttyUSB* and /dev/ttyACM*

### ISSUE THREAD

**Issue by gkroone** [SynoCommunity/spksrc#1650]
I see multiple packages(Domoticz, lirc,.. )  adding support for USB serial devices, and each package handles the permission setting of these devices on it's own, but all I've seen so far is that they set the permission to 666 or even 777?? for /dev/ttyUSB*, which seems to me like it's insecure.

now for domoticz RFlink funtionality, /dev/ttyACM\* also needs to be made accessible to the domoticz package, as the arduino boards reports to DSM as such.

I know ubuntu has a default group called "dialout" which gets added to all the serial ports, and users needing access to such ports get added to group "dialout". would it be possible and feasible to do something similar on DSM?

Setting the permissions and group could be easily done by adding a udev rules file into /lib/udev/rules.d

I've prepared a rules.d file for /dev/ttyACM\* to set it to permission 666, but prefer to add a group to subscribe to if possible. currently group dialout doesnt exist on DSM.
##

**Comment by Dr-Bean** [comment]
I looked at the underlying code for Lirc and Domoticz (briefly), but neither package currently sets permissions afaict? Maybe I missed that particular line of code: if so, link to them here please, that makes it easier to discuss.
If you're talking about open PR's (as is the case for Domoticz, I believe), you can link to that too.

Anyway, the group approach might work, although there are several methods to handle this if I'm not mistaken. I can't seem to find it, but I believe this was mentioned before somewhere? /cc @Decipher @bru7us @jorikcaljouw

**Comment by gkroone** [comment]
For domoticz, the permission is set in the following file:
https://github.com/gkroone/spksrc/blob/openzwave/spk/domoticz/src/dsm-control.sh

I made a modification to the file to copy the below file into /lib/udev/rules.d but I realize this is most likely not the place to put it( just don't know what the proper way is to copy a file to a DSM system folder.)
https://github.com/gkroone/spksrc/blob/openzwave/spk/domoticz/src/50-usbttyacm.rules

as for other packages in spksrc setting permission 666, I thought is saw it, but probably not in spksrc as I can't find it either. I do wonder how lirc copes with the permissions issue though(does lirc run as root?)

At least others are suggesting setting permissinos to 666 on /dev/ttyUSB0 elsewhere.
http://forum.synology.com/enu/viewtopic.php?f=155&t=82843&start=105

**Comment by bru7us** [comment]
I can only speak to the LIRC package - yes it runs as root - and I didn't take any actions to provide a secure solution. Functionality was the goal over security when I put the package together.

The socket permissions are also explicitly set to 777 to allow control via web interfaces on the box - again, for desired functionality. There is an assumption in place that installation of such a package would only take place on a box that is secured by other means.


As far as managing shared drivers, there isn't really a good way to do so in the current environment.
Ideally someone could create a shared package to manage any/all required drivers and then individual packages would provide a config for the driver manager to parse on startup and activate modules, apply permissions, etc. Any package that requires driver configuration would then simply provide the driver manager as a dependency.
