### ISSUE TITLE
Bit TorrentSync don't install on synology DS713+

### ISSUE THREAD

**Issue by synorodon** [SynoCommunity/spksrc#1652]
All seems perfect and final install (after package download)
 launch after installation checked

message : échec de l'installation

thanks for your attention

**Comment by piwi82** [comment]
BitTorrent Sync package from SynoCommunity is obsolete.
Download and install from the official BitTorrent website : http://help.getsync.com/customer/portal/articles/1888507-synology
If youy need further support, contact the BitTorrent Sync team : http://forum.bittorrent.com/forum/111-bittorrent-sync-for-nas-network-attached-storage/

**Comment by Dr-Bean** [comment]
@synorodon Verify that you have executed the steps mentioned here: 
https://synocommunity.com/#easy-install, if you're going for the BTSync 1.4 package (@piwi82's link is for BTSync 2.0)
