### ISSUE TITLE
Parse Error trying to first run ownCloud

### ISSUE THREAD

**Issue by 3ND-U53R** [SynoCommunity/spksrc#1656]
I'm trying to run a clean install of ownCloud and am getting the following error instead of the ownCloud first run login screen.

"Parse error: syntax error, unexpected '@', expecting ')' in /volume1/web/owncloud/config/autoconfig.php on line 6"

My config:
Synology DS214 DSM 5.1-5022 Update 4
MariaDB 5.5.41-0029
SynoCommunity ownCloud 8.0.2-6

I don't know if this is an issue with my installation/config or if this is something to do with the source. Please help and thank you.

**Comment by Dr-Bean** [comment]
Check with a different browser, make sure that no plugins or addons are blocking page components, and do a Ctrl-F5 to clear the cache of your browser.

**Comment by 3ND-U53R** [comment]
Thank you Dr-Bean for your prompt response.

Same result through Arora, Firefox and Chromium.

I notice Line 6 in autoconfig.php is dbpass. My password contains special characters. Could my password be conflicting with this value? Should I try changing the password to just alpha-numeric characters?

**Comment by Diaoul** [comment]
That should work indeed.

**Comment by 3ND-U53R** [comment]
Awesome! Removing the special characters from the password worked like a charm! 

Thank you both for your help and time. I greatly appreciate it.
