### ISSUE TITLE
Downloading wheels for python3 during packaging

### ISSUE THREAD

**Issue by wind-rider** [SynoCommunity/spksrc#1658]
During packaging, https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.wheel.mk#L52 takes care of downloading all required wheels for the spk.

However, I see in the `wheelhouse` that python2 versions of the wheels are being downloaded. This makes that at install-time I need the `--no-index` parameter so that the packages will be actually downloaded on the nas itself as python3 versions.

How can I make sure the right `pip` is called so that I can add --no-index for my pull request (https://github.com/SynoCommunity/spksrc/pull/1655)?

**Comment by Diaoul** [comment]
Is that solved by hardcoding pip3 instead of pip?

**Comment by Dr-Bean** [comment]
Ideally, you'd want to be able to switch between pip and pip3 somehow (maybe override it in the Makefile), but yes, hardcoding should fix it. As long as Python3 is installed on the host obviously...

**Comment by Diaoul** [comment]
Yes, I want to implement some switch mechanism but first need to check if it works by using pip3 ;)
If it does we can maybe include `python-cc.mk` and put the PIP definition there.

**Comment by Dr-Bean** [comment]
Hm. Python-cc.mk only works when you've cross-compiled Python[2/3] first. We really only want to do that when there's a need to cross-compile. That functionality works already, because we create wheels via `$(PYTHON) -m pip bdist_wheel`, so we don't use the $(PIP) variable at all.

On the other hand, when we create pure-python wheels, $(PIP) (or $(PIP3) for that matter) is defined in common.mk. It works independently, because it uses the host's Python (so it doesn't need a cross-compiled Python.
We specifically don't want to have to cross-compile Python before creating a pure-python wheel...

**Comment by Dr-Bean** [comment]
The setup works like this:
- `apt-get python3 python3-pip`
- change common.mk's `PIP = pip` to `PIP = pip3`
- Build a set of wheels: you end up with `<name>-py3-none-any.whl` files

Now all we need is a way to tell the Makefile to use `pip3` when we want to ;)

**Comment by wind-rider** [comment]
Is it maybe possible to use some variable like `PYTHONVERSION` in `spksrc.common.mk` to set `PIP`?

I can't search easily now, I'm not at home.

**Comment by Dr-Bean** [comment]
Well, the easy way out is set `PIP ?= pip` in common.mk, and override it from your Makefile (as in: add `PIP = pip3`).
You could make things more complicated/sophisticated, but not sure if we should...

**Comment by wind-rider** [comment]
I did as you said:
- `apt-get install python3 python3-pip`
- change spksrc.common.mk's `PIP = pip` to `PIP ?= pip3`
- add `PIP = pip3` to Makefile

For most python-only wheels this seems to work. However, for two python-only wheels I get build errors using pip3, while they went ok with pip. This is probably caused by their setup.py files being in utf-8 while apparently pip3 expects ascii??

Can you help me finding out why pip3 doesn't play well with utf8?
``````
Building wheels for collected packages: phue,python-libnmap,python-nest,python-pushover
  Running setup.py bdist_wheel for phue
  Destination directory: /spksrc/spk/homeassistant/work-armadaxp-5.1/wheelhouse
  Complete output from command /usr/bin/python3 -c "import setuptools;__file__='/spksrc/spk/homeassistant/work-armadaxp-5.1/wheelbuild/phue/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /spksrc/spk/homeassistant/work-armadaxp-5.1/wheelhouse:
  Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 151: ordinal not in range(128)

----------------------------------------
  Failed building wheel for phue
  Running setup.py bdist_wheel for python-libnmap
  Destination directory: /spksrc/spk/homeassistant/work-armadaxp-5.1/wheelhouse
  Running setup.py bdist_wheel for python-nest
  Destination directory: /spksrc/spk/homeassistant/work-armadaxp-5.1/wheelhouse
  Complete output from command /usr/bin/python3 -c "import setuptools;__file__='/spksrc/spk/homeassistant/work-armadaxp-5.1/wheelbuild/python-nest/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /spksrc/spk/homeassistant/work-armadaxp-5.1/wheelhouse:
  Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 591: ordinal not in range(128)

----------------------------------------
  Failed building wheel for python-nest
  Running setup.py bdist_wheel for python-pushover
  Destination directory: /spksrc/spk/homeassistant/work-armadaxp-5.1/wheelhouse
Successfully built python-libnmap python-pushover
Failed to build phue python-nest
Cleaning up...
``````

**Comment by wind-rider** [comment]
I found a possible workaround at https://github.com/rbarrois/python-semanticversion/issues/13:
"An alternative fix is to set
`LANG="en_us.UTF-8"`
in .bashrc of the user that does the pip install"

**Comment by Dr-Bean** [comment]
I don't have that issue on a basic Debian Jessie setup (no Docker), so that's weird. What are you working on?

**Comment by Diaoul** [comment]
Maybe we can use pip from native/python3?

**Comment by Dr-Bean** [comment]
Doesn't Jessie ship Python3 by default? Because (then) the only thing needed is to install python3-pip.

**Comment by wind-rider** [comment]
I'm using the official Docker image, I run it with
````
docker run -it -v /path/to/spksrc:/spksrc synocommunity/spksrc bash
````
in Ubuntu 14.04 LTS.

@Diaoul using native/python3 sounds also good to me, because there is a working pip in there, only I don't know how to call / use that environment from my makefile

**Comment by Dr-Bean** [comment]
I can reproduce it on Docker too. Seems related to not setting the locales. Something like this might be necessary in the Docker file: http://jaredmarkell.com/docker-and-locales.

**Comment by wind-rider** [comment]
Great, thanks for such a quick solution. Could you update the Dockerfile with that?

I'll continue with building the dependencies of my spk :)

**Comment by Dr-Bean** [comment]
Opened #1661. @Diaoul, are you okay with this approach, or did you have something else in mind? 
Not sure if the Docker image is rebuilt automatically (and if not: I can't upload it myself anyway), hence the PR.

**Comment by wind-rider** [comment]
I'm having some problems with python-only wheel dependencies - I didn't put them in the requirements.txt (I want to keep it clean).

I thought that removed the --no-deps options from pip in installer.sh and spksrc.common.mk, but they are still not downloaded. Should I do something else?

**Comment by Dr-Bean** [comment]
I'm not sure what you mean. To be clear: You should approach the content of `WHEELS` exactly the same as you'd approach `DEPENDS`: add all the requirements needed for the package to work on a Synology.
If a module is not defined in `WHEELS`, it won't be downloaded or created via the framework, and can't be installed during package installation.

So, in most cases, the modules you add to `WHEELS` (either by specifying the modules directly, or by using `src/requirements.txt`) are the same as in the original software's setup.py or requirements.txt.
The main exception is if you use modules that are part of the Python package: you don't need to add those, because they are made available by using `--system-site-packages` when creating the virtual environment.

Removing `no-deps` means that (depending on where you remove it: in the framework or the package's installer.sh), dependencies of requirements are downloaded or installed too, and if that's not necessary, then you're adding bulk to the package that's not needed.

**Comment by wind-rider** [comment]
I meant that I wanted to keep requirements.txt close to the upstream version. There only the top-level wheels are listed. Their dependencies and subdependencies are not listed.

I didn't think of it that dependencies might be optional and shouldn't be installed.

**Comment by Dr-Bean** [comment]
Ah, ok. The main goal of a requirements.txt is to be able to do repeatable installations.
The idea is that if you execute `pip install --no-deps -r requirements.txt`, you're supposed to end up with everything you need to run the application.
If the application doesn't work with just those requirements, then you should ask upstream to update their requirements.txt. Or...run with an out-of-sync requirements.txt ;)

**Comment by Diaoul** [comment]
Exactly @Dr-Bean, nothing to add.

**Comment by Dr-Bean** [comment]
To finalize the last detail: #1661 is merged, so after the docker image is updated, you should be good with creating wheels for Python3 :)

**Comment by wind-rider** [comment]
Yes, thank you very much :) I closed this issue already because of your pull request, I'll test it later today or tomorrow.
