### ISSUE TITLE
Can I use spksrc to build Synobox? If so how?

### ISSUE THREAD

**Issue by brimur** [SynoCommunity/spksrc#1660]
I just got a DS1815+ and to my dismay I cannot run SynoBox  from http://synobox.fr.nf/download/ because the spk is not accepted.

I have setup a Ubuntu box and setup spkrc (transmission test worked) and I would like to build the spk for SynoBox for syno-avoton-5.1

The source is here https://bitbucket.org/momiji/synobox/src but I am not proficient enough in building to know how to import that source into spksrc and then build it for my DS1815+

Any help appreciated. Thanks

B

**Comment by piwi82** [comment]
What is the trusted level set in the package center ? (https://synocommunity.com/#easy-install)

**Comment by brimur** [comment]
I set it to any publisher

**Comment by Diaoul** [comment]
Better ask the repo maintainer than SynoCommunity. This is not the usual setup so I can't answer you.
