### ISSUE TITLE
Cannot compile syncthing for armada 370

### ISSUE THREAD

**Issue by sbaramov** [SynoCommunity/spksrc#1666]
Hello,
I followed the tutorial from the https://github.com/SynoCommunity/spksrc page and I tried to compile the syncthing package for armada370. Regardless of what I try I get the following error: 

```
cd /home/vagrant/Syno/spksrc/native/go/work-native/go/src && ./make.bash
# Building C bootstrap tool.
cmd/dist
./make.bash: line 135: ./cmd/dist/dist: cannot execute binary file: Exec format error
Makefile:21: recipe for target 'myComp' failed
make[3]: *** [myComp] Error 1
make[3]: Leaving directory '/home/vagrant/Syno/spksrc/native/go'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[2]: *** [depend_target] Error 2
make[2]: Leaving directory '/home/vagrant/Syno/spksrc/cross/syncthing'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory '/home/vagrant/Syno/spksrc/spk/syncthing'
../../mk/spksrc.spk.mk:337: recipe for target 'arch-armada370' failed
make: [arch-armada370] Error 2 (ignored)
```

From the error I can see that it is trying to run `/home/vagrant/Syno/spksrc/native/go/work-native/go/src/cmd/dist/dist`. In this case, the error is completely valid because I am runing: 

```
$ uname -a
Linux vagrant-ubuntu-utopic-32 3.16.0-34-generic #47-Ubuntu SMP Fri Apr 10 18:03:41 UTC 2015 i686 i686 i686 GNU/Linux
```
and 
```
$ file /home/vagrant/Syno/spksrc/native/go/work-native/go/src/cmd/dist/dist
/home/vagrant/Syno/spksrc/native/go/work-native/go/src/cmd/dist/dist: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.16, not stripped
```

So obviously a ARM binary will not run on x86 arch. Should I create a ARM based VM and compile it there. If yes, then may be there is something wrong with the cross compile? Or may be Go does not support cross compilation? 

I did try several other architecture (bromolow and 88f6281) with exactly the same result.

**Comment by Dr-Bean** [comment]
I believe I already reported that [here](https://github.com/SynoCommunity/spksrc/pull/1631#issuecomment-90554962) and [here](https://github.com/SynoCommunity/spksrc/pull/1631#issuecomment-91195061).
You'll have more luck if you compile `native/go` first (just enter that dir, and do `make`), and then go on with compiling the arch you want.

**Comment by sbaramov** [comment]
Yes I did see issue [#1631](https://github.com/SynoCommunity/spksrc/pull/1631). However, in my ignorance, I have assumed the issue is for ARM5 only. In any case the suggested solution worked like charm. For the record: 
```
cd spksrc/
make setup
cd native/go
make
cd ../../spk/syncthing
make arch-armada370
```
Thanks for the help.
