### ISSUE TITLE
python 2.7.9 on ds214play

### ISSUE THREAD

**Issue by gborri** [SynoCommunity/spksrc#1667]
hello, 

I need to install python 2.7.9 on my synology but i can't find it. i see it is available on synoCommunity but not on my synology package center.

thanks
Giovanni

**Comment by Dr-Bean** [comment]
Are you running DSM4.3 or lower? Time to upgrade ;)

@Diaoul You didn't upload Python 2.7.9-13 for DSM4.3, I believe?

**Comment by Diaoul** [comment]
Indeed that's possible.

**Comment by gborri** [comment]
I'm on DSM 5.1 update 5

**Comment by gborri** [comment]
I have checked now and it's appeare... i dont' know why.
