### ISSUE TITLE
Owncloud: cannot enable 3th party apps

### ISSUE THREAD

**Issue by HJvD123** [SynoCommunity/spksrc#1671]
I'm running Owncloud (8.0.2) on my Synology NAS, latest DSM. All working fine, calendar also. Copied two 3rd party apps (tasks and news) to /usr/local/owncloud/share/owncloud/apps. Then tried to enable the apps within Owncloud, but they were not there. What am I doing wrong? Map settings from both apps 755 and root owner, just like the other maps.

**Comment by Dr-Bean** [comment]
Put the files in the correct place ;) `/volume1/web/owncloud` should be it.

`/usr/local/owncloud/share` is where the owncloud data is put before copying it over to the web folder during package installation.

**Comment by HJvD123** [comment]
Yep, that dit the trick. Tasks working fine. Thanks.

Then, I would like to get Outlook, cFos DAV and Owncloud to sync. You know of any tutorial for the Synology to get it to work? The cFos tutorial does not work for my setup with Synology...

**Comment by Dr-Bean** [comment]
The Owncloud package isn't all that specific to Synology, apart from some details such as file locations or accounts.

I'm not a user of Owncloud myself, so I can't help with more specific issues, and you're not providing a whole lot of details on the issues you run into. Maybe the Owncloud forums can help?
