### ISSUE TITLE
Problem install/update domoticz 2.0.2405-15

### ISSUE THREAD

**Issue by psnl** [SynoCommunity/spksrc#1677]
Hello,
When I try to update/install domoticz 2.0.2405-15 on my ds415 it fails. Previous version was working fine.
Message in /var/log/messages:
May  6 22:17:07 DiskStation codesign.php: Signature file not found in archive.

Regards,
psnl

**Comment by gkroone** [comment]
Where did you get the spk or what repository did you use to compile domoticz v2405? I am not aware of v2405 being published. I did notice that on the Domoticz source, some things were reverted in v 2418 but didn't look into the details yet. It might be something is wrong with v2405.

**Comment by psnl** [comment]
I used http://packages.synocommunity.com.
The NAS I use is the DS415+, sorry for the wrong version mentioned before. Thisvone has another processor

**Comment by gkroone** [comment]
As far as i know, the published spk from synocommunity is in the 22xx range.. Are you using the update function inside domoticz webgui? If so, that's going to cause problems as i read it tries and fails to compile, and still updates the web files. It might look like you run a new version, but in reality you run on old binaries. If that's the case, I'm not sure how to best fix your installation.

I've not yet looked at the update function in domoticz, but i think we need to remove that part from the spk as it can't work correctly.

**Comment by psnl** [comment]
I've tried to update from inside domoticz but always got the message that there was no new version available. I tried uninstalling and installing again but this also returned an error. The uninstall removed the /volume/@appstore/domoticz directoey. Is domoticz forsynology compiled for the ds415+, this uses a new/other processor

**Comment by gkroone** [comment]
What's the errors you're getting at uninstall/reinstall? 

I don't have much experience with troubleshooting spk uninstalling and installation. Maybe there's some logs you can provide.. i believe the package installer does keep a log somewhere. Not sure where though. First place i'd check is for something in /var/log

Normallt i could check for log file location on my nas, but not right now. Currently replying from mobile phone.

**Comment by psnl** [comment]
No error ocurred when uninstalled. Only during install of new version and update to  the new version. Found a log in /var/log/synopkg. But there's no lines indicating the installation of the  new version

2015/05/06 20:56:26     stop domoticz: stop version 2.0.2112-5 successfully, result 0                                                                                                 
2015/05/06 21:10:12     start domoticz: begin to start version 2.0.2112-5                                                                                                             
2015/05/06 21:10:12     start domoticz: start version 2.0.2112-5 successfully, result 0                                                                                               
2015/05/06 21:11:56     uninstall domoticz: begin to stop version 2.0.2112-5                                                                                                          
2015/05/06 21:11:59     uninstall domoticz: stop version 2.0.2112-5 successfully, result 0                                                                                            
2015/05/06 21:12:00     uninstall domoticz: Uninstall 2.0.2112-5 successfully

**Comment by Dr-Bean** [comment]
That Domoticz package (2.0.2405-15) does not come from SynoCommunity. See [here](https://synocommunity.com/package/domoticz) for the version we currently provide.
I would suggest you re-check which repositories you have in Package Center, and which might be providing that updated package.

We cannot provide any support for packages that are installed via other repositories or packages that you installed manually.

**Comment by psnl** [comment]
Removed other repositories and now  2.0.2112-5 is installing again. Sorry for the inconvenience
