### ISSUE TITLE
Tvheadend wont install

### ISSUE THREAD

**Issue by JeroenKloppenburg** [SynoCommunity/spksrc#1678]
I use latest DSM 5.1, and want to install Tvheadend 3.4.27-6 which showed up in the packages community.

After filling in admin/admin and clicking "apply" on the next window I simply get an error (in Dutch, so I might not translate to the same English message): "can not install "tvheadend"".

There is nothing in the log center related to this.

I've tried installing with Vidoestation installed and without. Tried my admin pass from DSM instead of "admin", rebooting, etc. To no avail.

There are no other messages so I'm clueless to what is causing the error.

I know this is quite a shot in the dark, but maybe its known and you can help me out here :)

Thanks!

**Comment by Dr-Bean** [comment]
Please verify that you have followed these instructions, in particular step 1: https://synocommunity.com/#easy_install

**Comment by JeroenKloppenburg** [comment]
OK I feel stupid now...

Thanks s much for replying nonetheless!

Jeroen

2015-05-08 10:52 GMT+02:00 Dr-Bean <notifications@github.com>:
