### ISSUE TITLE
dvbapi

### ISSUE THREAD

**Issue by MrOnyx** [SynoCommunity/spksrc#1686]
OSCam: 1.20 Build: r10660 install on Synlogy DS1812+ 5.2-5565
Problem with dvbapi
(dvbapi) ERROR: Can't open device /dev/dvb/adapter0/demux0 (errno=6 No such device or address)

**Comment by Dr-Bean** [comment]
We don't actively maintain or publish packages for OSCam.
As a suggestion: It seems you changed the OSCam version, and then built a package? Then revert those changes and try again.

**Comment by Dr-Bean** [comment]
Closing due to lack of response.
