### ISSUE TITLE
Mediainfo 0.7.73

### ISSUE THREAD

**Issue by llhoir** [SynoCommunity/spksrc#1688]
Current version gives problem when exported to XML (see http://sourceforge.net/p/mediainfo/bugs/886/)

**Comment by llhoir** [comment]
Current version gives problem when exported to XML (see http://sourceforge.net/p/mediainfo/bugs/886/)

**Comment by Dr-Bean** [comment]
Changed the title a bit, because the current version is 0.7.72

**Comment by Dr-Bean** [comment]
`mediainfo 0.7.73-2` has been published.
