### ISSUE TITLE
Problem compiling OpenIPMI for Zabbix on Cedarview architecture

### ISSUE THREAD

**Issue by joefrancois** [SynoCommunity/spksrc#1693]
Hello, 

I can figure out how to pass the compilation error for OpenIPMI for the Zabbix package. I have a VirtualBox running Debian 8 32bit.

Please let me know if you need more detail.

Thank you.

Here is the error I get.

make[6]: Entering directory '/home/joe/spksrc/spk/zabbix/work-cedarview/OpenIPMI-2.0.21/unix'
/bin/bash ../libtool  --tag=CC   --mode=link /home/joe/spksrc/toolchains/syno-cedarview/work/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc -Wall -Wsign-compare -I../include -I../include -I/home/joe/spksrc/spk/zabbix/work-cedarview/install//usr/local/zabbix/include   -L/home/joe/spksrc/spk/zabbix/work-cedarview/install//usr/local/zabbix/lib -Wl,--rpath-link,/home/joe/spksrc/spk/zabbix/work-cedarview/install//usr/local/zabbix/lib -Wl,--rpath,/usr/local/zabbix/lib  -o test_handlers test_handlers.o libOpenIPMIposix.la libOpenIPMIpthread.la ../utils/libOpenIPMIutils.la  -lrt
libtool: link: /home/joe/spksrc/toolchains/syno-cedarview/work/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc -Wall -Wsign-compare -I../include -I../include -I/home/joe/spksrc/spk/zabbix/work-cedarview/install//usr/local/zabbix/include -Wl,--rpath-link -Wl,/home/joe/spksrc/spk/zabbix/work-cedarview/install//usr/local/zabbix/lib -Wl,--rpath -Wl,/usr/local/zabbix/lib -o .libs/test_handlers test_handlers.o  -L/home/joe/spksrc/spk/zabbix/work-cedarview/install//usr/local/zabbix/lib ./.libs/libOpenIPMIposix.so ./.libs/libOpenIPMIpthread.so ../utils/.libs/libOpenIPMIutils.so -lrt -Wl,-rpath -Wl,/usr/local/zabbix/lib
./.libs/libOpenIPMIpthread.so: undefined reference to `pthread_condattr_setclock'
collect2: ld returned 1 exit status
Makefile:702: recipe for target 'test_handlers' failed
make[6]: *** [test_handlers] Error 1
make[6]: Leaving directory '/home/joe/spksrc/spk/zabbix/work-cedarview/OpenIPMI-2.0.21/unix'
Makefile:503: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/joe/spksrc/spk/zabbix/work-cedarview/OpenIPMI-2.0.21'
Makefile:414: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/joe/spksrc/spk/zabbix/work-cedarview/OpenIPMI-2.0.21'
../../mk/spksrc.compile.mk:36: recipe for target 'compile_target' failed
make[3]: *** [compile_target] Error 2
make[3]: Leaving directory '/home/joe/spksrc/cross/openipmi'
../../mk/spksrc.depend.mk:43: recipe for target 'depend_target' failed
make[2]: *** [depend_target] Error 2
make[2]: Leaving directory '/home/joe/spksrc/cross/zabbix'
../../mk/spksrc.depend.mk:43: recipe for target 'depend_target' failed
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory '/home/joe/spksrc/spk/zabbix'
../../mk/spksrc.spk.mk:295: recipe for target 'arch-cedarview' failed
make: [arch-cedarview] Error 2 (ignored)

**Comment by Dr-Bean** [comment]
Compile the cross package for OpenIPMI on it's own first. When that completes successfully, only then try it as part of a larger package. Try the newer toolchains first: the older, the more limitations you'll probably see. So, enter `cross/package`, and do e.g. `make arch-bromolow-5.1`

I did the same for OpenIPMI, with the basic Makefile you see below, and I did not run into issues. Compare it with yours, see if it works.
If you're wondering how I got to the `DEPENDS` entries or the `CONFIGURE_ARGS` there: the `make` process basically stops with an error. That error just about tells you what's going on.
```
PKG_NAME = OpenIPMI
PKG_VERS = 2.0.21
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://sourceforge.net/projects/openipmi/files/OpenIPMI%202.0%20Library
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/popt cross/ncurses

HOMEPAGE = 
COMMENT  = 
LICENSE  = 

GNU_CONFIGURE = 1

CONFIGURE_ARGS = --with-perl=no --with-python=no

include ../../mk/spksrc.cross-cc.mk
```

**Comment by Dr-Bean** [comment]
Closing due to lack of response.
