### ISSUE TITLE
[Subliminal 0.7.5-12 Beta] Encoding bug

### ISSUE THREAD

**Issue by cosades** [SynoCommunity/spksrc#1697]
Hi,

On my Synology DS214Play (DSM 5.2-5565), some subtitles are written with bad encoding.

For example, in French --> The.Shawshank.Redemption.1994.720p.BluRay.x264-SiNNERS.srt.

1) Download from Subliminal with OpenSubtitles provider --> ANSI as UTF8 (said by NotePad++)
2) Direct download from OpenSubtitles --> ANSI (said by NotePad++)

Differences (hex) :

GOOD ENCODING (direct dl from OpenSubtitles), extract
00000060:  3A 30 32 3A 31 31 2C 36  30 30 0D 0A 76 6F 74 72  :02:11,600..votr
00000070:  65 20 64 69 73 70 75 74  65 20 61 76 65 63 20 76  e dispute avec v
00000080:  6F 74 72 65 20 66 65 6D  6D 65 2C 0D 0A 6C 61 20  otre femme,..la 
00000090:  6E 75 69 74 20 6F F9 20  65 6C 6C 65 20 61 20 E9  nuit où elle a é
000000A0:  74 E9 20 74 75 E9 65 2E  0D 0A 0D 0A 33 0D 0A 30  té tuée.....3..0

BAD ENCODING (from Subliminal  with OpenSubtitles provider), extract
00000060:  3A 30 32 3A 31 31 2C 36  30 30 0D 0A 76 6F 74 72  :02:11,600..votr
00000070:  65 20 64 69 73 70 75 74  65 20 61 76 65 63 20 76  e dispute avec v
00000080:  6F 74 72 65 20 66 65 6D  6D 65 2C 0D 0A 6C 61 20  otre femme,..la 
00000090:  6E 75 69 74 20 6F D1 89  20 65 6C 6C 65 20 61 20  nuit oÑ‰ elle a 
000000A0:  D0 B6 74 D0 B6 20 74 75  D0 B6 65 2E 0D 0A 0D 0A  Ð¶tÐ¶ tuÐ¶e.....

Is it caused by Python 2.7.3 ?
Is there are direct solution (which .py file to modify ?)

Thank you !

**Comment by Dr-Bean** [comment]
I can reproduce this on Debian too, so it's not Synology related. Probably best if you report this on the Subliminal repository: https://github.com/Diaoul/subliminal.

Test: `./subliminal -p opensubtitles -l FR -vvv The.Shawshank.Redemption.1994.720p.BluRay.x264-SiNNERS.mp4`

**Comment by cosades** [comment]
Thank you very much, I published it under subliminal repo where other users are also experiencing difficulties about this.
