### ISSUE TITLE
Add DSM5.2 toolchains and kernels

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1703]
Synology has released the DSM5.2 toolchains and kernels a couple days ago. We'll probably want to add those in at one point or another.

http://sourceforge.net/projects/dsgpl/files/DSM%205.2%20Tool%20Chains/
http://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/

**Comment by bladehawk** [comment]
Would this address the issue where rewrite mod isn't included in the DSM download

(number 4 in the apache issues list below)
http://forum.synology.com/enu/viewtopic.php?f=232&t=79801

**Comment by Dr-Bean** [comment]
I'm not following, do you mean `mod_rewrite`? Toolchains and kernels are not related to Apache, so no. More to the point, as far as I know, `mod_rewrite` has been available for ages now, right?

**Comment by bladehawk** [comment]
I wasn't sure if it was related.  Synology stopped including it and newznab is broken without it so the package is broken.  A search on the issue pointed me at Gothic and I thought that the board was just for Newznab. 

Lance Druger
925-330-5852

**Comment by gkroone** [comment]
Back to the subject of DSM 5.2 Toolchains.. what do you think would be required for that? Would it be a simple copy if the toolchain and kernel directory  for DSM 5.1 and update the source file names etc, or is there a lot of other stuff expected to be required? I have not tried anything with it yet, but of we want to add kernel modules for DSM 5.2 to packages, i think this will be required.

**Comment by bladehawk** [comment]
I'm not sure what it would take or any dependencies.  I'm weaker in Linux than I'd like (I can get around and use VI over SSH,  simple things).  I understand infrastructure,  but I don't code, so I may not be the best person to ask. 

Lance Druger
925-330-5852

**Comment by Dr-Bean** [comment]
Yep, reuse the Makefiles and digests, but correct those for DSM5.2. Then start testing (create packages, install packages on various DSM5 versions and arches and see if the packages still work)

The main thing we want to know is if we can use the DSM5.2 toolchains for earlier DSM5 versions. The outcome of the tests determine the value for [`TC_FIRMWARE`](https://github.com/SynoCommunity/spksrc/blob/master/toolchains/syno-88f6281-5.1/Makefile#L5).
The kernels should be tested in the same way, but if those prove to be backwards incompatible, we might need some other changes to spksrc.

**Comment by Dr-Bean** [comment]
Not sure which model identifies as `alpine4k` (could be either DS215+, DS715 or both), but we should set `TC_ARCH = alpine alpine4k` in the Alpine 5.2 toolchain Makefile.

For x64, we could consider setting `TC_ARCH = x86 bromolow cedarview avoton bromolowESM braswell grantley broadwell`, although a number of the associated models haven't been released yet (and that might never happen for all we know).

**Comment by gkroone** [comment]
@Dr-Bean, I started creating the new toolchain and kernel directories and already I have most of the toolchains setup and kernel modules are compiling for the ones I created them. For qoriq kernel modules, I had to add a patch to make them compile, which I found on bugzilla for an earlier kernel version and modified so it applies. It can use some cleanup as it applies with offset messages, but works for now.

I don't really understand the whole toolchain process, what TC_FIRMWARE does and how the stuff with multiple TC_ARCH does, but I implemented what you described above.

I'll be creating a new branch for the DSM5.2 toolchains on github soon, so you can have a look at what I created.

**Comment by gkroone** [comment]
also it's unclear to me why there's multiple toolchains posted for the same arch, so I picked the most obvious ones, but unsure if that's correct.

**Comment by Dr-Bean** [comment]
Nice :) I had been working on it myself a day or so ago: just about finished the toolchains, and was halfway through the kernels (well, setting the code changes up anyway, didn't start downloading/compiling those yet)

Btw, what I was working on for the kernels was add the same approach with `DISTRIB_DIR` as we did with the toolchains: download them into a separate directory under `spksrc/distrib` (so the kernels are stored in `/spksrc/distrib/kernels/{version}`, because Synology apparently isn't adding the version in the filename anymore.

**Comment by Dr-Bean** [comment]
For the choice of toolchains, iirc, you can mostly stick to the same versions of gcc/glibc as the ones used for 5.1 (adjusted for the name change, that is). I believe there was only one exception: alpine.

What `TC_FIRMWARE` does is quite simple: it sets the correct `FIRMWARE` version in INFO. During package installation, the DSM version is checked against FIRMWARE: if the DSM version is lower than FIRMWARE, the package won't show up/won't install.
The best outcome is that we can use the 5.2 toolchains/kernels to create packages for DSM5.0. After comparing at the gcc/glibc versions, I think we should be okay there, but that should be tested to make sure.

**Comment by gkroone** [comment]
Ok, at least the archs where the kernel version changed, they will need to have a way to make sure packages with kernel modules will use correct toolchain.

I just started on kernel for ppc853x, and noticed it had another workarround for the bug patch I used for qoriq, which I removed, and replaced by the patch. this seems to compile the kernel modules just fine.

by compiling the kernel modules, do I also confirm the toolchain for such arch basically works? 

Also I noticed that for at least x64 and ppc853x
make clean
and  
make digests 
fails after the work/tc_vars.mk has been created. (first make command runs fine, but then the next comes up with errors and bugs out)

after manually removing work directory, the make digests works fine.

**Comment by gkroone** [comment]
I got all the arch's to build kernel modules, except armada375.

here's my initial committed work:
https://github.com/gkroone/spksrc/tree/DSM5.2-toolchains

building armada375 gives the followiing error. any help welcome.

  HOSTLD  scripts/mod/modpost
  HOSTCC  scripts/kallsyms
scripts/Makefile.build:44: /home/vagrant/spksrc/kernel/syno-armada375-5.2/work/source/linux/arch/arm/mach-armada375/../plat-armada/mv_drivers_lsp/mv_mux/Makefile: No such file or directory
make[2]: *** No rule to make target `/home/vagrant/spksrc/kernel/syno-armada375-5.2/work/source/linux/arch/arm/mach-armada375/../plat-armada/mv_drivers_lsp/mv_mux/Makefile'.  Stop.

**Comment by Dr-Bean** [comment]
> I just started on kernel for ppc853x, and noticed it had another workarround for the bug patch I used for qoriq, which I removed, and replaced by the patch. this seems to compile the kernel modules just fine.

Err...why not keep the original approach? Qoriq and ppc853x are basically the same toolchain/kernel, and that patch hasn't changed since it was introduced with 4.3.

>by compiling the kernel modules, do I also confirm the toolchain for such arch basically works?

Mostly :) You want to know that the kernels compile without errors anyway. Overall, it's the step before testing with actual packages, because that's the best confirmation you can get ;)

>Also I noticed that for at least x64 and ppc853x [..] fails after the work/tc_vars.mk has been created. (first make command runs fine, but then the next comes up with errors and bugs out)

Please be more specific, what is the exact output you're getting? I have not seen issues like that.

As for Armada375's kernel, it needs a fix. Should be implemented on Synology's side really, but we can put it in spksrc for the time being (`plat-armada` should be a symlink to `plat-armada-v2`, or at least that was the fix applied to 5.1). 
I'll enter a ticket for it once I can confirm that the rest of the kernels work as expected.

I hope you don't mind that I'll continue with my own updates for the time being. Reasons being that I believe you've started with different toolchains (e.g. using the older gcc/glibc versions, so those all need to be checked and changed if needed), and I'm including some other related changes to make things more manageable. Problem is, I'll get merge conflicts if I merge your commit, and I'd rather not have to redo my changes manually.

**Comment by gkroone** [comment]
No problem. I'll switch to yours as soon as you publish something. Would you mind committing to another branch while working on it or prefer to keep it to your local system till you're ready to submit a PR?

**Comment by gkroone** [comment]
note that I just learned that qoriq is still running glibc 2.8 and the latest glibc2.13 toolchain is incompatible with that.

**Comment by Dr-Bean** [comment]
Yep. That's why I said to largely keep using the same ones as used with 5.1 somewhere up above. Synology would want to stay backwards compatible within the same major DSM versions at least.

They might switch over with DSM6.0, but especially for older arches, I'm not counting on it.

**Comment by gkroone** [comment]
Regarding armada375, I was unable to find the fix you mentionned. Did that get removed due to synology  updating their GPL sources for 5.1?
With your suggested fix seems to get past the previous point, but i'm still compiling.

Here's what I did in the armada375 Makefile:

kernel_armada375_premake:
        $(RUN) mv $(WORK_DIR)/source/linux/arch/arm/plat-armada $(WORK_DIR)/source/linux/arch/arm/plat-armada.bak
        $(RUN) ln -s $(WORK_DIR)/source/linux/arch/arm/plat-armada-v2 $(WORK_DIR)/source/linux/arch/arm/plat-armada

**Comment by gkroone** [comment]
I've compiled and tested an installed the package diskutils for x86 on my DS1511+ still running DSM 5.1 and got no errors running the executables. do you think I need to test any other packages on DSM5.1 before upgrading to DSM5.2? I waited with upgrading until I was able to create packages with kernel modules for DSM5.2, which I beleive I can now do.

Also, how are we supposed to handle updated kernels? DSM 5.2 switched to 3.10 kernel for x86, so although normal executables may run fine when built with latest TC, kernel modules won't be backwards compatible with DSM5.1.

**Comment by Dr-Bean** [comment]
Armada375 kernel issue reported to Synology a couple days ago, no response yet.
I've started building a number of alpine5.2 packages, and if all goes well, those can be put on the repo to help 215+ owners.

As for the kernel version differences for x86: most modules built with the 5.1 kernels will work fine on 5.2 (usually not the other way around). We'll probably end up doing one of three things, sorted from easy to more challenging:
- Stick with the 5.1 kernels (probably only a short term solution)
- Build and distribute 4.3, 5.1 and 5.2 packages (as long as we have the disk space ;))
- Rethink the way we build and include kernel modules. Synology includes 4.3, 5.1 and 5.2 kernel modules in one package, and copy/install the appropriate module during start-stop (iirc). 
Similarly, we could depend on `VERSION` and install one or the other module. That means that spksrc needs to know when/how to compile various versions of kernel modules....I haven't worked out how to best approach that yet. 
@SynoCommunity/developers?

**Comment by Dr-Bean** [comment]
Received confirmation from Synology on Armada375 issue. They'll skip the fix for this version, and put it in the next one (probably 6.0). Here's the oneliner I intend to use:
````
myPreCompile:
    cd $(KERNEL_DIR)/arch/arm && rm -rf plat-armada && ln -s plat-armada-v2 plat-armada
```

**Comment by psycho-realm** [comment]
Thanks for your work! I keep a close look to this forum, hopefully i can use it soon on my ds215+

**Comment by Gwengarion** [comment]
Thanks, indeed! I also want to start installing some packages in my ds215+! Good luck!!

**Comment by Dr-Bean** [comment]
Finalizing the kernel changes: We're going for option two for now (short/mid term), `Build and distribute 4.3, 5.1 and 5.2 packages`.
The firmware versions of the 5.2 toolchains are set to `5.2-5565` for x86/64 arches, and are set to `5.0-4458` for all the others.

So, from a repo perspective, build and publish DSM5.1 x86/64 packages (avoton, bromolow, cedarview, x86) manually after building packages with the default `all-supported` rule. (I might change the rule if it proves to be too much of a hassle, but atm: meh)
I'll merge the changes later today.

**Comment by Dr-Bean** [comment]
And done with https://github.com/SynoCommunity/spksrc/commit/c2fd955c98883c23909d73a1a430af5d5dd300a6, https://github.com/SynoCommunity/spksrc/commit/26e134fe88b4b672aa91151ac6c29160bfc18d96, https://github.com/SynoCommunity/spksrc/commit/d933d45166d45a80ffd916bb61b5e04a15b6035b and https://github.com/SynoCommunity/spksrc/commit/422c15cef6a87fc0e3ad1ed063557b6160130394.

Note that by default, kernel files will be re-downloaded, courtesy of https://github.com/SynoCommunity/spksrc/commit/ffd9bd6ca15a4ec979fe0dc88d0e3738de0ae9b5. Prevent that by moving them to `$(DISTRIB_DIR)/$(KERNEL_DIR)/$(PKG_BRANCH)`.
