### ISSUE TITLE
Support gzip for haproxy => save bandwith + time

### ISSUE THREAD

**Issue by piejanssens** [SynoCommunity/spksrc#1704]
```
make USE_ZLIB=yes
```

If haproxy is compiled using USE_ZLIB=yes it is possible to use gzip to compress a lot of data.
For example you could add this to your default config section:

```
 compression algo gzip
 compression type text/html text/plain text/css
```

There are many more compression types available.

**Comment by Diaoul** [comment]
Can you open a PR to update the default configuration?

**Comment by MattPark** [comment]
since this update -- haproxy won't start for me if I use the previous version's config
I tried reinstalling which worked, but once I replaced the previos config it won't start

**Comment by MattPark** [comment]
So it's mad about this section -- specifically bind :80
basically, the start-stop-status script has a RUNAS=haproxy
This should be RUNAS=root

then the haproxy.cfg.tpl should say: 
```
global
    user haproxy
```

This is still secure because haproxy will drop privs after it binds where it needs to.

**Comment by quydo** [comment]
hi, does haproxy support gzip for image, such as image/png, image/jpg

I how can I check it if haproxy support

Many thanks,

**Comment by Diaoul** [comment]
@piejanssens: can you make a PR with the updated configuration?

**Comment by piejanssens** [comment]
I'll give it a try today.
