### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by cimnine** [SynoCommunity/spksrc#1705]
Has anyone ever tried to create an elasticsearch package?
##

**Comment by cytec** [comment]
someone did something for logstash here: https://github.com/SynoCommunity/spksrc/pull/1347

installing elasticsearch is basically pretty simple i think (install java, copy the files to DS and run it) not sure if there is an Package needed at all...

**Comment by Dr-Bean** [comment]
Closing in favor of #2535.
