### ISSUE TITLE
No connection to ffsync possible

### ISSUE THREAD

**Issue by prad1978** [SynoCommunity/spksrc#1710]
I have installed ffsync and i can reach the ffsync-server with the public url https://m.familie-xxx.at:8132/token/1.0/sync/1.5 in the browser: {"status": "error", "errors": [{"location": "body", "name": "", "description": "Unauthorized"}]}

(https: over web-proxy!)

The Firefox about:sync-log says:
1432272037966	Sync.LogManager	DEBUG	Flushing file log
1432272037966	Sync.LogManager	TRACE	Beginning stream copy to error-sync-1432272037966.txt: 1432272037966
1432272037967	Sync.Service	DEBUG	Exception: TypeError: url is null (resource://services-sync/record.js:246:8) JS Stack trace: RecordMgr_get@record.js:246:9 < onNotify@service.js:1313:18 < WrappedNotify@util.js:148:21 < WrappedLock@util.js:103:16 < _lockedSync@service.js:1285:12 < sync/<@service.js:1277:14 < WrappedCatch@util.js:77:16 < sync@service.js:1265:5
1432272037990	Sync.LogManager	TRACE	finished copy to: P:\PortableApps\FirefoxPortable\Data\profile\weave\logs\error-sync-1432272037966.txt
1432272037990	Sync.LogManager	TRACE	onCopyComplete: 1432272037990
1432272037990	Sync.LogManager	TRACE	Scheduling cleanup.
1432272037991	Sync.LogManager	DEBUG	Log cleanup threshold time: 1431408037991
1432272038096	Sync.LogManager	DEBUG	Done deleting files.
1432272516902	Sync.ErrorHandler	DEBUG	Beginning user-triggered sync.
1432272516902	Sync.Service	DEBUG	User-Agent: Firefox/38.0.1 FxSync/1.40.0.20150513174244.
1432272516902	Sync.Service	INFO	Starting sync at 2015-05-22 07:28:36
1432272516903	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1432272516904	Sync.Status	INFO	Resetting Status.
1432272516904	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1432272516905	Sync.BrowserIDManager	INFO	Failed to fetch the cluster URL: ({details:(new TokenServerClientServerError("Authentication failed.", "resource://gre/modules/services-common/tokenserverclient.js", 36))})
1432272516906	Sync.Service	DEBUG	Cluster value = null
1432272516906	Sync.Status	DEBUG	Status.sync: success.sync => error.sync.reason.no_node_found
1432272516906	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1432272516906	Sync.Synchronizer	INFO	No cluster URL found. Cannot sync.
1432272516906	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1432272516906	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 3752864 ms.
1432272516907	Sync.SyncScheduler	DEBUG	Next sync in 3752864 ms.

How can I make it functional for me?
regards peter
Falls eine Kommunikation in Deutsch möglich wäre, wäre das viel einfacher für mich. ;-)

**Comment by Dr-Bean** [comment]
I don't know what you mean exactly with `https: over web-proxy!`, but if your definition of web proxy is what I think it is, that's the source of your problem.

I would suggest to start off with the basic setup first: plain old http, internally. If that works, check if http externally works (make sure that you're not syncing anything private, if that's your concern). Setting up https is the last step.

**Comment by prad1978** [comment]
I have also tried the Sync with a NAT, but there is also the same problem.

Firefox-Log:

1432283478368	Sync.LogManager	DEBUG	Flushing file log
1432283478368	Sync.LogManager	TRACE	Beginning stream copy to error-sync-1432283478368.txt: 1432283478368
1432283478369	Sync.Service	DEBUG	Exception: TypeError: url is null (resource://services-sync/record.js:246:8) JS Stack trace: RecordMgr_get@record.js:246:9 < onNotify@service.js:1313:18 < WrappedNotify@util.js:148:21 < WrappedLock@util.js:103:16 < _lockedSync@service.js:1285:12 < sync/<@service.js:1277:14 < WrappedCatch@util.js:77:16 < sync@service.js:1265:5
1432283478404	Sync.LogManager	TRACE	finished copy to: P:\PortableApps\FirefoxPortable\Data\profile\weave\logs\error-sync-1432283478368.txt
1432283478404	Sync.LogManager	TRACE	onCopyComplete: 1432283478404
1432283478404	Sync.LogManager	TRACE	Scheduling cleanup.
1432283478404	Sync.LogManager	DEBUG	Log cleanup threshold time: 1431419478404
1432283478570	Sync.LogManager	DEBUG	Done deleting files.
1432283495339	Sync.ErrorHandler	DEBUG	Beginning user-triggered sync.
1432283495339	Sync.Service	DEBUG	User-Agent: Firefox/38.0.1 FxSync/1.40.0.20150513174244.
1432283495339	Sync.Service	INFO	Starting sync at 2015-05-22 10:31:35
1432283495340	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1432283495341	Sync.Status	INFO	Resetting Status.
1432283495341	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1432283495341	Sync.BrowserIDManager	INFO	Failed to fetch the cluster URL: ({details:(new TokenServerClientServerError("Authentication failed.", "resource://gre/modules/services-common/tokenserverclient.js", 36))})
1432283495342	Sync.Service	DEBUG	Cluster value = null
1432283495342	Sync.Status	DEBUG	Status.sync: success.sync => error.sync.reason.no_node_found
1432283495342	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1432283495342	Sync.Synchronizer	INFO	No cluster URL found. Cannot sync.
1432283495343	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1432283495343	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 7229824 ms.
1432283495343	Sync.SyncScheduler	DEBUG	Next sync in 7229824 ms.


Syno-Log (pserve.log) (last start after correcting the public url):

Starting server in PID 23864.
serving on 0.0.0.0:8132 view at http://127.0.0.1:8132
ERROR:syncserver:The public_url setting doesn't match the application url.
This will almost certainly cause authentication failures!
     public_url setting is: http://m.familie-radinger.at:8132
     application url is:    http://192.168.100.150:8132
You can disable this check by setting the force_wsgi_environ
option in your config file, but do so at your own risk.
ERROR:syncserver:The public_url setting doesn't match the application url.
This will almost certainly cause authentication failures!
     public_url setting is: http://m.familie-radinger.at:8132
     application url is:    http://192.168.100.150:8132
You can disable this check by setting the force_wsgi_environ
option in your config file, but do so at your own risk.
ERROR:syncserver:The public_url setting doesn't match the application url.
This will almost certainly cause authentication failures!
     public_url setting is: http://m.familie-radinger.at:8132
     application url is:    http://192.168.100.150:8132
You can disable this check by setting the force_wsgi_environ
option in your config file, but do so at your own risk.
ERROR:syncserver:The public_url setting doesn't match the application url.
This will almost certainly cause authentication failures!
     public_url setting is: http://m.familie-radinger.at:8132
     application url is:    http://192.168.100.150:8132
You can disable this check by setting the force_wsgi_environ
option in your config file, but do so at your own risk.
Starting server in PID 11890.
serving on 0.0.0.0:8132 view at http://127.0.0.1:8132
Starting server in PID 17839.
serving on 0.0.0.0:8132 view at http://127.0.0.1:8132
Starting server in PID 21435.
serving on 0.0.0.0:8132 view at http://127.0.0.1:8132
Starting server in PID 20396.
serving on 0.0.0.0:8132 view at http://127.0.0.1:8132
Starting server in PID 420.
serving on http://192.168.100.150:8132
ERROR:syncserver:The public_url setting doesn't match the application url.
This will almost certainly cause authentication failures!
     public_url setting is: m.familie-radinger.at
     application url is: 
http://m.familie-radinger.at:8132m.familie-radinger.at
You can disable this check by setting the force_wsgi_environ
option in your config file, but do so at your own risk.
ERROR:syncserver:The public_url setting doesn't match the application url.
This will almost certainly cause authentication failures!
     public_url setting is: m.familie-radinger.at
     application url is: 
http://m.familie-radinger.at:8132m.familie-radinger.at
You can disable this check by setting the force_wsgi_environ
option in your config file, but do so at your own risk.
Starting server in PID 3578.
serving on http://192.168.100.150:8132

Regards Peter

Am 22.05.2015 um 10:25 schrieb Dr-Bean:

**Comment by Dr-Bean** [comment]
It seems you are changing entries in `ffsync.ini` that you shouldn't change ;)

Can I suggest to not try with NAT, just try it on the same local network: one NAS, one Firefox client. On the NAS, install the package, and set your .ini file to look like this (changed domain name here):
```
host = 0.0.0.0
port = 8132
public_url = http://m.familie-xyz.at:8132/
```
On your client set `services.sync.tokenServerURI:  http://m.familie-xyz.at:8132/token/1.0/sync/1.5`.
Now sign in to sync, and see if that works.

Note that if your client cannot resolve your domain name (e.g. because of missing name resolution options internally), for Windows clients, you can add an entry in the hosts file to set m.familie-xyz.at to the local IP of your NAS. A DNS server is easier to maintain in the long run, but more advanced to set up correctly.

**Comment by prad1978** [comment]
I have found the mistake - maybe you can but it to your wiki:
In the firefox is a second entry: services.sync.clusterURL
This entry i have to chance to: http://m.familie-xxx.at:8132/storage/1.5/1/
And now it works.
I will test ist on an other pc for shure.

regards peter

**Comment by Dr-Bean** [comment]
Weird. That entry should be updated automatically to the tokenserverURL when the first sync starts. I'll add it in the troubleshooting section.

**Comment by Dr-Bean** [comment]
Added it in: https://github.com/SynoCommunity/spksrc/wiki/Firefox-Sync-Server-1.5#common-errors. Thanks again.

I also provided a description on how to configure SSL by using HAProxy. That may be of interest to you.
