### ISSUE TITLE
Package request: Raid Manager for Jmicron jms562

### ISSUE THREAD

**Issue by MMD70** [SynoCommunity/spksrc#1711]
Hello,

I`m using a EMK3202 Mobile Rack with 2x SSD`s in 1 bay and it`s tested and working.
It comes with Raid manager for Windows, so no use on NAS.
http://www.enermax.com/home.php?fn=eng/product_a1_1_1&lv0=3&lv1=81&no=278

I found a Jmicron Raid Manager for Ubuntu:
http://scott.keszler.name/venus_t5/venus_t5_cd/

Is there any way this can be ported to NAS so we can monitor the Raid inside the Mobile Rack?
Thx
MMD70

**Comment by piwi82** [comment]
SynoCommunity doesn't provide specific hardware support, try to ask Synology.

**Comment by MMD70** [comment]
Noob question.
Maybe a package can support more then one controller?

**Comment by BenjV** [comment]
This software is for the jmicron controller which is used in the majority of USB disk and docking station.
So this is not just for one hardware device usefull.

**Comment by Dr-Bean** [comment]
If that software isn't open source (or more preferable: officially supported by jmicron), then I don't think there's much we can do.

**Comment by MMD70** [comment]
The Hardware Raid Manager software is from Jmicron.
It`s a freeware download.
Will contact Jmicron what they think about this.
But I think it doesn`t necessarily have to be a port.
As @BenjV said, it can be useful for external RAID USB and docking stations too. +1 @BenjV 

Thank you

**Comment by Dr-Bean** [comment]
Useful or not is hardly the point here ;)

To be clear: Regardless of the software's status (e.g. 'freeware'), porting usually entails some form of reverse-engineering. Distributing the resulting software has a chance of being illegal in certain conditions, or is prohibited by the vendor in their license agreement altogether.
Apart from that, porting a piece of sofrware is a specialty job, and that doesn't fit in SynoCommunity's scope. We will not create a Linux version of a particular piece of Windows software.

What we probably can do is provide a package based on a (vendor supplied&supported) open-sourced Linux version of that software, assuming it can be compiled for the various Synology arches.

**Comment by BenjV** [comment]
There is a source for Ubuntu and Fedora so no windows porting or reengineering is neccessary.

**Comment by Dr-Bean** [comment]
Well, great. It shouldn't be too hard to provide the following then:
- Link to source code. I can't find either source or binaries, but that's probably my poor search capabilities.
- Link to documentation with build instructions/dependencies/licenses and other relevant information.

Without source code, we can't compile it for Synology devices. Even then, there's a change it'll only work for a limited set of arches. 

If it's binaries you're talking about: unless working binaries are available for the majority of Synology arches, it's probably not going to happen. You can test that quick enough: try to run one of those on your Synology, see what happens.

**Comment by Dr-Bean** [comment]
I'm closing this issue for now. Please see my previous comment for a couple of the questions we need answered before we can even assess whether a package can be created. Feel free to reopen/add the necessary information, and we'll go from there.

**Comment by tristan-k** [comment]
Does someone have a copy of `Linux_uBuntu_V0.09.27.7z`. Sadly the [Waybackmachine](https://web.archive.org/web/20150620234647/http://scott.keszler.name:80/venus_t5/venus_t5_cd/JMicron%20HW%20RAID%20Manager/Linux/) has no archive of it.

**Comment by thopiekar** [comment]
@tristan-k Need it, too. @MMD70, do you have any copy around?

**Comment by AloisKlingler** [comment]
@tristan-k @thopiekar 
https://www.cineraid.com/downloads/software/CR-H408/?MA 
sadly it only segfaults, I could not get it running :-(

**Comment by rareshornet** [comment]
I managed to open the cineraid package on popos(ubuntu 22.04). I had to download and extract and older i386 ubuntu package with libpng12 and copy it in the i386 system library folder. run it with sudo otherwise disks don't show up. Thanks so much for the cineraid link!!

**Comment by AloisKlingler** [comment]
if still somebody is interested use https://github.com/AloisKlingler/jmraidctl
