### ISSUE TITLE
rutorrent and Sonarr

### ISSUE THREAD

**Issue by Bon3** [SynoCommunity/spksrc#1712]
Hi Guys

Since Sonarr has been updated to use rtorrent as an Download Client has anyone got the current rtorrent release to work??

Sonarr says:
Requires rTorrent version 0.9.0 or newer compiled with XML-RPC support, and a SCGI to HTTP proxy (usually Lighttpd, Nginx, or Apache). Look for ruTorrent instructions for how to set up rTorrent.

Would be nice if we could get the current release of rutorrent to work with Sonarr :) any help is appreciated, oh and btw im running an DS-415+

**Comment by capkokoon** [comment]
ruTorrent works with Sonarr, as for the spk available on the repository.

What you need to do is :
1. configure Sonarr to update from the develop branch
2. toggle "show advanced settings" in the settings page
3. add rTorrent as a downloader in Sonarr, and specify the host, port and base used to access the ruTorrent UI and the RPC gateway (for instance, if your URL is http://myserverip.tld:8430/rutorrent, you must enter "localhost", "8430", and "rutorrent/plugins/rpc/rpc.php")

Make sure that you didn't remove the rpc plugin for ruTorrent (it is set up by default).

**Comment by Bon3** [comment]
What about user name and pass?? And the port for rutorrent where do i see that??

im getting: Unknown exception: Error: ConnectFailure (Connection refused)

When i try

**Comment by capkokoon** [comment]
Fill the "username" and "password" fields only if you have set up a htaccess auth to secure your panel. Otherwise, leave it blank.
The port is found in the URL :
* If your ruTorrent URL is like : http://IP:PORT/rutorrent, then you should fill the "port" field with the mentioned port
* If your ruTorrent URL is like http://IP/rutorrent, then enter "80" (web default port) in the field.

**Comment by Bon3** [comment]
the URL base has been removed in the newest version:

Sonarr Ver. 2.0.0.3237 develop isn't there anymore

**Comment by Bon3** [comment]
Perfect!! :) worked like a charm :)
