### ISSUE TITLE
DSM 5.2-5565 update - BTSync bandwidth issue 

### ISSUE THREAD

**Issue by kameka22** [SynoCommunity/spksrc#1713]
Since the dsm 5.2-5565 update, I have an issue with btsync 1.4.111-11.

BTSync is very slow to download datas from my dedicated server. The bandwidth varies between 50kb/s to 200 kb/s while normally my bandwidth is approx. 2mb/s. 

I have test with other btsynclink on my computer and the speed download is ok (it is not a problem with my dedicated server) . If i download a file with the download station, the speed download is also ok. I have reboot my nas, etc ... the problem does not go away ;(

I think there is an issue between the last dsm update and the btsync package. 

is anyone have this problem ?

**Comment by kameka22** [comment]
After apply the dsm 5.2-5565 update 1 update, the problem seems to have been solved ....
My bandwith is now ok.

**Comment by Dr-Bean** [comment]
Thanks for the info. I'll close this seeing as it's solved.
