### ISSUE TITLE
Subliminal 0.7.5-12 Beta Task not working after view days

### ISSUE THREAD

**Issue by robbeekie** [SynoCommunity/spksrc#1714]
Hello,
since I upgraded subliminal to 0.7.5-12 beta I noticed that the scan button didn't work, but the task did.
I noticed that the task stopt running after a few day and did start after stopping en starting the app.
So I build in that the service stops and starts once a day. 
It run good for 1 week and now this is also not working anymore.  The only I can get it to work is to deinstall the app en install is again. But then I have to fill in everything again.
Th log isn't showing a error.
I am running on the latest DSM

**Comment by Dr-Bean** [comment]
Dupe. See https://github.com/SynoCommunity/spksrc/issues/1561#issuecomment-98698994 and the messages before/after it. I haven't gotten around to fixing it yet.
