### ISSUE TITLE
Without root permissions, Python SPK build fails due to uWSGI module 

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1715]
During Python SPK compilation, uWSGI links its components and plugins to the uwsgi binary.
The location where the binary is placed is `/usr/local/bin/uwsgi`, as shown in the log below. This causes the Python SPK build to fail if you run without root permissions.

(Btw, if you do run with root permissions, the plugins etc. end up in the binary in `/usr/local/bin/uwsgi`, but probably not in the binary that is included in the Python SPK...)

Rather than fixing the code of uwsgi (too convoluted for me: fix one thing, break something else), an alternative would be to create an uWSGI wheel instead, and provide that as part of the Python SPK.
@Diaoul?

```
*** uWSGI linking ***
/spksrc/toolchains/syno-88f6281-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-gcc -o /usr/local/bin/uwsgi -L/spksrc/spk/python/work-88f6281-5.1/install//usr/local/python/lib -Wl,--rpath-link,/spksrc/spk/python/work-88f6281-5.1/install//usr/local/python/lib -Wl,--rpath,/usr/local/python/lib -L/usr/local/python/lib core/*snip* plugins/*snip -lpthread -lm -rdynamic -ldl -lpthread -ldl -lpthread -lutil -lm -lpython2.7 -lcrypt

/spksrc/toolchains/syno-88f6281-5.1/work/arm-marvell-linux-gnueabi/bin/../lib/gcc/arm-marvell-linux-gnueabi/4.6.4/../../../../arm-marvell-linux-gnueabi/bin/ld: cannot open output file /usr/local/bin/uwsgi: Permission denied
collect2: ld returned 1 exit status
*** error linking uWSGI ***
../../mk/spksrc.python-module.mk:28: recipe for target 'compile_python_module' failed
```

**Comment by Diaoul** [comment]
I'm ok for that. I did build latest python SPK with root permissions indeed. Tested and working fine on my NAS but a wheel would be much cleaner.

**Comment by Dr-Bean** [comment]
Done with https://github.com/SynoCommunity/spksrc/commit/0a3851f7255ace78020d49662ce18e9a910b7491
