### ISSUE TITLE
Museek won't install

### ISSUE THREAD

**Issue by daverickdunn** [SynoCommunity/spksrc#1718]
As the title suggests, it just says "Failed to install 'Museek+.' " at the final step of the pre-installation.

Are there any prerequisites for installing?

DSM: 5.2-5565 Update 1
Model: DS214play

As a side note, I actually started working on bringing Nicotine to Synology myself, I paused the project a few months back and was about to get into it again when I saw Museek+ up here. If there's scope for contribution I'd be happy to get involved.

**Comment by Dr-Bean** [comment]
Not all packages for Museek were signed yet. That's fixed, so you can give it another try.
Note that the package hasn't been updated in a while, and it may be a bit rough around the edges.

As for contributing (adding Nicotine or improving Museek for that matter): Sure. Open a PR with your additions/improvements and we'll go from there.

**Comment by daverickdunn** [comment]
Thanks, it installs now, but won't run... I'll just keep an eye out for future updates.

I'll give Museek a look, though I'm sure by the time I get my head around it you'll have thigns up and running, so there might not be much point.

Cheers

**Comment by Dr-Bean** [comment]
It does run, it just doesn't show it in Package Center. The package currently only contains the binary, there's no (web)interface.

**Comment by daverickdunn** [comment]
Ahh, I see. Cool, I'll give it a look. Cheers!
