### ISSUE TITLE
Enable libwebsockets support in Mosquitto

### ISSUE THREAD

**Issue by Diaoul** [SynoCommunity/spksrc#1723]
It's all in the title.

**Comment by marcelrv** [comment]
Did you already manage to get it in?? How to enable it?

**Comment by Diaoul** [comment]
Well it's compiled with libwebsockets like asked. I don't know what it takes to actually configure mosquitto to use it.

**Comment by marcelrv** [comment]
Indeed, I updated and found the lib. Great!!!

In the mean time I figured it out.. For others looking for the same,

edit the config file with : vi /usr/local/mosquitto/var/mosquitto.conf

add the following for a minimal setup:
```
listener 1883
listener 9001 127.0.0.1
protocol websockets
```

**Comment by Diaoul** [comment]
Should the package include this as default config?

**Comment by adamotte** [comment]
@Diaoul yes it would be easier for standard users (not familiar with ssh)
