### ISSUE TITLE
[request] Wallabag

### ISSUE THREAD

**Issue by romu70** [SynoCommunity/spksrc#1725]
Would be nice to have Wallabag in SynoComunity. [Wallabag](https://www.wallabag.org/) is a free alternative to Pocket (formerly Read It Later).

Thanks.
##

**Comment by cytec** [comment]
seems to be a PHP Application with MIT Licence.

**Comment by romu70** [comment]
and? is this a problem? (true question)

**Comment by cytec** [comment]
Nope just an info if someone wants to make a spk ;)

**Comment by nicosomb** [comment]
If you need some help about wallabag, ping me ;-)

**Comment by Kwadz** [comment]
+1
Is there a plan to make a SPK ?

**Comment by MoOx** [comment]
Would be nice to have something here. If there any documentation about how to add a package here (for a total newbie to spksrc)?

**Comment by nicosomb** [comment]
It seems there is already an opened PR https://github.com/SynoCommunity/spksrc/pull/2165

**Comment by tolkonepiu** [comment]
I tested version 2.0.5 work on Synology 215j. He works very slowly. 1.9.2 works well.

**Comment by magefesa** [comment]
+1

**Comment by Cre0** [comment]
+1

**Comment by romu70** [comment]
On my Synology, I run Wallabag through the official docker image. And it works pretty well. A nice workaround, easy to setup.

**Comment by tolkonepiu** [comment]
https://github.com/SynoCommunity/spksrc/pull/2824 merged

**Comment by Safihre** [comment]
Package is available, still needs to be converted for DSM6 support (#3113).
