### ISSUE TITLE
python3/pip/wheel help needed

### ISSUE THREAD

**Issue by larsimmisch** [SynoCommunity/spksrc#1729]
Hi,

I'm trying to package `attic` in my fork at https://github.com/larsimmisch/spksrc. Attic needs at least Python 3.2.

I think I've come pretty far; all cross dependencies (in particular `acl` and `attic`) compile. But *Building wheels* fails:

```
===>  Building package for arch x64-5.1
make[1]: Entering directory '/home/lars/spksrc/spk/attic'
===>  Processing wheels of attic
===>  Creating requirements file
===>  Building wheels
ERROR: 'pip wheel' requires bdist_wheel from the 'wheel' distribution.
../../mk/spksrc.wheel.mk:36: recipe for target 'wheel_target' failed
make[1]: *** [wheel_target] Error 1
make[1]: Leaving directory '/home/lars/spksrc/spk/attic'
../../mk/spksrc.spk.mk:417: recipe for target 'arch-x64-5.1' failed
make: [arch-x64-5.1] Error 2 (ignored)
```

This is a link to the Makefile of `spk/attic`: https://github.com/larsimmisch/spksrc/blob/master/spk/attic/Makefile

Any hint would be appreciated.

**Comment by Dr-Bean** [comment]
You're missing the `wheel` module. It's mentioned in the [README requirements](https://github.com/SynoCommunity/spksrc#requirements)

**Comment by larsimmisch** [comment]
Doh!

Thank you; I missed that, and I appreciate your help.

But the next problem is just around the corner:

```
===>  Building wheels
Downloading/unpacking attic==0.16 (from -r /home/lars/spksrc/spk/attic/work-x64-5.1/wheelhouse/requirements.txt (line 1))
  Downloading Attic-0.16.tar.gz (232kB): 232kB downloaded
  Running setup.py (path:/home/lars/spksrc/spk/attic/work-x64-5.1/wheelbuild/attic/setup.py) egg_info for package attic
    Attic requires Python 3.2 or later
    Complete output from command python setup.py egg_info:
    Attic requires Python 3.2 or later
```

I suspect that `setup.py` is invoked with python2 but I don't know how to force python3. I'll have a look at it tomorrow, but I'll appreciate any hints.

**Comment by Dr-Bean** [comment]
Set `PIP = pip3`. Take a look at the Homeassistant package, that's a Python3 based package as well.
Note that using pip3 might require you to install wheel again, but this time with pip3 (depends on the version of pip you're using).

**Comment by larsimmisch** [comment]
Excellent, thanks (doh again)

**Comment by Dr-Bean** [comment]
Let's close this for now. If you run into issues/questions, feel free to reopen. Otherwise, I assume we can expect a PR for the new package in due time ;)

**Comment by larsimmisch** [comment]
Thanks, yes. I'm still working on it - I have an installable package, but the dependencies aren't right yet, so it doesn't run yet (also, bafflingly, the #! for python3 is wrong in the installed script). I'll look at it more and reopen when I get truly stuck or send a pull request. I appreciate your help so far.

**Comment by Dr-Bean** [comment]
>#! for python3 is wrong in the installed script

I'd suggest to start your python script by using `${PYTHON3} <your script location>`. If you've correctly specified the correct location for the Python3 binary in `dsmcontrol.sh` (which should be in the virtualenv you created during installation), it won't care what the shebang looks like. 
Take a look at other Python-based packages (sickbeard/couchpotato) for example: they use the same approach, although for Python2 instead.
