### ISSUE TITLE
NZBGET icon

### ISSUE THREAD

**Issue by kjmuk** [SynoCommunity/spksrc#1731]
Installed NZBGET 14 on another DS all went well except I cannot get the icon, only way to run it is through Packag Centre then NZBGET then URL: then all works perfect... apologies for my stupidity...

I have done all the following.
- portforward 6789 on router.
- created directory called downloads. 
- group permissions ticked R/W
- added Python and Git

**Comment by Dr-Bean** [comment]
Log in as a user with administrator privileges. Then choose either of the following methods:
- Open `Control Panel` > `Privileges`, and set appropriate permissions from there;
- Open `Control Panel` > `User` > Open the correct user, and check the tab `Applications`.

**Comment by kjmuk** [comment]
Once again many many thanks, works perfectly.
