### ISSUE TITLE
Custom (Couchpotato, SickBeard, Headphones, SABnzbd) packages not starting after official git-server installation

### ISSUE THREAD

**Issue by kimpenhaus** [SynoCommunity/spksrc#1737]
Hi all,

I had all the custom packages up and running on my Synology NAS (with dependent _git_ package from synocommunity installed). Yesterday I installed the official (from Synology) _git-server_ to host git repositories on the NAS. After shutdown and restart none of those custom packages is starting any more.

```
tail /var/log/messages/
```

just shows

```
Jun  2 21:00:12 nas-name entry.cgi_SYNO.Core.Package.Control[1].start[30684]: pkgstartstop.cpp:187 Failed to start package couchpotatoserver-custom, [128], No such file or directory
Jun  2 21:00:12 nas-name entry.cgi_SYNO.Core.Package.Control[1].start[30684]: pkgstartstop.cpp:196 Failed to start package couchpotatoserver-custom, [128]
```

Anyone any clue?
##

**Comment by Diaoul** [comment]
Try running `/var/packages/sickbeard-custom/scripts/start-stop-status start` in SSH, there might be some information here.

**Comment by kimpenhaus** [comment]
Thanks - I managed to get it working again.

The problem was that _/etc/passwd/_ was modified and the shell for the app-accounts for the custom services was modified to _/sbin/nologin_ which causes the error. Switching back to _/bin/sh_ solved my issues.

**Comment by Dr-Bean** [comment]
Eh? I don't think Synology's Git package does that...

**Comment by kimpenhaus** [comment]
No clue if it does or not - all I can say is *it was modified* and all I did was to install the git-server package and did a restart.

**Comment by Diaoul** [comment]
Can you report this to Synology? Their package should not set `/sbin/nologin` for all users.

**Comment by Dr-Bean** [comment]
>And from what I can see it does modifiy the passwd file. users configured to have git access will have /var/packages/Git/target/bin/git-shell as shell configured. Might be that removing access will result in /sbin/nologin - but that's just guessing ;-)
That's exactly what it does (and that is a bug which Synology should fix). 

But, my remark was directed at your comment: `app-accounts for the custom services was modified`.
I cannot reproduce that. As far as I can tell, `Git` only changes the accounts which you provide access via the `Git` interface, and our application users aren't visible there.

**Comment by kimpenhaus** [comment]
Ah I see - I changed the user id's of the app's to a range which makes them visible in dsm. (I remember something above 1000). Should be the reason why they are affected by the '''Git''' package.

**Comment by Dr-Bean** [comment]
That's what I expected :) Thanks for letting us know.
Although there's not much we can do about it ourselves, I would second Diaoul's suggestion to report this to Synology. Disabling shell access for users when reverting/uninstalling their package should not happen: instead, it should revert to the original shell.

**Comment by kimpenhaus** [comment]
Absolutely!

You guys have any idea where to place the bug? forum - support - email? Haven't found any official bug-tracker so far at the synology page.

**Comment by Dr-Bean** [comment]
I'd recommend the support form: https://myds.synology.com/support/support_form.php.

**Comment by kimpenhaus** [comment]
Thanks - I reported the problem to the support and received a ticket number. Once I got feedback I will keep you guys up to date.

**Comment by rp4k** [comment]
can someone help me i updated to DSM6  from the control panel and now  sabnzb package wont start.  what should i do?  DS716+
