### ISSUE TITLE
MediaInfo libraries and chromaprint fpcalc for Intel broken

### ISSUE THREAD

**Issue by spz82** [SynoCommunity/spksrc#1738]
Hi,
During my FileBot tryout I found that MediaInfo libraries seem do not work (cannot be loaded)
You can read more in FileBot thread: http://www.filebot.net/forums/viewtopic.php?f=8&t=2734

similar situation with fpcalc:
`synek> fpcalc`
`fpcalc: error while loading shared libraries: libmp3lame.so.0: cannot open shared object file: No such file or directory`

`synek> uname -a`
`Linux synek 3.10.35 #5565 SMP Mon May 11 02:12:55 CST 2015 x86_64 GNU/Linux synology_x86_712+`

**Comment by Diaoul** [comment]
Try `LD_LIBRARY_PATH=/usr/local/chromaprint/lib fpcalc` or replace chromaprint with whatever the SPK that provides fpcalc is ;)

**Comment by spz82** [comment]
this do not help, maybe because there is no lib folder in /usr/local/chromaprint/ :D (only bin and app there).
I workarounded both issues (by taking libs from different ipkg package), but wanted to report here at the source of packages that something is wrong with them.

**Comment by rednoah** [comment]
I'd like to add that at least on my DS213J (armada370) things work right out of the box.

`Linux DiskStation 3.2.40 #5565 Mon May 11 02:11:58 CST 2015 armv7l GNU/Linux synology_armada370_213j`

chromaprint doesn't seem to have a lib folder, but the executable work just fine for me: 
`$ ls /usr/local/chromaprint/`
`app bin`

**Comment by AxelF0ley** [comment]
Confirmed. With the latest MediaInfo 0.7.73-2 (that installs libemediainfo.so) and Chromeprint 1.2-1 (that installs fpcalc), both the library (libmediainfo.so) and the utility (fpcalc) have issues.

I have a DS1812+ with DSM 5.2-5565. Here's the uname output:

[Wed Jun 03 12:59:10 root@nas:/volume1/@appstore/filebot]# uname -a
Linux nas 3.10.35 #5565 SMP Mon May 11 02:14:34 CST 2015 x86_64 GNU/Linux

**Comment by cytec** [comment]
strange... Quick fix should be: installing `ffmpeg` which contains `libmp3lame.so`... then `LD_LIBRARY_PATH=/usr/local/ffmpeg/lib fpcalc` should work... 

@Diaoul @Dr-Bean maybe we'll have to change `BUILD_DEPENDS` back to `DEPENDS` for `cross/chromaprint` or include `cross/lame` in `DEPENDS`

**Comment by Dr-Bean** [comment]
Right. If even one file from the depends is actually needed in the SPK, then `BUILD_DEPENDS` isn't the right thing to use. I didn't notice that when I mentioned it in the PR.

Either of your solutions would work, I guess (assuming you can compile `cross/lame` on its own, dunno). The first one seems more correct, but it means more cleanup is needed (or simply ignore that it's there, also possible).

**Comment by cytec** [comment]
@AxelF0ley @spz82 Mediainfo is working fine as far as i can see... have you tried running `/usr/local/mediainfo/bin/mediainfo`?  if that runs, it can't be the library because `mediainfo` needs `libmediainfo.so` to run ;)

**Comment by spz82** [comment]
overall `/usr/local/mediainfo/bin/mediainfo` seem to work.
while `/usr/local/mediainfo/lib/libmediainfo.so` cannot be loaded by FileBot (and another libmediainfo.so version from different source can...)

**Comment by cytec** [comment]
i guess you'll have to report that upsream then, as i mentioned above `/usr/local/mediainfo/lib/libmediainfo.so` is loaded by `/usr/local/mediainfo/bin/mediainfo` so maybe filebot got something wrong there :/

**Comment by spz82** [comment]
@rednoah so far I thought that linux-x86/ is not meaningful, but is it possible that it is folder name?

btw, @cytec you've mentioned ffmpeg package - is Intel version available on SynoCommunity repo? I see that on https://synocommunity.com/packages but do not see it via my DS712+ Package Center

**Comment by cytec** [comment]
@spz82 seems like there is only avoton and alpine available on synocommunity... i'm currently working on an updated version of ffmpeg, which can be found here: http://cytec.us/syno/test-spk/ffmpeg/ there is also a x64 SPK ;)

**Comment by spz82** [comment]
@cytec danke :)

**Comment by rednoah** [comment]
@spz82 Ignore that error message. It's misleading. It'll first search the library path, and if no library can be found or loaded, then JNA will try non-system locations and that's why you get that error.

**Comment by rednoah** [comment]
@spz82 I'd try grabbing the latest libmediainfo binaries from one of the official Debian packages and try with those. Just to show that FileBot/JNA can load the latest library, because I suspect making it work is a matter of some minor compiler settings.

**Comment by MACE-Zer0** [comment]
On I386 doesnt work :

Synology-1813> filebot -script fn:sysinfo
FileBot 4.6 (r3052)
JNA Native: 4.0.0
MediaInfo: java.lang.UnsatisfiedLinkError: Unable to load library 'mediainfo': Native library (linux-x86/libmediainfo.so) not found in resource path ([file:/volume1/@appstore/filebot/FileBot.jar])
p7zip: Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)
chromaprint-tools: fpcalc version 1.1.0 (/usr/local/chromaprint/bin/fpcalc)
Extended Attributes: OK
Groovy Engine: 2.4.3
JRE: Java(TM) SE Embedded Runtime Environment 1.8.0_33 (headless)
JVM: 32-bit Java HotSpot(TM) Embedded Server VM
CPU/MEM: 4 Core / 878 MB Max Memory / 37 MB Used Memory
OS: Linux (i386)
uname: Linux Synology-1813 3.10.35 #5565 SMP Mon May 11 02:14:34 CST 2015 x86_64 GNU/Linux synology_cedarview_1813+
Done ヾ(＠⌒ー⌒＠)ノ


BUT ON ARM IT DOES 

NAS_Gouveia> filebot -script fn:sysinfo
FileBot 4.6 (r3052)
JNA Native: 4.0.0
MediaInfo: MediaInfoLib - v0.7.73
p7zip: Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,2 CPUs)
chromaprint-tools: fpcalc version 1.2.0 (/usr/local/chromaprint/bin/fpcalc)
Extended Attributes: OK
Groovy Engine: 2.4.3
JRE: Java(TM) SE Embedded Runtime Environment 1.8.0_33 (headless)
JVM: 32-bit Java HotSpot(TM) Embedded Client VM
CPU/MEM: 2 Core / 245 MB Max Memory / 11 MB Used Memory
OS: Linux (arm)
uname: Linux NAS_Gouveia 3.2.40 #5565 SMP Mon May 11 02:13:03 CST 2015 armv7l GNU/Linux synology_armadaxp_ds214+
Done ヾ(＠⌒ー⌒＠)ノ:

**Comment by streetsurfer** [comment]
Having trouble with the above on x86 as well.
I tried symlinking at least the Mediainfo to the location filebot seeks out to no avail.
fpcalc just doesnt seem to work in any shape or form.
Has anyone got a workaround?

Thanks

**Comment by cytec** [comment]
@MACE-Zer0 seems more like a filebot problem as it searches for libmediainfo in linux-x86/

@streetsurfer have you tried this:
https://github.com/SynoCommunity/spksrc/issues/1738#issuecomment-108383894

seems like there is/was missing a library (not sure if @Dr-Bean published an update wich includes those libs already)

**Comment by streetsurfer** [comment]
@cytec Not exactly sure what cross/lame actually means.

I am however getting the same mediainfo and fpcalc output in ssh as above.

Sorry for being ignorant. Google search and other searches didnt really yield any results on this topic.

**Comment by Dr-Bean** [comment]
This thread is mixing up several different things, making it confusing for anyone to keep track of what's what. Open a separate issue for unrelated questions please.

@cytec: Not up to now. I've added `cross/lame` to `spk/chromaprint/Makefile` which removes the error on `fpcalc: error while loading shared libraries: libmp3lame.so.0: cannot open shared object file: No such file or directory`. 
I'll do a tiny bit of cleanup in the SPK (remove ui reload and image conversion, as it's pure CLI), but that should be all that's needed for chromaprint, right?

Then, on the mediainfo side: We don't have a fix as it's an upstream issue, is that right? If not, what is needed there?

**Comment by Dr-Bean** [comment]
Updated Chromaprint with https://github.com/SynoCommunity/spksrc/commit/b3f7cc372de66654cc15a7b40b9a712580784e27. Chromaprint 1.2-2 has been published on the repository.

**Comment by MACE-Zer0** [comment]
Thanks for your work , chromaprint its working fine now ,  just mediainfo not sure if its working or not since the problem , anyone got media info working on intel with the latest version ???, i will not update until i get feedback if its working !!!

**Comment by MACE-Zer0** [comment]
Media info still is not working  , when i put the lib folder from version 7.69 inside the instalation of 7.73 , it starts working again , but since i changed the librarys its working with the older version 7.69 , dont know why filebot cant load 7.73 !!!

**Comment by Dr-Bean** [comment]
The reason Filebot doesn't work with Mediainfo is because it seems people are instructed to install a 32-bit version of Java.
Mediainfo is compiled as 64-bit, seeing as the toolchain is 64-bit. Please replace your Java version with a 64-bit version, and try again.

**Comment by MACE-Zer0** [comment]
i dont think there is available java SE embedded 8 64bits version for linux /synology , only x86 ,  why did the version 7.69 worked ??? was it compiled as 32 ???

**Comment by Dr-Bean** [comment]
Sure there is. Check Oracle's download site, there should be a version for Linux x86, and one for Linux x64.

As for why your version of Mediainfo v7.69 worked: I wouldn't know. We've never released a mediainfo package with that version, so ask the person who provided it.

**Comment by MACE-Zer0** [comment]
for some reason another nas i have filebot that uses arm , has java 32bits and media info works fine , is it because that the java is for arm ??? , 

filebot -script fn:sysinfo
FileBot 4.6 (r3052)
JNA Native: 4.0.0
MediaInfo: MediaInfoLib - v0.7.73
p7zip: Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,2 CPUs)
chromaprint-tools: fpcalc version 1.2.0 (/usr/local/chromaprint/bin/fpcalc)
Extended Attributes: OK
Groovy Engine: 2.4.3
JRE: Java(TM) SE Embedded Runtime Environment 1.8.0_51 (headless)
JVM: 32-bit Java HotSpot(TM) Embedded Client VM
CPU/MEM: 2 Core / 245 MB Max Memory / 14 MB Used Memory
OS: Linux (arm)
uname: Linux NAS_Gouveia 3.2.40 #5592 SMP Wed Aug 19 13:37:34 CST 2015 armv7l GNU/Linux synology_armadaxp_ds214+
Done ヾ(＠⌒ー⌒＠)ノ

**Comment by streetsurfer** [comment]
This is running on the same xpenology box mentioned above.
Intel base. I've upgraded Java to the 64bit version.

NASBOX>
NASBOX> java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
NASBOX> filebot -script fn:sysinfo
FileBot 4.6 (r3052)
JNA Native: 4.0.0
MediaInfo: MediaInfoLib - v0.7.73
p7zip: Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)
chromaprint-tools: fpcalc version 1.2.0 (/usr/local/chromaprint/bin/fpcalc)
Extended Attributes: OK
Groovy Engine: 2.4.3
JRE: Java(TM) SE Runtime Environment 1.8.0_60 (headless)
JVM: 64-bit Java HotSpot(TM) 64-Bit Server VM
CPU/MEM: 4 Core / 1 GB Max Memory / 21 MB Used Memory
OS: Linux (amd64)
uname: Linux NASBOX 3.10.35 #1 SMP Thu Jul 30 00:30:25 UTC 2015 x86_64 GNU/Linux synology_bromolow_3615xs
Done ヾ(＠⌒ー⌒＠)ノ

**Comment by MACE-Zer0** [comment]
@streetsurfer  , sorry but im not that good  -  did you install the RPM or normal  ??  JDK or JRE , im trying but the synology doesnt accept my command , maybe doing it wrong , can u give me the command line u used to iniciate install and if you installed JDK or JRE ???

thanks

**Comment by streetsurfer** [comment]
@MACE-Zer0 I actually used the JAVA Manager that comes standard package with Synology.
I downloaded the 64bit tar.gz from Oracle.
Renamed it from (original file) jdk-8u60-linux-x64.gz to jdk-7u51-linux-i586.tar.gz which is the only format accepted by the JAVA Manager and it still worked.
Otherwise you can install it directly via SSH, but I am pretty sure you have to download the headless version.

**Comment by Dr-Bean** [comment]
@rednoah Could you please adjust your installation instructions for people on x86-64 models?

An overview of the models can be found here: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model. This applies to the models where `(x64)` is added to the name, currently `avoton`, `bromolow`, `cedarview` and `x86`.
