### ISSUE TITLE
tt-rss now git only, no longer doing periodic releases

### ISSUE THREAD

**Issue by nickbroon** [SynoCommunity/spksrc#1739]
See https://tt-rss.org/forum/viewtopic.php?f=10&t=3262
SynoCommunity is using the very old 1.14 release, while there have been 139 commits since then. See https://github.com/gothfox/Tiny-Tiny-RSS/compare/1.14...master
Can the tt-rss spksrc be updated?

**Comment by Dr-Bean** [comment]
Package tt-rss 20150529-8 has been published. Thanks for the PR, @nickbroon ;)
