### ISSUE TITLE
Package ownCloud: add configuration to use/force https (and alias)

### ISSUE THREAD

**Issue by liselorev** [SynoCommunity/spksrc#1740]
It would be more secure and customisable
if the package had an option (toggle?) to force the server to (only) be reachable through https,
optionally in combo with virtualhost (extra list of virtual hosts) and alias options

I had this running (in DSM 4.3 with owncloud 6.*?), and some updates later now this 
stopped working.

I believe the situation asks for:

* owncloud/config/config.php to have 

    * 'forcessl' => true,
    * 'trusted_domains' =>

             array (
                 0=>'127.0.0.1',
                 1=>'172.132.32.75', /* (fixed/internal/...) ip address of server */
                 2=>'domain.name.tld',  /* your domain name (public/internal)
            ),

* /etc/httpd/sites-enabled-user/httpd-ssl-vhost.conf-user 

    in section of the VirtualHost, wherein you want an Alias:
~~~~~
    <virtualhost *:443>
        ServerName domain.name.tld
        DocumentRoot "/var/services/web_ssl/domain_directory"
        SSLEngine on
        Alias /OwnCloud "/var/services/web_alias/owncloudd"
        <Directory "/var/services/web_alias/owncloudd" >
            Allow from all
            Order allow,deny
            AllowOverride All
            Options +Indexes
        </Directory>
    </VirtualHost>
~~~~~

**Comment by Dr-Bean** [comment]
Owncloud has that option built-in: Go to `Admin` or whatever it's called. There are two checkboxes: `Enforce HTTPS` and `Enforce HTTPS for subdomains`.

You might want to also verify DSM > Control Panel > Web Services > `Enable HTTPS connection for web services` is enabled.

**Comment by liselorev** [comment]
indeed the enforce https allows the first portion (owncloud/config/config.php)
but not the embedding in the web-server configuration (the possible alias)...
However the latter may be considered something that synology should provide instead (?).

**Comment by Dr-Bean** [comment]
Put `Alias /whatever "/var/services/web/owncloud"` to `/etc/httpd/sites-enabled-user/com.synocommunity.packages.owncloud.conf` on the first line. Then restart Apache with `/usr/syno/sbin/synoservicecfg --restart httpd-user` or equivalent.

I don't see the added value for the package though. Note that the above might be reversed when a package update comes along, but other than that, it should work.

**Comment by Dr-Bean** [comment]
@liselorev Did my solution work for you?

**Comment by liselorev** [comment]
Hi, @Dr-Bean, thanks for the solution,
I had discovered the solution myself before posting, however posted the suggestion ot extend because indeed if it is not made in some package, an update overwrites (or might) the changes.

**Comment by Dr-Bean** [comment]
Thanks for the suggestion, but we won't be adding it to the package :) 

Owncloud is available on its main path: `/owncloud` by default, which is sufficient for almost all users.
If you want to add more advanced changes, redo those changes after package upgrades come in via SynoCommunity, or you may even want to repackage with your changes.
