### ISSUE TITLE
Flexget broken by sqlAlchemy update

### ISSUE THREAD

**Issue by mcgouganp** [SynoCommunity/spksrc#1743]
Flexget no longer runs after Python update.

Commit 42292a48bd56c4004088f4fc47ac4f8b00d4222d which upgraded sqlalchemy to 1.0.4 breaks Flexget dependency.

**Comment by nineteenuk** [comment]
Yes. Updated python 2.7 with offered update and Flexget stopped working.

**Comment by Dr-Bean** [comment]
The one package I didn't test...Yes, the Flexget package needs an update, it's already fixed upstream.

**Comment by Dr-Bean** [comment]
Flexget 20150606-5 has been published on the repository. Thanks for the reports :)

**Comment by mcgouganp** [comment]
Thanks!

**Comment by nineteenuk** [comment]
Thanks too
