### ISSUE TITLE
ADDITIONAL_SCRIPTS not processing correctly

### ISSUE THREAD

**Issue by mtompkins** [SynoCommunity/spksrc#1746]
I have tried to use the ADDITIONAL_SCRIPTS env. variable to copy a script from a src folder to the produced package. This does not seem to complete successfully.

I have tried:
`ADDITIONAL_SCRIPTS = src/someScript.sh`

The error is in the copy command submission:
`cp: missing destination file operand after ‘.../work-cedarview-5.1/scripts/someScript’` 

I've confirmed using $(MSG) that it is not receiving a destination in the function call.

Ref: https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.spk.mk#L246

**Comment by Dr-Bean** [comment]
Hm. I think I actually broke that with the FWPORTS addition... It was never caught before because ADDITIONAL_SCRIPTS hasn't been used in ages.
 
Usually, a different method is used: add the scripts to `${INSTALL_SCRIPTS/bin`, instead of putting other scripts in with the start-stop scripts. Example: https://github.com/SynoCommunity/spksrc/blob/master/spk/selfoss/Makefile#L40.

**Comment by Dr-Bean** [comment]
Can you test this: In https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.spk.mk#L244, edit the line like this:
```
- $(DSM_SCRIPTS_DIR)/%: $(filter %.sc,$(FWPORTS))
+ $(DSM_SCRIPTS_DIR)/%.sc: $(filter %.sc,$(FWPORTS))
```

**Comment by mtompkins** [comment]
Thanks for the quick response. That ADDITIONAL_SCRIPTS Env Variable was just so *elegant* that I figured I'd mention it. Indeed I have been working around it by adding the manual copy as you referenced.

That change does address the issue and works. 
(I didn't test for any impact to the FWPORTS var as it looked simple enough.)

**Comment by Dr-Bean** [comment]
Note: Testing of FWPORTS needed before merging this fix.
@mtompkins Thanks for testing ;)

**Comment by Dr-Bean** [comment]
Fixed with https://github.com/SynoCommunity/spksrc/commit/4ca9d1e731b8c11d3d3fa7ad56cb1e8d0ffd6bab.
