### ISSUE TITLE
Cross compiling GCC

### ISSUE THREAD

**Issue by xmrflipflop** [SynoCommunity/spksrc#1748]
Hi all, I'm new to SynoCommunity and spksrc so please bear with me. I don't think I've found a SynoCommunity forum so I'm seeking help for my struggles here, redirect me if there's a more suitable place.

In short: I'm trying/failing to cross compile GCC for use on my DS215j (Armada 375). All the build errors are related to architecture, such as architecture not found. Which leads me to think it could be related to this issue https://github.com/SynoCommunity/spksrc/issues/1446.

The long version:
The target is an Armada 375, ARMv7 Coretex-A9 cpu.
I'd like to build a GCC compiler for the purpose of building Apache and Apache modules (mod_wsgi) natively on the NAS. (I would be open to the option of cross compiling Apache modules... but that could have more issues as it requires Perl, Python in addition to GCC).
I've set up a virtual machine with debian 8, i386, GCC v4.9.2 and went through the `Requirements` and `Usage` snippets. So far so good.
I've then added libraries required for GCC - GMP, MPFR, MPC, ISL. These compiles fine on their own and fine from GCC's folder.

The GCC `Makefile` have been configured as so
```Makefile
PKG_NAME = gcc
PKG_VERS = 5.1.0
PKG_EXT = tar.gz
PKG_DOWNLOAD_METHOD = svn
PKG_SVN_REV = 224186
PKG_DIST_NAME = tags/gcc_5_1_0_release
PKG_DIST_SITE = svn://gcc.gnu.org/svn/gcc
PKG_DIST_FILE = $(PKG_NAME)-r$(PKG_SVN_REV).$(PKG_EXT)
PKG_DIR = $(PKG_NAME)-r$(PKG_SVN_REV)

DEPENDS = cross/gmp cross/mpfr cross/mpc cross/isl
[...]
GNU_CONFIGURE = 1
CONFIGURE_ARGS = --enable-languages=c,c++ --disable-multiarch --disable-bootstrap

include ../../mk/spksrc.cross-cc.mk
```

`make arch-armada375` gives this error
```
make[6]: Entering directory '/home/xmrflipflop/projects/spksrc/cross/gcc/work-armada375-5.1/gcc-5.1.0/arm-marvell-linux-gnueabi/64/libgcc'
[...]
../../.././libgcc/config/arm/lib1funcs.S:116:2: error: #error Unable to determine architecture.
 #error Unable to determine architecture.
```
The error and `/64/` seem to be telling me something is wrong with the architecture of the files being built. I've then tried with `CONFIGURE_ARGS` or `TC_CFLAGS` such as `--with-arch=armv7-a` `-march=armv7-a` `-mcpu` .. etc. They gave rise to errors like
`configure: error: unrecognized option: '-march=armv7-a' Try './configure --help' for more information.`
libiberty `bad value (armv7-a) for -march= switch`
`configure: error: unrecognized option: '-march=armv7-a'`
(But didn't have the `/64/` build artefact folder)

I'd like any form of assistance or direction to get this working :(. I can provide `config.log `s if required.
Cheers,
Peter

**Comment by Dr-Bean** [comment]
Simply adding compile options, in the hope that they work...probably won't ;)
I'd start with doing what the compile process tells you do: run `./configure --help` and check which options are available. Most likely, the documentation (and in some cases, even the code itself) can help with that as well.

If you want to check if #1446 applies, then I'd suggest to try and rule it out: 
Pass on the compile command yourself (you should be able to copy it when spksrc is compiling), or use this comment https://github.com/SynoCommunity/spksrc/issues/1446#issuecomment-76383254 as a slightly alternative way.

Whatever the outcome (either finding that spksrc is a factor, or that it's not), you'll probably end up with the same follow-up action: looking at the code and documentation to figure out how to fix it. Either by working backwards from the error, or by working forward from the start of the compile process to the error.

**Comment by xmrflipflop** [comment]
Thanks for the reply Dr-Bean!

It's been some time since I've hit this wall and I've shifted towards using a raspberry pi like board with a full debian os to host django/mod_wsgi/apache2. The rest of this comment is from what I could remember from the time, please correct any mistakes. In the short term I don't think I'll be going back to implementing the stack on Synology, but suggestions would be kept in mind when I revisit this issue.

I remember trying to trace the spksrc codes to find out what commands are executed in the build process. But I'm personally not familiar with makefiles/scripts so it was a bit of a struggle. I recall briefly trying out `.PHONY: myConfigure` methods to have pre-build, post-build actions but as I wasn't familiar with what was going on, I wasn't able to determine if I've put in the wrong commands or wrong config.

Beside looking through the source codes, I don't think I've found any documentations that you were referring to? In particular the `.PHONY` directive related ones will be helpful. Could you direct me to the right place if they exist?

The answer to the last question may answer this one. So I recall trying to find and enable a `verbose` option in spksrc build to find out what commands have been executed. But I got lost either from the wall of GCC build outputs or something else. If possible, could you point me to the build steps after extracting package source to building the spk package? I was only able to find https://github.com/SynoCommunity/spksrc#what-is-spksrc-doing but again, wasn't sure where the pre build, post build steps come in and if the custom build steps overwrite or append to spksrc build steps.

**Comment by Dr-Bean** [comment]
I actually meant gcc documentation, not spksrc documentation.

By default, spksrc cross-compiles as you'd expect: [`./configure`](https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.configure.mk#L50), [`make`](https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.compile.mk#L36), [`make install`](https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.install.mk#L55) (amongst all the other things, such as downloading, extracting etc)

Overriding the defaults can be done by specifying it in the Makefile (e.g. `INSTALL_TARGET=myInstall`, and adding a `.PHONY: myInstall` target). That is not specific to spksrc, but to GNU Make: http://www.gnu.org/software/make/manual/make.html#Phony-Targets.

As for the verbose option, spksrc prints out everything it can. Presumably, it's possible that the software you're packaging is not showing everything that happens during the process, but not very likely either. Check its documentation to be sure.

For a list of the 'steps' for cross packages, see here: https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.cross-cc.mk#L46. The targets are processed from top to bottom. 
Each `include` refers to a specific file containing the targets for that particular step. If you check those files, you'll see it usually consists of a pre target, processed before the main target itself, and a post target, processed after the main target. This is also explained in short at the top of each file, e.g. here: https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.configure.mk#L1.

**Comment by xmrflipflop** [comment]
Oh I see. Thanks for the `.PHONY` explanation, that cleared up a lot for me. I'll look into this again if i wish to port the project back onto synology.
Cheers.
