### ISSUE TITLE
[Package Request] Ubooquity

### ISSUE THREAD

**Issue by Diaoul** [SynoCommunity/spksrc#1750]
##

**Comment by cytec** [comment]
ha @Diaoul not following the rules at all :D... hope i got the right one:

Website: http://vaemendis.net/ubooquity/
Description: Home server for comics and ebooks
Documentation: http://vaemendis.net/ubooquity/static5/documentation
Source code: http://vaemendis.net/ubooquity/static2/download (no source code available)
License: custom? free for non-commercial use

**Comment by Diaoul** [comment]
You got me. I saw a post on a forum and posted it here as a reminder.
Thanks for getting the information

**Comment by burghy86** [comment]
please, create this packet. are more simply add ebook than cops or bitbuckstream

**Comment by MakariAeron** [comment]
Any update on this?

**Comment by hgy59** [comment]
Ubooquity seems outdated (it requires java 8)
We have packages cops, BicBucStriim and Kavita.
