### ISSUE TITLE
undefined symbol: _PyErr_ReplaceException error after python 2.7.10 upgrade 

### ISSUE THREAD

**Issue by avercoutere** [SynoCommunity/spksrc#1753]
Hi,

I'm a DS214play user and i experience error when starting sabnzbd, headphones, sickbeard, maraschino and couchpotato since i've upgraded my synocommunity python package to 2.7.10

Here's some trace of headphone start :
```
> /var/packages/headphones/scripts/start-stop-status start
Starting Headphones ...
Traceback (most recent call last):
  File "/usr/local/headphones/share/Headphones/Headphones.py", line 23, in <module>
    from headphones import webstart, logger
  File "/volume1/@appstore/headphones/share/Headphones/headphones/__init__.py", line 25, in <module>
    import cherrypy
  File "/usr/local/headphones/share/Headphones/lib/cherrypy/__init__.py", line 61, in <module>
    from cherrypy._cpcompat import urljoin as _urljoin, urlencode as _urlencode
  File "/usr/local/headphones/share/Headphones/lib/cherrypy/_cpcompat.py", line 181, in <module>
    from urllib2 import parse_http_list, parse_keqv_list
  File "/usr/local/python/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/usr/local/python/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/local/python/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/python/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/python/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /usr/local/headphones/env/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyErr_ReplaceException
```
I have ipkg installed but i tried to remove all $PATH and $LD_LIBRARY_PATH relative to /opt without success.

I've tried uninstall pyhton and all relativ packages and reinstall without success.

The only work around for now is to replace `PYTHON="${INSTALL_DIR}/env/bin/python"` by  `PYTHON="/usr/bin/python"` in the /var/packages/{package}/scripts/start-stop-status of all scripts to use system python 2.7.9, but it don't seems to be a valid fix as i have to install some librairies like cheetah and pycurl for sabnzb and pyload.

Thanks in advance for your time,
Adrien

**Comment by avercoutere** [comment]
Forgot to say that after some research it's look like this bug http://bugs.python.org/issue23781. but it seems that it was corrected in pyhton 2.7.10 as explain here https://fossies.org/diffs/Python/2.7.9_vs_2.7.10/Include/pyerrors.h-diff.html

**Comment by Dr-Bean** [comment]
I've looked at the Python package sources I used for the packages, and that patch is indeed included.
Also, I've tested most of the packages you mentioned on a quite similar arch (bromolow) and didn't see any errors. 
Seems it's a local issue seeing as you're the only one reporting it, but either way, I don't have a fix other than reinstalling.

**Comment by Dr-Bean** [comment]
@cytec  @Diaoul FYI, I changed the name for the labels`status/closed/cannot-reproduce` to `status/cannot-reproduce` (`status/closed/duplicate` to `status/duplicate` to keep in line with the rest).
I want to be able to keep this type of issue open for a bit, but still use an appropriate label.

**Comment by Diaoul** [comment]
It's possibly related to DSM 5.2 update, maybe a toolchain update can fix this. Seems like something very arch-specific hence @Dr-Bean cannot reproduce it.

**Comment by avercoutere** [comment]
@Dr-Bean Thanks for the time, i think you're right that it's a local issue. I have several problems concerning python, ipkg, gcc, syno binary vs ipkg binary... I have switched every python startup script to /opt/bin/python and installed every librairies needed and it worked for the moment.

@Diaoul you say "toolchain update can fix this", how i managed this ? I've bootstrap my syno again yesterday without success.

Thanks again guys.

**Comment by Diaoul** [comment]
You don't need to bootstrap your NAS to benefit from packages made by SynoCommunity.
Optware is abandonned so I can only suggest you don't use it exposed to internet and/or for anything critical.

**Comment by Diaoul** [comment]
Toolchains needs to be updated in spksrc, it's nothing you can do on your side for now.

**Comment by Dr-Bean** [comment]
Toolchains don't seem all that likely to me though. Just confirmed Python can import io without issues and Headphones runs fine on Bromolow DSM5.2 with current toolchains.

So, it's either Evansport arch in particular (even though Bromolow and Evansport aren't even all that different, or it's local issue (meaning: this particular device). The latter seems the most likely to me, tbh.

**Comment by avercoutere** [comment]
After trying many things, i've completely removed optware and everything beginning to work... thanks again guys.
