### ISSUE TITLE
OpenSSL 1.0.2a 404 Not Found

### ISSUE THREAD

**Issue by richardhopton** [SynoCommunity/spksrc#1754]
When running a make on a spk the following error occurs:-

===>  Downloading files for openssl
wget http://www.openssl.org/source/openssl-1.0.2a.tar.gz
http://www.openssl.org/source/openssl-1.0.2a.tar.gz:
2015-06-12 12:51:43 ERROR 404: Not Found.

If this specific version is required then the url is now... http://www.openssl.org/source/old/1.0.2/openssl-1.0.2a.tar.gz or https://github.com/openssl/openssl/archive/OpenSSL_1_0_2a.tar.gz

Also OpenSSL maintain a clone on github too - https://github.com/openssl/openssl with this version being tagged...  https://github.com/openssl/openssl/tree/OpenSSL_1_0_2a

**Comment by Dr-Bean** [comment]
Let's use `PKG_DIST_SITE = ftp://ftp.openssl.org/source` instead. That contains both current and previous releases.

**Comment by richardhopton** [comment]
Have created a PR for this change... 
https://github.com/SynoCommunity/spksrc/pull/1755

**Comment by Dr-Bean** [comment]
Fixed with https://github.com/SynoCommunity/spksrc/commit/fd9af2b40eb4388ea9674e605adba0f94aacbe0e.
