### ISSUE TITLE
DS215+/Alpine4k Package availability

### ISSUE THREAD

**Issue by bastijnv** [SynoCommunity/spksrc#1756]
Hi,

Seems that http://packages.synology.com is no longer resolved, throwing invalid location when adding via the settings -> add sources.

My DNS is resolving it just fine, see nslookup:
Server:  dns.mnd.iss.as9143.net
Address:  212.54.44.54

Non-authoritative answer:
Name:    packages.synocommunity.com
Address:  176.31.184.40

Disabled IPv6 (other threads suggested issues). No real solution. Of course the security level is correctly set to trusted sources in addition to synology.

Tested on a DS215+, freshly installed an hour ago.

Bastijn

**Comment by piwi82** [comment]
The DS215+ uses a new architecture (<code>alpine4k</code>) that maybe the repository is not aware of. I suppose this architecture uses the same tool chain as <code>alpine</code>.

Architecture per model : https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model

**Comment by Dr-Bean** [comment]
We can add `alpine4k` arch to the repository, meaning you can add the repository to Package Center. 
But until #1703 is completed, and packages are (re)built, there won't be packages available for the 215+.

@piwi82 Correct, `alpine4k` uses the same toolchain and kernel as `alpine`.

**Comment by bastijnv** [comment]
Thanks. Makes sense. Guess I have to wait.

**Comment by Diaoul** [comment]
I added alpine4k so you can add the repository but there won't be any packages yet.

**Comment by Dr-Bean** [comment]
@Diaoul Mind if we remove and reup all `alpine` packages? I'd rather not have to bump all package versions to get `alpine4k` uploaded, and adding individual `alpine4k` packages seems a huge waste of space.

**Comment by Diaoul** [comment]
Does package deletion work correctly on spkrepo? I think I never used it :package: 
If that's the case go for it.

**Comment by Dr-Bean** [comment]
I used it...err...regularly :P Especially to upload multi-arch x64 packages, after realising bromolow got uploaded first :/

**Comment by psycho-realm** [comment]
Any news guys? Can't wait to install!:)

**Comment by Dr-Bean** [comment]
I'll return to working on this in a couple of days, I haven't had a lot of time available lately.

**Comment by psycho-realm** [comment]
Great Dr-Bean good luck mate! Thanks for your effort!

**Comment by Dr-Bean** [comment]
Packages from `bitlbee` up to `redis` (going alphabetically) have been published on the repository.
The rest is still compiling, so those will be made available at a later time. No ETA.
In the meantime, feedback is welcome.

Note: Debian-chroot will be delayed, that package will be done separately because of an open PR.

@Diaoul Seems you might have some unmerged commits locally for Mosquitto and HAProxy?

**Comment by chniko** [comment]
@Dr-Bean Thanks a lot, I've just installed Git and SickRage and looks like it's working fine.

I have one question, I tried to create the package transmission for my DS215+ (no success for the moment, I have an issue with "libcurl" during the make arch-alpine4k) and for that I created a new folder within the toolschains 'syno-alpine4k-5.2'. Did you have to do that also to generate the other you have just published or it is not necessary ?

**Comment by Dr-Bean** [comment]
I'll move Transmission up in the queue.

But you're more or less on the same track. Your approach should work fine, but we're using a slightly more efficient approach for spksrc.
Because `alpine` and `alpine4k` use the same toolchain, I've added `syno-alpine-5.2`, while making sure that `arch="alpine alpine4k"` is written to INFO (see the approach in `syno-x64-5.1`, same thing). 
I'll upload my changes to spksrc later though: I can't do it all at the same time ;)

**Comment by Dr-Bean** [comment]
...and added `rutorrent`, `sabnzbd`, `selfoss`, `shairport-sync`, `transmission`. 14 packages to go if I'm counting right.

**Comment by chniko** [comment]
@Dr-Bean Thanks :)
Another quick question
For the file `spksrc.extract.mk` I wanted to take into account the fact that the toolchains provided by Synology is in `txz` format, so I modified like that

```javascript
# Extract commands
EXTRACT_CMD.tgz = tar -xzpf $(DIST_FILE) -C $(EXTRACT_PATH)
# New for txz archives
EXTRACT_CMD.txz = tar -Jxvf $(DIST_FILE) -C $(EXTRACT_PATH)
````
but it was not taken into account, so I had to trick it like that
EXTRACT_CMD.**tgz** = tar **-Jxvf** $(DIST_FILE) -C $(EXTRACT_PATH)
but it's not proper... 
how it should be done ?

**Comment by Dr-Bean** [comment]
I'm happy to discuss this with you, but please open a new issue. Let's keep this one limited to package availability :)

**Comment by Dr-Bean** [comment]
All packages should be available on the repository, except for Debian-Chroot and Testdisk. Both packages need an update, and will be delayed.

If there are packages missing apart from the above, or packages that don't work, please let us know. In the meantime, I'm closing this as completed.

**Comment by FightingPower** [comment]
I can't install Sonarr. is it possible that Mono is still missing?
refreshed the library but it didn't appear.

**Comment by Dr-Bean** [comment]
Yep, it wasn't copied over for some reason. I'll fix that in a bit.

**Comment by Dr-Bean** [comment]
Mono should be available now.

**Comment by FightingPower** [comment]
It' s working now thanks

**Comment by psycho-realm** [comment]
Good job! Thanks for your work:)

**Comment by RodHub** [comment]
How about BTsync. I don't see it up there. :)

**Comment by Dr-Bean** [comment]
That's because we no longer provide a BTSync package, regardless of the model. Bittorrent maintains their own package from 2.0 forwards, and, assuming they publish an Alpine4k version, you can find it between the other Synology packages.

**Comment by RodHub** [comment]
So, I just have to be patient and wait for them to publish an Alpine4k version? Bummer :(
Just bought the DS215+ and was hoping to transfer all my data there. Now it will just be sitting there, waiting. Oh well, that's what you get when you buy the latest of the latest I guess.

**Comment by Dr-Bean** [comment]
I'd suggest to contact Bittorrent/head over to their forums, and ask for it. Who knows, they might not even be aware of the model...

**Comment by gore-** [comment]
HI all, 
I have a project with 43 DS215+ to install in 43 schools with storage / router / proxy - filtering
The actual SquidGuard isn't compatible with the Alpine4K, is it possible to compile for this one easily ? 

Thanks a lot for your help !
