### ISSUE TITLE
git-server failed to install

### ISSUE THREAD

**Issue by toloudis** [SynoCommunity/spksrc#1763]
Trying to install git-server 1.8.3, and I get a Failure message.  Looking at the logs, I see the following, which is the only thing that looks like an error.

/17 16:07:23     (system) trigger         :
                 Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/git-server
/17 16:07:23     (system) trigger         :
                 End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/git-server
/17 16:07:23     (system) trigger         :
                 Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/git-server
r: conf: Not found in archive
r: Exiting with failure status due to previous errors
/17 16:07:23     (system) trigger         :
                 End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/git-server
/17 16:07:23     (system) trigger        git-server 1.8.3-1:
                 Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/git-server
##

**Comment by Dr-Bean** [comment]
Don't mind the errors in the log, those are non-fatal.

The thing I'm missing here is the actual failure message you're referring to...
Also, can you confirm you've followed step 1 here: https://synocommunity.com/#easy_install?

**Comment by toloudis** [comment]
Yes, step 1 is done.
The install gets to a point where it asks me for a public key, and then I get the failure after entering it.   It's not clear if it should be for the currently logged in user but that is my assumption.
Is there anywhere else I should look for more detailed error information?

**Comment by christerjohansson** [comment]
I have this exact problem too. I can iinstall the regular GIT, but not GIT Server (beta), I get passed the public key and then it fails. From the previous log I can see that the tarball might be broken...end of file does not exist? 

My synology model is DS213+ with DSM 5.2-5565

**Comment by Dr-Bean** [comment]
I would suggest to at least add the relevant log lines.

I don't think git-server was ever checked for 5.x compatibility, and it's possible that it won't run on DSM5.x.
I can install the package without problems. However, I myself can't get the thing to work regardless of DSM version or git version (https://github.com/SynoCommunity/spksrc/pull/1472#issuecomment-73289584 and further), and I'm not going to try again anytime soon.

If you/anyone are willing to attempt fixing the package, I'd suggest to manually redo the steps in the installer via CLI, and see if that helps.

**Comment by christerjohansson** [comment]
Ok, I was not aware of this fact. On installation it clears the log too, I
don't get any logs.
I'll try to install it through my SSH instead and see if it works better. I
would really like a GIT-server at home...

2015-06-25 13:24 GMT+02:00 Dr-Bean <notifications@github.com>:

**Comment by mreppen** [comment]
The current version in the git repository installed for me (DSM 5.2), but at least gitolite was broken. The one from SynoCommunity package source doesn't install so it must be different.

3c9e691 should fix gitolite.
