### ISSUE TITLE
https://packages.synocommunity.com/ is down?

### ISSUE THREAD

**Issue by spacezed** [SynoCommunity/spksrc#1768]
Hi!, https://packages.synocommunity.com/ is down??, can't get access. any mirror? :'(

**Comment by Diaoul** [comment]
Yes it is, I'll try to look into it. We ran out of disk space.

**Comment by spacezed** [comment]
I look forward, thank you ;)

**Comment by jhenline** [comment]
Looks like it is back up, thanks.

**Comment by Dr-Bean** [comment]
@Diaoul Maybe we should remove older package versions when uploading new packages? Maybe keep one or two prev versions around, or something like that.

**Comment by dennisahlin** [comment]
It's down again?

**Comment by sjaveed** [comment]
Looks like it's down again unless it's just me.  Could someone else verify this?

**Comment by M0UL** [comment]
down for me too

**Comment by mb243** [comment]
Down for me too. 400 - Bad Request

**Comment by Gwengarion** [comment]
I cannot install any package from the synocomm, I click the button and it does nothing. Also, I cannot see all the packages in the site (Git for instance). Does anyone know what the issue is and how to solve it? Thanks!

**Comment by chniko** [comment]
@Gwengarion : what kind of Synology you have ?
If it's DS215+ for example (like me) I have the same behaviour.
It's due to the fact that this is a new architecture using a new CPU : `alpine4k`
Have a look at the issue #1756 
If you don't have this model, then it's probably something else.

**Comment by Dr-Bean** [comment]
@mb243 You're probably opening `packages.synocommunity.com` in your browser. Don't do that, that URI is only for your NAS. Use https://synocommunity.com in your browser.

Other than that, the server has been up since Diaoul has looked into it afaik, so I think we'll close this issue.
