### ISSUE TITLE
SABnzbd and Pyton 2 support for the alpine4k CPU

### ISSUE THREAD

**Issue by psycho-realm** [SynoCommunity/spksrc#1770]
Hi there,

I was wondering if you are planning to support SABnzbd and Pyton 2 for the new alpine4k processor in my DS215+/DS217 in the near future?

At the moment it is not available in the synocummunity. 

Thanks in advance for you reaction.

**Comment by piwi82** [comment]
<code>alpine4k</code> architecture will be supported.

Sources :
- https://github.com/SynoCommunity/spksrc/issues/1703#issuecomment-111233374
- https://github.com/SynoCommunity/spksrc/issues/1756#issuecomment-111979173

**Comment by psycho-realm** [comment]
Thanks for the fast respont
