### ISSUE TITLE
Home Assistant not starting

### ISSUE THREAD

**Issue by refactoredjello** [SynoCommunity/spksrc#1771]
What I did:
input user name and password and pressed login on the login page of home assistant

What I expected to happen:
I would see the home assistant dashboard

What did happen:
I remained at the verifying password screen 

I've been trying to get home assitant to load up since it first became available as an spk. I've tried use some the suggest methods found here: https://github.com/SynoCommunity/spksrc/pull/1655#issuecomment-108214252

@wind-rider

Any guidance would great!

**Comment by wind-rider** [comment]
Hi,

the default password is empty. Unless you manyally set a password you can just click login and it should show the dashboard.

For me that just works.

Today I made a new PR at https://github.com/SynoCommunity/spksrc/pull/1773, this should update Home Assistant to a new release including Chromecast support.

Some debugging guidance is also written there.
