### ISSUE TITLE
[Feature Request] Package for syncing with Mega.co cloud

### ISSUE THREAD

**Issue by kkorkmaz50** [SynoCommunity/spksrc#1772]
Hi, I am wondering if anyone is working on a package for Mega.co cloud. I think this would be nice feature for a Synology disk.

Website: https://mega.co.nz/
Description: Encrypted Cloud space, 50GB for free.
Documentation: https://mega.nz/#doc
Source code: https://mega.co.nz/#sync!linux
License: free?

**Comment by piwi82** [comment]
MEGA Sync Client is pre-compiled for major Linux distributions only, it doesn't seem to be open source.

**Comment by kkorkmaz50** [comment]
I think its possible, taking a quick glance at the terms I found:

15. Without limiting any other provision of these terms, you are only permitted to use the API if: you register at the developer registration page and agree that you may only publish or make available your application after we have approved it pursuant to our application approval process and license agreement available on request at api@mega.co.nz.

Perhaps contacting this email address might provide the source to be able to create a package?

**Comment by piwi82** [comment]
API and source code are two different things.
The source code is not available. MEGA Sync Client is a graphical client for major Linux distributions.
There is no way to get it running on a NAS, except by developing your own Sync Client using the API.

**Comment by kkorkmaz50** [comment]
thx for explaining. To bad it isnt possible. I also send an email to idea@mega.co.nz whit the question if they are planning on releasing a client for the Synology.

**Comment by kkorkmaz50** [comment]
goods news, i got a reply back from Mega that they might add support for it:
------------------------------------------------------------
Hello,

my name is Paul, I'm MEGAsync Linux developer.

I took a look at Synology and their framework to create packages.
Everything seems quite straightforward, so we might add support for this distribution at some point.

I'll let you know if / when we get to this task.

Regards
Paul.

**Comment by Dr-Bean** [comment]
If MEGA will be creating/maintaining their own package then let's close this request.
As an alternative, it seems MEGA would be a candidate to add to Cloud Sync, so you could consider opening a feature request with Synology for that.

**Comment by sam5558** [comment]
I'm relaunching this request to know if someone found a way to sync Mega with Synology ? This request was pulled in 2015 and i wasn't able to find a way to use MEGA with Synology. 
I also tried in synology chroot and MEGAsync cli but failed :'( 
Has someone succeded ? if so how ?
Sam

**Comment by rr10** [comment]
when MEGAsync for synology???

**Comment by ymartin59** [comment]
Please refer to https://github.com/john-shine/mega.syno

**Comment by crlshn** [comment]
https://github.com/meganz/MEGAcmd/tree/master/build/SynologyNAS
