### ISSUE TITLE
[Request] sabNZBd package for running from source

### ISSUE THREAD

**Issue by KaraokeStu** [SynoCommunity/spksrc#1775]
Hi,

Could someone either generate a package for this, or give me some guidance as to how I could do it myself? 

Thanks,

Stu

**Comment by Dr-Bean** [comment]
The SABnzbd source code is located here: https://github.com/sabnzbd/sabnzbd
The main file you want to edit in spksrc is:
 https://github.com/SynoCommunity/spksrc/blob/master/cross/sabnzbd/Makefile#L5
and you'll want to replace those lines around it with something like this file:
https://github.com/SynoCommunity/spksrc/blob/faf84898186f8d89cb4287b4368d2721d43f389e/cross/tt-rss/Makefile#L5

You'll probably want to edit some version information in spksrc/spk/sabnzbd/Makefile too. Other than that, follow the README on how to set up spksrc on a virtual machine and how to build packages.

**Comment by KaraokeStu** [comment]
I've created this and added a new pull request for my sabnzbd-beta package :)

https://github.com/SynoCommunity/spksrc/pull/1776

**Comment by Dr-Bean** [comment]
The package has been published for DSM5.0 and above on the beta channel, so take a look :)
