### ISSUE TITLE
btsync 1.4.111 missing from package center

### ISSUE THREAD

**Issue by evolsano** [SynoCommunity/spksrc#1777]
I can't find btsync 1.4.111 after upgrade to latest DSM 5.2.5565. I only found bittorrent sync 2 in the official package.

**Comment by Dr-Bean** [comment]
Our package has been retired. With the introduction of 2.x, BT doesn't support or maintain 1.4 anymore.

**Comment by Lorodion** [comment]
I just reinstalled my DS213+ and really need to use BTSync on it like I previously did. Had no idea that it had disappeared from the community package center or I would have made a backup of the spk myself.
Does anyone have the 1.4.111 spk for the qoriq architecture? I don't have access to any other linux environment to compile this myself..

**Comment by piwi82** [comment]
BTsync 2 is now available through Synology's official repo : https://www.synology.com/fr-fr/dsm/app_packages/bittorrentsync

BTsync 1.4 binary can still be downloaded here : http://syncapp.bittorrent.com/1.4.111/

SynoCommunity no longer provides the 1.4 package because it is obsolete.

**Comment by Turbofoehn** [comment]
Would it be possible to provide a legacy 1.4.111 package for the qoriq architecture only? At least as long as it is compatible with current versions. Unfortunately Bittorrent does no longer support that one.

@Lorodion I created an .spk for the DS 213+ by swapping out the binary. Message me, if you're still interested.

**Comment by Koernia** [comment]
@Turbofoehn I'm interested too. Any way to share the .spk somewhere ?

**Comment by Turbofoehn** [comment]
@Lorodion [btsync_1-4-111_qoriq_ds213+.spk.zip](https://github.com/SynoCommunity/spksrc/files/111550/btsync_1-4-111_qoriq_ds213.spk.zip)

YMMV, but so far, this has worked flawlessly on my DS 213+.

**Comment by The-MAD-Virus** [comment]
Is there by any chance, some one with the spk for ds413 ?

**Comment by hgy59** [comment]
> Is there by any chance, some one with the spk for ds413 ?

No chance to create it again. This package was deleted more than 8 years ago with #1747,

You can try the [btsync_1-4-111_qoriq_ds213+.spk.zip](https://github.com/SynoCommunity/spksrc/files/111550/btsync_1-4-111_qoriq_ds213.spk.zip) mentioned above, since ds213+ and ds412 are the same arch (qoriq).
This package is for DSM 3.1, so it might run on any DSM < 7.
