### ISSUE TITLE
Trying to compile xpdf from source

### ISSUE THREAD

**Issue by artelse** [SynoCommunity/spksrc#1779]
Hi, am trying to get xpdf-3.04 to build for my architecture. For the record, xpdf-3.02 is available thru ipkg, but is rather old and I want the new one to compile. I just need the command line tools pdftotext, pdfinfo, etc. not the full package.
I can unpack the source* and run ./configure with minor problems.
But how do I proceed in creating a cross compile?
Sorry to ask here, haven't seen a synocommunity forum or a clear tutorial anywhere.
thx

* xpdf source: http://www.foolabs.com/xpdf/download.html

**Comment by Dr-Bean** [comment]
Look at the INSTALL file that is part of the tarball. It should contain all the necessary information to compile from source. It seems to be a fairly straightforward approach: `./configure`, `make`, `make install`, although it does seem to have a dependency: Freetype.

To start off, add a new cross package (simply copy an existing one, rename it, and remove everything but the Makefile) and change it to suit your needs. For instance, https://github.com/SynoCommunity/spksrc/blob/master/cross/audiofile/Makefile is a fairly clean Makefile which fits your basic needs.

**Comment by artelse** [comment]
Thanks for the reply! I've made the directory and MakeFile in ```cross``` and ran ```make arch-armadaxp```. It does a bunch of stuff and then stalled here:
```/home/artelse/spksrc/toolchains/syno-armadaxp-4.3/work/arm-marvell-linux-gnueabi/bin/../lib/gcc/arm-marvell-linux-gnueabi/4.6.4/../../../../arm-marvell-linux-gnueabi/bin/ld: cannot find -lz```

Somehow it can't find zlib? Where should this be fetched and installed?
