### ISSUE TITLE
debian-chroot: several instances of "aptitude search ~U" launched

### ISSUE THREAD

**Issue by lepennec** [SynoCommunity/spksrc#1781]
Dear all,

I'm playing with the debian-chroot package on my old DS211J. Everything works flawlessly except the gui. When I launch it, it waits forever for something. I have tried to investigate and it seems that the cause is the attempt to count the number of updates available. Indeed, I see more and more instance of
- /bin/bash -c aptitude search "~U" | wc -l | tail
- aptitude search ~U
in my list of process. My perception is that it is so slow on my NAS that the command is relaunched withour killing the previous one... Any idea on how I could fix the issue?

   Yours,

    Erwan

**Comment by lepennec** [comment]
Modyfing direct.py by replacing updates_count = ... by updates_count = 0  fixes this issues... but triggers a similar one when trying to display the services... I can see more and more instances of
 /usr/local/debian-chroot/env/bin/python /usr/syno/sy
in my process list.

  Erwan

**Comment by Dr-Bean** [comment]
A new package has been released for Debian Jessie recently. Some minor modifications have been made to direct.py, which might affect your experience...probably not though.

Other than not using the GUI, I don't have any suggestions to offer (afaik, it's not necessary to use the GUI, it's simply convenience). Your current fix to set `updates_count` to `0` simply turns off the check altogether, so while that may help you in accessing the GUI, it doesn't make a lot of sense in general.
