### ISSUE TITLE
NZBGet wont update MainDir [$15]

### ISSUE THREAD

**Issue by SavellM** [SynoCommunity/spksrc#1784]
So I have an issue with NZBGet...

I changed the MainDir to /volume2/downloads from /volume2/Downloads
Just changed the D to d to keep in line with my other folders.

Also I changed the login username from NZBGet to nzbget.

I have stopped, restarted NZBget and it does not change.
It DOES change in the settings (ie it looks correct) but it doesn't actually work.

I keep getting the message: Could not create directory /volume2/Downloads/incomplete/
Even tho settings shows /volume2/downloads

Also I cannot login with the lowercase nzbget.

I have looked in SSH and the nzbget.conf and it looks correct in there too.
Unless I am missing somewhere (it was 2500 lines).

Could you let me know how to get these changes to take effect?

**Comment by SavellM** [comment]
Hi guys,

Is there anything I can do about this? I haven't downloaded in 4 days as I am waiting to change this if possible. Sorry to be a pain...

**Comment by Diaoul** [comment]
Seems like a permission issue. Make sure the `users` group has RW access to that directory.

**Comment by SavellM** [comment]
It does. Just double checked and users group has rw access

**Comment by SavellM** [comment]
I removed the permission, restarted and readded. Same thing. It seems like it won't add the correct folder or not sure. Also any update to NZBget v16?

**Comment by Diaoul** [comment]
Make sure the configuration of your MainDir is correct *in the web interface* and also in the config file located in /usr/local/nzbget/var/, then:
1. Stop nzbget
2. Move the folders created by nzbget (incomplete, complete, etc.) in a backup folder
3. Start nzbget again

It shouldn't be complaining anymore. If so, please put the message here.

**Comment by SavellM** [comment]
Ok so doubleched GUI and it is correct.
Went into nzbget.conf and this is the log:
# Root directory for all tasks.
#
# On POSIX you can use "~" as alias for home directory (e.g. "~/downloads").
# On Windows use absolute paths (e.g. "C:\Downloads").
MainDir=/volume2/downloads

So it is also correct.

Also the logs show:
# "nzbget" or use empty value.
ControlUsername=nzbget

So no longer the NZBGet...

But it seems removing the current downloads directory and recreating and restarting NZBGet seems to have got it working.

Will report back after my first successful download.

**Comment by SavellM** [comment]
OK I think that was the magic trick to remove the current directories...

Its now downloading fine and creating and moving files into the correct directories.
So no longer trying to use "D" or "NZBGet"...

Thanks, you can have the $15 ;)

**Comment by Dr-Bean** [comment]
NZBget v15 is the latest stable right now. If you want to switch over to beta versions, use the [NZBGet-testing](https://synocommunity.com/package/nzbget-testing) package. That's not a v16 either though ;)

**Comment by SavellM** [comment]
Ah right you are.

I saw dev branch and thought it was the latest... Ignore that ;)
