### ISSUE TITLE
Transmission on DS1515+

### ISSUE THREAD

**Issue by djdmg** [SynoCommunity/spksrc#1786]
I have try to install transmission on my synology DS1515+ but i always get an error ("error during installation") when 
i try to install. It's appear that transmission is comptible with avoton architectur.
Can you help me please

**Comment by Dr-Bean** [comment]
Please verify you have completed step 1 over here: https://synocommunity.com/#easy-install

**Comment by djdmg** [comment]
Thanks a lot Dr Bean is working perfect now
