### ISSUE TITLE
Can't find ImageMagick on DS414 Package Manager

### ISSUE THREAD

**Issue by dadino** [SynoCommunity/spksrc#1790]
I can see other packages in the Community tab from SynoCommunity, but I can't see ImageMagick. I already deleted SynoCommunity from the sources and added it back.
I'm now looking for an .spk to sideload, but I can't find one.
Do I have to follow some steps to have ImageMagick in the Community tab?

I'm on a DS414, which uses an ArmadaXp.

**Comment by piwi82** [comment]
ImageMagick is a beta package.
Beta packages are shown when the option is checked in the settings of Package Center.
