### ISSUE TITLE
Taking into account TXV archive from Synology

### ISSUE THREAD

**Issue by chniko** [SynoCommunity/spksrc#1793]
Hi,
I'm trying (was trying because @Dr-Bean just uploaded it!!) a spk for my Syno DS215+.
I found out that the toolchains provided by Synology was a `txv` archive.
So within the file `spksrc.extract.mk` I've tried the following:
```javascript
# Extract commands
EXTRACT_CMD.tgz = tar -xzpf $(DIST_FILE) -C $(EXTRACT_PATH)
# New for txz archives
EXTRACT_CMD.txz = tar -Jxvf $(DIST_FILE) -C $(EXTRACT_PATH)
````
but it was not taken into account, so I had to trick it like that
EXTRACT_CMD.**tgz** = tar **-Jxvf** $(DIST_FILE) -C $(EXTRACT_PATH)
but it's not proper... 
How should I do that ?

**Comment by Dr-Bean** [comment]
The extract command for a .txz file is `tar -xpf`: 
`EXTRACT_CMD.txz = tar -xpf $(DIST_FILE) -C $(EXTRACT_PATH)`

Some/Older tar versions might not correctly detect the format. Those may use `-Jxpf`, but proper up-to-date versions should not need it.

**Comment by chniko** [comment]
Ok, I will update the tar of my VM.
Thanks!
