### ISSUE TITLE
[help need] ffmpeg ppc compile error

### ISSUE THREAD

**Issue by The-MAD-Virus** [SynoCommunity/spksrc#1795]
hi every one !

can some one help me with tis error ?

```shell
CC	libavdevice/v4l2enc.o
AR	libavdevice/libavdevice.a
/home/user/spksrc-master/toolchains/syno-qoriq-5.1/work/powerpc-none-linux-gnuspe/bin/powerpc-none-linux-gnuspe-ranlib: '-D': No such file
library.mak:39: recipe for target 'libavdevice/libavdevice.a' failed
make[2]: *** [libavdevice/libavdevice.a] Error 1
```
i already check and the file exist, so what does '-D' mean ?!  i also see it in config.log when i try to compli

```shell
ranlib_default='ranlib -D'
```
all help is welcomme  ^_^

**Comment by The-MAD-Virus** [comment]
ok i did try to update the toolchain to 5.2 but there is still no '-D' option for powerpc-none-linux-gnuspe-ranlib.

so is there a way to override ranlib_default ???

**Comment by The-MAD-Virus** [comment]
ok a find the answer in the configure file of ffmpeg there is a test to check if there is or not the '-D' parameter in ranlib so all is ok but it check local ranlib and not the toolchain ranlib !

so for the moment i just remove the test with a patch, but can some one help me to find a better way ?

**Comment by vkostas** [comment]
This issue can be solved by adding this line
`CONFIGURE_ARGS += --disable-static --enable-shared --ranlib=$(RANLIB) --pkg-config=$(PKG_CONFIG_LIBDIR) --enable-pic`
Please see [issue 2082](https://github.com/SynoCommunity/spksrc/issues/2082) if you receive errors during standalone `ffmpeg` build.

**Comment by The-MAD-Virus** [comment]
Thanks mate ! I thought no one gonna help me, you just save my DS413 (ppc) !!!

Your line work pretty well, i only had to update de `lame` dependency to version 3.99.5 because the 3.99.4 doesn't exist any more.

any way thanks a lot ! hope all this gonna be update to the main version of `spksrc`

**Comment by vkostas** [comment]
I am working on building 'mpd' (created >30 dependencies).
Upgrading ffmpeg to the last version is part of my quest as well.
I am new to spksrc btw.

**Comment by schumi2004** [comment]
And where do we add this line, to ffmpeg, below existing CONFIGURE_ARGS?

In my case ffmpeg won't even compile standaloen for Alpine arch.

**Comment by vkostas** [comment]
You have to add it after (because of '+=' operator, add values to existing paraeter).

**Comment by schumi2004** [comment]
I think it's a toolchain thing. When i compile with 5.2 it always fails, standalone or as dependency.
I tried compiling it for Alpine btw.

**Comment by vkostas** [comment]
I will have a look this evening and let you know.

**Comment by vkostas** [comment]
Btw I am working on upgrading ffmpeg to the last version with full options (libass, fontconfig, etc).

**Comment by schumi2004** [comment]
Maybe it's my compile system (Ubuntu 15.10) setting up a Debian stable VM now and going to test again.

**Comment by vkostas** [comment]
I use VM Debian jessie.

**Comment by cytec** [comment]
@vkostas maybe take a look at this: https://github.com/SynoCommunity/spksrc/pull/1662 most stuff there is already done, just push the version of ffmpeg and needs some more cleanup and h265 support ;)

**Comment by Diaoul** [comment]
Take a look at the [Docker instructions](https://github.com/SynoCommunity/spksrc#docker) to setup your environement, it's much quicker than setting up a full-blown VM.

**Comment by schumi2004** [comment]
Tried new Debian VM, Docker setup and old Ubuntu VM with suggested patch but it keeps returning this error

CC  libavdevice/v4l2enc.o
AR  libavdevice/libavdevice.a
/home/user/spksrc-master/toolchains/syno-qoriq-5.1/work/powerpc-none-linux-gnuspe/bin/powerpc-none-linux-gnuspe-ranlib: '-D': No such file
library.mak:39: recipe for target 'libavdevice/libavdevice.a' failed
make[2]: *** [libavdevice/libavdevice.a] Error 1

I don't understand why it does this all of a sudden. It worked flawless not so long ago.

**Comment by cytec** [comment]
@schumi2004 see: https://github.com/SynoCommunity/spksrc/issues/1795#issuecomment-172304554 and the few coments above that one ;)

**Comment by vkostas** [comment]
@schumi2004 Adding ` --enable-pic` to `x264` `CONFIGURE_ARGS` it compiles successfully for ALPINE-5.2.

**Comment by schumi2004** [comment]
@vkostas thanks, that worked ;)

**Comment by GuillaumeSmaha** [comment]
@Dr-Bean @cytec @KaraokeStu I think it can be closed =)
