### ISSUE TITLE
cross compile go for arm devices

### ISSUE THREAD

**Issue by cytec** [SynoCommunity/spksrc#1796]
so i recently started working on a package for a go app which depends on cgo because it uses ffmpeg's libav directly. 

Seems like we'll get a problem with the current setup as `native/go` must be compiled with the proper `GOARM` version to support CGO correctly... currently it compiles without a GOARM version (i think that defaults to 6) and therefore will not work for arm5 devices (getting float abi errors)... recompiling `native/go` with `GOARM=5` fixed this for me...

@Dr-Bean @Diaoul  any thoughts on how to might "workaround" that?
maybe well have to create a "cross" package for go and compile it with the proper ARM version set for each package that depends on CGO?
##

**Comment by Dr-Bean** [comment]
Didn't #1631 address this?

**Comment by cytec** [comment]
woops seems like i've forgot that completely... 
well this fixes it for arm5 devices, can't tell if this is working for arm7 and 6 devices as i can't test... i don't know if you can compile "valid" binaries for arm7 with a native go arm compiler configured for arm5 ... I  just know it does not work the other way

**Comment by Dr-Bean** [comment]
It worked for Syncthing. The current (ARM) packages are all built with `GOARM=5`, and those work for ARMv7.

According to [this](https://code.google.com/p/go-wiki/wiki/GoArm#Lack_of_floating_point_hardware_on_ARMv5), setting GOARM=5 creates the most compatible version. The possible downside is performance is less-than-optimal on ARM versions with hardware floating point support (that is, if floating point operations are used), because GOARM=5 does not provide hardware floating point support.

**Comment by cytec** [comment]
if i recall correctly syncthing has no 3rd party dependencies which require CGO...
Don't know how that performs with c code/libs mixed with go code on arm>5 ...
also i don't know how much the performance will decrease because of this... maybe someone with an `arm7` decive can test some things here

**Comment by Dr-Bean** [comment]
I'm a bit confused...was the issue CGO support, or the GOARM var that's exported?

Afaict, CGO is not related to a particular GOARM setting, so any ARM arch will do for testing. 
CGO was turned off for Syncthing, as it caused issues for all ARM arches (fwiw, compiled with `GOARM=5`, but that's the same as upstream). 
It's not turned off for the native build, so as long as it works with cross-compiling in general, I don't see an issue with that.

As for the possible performance degradation of using `GOARM=5` for newer ARM versions: I don't have access to one of them, so can't help with that :/ Would be interesting to know though.

**Comment by cytec** [comment]
Yeah for syncthing everything should be ok :) CGO is not really needed if there is no pseudo C code in it, so everything is fine... 

if you however have a package with uses pseudo c code i _think_ you'll have to enable it (did not try to compile with CGO disabled for the actual package)... i'll have a look at that later on but from what i expierienced it throws out errors when `GOARM` wasn`t set correctly for `native/go` something with `...uses VFP register arguments, mt does not....` which hints on useing the incorrect float abi somehow..

**Comment by cytec** [comment]
Uh a little Off Topic on this one... but does anyone know how to register something to DSM's context menu? like ACEEditor/Text-Editor does? `edit with Texteditor` if it is in a supported format \cc @Diaoul

**Comment by Diaoul** [comment]
Nope, I've asked for this feature something like early 2014 but I don't recall having a positive answer. If you find an official package doing this you can inspect it.
