### ISSUE TITLE
How hard would it be to adapt Synology's toolchains to add a newer gcc to those platforms that miss C11?

### ISSUE THREAD

**Issue by piejanssens** [SynoCommunity/spksrc#1797]

**Comment by Dr-Bean** [comment]
All the tools and ingredients exist. How hard it is would probably depend on experience with working on toolchains.
For example, take a look at https://github.com/SynoCommunity/spksrc/pull/664 as an example, that might be of interest to you.

Seeing as you didn't add any content other than the subject, any particular reason you brought it up, or was it purely theoretical?

**Comment by piejanssens** [comment]
I own a DS413 which as you know has the Qoriq architecture. Seeing that Synology is no longer updating the gcc compiler in their tool chains for some platforms and that c11 is becoming more and more mainstream (ZNC for example) this is a concern.

**Comment by Dr-Bean** [comment]
Well, ZNC does seem to be the only piece of software with that limitation right now, but I understand your point.

I believe Diaoul has asked Synology if they could update the GCC version for the next release (triggered by the same ZNC issue as it so happens). I'd suggest to enter a similar feature request [here](https://www.synology.com/en-global/form/inquiry/feedback), so it gains as much traction as possible with Synology.

Other than that, if I'm not mistaken, @ximi1970 has a more up-to-date fork here: https://github.com/Ximi1970/spksrc/commits/feature-toolchains. Probably better to use that as a starting point over the previously mentioned PR.

**Comment by piejanssens** [comment]
I filed a similar feature request on the page you shared. Thanks.

**Comment by Dr-Bean** [comment]
I'm going to close this one. If someone feels like it, they can try and rebuild the Synology toolchains with a newer GCC version, and we can discuss the way forward based on that.
It's probably more likely that we end up with whatever Synology will release though ;)
