### ISSUE TITLE
[Request] Package for Node-red

### ISSUE THREAD

**Issue by allthepies** [SynoCommunity/spksrc#1799]
Hi All,

I'm getting into some Internet of Things Dev work and am using the Mosquitto MQTT broker community package successfully on my NAS.

What I'd love to have running on the NAS to complement this is Node-red http://nodered.org

I've tried installing it using the Node.js package without any success.  Would be great to have a packaged up install available.

Thanks for all the work.

Andy

**Comment by allthepies** [comment]
Actually!  Scratch that, I've managed to install it OK using npm.

**Comment by muety** [comment]
Would still be cool to have it as a Syno pacakge.
