### ISSUE TITLE
Latest sonarr update wont run.

### ISSUE THREAD

**Issue by techabyte** [SynoCommunity/spksrc#1800]
I notice an update in my package manager.

After update sonar just wont run...

2015/08/01 21:25:10     start nzbdrone: begin to start version 20150731-8
2015/08/01 21:25:12     start nzbdrone: start version 20150731-8 successfully, result 0
in the log :/ not sure the reason.

**Comment by techabyte** [comment]
Not sure what on earth has happened I changed a few things in start stop script and not sure what solved it for me.

**Comment by nzben** [comment]
I'm having this issue too. What solved it for you @techabyte?

**Comment by Dr-Bean** [comment]
That log doesn't show an issue on the package side: `start nzbdrone: start version 20150731-8 successfully, result 0` is exactly what it should be showing.
After an update, it might take a (long) while for Sonarr to start up. Just wait for a minute (literally), then try again.
