### ISSUE TITLE
[Request] SoftEther VPN server (help compiling)

### ISSUE THREAD

**Issue by Andy2244** [SynoCommunity/spksrc#1801]
Hi,

i spend the last 2 days trying to cross compile the https://www.softether.org vpn server and finally got some bins, but then on my DSM 5.2 (synology_avoton_415+) i always get those errors:
```
./vpnserver: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

The "libssl.so.1.0.0" is on the synology system under /lib, the links libssl.so/libssl.so.10 also point to libssl.so.1.0.0? If i try to statically link ssl/crypto i get similar errors for readline/ncurses libs, but those are also there.

objdump reports this:
```
Dynamic Section:
  NEEDED               libssl.so.1.0.0
  NEEDED               libcrypto.so.1.0.0
  NEEDED               libreadline.so.6
  NEEDED               libz.so
  NEEDED               libdl.so.2
  NEEDED               libpthread.so.0
  NEEDED               librt.so.1
  NEEDED               libm.so.6
  NEEDED               libncurses.so.5
  NEEDED               libc.so.6
```

I used the 32bit softether makefile and modified it, so it points to the cross avoton toolchain. I also included the needed depends in the spksrc makefile. (I was not sure if i could compile for 64bit, since in /lib64 all the shared libs where missing and spksrc also seemed to have no lib64 for the depends under /install/usr/local?)

There are a few problems for the source:
1) It needs to compile a "hamcorebuilder" inplace on the host system, since it uses this while compiling the other sources. I just manually build this on the debian 32 system and copy it to the tmp dir as needed. (the makefile needs a fix to build this tool automatically on the host, not as a crosscompile)

2) Has no advanced configure file, all it does is copy a already existing 32/64 makefile to the top folder, so most settings have to-be changed manually. I'm not a linux pro and editing makefiles manually is a pain for me, especially for correct cross-compiling.

Here is a zip with my 2 custom makefiles and the hambuilder tool bin:
https://drive.google.com/file/d/0B-4v-tWdPLgCMngzdzNEbFVBbE0

Here are the dynamic linked avoton DSM 5.2 bins for the softether server only, which do not run on my 415+:
https://drive.google.com/file/d/0B-4v-tWdPLgCaXBqZG1nbkFMNG8

Maybe someone can take a look and give some hints, since SoftEther is probably the best VPN server out there and i would like to replace the default one on my synology.

thx
Andy

PS: I also have a hard time debugging the lib problem in the synology, since all the tools like objdump/ldd/readelf are missing.

**Comment by cytec** [comment]
most likely this is because you depend on `cross/openssl` but do not copy the needed libs to the specified path...

easiest way to check this is by copy the whole install folder to your DS and then specify  `LD_LIBRARY_PATH` to point to the included lib folder before executing the binary

**Comment by Andy2244** [comment]
Ok, i copied the install/usr/lib to the NAS and pointed the LD_LIBRARY_PATH to it. This has fixed the lib problem thx, but now i get:
```
./vpnserver start
-- Alert: SoftEther VPN Kernel --
String Library Init Failed.
Please check your locale settings and iconv() libraries.
```
export shows those relevant entries:
```
export GCONV_PATH='/lib/gconv'
export HOME='/root'
export LANG='en_US.UTF8'
export LC_ALL='en_US.UTF8'
export LD_LIBRARY_PATH='/usr/local/lib'
```
"iconv" is also not present as command

**Comment by Dr-Bean** [comment]
I don't think patching the Makefile like that is necessary, all those variables should be available through spksrc. No need for hardcoding values, that makes it impossible to crosscompile for the various arches.

As for the iconv: you're missing a dependency from what I can see. Check the requirements in https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/BUILD_UNIX.TXT

**Comment by Andy2244** [comment]
So far i have given up trying to create a spkscr package, since i already spend 3 days trying to compile/run softether natively on synology, without success.
I did shift over to a docker solution, which "nearly" worked and i understand most of the settings/problems to get a VPN running inside docker. Than again, i could only get a docker setup working where i had access to any machine in the remote LAN, except the synology machine itself that runs docker+vpn.

**Comment by Dr-Bean** [comment]
The whole point of spksrc is that you don't need to compile it natively on a Synology. Cross-compile the source(s) first, package the outcome, and install the resulting package on the device.
I had a (fairly quick) look at the source, and it doesn't seem impossible to me to package that.

**Comment by Andy2244** [comment]
@Dr-Bean, you seem to misunderstood i mean run natively, which means without docker or some sort of virtual environment. I did a quick try to compile it "natively" using optware, which did not work. Thats why i tried to use spksrc, since the hoops you have to jump through are fewer than trying to setup the official cross compile framework.
As noted i got the source compiled, but i'm not able to fix the iconv() error and i also would have to spend more time fixing the makefiles, since they have some oddities. If you look at the file itself it becomes clear they are not designed to-be cross compiled. So this would involve having to write quite some scripted sed replace logic, to get a compatible spksrc package.

**Comment by Dr-Bean** [comment]
I have looked at the SoftEther configure- and makefiles...my point stands ;)
The missing iconv is likely because you'll find that you need to add `libiconv` to the dependencies (if the uploaded code is out of date, it that much harder to be able to help you out, but it's currently not there)

**Comment by Andy2244** [comment]
That don't seem to-be the problem, i have also created a libiconv() package, which i did add to the cross-compile dependencies and than statically linked it into the executable, yet i get the same error messages. I also added the package using optware and tried to use the dsm gconv and optware settings, without success. So something differs between DSM 5.2 and a real linux environment, but as noted i can not find a fix to this error.

**Comment by cytec** [comment]
Well like @Dr-Bean said already... it doesn't seem to be impossible... Personally i think (if i understood everything correctly) that you have a few problems getting your head around spksrc... 

you set `LD_LIBRARY_PATH` to `/usr/local/lib` and some other stuff and try to get it working with some kind of "mixing" spksrc and opt/ipkg... i don't think that this is a good way and i'm not even sure if this will work at all...

you _should_ only use spksrc... cross compile everything from there with the dependencies and then pack that stuff up and move it to your DS... the easiest way of doing this is by making a spk as there are all prefixes set according to the spk itself... if you however want to skip this step for now (which i do for testing all the time) i personally do something like this:

* cross compile everything including depends in `cross/xyz`
* move the whole `work-xy/install` folder to a share on my DS
* set env flags (LD_LIBRARY_PATH, etc) to point to that share (ex :/volume1/Test/xy/install/usr/local/lib` 
* try running it

maybe you`ll have to copy it to the proper prefix depending on the depends/coding of the package itself, as spksrc sets the prefix for you when configuring (which is set to /usr/local) in cross and (usr/local/packagename/) in spk if i recall that correctly

**Comment by Dr-Bean** [comment]
Well, I think I can prove it's not impossible: I seem to have a binary that starts and stops without complaining on x86-64.

That hamcorebuilder is a pain in the backside though, and will probably need a native build. For testing purposes, I'd suggest to compile with Evansport: that works on x86-64 arches and you won't run into issues related to running a 64-bit binary on a 32-bit host. Don't know if that'll work for ARM arches though.

**Comment by Andy2244** [comment]
Can you upload your makefiles, so i can try this for avoton?

**Comment by Dr-Bean** [comment]
https://github.com/Dr-Bean/spksrc/tree/softether.
Binaries end up in `$(WORK_DIR)/v$(PKG_VERS)/bin/` after a `make <arch>`. I believe you only need the two files in each of the subdirs, the rest is (presumably) compiled statically.
That needs some work when you get to creating a full package, you'll probably need to define your own `INSTALL_TARGET`, but that's the boring part ;)

**Comment by Andy2244** [comment]
Thx i really appreciating you taking the time.
I see no new DEPENDS = cross/libiconv entry or a -liconv, yet you have added the package to spksrc? So is libiconv not needed at all? Also what DSM version did you compile against 5.1 or 5.2?

**Comment by Dr-Bean** [comment]
I noticed last night that I didn't actually add the libiconv dep to softether, and softether did compile without issues. It might be that it isn't triggered when starting the vpnserver, or even that it's not used for the vpnserver (but for client/bridge/other), I can't say. That's why I said to check the DEPENDS.

The only thing I know is that the binary starts, stops and creates two config files without complaining, checking the functionality is up to you ;)

DSM5.1 or 5.2 shouldn't make a difference.

**Comment by Andy2244** [comment]
Thx, i used "evansport" and now the server starts without any extra modifications/copy of the default libs or optware laos on avoton. I assume that my problems than came from the different architectures i686 vs x86_64.

**Comment by Andy2244** [comment]
So far all seems to work as expected, but i have the same problem not being able to reach the NAS itself.
thx for your help

bye 
Andy

PS: I found out that this is some sort of linux specific behavior related to lan bridging, which was not a problem for my windows softether server. So i still need to find a way to reach the NAS itself or the VPN tunnel is rather useless :p

**Comment by Dr-Bean** [comment]
Closing in faver of #2209.
