### ISSUE TITLE
What's the technical reason there is no Syncthing spk for qoriq?

### ISSUE THREAD

**Issue by piejanssens** [SynoCommunity/spksrc#1803]
I don't see the package in my Package Center so there must be something with qoriq that makes Syncthing incompatible.

**Comment by piwi82** [comment]
See https://github.com/SynoCommunity/spksrc/issues/1011#issuecomment-44748868

**Comment by Dr-Bean** [comment]
..and if that particular comment isn't enough, @cytec has explained the issue more in depth further down in the same issue. Simply put: there's no support for ppc in Go.
