### ISSUE TITLE
[Request] SickBeard to have unique user to fix permissions issues with folders

### ISSUE THREAD

**Issue by skidaddl3** [SynoCommunity/spksrc#1804]
Like other apps (Plex), you can set permissions for folders to its own user account, therefore being able to track changes to files.

I'm not a coder, just followed what was on the synocommunity homepage.

I'm not quite sure how to get SickBeard to get the .torrent into the Black Hole, as one example. It doesn't seem to like to create a new show either...

**Comment by rawisdan** [comment]
I agree this would be helpful, having the same problem with Sonarr. Application seems really simple and a nice interface but don't want to SSH and change owners of the files etc. just to get it working. Seems to struggle with placing the files in the folders for both in progress downloads and complete downloads

**Comment by Dr-Bean** [comment]
All packages that need access to the file system are member of the group `users`, which is accessible via the DSM GUI.
If you want to set permissions for a package to write somewhere, allow the group `users` read/write access to a particular resource. Note that if you want the package to write two levels deep (i.e. `/volume1/level1/level2`), you'll need to set permissions on both `level1`(at least `Traverse folders`, so the package user can enter the directory) and `level2` (the actual permissions needed, so read/write in this example)

For Sonarr, you also can choose to set permissions via the `sc-media` group, your choice. That group, along with `sc-download` will slowly be implemented for more packages.
