### ISSUE TITLE
Pyload is out of date

### ISSUE THREAD

**Issue by ash0080** [SynoCommunity/spksrc#1807]
Pyload is out of date and cant update fresh plugins now. 
Would you plz replace it with the new stable version

http://forum.pyload.org/viewtopic.php?f=12&t=4436

**Comment by Dr-Bean** [comment]
The current version of pyLoad _is_ the latest version: 0.4.9.
What I see in your topic is that the maintainers seem to have introduced a bug somewhere, and that people are attempting to fix it with development code. 
Unless one of the maintainers explicitly says that's the proper fix, or better yet, releases a new version of pyLoad, I don't think it's a good idea to do that.
Please correct me if I'm wrong.

**Comment by ash0080** [comment]
The 1-click hosts downloader like Pyload is heavy based on plugins, Now the trouble is that, 
some code has changed in the fresh released,  At least the repository address of the update manager I think，and the old repository has been deserted. so, now it can't update itself.

So the synoCommunity version doesn't work now. Could we expect they change the repository back？

**Comment by Dr-Bean** [comment]
Yes, I understand that. It's not our package that's broken though, it's the upstream updater plugin/their repository. Everyone who auto-updates plugins has a broken installation.

You'll have to wait until the pyLoad developers respond and come up with a fix. Depending on the cause, they might be able to get the old repo back up or fix the updater and release a new version of pyLoad.

Alternatively, you can use the unofficial fix you referred to yourself. We can't introduce that change into the package before the developers respond with their course of action.

**Comment by Dr-Bean** [comment]
Fix via https://github.com/SynoCommunity/spksrc/pull/2077. Imo, releasing a new version of Pyload would have made sense, but at least this should get the package back in working order again.

**Comment by Dr-Bean** [comment]
pyload 0.4.9-2 has been published on the repository.
