### ISSUE TITLE
[Request] Please add form module for Flexget.

### ISSUE THREAD

**Issue by iruyanka** [SynoCommunity/spksrc#1808]
http://www.flexget.com/wiki/Plugins/formlogin

CRITICAL formlogin     taskname       mechanize required (python module), please install it.
WARNING  task          taskname       Aborting task (plugin: form)

We don't have form module in flexget?
I can't find in /volume1/@appstore/flexget/env/lib/python2.7

Thanks.

**Comment by Dr-Bean** [comment]
It's asking you to install the `mechanize` module. Did you try doing that?
`/usr/local/flexget/env/bin/pip install mechanize`, then see if you can install the plugin again.

**Comment by iruyanka** [comment]
OK. Thank you.
