### ISSUE TITLE
ZNC Crash

### ISSUE THREAD

**Issue by NY152** [SynoCommunity/spksrc#1809]
Since the last update ZNC, this one will launch more. I would not have to uninstall it to avoid losing the configuration. What should I do? Thank you

**Comment by Dr-Bean** [comment]
Make a backup of `/usr/local/znc/var`.

**Comment by NY152** [comment]
After complete reinstall of ZNC, I confirm it does not work on my DS412+ NAS. I do not know the cause but when launching the package it fails and nothing is possible. Also not to replace the folder /usr/local/znc/var because I have this error: "mv: write error: No space left on device"

the partition is not full yet !!!
