### ISSUE TITLE
PPC support for Mono / Sonarr

### ISSUE THREAD

**Issue by Decipher** [SynoCommunity/spksrc#1812]
Currently Mono and Sonarr have PPC architectures as unsupported, but based on the following link, that may not be the necessary: http://www.mono-project.com/docs/about-mono/supported-platforms/powerpc/

I have successfully combine Mono and am in the process of compiling Sonarr, although I have not yet tested to see if Mono installs correctly.

PR upon successful installation.

**Comment by Decipher** [comment]
Sonarr (nzbdrone) compiled without any issues, but I'm currently working remotely and don't have a good enough connection to my home network to test them. Will do first thing when I get home.

**Comment by The-MAD-Virus** [comment]
I'm pretty interested in your work and waiting for your result !
if i can help in testing ?!

**Comment by Dr-Bean** [comment]
Iirc, the issue wasn't with compiling, but that errors popped up during using Sonarr. You should be able to check that in the original thead about Sonarr.

I assume you're also updating Mono to the latest version then (as PPC support was probably introduced in v4.x)? Please check that 4.x is approved by the Sonarr devs, there was a reason we didn't update to a later version. Also, if you can, please check if PPC support also includes Qoriq, as Qoriq has a somewhat different instruction set.

**Comment by Decipher** [comment]
I can say that Mono compiles, installs and runs fine, although I can't say much more than that. I didn't do anything more than remove the 'unsupported' flag.

Sonarr compiles and installs, but doesn't run. Will do some more playing to determine exactly why.

**Comment by Dr-Bean** [comment]
Ftr, PPC support was indeed introduced with Mono 4.x: http://www.mono-project.com/docs/about-mono/releases/4.0.0.

**Comment by Dr-Bean** [comment]
Well, I did a quick test with compiling Mono 4.2.something for PPC arches: it halts somewhere halfway with a number of errors like this:
```
../../mono/metadata/sgen-client-mono.h:191: sorry, unimplemented: inlining failed in call to 'sgen_client_array_length': function body not available
sgen-scan-object.h:91: sorry, unimplemented: called from here
```
I won't be looking into it, so unless someone else does, no Mono for PPC arches unfortunately.

**Comment by Decipher** [comment]
Yeah, i've pretty much given up on anything worthwhile for PPC, and will be upgrading my Syno ASAP.

**Comment by piejanssens** [comment]
Testers needed: https://github.com/SynoCommunity/spksrc/issues/3470
