### ISSUE TITLE
BTSync is out of date

### ISSUE THREAD

**Issue by iandundas** [SynoCommunity/spksrc#1814]
The latest version, 2.0, is not compatible with the current provided version (1.4) - so if I receive a link from someone running the new latest version, I unfortunately can't use it.

**Comment by piwi82** [comment]
See https://github.com/SynoCommunity/spksrc/issues/1777#issuecomment-121882152

**Comment by M0UL** [comment]
the btsync offical repo is almost useless since it doesnt get updated allot.

**Comment by iandundas** [comment]
Ah that's perfect then - it's just listed as another app (2.0) in the official App Store. Thanks!
