### ISSUE TITLE
Sabnzbd web interface on Synology not opening

### ISSUE THREAD

**Issue by sach160** [SynoCommunity/spksrc#1818]
I've been using sabnzbd from synocommunity without issue for ages, but for no reason I can see, suddently I can't open the sabnzbd web interface anymore. Does anyone have any suggestions on how to resolve this? 

The address I use is https://10.0.1.50:9090/sabnzbd/
I've also tried the default address  http://10.0.1.50:8080 and the one showing in the log http://127.0.0.1:8080
I've tried restarting the app. I haven't tried reinstalling, - I had trouble setting it up so I'd like to see if there is a way to solve it without reinstalling first.

Log:

![screenshot 67](https://cloud.githubusercontent.com/assets/13821728/9294430/2c8c2c8c-4445-11e5-9381-9786de540c1b.png)

My system: DSM 5.2-5592 Update 2    sabnzbd version 0.7.20-13

**Comment by Dr-Bean** [comment]
See https://github.com/SynoCommunity/spksrc/issues/1286#issuecomment-60370066.

**Comment by sach160** [comment]
Thank you, this worked.
