### ISSUE TITLE
Mosquitto not available anymore?

### ISSUE THREAD

**Issue by kaandorp** [SynoCommunity/spksrc#1820]
the Mosquitto package doesn't appear anymore on my Sinology to install. I've checked on a DS 109+ and on a DS 414slim.

Both devices don't show the package.

**Comment by cytec** [comment]
should be there, i can see it on my DS ad you should too as both of the Mentioned models are supported archs by this Package: see https://synocommunity.com/package/mosquitto

maybe try reloading Package Center Informations?

**Comment by kaandorp** [comment]
I checked it on a colleagues DS as well which is a normal 414. There it's also not available. Yesterday I freshly installed a DS109+ and added the repo. Still no mosquitto package.

**Comment by Dr-Bean** [comment]
As @cytec said, it should be available. Depending on the DSM version, v3 or v4 should show up (latter is only published for DSM5.0 and up)

How are you checking for it? Searching via the search bar, or actually looking at the Community tab? See https://github.com/SynoCommunity/spksrc/issues/1689#issuecomment-102593693 if you're doing the first.

**Comment by kaandorp** [comment]
Never mind! I clicked the refresh button a few times and then it worked!
