### ISSUE TITLE
Can't install Python.

### ISSUE THREAD

**Issue by ricoooww** [SynoCommunity/spksrc#1823]
Hi,

Since I have reinstall my synology server, I get the error: Can't install Python, during the installation of SABNzbd...

**Comment by Dr-Bean** [comment]
Can you confirm you've followed step 1 here: https://synocommunity.com/#easy_install?

**Comment by ricoooww** [comment]
Oh wow... I'm sorry! Stupid me. Excuse me! It's work fine now. Thanks.
