### ISSUE TITLE
Display System Requirements for Packages

### ISSUE THREAD

**Issue by Haravikk** [SynoCommunity/spksrc#1825]
I know that most packages probably work just fine between DSM versions (are there even actually any incompatibilities with DSM 5?) however it would be nice if the packages list on the website (and available via the package centre) would automatically include required DSM versions in order to be completely clear. This way in future we could more easily see if, say, DSM 6 might break compatibility with some packages, so we know not to install the update right away.

**Comment by Dr-Bean** [comment]
We might be doing more that you realize to minimize risks of incompatibility issues...but I guess the whole point is that it looks effortless ;)

Packages that are incompatible with a certain model won't show up in Package Center. That also applies, to a certain extent, to the used DSM version on that model, within limits. 
For example: there's no functionality available to tell Package Center that a certain package is incompatible with DSM6 (read: a newer DSM version than current). 

Even if it were available, we probably wouldn't use it upfront: ultimately, someone is going to have to test packages on new DSM versions. We don't have the capability to test each model, so we rely on users to provide feedback for their model.

My advice: do not upgrade to the latest DSM version immediately after release, and wait until you feel confident that your particular setup won't be affected.

**Comment by Haravikk** [comment]
Sorry I think maybe I didn't explain myself well enough; to use the recent example of switching from DSM 4 to DSM 5, I would have liked to have been able to see which packages were confirmed to work on DSM 5 before I upgraded to it, while continuing to run DSM 4 in the meantime.

Of course, features I needed in DSM 5 forced me to upgrade anyway, and I was fortunate that nothing I had installed broke. But I could have just have easily have found that after upgrading some of my packages had stopped working.

So yeah, basically while running DSM N I'd like to be able to look at the package list, either in package centre or on the synocommunity site, and see "Compatible with DSM N+1" or such. I know a DSM 6 may be a long way off, and smaller updates probably won't break package compatibly (though there's always that possibility), I think it'd still be useful to see at a glance which packages are confirmed to work with an update before applying it. This way I can decide whether to go ahead anyway, or hold off for a while in case something crucial may break.

**Comment by Dr-Bean** [comment]
Experiences in the past have learnt that any DSM update (major or minor) may cause problems.
Furthermore, the main input for working packages comes from users of those packages, who, hopefully, open an issue here when they encounter problems. If no one opens an issue, does that mean the package is compatible? Or that the package is incompatible --but no one reported it--?
Even if other people report their packages are running after updating, that only gives an indication: some issues may pop up under certain conditions, on a certain model, or are not discovered immediately.

All in all, we can't and won't guarantee that packages are compatible with a particular DSM version. 

On the other hand, the experiences of other people may help you in deciding when to update. There are always people who update quickly, and report their findings, e.g here on this tracker or on Synology forums.
For major DSM releases, we might have a general issue opened. If there are no existing issues on this tracker, open a new issue and explain your concerns.

In any case, upgrading is at your own risk. Make sure you have working(!) backups of important data before attempting an upgrade.

**Comment by Haravikk** [comment]
Sure, but it still seems like it should still be possible for there to be some minimal system for feedback. 

One possibility actually could be spksrc itself; if users were given an opportunity to agree to anonymised profiling for a package, then spksrc could check in with the system's platform, DSM version and whether the package started successfully or not (or is still running after a few minutes).

While simply starting isn't a perfect indicator (actual features could still be broken) it could still give a very rough indicator of whether or not a DSM version breaks a package, i.e- updates would still be at your own risk, but if a package is being recorded as failing a lot under a particular DSM version, then a more concrete warning can be given about its compatibility with that DSM version.

Taking backups is of course good practice, but with Synology unwilling to support DSM version downgrades it's not exactly an easy process to roll back if a package you rely on is broken. Checking in detail whether packages will work or not is likewise good practice, but I assume you've used systems like these long enough to know that good practices are rarely followed. At least if some indication could be given it'd be much more clearly a user's own fault for upgrading if there are known issues.

**Comment by Dr-Bean** [comment]
Imo, you're making this a far bigger problem than it is. For a sense of perspective, to date, two occurrences of DSM updates have caused broken packages in the wild. Other updates have caused minor issues, but no outage, or were caught in time.
We've broken a lot more packages on our own, we don't need DSM updates for that...

If a compatibility issue is discovered, it will be fixed (*). During the time frame between discovery and fix, the communication channels are already in place: it's this tracker and probably twitter. People who are not able to find these channels won't be able to find a compatibility list.

(*)For completeness sake: If a package cannot be fixed, other measures are available, such as blocking installation for a particular DSM version or notification during package upgrade.

**Comment by Haravikk** [comment]
> For completeness sake: If a package cannot be fixed, other measures are available, such as blocking installation for a particular DSM version or notification during package upgrade.

This is the issue though; both of these mechanisms are only of use for new installations or for installing a new version of a package, they don't give any indication about whether a DSM upgrade will cause problems until it's already too late when you find the package no longer listed.

Whereas if I could go into Package Centre -> Community and see in the listing of packages that some are marked as incompatible with DSM X, or that they haven't been verified under it, then at a glance I can decide if I want to upgrade or not if any of my installed packages have a warning next to them, with the same kind of information on https://synocommunity.com/packages for people that look there instead. I don't know if such a warning can propagate down to the Installed listing (probably not if descriptions for those are stored locally).

**Comment by Dr-Bean** [comment]
I added that there to prevent it from becoming a discussion point, because there will be far bigger problems for all parties involved if that ever occurs for high-profile packages.

**Comment by Dr-Bean** [comment]
Closing. I think the discussion has run its course. I don't see a reason to set up a system to indicate whether or not a package is compatible, because such a system would be empty at this point in time.
