### ISSUE TITLE
Nzbget permission problem on shared folder

### ISSUE THREAD

**Issue by reyman** [SynoCommunity/spksrc#1828]
Hi,
I'm using latest version of nzbget 15.0-16 with ds213+

I create the shared folder to receive the finalized download after instalation of nzbget, and i have now permission error, and any download work. I try to reinstall nzbget without succes, problem persist.

`Could not create file /volume2/TVDOWNLOAD/tmp/nzb-1.tmp`

Any idea to resolve this problem ?

**Comment by Dr-Bean** [comment]
Make sure that the `users` group has sufficient permissions on the shared folder `TVDOWNLOAD`, as well as the subfolder `tmp`.

**Comment by reyman** [comment]
ok, problem solved, thanks :)
