### ISSUE TITLE
Horde 5.1.0-2 Synology // Installation fail

### ISSUE THREAD

**Issue by CarlitosSoto** [SynoCommunity/spksrc#1829]
I whent true all the screens will the one that say that is installed and the program will be ready shortly

The folder Horde on my disk station never gets populated // Folder is empty

**Comment by Dr-Bean** [comment]
Make sure you have PEAR installed (Synology package). It seems that Package Center doesn't trigger the notification anymore.

Also, note that the Horde package is a beta package, there will be some rough edges.
