### ISSUE TITLE
[owncloud] : owner and group owner inverted on folders compared to owncloud instructions

### ISSUE THREAD

**Issue by quiniouben** [SynoCommunity/spksrc#1830]
When installing SynoCommunity owncloud package, ownership for folders is http:root, thus http user and root group.
https://doc.owncloud.org/server/8.0/admin_manual/installation/installation_wizard.html documentation states the opposite : root user and http group for some folders and http:http for the rest.
In my case, in previous version (DS214+, DSM 5.2-5592 Update 3, previous owncloud version 8.0.2) it prevented me to install and activate new apps in owncloud until I apply the permissions according to the owncloud installation instructions (Setting Strong Directory Permissions part).
At udpate to new version 8.1.1, upgrade of the database went somehow wrong and restoring the permissions again according to owncloud instructions allowed to fix the trouble.

**Comment by Dr-Bean** [comment]
The ownCloud documentation is setup mainly for the larger distros, and it isn't directly applicable to DSM. The permissions setup are, as far as I know, sufficient (and limited to) to do what's needed.

Seeing as I just have enabled and disabled a whole bunch of apps without any issues at all, I'm wondering if you've either changed permissions/other details related to ownCloud (as in: your ownCloud setup isn't what we package) or that a specific plugin is causing an issue.

**Comment by quiniouben** [comment]
Hi, well, that's possible that my setup is now somehow special, but at least for the previous version (which was 8.0.2) I really had trouble using the package out of the box. However, if it works everywhere else, this is probably a special thing at mine (like my root group is not containing the correct users maybe ?),
About using different permissions than the one proposed by owncloud documentation, why not, as far as it works and fits the needs. However, let me propose that setting ownership like http:root on folders with permissions 0755 means you give http user write access on the folder whereas the intent of owncloud recommendation is exactly to prevent this and give rx permissions to http group and rwx to root user only.

**Comment by Dr-Bean** [comment]
The package is run as the `http` user, not as the `root` user. So the `http` user needs `x`, otherwise the package won't run.

**Comment by quiniouben** [comment]
Yes, I agree, and if you set ownership root:http and permissions 0755, http have x permission.
I am not part of owncloud project, but if I am not wrong, only if http user has to install the package for the first time it will need write permission for these few folders where owncloud instructions propose to use root:http ownership.
I don't want to bother you just for the theorical purity : I only encountered some troubles and wanted to give the info how I fixed it and discuss with you around this ownership topic.
Again, if the trouble is only existing at mine, I close the issue and I have nothing really strong against your ownership choices : if it works in general, that's fine.
By the way, thank you for preparing this package for the SynoCommunity.

**Comment by Dr-Bean** [comment]
Err, typo in my last message: `http` user needs `w` (and `x` obviously, but that wasn't the point). 

Seeing as ownCloud is run with the `http` user, that user needs at least `rwx` on the data dir (where your data is stored) and `rwx` on the dirs in the webfolder (`/volume1/owncloud/*`), e.g. to install plugins/apps.

We can either chown to the `http` user, or use the `http` group and adjust permissions accordingly, and either would work (on DSM5.0+ at least): on default environments the only user in the `http` group _is_ the `http` user. 
We chose for the `http` user, for several reasons, including backwards compatibility.
Does that seem reasonable?

Now, as to your problem: I can't seem to reproduce it. If the `http` user has the proper permissions (rwx on `/volumex/web/owncloud` and subdirs), then it should be able to install plugins/apps without any problems. Either it's the plugin causing it, or something else isn't the same as on my testdevice.
So, maybe you can share which plugin it was, which error messages you saw, and how you determined the problem was caused by faulty permissions.

**Comment by quiniouben** [comment]
Ok, sorry I could have guessed for the typo.
Yep, my mistake, most of folders must have http user owner, only owncloud "root" folder and .htaccess files are proposed as root:http in documentation, if I read it again more carefully now (and this is what I did on my system).
So your proposal is more than reasonable :).

About reproducing the trouble at mine, I can try to reproduce it in the next days (well, nights...) to give you more accurate information. If I remember correctly, I was first unable to activate Calendar and Contacts apps and at upgrade to 8.1.1 these two were deactivated again (which could be a owncloud "normal" behavior because version changed, that I can't tell right now).

**Comment by Dr-Bean** [comment]
Currently, all apps are deactivated automatically during updates. See https://github.com/owncloud/core/issues/16806#issuecomment-110037897 (and the other links provided in that comment). So that's 'normal' right now. As to why you couldn't activate them previously, I don't know.

**Comment by quiniouben** [comment]
Ok, let me close this issue as the title is about ownership and you propose a change to this.
I will try to reproduce my troubles and open a separate issue accordingly.
Thank you for this discussion.

**Comment by Dr-Bean** [comment]
FTR, it wasn't a proposal as in: this will be implemented. It is the current implementation ;)
