### ISSUE TITLE
Is it possible to access applications via QuickConnect

### ISSUE THREAD

**Issue by DontTurnAround** [SynoCommunity/spksrc#1832]
I will be going to college this fall and I'm planning on taking my DS214 with me, including *Sonarr* and *SABnzbd*, which I want to be able to access externally. I'm assuming that my college won't forward ports *8080* and *8989* to my disk station, so I need a way to access them without port forwarding. I could set up a reverse proxy using the built in apache server, but I would still need at least one port, preferably 80, forwarded to my disk station and that is highly unlikely.

It is possible to access my diskstation without port forwarding via QuickConnect. Is there a way I can access the Sonarr web UI with something like this `myusername.quickconnect.to/sonarr` similar to how you can access photos at `username.quickconnect.to/photos`. Or perhaps even once it resolves the IP and port, something like this `xxx.xxx.xxx.xxx:63758/sonarr`

In the Application Portal, other applications can be given a customized alias so they may be accessed simply by a directory appended to the URL.

Is there any way I can access these services externally without port forwarding?

**Comment by Dr-Bean** [comment]
Quickconnect does not support third-party applications: only the services that run via apache-sys can be accessed. The setup is quite tamper-proof...as it should be. Maybe you can get around it, maybe not.

There are ways to get some type of access outside of port forwarding, but unless I'm forgetting something obvious, nothing very appealing. E.g. setup a site-to-site VPN to an external server, or something like that.

**Comment by DontTurnAround** [comment]
I was able to get access to sonarr at `/sonarr` by directly editing the Apache vhosts to use as a reverse proxy. The only problem is that all resource links on the sonarr page are broken so it is unusable. When I looked into why, it appears I need the Apache module proxy_html to fix it. The only thing is, subplot doesn't provide that module nor apxs, the binary required to compile new modules. If anyone can tell me how to get a hold of mod_proxy_html that would be great.

**Comment by Dr-Bean** [comment]
What use is that though? You still can't access services running on port 80...

**Comment by DontTurnAround** [comment]
That is through port 5000. So what happens is if I type name.quickconnect.to in, it'll redirect to `pub.lic.ip.addr:63758`. Then I go to `pub.lic.ip.addr:63758/sonarr` and it works except for the absolutely linked resources.

**Comment by Dr-Bean** [comment]
Well, that has quite the chance of breaking then ;)
Maybe you've already discovered it, but `mod_proxy_http.so` should be available in `/etc/httpd/modules`, although it's not loaded for apache-sys.

As this is outside of the realm of SynoCommunity, I'll close the issue. But, if you find a working implementation, please share here or on the Synology forums: no doubt there are people who will find it useful.

**Comment by DontTurnAround** [comment]
Not mod_proxy_http.so which is already on the system, but mod_proxy_html.so, which is not provided by synology and impossible to compile with the build of apache they provide as they neglected to include the module compilation tool.
