### ISSUE TITLE
DSM 5.2 hangs on restart/shutdown by activated debian-chroot 

### ISSUE THREAD

**Issue by RafaelKa** [SynoCommunity/spksrc#1833]
Hello folks,

my DS214+ hangs on restart and shutdown-startup if debian-chroot is running.

Stopping debian-chroot is not possible to. Also i tried to halt debian-chroot in Web-GUI by clicking on "halt"(Anhalten) in Package-Center(Paket-Zentrum) but it hangs.
Then i tried to stop it in terminal 
```
/var/packages/debian-chroot/scripts/start-stop-status stop
Stopping Debian Chroot ...
^CTraceback (most recent call last):
  File "/usr/local/debian-chroot/app/stop.py", line 7, in <module>
    services.stop_all()
  File "/volume1/@appstore/debian-chroot/app/application/direct.py", line 78, in stop_all
    time.sleep(0.8)
KeyboardInterrupt

```
waited about 10 minutes on `Stopping Debian Chroot ...` and then pushed ctrl+c to abort this command.

Only AC plug pull out helps on hanging :/

**Comment by RafaelKa** [comment]
This happens if Service-Status from debian-chroot GUI returns always "OK". 
There was an entry for service:
```
hostname
/etc/init.d/hostname.sh
if [ `hostname` == `cat /etc/hostname` ]; then echo "OK"; else fail; fi
```

**Comment by packet68** [comment]
Hello Rafael,

I'm having exactly the same issue but on DS415+.

Could you explain in more details how you fixed it? Thanks a lot.

**Comment by RafaelKa** [comment]
@packet68: As explayned above, this happens if your command defined in DS gui for Debian services is wrong. If it returns always OK, then DS prevents shutdown, because some service is still runnung(even if it is not the case). 

Check all your entries in DS GUI for Debian Chroot, so that it returns "fail" if service is down.
