### ISSUE TITLE
Synthing on PowerPC (DS 410)

### ISSUE THREAD

**Issue by vollmersj** [SynoCommunity/spksrc#1835]
It would be great if syncthing would be supported on the PPC architecture. Thank you very much.

**Comment by cytec** [comment]
go doesn't support PPC see https://github.com/SynoCommunity/spksrc/issues/1011#issuecomment-64811369... there is also some more in depth information in that thread

**Comment by Diaoul** [comment]
Seems it is supported now: https://github.com/golang/go/tree/master/src/cmd/asm/internal/arch

**Comment by Dr-Bean** [comment]
Not sure about that. PPC64 may be supported in Go, but Synology doesn't have a PPC64 model.

The first 64-bit version Freescale provided is the e5500 core. QorIQ, PPC853x and the other PPC arch are based on a Freescale e500 core (predecessor of e5500), and that's 32 bit.
I ran into the same thing with Mono over here: https://github.com/SynoCommunity/spksrc/issues/1812.

Sources: https://en.wikipedia.org/wiki/Ppc64, https://en.wikipedia.org/wiki/PowerPC_e500, and the specsheets linked from here: http://forum.synology.com/wiki/index.php/What_kind_of_CPU_does_my_NAS_have.

**Comment by Diaoul** [comment]
Planned to check on that in the evening, thx @Dr-Bean, indeed it's 32-bit. Let's just keep that in mind if Synology decides to release a NAS with a newer PPC processor.
