### ISSUE TITLE
[Request] DNSCrypt

### ISSUE THREAD

**Issue by MMD70** [SynoCommunity/spksrc#1836]
Any chance we can get a DNSCrypt Server/Client package?

https://dnscrypt.org/
##

**Comment by cytec** [comment]
Website: https://dnscrypt.org/
Description: DNSCrypt is a protocol that authenticates communications between a DNS client and a DNS resolver. It prevents DNS spoofing.
Source code: https://github.com/jedisct1/dnscrypt-proxy

**Comment by Juiceman** [comment]
Why did you close this? I posted a $45 bounty for this two days ago.
[](https://www.bountysource.com/issues/26525373-request-dnscrypt)

**Comment by Juiceman** [comment]
`https://www.bountysource.com/issues/26525373-request-dnscrypt`

**Comment by KaraokeStu** [comment]
My bad, I was trying to close issues that hadn't  had any activity in over a year

**Comment by Juiceman** [comment]
No Worries. 😊

**Comment by cytec** [comment]
@Juiceman seems like i've got this working. as i don't know what you and @MMD70 need someone might have to test this out ;)

just throw me your arch and DSM version (keep in mind we currently only support DSM up to 5.2) and i'll try to provide you a test SPK ;)

**Comment by Juiceman** [comment]
DS216J ARM7 Armada 385 88F6820
DSM 6.1.3 but hopefully it will still work.

**Comment by cytec** [comment]
hmpf. seems like my current buildbox setup isn't able to compile for `armada38x` at all ...
i'll clean up my PR and hopefully someone will be able to push the update then

**Comment by cytec** [comment]
Done with: https://github.com/SynoCommunity/spksrc/pull/2838

**Comment by Juiceman** [comment]
Thank you so much for doing this! 😊
