### ISSUE TITLE
ImageMagick_Beta

### ISSUE THREAD

**Issue by Sebastiaan72** [SynoCommunity/spksrc#1838]
It's not working on DS214Play, Looks installed but apps (Xenforo Media Gallery, PartKeepr) can't see it.

Hopefuly you guys can sort this out <3

**Comment by Dr-Bean** [comment]
There's a difference between the ImageMagick binary and the PHP extension `Imagick` ;) We provide the first, not the second.
You could ask Synology if they can include the extension, otherwise you're looking at cross-compiling PHP and whatever else is needed to create the extension.
