### ISSUE TITLE
[Request] RDDTOOL Package for Synology

### ISSUE THREAD

**Issue by Sebastiaan72** [SynoCommunity/spksrc#1839]
Awesome graphs generated by rddtool
##

**Comment by piwi82** [comment]
You cloud provide more informations about RDDtool :
+ Official website : http://oss.oetiker.ch/rrdtool/
+ GitHub : https://github.com/oetiker/rrdtool-1.x
+ Compilation information : https://github.com/oetiker/rrdtool-1.x/blob/master/doc/rrdbuild.pod

**Comment by cytec** [comment]
i've made a cross package for that some time ago because it was required by ntopng... here you go https://github.com/cytec/spksrc/tree/develop-new/cross/rrdtool

**Comment by edasque** [comment]
@cytec did you keep rrdtool & ntopng up to date for DSM 6.x?

**Comment by ymartin59** [comment]
No package is ready for DSM 6.x yet...

**Comment by ymartin59** [comment]
@cytec Is it possible for you to publish a PR with `rrdtool` and `ntoppng` ?
