### ISSUE TITLE
Kallithea

### ISSUE THREAD

**Issue by SamuelTilly** [SynoCommunity/spksrc#184]
Hi! great repository with allot of good software, i was wondering if you could make a package for RhodeCode? so that everyone can enjoy their private git/mercurial repositories. i guess the installation would be similar to sickbeard and couchpotato. http://rhodecode.org/
##

**Comment by eldamar** [comment]
RhodeCode is no longer open source but a fork have been made called Kallithea https://kallithea-scm.org/, would love to see this available on my synology :)

**Comment by marcinkuzminski** [comment]
Just a note, rhodecode is OpenSource, sources are available here: https://code.rhodecode.com/rhodecode-enterprise-ce
