### ISSUE TITLE
Debian chroot for DS214play (synology_evansport_214play)

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#1842]
Package center on DS214play does not list Debian chroot package.
Is there any technical reason for it not to be available or is it just a package publication mistake ?

DS214play really needs it as DSM 5.2 on this 32 bits platform (Intel Atom CE5335) still runs Linux 3.2.40, preventing the use of Docker, even if 32 bits platform are not officially supported by Docker.

Thank you in advance to publish Debian chroot for DS214play

**Comment by Dr-Bean** [comment]
Debian Chroot is available for Evansport. Try refreshing Package Center.

**Comment by ymartin59** [comment]
Right. The "search" box in Package Center seems to ignore community packages. Sorry.
