### ISSUE TITLE
Squidquard SPK on 215+ (Alpine4K)

### ISSUE THREAD

**Issue by gore-** [SynoCommunity/spksrc#1843]
HI all, 
I have a project with DS215+ to install in 43 schools with storage / router / proxy - filtering
The actual SquidGuard SPK isn't compatible with the Alpine4K, is it possible to compile it for this one easily ? 

Thanks a lot for your help !

**Comment by Dr-Bean** [comment]
That package is quite outdated and I wouldn't recommend using it, especially not in a business environment.
I'm not sure if the current package still compiles, but you can try that yourself. See the README for details.

I'm in the process of reviewing #1676 which will eventually replace the current Squidguard package, but I haven't completed that yet.

**Comment by GaetanCambier** [comment]
dr-bean : the arch alpine4k is not availaible in the open source syno --> it's not possible to compile for ds215+ :s

**Comment by Dr-Bean** [comment]
`alpine4k` doesn't have a separate toolchain. The arch is basically identical to `alpine`, which is why I did this: https://github.com/SynoCommunity/spksrc/blob/master/toolchains/syno-alpine-5.2/Makefile#L3.
So, just use `make arch-alpine`, and it'll produce a package which works on both arches.

**Comment by GaetanCambier** [comment]
OK thanks, all is OK
In fact, I have a user of nas-forum that explain that (alpine not compatible with ds215+ because is à alpine4k),  but it's false.

**Comment by Dr-Bean** [comment]
Well, depending on how you look at it, that user was right ;) All packages created before that change were not compatible with `alpine4k` models, because the correct entry in INFO was missing.

**Comment by GaetanCambier** [comment]
OK, i check that when at Home
Thanks for the info

**Comment by gore-** [comment]
Great news, thanks for your help ! :) If you do that, I can test it quickly

Regards

**Comment by GaetanCambier** [comment]
i have compiled for alpine4k ;)

**Comment by gore-** [comment]
Tested and validated, it works fine ! 
A Big THANK YOU ! :D

We are in preparation for the first batch of 6 Synologys :)

Thanks again

Cyril
