### ISSUE TITLE
Retire Ruby package?

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1844]
It seems Synology is maintaining a Ruby package, and it's not too far out of date: Ruby 2.2.3 is available, Synology currently has Ruby 2.2.2 available as package.
Our current Ruby package does not compile, and the package is not on the repo because of that. 
We can update our package to latest, but unless we can offer something Synology's package doesn't, I don't see a point in that.

@SynoCommunity/developers?

**Comment by piwi82** [comment]
I totally agree, if Synology is able to maintain this package in a recent version (even if not the latest), we don't need to compile it.

**Comment by cytec** [comment]
i think it isn't even used by any other package is it?

**Comment by Dr-Bean** [comment]
Correct, there's no other package.
Ok, I guess we'll remove the (cross/native/spk) packages from spksrc in the near future, if the need arises, we can always revert/reintroduce. 

Thanks for the feedback :)

**Comment by Dr-Bean** [comment]
Done with 799f368bd5d0f3dd8627df5049027d54cb8a145c
