### ISSUE TITLE
Brand new DS214PLAY not installing SABNZBD

### ISSUE THREAD

**Issue by jtapia32** [SynoCommunity/spksrc#1845]
Hello,

I just bouhght an DS214Play, after installing the latest DSM software, I installed Python from Synocommunity successfully, but when trying to install SABNZBD, the install click does not respond. nothing happen.  I apologize I'm new with this, and I would appreciate any help.

**Comment by Dr-Bean** [comment]
Did you install SynoCommunity's Python 2.7 package (not the Python3 package)? Do you have similar problems with other packages (Synology packages, other SynoCommunity packages), or is it just the sab package?

I'd start off with a reboot of the device. You may have lost connection with it, or it has lost connection with the network, something like that.
If that doesn't yield results then probably it's time to log in via SSH (Putty or equivalent), and take a look at `/var/log/messages` and `/var/log/synopkg.log`.

**Comment by jtapia32** [comment]
Hello,

Thank you for the quick response.  Yes I installed the Python 2.7, from synocommunity and I'm able to install Sikbeard, but have the same problem when trying to install Sabnzbd or NZBget, when I click the install button it does not respond. I did reboot with no success. I will try to check the logs when I'm back from work. 

Thank you.

**Comment by jtapia32** [comment]
Hello,

Just wanted to update you that I found the issue, it has to do with an old version of IE.  I apologize for any inconvenience.
