### ISSUE TITLE
Error after installing and updating Headphones package.

### ISSUE THREAD

**Issue by MostDefiantly** [SynoCommunity/spksrc#1846]
NAS: Synology DS415+ running DSM 5.2-5592 Update 4

I can install the Headphones package, and open the web interface. But once I go to update (it's over 500 commits behind now) the package refuses to start and only option I have is to uninstall.

So perhaps updating the package to a more recent build would circumvent it dynamiting itself? Or is this a bug with the package itself?

Not sure what direction would be the "best" here.

**Comment by Dr-Bean** [comment]
Anything in the log?

**Comment by MostDefiantly** [comment]
D'oh! Bonehead move on my part not linking the log. :)

Here's the /var/log/message entries after a fresh install, update, and failure:

Sep 19 00:01:22 NAS entry.cgi_SYNO.Core.Package.Control[1].start[20843]: pkgstartstop.cpp:187 Failed to start package headphones, [1], No such file or directory
Sep 19 00:01:22 NAS entry.cgi_SYNO.Core.Package.Control[1].start[20843]: pkgstartstop.cpp:196 Failed to start package headphones, [1]
Sep 19 00:18:57 NAS PkgSynoMan.cgi: pkgtool.cpp:1332 /volume1/@tmp/55FD0C618C6413E1//WIZARD_UIFILES/install_uifile_enu: * Line 20, Column 9
Sep 19 00:18:57 NAS PkgSynoMan.cgi: pkgtool.cpp:1560 Failed to read UIFILES install_uifile_enu
Sep 19 00:19:03 NAS PkgSynoMan.cgi: pkgtool.cpp:1332 /volume1/@tmp/55FD0C67D69E42E//WIZARD_UIFILES/install_uifile_enu: * Line 20, Column 9
Sep 19 00:19:03 NAS PkgSynoMan.cgi: pkgtool.cpp:1560 Failed to read UIFILES install_uifile_enu
Sep 19 00:21:39 NAS entry.cgi_SYNO.Core.Package.Installation[1].install[26971]: pkgtool.cpp:1332 /volume1/@tmp/55FD0D03DF5A4D65//WIZARD_UIFILES/install_uifile_enu: * Line 20, Column 9
Sep 19 00:21:39 NAS entry.cgi_SYNO.Core.Package.Installation[1].install[26971]: pkgtool.cpp:1560 Failed to read UIFILES install_uifile_enu
Sep 19 00:21:39 NAS entry.cgi_SYNO.Core.Package.Installation[1].install[26971]: pkgtool.cpp:1332 /volume1/@tmp/55FD0D037D92D0C6//WIZARD_UIFILES/install_uifile_enu: * Line 20, Column 9
Sep 19 00:21:39 NAS entry.cgi_SYNO.Core.Package.Installation[1].install[26971]: pkgtool.cpp:1560 Failed to read UIFILES install_uifile_enu
Sep 19 00:21:50 NAS entry.cgi_SYNO.Core.Package.Control[1].start[26971]: pkgstartstop.cpp:187 Failed to start package headphones-custom, [1], No such file or directory
Sep 19 00:21:50 NAS entry.cgi_SYNO.Core.Package.Control[1].start[26971]: pkgstartstop.cpp:196 Failed to start package headphones-custom, [1]
Sep 19 00:23:02 NAS entry.cgi_SYNO.Core.Package.Control[1].start[28281]: pkgstartstop.cpp:187 Failed to start package headphones-custom, [1], No such file or directory
Sep 19 00:23:02 NAS entry.cgi_SYNO.Core.Package.Control[1].start[28281]: pkgstartstop.cpp:196 Failed to start package headphones-custom, [1]
Sep 19 00:25:23 NAS PkgSynoMan.cgi: pkgtool.cpp:1332 /volume1/@tmp/55FD0DE2A39E7427//WIZARD_UIFILES/install_uifile_enu: * Line 20, Column 9
Sep 19 00:25:23 NAS PkgSynoMan.cgi: pkgtool.cpp:1560 Failed to read UIFILES install_uifile_enu
Sep 19 00:25:23 NAS PkgSynoMan.cgi: pkgtool.cpp:1332 /volume1/@tmp/55FD0DE361AEEB16//WIZARD_UIFILES/install_uifile_enu: * Line 20, Column 9
Sep 19 00:25:23 NAS PkgSynoMan.cgi: pkgtool.cpp:1560 Failed to read UIFILES install_uifile_enu
Sep 19 00:27:01 NAS entry.cgi_SYNO.Core.Package.Installation[1].install[30466]: pkgtool.cpp:1332 /volume1/@tmp/55FD0E4571638E22//WIZARD_UIFILES/install_uifile_enu: * Line 20, Column 9
Sep 19 00:27:01 NAS entry.cgi_SYNO.Core.Package.Installation[1].install[30466]: pkgtool.cpp:1560 Failed to read UIFILES install_uifile_enu
Sep 19 00:27:02 NAS entry.cgi_SYNO.Core.Package.Installation[1].install[30466]: pkgtool.cpp:1332 /volume1/@tmp/55FD0E467E0EAE98//WIZARD_UIFILES/install_uifile_enu: * Line 20, Column 9
Sep 19 00:27:02 NAS entry.cgi_SYNO.Core.Package.Installation[1].install[30466]: pkgtool.cpp:1560 Failed to read UIFILES install_uifile_enu
Sep 19 00:27:14 NAS entry.cgi_SYNO.Core.Package.Control[1].start[30466]: pkgstartstop.cpp:187 Failed to start package headphones-custom, [1], No such file or directory
Sep 19 00:27:14 NAS entry.cgi_SYNO.Core.Package.Control[1].start[30466]: pkgstartstop.cpp:196 Failed to start package headphones-custom, [1]
Sep 19 00:27:27 NAS entry.cgi_SYNO.Core.Package.Control[1].start[31266]: pkgstartstop.cpp:187 Failed to start package headphones-custom, [1], No such file or directory
Sep 19 00:27:27 NAS entry.cgi_SYNO.Core.Package.Control[1].start[31266]: pkgstartstop.cpp:196 Failed to start package headphones-custom, [1]
Sep 19 00:27:35 NAS PkgSynoMan.cgi: pkgserver.cpp:253 Failed to read data.
Sep 19 00:27:35 NAS PkgSynoMan.cgi: pkgserver.cpp:253 Failed to read data.
Sep 19 00:27:35 NAS PkgSynoMan.cgi: pkgserver.cpp:615 Failed to curl perform, code=42, err=Error, url=http://packages.synocommunity.com/headphones-custom/3/headphones-custom.v3.f1594%5Bnoarch%5D.spk?arch=avoton&build=5592
Sep 19 00:37:42 NAS entry.cgi_SYNO.Core.Package.Control[1].start[2654]: pkgstartstop.cpp:187 Failed to start package headphones, [1], No such file or directory
Sep 19 00:37:42 NAS entry.cgi_SYNO.Core.Package.Control[1].start[2654]: pkgstartstop.cpp:196 Failed to start package headphones, [1]
Sep 19 10:17:01 NAS entry.cgi_SYNO.Core.Package.Control[1].start[16494]: pkgstartstop.cpp:187 Failed to start package headphones, [1], No such file or directory
Sep 19 10:17:01 NAS entry.cgi_SYNO.Core.Package.Control[1].start[16494]: pkgstartstop.cpp:196 Failed to start package headphones, [1]

**Comment by Dr-Bean** [comment]
Could you provide headphones log itself: `/usr/local/headphones/var/logs/headphones.log`?
Alternatively, start headphones manually with the following command, and see if it shows any output:
```
su headphones -c "PATH=/usr/local/headphones/env/bin:/usr/local/python/bin:/usr/local/git/bin:$PATH /usr/local/python/bin/python /usr/local/headphones/share/Headphones/Headphones.py --daemon --pidfile /usr/local/headphones/var/headphones.pid --config /usr/local/headphones/var/config.ini --datadir /usr/local/headphones/var/"
```

**Comment by MostDefiantly** [comment]
Sure. Here's the headphones.log:

21-Sep-2015 18:27:44 - INFO    :: MainThread : Checking to see if the database has all tables....
21-Sep-2015 18:27:45 - INFO    :: MainThread : Retrieving latest version information from GitHub
21-Sep-2015 18:27:46 - INFO    :: MainThread : Comparing currently installed version with latest GitHub version
21-Sep-2015 18:27:46 - INFO    :: MainThread : New version is available. You are 521 commits behind
21-Sep-2015 18:27:46 - INFO    :: MainThread : Daemonized to PID: 22318
21-Sep-2015 18:27:46 - INFO    :: MainThread : Writing PID 22318 to /usr/local/headphones/var/headphones.pid
21-Sep-2015 18:27:46 - INFO    :: MainThread : Starting Headphones on http://0.0.0.0:8181/
21-Sep-2015 18:27:54 - INFO    :: MainThread : Received signal: update
21-Sep-2015 18:27:59 - INFO    :: MainThread : Headphones is updating...
21-Sep-2015 18:28:07 - INFO    :: MainThread : Removing pidfile /usr/local/headphones/var/headphones.pid
21-Sep-2015 18:28:07 - INFO    :: MainThread : Headphones is restarting...
21-Sep-2015 18:28:07 - INFO    :: MainThread : Restarting Headphones with ['/usr/local/headphones/env/bin/python', '/usr/local/headphones/share/Headphones/Headphones.py', '--daemon', '--pidfile', '/usr/local/headphones/var/headphones.pid', '--config', '/usr/local/headphones/var/config.ini', '--datadir', '/usr/local/headphones/var/', '--nolaunch']

And here's the output after running the startup command manually:

su headphones -c "PATH=/usr/local/headphones/env/bin:/usr/local/python/bin:/usr/local/git/bin:$PATH /usr/local/python/bin/python /usr/local/headphones/share
/Headphones/Headphones.py --daemon --pidfile /usr/local/headphones/var/headphones.pid --config /usr/local/headphones/var/config.ini --datadir /usr/local/headphon
es/var/"
Traceback (most recent call last):
  File "/usr/local/headphones/share/Headphones/Headphones.py", line 23, in <module>
    from headphones import webstart, logger
  File "/volume1/@appstore/headphones/share/Headphones/headphones/__init__.py", line 67, in <module>
    SCHED = BackgroundScheduler()
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/base.py", line 61, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/base.py", line 95, in configure
    self._configure(config)
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/background.py", line 27, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/headphones/share/Headphones/lib/apscheduler/schedulers/base.py", line 576, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/headphones/share/Headphones/lib/tzlocal/unix.py", line 108, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/headphones/share/Headphones/lib/tzlocal/unix.py", line 91, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/headphones/share/Headphones/lib/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'Timezone/Pacific'

**Comment by Dr-Bean** [comment]
That error seems to suggest it's a timezone issue coming from Headphones, meaning you should probably open an issue for with the Headphones developers. It's definitely not a package issue.
It could be Synology related, but it's possible Headphones just needs to update its libraries.

You could try and change the time zone in Regional Settings in DSM, because it looks like Headphones uses the system time zone. Set it to, say, GMT+0, and see what happens.

**Comment by MostDefiantly** [comment]
Good call. I set the Timezone to GMT+0 and the package started up without producing an error.

While it was running I then set it back to GMT-8, and am now able to stop and start Headphones as expected. 

Thanks a lot for your help!

**Comment by Dr-Bean** [comment]
Great result :) Thanks for letting us know.
