### ISSUE TITLE
Package URL does not automatically update for HTTPS

### ISSUE THREAD

**Issue by flammable** [SynoCommunity/spksrc#1847]
Hello all -

I can't thank you enough for these packages - my Synology server would be far less useful otherwise.

I've gotten around to purchasing and installing a real (not self-signed) SLL cert for my server.  DSM works great!  A few of the SynoCommunity packages accept the cert, too.  The only catch is, the URLs displayed in DSM don't reflect the new HTTPS URLs and ports - so the shortcuts don't work anymore.  I started to look into how to override this, and found that the functionality is there for Sick Beard and SABnzbd, but appears to be broken.  CouchPotato is hardcoded to HTTP only.

**Sick Beard:**

After enabling HTTPS, Sick Beard no longer responds to HTTP requests.  Looking at `/usr/local/sickbeard/app/sickbeard.cgi` shows that there's an attempt to detect HTTPS:

```
#!/usr/local/sickbeard/env/bin/python
import os
import ConfigParser


config = ConfigParser.SafeConfigParser()
config.read('/usr/local/sickbeard/var/config.ini')
protocol = 'https' if int(config.get('General', 'enable_https')) else 'http'
port = int(config.get('General', 'web_port'))

print 'Location: %s://%s:%d' % (protocol, os.environ['SERVER_NAME'], port)
print
```

However, the relevant portion of config.ini looks like this:

```
[General]
enable_https = 1
```

I do not speak Python, but it appears that sickbeard.cgi is looking for enable_https to be `https`, not `1`, correct?

**SABnzbd:**

`/usr/local/sabnzbd/app/config` reads:

```
{
    ".url": {
        "com.synocommunity.packages.sabnzbd": {
            "title": "SABnzbd",
            "desc": "SABnzbd Web UI",
            "icon": "images/sabnzbd-{0}.png",
            "type": "url",
            "url": "3rdparty/sabnzbd/sabnzbd.cgi",
            "allUsers": true,
            "grantPrivilege": "local"
        }
    }
}
```

In the same directory, there's sabnzbd.cgi:

```
#!/usr/local/sabnzbd/env/bin/python
import os
import configobj


config = configobj.ConfigObj('/usr/local/sabnzbd/var/config.ini')
protocol = 'https' if int(config['misc']['enable_https']) else 'http'
https_port = int(config['misc']['port']) if len(config['misc']['https_port']) == 0 else int(config['misc']['https_port'])
port = https_port if protocol == 'https' else int(config['misc']['port'])

print 'Location: %s://%s:%d' % (protocol, os.environ['SERVER_NAME'], port)
print
```

However, after doing some searching, I found `/usr/local/sabnzbd/app/config` is actually referring to `/usr/syno/synoman/webman/3rdparty/sabnzbd/sabnzbd.cgi`, which contains the same code as `/usr/local/sabnzbd/app/sabnzbd.cgi` (it's a separate file, not a symlink).  The code appears to stem from https://github.com/SynoCommunity/spksrc/issues/338.

The relevant portions of `/usr/local/sabnzbd/var/config.ini` that these files are referencing look like:

```
https_port = 9090
enable_https = 1
```

However, the link in DSM still shows HTTP anyway.

Again, I don't understand enough Python to fully understand what's happening here, but something appears to be wrong.  I still have HTTP enabled alongside HTTPS for SABnzbd, since I can't seem to get Sick Beard to connect to SABnzbd over HTTPS (I haven't tried CouchPotato yet).  That could be related.

**CouchPotato:**

This seems a bit simpler - it's hardcoded to http on port 5050, in `/usr/local/couchpotatoserver/app/config`.  Is it safe to edit that file?  Will it be overwritten when a new version of CouchPotato is released through Package Center?  It'd be awesome if there was working logic to detect if HTTPS is enabled.

Should I file these all as separate issues, or is a single combined issue okay?  Thanks for taking a look at this!

Also, if it's relevant, I'm using DSM 5.2-5592 Update 4 on a Synology DS1815+.

**Comment by Dr-Bean** [comment]
At some point I was removing the functionality for a number of packages, and the only reason I didn't remove it for these particular packages was because the Python-based ones still seemed to work at that point. Guess they don't anymore ;)

Imo, we should remove the functionality altogether, and revert to using static shortcuts. It keeps the behavior of all packages the same, and using a reverse proxy such as haproxy is arguably better than using the built-in SSL functionality for packages.

**Comment by flammable** [comment]
Oh cool, thanks for the insight.  If I could use HAProxy to secure everything, that would take care of the remaining services that don't seem to handle SSL on their own.

I'll see if I can get that working.  I appreciate the help!

**Comment by flammable** [comment]
Hi Dr-Bean!  I know this isn't the right place to ask for help with HAProxy - is there a particular forum or guide you'd recommend for setting things up as you describe?

Thanks!

**Comment by Dr-Bean** [comment]
If you can read past the html tags, this should help a bit: https://github.com/SynoCommunity/spksrc/blob/master/spk/haproxy/src/app/help/enu/index.html.

**Comment by Dr-Bean** [comment]
@flammable Did you get things to work?

**Comment by flammable** [comment]
Hi Dr-Bean! Unfortunately, I've run into some difficulty.  I think I've found the problem, though it might be specific to my setup.

My Synology box runs on a subdomain, and I don't have the ability to add further sub-subdomains off of that (my DNS provider won't do wildcard subdomains).  It looks like the default HAProxy config is aimed at people who use a domain name solely for their box.

I started to investigate what it would take to change that to directories instead (such as sub.domain.com/transmission instead of transmission.sub.domain.com) but I must be doing something wrong - changing the "Associations" tab from:

if { hdr_beg(Host) -i transmission. }

to:

if { hdr_end(Host) -i transmission. }

doesn't seem to be working.  I'm thinking it might have to do with the regex on the Frontend tab, but that's where I stopped last weekend.  Am I on the right track?

Sorry to clutter this bug report with troubleshooting information.  I did a lot of searching online, and was trying to learn the HAProxy config file format (assuming I'd have to abandon the GUI) in an effort to get this working.  Would the Synology forums be a better place to ask for help?

Also, this might be a stupid question, but: if I have port 5443 open, I could close the HTTP ports used by Transmission, Sick Beard, SABnzbd, etc., right?  Right now, I have port forwarding set up on my router for all of those ports (and a couple more), but accessing the applications through HAProxy would encrypt them through port 5443, correct?

Thanks for all of the help with this, and again, I totally understand if you'd prefer to take this discussion elsewhere.

**Comment by Dr-Bean** [comment]
>sub.domain.com/transmission

The default setup may not be fit for your particular situation, but you can obviously change it to suit your needs ;)
Change the condition to use `path_beg` instead of `hdr_beg`: `if { path_beg /transmission }`.

>if I have port 5443 open, I could close the HTTP ports used by Transmission, Sick Beard, SABnzbd, etc., right?

Yes. All traffic to those applications (can) flow via HAProxy.
As an additional suggestion: look into setting up your router to forward incoming traffic from the WAN on port 443 to port 5443 on the NAS. That means that you can use http://example.com/transmission externally without adding the port each time.

As for other places of help, I don't think the Synology forums are the best place. HAProxy is widely used, so at the very least, there are probably mailing lists (and -archives), bugtrackers and things like that. As you can imagine, there are probably people who have had similar questions, so it's more likely you're stuck on coming up with correct search terms to get the answer you're looking for :)

**Comment by flammable** [comment]
Thanks!  That works great!

Some minor tweaks, for those who find this thread in the future:

Sick Beard: I had to edit `/usr/local/sickbeard/var/config.ini`. Change `web_root = ""` to `web_root = "/sickbeard"`
CouchPotato: In Settings, toggle Show Advanced. For "URL Base", set it to something like "couchpotato".  I also set the proxy server to 127.0.0.1:5443, but that's probably unnecessary.
SABnzbd: Worked without modification.
Transmission: Worked without modification.
HAProxy Statistics: Worked without modification.

I haven't figured out BitTorrent Sync yet - I just get "invalid request" when loading the page.  Also, DSM, Audio Station, and File Station all load blank pages.  I'm really encouraged how close I am, though.  Thank you so much, Dr-Bean!

**Comment by flammable** [comment]
Just following up again.  I found a solution to BTSync, DSM, Audio Station, and File Station.

BTSync: Looks like the URL base is hardcoded to `gui`, so I went with that.  The backend looks like: `btsync localhost:8890 check` and the association looks like: `if { path_beg /gui }`.  It's not as nice-looking as /btsync, but it's better than exposing the HTTP port.
DSM, Audio Station, and File Station: I couldn't figure out why these didn't work.  I ended up deleting the HAProxy backends and associations for all three (dsm, audio, and file).  For DSM, I enabled HTTPS on port 6101, then added that to the port forwarding on my router.  Since I only access File Station via the iOS app, I deleted the alias and custom port - I'm using DSM's HTTPS port instead.  For Audio Station, I kept the alias enabled, but am also using DSM's port 6101 for HTTPS.

It's not perfect, and I'd really like everything to go through HAPRoxy, but it looks like everything needs a URL base, and even then, DSM really doesn't like using HAProxy for its services.

Maybe one day, I'll break down and buy a full domain name for my Synology server - I'm pretty sure that would fix everything, too.

It'd be awesome if there were a way that I could change the URLs within the Synology web interface for all of these services - that's what got me to post this thread in the first place.  In the meantime, I'm just going to get comfortable with using browser bookmarks instead. :)

**Comment by Dr-Bean** [comment]
> It'd be awesome if there were a way that I could change the URLs within the Synology web interface for all of these services

Those changes would need to be redone every time DSM updates, so not a good idea. What you probably need is a way to rewrite the url/path in HAProxy. That goes beyond what the GUI provides though.

**Comment by Dr-Bean** [comment]
I'm going to close this. The original issue has been answered, and #1856 should take care of changing the shortcuts in DSM in due time.

**Comment by flammable** [comment]
Thanks for the help with this, Dr-Bean!
