### ISSUE TITLE
sshfs

### ISSUE THREAD

**Issue by sea3pea0** [SynoCommunity/spksrc#1848]
Hi everybody, I'm working on making an spk for sshfs. I'm rather new to this but I'd like to see what I can do to make this happen. So far I have cross compiled fuse. But when I try to cross compile sshfs it stops and says packages glib-2.0 and gthread-2.0 not found. I know on the website for sshfs it says fuse, glib-2.0 and glib-2.0-devel are dependencies. I did see glib in the cross folder in spkrsrc so in the make file under dependencies for sshfs I put cross/fuse and cross/glib. With that I still get the message asking for glib-2.0 and gthread-2.0. Can anyone point me in the right direction to get these dependencies sorted out? Thanks.    

This is the output from where the cross compile of sshfs fails:

configure: error: Package requirements (fuse >= 2.3 glib-2.0 gthread-2.0) were n                                                                                                                               ot met:

No package 'glib-2.0' found
No package 'gthread-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SSHFS_CFLAGS
and SSHFS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
../../mk/spksrc.configure.mk:50: recipe for target 'configure_target' failed
make[1]: *** [configure_target] Error 1
make[1]: Leaving directory '/media/spksrc/cross/sshfs-fuse'
../../mk/spksrc.cross-cc.mk:122: recipe for target 'arch-cedarview-5.2' failed
make: [arch-cedarview-5.2] Error 2 (ignored)

**Comment by Dr-Bean** [comment]
That message seems to be a generic error message if something is 'wrong' with any of the dependencies. You'll find that not all projects are ready for cross-compiling out of the box, and that is the at least the case with fuse.

Fuse puts the files in the wrong location during `make install`, amongst other things. I already had this code for another project, so this might be sufficient to get rid of the warnings in your case.

- Add `CONFIGURE_ARGS = --exec-prefix=$(STAGING_INSTALL_PREFIX)` to fuse's Makefile
- Add a patch like this:
```
--- util/Makefile.in.org	2015-08-19 10:56:51.834947550 +0200
+++ util/Makefile.in	2015-08-19 11:00:09.906943386 +0200
@@ -650,7 +650,7 @@
 
 info-am:
 
-install-data-am: install-data-local
+install-data-am:
 
 install-dvi: install-dvi-am
 
@@ -730,10 +730,8 @@
 	fi
 
 install-exec-local:
-	$(MKDIR_P) $(DESTDIR)$(MOUNT_FUSE_PATH)
-	$(INSTALL_PROGRAM) $(builddir)/mount.fuse $(DESTDIR)$(MOUNT_FUSE_PATH)/mount.fuse
-	$(MKDIR_P) $(DESTDIR)$(INIT_D_PATH)
-	$(INSTALL_SCRIPT) $(srcdir)/init_script $(DESTDIR)$(INIT_D_PATH)/fuse
+	$(MKDIR_P) $(sbindir)
+	$(INSTALL_PROGRAM) $(builddir)/mount.fuse $(sbindir)/mount.fuse
 	@if test -x /usr/sbin/update-rc.d; then \
 		echo "/usr/sbin/update-rc.d fuse start 34 S . start 41 0 6 . || true"; \
 		/usr/sbin/update-rc.d fuse start 34 S . start 41 0 6 . || true; \
```

**Comment by sea3pea0** [comment]
Okay that worked. I was able to cross compile sshfs-fuse. So, in cross/sshfs-fuse/work.. I have a fuse.plist file, a glib.plist file, a libffi.plist file, a sshfs.plist file and a zlib.plist file. When making the PLIST file do I take from all of those and merge them into one PLIST file in the cross/sshfs-fuse folder?

I am a little unsure about the next step in making the actual spk. Do I take a template, say spk/nano and copy it into spk/sshfs-fuse and then put the PLIST file I made in that folder and edit the makefile, then in spf/sshfs-fuse/src edit the dsm.control.sh as well as the installer.sh files?

**Comment by Dr-Bean** [comment]
Take a look at the PLIST wiki article [here](https://github.com/SynoCommunity/spksrc/wiki/PLIST-files).
Also, check how other (cross) packages work (as in: look at the contents, compile it, and see what the result is). Each PLIST contains only the information for that particular cross package, nothing else.

As for copying another package as a template, I believe the README suggests as much. It obviously doesn't matter how it's written, but copying from a (relatively comparable) package is easier in that you get the formatting and order right and you're less likely to forget entries or files.
So yes, copy Nano's approach, and start editing that. Also compile the Nano package itself, so you can compare between the two.
You might want to keep a copy of the DSM Developers Guide handy as well. Link should be available on the Synology site.

**Comment by sea3pea0** [comment]
I am proud to say I just completed a working spk for sshfs-fuse! Thanks for your help and encouragement, without which I probably would not have embarked on this task.

I think I did a pretty good job, the only thing I can think of that might need some refinement is my PLIST file for sshfs-fuse. It might have some items in it that could be stripped out. 

Next I am going to try and figure out how to fork this so I can share my work.

**Comment by Dr-Bean** [comment]
sshfs 2.5-1 has been published on the repository.

**Comment by dthorpe** [comment]
How does one use / configure this sshfs service after it is installed on my DSM?

**Comment by sea3pea0** [comment]
You use it from the command line. Personally I use an upstart script to make my sshfs mount. Here is a link that explains how to use sshfs: http://linux.die.net/man/1/sshfs . You can change some configuration options in /etc/fuse.conf . If you want I could post the contents of my upstart script that is use to make my sshfs mount.
