### ISSUE TITLE
ZNC Login details

### ISSUE THREAD

**Issue by paxter** [SynoCommunity/spksrc#1849]
I've just installed ZNC package and the service is running, but how I can login into the webinterface? There isn't any configuration to change. I tried my synology user account, but that doesn't work.
Maybe somebody can help me with that issue.

**Comment by Dr-Bean** [comment]
You have provided the login details during the install wizard. If you didn't change those details, it's admin/admin.

**Comment by paxter** [comment]
Haha lol, you're right. I reinstalled ZNC with other login datas and now it's working. Thanks for helping and sorry for disturbing.
regards
