### ISSUE TITLE
[Request] rutorrent ipfiltering

### ISSUE THREAD

**Issue by Mullett** [SynoCommunity/spksrc#1853]
The new version of rtorrent gives the ability to add ipfilter if rtorrent has been compiled with it enabled.

Would it be possible to update so that it supports this feature please.
##

**Comment by piwi82** [comment]
You could also use the firewall to filter IP addresses.

**Comment by Mullett** [comment]
all 400,000+ of them lol?

**Comment by piwi82** [comment]
I don't know why you need so much IP addresses to be filtered, but @cytec could probably help about adding ipfilter to rutorrent.

https://github.com/SynoCommunity/spksrc/commits/master/spk/rutorrent

**Comment by Mullett** [comment]
it basically blocks IPs that track your activity. It has been a feature in most torrent clients for a few years now.
