### ISSUE TITLE
[Request] Tvheadend v4.0.5

### ISSUE THREAD

**Issue by inrepublica** [SynoCommunity/spksrc#1855]
Hi,

Tvheadend has relaeased a new stable version in 4.0.5.
Apparently a package exist here: http://syno.dierkse.nl/
##

**Comment by Dr-Bean** [comment]
@jdierkse?

**Comment by PiterEL** [comment]
Has anybody newest (latest) version TVHeadend on Synology ? I have model DS713+. please give me link where i can download latest version in spk ?

Anybody has with transcodding ?

Jdierkse can you update spk to latest version TVHeadend 4.1.1207 ?

**Comment by Dr-Bean** [comment]
@PiterEL This is not a discussion forum, but a bug tracker for SynoCommunity and the spksrc framework.

If the package/version you want does not exist on the SynoCommunity repository, then apparently no-one is interested enough in creating and maintaining it.

**Comment by dagwieers** [comment]
+1 A newer tvheadend would be very much appreciated !

**Comment by gtkow** [comment]
With the new version of kodi (16) the plugin tvheadend dosen't work with the old version of TVHeadend  server. Please it's possible to upgrade the version?

**Comment by GoodOmens83** [comment]
Does anyone know a source of tar balls for the 4.1 releases?

I've updated TVheadend to 4.0.8 in a recent PR: https://github.com/SynoCommunity/spksrc/pull/2189

**Comment by m4tt075** [comment]
Outdated. Can you close this, please?

**Comment by m4tt075** [comment]
@KaraokeStu : Could you close this, please?

**Comment by m4tt075** [comment]
@ymartin59 Could you close this, please?

**Comment by ymartin59** [comment]
Now package has been published. Sure I do.
