### ISSUE TITLE
Revert python-based DSM shortcuts to static shortcuts

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1856]
According to #1847, using shortcuts based on config don't work anymore. Seeing as it's also inconsistent with most packages where the functionality isn't even available, let's revert to static shortcuts.
Packages: ~~deluge~~, mylar, ~~sabnzbd~~, ~~sabnzbd-testing~~, ~~sickbeard~~.

~~(As for Sickbeard, I'm considering retiring the sickbeard package or merging it with the sickbeard-custom package somehow, seeing as it hasn't seen active development in quite a while)~~ Done via #1925.

**Comment by Dr-Bean** [comment]
SABnzbd-testing package done with 887d2acdcd118b352f766f67e246aa02bfd22c5a

**Comment by BKSteve** [comment]
Dr-Bean, could you look at SickRage package too please, it's pretty much replaced the SickBeard-Custom

**Comment by Dr-Bean** [comment]
@BKSteve If you're referring to the similarities between SickRage and the Sickbeard-Custom package, both of those serve their own purpose. If you want to discuss that, please do so in a separate issue. If you're referring to something else, please explain.

**Comment by BKSteve** [comment]
@Dr-Bean what I meant was I moved from SickBeard-Custom (SBC) which provided a DSM Shortcut to SickRage (SR) which for me does not provide a DSM shortcut.
Looking into the two packages app/config the SR package does not seem to provide or create the DSM shortcut. I even made a SickRage.cgi file and modified the config but still no DSM Shortcut.

**Comment by Dr-Bean** [comment]
@BKSteve If you don't use the `admin` account, you must set permissions to show the icon via Control Panel>Privileges.

**Comment by BKSteve** [comment]
@Dr-Bean thanks, this was the issue, totally forgot user privileges

**Comment by Dr-Bean** [comment]
Deluge done with https://github.com/SynoCommunity/spksrc/commit/4a9d7846001ca724aad5106391da0344f868c9a3

**Comment by Dr-Bean** [comment]
Sabnzbd done with https://github.com/SynoCommunity/spksrc/commit/ddfb420015fc698d0f9316c0cca743f0aba012ed.

**Comment by Dr-Bean** [comment]
Mylar done with 34fc319f31fe42fa72d57d0f2693858d8a734e96, no package release as package needs a general review at this point.
With that, the work here is done.
