### ISSUE TITLE
Update Mono to 4.x, publish as beta package

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1857]
Mono 4.x is available and stable. There are a large amount of changes between 3.10 and 4.x, and as there are some reports of issues with Sonarr, we want to be careful with replacing the current 3.10 package.

I have been running 4.0.4.1 locally for the last couple of weeks without issues, but according to the Sonarr devs, regressions occur even between minor releases, and might only pop up under certain conditions.

Let's update the package to the latest stable, release it as beta alongside 3.10, and keep it there for a reasonable time (1~2 months). If we receive feedback, we should forward that to the Sonarr devs.

**Comment by M0UL** [comment]
+1

**Comment by cytec** [comment]
1+ for running them side by side for a reasonable time... don't know how emby will handle 4.x but according to their website, emby should be fine running with mono 4

**Comment by M0UL** [comment]
sonarr also will run fine with mono 4.x

**Comment by Dr-Bean** [comment]
The issue is less with the packages using Mono, it's Mono introducing regressions with new versions (which, in turn, break the packages that use it...) The Sonarr devs prefer a longer beta period because those bugs don't necessarily show up immediately and can be hard to catch.

Anyway, I'll hopefully merge/publish in a couple of days.

**Comment by Dr-Bean** [comment]
mono 4.0.4.1-5 has been published on the repository.
