### ISSUE TITLE
[Bug] A l'installation du package Transmission

### ISSUE THREAD

**Issue by clark17** [SynoCommunity/spksrc#1858]
Quand on installe le paquet transmission celui-ci nous demande un répertoire où stocker les téléchargements. On ne peut choisir qu'un répertoire existant car si on essaye avec le répertoire par défaut:
![1](http://i.imgur.com/9oMmeK5.png)

Du coup j'indique un répertoire existant et l'installation ce passe sans problème.
Mais ensuite quand je lance un torrent j'ai une erreur "permission denied":
![1](http://i.imgur.com/NmGUQ44.png)

Cela semble être un problème de droits accorder ou non a l'utilisateur transmission.

**Comment by Dr-Bean** [comment]
English please :) Fwiw, both your problems have been discussed multiple times on this tracker.

First screenshot: We don't create the dirs on the file system, you need to do that yourself. So, in that case, you should create a shared folder called `downloads` before installing Transmission.

Second screenshot: we only set permissions on the lowest level. In this case, we set r/w permissions on `Telechargements`. We do not set permissions for `Stockage`. 
You should set, at the very least, `Traverse folders` permissions (part of `read` permissions) for the `users` group.

**Comment by Dr-Bean** [comment]
Closing due to lack of response...
