### ISSUE TITLE
headphones-custom problem

### ISSUE THREAD

**Issue by sea3pea0** [SynoCommunity/spksrc#1861]
I re-installed my Synology OS and I am having problems getting headphones-custom working again even though it was working before. I tried it with both the master and develop branches. After installing everything looks normal, to me, in the [logs](https://gist.github.com/sea3pea0/86c7fe8e0d12f3a49c42). However I am unable to connect to the web server. I ran it from the command line to see if anything looked wrong in the console but everything looked fine. I tried changing the port, restarting, rebooting the router but nothing I have thought of yet has worked. Couchpotato-custom works, the standard headphones package works just not the custom one. It was working yesterday before I reinstalled the OS, but it was an old install that had since been updated to the latest commit.

**Comment by Dr-Bean** [comment]
Noticed that a while back, but hadn't fixed it yet. https://github.com/rembo10/headphones/commit/f131d316caf146fd145ec4ca947a80c073803b7e caused this.

Stop the package, and change the entry `http_host = localhost` to `http_host = 0.0.0.0` in `/usr/local/headphones-custom/var/config.ini`.

We should add that to the config.ini of both Headphones packages.

**Comment by Dr-Bean** [comment]
Fixed with 4068337d056a507766557f21b8a6cb27846cd525 and c58e134c973a8a62227931007d6b185e1e98b474. Both packages have been updated on the repository.
Thanks for reporting ;)
