### ISSUE TITLE
Bitlbee update 3.4.1 (or higher)

### ISSUE THREAD

**Issue by FoUStep** [SynoCommunity/spksrc#1863]
Does anyone know if the current version 3.2.2-10 gets updated to 3.4.1 (or higher if it's available?). I've sent an e-mail to the maintainer but he does not reply.

Maybe anyone else is capable of doing this?

**Comment by CondormanFr** [comment]
I do the change and the pull request is waiting for approval.
Can I build a spk for your device and you test it ?

**Comment by FoUStep** [comment]
Sure if I know how to install this properly as a package on my DS212J. (another repo?)

**Comment by CondormanFr** [comment]
Are you in DSM 5.2?

Envoyé depuis un mobile Samsung.

<div>-------- Message d'origine --------</div><div>De : FoUStep <notifications@github.com> </div><div>Date :09/10/2015  07:21  (GMT+01:00) </div><div>À : SynoCommunity/spksrc <spksrc@noreply.github.com> </div><div>Cc : CondormanFr <github@gouyet.com> </div><div>Objet : Re: [spksrc] Bitlbee update 3.4.1 (or higher) (#1863) </div><div>
</div>Sure if I know how to install this properly as a package on my DS212J. (another repo?)

**Comment by FoUStep** [comment]
Yes I’m on build DSM 5.2-5592

**Comment by CondormanFr** [comment]
Here is the package for DS212J DSM 5.2

 

You just have to go to package manager and choose manual installation and select the .SPK file.

See https://help.synology.com/dsm/?section=DSM <https://help.synology.com/dsm/?section=DSM&version=5.2&link=PkgManApp%2Finstall_buy.html> &version=5.2&link=PkgManApp%2Finstall_buy.html

 

Let me know.

**Comment by FoUStep** [comment]
Sounds easy enough CondormanFr, however I cannot see your .SPK file attached (to somewhere).

**Comment by Dr-Bean** [comment]
Github doesn't allow mail attachments, @CondormanFr. You can upload the SPK somewhere, and provide a link for @FoUStep.

**Comment by CondormanFr** [comment]
@FoUStep <https://github.com/FoUStep>  : Here is a link to download the spk.

 

http://ovh.to/Z4eGG9V

 

De : Dr-Bean [mailto:notifications@github.com] 
Envoyé : vendredi 9 octobre 2015 12:14
À : SynoCommunity/spksrc <spksrc@noreply.github.com>
Cc : CondormanFr <github@gouyet.com>
Objet : Re: [spksrc] Bitlbee update 3.4.1 (or higher) (#1863)

 

Github doesn't allow mail attachments, @CondormanFr <https://github.com/CondormanFr> . You can upload the SPK somewhere, and provide a link for @FoUStep <https://github.com/FoUStep> .

**Comment by FoUStep** [comment]
Trying to install, it says: “Processing. Please wait…”. Currently running for 10+ minutes, I’ll let it run for a while, not sure if it times out or running out.

**Comment by FoUStep** [comment]
Works great, had to stop old bitlbee 3.2.2-10 and change properties of allowing non digital signatures. MSN works again as well.

**Comment by CondormanFr** [comment]
Good news. Waiting for @Dr-Bean for approval and publish on SynoCommunity.

**Comment by FoUStep** [comment]
No issues so far. Thanks CondormanFr!

**Comment by Dr-Bean** [comment]
Bitlbee 3.4.1-11 has been published on the repository. Thanks @CondormanFr.
