### ISSUE TITLE
Plexivity 0.9.7-8 : Failed to run package.  Cannot downgrade now, please help

### ISSUE THREAD

**Issue by dsakai** [SynoCommunity/spksrc#1868]
I've been running Plexivity for a few months now without any major issues (except that "top movies" does not show).  But after the update this morning, it would load.  Nor can I downgrade back to 0.9.6-x

Please help.

Thanks,

David

**Comment by Dr-Bean** [comment]
We don't provide a package for Plexivity, so we can't help with that.
/cc @cytec, assuming the package was provided via cytec.us, make sense to set a different distributor instead of SynoCommunity.

**Comment by cytec** [comment]
... i'll check that

**Comment by Dr-Bean** [comment]
[offtopic for here] @cytec, you might want to look at replacing that pybundle with something else. Pip hasn't supported pybundles for a while now.

**Comment by cytec** [comment]
@dsakai seems like somehow the requirements are't installed correctly... like @Dr-Bean mentioned pybundles aren't supported anymore and i didn't think about that when updating the package... so a quick fix would be:

1. ssh into your DS
2. run `/usr/local/plexivity/env/bin/pip install -r /usr/local/plexivity/share/plexivity/requirements.txt` 

after that finished it should start up :)

also i should make a PR for that Package finally ^^

**Comment by cytec** [comment]
@Dr-Bean so when i redo this... if i recall that correctly `WHEELS` can't be set to `share/requirements.txt` because it builds wheels before it clones the repo and therefore i am not able to use the requirements.txt provided by the package itself... so i have to include requirements.txt in src and keep it up to date myself?

**Comment by Dr-Bean** [comment]
Yep. You could presumably use a cross package for the project itself, and get the requirements.txt from that, but I'd prefer it if you didn't if the project doesn't need cross-compiling.

Thing is, you need to check/verify the requirements anyway. Maybe not all of the requirements are (or stay) pure-python.
Also, not all devs add all the modules to requirements.txt: some may be listed in setup.py instead, and sometimes, the dev doesn't register the (dependencies of) dependencies of requirements. If you don't know for sure, the safest thing to do is to include them all.

You might find it helpful to install the complete project on a separate Debian VM/in a separate virtualenv, and do a `pip freeze > new_requirements.txt` after installation. That way, you can compare it with the original requirements.txt and go from there.

One remark, somewhat related to the above: if you don't need `--system-site-packages`, then don't use it. Makes the package easier to maintain in the long run imo.

**Comment by cytec** [comment]
PR is here: https://github.com/SynoCommunity/spksrc/pull/1871

**Comment by Dr-Bean** [comment]
Comments are there too ;) As for the clone vs cross package, I was thinking along a different track than you, I guess. It makes sense to create a cross package if you can download a tarball for a specific release (and extract it to /share/thing etc), and you can in this case.
That means that at least theoretically, you can use the included requirements, as long as you're aware of the risks involved.

**Comment by cytec** [comment]
@Dr-Bean yeah right... that would be an +1 for a cross package but for now i'd like to keep it with the simple git clone solution, maybe i'll move it to a specific cross package with the next update and for this time keep an eye on the requirements.txt provided with the source :)
