### ISSUE TITLE
Update Node.js to 4.2 LTS

### ISSUE THREAD

**Issue by leak** [SynoCommunity/spksrc#1872]
Could anyone please update the Node.js package to version 4.2 which is marked for Long Term Support and also incorporates the features from the reintegrated io.js fork.
##

**Comment by Dr-Bean** [comment]
According to https://github.com/nodejs/node#unix--macintosh, GCC4.8 is needed. The current toolchains go up to GCC4.7, which is why we can't update the package.
We requested Synology to update GCC (via e.g. https://github.com/SynoCommunity/spksrc/issues/1457#issuecomment-81726526), so maybe that's included in the next toolchain release. 

You might want to consider asking Synology to update their Node package via https://www.synology.com/en-global/form/inquiry/feedback, then we can retire our package ;)

**Comment by hmalphettes** [comment]
Thanks for the feedback link: filed the request.
Here is my vote for others to raise Synology's attention about node support: if you want it go and fill it.

For now in my case I run node-0.12 with the `--harmony` option.
It will give you block scoping (const/let), generators, Map and Set (incomplete).
Avoid buggy arrow functions. Multi-line template strings are unsupported.

More complete list: http://stackoverflow.com/questions/28388885/ecmascript-6-features-available-in-node-js-0-12

**Comment by leak** [comment]
Thanks for the pointers. I also started an inquiry about node and the toolchain.

**Comment by iharris** [comment]
Yes, would be very good to get the latest version running vs 6 months old.

**Comment by W7PEA** [comment]
The new DSM 6 Beta is out, has anyone been able to check we can upgrade NodeJS after 6 is out?

**Comment by piwi82** [comment]
New toolchains for DSM6 beta 2 are out (2 hours ago) : https://sourceforge.net/projects/dsgpl/files/DSM%206.0%20Beta2%20Tool%20Chains/
I don't know how to check the version of GCC.

**Comment by piwi82** [comment]
Synology provides packages for NodeJS [v0.10](https://www.synology.com/fr-fr/dsm/app_packages/Node_js_v0_10), [v0.12](https://www.synology.com/fr-fr/dsm/app_packages/Node_js) and [v4](https://www.synology.com/fr-fr/dsm/app_packages/Node_js_v4).

**Comment by Dr-Bean** [comment]
Seeing as Synology appears to be maintaining their Node packages again, I think we should consider retiring our Node package. 
We don't use Node as a dependency for other packages, and providing an identical base package like this seems unnecessary.

@SynoCommunity/developers?

**Comment by andyearnshaw** [comment]
Only NodeJS v0.10 is available when I search on my DS212+.  I wonder if there's a specific reason for this.

**Comment by Dr-Bean** [comment]
From a certain version onwards V8, the engine, doesn't run on ARMv5 anymore: https://github.com/SynoCommunity/spksrc/pull/1475#issuecomment-74140724.

I've turned off distribution of the packages. We can remove the code from spskrc in the near future.

**Comment by Dr-Bean** [comment]
Node has been removed with fed349ebf1c48a25b98526a181e8ceb0eca4f24a

**Comment by hmalphettes** [comment]
@Dr-Bean thanks for caring after this package and retiring it. Much appreciated!
