### ISSUE TITLE
Architectures modifications

### ISSUE THREAD

**Issue by piwi82** [SynoCommunity/spksrc#1873]
Synology has changed the names of some architectures, just take a look at http://download.synology.com/download/spk/Spreadsheet/1.0-0058/

I don't know yet what <code>armv5</code>, <code>armv7</code>, and <code>i686</code> are replacing, but there is no change in clients requests to the package server :

<pre>[13/Oct/2015:18:31:14 +0200] "GET /vim/2/vim.v2.f1594%5B88f628x%5D.spk?arch=88f628x&build=7135&unique=synology_88f6282_211&build=7135&major=6&pkg_version=&minor=0&mode=install HTTP/1.1" 200 10178560 "-" "synology_88f6282_211 DSM6.0-7135 (package)"</pre>

##

**Comment by Dr-Bean** [comment]
Interesting :) Synology seems to be using the same approach as our x64 packages, but for ARM as well.

The following table is unconfirmed until Synology publishes a new toolkit version, but this is what I came up with. Maybe the new toolchains will follow the same approach, but we'll have to wait and see. I don't think it would matter too much.

Synology | Toolchain
------------ | -------------
armada370 | armada370
armada375 | armada375
(armada38x) | (armada38x)
armadaxp | armadaxp
armv5 | 88f528x 88f628x 
armv7 | alpine alpine4k (armadaxp)
comcerto2k | comcerto2k
i686 | evansport
monaco | (monaco)
ppc | ppc853x qoriq
x86_64 | avoton (braswell) bromolow cedarview x86

Between parentheses `()` indicates unreleased/unconfirmed.

**Comment by piwi82** [comment]
New architectures added : `hi3535` (NVR216) and `armada38x` (DS216).
TC's for `northstarplus` (RT1900ac), `hi3535` and `armada38x` aren't yet available.

**Comment by Dr-Bean** [comment]
Northstarplus? You mean this one: http://sourceforge.net/projects/dsgpl/files/SRM%201.0%20Tool%20Chains/ ? ;)
We don't support it yet though, ref. https://github.com/SynoCommunity/spksrc/issues/1869.

**Comment by piwi82** [comment]
Oups, I missed this path (`/SRM 1.0 Tool Chains`) :wink:
