### ISSUE TITLE
Darkstat - feature request

### ISSUE THREAD

**Issue by samsar777** [SynoCommunity/spksrc#1875]
Hi,

I found Darkstat as an interesting tool. However it value would increase significantly if list of connections would list both source and destination IPs. As for now, I can see only one IP, so difficult to figure out which client within my network connect or was connecting to what IP.

Thank you.
M.

**Comment by cytec** [comment]
you should report/request this from the developer of darkstat: https://unix4lyfe.org/darkstat/
