### ISSUE TITLE
BTSync 2.2.5 for DS216play

### ISSUE THREAD

**Issue by synofriend** [SynoCommunity/spksrc#1882]
Hello,
I am new here in github and i hope that my question is at the right place here. I bought the new Synology DS216play. Is there any package to install BTSync on my new diskstation?

Thanks for your help!

**Comment by Dr-Bean** [comment]
The BTSync package is provided in Synology's own repository: https://www.synology.com/en-global/dsm/app_packages/bittorrentsync. If it's not there, enter a request with Synology or contact the BTSync developers.
