### ISSUE TITLE
Change certificate bundle location for Git

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1883]
The Git package uses on `/usr/syno/etc/cacert.pem` as it's certificate bundle, as per https://github.com/SynoCommunity/spksrc/blob/master/cross/git/src/gitconfig#L2. However, DSM6 doesn't seem to have this file in the same location anymore.

We can either use `/etc/ssl/certs/ca-certificates.crt`, which exists on DSM5.x as well, or stop relying on Synology altogether, and reuse the approach that was recently implemented for curl: https://github.com/SynoCommunity/spksrc/blob/master/cross/curl/Makefile#L30. 

Maybe the best direction is to split the perl script off in a separate cross package, so we can depend on it from other packages. The script itself is available here: https://github.com/bagder/curl/blob/master/lib/mk-ca-bundle.pl.

**Comment by abetancort** [comment]
In the mean time, while we wait for an updated package, if you need to use git you can do it by 
**Disabing Certificate Checking**; be aware that this is a security hazard as you ar forgoing the protections of SLL.

##### Which can be achieved by:     
- Either Inserting an **`export GIT_SSL_NO_VERIFY=1`** in the default's users and root **.profile**, or
- by issuing the following command at **`git config --global http.sslverify false`**.

**Comment by Dr-Bean** [comment]
Thanks, but no thanks...Disabling security is rarely the answer, and this is definitely not an exception.
Why wouldn't you simply update gitconfig with the correct location? Change the file manually, or issue a command like this:
```
/usr/local/git/bin/git config --system http.sslcainfo /etc/ssl/certs/ca-certificates.crt`
```

Note that you'll be waiting for a fix a while longer, because right now, it's too soon to be sure of any changes Synology makes.

**Comment by abetancort** [comment]
Let me state the obvious, **you are totally right**, but before I did not have a better answer, so I posted "*my sinful way*" of getting around the problem, with the hope that would elicit a more orthodox approach from someone. 

I know, and accep, that there won't be a compatible release until DSM 6 is well out of beta, but having so many other packages depend on this git distribution, I had to find a way to live thru the beta and learn something new in the mean time. 

Thanks @Dr-Bean

**Comment by Dr-Bean** [comment]
Done with dc5f8e3110d175bf11d14bd650666ecfb95a43ae
