### ISSUE TITLE
Update ZNC to 1.6 series

### ISSUE THREAD

**Issue by charlesjohnson** [SynoCommunity/spksrc#1884]
There have been major improvements to ZNC in the 1.6 series, released in July of 2015. Synocommunity currently ships 1.4, released in May of 2014.

I'd be happy to contribute if there's an appropriate repo to PR against.

**Comment by Dr-Bean** [comment]
Use the search ;) Take a look at #1733, and at the following comment in particular: https://github.com/SynoCommunity/spksrc/issues/1733#issuecomment-128625207

**Comment by charlesjohnson** [comment]
A search for `is:issue is:open znc` returns #1567 and #860, but not the closed #1733. Thanks.
