### ISSUE TITLE
[Request] Museek+ and DS214play

### ISSUE THREAD

**Issue by chmod0777** [SynoCommunity/spksrc#1885]
Heya =)

I check this best spk in my NAS but don't run =(

Can we check model DS214play??? and run it?? 

TY

**Comment by Dr-Bean** [comment]
Museek+ is unmaintained, and will probably be removed from the repository unless that changes.

**Comment by chmod0777** [comment]
bad notice =(

OK ty

**Comment by Dr-Bean** [comment]
The packages have been deactivated (as in: no longer visible when using Package Center, but will show up on synocommunity.com/packages).

**Comment by Dr-Bean** [comment]
Closing. The packages have been removed from the repo for now.

Unless something changes here: http://museek-plus.org/ or here: https://github.com/eLvErDe/museek-plus, it seems the project is dead and we're probably better off removing it from spksrc.
