### ISSUE TITLE
Pillow compil failed

### ISSUE THREAD

**Issue by CondormanFr** [SynoCommunity/spksrc#1886]
I'm finishing a new SPK to allow to run WeeWX on Synology.
The last issue is with image creation.
The python project use PILLOW to generate picture and I get an error because 

```"The _imagingft C module is not installed".```

In fact, Pillow need to have libfreetype. (as explain here : https://github.com/weewx/weewx/wiki/Troubleshooting-Pillow)

I didn't success in installing Pillow 2.9.0 or 3.0.0  with WHEELS because this version seems not compatible with 64 bit linux : I get this error : 
```
 ImportError: /volume1/@appstore/weewx/env/lib/python2.7/site-packages/PIL/_imaging.so: wrong ELF class: ELFCLASS32
```

So at the end, it seems that the only way to have a working version of Pillow must be to cross compil it.
Pillow is already in spksrc but the actual version doesn't compil : 

```
===>  Configuring for Pillow
===>  Compiling for Pillow
env: setup.py: No such file or directory
../../mk/spksrc.python-module.mk:28: recipe for target 'compile_python_module' failed
make[1]: *** [compile_python_module] Error 127
make[1]: Leaving directory '/spksrc/cross/pillow'
```
Is-it possible to solve this issue, then I will test to add libfreetype as depends and try to make running WeeWX...

Thanks

**Comment by Dr-Bean** [comment]
Pillow needs cross-compiling, yes. At the moment, it's compiled as a python module, and created as part of the python SPK (hence the `mk/spksrc.python-module.mk`, you can't compile it standalone).
You can do one of two things:
- Leave the Pillow package as-is, and just add freetype as a dependency. Compile a new version of the Python package, and during your package installation, create a virtualenv with `--system-site-packages`, which will make Pillow available in that virtualenv
- Convert the Pillow package into a wheel. Change the include to `mk/spksrc-wheel.mk`, and include the cross-package as BUILD_DEPENDS of your package. Note that you don't want to break the Python package, so make sure that still works.

**Comment by Dr-Bean** [comment]
Closing, I assume my explanation was clear enough.
