### ISSUE TITLE
redis is not launching on ds1815+

### ISSUE THREAD

**Issue by acognard** [SynoCommunity/spksrc#1887]
hi all, i installed redis on a ds1815+ , but it does not launch. tks in advance for any help. Sincerly. Arnaud

**Comment by Dr-Bean** [comment]
It does run, it's just that Package Center returns the wrong status. See https://github.com/SynoCommunity/spksrc/issues/1690. I don't believe I published the new version yet.

**Comment by Dr-Bean** [comment]
redis 3.0.5-5 has been published on the repository.
