### ISSUE TITLE
Synocomunity & DSM 6.0 Docker

### ISSUE THREAD

**Issue by rjulie95** [SynoCommunity/spksrc#1889]
Hello,

Y build a virtual machine with Docker and dsm 
When y try to add the synocommunity as a source y have this error message 

![2015-10-19_23-00-13](https://cloud.githubusercontent.com/assets/8410772/10615274/37d45a40-775f-11e5-9163-1ccd0e7c8533.png)

Y find this error in log fille

Oct 19 22:59:30 Transmission PkgSynoMan.cgi: pkgcurltool.cpp:444 http://packages.synocommunity.com/, Failed to request packages, httpResponseCode=422

And in log of Synocommunity y see this message

a.b.c.d - - [19/Oct/2015:22:42:40 +0200] "GET /?package_update_channel=stable&unique=synology_dockerx64_dockerdsm&build=7135&language=fre&major=6&arch=dockerx64&minor=0&timezone=Amsterdam HTTP/1.1" 422 215 "-" "synology_dockerx64_dockerdsm DSM6.0-7135 (package)"

Y think soo the new dockerx64, it's not recognized 

Thank
##

**Comment by Dr-Bean** [comment]
Please ask Synology if `dockerx64` is the official name of the arch or if that will change to something else. If so, I think we can add it to https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.common.mk#L41 (and some other places)

Note that we will not add it in until the new toolchains are released.

**Comment by rjulie95** [comment]
Y just sumited at synology

**Comment by rjulie95** [comment]
For information, control panel on Docker 

![2015-10-22_19-51-02](https://cloud.githubusercontent.com/assets/8410772/10673535/a9995020-78f6-11e5-8283-0d9366639331.png)

**Comment by rjulie95** [comment]
The answer to synology :  

May I know what package you tried to add? Is it our build-in package on Package Center?

If not, we do no recommend you to install any 3rd-party package since it might cause system to be abnormal.

But indeed, DS1815+ is a x64 platform and I think it can't be changed to other names.
