### ISSUE TITLE
NZBGet 15.0-16 won't update to latest version in DSM beta 6

### ISSUE THREAD

**Issue by RoketteS** [SynoCommunity/spksrc#1892]
Package NZBGet can be updated says:
1) a 1 icon on the main Package Center Icon
2) Information messages says it can be update

But in the Package Center there is no nzbget located at the update tab and openen the package in package center also does not show any update available.

Regards,
Steve

**Comment by Dr-Bean** [comment]
Please add which model you see this behavior on.

**Comment by RoketteS** [comment]
DS213j

**Comment by reyman** [comment]
Same problem with DS213+ here

**Comment by Dr-Bean** [comment]
Weird. The catalog provides the updated package, so it seems the behavior of Package Center changed (intentional or not)
Have you testing that the new package shows up after uninstalling the current package?

**Comment by reyman** [comment]
The package center "failed to connect" when i search to display the community package page. It's weird because the "1" option appear on desktop icon of update manager

**Comment by Dr-Bean** [comment]
Do you have multiple sources configured, apart from SynoCommunity? Remove them, and try again.

**Comment by RoketteS** [comment]
Ok I removed all extra repositories except SynoCommunity e.g. http://packages.synocommunity.com/ and restarted.
Bingo the package appeared at the Update tab!
Does this mean I have to renter exe very repository manually and test if it shows up again to determine which repository is the culprit?

**Comment by RoketteS** [comment]
My complete list of extra repositories:
http://packages.jdel.org/
http://repo.synozwave.com/
http://synopkgs-garble.rhcloud.com/
http://spk.synologyitalia.com
http://cytec.us/spk/
http://packages.mdevries.org
http://packages.page81.net/
http://packages.pcloadletter.co.uk/
http://spk.unzureichende.info/
http://synobox.fr.nf/synopackages/
http://synobox.fr.nf/synopackages/beta.php/
http://synology.acmenet.ru
http://synology.sysco.ch
http://www.cphub.net/index.php/getpackages.php/
http://www.brigittehelsen.be/plexconnect/
http://update.10trum.de/packageupdate/getpackages.php

**Comment by Dr-Bean** [comment]
>Does this mean I have to renter exe very repository manually and test if it shows up again to determine which repository is the culprit?

It's not something we can help with, so that's up to you. Do you actually _use_ all those repositories?

**Comment by RoketteS** [comment]
No not really synocommunity is the most important! so I will leave them all out, cause the first 4 did give me the same error packages not shown or invalid location. Thanks a lot!
