### ISSUE TITLE
[Request] FFMPEG for Intel Atom/Cedarview architecture

### ISSUE THREAD

**Issue by Popsikill** [SynoCommunity/spksrc#1898]
Just wanted to add my 2 cents - would love the FFMPEG package to be available on my Synology DS1813+, which has an Intel Atom / Cedarview architecture (x86) which isn't currently supported by the package.

**Comment by cytec** [comment]
there is an ffmpeg update pending which i was working on.
It can be found here: https://github.com/SynoCommunity/spksrc/pull/1662 and needs a little more cleanup and a final testing i belive.
 i thought 2.2 was available for all x86 arches already :/

**Comment by Dr-Bean** [comment]
@cytec Alternatively, you could compile an x64 version of the current ffmpeg version, and before publishing, remove the current avoton package (which prevents that atm). It would probably make more sense to get your PR merged though :)

**Comment by MattPark** [comment]
Yeah I got a newer ffmpeg working using debian-chroot, but I would love one that works natively so I don't have to chroot out to use ffprobe.  I think nzbget needs this as well to check and see if your media is "corrupt"

**Comment by GuillaumeSmaha** [comment]
I think it can be closed.
@Dr-Bean @cytec @KaraokeStu Now, ffmpeg compiles for cedarview. See file list on https://guillaume.smaha.net/syno/

**Comment by cytec** [comment]
basically yes, but still need to publish the latest ffmpeg anyway...

**Comment by cytec** [comment]
@GuillaumeSmaha @KaraokeStu @Diaoul @Dr-Bean ffmpeg is updated and pushed to the repo

**Comment by omegagx** [comment]
I have a DS416play (Intel Celeron N3060 x64) and the ffmpeg package isn't showing up on the list of packages for some reason. Any ideas?
