### ISSUE TITLE
OwnCloud update from 6 to 8

### ISSUE THREAD

**Issue by SebastianSa** [SynoCommunity/spksrc#1899]
Hi all,
as some others I have not updated OwnCloud to 7.x now when updating to 8 I need to go an intermediate step by installing 7.x. But I can't find any historic files of the Synology packages.

Is there a location where can I download the 7.x package for my DS212j - 88f6281 ?

Thanks
Sebastian

**Comment by Dr-Bean** [comment]
We don't keep historic versions around (they won't show up in Package Center regardless, it only shows the latest version). Seeing as we've had the question before, might as well provide this one as well.

Check this issue if you've already updated: https://github.com/SynoCommunity/spksrc/issues/1709#issuecomment-105633610. As I said in the same issue, no guarantees it'll work, so make sure you have backups of the database (and your files, but you should have those regardless).

Here's the link: https://www.dropbox.com/s/01llphfci3zc2n9/owncloud_88f6281-4.3_7.0.3-5.spk.
