### ISSUE TITLE
Update for NZBGet - v16.3

### ISSUE THREAD

**Issue by Panja0** [SynoCommunity/spksrc#1901]
hugbug just released v16.3 of NZBGet.
Fixed: certain downloads may fail due to a bug in the workaround implemented in v16.2

Hopefully you guys can get this release up and running for our beloved Synology's? :)
I'm having lots of problems due to that workaround in v16.2

Thanks for your hard work!

**Comment by Dr-Bean** [comment]
Done with https://github.com/SynoCommunity/spksrc/commit/01f4f94d7c6eaf967cafaa2b7aef92061c9a097b, packages will be published in a couple minutes.
Thanks for bringing it up ;)

**Comment by Panja0** [comment]
Awesome! Thanks for the fast release. :)
