### ISSUE TITLE
[REQUEST] uTorrent Server

### ISSUE THREAD

**Issue by akafester** [SynoCommunity/spksrc#1902]
Given that an application like Sonarr have limited support for downloaders, some alternatives would be nice to have access to.
And uTorrent is one of the most used and supported of them all.
Transmission is a bit wonky at times which usually ends in a reinstall. rTorrent isn't fully supported (yet?) so not a viable alternative.

**Comment by cytec** [comment]
there is a ruTorrent SPK already available the fact that it is in `BETA` status might be a bit confusing... Synocommunity handles `BETA` more like "its there, and it is running and all that stuff, but we don't have enough feedback to be 100% sure everything works as it should"

**Comment by akafester** [comment]
It's not ruTorrent i mean. It's µTorrent Server (http://www.utorrent.com/downloads/linux).

**Comment by cytec** [comment]
yeah i know what you requested, but as you mentioned there is already rTorrent and Transmission and afaik µTorrent Server isn't opensource...

**Comment by Diaoul** [comment]
I think there is work on Deluge currently too.

**Comment by akafester** [comment]
@cytec I realized that it was closed source an hour after i posted my answer. Sorry about that. The reason i wanted an alternative is that rTorrent is way to complicated to setup. I got it working, but again the support in Sonarr isn't great. Transmission is a wonky adventure at best. It crashes at random and most times it seems slow. I found a working Deluge spk yesterday (http://ssd.dlinkddns.com/pub/synology/deluge/) and trying it out. So far it seems great, easy setup and fast downloads so far. I don't know if it's stable yet given that it was yesterday i installed it.

The reason i requested this was first and foremost to give the community som alternatives. I, for one, can't see anything wrong with having options and alternatives.

**Comment by Diaoul** [comment]
I'm using transmission on my NAS without any issue. It can saturate my bandwidth (optical fiber, 400Mb). If you experience problems with it I suggest you open a separate issue.

**Comment by Dr-Bean** [comment]
Seeing as uTorrent isn't open-source, Transmission is as stable as it gets, and ruTorrent and Deluge are both available as beta packages (Deluge since a couple of minutes), I believe there's nothing left to do here.

As Diaoul suggested, please open a new issue specific to your Transmission problems, or try out the other packages. In the meantime, I'll close this issue.
