### ISSUE TITLE
[request] SPK for telldus-core (driver for Telldus Tellstick/DUO) on Synology DS

### ISSUE THREAD

**Issue by beckos** [SynoCommunity/spksrc#1903]
Hi! I have a Synology DS712+ and a Telldus Tellstick DUO 433MHz controller that i want to connect to the NAS, and use OpenHAB automation. I installed OpenHAB packages you provided to the syno community and I can run the demo interface. However, I fail in bootstraping the DS (ipkg not found error) and I cannot step forward and install telldus-core on the box. I wonder if you could do am SPK package for Tellstick DUO driver so that I can use it with OpenHAB. I must admit, I don’t know linux at all. I am just a simple user… I am thanking you in advance! BEST REGARDS!
##

**Comment by Diaoul** [comment]
[We don't provide an OpenHAB package](https://synocommunity.com/packages) and don't recommend using IPKG as software in there is outdated and unmaintained.
