### ISSUE TITLE
Nzbget 16.3-20 Won't Start

### ISSUE THREAD

**Issue by phybersplice** [SynoCommunity/spksrc#1904]
Hi;

I can't seem to get NZBGET 16.3-20 to start up.
Where would I be able to find logs as to why it's not starting?

**Comment by Dr-Bean** [comment]
See https://github.com/SynoCommunity/spksrc/issues/1824 and https://github.com/SynoCommunity/spksrc/issues/1608

**Comment by phybersplice** [comment]
I deleted the queue directory and reinstalled.  Worked fine after that.
