### ISSUE TITLE
support for DS216Play

### ISSUE THREAD

**Issue by mrecke01** [SynoCommunity/spksrc#1906]
Currently no synocommunity packages seem to support DS216play (Monaco).

Would be very happy to install couchpatato & Sonarr...

**Comment by cytec** [comment]
afaik synology didn't release a toolchain for Monaco atm... so you'll have to wait for them to release the toolchains

**Comment by piwi82** [comment]
See https://github.com/SynoCommunity/spksrc/issues/1876#issuecomment-147851471

The tool chains for DS216play will probably be available in a *DSM 6.0 Tool Chains* folder at http://sourceforge.net/projects/dsgpl/files/

**Comment by Dr-Bean** [comment]
Let's close this one, as it's indeed a duplicate of https://github.com/SynoCommunity/spksrc/issues/1876.
