### ISSUE TITLE
ruTorrent erasedata plugin not working

### ISSUE THREAD

**Issue by Ghosthree3** [SynoCommunity/spksrc#1907]
I have tried everything I can think of to fix this but nothing works. Torrents can download just fine, but trying to do a 'Delete->Delete All' gives FAIL errors in erasedata's errors.log file. I've even tried giving 777 permissions, still fails. Tried looking around for a solution but couldn't find anything, and probably won't since I'm willing to bet it's associated with this specific build on this specific OS.

**Comment by Ghosthree3** [comment]
Ok because I'm amazing - and spent over 16 hours on the problem - I figured it out and here's the solution.

php's open_basedir needs to include the directory of your torrents, open up /etc/php/conf.d/user-settings.ini and add :/volume1/downloads/Torrents to the line. Also add :/tmp because it will save you a lot of headaches later.

**Comment by Dr-Bean** [comment]
I would have suggested to open a PR with your improvements, but as far as I know, https://github.com/SynoCommunity/spksrc/blob/master/spk/rutorrent/src/installer.sh#L74 should already handle any open-basedir related stuff.
