### ISSUE TITLE
Please clean and re-make Alpine toolchain

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1915]
@SynoCommunity/developers and other package builders.
Fyi, I've switched over to the 'other' Alpine toolchain with https://github.com/SynoCommunity/spksrc/commit/207786329617784340ecdea7b93ed69b9324f880. The current toolchain can't handle compiling boost.

Please run a `cd /spksrc/toolchain/syno-alpine-5.2 && make clean && make`.

**Comment by cytec** [comment]
nice maybe this fixes https://github.com/SynoCommunity/spksrc/issues/974 as well?

**Comment by Dr-Bean** [comment]
Could be. The toolchain swap was specifically to fix a compile issue with Alpine.. I set up #1911 to fix Boost in general, which I'll probably merge later today.

If you have the code you prepared for #974 archived somewhere, you can probably test it quicker than I can set it up ;) You did refer to C++11: I can't tell if that's a hard requirement, but if so, it's still an issue with the majority of toolchains.

**Comment by cytec** [comment]
yup C++11 is needed for mkvtools 5+ but maybe older versions still work... i have to check if i have those files floating around somewhere

**Comment by Dr-Bean** [comment]
Last call for updating your Alpine toolchain ;)
