### ISSUE TITLE
Installed CouchPotato, getting pkgstartstop.cpp:196 Failed to start package

### ISSUE THREAD

**Issue by kunjanbarot** [SynoCommunity/spksrc#1918]
Hi guys,

I (re)installed CouchPotato from the package source but everytime I click on Run on the package I get a Failed to run package service error.

Checking var/log/messages displays the following "generic" error log:

Nov  8 01:12:09 entry.cgi_SYNO.Core.Package.Control[1].start[18395]: pkgstartstop.cpp:187 Failed to start package couchpotatoserver, [127], No such file or directory
Nov  8 01:12:09 entry.cgi_SYNO.Core.Package.Control[1].start[18395]: pkgstartstop.cpp:196 Failed to start package couchpotatoserver, [127]

Can anyone please help?

**Comment by Dr-Bean** [comment]
Provide DSM version and model please. If you're on DSM6, it's a beta and you can expect problems with it.

**Comment by kunjanbarot** [comment]
Hi Dr-Bean,

I looked at the scripts that get run and realised that I needed to reinstall Python as it didn't exist in the directory mentioned in the script.
