### ISSUE TITLE
Update syncthing to v0.12

### ISSUE THREAD

**Issue by MakeMeASandwich** [SynoCommunity/spksrc#1920]
[Syncthing v0.12 is out](https://forum.syncthing.net/t/syncthing-v0-12-0-beryllium-bedbug/6026) and incompatible to previous versions (only v0.11 is available in the repository).

**Comment by Dr-Bean** [comment]
Syncthing has a built-in upgrade function. It'll ask you to upgrade, unless you have `automatic upgrades` turned off in settings.

**Comment by MakeMeASandwich** [comment]
> Syncthing has a built-in upgrade function. It'll ask you to upgrade, unless you have automatic upgrades turned off in settings.

I might be wrong, but v0.11 to v0.12 is not automatically upgraded. At least I need to press the "upgrade" button.
Do as you think is best :+1:

**Comment by Dr-Bean** [comment]
I didn't say that Syncthing would auto-upgrade automatically ;) Difference in terminology perhaps, but that's what Syncthing calls the function. It would be a bad thing if Syncthing did upgrade without asking.

**Comment by dundeemt** [comment]
Will there be an announcement here, else where when the synology app is updated to .12?  Or should I install .11 on my nas, even though it won't connect to my 0.12 clients but I should get an email from the nas when an update is available?

**Comment by Dr-Bean** [comment]
Not sure I understand your concern here. Install the Syncthing package. When Syncthing asks you to upgrade to 0.12.x, go right ahead.

If you want to wait for the package upgrade, that's up to you. You end up with the exact same thing in terms of functionality, the main difference is that the version shown in Package Center will change from the current version to 0.12.x-y, or we switch over to a date instead of a fixed version. (and we'll probably move the package out of beta).

**Comment by dundeemt** [comment]
Thanks, once I installed 0.11 it became obvious.

When I did upgrade to 0.12.2, syncthing complained about Global Discovery
and udp://syncthing.... not being available.  So I changed the Global
Discovery setting to "default" just like my other installs and it seems
happy.



On Tue, Nov 10, 2015 at 1:25 AM, Dr-Bean <notifications@github.com> wrote:

> Not sure I understand your concern here. Install the Syncthing package.
> When Syncthing asks you to upgrade to 0.12.x, go right ahead.
>
> If you want to wait for the package upgrade, that's up to you. You end up
> with the exact same thing in terms of functionality, the main difference is
> that the version shown in Package Center will change from the current
> version to 0.12.x-y, or we switch over to a date instead of a fixed
> version. (and we'll probably move the package out of beta).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SynoCommunity/spksrc/issues/1920#issuecomment-155343027>
> .
>



-- 
Best,

Jeff Hinrichs
dundeemt@gmail.com
402.218.1473

**Comment by z-vap** [comment]
I pressed the button but it does not upgrade it keeps defaulting back to the main page.

**Comment by z-vap** [comment]
ok nevermind. It was related to Mozilla Firefox for some reason.  When i did this with Chrome it upgraded

**Comment by Dr-Bean** [comment]
Done with 64fcd1af67765bb051bbeee9e747a35b6e93156f
