### ISSUE TITLE
transmission is not available for armada 375？

### ISSUE THREAD

**Issue by NewG7** [SynoCommunity/spksrc#1923]
![20151109234112](https://cloud.githubusercontent.com/assets/15732221/11037919/5c785734-873b-11e5-820c-23a12d8f244e.png)

**Comment by Dr-Bean** [comment]
Provide DSM version please. If you're still on DSM4, we probably won't have uploaded it.

**Comment by NewG7** [comment]
![20151110092418](https://cloud.githubusercontent.com/assets/15732221/11051769/d6d35604-878c-11e5-8b31-25b0aa589fbc.png)
:)

**Comment by Dr-Bean** [comment]
DSM5.2 then. No reason it shouldn't show up, except if the problem is at your end.

Refresh Package Center, check again. If that doesn't work, remove all 3rd-party repositories, and add just SynoCommunity's. Follow the instructions here: https://synocommunity.com/#easy-install.

**Comment by NewG7** [comment]
sorry,Dr-Bean.i mean that i clicked the install button but no response. and other synocommunity Packages was installed correctly and immediately.

**Comment by Dr-Bean** [comment]
The issue is localized to you, because there's nothing wrong with the repository. It might be related to connectivity in several different ways, which is why I suggested what I suggested.
Otherwise, log in via SSH, and check `/var/log/messages` and `/var/log/synopkg.log`

**Comment by NewG7** [comment]
I checked the dns, disk, permissions, and upgrade to 6.0. it still does not respond, can u give me a pkg file to installed locally,thanks
there's nothing in log file about transmission

**Comment by NewG7** [comment]
I re-installed my DSM system, and reset the configuration, or can not be installed

**Comment by Dr-Bean** [comment]
I'm not sure how to read your last comment (mainly the 'or can not be installed' part). Fyi, DSM6 is currently not supported, but it's not clear which version you have installed right now. 

If PC doesn't respond and synopkg.log doesn't show anything either, then I'd suggest to check with a different browser as well.

**Comment by NewG7** [comment]
Sorry of my poor english. i mean that 'still can not be installed' in dsm 5.2. 
chrome and ie was attempted.

**Comment by Dr-Bean** [comment]
Does this issue still exist? Yesterday, a new version of the Transmission package was released, so you might want to check again if that's the case.
