### ISSUE TITLE
Proposal: Retire Sickbeard package

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1925]
Sickbeard hasn't seen active development for quite a while now (last commit in develop: april 2015, and last commit in master: november 2014), and the [issue tracker](https://code.google.com/p/sickbeard/issues/list) is set to read-only due to Google Code slowly shutting down.

With successors such as SickGear, SickRage and probably a whole bunch of other forks, it may be best to stop publishing the main SB package, and in time remove the code from spksrc if nothing changes.

Ftr, merging the `-custom` code back into the main package seems to be more trouble then it's worth at this point. The `-custom` package will continue to be available, and the default fork is still set to the original repo for people who wish to continue using the original SB code.

Thoughts/objections?

**Comment by Diaoul** [comment]
I'm OK with that.

**Comment by cytec** [comment]
fine with that too

**Comment by Dr-Bean** [comment]
Deactivated the package. We can decide at a later point when it's ok to remove the code from spksrc.
