### ISSUE TITLE
REQUEST: New Backup Package Request

### ISSUE THREAD

**Issue by ecomatt** [SynoCommunity/spksrc#1927]
Hi im not sure if this is the correct place to put a request out?
But I'm really disappointed in Sinology for not adding google drive to the backup app.

Would anyone be able or interested in building a backup app to backs up to google drive.
The CloudSync is not good as i have multiple top level share folders that i wants to encrypt and backup to the cloud, I do not want the files to necessarily be browsable on google ether.

This would be for incremental backup and not a sync.
Can anyone help me out with this?

Thanks

**Comment by piwi82** [comment]
SynoCommunity packages existing open source software only, we do not develop specific software.
Have you asked Synology ? Maybe it is planned for DSM 6 final.

**Comment by ecomatt** [comment]
thanks for your reply 
are there any open source backup scripts software that can backup to google drive?
I have asked synology many times about this as they support google drive in sync but not in backup. but i get nowhere. i am testing DSM6 and it has not been added yet.
Any thoughts about a way around this?

**Comment by Diaoul** [comment]
> are there any open source backup scripts software that can backup to google drive?

That's the question @piwi82, search something that fits your requirements first then we will see if we can package it.

**Comment by ecomatt** [comment]
ok i will continue to search - i suppose i was hoping that someone in the community might already know of something out there...

**Comment by ecomatt** [comment]
the only one i have come across before was duplicati.com

**Comment by Diaoul** [comment]
I just googled `rsync google drive` and found https://github.com/iwonbigbro/gsync

**Comment by Diaoul** [comment]
And this:

* http://shobute.com/posts/backup-to-google-drive-with-duplicity
* https://blog.notmyhostna.me/duplicity-with-pydrive-backend-for-google-drive/
* http://askubuntu.com/questions/436503/deja-dup-google-drive-support

**Comment by Diaoul** [comment]
See #1810

**Comment by Dr-Bean** [comment]
So...is there anything concrete we can do here?

**Comment by Dr-Bean** [comment]
Guess not ;)
