### ISSUE TITLE
REQUEST: NZBGET update to 16.3-20 for DSM 4.2xxxxxx with 88f628x architecture

### ISSUE THREAD

**Issue by janbal** [SynoCommunity/spksrc#1928]
My DS is a DS109 with architecture 88f628x and latest possible DSM 4.2xxxxx

I use NZBGet version 15.0-16 from the SynoCommunity.

The newest version of NZBGet version however is 16.3-20.

I would be very obliged if the Synocommunity could make this newest version available for my DSM and architecure.
Thank you in advance.

**Comment by cxhamilton** [comment]
Your architecture (88f628x) is supported according to https://synocommunity.com/package/nzbget

**Comment by Dr-Bean** [comment]
Done, take a look ;)

**Comment by janbal** [comment]
Works! Thx a lot
