### ISSUE TITLE
Improve directory permissions handling

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1932]
Over time, we've seen quite the number of issues related to setting permissions. In the majority of cases, it's because people intend to use a subdir of a share as a main location, and the installer does not handle permissions for the intermediate dirs. We don't inform users that this means they need to set permissions manually which doesn't help the situation.

To illustrate: 
- `/volume1/chosen_dir` is handled correctly;
- `/volume1/intermediate/chosen_dir` is not handled, because traverse permissions are required -but not set- for the intermediate dir(s).

The following function can be called from `postinst` with a dir as argument. It sets r/w permissions on the chosen dir itself, and sets traverse permissions for all intermediate dirs.

This also removes the need to set Unix permissions  for the `users` group (as in: chmod/chown which we do in a number of installers), which is something we should start considering imo.
Along with that, with minor changes, the function can be switched to set permissions for an application user instead of a group (if Synology still plans to implement it, I don't think it's in the current beta)

```
syno_set_permissions ()
{
    dirname=$1
    SYNO_VOLUME=`echo $1 | awk -F/ '{print "/"$2}'`
    # Set read/write permissions for SYNO_GROUP
    synoacltool -add "${dirname}" "group:${SYNO_GROUP}:allow:rwxpdDaARWc--:fd--"
    while test "${dirname}" != "${SYNO_VOLUME}"; do
        # Walk up the tree and set traverse permissions up to SYNO_VOLUME
        dirname="$(dirname "${dirname}")"
        if [ ! "`synoacltool -get \"${dirname}\"|grep \"group:${SYNO_GROUP}:allow:..x\"`" ]; then
            synoacltool -add "${dirname}" "group:${SYNO_GROUP}:allow:--x----------:---n"
        fi
    done
}
```

In practice, postinstall () would look like this for a download-type package:

```
    # Create user
    adduser
    # Create SYNO_GROUP
    syno_group_create

    if [ "${SYNOPKG_PKG_STATUS}" == "INSTALL" ]; then
        # Set group and permissions on dir
        if [ `/bin/get_key_value /etc.defaults/VERSION buildnumber` -ge "4418" ]; then
            syno_set_permissions "${wizard_download_dir}"
        fi
    fi
```

/edit: added some quotes here and there to fix potential issues with spaces in dirs and groupnames.
##

**Comment by Diaoul** [comment]
I was just thinking we can create a "library" of shell functions that we include in installer.sh and is maintained in a single place within spksrc so that every package can make use of it. This would be the perfect place for this kind of function as well as handling different DSM versions.

**Comment by Dr-Bean** [comment]
Sure, makes sense. Auto-include a `common.sh` if `INSTALLER_SCRIPT = src/installer.sh` is defined during SPK building or something like that. Where do we put it, in a new dir?

How about we set up/move these, with examples from the Deluge installer:
check_dir_existence() [content](https://github.com/SynoCommunity/spksrc/blob/master/spk/deluge/src/installer.sh#L50-L53)
syno_group_create() [content](https://github.com/SynoCommunity/spksrc/blob/master/spk/deluge/src/installer.sh#L24-L33)
syno_group_remove() [content](https://github.com/SynoCommunity/spksrc/blob/master/spk/deluge/src/installer.sh#L35-L45)
syno_set_permissions() see above
legacy_set_permissions() (probably [content](https://github.com/SynoCommunity/spksrc/blob/master/spk/deluge/src/installer.sh#L104-L105)
backup_stuff() [content](https://github.com/SynoCommunity/spksrc/blob/master/spk/deluge/src/installer.sh#L162-L165)
restore_stuff() [example](https://github.com/SynoCommunity/spksrc/blob/master/spk/deluge/src/installer.sh#L172-L175)

Not sure about the following two yet:
add/remove user
add/remove firewall config (probably moving the command to a pre-existing if-statement for package install/uninstall would help to clean things up visually)

**Comment by GoodOmens83** [comment]
Does this work in DSM6?

Running something like `synoacltool -get /somepath` produces `(synoacltool.c, 359)It's Linux mode`

Or am I doing it wrong?

**Comment by Dr-Bean** [comment]
Yeah...it looks like synoacltool on DSM6 can't read ACL's on shared folders created with DSM5. Try creating a new shared folder on DSM6, and use the same command; it should yield a result then.

Not sure whether it's a bug or intentional (for whatever reason), but either way, we should report it to Synology and see what they have to say about it.

**Comment by GoodOmens83** [comment]
Ah yes you are correct.  I sent a note to Synology asking if there is any way to "upgrade" a folder so that command works.   You can add new ACL's to existing created DSM5 folders though and it will read them back.  Haven't done too much testing though to see if the newly added ones work.

**Comment by Dr-Bean** [comment]
PR at #2345.

**Comment by Safihre** [comment]
We now have Generic Service to handle it all 👍
