### ISSUE TITLE
Sonarr with DSM 6.0 beta

### ISSUE THREAD

**Issue by Eselohr** [SynoCommunity/spksrc#1933]
Hi there,

Sonarr has stopped working under DSM 6.0 beta. Is there any development in fixing this issue? 

Thanks! 
##

**Comment by Dr-Bean** [comment]
DSM6 is currently not supported. In the future, when DSM6 is more mature, yes, we'll look into it. Until then, problems like this can be expected unfortunately.

**Comment by tjbrid43** [comment]
DSM 6.0 has been release and my was updated this morning.

However - sonarr package will not run. Please help!

Thanks

**Comment by atmfrenki** [comment]
Same problem here..... also had no backup of the settings used.... can i get those out of a config file through root access? (figured that out ;-)

**Comment by fizzy31** [comment]
Hello

same problem
DSM 6.0-7321
DS414
Last version of Mono available on SynoCommunity

thanks

**Comment by atmfrenki** [comment]
Problem Solved!!!
Mono is the problem.
I solved it to, based on this topic:

https://forums.sonarr.tv/t/update-dsm-6-0-sonarr-wont-run/10159/9

**Comment by vvhof** [comment]
https://github.com/SynoCommunity/spksrc/issues/2207#issuecomment-200958470

**Comment by mydevpeeps** [comment]
assuming this is outdated and marked as fixed? why is it still open?

**Comment by cytec** [comment]
because sonarr is still not working with DSM 6... see https://github.com/SynoCommunity/spksrc/issues/2216

**Comment by Safihre** [comment]
DSM6 compatible version of the package is expected to be released soon. It can already be installed by downloading it from here #3138.
After the official release on SynoCommunity, the package will auto-update from the official release.
