### ISSUE TITLE
Step to extracting Qoriq toolchain txz file resulted in a error

### ISSUE THREAD

**Issue by GoodOmens83** [SynoCommunity/spksrc#1934]
Was trying to cross-compile rutorrent on Debian using make arch-qoriq and received an error that the txz  (qoriq-gcc4374_eglibc2874_qoriq-GPL.txz) file did not appear to be a correct tar file.

Corrected by updating the makefile (spksrc.extract.mk) from "EXTRACT_CMD.txz = tar -xpf $(DIST_FILE) -C $(EXTRACT_PATH)" to "EXTRACT_CMD.txz = tar -Jxpf $(DIST_FILE) -C $(EXTRACT_PATH)"

Not sure if its specific to my environment or what.

**Comment by Dr-Bean** [comment]
Which version of Debian, and which version of tar are you using? It seems to me that the version of `tar` you're using is too old to understand the `txz` extension, but that shouldn't be a problem with an up-to-date Debian distro.

**Comment by GoodOmens83** [comment]
I was on Debian 6 and unfortunately wiped and upgraded to 8 so I can't check the specific tar version.

I had run apt-get update/upgrade before running so in theory I should have been on a newer version of tar.

**Comment by Dr-Bean** [comment]
In theory, probably, but there's no way to check. I assume that everything works as expected now?

**Comment by GoodOmens83** [comment]
Yup.  I'll close this out as it's working as in from GIT on Debian 8.
