### ISSUE TITLE
Can't install deluge

### ISSUE THREAD

**Issue by FlyGuy94** [SynoCommunity/spksrc#1936]
When I try to install deluge it tells me it can't install because the download directory doesn't exist?
The directories are there and they have been used in the past with transmission no problem.

**Comment by flipside101** [comment]
HI Just came here to log the same problem , ive checked and rechecked permissions and all looks fine and the deluge version i had running in docker can access them with no issue

**Comment by Dr-Bean** [comment]
Provide the exact error message you're getting please. Which fields did you fill in during the wizard, all three, or just the top one?

**Comment by FlyGuy94** [comment]
The error message reads "Complete directory /volume1/Downloads/Downloads does not exist."
Note how the v in volume1 is not a capital. Isn't linux captital strikt. If I try to change it to a capital the box turns red and I can't continue.

**Comment by Dr-Bean** [comment]
Don't fill in the last field (leave blank), there's indeed a typo in the associated code there.
You can change the complete dir in the Deluge interface, after installation completes. It's auto-set to the download dir (so the same value as the first field), but you can activate the checkbox and correct that.

**Comment by FlyGuy94** [comment]
It thinks about it. then It wants to start it. then I get this (screenshot) after I log out and back in it works. But yeah beta.
![knipsel](https://cloud.githubusercontent.com/assets/11855105/11168267/b5fdcece-8b87-11e5-8a8c-e792bf305237.PNG)

**Comment by Dr-Bean** [comment]
...that pops up all by itself on DSM6 beta? How nice :/

But to confirm: You've been able to install Deluge, and it works? Note that permissions are not properly handled by the installer at this point (read #1932), so if need be, you can set permissions on the correct directories using the `sc-download` group via FileStation.

**Comment by FlyGuy94** [comment]
I'm on xpenology 5.2 not 6.0 Deluge works I just downloaded something and no permission errors. I handle permissions manually anyway.

**Comment by flipside101** [comment]
HI I'm on DSM 5.2 on a 412+ and have the same issue. The fix of not putting in the last path works but i to get the pop up of the entire config file at the end . i logged out and back in and had to start the package

**Comment by Dr-Bean** [comment]
Yeah, that'll be fixed with an update. The build process for deluge is very verbose, and for some reason, it wants to show it all to you ;)

**Comment by flipside101** [comment]
😀 thank you for the work on this

**Comment by Dr-Bean** [comment]
Done with 692088c32ab2e39aa0fccbdd8836528b4c97094d

**Comment by Dr-Bean** [comment]
Deluge 1.3.12-4 has been published.
