### ISSUE TITLE
BicBucStriim / COPS - problème d'accès au fichier metadata.db

### ISSUE THREAD

**Issue by Zorineau** [SynoCommunity/spksrc#1937]
Après avoir lutté pour faire refonctionner COPS et BBS sur mon NAS et suite au topic sur le NAS-Forum
Je récapitule ici mes actions.

**Pour préparation du NAS**
- Desinstallation COPS/BBS
- Copie du fichier metadata.db et d'un dossier livre dans un nouveau répertoire sans liens (non conservation des droits initiaux pour propriété)
- Desactivation des composants php (intl, mycript, mssql) que j'avais activé manuellement dans mes essais
- Reset PHP open_basedir
- Création de 2 share pour les test (droit non modifiés (groupe admin seulement)
  - /volume1/test1/metadata.db
  - /volume1/test2/calibre/metadata.db

**installation BBS**
- installation du package : OK
- connexion url bbs : OK
- accès aux dossiers : 
  - test1 : KO le Dossier existe mais ne peut être lu
  - test2/calibre : KO le Dossier existe mais ne peut être lu
- ajout du groupe **http** en lecture sur le share **test1** : ça fonctionne !
- ajout du groupe **http** en lecture sur le dossier **calibre** : KO
  - ajout du groupe **http** en lecture sur le share **test2** : ça fonctionne !

_A ce stade je suis dèg d'y avoir passer des heures en cherchant a gauche a droite un console avec putty et j'en passe ... donc je vire tout ça et je recommence avec COPS juste pour rire ... haha rire jaune)_

**installation COPS 1**
- installation en spécifiant le chemin test1 : KO
  - Edit Share properties, tous les droits ont été reinitialisé et remplacé par un **user http**
  - Je remplace tout par lecture pour le **groupe http** : ça fonctionne !

_On pète tout et on recommence pour le 2 eme lien_

**installation COPS 2**
- installation en spécifiant le chemin test2 : KO
  - Edit Folder **calibre** properties, tous les droits ont été reinitialisé et remplacé par un **user http**
  - Je remplace tout par lecture pour le **groupe http** : KO
  - Ajout en _traverser du dossier_ du groupe **http** sur le share **test2** : ça fonctionne !

**Conclusions**
BBS & COPS requiert que le **GROUPE HTTP** puisse parcourir l'arborescence jusqu'au dossier calibre et avoir un accès en lecture a ce dernier

Le package COPS reinitialise complètement les droits du dossier ciblé dans l'installation par un accès en lecture pour le **user HTTP** qui n'existe pas et n'apporte pas la fonctionnalité attendue.
de plus si il s'agit d'un sous dossier il ne permet pas la traversé des dossiers parents a ce mauvais compte.

les modules php ne sont pas requis in fine, pas plus que la modification du open_basedir dans les paramètres php.
##

**Comment by Dr-Bean** [comment]
Cops 1.0.1-5 has been published on the repository as a beta package.
