### ISSUE TITLE
Python didn't compil : issue with uwsgi

### ISSUE THREAD

**Issue by CondormanFr** [SynoCommunity/spksrc#1939]
Python SPK compil failed : 

I ran the /spksrc/native/python make command and I get no error.

When I launch the make command in the spk\python folder, i get this error : 

```
[thread 1][/spksrc/toolchains/syno-avotonIn file included from /usr/include/python2.7/Python.h:8:0,
                   from plugins/python/uwsgi_python.h:2,
                   from plugins/python/python_plugin.c:1:
  /usr/include/python2.7/pyconfig.h:3:51: fatal error: x86_64-linux-gnu/python2.7/pyconfig.h: No such file or directory
  compilation terminated.
  In file included from /usr/include/python2.7/Python.h:8:0,
                   from plugins/python/uwsgi_python.h:2,
                   from plugins/python/pyloader.c:1:
  /usr/include/python2.7/pyconfig.h:3:51: fatal error: x86_64-linux-gnu/python2.7/pyconfig.h: No such file or directory
  compilation terminated.
  In file included from /usr/include/python2.7/Python.h:8:0,
                   from plugins/python/uwsgi_python.h:2,
                   from plugins/python/pyutils.c:1:
  /usr/include/python2.7/pyconfig.h:3:51: fatal error: x86_64-linux-gnu/python2.7/pyconfig.h: No such file or directory
  compilation terminated.

  ----------------------------------------
  Failed building wheel for uwsgi
Failed to build uwsgi
ERROR: Failed to build one or more wheels
../../mk/spksrc.wheel.mk:36: recipe for target 'wheel_target' failed
make[1]: *** [wheel_target] Error 1
make[1]: Leaving directory '/spksrc/spk/python'
```

**Comment by Diaoul** [comment]
If a previous build errored, try again after `make clean`

**Comment by CondormanFr** [comment]
I do the build for the second time with make clean and I get the same error...

**Comment by Dr-Bean** [comment]
UWSGI was updated on PyPI, and since we don't pin the version in WHEEL, we have a mismatch.
Either update the UWSGI cross package to latest, or pin the current version in Python's Makefile 
(`WHEEL = "uswgi==<whatever version>"`)

I already knew about it, but planned to hold off with updating modules until Python 2.7.11, after 5 dec...there's usually very low demand to build the Python SPK.

**Comment by CondormanFr** [comment]
OK, i updated the cross package to latest and it works. Thanks.

**Comment by Dr-Bean** [comment]
Fixed with https://github.com/SynoCommunity/spksrc/commit/f075dd682fc4a287584cd6e9fd720335adb192ac.

Unfortunately, I couldn't use your PR (see the comment there for the reason), but I needed to update uwsgi to be able to create the Python package for Monaco :)
