### ISSUE TITLE
Deluge Deamon

### ISSUE THREAD

**Issue by Bon3** [SynoCommunity/spksrc#1940]
Hi,

Just installed Deluge beta from the repo,

trying to connect to the deamon from my mac. but it doesnt want to connect upon checking logs:

BadLoginError: username does not exist

but the normal Deluge login for the deamon is always admin/admin??

**Comment by baz1860** [comment]
Nzbget has its defaults changed to nzbget/nzbget; I don't personally use
deluge, but perhaps deluge/deluge might work?

**Comment by Bon3** [comment]
Tried that also :( no luck at all

**Comment by Diaoul** [comment]
https://github.com/SynoCommunity/spksrc/pull/1911#issuecomment-154026024

**Comment by Bon3** [comment]
Diaoul im not referring to the webui password,

im refering to downloading the Deluge client and using it as thinclient. Connect through the Deluge MacOS application directly to the deamon in that case you also need user, which by default is admin/admin

**Comment by Dr-Bean** [comment]
Check the [documentation](http://dev.deluge-torrent.org/wiki/UserGuide/Authentication). 
By default, only connections from localhost are allowed, so you'll need to allow remote connections as well.

**Comment by Bon3** [comment]
Did that also... Still its giving me an hassle regarding credentials.. :) 

In the documentation it states:
Username and Password are those added to the deluged config auth file.

Could you check to see what the default is?

**Comment by Dr-Bean** [comment]
There is no default user, except the localhost web client. You need to add a user yourself, as per the linked documentation, allow remote connections, and restart Deluge/the package.

**Comment by Bon3** [comment]
ahh ok... now i understand sorry for the confusion on my part..

**Comment by Dr-Bean** [comment]
This seems to be solved, right? Then lets close it.
