### ISSUE TITLE
Debian Chroot 8.1-6 on DSM 5.2 

### ISSUE THREAD

**Issue by Cartman25** [SynoCommunity/spksrc#1943]
After DSM 5.2-5644 Update 1

I can't use my chroot, i have this error :

realpath: /usr/local/debian-chroot/var/chroottarget: No such file or directory
chroot: can't execute '/bin/bash': No such file or directory

I check on package center, the package is in stopped state.
I try to launch it but if fails.

I resintall Debian Chroot, reconfigure it but after reboot same problem.

Can anyone help ?

**Comment by Dr-Bean** [comment]
Have you followed the instructions in the wiki: https://github.com/SynoCommunity/spksrc/wiki/Debian-Chroot?

**Comment by Cartman25** [comment]
Hello, thanks for your answer.

Yes i forgot to mention that the setup and first use is OK. I did everything and even setup Squid3 for my proxy under chroot.

But after the reboot of DSM, the chroot is broken.

Any idea ?

**Comment by Cartman25** [comment]
I reinstall again, log for apt get update and upgrade 

Some failed command :

Setting up udev (215-17+deb8u2) ...
**Failed to read /proc/cmdline. Ignoring: No such file or directory**
**A chroot environment has been detected, udev not started.**
**A chroot environment has been detected, udev not started.**
(Reading database ... 9728 files and directories currently installed.)
Preparing to unpack .../libsystemd0_215-17+deb8u2_i386.deb ...
Unpacking libsystemd0:i386 (215-17+deb8u2) over (215-17+deb8u1) ...
Setting up libsystemd0:i386 (215-17+deb8u2) ...
Processing triggers for libc-bin (2.19-18+deb8u1) ...
(Reading database ... 9728 files and directories currently installed.)
Preparing to unpack .../systemd_215-17+deb8u2_i386.deb ...
Unpacking systemd (215-17+deb8u2) over (215-17+deb8u1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up systemd (215-17+deb8u2) ...
Installing new version of config file /etc/systemd/resolved.conf ...
Failed to read /proc/cmdline. Ignoring: No such file or directory
Failed to read /proc/cmdline. Ignoring: No such file or directory
Failed to set capabilities on file `/usr/bin/systemd-detect-virt' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
Failed to read /proc/cmdline. Ignoring: No such file or directory
Failed to read /proc/cmdline. Ignoring: No such file or directory
(Reading database ... 9728 files and directories currently installed.)
Preparing to unpack .../systemd-sysv_215-17+deb8u2_i386.deb ...
Unpacking systemd-sysv (215-17+deb8u2) over (215-17+deb8u1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up systemd-sysv (215-17+deb8u2) ...
(Reading database ... 9728 files and directories currently installed.)
Preparing to unpack .../cron_3.0pl1-127+deb8u1_i386.deb ...
Failed to read /proc/cmdline. Ignoring: No such file or directory

**Comment by Cartman25** [comment]
Well i setup again but under /volume1 and it works. Whats the problem under /volume2 ?

**Comment by Dr-Bean** [comment]
No idea. We don't particularly test packages with other volumes, and you're the first to report this. I do know that there are differences in permissions between volumes, so maybe there's a relation there.
If you find out, let us know :)

**Comment by Cartman25** [comment]
Well i found the problem i guess.
Before DSM update i used to put some automatic services at startup under Synology domain in:

/usr/syno/etc/rc.d/Zsomething.sh

mount -o bind /proc /volume2/@appstore/debian-chroot
chroot /volume2/@appstore/debian-chroot /etc/init.d/squid3 start

I think i must change the way i automate the startup on DSM boot.

Any idea ?

**Comment by Dr-Bean** [comment]
I don't immediately see a reason why you can't use the Debian-chroot interface that's provided with the 
package?

Using `/usr/syno/etc/rc.d` is not a good place on a Synology anyway, because it won't survive a DSM update.

**Comment by Cartman25** [comment]
I know it's strange ..

But at the moment i removed the script in /usr/syno/etc/rc.d/, the package starts without problem Oo !

So i setup again the package under /volume2, then i used the package interface to add new services at startup (service squid3 start)

Then it's OK right now at reboot of the NAS !

Thanks for following my issue.
