### ISSUE TITLE
Support for DS716+ / Braswell

### ISSUE THREAD

**Issue by ghostdogid** [SynoCommunity/spksrc#1944]
Hey,

will there be a Support for the new DS716+

THX.

**Comment by piwi82** [comment]
There will be, as soon as Synology will release the tool chains for the new architecture <code>braswell</code> (http://sourceforge.net/projects/dsgpl/files/).

**Comment by ghostdogid** [comment]
Thank you!

**Comment by Diaoul** [comment]
Let's leave this one open so it appears when users do a minimal search.

**Comment by Haocen** [comment]
Hi, since some binary executables are universal(I have my homebrew Aria2 running happily), is there a way to edit existing packages, for example transmission, manually, to allow installation on braswell products?

**Comment by Dr-Bean** [comment]
Provided you start off with the correct arch, it might work. It depends on the differences between the Braswell toolchain and kernel sources and those of the other x86/64 arches. We'll decide on how to implement it when it's released.

Note that we won't support your handcrafted packages, so the risks are yours. If your next question is: "Which risks?", then I suggest you wait...

**Comment by next2non** [comment]
The tool chain is up now, hope it won't be long before it's working on DS 716+

**Comment by Dr-Bean** [comment]
Still missing GPL source.

**Comment by piwi82** [comment]
Did you mean this : http://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/5644branch/ ?

**Comment by Diaoul** [comment]
We need a quicker hash check for toolchains so when we update them it triggers update for everyone. New DSM release is usally when Synology makes changes to toochains without notice or release.

**Comment by Dr-Bean** [comment]
It wasn't there when I added that comment, I'm sure of it ;)

**Comment by Dr-Bean** [comment]
@Diaoul I'm not sure I understand what you're saying...care to explain? I don't think existing TC's have changed (or at least, I'm not aware of it)

**Comment by Diaoul** [comment]
What I'm saying is Synology can (and did with other DSM releases) change the file located [here](https://github.com/SynoCommunity/spksrc/blob/master/toolchains/syno-x64-5.2/Makefile#L10) for example.
No worry we will update the digests file but since the digests of toolchains aren't checked unless you `make clean` the toolchains, this might result in some of us not having the same toolchains yet the URL and filename didn't change.

**Comment by Dr-Bean** [comment]
Hm. We can't fix changed file locations on our end (except keep them up-to-date), so there's nothing we win there.
As for changed digests, didn't SourceForge provide a computed MD5 for the file that we can compare to digests? It's down for me, so I can't check.

**Comment by piwi82** [comment]
The checksum (MD5) ca be retrieved using the RSS feed provided on the download page.
* http://sourceforge.net/projects/dsgpl/rss?path=/DSM%205.2%20Tool%20Chains/Intel%20x86%20Linux%203.2.40%20%28Pineview%29

<code>&lt;media:hash algo="md5"&gt;54d756924c6ba864e472e67c5bc79925&lt;/media:hash&gt;</code>

**Comment by Dr-Bean** [comment]
Let's move this part of the discussion to #1996 :)

**Comment by 1shez** [comment]
When the packages are updated for Braswell/DS716+ would this be where everyone will be notified? And how far along are we now in getting them updated?

**Comment by hongkongkiwi** [comment]
:+1:  Very excited to see these packages available. Totally didn't realise I couldn't use synocommunity on my new 716+ :-(

**Comment by piwi82** [comment]
@1shez : SynoCommunity is community based, no one is paid to package applications. So don't expect any ETA or notification.

**Comment by anyall** [comment]
Hello,
Is it possible to download only 1 package and install it manually?
I'm interested in OwnCloud spk...

**Comment by piwi82** [comment]
How would you like to download a package that doesn't yet exist ?
`braswell` packages will automatically appear in the *Package center* when compiled.

**Comment by yeled** [comment]
I can confirm this [pull request](https://github.com/SynoCommunity/spksrc/pull/2013) wfm.

**Comment by 1shez** [comment]
Am I right in saying that we can now add the synocommunity repo to our DS716+ now and install packages?

**Comment by SimWhite** [comment]
@1shez Not yet.

**Comment by 1shez** [comment]
Thanks - looks like everything is slowly coming together though.

**Comment by Diaoul** [comment]
I did a commit to add the toolchain: 3088bdca0e991a22ec3a94d25a8d39baf863aba9
I won't be able to publish all the packages until next week. I'll do at least the major ones.

**Comment by davidmerrique** [comment]
@Diaoul Thank you! I've managed to add the package source. I don't see those packages in 3088bdc though. Will it just take a while for them to show up?

**Comment by deadlyknapsack** [comment]
@Diaoul thank you!!! :-)

**Comment by 1shez** [comment]
Thank you! Merry Christmas!

**Comment by deadlyknapsack** [comment]
@Diaoul I tried NZBGet on my DS716+ yesterday, but when it tries to unpack, I get an error: failed unpack. Is it too soon to open an issue, or am I missing a setting?

**Comment by Diaoul** [comment]
Which DSM version? Maybe it doesn't find unrar on your system for some
reason.

**Comment by deadlyknapsack** [comment]
@Diaoul it was a permission issue. Fixed it and then deleted my comment. So far no issues :-)

**Comment by 1shez** [comment]
Could anyone tell me what packages are now available for the DS716+ ?

I'm wanting to install NZBGet, Sonarr and Couchpotato - are these available?

**Comment by deadlyknapsack** [comment]
@1shez NZBGet and Couchpotato are working fine.

**Comment by 1shez** [comment]
@deadlyknapsack Thank you - is Sonarr available do you know?

**Comment by deadlyknapsack** [comment]
No idea.

**Comment by dutchtrooper** [comment]
Hello
I want to install NZBGet on my Nas 716+
The tell me that i must get packages  http:/packages.synocommunity.com
only its telling me that it is a wrong url
What iam doing wrong?

**Comment by 1shez** [comment]
That is the wrong URL that's why. 

https://packages.synocommunity.com

**Comment by dutchtrooper** [comment]
Thanks 1shez :)

**Comment by deadlyknapsack** [comment]
@1shez any news on Sonarr? :)

**Comment by 1shez** [comment]
@deadlyknapsack Best thing to do is just keep checking. @Diaoul did mention that main packages were done right away and the rest will be done next week :)

**Comment by Dr-Bean** [comment]
Kernel added with https://github.com/SynoCommunity/spksrc/commit/6af15b18c99d6a75e0190d378f9be10f7a14a05c. @Diaoul Still building, or should I build and retry all packages?

**Comment by Diaoul** [comment]
There might be a few packages missing, you can go ahead and add the missing ones.

**Comment by Dr-Bean** [comment]
@Diaoul I might even redo the existing packages for Braswell...please recreate/fill local.mk, we're missing a number of values in INFO for those packages ;)

**Comment by Diaoul** [comment]
I did a fresh install with `make setup`. This is caused by your recent changes, I thought configuration was optional and had correct default values?

**Comment by Dr-Bean** [comment]
https://github.com/SynoCommunity/spksrc/issues/2007#issuecomment-166133012 should explain it, I think.
The configuration is optional in that packages work without setting values. But, for packages _we_ distribute on the SynoCommunity repo, we want to use the values as per that comment.

**Comment by Diaoul** [comment]
I stopped at `[...] or regenerate [...]`. My bad.
Why not have `make setup` do all that for us? I mean spksrc is developed by SynoCommunity so I think it makes sense to default the config for SynoCommunit's repository. It's already the case for the API.

**Comment by Dr-Bean** [comment]
Actually, I considered removing the hardcoded API as well ;) I decided against it at the time: without publish permissions, it can't be used anyway.

Setting blank entries in local.mk helps to get away from packages created and published with spksrc to be associated with SynoCommunity _by default_.
Setting default values via `make setup` defeats the purpose: it's hardly different from hardcoding it in spk.mk imo.

**Comment by Diaoul** [comment]
I meant it *can* work with other repositories not it does it by default.
I get your point, what about prompting the user during `make setup` and asking if we want to use SynoCommunity's default configuration? (y/N)
I just want a common way for SynoCommunity developers to setup their environment without having to look some issue on GitHub to find the appropriate configuration steps. Even a additional `make setup-synocommunity` is fine by me.

**Comment by Dr-Bean** [comment]
Sure, we don't necessarily want to make it harder for ourselves, so that's a valid point.
I'd probably prefer `make setup-synocommunity` myself, but a prompt would work. I'll come up with something.

**Comment by Dr-Bean** [comment]
Published the remaining Braswell packages, and recreated the ones uploaded by @Diaoul.
There are probably a couple packages missing due to build issues, those will be fixed in due time.

**Comment by Dr-Bean** [comment]
As requested, added a `make setup-synocommunity` command for SynoCommunity devs with 1277c441e4ea617631eeb72e2fcd6b61a2d8ca52.

**Comment by Castelen** [comment]
I still get "invalid locatin." when trying to add https://packages.synocommunity.com/.

Is the package source available for DS716+ yet or not?

**Comment by gizmocuz** [comment]
Also getting an "invalid location" on my DS216+ (braswell)
No VPN in use here.

Building packages myself and hosting a private repo is working...
