### ISSUE TITLE
Request: Add DS216play/ Monaco Toolchain

### ISSUE THREAD

**Issue by flyhnl** [SynoCommunity/spksrc#1946]
HI there,

Today Synology has released the chain tools(http://sourceforge.net/projects/dsgpl/files/) for the STMicroelectronics Monaco architecture which the DS216play uses.
Can you incorporate this? and release the community packages so we can use this?

**Comment by funnybutrandom** [comment]
Oooo yes please!

**Comment by Dr-Bean** [comment]
Thanks, but please use search before opening a new issue, so things are kept centralized. Use https://github.com/SynoCommunity/spksrc/issues/1876.
