### ISSUE TITLE
DS213+ didn't installing typhon packge

### ISSUE THREAD

**Issue by anjelo111** [SynoCommunity/spksrc#1947]
![python](https://cloud.githubusercontent.com/assets/15936963/11292460/879d6d10-8f91-11e5-8e01-f92e29079563.png)
when i install typhon package then installed package success with ignoring indexs.
like this.

Ignoring indexes : http://pypi.python.org/simple Collecting uwsgi
(from -r /usr/local/python/share/wheelhouse/requirements.txt(line1))
Installing collected packages : uwsgi Successfully installed uwsgi-2.0.10

anyone help me??

**Comment by Dr-Bean** [comment]
It's just an info message, nothing to worry about.
Package is already fixed, the next version of the package won't show that message anymore.

**Comment by anjelo111** [comment]
thank you for your answer. 
installed python and debian-chroot, next connect SSH
but when i connect SSH and commend bash shell 'apt-get update' then message showed 
'illegal instruction'.
this problem is python package??
![putty](https://cloud.githubusercontent.com/assets/15936963/11318898/03730a78-90a8-11e5-83b7-023436288aa1.png)

**Comment by Dr-Bean** [comment]
Read this: https://github.com/SynoCommunity/spksrc/issues/834. It has nothing to do with Python, and everything with the arch Qoriq (or PPC for that matter)
