### ISSUE TITLE
DS216play unable to install Sonarr

### ISSUE THREAD

**Issue by Emptaze** [SynoCommunity/spksrc#1954]
When I click on install, nothing happens. Basically what happened when the architecture was added to the repository but the packages were not installable yet. Might be related to Mono because that's not visible as package and I believe Sonarr runs on it?

**Comment by Dr-Bean** [comment]
Mono 4.0.4.1 is available as a beta package. You can enable beta packages in the Package Center settings.
Mono 3.x (the current stable version for other arches) won't be made available for Monaco.
