### ISSUE TITLE
NZBGet Error while uploading an NZB file

### ISSUE THREAD

**Issue by cell2k** [SynoCommunity/spksrc#1955]
Hello there,

i have a problem with NZBGet from time to time. Please be advised that this problem isnt´s occuring every day. 
I´ve setted up the system and everything works just fine. After a few days i can´t add anymore NZBs to the queue.

My NZBget runs on a Synology Diskstation with the latest DSM. I´ve connected a remote-folder (which is the NZBDir) from my workstation from which i access the NZBGet Web-GUI.
Now i want to add an NZB and click "scan incomming directory": now the circle runs and runs and runs and nothing happens. 

I click on "Upload NZB", my harddrive opens and i select an NZB-file. Now the filename is shown in the GUI and the circle turns and turns and turns. After AGES i get an error:

Error in http://192.168.xxx.xxx:xxxx/upload.js (line 336)
Uncaught ReferenceError: next is not defined

On that point i reload NZBGet and then everything works fine for a few days until it all starts over.
I wouldn´t mind to reload it from time to time but on the day it happens the time it takes to throw the error is extrem long (up to an hour). In this time i can´t do anything.

**Comment by Dr-Bean** [comment]
This seems to be an issue in NZBget itself. I'd suggest to open an issue on the nzbget support forums, http://forum.nzbget.net/viewforum.php?f=3.
The developer (and other contributors) are very active, and should be able to help you out.
