### ISSUE TITLE
Tvheadend issue finding DVB Inputs

### ISSUE THREAD

**Issue by samgix6** [SynoCommunity/spksrc#1959]
Hi, I have read the troubleshooting steps regarding missing DVB inputs for TVHeadend on my 1515+.  I have stopped TVheadend, made sure Video Station was up and running, restarted the NAS, and then started TVheadend again.  The config page opens fine, just no input sources.  The dropdown is blank.  Any suggestions?  
##

**Comment by PiterEL** [comment]
Has anybody newest (latest) version TVHeadend on Synology ? I have model DS713+. please give me link where i can download latest version in spk ?

Anybody has with transcodding ?

**Comment by lexyan** [comment]
@samgix6 : Try to disable TV EPG in VideoStation Settings as it does'nt release DVB sticks.

@PiterEL : You can find updated package of TvHeadend here => http://syno.dierkse.nl/ or compile it yourself based on the current TvHeadend package

**Comment by botazefa** [comment]
I've installed on 1515+.  Both my Hauppauge 950Q USB sticks show-up as DVB inputs.  I'm having other problems, but not that.  Make sure you haven't disabled DTV in VideoStation.  That's what loads the drivers and handles the hotplug to create the /dev/dvb/adapterX files.  If you don't have any adapters, then you can do a 'dmsg | grep -i usb' or something like that.  It looks to me like the DS1515+ ships with all the standard Linux DVB drivers/firmwares, so if DTV is enabled in VideoStation and you're still not seeing /dev/dvb/adapterX, I'd bet your tuner isn't Linux supported.
