### ISSUE TITLE
Deluge AutoAdd doesn't show up in preferences

### ISSUE THREAD

**Issue by sinewave** [SynoCommunity/spksrc#1961]
Hi,

So excited to see that you added this package! Im having some trouble getting AutoAdd to work though. I enabled the plugin but it doesn't show up in the Preferences window and I don't know if another way to configure the auto add folders?

Any ideas?

**Comment by Dr-Bean** [comment]
Not package related. See http://forum.deluge-torrent.org/viewtopic.php?f=9&t=26775&start=10#p126655.
