### ISSUE TITLE
Synology DS716+ Braswell support

### ISSUE THREAD

**Issue by ArieLiebregts** [SynoCommunity/spksrc#1964]
Hello,
I just bought a Synology DS716+ with an Intel Braswell processor.
Now I cannot install the SynoCommunity packages. 
When will Braswell be supported?

**Comment by cytec** [comment]
@ArieLiebregts see https://github.com/SynoCommunity/spksrc/issues/1944

**Comment by deadlyknapsack** [comment]
Synology said the tool chain will be available in the beginning of December. Not sure how much time is needed for the packages to be changed.
