### ISSUE TITLE
Jackett

### ISSUE THREAD

**Issue by Diaoul** [SynoCommunity/spksrc#1965]
https://github.com/Jackett/Jackett

**Comment by piwi82** [comment]
[Installation on Linux/OSX](https://github.com/Jackett/Jackett#installation-on-linuxosx) :

1. Install Mono 4 or better :weary:

This is a nice app, let's hope the Mono stuff will work flawlessly.

**Comment by Dr-Bean** [comment]
It does ;) Mono 3.x works, unless you count some unconfirmed issues with exceptions. Apart from that, Mono 4.x is available in beta, and Jackett was one reason for adding it.

Sidenote: I'll probably update Mono 4.x to latest in a bit, after I've worked out the PLIST and can confirm it works with Sonarr as well. Current version should work with Jackett without a hitch, several people are already using it.

**Comment by Diaoul** [comment]
Didn't know you had that one on your TODO list ;)

**Comment by Dr-Bean** [comment]
Well, I think you just pulled it off my list, and put it on yours :P

**Comment by Diaoul** [comment]
Did I?

**Comment by Dr-Bean** [comment]
I'm quite happy to give someone else a chance to package this. Think of the everlasting glory and praise you'll receive. @piwi82 sounded quite enthusiastic earlier...how about it?

**Comment by Diaoul** [comment]
Totally agree :+1:

**Comment by piwi82** [comment]
:sweat_smile: I don't use this app, I have just take a look at what it does.
Don't expect me to package this one :wink:

BTW: I have pushed [Adminer](https://github.com/SynoCommunity/spksrc/commit/9aa714df262ca0d7fcca6b9bf11d554933697fc6) to the repository. I don't remember how to publish it as beta (API key ? URL to post stuff ? ...)

**Comment by Dr-Bean** [comment]
Well...back to Diaoul then, I suppose ;)
All joking aside, I should have the code stashed somewhere I think. I still needed to figure out a way to get start-stop-daemon to work correctly, because iirc, it didn't work when I set it up identical to Sonarr, but I haven't looked at it since.

To publish as beta, set `BETA = 1` in the Makefile.

**Comment by Dr-Bean** [comment]
Done with https://github.com/SynoCommunity/spksrc/commit/aeac78cb0b82d6bb5d69aa68867f91a983e2a7da.

**Comment by Dr-Bean** [comment]
Jackett 0.7.33-1 has been published.
