### ISSUE TITLE
cannot update mono and git because of unkown publisher

### ISSUE THREAD

**Issue by M0UL** [SynoCommunity/spksrc#1967]
i cannot update mono and git because of unkown publisher

**Comment by Dr-Bean** [comment]
Did you follow https://synocommunity.com/#easy-install, and in particular, step 1?

**Comment by M0UL** [comment]
yes, i had to put it on allow unknown publishers, for the update to work

**Comment by Dr-Bean** [comment]
`Trusted publishers` should be sufficient. If that doesn't work for you, there's something wrong with the connectivity of your Synology. Removing and -re-adding the repo should work for that.
