### ISSUE TITLE
Can't open any packages from Community (SickRage, SickBeard Custom, Transmission)

### ISSUE THREAD

**Issue by nekikr** [SynoCommunity/spksrc#1968]
Hi,

I bought DS215j, currently have DSM 5.2-5644 Update 1 installed on it. I followed the steps to add SynoCommunity source, no problems there. I installed Git and Python (both are running), no problem there as well. But if I install SickBeard/SickRage/Transmission, I can install them, run them, but when I click on "open", nothing happens. No errors, no warning, nothing. What is wrong?

Thank you for help!

**Comment by GoodOmens83** [comment]
What do you mean by "open" them?  How are you trying this.

Are you going to the specific url mentioned in the app page?  Like opening your browser to http://\<synologyipaddress>:8899 for sickrage?  Where \<synologyipaddress> is the internal ip address of your synology box (e.g. 192.168.1.2 or 10.0.1.2 etc.)

**Comment by nekikr** [comment]
Well, "open" as in start application and use it :) If I go to Package center and Community, I have installed SickRage for example, and under the logo there is "run" button. If I press it nothing happens. I guess if it was working I would open this application and be able to use it. But when I click on "open" nothing happens.
If I click the link (http://ipv6 address:8899) new page opens (I use Chrome) but it is blank and says about:blank in the address bar.

**Comment by Diaoul** [comment]
Not sure IPv6 is supported by those packages. Try IPv4. Also check you don't block popups/ads and/or try a different browser.

**Comment by GoodOmens83** [comment]
Also make sure you are on the same internal network as your box.  If you are remote you'll need to open the appropriate port in your router.  I wouldn't advise that though :)

**Comment by nekikr** [comment]
Problem is in Chrome/IPv6. In Chrome link to SickRage is displayed in IPv6 format (I guess by default Chrome displays this instead of IPv4 if both are available, after switching to IE it works. Well, SickRage opens up, but I can't use it. I guess I had to make a new user in Synology so that SickRage could connect to it but first I had error that I should login to DS and retry, after reset it says sickrage is either user already (not on the list though) or some kind of system reserved user. Maybe it's best I leave this forever-beta apps alone... thank you for your help guys!

**Comment by Diaoul** [comment]
Give the sc-media group permission to where SickRage needs to have access. SickRage package will be deleted soon in favor of sickbeard-custom which does exactly the same thing so for any new installation I suggest you use that.

**Comment by nekikr** [comment]
Ok, so I deleted SickRage and installed SickBeard Custom. In the show settings I get a warning regarding permission denied for that folder. I go back to Synology and do what you wrote, sc-media group now has read/write access to the folder in question. I also marked "allow" for all applications. Still the same problem regarding permission.
So, I go back to users, add new user "sickbeard-custom", place it in sc-media group, give it access to the folder, give it access to applications that are related to this topic but at the last step, when there is summary of what this user is and what will have I click on "apply" and get error message "The operation failed. Please log in to DSM again and retry." I am logged in as admin, never had a problem like this before.

**Comment by Dr-Bean** [comment]
Use the `users` group for Sickbeard-Custom. See https://github.com/SynoCommunity/spksrc/issues/1893. 
Note that if you're using a subdirectory (as in `/volumex/shared_folder/subdir`), then you need to set read/write permissions for the lowest level, and at least traverse (part of read) permissions for the dirs in between.

For the record, you don't ever need to manually create a user with our packages: that's handled as part of the package installation.

**Comment by nekikr** [comment]
I am not sure how... I am not using subdirectory, so at least there is that. In the link you procided there is: "Use the users group in the mean time." I cannot add this sickbeard custom user to users group since I get an error like I wrote. The second hint is: "you can also edit the file "/etc/groups" and add the sickbeard-custom user to the sc-media group." How can I access this file? Under File Station on Synology there is no such directory (I know it must exist somewhere, but how can I access it)?

**Comment by Diaoul** [comment]
You don't need to edit anything, just grant the users group rw permission on the share.

**Comment by Dr-Bean** [comment]
I pointed to that issue to explain the background, nothing else :)
Here's what I would do in your situation:
- Install the package. 
- Say you place your files in `/volume1/videos`. Then you need to set read/write access for the `users` group on the shared folder `videos` (via the DSM GUI)
That's all there is to it.

**Comment by Dr-Bean** [comment]
^^ What he said ;) Beaten by 4 seconds :/

**Comment by nekikr** [comment]
Ok, this worked, thank you so much! I can't believe I did everything but such basic thing :/

One last thing, I hope, if you would be so kind:
I configured SickBeard Custom now, made everything in settings for subtitles (working), shows (listed and correct), folders and everything else, BUT there is a problem. SickBeard recognizes that there are some episodes missing, it finds torrents, passes them to Synology Download Station where they are listed but they are not downloading. A bunch of torrents are just listed there, File Size unknown, Progress unknown, nothing is happening. What could be wrong?

**Comment by nekikr** [comment]
Ok, done it. It seems it only works with Transmission but not Synology Download Station. Sucks that you have to read through 50 forums and web pages to get this information, I guess people writting this code are never thinking how people will actually use their product :(

Thank you for all your help, you are the best!

**Comment by NmE** [comment]
Unable to launch both Sabnzbd and Transmission after the latest update.
Assigned both "users" and "sc-download" full access to the shares, but still unable to launch the apps.

Log files does not show anything since the apps fail to launch.

**Comment by Dr-Bean** [comment]
@nekikr Download Station uses Transmission for torrents as well, so I don't immediately see a reason why it wouldn't work. Personally, I have never tried Sick* together with Download Station, but I'm sure there are people that use the combination. 
Something else: Note that the large majority of people involved are writing that code in their free time, so you can spend your free time on what you like to do...if nothing else, please be constructive in your criticism.

@NmE, your problem is not related to this issue as far as I can see. First guess: at some point, you have changed the user of both packages to something else. If so, please revert that, or reinstall the packages.
Otherwise, please open a new issue.

**Comment by Dr-Bean** [comment]
Seeing as this is resolved, let's close this :)
