### ISSUE TITLE
Error building boost for deluge

### ISSUE THREAD

**Issue by bonebox** [SynoCommunity/spksrc#1969]
I get the following error with compiling the boost package when building deluge.  There are 100 or so of these with `./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
compilation terminated.`

```
...failed gcc.compile.c++ bin.v2/libs/python/build/gcc-4.6.4/release/threading-multi/numeric.o...
gcc.compile.c++ bin.v2/libs/python/build/gcc-4.6.4/release/threading-multi/list.o
In file included from ./boost/python/detail/prefix.hpp:13:0,
                 from ./boost/python/list.hpp:8,
                 from libs/python/src/list.cpp:5:
./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
compilation terminated.
```

**Comment by bonebox** [comment]
It seems the problem is it's looking for pyconfig.h (and other python headers) in `/build/spksrc/cross/boost/work-armadaxp-5.2/install/usr/local/include` when they are in `/build/spksrc/cross/boost/work-armadaxp-5.2/install/usr/local/include/python2.7`.  Copying the files from the latter directory to the former allows it to continue.  However, now it's failing with the following:

```
make[2]: Entering directory `/build/spksrc/cross/deluge'
===>  Downloading files for deluge
===>    File deluge-1.3.12.tar.lzma already downloaded
===>  Verifying files for deluge
===>    File deluge-1.3.5.tar.lzma not downloaded
make[2]: *** [checksum_target] Error 1
make[2]: Leaving directory `/build/spksrc/cross/deluge'
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory `/build/spksrc/spk/deluge'
make: [arch-armadaxp-5.2] Error 2 (ignored)
```

**Comment by bonebox** [comment]
Not sure if this is the issue, but `cross/deluge/Makefile` references version `1.3.12`, while `cross/deluge/digests` references `1.3.5`.

**Comment by bonebox** [comment]
Changing digests to the following allowed the build the continue:

```
deluge-1.3.12.tar.lzma SHA1 ffb5919e8a4a881580af2a2791fa8940c2708228
deluge-1.3.12.tar.lzma SHA256 eb875724a8f52ac36c3890bdcee9f77c648ef03b6375387af5c26d5229fdc65e
deluge-1.3.12.tar.lzma MD5 56f5c1cd3f671fecc58a9168f5bd6d48
```

**Comment by bonebox** [comment]
Now I get the following error:

```
Collecting python-libtorrent (from -r /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/requirements.txt (line 4))
  Could not find a version that satisfies the requirement python-libtorrent (from -r /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/requirements.txt (line 4)) (from versions: )
No matching distribution found for python-libtorrent (from -r /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/requirements.txt (line 4))
```

**Comment by Dr-Bean** [comment]
Yep, I overlooked that digests file. It didn't trigger anything here, because I have both the new and the old file in my distrib dir. Thanks for noticing, fixed with 9e850af31f62d3a79c0a9cf944aca32520ee4ed5.
Make sure to start off with a `make clean` after updating.

As for the wheel collection failing, that means that the wheel was either never created (and something went wrong further up in the build process), or there's a name mismatch. 
There should be a wheel called `python_libtorrent-1.0.6-cp27-none-any.whl` in `/build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse`, so please check that.
If it's not there, you'll have to look at the output of the build process to see what went wrong.

**Comment by bonebox** [comment]
> There should be a wheel called python_libtorrent-1.0.6-cp27-none-any.whl in /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse, so please check that.

Yes, I did notice that the file is there.  Apparently pip isn't finding it for some reason?

**Comment by bonebox** [comment]
Here's more of the output. It's finding the other wheels in that directory, so not sure why it's not finding the one for python-libtorrent.

```
make[1]: Entering directory `/build/spksrc/spk/deluge'
===>  Processing wheels of deluge
===>  Creating requirements file
===>  Building wheels
Collecting characteristic (from -r /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/requirements.txt (line 1))
/usr/local/lib/python2.6/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  File was already downloaded /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/characteristic-14.3.0-py2.py3-none-any.whl
Collecting chardet (from -r /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/requirements.txt (line 2))
  Using cached chardet-2.3.0.tar.gz
Collecting pyasn1-modules (from -r /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/requirements.txt (line 3))
  File was already downloaded /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting python-libtorrent (from -r /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/requirements.txt (line 4))
  Could not find a version that satisfies the requirement python-libtorrent (from -r /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/requirements.txt (line 4)) (from versions: )
No matching distribution found for python-libtorrent (from -r /build/spksrc/spk/deluge/work-armadaxp-5.2/wheelhouse/requirements.txt (line 4))
make[1]: *** [wheel_target] Error 1
make[1]: Leaving directory `/build/spksrc/spk/deluge'
make: [arch-armadaxp-5.2] Error 2 (ignored)
```

**Comment by bonebox** [comment]
So I managed to get past the python-libtorrent error by just removing it from the wheels list in the Makefile. It then finished building the package successfully.  I installed it through package manager and it installed successfully, however won't run.  After inspecting the files, I noticed that the necessary executables are not present (i.e. deluged, deluge-web, etc).

**Comment by Dr-Bean** [comment]
>/usr/local/lib/python2.6/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py

You're working with Python2.6. Install Python2.7, and make sure that its pip is put it on $PATH before python2.6's.

>I noticed that the necessary executables are not present (i.e. deluged, deluge-web, etc). 

That's expected. Deluge checks for libtorrent-python, and won't install without it.

**Comment by bonebox** [comment]
Since python-libtorrent is getting built, it still gets copied over into the package.  I was able to get Deluge running successfully on my Synology by copying over the package.tgz and installing it manually.

However, I'm going to try building it again with Python2.7...

**Comment by bonebox** [comment]
Thanks for the help, that was the problem.  I was using a virtual machine running an older distro of Debian (Squeeze) because it was the only 32-bit image I could find, and it was using Python 2.6. In hindsight, I probably should have just installed my own.  I pointed to the Python 2.7 in native/python and was able to make without any issues, and the package installed successfully on my NAS.

**Comment by Dr-Bean** [comment]
Perfect :)
If you're looking for an alternative to setting up a VM yourself, try the docker image: https://hub.docker.com/r/synocommunity/spksrc.
