### ISSUE TITLE
DS716+ Invalid Location

### ISSUE THREAD

**Issue by 1shez** [SynoCommunity/spksrc#1970]
Hi when I try adding the repo on my new DS716+ I get the error 'Invalid Location. Am I right in saying that this is because the repo doesn't support this model yet? And if so is there any other way I can get NZBGet and Sonarr on there manually? Help will be greatly appreciated.

**Comment by Dr-Bean** [comment]
Please see #1944.

**Comment by 1shez** [comment]
I have already seen this - is there an estimated date for this? How long does it usually take Synology to update - will all packages work right away? Is there a way for me to install packages in the meantime before this happens?

**Comment by Diaoul** [comment]
1. Can take months
2. Once we compiled and uploaded them
3. No, unless you signed the NDA with Synology and got the toolchains
