### ISSUE TITLE
DS716+ Invalid location

### ISSUE THREAD

**Issue by sukysjonas** [SynoCommunity/spksrc#1973]
Hi

Trying to add http://packages.synocommunity.com/ to Package Manager results in 'Invalid location' error.
DNS servers are set properly.
Could this be an issue related to the newly supported 'braswell' architecture?
For instance, to install Plex Media Server, 'braswell' needs to be manually added to INFO file.

Any help highly appreciated!

**Comment by cytec** [comment]
use the search... see #1944 or #1970
