### ISSUE TITLE
rtorrent-0.9.6 libtorrent-0.13.6

### ISSUE THREAD

**Issue by MrOnyx** [SynoCommunity/spksrc#1978]
Please add rtorrent 9.6 for Synology Models cedarview.

**Comment by Dr-Bean** [comment]
It's already there? Turn on beta packages in Package Center settings, otherwise you won't see it.

**Comment by MrOnyx** [comment]
I can not see
![unbenannt](https://cloud.githubusercontent.com/assets/2565966/11612997/30bce142-9c11-11e5-9865-0d4c482ffde3.PNG)
![unbenannt1](https://cloud.githubusercontent.com/assets/2565966/11612998/35dbe560-9c11-11e5-913c-4215a7f2213d.PNG)
![unbenannt2](https://cloud.githubusercontent.com/assets/2565966/11612999/393cb716-9c11-11e5-8220-778bd8b78fa0.PNG)

**Comment by Dr-Bean** [comment]
The view on synocommunity.com only shows the `-7` packages for 'new' arches, there's nothing we can do about it. `-6` is the latest for all the others. There's no functional difference between the two.

**Comment by MrOnyx** [comment]
This version is installed rtorrent 0.9.2/0.13.2 rutorrent 3.6.6
how to update rtorrent to 0.9.6/0.13.6

**Comment by GoodOmens83** [comment]
0.9.2 is the latest in the package library.  A package for 0.9.6 is being developed and not released.

**Comment by MrOnyx** [comment]
@GoodOmens83 
myself I have no idea how to compiling packages
![dsm](https://cloud.githubusercontent.com/assets/2565966/11614110/443d3326-9c38-11e5-8737-b2b6d0311f99.PNG)
