### ISSUE TITLE
Update Owncloud to 8.2.1

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1979]
Link: https://download.owncloud.org/community/owncloud-8.2.1.tar.bz2
Release notes: https://owncloud.org/changelog/
Manual upgrade instructions: https://doc.owncloud.org/server/8.2/admin_manual/maintenance/manual_upgrade.html
##

**Comment by Kaelber** [comment]
I use Synology servers DS412+, DS1512+, DS712+, DS414. This version of owncloud doesn´t run on all machines properly, so I use the package here on all servers and maximum owncloud v8.1.4. The v8.2.1 seems running on my DS712+ with current DSM 6 Beta, but e.g. on the DS412+ the v8.2.1 runs not good.

**Comment by Pimmetje** [comment]
@Kaelber What part does not run correctly? 

Is it safe to do a manual update?
What do i need to update?

**Comment by Kaelber** [comment]
In the meantime I use v8.2.2.2 and all is running well. I use a manual update [https://owncloud.org/install/#instructions-server](url)
Read the documentation for this, it was no problem.

**Comment by Pimmetje** [comment]
Can i do this without breaking my the synology package? I know owncloud but i am new to synology :D

**Comment by Kaelber** [comment]
No, nothing breaks. Only consider, that in the package center the no. of version doesn´t change, if a package is installed. But it´s also possible to install owncloud without package with the webinstaller of owncloud or manual by hand. This is also no problem.

**Comment by Eothred** [comment]
ownCloud version 9 is now out, see the same changelog link, or [release anouncement](https://owncloud.org/blog/owncloud-server-9-0-released/)

**Comment by Eothred** [comment]
@Kaelber so, if you do a manual update, do you not then risk that if the synocommunity package is updated later on, that update will break? you should in that case disable updating of this particular app?

**Comment by Kaelber** [comment]
If you use the ownCloud package of synocommunity, currently 8.1.1.7, it´s no problem to update to the actual version 8.2.2.2 (it´s better, because new version 9.0.0.19 is to buggy.). In my newer installations, I doesn´t use packages from synocommunity or other, I use the ZIP or the Webinstaller of ownCloud, it´s also running.

**Comment by Eothred** [comment]
OK, thanks for that clarification. I updated to 8.2 series then for now using the update functionality in the admin interface of ownCloud. Worked smoothly for me.

**Comment by Safihre** [comment]
Handled via #2710.
