### ISSUE TITLE
Update Python packages

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#1981]
Download link: https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tar.xz
Changelog: https://hg.python.org/cpython/raw-file/53d30ab403f1/Misc/NEWS

Along with this, review and update all dependencies of the package.
##

**Comment by Dr-Bean** [comment]
+ Add psutil wheel to both Python packages. Use the current `cross/psutil`, update that to latest, add another `cross/psutil-old_version` package as to not break homeassistant (or better yet, get it updated...)

**Comment by Dr-Bean** [comment]
Python2 updated via 46317af0341f2fa56ed081e81c62c471210ce147, including the psutil addition.
Psutil addition for python3 done with 132f043e67e50e09d3693572362afc0b0465e034.

**Comment by Dr-Bean** [comment]
- Drop six from Python3's WHEELS, and add the wheel installation stuff in the installer. I was testing with using native/python's pip in preparation for updating to Python3.5, and this slipped through.

**Comment by Dr-Bean** [comment]
Published Python 2.7.11-15. I'll keep this one open to remind me of the rest of the work.

**Comment by dominix** [comment]
python doesn't install on my RS3412RPxs.
where should I find the error-log ?

**Comment by Dr-Bean** [comment]
Congrats. You're the first person to be directed to the FAQ: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#i-tried-to-install-a-package-and-i-get-failed-to-install-package-what-do-i-do.
If that doesn't work for you, please open a new issue. This particular issue is not meant for troubleshooting.

**Comment by Dr-Bean** [comment]
I think this is done, so closing.
