### ISSUE TITLE
ffsync Non-authentication error in _fetchTokenForUser: TokenServerClientError

### ISSUE THREAD

**Issue by Hubfront** [SynoCommunity/spksrc#1984]
Hello, i tried to get the ffsync working on my DS214play, but after installing ffsync and logging into Firefox account no data seem to be inserted in the db.

The following is the error-log:

[error-sync-1449447430571.txt](https://github.com/SynoCommunity/spksrc/files/53337/error-sync-1449447430571.txt)

or as plain text:

1449447429871	Sync.Service	INFO	Loading Weave 1.44.0
1449447429872	Sync.Engine.Clients	DEBUG	Engine initialized
1449447429872	Sync.Engine.Clients	DEBUG	Resetting clients last sync time
1449447429876	Sync.Engine.Bookmarks	DEBUG	Engine initialized
1449447429878	Sync.Engine.Forms	DEBUG	Engine initialized
1449447429880	Sync.Engine.History	DEBUG	Engine initialized
1449447429883	Sync.Engine.Passwords	DEBUG	Engine initialized
1449447429884	Sync.Engine.Prefs	DEBUG	Engine initialized
1449447429886	Sync.Engine.Tabs	DEBUG	Engine initialized
1449447429886	Sync.Engine.Tabs	DEBUG	Resetting tabs last sync time
1449447429889	Sync.Engine.Addons	DEBUG	Engine initialized
1449447429890	Sync.Service	INFO	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0
1449447429893	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1449447429894	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1449447429894	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1449447429894	Sync.AddonsReconciler	INFO	Registering as Add-on Manager listener.
1449447429894	Sync.AddonsReconciler	DEBUG	Adding change listener.
1449447429895	Sync.ErrorHandler	DEBUG	Beginning user-triggered sync.
1449447429897	browserwindow.syncui	DEBUG	observed: weave:service:ready
1449447429897	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1449447429899	Sync.Engine.AdblockPlus	DEBUG	Engine initialized
1449447429900	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1449447429901	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1449447429902	Sync.Service	DEBUG	User-Agent: Firefox/42.0 FxSync/1.44.0.20151029151421.
1449447429902	Sync.Service	INFO	Starting sync at 2015-12-07 01:17:09
1449447429902	Sync.Service	DEBUG	In sync: should login.
1449447429902	browserwindow.syncui	DEBUG	observed: weave:service:login:start
1449447429902	browserwindow.syncui	DEBUG	onActivityStart with numActive: 0
1449447429902	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1449447429902	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1449447429902	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1449447429903	Sync.Tracker.Clients	WARN	Changed IDs file clients contains non-object value.
1449447429907	Sync.Tracker.Bookmarks	WARN	Changed IDs file bookmarks contains non-object value.
1449447429908	Sync.Tracker.Forms	WARN	Changed IDs file forms contains non-object value.
1449447429909	Sync.Tracker.History	WARN	Changed IDs file history contains non-object value.
1449447429910	Sync.Tracker.Passwords	WARN	Changed IDs file passwords contains non-object value.
1449447429915	Sync.Tracker.AdblockPlus	WARN	Changed IDs file adblockplus contains non-object value.
1449447429916	Sync.Tracker.AdblockPlus.private	WARN	Changed IDs file adblockplus.private contains non-object value.
1449447430508	Hawk	DEBUG	(Response) /certificate/sign: code: 200 - Status text: OK
1449447430509	Sync.RESTResponse	TRACE	Processing response headers.
1449447430509	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -509
1449447430510	FirefoxAccounts	DEBUG	getCertificate got a new one: true
1449447430511	FirefoxAccounts	DEBUG	_updateAccountData with items: ["keyPair","cert"]
1449447430512	FirefoxAccounts	DEBUG	getAssertionFromCert
1449447430513	FirefoxAccounts	DEBUG	writing plain storage: ["email","sessionToken","uid","verified","oauthTokens"]
1449447430514	FirefoxAccounts	TRACE	starting write of json user data: ["email","sessionToken","uid","verified","oauthTokens"]
1449447430519	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1449447430520	Sync.BrowserIDManager	DEBUG	Getting a token
1449447430521	Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: http://diskstation:8132/1.0/sync/1.5
1449447430533	FirefoxAccounts	TRACE	finished write of json user data - took: 19
1449447430534	FirefoxAccounts	DEBUG	writing secure storage: ["kA","kB"]
1449447430534	FirefoxAccounts	TRACE	starting write of user data to the login manager
1449447430559	FirefoxAccounts	TRACE	finished write of user data to the login manager
1449447430561	Common.TokenServerClient	DEBUG	Got token response: 404
1449447430561	Sync.RESTResponse	TRACE	Processing response headers.
1449447430563	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientError({"message":{}}) (resource://gre/modules/services-common/tokenserverclient.js:36:36) JS Stack trace: @tokenserverclient.js:36:36 < @browserid_identity.js:14:1 < @status.js:15:1 < SyncServiceObserver.init@sync.js:76:62 < @sync.js:459:1 < require@bootstrap.js:140:7 < @main.js:30:1 < require@bootstrap.js:140:7 < startup@bootstrap.js:24:3 < XPI_callBootstrapMethod@XPIProvider.jsm:4774:9 < XPI_startup@XPIProvider.jsm:2484:13 < callProvider@AddonManager.jsm:221:12 < _startProvider@AddonManager.jsm:828:5 < AMI_startup@AddonManager.jsm:999:9 < AMP_startup@AddonManager.jsm:2672:5 < AMC_observe@addonManager.js:58:7
1449447430563	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1449447430563	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1449447430564	browserwindow.syncui	DEBUG	observed: weave:ui:login:error
1449447430564	browserwindow.syncui	DEBUG	onLoginError: login=error.login.reason.network, sync=success.sync
1449447430564	browserwindow.syncui	DEBUG	_loginFailed has sync state=error.login.reason.network
1449447430565	Sync.BrowserIDManager	ERROR	Background fetch for key bundle failed: TokenServerClientError({"message":{}}) (resource://gre/modules/services-common/tokenserverclient.js:36:36) JS Stack trace: @tokenserverclient.js:36:36 < @browserid_identity.js:14:1 < @status.js:15:1 < SyncServiceObserver.init@sync.js:76:62 < @sync.js:459:1 < require@bootstrap.js:140:7 < @main.js:30:1 < require@bootstrap.js:140:7 < startup@bootstrap.js:24:3 < XPI_callBootstrapMethod@XPIProvider.jsm:4774:9 < XPI_startup@XPIProvider.jsm:2484:13 < callProvider@AddonManager.jsm:221:12 < _startProvider@AddonManager.jsm:828:5 < AMI_startup@AddonManager.jsm:999:9 < AMP_startup@AddonManager.jsm:2672:5 < AMC_observe@addonManager.js:58:7
1449447430566	Sync.BrowserIDManager	ERROR	Could not authenticate: TokenServerClientError({"message":{}}) (resource://gre/modules/services-common/tokenserverclient.js:36:36) JS Stack trace: @tokenserverclient.js:36:36 < @browserid_identity.js:14:1 < @status.js:15:1 < SyncServiceObserver.init@sync.js:76:62 < @sync.js:459:1 < require@bootstrap.js:140:7 < @main.js:30:1 < require@bootstrap.js:140:7 < startup@bootstrap.js:24:3 < XPI_callBootstrapMethod@XPIProvider.jsm:4774:9 < XPI_startup@XPIProvider.jsm:2484:13 < callProvider@AddonManager.jsm:221:12 < _startProvider@AddonManager.jsm:828:5 < AMI_startup@AddonManager.jsm:999:9 < AMP_startup@AddonManager.jsm:2672:5 < AMC_observe@addonManager.js:58:7
1449447430568	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1449447430569	browserwindow.syncui	DEBUG	observed: weave:service:login:error
1449447430569	browserwindow.syncui	DEBUG	onActivityStop with numActive: 1
1449447430569	browserwindow.syncui	DEBUG	_loginFailed has sync state=error.login.reason.network
1449447430569	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1449447430570	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms.
1449447430570	Sync.ErrorHandler	ERROR	Sync encountered a login error

**Comment by Dr-Bean** [comment]
What happens when you put http://diskstation:8132/1.0/sync/1.5 in the address bar of your browser? (might need to right-click, view source). The 404 you're getting there seems to indicate that there's an issue with that.

**Comment by Hubfront** [comment]
Solved: it was a simple typo. 
How did i found it? Regarding your question: i was getting a 0 as response for getting http://diskstation:8132/1.0/sync/1.5 . So the server was responding.
Therefore i rechecked the value for identity.sync.tokenserver.uri and found a typo: it must read http://diskstation:8132/token/1.0/sync/1.5 in my case.

Sorry for inconvenience glad it works now :)
