### ISSUE TITLE
Can't start Sabnzbd after update

### ISSUE THREAD

**Issue by theVanZan** [SynoCommunity/spksrc#1986]
I updated sabnzbd over the weekend. Previously I had everything set up and working fine for about a year. But after the update I couldn't start sabnzbd back up. I kept getting a failed to start service error.

I tried to fix things tonight but seem to have made things worse. I uninstalled sabnzbd with the aim of re-installing it.

From when it was installed and I was trying to start it I checked /var/log/messages and see lots of:

pkgstartstop.cpp:187 Failed to start package sabnzbd, [1] No such file or directory.

Would appreciate some help as I seem to be making things worse! Thank you.

**Comment by theVanZan** [comment]
I managed to re-install it and I can see the set up wizard. Just got to config it all again...:(

**Comment by arkayenro** [comment]
i just upgraded and have the same issue

Dec  8 14:43:26 NAS entry.cgi_SYNO.Core.Package.Control[1].start[19753]: pkgstartstop.cpp:182 Failed to start package sabnzbd, [1]

uninstalled and re-installed and still get the same error

**Comment by arkayenro** [comment]
my fault, should have checked synopkg.log, i forgot that i run sab as root so have to change the USER variable in /var/packages/sabnzbd/scripts/start-stop-status to root to get it to start

**Comment by Dr-Bean** [comment]
Here's a very similar problem, with likely the same cause, where I've just explained how it works: https://github.com/SynoCommunity/spksrc/issues/1972#issuecomment-162820695.

@arkayenro It's up to you, but you'll see your problem reoccurring with every package update if you change the user. Besides, not a good idea to run as root...again, up to you of course.
