### ISSUE TITLE
Newbie obstacles

### ISSUE THREAD

**Issue by mulle-nat** [SynoCommunity/spksrc#1987]
I want to compile syncthing for my DS213+.

So I created a 32 bit Debian VM and followed the instructions. The first problem I encountered:  I am supposed to install **bjam**, but that package doesn't exist anymore. So I ignored it.

The second problem happened when trying to build **transmission**. I did `make arch-qoriq-5.2` and this worked OK until it couldn't download `openssl-1.0.2d.tar.gz`. Something is broken there, but I don't really want to build transmission anyway.

I want to build **syncthing**, but when I say `make arch-qoriq-5.2` in **syncthing** it doesn't work, because `Arch 'qoriq' is not a supported architecture`.

But in **transmission** it's known. How is architecture support determined on a package basis ? I would like to give it a try anway.

**Comment by Diaoul** [comment]
The decision is not SynoCommunity's. Syncthing is developed in Go and qoriq (or PPC in general for that matter) doesn't support Go.

See https://github.com/SynoCommunity/spksrc/blob/master/spk/syncthing/Makefile#L7

It seems however [ppc64 might be supported](https://github.com/golang/go/issues/10298)? If that's the case we might reconsider.

**Comment by Diaoul** [comment]
Closing in favor of #1835

**Comment by mulle-nat** [comment]
Thanks for pointing out line #7, which basically answers my question. 
As far as I know go 1.5 can do ppc somewhat [releasenotes](https://golang.org/doc/go1.5)

```
 Also available as experiments are ppc64 and ppc64le (64-bit PowerPC, big- and little-endian). Both these ports support cgo but only with internal linking. 
```

Is qoriq in the 213+ 64 bit ?

**Comment by Diaoul** [comment]
I don't know but it's worth a shot.
