### ISSUE TITLE
[new package request] Piwigo

### ISSUE THREAD

**Issue by Eothred** [SynoCommunity/spksrc#1990]
I was wondering how complicated it would be to provide a Piwigo package, or if it is at all possible. I get the impression it might not be an awfully complicated task. Maybe I could even consider to try to do this myself if I find the time and people could give me a few pointers.
- [Web page](http://piwigo.org)
- [Requirements](http://piwigo.org/basics/requirements)
- [Demoes](http://piwigo.org/showcase/)
##

**Comment by cytec** [comment]
you should be able to install that when you have enbabled your webserver :)

**Comment by Eothred** [comment]
OK, I will have a look into manual installation as soon as I have time. If that is easy to install when webserver is enabled that also means it should be easy to write the package I guess?
