### ISSUE TITLE
Just out of curiosity, now that Braswell is released.

### ISSUE THREAD

**Issue by deadlyknapsack** [SynoCommunity/spksrc#1992]
I noticed that the Braswell tool chain is released. I have zero experience with Synology, packages or compiling in general. But out of curiosity, is there any estimate on how long it will take for the packages to be updated for the DS716+? Are we talking about days, weeks, months? Cheers! Keep up the good work guys!

**Comment by Dr-Bean** [comment]
Please use the search, use #1944.
