### ISSUE TITLE
copy /usr/include/<file>.h to install/usr/local/include folder

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2005]
(.h) header files in /usr/include/ are not visible during execution of config file.
I see two variables in config file.
includedir='${prefix}/include'
oldincludedir='/usr/include'
If I manually copy header file /usr/include/<myfile>.h to directory "cross/<project>/work-<arch>-<dsm>/install/usr/local/include" all is good but I guess it must exist an option to copy all needed files automatically. It doe not make sense this task is a manual one.
Can anybode help me?

**Comment by Diaoul** [comment]
Have you read https://github.com/SynoCommunity/spksrc#usage?
If so, on which step is this error occuring?

**Comment by vkostas** [comment]
@Diaoul
Error occurs during configure script. I am cross compiling mpd.0.18.23 btw on a debian jessy.

1. make arch-\<my_arch\>
checking tcpd.h usability... no
checking tcpd.h presence... no
checking for tcpd.h... no
configure: WARNING: libwrap not found -- disabling libwrap
/////
I had installed libwrap before make
sudo aptitude install libwrap0-dev libwrap0

2. sudo find / -name tcpd.h
/usr/include/tcpd.h

3. I know this is stupid way to do it but gave it a try...
cp /usr/include/tcpd.h work-\<my_arch\>-\<my_dsm_version\>/install/usr/local/include

4. make arch-\<my_arch\>
checking for tcpd.h... yes
checking for request_init in -lwrap... no
configure: WARNING: libwrap not found -- disabling libwrap

5. sudo find / -name libwrap*
found file libwrap.m4 in work-\<my_arch\>/mpd.0.18.23/m4 and following ones in the system.
/usr/share/doc/libwrap0
/usr/share/doc/libwrap0-dev
/usr/lib/i386-linux-gnu/libwrap.a
/usr/lib/i386-linux-gnu/libwrap.so
/lib/i386-linux-gnu/libwrap.so.0.7.6
/lib/i386-linux-gnu/libwrap.so.0
/var/lib/dpkg/info/libwrap0-dev:i386.md5sums
/var/lib/dpkg/info/libwrap0:i386.postinst
/var/lib/dpkg/info/libwrap0-dev:i386.postinst
/var/lib/dpkg/info/libwrap0:i386.postrm
/var/lib/dpkg/info/libwrap0:i386.shlibs
/var/lib/dpkg/info/libwrap0:i386.symbols
/var/lib/dpkg/info/libwrap0:i386.list
/var/lib/dpkg/info/libwrap0:i386.md5sums
/var/lib/dpkg/info/libwrap0-dev:i386.list

Why compiler cannot find this library? I have the same issue with several other libraries.

**Comment by lexyan** [comment]
You install libwrap for your system and not for the spksrc cross-compilation system.
Read https://github.com/SynoCommunity/spksrc#Contribute and try to had libwrap in the cross folder.

**Comment by vkostas** [comment]
Of course I have read the readme file (usage, contribute, etc).
The only thing it says is "Try to cross-compile and fix issues as they come (missing dependencies, configure arguments, patches)".
1. How can I know what exactly to copy to cross folder?
2. Then how to add the copy instructions into the Makefile?
libwrap is just one of the issues I have. In fact cross-compile ends without error. I just want to remove as much warnings as possible.
I need some guide how other spksrc contributors proceed in similar cases. A real example would be nice.

**Comment by lexyan** [comment]
I have added tcp_wrappers to my fork in cross/tcp_wrappers, you can get it here => https://github.com/lexyan/spksrc/tree/master/cross/tcp_wrappers

**Comment by vkostas** [comment]
@lexyan Thank you!!!

**Comment by Dr-Bean** [comment]
Yep, @lexyan is correct: you don't want to install (dev) packages on the host, you want to cross-compile them. That's what the `cross` folder is for.

Seems that the question is answered then?
