### ISSUE TITLE
ownCloud 8.x.x on Synology server | ownCloud Client Download problem

### ISSUE THREAD

**Issue by Kaelber** [SynoCommunity/spksrc#2006]
I use Synology servers DS412+, DS1512+, DS712+, DS414, all equiped with ownCloud.

I have server directories with External Storage Support included with the effect that at server side and between different Synology DS's everything is going great. Are files modified on client side, this are also uploaded with the client (v2.1.0). Only download files that have been changed on the server does not always work.

If downloading not ongoing and when files are uploaded, the other server-side files also are downloaded, but only in those directories, a uploading is done. And this effect only is in this directories, I have this load processes.

It seems to me that this all is related to the Synology package service of ownCloud. If the Synology package service of "ownCloud" is set to "Run", also the download to the client is working. If this Synology package service is "stopped", I have the above effect.

The only question is, why the Synology package service will stop without intervention. Can you say something about someone? Which may be a reason why the service stops?

This effect I also have had with owncloud 7.x.x in the past.

**Comment by Kaelber** [comment]
The Synology package service will stop without intervention. To start I use Synology package center.
![owncloud started](https://cloud.githubusercontent.com/assets/12963736/11894367/eb8989da-a576-11e5-99cb-15f0ff35f783.jpg)
![owncloud stopped](https://cloud.githubusercontent.com/assets/12963736/11894366/eb865b2a-a576-11e5-9180-6d759708fc55.jpg)

**Comment by Kaelber** [comment]
I also try a new installation of owncloud 8.1.1-7 but also with a very new setup of all, I have the same effect.

**Comment by Kaelber** [comment]
It seems, also the package service is not the reason. Also, if the service is running, is possible to have the above effects....

Now, what can I doe?

**Comment by Dr-Bean** [comment]
>If the Synology package service of "ownCloud" is set to "Run", also the download to the client is working. If this Synology package service is "stopped", I have the above effect.

Well, it makes sense to me that If the package isn't running, it won't be able to do what's needed. Look at running the service manually (https://github.com/SynoCommunity/spksrc/blob/master/spk/owncloud/src/owncloud.sh#L13), then try and do what you normally do. If it crashes, then you have something to look at. Note that the service is normally run with the `http` user.

**Comment by Kaelber** [comment]
Thanks for your comment and script for this, but this is no solution, because the change from "run" to "stop" are multiple per day and this manually things therefore are not so efficient.

In this moment I try the solution with the ownCloud webinstaller on my Synology servers 
DS412+ with DSM 5.2-5644 update 2, 
DS1512+ with DSM 5.2-5644 update 2, 
DS712+ with DSM 6.0 Beta, 
DS414 with DSM 5.2-5644 update 2. 
In this way I have two circumstances:

1. version 8.1.4 doesn´t support external storage, also if I support :/volume1 in open_basedir and the app is activated.

2. version 8.2.1 is running on all machines, but in those servers with DSM 5.2-5644 update 2 I doesn´t get the Administration page, only a message of the Synology server, that this page is not available. This is strange, because only on the machine with DSM 6.0 Beta the Administration page is running. What is the difference here, what can I doe?

I need in the external company a running server application, because I can not enter the server with a port (such http://IP_server:5001), I only can run adresses with a path (such http://IP_server/owncloud).

**Comment by Dr-Bean** [comment]
It wasn't intended as a solution, merely a way for you to gain more insight into why it's happening. 
Your explanation is very extensive and detailed, with, as far as I can see, a lot of unrelated stuff. Bring it back to the essentials: The Owncloud PHP service appears to stop/crash. Can you reliably replicate that and if so, what log/trace/debug information is available to you?
With that information, you should be able to tell if it's Owncloud itself being buggy, or whether it's related to DSM or even the package we provide.
If you can reproduce the issue after manually installing Owncloud (or via the webinstaller... I assume a different way to install Owncloud?), then you should talk to the Owncloud developers.

All the other stuff just confuses things. Administrations page not available? Different problem. DSM6? That's a beta, and is never going to be representative of a stable environment. My advice: stay away from it.

**Comment by Kaelber** [comment]
Okay, I consider this.

Because of the Administration page I got the log:

is_dir(): open_basedir restriction in effect. File(/var/services/homes) is not within the allowed path(s): (/etc.defaults:/etc:/usr/syno/synoman:/tmp:/var/services/tmp:/var/services/web:/var/services/homes:/volume1) at /volume1/web/owncloud/3rdparty/symfony/process/Symfony/Component/Process/ExecutableFinder.php#59

I can´t read that, what is to doe, because in the open_basedir it seems it all setted (:/var/services/homes).

**Comment by Dr-Bean** [comment]
Yes, but that doesn't happen with the package we provide, does it? Our Owncloud package is currently at 8.1.1. An update to update the Owncloud package to 8.2.1 is requested via #1979, but currently, no progress has been made there.

**Comment by Kaelber** [comment]
Okay, thats true with #1979, but I think, in any time you have a updated package and during the developement you also have to fight with such things. I prefer your package, because it´s a "normal" application for Synology servers. Because the installation is very easy to use, I use yours since you made, also in this time, you have parallel with Eric Gielians from eg-blog with owncloud 5+

**Comment by Kaelber** [comment]
It seems, is not good to use owncloud v8.2.1 on DSM 5.2, because of apache v2.4 is needed but apache v2.2 is installed. On DSM 6 is apache 2.4 installed and there owncloud is running well so far, it seems. But it´s strange for me, that v8.1.1 and 8.1.4 also needs apache v2.4 but this version runs on the DSM 5.2. servers, only with the above effect.

So I go back to your package with using the last 8.1.x => I use v8.1.4 .......

**Comment by Kaelber** [comment]
So I´m back on v8.1.4 with the SynoCommunity package, only the above effect is happen. I use now only external storage. If I make anything at the files on server side with the owncloud server gui, also the client works. If I store or delete files with a FTP-client in the filesystem, the client doesn´t work.

**Comment by Dr-Bean** [comment]
We can't provide support for altered versions of the SynoCommunity Owncloud package. Besides that, the issue does not seem package related to me, as indicated by the fact that even with a different version, you still have issues.

Take another look at my earlier comment. You will need to gather more information about the issue. Create a testcase in which you can reliably trigger the issue. Collect logs and debug info. When you have that, your best bet is to register a bug/open an issue with the Owncloud developers, and provide that info.

**Comment by Kaelber** [comment]
Now I found a solution as follow and I include in the crontab

0,20,40 4-23 * * * root /bin/su -s /bin/sh -c "cd /volume1/web/owncloud && /usr/bin/php -f occ files:scan rescan" http >> /volume1/web/owncloud/data/logs/cron_rescan_rescan_$(date +\%Y-\%m-\%d_\%H-\%M-\%S).log 2>&1

but this only works, when the open_basedir is empty and is only valid for ownCloud 8.2.x-versions.

This doesn´t run with 8.1.x versions. This may no problem, I update all servers on v8.2.2 - but with the new Synology DSM 6.0 beta also this doesn´t work with the ownCloud versions 8.2.x.

As follow a rescan-log with the combination Synology DSM 6.0 beta mit ownCloud 8.2.2:

An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: could not find driver' in /volume1/web/owncloud/lib/private/db/connection.php:52
Stack trace:
#0 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /volume1/web/owncloud/lib/private/db/connection.php(135): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /volume1/web/owncloud/lib/private/db/connectionfactory.php(118): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /volume1/web/owncloud/lib/private/server.php(328): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC{closure}(Object(OC\Server))
#9 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /volume1/web/owncloud/lib/private/server.php(763): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /volume1/web/owncloud/lib/private/db.php(42): OC\Server->getDatabaseConnection()
#12 /volume1/web/owncloud/lib/private/server.php(235): OC_DB::getConnection()
#13 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC{closure}(Object(OC\Server))
#14 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('AppConfig')
#15 /volume1/web/owncloud/lib/private/server.php(702): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /volume1/web/owncloud/lib/private/server.php(373): OC\Server->getAppConfig()
#17 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC{closure}(Object(OC\Server))
#18 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('AppManager')
#19 /volume1/web/owncloud/lib/private/server.php(929): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#20 /volume1/web/owncloud/lib/private/app.php(259): OC\Server->getAppManager()
#21 /volume1/web/owncloud/lib/private/app.php(104): OC_App::getEnabledApps()
#22 /volume1/web/owncloud/lib/base.php(566): OC_App::loadApps(Array)
#23 /volume1/web/owncloud/lib/base.php(1081): OC::init()
#24 /volume1/web/owncloud/console.php(42): require_once('/volume1/web/ow...')
#25 /volume1/web/owncloud/occ(11): require_once('/volume1/web/ow...')
#26 {main}

Any idea?

In which way may be possible to include a fixed rescan modul in owncloud, to have a "internal" ownCloud system solution?

**Comment by d-tamm** [comment]
See this solution, which worked for me:
http://www.synology-forum.de/showthread.html?74988-DSM-6-0-OwnCloud-8-2-X-X-PHP-Cron-Fehler
Essentially using /usr/local/bin/php56 instead of /bin/php
