### ISSUE TITLE
Move maintainer, distributor, report_url to local.mk?

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2007]
Instead of defaulting to SynoCommunity for maintainer (-url), distributor (-url) and report_url, we should consider moving them to local.mk. 
This prevent packages from being published outside of SynoCommunity's repo, but under our name. See #2003 for example. Those packages point to SynoCommunity, causing confusion as to who is responsible for those packages.

In doing so, unfortunately, package authors who wish to be credited won't be, unless they publish their packages on the repo themselves. A possible solution might be to set `maintainer` in the spk's Makefile instead.

@SynoCommunity/developers?

**Comment by piwi82** [comment]
:+1:

**Comment by Dr-Bean** [comment]
I just realised the last part is probably not an issue. We already provide the ability to set the maintainer in the Makefiles obviously...After defining the variables in local.mk, it's should be sufficient to delete all instances of `MAINTAINER = SynoCommunity` from spk/*/Makefile, and we're done.

**Comment by Diaoul** [comment]
I believe there is a maintainer branch that does just that. However that's not implemented in the backend.

**Comment by Dr-Bean** [comment]
It's not the main goal anyway ;) I'll set up a PR in a bit.

Do you still want to have the the maintainer branch merged then (as far as it'll go anyway)?

**Comment by Diaoul** [comment]
I think maintainer should be kept in the Makefile. Ultimately it should be set to the package author in some way or at least point to it as a link. It's easy enough to change if you fork spksrc and won't prevent updates unless conflicting with another changeset upstream.

I agree for the others, spksrc should be repository agnostic (asides from local.mk)

**Comment by Dr-Bean** [comment]
Take a look: https://github.com/SynoCommunity/spksrc/pull/2014.
If MAINTAINER is set in the SPK's Makefile, it'll take precedence. Otherwise, it'll pick it out of local.mk/error out. It's the only required field of the bunch.
All the others should be set in local.mk, all to be set manually.

**Comment by Diaoul** [comment]
Awesome then :+1:

**Comment by Dr-Bean** [comment]
I'll merge this in a bit. For the record, MAINTAINER_URL behavior has changed. The URL should probably be built on the repo side, but we don't use it atm so no urgency.

**Comment by Dr-Bean** [comment]
Merged with 5a17600350866ace6170943668f40403dc9abc1a.
@SynoCommunity/developers, please add the following to your local.mk, or regenerate.
```
MAINTAINER?=SynoCommunity
MAINTAINER_URL=https://synocommunity.com
DISTRIBUTOR=SynoCommunity
DISTRIBUTOR_URL=https://synocommunity.com
REPORT_URL=https://github.com/SynoCommunity/spksrc/issues
```

**Comment by Dr-Bean** [comment]
Created #2024 to update the maintainers, assuming the content is still correct (not complete by a long shot, but that's a separate subject)

**Comment by Dr-Bean** [comment]
Merged #2024 with 1a5de241086eb28dfeb86502e507379d990a86d8, I'll remove the `maintainers` branch sometime if I don't forget.

For future reference: a `make setup-synocommunity` was added which sets the defaults in local.mk as per https://github.com/SynoCommunity/spksrc/issues/2007#issuecomment-166133012

**Comment by Dr-Bean** [comment]
Removed the maintainer branch.

**Comment by Diaoul** [comment]
:+1: good work
