### ISSUE TITLE
Sickrage (NameError: 'show' is not defined)

### ISSUE THREAD

**Issue by xmenxmen** [SynoCommunity/spksrc#2011]
After the latest Sickrage update i got this error.
Synology Dsm 5.2 1513+

Error !

NameError: 'show' is not defined

<% qualities = Quality.splitQuality(sickbeard.QUALITY_DEFAULT) %> <% anyQualities = qualities[0] %> <% bestQualities = qualities[1] %> <%include file="/inc_qualityChooser.mako"/> <br> <div class="field-pair alt"> <label for="saveDefaultsButton" class="nocheck clearfix"> <span class="component-title"><input class="btn btn-inline" type="button" id="saveDefaultsButton" value="Save Defaults" disabled="disabled" /></span>
/usr/local/sickrage/var/SickRage/gui/slick/views/inc_qualityChooser.mako, line 0:
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 752:
callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
/usr/local/sickrage/var/SickRage/gui/slick/views/inc_addShowOptions.mako, line 88:
<%include file="/inc_qualityChooser.mako"/>
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 752:
callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
/usr/local/sickrage/var/SickRage/gui/slick/views/home_addExistingShow.mako, line 36:
<%include file="/inc_addShowOptions.mako"/>
/usr/local/sickrage/var/SickRage/gui/slick/views/layouts/main.mako, line 270:
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 890:
callable_(context, *args, **kwargs)
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
/usr/local/sickrage/var/SickRage/lib/mako/template.py, line 454:
as_unicode=True)
/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 191:
return self.mako_lookup.get_template(template_name).render_unicode(**template_kwargs)
/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 194:
return self.render_string(template_name, **kwargs)
/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 2605:
topmenu="home")
/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 219:
return function(**kwargs)

**Comment by xmenxmen** [comment]
How can i go one update back?

**Comment by lexyan** [comment]
It seems to be a Sickrage issue, not SynoCommunity.
If you want to go back after an update you need to stop SickRage and then connect through ssh to your NAS.
Navigate to /usr/local/sickrage/var/SickRage
do a "git log " to get the hash of the previous commit (hit Q to stop listing)
and git checkout hash_of_the_commit
you can restart SickRage
