### ISSUE TITLE
Sickrage runtime error - Downloaded is not defined.

### ISSUE THREAD

**Issue by stupadaso** [SynoCommunity/spksrc#2012]
Getting a similar error as the guy who posted a couple hours ago, only difference is mine says "downloaded" is not defined. I get this error whenever I click on the name of one of the TV programs that is watched by Sickrage. 

Sickrage itself seems to still be working properly, I just can't get into each individual show to edit it.

Sickrage took an update a few days ago. I can't remember exactly when. This issue seems to have started after the update.

(As a side note - since my 1812+ updated back in late Nov/early Dec - to Update 2 - Sickrage has been a little finicky. Whenever I check it almost every morning, about 2/3rds of the time the Sickrage package has shut itself off at some point during the night. I have to go back into the NAS package center and turn Sickrage back on. There is nothing in the logs about it. The log contains nothing except the basic daily search entries. FYI - This particular NAS never turns off, never sleeps, never goes into hibernation. It's always working 24/7/365. Also, the stopping of Sickrage never coincides with any scheduled tasks, like SMART tests or anything like that.)

Synology 1812+ with DX513 expansion

DSM 5.2-5644 Update 2

Error !

NameError: 'DOWNLOADED' is not defined

<script type="text/javascript" src="${srRoot}/js/ajaxEpSearch.js?${sbPID}"></script> <script type="text/javascript" src="${srRoot}/js/ajaxEpSubtitles.js?${sbPID}"></script> </%block> <%block name="content"> <%namespace file="/inc_defs.mako" import="renderQualityPill"/> <input type="hidden" id="srRoot" value="${srRoot}" /> <div class="pull-left form-inline"> Change Show: <div class="navShow"><img id="prevShow" src="${srRoot}/images/prev.png" alt="&lt;&lt;" title="Prev Show" /></div>
/usr/local/sickrage/var/SickRage/gui/slick/views/displayShow.mako, line 23:
<%block name="content">
/usr/local/sickrage/var/SickRage/gui/slick/views/layouts/main.mako, line 270:
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 890:
callable_(context, *args, **kwargs)
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
/usr/local/sickrage/var/SickRage/lib/mako/template.py, line 454:
as_unicode=True)
/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 191:
return self.mako_lookup.get_template(template_name).render_unicode(**template_kwargs)
/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 194:
return self.render_string(template_name, **kwargs)
/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 1278:
title=showObj.name
/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py, line 219:
return function(**kwargs)

**Comment by Diaoul** [comment]
Report upstream
