### ISSUE TITLE
[SickBeard] since last update to 20151220-4 can't connect to T411

### ISSUE THREAD

**Issue by origais** [SynoCommunity/spksrc#2023]
Hi,
since last update, I got the following error:
2015-12-22 09:53:00 SEARCHQUEUE-DAILY-SEARCH :: [T411] :: Unable to connect to provider

I did no change either my T411 account login or pass, and did not change anything in Sickbeard conf.

note: github was updated at the same time as sickbeard to version 2.6.3-5
note2: DS412+

Thanks for your help

**Comment by Dr-Bean** [comment]
The update didn't touch the SB code, only backup/restore during the update process. Note that it's very well possible that the provider isn't/wasn't available due to maintenance or what have you. Otherwise, issues with providers should be reported upstream.
