### ISSUE TITLE
Error in directories creation after sabnzbd install

### ISSUE THREAD

**Issue by vinzcoyote** [SynoCommunity/spksrc#2025]
hello, i have an issue just after installing sabnzbd on DS716+
it said "Unable to create folder /volume1/downloads/SABnzbd/incomplete

I never had this message before on DS210+, any idea?
thx

**Comment by Dr-Bean** [comment]
Set appropriate permissions on the SABnzbd dir. Use the `users` group or the `sc-download` group.

**Comment by vinzcoyote** [comment]
OK, thanks
it was the downloads dir needing permissions
all ok now

**Comment by Pimmetje** [comment]
I had the same issue. Maybe it could be written somewhere in the installer. Or maybe the installer can apply the needed permissions?
