### ISSUE TITLE
Web UI Plugin Manager Issues (Syn DS412+)

### ISSUE THREAD

**Issue by arijaycomet** [SynoCommunity/spksrc#2026]
Running the latest updated OctoPrint (v20151221-2) on my Synology DS412+ (on DSM 5.2-5644 Update 2).  Things run great, CuraEngine works awesome, etc.  However, I'm unable to add any additional Plug-ins using the Web UI Plugin Manager.  Specifically, Email Notifier is the one I'm trying to get going.

Below is a copy (cut/paste) of the log it shows on screen through the UI when attempting to complete the installation.  My Synology setup is very basic (and I'm an Intermediate user at best, no expert!).  Nothing is rooted or hacked or whatever... so if I need to do some command line changes or something let me know (and being wet behind the ears, I may need hand-holding there LOL)

Please advise/help with any advice to help get this to install correctly.  Thanks!

--- [ copy/paste of on-screen logging during plugin install attempt ] ---

Installing plugin "Email Notifier" from https://github.com/anoved/OctoPrint-EmailNotifier/archive/master.zip...
/usr/local/octoprint/env/bin/pip install https://github.com/anoved/OctoPrint-EmailNotifier/archive/master.zip
Collecting https://github.com/anoved/OctoPrint-EmailNotifier/archive/master.zip
Downloading https://github.com/anoved/OctoPrint-EmailNotifier/archive/master.zip
Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-WKtTUH-build
Complete output from command python setup.py egg_info:
Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?

----------------------------------------

Done!

**Comment by markbastiaans** [comment]
I've managed to reproduce the issue. I've found the cause, am currently working on a fix and will do a new PR for OctoPrint soon.

**Comment by Dr-Bean** [comment]
octoprint 20160103-3 has been published.
