### ISSUE TITLE
Sonarr doesn't start after update.

### ISSUE THREAD

**Issue by Logis** [SynoCommunity/spksrc#2027]
DS212
Mono 4.2.1.102-6
Sonarr 20150731-8

after updating Sonarr via the web GUI, it won't start anymore.

Log shows:
[Log fail.txt](https://github.com/SynoCommunity/spksrc/files/72022/Log.fail.txt)

Not sure where to go from here. Any advice ?

Fixed , backed up the /.config and reinstalled sonarr.

**Comment by Dr-Bean** [comment]
Fixed I see? Then let's close this, thanks for letting us know.
