### ISSUE TITLE
Create dependent cross-packages?

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2028]
Building a new *spksrc* package needs of course its dependent packages.
I am working on mpd.
So far I am able to cross-compile it. Many of prerequisite packages are cross ones, the rest is just *sudo aptitude install*-ed.

Looking at the package list (dependent-required, recommended, optional) can get you very far. E.g. a part of pulseaudio prerequisite packages are:
* json-c (d)
* libsndfile (d)
  * alsa-lib (o)
    * doxygen (o)
      * <b>cmake (o)</b>
        * curl (r)
        * libarchive (r)
    * python-2.7 (o)
  * FLAC (o)
    * libogg (o)
    * NASM (o)
    * DocBook-utils (o)
    * Doxygen (o)
    * Valgrind (o)
  * libogg (o)
  * libvorbis (o)
  * sqlite (o)

Are there some packages will work by normally *sudo aptitude install*-ing them or we should nevertheless create all prerequisite cross-packages? E.g. <b>cmake</b> does not need to be cross-compiled. How to decide whether we don't need the cross-package (that would help reducing the effort)?
What about the *optional* packages (does it depend on the good mood of the contributor :-) )?

**Comment by Diaoul** [comment]
mpd is already there: https://github.com/SynoCommunity/spksrc/blob/master/cross/mpd/Makefile all you need is update the libs and mpd itself if necessary.

**Comment by vkostas** [comment]
Of course *mpd* is there, but it has an "ancient" version.
My question goes beyond mpd.
Can anybody tell how to distinguish prerequisite packages must-go in cross-compile from the ones it is enough to install them (aptitude install).

**Comment by Diaoul** [comment]
I don't get your question, you *never* need to use `aptitude` or `apt-get`.
There are few exceptions (mainly tools such as documentation generators and code generators) but they should already be included in spksrc's Docker image. As for when to add one of those exceptions, first thing is to try to disable it with a configure option (`--without-docs` or similar to disable documentation for example and hopefully the need for Doxygen) and if that's not possible install it locally. To make sure there is no side effect in the produced binary, cross-compile an arch different from your host (I personnaly use 88f6281).

Make that part of a PR and explain why you needed that tool.

**Comment by vkostas** [comment]
Hi @Diaoul.
Thx for the tip. I will definitely try it.
Taking pulseaudio (http://www.linuxfromscratch.org/blfs/view/svn/multimedia/pulseaudio.html) as a real example, I would need to build around +100 prerequisite cross-packages (including optional ones).
It does not sound "right" to me I have to build so many packages just for pulseaudio . That's my "headache".
Any hint is welcome. Thx.

**Comment by Diaoul** [comment]
Start with required and recommended, add optionals if necessary for the package. tl;dr start small

**Comment by Dr-Bean** [comment]
Seems to be answered, so closing. If not, @vkostas, let us know.
