### ISSUE TITLE
Sonarr won't install

### ISSUE THREAD

**Issue by 1shez** [SynoCommunity/spksrc#2031]
I can see Sonarr has now been updated for Braswell (716+) and now shows up in package center. First of all I just want to say thank you.

I can install any other package but when I try install Sonarr nothing happens - I click on install and nothing happens. I've tried on 2 different browsers and have restarted the DS but to no avail - so I'm guessing there may be some issue with the package - as like I said I can install every other package available in SynoCommunity.

**Comment by Dr-Bean** [comment]
Enable beta packages. You need to install Mono, and that package is only available in the beta channel for your model.

**Comment by 1shez** [comment]
@Dr-Bean Many thanks. I can confirm I have fully tested this on my DS716+ and it works absolutely fine.
