### ISSUE TITLE
openssl LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2036]
openssl produces some errors (which do not stop building process btw).
Tried with various architectures, same result. Is it smth to worry about? ...
Thx a lot.

Doing certs/demo
ERROR: ld.so: object '~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../libcrypto.so.1.0.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../libssl.so.1.0.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../apps/openssl: 1: ~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../apps/openssl: Syntax error: word unexpected (expecting ")")
ERROR: ld.so: object '~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../libcrypto.so.1.0.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../libssl.so.1.0.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../apps/openssl: 1: ~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../apps/openssl: Syntax error: word unexpected (expecting ")")
WARNING: Skipping duplicate certificate ca-cert.pem
ERROR: ld.so: object '~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../libcrypto.so.1.0.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../libssl.so.1.0.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../apps/openssl: 1: ~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../apps/openssl: Syntax error: word unexpected (expecting ")")
WARNING: Skipping duplicate certificate dsa-pca.pem
ERROR: ld.so: object '~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../libcrypto.so.1.0.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../libssl.so.1.0.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../apps/openssl: 1: ~/spksrc/cross/openssl/work-88f6281-5.2/openssl-1.0.2e/util/../apps/openssl: Syntax error: word unexpected (expecting ")")
WARNING: Skipping duplicate certificate dsa-ca.pem
##

**Comment by Dr-Bean** [comment]
Nothing interesting. It probably is related to how we cross-compile OpenSSL. From what I can tell, the errors occur when the build process tries to execute the cross-compiled binary to set up root certificates. Seeing as those aren't included in the first place, the end result is exactly the same as it would have been if the step did succeed.

Seems there's no easy way to turn it off, but feel free to give it a try.
