### ISSUE TITLE
[NZBGet] /usr/local/nzbget/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget/bin/nzbget)

### ISSUE THREAD

**Issue by Decipher** [SynoCommunity/spksrc#2037]
NZBGet doesn't appear to run on my DS413. When running `start-stop-status start` via ssh it gives the following error:

    /usr/local/nzbget/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget/bin/nzbget)

**Comment by Decipher** [comment]
Oddly it appeared to sort itself out when I uninstalled and re-installed domoticz. Unsure of the relationship.

**Comment by Dynom** [comment]
Thanks, your issue did help me out after hours of searching!
