### ISSUE TITLE
[Request] MAKE

### ISSUE THREAD

**Issue by alexvd12** [SynoCommunity/spksrc#2039]
Hi could you please add MAKE to the syncommunity?

I will happily donate extra.

**Comment by Dr-Bean** [comment]
Please provide sufficiently detailed information when you open a request. What is MAKE? 
Do you mean [GNU Make](https://www.gnu.org/software/make)? I'm sorry, that's probably not going to happen. The spksrc framework allows you to cross-compile software, instead of compiling directly on the device.

**Comment by Dr-Bean** [comment]
Closing, not enough info. See https://github.com/SynoCommunity/spksrc/issues/1990 for an example on what to provide in a request.
