### ISSUE TITLE
[request] Filebot Renamer

### ISSUE THREAD

**Issue by kinnth** [SynoCommunity/spksrc#2040]
I'd like to get the TV and movie renamer make for Synology

http://www.filebot.net/

It already exists on his own server, but it might be nice to get it on the Synocommunity

https://www.filebot.net/forums/viewtopic.php?f=3&t=1802

**Comment by Dr-Bean** [comment]
With the developer of FileBot himself maintaining the package on his own repository, there's limited to no added value in maintaining a second package. 
We might do things differently in regards to how the package is setup/installed, but not to an extent that a FileBot user would notice a difference.
