### ISSUE TITLE
Request: FFmpeg - filters support

### ISSUE THREAD

**Issue by Szeryff** [SynoCommunity/spksrc#2042]
Current FFmpeg version doesn't work with filters and it doesn't allow to hardcode subs into movie
file.
Is it possible to compile new version with flag '--enable-libass'. According to internet it should solve the problem.

**Comment by Dr-Bean** [comment]
#1662 will probably handle this, whenever @cytec gets to finishing it.

**Comment by cytec** [comment]
oh.. yeah... almost forgot that :/
Hope i can make some time in the near future to finish this finally

**Comment by GuillaumeSmaha** [comment]
@Dr-Bean @cytec @KaraokeStu I think it can be closed =)
