### ISSUE TITLE
GnuPG  - synocommunity package - issue with gpg agent

### ISSUE THREAD

**Issue by spesmagna** [SynoCommunity/spksrc#2043]
Hello all,

Regarding the GnuPG package for Synology. Can someone please kindly advise how to get it going once the package is installed? When I use the command line and run gpg --gen-key I get an error about gpg agent not being found. Is the gpg agent something extra I need to install?

Thank you,

Spesmagna

**Comment by Dr-Bean** [comment]
@adrien-delhorme, any input here?
@spesmagna For starters, you need to use the correct path. `/usr/local/gnupg/bin` is where the binaries for gnupg are located, and I don't believe a `gpg` binary is available. So you're executing something else...

**Comment by adrien-delhorme** [comment]
@Dr-Bean the gnupg spk only create a `gpg-agent` binary, but on my Synology a `gpg` binary was already present in `/usr/bin/gpg`, don't you?

@spesmagna have you tried to run the `gpg-agent` command?

**Comment by Dr-Bean** [comment]
@spesmagna Any update?

@adrien-delhorme Yes, I know that, the reason I said it was because Synology's approach is missing the associated `gpg-agent` binary for some reason. On the other hand, your package currently has a `gpg2` binary available, but it doesn't seem to want to work with the included `gpg-agent` either (try it).

**Comment by Koxx3** [comment]
on synology gpg-agent is installed in /volume1/@appstore/gnupg/bin/
you can run it ... but ... there is no pinentry.
so, impossible to decrypt anything :(
duplicity cannot recover files without decryption.

**Comment by adrien-delhorme** [comment]
I will try to cross compile pinentry. But I really don't know how gnupg works, so if someone can help...
What command are you running to get an error about missing pinentry?

**Comment by adrien-delhorme** [comment]
Finally I added pinentry in #2238

**Comment by Dr-Bean** [comment]
gnupg 2.1.6-2 has been published on the repository. Thanks @adrien-delhorme ;) Closing this one, it should be solved.

**Comment by skarbnik** [comment]
Hello guys, I am pretty new to using gpg on Synology DS212. I have installed gnupg 2.1.6-2 and when running gpg --gen-key, it processes the entire creation routine, but finally gives me the following error: 

gpg: error running `/usr/bin/gpg-agent': probably not installed
gpg: DBG: running `/usr/bin/gpg-agent' for testing failed: Configuration error
gpg: can't connect to the agent: IPC connect call failed
gpg: problem with the agent: No agent running
gpg: error running `/usr/bin/gpg-agent': probably not installed
gpg: DBG: running `/usr/bin/gpg-agent' for testing failed: Configuration error
gpg: can't connect to the agent: IPC connect call failed
gpg: problem with the agent: No agent running
gpg: Key generation canceled.

Can anyone of you advise? I figure this is exactly the problem you have had in the beginning, and I wonder why the update has not worked for me. (This is serious, I even got a GitHub-Account to proceed here!) Thank you.

**Comment by Dr-Bean** [comment]
@skarbnik You're running the gpg binary that Synology includes (and which is broken, as per my comment here: https://github.com/SynoCommunity/spksrc/issues/2043#issuecomment-172790467)
Run the binary that our package adds: `/usr/local/gnupg/bin/gpg --gen-key` and go from there.

**Comment by skarbnik** [comment]
Hi @Dr-Bean, thank you so much for your answer. I tried /usr/local/gnupg/bin/gpg, stumbled into some problems with executing the gpg binary, then found the right binary package and succeeded executing it with ./gpg2 --full-gen-key. Everything worked fine. Thanks for your great support!

**Comment by Dr-Bean** [comment]
Oh right, it's gpg2, forgot about that. Glad to hear it's working for you :)
