### ISSUE TITLE
Qoriq support for Mono

### ISSUE THREAD

**Issue by BernieV1977** [SynoCommunity/spksrc#2044]
Is it possible to support Mono for the DS213+ (Qoriq architecture)?
Thx!

**Comment by Dr-Bean** [comment]
Unfortunately not. Mono doesn't support Qoriq or (most) other PPC arches. See https://github.com/SynoCommunity/spksrc/issues/1812 for example.

**Comment by piejanssens** [comment]
@Dr-Bean Mono 5.0.0 release notes:

```Bring PowerPC back to life

Mono can bootstrap on ppc64le.```

**Comment by piejanssens** [comment]
Testers needed: https://github.com/SynoCommunity/spksrc/issues/3470
