### ISSUE TITLE
Illegal instruction with debian-chroot on qoriq

### ISSUE THREAD

**Issue by jaybird2** [SynoCommunity/spksrc#2046]
I installed debian-chroot 8.1-6  on a ds213+ (qoriq) within dsm 5.2.
There i get the following error.
-------------------------------------
/volume2/@appstore/debian-chroot/var/chroottarget$ chroot . /bin/bash
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
root@schatzkiste:/# apt-get install gcc
Illegal instruction
root@schatzkiste:/# apt-get update
Illegal instruction
root@schatzkiste:/# cat /proc/cpuinfo
processor       : 0
cpu             : e500v2
clock           : 1066.666000MHz
revision        : 5.1 (pvr 8021 1151)
bogomips        : 133.33
------------------------------------

Any advice here?

thx.

**Comment by Dr-Bean** [comment]
Known issue, see https://github.com/SynoCommunity/spksrc/issues/834
