### ISSUE TITLE
Where do you run a Python command line for YagMail / OctoPrint? (Syn DS412+)

### ISSUE THREAD

**Issue by arijaycomet** [SynoCommunity/spksrc#2049]
Thanks to the recent update (octoprint 20160103-3), I'm finally able to get the EmailNotifier Plugin to install properly on my OctoPrint Package installed on my Syn DS412+ device.  However, I'm not getting email notifications at all.  This is on my HOME 3D Printer.

When I setup my OctoPi at WORK location, I had to run a Python script to setup keychain as noted here:
https://github.com/kootenpv/yagmail

To do so I just had to write "import yagmail" while in the correct Python folder.  I'm unable to figure out what folder that is on my NAS here at home.  Obviously you need to run the yagmail.register command to setup a username and password (at least that is what it took at work to get things working, so my home setup probably needs the same to work right for my SMTP server)

(Sidebar: to get work to behave I did app-specific password using Gmail-- and it works flawlessly for me-- so I know that is prob what I'll need to do here, but i'm not even able to get to a python command line to run the yagmail.register entry for keychain--- because I'm a n00b!) LOL

TIA for the help! - Ari

**Comment by Dr-Bean** [comment]
Octoprint is installed in its own virtualenv: `/usr/local/octoprint/env`.

**Comment by arijaycomet** [comment]
I'mw ay out of my depth here.  I was able to terminal into my NAS, and LS to that directory.  In the BIN directory I see Keyring (green) though I must admit I have no clue what file type that means it is. I'm not entirely sure what to do from there, to register my username and password.  No clue.

So I tried typing Python to get a command prompt there for Python.  But then I try to follow the same steps I did at my office, but when I write "import yagmail" i get this:
>>> import yagmail
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named yagmail

Again, WAY out of my depth here.  I know basic command prompt stuff just from my DOS days back as a kid. I'll be 40 later this year, but my career path really never gave me reason to master Linux or anything.  So while I dabble, this is a fool's errand for me.  Any help, hand holding, sorry for being such a beginner! Thanks....

**Comment by Dr-Bean** [comment]
Yagmail isn't installed alongside the plugin, so you need to install it yourself. The Yagmail README provides the generic info on how to do that here: https://github.com/kootenpv/yagmail#install. 
The virtualenv I mentioned previously has its own copy of `pip`, (located in `/usr/local/octoprint/env/bin/pip`), so you need to use that for the installation.
Same as for the `import yagmail` stuff, you need to use the Python binary inside the virtualenv.

**Comment by kootenpv** [comment]
Hey, you could try:

    /usr/local/octoprint/env/bin/pip install yagmail

Then run once:

    /usr/local/octoprint/env/bin/python -c "import yagmail; yagmail.register('username', 'password')"

**Comment by Dr-Bean** [comment]
^^ Correct, that's just about my comment but written out with the exact commands needed. Thanks @kootenpv ;) 
@arijaycomet I'm going to close this. It's not a package issue, and if you have questions on how Python works, there are probably better resources than this bugtracker.
