### ISSUE TITLE
Connecting to Deluge with CouchPotato

### ISSUE THREAD

**Issue by mattcartlidge** [SynoCommunity/spksrc#2050]
Hi

Not sure if this is a bug since Deluge is still in BETA but I cannot for the life of me connect to Deluge using CouchPotato. I've tried all sorts of username/password/IP/port combos but nothing - connection just fails. I'm using the latest version of DSM on a Synology 1515+.

Thanks,

Matt.

**Comment by Dr-Bean** [comment]
Set up an account in Deluge first. Read the documentation on how to do that here: http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient#AddUsertotheauthenticationfile. 
https://github.com/SynoCommunity/spksrc/issues/1940 may have some information as well.

**Comment by mattcartlidge** [comment]
Yes, that did the trick, thanks. Bit of a learning curve as I had to figure out how to edit files that are not accessible using the normal shares in my Synology but I got there in the end. What a shame that Deluge users cannot be added using the GUI - I suspect this is a stumbling block for a lot of users who just expect it to work.

**Comment by Diaoul** [comment]
Deluge is quite an advanced Bittorent client. Maybe we can help with a wizard?

**Comment by mattcartlidge** [comment]
A wizard would help. It's great that it's advanced, but if the simple functions aren't there then the user base becomes much smaller. I'm a technical person and nearly gave up - I started using Transmission instead.

**Comment by Diaoul** [comment]
Transmission does the job. Personnaly I don't need the advanced features of Deluge.

**Comment by mattcartlidge** [comment]
The reason I tried to move to Deluge is because I couldn't get magnet links working in Transmission - and still can't for some reason so I scrapped it.

**Comment by Dr-Bean** [comment]
Deluge is intended for relatively advanced users, and is centered around local configuration files and whatnot. Iirc, the developers have rejected requests to make the auth file accessible from the interface and you could argue that's a good thing.
I considered a wizard, but I'm not so sure that's the right thing to do in this case. I could imagine something like allow a string in the format of `user:pass:authlevel` to be passed from the wizard to the auth file (with or without turning remote access on), but explaining all that in a wizard...hm.

**Comment by Dr-Bean** [comment]
btw...magnet links should not be a problem for Transmission, via the interface works fine. Maybe there's a bug in passing the links from CP to Transmission?

**Comment by meffect** [comment]
I use deluge because it's the only one that has a decent chrome link capture funnel extension. i wouldn't bother with a gui. people need to learn command line

**Comment by Dr-Bean** [comment]
Well, I agree that a wizard is not the best fit, but made an attempt to cram this into the wizard anyway.

I don't want to ask users to enter the final string themselves, there's no way to properly explain that in the limited space (hyperlinks don't work, in case that comes up).

So the alternative is to ask four questions: explicitly allow remote access (multiselect), a username (text), password (password) and authlevel (text, although multiselect is acceptable).
The issue with that is that the wizard only allows three options per page, and adding two pages to the wizard for this just doesn't make sense.

Maybe someone has a brilliant solution here, but as it stands, this won't be added.

**Comment by Dr-Bean** [comment]
..what I probably am going to do is set `HELPURL` to point to the Deluge FAQ (http://dev.deluge-torrent.org/wiki/Faq).

Maybe I can add instructions in the wizard to look at this: http://dev.deluge-torrent.org/wiki/Faq#Icantconnecttothedaemonfromanothermachine or this: http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient.

**Comment by Dr-Bean** [comment]
Done with 1079a5140b4dc0c6e495e2fbdf7caa16d7259b55 and aab71a4b05f06c204de2867a46f4214396ea52fb.
