### ISSUE TITLE
bison 2.5.1 does not create C and header output files

### ISSUE THREAD

**Issue by gernst48** [SynoCommunity/spksrc#2051]
The bison 2.5.1 for Synology 4.3 and 5.2 does not create the C and header output file.

I try to make the rpcapd daemon but the bison is not working.

$ bison -V
bison (GNU Bison) 2.5.1

**Comment by Dr-Bean** [comment]
Please provide more details, because I have no idea what you're talking about. Why do you think that bison should create that output?

**Comment by gernst48** [comment]
Usually the bison generates from an *.y the output files cp y.tab.c y.tab.h
This is perfect working for instance on a Debian system

During the rpcapd make on a Debian system the following happens:
bison -y -p pcap_ -d grammar.y
cp y.tab.c grammar.c
cp y.tab.h tokdefs.h

But on Synology there is no output at all.
I have tried everything, but there is no at all.

On Synology following happens:
bison -y -p pcap_  grammar.y
make: *** [grammar.c] Broken pipe

I have also tried this in a test directory only with the grammar.y file
on Debian and on Synology. Again on Debian the two files are
generated on Synology nothing happens.

Please try it with any *.y file or if you like I could send
you the grammar.y file.

**Comment by Diaoul** [comment]
Why would you want to run Bison on a Synology NAS anyway? What would you do with the generated .h and .c? There is no compiler on the Synology NAS itself.

**Comment by gernst48** [comment]
Totally wrong, I have running the GNU c compiler and all other tools from the SynoCommunity.
Look at the http://ipkg.nslu2-linux.org/feeds/optware/syno-i686/cross/unstable
there are all the tools located.

**Comment by Diaoul** [comment]
This is not SynoCommunity's work. It's optware's.

**Comment by gernst48** [comment]
Yea, your are right, I was fooled by a wrong web link. Sorry.

**Comment by Dr-Bean** [comment]
If you were to use spksrc instead of optware/ipkg, you'd probably have less issues with creating the package ;)
Anyway, closing.
