### ISSUE TITLE
Selfoss and tiny tiny rss don't launch after install

### ISSUE THREAD

**Issue by reyman** [SynoCommunity/spksrc#2052]
Hi, since the update to dsm 6 beta, selfoss and tiny tiny rss won't launch.

I can provide any details here which can help you to debug.

I have a syno 213+ on beta dsm 6
##

**Comment by nickbroon** [comment]
Make sure you have the most recent version of tt-rss 20160102-10
I also had to reset the list of PHP extensions to the default using the Synology Control centre.
tt-rss interface will then appear.

However I'm continuing to see a problem with tt-rss update_daemon failing: https://github.com/SynoCommunity/spksrc/pull/1976#issuecomment-169177872

**Comment by Dr-Bean** [comment]
DSM6 is currently not supported, so some packages, including these two, may present problems. If you figure out a fix, be sure to let us know/open a PR.

**Comment by haegar33** [comment]
"currently not supported" is now valid for more than half a year for TT-RSS. If the package is no longer developed it should be removed from the repository.
For TT-TSS the "invalid SQL password" error can be solved with an additional symbolic link (described somewhere here on Github) However the update daemon is not installed with that package or simply not working.

**Comment by hgy59** [comment]
tt-rss is fixed by #4923
