### ISSUE TITLE
Download Fails from  http://packages.synocommunity.com/ for NZBGet on DSM 4.2 (DS209)

### ISSUE THREAD

**Issue by ccwillia** [SynoCommunity/spksrc#2053]
Every time i try to download NZBGet from the synocmmunity i get a download failed message.  I am using a DS209 upgraded to DSM 4.2

**Comment by Diaoul** [comment]
I moved SynoCommunity behind the CloudFlare CDN. DNS transition is ongoing but everything should work. Please retry in a few moments.

**Comment by ccwillia** [comment]
Ok, from the logs i am getting a 403.  I try again in 10-15min

**Comment by ccwillia** [comment]
It is still failing to download

**Comment by Diaoul** [comment]
I don't think the repo supports DSM 4.2 actually.

**Comment by ccwillia** [comment]
I have downloaded other packages from the synocommunity before

**Comment by ccwillia** [comment]
I get 403's for all the package icons as well

Jan  6 23:18:10 geticon.cgi: pkgcurltool.cpp:458 http://packages.synocommunity.com/homeassistant/1/icon_72.png, Failed to request packages, httpResponseCode=403

**Comment by Diaoul** [comment]
Sorry, 4.2 is supported, 4.1 isn't. The URL you linked works for me and it seems it works for others too as you're the only one reporting that issue. Is the website working? Do you have a particular setup?

**Comment by ccwillia** [comment]
yes, i can access the website and the url i posted from my browser but not from package center   In the easy setup,  step 1 mentions setting the trust level.  4.2 doesn't have a trust level option in package center settings.  i checked with my brother who also has downloaded packages from synocommunity in the past and is also using ds209+ 4.2  and he experiences the same.

**Comment by ccwillia** [comment]
Since i am still unable to connect to synocommunity from my package manager is it possible to download the package and install it manually?  I have the DS209+ which is the ppc853 arch

**Comment by dsopik** [comment]
I am also having the same problem with a DS209 with DSM version 4.2.  I am trying to load COPS,  and I have tried other packages but they all fail.  Also, all of the icons for the packages do not show up.  I have loaded COPS in the past, but I am rebuilding my nas from scratch, and I can no longer load it.

**Comment by mgroenendijk** [comment]
Same here. Also DSM 4.2 and DS209. Last week i was able to download and since 2 days it's not working anymore.

**Comment by ccwillia** [comment]
Any updates?

**Comment by Dr-Bean** [comment]
If you're in a hurry, then you're probably best off with compiling the packages yourself. Otherwise, you'll have to wait until Diaoul has time to look into it.

**Comment by ccwillia** [comment]
I was able to get everything setup, but when i run "make nzbget" it gives me an error on unrar and i confirmed i have unrar installed.  I appears like it might be running unrar without passing in the parameters

"make[3]: *** [unrar] Error 7"

**Comment by ccwillia** [comment]
Looking at the toolchains i don't see one for ppc853x 4.2.  I have the DS209+ which uses ppc853x but can't not be upgraded beyond DSM 4.2.  Did  the toolchains change late last year because I have used the packages from synocommunity in the past

**Comment by RichBradshaw1** [comment]
I'm having this issue too. Only started using the repo over Christmas and New Year while I had some time to myself. I'm using a HP MicroServer with Synology software on it. Isn't working now, and I don't get the icons either.

If the filter works on the user agent, can it be relaxed a little to allow older versions? It was working at the beginning of January, what's changed?

Thanks,
Rich

**Comment by Diaoul** [comment]
The only thing that's changed is that I switched to CloudFlare's CDN last week to handle the traffic and do some caching to offload the server.
No other change has been made on the server side.
I'm not sure what's wrong here, I'm looking into it but it may take some time.

**Comment by RichBradshaw1** [comment]
Thank you for taking the time, much appreciated. Odd that it was all working OK previously. If there's anything I can do to help, let me know...

**Comment by Ronvanloo** [comment]
Hello
I have a DS109J using DSM 4.2-3255 
I can't install the http://packages.synocommunity.com community. 
When I click OK I got the message: "Save failed. Please try again later"
Maybe this has to do with the same problem described here.

Thanks Ron.

**Comment by ccwillia** [comment]
I checked my model again and i actually have the ds209 not the ds209+.  I was able to build and install using the nzbget package with the 88f6281-4.3 arch.

**Comment by Amelandbor** [comment]
DS409 - DSM 4.2-3255

PkgSynoMan.cgi: PkgSynoMan.cpp:342 Failed to download package, httpResponseCode=403

**Comment by Diaoul** [comment]
OK so you can see the packages but not download a package? Or do you see the list of packages? I can't find the exact request made by a DSM 4.2 NAS to a package server. @piwi82: do you remember the query?

**Comment by piwi82** [comment]
There is no trace of requests from a DS209 in `/var/log/nginx/access.log` on the server.
I have found the following request in an old log file :
```
[09/Oct/2014:01:11:33 +0200] "POST / HTTP/1.1" 200 26146 "-" "\x22Mozilla/4.0 (compatible; MSIE 6.1; Windows XP)\x22" "package_update_channel=stable&unique=synology_88f6281_209&build=3248&language=fre&major=4&arch=88f6281&minor=2&timezone=Brussels"
```
Does the repository still support `POST` requests ? Is there any filter an the `user-agent` ?

**Comment by Diaoul** [comment]
Yes it does. This command works for me:

    http -f POST http://packages.synocommunity.com User-Agent:"\x22Mozilla/4.0 (compatible; MSIE 6.1; Windows XP)\x22" package_update_channel=stable unique=synology_88f6281_209 build=3248 language=fre major=4 arch=88f6281 minor=2 timezone=Brussels

Can any of you try that command? You will need httpie (curl for humans, `sudo apt-get install httpie`)

**Comment by Diaoul** [comment]
I just lowered the security firewall from CloudFlare, I had a lot of "bad browser threats" which I suspect is the issue here due to the way the request to the package server is issued on old DSMs. Give it one hour and try again please.

**Comment by RichBradshaw1** [comment]
@Diaoul the http -f command works I believe.
Installed httpie and appended > results.txt onto the end of the "http" command. Looks like it returns a JSON results set - is that right? My results.txt attached.
[results.txt](https://github.com/SynoCommunity/spksrc/files/87989/results.txt)

**Comment by Diaoul** [comment]
Yes it's OK. I don't get why it wouldn't work from the NAS. We may be missing some HTTP headers or something (maybe User-Agent isn't properly bloated with unicode characters using httpie).
If you can, record the requests made by your NAS to the package server with Wireshark or similar and output here the exact request. The one we get from the nginx logs is far from a complete HTTP request.

**Comment by RichBradshaw1** [comment]
OK, still working my way through the Wireshark capture, found the HTTP list made when looking through the packages, the link passed back in the packages list is as follows:
         "link" : "https://packages.synocommunity.com/headphones-custom/4/headphones-custom.v4.f1594%5Bnoarch%5D.spk?build=4458&arch=bromolow",\n

I'm looking for the conversation when I try to download something and grab the request made.

**Comment by RichBradshaw1** [comment]
If I use Chrome to download using the link provided by WireShark, it seems to work ok. However, doesn't work within the NAS still. Can't find the header info within WireShark - not sure if its because its a HTTPS link.

**Comment by Erci76** [comment]
Hello, im a ds109 user, i have same problem here. 

Old situation: DS 109 with DS 4.2 (4.2-3255) HD Barracuda 500 Gb, be able to install nzbget, etc 
New situation: DS 109 with DS 4.2 (4.2-3255) HD 2TB, not be able to install nzbget, error message "failed to download". Images/icons of repository (packages.synocommunity.com) are also not loaded.403 message.

**Comment by arjen9551** [comment]
Same issues here. Tried reinstalling Sickrage yesterday (and updating Python + Git), but none of the packages seem to work. Reboot also did not fix it. 
Synology DS209+II with DSM 4.2-3252

**Comment by Diaoul** [comment]
I changed another setting in CloudFlare. Please tell me if that works now.

**Comment by Amelandbor** [comment]
It's working, thanks a lot @Diaoul

**Comment by arjen9551** [comment]
I can also confirm it is working again. Thanks a lot!

**Comment by dsopik** [comment]
I can also confirm it is working again. Thank you!

**Comment by Ronvanloo** [comment]
I still have the problem that I can't add http://packages.synocommunity.com/ as a community on the Synology DS109J. I got the message: Error saving, try again later
Can someone confirm if this community string doesn't work on this type of Synology.
I use DSM 4.2-3252

**Comment by Erci76** [comment]
should https://packages.synocommunity.com also work ?  or it must be http request?

**Comment by Ronvanloo** [comment]
That link also gives the same error message.

**Comment by Diaoul** [comment]
This URL is for the NAS only. Try deleting all your other package sources and adding only SynoCommunity.
There is no reason it shouldn't work for you if the problem is fixed for others.

**Comment by Erci76** [comment]
its working, DS109, DS 4.2-3255

**Comment by RichBradshaw1** [comment]
Confirmed working for me too. Thank you very much for resolving. Much appreciated, donation on its way.

**Comment by Ronvanloo** [comment]
I still can't add this package source to my DS109.
I deleted all other the other package source.
I also change the language of the management console to English.
I restarted the DS109 but I still got the message:

![clipboard01](https://cloud.githubusercontent.com/assets/16646807/12354081/cbb6dc56-bb93-11e5-9bd2-d0a8e502b4fc.jpg)

**Comment by Erci76** [comment]
@Ronvanloo try without last slash (/) ?
![working](https://cloud.githubusercontent.com/assets/16699523/12354353/a4c35c3a-bb95-11e5-8710-45a63f9f5dd6.png)

**Comment by Ronvanloo** [comment]
I tried with and without http:// https:// also leaving the / at the end is no option.
So I think I'm out of options at the moment.
maybe someone has an idea what is causing this problem. Otherwise everybody thanks for the help.

Regards,

Ron.

**Comment by Ronvanloo** [comment]
The only thing I can mention is that when I some random characters after .com I got the message: invalid location.

![image](https://cloud.githubusercontent.com/assets/16646807/12377258/488c213a-bd17-11e5-930b-bff29e70fc88.png)

So I think I can communicate with the source but something is prohibiting from saving.

**Comment by Erci76** [comment]
@Ronvanloo I'm using ds109 with dsm 4.2.3255, it is working here. 
You are using 4.2-3252, can you update to last firmware and try it again?

**Comment by Ronvanloo** [comment]
No I also use the 4.2.3255 firmware.

**Comment by Erci76** [comment]
This doesn't seem right. Are you able to add other packages?  (http://packages.mdevries.org/) 
If not, there must (can) be a firewall issue.

**Comment by Ronvanloo** [comment]
Yes without any problem:

![image](https://cloud.githubusercontent.com/assets/16646807/12377535/8e9c3480-bd21-11e5-888e-6fed1f513a32.png)

I see the packages but I can't install them because I need python and this is to donwload at synocommunity.

**Comment by sgorchichko** [comment]
Same issue for me on DS209j. Can't save repo. :(

**Comment by piwi82** [comment]
@sgorchichko : Have you tried to [remove all third-party repositories](https://github.com/SynoCommunity/spksrc/issues/2053#issuecomment-171661156) before adding SynoCommunity's ?

**Comment by sgorchichko** [comment]
@piwi82 Yes, actually I have had SynoCommunity repo added before but accidentaly removed it. It was the only repo I had. But when I tried to re-add it I got the error above.

**Comment by Ronvanloo** [comment]
Today I did a complete reset of the Synology and installed DSM 4.2 fresh on the DS109j.
The first thing I did was adding the community SynoCommunity  but again I got the message "Save failed. please try again later"

I think this was the last option I had for trying to add this community.

**Comment by Diaoul** [comment]
If anything it's network related.

**Comment by Ronvanloo** [comment]
That could be a possibility. Therefore I connected my DS109j at a friend of mine to his network.
There I got the same error. 
At home I also changed my network and used another modem/router and I still have the same problem.
Maybe this community string can't be added on a Synology when it has a j in his name. Because @sgorchichko also has a Synology j type.

**Comment by punkrockjack** [comment]
I too can't install from http://packages.synocommunity.com/
It lists the packages, but says that the download failed. It used to work fine.

I'm on a DS415+, running DSM 5.2-5644 Update 5

**Comment by wurz72** [comment]
I had this exact issue and it turned out to be a DNS problem.

I ssh'd into my DS211(note I don't have a "J" model) and tried pinging packages.synocommunity.com and got "bad address". I tried pinging google.com and got the same. (btw you need to run ping as root. How weird is that?!)

Anyhow, I checked the network settings in DSM and the DNS server was set to an IP address from my old ISP. I had just switched to a new provider. So I updated the DNS server to the IP address of my router. This fixed the issue and I was able to add the repository and see packages.

**Comment by Ronvanloo** [comment]
Thanks for keeping this thread alive.
I used telnet to connect to my Synlogy.
From there I did a ping to google.com and packages.synocommunity.com
Both replied to me. So I think DNS is not the problem.
I think this is a problem using a DS109J
