### ISSUE TITLE
package with kernel modules

### ISSUE THREAD

**Issue by guenneguezt** [SynoCommunity/spksrc#2055]
Hy,

Is it possible to define in Makefile a DEPENDS module to be able to cross compile it ?

Thanks
Thomas

**Comment by Dr-Bean** [comment]
Sure. There are two open Domoticz PR's, one (or both) add a kernel module that way, although they might not be 100% correct. Take a look at them for inspiration ;)

**Comment by guenneguezt** [comment]
Have you got a like ? I search but doesn't find it...
Thanks
Thomas

**Comment by Dr-Bean** [comment]
https://github.com/SynoCommunity/spksrc/pull/1612 and https://github.com/SynoCommunity/spksrc/pull/1769. cross/cp210x is the package you're looking for. Note the comment from Diaoul in the second link: that might need fixing.
