### ISSUE TITLE
http://packages.synocommunity.com returns "400 Bad Request"

### ISSUE THREAD

**Issue by rugaard** [SynoCommunity/spksrc#2063]
It looks like the URL you need to enter as a package source in DSM:
http://packages.synocomunnity.com is down.

Currently no packages appear in the "Package Center" when adding that URL as a source. And when trying to open the URL in the browser you receive a "400 Bad Request".

Thought it might have been a glitch with the server or something like that, but it has been like this since after Christmas.

Hopefully someone knows what to do. If you need more info or need me to test stuff, please let me know and I'll provide it or test it :)

Thanks in advance and thank you for a lovely job!

**Comment by Dr-Bean** [comment]
That URL is not meant for your browser. Use https://synocommunity.com for that.

As for packages not showing up, please provide model and DSM version. If you have any other repositories added in Package Center, remove them and try again.

**Comment by rugaard** [comment]
Geez, I feel like a moron. Never trust copy/pasting from articles.

When I removed my existing (and misspelled source) and added the one in from your site it worked perfectly. All packages showed up :flushed: 

Sorry for the (embarrassing) inconvenience. And again thank you for an amazing job! :sunglasses: :+1:
