### ISSUE TITLE
tvheadend-testing 4.1.988-1 doesn't display web page

### ISSUE THREAD

**Issue by botazefa** [SynoCommunity/spksrc#2067]
I'd previously had regular tvheadend installed and the web interface worked well.  I uninstalled it and manually installed the 4.1.988-1.  When I try to load the web page, I do get the authentication dialogue for username/password, but the web page is then completely blank.  I've tried on firefox/linux and explorer/windows. Same result.  I'm no web expert, but the firefox developer console shows this, which leads me to believe I've hosed the install somehow.  Pointers appreciated!

SyntaxError: illegal character locale.js:1:0
SyntaxError: illegal character tvh.js.gz:1:0
ReferenceError: Ext is not defined
 extjs.html:8:1

**Comment by Dr-Bean** [comment]
There's no tvheadend-testing package on our repository. Please ask the developer of that package for support.
