### ISSUE TITLE
Better Transmission Fork

### ISSUE THREAD

**Issue by pigr8** [SynoCommunity/spksrc#2069]
can we please add this transmission fork https://github.com/cfpp2p/transmission and use this a custom transmission package? it's way better that the stock 2.84 version, it's based on 2.77 and has fixed issues and more functionality.

or maybe someone can address me how to cross compile it (bromolow).

**Comment by Dr-Bean** [comment]
The owner seems to state that it is experimental here: https://trac.transmissionbt.com/ticket/532#comment:219. I think we'll stick with stable.

To compile it yourself, start by reading the README. Set up a Debian x86 VM or use the spksrc Docker container. You'll want to change the code related to cross-compiling Transmission (download site and whatnot), so for starters, look at `cross/transmission`.

**Comment by Diaoul** [comment]
We won't package this. This is too specific, you can compile it yourself quite easily.
