### ISSUE TITLE
Compiling tesseract but no SPK

### ISSUE THREAD

**Issue by artelse** [SynoCommunity/spksrc#2078]
I compiled Tesseract-ocr and its dependencies fine, but no `spk` shows up in `spksrc/packages`. Or do I need to manually do a `make install`?

**Comment by cytec** [comment]
tesseract-ocr is only available in cross you need to create a package in spk to use it... see pyload for example (which is the only spk useing it afaik)

**Comment by artelse** [comment]
Got it, thanks! Will get back when that works out ok.
