### ISSUE TITLE
Connect to Deluge from Windows Client

### ISSUE THREAD

**Issue by orhanck23** [SynoCommunity/spksrc#2079]
Hi,

I set-up Deluge on my Synology, I like the webui but I prefer the Windows client, when I try to add my Synology IP address to "Connection Manager", along with the username and password specified in the /var/auth file - it shows as offline, can't connect. I'm aware that it's a better, could it be that it isn't supported yet?

Many thanks Dr-Bean!

**Comment by Dr-Bean** [comment]
Just to make sure, have you seen (and followed) https://github.com/SynoCommunity/spksrc/issues/2050#issuecomment-169603283 or https://github.com/SynoCommunity/spksrc/issues/1940?
You didn't specify if you actually added a user, but if you're trying to use the `local` user (or whatever the first entry is in that file), that probably won't work.

**Comment by orhanck23** [comment]
Ahh yes I was trying to use the local user, got it working now!

Thank you Dr-Bean!
