### ISSUE TITLE
Autostart Deluge on Boot

### ISSUE THREAD

**Issue by orhanck23** [SynoCommunity/spksrc#2081]
I was wondering if there was a way to automatically login into deluge webui when the Synology boots,
I'm aware of an ubuntu init.d script pointed here http://dev.deluge-torrent.org/wiki/UserGuide/Service/DebianUbuntuInitd.

But is there a way for a Synology?

Thanks Dr-Bean!

**Comment by Dr-Bean** [comment]
I don't understand your question. The script you refer is an init script for Ubuntu, it doesn't handle logins.

The two (Deluge daemon and the web ui) don't have a direct link (as is the case with e.g. Transmission). You'll always have to tell the ui which daemon it should connect to. On top of that, setting a password before allowing access is common sense, especially if you plan to allow external access.
