### ISSUE TITLE
Repo down? Bad request?

### ISSUE THREAD

**Issue by eikum** [SynoCommunity/spksrc#2083]
Hi,

I get this error when trying to access 
http://packages.synocommunity.com

Bad Request

The browser (or proxy) sent a request that this server could not understand.

**Comment by piwi82** [comment]
https://synocommunity.com/#easy-install

**Comment by Diaoul** [comment]
https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#im-seeing-a-400-bad-request-the-browser-or-proxy-sent-a-request-that-this-server-could-not-understand
