### ISSUE TITLE
Rutorrent: Add RapidSSL certificate

### ISSUE THREAD

**Issue by Zizit25** [SynoCommunity/spksrc#2084]
Hi All,
I just want to inform, that some private trackers have changed their SSL certificates.
Is it possible to add RapidSSL SHA256 or GeoTrust to the list of cacert.pem file inside RuTorrent?
Thanks

**Comment by GoodOmens83** [comment]
@Zizit25 Can you point me to the cert and I can add it.

Thanks!

**Comment by Zizit25** [comment]
Hi @GoodOmens83,
I think these links can help you :

https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&id=SO26457
OR
https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&actp=CROSSLINK&id=SO26459

Thanks

**Comment by Dr-Bean** [comment]
Before doing anything here, please ensure the appropriate cert isn't already included in cert.pem provided by `cross/curl`. 
In the current released rutorrent package, it's quite likely that cacert.pem from Synology is still used (stored in `/etc/ssl` or whatever the location is), which has an unknown update schedule and is likely to be outdated.

**Comment by GoodOmens83** [comment]
@Dr-Bean 

The install src for ruTorrent contains a cacert.pem file which rtorrent uses `http_cacert = /usr/local/rutorrent/etc/cacert.pem` - not the one provided by openssl.  I can see about using the one provided by openssl?  It has the rapidssl cert.

**Comment by Dr-Bean** [comment]
I would suggest to use `cert.pem` which is added when `cross/curl` is compiled. It's in the root of the package dir. That way, we have full control over it.

**Comment by GoodOmens83** [comment]
@Dr-Bean Do you know if openssl cert gets copied/placed anywhere on the synology device or should I just copy it to `rutorrent/src` directory from the openssl work directory via the Makefile and update .rtorrent.rc to use that instead?

**Comment by Dr-Bean** [comment]
Probably a misunderstanding here. Openssl doesn't produce certs, so there's nothing to copy. I'm talking about this: https://github.com/SynoCommunity/spksrc/blob/master/cross/curl/Makefile#L30.
Seeing as curl is one of the dependencies of rtorrent, a `cert.pem` is already available in the package, and I assume that includes the requested cert.
The thing that's missing is to tell rutorrent to use that instead of the current cacert.pem in /usr/local/rutorrent/etc/cacert.pem.

(Note that this also requires further cleanup, e.g. removing the outdated `cacert.pem` from the rutorrent package, rewriting the config for existing packages and whatnot before it can be accepted in a PR)

**Comment by GoodOmens83** [comment]
So:
- remove cacert.pem from github (and the corresponding install line)
- the openssl generated cert.pem is already installed in `/usr/local/rutorrent` - do you want me to update `.rtorrent.rc` to use this or just ln -s `/usr/local/rutorrent/etc/cacert.pem /usr/local/rutorrent/cert.pem` for compatibility sake (or just mv the cert.pem to etc/cacert.pem)?

**Comment by Dr-Bean** [comment]
Yes, update `.rctorrent.rc` for sure.

We don't want to move around or symlink cert.pem to somewhere else, because we'd need to keep doing that with every update. For upgrading existing installations, we can do something in preupgrade, like this (untested!):
```
# Revision 8 introduces backward incompatible changes
    if [ `echo ${SYNOPKG_OLD_PKGVER} | sed -r "s/^.*-([0-9]+)$/\1/"` -le 8 ]; then
        sed -i -e "s|http_cacert = *|http_cacert = $(INSTALL_DIR)/cert.pem|g" $(INSTALL_DIR/var/.rtorrent.rc
    fi
```

**Comment by Dr-Bean** [comment]
Done with 415a9b1e9a702adf87ae8e24c1c594c34ba54a85
