### ISSUE TITLE
Ghostscript?

### ISSUE THREAD

**Issue by artelse** [SynoCommunity/spksrc#2086]
Has anyone tried to compile Ghostscript? I want to use it in combo with Tesseract/ Leptonica to OCR pdf files. I tried the version on ipkg but that is old and results in a segmentation error. Hints anyone?

**Comment by artelse** [comment]
Am giving compiling gs a go. First issue:
`Running libtiff configure script...
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu`
This seems to indicate gs or libtiff is not being cross compiled? How can I fix this? I tried to put `--host` in configure in the Makefile, but no avail.

**Comment by Dr-Bean** [comment]
If the build process for GS is setup correctly, then it should pass on the necessary compile flags and whatnot to the dependencies. If it doesn't, you'll probably need to patch the code so that it does.

**Comment by artelse** [comment]
Thanks for the response! But I moved to a debian-chroot installation and am having much more success.
