### ISSUE TITLE
Invalid location when adding the repo

### ISSUE THREAD

**Issue by NMBrux** [SynoCommunity/spksrc#2089]
I deleted the repo from my DS412+ while trying to troubleshoot the damn sickrage issues and now I cannot add it again. I keep getting an "invalid location" message. Is the repo down or is it just me?

**Comment by Dr-Bean** [comment]
Just you ;) Remove all the third-party repositories, then add just ours (http://packages.synocommunity.com), let us know if that works.

Could you please add your DSM version?

**Comment by NMBrux** [comment]
No other repos added. Problem persists. I am on the latest Stable DSM. I will try again tonight when I go home.

**Comment by tomdbpost** [comment]
Same problem here with the Synology DS216, also running the latest stable DSM. Will try the sollution @Dr-Bean added here tonight aswell.

**Comment by tomdbpost** [comment]
@Dr-Bean Unfortunately the solution did not work. Still got the "invalid location" message. Is this due to post #2033? Is there a way I could help to get Synocommunity working on the DS216?

**Comment by Dr-Bean** [comment]
@tomdbpost Yes, the 216 model is not yet supported in spksrc. Further discussion on this subject should be kept in #2033.

**Comment by NMBrux** [comment]
Ok problem solved. I couldn't add the repo as long as I was behind my VPN. After I disconnected the VPN I managed to add the repo.

**Comment by Dr-Bean** [comment]
Thanks for letting us know.
