### ISSUE TITLE
[Request] FlexGet update fail.

### ISSUE THREAD

**Issue by iruyanka** [SynoCommunity/spksrc#2091]
How to update flexget?

 Failed building wheel for regex
  Running setup.py clean for regex
Failed to build regex
Installing collected packages: regex, rebulk, guessit, SQLAlchemy, flask-login, pytvmaze, FeedParser, futures, tzlocal, apscheduler, webassets, flask-assets, cssmin, functools32, jsonschema, flask-restplus, enum34, pathlib, pyScss, html5lib, beautifulsoup4, requests, cherrypy, ordereddict, path.py, flexget
  Running setup.py install for regex ... error
    Complete output from command /usr/local/flexget/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fxfrxR/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wFqrql-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/flexget/env/include/site/python2.7/regex:
    /usr/local/flexget/env/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '2016.01.10' to '2016.1.10'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying Python2/regex.py -> build/lib.linux-x86_64-2.7
    copying Python2/_regex_core.py -> build/lib.linux-x86_64-2.7
    copying Python2/test_regex.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_regex' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/Python2
    /spksrc/toolchains/syno-x64-5.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -fno-strict-aliasing -I/spksrc/spk/python/work-x64-5.2/install//usr/local/python/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/python/include/python2.7 -c Python2/_regex.c -o build/temp.linux-x86_64-2.7/Python2/_regex.o
    unable to execute '/spksrc/toolchains/syno-x64-5.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc': No such file or directory
    error: command '/spksrc/toolchains/syno-x64-5.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/flexget/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fxfrxR/regex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wFqrql-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/flexget/env/include/site/python2.7/regex" failed with error code 1 in /tmp/pip-build-fxfrxR/regex

**Comment by Dr-Bean** [comment]
The challenge here is that the latest versions of Flexget are using one or more Python libraries that need to be compiled, whereas in the past Flexget was pure-python. `Regex` is one of those libraries.

From an spskrc perspective, that means you need to cross compile it. Set up a development environment. Take a look at the README for instructions.

Then, add a cross-package for the `regex` project (see for example the [Mercurial cross package](https://github.com/SynoCommunity/spksrc/tree/master/cross/mercurial), which is similar in setup.

Lastly, you'll need to add it to the `BUILD-DEPENDS` of the Flexget SPK , along with Python and some other necessary dependencies. Take a look at the [Mercurial SPK package](https://github.com/SynoCommunity/spksrc/blob/master/spk/mercurial/Makefile#L6). You can then recompile Flexget for you architecture.

**Comment by Diaoul** [comment]
Or we can add it to the Python SPK so we can keel FlexGet as a noarch package. It seems like a popular package.

**Comment by Dr-Bean** [comment]
Have to check if there are more packages like it though, but otherwise, you've got a point ;)
It would help to keep Flexget noarch...

**Comment by iruyanka** [comment]
@Diaoul Please add FlexGet of Python SPK.

Before I used command. It is module on pypi.
/usr/local/flexget/env/bin/pip install --upgrade flexget

An error occurs in the latest version.

**Comment by Dr-Bean** [comment]
Quick look: PyYAML, pyScss with optional C-code, regex, SQLAlchemy (already part of Python SPK)

@iruyanka Flexget won't be added to the Python SPK. Diaoul suggested to include (just) the regex module, nothing more.

**Comment by iruyanka** [comment]
@Dr-Bean OK. Sorry.
I want to use FlexGet latest version with no problem.

**Comment by Mirgolth** [comment]
Subscribing to the thread as I was coming to get help for the same issue.

**Comment by liiight** [comment]
This is due to an upgrade to guessit with flexget imports by default. Related to this: https://github.com/guessit-io/guessit/issues/257

We plan to remove that dependency very soon regardless of that pending fix

**Comment by Toilal** [comment]
I've just release guessit-2.0rc8 that makes regex native module optional, so it should work now. There's still something wrong with subliminal plugin users, because subliminal still use guessit 1.x. I'll try to upgrade subliminal to guessit 2 in the next few days, stay tuned :)
