### ISSUE TITLE
configure: error: cannot run C compiled programs

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#2094]
I'm trying to compile TVHeadend for DS211 (88f6281) and DS715 (alpine) and it keeps giving me this error:

configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.

http://pastebin.com/yikH857C

I checked config.log and found this:
configure:3758: ./conftest
./configure: line 3760: ./conftest: cannot execute binary file: Exec format error
configure:3762: $? = 126
configure:3769: error: in `/home/openelec/github/test/spksrc/spk/tvheadend-testing/work-alpine-5.2/tvheadend-testing-git045f739/build.linux/ffmpeg/yasm-1.3.0':
configure:3771: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.

I'm breaking my head on this. I think i have seen such before but can't find any info or solution for it.

**Comment by Diaoul** [comment]
Have you set `GNU_CONFIGURE = 1` in your cross makefile?

**Comment by schumi2004** [comment]
Yeah it's there.

I think TVH source has changed something related to yasm (1.3.0)
Version 4.1.1334 works just fine but higher versions fail on yasm.

I know it's a huge version difference but if my memory is correct I have seen such error before but can't recall how to solve it.

**Comment by schumi2004** [comment]
Seems TVH defs tried to compile ffmpeg on their own, no need to compile ffmpeg again.

Issue solved, thanks ;)
