### ISSUE TITLE
Upgrade EJABBERD package from version 2 to the current version which is 16.01

### ISSUE THREAD

**Issue by askpatrickw** [SynoCommunity/spksrc#2095]
The ejabberd package is version 2, but the current version is 16. 
I can only imagine how many security related fixes there are between those two versions. How do we upgrade that? Is there something the general community can help with?

Thanks
##

**Comment by Dr-Bean** [comment]
The situation is slightly less alarming ;) Ejabberd v2's codebase is not the same codebase as subsequent versions. Support for v2 continued while the new codebase, from which v16 stems, became mature. 
Support is discontinued now, and has been for a while, but I would be surprised if there were large security issues with v2.

I have looked into packaging a current Ejabberd version, but it's a huge pain and a lot of work. There are a lot of dependencies included in the main package, and each has to be split off into its own package for cross-compiling. Very slow going...

**Comment by W7PEA** [comment]
Thanks for the reply. That does sound better than I had feared. It does look like there are a couple of vulns that people should be aware of related to the ssl code just getting old.

  https://www.cvedetails.com/vulnerability-list/vendor_id-4455/product_id-7709/version_id-153998/Process-one-Ejabberd-2.1.12.html

**Comment by oli-oli** [comment]
I'm joining to this request, also looking for an update of eJabberd Server package for ours Synology...

Regards,
Oli.

**Comment by teihoo** [comment]
I would be also happy to see latest release of ejabberd on Synology. Hope someone will be able to get through the painstaking job :)

**Comment by hgy59** [comment]
@teihoo, @oli-oli, @askpatrickw
#4333 provides now working packages of ejabberd 21.01.

**Comment by teihoo** [comment]
Sweet! Thank you for this, I'll try setting it up this weekend.

**Comment by hgy59** [comment]
@teihoo did you have a chance to test this?

**Comment by teihoo** [comment]
> @teihoo did you have a chance to test this?

I did it installed fine and it works to login. I had issues with setting up admin account and further configuration, as it was hitting me with login prompt on virtual servers and admin login didn't work. I need a bit more time trying to get it setup.
