### ISSUE TITLE
PPC: EFD_CLOEXEC not declared

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2096]
I am trying to build Pulseaudio but PPC "complains" with error `EFD_CLOEXEC not declared`.
It looks it is related to `sys_eventfd`. Probably it assumes it is active for PPC (maybe because of the host?).
Anyone can help/advice?

**Comment by vkostas** [comment]
All 5.2 TCs have `EFD_CLOEXEC` definition available in `sys/eventfd.h` (directly or indirectly by using `bits/eventfd.h`) EXCEPT *`qoriq-5.2`*.

>syno-monaco-5.2/work/arm-cortexa9hf-linux-gnueabi/arm-cortexa9hf-linux-gnueabi/sysroot/usr/include/bits/eventfd.h
>syno-avoton-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/include/bits/eventfd.h
>syno-avoton-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include/bits/eventfd.h
>syno-x64-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/include/bits/eventfd.h
>syno-x64-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include/bits/eventfd.h
>syno-evansport-5.2/work/i686-pc-linux-gnu/i686-pc-linux-gnu/sys-root/include/sys/eventfd.h
>syno-evansport-5.2/work/i686-pc-linux-gnu/i686-pc-linux-gnu/sys-root/usr/include/sys/eventfd.h
>syno-armada370-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/include/sys/eventfd.h
>syno-armada370-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/thumb2/usr/include/sys/eventfd.h
>syno-armada370-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include/sys/eventfd.h
>syno-braswell-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/include/bits/eventfd.h
>syno-braswell-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include/bits/eventfd.h
>syno-x86-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/include/bits/eventfd.h
>syno-x86-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include/bits/eventfd.h
>syno-cedarview-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/include/bits/eventfd.h
>syno-cedarview-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include/bits/eventfd.h
>syno-88f6281-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/include/sys/eventfd.h
>syno-88f6281-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include/sys/eventfd.h
>syno-bromolow-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/include/bits/eventfd.h
>syno-bromolow-5.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include/bits/eventfd.h
>syno-armada375-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/include/sys/eventfd.h
>syno-armada375-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/thumb2/usr/include/sys/eventfd.h
>syno-armada375-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include/sys/eventfd.h
>syno-alpine-5.2/work/arm-cortex_a15-linux-gnueabi/arm-cortex_a15-linux-gnueabi/sysroot/usr/include/bits/eventfd.h
>syno-armadaxp-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/include/sys/eventfd.h
>syno-armadaxp-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/thumb2/usr/include/sys/eventfd.h
>syno-armadaxp-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include/sys/eventfd.h
>syno-comcerto2k-5.2/work/arm-cortexa9-linux-gnueabi/arm-cortexa9-linux-gnueabi/sysroot/include/bits/eventfd.h
>syno-comcerto2k-5.2/work/arm-cortexa9-linux-gnueabi/arm-cortexa9-linux-gnueabi/sysroot/usr/include/bits/eventfd.h

Is it possible Synology has provided a "broken" TC for Qoriq?

**Comment by vkostas** [comment]
Went even further.
I included `#include <bits/eventfd.h>` to qoriq-5.2 `sys/eventfd.h` (same way as the working TCs).
It compiles now.
@Diaoul Is it "allowed" to amend standard synology toolchain with small patches or it is a strict rule to not touch them?
I.e. toolchains/syno-qoriq-5.2/patches
>`--- powerpc-none-linux-gnuspe/include/sys/eventfd.h	2016-01-26 13:33:27.325627641 +0100`
>`+++ powerpc-none-linux-gnuspe/include/sys/eventfd.h	2016-01-25 20:42:40.806853546 +0100`
>`@@ -20,6 +20,7 @@`
>` #define	_SYS_EVENTFD_H	1`
>` `
>` #include <stdint.h>`
>`+#include <bits/eventfd.h>`
>` `
>` /* Type for event counter.  */`
>` typedef uint64_t eventfd_t;`

Of course the question then might be: will the package work in the real NAS of the patched TC?
I loged a synology support ticket. Hopefully they will advise.

**Comment by Diaoul** [comment]
Yes it is allowed to do that. Fixing the toolchain is sometimes required.

**Comment by Diaoul** [comment]
Of course what matters is that the compiled binary works fine on the target device so you might need users to confirm that for you.

**Comment by vkostas** [comment]
Thank you.
