### ISSUE TITLE
NZBGet no longer available for [ppc853x] after updating to DSM 4.2 (build 3255) on DS209+II

### ISSUE THREAD

**Issue by mr214** [SynoCommunity/spksrc#2097]
After updating my DS209+II [ppc853x] to DSM 4.2-3255, I no longer see NZBGet in the list of available packages.

NZBGet was previously installed and working before updating.  After the update it started experiencing problems so I uninstalled it and was going to reinstall to see if that would fix it.  However, it's no longer showing up in the list.

http -f POST http://packages.synocommunity.com User-Agent:"\x22Mozilla/4.0 (compatible; MSIE 6.1; Windows XP)\x22" package_update_channel=stable unique=synology_ppc853x_209 build=3255 language=enu major=4 arch=ppc853x minor=2 timezone=Chicago

**Comment by Dr-Bean** [comment]
See https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support. 
We don't publish packages for older than DSM 5.0 by default. As time goes by, more and more packages will get updated, and that means that packages for unsupported DSM versions will be removed.

For now, I've published a version which should work, but it's probably best to get acquainted with the build process yourself.
