### ISSUE TITLE
Toolchain Debugger not available in Makefile

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2098]
Trying to cross-compile `samba` but it needs TC debugger (`gdb`) which apparently is not available in `ENV`. Is it done in purpose?
Can we add `gdb` to `spksrc.tc.mk`?
>-TOOLS = ld ldshared:"gcc -shared" cpp nm cc:gcc as ranlib cxx:g++ ar strip objdump readelf
>+TOOLS = ld ldshared:"gcc -shared" cpp nm cc:gcc as ranlib cxx:g++ ar strip objdump readelf gdb

**Comment by Diaoul** [comment]
It wasn't needed until now and I don't even think there was a cross compilation toolchain that came with gdb anyway.
If that works feel free to add it.
