### ISSUE TITLE
Invalid location

### ISSUE THREAD

**Issue by Weggy** [SynoCommunity/spksrc#2100]
Hi,

When following the "https://synocommunity.com/" instructions to:
In the Package Sources tab, click Add, type SynoCommunity as Name and http://packages.synocommunity.com/ as Location and then press OK to validate.

I get the following error message: Invalid location

Anyone else getting this?

**Comment by piwi82** [comment]
This issue has already been solved : https://github.com/SynoCommunity/spksrc/issues/2089#issuecomment-173169801
You should search for similar problems in existing issues before creating a new one : https://github.com/SynoCommunity/spksrc/issues?utf8=✓&q=is%3Aissue+invalid+location
