### ISSUE TITLE
Problems with Git-server

### ISSUE THREAD

**Issue by Vilican** [SynoCommunity/spksrc#2101]
I installed a Git-server on my DS115j. How do I correctly create a repository to be shown on /gitweb/?
Thank you
##

**Comment by coboltDE** [comment]
I'm having trouble finding any(!) documentation for SynoCommunity's git-server. how to use all of those cool things that package brings? please help.

**Comment by ymartin59** [comment]
Relevant ! According to code, package provides both gitweb and gitolite background service with automated SSH keys generated from dropbear.
There is no chance it is still running on DSM 6.x by the way... a package update will be required.

**Comment by coboltDE** [comment]
gitweb is still working on 6.x - but i can't get gitolite working. public key auth. doesnt work either at the moment.
