### ISSUE TITLE
Debian Chroot package file is corrupt

### ISSUE THREAD

**Issue by CurreE** [SynoCommunity/spksrc#2103]
So I just bought a brand new DS416 and tried to install Debian Chroot 8.1-6 using the Package Center.  The Python package it depends on installed fine, then Debian Chroot downloaded, but immediately after that I got an error message:

"The package file is corrupt. Please download it again or contact the package developer"

This is with DSM 5.2-5644 Update 3.  I have tried to install multiple times but always get the same error message.

**Comment by Dr-Bean** [comment]
To rule out checksum-related errors, I've reuploaded the package. Can you try again?

**Comment by CurreE** [comment]
I just tried again and it failed with the same error message.

**Comment by Diaoul** [comment]
Due to various caching you may need to wait 2 hours for the new version to show up.

**Comment by CurreE** [comment]
Alright, good to know, I'll try again later.

**Comment by CurreE** [comment]
I tried again first thing this morning when I woke up and it worked this time!  Thanks very much for your help.
