### ISSUE TITLE
Update: btsync 2.3

### ISSUE THREAD

**Issue by chmuibk** [SynoCommunity/spksrc#2105]
Hi folks

btsync 2.3 is out and it has some nice new features (support of encrypted folders) and a polished web interface which is nice.
As far as I know there are no new dependencies or any changes needed for this update.

**Comment by Dr-Bean** [comment]
We haven't maintained a BTSync package since 2.x came out. You're probably looking for this:
http://help.getsync.com/hc/en-us/articles/206215185-Synology

**Comment by chmuibk** [comment]
Sorry, my bad :)
