### ISSUE TITLE
nzbget with special characters eg umlauts

### ISSUE THREAD

**Issue by Kopierwichtel** [SynoCommunity/spksrc#2106]
Hello, 

I'm using a DS2413+ (DSM 5.2-5644 Update 3) with nzbget 16.4-21 and have a problem during unpacking: if the password contains special chars like öäü the unpack isn't working. Also if the rar files contains files with umlauts in the name the unpack isn't working properly. The target filename is cut where the umlaut is.

I can provide details abou the post where i had the issue, but am not sure if this is OK/allowed. Please let me know.

Thanks in advance

Kopierwichtel

**Comment by Kopierwichtel** [comment]
btw. the error message if get for the password is, that the password is incorrect. But i checked thats its correct.
I also installed sabnzbd and here i don't have this issue.

**Comment by Kopierwichtel** [comment]
I searched the issues and saw, that this is already existed in the past #932. I checkted the locale of my DS and its set to german (de_DE), which should be correct. In sabnzbd special characters are working. Might thi sbe related to the Intel platform of my DS2413+?

Would be great if you can help me, as nzbget is much faster than sabnzdb.

**Comment by Dr-Bean** [comment]
I would suggest to report this upstream (nzbget forums), see if the developer or anyone else has a suggestion.
