### ISSUE TITLE
subliminal run failing

### ISSUE THREAD

**Issue by raspap** [SynoCommunity/spksrc#2107]
Hi,

I have been able to install Subliminal through the Synocommunity channel on my NAS, but trying to run it from the Package Center gives an error: "Failed to run the package service".

I am using:
subliminal 0.7.5-12
python 2.7.11-15
DSM 6.0 beta 2

Any idea on how to debug this?

Thanks!
##

**Comment by globoid** [comment]
+1

**Comment by FesseCestMoi** [comment]
Hi,

The problem is still up on the official dsm6 release.

DSM 6.0-7321

Any news ?

**Comment by doppiej** [comment]
Any news on this?
I am also experiencing this problem..

**Comment by Safihre** [comment]
Closing due to age, further updates of Subliminal (like DSM6 compatibility) should be part of #2357.
