### ISSUE TITLE
Pyload Beta package under DSM 6 Beta 2 is damaged.

### ISSUE THREAD

**Issue by backslash69** [SynoCommunity/spksrc#2108]
The System installs Python when i install PyLoad.

**Comment by Dr-Bean** [comment]
Not sure what the problem is. The SynoCommunity Python package is supposed to be installed if you want to use our pyLoad package. Please explain in more detail what the issue is.

**Comment by backslash69** [comment]
Sorry about. Was a temporary Failure from my Synology.
