### ISSUE TITLE
Domoticz GitHub

### ISSUE THREAD

**Issue by Martijn085** [SynoCommunity/spksrc#2109]
It seems that Domoticz has moved to git, the source to build a new SPK file doesn`t work anymore.

> svn: No repository found in 'svn://svn.code.sf.net/p/domoticz/code/trunk'

The Domoticz forum says: You are updating from a very old version, and as for source code, we moved to git

Can someone update the package with the git source?
##

**Comment by piwi82** [comment]
Domoticz has moved to GitHub [here](https://github.com/domoticz/domoticz).
Indeed, [SynoCommunity is using the original SVN](https://github.com/SynoCommunity/spksrc/blob/master/cross/domoticz/Makefile#L7) : 
[Package developers](https://github.com/SynoCommunity/spksrc/commits/master/cross/domoticz) should be able to update the source.

**Comment by CondormanFr** [comment]
There is an other synology domoticz pakage here : [http://www.jadahl.com/](http://www.jadahl.com/)

**Comment by Diaoul** [comment]
Those packages are built with spksrc. It would be simpler if the author could contribute to SynoCommunity rather than forking.
