### ISSUE TITLE
Sickbread custom Failed to run the Package Service

### ISSUE THREAD

**Issue by ba3bas** [SynoCommunity/spksrc#2112]
Hi

I have Sickrage custom installed on my DSM.

All of a sudden, it stopped working to I manually stopped the application.
Now it won't restart no matter what I try.

I have a Synlogy DS1515+ running DSM 5.2-5644 update 3.

I can't find anyway of running some sort of command line as I would in Linux.
Granted i'm not that linux literate either.

Any help would be appreciated

**Comment by bennysaurus** [comment]
+1 here too. It looks like the start-stop-status script points to "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py" which no longer exists after the update.

**Comment by m3digi** [comment]
I'm having the same issue on my Synology DS413.

**Comment by pausete** [comment]
+1 Here in Synology DS115j

**Comment by glekkes** [comment]
+1 for Synology DS411+II

**Comment by bennysaurus** [comment]
Turns out this is related at least for me to the sickrage branch I was
running. Uninstalling and using another repo worked fine.

**Comment by ba3bas** [comment]
I've tried installing sickrage and that fails, but sickbeard works.

Anyone got a link for the latest sickrage download?

**Comment by m3digi** [comment]
This one works: https://github.com/SickRage/SickRage.git

**Comment by ba3bas** [comment]
I can confirm I am back up and running. 
If you haven't backed up you previous config recently yuo need to re-add all your settings but all good otherwise

**Comment by m3digi** [comment]
I found my SickRage stopped again.  I checked the logs an found the following:

`2016-02-01 12:15:41 INFO     EVENT-QUEUE :: Shutting down Tornado
2016-02-01 12:15:42 INFO     EVENT-QUEUE :: Restarting SickRage with ['/usr/local/sickbeard-custom/env/bin/python', u'/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py', '--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', u'--nolaunch']`

I'm now unable to restart Sickrage. I received a message saying 'Failed to run the package service.'

**Comment by cristianciofu** [comment]
Apparently on the latest DSM version the issue is back...

Just tried to install it using the SickBeard custom and I'm having the same error :(

Any ideas?

Thanks

**Comment by cristianciofu** [comment]
Ok, I got it working. Here's the "fix" 👍

Go to:
Configurations -> Groups -> asjust the permissions of sc-download and sc-media -> give all folders read/write access.

After this reboot your Synology and try to open Sickrage.

Solution found here : https://forum.synology.com/enu/viewtopic.php?p=430659#p430659

**Comment by ba3bas** [comment]
I quit using sick beard/rage and moved to sonarr instead

No issues at all now

**Comment by ba3bas** [comment]
Great stuff

**Comment by cristianciofu** [comment]
@ba3bas when I'm trying to install I get this error : "The following packages are missing in the package server. Please contact the Synology support team. mono"

So any idea how can I install "mono" ? :)

**Comment by ba3bas** [comment]
Should be in productivity in the package centre

Although not sure why it's needed but try there

https://www.synology.com/en-global/dsm/app_packages/Mono

**Comment by cristianciofu** [comment]
found it :) thanks @ba3bas
