### ISSUE TITLE
Can't add Synocommunity into Package Center

### ISSUE THREAD

**Issue by sgorchichko** [SynoCommunity/spksrc#2116]
I can't add http://packages.synocommunity.com into Packge Center. I got Save failed when trying to add.

What to do?
##

**Comment by dancingnzb** [comment]
Easy Install
Step 1

Log into your NAS as administrator and go to Main Menu → Package Center → Settings and set Trust Level to Synology Inc. and trusted publishers.

Step 2

In the Package Sources tab, click Add, type SynoCommunity as Name and http://packages.synocommunity.com/ as Location and then press OK to validate.

Step 3

Go to Beta tab, tick on yes, I want to see beta versions

Step 4

Go back to the Package Center and enjoy SynoCommunity's packages in the Community tab.


Please let me know if there is something else you having issues with after following those steps

**Comment by sgorchichko** [comment]
@dancingnzb unfortunately DSM 4.2 do not have any settings for Trust level.
![image 1](https://cloud.githubusercontent.com/assets/1161230/12696755/7dd35554-c783-11e5-89ab-507560fb0581.png)

**Comment by Todberg** [comment]
Yes, it does not work on DSM 5.2 either.

**Comment by Kalyse** [comment]
Also, does not work on DSM 5.2-5644 Update 1. 

It would basically just hover on the Loading section for a few minutes. After about 2 minutes, it stops loading without an error. 

![selection_970](https://cloud.githubusercontent.com/assets/199760/12718897/88ae8c66-c8e9-11e5-8015-94de2af243d9.png)

**Comment by Melgawa** [comment]
Hello !

I have the same issue. Running 4.2-3256.

I can ping packages.synocommunity.com just fine but still the "save failed" issue when I try to add it.

Any hint ? Any log I couldhave a look into ?

Thanks !

**Comment by Safihre** [comment]
Closing due to age. Please re-open if it's still an issue.
