### ISSUE TITLE
Repository does not work

### ISSUE THREAD

**Issue by Todberg** [SynoCommunity/spksrc#2118]
Gets 'invalid location' when trying to add your repository to my NAS, http://packages.synocommunity.com/.

**Comment by gizmocuz** [comment]
What type of Synology do you have ?

**Comment by reasonv** [comment]
I have the same issue. My NAS is DS416j with the latest DMS (5.2-5644 update 3). Is there solution for this?

**Comment by Kalyse** [comment]
Also, does not work on DSM 5.2-5644 Update 1.DS414. 

It would basically just hover on the Loading section for a few minutes. After about 2 minutes, it stops loading without an error. 

![selection_970](https://cloud.githubusercontent.com/assets/199760/12718897/88ae8c66-c8e9-11e5-8015-94de2af243d9.png)

**Comment by piwi82** [comment]
What DNS server were you using ?

**Comment by Kalyse** [comment]
192.168.2.1 (Clearly my local network had problems. I'm not going to
investigate why so I've just changed it)

**Comment by reasonv** [comment]
My DNS server is 10.35.250.49. I have tried it with 8.8.8.8 but did not resolve the issue.

**Comment by reasonv** [comment]
I have run the command you requested and got this: 
![image](https://cloud.githubusercontent.com/assets/17005561/12722265/6407c9a2-c904-11e5-99b5-9d10c292f120.png)
It seems it is not a DNS problem in my case.

**Comment by piwi82** [comment]
@Kalyse and @reasonv  : I assume this (192.168.2.1 and 10.35.250.49) is the private IP address of your router (ISP box). What are the public IP addresses of the DNS used by your router ?

**Comment by Kalyse** [comment]
I solved my problem. You are correct. THat was my problem. The gateway that
my router was on and my Synology weren't the same... I'm solved.. but I
think @reasonv may have a different issue altogether.

**Comment by reasonv** [comment]
#piwi82 Does it matter? My NAS resolves the right IP address of community, the screenshot proved it. Any other ideas?

**Comment by gizmocuz** [comment]
My problem was that i have an DS216 (no plus), and the architecture syno-armada38x is not in the spksrc repo yet.
(But i could add it myself locally and build the applications)

**Comment by reasonv** [comment]
@gizmocuz The DS416j has also Armada 388 processor (DS216 has Armada 385). I think our NASs belong to the same category according to this page: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model. Would you share with me the datailed list how you solved this? Please be noted, I have never worked with Linux before. Thank you in advance

**Comment by gizmocuz** [comment]
@reasonv  Sorry, if you never worked with linux before, then i am also pretty sure that you can not fix compile warnings, or make upgrades to the spksrc trunk
I would wait until the spksrc team adds the armada38x toolchain in the repo

**Comment by reasonv** [comment]
So currently this repository cannot be added on those NAS which has Armanda38x processor. Because this processor does not support this spksrc? And when it will, we can add it? I assume no one knows when it will happen. :(

**Comment by gizmocuz** [comment]
The DS216 (and maybe the DS216j) kan not add the Syno Community repository to the system because the armada38x toolchain is not in the git repo
The toolkit can be downloaded like any other toolkit
I am sure there are some people already working to get this included.
If not i can make a pull request

**Comment by tomdbpost** [comment]
@gizmocuz @reasonv Having the same problem wiht my DS216. Please follow this post: https://github.com/SynoCommunity/spksrc/issues/2033

**Comment by bigcheek** [comment]
@gizmocuz this would be great and very nice of you if you could make a pull request.
A lot of people that unfortunately haven't got the skills to do so are waiting for this :)

**Comment by gizmocuz** [comment]
The only issue i still have is compiling python2, python3 works, and python2 is used in a lot of third party apps

**Comment by tomdbpost** [comment]
@gizmocuz Maybe you can team up with @Diaoul en @Dr-Bean to get this last part working? Don't Unfortunately I don't have the skills to help you myself

**Comment by gizmocuz** [comment]
They know how to reach me, i am sure they are on it, or waiting till DSM 6 is finished

**Comment by tomdbpost** [comment]
@Gizmocuz can you make a pull request for this? Sorry for maybe pushing this a bit. It's just a bit frustrating that I don't have the skills to contribute on this myself. Anyway thanks for all the help so far and the time you and some other guys spend working on this. Much appreciated!

**Comment by gizmocuz** [comment]
It is not easy at the moment to make a pull request because i also updated some libraries (like libpng...) it is not a clean request.
Why dont you make a folder syno-armada38x-5.2 in the toolchain folder ?
Add a Makefile and put this in it:

```
TC_NAME = syno-$(TC_ARCH)

TC_ARCH = armada38x
TC_VERS = 5.2
TC_FIRMWARE = 5.2-5644

TC_DIST_NAME = armada38x-gcc493_glibc220_hard-GPL.txz

TC_EXT = txz
TC_DIST_SITE = http://sourceforge.net/projects/dsgpl/files/DSM%205.2%20Tool%20Chains/Marvell%20Armada%2038x%20Linux%203.10.35

TC_BASE_DIR = arm-unknown-linux-gnueabi
TC_PREFIX = arm-unknown-linux-gnueabi
TC_TARGET = arm-unknown-linux-gnueabi

```

In the kernel folder also create the same folder, and add a Makefile with this:

```
ARCH ?= armada38x
TCVERSION ?= 5.2
PKG_NAME = armada38x
PKG_BRANCH = 5644
PKG_ARCH = armada38x
PKG_EXT = txz
PKG_DIST_NAME = $(PKG_ARCH)-source.$(PKG_EXT)
PKG_DIST_SITE = http://downloads.sourceforge.net/project/dsgpl/Synology%20NAS%20GPL%20Source/$(PKG_BRANCH)branch
PKG_EXTRACT = source/linux-3.10.x-bsp
SYNO_CONFIG = synoconfigs/$(ARCH)
BASE_ARCH = arm

HOMEPAGE = http://www.synology.com/

PRE_COMPILE_TARGET = myPreCompile

include ../../mk/spksrc.kernel-modules.mk

PHONY: myPreCompile
myPreCompile:
        cd $(KERNEL_DIR)/arch/arm/ && rm -rf plat-armada && ln -s plat-armada-v2 plat-armada

```

Thats about it

**Comment by SvendsenMartin** [comment]
What's required to get cytec's commit merged in so the ds416j will be able to access the community repository - is there anything we can do to help the proces?

**Comment by cytec** [comment]
@SvendsenMartin nope. Either @Diaoul or @Dr-Bean must check it and merge it afterwards :)

**Comment by piwi82** [comment]
BTW, The toolchains for DSM 6 beta 2 are out : https://sourceforge.net/projects/dsgpl/files/DSM%206.0%20Beta2%20Tool%20Chains/

**Comment by reasonv** [comment]
@piwi82 Does it mean that SynoCommunity will work by default with DSM6 if it will be available? (and of course with DSM6 beta, if someone wants to install it.)
That's a good news! Does anybody knows when do we expect for DSM6? In April or before?

**Comment by piwi82** [comment]
I think SynoCommunity will wait for the final (stable) version of the DSM 6 toolchains.

**Comment by Diaoul** [comment]
We don't have access to DSM 6 NASes to do the necessary testing of our packages so you'll have to wait that a developer is willing to update to DSM 6.0 and update the packages.
That means it can take some time, even after the official release.

**Comment by Dr-Bean** [comment]
I'm going to close this one. As with similar issues in the past, this is getting to be collection of different things.

Here's some pointers:
- Feel free to pick up DSM6 related issues if you're running DSM6 already.
- Armada38x related stuff is/was discussed in #2033. Please read my comments there in particular
- If you have issues with adding the repository for other models: make sure your device is properly connected to the internet. That includes verifying IP-addresses, gateways, DNS servers, firewalls, routers, all of it.
- Before opening a new issue, verify that there are no other _open_ issues that are _exactly_ the same as your issue. Don't reuse a closed issue: you're not likely to get a response in that case. Don't dump your question into something that looks similar, if need be, we can mark an issue as duplicate.
- After checking the above and still running into problems, you're free to open a new issue ;) 
Describe your model and DSM version, the symptoms you have, and what you have done to solve the issue. Especially if your problem is related to adding the repo to Package Center, you should include the results of running `nslookup packages.synocommunity.com` on the NAS.
