### ISSUE TITLE
[request] nzbhydra

### ISSUE THREAD

**Issue by Morktral** [SynoCommunity/spksrc#2120]
Description: Replacement of NzbMEgasearch
Website: https://github.com/theotherp/nzbhydra
Documentation: https://github.com/theotherp/nzbhydra/wiki
Build/Installation documentation: https://github.com/theotherp/nzbhydra
Source Code: 
License:Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
##

**Comment by adchevrier** [comment]
I've started working on this package, I'll update shortly

**Comment by adchevrier** [comment]
Just made a PR

**Comment by Safihre** [comment]
Package is published as far as I can see.
https://synocommunity.com/package/nzbhydra
