### ISSUE TITLE
ncurses vs ncursesw

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2121]
As per [issue #1210](https://github.com/SynoCommunity/spksrc/issues/1210) `ncurses` and `ncursesw` are exclusive to each-other. 
I found that `ncursesw` is `ncurses` with `UTF-8` capablility. Maybe I am wrong.
Both Python 2&3 use `ncurses`, alsa-utils as well, probably other packages do so.
As per [issue #1210](https://github.com/SynoCommunity/spksrc/issues/1210), to build a certain package using one or the other `ncurses` then it should be sufficient to add the "correct" `ncurses` package as first dependency package of the main one.
Can anyone confirm this is the "approved"/"official" way?
Will Python/asla-utils/etc be still in "good" shape after "upgrading" to ncursesw?
If so, then why not using always `ncursesw`? What's the catch with `ncurses`?

**Comment by cytec** [comment]
see http://invisible-island.net/ncurses/ncurses.faq.html#growing_features

**Comment by vkostas** [comment]
Thx, I had gone through that site before my post. It clearly states ncursesw builds packages can be built with ncurses but *it could have different locale behaviour*.
I started the thread because I need an upfront agreed solution as it has a big impact in other packages (using python and/or alsa-utils).
Maybe ncursesw could be activated from a flag in the main package (e.g. 'USE_NCURSESW = Yes') or just place 'cross/ncursesw' as high as possible on the DEPENDS list?
@Diaoul @Dr-bean
Maybe you could help.

**Comment by vkostas** [comment]
My problem is with some cross/packages (like `alsa-ultils`) someone would build them with ncurses and someone with `ncursesw`. I don't think the solution is to double them with `ncurses` and `ncursesw`.

**Comment by vkostas** [comment]
It looks I found the solution,
`ncursesw` has now PKG_NAME=ncursesw.
The first of `cross/ncurses(w)` defines which of them will be used (set correct ncurses as first dependency in the main package). As of that moment `cross/ncurses` and `cross/ncursesw` will use the correct "flavor" (no matter which one is called).
A cross/package can identify the pesence of `ncurses` or `ncursesw` as below:
>NCURSES_SUFFIX =
>ifneq ($(wildcard $(WORK_DIR)/.ncursesw-*), )
>  NCURSES_SUFFIX = w
>endif

This code is saved to a separate include `which_ncurses.mk` in folder `cross/ncurses`.
A cross/package must `include ../ncurses/which_ncurses.mk` so it can use the `$(NCURSES_SUFFIX)` (blank or `w`).
Configure argument `--with-ncurses` becomes `--with-ncurses$(NCURSES_SUFFIX)`.
I will push those changes together with my `mpd` project.
Issue can be closed.
