### ISSUE TITLE
nzbdrone not added to group sc-media

### ISSUE THREAD

**Issue by wigwam12** [SynoCommunity/spksrc#2122]
HI
Due to the non-functioning of SickrageTV and fearing losing all my settings I decided to try Sonarr.
Setup seemed to work fine but I found a whole list of errors along the lines of;
Import failed, path does not exist or is not accessible by Sonarr: /volume1/Downloads/complete/tv/[name of show]
Someone kindly advised that If I installed the SynoCommunity package, then a user group sc-media was added containing user nzbdrone.
and to go to control panel -> Group -> sc-media -> Edit -> Permissions and set the appropriate permissions on the respective source and destination folders.

BUT I have looked
I have a group called sc-Download which contains user SABnzb and Transmission and a group called sc-media which only contains 1 user sickrage
couchpotato isn't in either user nor is sonarr (nzbdrone)
I tried to add but when I seach for both sonarr and nzdrone after clicking "add" nothing is displayed?

I checked "Top" and the user is nzbdrone.
Could someone please guide me to fixing this?

Thanks

**Comment by Dr-Bean** [comment]
You realize that our package users are hidden, so you can't see it from the DSM interface, right? 
There have been some unconfirmed reports from people who do see some of the package users in the interface, but that's not the norm.
