### ISSUE TITLE
Sabnzb 1.0.0RC1

### ISSUE THREAD

**Issue by matthieugoua** [SynoCommunity/spksrc#2124]
The last package in synocomunauty is Beta5

The RC1 is Out

**Comment by Dr-Bean** [comment]
PR's welcome.

**Comment by lysin** [comment]
Now on RC2...


## SABnzbd 1.0.0RC2

**Changes in RC2

  -  Changing server priorities during a download could lead to unexpected results and lockups
  -  Made Glitter friendly for reverse proxies
  -  Config->Main shows more diagnostic info
  -  Default host to test IPv6 is now self-test.sabnzbd.org

If someone could upate this it would be great! 

Thanks

**Comment by Smiggel** [comment]
Would be nice if the package can be updated.

**Comment by mhartvig** [comment]
Updated it to version 1.0.0 RC4 in #2187

**Comment by Dr-Bean** [comment]
sabnzbd-testing_1.0.0-5 was published on the repository.
