### ISSUE TITLE
Sickrage path change

### ISSUE THREAD

**Issue by surrealroad** [SynoCommunity/spksrc#2125]
Sickrage 7.x now requires the file SiCKRAGE.py to be launched instead of sickbeard.py. This works if I run the command manually, but not if I try to start the package in package manager.

Where can I change this if I ssh into the NAS?

See https://sickrage.tv/forums/forum/help-support/frequently-asked-questions-faq/33287-installation-faq

**Comment by HollishKid** [comment]
I'm without any knowledge of running commands manually on my NAS.
Having always used the functionnalities as such. The packet won't launch anymore though. How can I get it to work again?

Thanks for your response!

**Comment by cmitz** [comment]
@HollishKid don't hijack threads. Shame on you.

@surrealroad The sickbeard-custom app is stored in: 
`/volume1/@appstore/sickbeard-custom`

Since I don't have the package installed (and since synocommunity is currently down) I can't provide an exact location but there might be a launch script there.

**Comment by surrealroad** [comment]
@cmitz unfortunately not

**Comment by cytec** [comment]
@surrealroad edit `start-stop-status` which can be found here `/var/packages/sickbeard-custom/scripts/`... to be more exact you'll be looking for this line:

`SICKBEARD="${INSTALL_DIR}/var/SickBeard/SickBeard.py"`

and change it to this:

`SICKBEARD="${INSTALL_DIR}/var/SickBeard/SiCKRAGE.py"`

**Comment by surrealroad** [comment]
ah right. I have the actual sickrage package installed, not the sickbeard-custom. I'll try that.

**Comment by surrealroad** [comment]
that worked
