### ISSUE TITLE
TestDisk & PhotoRec 7.1-WIP 

### ISSUE THREAD

**Issue by helt** [SynoCommunity/spksrc#2130]
Afaik this does not comply with your definition of bleeding edge ("Latest stable version of your favorite software""). Yet, i want to ask if there is a way to get the current 7.1-WIP onto my NAS.

**Comment by cytec** [comment]
AFAIK Latest stable release is still 7.0

**Comment by helt** [comment]
yes. thats correct. however, PR 7.1-WIP seems to remedy some issues with *large* volumes. Thats why i need it. Thats why i ask.

**Comment by Dr-Bean** [comment]
Closing, I gather this is solved.
