### ISSUE TITLE
Potential new package? for sage 50 accounting

### ISSUE THREAD

**Issue by ecomatt** [SynoCommunity/spksrc#2133]
Hi is this something that you guys might be interested in building?
So people can run sage 50 from synology. 
As I understand it, it needs to install several things to get sage to be able to store its files on the synology server.
Details for linux installers can be found here. 
https://support.na.sage.com/selfservice/viewContent.do;jsessionid=D424613AE52C866428389BA9B44E99EB.worker1h?externalId=31857&sliceId=1

connection manager readme
http://cdn.na.sage.com/ftp/sa/install/2014/LinuxConnectionManager_Readme.txt

Thanks

**Comment by piwi82** [comment]
This cannot  be built for Synology NASes :
System Requirements
====================

Hardware Requirements
----------------------
- 50MB of disk space for the Connection Manager + additional 
space for each Sage 50 company file
- 512MB of RAM

Supported Linux Distributions
------------------------------
- SuSE Enterprise Server 10 (32- and 64-bit versions)
- Red Hat Enterprise Desktop 5 (64-bit version)
- Red Hat Enterprise Server 5 (32- and 64-bit versions)

Dependencies*
-------------				
- MySQL ODBC Connector 3.51
- MySQL ODBC Connector 5.2(ansi)
- Mono
- File Sharing Software such as Samba
* Dependent applications must be installed prior to installing 
the Sage 50 Connection Manager for Linux.  

Components
-----------
The Linux Connection Manager consists of the following 
components:
- The RPM for installation on a supported Linux distribution
- The public key file (.asc) to verify the contents of the RPM 
package. The name of this file is “sagesaconnmgr-public-key.asc”.
- MySQL ODBC 3.51 for Linux
- MySQL ODBC 5.2 for Linux
- The configuration files that specify the configurations for 
MySQL (dbengine.conf) and Sage 50 Connection Manager 
(ConnectionManager.conf).

**Comment by Dr-Bean** [comment]
Closing. Unfortunately, the software isn't open-source and there are only packages available for a select set of Linux distro's. There's nothing we can do here.
