### ISSUE TITLE
mono not starting after install

### ISSUE THREAD

**Issue by usermen** [SynoCommunity/spksrc#2134]
Hi All,
I have a little problem with Mono package.
After install, in package center mono has status "running", but when I type mono --version via ssh, my synology NAS inform me that mono is not recognised command. When I try compile hello world program via mcs i received similar error.

How can I run mono?

**Comment by Pimmetje** [comment]
For me it works:
DSM> /usr/local/mono/bin/mono --version
Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Mon Nov 30 14:47:31 CET 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by usermen** [comment]
Hi,

Thank You for Your answer!

compilation from given location works great. I thought that the mono package from  SynoCommunity works as well as a package from synology.

What do I need to compile my code as the package from synology? It is so important that I want to run my website in ASP.net

Thank for any help

**Comment by Attila2** [comment]
Hi,

Thanks for the clarification.

Can we get a link (or short guide) on how to set up Mono 4 to run ASP.NET pages on DSM.
(I couldn't find xsp2/4; and don't know how to set it up with the default webserver on DSM).

Thank you in advance.

**Comment by cytec** [comment]
well technically this isn't something to discuss here. we just provide the SPK containing mono no tutorials/guides on how to get your specific use case to work :/

**Comment by Dr-Bean** [comment]
Closing: I'd suggest to look at forums aimed specifically on using Mono. If there are changes needed to the package, we can look into that, but otherwise, we can't provide support on using software.
