### ISSUE TITLE
include e4defrag / remove --disable-defrag

### ISSUE THREAD

**Issue by vbondzio** [SynoCommunity/spksrc#2137]
Hi all,

could you try to "back out"  https://github.com/SynoCommunity/spksrc/commit/9dd399750b790370f5827751884f0bd2abd2adb6

and see whether it works with later toolchains?

Cheers,

Valentin

(filed as per email with Diaoul)
##

**Comment by Aktanusa** [comment]
So I manually "back out" [9dd3997](https://github.com/SynoCommunity/spksrc/commit/9dd399750b790370f5827751884f0bd2abd2adb6) and built for my DS216j (armada38x) and it seems fine.  I'll do more testing though.

**Comment by hgy59** [comment]
e4defrag is included in synocli-disk (and in "do it yourself" diskutils).
It is not added to the path so you have to use full qualified path:
`/var/packages/synocli-disk/target/sbin/e4defrag`
