### ISSUE TITLE
TVHeadend 4.0.8-1 start-status-stop: tvheadend-4.0 user does not exist

### ISSUE THREAD

**Issue by botazefa** [SynoCommunity/spksrc#2139]
On Synology DS1515+, the /var/packages/tvheadend-4.0/scripts/start-stop-status script specifies;

USER="tvheadend-4.0"

tvheadend-4.0 user does not exist. TVHeadend starts-up fine and the web interface looks normal, but it's not possible to access the dvb inputs.

When the USER var is updated to tvheadened-40, it all works properly. 

Please advise if I should post this issue elsewhere.

**Comment by Dr-Bean** [comment]
Seeing as we do not provide a tvheadend-4.0 package on our repository, I would suggest reporting it to wherever you got the package.

**Comment by botazefa** [comment]
I'm having difficulty understanding which community packages atlre supported here. The tvheadend-40 doesn't have any READMEs and it came from the community repo. I guess your repo us just for the pkg framework? Breadcrumbs appreciated. Please feel free to clise this ticket.

---
Marc Thompson

**Comment by Dr-Bean** [comment]
Easy enough: We support SynoCommunity packages distributed via our repository: https://synocommunity.com/packages.
Packages that are not distributed via our repository are not supported.
