### ISSUE TITLE
Syncthing umask issue?

### ISSUE THREAD

**Issue by gotson** [SynoCommunity/spksrc#2140]
Hi guys,

i installed Syncthing, but all files replicated on the Nas from another device, when file permissions are ignored in Syncthing, are not created with the correct permissions.

Files/folders get created with permissions `-rw-r--r--` / `drwxr-xr-x`, but i expect them to be created with `-rw-rw-r--` / `drwxrwxr-x`
Note that the user:group of the files is correct (syncthing:users)

I tried adding a `umask 002` in the `.profile` file of the user `syncthing`, but it doesn't seem to be taken into account when syncthing is running, but it is applied when i log in using syncthing user and create new files.
Hence i suppose the startup script provided in the package does not make use of the `.profile` file.

Issue also mentionned on Syncthing forums, but not really a Syncthing issue:
https://forum.syncthing.net/t/umask-on-synology/2499

I looked around also in the various issues on github, and also on the other packages installed i use:
- it looks like `start-stop-daemon` from `busybox`does not support `umask`
- `transmission`has a umask setting in its app config, so it works fine
- `btsync`is a Synology package, and doesn't use `start-stop-daemon`, but runs as `admin` via `su` and set the proper `umask`at startup
- `couchpotato-custom` has a specific `chmod`setting in its config, so folders created have correct permissions, and files inside are under `transmission` user, so are correct too
- `sonarr` has an option to `chmod`/`chown`files/folders, and is thus fine
- some people on GH says that the Unix rights should not be used, and that Synology ACL are used instead. However my user account has full rights on the share, but i cannot edit some files/folders created by `syncthing` user, so i guess Unix rights are used after all.

Does anyone have the issue, is there any possible workaround ?
Changing the `start-stop-daemon` to something else would do the trick, is it something you plan to do to fix those issues ?
##

**Comment by Dr-Bean** [comment]
I don't think there's much we (SC) can do here. We have to use busybox' `start-stop-daemon`, seeing as Syncthing does not provide a daemon itself (as opposed to BTSync), and there are no available alternatives that allow us to manage the package otherwise.

All the other options you mention should be built into the software itself. The only option that Syncthing has is `Ignore permissions`. Have you tried using that?

**Comment by gotson** [comment]
I am using IgnorePermissions already.

Why do you have to use  busybox' `start-stop-daemon` exactly ?
Isn't it possible to replicate the behavior of the command with more simpler shell commands, and handle `umask` at the same time ?

**Comment by Dr-Bean** [comment]
As I said, Syncthing doesn't provide its own daemon. As a general approach, we use `start-stop-daemon` for software which doesn't provide its own daemon. Apart from busybox, there are no alternatives that would work on a Synology that I'm aware of right now.

If you want to migrate to a different approach, feel free to change the start-stop-status script on your NAS, play around with it and make whatever changes you need. Let us know the results, or open a PR with the necessary changes when you figure out something better.

**Comment by gotson** [comment]
I created a PR: https://github.com/SynoCommunity/spksrc/pull/2147

**Comment by ymartin59** [comment]
There is no Unix mod/permissions but ACL are there. See synoacl command.
