### ISSUE TITLE
Openssl init Failed

### ISSUE THREAD

**Issue by tahasiddiqui123** [SynoCommunity/spksrc#2141]
while building softEther sourceCode using 'make' command following alert occurs
-- Alert: RsaCheck() --
OpenSSL Library Init Failed. (too old?)
Please install the latest version of OpenSSL.

my version of openSSL is 
'OpenSSL 1.0.2f  28 Jan 2016'
Still this error occurs why

**Comment by Pimmetje** [comment]
Did u try  #2119

**Comment by tahasiddiqui123** [comment]
yeah I already have this version of open ssl.
'OpenSSL 1.0.2f 28 Jan 2016'

**Comment by cytec** [comment]
uhm... what is softEther? it's not something we provide in this repo

**Comment by Dr-Bean** [comment]
Closing. We currently don't provide a package for SoftEther. If that's what you're planning/creating, please open a new issue and share the code you're working with. Otherwise, there's no way for us to be able to help.

**Comment by nickdsl** [comment]
Hi! Yesterday i found the reason.
I created topic on SoftEtherVpn forum.
http://www.vpnusers.com/viewtopic.php?f=7&t=7429
Enjoy! ;)
