### ISSUE TITLE
Include syncthing-inotify in Syncthing

### ISSUE THREAD

**Issue by OrangeFoil** [SynoCommunity/spksrc#2142]
Since I installed Syncthing on my NAS the hard drives don't power down on idle anymore because Syncthing is scanning the folders every 60 seconds to monitor changes.

So instead of relying on a periodical rescan it would be great if the Syncthing package also installed [syncthing-inotify](https://github.com/syncthing/syncthing-inotify), which is also developed and maintained by the Syncthing team.

> This application (syncthing-inotify) uses OS primitives to detect changes as soon as they happen. Therefore, if you save a file, syncthing-inotify will know about it and pass this information to Syncthing such that near real-time synchronisation can be achieved.
##

**Comment by Dr-Bean** [comment]
Done with #2629 thanks to @o0v7r0o. Packages are published on the repository and should show up shortly.
