### ISSUE TITLE
BucBucStriim v1.3.6

### ISSUE THREAD

**Issue by baz1860** [SynoCommunity/spksrc#2144]
Can the BucBucStriim package be updated to the latest available?

Latest is available from https://github.com/rvolz/BicBucStriim/releases; currently 1.3.6

The admin notes that databases from v1.2 are incompatible - but has a workaround

"The database structure of version 1.2 is incompatible with previous versions, so exisiting users should start with a fresh install. However, if you have lots of books and don’t want to regenerate all the thumbnails for them:

Backup your old BicBucStriim installation, eg. mv bbs bbs.old
Install the new version and run it
There should be a new directory: bbs/data/titles
Copy the thumbnail files (thumb_*.png) from your old data directory to bbs/data/titles
Use chmod -R ga+w bbs/data/titles to correct the permissions after copying if there are access errors
Notice for users upgrading from v1.2.4 or earlier: since v1.2.5+ issue #104 added the possibility to have multiple admin users. If you have trouble to login as admin, either

use the sqlite3 cli to update user set role=1 where username='admin';
delete data/data.db"
##

**Comment by Dr-Bean** [comment]
PR's welcome. The above workaround can probably be implemented without too many issues.

**Comment by Dr-Bean** [comment]
See https://github.com/SynoCommunity/spksrc/pull/2258. Workaround probably not needed, as we were on 1.2.5 already (the changelog of BBS doesn't mention issues between 1.2.x and 1.3.x, right?)

**Comment by Dr-Bean** [comment]
I believe this issue can be closed, #2258 was merged ages ago, and I don't think we've had other issues being reported (for DSM6, probably a new issue should be opened if there's a need)
