### ISSUE TITLE
[debian-chroot] use systemd-nspawn for using systemd in debian-chroot

### ISSUE THREAD

**Issue by RafaelKa** [SynoCommunity/spksrc#2145]
Hello folks,

i upgraded my debian-chroot from wheezy to jessie and tried tu use systemctl, which prints `Running in chroot, ignoring request.`. 
I found very nice article about [chroots and systemd](http://0pointer.de/blog/projects/changing-roots).

Do you think, it makes sense to change to systemd-nspawn in this package?
##

**Comment by Safihre** [comment]
Closing due to age. Re-open if request is still desired.
