### ISSUE TITLE
Manual download spk from synocommunity

### ISSUE THREAD

**Issue by RPK1982** [SynoCommunity/spksrc#2148]
Hi all, 

Newby on the forum here

I'm running on a ds207+ (still) and still going strong. Unfortunately recently my version of Couchpotato crashes and I can't get it up and running. My idea whas to de-install my current couchpotato package version (20130505-3)  and re-install a new version. 

However I can't download the spk straight from the website. I tried multiple PCs, IE and Firefox, but no difference. I don't see a link or button where to manually download the package from the net.
As my architecture only support up to DSM 3.1, I don't have the ability to link the package center to an external source. For all you early synology adapters :-), DSM 3.1 can only install spk package which are first downloaded locally.

Anyone who can help me out? Preferable with the latest .spk of Couchpotato custom version (which I read is the package to go for these days).

Other suggestions are welcome (just to beat you to the punch; not being buying a new NAS), like maybe how to fix couchpotato

Much appreciated

**Comment by cytec** [comment]
There are no manual download links available even if there would be, afail currently we'll only provide SPK's for the most recent stable version of DSM ... so the only solution i can think of here is to setup spksrc and build the spk's for 3.1 yourself..

**Comment by Dr-Bean** [comment]
See above, we don't provide manual downloads.
