### ISSUE TITLE
Problems adding Package Sources - DSM 5.2-5644 Update 5

### ISSUE THREAD

**Issue by mxmusso** [SynoCommunity/spksrc#2149]
Hello, I can't add Package Sources. Followed your instructions at https://synocommunity.com/#easy-install and also tried  putting "any publisher" but I only see a red message saying "invalid position". 

Thanks for your help. 

I have a DS115j with DSM 5.2-5644 Update 5
##

**Comment by Malbak** [comment]
Same issue here with the same model and same DSM.

**Comment by Safihre** [comment]
Closing due to age. Please re-open if it's still an issue.
