### ISSUE TITLE
Can not compile arch 88f5281-3.1 package with spksrc

### ISSUE THREAD

**Issue by Blue4green** [SynoCommunity/spksrc#2154]
I've installed docker with spksrc in it. I have a DS207+ so give the command:
make arch-55f8281-3.1 in the nzbget dir. But then after downloading arm-marvell-linux-gnu i got directly errors...

tar: arm-marvell-linux-gnu/lib/libthread_db.so: Cannot create symlink to libthread_db.so.1: Protocol error
tar: arm-marvell-linux-gnu/lib/libnss_nis.so.2: Cannot create symlink to libnss_nis-2.3.2.so: Protocol error
tar: arm-marvell-linux-gnu/lib/noldmstm/libthread_db.so: Cannot create symlink to libthread_db.so.1: Protocol error
tar: arm-marvell-linux-gnu/lib/noldmstm/libnss_nis.so.2: Cannot create symlink to libnss_nis-2.3.2.so: Protocol error
tar: arm-marvell-linux-gnu/lib/noldmstm/libm.so.6: Cannot create symlink to libm-2.3.2.so: Protocol error
etc etc etc.
.........
.........
/spksrc/spksrc/spk/nzbget/work-88f5281-3.1/tc_vars.mk:1: **\* An error occured while setting up the toolchain, please check the messages above.  Stop.
make[1]: Leaving directory '/spksrc/spksrc/spk/nzbget'
../../mk/spksrc.spk.mk:416: recipe for target 'arch-88f5281-3.1' failed
make: [arch-88f5281-3.1] Error 2 (ignored)
make: warning:  Clock skew detected.  Your build may be incomplete.

What do I wrong. I tried also a 5.2 with a different arch but I got similar errors.... Hopefully someone can help me.
##

**Comment by Dr-Bean** [comment]
Maybe try the `88f6281-4.3` toolchain. It might be compatible enough to work.
The `88f5281-3.1` toolchain hasn't worked for as long as I recall...I'm not sure why we're even bothering with keeping it around.

**Comment by Blue4green** [comment]
Tnx man. I will try it and let you know if it works.

**Comment by Blue4green** [comment]
It did not work. Probably the simlinks can not be made due to the NTFS partition. Do you think I have a better chance in an Ubuntu environment with an ext4 partition?

**Comment by Blue4green** [comment]
Ok, I managed the spk for 88f6281-5.2, but it cannot be installed. Just a warning is showed that the system needs at least DSM 5.0. Compile versions 4.3 or 3.1 is not possible. 
So it seams that those versions a broken. So please is someone capable of repairing this issue?

**Comment by Blue4green** [comment]
In mac I have the following errors while compiling nzbget for toolchain 55f5281-3.1 

===>    Extracting for syno-88f5281
tar -xzpf /spksrc/spksrc/toolchains/syno-88f5281-3.1/../../distrib/toolchains/3.1/gcc343_glibc232_88f5281.tgz -C /spksrc/spksrc/toolchains/syno-88f5281-3.1/work 
tar: arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-g++: Cannot hard link to ‘arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-c++’: Operation not permitted
tar: arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-gcc-3.4.3: Cannot hard link to ‘arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-gcc’: Operation not permitted
tar: arm-marvell-linux-gnu/arm-marvell-linux-gnu/bin/ld: Cannot hard link to ‘arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-ld’: Operation not permitted
tar: arm-marvell-linux-gnu/arm-marvell-linux-gnu/bin/ranlib: Cannot hard link to ‘arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-ranlib’: Operation not permitted
tar: arm-marvell-linux-gnu/arm-marvell-linux-gnu/bin/strip: Cannot hard link to ‘arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-strip’: Operation not permitted
tar: arm-marvell-linux-gnu/arm-marvell-linux-gnu/bin/as: Cannot hard link to ‘arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-as’: Operation not permitted
tar: arm-marvell-linux-gnu/arm-marvell-linux-gnu/bin/objdump: Cannot hard link to ‘arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-objdump’: Operation not permitted
tar: arm-marvell-linux-gnu/arm-marvell-linux-gnu/bin/nm: Cannot hard link to ‘arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-nm’: Operation not permitted
tar: arm-marvell-linux-gnu/arm-marvell-linux-gnu/bin/g++: Cannot hard link to ‘arm-marvell-linux-gnu/arm-marvell-linux-gnu/bin/c++’: Operation not permitted
tar: arm-marvell-linux-gnu/arm-marvell-linux-gnu/bin/ar: Cannot hard link to ‘arm-marvell-linux-gnu/bin/arm-marvell-linux-gnu-ar’: Operation not permitted
tar: arm-marvell-linux-gnu/include/syno.h: Cannot hard link to ‘arm-marvell-linux-gnu/include/linux/syno.h’: Operation not permitted
tar: arm-marvell-linux-gnu/include/scsi/scsi_ioctl.h: Cannot hard link to ‘arm-marvell-linux-gnu/arm-marvell-linux-gnu/sys-include/scsi/scsi_ioctl.h’: Operation not permitted
tar: arm-marvell-linux-gnu/include/scsi/scsi.h: Cannot hard link to ‘arm-marvell-linux-gnu/arm-marvell-linux-gnu/sys-include/scsi/scsi.h’: Operation not permitted
tar: arm-marvell-linux-gnu/include/scsi/sg.h: Cannot hard link to ‘arm-marvell-linux-gnu/arm-marvell-linux-gnu/sys-include/scsi/sg.h’: Operation not permitted
tar: Exiting with failure status due to previous errors

**Comment by Dr-Bean** [comment]
As I said before, you can probably forget the idea that the `55f5281-3.1` toolchain will compile correctly, regardless of the environment you're trying to compile it with.

Compiling the package with `88f6281-4.3` should work. At least you should not be getting extraction errors. I would suggest to try the virtual machine setup to see if that works for you: https://github.com/SynoCommunity/spksrc#virtual-machine. 

The 5.2 toolchain is hardcoded to set the minimum DSM version to DSM5.x, that's why you got an error that the package can't be installed.
If a package compiled with `88f6281-4.3` does not work, I think you're out of luck.

**Comment by Blue4green** [comment]
Tnx. I will try as a last attempt.

**Comment by Dr-Bean** [comment]
Any luck here?

**Comment by Blue4green** [comment]
Not tried yet Dr-Bean. Some virus touched me (not the computer).

**Comment by Blue4green** [comment]
No luck here. The 55f6281-4.3 package is build but during install on my 207+ I get an error that the platform is not compatible. Any ideas?

**Comment by Dr-Bean** [comment]
As I said, i'm not sure at all if the two are compatible, but you would need to manually correct `arch="88f6281"` to `arch="88f5281"` in the INFO file (or do that in the Makefile: e.g. define `override ARCH = `, like [here](https://github.com/SynoCommunity/spksrc/blob/master/spk/couchpotatoserver-custom/Makefile#L33)

**Comment by Dr-Bean** [comment]
@Blue4green Any progress here?

**Comment by Blue4green** [comment]
Did not work out. I got the same error.

**Comment by ymartin59** [comment]
In `spk/nzbget`, command `make arch-88f6281-4.3` produces expected package `nzbget_88f6281-4.3_16.4-22.spk`. If still relevant, I may provide it here.

**Comment by Safihre** [comment]
Support for `88f5281` has been removed with the removal of the DSM3 toolchains.
Closing.
