### ISSUE TITLE
Synology Package Center not seeing updates

### ISSUE THREAD

**Issue by Aimhere2k** [SynoCommunity/spksrc#2156]
I have a DS413j running DSM 4.3. I use NZBGet via SynoCommunity. The installed version is 16.3, which it's been lingering at for a while now. I just checked for updates within NZBGet and it says there is a new version 16.4, but that NZBGet is not configured for auto-updates, and when I check in Package Center, it shows no updates are available (nothing beyond 16.3).

I've tried removing other package sources besides SynoCommunity and rebooting, but Package Center refuses to show the new version in updates. 

If it helps, Package Center is also not showing any available updates for one or two other SynoCommunity packages (Midnight Commander, as I recall).

Any ideas? Am I going to have to uninstall in order to get the new version?

**Comment by Dr-Bean** [comment]
We only publish packages for the latest stable by default, see the FAQ: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support.

Probably the quickest way is to create the package yourself, see the instructions in the README.

**Comment by Aimhere2k** [comment]
Ugh, I use SynoCommunity packages _because_ I'm not terribly fluent in Linux and don't want to have to compile/build stuff on my own. Is there no other way?

**Comment by Dr-Bean** [comment]
With DSM6.0 around the corner, I'd say you should reconsider your choice to stay on DSM4.3. DSM4.3 is no longer supported by Synology, and sticking with DSM4.3 because of _anecdotal_ evidence is not the right choice imo. 
For that matter, it might be safer to stick with an older version of NZBGet too...;)

**Comment by Dr-Bean** [comment]
Fixed with a one-off release of nzbget 16.4-22.
