### ISSUE TITLE
Owncloud 8.2.2 as package

### ISSUE THREAD

**Issue by WhileDekker** [SynoCommunity/spksrc#2157]
Hi,

i really appreciate your work on the owncloud packages and probably you get this asked a lot, but are there plans to upgrade the owncloud package soonish?

Usually I dont mind not having the latest owncloud version, so the update rate is usually not a problem for me at all, but there seems to be a bug in Owncloud 8.1 which breaks the calendar sync with Windows 10 devices and at least it seems to be that this bug is fixed in 8.1.3. and later (https://github.com/owncloud/calendar/issues/853)

I have also read #1979 where a manual upgrade is described, but I don't want to mess around in the installation to avoid problems in later upgrades (or even destroy my current installation).

I really appreciate your work - you are doing a great job, so therefore I am asking if by any chance an update of the owncloud package would be possible?

Thanks

**Comment by Dr-Bean** [comment]
That's what #1979 is for. Open a PR with the necessary changes, or wait until someone else has time. 
Closing as duplicate.
