### ISSUE TITLE
HTPC-Manager bug

### ISSUE THREAD

**Issue by M0UL** [SynoCommunity/spksrc#2158]
i cant get HTPC-Manager  to work with this repo: https://github.com/Hellowlol/HTPC-Manager
it seems to be switching to default repo.

**Comment by Dr-Bean** [comment]
Can't reproduce. I assume you're starting with a clean install of the package, yes?

**Comment by M0UL** [comment]
yes

**Comment by Dr-Bean** [comment]
So..what happens? How have you determined that a different repo is used, instead of the one you chose? For example, is there anything available in a logfile, or did you verify this by some other means?

**Comment by Dr-Bean** [comment]
@M0UL, any update?

**Comment by M0UL** [comment]
sorry about not replay. i already fixed. i select the wrong branch when installing. i had to select master2 instead of master
