### ISSUE TITLE
Issues with DSM 6: HAproxy and sickbeard

### ISSUE THREAD

**Issue by acseven** [SynoCommunity/spksrc#2159]
Hi,

After upgrading to DSM 6 Beta 2, I've found these issues:
- HAProxy is running with the previous configuration, but the GUI doesn't load any actual data (it just keeps trying to load data, and it's not even possible to close the window)
- Sickbeard: I'm not sure if it's running yet, but trying to access the backed returns "403 Forbidden"

Any idea what can I do what to solve these issues?

Thanks
##

**Comment by Wild4fire** [comment]
How's it going now you've upgraded to the final release of DSM 6.0?

(btw, after upgrading from DSM 5.x to DSM 6.0 SickBeard was still working fine here)

**Comment by tyzefh** [comment]
I've exactly the same problem. 

I just have install the package under DSM 6.0 (update 1). 
The haproxy.cfg created don't work with a problem with ssl : 
`Starting HAProxy ...
[ALERT] 107/165755 (23877) : parsing [/usr/local/haproxy/var/haproxy.cfg:34] : 'bind :5443' : unable to load SSL private key from PEM file '/usr/local/haproxy/var/crt/default.pem'.
[ALERT] 107/165755 (23877) : Error(s) found in configuration file : /usr/local/haproxy/var/haproxy.cfg
[ALERT] 107/165755 (23877) : Proxy 'https': no SSL certificate specified for bind ':5443' at [/usr/local/haproxy/var/haproxy.cfg:34] (use 'crt').
[ALERT] 107/165755 (23877) : Fatal errors found in configuration.`
the default.pem is an empty file

I've removed the https frontend section and then the server start but the gui fail to load configuration.

**Comment by Safihre** [comment]
Further HaProxy updates (like DSM6 compatibility) will be handled in #2712.
