### ISSUE TITLE
ruTorrent not saving setting

### ISSUE THREAD

**Issue by gedimiz** [SynoCommunity/spksrc#2161]
Dear staff,

ruTorrent package does not save setting after restarting it. I read, that ruTorrent cannot save to rtorrent.rc file. I use WinSCP to connect to Synology DS215j, but I cannot find this rtorrent.rc file. There is no such file in the directories described.
/usr/local/rutorrent/share/rutorrent/conf/
I have no /opt/etc directory in root of my NAS.

Does anyone know how configure ruTorrent on Synology.

**Comment by GoodOmens83** [comment]
I don't think rutorrent will save settings to the rtorrent.rc file.  

`.rtorrent.rc`  (notice the . in front of the file, it might be hidden) is stored in `/volume1/@appstore/rutorrent/var/`  Make your changes there.
