### ISSUE TITLE
No sync with Synology DS416j

### ISSUE THREAD

**Issue by benjic78** [SynoCommunity/spksrc#2162]
Hello,
My NAS doen't add location "http://packages.synocommunity.com/"
Error say : "emplacement incorrect" // incorrect location

When i go to hyperlien on firefox : http://packages.synocommunity.com
404 Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

thx for your support

**Comment by Dr-Bean** [comment]
Handled via #2033.
