### ISSUE TITLE
[REQ] Update monit to version 5.16.x

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#2163]
Could someone have a look at Monit to upgrade it to most recent version?

I did a attempt myself but couldn't figure it out.
I think it's a issue in the monit code.

http://pastebin.com/v9n4dT8q

**Comment by Dr-Bean** [comment]
Add `--with-ssl-incl-dir=$(STAGING_INSTALL_PREFIX)/include` to the `CONFIGURE_ARGS` in `cross/monit/Makefile`. The default `sslincldir` is `/usr/include`, and adding that location breaks the cross-compile process.

Maybe you can test it locally and open a PR once you've confirmed that it works?

**Comment by schumi2004** [comment]
Will try, thanks.
Will submit PR when tested successfully.

**Comment by schumi2004** [comment]
@Dr-Bean 
It worked perfect, will submit PR soon, thanks.
http://pastebin.com/qBaz4XVb
