### ISSUE TITLE
DataTables warning (Plexivity)

### ISSUE THREAD

**Issue by eikewink** [SynoCommunity/spksrc#2167]
(plexivity)

Hi Guys,
i'm running the DS115J and the first Days everything is really good. After some days if i hit the "verlauf" (history) button i get this error back:

DataTables warning: table id=globalHistory - Ajax error. For more information about this error, please see http://datatables.net/tn/7

if i search under admin --> history everything is looking fine

all aother functions are working as they should

**Comment by cytec** [comment]
please report this error upstream
