### ISSUE TITLE
[REQ] Upgrade TVheadend server package

### ISSUE THREAD

**Issue by Raptorek** [SynoCommunity/spksrc#2170]
Hi guys, I wanna ask. Can contributor upgrade server package for Tvheadend? This version is too old, and also is not working with new version of addon for Kodi. Thanks

**Comment by sirjaymz** [comment]
https://tvheadend.org/projects/tvheadend/wiki/download
Syno specific
http://syno.dierkse.nl/

**Comment by Dr-Bean** [comment]
Duplicate of https://github.com/SynoCommunity/spksrc/issues/1855.
