### ISSUE TITLE
UI Develop not functioning with DSM 5.2 installation.

### ISSUE THREAD

**Issue by sirjaymz** [SynoCommunity/spksrc#2171]
UI Develop not functioning with DSM 5.2 installation.
DSM 5.2-5644

Install UI Develop as instructed.
UI app does not appear as it has in the past, even though it says it's 'Running'
https://github.com/SynoCommunity/spksrc/wiki/UI-Develop
https://github.com/downloads/SynoCommunity/spksrc/uidevelop-0.1-1.spk

Troubleshooting included.
uninstalling/reinstall.
reboot system.
login via CLI and review /volume1/@appstore/uidevelop/app/config 

Nothing obvious looks out of norm.

**Comment by sirjaymz** [comment]
outputed DMESG to txt file after stopping and re-running the app from in Package Manager.

type=1400 audit(1457123254.762:27): apparmor="DENIED" operation="open" parent=16353 profile="/usr/syno/synoman/webman/initdata.cgi" name="/volume1/Share/ui/uidevelop/config" pid=31721 comm="initdata.cgi" requested_mask="r" denied_mask="r" fsuid=0 ouid=1000

**Comment by Dr-Bean** [comment]
That package hasn't been updated in a long time. I doubt that it would be usable for DSM5+, even if you would get it to work.

**Comment by sirjaymz** [comment]
Yeah.. after looking into this, value seems not worth it at this time. please close appropriately.
