### ISSUE TITLE
sabnzbd user when being created

### ISSUE THREAD

**Issue by exussum12** [SynoCommunity/spksrc#2172]
When installing sabnzbd the suer is allowed to log in (their shell is /bin/sh).

This should either be /bin/false or /bin/nologin as there is no reason to log in as this user

**Comment by Dr-Bean** [comment]
How would you log in as the `sabnzbd` user?
Being able to `su` to a different user isn't an issue, seeing as you already have to have shell access to do that. If an unauthorized person is able to gain shell access, you have bigger problems.

Either way, if you have tested and proven that the package works without a valid shell set for the user, feel free to open a PR (please test with upgrading and new package installations). 
I know we've tried it before with a different package (can't recall which), and reverted it after the package stopped working for a number of people.

**Comment by exussum12** [comment]
Closing issue as the user is disabled. Thanks
