### ISSUE TITLE
Will ruTorrent work in DSM 6.0 rc?

### ISSUE THREAD

**Issue by smreka** [SynoCommunity/spksrc#2174]
Hi, I'm thinking of upgrading DSM to 6.0 RC and am wondering will ruTorrent work?

Thanks for your time.

Tom

**Comment by abraxxa** [comment]
As 6.0 final is out I'd also like to know if there is a compatibility list for all packages.

**Comment by cytec** [comment]
@abraxxa really? how about just open your eyes? 
https://github.com/SynoCommunity/spksrc/issues/2207

**Comment by abraxxa** [comment]
I added the comment to also list working packages in #2207 hours ago, so don't be a prick!

**Comment by Dr-Bean** [comment]
I hope you agree that name calling has no place here. I would suggest to edit that message.

As DSM6RC is no longer a valid choice, I'm going to close this issue. Use #2207 to report issues with packages. If need be, a separate issue or better yet, a PR, can be opened to discuss/implement resolutions.
