### ISSUE TITLE
ejabberd - in-band registration of a new user returns error 403

### ISSUE THREAD

**Issue by morys42** [SynoCommunity/spksrc#2177]
I googled for solution and found that the line
{access, register}
in config file needs to be changed to access_from , but I cannot access the config file and it cannot be done through the web interface. If I use default admin or manually registered user, I login, so the server works fine.
Thanks for suggestions.

**Comment by Dr-Bean** [comment]
Log in via SSH, and change the file that way?

**Comment by morys42** [comment]
I tried that but was unable to find the config file. I'll try again, thanks

**Comment by cytec** [comment]
@morys42 take a look at `/usr/local/ejabberd` i'd tip on the `var` folder in there

**Comment by morys42** [comment]
thanks. Actually, it's
/usr/local/ejabberd/etc/ejabberd/  ejabberd.cfg
