### ISSUE TITLE
Transmission-remote not removing completed torrents

### ISSUE THREAD

**Issue by alirz1** [SynoCommunity/spksrc#2180]
Not sure where to post this question.
I have the same version of transmission as synology running on my openwrt based router and i have no issue with the below torrent command on the router. it functions fine.
However on the synology the following command to remove 100% completed torrents does not work.
The problem seems to be with the second part of the command which is after the XARGS

command:
/volume2/@appstore/transmission/bin/transmission-remote -l | grep 100% | grep Done | awk '{print $1}' | xargs -n 1 -I % /volume2/@appstore/transmission/bin/transmission-remote  -t % -r

result:
xargs: invalid option -- 'I'
BusyBox v1.16.1 (2015-11-12 18:06:25 CST) multi-call binary.

Usage: xargs [OPTIONS] [PROG ARGS]

Run PROG on every item given by stdin

Options:
        -p      Ask user whether to run each command
        -r      Don't run command if input is empty
        -0      Input is separated by NUL characters
        -t      Print the command on stderr before execution
        -e[STR] STR stops input processing
        -n N    Pass no more than N args to PROG
        -s N    Pass command line of no more than N bytes
        -x      Exit if size is exceeded

**Comment by Dr-Bean** [comment]
This is not an issue with our Transmission package, it's a limitation of the xargs command from Busybox. As the error indicates, the `-l` option isn't available on busybox.

I would suggest to investigate what the command is to remove a torrent via transmission-remote, and see if you can pass on the correct content in a different way.

Closing, as there's nothing to do for us here.
