### ISSUE TITLE
Update syncthing to v0.12.20/latest

### ISSUE THREAD

**Issue by joaocc** [SynoCommunity/spksrc#2181]
Pretty self explanatory.
I'm a bit noobie on packaging things for Synology, but would like to help updating the package.
Thx

**Comment by Dr-Bean** [comment]
We're already at 0.12.8 of couse, but we can update the package to latest (currently 0.12.20). Note that you can update Syncthing with its built-in updater as well.

If you want to help, look at some of the previous commits for Syncthing, e.g. this one: https://github.com/SynoCommunity/spksrc/commit/737f502c02533738e4ed8b345dbc7157c08be123.
That more or less shows what needs to be changed: the cross package's Makefile + associated digests file, the spk's Makefile and check if the config file needs to be updated.
Set up a development environment as per the README, make the necessary changes to the package. Then build and test the package: if all goes well, you can open a PR.

**Comment by Dr-Bean** [comment]
Done with 3b6a42dbdd64a24b4351d4d12db10b8a1c2b346b
