### ISSUE TITLE
[request] PlexPy [$25]

### ISSUE THREAD

**Issue by mellowpimp** [SynoCommunity/spksrc#2183]
Hi, not sure if this is the right place, but i count find another place to make an request. 

Application name: PlexPy
Application link: https://github.com/drzoidberg33/plexpy
Application description: Monitoring tool for Plex.

Comments:
I know plexivity is available, which is a similar application, but in my experience, plexpy is more stable, and has a lot of more features. no offense to plexivity  

It works out of the box with a git clone (tested on my DS1815.)
only interfacing with the DSM package GUI would be needed for stopping and starting the package. 
##

**Comment by mellowpimp** [comment]
Added a reward, seems only fair as my request will take someone's time, effort and willingness to create it.

**Comment by rjblake** [comment]
@mellowpimp - I already created a native Synology SPK for it. Feel free to download it from [here](http://blake-world.com/files/plexpy.spk). You can start/stop from the Synology Package center once installed. The install script does not check for python and is only tested on DSM6.0. Donate the $25 to a worthy charity of your choice

**Comment by cytec** [comment]
i wouldn't suggest to use that SPK. there is no real package structure and the tool itself is run as root :/
basically seems more like a fast first try

**Comment by rjblake** [comment]
@cytec - perhaps you can elaborate on the 'no real package structure' - the install folders, scripts etc. are as per Synology's SPK developer's documentation. There are no 'hacks' or workarounds to get it added to package center and the PlexPy code can be validated against the master build version as in the package.tgz. The start-stop-status script runs using the su -c command due to the user creation issues with DSM6.0 that are well documented on spksrc [here](https://github.com/SynoCommunity/spksrc/issues/2216). Of course you can extract all the files and check exactly what they do. In the end, it's the PlexPy build you have to trust. Some others are quite happy with the solution as it stands right now ([plex.tv](https://forums.plex.tv/discussion/178104/help-installing-plexpy/p1).Use it or don't I have nothing to gain or lose.

**Comment by cytec** [comment]
@rjblake well perhaps i wasn't clear enough on what i mean: i don't say it's untrusted or not trust worthy... I know about the user creation issue and synology's hint on using `synouser` to create users it's just that i think running any package as root isn't a good idea at all. 

what i mean by 'no real package structure' isn't anything 'critical' either, as you say the scripts folder is as it should be and everything is fine... it's more like a 'cosmetic' thing to put plexpy in a seperate `share/plexpy` subfolder and create a `var` folder for your data so one can update the SPK if it's needed... basically i'm refering to a structure like `sickbeard-custom` uses :)

@mellowpimp building a SPK for this shouldn't be a problem once we decided how we want to deal with the user creation for DSM6... building a SPK with the current approach would only lead to several users complaining that it doesn't work with DSM6.

**Comment by rjblake** [comment]
@cytec - agreed on running the package as root (although there are plenty of packages that do so). As mentioned on the Plex.tv forum, a possible option is to run as the 'plex' user since PlexPy is only of use if you have Plex installed in the first instance. This is quick and easy fix.
My sickbeard-custom doesn't run unless I run it as root as I only installed after DSM6.0; so in that respect sickbeard-custom is also currently 'broken' on DSM6.0. The default data dir is in /usr/local/sickbeard-custom/var which I'd also not recommend, as this is the system drive and more likely to have space issues. The current PlexPy installer script currently creates a backup of the database and config; so an upgrade of the SPK will not overwrite the data and/or config.

**Comment by Diaoul** [comment]
@rjblake: `/usr/local/{package}` is a symlink to `/volumeX/@appstore/{package}/target` for all SynoCommunity packages. So no space issue.

**Comment by Diaoul** [comment]
I may add that user satisfaction isn't a good indicator of package quality. Take a look at some Synology packages, you'd be surprised the numerous hacks that you can find but hey, users are happy. If you want to contribute to spksrc, we always welcome PRs.

**Comment by rjblake** [comment]
@Diaoul - my bad - should have checked further than /usr for the location. Insofar as package quality - the only issue I see is the Synology synouser issue (awaiting info from Synology) and possible database location (easy fix). In the interim, as above, PlexPy will now run as the 'plex'  user

With regards the ' cosmetics' - hardly what I'd refer to as 'no real package structure' or reason to suggest not to use. To move a few files and folders to ${PACKAGE}/var/PlexPy and put some checks in for DSM5 or DSM6 is pretty quick and easy too. Alternatively, the exact same approach could be taken as the SickBeard-Custom installer and simply pull the GIT master.

The SPK is merely a way to easily install PlexPy for those who can't or don't want to hack around with the CLI and created in the absence of one here on SynoCommunity as the only other options around were to use Docker (cannot on the ARM based Synos), or manually create the install and required scripts.

**Comment by Diaoul** [comment]
The point here is either make a real contribution by making a PR so the package is conform to SynoCommunity's standards or don't contribute at all. `Hey I made a quick package for this and it works` isn't a worthy contribution, we cannot use that to make a package. The package, if associated with the name SynoCommunity could mislead users believing the package was developed by SynoCommunity and then the same users complain that the package is broken here even though SynoCommunity had nothing to do with it.

I believe @cytec was just pointing out the package was not issued by SynoCommunity and had some huge flaws as per SynoCommunity standards. Hence the recommendation. No offense.

**Comment by rjblake** [comment]
Ok - got it. Please point me to the documented standards for SynoCommunity so I can follow the required structure. And I do take offense to your claim regards 'huge flaws' - vastly exaggerated claim

**Comment by Dr-Bean** [comment]
@rjblake: You missed part of the quote there: `huge flaws as per SynoCommunity standards`. Not `huge flaws` in general. In other words: your current method of packaging is incompatible with spksrc and SynoCommunity. There's no need to take offense to that.

We like to think we have high code quality standards and release high quality packages. You're not required to follow our standards, unless you want to release a package via SynoCommunity/get code merged into spksrc.
Take a look: you'll see that every package follows the same approach, and on this scale, it helps to ensure maintainability and repeatability in the long run.

**Comment by cytec** [comment]
Thanks @Diaoul for clearing that up...  @rjblake Thats exactly what i ment! Most stuff i said was only in view of SynoCommunity standarts, i did not mean to offend you in any way :) and as you said everything i mentioned is easy fixable if you'd like to get this published/merged.

Using the Plex user isn't really a solution either, as that would lead to depending on the Plex SPK and would not be useful for users which want to install PlexPy to monitor a remote Server (aka. PMS not on the same DS)

**Comment by rjblake** [comment]
@Dr-Bean - clear as. At no time did I ever claim this was a SynoCommunity spk (clearly evident by it non availability through SynoCommunity). Will submit PR based on sickbeard-custom as this is quoted above as a leading example. @cytec regards the 'user' problem - I expect that every package on SynoComunity suffers from the adduser/synouser issue on DSM6.0 right now. What is the currently recommended SynoCommunity workaround for this currently?

**Comment by rjblake** [comment]
Have created the scripts as per Synocommunity and a Pull request - think I've created the request correctly...

**Comment by cytec** [comment]
done with: https://github.com/SynoCommunity/spksrc/commit/ac2200ce9be7e7065b4df4f8cb5d7b7748c7bc3a
