### ISSUE TITLE
Invalid location

### ISSUE THREAD

**Issue by balmhood** [SynoCommunity/spksrc#2184]
I was able to connect before and now it keeps stating invalid location each time i try to add http://packages.synocommunity.com  as a package source.

i have tried chnaging dns to google and opendns to no avail

DS213+ abd using  DSM 5.2-5644 Update 5

any idea?

**Comment by MrDushi** [comment]
I have the same issue:
DS216j
DSM 5.2-5644 Update 3

**Comment by balmhood** [comment]
added the google dns 8.8.8.8 in synology vs router and all works again
