### ISSUE TITLE
[REQ] Update nzbget-testing to version 17.x, c++14 required!

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#2185]
As title says, please upgrade nzbget testing to version 17.x
http://pastebin.com/TaCUYebS
##

**Comment by Dr-Bean** [comment]
This might not be possible. From what I see, C++ 14 is implemented fully in GCC5+. The DSM6RC toolchains are all GCC4.9.

Background of nzbget's reasoning here: https://github.com/nzbget/nzbget/issues/88.

**Comment by schumi2004** [comment]
Ow, to bad then. I was expecting something like this.

**Comment by Dr-Bean** [comment]
I would suggest to have a go at it with the DSM6RC toolchains anyway. Parts of the C++ 14 standard were introduced pre-GCC5, and that might be enough.

**Comment by hugbug** [comment]
GCC 4.9 is OK for NZBGet v17. Although GCC 4.9 doesn't fully support C++14 I'm doing extra efforts to ensure NZBGet works with GCC 4.9.

>checking whether /home/openelec/github/spksrc/toolchains/syno-alpine-5.2/work/arm-cortex_a15-linux-gnueabi/bin/arm-cortex_a15-linux-gnueabi-g++ supports C++14 features with -std=c++14... no

GCC 4.9 supports flag `-std=c++14`. Are you sure this is the output from GCC 4.9? Please post **config.log**, it usually includes full compiler versions.

**Comment by GoodOmens83** [comment]
Tried compiling the latest 17 development version (from github) with the 6.0 beta2 toolchains and everything compiled fine.  Can't test as I don't have 6.0 installed.

`checking whether to test compiler features... yes`
`checking whether /home/xxx/spksrc/toolchains/syno-avoton-6.0/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-g++ supports C++14 features by default... no`
`checking whether /home/xxx/spksrc/toolchains/syno-avoton-6.0/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-g++ supports C++14 features with -std=c++14... yes`

**Comment by Dr-Bean** [comment]
Thanks for the info @hugbug. The toolchain @schumi2004 was using is based on GCC4.6, so that's why those errors occurred (a lot of the NAS devices on the market use old versions of kernels/GCC/whatnot, which is a shame).

Seems that we shouldn't have an issue getting nzbget updated to latest once the final toolchains are included in spksrc, so that's good. Thanks for testing, @GoodOmens83.

Might as well reopen this issue so we can refer to it properly.

**Comment by schumi2004** [comment]
I'll do another attempt but it seems i don't have latest toolchain available in mij spksrc tree although it's updated.
Will report the outcome later today.

**Comment by Dr-Bean** [comment]
We haven't (and will not) add the DSM6RC toolchains. You can add one or more manually, e.g. copy a Makefile from an existing toolchain, and modify that.

**Comment by schumi2004** [comment]
Yeah did that but it returned an error.

This is my current make file http://pastebin.com/acSgxJ3W
And the error i get now http://pastebin.com/i7rdQrwE

Will check later today when i have more time.

**Comment by Dr-Bean** [comment]
Looks like a 32b host, and that's no good for DSM6 toolchains.

**Comment by schumi2004** [comment]
Is it? The spksrc readme suggest to use a 32b host instead of 64b.

**Comment by Dr-Bean** [comment]
Yes, but we're in the process of changing that. See https://github.com/SynoCommunity/spksrc/pull/2146

**Comment by hugbug** [comment]
@schumi2004: I can built NZBGet Linux installer of the current develop for you. Drop me a note via E-Mail with an info about CPU, if you are interested.

**Comment by GoodOmens83** [comment]
@schumi2004: My test compile was done on Debian 64 virtual machine.

I can post my Makefile but I just copied a 5.2 toolchain (renaming it synology-6.0-...) and just replaced the url with the 6.0 beta2 url.  `make setup dsm-6.0` will allow you to compile for 6.0.

**Comment by schumi2004** [comment]
@GoodOmens83 thanks i will try the same here.
@hugbug thanks for the offer but will first try it myself. for your reference, i was compiling it for a DS715, Alpine architecture.

**Comment by schumi2004** [comment]
Did some more testing with different vm's etc but something seems to be wrong with busybox. I'll drop my attempts for now and wait until final toolchain is released. First need to fix other things that are broken by DMS6

**Comment by cytec** [comment]
yeah would have been my suggestion too... DSM 6 seems to break like a lot... definitively to much for my liking to worry about a -testing package update... lets just hope they release the final TC's anytime soon and we don't have to wait ages

**Comment by d-zalewski** [comment]
v18 is out https://github.com/nzbget/nzbget/releases/tag/v18.0

**Comment by Safihre** [comment]
Test package for NZBGet has been released: #3138.
We no longer compile it here on the repo, but fetch the latest official installer from NZBGet.
During package installation you can choose if you want the latest stable or testing release. After this you can use NZBGet's internal update system to do updates.
We hope to soon publish this on the official repo.
