### ISSUE TITLE
[REQ] Ubooquity spk

### ISSUE THREAD

**Issue by burghy86** [SynoCommunity/spksrc#2190]
please, add on your repo this package?

a guide here:
http://vaemendis.net/ubooquity/wiki/doku.php?id=tutorial:synology:synology_nas_installation_tutorial

thank you so much.

**Comment by Dr-Bean** [comment]
Please use the search, we already have a request for this: https://github.com/SynoCommunity/spksrc/issues/1750. (and for future reference, please see [CONTRIBUTING](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#package-requests) and include the necessary info when opening a request)
