### ISSUE TITLE
sabnzbd 1.0 is out!

### ISSUE THREAD

**Issue by Stanzilla** [SynoCommunity/spksrc#2191]
https://github.com/sabnzbd/sabnzbd/tree/1.0.0

**Comment by lysin** [comment]
+1

**Comment by mhartvig** [comment]
Updated the testing channel to version 1.0.0 in #2194

**Comment by Stanzilla** [comment]
Why testing though? It's a final release?

**Comment by Dr-Bean** [comment]
That's a separate package, specifically for beta versions of Sab and people willing to test with that.
For stable, we're waiting on #2195 (or even a second PR that takes the comments there into account, either works)

**Comment by mbnn** [comment]
Are we getting 1.0 in the 'non beta' syno package pls?:)

**Comment by Popsikill** [comment]
Keep to get this up and running on my Synology :+1:

**Comment by mbnn** [comment]
Any update on the SABNZBD 1.0 release? :)

**Comment by Veldkornet** [comment]
I see #2195 has been closed and #2201 merged. 
Also the site is showing v1.0.0-15 -> https://goo.gl/4jXkQa

What else still needs to happen? My Synology isn't seeing the update yet.

**Comment by mbnn** [comment]
Same here :) Where is the 1.0 version pls? :)

**Comment by SmokE-PGF** [comment]
Doesn't show a way to update under the Package Center am I missing something?

**Comment by Dr-Bean** [comment]
Please be patient. If you want it immediately, feel free to compile it yourself.

**Comment by techabyte** [comment]
Sab on latest DSM removes unzip so sab is currently broken till 1.0 is pushed or releases a fix for 0.7 to use 7zip :/

**Comment by r33mi** [comment]
Rest is working fine, upgraded my SABnzbd myself. unzip is broken though...

**Comment by SmokE-PGF** [comment]
Ran Sab in a docker container seems to have fixed everything even unzips fine

**Comment by Diaoul** [comment]
Well of course, Docker is like another machine. That workaround is limited to NASes able to run Docker in the first place.

**Comment by jarrod-s** [comment]
As Veldkornet noted the individual package entry shows - SABnzbd v1.0.0-15 
However in the main index of all packages shows - SABnzbd v0.7.20-14 
I assume Synology Package Centre compares to the main index so does not believe there is an update.

**Comment by mbnn** [comment]
Says: https://synocommunity.com/packages  0.7.20 aswell, so I guess it's not done yet ;)

**Comment by loli71** [comment]
https://synocommunity.com/packages show SABnzbd v0.7.20-14 
https://synocommunity.com/package/sabnzbd show SABnzbd v1.0.0-15  ....
My Synology Package Centre show SABnzbd v0.7.20-14 :-(

Maybe a little issue in package publication on synocommunity ?

**Comment by mbnn** [comment]
That is strange indeed, I guess @Diaoul can answer that.

**Comment by cytec** [comment]
@Diaoul that's stange.. i've just checked and as @loli71 said the homepage provides 0.7.20 the package detail page 1.0.0 but there is no 1.0.0 build anywhere in the repo but there is a 1.0.0 entry in the versions table ... maybe there went something wrong on the repo site?

**Comment by Dr-Bean** [comment]
Not strange. I noticed an issue and removed the packages again. I'll remove the version, so people don't get confused.

**Comment by loli71** [comment]
Thanks cytec for the clarification.
One question, if I compile it by myself (with spksrc) as proposed Dr-Bean, and use manual installation in DSM, will futur version provided by synocommunity will be see as update for my own compilated package ?

**Comment by cytec** [comment]
ha thanks @Dr-Bean now it all made sense ;)
