### ISSUE TITLE
DataTables warning (Plexivity)

### ISSUE THREAD

**Issue by eikewink** [SynoCommunity/spksrc#2204]
If i hit History i get the folloiwing Error:
DataTables warning: table id=globalHistory - Ajax error. For more information about this error, please see http://datatables.net/tn/7

DS115J DSM 6.0
##

**Comment by cytec** [comment]
seems like a issue with plexivity itself... please report upstream

**Comment by eikewink** [comment]
Where ? Do you have a link ?




Gruß,Eike Winkelmann

-------- Ursprüngliche Nachricht --------
Von: cytec <notifications@github.com> 
Datum: 24.03.2016  11:09  (GMT+01:00) 
An: SynoCommunity/spksrc <spksrc@noreply.github.com> 
Cc: eikewink <eike@quickbornheide.de> 
Betreff: Re: [spksrc] DataTables warning (Plexivity) (#2204) 

seems like a issue with plexivity itself... please report upstream

**Comment by cytec** [comment]
https://bitbucket.org/raphaelmutschler/plexivity
