### ISSUE TITLE
[request] ruTorrent login to web page

### ISSUE THREAD

**Issue by kzendra** [SynoCommunity/spksrc#2206]
Currently only way to protect ruTorrent is to have it accessible from local network only (not very secure) or to use .htaccess (very complicated for beginner)
ruTorrent could use logins from synology, or create it's own logins. Anything that would enable beginner to setup the secure access...
##

**Comment by GoodOmens83** [comment]
A more robust login process would be up to ruTorrent to implement.  As far as I know there is no way to "hook" into the DSM login process from a third party app.  That leaves htaccess as the only option.

**Comment by abraxxa** [comment]
There is the single-signon package from Synology, maybe that can be leveraged to implement this feature.

**Comment by Dr-Bean** [comment]
The SSO package doesn't integrate with DSM accounts, but maintains a separate user DB as far as I know.
As for an authentication mechanism: Synology provides the functionality (see dev guide, `Integrate with DSM Web Authentication`. I don't think we have packages using it though. We've had some attempts in the past, (look at Zabbix PR's), which may help as a starting point.

**Comment by dolphinkite** [comment]
How about simply adding the .htaccess (or something similar) within the package, with simple but detailed instructions on how to set it up?

**Comment by Safihre** [comment]
Closing due to age, maybe we can add to #3175.
