### ISSUE TITLE
[request] Glances

### ISSUE THREAD

**Issue by R0GGER** [SynoCommunity/spksrc#2208]
**Website:** http://nicolargo.github.io/glances/
**Description:** Glances is a cross-platform curses-based system monitoring tool written in Python.
**Documentation:** http://glances.readthedocs.org/en/latest/ and/or https://github.com/nicolargo/glances/wiki 
**Build/Installation documentation:** https://github.com/nicolargo/glances#installation
**Source code:** https://github.com/nicolargo/glances
**License:** LGPL

**Screenshot:**
![screenshot-wide](https://cloud.githubusercontent.com/assets/8298741/14835024/f2b0e256-0c07-11e6-9200-095d0908e8e8.png)

**Comment by Dr-Bean** [comment]
Please follow instructions in CONTRIBUTING: https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#package-requests

**Comment by R0GGER** [comment]
@Dr-Bean Better now?

**Comment by cytec** [comment]
@R0GGER much better thanks ;)

**Comment by schumi2004** [comment]
Just found out about Glances and was wondering if the autoinstall script is sufficient enough to get it running?

**Comment by cytec** [comment]
@schumi2004 since it's a python app (and i think the python SPK comes with psutil already) a simple `/usr/local/python/bin/pip install glances` should be enough to get it installed ;) keep in mind that you'll have to reinstall it after an python update... to avoid that step try using a virtualenv ;)

**Comment by cytec** [comment]
strange... i've tested it and it worked for me :/

**Comment by schumi2004** [comment]
Mmmm strange. I'm trying it on a DS715 maybe that's the issue?

https://pastebin.com/x4bXABdL
