### ISSUE TITLE
[selfoss] problems with writing new entries to mariadb

### ISSUE THREAD

**Issue by thatgim** [SynoCommunity/spksrc#2210]
Since my upgrade to DSM 6.0-7321 selfoss seems inable to write new entries to mariadb. Reading data seams fine. Even altering (e.g. changing read/unread) existing entries works.

I connect via ssh and executed the update script which resulted in den following error:
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /volume1/web/selfoss/libs/f3/db/sql.php on line 397
Fatal error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'

Versions:
mariadb 5.5.47-0064
selfoss 2.13-6
DSM 6.0-7321
on a DS413
##

**Comment by gimbar** [comment]
Sry, missed the right thread :(
Please deletes this. I'll post it again at the right location

**Comment by Normaniac** [comment]
This fixed it for me (sort of): https://forum.synology.com/enu/viewtopic.php?f=20&p=426548

Seemed to be two versions of php. Using "php56" instead of "php" via cli worked so far.
