### ISSUE TITLE
Problems with Transmission after update to version 2.92-12

### ISSUE THREAD

**Issue by def1ance** [SynoCommunity/spksrc#2211]
Hello, 

i've recently updated the package for transmission to version 2.92-12 on my DS214+ which is still using DSM version 5.2-5644 update 3. Sadly i've realised that theres a new DSM version after i've finished the update and that the new package proberbly is for the new DSM version - but i dont want to install this DSM update yet. 

Since this update transmission doesn't get any connection (peers) from the broadcast server from the torrent. Under "info" State is "downloading" and according the trackers info there are several peers (seeder/leecher) but it stays idle. I tested downloading with a different client (on non NAS) and there i didn't had any problems. I've double checked (port) settings but i can't find any error on my site. Had no problems before the update either. 

Is there a known bug with the new package and the old version? Is it possible downgrade to the old version?

Thanks and best regards, 
def

**Comment by GoodOmens83** [comment]
I would look at your firewall settings under security to make sure the firewall is not enabled (or if it is the proper ports are set up).

What does "Preferences >> Network >> Ports" say?  Is the port open?

**Comment by def1ance** [comment]
Hello, 

port is stating "open" yes. My firewall settings (on NAS and router) are okay - i've set a new port, too. I already reinstalled the package, too. Sadly without success.

**Comment by Dr-Bean** [comment]
I doubt that it's package related to be honest, we'd see a lot more people reporting this if that were the case.
Maybe check if adding a popular, public torrent (something like a Linux ISO for example) works? I'm thinking there might be trackers that have banned this version of Transmission (no idea how that shows up in the Transmission interface, could be worth a shot)

**Comment by Dr-Bean** [comment]
@def1ance Any info here?

**Comment by def1ance** [comment]
@Dr-Bean i've installed DSM 6 on my DS and everything seems to be working fine. You can close this issue.

**Comment by Dr-Bean** [comment]
For future reference, you can close your own issues yourself :)
