### ISSUE TITLE
nzbget and nzbget-testing both fail

### ISSUE THREAD

**Issue by tarnished1** [SynoCommunity/spksrc#2212]
Hi~
   Thank you for all your work.

nzbget, and nzbget-testing both fail with 

Starting NZBGet Testing ...
/usr/local/nzbget-testing/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget-testing/bin/nzbget)
/usr/local/nzbget-testing/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget-testing/bin/nzbget)
/usr/local/nzbget-testing/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget-testing/bin/nzbget)

Modle: DS1815+
DSM Version: DSM 6.0-7321

**Comment by Dr-Bean** [comment]
Use #2207 please. You migt need to wait for the DSM6 toolchains.
