### ISSUE TITLE
SynoCommunity not visible in DS412+ Package Center

### ISSUE THREAD

**Issue by rudolftanner** [SynoCommunity/spksrc#2213]
I want to install DebianChroot again - but following https://synocommunity.com/ fails,
it used to work on an old DMS version.

Is this a DMS DSM 6.0-7321 / Synology issue or a SynoCommunity server problem?
Since I have not found and answer in any forum, this appears to be a new issue.

**Comment by BKSteve** [comment]
Have you tried the classic method of following the main setup steps, 
Step 2
http://packages.synocommunity.com/

**Comment by rudolftanner** [comment]
Closed. 


After another few trials it worked. Now I battle to be able to login into debian with root. 
I had assumed that this is due to V6, as I saw a statement that it supports 5.2 and earlier versions but not V6. 
Thanks for coming back. 
----- Original Message -----

**Comment by Dr-Bean** [comment]
Closing, as the original issue has been resolved. Anything else fits better in the issue we have for Debian Chroot and DSM6: https://github.com/SynoCommunity/spksrc/issues/1910
