### ISSUE TITLE
Owncloud: Data Folder outside web root

### ISSUE THREAD

**Issue by caco3** [SynoCommunity/spksrc#2214]
It seems to be impossible to move the Owncloud data folder outside the web root. This however is a serious security issue!
I guess this is based on some Synology restrictions. How ever if it still would be possible, please modify the installer so it uses a data folder outside the web root, i.e. `/volume1/owncloud_data`

**Comment by Dr-Bean** [comment]
'Seems' indeed. You are free to choose any location, but putting it in the web root is definitely not recommended and generally speaking a bad idea. We even set the default to be `/volume1/owncloud`.

Why do you think it's impossible to use a different location?

**Comment by caco3** [comment]
Due to the issue in https://github.com/SynoCommunity/spksrc/issues/2136 I am not able to test it with a fresh install on DSM 6.
When I modify the owncloud config file myself to move the data folder outside the web root, I get this errors:
```
Data directory (/volume1/owncloud_data) is invalid
Please check that the data directory contains a file ".ocdata" in its root.
```

All through the folder and the file exist and are readable by everybody.

Furthermore, I get this error:
```
Cannot create "data" directory (/volume1/owncloud_data)
This can usually be fixed by giving the webserver write access to the root directory.
```

I believe there is an open base dir restriction in action.
So I wonder why the installer still suggests this impossible setup!

**Comment by Dr-Bean** [comment]
Yes, you'll encounter issues with DSM6: the package is currently not compatible with DSM6. Those issues will be solved in due time.

However, you haven't answered my question. I'm still not clear where your idea comes from that our installer 'suggests this impossible setup'? It doesn't. 
During package installation, the wizard suggests that you put your data in `/volume1/data`. You can edit to suit your needs.
Based on the input in the wizard, permissions and open basedir restrictions are set accordingly during the actual package installation. Nowhere do we suggest to use the webroot.

Editing the datadir manually afterwards is possible, as long as you know what things to adjust. See the installer in spk/Owncloud/src/installer.

**Comment by Dr-Bean** [comment]
Closing, not enough info, and as far as I can tell, it's not an issue with the package.
