### ISSUE TITLE
DSM6 Can't install  Tiny Tiny RSS on fresh installed synology

### ISSUE THREAD

**Issue by ivanwin** [SynoCommunity/spksrc#2217]
Hi,
I've seen this error trying to install tt-rss on my new synology.
Filling the wizard, i got this error
"Incorrect MySQL root password"

After checking several things, i've found that the installer var:
MYSQL="/usr/syno/mysql/bin/mysql"
target to something that doesn't exists.

the bin mysql installed by the mariaDB packages was found in:
/volume1/@appstore/MariaDB/usr/bin/mysql
or
/usr/bin/mysql

I've put a link in /usr/syno/mysql/bin/mysql pointing to /usr/bin/mysql
and it worked

**Comment by Dr-Bean** [comment]
We'll probably have to use `/usr/bin/mysql` in all packages, because people can use a different volume to install MariaDB. The approach will probably be similar to [this](https://github.com/SynoCommunity/spksrc/blob/master/spk/tt-rss/src/installer.sh#L11). 

PR's are welcome, but please note that this affects all packages using MariaDB, not just tt-rss.

I'm closing this one as a duplicate, seeing as we already have an open issue for the same reason: #2093. Let's continue there.

**Comment by digifreak** [comment]
I just tried to install tt-rss (V. 1016102-10) but the problem seems to persist.
Have you got a solution so far?

**Comment by ivanwin** [comment]
Try to create the link manually with a root account:
 ln -s /usr/bin/mysql /usr/syno/mysql/bin/mysql
that should do the trick.

You'll probably be annoyed with updating feed scripts,
and should update PHP path into those scripts.

**Comment by digifreak** [comment]
Thanks for your help.
But it after typing your command it says that there is no such file or directory

**Comment by ivanwin** [comment]
ls /usr/bin/mysql gives nothing?
Do you have mariaDB package installed?

On 26 May 2016 at 22:18, digifreak <notifications@github.com> wrote:

> Thanks for your help.
> But it after typing your command it says that there is no such file or
> directory
>
>
>
>
> > Am 26.05.2016 um 21:17 schrieb ivanwin <notifications@github.com>:
> >
> > Try to create the link manually with a root account:
> > ln -s /usr/bin/mysql /usr/syno/mysql/bin/mysql
> > that should do the trick.
> >
> > You'll probably be annoyed with updating feed scripts,
> > and should update PHP path into those scripts.
> >
> > —
> > You are receiving this because you commented.
>
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SynoCommunity/spksrc/issues/2217#issuecomment-221982462>
>



-- 
*Ivan GOUIN*

*Mob (Suisse**)* : +41 (0)79 941 07 90
*Mob (France**)* : +33 (0)7 83 699 077

*Mail* : gouin.ivan@gmail.com

**Comment by Renkua** [comment]
On my Synology, i have to do 
```
sudo mkdir /usr/syno/mysql
sudo mkdir /usr/syno/mysql/bin 
```
before the link

**Comment by digifreak** [comment]
> ls /usr/bin/mysql gives nothing?
Do you have mariaDB package installed?

Yes, I installed mariaDB on my synology.

**Comment by digifreak** [comment]
Ok, I made the two directories
(sudo mkdir /usr/syno/mysql
sudo mkdir /usr/syno/mysql/bin)

When I try to link the folder, o got an "permission denied" error...
(Sorry, but I am not exactly an expert using unix ;) )
I think I need to change the right. But what are the appropriate rights?

**Comment by Renkua** [comment]
Do you use sudo for your command?

sudo ln -s /usr/bin/mysql /usr/syno/mysql/bin/mysql

It works for me

**Comment by digifreak** [comment]
Thank you all for your patience and willingness to help!

Sudo did the trick. I thought that beeing logged in as root, I would have all rights.
Great - now I hav my own rss server :)

**Comment by johnflavin** [comment]
To anyone finding this in the future, a fresh install of Maria DB 5 on DSM 6.1.4 will install (a link) to `/bin/mysql`, not `/usr/bin/mysql` as in the comments above. So to get Tiny Tiny RSS to install you should execute
```bash
$ mkdir -p /usr/syno/mysql/bin
$ sudo ln -s /bin/mysql /usr/syno/mysql/bin/mysql
```

**Comment by Daopr** [comment]
thanks for all your helps, I finally installed maria db 5 on dsm 6.1.4, and so does the ttrss.

**Comment by MateMathieu** [comment]
Hi all,
It would be excellent if the maintainer can switch to Maria DB 10 and fix this folder/link issue on the community package provided by the synocommunity.
This is the kind of small polish that makes the use of open-source software likelier to popularize it.
Thanks for the hard work already done!
