### ISSUE TITLE
Can not start any SynoCommunity package

### ISSUE THREAD

**Issue by cacaelm** [SynoCommunity/spksrc#2218]
Hi, I bought a new DS216play and can not get any SynoCommunity package running. They are installed, but not able to run the applications. Got the message "Kon pakket service niet uitvoeren".

Have followed the instructions as presented, but believe this might be an autorization issue. Are there details on required autorizations / users / groups?

**Comment by GoodOmens83** [comment]
If you are running DSM6 - new installs are currently broken do to changes made by Synology that breaks a lot of things.  See this thread: 

https://github.com/SynoCommunity/spksrc/issues/2207

There is no timeline for a fix.

**Comment by Dr-Bean** [comment]
Yep, thanks @GoodOmens83 :) Closing this one as a duplicate.
