### ISSUE TITLE
Invalid package source location on VirtualDSM

### ISSUE THREAD

**Issue by kraades** [SynoCommunity/spksrc#2219]
When I try to add the package source location http://packages.synocommunity.com on VirtualDSM I get a _Invalid location_ error message.

The idea was to test packages on VirtualDSM before installing it on the host itself. At the moment this is not possible.

In my case the host is braswell arch (model DS716+) and the guest is kvmx64 arch (model VirtualDSM).

DS716+:

```
admin@DS716:~$ uname -a
Linux DS716 3.10.77 #7321 SMP Wed Mar 23 11:48:26 CST 2016 x86_64 GNU/Linux synology_braswell_716+
admin@DS716:~$]
```

VirtualDSM:

```
admin@DS716V:~$ uname -a
Linux DS716V 3.10.77 #7321 SMP Wed Mar 23 11:46:53 CST 2016 x86_64 GNU/Linux synology_kvmx64_virtualdsm
admin@DS716V:~$
```
##

**Comment by Dr-Bean** [comment]
I'll mention it here too: spksrc has to integrate the DSM6 toolchains before this can be added. We can easily add `kvmx64` and probably `dockerx64` (#1889) it to `TC_ARCH` in x64-6.0 (or see if we can switch over to Synology's format: `arch="x86_64"`)

**Comment by kraades** [comment]
It would be great if we can test the effects of a new DSM version on packages first on VirtualDSM before applying the new DSM version to the "production" machine. Especially with the latest DSM versions when it is not always obvious that packages keep working. So it would be great if kvmx64 support for VirtualDSM could be added (so we can also install the packages on VirtualDSM). Thanks.

**Comment by Dr-Bean** [comment]
Done via 31e654b3526dbb6c21472551ed43203557aca741. This is currently a separate branch, but will be merged into master.

**Comment by Dr-Bean** [comment]
...and in case it's not clear, packages won't show up yet. See https://github.com/SynoCommunity/spksrc/issues/2216#issuecomment-271852804 for more info.

**Comment by akafester** [comment]
Is this fixed?

**Comment by kraades** [comment]
Maybe fixed, but not yet in production. See ^^^.
