### ISSUE TITLE
btsync not running

### ISSUE THREAD

**Issue by pamporo** [SynoCommunity/spksrc#2220]
After upgrading my DS 415+ to DSM 6.0-7321, Btsync is not running anymore. I've tried to manually upgrade the app to 2.3.6 and also uninstall and reinstall with no success. Every time I try to run the package I get the error "Failed to run package service" .

Logs: 
http://pastebin.com/raw/EN4yLEmu

**Comment by Dr-Bean** [comment]
We haven't provided a BTSync package in quite a while. Please report to the BTSync package developers.
