### ISSUE TITLE
[REQUEST] autodl-irssi for rutorrent

### ISSUE THREAD

**Issue by R1skNt** [SynoCommunity/spksrc#2221]
could you please compile this plugin to work on rutorrent
##

**Comment by pannbiff** [comment]
it does work on rutorrent in DSM 6.0, but it would be nice to have it available in package center :)

**Comment by pannbiff** [comment]
Im currently running irssi + autodl through debian chroot, but has anyone tried the autodl-irssi together with the irssi package offered by SynoCommunity?

**Comment by Dr-Bean** [comment]
Please follow instructions in CONTRIBUTING: https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#package-requests

**Comment by GoodOmens83** [comment]
Just follow the instructions here:

https://github.com/autodl-community/autodl-rutorrent/wiki:

>Navigate to the ruTorrent plugin directory. If using the official version of the ruTorrent plugin, remove the autodl-irssi directory found there.

`sudo /volume1\@appstore/git/bin/git clone https://github.com/autodl-community/autodl-rutorrent.git autodl-irssi`
`sudo cp autodl-irssi/_conf.php autodl-irssi/conf.php`
`sudo chown -R rutorrent:http autodl-irssi`

The plugins directory should be something like `/volume1/web/rutorrent/plugins'

**Comment by pannbiff** [comment]
This is also needed:

https://github.com/autodl-community/autodl-irssi/wiki/Manual-Installation

> Note: Make sure you're not root when you execute the following commands.

`mkdir -p ~/.irssi/scripts/autorun
cd ~/.irssi/scripts
curl -sL http://git.io/vlcND | grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)' | xargs wget --quiet -O autodl-irssi.zip
unzip -o autodl-irssi.zip
rm autodl-irssi.zip
cp autodl-irssi.pl autorun/
mkdir -p ~/.autodl
touch ~/.autodl/autodl.cfg`

**Comment by r1sknt** [comment]
thanks guys for your contribution, firstly I have  done the setup for rutorrent and rtorrent manually not from the synocommunity package, and  i managed to get the plugin "autodl' works on the "rutorrent web-ui" 
the problem is on how te setup irssi properly and connect it with the autodl plugin.

i have followed this 
https://github.com/autodl-community/autodl-irssi/wiki/Manual-Installation
&
https://github.com/autodl-community/autodl-rutorrent/wiki:
but the irssi didn't work as usually like on pure linux distro.

@GoodOmens83 why would i need to install the plugin here
`/volume1\@appstore/git/bin/git` 
?

shouldn't be on the rutorrent plugin folder?

**Comment by GoodOmens83** [comment]
@r1sknt - I never said to install it in that directory.  That line you quoted is git and is used to pull the latest repository from the internet - you left out the other half of my line.

You would need to do something like (assuming you have the git package installed):

`cd /volume1/web/rutorrent/plugins`
`sudo /volume1\@appstore/git/bin/git clone https://github.com/autodl-community/autodl-rutorrent.git autodl-irssi`

**Comment by pannbiff** [comment]
i havent figured out how to get it to work with Irssi from the SynoCommunity package, i dont know where to put the scripts and autodl folder. Screen or something similair is also needed to make irssi run in the background, can this be installed?

I currently run debian chroot where i could install irssi and screen. I put script folder and autodl folder in my home folder and it works. 

But it would be so much easier if i wouldnt need debian chroot to make it work.

**Comment by bamtan** [comment]
@pannbiff is your ruTorrent still functioning? I'd appreciate some assistance in setting it up on my 216J.

**Comment by th0ma7** [comment]
New updated `rutorrent` package will be made available in the short future.
This `autodl-irssi` is not set to be included in this next release.
Feel free to re-open with a method to implement it so we can include it in a subsequent revision of the package.
