### ISSUE TITLE
Transmission Web Client is getting creazy under Chrome

### ISSUE THREAD

**Issue by Sadomodo** [SynoCommunity/spksrc#2228]
Hello,
Since the last update 2.92-12, the web client - with chrome - is constantly refreshing the interface so I cannot do anything with it. Tested on two different PC.
With Edge for instance, it works properly.

**Comment by Dr-Bean** [comment]
Report this upstream please. If there's a bug in Transmission, the Transmission devs should be able to confirm and fix it.
