### ISSUE TITLE
Can't use parameters and directories with subliminal with DSM 6

### ISSUE THREAD

**Issue by kanaweb1** [SynoCommunity/spksrc#2229]
Hi,

I was using subliminal from several years on my nas synology but after a crash, i upgraded it from DSM5 to DSM 6. 
And now I can't write anything in parameters . I found a workaround (I hope) in editing config.ini and it seems to work but I don't know how to edit directories to be scanned. Indeed, when I click on Directories and Add , I can't browse any directory.

Can someone help me ?

Best regards,
Fabrice

**Comment by Dr-Bean** [comment]
As shown in #2207 and #2107 amongst others, DSM6 has changed things significantly. Built-in interfaces won't work, so until that's solved, you might want to consider switching to command-line/shell scripts/tasks for what you want to do.
