### ISSUE TITLE
SynoCommunity not working when going through VPN

### ISSUE THREAD

**Issue by Manfred73** [SynoCommunity/spksrc#2231]
I have activated openVPN (Private Inernet Access) on my Synology and all traffic goes through this VPN.
However, when I want to browse / install packages from the SynoCommunity, this doesn't seem to work: I don't see any packages. When I disable VPN connection, it is working. Using DSM 6.0-7321.

**Comment by Dr-Bean** [comment]
That's _because_ all traffic is routed through the VPN. The device has no way to route to outside locations when the VPN is active, so it can't reach the repository.
I don't know if the VPN software supports it, but you'd need a static route or exception to route the traffic to SynoCommunity outside of the VPN.

**Comment by Dr-Bean** [comment]
Closing. I don't believe this is something we can influence. It probably makes sense to see what Synology has to say about this: you should open a support request.
