### ISSUE TITLE
[DSM 5.2][DS112+][chroot] apache2 package not working.

### ISSUE THREAD

**Issue by mskyaxl** [SynoCommunity/spksrc#2233]
Apache hangs and it is not replying to requests:

```
chroot@DiskStation:~ >wget 192.168.1.110/index.html
--2016-04-04 01:13:16--  http://192.168.1.110/index.html
Connecting to 192.168.1.110:80... connected.
HTTP request sent, awaiting response... 
```

Apache version:
`chroot@DiskStation:~ >apache2 -version
Server version: Apache/2.4.10 (Debian)
Server built:   Jan  3 2016 04:19:40`

error.log shows
```

[Mon Apr 04 01:31:56.607622 2016] [core:error] [pid 1436:tid 1308619824] (38)Function not implemented: AH02179: apr_socket_accept: (client socket)
[Mon Apr 04 01:31:57.616987 2016] [core:error] [pid 1467:tid 1308619824] (38)Function not implemented: AH02179: apr_socket_accept: (client socket)
[Mon Apr 04 01:31:58.627040 2016] [core:error] [pid 1498:tid 1308619824] (38)Function not implemented: AH02179: apr_socket_accept: (client socket)
[Mon Apr 04 01:31:59.636984 2016] [core:error] [pid 1531:tid 1308619824] (38)Function not implemented: AH02179: apr_socket_accept: (client socket)
[Mon Apr 04 01:32:00.647017 2016] [core:error] [pid 1559:tid 1308619824] (38)Function not implemented: AH02179: apr_socket_accept: (client socket)
[Mon Apr 04 01:32:01.656969 2016] [core:error] [pid 1589:tid 1308619824] (38)Function not implemented: AH02179: apr_socket_accept: (client socket)
[Mon Apr 04 01:32:02.667139 2016] [core:error] [pid 1618:tid 1308619824] (38)Function not implemented: AH02179: apr_socket_accept: (client socket)
[Mon Apr 04 01:32:03.676917 2016] [core:error] [pid 1648:tid 1308619824] (38)Function not implemented: AH02179: apr_socket_accept: (client socket)
```

Diskstation architecture: 88f6282(DS112+)

Possible solution: re-compiling the right apr* pachages?

**Comment by Dr-Bean** [comment]
This is from inside Debian Chroot? I don't know that we have any control over that from a packaging perspective. Are you sure the issue doesn't exist because port 80 is already in use?

**Comment by mskyaxl** [comment]
Thanks for the reply!

Yes, this is from Debian Chroot. 
and
Yes, I am sure that the issue it's not because of port 80 because I was able to compile the apache2 independently, not as a package and the issue is not occurring anymore.

I've tried also to compile the debian package by myself but got stuck in all kind of errors, obviously I'm not too experienced in that area. I wanted it to have it as debian package to ease the configuration. 

My impression was that you also have control on these packages but if this is not the case than obviously this issue can be closed.

**Comment by Dr-Bean** [comment]
There's only one way to set up the chroot as far as I know, and that's to use debootstrap as shown here: https://github.com/SynoCommunity/spksrc/blob/master/spk/debian-chroot/Makefile#L55.

All the packages that you install, including Apache, come from one of Debian's mirrors, there's nothing special about that. Could be something related to the arch, but that's all I got ;)

**Comment by mskyaxl** [comment]
Than this issue can be closed. I don't think it's related to arch as I was able to compile apache2 on target using the utils installed from debian mirrors and I got it running.
Thanks for analysis!
