### ISSUE TITLE
TinyRSS Version Information

### ISSUE THREAD

**Issue by live4truths** [SynoCommunity/spksrc#2234]
Greetings.

I am likely missing something completely, but I am looking for clarity of version information for the TTRSS package.

Version information on synocommunity shows 20160102-10, which does not really reference any rolling release on the TTRSS Git

I would like to compare what version is what. I am also looking for any information anyone has about using the rolling releases once installed. How do we update TTRSS?

Thank you.

**Comment by Dr-Bean** [comment]
See the cross package: https://github.com/SynoCommunity/spksrc/blob/master/cross/tt-rss/Makefile#L4.

Updating tt-rss can be done via updating the package. Feel free to open a PR (after testing!). See the README and CONTRIBUTING for more details.

**Comment by live4truths** [comment]
@Dr-Bean Unfortunately, I do not believe I am start enough to do any legitimate testing on TTRSS (or any package) for mass production... My concern comes from Fox (Dev of TTRSS) patching a major vulnerability recently, and the version we have available here is significantly older than that.

I do not understand "updating the package", I am probably being ignorant but, cannot figure out  how to  update it manually.

Thank you for your time, what you do here is fantastic.
