### ISSUE TITLE
sabnzbtest 1.0.0-5 failed to run package

### ISSUE THREAD

**Issue by zstkeyboard** [SynoCommunity/spksrc#2236]
DSM 6.0-7321
RS3411xs

I've ran it from the command line
/var/packages/sabnzbd-testing/scripts/start-stop-status start

first output was that the user didn't existed, created the user manual and ran the script again.

needed to input password than got the error Permission denied.
i've added the user to the admin group and the issue still exist.

how can i check the rights and fix it

regards

key

**Comment by Martijn085** [comment]
Packages or not runing on DMS 6 at the moment, see: https://github.com/SynoCommunity/spksrc/issues/2216

**Comment by zstkeyboard** [comment]
thx Martijn085

I'll remove the package add the user and install the package again.
see if that will work 
key
