### ISSUE TITLE
DSM5.2: Rutorrent wont Run 

### ISSUE THREAD

**Issue by DeanoBeano** [SynoCommunity/spksrc#2240]
Ok so i am probably  doing something wrong but it wont run every time i try it just stops.

So i have followed the instructions on install but is it as simple as install this package and you have a fully working Rutorrent or is there something else i need to install ? or add ?

DSM 5.2    DS213J 

Thanks for any help 
Deano 
##

**Comment by pannbiff** [comment]
Webstation is enabled? 

When installing theres something with openbase_dir that needs to be unchecked?

web/rutorrent needs permission set to 0755

**Comment by DeanoBeano** [comment]
ok so i have now disabled Openbase_dir 

 But how do i set web/rutorrent  permission to 0755  ?

**Comment by pannbiff** [comment]
Log in as root with your ftp-client (WinSCP is free if you dont have one). Should be same password as your main user. Then Right click on the rutorrent in /volume1/web/ (or which volume you use), choose properties and then change permission to 0755.

**Comment by DeanoBeano** [comment]
Ok thanks for help to be honest i think i will wait  now till it comes out of beta  and just stick with transmission that comes with  the DSM .

**Comment by Dr-Bean** [comment]
Try the new package in the meantime. Should work out of the box (at least, from what I can see...)
If it's not visible in Package Center yet, check again in an hour or two.

**Comment by DeanoBeano** [comment]
Same problem with the new package :(

**Comment by pannbiff** [comment]
The problems i had disappered when i updated, but it did remove the autodl plugin.

**Comment by nex6** [comment]
_Model and arch of your NAS_. DS415Play - evansport x15

_DSM version;_ 6.0-7321 Update 1 2016/04/14

_Provide log files if available:_ No log files available

_If the package doesn't start, try to start the package via the command line and provide the output: _"Starting ruTorrent ..." Checking status directly after generates: "ruTorrrent is not running"

Have had some problems with SSH service not possible to start so I re-installed DSM today, installed Webstation and then directly tried to install ruTorrent from the Synocommunity package, after installation package will not run, is doing something for a couple of seconds and then stopped again. Everything else working as it should.

First try to start manually, I got an error **"unknown user rutorrent"** so I created a rutorrent user and when trying again I get message **"Starting ruTorrent ..."** but nothing happens..

Would really appreciate some assistance, not a complete n00b but pretty close :)

**Comment by Dr-Bean** [comment]
@nex6 Rutorrent and DSM6 belongs in https://github.com/SynoCommunity/spksrc/issues/2215

**Comment by omegadaniel** [comment]
I'm also experiencing this issue. DS415play, DSM 5.2-5644 Update 5

**Comment by Safihre** [comment]
I worked on new DSM5/6 compatibility but got stuck, I did the basic work but need some help to figure out the right paths to config files etc. If you want, you can help me here: #3175.

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #2215 and maybe PR #3175.
