### ISSUE TITLE
HAproxy not available on DS414

### ISSUE THREAD

**Issue by cyrilphoenix71** [SynoCommunity/spksrc#2244]
Hello,
I try to install HAproxy package on a ds414 but Unfortunatly, it's not working.
At the end of the installation, I got a message "Failed to start or repair the package"
==> The exact message in frenc was "Echec lors du lancement de la reparation du paquet"
Now the package appears to be installed, but stoped. If I try to start it, I get the same message again.

Can you help me ?
Thanks
Cyril
##

**Comment by Dr-Bean** [comment]
Please follow instructions in the guidelines when reporting an issue. See CONTRIBUTING: https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issue-content

**Comment by lexyan** [comment]
SSL certificate are not in the same folder under DSM6, you need to modify the file '/usr/local/haproxy/app/application/direct.py' and add `if os.path.isfile(u'/usr/syno/etc/certificate/system/default/fullchain.pem'):
		listCRT = [u'/usr/syno/etc/certificate/system/default/privkey.pem',u'/usr/syno/etc/certificate/system/default/fullchain.pem']` on line 94 before `with open(self.crt_path, 'w') as crt:`

plus you need to correct the file /etc/shadow to add haproxy user, as the command adduser is broken in dsm6 and users are removed after reboot.

**Comment by Safihre** [comment]
Further HaProxy updates (like DSM6 compatibility) will be handled in #2712.
