### ISSUE TITLE
[request] nmon

### ISSUE THREAD

**Issue by fritz001** [SynoCommunity/spksrc#2247]
Description: nmon is short for Nigel's performance Monitor for Linux on POWER, x86, x86_64, Mainframe & now ARM (Raspberry Pi)
Website: http://nmon.sourceforge.net/pmwiki.php
Documentation: http://nmon.sourceforge.net/pmwiki.php
Build/Installation documentation: http://nmon.sourceforge.net/pmwiki.php?n=Main.CompilingNmon
Source Code: 
License: GPL
##

**Comment by hgy59** [comment]
nmon 16m is included in synocli-monitor since v1.0-1
