### ISSUE TITLE
Feature request: Add lxml package to python2

### ISSUE THREAD

**Issue by rlindner81** [SynoCommunity/spksrc#2248]
Since DSM6 it no longer seems to be possible to add lxml via pip. The lxml allows users to efficiently parse html, which is a major usecase for some scripts running on my NAS.

**Comment by Dr-Bean** [comment]
SynoCommunity's python already includes lxml: https://github.com/SynoCommunity/spksrc/blob/master/spk/python/Makefile#L12.
I'm guessing that you're running Synology's python (check with `which python`). If so, you should contact Synology with a feature request. Or switch to using our package...

**Comment by rlindner81** [comment]
You are quite right. Thanks for clarifying. :+1:
