### ISSUE TITLE
Can't install deluge

### ISSUE THREAD

**Issue by Holmes77** [SynoCommunity/spksrc#2249]
Hello,
I'm new here and a fresh Synology nas user so excuse me if sound stupid...

I've been testing some torrent clients. Eventually choose deluge from synocommunity packages. Unfortunately at some point I unistalled it and now I can't do it again. I get something like 'Port undefined for this package is either used by another service or reserved for system use' and so on.
I didn't install any new packages. Due to my lack of knowledge I don't even know where to start looking for conflicts.
Can anyone help? TIA

ds115, DSM 6.0-7321

**Comment by Dr-Bean** [comment]
Check `/usr/local/services.d/` for a file that uses the same ports (8112 or 6881:6891) as Deluge. It could also be that the deluge.sc file wasn't removed during uninstall.

Note that Deluge, along with a lot of other SynoCommunity packages, won't work on DSM6 if you didn't migrate from DSM5 with the package already installed. See #2216 for one of the reasons.

**Comment by Dr-Bean** [comment]
Closing, my previous comment should have explained it all.
