### ISSUE TITLE
Git Server beta — launch repair fail 

### ISSUE THREAD

**Issue by tomtompy** [SynoCommunity/spksrc#2255]
Hi,

I try to install 1.8.3-1 beta on my Synology.
I have this error "echec lors du lancement de la réparation du paquet" (fail repair packet) and no log.
config :
DS213
MARVELL Kirkwood 88F6282
DSM 6.0-7321
What's wrong ? Git package is needed ?
##

**Comment by Safihre** [comment]
Further Git-Server updates (like DSM6 compatibility) will be handled in #2101.
