### ISSUE TITLE
Retire newznab package and remove code from spksrc

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2256]
Upstream newznab hasn't been maintained since the release of 0.23. I think it's best to retire the `newznab` package and remove it from spksrc.

I've deactivated the packages on the repository. If no objections are made, I'll probably remove the code from spksrc in a couple of weeks.

**Comment by cytec** [comment]
was thinking about that a while ago... maybe replacing `newznab` with `nZEDb` would be an option for those who want to setup an indexer on a DS?

**Comment by Dr-Bean** [comment]
Sure...feel free to a package request ;)

**Comment by Dr-Bean** [comment]
Removed newznab code with https://github.com/SynoCommunity/spksrc/commit/836e423429e3790410cb7ce45418c6a403722b86.
I briefly looked at the nZEDb codebase, and it looks like the newznab package code could very well serve as inspiration/starting point to create a package for nZEDb, so that's something to keep in mind.
