### ISSUE TITLE
Pyload and DSM 6

### ISSUE THREAD

**Issue by Phelton** [SynoCommunity/spksrc#2259]
Hi,
pyload package don't work on DSM 6.
-don't create user
-don't create directory
-don't start application

My Synology is DS214se with Armada 370

can you resolve package issue?

thanks
##

**Comment by benmailny** [comment]
Same issue:

DSM-Version: DSM 6.0-7321 
Synology: DS412+
Pyload Version beta: 0.4.9-2

Thank you for help (installed via package Center)

**Comment by matrog** [comment]
is it starting manually via ssh? I managed to add DSM toolchain and recompile for x64 arch and it work even if i had to fix some user/permission issues

**Comment by bolhaskutya** [comment]
Any updates?

**Comment by FloLaco** [comment]
Hello guys, any news about this issue ?

**Comment by mreid-tt** [comment]
hey @hgy59, I noted a user was asking for and update via https://github.com/SynoCommunity/spksrc/issues/4524#issuecomment-1962929283. I also noted a previous commit https://github.com/SynoCommunity/spksrc/pull/3648/commits/2934189c12c6fb4c7aad73211d5374495d1c20cd for this package. Not sure what the current status is.

**Comment by hgy59** [comment]
> hey @hgy59, I noted a user was asking for and update via [#4524 (comment)](https://github.com/SynoCommunity/spksrc/issues/4524#issuecomment-1962929283). I also noted a previous commit [2934189](https://github.com/SynoCommunity/spksrc/commit/2934189c12c6fb4c7aad73211d5374495d1c20cd) for this package. Not sure what the current status is since the latest published version seems to be
> v0.4.9-2.

latests version is pyload v0.4.20 and i don't know why it is not published. This is python2 and will not be maintained anymore and we will not support it on DSM 7+.

There is pyload 0.5.x for python 3 (on main branch but no releases in github, development releases as pyload-ng on pypi) but this is still under development (beta since 2021, latest release this month, see https://pypi.org/project/pyload-ng/#history)

**Comment by mreid-tt** [comment]
> latests version is pyload v0.4.20 and i don't know why it is not published. This is python2 and will not be maintained anymore and we will not support it on DSM 7+.

Hmm, okay. I tried to publish it via this [build run](https://github.com/mreid-tt/spksrc/actions/runs/8054590983) but nothing got published even though the run was successful. Maybe some got broken along the way?

**Comment by hgy59** [comment]
> Hmm, okay. I tried to publish it via this [build run](https://github.com/mreid-tt/spksrc/actions/runs/8054590983) but nothing got published even though the run was successful. Maybe something got broken along the way?

this is by intention. @th0ma7 added the BROKEN file to the spk/pyload folder with the content of:
```
2021-10-06 (@th0ma7)
Should consider migrating to python3 version and remove js dependency
```
