### ISSUE TITLE
Ejabberd not starting after installation

### ISSUE THREAD

**Issue by profoundman** [SynoCommunity/spksrc#2260]
Hello, 
Would like to report that Ejabberd fails to run after new installation on Synology.
No error msg during installation. However after install, the app attempt to start for 2 minutes after failing with the msg (Failed to run the package service)

System is: DS412+
OS version: DSM 6.0-7321 Update 1

Your help in this matter is appreciated

Thank you.
##

**Comment by letmp** [comment]
same here. tried to start it from commandline. here is the output:

```
Starting ejabberd ...
id: ejabberd: no such user
/usr/local/ejabberd/sbin/ejabberdctl: line 68: [: : integer expression expected
su: user ejabberd does not exist
```

**Comment by letmp** [comment]
after adding a ejabberd user manually i get this error:

`Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{{error,"Error when reading /usr/loc
`

**Comment by adan89lion** [comment]
same here, I think ejabberd package is not compatible with this version of dsm.
meanwhile, I've tried to install Openfire, another xmpp server for dsm, but it cannot installed because of the java version(although I've installed java in my dsm but it shows the same error while installing)

**Comment by NoOneAtHome** [comment]
@Dr-Bean is this package still being maintained?  I would be willing to post a bounty if it would help.

**Comment by sorcer1122** [comment]
Same here, not starting. Is there any fix?

**Comment by matterik** [comment]
So is there a solution. I cannot start the package ejabberd either.

**Comment by teihoo** [comment]
Not starting for me either on Synology DSM 6.1 Update 1 on DS213j. Anyone got some workarounds maybe?

**Comment by CamSnap** [comment]
Bummer, I was so looking forward to running this for secure internal messaging. 
Not working on DSM 6.1.1-15101 Update 2

**Comment by CamSnap** [comment]
posted a small bounty to see if we can get this running again.

**Comment by Heptite** [comment]
This problem still exists as of February 23. I have a new Synology NAS and I tried to install ejabberd, but it won't start, even if I try to manually start it in the Package Center.

**Comment by morbac** [comment]
I had the same problem, which disappeared after rebooting the synology.

**Comment by willemb2** [comment]
It is version 2.1.13. Released [25 Jun 2013](https://github.com/processone/ejabberd/releases/tag/v2.1.13)..... I'm afraid this project is dead. Sorry, I cannot help, have not done any compiling since Algol60 in the early 1970ties.

**Comment by Heptite** [comment]
I gave up on it. I now have a Raspberry Pi that runs ejabberd, among other things. I have withdrawn my portion of the bounty on this issue.

**Comment by hgy59** [comment]
@Heptite, @willemb2, @morbac, @CamSnap 
#4333 provides now working packages of ejabberd 21.01.
