### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Martijn085** [SynoCommunity/spksrc#2262]
When i try to compile some stuff i keep getting this error on openssl:

`../libcrypto.so: undefined reference to `rc4_md5_enc'`

Someone had a solution for this?

**Comment by Dr-Bean** [comment]
More details please. What command were you running and where from (cross package, spk?)? It this an actual error that halts the process, or a warning while compilation continues?

**Comment by Martijn085** [comment]
it`s a warning when compiling, I have tested it with ffsync and transmission. This is the complete log:

`rm -f openssl
shlib_target=; if [ -n "libcrypto.so.1.0.0 libssl.so.1.0.0" ]; then \
                shlib_target="linux-shared"; \
        elif [ -n "" ]; then \
          FIPSLD_CC="gcc"; CC=/usr/local/ssl/fips-2.0/bin/fipsld; export CC FIPSLD_CC; \
        fi; \
        LIBRARIES="-L.. -lssl  -L.. -lcrypto" ; \
        make -f ../Makefile.shared -e \
                APPNAME=openssl OBJECTS="openssl.o verify.o asn1pars.o req.o dgst.o dh.o dhparam.o enc.o passwd.o gendh.o errstr.o ca.o pkcs7.o crl2p7.o crl.o rsa.o rsautl.o dsa.o dsaparam.o ec.o ecparam.o x509.o genrsa.o gendsa.o genpkey.o s_server.o s_client.o speed.o s_time.o apps.o s_cb.o s_socket.o app_rand.o version.o sess_id.o ciphers.o nseq.o pkcs12.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o spkac.o smime.o cms.o rand.o engine.o ocsp.o prime.o ts.o srp.o" \
                LIBDEPS=" $LIBRARIES -ldl" \
                link_app.${shlib_target}
make[5]: Entering directory `/spksrc/synocommunity/spk/ffsync/work/openssl-1.0.2g/apps'
../libcrypto.so: undefined reference to `rc4_md5_enc'
collect2: error: ld returned 1 exit status
make[5]: *** [link_app.gnu] Error 1
make[5]: Leaving directory `/spksrc/synocommunity/spk/ffsync/work/openssl-1.0.2g/apps'
make[4]: *** [openssl] Fout 2
make[4]: Map '/spksrc/synocommunity/spk/ffsync/work/openssl-1.0.2g/apps' wordt verlaten
make[3]: *** [build_apps] Fout 1
make[3]: Map '/spksrc/synocommunity/spk/ffsync/work/openssl-1.0.2g' wordt verlaten
make[2]: *** [compile_target] Fout 2
make[2]: Map '/spksrc/synocommunity/cross/openssl' wordt verlaten
make[1]: *** [depend_target] Fout 2
make[1]: Map '/spksrc/synocommunity/cross/python' wordt verlaten
make: *** [depend_target] Fout 2
****@****:/spksrc/synocommunity/spk/ffsync#`

**Comment by Dr-Bean** [comment]
Use one of the following formats. Note the letter case for the variables.
- `make arch-armadaxp-5.2`
- `make arch-armadaxp`. Reads the toolchain version from `DEFAULT_TC` defined in `local.mk`, otherwise same as the first option. Fails if `DEFAULT_TC` is not defined.
- `make ARCH=armadaxp TCVERSION=5.2`

**Comment by Martijn085** [comment]
Thanks! Tranmissions is now compiling. Only ffsync seems to be failing with another error:

> Failed building wheel for cffi
>   Running setup.py clean for cffi
> Failed to build cffi
> Installing collected packages: cffi
>   Running setup.py install for cffi ... error
>     Complete output from command /spksrc/synocommunity/native/python/work-native/install/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mBxpOS/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WhgWb8-record/install-record.txt --single-version-externally-managed --compile:
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-2.7
>     creating build/lib.linux-x86_64-2.7/cffi
>     copying cffi/gc_weakref.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
>     copying cffi/_embedding.h -> build/lib.linux-x86_64-2.7/cffi
>     running build_ext
>     building '_cffi_backend' extension
>     creating build/temp.linux-x86_64-2.7
>     creating build/temp.linux-x86_64-2.7/c
>     /spksrc/synocommunity/toolchains/syno-armadaxp-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/spksrc/synocommunity/toolchains/syno-armadaxp-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -mhard-float -mfpu=vfpv3-d16 -I/spksrc/synocommunity/spk/ffsync/work-armadaxp-5.2/install//usr/local/ffsync/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/spksrc/synocommunity/toolchains/syno-armadaxp-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -mhard-float -mfpu=vfpv3-d16 -I/spksrc/synocommunity/spk/ffsync/work-armadaxp-5.2/install//usr/local/ffsync/include -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/spksrc/synocommunity/native/python/work-native/install/usr/local/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
>     In file included from /spksrc/synocommunity/native/python/work-native/install/usr/local/include/python2.7/Python.h:58:0,
>                      from c/_cffi_backend.c:2:
>     /spksrc/synocommunity/native/python/work-native/install/usr/local/include/python2.7/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
>     c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
>     compilation terminated.
>     error: command '/spksrc/synocommunity/toolchains/syno-armadaxp-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-gcc' failed with exit status 1
> 
>     ----------------------------------------
> Command "/spksrc/synocommunity/native/python/work-native/install/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mBxpOS/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WhgWb8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-mBxpOS/cffi/
> make[3]: *** [myPostInstall] Fout 1
> make[3]: Map '/spksrc/synocommunity/native/python' wordt verlaten
> make[2]: *** [depend_target] Fout 2
> make[2]: Map '/spksrc/synocommunity/cross/python' wordt verlaten
> make[1]: *** [depend_target] Fout 2
> make[1]: Map '/spksrc/synocommunity/spk/ffsync' wordt verlaten
> make: [arch-armadaxp-5.2] Fout 2 (genegeerd)

**Comment by Dr-Bean** [comment]
Compile `native/python` separately.

**Comment by Martijn085** [comment]
I`m sorry but i don`t know mean. I`m totally new with this compiling stuff...

For ffsync i only use: 'make arch-armadaxp-5.2', what i need to do more to compile 'native/python'?

**Comment by Dr-Bean** [comment]
From the spksrc root dir: `cd native/python`, run `make clean`, followed by `make`. 
Then go back to `ffsync`. Probably best to do a `make clean` there as well, then go from there..

There's some type of bug where (environment) variables from cross- or spk packages are applied when compiling native packages. Currently, the way around that is to compile the native packages separately, first, before compiling cross- or spk packages that depend on them.

**Comment by Martijn085** [comment]
That works, thanks for a the help! It's a lot clearer now.
