### ISSUE TITLE
[AcoustID] Beta -> Stable

### ISSUE THREAD

**Issue by rednoah** [SynoCommunity/spksrc#2264]
I haven't had any issues with the `AcoustID` package. I think it can be moved out of beta:
https://github.com/SynoCommunity/spksrc/blob/9aed40943cb627a760009a8287be4a20140c9d1f/spk/chromaprint/Makefile#L10

**Comment by Dr-Bean** [comment]
Thanks for letting us know. Package should probably be updated to latest (1.3.1), and the beta tag can be removed.

**Comment by cytec** [comment]
PR is here: https://github.com/SynoCommunity/spksrc/pull/2266 currently running `all-supported` on that one ;)

**Comment by rednoah** [comment]
Confirmed. Works fine.
```
$ fpcalc 2> /dev/null -version
fpcalc version 1.3.1
```
