### ISSUE TITLE
please help: FFMpeg Security Adviser alert & how to uninstall FFMpeg?

### ISSUE THREAD

**Issue by vr1111** [SynoCommunity/spksrc#2265]
Hi,
I'm getting "High" Security Adviser warning for FFmpeg -- saying that it has modified system files. I can't uninstall the package, since it is not visible in Synology DSM Package Center.
Can someone please share instructions how to uninstall, without DSM Package Center?
I'm running DSM 6

I contacted Cytec, but he said this issue was totally new to him, and suggested that I post here.
Please help. Any help is much appreciated. I'm including the screen shot. 
![screen shot 2016-04-12 at 4 48 20 am](https://cloud.githubusercontent.com/assets/18500050/14580975/e320e864-03a5-11e6-8de2-79ef96bbb795.jpg)

![Uploading Screen Shot 2016-04-12 at 4.48.20 AM.jpg…]()
##

**Comment by cytec** [comment]
@SynoCommunity/developers anyone of you ever got something like that?
@vr1111 like i said in that email already i don't know where this comes from, seems like some sort of "security guard" or something like that, maybe try to disable that and uninstall then... or try moving/deleting /usr/bin/ffmpeg and see what happens but that might break something else :/

**Comment by GoodOmens83** [comment]
What packages are installed?  What packages have you ever installed/de-installed?

Did you ever install ffmpeg?  It could be something entirely different that has tried to do something.

**Comment by vr1111** [comment]
I mostly have Synology official packages.
As for Community packages, I also installed these from SynoCommunity:
Maria db, Transmission (disabled both now), and FFMpeg (can't see it in Package Center)

I also installed a package called net2ftp from another Community repository (http://www.eg-blog.de/?p=440)

Any of those known to be problematic?

Does anyone here know Diaoul? I just saw he's the developer of FFmpeg -- I thought Cytec was the developer... Maybe he would know?

**Comment by Dr-Bean** [comment]
If it was the current ffmpeg package, it's quite likely to be this: https://github.com/SynoCommunity/spksrc/blob/master/spk/ffmpeg/src/installer.sh#L6.
AppArmor probably triggers on the symlink creation in that location, seeing as Synology's `ffmpeg` is installed there.

**Comment by vr1111** [comment]
Dr-Bean, what do you think the solution would be to prevent this from happening, or to install this version of Ffmpeg, and go back to Synology's official one?

**Comment by Dr-Bean** [comment]
The solution is a package that doesn't put binaries or symlinks in locations that are used by Synology. If our current ffmpeg package causes this type of behavior, it shouldn't even be published. 
@cytec is working on updating the ffmpeg package, see #1662. I believe the install routine is cleaned up already in that PR, but if not, it should be ;)

As for going back to Synology's ffmpeg: It depends on your needs. I assume there was a reason for you to install a third-party package in the first place, right?

**Comment by cytec** [comment]
@Dr-Bean yup... the new PR links to `/usr/local/bin` but as mentioned there already im not 100% sure if adding it to path by default is a good idea...

**Comment by Dr-Bean** [comment]
Yep. I'd suggest not to add a symlink in this particular case. Better to be on the safe side, and completely avoid creating symlinks to binaries that could conflict with Synology's stuff.

**Comment by vr1111** [comment]
Sounds like you guys are onto something. Now is there a way to remove the earlier FFMpeg package I installed, that messed with Synology's /usr/local/bin location?

**Comment by Dr-Bean** [comment]
If it's not shown in Package Center under `Installed packages`, then the only way is to manually make the necessary changes.

Are you still affected by it (as in: does the warning dialog show every time, or something like that?), or are you asking just to be sure that your device has reverted to default settings?

**Comment by vr1111** [comment]
Still having the same Security Adviser "High" flag (same screen-shot I posted)... Could you post instructions how to manually solve this, to get rid of the flag? I upgraded to the latest DSM 6.0

**Comment by vr1111** [comment]
This is what I'm getting when I run Security Adviser, and it points to usr/bin/ffmpeg
Manual removal instructions would be much appreciated!
![screen shot 2016-04-22 at 7 45 21 am](https://cloud.githubusercontent.com/assets/18500050/14741760/40e4e45c-085e-11e6-9107-902c7c62f3d3.jpg)

**Comment by andouar** [comment]
Hi, 
I'm having the exact same issue with my DS216+II. I installed the ffmpeg package then got the security warning with the same link to the knowledge base leading nowhere :P 
I tried to reset the operating system using a paperclip with the reset buton for 4 seconds then within the 10 seconds re hit the reset buton for 4 seconds, as suggested by synology support. I should had oranges bliking led on the front but never managed to obtain them. 
I upgraded the DS216+II ram from 1Gb to 4Gb, that could be the problem for me to reset the opating system without loosing the datas on the Nas. did you tried vr1111 this possibility? Saving the Nas configuration before then restauring it after the reset.
I will try later (when i'll have more time) to reset the operating system with the original ram set.

**Comment by etcusrvar** [comment]
If you're still having the Security Advisor issue, fixing it isn't hard.

Go to https://www.synology.com/en-us/support/download, and download the .pat file for your DSM. It's a tarball.
Extract hda1.tgz from this tarball.
As root, extract extract usr/bin/ffmpeg from hda1.tgz.
As root, copy this ffmpeg binary to /usr/bin.

The Security Advisor scan should be fine now.

**Comment by fildours** [comment]
Hi,
I've got the same issue with security advisor warning on usr/bin/ffmpeg after installation of ffmpeg package from community rep. Tried the above fix as SSH root but security advisor still warn after replacing the correct ffmpeg in usr/bin.
Any idea?
Thanks.

**Comment by Dr-Bean** [comment]
The current ffmpeg package on our repository doesn't make symlinks at all, so unless you installed an old package from somewhere else, it's not related to our package. 
Maybe uninstall the package, and if it still occurs after that, contact Synology support?

**Comment by fildours** [comment]
Thanks. The package I installed came from syno community rep and I installed it at least 6 months ago. Already tried to uninstall but still the same issue. I'll contact Synology support then.

**Comment by Dr-Bean** [comment]
The current ffmpeg package isn't six months old, I don't think...My suggestion: Yes, uninstall the old and broken package, redo the suggestion to extract the Synology ffmpeg binary and place it on your system, and see if the error still occurs. If it does, yes, you'll probably need to contact Synology support.

Since it's no longer a current thing with the ffmpeg package, I think I'll close this issue.

**Comment by fildours** [comment]
Ok, just to clarify: I didn't installed the "current" version of the package but an older version (in my mind I downloaded it and installed it on my Syno at least 6 months ago).

**Comment by Dr-Bean** [comment]
Right. The thing is that the current package (ffmpeg v3.1.2-4) does not 'repair' the replacement of `usr/bin/ffmpeg` that the old ffmpeg package did.
As unfortunate as it is, it's impossible to package such a repair: it depends on your DSM version, the specific model of device, and so on.

So that brings us back to the issue you're seeing: if you have _ever_ had the old ffmpeg package installed, the advisor is still complaining about the changes that it made. Upgrading to the latest version of the ffmpeg package won't change that.
The upside is that the current ffmpeg package in itself will not trigger the advisor...

**Comment by fildours** [comment]
Ok, understood. Thanks for the detailed answer.
