### ISSUE TITLE
[suggestion] SynoCommunity 'base package'

### ISSUE THREAD

**Issue by spockfish** [SynoCommunity/spksrc#2272]
Hi,

As a happy user of SC I'm looking into ways of contributing to the project. Looking at how things are setup (infrastructure, packaging etc.) I was wondering if it ever was discussed to create a 'SynoCommunity base package': a dependancy for all other packages that provides some level of abstraction (script functions etc.).

Rationale is that looking at the latest DSM 6 release a lot of packages need work, but it is imho a lot of the same work. Having this all abstracted away in a default package would liften the maintenance burden a little bit, and makes the separate package script less error-prone.

Forgive me if this has already been discussed somewhere else: at least I could not find it ;-)

**Comment by cytec** [comment]
yeah something like that was discussed a while ago... and then again not so long ago when DSM 6 came out again here: https://github.com/SynoCommunity/spksrc/issues/1932#issuecomment-156483170

**Comment by Dr-Bean** [comment]
Indeed. It's on my todo list, but determining the correct content as far as DSM6 goes is more important. Moving functions to `common` script and getting that included is easy enough after that.

Let's mark this as a duplicate.

**Comment by Dr-Bean** [comment]
Too quick to enter...
@spockfish Feel free to contribute to the other issue with your ideas.
