### ISSUE TITLE
[Request] Update native Go

### ISSUE THREAD

**Issue by The-MAD-Virus** [SynoCommunity/spksrc#2273]
Hi !
It's me again, the guy with its qoriq system !
i would like to know if it's possible to update Go to 1.6.2  ? so may be i can compile Syncthing on my DS413.
can you at least give me some hint so i can try to update it my self ?

**Comment by cytec** [comment]
I'm currently working on an update for `native/go` to the latest version... but still... no PPC support AFAIK

**Comment by The-MAD-Virus** [comment]
OK thanks, i'll wait for your update, it will be good for my other nas ^_^

**Comment by cytec** [comment]
well.. if you want `go` on your ANS itself thats a different thing... i'm just talking about the version used by `spksrc` to build spks like `spk/syncthing`

**Comment by The-MAD-Virus** [comment]
Yes i know, i just like my repository to be up to date.
thx again
