### ISSUE TITLE
Pyload: No module named Account

### ISSUE THREAD

**Issue by hardyGitHub** [SynoCommunity/spksrc#2274]
Sorry to annoy you,

got this pyload package up and running on my ds415+ until I have used it for a long time on my former ds211. 

After a lot of tries its running but I cannot use my shareonlinebiz account for what ever reason. 

Using the adding account feature on the webinterface I got several "errors occured massages". 

Trying to edit the account.conf didn't work, another error occured . I have no clue what is the issue and how to solve the problem.

ERROR   *_LinkdecrypterCom: Crypter list *_ not found might be a server down or not reachable problem.

But how can I import the module named Account, or use my account shareonline.biz? 

I am lost, especial because I can usualy solve my problems by my on, so that I do not need not disturb you. 

Maybe there is an easy way out, an you can help me.

Thanx in advance !

222 20.04.2016 18:08:25 INFO    starte pyLoad 0.4.9
223 20.04.2016 18:08:25 INFO    Benutze Home-Verzeichnis: /volume1/@appstore/pyload/etc
224 20.04.2016 18:08:25 INFO    Checksum: Checksum validation is disabled in general configuration
225 20.04.2016 18:08:25 INFO    ExtractArchive: Aktiviert UnRar UnZip
226 20.04.2016 18:08:25 INFO    Aktivierte Plugins: BypassCaptcha, CaptchaTrader, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, HotFolder, ImageTyperz, LinkdecrypterCom, UnSkipOnFail, UpdateManager, XFileSharingPro
227 20.04.2016 18:08:25 INFO    Deaktivierte Plugins: AlldebridCom, Captcha9kw, CaptchaBrotherhood, DeathByCaptcha, DownloadScheduler, EasybytezCom, Ev0InFetcher, ExpertDecoders, IRCInterface, MergeFiles, MultiHome, MultishareCz, Premium4Me, PremiumizeMe, RealdebridCom, RehostTo, XMPPInterface, ZeveraCom
228 20.04.2016 18:08:25 INFO    Downloadzeit: True
229 20.04.2016 18:08:25 INFO    Starte ThriftBackend: 0.0.0.0:7227
230 20.04.2016 18:08:25 INFO    Starting threaded webserver: :::8000
231 20.04.2016 18:08:25 INFO    Free space: 6.82 TiB
232 20.04.2016 18:08:25 INFO    Activating Accounts...
233 20.04.2016 18:08:25 INFO    Activating Plugins...
234 20.04.2016 18:08:26 ERROR   LinkdecrypterCom: Crypter list not found
235 20.04.2016 18:08:26 INFO    pyLoad is up and running
236 20.04.2016 18:08:28 INFO    UpdateManager: No Updates for pyLoad
237 20.04.2016 18:09:40 ERROR   Error importing ShareonlineBiz: No module named Account
##

**Comment by cytec** [comment]
this is a pyload specific error. the place you are looking for is:https://github.com/pyload/pyload

**Comment by Dr-Bean** [comment]
Are you sure it's our package? You're running on port 8000, while our package is set to use 8190.

As for the error, that may well occur with our package regardless. Packaging or installing Pyload is a bit of an obstacle course it seems. Our current install method is correct as per https://github.com/pyload/pyload/issues/2000(install official release, patch Updatemanager), but in practice, that doesn't work.
I don't know why the maintainers aren't releasing a new version, but that would make sense imo.

**Comment by hardyGitHub** [comment]
Yes it's your package I' am running on port 8000. I had been changing it after installation, because as I wrote I came from a ds211 were I was using port 8000 and I didn't wanted to change all Firewalls, routes and  smartphoneapps aso. Yes its an obstacle course, and I am quite familiar with installing pyload since 2009, but I haven't faced complications like this before. First after setting up DS415+ I tried your package let's say 5 times. DSM 6.0 was able to install but not to run the package. Tried another package with manual installation DSM 6.0 was reporting up an running, but it was not. Manual start showed up a lot of missing files links aso. OK tried yours via DSM further two times and gess up an running. Changed port to 8000 just the account feature is not working. 
Acctually it exceeds my knowledge about pyload. The whole remote procedure call thing. 
Maybe I have to change modules.conf to add the module ACCOUNT, but how, or I need to correct the path of remote procedure call, but were I can find the call, or I need to copy the module to the wright path. Look like a lot of internet studies and spending a lot of time for this issue. ;-))

**Comment by Dr-Bean** [comment]
DSM6 issues (as in: a fresh install on DSM6 doesn't run due to missing users) is part of #2259 and #2216.

As @cytec said, you're still going to have to report it upstream. Please ask the maintainers to consider releasing a new version...that would probably solve our issue and a lot of their issues...

**Comment by hardyGitHub** [comment]
Got the solution so far!
needed to extract pyLoad-0.4.9-5-avoton.spk. Then I copy all files from pyLoad-0.4.9-5-avoton/package/pyload/module/plugins to /volume1/@appstore/pyload/etc/userplugins. chown pyload.root to all files. Some plugins needed the chmod u+x to make them executable. Finally I had to face this 
Error importing ShareonlineBiz: No module named misc
I downloaded it from 
https://github.com/pyload/pyload/blob/ff880300c3200d0c6adfd2f8f3732a10e06d30ec/module/plugins/internal/misc.py
copied it to /volume1/@appstore/pyload/etc/userplugins/internal, made it executable.
Done works for me.
Seems, that there are some installationroutinemistakes!

**Comment by Safihre** [comment]
Further PyLoad updates (like DSM6 compatibility) via #2259.
