### ISSUE TITLE
DSM update corrupted DS

### ISSUE THREAD

**Issue by ozuser** [SynoCommunity/spksrc#2275]
Device: DS1812+

Upgraded from DSM 5.2-5644-8 to 6.0-7321 and then to 6.0-7321-2. After the final reboot, went to package center to upgrade the packages. It asked me to "Repair All" which I clicked but it failed and then tried to "Upgrade All" but that failed as well after trying to upgrade and hung. Tried to relogin but it failed with something like this user doesn't have the privilege. 

Finally tried rebooting using the front power button but after the reboot the device came up in the DS Assistant as "Ready" but when I go to the login page, it says "Processing please wait" but doesn't login. 

The DSM upgrade is normally a hassle free process and never faced this sort of problem. Please help.

**Comment by Dr-Bean** [comment]
This is the SynoCommunity bug tracker, not Synology support. Report your issues with upgrading here: https://www.synology.com/en-global/company/contact_us
