### ISSUE TITLE
SabNzb-Sickbeard-Couchpotato doesn't work with DSM6

### ISSUE THREAD

**Issue by shabazz95** [SynoCommunity/spksrc#2277]
All these three packages doesnt work anymore on DSM6.0.

Is there any solution or simply not compatible ?

"Echec lors du lancement de la réparation du paquet".

**Comment by Paradoxx2015** [comment]
Same problem. The app Sickbreard-custon and couchpotato in my case. They work if i SSH (root) and use ./start-stop-status start in script folder for the app. But they will not start thru the package center.

**Comment by Dr-Bean** [comment]
Duplicate of #2207 and related to #2216.
