### ISSUE TITLE
[Request] Fully updated TTRSS

### ISSUE THREAD

**Issue by live4truths** [SynoCommunity/spksrc#2278]
Website: https://tt-rss.org/gitlab/fox/tt-rss/wikis/home
Version: 9e84bab4
Description: RSS Reader
Documentation: https://tt-rss.org/gitlab/fox/tt-rss/wikis/home
Source code: https://github.com/major/tt-rss
License: GNU

I have been trying desperately to figure out how to update/create/all that sort of stuff with synology packages for the past few weeks. Failing miserably. having to reload my NAS a few times. While I love learning, I am hoping to find the community willing to keep the package updated while I continue. It would likely take someone educated here 5 minutes, and me 5 months.

Thank you for reading.
##

**Comment by live4truths** [comment]
Would this get any more interest if I threw $5 at it?

**Comment by live4truths** [comment]
$10? :(

**Comment by joeyd2** [comment]
Yes, could we please get an update? It's been a very long time since it was updated and maybe fix the PHP error when installing on DSM 6?

**Comment by live4truths** [comment]
Anyone?

**Comment by michailf** [comment]
You can try my fork https://github.com/michailf/spksrc/tree/dsm6

It builds tt-rss 17.1

You may have to use DSM 5.2 toolchain.

**Comment by live4truths** [comment]
@michailf Thank you for this, I am probably not smart enough to figure out how to convert it to the 5.2 version, or even install this. TTRSS was one of the few programs I was waiting on to move to DSM6, So if I can figure it out (or you have any insight to help) I will give it a shot.

Thank you for your hard work

**Comment by michailf** [comment]
@live4truths You have to follow the instuctions provided in the README.

First get the dev environment.  You can use Docker for this.

### Clone dsm6 branch from my fork into your home directory 
git clone -b dsm6 https://github.com/michailf/spksrc.git ~/spksrc

### Install Docker, if you don't have it yet

### Download docker image (you may have to execute this command more than once, if download gets interrupted)
sudo docker pull synocommunity/spksrc

### Run the docker image
docker run -it -v ~/spksrc:/spksrc synocommunity/spksrc /bin/bash

At this point you will be logged in to the dev environment.

### Follow instructions here to build your package: 

https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO

cd /spksrc
make setup
cd spk/tt-rss
make arch-x64-5.2

You have to replace "arch-x64-5.2" with architecture appropriate for your environment.

The output package will be in /spksrc/packages/ in the build environment or ~/spksrc/packages/ on your host machine.
