### ISSUE TITLE
owncloud wakes DS214 every half hour

### ISSUE THREAD

**Issue by michstress** [SynoCommunity/spksrc#2280]
Hi!

I use the 8.1.1-7 owncloud package mainly to sync my android contacts via carddav on my DS214 (DSM 6.0-7321 Update 2). It works fine, but it I needed to disable it, because it wakes the NAS every half hour. 
...
/var/log/messages:
Apr 22 08:58:01 NAS2 kernel: [853237.855091] ata1: link is slow to respond, please be patient (ready=0)
Apr 22 08:58:03 NAS2 kernel: [853239.359694] ata1: wake up successful, the reset fail can be ignored
Apr 22 09:27:56 NAS2 kernel: [855028.894985] ata1: wake up from deepsleep, reset link now
Apr 22 09:27:56 NAS2 kernel: [855028.982914] ata1: device plugged sstatus 0x123
Apr 22 09:28:02 NAS2 kernel: [855037.844750] ata1: link is slow to respond, please be patient (ready=0)
Apr 22 09:28:03 NAS2 kernel: [855039.289348] ata1: wake up successful, the reset fail can be ignored
...
Any thoughts how to configure owncloud to wake the NAS less often? (Like once or twice a day?)

Regards Martin

**Comment by GoodOmens83** [comment]
Just a purse guess but this file:

**Comment by michstress** [comment]
Hi,

sorry for the very late reply, but indeed you suggestion worked, I could verify it now over 24h. Thanks a lot for you help, it was annoying to start/stop owncloud for every carddav sync :)

**Comment by tmarkwardt** [comment]
HiWenn noch frei ist,ichMit freundlichen Grüßen,Torsten MarkwardtWorkplace Services Architect - Hardware & OS Services (I.LPW 32)DB Systel GmbHWeimarische Straße 42, 99099 ErfurtTel. +49 361 300-6461, Fax +49 361 300-6447, intern 980-Mobil: +49 160 97445275~~~ powered by Lotus Traveler ~~~_________________________________________________________________________________Der DB-Konzern im Internet >> http://www.deutschebahn.comSitz der Gesellschaft: Frankfurt am MainRegistergericht: Frankfurt am Main, HRB 78707USt-IdNr.: DE252204770Geschäftsführer: Detlef Exner (Vorsitzender), Dr. Burkhard Klanke, Dr. Klaus RüfflerVorsitzender des Aufsichtsrates: Dr. Rolf Kranüchel



   Dr-Bean --- Re: [SynoCommunity/spksrc] owncloud wakes DS214 every half hour (#2280) --- 
    Von:"Dr-Bean" <notifications@github.com>An:"SynoCommunity/spksrc" <spksrc@noreply.github.com>Datum:Di., 10.05.2016 11:06Betreff:Re: [SynoCommunity/spksrc] owncloud wakes DS214 every half hour (#2280)
  
  Closed #2280.
