### ISSUE TITLE
Transmission : Error mode

### ISSUE THREAD

**Issue by sebmex** [SynoCommunity/spksrc#2281]
Hi,

since DSM update last week (DSM 6.0-7321 Update 2 and then update 3), my transmission package (2.92-12) is in error.

When i try the Repair function it says "the port undefined configured for this package is used by another service, etc."
What can i do ?

Thanks

Sebmex

**Comment by Tstassin** [comment]
Did you try to reboot ?

**Comment by sebmex** [comment]
reboot didn't do anything, but reinstalling the package did the trick.

Thanks, nice software.
