### ISSUE TITLE
Update salt-master to at least the latest release, 2016.3.0

### ISSUE THREAD

**Issue by nogweii** [SynoCommunity/spksrc#2282]
I've noticed that the version in the repository is 2015.5.3-8, at least for my DS415+.

If you upgrade to the current latest, be aware that the next version 2016.3.x should be marked stable soon. (1-2 weeks, per rumours at this year's SaltConf.)

**Comment by evaryont** [comment]
Hurray, the [2016.3.0 release](https://docs.saltstack.com/en/latest/topics/releases/2016.3.0.html) is now out.

**Comment by Diaoul** [comment]
I have a local version working. Stay tuned.

**Comment by mreid-tt** [comment]
Should this ticket be closed with v3004-11 [published](https://synocommunity.com/package/salt-master)?

**Comment by nogweii** [comment]
Ah, yeah. Thanks for the follow up. 😄
