### ISSUE TITLE
debian-chroot update

### ISSUE THREAD

**Issue by tomfisk** [SynoCommunity/spksrc#2284]
I have a debian-chroot update waiting on 3 systems.  Just wanted to check if the update process preserves everything I've added (e.g. scripts in /home directories, binaries in /usr/local/bin, applications in /opt).

**Comment by Dr-Bean** [comment]
An update of the package does not affect an existing chroot: it is saved and restored during the package upgrade. See `preupgrade` and `postupgrade` in the [installer](https://github.com/SynoCommunity/spksrc/blob/master/spk/debian-chroot/src/installer.sh).

**Comment by tomfisk** [comment]
Thanks much for the clarification!

**Comment by Dr-Bean** [comment]
Cool, I guess this one can be closed then :)
