### ISSUE TITLE
Git Server error

### ISSUE THREAD

**Issue by iruyanka** [SynoCommunity/spksrc#2285]
git pull
fatal: Unable to find remote helper for 'https'

I don't know why it is. 2 months ago no errors.

**Comment by Dr-Bean** [comment]
Please see the guidelines when reporting issues. https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issue-content.

**Comment by iruyanka** [comment]
@Dr-Bean https://blog.hostonnet.com/git-unable-to-find-remote-helper-for-https

It is.

**Comment by Dr-Bean** [comment]
I have no idea what you're trying to say here. Please take a look at the link I provided in my previous comment, and _explain what you're trying to do_. Then, explain what result you're getting. 
Be specific. Include a copy/paste of your SSH session or something.

**Comment by iruyanka** [comment]
http://blog.acidpop.kr/228

solved

**Comment by Dr-Bean** [comment]
For future reference, this essentially boils down to removing all `git` related packages and reinstalling.

**Comment by iruyanka** [comment]
![git](https://cloud.githubusercontent.com/assets/5034950/15420364/6cb68e46-1ea7-11e6-8ce9-78957fe6ed1d.png)

@Dr-Bean Already I try reinstalling, but same error.

I guess connect "https" error.

git clone "https://github.com/acidpop/xpebot" and all github source same error.
"git pull" All git source update same error.

![gitserver](https://cloud.githubusercontent.com/assets/5034950/15420585/848586d4-1ea8-11e6-80ac-035f7640392d.png)

git clone "git://github.com/acidpop/xpebot" / "https" to "git" address change I can install.

**Comment by Dr-Bean** [comment]
Okay, that's information we can work with :)
What does `which git` return? Does it work when you run `/usr/local/git/bin/git https://github.com/acidpop/xpebot`?

**Comment by iruyanka** [comment]
```
/usr/local/git/bin/git https://github.com/acidpop/xpebot
git: 'https://github.com/acidpop/xpebot' is not a git command. See 'git --help'.
```

not a git command.

**Comment by iruyanka** [comment]
```
/usr/local/git/bin/git clone https://github.com/acidpop/xpebot
```

Oh, I can installed.

**Comment by iruyanka** [comment]
Ah...Sorry. @Dr-Bean 

My mistake. I installed two git server.

1. Synology - version 2.8.0-0038
2. SynoCommunity - version 1.8.3-1

Synology version:
git clone "https://github.com/acidpop/xpebot"
fatal: Unable to find remote helper for 'https'

It is synology version, So my mistake. Sorry.

**Comment by iruyanka** [comment]
```
/usr/local/git/bin/git clone https://github.com/acidpop/xpebot
```

SynoCommunity - version 1.8.3-1

I can installed. Thanks.

**Comment by iruyanka** [comment]
But I don't know pull command.

```
/usr/local/git/bin/git pull
```

Is it?

**Comment by Dr-Bean** [comment]
Yes. Do a `/usr/local/git/bin/git --help` for info on which commands are available.

**Comment by iruyanka** [comment]
@Dr-Bean 

```
/usr/local/git/bin/git pull
fatal: Not a git repository (or any of the parent directories): .git
```

I don't know git pull.

**Comment by Dr-Bean** [comment]
You can't run `git pull` in a directory that is not designated as a git repository. In other words: run `git clone` first, then you can keep the local git repository updated with an occasional `git pull`

**Comment by iruyanka** [comment]
@Dr-Bean Ah ha. Really Thanks. Good.

**Comment by Dr-Bean** [comment]
So now everything is working as expected then? :)

**Comment by iruyanka** [comment]
@Dr-Bean 

everything?

Um, I just simple user. So, I need Install and update.
now perfect thanks to you.
