### ISSUE TITLE
ruTorrent but no rTorrent?

### ISSUE THREAD

**Issue by RyanAStrouse** [SynoCommunity/spksrc#2287]
Hello,

I downloaded the ruTorrent package from my Synology package center (running DSM 6.0 which I know came with a slew of problems), have it all configured and "Running", however, I cannot get to a web GUI.

After much research, I believe it's because there is no rTorrent client installed? I seem to remember that being available in the package center too, but now it is no longer listed. Am I missing something?

I also attempted to find the files and manually install but get a "wrong file format".

Have also tried doing some SSH and wasn't sure where to download an official package.

The source of my thinking is that when looking around for answers I stumbled upon /usr/local/rutorrent/bin/rtorrent not existing on my server.

Following this guide: http://www.youritromp.nl/2014/06/rtorrent-seedbox-on-a-synology-nas/

I get to the part to `ps | grep -v grep | grep 'rtorrent'` and nothing happens

Any help is appreciated!

**Comment by GoodOmens83** [comment]
First off - fresh installs of just about any package on DSM6 are both not supported and will most likely not work.

The guide you linked is outdated and the config file listed is no longer relevant (`http_cacert = /usr/local/rutorrent/etc/cacert.pem` should something like `http_cacert = /usr/local/rutorrent/cert.pem`)

The fact you do not have the `rtorrent` binary in `/usr/local/rutorrent/bin` is strange and I don't have an explanation.  Coupled with the web interface is not installed (which should be accessible even if there was no rtorrent binary) tells me the package was not successfully installed.  Is the rutorrent directory in `/var/services/web`?  If not you need try a reinstall.  Something got botched.

**Comment by RyanAStrouse** [comment]
Thank you! Will check this out and let you know how it goes, very good information!

**Comment by malwinMP** [comment]
Is there a possibility to install only rTorrent without ruTorrent?

**Comment by RyanAStrouse** [comment]
No longer attempting to use this program.
