### ISSUE TITLE
Sabnzb  not starting

### ISSUE THREAD

**Issue by henwol** [SynoCommunity/spksrc#2291]
After a clean install of DSM6.0 , and after install Sabnzb / transmission will not start anymore ( Synology DS215j)

**Comment by cytec** [comment]
this is a known issue, based on how user creation is handled in DSM 6

**Comment by henwol** [comment]
Do you know when there will be an solution ?

**Comment by thepatrick** [comment]
This is still an issue a year later... is there a fix? Or should this package just be removed since it doesn't work?

**Comment by KaraokeStu** [comment]
The package does work, based on the intended architecture of the repository, which is dsm 5.x 

Dsm 6.x is still being developed and tested, but is unfortunately taking longer than anticipated and we're waiting on the maintainers of the repo, @Dr-Bean and @Diaoul

**Comment by thepatrick** [comment]
@KaraokeStu unfortunately I can't see any warnings on synocommunity.com or the README in this repo, so for me it just looks broken 😢

**Comment by cytec** [comment]
@thepatrick we have this: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support im not sure maybe we should add something to the readme too but i thought we did make a pretty solid step towards DSM6 lately.

**Comment by okoetter** [comment]
I am confused. I use latest sabnzbd package (2.1.0-29) on the latest DSM (6.1.2-15132 Update 1) on my DS214play without any problems...

**Comment by Safihre** [comment]
Closing due to age. Test-packages for DSM6.1 and new architectures available here: #3138.
Those will later be published to the real package rep.
