### ISSUE TITLE
Znc Fails to start DSM6 #dsm6

### ISSUE THREAD

**Issue by rp4k** [SynoCommunity/spksrc#2294]
DSM6.0-7321 Update 4 
machine : DS716+

ZNC :

> 2016/05/02 03:36:18 install znc 1.6.0-11:
> End: postinst ret=[0]
> 2016/05/02 03:36:18 install znc 1.6.0-11:
> Begin: /bin/rm -rf /volume1/@tmp/pkginstall
> 2016/05/02 03:36:18 install znc 1.6.0-11:
> End: /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
> 2016/05/02 03:36:18 install znc 1.6.0-11 successfully
> 2016/05/02 03:41:19 start znc: begin to start version 1.6.0-11
> 2016/05/02 03:41:21 stop znc: begin to stop version 1.6.0-11
> 2016/05/02 03:41:21 stop znc: stop version 1.6.0-11 successfully, result 0
> 2016/05/02 03:41:26 start znc: start version 1.6.0-11 failed, result 272
> May  2 03:59:47 Rp4k synoscgi_SYNO.Core.Package.Control_1_start[21188]: service_start.c:74 synoservice: [pkgctl-znc] starting ...
> May  2 03:59:49 Rp4k synoscgi_SYNO.Core.Package.Control_1_start[21188]: service_start.c:180 synoservice: [pkgctl-znc] start failed.[0xD900 manager               .cpp:204]
> May  2 03:59:49 Rp4k synoscgi_SYNO.Core.Package.Control_1_start[21188]: service_stop.c:23 synoservice: [pkgctl-znc] stopping ...
> May  2 03:59:49 Rp4k synoscgi_SYNO.Core.Package.Control_1_start[21188]: service_stop.c:38 synoservice: [pkgctl-znc] is already stopped.
> May  2 03:59:49 Rp4k synoscgi_SYNO.Core.Package.Control_1_start[21188]: service_stop.c:86 synoservice: [pkgctl-znc] stopped.

seems to fail on start and idk what result 272 is.
i was able to get it to install . but only after i created the group "ZNC"

**Comment by Dr-Bean** [comment]
Ref #2216.

**Comment by Safihre** [comment]
Further DSM6 compatibility in #2977.

**Comment by ph4r05** [comment]
Just note, quickfix to start ZNC on DSM6 while `adduser` bug is fixed:

I had to change the start script in the following way:

`/var/packages/znc/scripts/start-stop-status`:

```sh
# Originally:
#su ${USER} -c "${ZNC} -d ${INSTALL_DIR}/var"

# Now:
sudo -u ${USER} -EH -i -- sh -c "${ZNC} -d ${INSTALL_DIR}/var"
```

**Comment by rjsproxy** [comment]
Thanks ph4r05.  I had to run znc once manually to create /usr/local/znc/var/znc.pem (afaict), but after that start-stop-status script seems to work.
