### ISSUE TITLE
DSM Application GUIs

### ISSUE THREAD

**Issue by EZarnosky** [SynoCommunity/spksrc#2295]
If there any way to create DSM applications for the packages that are released? Put the packages that are managed via web GUIs into a DSM app with a iframe? i personally do not like opening a mot of ports out through my firewall and would find it easier to manage the packages installed on the DSM in the DSM.

If is is possible I wouldn't might adding a bounty onto a couple to the packages i use on a regular basis.

**Comment by fbartels** [comment]
The way an iframe works you would still need access to the page in the iframe from the location you are currently in. Essentially the website will tell you browser to open a specified url in a container. For me it sounds more like you are searching for a reverse proxy (so that you can mak my-ip:1234/app to my-ip/app).

**Comment by piwi82** [comment]
You can create virtual hosts (Apache aliases) in `Control panel > Web services > Virtual hosts`.

**Comment by EZarnosky** [comment]
Actually I am looking for an application I can open in the DSM that through the window it open has an embedded iframe to the installed package.

example: Click the application icon for Syncthing. a window inside the DSM GUI opens with a iframe that has the Syncthing web GUi embedded in it. I don't like opening multiple tabs to manage things on my NAS.

(note: I was wrong, I would need to open the ports for embedded iframes. OR I could do as you suggested and set up reverse proxying)

**Comment by GoodOmens83** [comment]
Look at the developers guide (might be outdated for DSM6): https://global.download.synology.com/download/Document/DeveloperGuide/DSM_Developer_Guide.pdf

Specifically the section "Integrate Your Package into DSM Web GUI" - not really sure but it looks like you might be able to create some files (cgi, CSS, images) under `/usr/syno/synoman/webman/3rdpaty/[package name]/`.  Haven't played with it so not really sure how it works.

**Comment by Dr-Bean** [comment]
For SynoCommunity packages, it's a design decision to open the web interface of packages outside of DSM. 
As @GoodOmens83 said, Synology has documented how it works: take a look at the `type` property for example. We won't be applying it to our packages though, so if you do make changes locally, those will be reversed if a package update is installed.
