### ISSUE TITLE
Tool chains for DSM 6

### ISSUE THREAD

**Issue by piwi82** [SynoCommunity/spksrc#2296]
DSM 6 tool chains are out : https://sourceforge.net/projects/dsgpl/files/DSM%206.0%20Tool%20Chains/

**Comment by mpeter1975** [comment]
Final toolchain: https://sourceforge.net/projects/dsgpl/files/DSM%206.0%20Tool%20Chains/

**Comment by spockfish** [comment]
there seems to be something wrong with the armada packages. I've tested it for armadaxp, and while I can build stuff (tested it with Sonarr) against the beta2 toolchain, it will fail with this final version :-(

**Comment by mettix** [comment]
which toolchain i need for DSS1515+?

**Comment by piwi82** [comment]
Your DS1515+ architecture is `avoton` : https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model

**Comment by faun** [comment]
Sonarr installation is having issues with linked libraries (mediainfo, specifically) see https://github.com/Sonarr/Sonarr/issues/1303

**Comment by Dr-Bean** [comment]
@faun, thanks for reporting. However, it doesn't seem directly related to DSM6 toolchains, and you're not providing a lot of information. 
Please create a new issue, following [this template](https://github.com/SynoCommunity/spksrc/issues/new?title=%5Bpackage%5D%3A%20Description%20&body=Issue%20description%3A%0AModel%3A%0AArchitecture%3A%0ADSM%20version%3A%0ALog%20file%3A). See https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issue-content for other details.

**Comment by Dr-Bean** [comment]
PR at #2306, waiting for more progress on #2216.

**Comment by szyb** [comment]
Is there any workourand to make mono works on DS215j?

**Comment by Dr-Bean** [comment]
DSM6.0.2 toolchains have been added into a new `dsm6` branch. Will get merged to master eventually, but at least it means we can produce packages with that toolchain.
I think I'll close this one for now.
