### ISSUE TITLE
Add iperf[23] package

### ISSUE THREAD

**Issue by mildis** [SynoCommunity/spksrc#2300]
Feature request to add iperf2 and iperf3 packages to SynoCommunity.

**Comment by cytec** [comment]
Please follow the guidelines when opening a new request: https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#package-requests

**Comment by mildis** [comment]
Website:
* iperf2 : https://sourceforge.net/projects/iperf2/
* iperf3 : http://software.es.net/iperf/

Description: iperf is a tool to test network bandwidth.

Documentation: see websites

Build/Installation documentation: 
* iperf2 : classic configure/make (see website)
* iperf3 : https://github.com/esnet/iperf/blob/master/INSTALL

Source code: 
* iperf2 : https://sourceforge.net/projects/iperf2/files/iperf-2.0.8.tar.gz/download
* iperf3 : https://github.com/esnet/iperf

License: BSD

**Comment by abrodkin** [comment]
iperf is indeed quite an essential tool which helps to benchmark bandwidth of networking so it would be really good to have it available for Synology NAS.

**Comment by publicarray** [comment]
I believe this can be closed. iperf is part of the `Syno-CLI Monitor` package.
