### ISSUE TITLE
tvheadend testing 4.1.1953-1 wont start

### ISSUE THREAD

**Issue by codac** [SynoCommunity/spksrc#2301]
After updating tvheadend testing to 4.1.1953-1, the package wont't start at all.
Protocols are all empty, so hint for the root cause.

**Comment by steef84** [comment]
On DSM6 latest version DS213+ qoriq proc tvheadend won't start neither with start-stop-script. However starting the binary manually seems to work.

**Comment by GoodOmens83** [comment]
SynoCommunity does not produce the tvheadend-testing package.  You might try posting here: https://tvheadend.org/projects/tvheadend/boards
