### ISSUE TITLE
[Tiny Tiny RSS] Fails to install on DSM 6.0

### ISSUE THREAD

**Issue by Bobyl** [SynoCommunity/spksrc#2304]
Installation of Tiny Tiny RSS on a fresh DSM 6.0 install fails on error: «Bad MySQL root password»

I have of course checked for usual mistakes (caps lock), i've changed the sql password to a trivial one in case some characters were badly transfered (special characters or accentuated), I've even tried with an empty root password.

Manual install of tt-rss on the NAS works (excepted for the php/php56 issue with feed update).

NAS = DS213j
DSM version = 6.0-7321 Update 6

**Comment by Dr-Bean** [comment]
See #2217, #2093 and #2056. I believe I already fixed this particular error, but new packages have not been released yet: we need #2296 to be implemented first. Closing as duplicate.
