### ISSUE TITLE
[HAproxy] /sbin/ldconfig: No such file or directory

### ISSUE THREAD

**Issue by BenjaminRousseau** [SynoCommunity/spksrc#2308]
Hello everyone,

I tried to install HAproxy but I can't launch it.
I get this error :  /sbin/ldconfig: No such file or directory

What can I do ? 

Thank you !

**Comment by Dr-Bean** [comment]
Follow the guidelines when reporting an issue please: chttps://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issue-content.

**Comment by BenjaminRousseau** [comment]
I tried to install HAproxy from the Synology package manager. It was well installed. But when I launch the service, I get this error : "/sbin/ldconfig: No such file or directory"

DSM version : 6.0-7321 update 6
No specific log
bash_err.log:
```BASH_ERR: report_error [ (9098)"/usr/local/haproxy/env/bin/python /usr/local/haproxy/env/bin/pip install --use-wheel --no-deps --no-index -U --force-reinstall -f /usr/local/haproxy/share/wheelhouse -r /usr/local/haproxy/share/wheelhouse/requirements.txt" -> (9109)"sh -c /sbin/ldconfig -p 2>/dev/null" -> (9112)"sh -c /sbin/ldconfig -p 2>/dev/null" ] sh: /sbin/ldconfig: No such file or directory```

And when I launch manually the package :
Starting HAProxy ...
[ALERT] 131/230324 (16122) : parsing [/usr/local/haproxy/var/haproxy.cfg:34] : 'bind :5443' : unable to load SSL certificate from PEM file '/usr/local/haproxy/var/crt/default.pem'.
[ALERT] 131/230324 (16122) : Error(s) found in configuration file : /usr/local/haproxy/var/haproxy.cfg
[ALERT] 131/230324 (16122) : Proxy 'https': no SSL certificate specified for bind ':5443' at [/usr/local/haproxy/var/haproxy.cfg:34] (use 'crt').
[ALERT] 131/230324 (16122) : Fatal errors found in configuration.

I also see that my default.pem file is empty.

**Comment by Dr-Bean** [comment]
Still missing information (model), check the guidelines. 
I do believe that a missing `sbin/ldconfig` isn't blocking, or at least, it shouldn't be from what I can tell.

Do `/var/log/synopkg.log` and/or `/var/log/messages` provide any info? You may need to attempt a new install of haproxy if the logs have already rotated, if you post logs, please limit them to the relevant parts.

**Comment by BenjaminRousseau** [comment]
The problem was linked to the ssl certificate that was a blank file ...
