### ISSUE TITLE
Mosquitto for Synology DS213 with DSM 4.2

### ISSUE THREAD

**Issue by kranena** [SynoCommunity/spksrc#2310]
Hi

I am looking for mosquitto for a ds213 (88f6282 ) with DSM 4.2.
According to the architecture it should be possible, but it is not visible in the package center

is it supported?

Regards,
Andre

**Comment by Dr-Bean** [comment]
4.2 is no longer supported by us, no. See also https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support.

You can attempt to compile it yourself. See the README: setup a development/build environment and then take a look at https://github.com/SynoCommunity/spksrc/wiki/spksrc-example. 
You may run into issues where certain dependencies can't be compiled, but there's only one way to find out if that's the case.
