### ISSUE TITLE
Update SABnzbd to 1.0.2: Fix Sonarr history in SABnzbd

### ISSUE THREAD

**Issue by CurseOfDamnation** [SynoCommunity/spksrc#2317]
Issue:
Sonarr is not able to read the status from Sabnzbd from history-API
Because of this it won't send a bad download to the blacklist.
So next time it will try the same download again.
So failed downloads need to be blacklisted manually.

Issue is solved in 1.0.1 release of SABNZBD
https://github.com/sabnzbd/sabnzbd/releases/tag/1.0.1

Model: DS1515+
Architecture: synology_avoton_1515+
DSM Version: DSM 6.0-7321 Update 7

**Comment by stevehoek** [comment]
SABnzbd 1.0.2 is now out... please use latest version when repackaging for syno
https://github.com/sabnzbd/sabnzbd/releases/tag/1.0.2

**Comment by KaraokeStu** [comment]
This will be fixed once pull request https://github.com/SynoCommunity/spksrc/pull/2324 has been accepted

**Comment by CurseOfDamnation** [comment]
I've added a bounty to this issue.
https://www.bountysource.com/issues/34192180-update-sabnzbd-to-1-0-2-fix-sonarr-history-in-sabnzbd

**Comment by CurseOfDamnation** [comment]
Release 1.0.3 just got released:
https://github.com/sabnzbd/sabnzbd/releases/tag/1.0.3

Bugfixes in 1.0.3

Fix jobs hanging at 99% or 100%
Support X-DNZB-PASSWORD header for indexers that use this
Prevent fatal "too many connections" issue
Show checksum errors reported by unrar
Windows: fix coupling of NZB files to SABnzbd, when the name contains non-US-ASCII characters

**Comment by KaraokeStu** [comment]
No problem, I'll get this moved into the commit in the next couple of days

**Comment by Popsikill** [comment]
Just curious when we can expect the newer 1.0+ SABnzbd to be pushed out to our Synology?
(Have a DS1813+)

**Comment by KaraokeStu** [comment]
I'll try to get the pull requests sorted tomorrow afternoon for 1.0.3 in both testing and release.

Then it's up to the maintainer to accept the request and publish it.

However, if you need a test package, I'll upload the compiled packages in the interim for the testing version.

Stu

**Comment by KaraokeStu** [comment]
Fixed with PR https://github.com/SynoCommunity/spksrc/pull/2365

**Comment by KaraokeStu** [comment]
Also testing updated with PR https://github.com/SynoCommunity/spksrc/pull/2366

**Comment by CurseOfDamnation** [comment]
Thanks @KaraokeStu :+1:

**Comment by KaraokeStu** [comment]
Pull requests now ready to merge

**Comment by KaraokeStu** [comment]
If anyone wants 1.0.3 before it is published, let me know and I'll post the link

**Comment by CurseOfDamnation** [comment]
@KaraokeStu,  that would be great :)

**Comment by Popsikill** [comment]
Any idea how long it's going to take to flow through to our Synology? And yea a link would b great :)

**Comment by KaraokeStu** [comment]
Hi,

It'll take as long as it takes, but in the mean time you can download the relevant package here:

http://syno.karaokestu.co.uk

Cheers,

Stu

**Comment by Popsikill** [comment]
Thanks Stu!

Which one should I download for a DS1813+? Will this overwrite my existing SABnzbd+ as an update would? Would future updates be as normal through package manager? and would this fix the issue it has with zip and/or adduser?

Cheers :-)

**Comment by KaraokeStu** [comment]
Based on your model number, you should download the cedarview build, however I hadn't compiled that one yet... Compiling now! 

It'll work exactly the same as a normal package and will upgrade your existing install and will accept future updates from the package centre.

This will definitely fix the issue with zip, however I'm not sure about adduser

**Comment by Popsikill** [comment]
Mate you are a champion! keep fighting the good and will download and install this evening :-)

**Comment by KaraokeStu** [comment]
All fixed, the original link now works again.

@Popsikill the link for you is http://syno.karaokestu.co.uk/sabnzbd_cedarview-5.2_1.0.3-16.spk

**Comment by Dr-Bean** [comment]
sabnzbd 1.0.3-16 has been published on the repository.

**Comment by madvtak** [comment]
@KaraokeStu would you happen to still have 0.7.20-24

**Comment by KaraokeStu** [comment]
Not at the moment, but I could probably generate it - what model do you need it for? 

@Dr-Bean Is it worth generating a sabnzbd-classic package for people not wanting to upgrade to 1.x?

**Comment by madvtak** [comment]
@KaraokeStu it would be for the DS1515+

I would second having a SABnzbd-Classic for those not wanting to upgrade until all the bugs are worked out of the 1.x

**Comment by Dr-Bean** [comment]
I'm sorry, but I don't see that happening. There's nothing unstable about the 1.0.x releases. It's the same codebase as 0.7.20, and it would have been called 0.8.x, but the SABnzbd devs felt that it was time to renaming start with a fresh 1.0.x.

Take a look at the [SABnzbd releases]( https://github.com/sabnzbd/sabnzbd/releases) page to get an idea of how the 1.0 branch has developed: the amount of beta's and RC's tells me there's attention to detail.
As for SynoCommunity, we've had the -testing package at 1.0.x for a while, with zero bugreports on our side. The current unstable is 1.1.x, and the -testing package had just had an update to that so people can help test that version.

If you don't like the Glitter skin, Plush is still available in the settings.
And of course, if you feel you did find a bug in SABnzbd after all, check the [sabnzbd forums](https://forums.sabnzbd.org), or report an issue on their Github repo: the devs are very responsive.

**Comment by madvtak** [comment]
@Dr-Bean So do i need to open a new issue with not able to start the package? I already seen the various issues that others are having with just getting the the package to run. I'm sure there are no bugs but i just can't start it period. That's why i asked if @KaraokeStu can upload an older package because i updated and it broke.

**Comment by KaraokeStu** [comment]
Hi @madvtak please could you create a new issue with the problems you have starting and, if possible, include your logs with identifiable information removed.

Thanks

**Comment by Dr-Bean** [comment]
@madvtak Yes please. Answer the questions asked in the template, so we have a starting point. Note that DSM6 support, what all the other issues are about, are not solved yet. That is unrelated to SABnzbd.

**Comment by madvtak** [comment]
@Dr-Bean & @KaraokeStu  i don't think creating an new issue will help, this is with the latest  DSM 6.0.1-7393. I believe there are a lot of us awaiting for all the bugs to be ironed out with DSM6 and a lot of the packages. Like i've stated i just updated and now the package doesn't start anymore. I just want to try and roll back to the older package. I have no logs currently, i uninstalled and tried doing a fresh install of the package. No joy.

**Comment by Dr-Bean** [comment]
Open a new issue please.

**Comment by madvtak** [comment]
so im guessing no roll back package? @KaraokeStu

**Comment by KaraokeStu** [comment]
If you've uninstalled, then I believe you'll have the same issue with the earlier package too
