### ISSUE TITLE
dsm6: debian-chroot no web-based daemon-configuration possible

### ISSUE THREAD

**Issue by schrolli** [SynoCommunity/spksrc#2318]
Hi,

i successfully installed debian-chroot on my rs815+ and wanted to follow some blogposts on adding autostart-daemons (e.g. https://markpith.wordpress.com/2015/10/26/debian-chroot-on-synology-nas/) But i wasn't able to find the described link/page in the dsm-web-gui. Especially: 

> open the Debian Chroot package in the DSM web interface. On the left hand click on services.

where can i "open the debian chroot package"? I have only an entry in the package-manager, but neither in the control-center nor a new button in the "Main Menu" or on the desktop. And in the package-manager, there is no "services" button. The "action" selectbox only holds two elements: start/stop and uninstall.

![debian_chroot_package_manager](https://cloud.githubusercontent.com/assets/2263484/15250166/b996c688-1923-11e6-89c4-e7304bffde07.png)

I have searched here in the issues and on google, but didn't found anything related to this. I hope, you can help me.

I can live with a manual file-config, if the gui is broken due to dsm6-upgrade. but i didn't found anything on that topic, too...

greetings,
schrolli

**Comment by Dr-Bean** [comment]
#1910 for DSM6-related stuff. If you're missing the Debian-Chroot icon in the menu, take a look at the FAQ: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#a-package-does-not-show-an-icon-in-the-dsm-menu-how-can-i-fix-this

**Comment by schrolli** [comment]
thanks for the quick response.

though, #1910 is dealing with infinite loading of a page after clicking the "Chroot-icon". the FAQ simply suggests to log in as admin. I had forgotten to mention, that i am logged in as admin...

Additionally, i didn't mention, that i upgraded to dsm6 and after that, i made a "clean install" of the chroot-package. In the meantime, i rebooted the rackstation with no luck.

Am I right, that there should be a new icon in the "main menu" on the top left?

**Comment by divx118** [comment]
@schrolli https://github.com/SynoCommunity/spksrc/wiki/Debian-Chroot should be a good read. BTW I am also experiencing the same issue DSM config is not working on 6.0. Probably some permission issue, however I need to look into that yet. From the command line it works fine, I added a normal user to the chroot with sudo rights and started a ssh server of course on a different port then the one from DSM. ssh directly into the chroot works fine now.

**Comment by schrolli** [comment]
@divx118 i surely had read that wiki-page before. I have no issues with installing the packages inside the chroot. I only am not able to configure the service to start on boot-time.

@all: are these configurations saved in the postgres-database? do i have a chance to add some rows to get it working, or where are these configurations saved? thanks in advance!

**Comment by divx118** [comment]
@schrolli Just add the chroot start command in /etc/rc.local from DSM. At least the ssh service starts automatically when starting the chroot. If your service doesn't then add it to the init.d scripts in the chroot or I don't know if rc.local is executed (didn't try it yet) add it to /etc/rc.local in the chroot.

**Comment by belkone** [comment]
for fix, look: https://github.com/SynoCommunity/spksrc/issues/1910#issuecomment-253990371

**Comment by Mausy5043** [comment]
@divx118 :  With DSM6.1 there is no `/etc/rc.local` in DSM.  
[Synology's](https://developer.synology.com/developer-guide/integrate_dsm/run_with_system_boot.html) instruction is to use `/usr/local/etc/rc.d/` . That **does** exist.
