### ISSUE TITLE
[DELUGE] does not save/load configuration after a reboot

### ISSUE THREAD

**Issue by Vilscon** [SynoCommunity/spksrc#2325]
_Everything was running fine until I updated to DSM 6.0 and my DS216+ updated from 32-bit to 64-bit and PGSQL didn't jump from 32-bit to 64-bit resulting in Video station and other applications to malfunction. Therefor I did a reset by pressing the reset-button on the back of my machine for 4 seconds twice. Everything _as it seems_ as deleted and I had to reinstall everything. However.._
## 

Somehow Deluge isn't working correctly. Unlike before, after every reboot Deluge forgets it's configuration, such as plugins enabled and the configuration of my proxy settings. Strange thing is.. if I enable 'labels', all labels and it's configuration are loaded. This sadly doesn't occur too with the proxy settings.

I simply can't find a way to resolve this and let Deluge read the damn core.conf file.
I can confirm, however, that the actual configuration is present when I 
`vi /volume1/@appstore/deluge/var/core.conf`

I just want a torrent downloader that can use a proxy. Any.
## 

I already reinstalled deluge about 5 times, with and without reboots, with and without adding a manual user called 'deluge' and adding it to the administrator group. I've given up pretty much right now.

Also if I just stop the deluge service (/scripts/start-stop-status stop - start), deluge loses all it's settings.
## 

DSM 6.0 Update 7
DS216+ with Intel soc.

**Comment by Dr-Bean** [comment]
DSM6 is not supported yet. See #2207, #2216 etc.

**Comment by Blackvibes** [comment]
But isn't there any work-around? I got it completely working after upgrading from 5.2 to DSM 6 and my DS216+ had a technical issue, so I got a new one under warrenty which came with DSM 6.0 update 2 out of the box and I got Deluge working without any issue. 

Just when I reinstalled the machine to update from 32-bit to 64-bit and it jumped to DSM 6.0 update 6 (now 7) somehow deluge isn't working. Even when going at `adduser` manually.

**Comment by Blackvibes** [comment]
### Workaround!
As I, somehow, can't fix Deluge saving it's configuration I simply gave up. However, I remembered some stuff I read regarding running Deluge inside a docker container. **1)** So I installed Docker and **2)** loaded a LinuxServer-deluge _(or something like that called, just search for Deluge)_ image which only installs Deluge inside a docker environment. Pretty lightweight, only requesting a few MB's of RAM and a minor touch of your CPU, I guess. (5 mins experience yet). I stopped- and restarted the docker container, I restarted my Synology without stopping docker. In both situations Deluge kept running perfectly, unlike running it locally.

So my advice for Deluge users: Just set-up Docker.

I'll stick this way until I read about a nicely working Deluge installable directly from the SynoCommunity.

_Oh, and by the way: you can set Deluge to port 8112, so you don't need to reconfigure other applications to another port._

**Comment by Safihre** [comment]
Tracked in #2931.
