### ISSUE TITLE
[request] : Mattermost

### ISSUE THREAD

**Issue by romu70** [SynoCommunity/spksrc#2326]
Mattermost is an open source alternative to Slack, so it would be great to have it packaged within our Syno. Thanks.

http://www.mattermost.org/

**Comment by Dr-Bean** [comment]
Please use the search before opening an issue as per the [guidelines](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#package-requests).
Duplicate of https://github.com/SynoCommunity/spksrc/issues/2153.

**Comment by romu70** [comment]
Yes, my bad, sorry.
