### ISSUE TITLE
Unable to run apt-get

### ISSUE THREAD

**Issue by stonesrose** [SynoCommunity/spksrc#2327]
Neither apt-get nor aptitude are installed. 

Fresh install 5/17

root@DiskStation:~# /var/packages/debian-chroot/scripts/start-stop-status chroot
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
root@DiskStation:/# apt-get update
bash: apt-get: command not found
root@DiskStation:/#

root@DiskStation:/# find . -name apt-get
root@DiskStation:/#

root@DiskStation:/# find . -name apt
./var/lib/apt
./var/cache/apt
./etc/apt
root@DiskStation:/#

**Comment by baz1860** [comment]
I've had a couple of drinks, so I may be remembering this wrong, but there
was an issue in Debian a few years ago where a similar thing happened, if
you issues the command 'sudo aptitude install aptitude' it may configure
properly - this seems ridiculous but i remember it working in the past

**Comment by Dr-Bean** [comment]
@stonesrose Adding a model would be appreciated. If it's PPC based, it's probably a known issue.

**Comment by meffect** [comment]
I have this same problem.. synology ds1813+ dsm 6.0

**Comment by talisto** [comment]
I just ran into the same issue as stonesrose.  Running on a DS1515+ w/ DSM 6.0.2-8451 Update 1, Debian Chroot installs fine, but apt-get does not seem to exist.  

root@diskstation:/opt/lib# /var/packages/debian-chroot/scripts/start-stop-status chroot
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
root@diskstation:/# find / -name apt-get
root@diskstation:/#

Is this not supported on DSM 6.0?
