### ISSUE TITLE
Package source unavailable in Docker DSM

### ISSUE THREAD

**Issue by dArk4psyco** [SynoCommunity/spksrc#2328]
in Docker DSM i can not add Synocommunity package source.
Message "invalid location" appears.
I have set the Trust Level to Synology Inc. and trusted publishers.

**Comment by Dr-Bean** [comment]
Use the search before opening an issue as per the [guidelines](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issues)
Duplicate of https://github.com/SynoCommunity/spksrc/issues/1889.
