### ISSUE TITLE
Lazy Librarian fails to run

### ISSUE THREAD

**Issue by sea3pea0** [SynoCommunity/spksrc#2336]
I troubleshooted this a little bit by trying to issue the command to run this app from the command line and noticed that I get a "su: permission denied" for the "su - lazylibrarian" part of the command. Anybody have a quick idea as to the source of the problem?

**Comment by Dr-Bean** [comment]
Please follow the guidelines when reporting an issue: https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issue-content.

**Comment by sea3pea0** [comment]
- DS412+,
- DSM 6.0-7321 Update 7 (cedarview)
- Package fails to run after clicking "Run" in package center
- Manually issued run command from start-stop-status script
- Got message "su: permission denied"
- Tried issuing just "su lazylibrarian" got same message as before
- Tried "su nzbdrone" and it worked
- From synoservice.log:
`May 22 10:35:31 dsm synoscgi_SYNO.Core.Package.Control_1_start[19586]: service_start.c:180 synoservice: [pkgctl-lazylibrarian] start failed.[0xD900 manager.cpp:204]
May 22 10:35:32 dsm synoscgi_SYNO.Core.Package.Control_1_start[19586]: service_stop.c:23 synoservice: [pkgctl-lazylibrarian] stopping ...`

**Comment by Dr-Bean** [comment]
The current package installer isn't able to create users on DSM6, so you're supposed to see a `Failed to run package service` due to a non-existent user if nothing else has been touched.

Instead, you seem to have created a user manually. That user does not have sufficient permissions to run commands, hence the error. See #2207, #2216 and most of the issues labeled with `dsm 6.0` on this tracker.

**Comment by sea3pea0** [comment]
Ok I see this is probably a DSM 6.0 problem. I didn't add the "lazylibrarian" user manually. The package managed to do so on its own. All the other packages I've installed from Syno Community that I have installed on DSM 6.0 so far have worked for me (Sonarr, Couch Potato Custom etc.)

**Comment by Safihre** [comment]
DSM6 compatible version of the package is expected to be released soon. It can already be installed by downloading it from here #3138.
After the official release on SynoCommunity, the package will auto-update from the official release.
