### ISSUE TITLE
Update tvheadend-testing to 4.2.x

### ISSUE THREAD

**Issue by aesthetiker** [SynoCommunity/spksrc#2338]
Please update tvheadend-testing to 4.2.x builds.

**Comment by Dr-Bean** [comment]
We don't provide a tvheadend-testing package.

**Comment by aesthetiker** [comment]
Sure source is synocommunity checked that again.

**Comment by Dr-Bean** [comment]
No, it's not :) See the list of packages here: https://synocommunity.com/packages.
We have a `tvheadend` package here: https://synocommunity.com/package/tvheadend. We do not have a `tvheadend-testing` package.

**Comment by pepeEL** [comment]
TVheadend 4.2 is not released...
About update TVHeadend-testing please write to user J. Dierkse <j.dierkse@madeo.nl>

**Comment by pepeEL** [comment]
But why Synocommunity not support TVHeadend-testing ?

**Comment by Dr-Bean** [comment]
@pepeEL I'm quite sure you have asked that question before, and I have answered it before. SynoCommunity is a volunteer-driven effort. If no-one makes the effort, nothing happens.
