### ISSUE TITLE
Add Duplicati package

### ISSUE THREAD

**Issue by kenkendk** [SynoCommunity/spksrc#2342]
Duplicati now has a Synology package:
https://github.com/duplicati/duplicati/releases

What would be required to add it to SynoCommunity?

It is 100% CIL code, meaning that it does not require architecture specific compilation, it relies only on the Mono package and includes all dependent libraries. 

Unless you _want_ to compile it from source, it is much easier to just grab the latest zip and build the spk as done with this script:
https://github.com/duplicati/duplicati/blob/master/Installer/Synology/make-binary-package.sh
- Website: http://www.duplicati.com
- Description: Duplicati is a free, open source, backup client that securely stores encrypted, incremental, compressed backups on cloud storage services and remote file servers.
- Documentation: https://github.com/duplicati/duplicati/wiki
- Build/Installation documentation: https://github.com/duplicati/duplicati/wiki/How-to-build-from-source
- Source code: https://github.com/duplicati/duplicati
- License: LGPL 2.1

**Comment by Dr-Bean** [comment]
Assuming you're interested in setting up the package yourself, I would suggest taking a look at the Jackett package we have.
It's a relatively basic package, and might serve as a good starting point for creating a package for Duplicati.
Here's the commit where I added it: https://github.com/SynoCommunity/spksrc/commit/aeac78cb0b82d6bb5d69aa68867f91a983e2a7da.
We're not looking to compile from source for this type of software, so using a zip is fine with me: that's what the cross package is used for.

**Comment by KaraokeStu** [comment]
I've had a quick look at this, however it is a little different to the standard Mono installs we have used in the past, as this also requires us to generate the website as well as starting the daemon.

Their scripts do it, but I'm investigating what is required to convert their script into a SynoCommunity "friendly" install method.

@Dr-Bean Do we have any other packages that spawn a daemon along with the website and a proxy?

**Comment by publicarray** [comment]
For 64 bit devices duplicati has released an official spk: https://www.duplicati.com/download
