### ISSUE TITLE
Update syncthing to 0.13

### ISSUE THREAD

**Issue by christofdamian** [SynoCommunity/spksrc#2343]
_[For package requests, click here](https://github.com/SynoCommunity/spksrc/blob/master/.github/PACKAGE_REQUEST_TEMPLATE.md)_.

I know this will happen eventually, but I thought it would be good to track this as 0.12 is not compatible with 0.13. The Linux packages (Fedora at least) and Android app are already on 0.13.

### Setup
Package Name:  syncthing
Package Version:  

### Expected behaviour
Syncthing connects to other clients

### Actual behaviour
Syncthing 0.12 is not compatible to 0.13, so this version has to be updated

**Comment by Dr-Bean** [comment]
@cytec Any progress in getting `Go` updated? Not that there's a dependency, but its probably easy enough to combine :)

**Comment by cytec** [comment]
should be doable doe to lack of time lately i haven't really done anything...
if i remember correctly 1.6+ requires a already installed 1.4 version of go to enable cross compilation... so you are cool with https://github.com/SynoCommunity/spksrc/issues/2176#issuecomment-208222178? useing `go-1.4` to bootstrap `go`?

**Comment by cytec** [comment]
merged and published
