### ISSUE TITLE
rtorrent not available as a download option in the gui

### ISSUE THREAD

**Issue by tirrorex** [SynoCommunity/spksrc#2344]
Hi, it seems rtorrent is not an option in the gui anymore (at least i don't have it).
I am using latest version from developp branch with https://github.com/tuxeh/docker-sonarr
I have enable advanced settings.
Is there something special to do? did you guys remove rtorrent as a download client option?

**Comment by Dr-Bean** [comment]
Did you mean to open an issue on the Sonarr forums/Sonarr bugtracker?

**Comment by tirrorex** [comment]
Shit i must have clicked into a link before opening the issue T_T
