### ISSUE TITLE
Apply patches only for a list of arch

### ISSUE THREAD

**Issue by GuillaumeSmaha** [SynoCommunity/spksrc#2346]
I have patches to apply due to the old version of gcc (parse error) and I think it's not a good idea to apply it for the recent archs.
Example : a static method is called and gcc crashes because there is private so commenting private keyword solves the issues.

My question is : do have a method to apply a patch for a set of arch like (ppc824-4.2 powerpc-4.0) ?

**Comment by Dr-Bean** [comment]
Presumably something like the following works:
```
PATCH_TARGET = nop
ifeq ($(findstring $(ARCH),ppc824 powerpc),$(ARCH))
PATCH_TARGET = patch_target
endif
```
...but that has two downsides (other than being extremely ugly...): it probably won't take the TCVERSION into account, and if a patch applies to one arch but not the other, that's even worse.

I wouldn't mind if you skipped all that, set those arches as `UNSUPPORTED` (or set `MINIMUM_DSM` to 4.3) and went from there. It's not worth the effort. We don't provide packages on our repo, or even support for EOL DSM versions, and 4.2 and older definitely belongs in that category.
What do you think?

**Comment by GuillaumeSmaha** [comment]
I will try it and instead of using `$(ARCH)`, i will use `ifeq ($(ARCH)-$(TCVERSION), ppc824-4.2)`.

The aim is only to fix some bugs like `internal compiler error: internal consistency failure` which often need a specific fix.

Yes, those DSM versions are unsupported but this method could be useful in the future :)

**Comment by Dr-Bean** [comment]
Probably the better approach is to make sure the patch itself includes directives to apply only in the correct circumstances.

**Comment by GuillaumeSmaha** [comment]
I can apply a patch which contains a `#ifdef GlobalVar` to use the specific code only for a defined `arch-dsm`
See the example : https://github.com/GuillaumeSmaha/spksrc/commit/5c12965e562465c8c02fc4913cbc31e388901b04

Or I can add a new directory for the patches, what do you think about this approach https://github.com/GuillaumeSmaha/spksrc/commit/3e4c1e630e5666f6459d338a6c2c215091526313 ?

**Comment by Dr-Bean** [comment]
As containing the patch stuff inside the patch probably makes the most sense here, let's go with the first option in 5c12965. Nice work :)

I'll add some comments on the Makefile (well, on the whole PR probably ;) ) when merged and it's time to review.

**Comment by GuillaumeSmaha** [comment]
I close the topic. Thanks for your answer.
