### ISSUE TITLE
Feng Office Installer Claims MySQL Root Password is Incorrect

### ISSUE THREAD

**Issue by ghost** [SynoCommunity/spksrc#2348]
### Setup

_Package Name:_  Feng Office
_Package Version:_ 2.5.1.2-3

_NAS Model:_ DS414
_NAS Architecture:_
_DSM version:_ DSM 6.0-7321 Update 6
### Expected behavior

The installation process to accept the MySQL correct root password and complete installing the package
### Actual behavior

The installation process aborts claiming the MySQL root password is incorrect 
### Steps to reproduce

_1._ Open Package Center
_2._ Click Community Tab
_3._ Select Feng Office
_4._ Click Install
_5._ Enter MySQL root password
_6._ Enter Feng Office MySQL user password
_7._ Click Next
_8._ Enter Domain name
_9._ Click Next
_10._ Confirm settings and click Apply
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

```
No log file
```
#### Other logs

_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

```
2016/05/27 10:55:41 install  :
            End:    /bin/mkdir -p /volume1/@tmp/pkginstall/package  ret=[0]
2016/05/27 10:55:41 install  :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/fengoffice/@SYNOPKG_DOWNLOAD_fengoffice -C /volume1/@tmp/pkginstall --no-same-owner
2016/05/27 10:55:41 install  :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/fengoffice/@SYNOPKG_DOWNLOAD_fengoffice -C /volume1/@tmp/pkginstall --no-same-owner    ret=[0]
2016/05/27 10:55:41 install fengoffice 2.5.1.2-3:
            Begin:  /bin/tar xf /volume1/@tmp/pkginstall/package.tgz -C /volume1/@tmp/pkginstall/package --no-same-owner
2016/05/27 10:55:43 install fengoffice 2.5.1.2-3:
            End:    /bin/tar xf /volume1/@tmp/pkginstall/package.tgz -C /volume1/@tmp/pkginstall/package --no-same-owner    ret=[0]
2016/05/27 10:55:43 install fengoffice 2.5.1.2-3:
            Begin:  preinst
2016/05/27 10:55:43 install fengoffice 2.5.1.2-3:
            End:    preinst ret=[1]
2016/05/27 10:55:43 install fengoffice 2.5.1.2-3:
            Begin:  /bin/rm -rf /volume1/@tmp/pkginstall
2016/05/27 10:55:44 install fengoffice 2.5.1.2-3:
            End:    /bin/rm -rf /volume1/@tmp/pkginstall    ret=[0]
2016/05/27 10:55:44 install fengoffice 2.5.1.2-3 failed

```

**Comment by mettix** [comment]
Hello,

I'm having +/- the same issue since januari for removing Owncloud from my Synology.. Seen some workarounds, but none that worked for me..

**Comment by Dr-Bean** [comment]
Ref #2093, which is already implemented, and #2216, which is in progress,

**Comment by knutzmann** [comment]
have the same problem on my DS214 installing fengoffice .. is there a solution yet?

**Comment by attilabal** [comment]
Same issue here. I did change the root pwd but the installation is faild over and over again...

**Comment by josonwang** [comment]
Same problem on my NAS synology D216j, Did this one still not solved yet?

**Comment by Sigawan** [comment]
Installation of the feng office package on the latest  DSM 6.1.5 15254 fails with the same error as most other packages hosted at synocommunity 'incorrect mysql root password'

Is any work being done on this generic problem in the years since it was first reported?

**Comment by josonwang** [comment]
No body to do this re-correct work

**Comment by Sigawan** [comment]
I gather from comments scattered around, that Synology made undocumented changes from DSM 5 to 6 which break these packages & Synology will not provide up to date documents?

**Comment by ymartin59** [comment]
Yes they did. Search for Synology DSM SDK and development guide.
