### ISSUE TITLE
debian-chroot cannot mount /volume1

### ISSUE THREAD

**Issue by artelse** [SynoCommunity/spksrc#2350]
In the start-stop-status script of debian-chroot I added the following to mount /volume1:

`grep -q “${CHROOTTARGET}/volume1 ” /proc/mounts || mount -o bind /volume1 ${CHROOTTARGET}/volume1`

When I start the script it cannot find the volume with this error:

`mount: mount point /volume1/@appstore/debian-chroot/var/chroottarget/volume1 does not exist`

Any ideas? I followed instructions from this [blog post](https://markpith.wordpress.com/2015/10/26/debian-chroot-on-synology-nas/).
Running DSM 6.0 on a DS214+

**Comment by Dr-Bean** [comment]
The error kind of speaks for itself, doesn't it? The mount point you want to map `/volume1` to does not exist. You'll have to create it.

**Comment by artelse** [comment]
That's what I thought of course, but the mount point does exist. But when I `ls /volume1` it lists `@appstore`, but I can't tab-complete it.. it cannot find it. I am root, so that excludes a permissions problem. Sorry I am not a unix tiger (yet) ;)

**Comment by artelse** [comment]
Your first answer was correct, I had to create the mount folder first. Thanks for the help!
