### ISSUE TITLE
[Package Request] Borg Backup

### ISSUE THREAD

**Issue by Obruut** [SynoCommunity/spksrc#2351]
Description: BorgBackup (short: Borg) is a deduplicating backup program. Optionally, it supports compression and authenticated encryption.
Website: http://borgbackup.readthedocs.io
Documentation: http://borgbackup.readthedocs.io/en/stable/usage.html
Build/Installation documentation: http://borgbackup.readthedocs.io/en/stable/installation.html
Source Code: https://github.com/borgbackup/borg
License: https://borgbackup.readthedocs.io/en/stable/authors.html#license

**Comment by artelse** [comment]
I just installed Borg onto debian-chroot and no problems compiling/installing. I am only having problems mounting volumes as posted in previous issue.

**Comment by Obruut** [comment]
True, that's possible. But I think more people could use Borg if it was possible to install as a package.

The past months Borg Backup has grown to one of the best dedup backup programs I've know, and would love a 'native' solution.

**Comment by kBite** [comment]
@yuroller I'm very interested in this package. I have a DS218play and if possible would like to help. Would you please list all open tasks here?

**Comment by yuroller** [comment]
If you are able to build packages for you ds unit, borgbackup should build and (hopefully) run correctly.
Some time ago I successfully built borgbackup for all supported architectures by spksrc project, but I was able to test just on my ds212+ 6.0.2.
You can find build instructions on wiki.
Borgbackup depends on python3 packages, so you need both.
Ask if you need help.

**Comment by ymartin59** [comment]
Do not bother to build it yourself. I am publishing that package

**Comment by noplanman** [comment]
@ymartin59 Are you publishing others too? Where are they listed?

**Comment by noplanman** [comment]
:tada: Looks like Borg is now officially on the repo, great!

But it still needs a manual build/install of Python3, as the version on the repo is outdated.

Will that be updated soon as well?
@ymartin59 Is there a way to contribute builds to the project?

**Comment by ymartin59** [comment]
@noplanman What is your DSM architecture?

**Comment by noplanman** [comment]
`qoriq` and `armada370` are the ones I have.

I've built Python3 for both of them and installed Borg successfully, so all good :smiley:

**Comment by noplanman** [comment]
@ymartin59 I just noticed that the Python 3 package on the SynoCommunity packages page is at 3.5.2-5, but the constraint for Borg is set at 3.5.2-6.
As I still only see 3.4.1-4 in my DSM package center, I can't test to see if it works.

Also, I'd like to point to this comment, regarding the Python 3 version constraint:
https://github.com/borgbackup/borg/issues/719#issuecomment-383418808

**Comment by mannp** [comment]
@ymartin59 many thanks for creating these borg dsm packages, I have been trying to get borg going for some time on my dsm's without much success, so thanks!

Hoping the python version gets bumped at some stage to give them at try :grinning:

**Comment by mannp** [comment]
@ymartin59 many thanks for creating these borg dsm packages, I have been trying to get borg going for some time on my dsm's without much success, so thanks!

Hoping the python version gets bumped at some stage to give them at try.

**Comment by ymartin59** [comment]
I have published fixes with dependency to Python 3. Should be better.

**Comment by noplanman** [comment]
Awesome, thanks @ymartin59 :smiley: 

So as soon as all Python3 builds are available on the SynoCommunity repo, this can probably be closed off here.

**Comment by ymartin59** [comment]
From my point of view, all builds are already available... new borg package version can run with previous Python 3 revision.

**Comment by noplanman** [comment]
I still only see 3.4.1-4 in both my DS package centers.

They also aren't listed as available yet on the site, but I obviously don't know how that gets updated / rolled out (`armada370` and `qoriq`):
https://synocommunity.com/package/python3

**Comment by mannp** [comment]
@noplanman seems its v3.5.2-6  now :grinning:

**Comment by noplanman** [comment]
@mannp Yes! Not for all architectures yet though, but probably very soon :innocent: 

@ymartin59 On a side note:
It would be great if the spk builds could be downloaded directly from the SynoCommunity site. That way, it would be easily possible to install them via command line, which doesn't work at the moment (or I haven't figured it out yet).

**Comment by mannp** [comment]
@noplanman yes I checked here -> https://synocommunity.com/package/python3 but you are right, my qoriq is still on the previous version.

As you say, I'm sure it'll arrive soon :)

**Comment by ymartin59** [comment]
@mannp please update borgbackup from repository, it should run with previous python3 version you already have available for qoriq

**Comment by mannp** [comment]
@ymartin59 ok I see, but I only have versions 3.4.1-4 from synocommunity and 3.5.1-0108 from synology available.

So should it now work with the official synology package.

**Comment by kBite** [comment]
Because this package bundles `borgmatic` this may be the right place to ask: might someone bother to update bundled `borgmatic` from version `1.0.3` to latest (`1.1.15`).

I was able to successfully build `borgbackup_rtd1296-6.1_1.1.5-2.spk` with Docker, so bumping `borgmatic` seems uncomplicated:

```
diff --git a/spk/borgbackup/src/requirements.txt b/spk/borgbackup/src/requirements.txt
index 93406ef..2136059 100644
--- a/spk/borgbackup/src/requirements.txt
+++ b/spk/borgbackup/src/requirements.txt
@@ -3,4 +3,4 @@
 #msgpack-python==0.4.8
 
 # Downloaded dependencies
-borgmatic==1.0.3
+borgmatic==1.1.15
```

**Comment by ymartin59** [comment]
borgbackup 1.1.5 has been published
