### ISSUE TITLE
Remove branches `br_squidguard`, `tinc`, `zebulon` from SynoCommunity/spksrc

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2354]
The branches are all very outdated and unused. The only thing that might be interesting from my perspective is `tinc` as a package, but if that comes up, it shouldn't be too hard to set up a package for it.
@Diaoul, what do you think?

**Comment by piwi82** [comment]
We have tested `tinc` with @Diaoul a long time ago. There are several drawbacks in the configuration of `tinc`. It creates network devices and interfaces ([`tun`, `tap`](http://tinc-vpn.org/documentation/Network-interfaces.html#Network-interfaces)) that can not be handled by DSM (no firewall or routing through DSM), and the rest of the configuration requires good skills in networking.

As you have noticed, `tinc` branch is outdated and I think no one is interested in using it.

Should we delete this branches or archive it in a folder named `outdated` ?

**Comment by Dr-Bean** [comment]
I mentioned tinc because the commit didn't look to hard to replicate, I have no idea how the software works or is configured ;) It was before I was involved in spksrc, so thanks for explaining :)

If with 'archiving', you mean 'put it somewhere in master to keep it around': there's a point when we should delete what we don't intend to use. All three branches have been abandoned for 3 years or more, and I don't think there's anything useful in them at this point.

**Comment by piwi82** [comment]
OK for deleting then :wink:

**Comment by Diaoul** [comment]
Go for clean up!

**Comment by Dr-Bean** [comment]
Done, thanks guys :)
