### ISSUE TITLE
Transmission cannot launch

### ISSUE THREAD

**Issue by Surfi89** [SynoCommunity/spksrc#2355]
_For new Package Requests, see the guidelines_  
### Setup

_Package Name:_ Transmission
_Package Version:_ 2.92-12

_NAS Model:_ Synology DS216j
_NAS Architecture:_ I don't know where to check this
_DSM version:_ 6.0-7321 update 6
### Expected behavior

I installed the Transmission package from the community correctly and it should launch witouth any problems.
### Actual behavior

Instead of what it is expected to do, it gives me the message "Failed to run package service" and it does not launch.
I gave all read/write permission to all my users and group for the 3 Transmission shared folders and subfolders and when installing I put the login of a user created only for using Transmission, but I tried with my user too and it does not launch anyway.
What should I do?
### Steps to reproduce

_1._
_2._
_3._
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

```
The log is empty
```
#### Other logs

_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

```
The log is empty
```

**Comment by BrandonSk** [comment]
I confirm this behavior.
I have a fresh install of DSM 6.0-7321 Update 7. I did the reinstall couple of times and the behavior was the same. First package I installed was transmission - just to make sure that everything is default and not modified by other apps. Transmission service fails to start.

I tried changing permissions on shared folders as well as application folders and executables according to various guides. None of that helped.

Finally, modifying the start-stop-status script in /var/packages/transmission/scripts and changing user variable to root (USER="root") allows the package to run, but is not a solution.

So there is apparently an permission issue, but I am unable to find out where.

**Comment by Dr-Bean** [comment]
Ref #2216

**Comment by KeizerSauze** [comment]
Any solution yet ?

**Comment by sybold** [comment]
create a user named 'transmission' and add the appropriate permissions and user group permissions

**Comment by xkelly** [comment]
Having the same problem of the latest version of SynComm Trans not starting after updating to the latest DSM. When trying sybold's suggestion, I get "The user name already exists or is reserved for system use only."  Thoughts?

**Comment by silvioterra** [comment]
So I haven't seen anyone answer this conclusively, but I followed the steps on this video and got it working: https://www.youtube.com/watch?v=RPVs-Gt44dg

Mind you, my goal was to get it working WITHOUT giving the transmission user admin rights (which seemed to be the solution everyone else was saying).

The 'trick' was that you HAVE to set the complete/incomplete/watch directories (all 3) not just the first one (naming is of course up to you). I guess if you leave it blank the service will try to create some directories somewhere for the incomplete/watch directories and will fail. 

I'll admit that this is simply speculation from the fact that manually creating all 3 made the service actually start.

**Comment by thetoolman** [comment]
not sure why it happens, but the transmission user often gets set to have no logins allowed in /etc/passwd:

transmission:x:1028:100:transmission service account:/var/services/homes/transmission:/sbin/nologin

Fix it by changing the last part to:

transmission:x:1028:100:transmission service account:/var/services/homes/transmission:/bin/sh

**Comment by samuelbenhamou** [comment]
issue is down to the fact that su does not seem to work as expected (though from what I gathered it is expected from synology verions). 
Changing the starting block to use "sudo" did the trick for me 
(file: /var/packages/transmission/scripts/start-stop-status)
start_daemon ()
So from : 
`    su - ${USER} "PATH=${PATH} ${TRANSMISSION} -g ${INSTALL_DIR}/var/ -x ${PID_FILE}"
`
to 

`
    sudo -u ${USER} /bin/sh -c "PATH=${PATH} ${TRANSMISSION} -g ${INSTALL_DIR}/var/ -x ${PID_FILE}"
`

**Comment by GuillaumeDelarue** [comment]
Usingf sudo as above did the trick for me too. Many thanks!

**Comment by vschoener** [comment]
@samuelbenhamou I tried to change the command, but it still not working. Do I have to create a transmission user?

**Comment by samuelbenhamou** [comment]
I don't recall having to create a user and would guess the install package from the repo takes care of it but as a matter of fact, i do have a transmission user on my system

**Comment by vschoener** [comment]
Alright, thanks :) Even with the use, its not working and the log doesn't help me that much to understand the real problem :/

**Comment by ymartin59** [comment]
Please test DSM 6 package from https://github.com/SynoCommunity/spksrc/issues/3138

**Comment by KeizerSauze** [comment]
Hi,

So, it’s working ?


Bye
