### ISSUE TITLE
[Subliminal] on Synology DSM 6 + (v 0.7.5-12)  : User Interface won't work (ui bug?)

### ISSUE THREAD

**Issue by LoneWanderer-GH** [SynoCommunity/spksrc#2357]
### Setup

_Package Name:_ Subliminal
_Package Version:_ 0.7.5-12

_NAS Model:_ Synology DS415+
_NAS Architecture:_ INTEL Atom C2538
_DSM version:_ DSM 6.0-7321 Update 7
### Expected behavior

Access to the Paramters UI of Subliminal application
### Actual behavior

Apps Launches, UI is loaded.
pictures here: http://hpics.li/c393ee6 ; http://hpics.li/45d7c3d
2 menus on the left : 
- "Parameters"
- "Folders"

**"Folders" :**
- cannot add a folder : file chooser popup does not allow to enter a path string
- cannot add a folder : file chooser popup navigation frame is buggy : i can only see my NAS name, and no tree/folders
  
  **"Parameters" :**
- the part of the frame containing the parameters UI is unavailable, a popup shows the "Loading" text/icon of DSM. does never end unless app is killed or NAS stopped.

**"Quit UI" :** 
- unable to quit using the "X" close button.
- Have stop the package in package menu
### Steps to reproduce

_0._ Use "Chrome" Version 50.0.2661.102 m
_1._ Install Subliminal 0.7.5-12 on DSM 6.0-7321 Update 7
_2._ Launch app
_3._ After app failing to launch, create the user subliminal and grant access to the "video" and "downloads" shared folders, alllocate user in groups sc-medias, sc-downloads and administrations (!!!)
_4._  Launch app in package manager, app fails to launch.
_5._  Uninstall app
_6._  Install App in package manager,
_7._  Launch app in package manager. It starts. 
_8._ Click on the package in package menu (windows-like start menu)
_9._ A Subliminal UI appears but can't be used. Refer now the "Actual behavior" section written above :)
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_
SCheduler.log 

```
06/02/2016 21:19:28:INFO:root:Starting
06/02/2016 21:27:03:INFO:root:Stopping
06/02/2016 21:27:39:INFO:root:Starting
```
#### Other logs

_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
`/var/log/synopkg.log`

```
2016/06/02 21:19:07     start subliminal: begin to start version 0.7.5-12
2016/06/02 21:19:29     start subliminal: start version 0.7.5-12 successfully, result 0
2016/06/02 21:27:02     stop subliminal: begin to stop version 0.7.5-12
2016/06/02 21:27:05     stop subliminal: stop version 0.7.5-12 successfully, result 0
2016/06/02 21:27:25     start subliminal: begin to start version 0.7.5-12
2016/06/02 21:27:39     start subliminal: start version 0.7.5-12 successfully, result 0
```

vi rejects to open /var/log/messages as an admin user (admin group, not root)

PS: logs obtains via telnet + vi

**Comment by dkrux** [comment]
same problem :(
My config file /volume1/@appstore/subliminal/var/config.ini looks like this:
`providers = addic7ed, opensubtitles, podnapisi' 'thesubdb, tvsubtitles`
it looks weird to me ... how is this line supposed to be?

This morning I updated my system to DSM 6.0.1-7393 and now it's impossible to launch the app.
I tried this command :
`sudo /var/packages/subliminal/scripts/start-stop-status start
Starting Subliminal ...
su: Permission denied`
It's probably related to this https://github.com/SynoCommunity/spksrc/issues/2099#issuecomment-208935150

**Comment by meffect** [comment]
Same issue

**Comment by fn002449** [comment]
Same problem as topic starter here.. is there a way to fix it?
I'm using DSM 6.0.1-7393 Update 1 (DS214play)

I saw that on github there is a 2.0.3 release. Is there no package for this version?

**Comment by dkrux** [comment]
I temporary fixed it by setting a manual cron : 
/usr/local/subliminal/env/bin/subliminal -l EN -c /volume1/@appstore/subliminal/cache /volume1/video/

**Comment by JeromeChaville** [comment]
Hello Telomere31,
I have the exact same problem on my Syno since last year.
Did some tried and found any solution ? I do not understand the solution proposed by dkrux. 
Somebody tried it ?
Any other alternate tool that can perform the same magic than Subliminal ?
Thanks upfront for your help!

**Comment by Jean-Christophe-P** [comment]
Hi,

Same problem here. No solution so far.
Just posting to be updated :-)

Thanks for your work

**Comment by cray19003** [comment]
Hi,
Same here.
Waiting for an update too :)

**Comment by Tristouille** [comment]
Same here, launching after a reboot but GUI si frozen.

**Comment by didierkrux** [comment]
**Here is my solution:**

**I stopped subliminal package but still kept it installed.**

<img width="999" alt="capture d ecran 2016-10-26 a 20 55 04" src="https://cloud.githubusercontent.com/assets/9531862/19740350/b33c92f4-9bbe-11e6-935a-5db7860f51ee.png">

**Then created this task in the task scheduler. Its executed every hour.**

<img width="582" alt="capture d ecran 2016-10-26 a 21 00 03" src="https://cloud.githubusercontent.com/assets/9531862/19740553/597b5ff6-9bbf-11e6-8ac6-0987763ebe32.png">
<img width="785" alt="capture d ecran 2016-10-26 a 20 58 03" src="https://cloud.githubusercontent.com/assets/9531862/19741095/b3316400-9bbf-11e6-80d5-75b353db8f2e.png">

**command: `/usr/local/subliminal/env/bin/subliminal -l EN -c /volume1/@appstore/subliminal/cache /volume1/download/`**

`EN` is for english language
`/volume1/download/` is my video folder

**Comment by Tristouille** [comment]
it does not run. what user are you using for this task ? and what is the /volume1/@appstore/subliminal/cache  path for ?

**Comment by didierkrux** [comment]
I used `admin` user.
`/volume1/@appstore/subliminal/cache` is subliminal cache folder, you don't need to change this one. Just replace `/volume1/download/` by your video folder you want to scan.

**Comment by Tristouille** [comment]
Thanks for the workaround didierkrux, It seems to work, though it doesn't seem to find as much subtitles as before. I added options -a 12w to look for older episodes, but I'm not sure about the depth parameter. Ideas ?

**Comment by balmhood** [comment]
Hi all, 
I do have the exact same issue with Subliminal on a `DS416Play` wtith ` DSM 6.0.2-8451 update 2`

do we know what's the problem?

**Comment by stoupa-cz** [comment]
Hi all,

I just tried it on the latest "DSM 6.0.2-8451 Update 4" on old DS211j and the problem remains. I didn't try the workaround though.

**Comment by andreicel** [comment]
Look this
[https://www.youtube.com/watch?v=9wLctApqoBY&t=29s](url)

**Comment by byothe** [comment]
Hi there,
Do we know if there is still someone maintaining this package ?

**Comment by cytec** [comment]
if i remember correctly @Diaoul is the original creator/maintainer...

**Comment by byothe** [comment]
I Hope he'll work soon on Subliminal

**Comment by royduin** [comment]
Any updates on this? @Diaoul?

**Comment by cytec** [comment]
afaik he is a little bit busy with IRL Stuff lately, so be patient ;)

**Comment by jackhammerjoe** [comment]
any updates in this case or alternatives for easy-to-use automatic subtitle downloader?

**Comment by jackhammerjoe** [comment]
This thing is dead, hm?!

**Comment by jackhammerjoe** [comment]
RIP subliminal for Synology

**Comment by abescalamis** [comment]
I will suggest you to use the Docker version of subliminal, I use it on my synology ds916+, it was really easy to install and then I just set it to run as task.

**Comment by dimitrov-adrian** [comment]
+1

**Comment by hgy59** [comment]
We are dropping support for Python 2 dependent packages
