### ISSUE TITLE
[Package Request] stunnel 

### ISSUE THREAD

**Issue by sirjaymz** [SynoCommunity/spksrc#2358]
Description: stunnel
Website: https://www.stunnel.org/index.html
Documentation: https://www.stunnel.org/docs.html
Build/Installation documentation: hmmm
Source Code: https://www.stunnel.org/downloads/stunnel-5.32.tar.gz - ftp://ftp.stunnel.org/stunnel/
License:  Stunnel is a free software authored by Michał Trojnara. Although distributed under GNU GPL version 2 or later with OpenSSL exception, stunnel is not a community project. We retain the copyright of the source code. Please contact us for commercial support or non-GPL licenses. Free, community-based support is also available via stunnel-users mailing list.

**Comment by sirjaymz** [comment]
https://www.bountysource.com/issues/34820100-package-request-stunnel

**Comment by StoneISStephan** [comment]
Did you know that you can install stunnel with bootstrapper?
ipkg (optware) contains stunnel4
opkg (entware) contains stunnel5

**Comment by cytec** [comment]
@Dr-Bean so im currently working on this as i had some need for myself... seems like there isn't any sort of Icon or something available ... what should i do? can't think of any other app where we don't have an icon at all...

**Comment by Dr-Bean** [comment]
@cytec Just a quick response due to holidays: Similar to ncdu package, maybe use the screenshot from https://www.stunnel.org/screenshot.html? Could even put a watermark with text `stunnel` over it ;)

**Comment by hgy59** [comment]
@sirjaymz are you still waiting for this package? 
You can download all packages created by the github build action [here](https://github.com/SynoCommunity/spksrc/actions/runs/351496045) (click the packages link) for manual installation.
These are all generic archs. You find the matching generic arch for your specific Diskstation Model  in the wiki page [Package Archs](https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures).

Please report any feedback in  #4261.
