### ISSUE TITLE
Adding repo - invalid location

### ISSUE THREAD

**Issue by malwinMP** [SynoCommunity/spksrc#2360]
### Setup

_NAS Model : DS215j
_NAS Architecture: synology_armada375_215j
_DSM version: DSM 6.0-7321 Update 6

Followed the guide in easy install section and keep getting "invalid location" error while adding repo. Is repo working or it's down?

**Comment by Dr-Bean** [comment]
Nothing wrong that I'm aware of. Could have been a network hiccup. Otherwise, here's some steps for you to start troubleshooting:
- Are you connected via a VPN? Use a direct/local connection instead.
- What is the IP address is resolved by `packages.synocommunity.com`? 
    - Log in to your NAS via SSH;
    - Run `nslookup packages.synocommunity.com`.
- What is the DNS server configured on your NAS? A possible workaround is to set set one or two public DNS servers in your Synology:
    - Open Control Panel>Network;
    - On the General tab, activate the checkbox called Manually configure DNS server;
    - Add in one or two of the DNS servers you want to use. (Suggestions: Google (8.8.8.8/8.8.4.4), OpenDNS (208.67.222.222, 208.67.220.220)l
    - Click Apply.

**Comment by malwinMP** [comment]
> $ nslookup packages.synocommunity.com
Server:         4.4.4.4
Address:        4.4.4.4#53
Non-authoritative answer:
packages.synocommunity.com      canonical name = synocommunity.com.
Name:   synocommunity.com
Address: 104.31.95.179
Name:   synocommunity.com
Address: 104.31.94.179

No VPN, I've checked DNS provided from my local ISP as well as google DNS. ATM im using google DNS.

**Comment by esbiete** [comment]
Same here. When trying to add Synocommunity as a Package Sources, after clicking Ok to check, it responds with an "Operation Failed." Trusted publishers is activated. DNS's are Ok.

**Comment by malwinMP** [comment]
I've configured VPN and successfully added the Repo

**Comment by esbiete** [comment]
I'm not using any VPN, and have the same problem. Curious...
`Server:         10.0.0.100
Address:        10.0.0.100#53

Non-authoritative answer:
packages.synocommunity.com      canonical name = synocommunity.com.
Name:   synocommunity.com
Address: 104.31.95.179
Name:   synocommunity.com
Address: 104.31.94.179
`

**Comment by esbiete** [comment]
It seems is happening with any repository that I want to add. I think there's something screwed up with Package Center, some lock because running services are said to be stopped and I cannot install any new package. Do you know where can be manually added?
