### ISSUE TITLE
sonarr data settings

### ISSUE THREAD

**Issue by M0UL** [SynoCommunity/spksrc#2361]
allow to set the config folder for sonarr with the -data switch.

**Comment by Dr-Bean** [comment]
Can you explain why? What's wrong with the default location?

**Comment by cytec** [comment]
IMHO that's nothing we should do. In fact every package manager (like apt-get etc) what Synocommunity basically is, provides it's own predefined path. you'll able to change the `start-stop-status` script yourself but making that an install option would imho most likely result in requests to change that for every Package we provide...

**Comment by Dr-Bean** [comment]
For the record, @cytec, I agree completely :) 
I left it open to see if there was another reason to be able to set the datadir that wasn't immediately obvious. But, without any indication of that, this will be closed. 

@M0UL For future reference, please provide sufficiently detailed information when you open an issue/request. In a lot of cases, the `why` is even more important than the `what`, and this is a good example.
