### ISSUE TITLE
New DSM update - Transmission now (almost) working.....

### ISSUE THREAD

**Issue by nozebleed** [SynoCommunity/spksrc#2363]
_For new Package Requests, see the guidelines_  
### Setup

_Package Name:_ Transmission
_Package Version:_ 2.92-12

_NAS Model:_ DS216j
_NAS Architecture:_
_DSM version:_ DSM 6.0.1-7393

Received a new DSM6 update a couple days ago, Transmission is now launching but when I upload a file and start the service, it downloads about 5mb then fails "permission denied...." I'm sorry I am not on the network right now so I cant say what it is verbatim. 

Sorry I am a noob to synocommunity - is it just an issue with giving proper permissions or setting it up as a user? Before this update, I couldnt get it to launch at all.

**Comment by Safihre** [comment]
Test packages for DSM6.1 and various architectures are available here #3138. They also include a new way of handling permissions.
We hope to publish the packages to the official repo soon and appreciate all testing and reports on the functioning of these packages.
