### ISSUE TITLE
http://ftp.debian.org not working?

### ISSUE THREAD

**Issue by charmisuk** [SynoCommunity/spksrc#2367]
_For new Package Requests, see the guidelines_  
### Setup

_Package Name:_
_Package Version:_

_NAS Model:_DS715
_NAS Architecture:_
_DSM version:_DSM 6.0.1-7393

Hello, I just started using Synology DS715 yesterday and downloaded Debian Chroot with Python through Synocommunity. I tried to do simple apt-get upgrade and update, but its not working. Please check the log below. The http://ftp.us.debian.org site seems to be working fine, but why is this not working? Any insight would be appreciated.

root@bitcoinuser:/# apt-get update
Err http://ftp.us.debian.org stable InRelease                                                                        

Err http://ftp.debian.org wheezy-updates InRelease                                                                   

Err http://security.debian.org jessie InRelease                                                                      

Err http://security.debian.org jessie/updates InRelease                 

Err http://ftp.fr.debian.org jessie InRelease                           

Err http://ftp.fr.debian.org jessie-updates InRelease                   

Err http://ftp.us.debian.org stable Release.gpg  
  Could not resolve 'ftp.us.debian.org'
Err http://ftp.debian.org wheezy-updates Release.gpg
  Could not resolve 'ftp.debian.org'
Err http://security.debian.org jessie Release.gpg
  Could not resolve 'security.debian.org'
Err http://ftp.fr.debian.org jessie Release.gpg
  Could not resolve 'ftp.fr.debian.org'
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://ftp.fr.debian.org jessie-updates Release.gpg
  Could not resolve 'ftp.fr.debian.org'
Reading package lists... Done
W: Failed to fetch http://ftp.us.debian.org/debian/dists/stable/InRelease  

W: Failed to fetch http://ftp.debian.org/debian/dists/wheezy-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/InRelease  

W: Failed to fetch http://ftp.fr.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://ftp.fr.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://ftp.us.debian.org/debian/dists/stable/Release.gpg  Could not resolve 'ftp.us.debian.org'

W: Failed to fetch http://ftp.debian.org/debian/dists/wheezy-updates/Release.gpg  Could not resolve 'ftp.debian.org'

W: Failed to fetch http://security.debian.org/dists/jessie/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://ftp.fr.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'ftp.fr.debian.org'

W: Failed to fetch http://ftp.fr.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'ftp.fr.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
root@bitcoinuser:/# apt-get upgrade
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  apt apt-utils base-files cron libapt-inst1.5 libapt-pkg4.12 libc-bin libdns-export100 libgnutls-deb0-28
  libgnutls-openssl27 libicu52 libirs-export91 libisc-export95 libisccfg-export90 libssl1.0.0 libsystemd0 libudev1
  multiarch-support rsyslog systemd systemd-sysv tzdata udev
23 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 16.7 MB of archives.
After this operation, 742 kB disk space will be freed.
Do you want to continue? [Y/n] Y
Err http://ftp.us.debian.org/debian/ stable/main base-files armhf 8+deb8u2
  Could not resolve 'ftp.us.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main base-files armhf 8+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libapt-pkg4.12 armhf 1.0.9.8.1
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main apt armhf 1.0.9.8.1
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libc-bin armhf 2.19-18+deb8u1
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libudev1 armhf 215-17+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main udev armhf 215-17+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libsystemd0 armhf 215-17+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main systemd armhf 215-17+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main systemd-sysv armhf 215-17+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main cron armhf 3.0pl1-127+deb8u1
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libapt-inst1.5 armhf 1.0.9.8.1
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libssl1.0.0 armhf 1.0.1k-3+deb8u1
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libgnutls-openssl27 armhf 3.3.8-6+deb8u3
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libgnutls-deb0-28 armhf 3.3.8-6+deb8u3
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libisc-export95 armhf 1:9.9.5.dfsg-9+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libdns-export100 armhf 1:9.9.5.dfsg-9+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libicu52 armhf 52.1-8+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libisccfg-export90 armhf 1:9.9.5.dfsg-9+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main libirs-export91 armhf 1:9.9.5.dfsg-9+deb8u2
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main multiarch-support armhf 2.19-18+deb8u1
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main tzdata all 2015f-0+deb8u1
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main apt-utils armhf 1.0.9.8.1
  Could not resolve 'ftp.fr.debian.org'
Err http://ftp.fr.debian.org/debian/ jessie/main rsyslog armhf 8.4.2-1+deb8u1
  Could not resolve 'ftp.fr.debian.org'
E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/b/base-files/base-files_8+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/a/apt/libapt-pkg4.12_1.0.9.8.1_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/a/apt/apt_1.0.9.8.1_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/g/glibc/libc-bin_2.19-18+deb8u1_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/s/systemd/libudev1_215-17+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/s/systemd/udev_215-17+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/s/systemd/libsystemd0_215-17+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/s/systemd/systemd_215-17+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/s/systemd/systemd-sysv_215-17+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/c/cron/cron_3.0pl1-127+deb8u1_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/a/apt/libapt-inst1.5_1.0.9.8.1_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1k-3+deb8u1_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/g/gnutls28/libgnutls-openssl27_3.3.8-6+deb8u3_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/g/gnutls28/libgnutls-deb0-28_3.3.8-6+deb8u3_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/b/bind9/libisc-export95_9.9.5.dfsg-9+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/b/bind9/libdns-export100_9.9.5.dfsg-9+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/i/icu/libicu52_52.1-8+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/b/bind9/libisccfg-export90_9.9.5.dfsg-9+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/b/bind9/libirs-export91_9.9.5.dfsg-9+deb8u2_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/g/glibc/multiarch-support_2.19-18+deb8u1_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/t/tzdata/tzdata_2015f-0+deb8u1_all.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/a/apt/apt-utils_1.0.9.8.1_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Failed to fetch http://ftp.fr.debian.org/debian/pool/main/r/rsyslog/rsyslog_8.4.2-1+deb8u1_armhf.deb  Could not resolve 'ftp.fr.debian.org'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by charmisuk** [comment]
Okay, i think this is DNS problem. I pinged IP address and it worked, and pinging ftp.debian didn't. I changed /etc/resolv.conf file a bit, and its working about 80% of the downloads by using 8.8.8.8 instead of 75.75.75.75. Any thoughts on how the resolv.conf file should look?

**Comment by piwi82** [comment]
You should define your DNS configuration in `DSM > Control panel > Network`, not directly in `/etc/resolv.conf`.

**Comment by ksze** [comment]
@piwi82 The problem is that changing the DNS configuration in `DSM > Control Panel > Network` doesn't update the *chroot's* `/etc/resolv.conf`

It would be nice to have an elegant way to automatically update the chroot's /etc/resolv.conf. Presumably that involves some kind of hook onto DSM's own resolv.conf update.

**Comment by piwi82** [comment]
Yes, you have to modify the _chroot's_ `/etc/resolv.conf`, then try `# nslookup ftp.us.debian.org` or `# dig ftp.us.debian.org` to ensure name resolution is working.

**Comment by ruslyrossi47** [comment]
To solve this problem, just change the /etc/resolv.conf to public DNS or google DNS, so it will like this:

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Comment by errorlog88** [comment]
W: Failed to fetch http://security.debian.org/dists/lenny/updates/main/binary-i3                                                                                        86/Packages.gz  404  Not Found

W: Failed to fetch http://security.debian.org/dists/squeeze/updates/main/source/                                                                                        Sources.gz  404  Not Found

W: Failed to fetch http://security.debian.org/dists/squeeze/updates/main/binary-                                                                                        i386/Packages.gz  404  Not Found

W: Failed to fetch http://http.us.debian.org/debian/dists/squeeze/contrib/binary                                                                                        -i386/Packages.gz  404  Not Found [IP: 64.50.233.100 80]

W: Failed to fetch http://http.us.debian.org/debian/dists/squeeze/non-free/binar                                                                                        y-i386/Packages.gz  404  Not Found [IP: 64.50.233.100 80]

W: Failed to fetch http://http.us.debian.org/debian/dists/squeeze/main/binary-i3                                                                                        86/Packages.gz  404  Not Found [IP: 64.50.233.100 80]

W: Failed to fetch http://ftp.se.debian.org/debian/dists/squeeze/main/source/Sou                                                                                        rces.gz  404  Not Found [IP: 194.71.11.173 80]

W: Failed to fetch http://ftp.se.debian.org/debian/dists/squeeze/contrib/source/                                                                                        Sources.gz  404  Not Found [IP: 194.71.11.173 80]

W: Failed to fetch http://ftp.se.debian.org/debian/dists/squeeze/non-free/source                                                                                        /Sources.gz  404  Not Found [IP: 194.71.11.173 80]

W: Failed to fetch http://ftp.se.debian.org/debian/dists/squeeze/main/binary-i38                                                                                        6/Packages.gz  404  Not Found [IP: 194.71.11.173 80]

W: Failed to fetch http://ftp.se.debian.org/debian/dists/squeeze/contrib/binary-                                                                                        i386/Packages.gz  404  Not Found [IP: 194.71.11.173 80]

W: Failed to fetch http://ftp.se.debian.org/debian/dists/squeeze/non-free/binary                                                                                        -i386/Packages.gz  404  Not Found [IP: 194.71.11.173 80]

W: Failed to fetch http://mirrors.kernel.org/debian/dists/lenny/main/binary-i386                                                                                        /Packages.gz  404  Not Found [IP: 147.75.101.1 80]

W: Failed to fetch http://mirrors.kernel.org/debian/dists/lenny/contrib/binary-i                                                                                        386/Packages.gz  404  Not Found [IP: 147.75.101.1 80]

W: Failed to fetch http://volatile.debian.org/debian-volatile/dists/lenny/volati                                                                                        le/main/source/Sources.gz  Undetermined Error [IP: 149.20.4.15 80]

W: Failed to fetch http://volatile.debian.org/debian-volatile/dists/lenny/volati                                                                                        le/main/binary-i386/Packages.gz  Undetermined Error [IP: 149.20.4.15 80]

E: Some index files failed to download, they have been ignored, or old ones used                                                                                         instead.


Please help, whats wrong?

**Comment by avisvs** [comment]
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
