### ISSUE TITLE
p7zip - cross/p7zip refresh needed to v16.x when available

### ISSUE THREAD

**Issue by sirjaymz** [SynoCommunity/spksrc#2368]
### Setup
_Package Name: p7zip
_Package Version: 9.20.1

_NAS Model: DS1813+
_NAS Architecture: cedarview
_DSM version: 5.2-5967

http://www.7-zip.org/

Multiple 7-Zip Vulnerabilities
http://blog.talosintel.com/2016/05/multiple-7-zip-vulnerabilities.html

Concerns for other SPK's that rely on p7zip support could  open DSM device up to vulnerabilities that can be resolved with quick update. 

@Diaoul if you don't have time, I'll see if i can setup a PR.

**Comment by sirjaymz** [comment]
15.14.1 compiles, with a new patch file. 
This new compile however does not get the needed fix though.. 
tried using  "diff -Naur" between the 16.02 source of 7zip and the source of 15.14.1 to make additional patch files between those sources of the code referenced on https://sourceforge.net/p/p7zip/discussion/383043/thread/9d0fb86b/#6ecc without success. 
still working it.

**Comment by sirjaymz** [comment]
success.. setting up PR.

**Comment by Dr-Bean** [comment]
nzbget 16.4-22 	and nzbget-testing 16.0~r1439-11 are the two affected packages, both have been published on the repository.

Closing: If/when p7zip will be updated to 16.x, it'll quite likely contain the exact same patches.
