### ISSUE TITLE
rTorrent not running after upgrading ruTorrent from 3.6-6 to 3.7-8 on DSM 5.2 

### ISSUE THREAD

**Issue by damfino** [SynoCommunity/spksrc#2369]
_For new Package Requests, see the guidelines_  
### Setup

_Package Name:_ ruTorrent
_Package Version:_ 3.7-8

_NAS Model:_ DS214play
_NAS Architecture:_ INTEL Atom CE5335
_DSM version:_ DSM 5.2-5644 Update 5
### Expected behavior

Today I've upgraded the package from the 3.6-6 to 3.7-8.
Once the upgrade was done I've clicked on "Run" from the action menu on the package center window expecting to see the status change from "Stopped" to "Running".
### Actual behavior

Instead nothing happens. The "loading" animation runs for a couple of seconds and the status doesn't change. 
Checking /volume1/@appstore/rutorrent/var/rtorrent.pid it says that the process has PID 27777, but ps | grep rtorrent gives nothing. So the process is not running.
### Steps to reproduce

_1._ Upgrade the package from the Package Center
_2._ Click on Run from the action menu
_3._
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

```
Insert the package log here
```
#### Other logs

_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
[synopkg.log.zip](https://github.com/SynoCommunity/spksrc/files/305657/synopkg.log.zip)
Insert log here

```
```

**Comment by damfino** [comment]
Is it possible to downgrade this package to the previous version?

**Comment by GoodOmens83** [comment]
Can you access the web interface?

**Comment by damfino** [comment]
@GoodOmens83 

Thanks for your interest in my issue. 

> 1) Can you access the rutorrent web interface?

Yep, and the "log" tab says:
[13.06.2016 13:20:51] WebUI started.
[13.06.2016 13:20:51] No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.


> 2) Have you tried simply rebooting the NAS (this might the simplest fix)?

Yes, I did it many times, no luck.

> 3) Have you tried removing the PID file and trying to restart it from the web interface?

Just tried. Another pid files shows up but the daemon stops immediately.

> 4) try running:
var/packages/rutrorrent/scripts/start-stop-status stop
/var/packages/rutrorrent/scripts/start-stop-status start
and see if any errors are shown

Here's what I get:
DS214> /var/packages/rutorrent/scripts/start-stop-status stop 
ruTorrent is not running
DS214> /var/packages/rutorrent/scripts/start-stop-status start
Starting ruTorrent ...
Apparently no errors, and /var/log/synopkg.log says:
2016/06/13 13:27:52     start rutorrent: begin to start version 3.7-8
2016/06/13 13:27:52     start rutorrent: start version 3.7-8 successfully, resul
t 0
But still, no rtorrent daemon running.

> 5) What are the contents of your .rtorrent.rc file? (/usr/local/rutorrent/var/.rtorrent.rc)

scgi_port = localhost:8050
directory = /volume1/Torrent
session = /usr/local/rutorrent/var/.session
max_memory_usage = 183337984
log.open_file = "rtorrent.log", "/usr/local/rutorrent/var/rtorrent.log"
log.add_output = "warn", "rtorrent.log"
http_cacert = /usr/local/rutorrent/cert.pem
system.umask.set = 002
port_range = 42042-42045

BTW, the rtorrent.log does not exist anywhere.

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #2215 and maybe PR #3175.
