### ISSUE TITLE
ioQuake3 server request

### ISSUE THREAD

**Issue by paulbnjl** [SynoCommunity/spksrc#237]
Hello !
It will be awesome to run a quake3 server on synology machines! Because it's old, don't consume too much, AND everybody likes quake3 ! :)
Fortunately, there is an opensource implementation of the quake3 engine : ioquake3.
http://ioquake3.org/

Unfortunately, i can't manage ton compile it on my 212+ (the "make" systematically fail). The funny thing is that somebody on the internet seems to have set the things to work right : http://the.taoofmac.com/space/games/Quake%20III%20Arena/ioquake3
I've tried to contact him without success (mailer daemon error).

I've also tried to play a little a little with the ARM port for rapsberry pi, without success.
https://github.com/raspberrypi/quake3

Maybe somebody more smart than me can do something about this ! :)

Thanks a lot !
##

**Comment by digitalbox94** [comment]
IOQuake 3 server is working fine on NAS Synology. Let me know if you need additional details :)
