### ISSUE TITLE
Certificate *.synocommunity.com expired 

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2372]
As the title says ;) 
For the time being, we can work around it with a `--verify=no` [here](https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.spk.mk#L293).

The website uses a cert issued by CloudFlare, no problems there.

@Diaoul, could you take a look? Thanks.

**Comment by Diaoul** [comment]
Yes, as the website is using CloudFlare I thought it wouldn't be an issue but the API still needs it. Given that valid certs cost money and Let's Encrypt takes some time to setup please use your workaround for now.

**Comment by KaraokeStu** [comment]
Seems to have been resolved by cloudflare - certificate renewed on Jun 6th 2016

https://www.sslshopper.com/ssl-checker.html#hostname=packages.synocommunity.com

**Comment by Dr-Bean** [comment]
@KaraokeStu As I said, the website isn't affected :) It's the backend that uses an expired cert.

**Comment by KaraokeStu** [comment]
@Dr-Bean oops... ignore me ;)

**Comment by cytec** [comment]
@Diaoul have you checked startssl.com? you'll have to resign the cert every year but therefore it's free for non-commercial use ;)

**Comment by KaraokeStu** [comment]
@Diaoul also there is https://www.wosign.com/english/freeSSL.htm which I have used - gives you a 2 year certificate for free! :)
