### ISSUE TITLE
CouchPotato issue with DSM 6

### ISSUE THREAD

**Issue by Xoledas** [SynoCommunity/spksrc#2381]
Hi,

I'v bought last week a Sinology DS216play with a 4To HD.

I tried to install couch potato from synocommunity but it doesn't work.
It can't start through the package center.

I tried to follow some solution i found online like editing file and modify the user that in "start daemon" and i finally succeeded to start it. But then the url doesn't work and i can't access it...

Is there anything i can do ? or did i do something wrong ?
Maybe i have to wait for the community to upgrade it ?

I currently run DSM 6.0.1-7393
CP version : 20141013-6

**Comment by cytec** [comment]
see https://github.com/SynoCommunity/spksrc/issues/2104 or https://github.com/SynoCommunity/spksrc/issues/2207 basically wait for https://github.com/SynoCommunity/spksrc/issues/2216
