### ISSUE TITLE
 [Package Request] Please add some package to filter traffic.

### ISSUE THREAD

**Issue by xaozai** [SynoCommunity/spksrc#2382]
Please add some package to filter Internet traffic: cutting ads, xxx content, violence, drugs, etc. - something like a proxy that will analyze incoming traffic, including https. 
It might be privoxy (privoxy.org), DansGuardian (dansguardian.org), Mindwebfilter (code.google.com/archive/p/mindwebfilter/). However, I don't know if they filter https.
Maybe is there something better than this software?..

**Comment by piwi82** [comment]
Have you tried SquidGuard ?
https://synocommunity.com/package/squidguard

**Comment by xaozai** [comment]
Hmm. Somehow i missed this package in the package list. I'll try it... Thanks!

**Comment by loli71** [comment]
But careful SquidGuard package from synocommunity is totally out of age and not working ...

**Comment by xaozai** [comment]
Yes, filtering software, which is based on analyzing the content of pages is probably losing its relevance due to the spread of HTTPS... Probably be a more efficient use of filtering based on DNS.
