### ISSUE TITLE
"Page not found" when clicking on umurmur icon

### ISSUE THREAD

**Issue by rbieb** [SynoCommunity/spksrc#2384]
### Setup

_Package Name:_ umurmur
_Package Version:_ 0.2.16-6

_NAS Model:_ DS415+
_NAS Architecture:_ x86
_DSM version:_ DSM 6.0.1-7393
### Expected behavior

I click the icon and the umurmur interface pops up and lets me adjust the server settings
### Actual behavior

I get "Sorry, the page you are looking for is not found." The link that's being used is this one:

www.mysynology.com/3rdparty/umurmur/umurmur.cgi
### Steps to reproduce

_1._ Install umurmur
_2._ Click on icon
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

``````
Insert the package log here
``` There is no info at all about this, the access is not even registered
``````

**Comment by ispgeek** [comment]
I am also getting the same thing with a DS1515+    - This was reported in June when can we expect to get some assistance with it?

**Comment by KaraokeStu** [comment]
I'll have a look when I'm back in the office next week, however it could be a DSM 6 issue, and if that is the case, I'll be unable to reproduce the issue

**Comment by Bobo59** [comment]
I have this problem, 
I get "Sorry, the page you are looking for is not found." The link that's being used is this one"
Someone found solution ?
Thx

**Comment by ymartin59** [comment]
uMurmur has been published. Please report any trouble in new issue
