### ISSUE TITLE
Cannot add synocommunity in DSM Docker

### ISSUE THREAD

**Issue by guil0205** [SynoCommunity/spksrc#2387]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Add Synocommunity link in package center

_NAS Model:_ DockerDSM
_NAS Architecture:_ INTEL Atom C2538
_DSM version:_ DSM 6.0.1-7393 Update 1

### Expected behavior
I can not add Synocommunity in the Package Sources.
When I try, I have a message that say in french "the place isn't correct" 

### Steps to reproduce
_1._ Go to package center
_2._Settings
_3._ Add SynoCommunity in package source

#### Other logs
I find this log in Confstore/var/log/messages :
Jun 12 19:41:01 SynologyVM synoscgi_SYNO.Core.Package.Feed_1_add[5159]: pkgcurltool.cpp:443 http://packages.synocommunity.com, Failed to request packages, httpResponseCode=422

Tks :)

**Comment by piwi82** [comment]
DockerDSM is not (yet) supported by SynoCommunity.
