### ISSUE TITLE
DS916+ DSM 6.0.1-7393 1: SabNzbd and NzbGet will not start

### ISSUE THREAD

**Issue by MrtAlways** [SynoCommunity/spksrc#2388]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: http://packages.synocommunity.com/
_Package Version:_

_NAS Model: DS916+
_NAS Architecture: INTEL Pentium N3710
_DSM version: DSM 6.0.1-7393 Update 1

### Expected behavior
Sabnzbd and Nzbget should start

### Actual behavior
Packet service can not run

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by madvtak** [comment]
See this thread, its known. https://github.com/SynoCommunity/spksrc/issues/2207#issuecomment-227545431

@Dr-Bean please close this.

**Comment by MrtAlways** [comment]
Thanks
