### ISSUE TITLE
Fresh ruTorrent (3.7-8) install not working on DSM 6.

### ISSUE THREAD

**Issue by Gamatora** [SynoCommunity/spksrc#2392]
### Setup

_Package Name:_ ruTorrent
_Package Version:_ 3.7-8

_NAS Model:_ DS415+
_NAS Architecture:_ synology_avoton_415+
_DSM version:_ DSM 6.0.1-7393 Update 1
### Expected behavior

Was expecting ruTorrent to work.
### Actual behavior

Had the following logs in web interface:

`[26.06.2016 14:15:15] WebUI started.
[26.06.2016 14:15:16] Webserver user doesn't have read/write/execute access to the tmp directory. ruTorrent will not work. (/usr/local/rutorrent/tmp)
[26.06.2016 14:15:16] rTorrent user must have read/execute access to the tmp directory. ruTorrent will not work. (/usr/local/rutorrent/tmp)
[26.06.2016 14:15:16] rss: Some functionality will be unavailable. Webserver user can't access external program (curl).
[26.06.2016 14:15:16] rutracker_check: Plugin will not work. Webserver user must have execute access to the rtorrent session directory (/usr/local/rutorrent/var/.session/).`
### Steps to reproduce

_1._ Clean and fresh DSM 6 setup.
_2._ Install Web Station, install ruTorrent.
_3._ Go to http://nas-ip/rutorrent/
#### Package log

`cat /usr/local/rutorrent/var/rtorrent.log`: file is empty

**Comment by madvtak** [comment]
Duplicate issue, please close this.

https://github.com/SynoCommunity/spksrc/issues/2207

**Comment by fritz001** [comment]
I do have up and running  rutorrent 3.7-8  on DS214P ( DSM 6.0.1-7393 Update 1 )

With some minor issues, is running quite well...

**Comment by bamtan** [comment]
@fritz001 Is there any where I can contact you? I'd like to get ruTorrent working on my Synology (ds216j). cheers

**Comment by fritz001** [comment]
Hi Louis,

Can you give more details  just to have more info how to  help you.

**Comment by bamtan** [comment]
@fritz001 It simply does not run anymore -- just loads and then 'stopped'.

I had it give me an IP address (http://NAS-IP/rutorrent/) but even then it gave me an error 403 when visiting the site.

Apparently another user found a fix on #2215, but I'm unsure on how to apply what those fixes were. 

I've successfully set up Transmission, and had Deluge web-ui working, but I much prefer ruTorrent. 

Are you on IRC, or Discord? my Discord is bamtan#5968, I'd really appreciate some assistance in getting this working, thank you

**Comment by fritz001** [comment]
Hi Louis,

So:

1st:

-- connect to NAS as root ( 1st as admin and after sudo su - )

screen -c ${USER} -u ${USER} -p ${PID_FILE} -- -D -m ${RTORRENT}

1.a     if you get this error: "screen: error while loading shared
libraries: libelf.so.0: cannot open shared object file: No such file or
directory"

in order to make it work, downloaded

http://launchpadlibrarian.net/158018450/libelfg0_0.8.13-5_i386.deb

and extracted libelf.so.0 in /usr/local/rutorrent/lib

**Comment by bamtan** [comment]
@fritz001 I don't have the command `screen` nor IPKG to install it with. I'm on an armv71 Synology, is that maybe why? (DS216j)

**Comment by fritz001** [comment]
Well,

We'll try a different approach:

be logged as root

1.  goto  "/var/packages/rutorrent/scripts" and do

sh -x ./start-stop-status  start

and tell me if any errors

**Comment by bamtan** [comment]
@fritz001 this is what I got 
```
# sh -x ./start-stop-status start
+ PACKAGE=rutorrent
+ DNAME=ruTorrent
+ INSTALL_DIR=/usr/local/rutorrent
+ PATH=/usr/local/rutorrent/bin:/usr/local/rutorrent/usr/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/l                                          ocal/sbin:/usr/local/bin:/usr/local/git/bin
+ USER=rutorrent
+ RTORRENT=/usr/local/rutorrent/bin/rtorrent
+ PID_FILE=/usr/local/rutorrent/var/rtorrent.pid
+ LOG_FILE=/usr/local/rutorrent/var/rtorrent.log
+ case $1 in
+ daemon_status
+ start-stop-daemon -K -q -t -u rutorrent -p /usr/local/rutorrent/var/rtorrent.pid
+ echo Starting ruTorrent ...
Starting ruTorrent ...
+ start_daemon
+ export HOME=/usr/local/rutorrent/var
+ HOME=/usr/local/rutorrent/var
+ start-stop-daemon -S -q -m -b -N 10 -x screen -c rutorrent -u rutorrent -p /usr/local/rutorrent/var/rtorrent.pid -- -D -m /u                                          sr/local/rutorrent/bin/rtorrent
```

I don't have `screen`, so maybe that's a problem.

**Comment by Safihre** [comment]
I worked on new DSM5/6 compatibility but got stuck, I did the basic work but need some help to figure out the right paths to config files etc. If you want, you can help me here: #3175.

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #2215 and maybe PR #3175.
