### ISSUE TITLE
[Package Request] youtube-dl

### ISSUE THREAD

**Issue by xaozai** [SynoCommunity/spksrc#2394]
Is it possible to add the package "youtube-dl"?
https://rg3.github.io/youtube-dl/

youtube-dl is a command-line program to download videos from YouTube.com and a few more sites.
Here's is the list of all the supported sites, ordered alphabetically: https://rg3.github.io/youtube-dl/supportedsites.html

**Comment by cytec** [comment]
easy solution: install the Python SPK from SynoCommunity and install `youtube-dl` with pip: `/usr/local/python/bin/pip install youtube-dl` which then should be accessible through `/usr/local/python/bin/youtube-dl`

**Comment by Diaoul** [comment]
Be sure to repeat this each time you update the Python SPK though :)
Or isolate it in a virtualenv.

**Comment by xaozai** [comment]
How do I isolate it in a virtual environment?..

**Comment by cytec** [comment]
`/usr/local/python/bin/virtualenv env` in any directory will create an `env` folder inside that folder using SynoCommunity's python version and will even work after SPK updates... you'll have to use the environment for installing then: `./env/bin/pip install youtube-dl` and youtube-dl will be installed in `./env/bin` too for more detailed info: https://virtualenv.pypa.io/en/stable/userguide/

**Comment by xaozai** [comment]
Ok. Thank you!
