### ISSUE TITLE
[Package Request] btsync

### ISSUE THREAD

**Issue by denser** [SynoCommunity/spksrc#2395]
_Name_:bittorrentsync
_Description_:Sync skips the cloud and finds the shortest path between devices when transferring data. No Cloud. No uploading to third party servers. Just fast, simple file syncing.
_Website_:https://getsync.com/platforms/other-devices/
_Software documentation_:https://help.getsync.com/hc/en-us/articles/206215185
_Build/Installation documentation_:https://help.getsync.com/hc/en-us/articles/206215185
_Source Code_:-
_License_:https://help.getsync.com/hc/en-us/articles/206215185

Package exist on official site and somewhy SynoCommunity pointed as publisher. I cant find Btsync in [repo](https://synocommunity.com/packages)

So, why dont add this great package to repo?

**Comment by cytec** [comment]
BTSync was published on the repo a while ago but the developers decided to puplish the package directly to synology and thus it was removed from here. No need for us to try and keep it up to date if the dev's do it for each release :)

EDIT: Seems like they now publish SPK's on their website to download and in those SPK's SynoCommunity is set as Distributor/Maintainer for some reason \cc @Dr-Bean @Diaoul

**Comment by piwi82** [comment]
BitTorrent Sync is now managed by another company, [Resilio](https://blog.resilio.com/?p=783).
For installation, follow the instructions described here : https://help.getsync.com/hc/en-us/articles/206215185

**Comment by denser** [comment]
Thx for answers. All clear now.

**Comment by Dr-Bean** [comment]
> Seems like they now publish SPK's on their website to download and in those SPK's SynoCommunity is set as Distributor/Maintainer for some reason \cc @Dr-Bean @Diaoul

I actually sent out an email to the Resilio team yesterday, and just came across this issue by pure coincidence. It'll be fixed for future packages.
