### ISSUE TITLE
Need help with Ejabberd

### ISSUE THREAD

**Issue by FragZServer** [SynoCommunity/spksrc#2396]
### Setup

Ejabberd v 2.1.13-1

_NAS Model:_DS416
_DSM version:_DSM 6.0.1-7393 Update 1

I tried installing Ejabberd. It launches, but I need some more infos on how to set it up I guess? I tried connecting to the server using Pidgin and it did not work.

Any assistance is appreciated and may be rewarded with a donation to whoever can make this thing work for us!

**Comment by Safihre** [comment]
Closing due to age. It can be-reopend if someone wants to improve the package.
