### ISSUE TITLE
Transmission 2.9-12 - Failed To run the Package Service

### ISSUE THREAD

**Issue by vas-pipilas** [SynoCommunity/spksrc#2399]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Transmission
_Package Version: 2.9-12

_NAS Model: DS411j
_NAS Architecture:_
_DSM version: 6.0.1

### Expected behavior
Transmission package should be installed and run

### Actual behavior
Transmission is install but getting error "failed to run the package service" 

### Steps to reproduce
install package
Try to run
failed

### Comments

I have tried reinstalling and installing transmission several times but always getting the same error.
I have never created a user for transmission neither on DSM Gui nor in ssh
After the installation i checked the users on /etc and i see no transmission user created
I checked the dsm groups in the gui and the group sc-downloads has been created successfully
i checked the folder permissions and the required shared folder and subfolders have r/w accesses to the groups users/sc-download
i checked in ssh and the permissions are all 7 in the required folder
the var/logs report error pkgctl-transmission][0xD900 privilege.cpp:60 
i have tried also creating a new folder just for transmission ; same result

##### Logs #####

cat /var/log/messages

Jul  8 13:18:42 KiLLBiLL kernel: [244527.770000] init: pkgctl-transmission pre-start process (29347) terminated with status 1
Jul  8 13:18:42 KiLLBiLL synoscgi_SYNO.Core.Package.Control_1_start[29333]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-transmission][0xD900 privilege.cpp:60]
Jul  8 13:18:42 KiLLBiLL synoscgi_SYNO.Core.Package.Control_1_start[29333]: service_initjob_action.c:27 InitJobStart failed, [0xD900 privilege.cpp:60]
Jul  8 13:18:42 KiLLBiLL synoscgi_SYNO.Core.Package.Control_1_start[29333]: pkgstartstop.cpp:260 Failed to start pkgctl-transmission (err=-1) [0xD900 privilege.cpp:60]

root@KiLLBiLL:/usr/local/transmission/var# cat /etc/group
#$_@GID__INDEX@_$65536$
administrators:x:101:admin
AudioStation:x:254178:
avahi:x:84:
bind:x:53:
CloudStation:x:237243:
daemon:x:2:daemon,root
dbus:x:81:
dovecot:x:143:dovecot
DownloadStation:x:125560:
ftp:x:21:ftp
http:x:1023:
HyperBackup:x:256822:
ldap:x:439:
log:x:19:root
lp:x:7:lp
maildrop:x:126:
MediaServer:x:118831:
mysql:x:66:
nobody:x:99:
ntp:x:87:
PhotoStation:x:138862:
postfix:x:125:postfix
postgres:x:55:
root:x:0:
rpc:x:32:
sc-download:x:65536:transmission
smmsp:x:25:admin,smmsp
StorageAnalyzer:x:276949:
system:x:1:system
users:x:100:
VideoStation:x:228233:
wheel:x:10:admin

Kernel Log ####

Jul  8 13:18:42 KiLLBiLL kernel: [244527.770000] init: pkgctl-transmission pre-start process (29347) terminated with status 1

Folder Rights

drwxrwxrwx 7 admin users 24576 Jul  8 11:22 Torrents
drwxrwxrwx 10 root            users                4096 Jan 18 13:12 downloads

Can you please assist me? 

whatever details needed i will be glad to provide

Regards,

**Comment by AndrewNeo** [comment]
I'm having this exact same problem on a DS413.

If I try to write the `start-stop-status` script as root I just get `su: Permission denied`. Brand new never touched anything install of Transmission.

```
admin@Box:/var/packages/transmission/scripts$ sudo ./start-stop-status start
Starting Transmission ...
su: Permission denied
```

**Comment by GldRush98** [comment]
Try starting it from the shell with this:

su transmission -c "PATH=/usr/local/transmission/bin:/usr/local/python/bin:${PATH} /usr/local/transmission/bin/transmission-daemon -g /usr/local/transmission/var/ -x /usr/local/transmission/var/transmission.pid"

**Comment by christiansam** [comment]
according to the lastest pull request "https://github.com/SynoCommunity/spksrc/pull/2230/files", the following works for me with DSM 6.01

admin@host:~$ sudo -u transmission PATH=/usr/local/transmission/bin:/usr/local/python/bin:${PATH} /usr/local/transmission/bin/transmission-daemon -g /usr/local/transmission/var/ -x /usr/local/transmission/var/transmission.pid

does anyone know when this package gets updated and becomes available?

cheers
christian

**Comment by abraxxa** [comment]
The fix for me was to create the /etc/shadow entry (the username I'm using is 'transmission'):
`transmission:*:16936:0:99999:7:::`

**Comment by christiansam** [comment]
one strange thing i have noticed on my DSM 6.01 system: some mechanism seems to have removed the "transmission" user, which was created by the transmission package when being installed.
might this be a side effect from not running a package a long time, or rather has anyone noticed this too?

**Comment by fjsonin** [comment]
Hi, I have the same problem with my DS115J, I reinstalled the nas from scratch and I am not able to start transmission after the installation with the same messages as you have.

**Comment by abraxxa** [comment]
Just add the line I've posted and it will start.

**Comment by vas-pipilas** [comment]
Sorry for the late update on this; as other people stated after installation it just failed to start the transimission; my problem was fixed after i restarted the NAS ; for some reason after the restart the process started normally.

**Comment by haellingsen** [comment]
@vas-pipilas same thing solved it for my DS 115j as well. A simple restart.

**Comment by KaraokeStu** [comment]
Great stuff, thanks for letting us know

**Comment by teddue** [comment]
I have the same issue on a DS216j, running DSM 6.0.2-8451 Update 7

Logs and GUI show the same behaviour and output as OP's.

**Comment by fulvio-m** [comment]
@abraxxa suggestion worked for me aswell, running DS216J with DSM 6.1.4-15217, transmission version is 2.92-12
