### ISSUE TITLE
Clean target for SPKs

### ISSUE THREAD

**Issue by Diaoul** [SynoCommunity/spksrc#24]
I don't know what the current behavior of PLIST for SPK is but I wish I did not have to "install" some stuff like here :
https://github.com/SynoCommunity/spksrc/blob/master/spk/umurmur/Makefile#L29

Would that be possible to have a file with this kind of structure for installing stuff in `src/` ?

    dir:var/
    file:src/cert.fields:var/cert.fields
    bin:src/umurmur.cgi.pl:share/synoman/umurmur.cgi
    

First part also defines the mode of the created file

**Comment by Dr-Bean** [comment]
This is mostly covered by using `BUILD_DEPENDS` instead of `DEPENDS`.
