### ISSUE TITLE
Problems with Jackett

### ISSUE THREAD

**Issue by Stanzilla** [SynoCommunity/spksrc#2402]
_For new Package Requests, see the guidelines_  
### Setup

_Package Name:_ Jackett
_Package Version:_ 0.7.33-1

_NAS Model:_ DS212
_NAS Architecture:_
_DSM version:_ 6.0.1-7393 Update 1
### Expected behavior

Should work as before the auto update
### Actual behavior

After Jackett auto updates, the service stops responding to DSM commands, as in it shows as stopped, is actually running though, can't be stopped via DSM gui etc
### Steps to reproduce

_1._ Install
_2._ Let it auto update
_3._
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

```
Insert the package log here
```
#### Other logs

_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

```
Insert log here
```

Posted logs over here since I assumed it might be an issue with Jackett itself, might just be both though https://github.com/Jackett/Jackett/issues/397

**Comment by KaraokeStu** [comment]
Just wanted to add the same is happening here on DSM 5.2

**Comment by Dr-Bean** [comment]
Jackett 0.7.713-2 has been published on the repository. It might..or might not...;) solve these issues.

For future reference, Jackett keeps a log in `/usr/local/jackett/var/.config/Jackett/log.txt` and keeps a separate update log at `/usr/local/jackett/var/.config/Jackett/updater.txt`. Those should be added to your issue in case it still occurs/pops up again.
