### ISSUE TITLE
(Another) Unable to start headphones issue

### ISSUE THREAD

**Issue by xxkap0wxx** [SynoCommunity/spksrc#2412]
_For new Package Requests, see the guidelines_  
### Setup

_Package Name:_ Headphones
_Package Version:_ 20151012-7

_NAS Model:_ DS716+
_NAS Architecture:_ Intel Celeron
_DSM version:_ 6.0.1-7393 Update 1
### Expected behavior

I've never been able to get Headphones to start and I very much want to!  Other packages (Sonarr, SABnzbd, etc) - no problem.  I've tried it every which way, and here's the deal:
- Uninstall everything from previous attempt
- Search for anything related to headphones and remove it
- Set timezone to +0 (or not - same results regardless)
- Install Headphones package from synocommunity (package installs but stops instantly - no log produced)
- Change user in start-stop-status script to Root (so I don't get su errors)
- run ./start-stop-status start
- Expect things to start but...
### Actual behavior
- Headphones throws timezone error ending in:

`File "/usr/local/headphones/share/Headphones/lib/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'Timezone/Pacific'
`
#### Package log

None created

```
```

**Comment by rp4k** [comment]
Package Name: Headphones
Package Version: 20151012-7

NAS Model: DS716+
DSM 6.0.1-7393 Update 2
HD : 6TB   
RAM : 8GB 


after changing the startstopscript to root  and saving the changes.  i ran the package just fine. 

http://s31.postimg.org/iifsjn6nf/Capture.jpg
http://s31.postimg.org/jaigiuauj/Capture2.jpg

**Comment by xxkap0wxx** [comment]
@rp4k - thanks for checking.  Your first screenshot is from Mylar - was something else supposed to be there?  I wish there was a better way to get logs out about what's going on, because this somehow seems to work for most people, but not for me.  

Any idea if the SynoCommunity installation is supposed to be doing anything with users or groups?  I know changing things to root in start-stop-status should theoretically end-run around this, but I'm curious.  Any idea what's going on with that timezone bug in the first place?

**Comment by Safihre** [comment]
DSM6 compatible version of the package is expected to be released soon. It can already be installed by downloading it from here #3138.
After the official release on SynoCommunity, the package will auto-update from the official release.
