### ISSUE TITLE
Packages URL an 'invalid location' on DSM 6.0.1-7393 Update 1 and Update 2

### ISSUE THREAD

**Issue by philwolstenholme** [SynoCommunity/spksrc#2414]
### Setup
_NAS Model:_ DS212
_NAS Architecture:_ ARM (MARVELL 88F6282)
_DSM version:_ DSM 6.0.1-7393 Update 1 and Update 2

### Expected behavior
`http://packages.synocommunity.com` is accepted as a valid source of community packages

### Actual behavior
Trying to add `http://packages.synocommunity.com` (or variations with https or no protocol) gives an 'Invalid location' error message, and the packages repository cannot be added.

### Steps to reproduce
_1._ Try to add `http://packages.synocommunity.com` as a source of community packages on DSM 6.0.1-7393

I can ping `http://packages.synocommunity.com` just fine, but DSM doesn't seem to recognise it as a packages repository.

**Comment by SadUser** [comment]
Hi,
I've got the same Problem with the NVR216 (DSM 6.0.1-7393 Update 2).
My DS414 (DSM 6.0.1-7393 Update 2) works well.

Maybe it is an architecture-problem?
[https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model](url)

**Comment by philwolstenholme** [comment]
It worked fine for me until I removed the source and then tried to re-add it (all on the same device).

**Comment by SadUser** [comment]
The NVR216 is fresh installed, so it isn't possible to re-add it.
