### ISSUE TITLE
new version of sonarr

### ISSUE THREAD

**Issue by manuelramm** [SynoCommunity/spksrc#2417]
first of all, sorry for creating an issue for this, but I see no better way:
I installed sonarr from packages.synocommunity and this works fine, but this version is from 2015. How can I update or compile a new version of sonarr? (https://sonarr.tv/#download)
Can somebody help me please or provide me a newer compiled version for my synology ds214+?
Really thanks in advance!!

**Comment by vvhof** [comment]
Hey @manuelramm 
just start sonarr and navigate to system/updates. Sonarr has a build in update mechanism and it should have already updated itself!

**Comment by M0UL** [comment]
@manuelramm the build in updater is off by default, you need turn it on the settings.

**Comment by KaraokeStu** [comment]
Closed as @M0UL provided a valid fix. Not a bug
