### ISSUE TITLE
ruTorrent - Bad response from server: (500 [error,list])

### ISSUE THREAD

**Issue by pannbiff** [SynoCommunity/spksrc#2422]
### Setup

_Package Name:_ ruTorrent
_Package Version:_ 3.7-8

_NAS Model:_ DS215+
_NAS Architecture:_ ANNAPURNALABS Alpine AL212
_DSM version:_ DSM 6.0.1-7393 Update 2
### Expected behavior

Being able to access the Webui and have all torrents to show up.
### Actual behavior

No torrents show up and i can see "Bad response from server: (500 [error,list])" in the log.
### Steps to reproduce

_1._ Add lots of torrents
_2._ Access the Webui
_3._
### Comments

I have 4000+ torrents and that seems to be to much for the hardware to handle (only 1024 MB ram)? Is there anything i can do to make this work without having to remove torrents?

**Comment by GoodOmens83** [comment]
4000+ torrents - you are def hitting system limits.  You need more ram.

You might be able to edit the '.rtorrent.rc' file to give a little more ram to rtorrent (as I think it defaults to 25% of system memory).

That file is in /usr/local/rutorrent/var, can't remember if it's commented out by default or not.  You might be out of luck though as DS215+ does not have user upgradable ram

**Comment by pannbiff** [comment]
**Thanks!** :) 

I changed from 128M to 256M in the '.rtorrent.rc', but that caused all kinds of errors. Turns out that two other files also required editing.

- /etc/php/php.ini 
- /usr/local/etc/php56/php.ini 

(memory_limit = 256M)

Currently at 5000+ torrents and everything works just as it should do. :)

**Comment by Dr-Bean** [comment]
Closing then: we're already setting relatively [sane defaults](https://github.com/SynoCommunity/spksrc/blob/master/spk/rutorrent/src/installer.sh#L87) in the package, and we're not touching the system files :)

**Comment by elrengo81** [comment]
Hi I've the same behavior. I use ruTorrent V.3.9 on my router, Asus RT-AC3100, with Asuswrt-merlin firmaware. ruTorrent use lighthttpd as web-server. I have installed php7.

After try to create a torrent the rutorrent crash no show any torrent I show the following menssage: ] Bad response from server: (500 [error,getplugins]) Internal Server Error

**Comment by ymartin59** [comment]
Not the right place. Neither for ruTorrent, nor for Asus router... only for Synology NAS DSM here.
