### ISSUE TITLE
System hang when try to query Hyper Backup backup status and the remote backup NAS is down

### ISSUE THREAD

**Issue by Dusenberg** [SynoCommunity/spksrc#2424]
### Setup
_Package Name:_Hyper Backup 1.1.0-0215
_Package Version:_1.1.0-0215

_NAS Model:_DS216
_NAS Architecture:_synology_armada38x_ds216
_DSM version:_6.0-7312

### Actual behavior
I installed a new DS216 two days ago to replace elderly DS211J. Yesterday I configured a new multi-version backup regime with the DS211J relegated to the role of backup target on the local LAN. Both NAS have same software versions with Hyper Backup on both NAS and Hyper Vault on the DS211J. The backups are scheduled to run automatically early morning. As the role of the DS211J is now solely to hold backups, it powers up and down at the start and end of the backup window, for protection against network intrusion or malware, to extend the older DS211J's life, and to save electricity.  

Yesterday I manually ran all the backups to initialise first copies. Today I wanted to check the backup and version status after the first scheduled run, so logged into the DS216 via a browser on a laptop. The DS211J had powered down at this point. I opened Hyper Backup on the DS216, selected a backup task and then hit the 'versions' button, hoping to see two versions of the backup listed. For a couple of minutes there was a spinning wheel displayed and I realised the system was trying to contact the DS211J. Eventually the system displayed a 'No versions available' message which is highly misleading. I closed Hyper Backup and tried to open File Station but all that happened was an anonymous small spinning wheel icon appeared on the top task bar in the DSM desktop alongside another which I assumed must still be Hyper Backup exiting. I also noticed the cpu was showing 0% in the Resource Monitor widget at this time which was strange. So I tried to open Resource Monitor to see what processes were running and a third spinning wheel joined the other two. At this point the system hung and wouldn't respond to any clicks in the browser. I tried to get in via a terminal session using ssh from the laptop but that command just hung as well (I have previously used ssh terminal from the same laptop so know it works).  The only option I had was to press the power button on the front of the DS216 and reboot. The system came up into normal operation.

Several issues manifest:
a) Bug:  The Hyper Backup system appears not to be handling non-availability of remote NAS correctly and seems to enter an infinite loop that sucks in the rest of DSM and/or browser desktop

b) Bug: misleading 'No versions available' message in Hyper Backup when it finds remote target is not available, should read 'Remote server not available'

c) Functionality: the scenario indicates the source NAS, the DS216, may not have persistent knowledge of the backup versions that it produces on a remote server but relies on Hyper Vault on the remote server. This means the backup server has to be online anytime backup version status information is needed, which doesn't seem right and increases security risk. I appreciate if the remote server is down then physical backup data can't be viewed, but that isn't what is needed in the first instance to review what can be done in a potential data restore situation - the version list is.

#### Package log
None

#### Other logs
`/var/log/messages` 
```
Aug  4 08:59:42 DISKSTATION kernel: [ 3564.429432] ata2: wake up successful, the reset fail can be ignored
Aug  4 09:03:56 DISKSTATION synoscgi_SYNO.Backup.Version_2_list[8773]: [8773]network_tm.cpp:1279 Error: get target [DS216_Household] failed
Aug  4 09:07:26 DISKSTATION synopoweroff: system_sys_init.c:90 synopoweroff: System is going to poweroff
Aug  4 09:07:27 DISKSTATION [ 4029.825915] init: synonetd main process (1613) killed by TERM signal
Aug  4 09:07:27 DISKSTATION [ 4029.847579] init: synostoraged main process (4207) terminated with status 15
Aug  4 09:07:27 DISKSTATION [ 4029.857297] init: hotplugd main process (4814) killed by TERM signal
Aug  4 09:07:27 DISKSTATION [ 4029.882566] init: synocgid main process (5121) killed by TERM signal
Aug  4 09:07:27 DISKSTATION syno_poweroff_task: System is acting poweroff.
Aug  4 09:07:27 DISKSTATION [ 4030.028030] init: inetd main process (5333) killed by TERM signal
Aug  4 09:07:27 DISKSTATION kernel: [ 4030.496958] nfsd: last server has exited, flushing export cache
Aug  4 09:07:27 DISKSTATION dsmbackup: dsmbackup.cpp:158 cancel all failed, queue error = 503
Aug  4 09:07:31 DISKSTATION [ 4033.961604] init: Disconnected from D-Bus system bus
Aug  4 09:07:31 DISKSTATION synoiscsiep: iscsi_stop_all.cpp:110 Terminated all lunbackup processes.
Aug  4 09:07:34 DISKSTATION synoiscsiep: iscsi_stop_all.cpp:199 Successfully stopped iSCSI service.
Aug  4 09:07:37 DISKSTATION root: Check device busy: passed
Aug  4 09:07:38 DISKSTATION kernel: [ 4040.743980] md: md2: set sda5 to auto_remap [0]
Aug  4 09:07:38 DISKSTATION kernel: [ 4040.748547] md: md2: set sdb5 to auto_remap [0]
```

**Comment by piwi82** [comment]
SynoCommunity does not provide support for official packages. Please, ask Synology.
