### ISSUE TITLE
Nzbget password problem

### ISSUE THREAD

**Issue by Clifdon** [SynoCommunity/spksrc#2427]
_For new Package Requests, see the guidelines_  
### Setup

_Package Name: NZBGet
_Package Version: 16.4-22

_NAS Model: 1511+
_NAS Architecture: x86 (x86_64)
_DSM version: DSM 6.0.1-7393 Update 2
### Expected behavior

Password entered in installation wizard: m&movies#3
### Actual behavior

saved password(checked`/volume1/@appstore/nzbget/var/nzbget.conf`) : m@control_password@movies#3
### Steps to reproduce

After installation of nzbget on my Synology 1511+ noticed some weird problem with the password settings. 
I wanted to use the password: m&movies#3
But couldn't login so I checked `/volume1/@appstore/nzbget/var/nzbget.conf`and it said:

```
ControlUsername=nzbget

# Password which NZBGet server and remote client use.
#
# Set to empty value to disable authorization request.
ControlPassword=m@control_password@movies#3
```

I reinstalled with the same password and it occurred again. So I tried with the password: Doe, everything went well. 

It seems like the use of the & sign is forbidden and it replaces the '&' with '@control_password@' without any warning.

**Comment by ymartin59** [comment]
Updates have been published. Re-open if issue is still relevant.
