### ISSUE TITLE
SabNZB installation Python failed to download

### ISSUE THREAD

**Issue by eco1234** [SynoCommunity/spksrc#2430]
When I want to install the SabNZB package, I'm forcest to install the Python package, but everytine he's tellling me he failed to download the Python package. 

Other packages I can install fine?

**Comment by KaraokeStu** [comment]
Do you currently have any other package sources installed?

**Comment by Dr-Bean** [comment]
Closing. This should work fine: Package Center does its own dependency resolving at least on DSM5 and 6. If you're working with an older DSM version, then you can manually choose to install the SynoCommunity Python package before the Sab package.
