### ISSUE TITLE
Couchpotato will not start after install on DSM 6.0.1-7393 Update 2 

### ISSUE THREAD

**Issue by Northguy** [SynoCommunity/spksrc#2431]
On my DS212+ couchpotato will not start after a fresh install. Root cause: entry for couchpotatoserver user is missing in _/etc/shadow_

I created a manual entry `couchpotatoserver:*:10933:0:99999:7:::` at the end of _/etc/shadow_ .

`start_daemon ()
{
  su - ${USER} -c "PATH=${PATH} ${PYTHON} ${COUCHPOTATOSERVER} --daemon --pid_file ${PID_FILE} --config_file ${CFG_FILE}"
}
`
should be

`start_daemon ()
{
  sudo su - ${USER} -c "PATH=${PATH} ${PYTHON} ${COUCHPOTATOSERVER} --daemon --pid_file ${PID_FILE} --config_file ${CFG_FILE}"
}
`

And now couchpotato can start.  Seems that something is missing in the install script?

**Comment by cytec** [comment]
see: https://github.com/SynoCommunity/spksrc/issues/2216
