### ISSUE TITLE
Unable to run Shairport Sync on DS213j

### ISSUE THREAD

**Issue by SynoMalta** [SynoCommunity/spksrc#2432]
### Setup

_Package Name:_ Shairport Sync v2.3.11-2
_Package Version:_ v2.3.11-2

_NAS Model:_ DS213j
_NAS Architecture:_ MARVELL Armada 370 88F6707
_DSM version:_ DSM 6.0.1-7393 Update 2
### Behavior

I am trying to run the Shairport Sync v2.3.11-2 package from the SynoCommunity repository on my DS213j (MARVELL Armada 370 88F6707). After downloading from the package centre the status becomes "Starting..." but after a moment becomes "Stopped". I have already attached a USB soundcard and DS audio recognizes it. Any suggestions please?

**Comment by SynoMalta** [comment]
Sorry no data in package log (I assume because the package is not running)

**Comment by artbazz** [comment]
Same issue here also with DS213j (Armada 370)
In the log I found a **segmentation fault**...

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #3040.
