### ISSUE TITLE
SABnzbd-Synology "Invalid par2 files, cannot verify or repair"

### ISSUE THREAD

**Issue by regblade85** [SynoCommunity/spksrc#2439]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_SABnzbd
_Package Version:_1.0.3-16

_NAS Model:_Synology DS1815+
_NAS Architecture:_standard
_DSM version:_DSM 6.0.2-8451

### Expected behavior
sickrage snatches NZbd file and SABnzbd should download and move to complete folder.

### Actual behavior
NZB attempts to download and gives this error on all attempts "Invalid par2 files, cannot verify or repair"

### Steps to reproduce
_1._add a NZB file from a search provider or through sickrage
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

I dont know where to find this???

Insert log here
![2016-08-24_2130](https://cloud.githubusercontent.com/assets/20625269/17929169/0da59bf4-6a42-11e6-812a-2632da281341.png)

**Comment by KaraokeStu** [comment]
This appears to be an error within SABnzbd itself, and this is not the place for support with the application itself, just installing, updating or starting the actual package.

Based on your logs there, it appears that the articles containing the RAR files are not on your servers, and that it cannot find the correct PAR2 files, so the error appears legitimate

**Comment by KaraokeStu** [comment]
Not a bug with the package.

Try another news host or ask on the sabnzbd forums
