### ISSUE TITLE
Add port 443 in sslh and haproxy with use of synow3.

### ISSUE THREAD

**Issue by bvanhaverbeke** [SynoCommunity/spksrc#2440]
Since DSM 6.0.2 there is a function in VPNCenter that allows listening on 443.
This is done through the use of /usr/syno/bin/synow3.

with synow3 --set-443-multiplex one can change the ssl port of nginx from 443 to 412
with synow3 --set-443-off one can turn ssl off in nginx
with synow3 --set-443-on one can put everything back again.

Could this be incorporated in sslh and haproxy to make the programms work out of the box with port 443 ?

This would make the programms very effective.

Thanks

**Comment by Dr-Bean** [comment]
We don't touch Synology defaults if we can help it, so this probably will not be implemented as part of our packages.
A common way for listening on port 443 externally is handling this via a router: set port forwarding 443 externally to 8443 internally for example.
