### ISSUE TITLE
[Package Request] infinit.sh

### ISSUE THREAD

**Issue by hazcod** [SynoCommunity/spksrc#2442]
Name: Infinit.sh
Description: Infinit's decentralized storage platform transforms commodity servers into multiple flexible, scalable, secure and fault-tolerant storage infrastructure tailored for your applications.
Website: https://infinit.sh/
Software documentation: https://infinit.sh/documentation/overview
Build/Installation documentation: https://infinit.sh/get-started
Source Code: /
License: ?

**Comment by cytec** [comment]
no source code available... 
maybe ask them to provide a suitable package for Synology Devices or wait till they open source it (afaik they plan to)

**Comment by hgy59** [comment]
not available
