### ISSUE TITLE
NZBget multi failures occuring

### ISSUE THREAD

**Issue by regblade85** [SynoCommunity/spksrc#2443]
Hi, i was initially getting multiple failures with SAB so i installed NZB, now alot of files are failing. Anyone know why?

Setup

_Package Name:_SABnzbd
_Package Version:_1.0.3-16

_NAS Model:_Synology DS1815+
_NAS Architecture:_standard
_DSM version:_DSM 6.0.2-8451
Expected behavior

sickrage snatches NZbd file and SABnzbd should download and move to complete folder.
Actual behavior

NZB attempts to download and gives this error on all attempts "Invalid par2 files, cannot verify or repair"
Steps to reproduce

1._add a NZB file from a search provider or through sickrage

**Comment by regblade85** [comment]
Hi, i keep getting unpck adn health failures with NZBget, can anyone give me any pointers please

**Comment by Dr-Bean** [comment]
Thanks for reporting, but this is not due to the package or even the software. Failures like that are likely to be caused by articles being corrupt on your news server, articles not available due to takedowns, or the poster did something wrong during uploading.
