### ISSUE TITLE
Sonarr doesn't start anymore on my Synology

### ISSUE THREAD

**Issue by JDrillz** [SynoCommunity/spksrc#2444]
### Setup

Package Name: Sonarr
Package Version: 20150731-8

NAS Model: DS213j
NAS Architecture:
DSM version: 6.0.2-8451
### Expected behavior

Sonarr should start
### Actual behavior

Sonar doesn't start
### Steps to reproduce

_1._ Install Mono
_2._ Install Sonarr
_3._ Launch Sonarr
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

```
Installing package version="20150731-8"
Package Install Completed
```
#### Other logs

_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

```
Insert log here
```

Hi guys! Until yesterday everything was working properly, but now Sonarr (and Jackett) doesn't start anymore from my Synology DS213j.
When I try to launch Sonarr by clicking on its icon, a "failed connection" page appears.
If I try to launch it "manually" from the Package Center, Sonarr try to start itself, but then "stopped" appears under "status".
Same thing with Jackett.
Last night I updated Mono, so I imagine that this is the problem.
How can I solve?
I already tried to uninstall/reinstall everything.
Thanks!

@maxrogers

**Comment by csgnyc** [comment]
Having the same problem.

**Comment by JDrillz** [comment]
Solved following [THIS](https://www.reddit.com/r/sonarr/comments/4c7ddp/howto_sonarr_on_synology_dsm_60_workaround/) 
You have to type `sudo -i` in order to log as root in the Synology terminal. Now it works :)

**Comment by nlamirault** [comment]
Same issue in 212j with DSM 6.x
I try following https://www.reddit.com/r/sonarr/comments/4c7ddp/howto_sonarr_on_synology_dsm_60_workaround/ too.
with MONO_PATH: 
```
MONO_PATH="/var/packages/mono/target/bin/"
```

Logs : 

```
==> /var/log/synopkg.log <==
2017/01/05 13:44:53     start nzbdrone: begin to start version 20150731-8

==> /var/log/synoservice.log <==
2017-01-05T13:44:54+00:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[28294]: service_stop.c:23 synoservice: [pkgctl-nzbdrone] stopping ...
2017-01-05T13:44:55+00:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[28294]: service_stop.c:86 synoservice: [pkgctl-nzbdrone] stopped.
2017-01-05T13:44:55+00:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[28294]: service_start.c:74 synoservice: [pkgctl-nzbdrone] starting ...

==> /var/log/synopkg.log <==
2017/01/05 13:44:57     start nzbdrone: start version 20150731-8 successfully, result 0

==> /var/log/synoservice.log <==
2017-01-05T13:44:57+00:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[28294]: service_start.c:178 synoservice: [pkgctl-nzbdrone] started.
```

I try manually : 

```
./start-stop-daemon -c nzbdrone -S -N 10 -x env PATH=/var/packages/mono/target/bin:/usr/local/nzbdrone/bin:${PATH} LD_LIBRARY_PATH=/usr/local/nzbdrone/lib /var/packages/mono/target/bin/mono -- --debug /usr/local/nzbdrone/share/NzbDrone/NzbDrone.exe
1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m[Info] Bootstrap: Starting Sonarr - /volume1/@appstore/nzbdrone/share/NzbDrone/NzbDrone.exe - Version 2.0.0.3357 1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;m
1%{8}%<%t33%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;3%;m[Error] PidFileProvider: Unable to write PID file: /usr/local/nzbdrone/var/.config/NzbDrone/nzbdrone.pid 1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;m


1%{8}%<%t31%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;1%;m[Fatal] ConsoleApp: EPIC FAIL! 1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;m
1%{8}%<%t31%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;1%;m1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;m1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;m
1%{8}%<%t31%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;1%;m1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;mSystem.UnauthorizedAccessException: Access to the path "/usr/local/nzbdrone/var/.config/NzbDrone/nzbdrone.pid" is denied.1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m1%{8}%<%t40%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;0%;m
```

**Comment by AE9RB** [comment]
The info in `/var/packages/nzbdrone/target/var/.config/NzbDrone` wants to move to `~/.config/NzbDrone` after you update Sonarr. To work around I manually made a `nzbdrone` user in the UI with the proper permissions and enabled user home service. The goal of the workaround is to make `/volume1/homes/nzbdrone/` exist.

This may also explain some issues with people losing configs. However, mine is a new install so I didn't investigate that.

**Comment by Safihre** [comment]
DSM6 compatible version of the package is expected to be released soon. It can already be installed by downloading it from here #3138.
After the official release on SynoCommunity, the package will auto-update from the official release.
