### ISSUE TITLE
Syncthing Package unavailable on my Synology?!? even working build exists?

### ISSUE THREAD

**Issue by dionysius** [SynoCommunity/spksrc#2445]
I know syncthing, I'm using it since at least half a year now. I'd like to use my synology as another server to faster sync within the home network. My problem is, I can't install syncthing because it doesn't show up. Why? The binary runs fine...

A) How can I download .spk manually? or
B) How do i build .spk with syncthing? (Edit: [found this](https://github.com/SynoCommunity/spksrc/wiki/spksrc-example)) or
C) Can you add my architecture to package? or
D) Why is 88f628x (official package architecture support description) not equal to 88f6281?

### Setup
_Package Name:_ [syncthing](https://synocommunity.com/package/syncthing)
_Package Version:_ v0.13.4-9 (as of the package site)

_NAS Model:_ DS409
_NAS Architecture:_ [88f6281 (armv5)](https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model)
_DSM version:_ DSM 4.2-3256

### Expected behavior
I can download and install syncthing from inside the Syno package manager

### Actual behavior
Can't. It's not there?!? 

![2016-08-31 16_54_20-synology diskstation - srv-dionysius](https://cloud.githubusercontent.com/assets/1341084/18133675/cbabd95c-6f9b-11e6-9a3a-28f93a677a12.png)
![2016-08-31 16_39_48-synology diskstation - srv-dionysius](https://cloud.githubusercontent.com/assets/1341084/18133691/de338052-6f9b-11e6-9ee2-8c9617ef0fc2.png)

### Steps to reproduce
The binary runs fine, so there should be no reason to hide it?!? See below

#### Other logs
```
ssh root@srv-dionysius
#installation
srv-dionysius> cd /volume1/downloads
srv-dionysius> wget --no-check-certificate https://github.com/syncthing/syncthing/releases/download/v0.14.5/syncthing-linux-arm-v0.14.5.tar.gz
srv-dionysius> tar zxvf syncthing-linux-arm-v0.14.5.tar.gz
#running
srv-dionysius> ./syncthing
[monitor] 15:35:56 INFO: Starting syncthing
[start] 15:35:56 INFO: Generating ECDSA key and certificate for syncthing...
[HSLBO] 15:35:57 INFO: syncthing v0.14.5 "Dysprosium Dragonfly" (go1.7 linux-arm) jenkins@build.syncthing.net 2016-08-23 08:42:09 UTC
[HSLBO] 15:35:57 INFO: My ID: HSLBOVX-NJ7Y3SU-EACT27Q-6HAXGKZ-Q4HTKWU-RXXCX5H-33I5EQJ-Y5OVDAY
[HSLBO] 15:35:57 INFO: Single thread hash performance is ~7.0 MB/s
[HSLBO] 15:35:57 INFO: Default folder created and/or linked to new config
[HSLBO] 15:35:57 INFO: Defaults saved. Edit /root/.config/syncthing/config.xml to taste or use the GUI
[HSLBO] 15:35:57 INFO: Ready to synchronize jylgu-wcwvu (readwrite)
[HSLBO] 15:35:57 INFO: Using discovery server https://discovery-v4-1.syncthing.net/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[HSLBO] 15:35:57 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[HSLBO] 15:35:57 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[HSLBO] 15:35:57 INFO: Using discovery server https://discovery-v6-1.syncthing.net/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[HSLBO] 15:35:57 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[HSLBO] 15:35:57 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[HSLBO] 15:35:57 INFO: TCP listener ([::]:22000) starting
[HSLBO] 15:35:57 INFO: Completed initial scan (rw) of folder jylgu-wcwvu
[HSLBO] 15:35:58 INFO: Device HSLBOVX-NJ7Y3SU-EACT27Q-6HAXGKZ-Q4HTKWU-RXXCX5H-33I5EQJ-Y5OVDAY is "srv-dionysius" at [dynamic]
[HSLBO] 15:35:58 INFO: Loading HTTPS certificate: open /root/.config/syncthing/https-cert.pem: no such file or directory
[HSLBO] 15:35:58 INFO: Creating new HTTPS certificate
[HSLBO] 15:36:06 INFO: GUI and API listening on 127.0.0.1:8384
[HSLBO] 15:36:06 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[HSLBO] 15:36:09 INFO: Detected 0 NAT devices
^C[monitor] 15:36:10 INFO: Signal 2 received; exiting
[HSLBO] 15:36:10 INFO: Exiting
srv-dionysius> cd ..
srv-dionysius> ls -lah
drwxrwxrwx    3 root     root        4.0K Aug 31 17:35 .
drwxr-xr-x   15 root     root        4.0K Aug 13 13:33 ..
drwxrwxr-x    5 1004     1004        4.0K Aug 31 17:35 syncthing-linux-arm-v0.14.5
-rw-rw-rw-    1 root     root        5.1M Aug 23 11:16 syncthing-linux-arm-v0.14.5.tar.gz
```

**Comment by dionysius** [comment]
Well, I found out compiling syncthing myself for dsm-4.3 for arch-88f6281 works like a charm.

So I think just the package missing / not compiled for dsm-4.3 / arch-88f6281?

(Close at your will)

**Comment by cytec** [comment]
We don't provide SPK's for 4.3 anymore. But as you said, you can build it yourself.
