### ISSUE TITLE
Is anybody still maintaining this?

### ISSUE THREAD

**Issue by m4tt075** [SynoCommunity/spksrc#2447]
Asking because Dr-Bean hasn't been active for several weeks now and there are several PRs which seem pretty mature but are idleing around. Anybody knows what's going on here?

**Comment by Diaoul** [comment]
Synology with DSM 6 made huge changes without noticing developers and released the documentation only a few weeks ago. Every major release is a mess. This can be quite discouraging. 

Maintaining spksrc is becoming more and more complex and very time consuming for just a few developers. That plus the ever growing number of packages (50+), users (160k+) and the fact that maintenance is done on developers' free time.

Maybe Dr-Bean is just away for a few time and will come back, maybe not.

**Comment by StoneISStephan** [comment]
What if we all start donating something.
Give some money to the people who set all of this up and are willing to maintain it.

I just donated 20€, paypal makes it very easy nowadays.
And I've been using spksrc for a few years now, they're worth the donation regardless.

**Comment by Diaoul** [comment]
I'm not sure the problem is with money but with time. Personally I've been thinking building a new framework from scratch with all the stuff learned from spksrc and the newest features of DSM 6 but that takes a lot of time and effort with DSM being more and more complex. I may get into it eventually but this is too big a project for a single person.

Please direct your efforts to contributing code rather than money and if you really want to donate your money, do it through Bountysource on issues rather than Paypal.

**Comment by m4tt075** [comment]
OK. Clear, Diaoul. Thank YOU for your efforts!

**Comment by rpgdev** [comment]
Well, it seems I won't be updating to DSM 6 in the near future then.

**Comment by jeffreydwalter** [comment]
@Diaoul let me know how I can help with a new framework.

**Comment by rpgdev** [comment]
If debian-chroot isn't available on more recent devices from Synology I'd probably just "graduate" to a small home server. Pure Linux is just too good after you've hit DSM limitations here and there.

**Comment by Diaoul** [comment]
Depends on your needs. With Docker I'd say you can do pretty much everything on a NAS nowadays with no performance drawbacks (as you would have with a VM).

**Comment by rpgdev** [comment]
True and I hadn't considered that but I'm guessing the package is only available on higher end DS. Still worth considering I guess since Synology's hardware is very convenient.

**Comment by m4tt075** [comment]
Yes, same considerations. Just missed the train with my DS415Play. Will likely leave Syno though as I'm absolutely not happy about how they have handled the DSM6.0 transition when it comes to 3rd party package support.

**Comment by Hubfront** [comment]
It's not nice how synology treats the developers here. Is qnap better when it comes to support with documentation?

**Comment by rpgdev** [comment]
@m4tt075 what do you mean when you say "Just missed the train with my DS415Play."?

**Comment by m4tt075** [comment]
@rpgdev: Slightly more performant models run docker, the DS415Play doesn't...

**Comment by rpgdev** [comment]
@m4tt075 oh ok. Got it.

**Comment by KaraokeStu** [comment]
This project is still being maintained. Where possible, I'm now keeping up to date with the 5.x package maintenance, however no guarantees can be currently made that the package updates will be 6.x compatible

**Comment by m4tt075** [comment]
Thank you, @KaraokeStu. Will close the issue then...
