### ISSUE TITLE
How to mount usb shares on debian-chroot?

### ISSUE THREAD

**Issue by rpgdev** [SynoCommunity/spksrc#2448]
_For new Package Requests, see the guidelines_  
### Setup

_Package Name:_ debian-chroot
_Package Version:_ 8.4-7

_NAS Model:_ ds213j
_NAS Architecture:_ arm
_DSM version:_ 5.2
### Expected behavior

I try to mount the usb share the same way I mounted the drives and while it seems the share is mounted (the @eadir and usbshare folder are there) I don't see any of the folders or files that should be under the usbshare folder.
### Actual behavior

No file or folder is listed
### Steps to reproduce

I used this guide to set up chroot and the mounting of the disks, it worked for those but not for usb drives: https://markpith.wordpress.com/2015/10/26/debian-chroot-on-synology-nas

**Comment by pannbiff** [comment]
This works for me:

`grep -q "${CHROOTTARGET}/volumeUSB1 " /volumeUSB1 || mount -o bind /volumeUSB1 ${CHROOTTARGET}/volumeUSB1`

and

`umount ${CHROOTTARGET}/volumeUSB1`

**Comment by rpgdev** [comment]
Thanks for answering @pannbiff but that doesn't work for me. The behaviour is the same, it appears mounted but no files are shown.

**Comment by Safihre** [comment]
Closing this due to age and it being more of a support question.
Can be re-openend if it's a bug in the package.
