### ISSUE TITLE
New NZBhydra package not in synocommunity

### ISSUE THREAD

**Issue by nimbuz** [SynoCommunity/spksrc#2455]
Hi

I wanted to install the new nzbhydra package after reading that it got merged, however it is not showing up in the synocommunity packages on my synology nas. Does it take a new package a while to get there, or is there something I need to do in order for it to show up?
I hope this question does not break the guidelines. Please let me know if it does, and thanks in advance!

**Comment by KaraokeStu** [comment]
Hi, don't worry... It will take a little while to get onto the repo, as I'm waiting for publish access from the admins. I should have it, but an email has got lost somewhere in the ether

**Comment by KaraokeStu** [comment]
All done and published
