### ISSUE TITLE
Cant get SABnzbd to start after recent package update...

### ISSUE THREAD

**Issue by shaun71190** [SynoCommunity/spksrc#2469]
I cant seem to get it to start anymore i have tried everything from restarting to reinstalling i just cant seem to get it to start anymore after this update.... I tried the testing beta version it installed and started the first time great i stop it and then bam now its doing the samething the other is doing no matter what it will not start... since the fresh install i am now getting this error via PUTTY which seems like a su error .....

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
- PACKAGE=sabnzbd
- DNAME=SABnzbd
- INSTALL_DIR=/usr/local/sabnzbd
- PYTHON_DIR=/usr/local/python
- PATH=/usr/local/sabnzbd/bin:/usr/local/sabnzbd/env/bin:/usr/local/python/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
- USER=sabnzbd
- PYTHON=/usr/local/sabnzbd/env/bin/python
- SABNZBD=/usr/local/sabnzbd/share/SABnzbd/SABnzbd.py
- CFG_FILE=/usr/local/sabnzbd/var/config.ini
- LOG_FILE=/usr/local/sabnzbd/var/logs/sabnzbd.log
- PID_FILE=/usr/local/sabnzbd/var/sabnzbd.pid
- case $1 in
- daemon_status
- '[' -f /usr/local/sabnzbd/var/sabnzbd.pid ']'
- rm -f /usr/local/sabnzbd/var/sabnzbd.pid
- return 1
- echo Starting SABnzbd ...
  Starting SABnzbd ...
- start_daemon
- su - sabnzbd -c 'PATH=/usr/local/sabnzbd/bin:/usr/local/sabnzbd/env/bin:/usr/local/python/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin /usr/local/sabnzbd/env/bin/python /usr/local/sabnzbd/share/SABnzbd/SABnzbd.py -f /usr/local/sabnzbd/var/config.ini --pidfile /usr/local/sabnzbd/var/sabnzbd.pid -d'
  su: Permission denied

Package name : SABnzbd
Package ver: 1.1.0-18

NAS MOD: Synology DS1515+
Arch: x64
DSM ver: DSM 6.0.2-8451 Update 1

**Comment by shaun71190** [comment]
I forgot i didnt add the user so i added the user and now i added the user and it does this now...


shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
+ PACKAGE=sabnzbd
+ DNAME=SABnzbd
+ INSTALL_DIR=/usr/local/sabnzbd
+ PYTHON_DIR=/usr/local/python
+ PATH=/usr/local/sabnzbd/bin:/usr/local/sabnzbd/env/bin:/usr/local/python/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
+ USER=sabnzbd
+ PYTHON=/usr/local/sabnzbd/env/bin/python
+ SABNZBD=/usr/local/sabnzbd/share/SABnzbd/SABnzbd.py
+ CFG_FILE=/usr/local/sabnzbd/var/config.ini
+ LOG_FILE=/usr/local/sabnzbd/var/logs/sabnzbd.log
+ PID_FILE=/usr/local/sabnzbd/var/sabnzbd.pid
+ case $1 in
+ daemon_status
+ '[' -f /usr/local/sabnzbd/var/sabnzbd.pid ']'
+ rm -f /usr/local/sabnzbd/var/sabnzbd.pid
+ return 1
+ echo Starting SABnzbd ...
Starting SABnzbd ...
+ start_daemon
+ su - sabnzbd -c 'PATH=/usr/local/sabnzbd/bin:/usr/local/sabnzbd/env/bin:/usr/local/python/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin /usr/local/sabnzbd/env/bin/python /usr/local/sabnzbd/share/SABnzbd/SABnzbd.py -f /usr/local/sabnzbd/var/config.ini --pidfile /usr/local/sabnzbd/var/sabnzbd.pid -d'
/usr/local/sabnzbd/env/bin/python: can't open file '/usr/local/sabnzbd/share/SABnzbd/SABnzbd.py': [Errno 2] No such file or directory

**Comment by KaraokeStu** [comment]
Could you please add more details, as requested when logging bugs...

### Setup
_Package Name:_
_Package Version:_

_NAS Model:_
_NAS Architecture:_
_DSM version:_

**Comment by shaun71190** [comment]
Oh i forgot those few things...
Package name : SABnzbd
Package ver: 1.1.0-18

NAS MOD: Synology DS1515+
Arch: x64
DSM ver: DSM 6.0.2-8451 Update 1

**Comment by shaun71190** [comment]
@M0UL I did attempt to do that didnt work for me one bit lolz DSM 6 is just wacky....

**Comment by KaraokeStu** [comment]
Unfortunately, I don't currently have DSM 6.0 so am unable to test on this at present - will try to get it installed and tested locally

**Comment by soothingone** [comment]
Mine also stopped working, and after a lot of troubleshooting, I ended up just running a "chown -r sickbeard-custom *" whn in the /volume1/@appstore/sickbeard-custom/var/ folder, this solved it

**Comment by Safihre** [comment]
Closing due to age. Test-packages for DSM6.1 and new architectures available here: #3138.
Those will later be published to the real package rep.
