### ISSUE TITLE
Unable to launch Subliminal 0.7.5-12 on Synology DS216j NAS

### ISSUE THREAD

**Issue by cray19003** [SynoCommunity/spksrc#2474]
Hello,
I can't launch the Subliminal package.
Can anyone help me ?
Thanks.

### Setup
_Package Name:_Subliminal
_Package Version:_0.7.5-12

Installed packadge
_Package Name:_Python
_Package Version:_2.7.11-1

_NAS Model:_DS216j
_DSM version:_DSM 6.0.2-8451 Update 1

### Expected behavior
I expect that the package should start.

### Actual behavior
I got an error message : "Failure to launch package repair"

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
No log

**Comment by cray19003** [comment]
Ok, a reboot slove the problem. Sorry.

**Comment by cray19003** [comment]
After lauchung Subliminal, the loading indicator never ends.
Did I miss something ?

![syno](https://cloud.githubusercontent.com/assets/22468046/18878879/87fe8974-84d2-11e6-87c2-709795500048.jpg)

**Comment by cray19003** [comment]
OK following #2357

**Comment by didierkrux** [comment]
I did this because there is no official solution: https://github.com/SynoCommunity/spksrc/issues/2357#issuecomment-256447783

**Comment by andreicel** [comment]
Look this
[https://www.youtube.com/watch?v=9wLctApqoBY&t=29s](url)

**Comment by Dr-Bean** [comment]
@andreicel This is a bugtracker for SynoCommunity packages. Manual installations and whatnot are out of scope. Please don't do this again.
