### ISSUE TITLE
ImageMagick is missing

### ISSUE THREAD

**Issue by iBook140** [SynoCommunity/spksrc#2477]
Hello,

I installed the package center as described, but ImageMagick is missing, so I can’t install it on my DS916+ :( 

Checkbox to see beta versions is checked!

Would be great, if you could add this package again.

Thanks in advance and kind regards
René

**Comment by cytec** [comment]
Seems like the SPK wasn't published for braswell yet

**Comment by iBook140** [comment]
Thank you very much for your answer! 

This means bad luck, or is there any possibility to get this running?

Kind regards
René

**Comment by KaraokeStu** [comment]
Updating to 6.9.5-10... building now, will publish if all succeeds

**Comment by KaraokeStu** [comment]
Merged and published

**Comment by iBook140** [comment]
Sorry to ask again but ImageMagick doesn’t seem to be present when I look at the php.info 

I tried to restart Web Station and PHP, is a complete reboot necessary?

Kind regards
René

**Comment by cytec** [comment]
We don't provide a ImageMagick PHP Extension. Only CLI tools and libraries for 3rd party stuff

**Comment by iBook140** [comment]
Okay, thanks anyway!

Kind regards
René
