### ISSUE TITLE
Tcl  stop with  error message

### ISSUE THREAD

**Issue by biloucat** [SynoCommunity/spksrc#2479]
Package Name: tcl
Package Version: 1.0

NAS Model: DS412+ Intel Atom D2700 Architecture: cedarview (x64)
NAS Architecture:
DSM version: 5.2

### Expected behavior
tclsh should run

### Actual behavior
tclsh stop with  the message:
 error while loading shared libraries: libtcl8.6.so

it seems for me that the link  tcl -> /var/packages/tcl/target in /usr/local is missing

**Comment by KaraokeStu** [comment]
@eelcohuininga Could you have a look into this please?

**Comment by KaraokeStu** [comment]
I had a quick look and it appears that TCL needs to load shared libraries - these are linked to the correct location, but LD_LIBRARY_PATH is not set correctly.

Setting this via
   export LD_LIBRARY_PATH=/usr/local/lib

Makes it all work properly

**Comment by biloucat** [comment]
i think that /usr/local/  is in the library path but that tcl is not in /usr/local because the link /usr/localtcl -> /var/packages/tcl/target is missing

**Comment by biloucat** [comment]
if i remove  the link /usr/local/tcl -> /var/packages/tcl/target, without doing nothing else , tclsh break;
if i redo the link  /usr/local/tcl -> /var/packages/tcl/target, tclsh start again

**Comment by biloucat** [comment]
perhaps the links in /usr/local/lib:
  libtcl.so -> /volume1/@appstore/tcl/lib/libtcl8.6.so 
  libtcl8.6.so -> /volume1/@appstore/tcl/lib/libtcl8.6.so
are useless but the link 
  tcl8.6 -> /volume1/@appstore/tcl/lib/tcl8.6/
is useful !

**Comment by eelcohuininga** [comment]
Hi,
Can you check a couple of things for me?
1. Can you confirm that the symlink ```/usr/local/lib/libtcl8.6.so``` points to ```/volume1/@appstore/tcl/lib/libtcl8.6.so```?
2. Does ```tclsh``` work again if you de-install the package, and then re-install it?

**Comment by eelcohuininga** [comment]
```tclsh``` needs the LD_LIBRARY_PATH to be set to the location of ```libtcl8.6.so```. This is set by the installer script, but I guess this is wrong, because if you reboot your Synology, the LD_LIBRARY_PATH never gets set. I think I'll have to move it to the start-stop-status script in order for it to get set every time the package is started.

**Comment by eelcohuininga** [comment]
The ```tcl8.6``` map is needed for the default settings of ```tclsh```. It will start just fine without it, but it will throw an error message if it's not present. It should have nothing to do with the ``` error while loading shared libraries: libtcl8.6.so``` error.

**Comment by biloucat** [comment]
@eelcohuininga After the install there are 3 symlinks in /usr/local/lib:
libtcl.so -> /volume1/@appstore/tcl/lib/libtcl8.6.so
libtcl8.6.so -> /volume1/@appstore/tcl/lib/libtcl8.6.so
tcl8.6 -> /volume1/@appstore/tcl/lib/tcl8.6/
And tclsh don't work (re-install change nothing)
If i manually add  the symlink /usr/local/tcl -> /var/packages/tcl/target, tclsh work
if i remove the two links /usr/local/lib/libtcl.so and /usr/local/lib/libtcl8.6.so, tclsh work still
For me LD_LIBRARY_PATH is useless
i not reboot my syno

**Comment by biloucat** [comment]
@eelcohuininga 
you could see at https://synopackages.wordpress.com/2016/02/28/tcl-8-6-4-for-synology-nas-and-router/

**Comment by eelcohuininga** [comment]
Thanks for the info @biloucat . Seems like DSM5.2 and earlier need the ```/usr/local/${PACKAGE}``` link to function properly. I've tested it on DSM6 and afaik it doesn't need that link.

I've updated the installer script so it creates this link. I also changed the other links so they point to ```/var/packages/${PACKAGE}/target/```. 

Can you try it out and see if it works properly for you? I've put it temporarily online at https://github.com/eelcohuininga/synotcl/blob/master/tcl_cedarview-5.2_8.6.6-2.spk

**Comment by biloucat** [comment]
@eelcohuininga i try it and it works
three comments:
**the symlink tcl -> /var/packages/tcl/target// (two / instead of one /, at the end)
  perhaps PACKAGE_DIR="/var/packages/${PACKAGE}/target/" could be PACKAGE_DIR="/var/packages/${PACKAGE}/target" in the installer
**Are you sure that the symlinks libtcl.so  and libtcl8.6.so are useful ?
**Are you sure that "export LD_LIBRARY_PATH=/usr/local/lib/" is useful ?
    and i can't see it with export in terminal ssh

**Comment by eelcohuininga** [comment]
The libtcl.so and libtcl8.6.so symlinks are needed for packages which require the Tcl library files (packages like Eggdrop), so yes they're useful.
The LD_LIBRARY_PATH is not useful in this form, since it's related to the user's shell profile. It either has to be added to /etc/profile so all users get the LD_LIBRARY_PATH setting as default, or users/packages have to set it themselves. I'll remove the export LD_LIBRARY_PATH from the installer script, so users and/or package developers can decide for themselves if they want to define it or not.

**Comment by biloucat** [comment]
@eelcohuininga : thanks for your work.
i am on archlinux and test cross-compile with spksrc for the first time: i have compiled and installed your package v1 with success (with manual adding symlink) !
could you tell me how add sqlite and tcllib to the package
could you tell me how to compile for DSM 6.0 ( I am reluctant to upgrade from 5.2 to 6.0 !)

**Comment by biloucat** [comment]
@eelcohuininga 
PLIST is incomplete:
for example history.tcl is missing in /lib/tcl8.6 and many others
so command history is unknown in tclsh

**Comment by eelcohuininga** [comment]
@biloucat:
- SQlite is pre-packaged with Tcl, so regular compiling will also give you SQlite. I removed it from this package because of the rules implied here: https://github.com/SynoCommunity/spksrc/wiki/PLIST-files Because SQlite is a seperate application, which is already seperately included in the spksrc, I removed it from the package. Perhaps @KaraokeStu can give some hints on this subject? Should SQlite be included in the Tcl package? Or should SQlite be a dependancy of Tcl? Or should users install the SQlite spk-package seperately from Tcl? What are the spksrc-rules on this subject?
- history.tcl was removed for the same reason: My impression of the PLIST-files rules is that the package should be as light as possible. Maybe I was a bit too 'progressive' with that :-) I'll add it to the package.
- /lib/tcl8.6/* should be included in the package, see the PLIST file. I've put a full list of all files compiled by spksrc here: http://pastebin.com/sERFxPqC Can you explicitly point out which files you are missing?
- The packages are compiled with the master tree of spksrc, which means that they're compiled for DSM5.2 (amongst others). I personally am running DSM6.0 for over half a year I guess, and the Tcl package published here is running fine under DSM6.0.

**Comment by biloucat** [comment]
All files in lib/tcl8.6 are useful
I am interested by tcllib : perhaps a new package
I am on vacation for 15 days without internet and make tests later  !

**Comment by eelcohuininga** [comment]
I'll work on a revision 3 of the Tcl8.6.6 package :) Have a nice holiday!

**Comment by eelcohn** [comment]
Ok, I finally had time to do the new Tcl package. @biloucat: would you be able to test the new package? You can find it at https://github.com/eelcohn/synotcl/blob/master/tcl_cedarview-5.2_8.6.6-3.spk

Please check that:
* Upgrading the package works correctly
* All the functions you want to use work correctly

FYI: the following files are now included in the package:
```
bin:bin/sqlite3_analyzer
bin:bin/tclsh8.6
rsc:lib/itcl4.0.5/itclConfig.sh
rsc:lib/itcl4.0.5/itclHullCmds.tcl
rsc:lib/itcl4.0.5/itcl.tcl
rsc:lib/itcl4.0.5/itclWidget.tcl
rsc:lib/itcl4.0.5/libitcl4.0.5.so
rsc:lib/itcl4.0.5/pkgIndex.tcl
lib:lib/libtcl8.6.so
lnk:lib/libtcl.so
rsc:lib/pkgconfig/tcl.pc
lib:lib/sqlite3.13.0/libsqlite3.13.0.so
rsc:lib/sqlite3.13.0/pkgIndex.tcl
rsc:lib/tcl8.6/auto.tcl
rsc:lib/tcl8.6/clock.tcl
rsc:lib/tcl8.6/encoding/ascii.enc
rsc:lib/tcl8.6/encoding/big5.enc
rsc:lib/tcl8.6/encoding/cp1250.enc
rsc:lib/tcl8.6/encoding/cp1251.enc
rsc:lib/tcl8.6/encoding/cp1252.enc
rsc:lib/tcl8.6/encoding/cp1253.enc
rsc:lib/tcl8.6/encoding/cp1254.enc
rsc:lib/tcl8.6/encoding/cp1255.enc
rsc:lib/tcl8.6/encoding/cp1256.enc
rsc:lib/tcl8.6/encoding/cp1257.enc
rsc:lib/tcl8.6/encoding/cp1258.enc
rsc:lib/tcl8.6/encoding/cp437.enc
rsc:lib/tcl8.6/encoding/cp737.enc
rsc:lib/tcl8.6/encoding/cp775.enc
rsc:lib/tcl8.6/encoding/cp850.enc
rsc:lib/tcl8.6/encoding/cp852.enc
rsc:lib/tcl8.6/encoding/cp855.enc
rsc:lib/tcl8.6/encoding/cp857.enc
rsc:lib/tcl8.6/encoding/cp860.enc
rsc:lib/tcl8.6/encoding/cp861.enc
rsc:lib/tcl8.6/encoding/cp862.enc
rsc:lib/tcl8.6/encoding/cp863.enc
rsc:lib/tcl8.6/encoding/cp864.enc
rsc:lib/tcl8.6/encoding/cp865.enc
rsc:lib/tcl8.6/encoding/cp866.enc
rsc:lib/tcl8.6/encoding/cp869.enc
rsc:lib/tcl8.6/encoding/cp874.enc
rsc:lib/tcl8.6/encoding/cp932.enc
rsc:lib/tcl8.6/encoding/cp936.enc
rsc:lib/tcl8.6/encoding/cp949.enc
rsc:lib/tcl8.6/encoding/cp950.enc
rsc:lib/tcl8.6/encoding/dingbats.enc
rsc:lib/tcl8.6/encoding/ebcdic.enc
rsc:lib/tcl8.6/encoding/euc-cn.enc
rsc:lib/tcl8.6/encoding/euc-jp.enc
rsc:lib/tcl8.6/encoding/euc-kr.enc
rsc:lib/tcl8.6/encoding/gb12345.enc
rsc:lib/tcl8.6/encoding/gb1988.enc
rsc:lib/tcl8.6/encoding/gb2312.enc
rsc:lib/tcl8.6/encoding/gb2312-raw.enc
rsc:lib/tcl8.6/encoding/iso2022.enc
rsc:lib/tcl8.6/encoding/iso2022-jp.enc
rsc:lib/tcl8.6/encoding/iso2022-kr.enc
rsc:lib/tcl8.6/encoding/iso8859-10.enc
rsc:lib/tcl8.6/encoding/iso8859-13.enc
rsc:lib/tcl8.6/encoding/iso8859-14.enc
rsc:lib/tcl8.6/encoding/iso8859-15.enc
rsc:lib/tcl8.6/encoding/iso8859-16.enc
rsc:lib/tcl8.6/encoding/iso8859-1.enc
rsc:lib/tcl8.6/encoding/iso8859-2.enc
rsc:lib/tcl8.6/encoding/iso8859-3.enc
rsc:lib/tcl8.6/encoding/iso8859-4.enc
rsc:lib/tcl8.6/encoding/iso8859-5.enc
rsc:lib/tcl8.6/encoding/iso8859-6.enc
rsc:lib/tcl8.6/encoding/iso8859-7.enc
rsc:lib/tcl8.6/encoding/iso8859-8.enc
rsc:lib/tcl8.6/encoding/iso8859-9.enc
rsc:lib/tcl8.6/encoding/jis0201.enc
rsc:lib/tcl8.6/encoding/jis0208.enc
rsc:lib/tcl8.6/encoding/jis0212.enc
rsc:lib/tcl8.6/encoding/koi8-r.enc
rsc:lib/tcl8.6/encoding/koi8-u.enc
rsc:lib/tcl8.6/encoding/ksc5601.enc
rsc:lib/tcl8.6/encoding/macCentEuro.enc
rsc:lib/tcl8.6/encoding/macCroatian.enc
rsc:lib/tcl8.6/encoding/macCyrillic.enc
rsc:lib/tcl8.6/encoding/macDingbats.enc
rsc:lib/tcl8.6/encoding/macGreek.enc
rsc:lib/tcl8.6/encoding/macIceland.enc
rsc:lib/tcl8.6/encoding/macJapan.enc
rsc:lib/tcl8.6/encoding/macRoman.enc
rsc:lib/tcl8.6/encoding/macRomania.enc
rsc:lib/tcl8.6/encoding/macThai.enc
rsc:lib/tcl8.6/encoding/macTurkish.enc
rsc:lib/tcl8.6/encoding/macUkraine.enc
rsc:lib/tcl8.6/encoding/shiftjis.enc
rsc:lib/tcl8.6/encoding/symbol.enc
rsc:lib/tcl8.6/encoding/tis-620.enc
rsc:lib/tcl8.6/history.tcl
rsc:lib/tcl8.6/http1.0/http.tcl
rsc:lib/tcl8.6/http1.0/pkgIndex.tcl
rsc:lib/tcl8.6/init.tcl
rsc:lib/tcl8.6/msgs/af.msg
rsc:lib/tcl8.6/msgs/af_za.msg
rsc:lib/tcl8.6/msgs/ar_in.msg
rsc:lib/tcl8.6/msgs/ar_jo.msg
rsc:lib/tcl8.6/msgs/ar_lb.msg
rsc:lib/tcl8.6/msgs/ar.msg
rsc:lib/tcl8.6/msgs/ar_sy.msg
rsc:lib/tcl8.6/msgs/be.msg
rsc:lib/tcl8.6/msgs/bg.msg
rsc:lib/tcl8.6/msgs/bn_in.msg
rsc:lib/tcl8.6/msgs/bn.msg
rsc:lib/tcl8.6/msgs/ca.msg
rsc:lib/tcl8.6/msgs/cs.msg
rsc:lib/tcl8.6/msgs/da.msg
rsc:lib/tcl8.6/msgs/de_at.msg
rsc:lib/tcl8.6/msgs/de_be.msg
rsc:lib/tcl8.6/msgs/de.msg
rsc:lib/tcl8.6/msgs/el.msg
rsc:lib/tcl8.6/msgs/en_au.msg
rsc:lib/tcl8.6/msgs/en_be.msg
rsc:lib/tcl8.6/msgs/en_bw.msg
rsc:lib/tcl8.6/msgs/en_ca.msg
rsc:lib/tcl8.6/msgs/en_gb.msg
rsc:lib/tcl8.6/msgs/en_hk.msg
rsc:lib/tcl8.6/msgs/en_ie.msg
rsc:lib/tcl8.6/msgs/en_in.msg
rsc:lib/tcl8.6/msgs/en_nz.msg
rsc:lib/tcl8.6/msgs/en_ph.msg
rsc:lib/tcl8.6/msgs/en_sg.msg
rsc:lib/tcl8.6/msgs/en_za.msg
rsc:lib/tcl8.6/msgs/en_zw.msg
rsc:lib/tcl8.6/msgs/eo.msg
rsc:lib/tcl8.6/msgs/es_ar.msg
rsc:lib/tcl8.6/msgs/es_bo.msg
rsc:lib/tcl8.6/msgs/es_cl.msg
rsc:lib/tcl8.6/msgs/es_co.msg
rsc:lib/tcl8.6/msgs/es_cr.msg
rsc:lib/tcl8.6/msgs/es_do.msg
rsc:lib/tcl8.6/msgs/es_ec.msg
rsc:lib/tcl8.6/msgs/es_gt.msg
rsc:lib/tcl8.6/msgs/es_hn.msg
rsc:lib/tcl8.6/msgs/es.msg
rsc:lib/tcl8.6/msgs/es_mx.msg
rsc:lib/tcl8.6/msgs/es_ni.msg
rsc:lib/tcl8.6/msgs/es_pa.msg
rsc:lib/tcl8.6/msgs/es_pe.msg
rsc:lib/tcl8.6/msgs/es_pr.msg
rsc:lib/tcl8.6/msgs/es_py.msg
rsc:lib/tcl8.6/msgs/es_sv.msg
rsc:lib/tcl8.6/msgs/es_uy.msg
rsc:lib/tcl8.6/msgs/es_ve.msg
rsc:lib/tcl8.6/msgs/et.msg
rsc:lib/tcl8.6/msgs/eu_es.msg
rsc:lib/tcl8.6/msgs/eu.msg
rsc:lib/tcl8.6/msgs/fa_in.msg
rsc:lib/tcl8.6/msgs/fa_ir.msg
rsc:lib/tcl8.6/msgs/fa.msg
rsc:lib/tcl8.6/msgs/fi.msg
rsc:lib/tcl8.6/msgs/fo_fo.msg
rsc:lib/tcl8.6/msgs/fo.msg
rsc:lib/tcl8.6/msgs/fr_be.msg
rsc:lib/tcl8.6/msgs/fr_ca.msg
rsc:lib/tcl8.6/msgs/fr_ch.msg
rsc:lib/tcl8.6/msgs/fr.msg
rsc:lib/tcl8.6/msgs/ga_ie.msg
rsc:lib/tcl8.6/msgs/ga.msg
rsc:lib/tcl8.6/msgs/gl_es.msg
rsc:lib/tcl8.6/msgs/gl.msg
rsc:lib/tcl8.6/msgs/gv_gb.msg
rsc:lib/tcl8.6/msgs/gv.msg
rsc:lib/tcl8.6/msgs/he.msg
rsc:lib/tcl8.6/msgs/hi_in.msg
rsc:lib/tcl8.6/msgs/hi.msg
rsc:lib/tcl8.6/msgs/hr.msg
rsc:lib/tcl8.6/msgs/hu.msg
rsc:lib/tcl8.6/msgs/id_id.msg
rsc:lib/tcl8.6/msgs/id.msg
rsc:lib/tcl8.6/msgs/is.msg
rsc:lib/tcl8.6/msgs/it_ch.msg
rsc:lib/tcl8.6/msgs/it.msg
rsc:lib/tcl8.6/msgs/ja.msg
rsc:lib/tcl8.6/msgs/kl_gl.msg
rsc:lib/tcl8.6/msgs/kl.msg
rsc:lib/tcl8.6/msgs/kok_in.msg
rsc:lib/tcl8.6/msgs/kok.msg
rsc:lib/tcl8.6/msgs/ko_kr.msg
rsc:lib/tcl8.6/msgs/ko.msg
rsc:lib/tcl8.6/msgs/kw_gb.msg
rsc:lib/tcl8.6/msgs/kw.msg
rsc:lib/tcl8.6/msgs/lt.msg
rsc:lib/tcl8.6/msgs/lv.msg
rsc:lib/tcl8.6/msgs/mk.msg
rsc:lib/tcl8.6/msgs/mr_in.msg
rsc:lib/tcl8.6/msgs/mr.msg
rsc:lib/tcl8.6/msgs/ms.msg
rsc:lib/tcl8.6/msgs/ms_my.msg
rsc:lib/tcl8.6/msgs/mt.msg
rsc:lib/tcl8.6/msgs/nb.msg
rsc:lib/tcl8.6/msgs/nl_be.msg
rsc:lib/tcl8.6/msgs/nl.msg
rsc:lib/tcl8.6/msgs/nn.msg
rsc:lib/tcl8.6/msgs/pl.msg
rsc:lib/tcl8.6/msgs/pt_br.msg
rsc:lib/tcl8.6/msgs/pt.msg
rsc:lib/tcl8.6/msgs/ro.msg
rsc:lib/tcl8.6/msgs/ru.msg
rsc:lib/tcl8.6/msgs/ru_ua.msg
rsc:lib/tcl8.6/msgs/sh.msg
rsc:lib/tcl8.6/msgs/sk.msg
rsc:lib/tcl8.6/msgs/sl.msg
rsc:lib/tcl8.6/msgs/sq.msg
rsc:lib/tcl8.6/msgs/sr.msg
rsc:lib/tcl8.6/msgs/sv.msg
rsc:lib/tcl8.6/msgs/sw.msg
rsc:lib/tcl8.6/msgs/ta_in.msg
rsc:lib/tcl8.6/msgs/ta.msg
rsc:lib/tcl8.6/msgs/te_in.msg
rsc:lib/tcl8.6/msgs/te.msg
rsc:lib/tcl8.6/msgs/th.msg
rsc:lib/tcl8.6/msgs/tr.msg
rsc:lib/tcl8.6/msgs/uk.msg
rsc:lib/tcl8.6/msgs/vi.msg
rsc:lib/tcl8.6/msgs/zh_cn.msg
rsc:lib/tcl8.6/msgs/zh_hk.msg
rsc:lib/tcl8.6/msgs/zh.msg
rsc:lib/tcl8.6/msgs/zh_sg.msg
rsc:lib/tcl8.6/msgs/zh_tw.msg
rsc:lib/tcl8.6/opt0.4/optparse.tcl
rsc:lib/tcl8.6/opt0.4/pkgIndex.tcl
rsc:lib/tcl8.6/package.tcl
rsc:lib/tcl8.6/parray.tcl
rsc:lib/tcl8.6/safe.tcl
rsc:lib/tcl8.6/tclAppInit.c
rsc:lib/tcl8.6/tclIndex
rsc:lib/tcl8.6/tm.tcl
rsc:lib/tcl8.6/word.tcl
rsc:lib/tcl8/8.4/platform-1.0.14.tm
rsc:lib/tcl8/8.4/platform/shell-1.1.4.tm
rsc:lib/tcl8/8.5/msgcat-1.6.0.tm
rsc:lib/tcl8/8.5/tcltest-2.4.0.tm
rsc:lib/tcl8/8.6/http-2.8.9.tm
rsc:lib/tcl8/8.6/tdbc/sqlite3-1.0.4.tm
rsc:lib/tclConfig.sh
rsc:lib/tclooConfig.sh
lib:lib/tdbc1.0.4/libtdbc1.0.4.so
rsc:lib/tdbc1.0.4/pkgIndex.tcl
rsc:lib/tdbc1.0.4/tdbcConfig.sh
rsc:lib/tdbc1.0.4/tdbc.tcl
lib:lib/tdbcmysql1.0.4/libtdbcmysql1.0.4.so
rsc:lib/tdbcmysql1.0.4/pkgIndex.tcl
rsc:lib/tdbcmysql1.0.4/tdbcmysql.tcl
lib:lib/tdbcodbc1.0.4/libtdbcodbc1.0.4.so
rsc:lib/tdbcodbc1.0.4/pkgIndex.tcl
rsc:lib/tdbcodbc1.0.4/tdbcodbc.tcl
lib:lib/tdbcpostgres1.0.4/libtdbcpostgres1.0.4.so
rsc:lib/tdbcpostgres1.0.4/pkgIndex.tcl
rsc:lib/tdbcpostgres1.0.4/tdbcpostgres.tcl
lib:lib/thread2.8.0/libthread2.8.0.so
rsc:lib/thread2.8.0/pkgIndex.tcl
rsc:lib/thread2.8.0/ttrace.tcl

```

Basically it's now a full distro, except for the following files
```
lib:lib/itcl4.0.5/libitclstub4.0.5.a
lib:lib/libtclstub8.6.a
lib:lib/tdbc1.0.4/libtdbcstub1.0.4.a
rsc:include/*
rsc:man/*
```

**Comment by biloucat** [comment]
@eelcohn 
THANKS for your work
Upgrading the package works correctly
something is bad:
if if try the command "clock scan 1752-09-02 -format %Y-%m-%d -locale en_US"
on my archlinux, i get: -6857309361
on my syno, i get: can't find package msgcat 1.6
on my archlinux, package require msgcat -> 1.6.0
on my syno, package require msgcat ->  can't find package msgcat

**Comment by biloucat** [comment]
@eelcohn 
for msgcat, i think that you must add the link /usr/local/lib/tcl8 -> /var/packages/tcl//target/lib/tcl8
other remark:
on my syno:
puts $auto_path give:
/usr/local/lib/tcl8.6 /usr/local/lib /home/synology/tcl/spksrc/spk/tcl/work-cedarview-5.2/install/usr/local/tcl/lib
    the last path is bad 
on my archlinux:
puts $auto_path give /usr/lib/tcl8.6 /usr/lib

**Comment by biloucat** [comment]
@eelcohn 
see https://www.tcl.tk/man/tcl/TclCmd/tclvars.htm#M4 and
   https://www.tcl.tk/man/tcl/TclCmd/tclvars.htm#M23
on my syno: puts $tcl_pkgPath give:
         /home/synology/tcl/spksrc/spk/tcl/work-cedarview-5.2/install/usr/local/tcl/lib 
on my archlinux: puts $tcl_pkgPath give: 
        /usr/lib

**Comment by biloucat** [comment]
@eelcohn 
in /var/packages/tcl/target/lib/:
libtcl.so -> /home/synology/tcl/spksrc/spk/tcl/work-cedarview-5.2/install/usr/local/tcl/lib/libtcl8.6.so is bad and perhaps useless in /var/packages/tcl/target/lib/ as there is one in /usr/local/lib
so, in cross/tcl
remove:
   POST_INSTALL_TARGET = myPostInstall
   .PHONY: myPostInstall
   myPostInstall:
	# Let's create a symlink so that any other packages which are compiled by spksrc will link to a library without a version number in the filename
	ln -s $(STAGING_INSTALL_PREFIX)/lib/libtcl8.6.so $(STAGING_INSTALL_PREFIX)/lib/libtcl.so

if a link is useful, i think it can created in installer.sh and 

PACKAGE_DIR="/var/packages/${PACKAGE}/target/" could/must be PACKAGE_DIR="/var/packages/${PACKAGE}/target" in the installer.sh

For the bad  $tcl_pkgPath:
add a directory patches in cross/tcl and put configure.patch in
[configure.patch.txt](https://github.com/SynoCommunity/spksrc/files/539500/configure.patch.txt)

**Comment by eelcohn** [comment]
@biloucat : thanks for the info, I'll take a look at it soon, probably this weekend.

**Comment by biloucat** [comment]
@eelcohn : for sqlite
in syno:
"package require sqlite3" give "can't find package sqlite3"
After "ln -s /var/packages/tcl/target/lib/sqlite3.13.0 /usr/local/lib/sqlite3.13.0"
"package require sqlite3" give "3.13.0"

**Comment by biloucat** [comment]
@eelcohn 
first remark:
 if i put 
  +TCL_PACKAGE_PATH="/var/packages/tcl/target/lib"
in configure.patch, then the link  "/usr/local/lib/sqlite3.13.0" is useless but not the links  
"/usr/local/lib/tcl8" and "/usr/local/lib/tcl8.6" : too bad !

second remark:
"package require tdbc::postgres" give me "couldn't load file "libpq.so.5": libpq.so.5: cannot open shared object file: No such file or directory"
 however, libpq.so.5 is in /usr/lib BUT IT IS a 32bit version !!!
   I do not know what to do !

third remark:
i found that the value of $(STAGING_INSTALL_PREFIX) is  present, on the syno, in the files
bin/tclsh8.6 lib/tdbc1.0.4/tdbcConfig.sh lib/libtcl8.6.so lib/itcl4.0.5/itclConfig.sh lib/itcl4.0.5/libitcl4.0.5.so lib/pkgconfig/tcl.pc and lib/tclConfig.sh
  
I do not know what to do to avoid it and I'm a bit tired !

**Comment by eelcohn** [comment]
Hi,

I've been kinda busy lately so it took me a while to implement all the changes. I've been digging into the path variables you've mentioned before. Unfortunately Tcl sets some of the path variables directly into the binary files, which is IMO a really bad thing to do. Tcl should set all these variables in a config file, or let the user supply them as a command line option.

I did however manage to create a package which works for me. I've updated the tclConfig.sh with the correct paths and added more symlinks to /usr/local/lib (this is not a really clean way IMO, but as I said before, Tcl should not set variables in it's binary files. Maybe I'll contact them and bring this to their attention).

@biloucat : can you once again test the new package? You can find it (temporarily) at https://github.com/eelcohn/synotcl/blob/master/tcl_cedarview-5.2_8.6.6-4.spk

Please check once again if you can:
- Upgrade the package correctly
- See if the functionality you require works correctly

These are the tests I've done myself:
```
$ tclsh
% clock scan 1752-09-02 -format %Y-%m-%d -locale en_US
-6857309972
% package require sqlite3
3.13.0
% package require tdbc::postgres
1.0.4
% 
```
Seems like it's working now :)

**Comment by biloucat** [comment]
@eelcohn :
i reinstalled version 8.6.6-1 and then updated to 8.6.6-4, that is ok but i still see Version 8.6.6-1 in Package Center.
-----------------------------------------------------------------------------------------------------------------
$tcl_pkgPath and therefore $auto_path are still bad:
  "/home/synology/tcl/spksrc/spk/tcl/work-cedarview-5.2/install/usr/local/tcl/lib"  and
  "/usr/local/lib/tcl8.6 /usr/local/lib /home/synology/tcl/spksrc/spk/tcl/work-cedarview-5.2/install/usr/local/tcl/lib"
Have you installed the patch configure.patch ?
---------------------------------------------------------------------------------------------------------------------
 "package require tdbc::postgres" still give me:
"couldn't load file "libpq.so.5": libpq.so.5: cannot open shared object file: No such file or directory"

If i put /usr/lib/libps.so.5.6 on my archlinux, "file libps.so.5.6" give me: 
"libpq.so.5.6: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, stripped"
Could-you tell me what you get with DSM6 ?
how build a package in 32 bits ?
---------------------------------------------------------------------------------------------------------------------------
"package require tdbc::mysql" give me:
"couldn't load file "libmysql_server_init.so.15": libmysql_server_init.so.15: cannot open shared object file: No such file or directory"
But perhaps because MariaDb is not installed on my syno ?

**Comment by biloucat** [comment]
@eelcohn @eelcohn
 i reinstalled version 8.6.6-1 and then updated to 8.6.6-4, that is ok but i still see Version 8.6.6-1 in Package Center.

-----------------------------------------------------------------------------------------------------------------
$tcl_pkgPath and therefore $auto_path are still bad:
  "/home/synology/tcl/spksrc/spk/tcl/work-cedarview-5.2/install/usr/local/tcl/lib"  and
  "/usr/local/lib/tcl8.6 /usr/local/lib /home/synology/tcl/spksrc/spk/tcl/work-cedarview-5.2/install/usr/local/tcl/lib"
Have you installed the patch configure.patch ?

---------------------------------------------------------------------------------------------------------------------
 "package require tdbc::postgres" still give me:
"couldn't load file "libpq.so.5": libpq.so.5: cannot open shared object file: No such file or directory"

If i put /usr/lib/libps.so.5.6 on my archlinux, "file libps.so.5.6" give me: 
"libpq.so.5.6: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, stripped"
Could-you tell me what you get with DSM6 ?
how build a package in 32 bits ?

---------------------------------------------------------------------------------------------------------------------------
"package require tdbc::mysql" give me:
"couldn't load file "libmysql_server_init.so.15": libmysql_server_init.so.15: cannot open shared object file: No such file or directory"
But perhaps because MariaDb is not installed on my syno !?

**Comment by biloucat** [comment]
@eelcohn:
 After a while, Version 8.6.6-4 appeared  in Package Center.

**Comment by eelcohn** [comment]
What I thought would be a relatively quick development of a Tcl package for SynoCommunity turns out to be quite a difficult journey........ :-|

I'll soon push a Tcl 8.6.6-5 package with a correctly implementation of the patch supplied by biloucat. This still leaves some open issues, but at this point I'm kinda running out of options. This new package will address most of the issues mentioned above though.

@biloucat:
- These packages have not been published in the SynoCommunity repository yet. They're beta testing packages, that could be a reason why the correct version number might not show up in the Package Center.
- The errors you experience might come from the fact that every single Tcl module has a seperate configure file. This means that all these configure files may have to be patched. If you have time, can you look into this?

**Comment by eelcohn** [comment]
Finally! I think I've figured out where all the error messages come from.

I've found a way to cross-compile Tcl with the correct values for $auto_path and $tcl_pkgPath. The idea is to do the `make` with --prefix=/var/packages/tcl/target, and `make install` with --prefix={local path on compiler machine}. This way the executables and libraries are compiled with the correct values.

The errors we get from `package require tdbc::mysql / tdbc::odbc / tdbc::postgres` are most likely caused by the fact that Tcl needs both the header and library files from mysql/odbc/postgres when these modules are compiled.

When you look at the file `tcl8.6.6/pkgs/tdbcmysql1.0.4/README` it states that:
```
In addition to the options described there, the 'configure' script for tdbcmysql
accepts the following two options:

    --with-mysql-includedir=PATH

        Specifies PATH as the path to the directory that contains
        'mysql.h' and related header files.

    --with-mysql-libdir=PATH

        Specifies PATH as the path to the directory that contains
        the MySQL link libraries.
```
and the file `tcl8.6.6/pkgs/tdbcpostgres1.0.4/README` states that:
```
Prior to running 'configure', you should ensure that the directory that contains
the Postgres executables (specifically, pg_config) is on the PATH. pg_config, in turn,
will locate the necessary #include files and libraries to build the module.
```
My guess is that Tcl needs these header and library files to make them work. They're not included in spksrc yet, so Tcl cannot cross-compile against them. Until these packages are part of spksrc I cannot get them to work in Tcl.

In the mean time I'll release v8.6.6-6 which has all the correct $auto_path and $tcl_pkgPath settings.

**Comment by eelcohn** [comment]
Just pushed v8.6.6-6 to the spksrc tree. These are the checks I've done for this package:
```
$ tclsh
% clock scan 1752-09-02 -format %Y-%m-%d -locale en_US
-6857309972
% puts $tcl_pkgPath
/var/packages/tcl/target/lib
% puts $auto_path
/var/packages/tcl/target/lib/tcl8.6 /var/packages/tcl/target/lib /usr/local/lib
$ package require itcl
4.0.5
% package require sqlite3
3.13.0
% package require tdbc
1.0.4
% package require tdbc::mysql
couldn't load file "libmysql_server_init.so.15": libmysql_server_init.so.15: cannot open shared object file: No such file or directory
% package require tdbc::odbc
couldn't load file "libodbc.so": libodbc.so: cannot open shared object file: No such file or directory
% package require tdbc::postgres
couldn't load file "libpq.so.5": libpq.so.5: cannot open shared object file: No such file or directory
% package require sqlite3
3.13.0
% package require Thread
2.8.0
% 
```
There are known issues with mysql, odbc and postgres packges, see the post above.

**Comment by eelcohn** [comment]
I've checked the mysql, odbc and postgres issues: I can confirm that they occur because no mysql, odbc or postgres package is installed on the DiskStation. It has nothing to do with the compilation or the package. If you want these options, you need to add the mysql, odbc and/or postgres packages to the SynoCommunity.
