### ISSUE TITLE
uMurmur not working with Mumble Client 1.2.17 anymore

### ISSUE THREAD

**Issue by nuker1** [SynoCommunity/spksrc#2482]
Hi,

I set up the uMurmur Server on my DS216j and it was working fine until the new Version 1.2.17 of the Mumble Client was released. Since then i can still connect to the Server from inside my LAN, but other persons who connected serval times before from the outside can't connect anymore.
Will there be an update? Is there something i can do?

thanks

**Comment by KaraokeStu** [comment]
Hi, to be honest on this - you'd need to check what the latest version of uMurmur Server source code is and we can look to re-base the code to point to that version

**Comment by nuker1** [comment]
Sorry, I'm not sure what you mean.
But I tried to downgrade the client and also used the Android app - but I 
can not connect, except via LAN.


Am 12. Oktober 2016 3:43:35 PM schrieb Stuart Duncan 
<notifications@github.com>:

**Comment by KaraokeStu** [comment]
This sounds like an issue accessing the ports from the outside - how do you have the ports mapped? Statically or via UPnP?

**Comment by nuker1** [comment]
Static. UPnP somehow never works.


Am 13. Oktober 2016 10:41:10 AM schrieb Stuart Duncan 
<notifications@github.com>:

**Comment by m4tt075** [comment]
DSM6-compatible test packages are available [here](https://github.com/m4tt075/spksrc/releases/tag/umu-0.2.17) now. Please test and report back.

**Comment by ymartin59** [comment]
uMurmur update has been published. Please report any trouble in new issue
