### ISSUE TITLE
[Package Request] Music Player Daemon (MPD)

### ISSUE THREAD

**Issue by clauseggers** [SynoCommunity/spksrc#2484]
Name: Music Player Daemon (MPD)
Description: Server-side network controlled music player daemon.
Website: https://www.musicpd.org
Software documentation: https://www.musicpd.org/doc/user/
Build/Installation documentation: https://www.musicpd.org/doc/user/install_source.html
Source code: http://git.musicpd.org/cgit/master/mpd.git/ alt. mirror https://github.com/MaxKellermann/MPD 
License: GNU General Public License

**Comment by vkostas** [comment]
FYI, I am currently working on an amended version of MPD.

**Comment by hgy59** [comment]
@vkostas are you still working on this?
@Safihre is about to remove the cross/mpd with #3173

**Comment by vkostas** [comment]
@hgy59  I had stopped like one year ago (still have the packages) due to many unsolved dependencies + DSM 6 user issue (haven't checked yet if definitely solved). Added a msg to #3173.

**Comment by hgy59** [comment]
initial mpd package released on 2022-06-06
