### ISSUE TITLE
Cannot add SynoCommunity as Package source

### ISSUE THREAD

**Issue by ced034** [SynoCommunity/spksrc#2485]
SynoCommunity Repository

DS415+
INTEL Atom C2538
DSM 6.0.2-8451 Update 2

Trying to add the repo for SynoCommunity

Gives error "Invalid location"

### Steps to reproduce
Try to add http://packages.synocommunity.com/ to Package Sources

**Comment by piwi82** [comment]
Have you read the _Easy install_ ?
https://synocommunity.com/#easy-install

**Comment by ced034** [comment]
I have, it was previously added but nothing would show up under the community tab, so I removed the source and can't add it again.

![capture](https://cloud.githubusercontent.com/assets/22746940/19240552/35547b82-8f0b-11e6-83dc-6c8ef7f8f8df.JPG)

**Comment by cytec** [comment]
@piwi82 shouldn't it be https://* ?

**Comment by ced034** [comment]
Have tried both, actually copy and pasted from the easy install guide.

**Comment by piwi82** [comment]
@cytec Both work.
@ced034 Check your IP config (gateway) and your DNS servers.

**Comment by ced034** [comment]
I have checked everything and reset router, still the same problem. Tried to add some other random sources and some worked, some didn't. I can install any official Synology package no problem.

Maybe it has something to do with the newest DSM? DSM 6.0.2-8451 Update 2 came out on the 5th.

**Comment by piwi82** [comment]
Everything is fine accessing the repository (and installing packages) with DSM 6.0.2-8451u2 on my DS411+II, so this is not a problem with the last update.
If SynoCommunity repository was having problems, there would be a ton of other users having the same issue.

**Comment by Diaoul** [comment]
Check your "Certificate" tab to see if it is not revoked or something.

**Comment by ced034** [comment]
Ok I checked on my other Diskstations and same problem with DS411+ and DS412+

So this must then be a problem with my internet connection? Maybe my ISP did something weird.

Certificate not revoked, all looks OK on that side, thanks for the help everyone.

**Comment by ced034** [comment]
Tried on a Diskstation at work with a totally different ISP, same problem :(

Maybe it's a South African thing?

**Comment by ced034** [comment]
OK so did a full factory reset on one of my spare Diskstations and I can add the source no problem. The other ones still have the same error.

**Comment by KaraokeStu** [comment]
Closed as this seems to be an ISP-specific issue

**Comment by Diaoul** [comment]
@ced034 : maybe try to contact Synology on the issue. DS415+ is a supported model and it's working for other people so we cannot be of any help I'm afraid.

**Comment by Hafer0** [comment]
Have the same issue twice. DS415+ and DS114, both DSM 6.1-15047-2 Update 2 on different ISPs. 
So probably not ISP specific
