### ISSUE TITLE
Newznab Package

### ISSUE THREAD

**Issue by G1zm0** [SynoCommunity/spksrc#249]
This is related to [#227](https://github.com/SynoCommunity/spksrc/issues/227#issuecomment-8543626), to keep a log.
And ask for help if needed.

Step 1 to install is setting al [Prerequisites](http://newznab.readthedocs.org/en/latest/install/#prerequisites)
- Enable php and webstation in DSM.
- Do NOT enable register_globals
- add :/opt/share/pear to php open_basedir
- ipkg install php-curl
- ipkg install php-pear
- edit php.ini 
1. (set max php memory limit to 256), won't know if this will work.
2. add pear to openbase_dir (include_path = ".:/php/includes:/opt/share/pear")

[Result:](https://dl.dropbox.com/u/16935152/newsnab/step1.png)

**Comment by Dr-Bean** [comment]
Fyi, I plan on retiring the `newznab` package due to lack of upstream development. See https://github.com/SynoCommunity/spksrc/issues/2256.

**Comment by Dr-Bean** [comment]
As there were no objections to my previous comment, closing and locking to prevent further comments.
