### ISSUE TITLE
No "Owncloud" package in DS216play - DSM 6.0.2-8451 Update 2 

### ISSUE THREAD

**Issue by cavemaster** [SynoCommunity/spksrc#2493]
Hello,

I added "http://packages.synocommunity.com" to my packet list.
Unfortunatly Owncloud is missing even if it is listed here:

https://synocommunity.com/package/owncloud

Do you know what I'm doing wrong?
Thanks in advance.

Thomas

![owncloud](https://cloud.githubusercontent.com/assets/22890627/19442612/34cfde5c-948a-11e6-8648-0ad0540c1542.PNG)

**Comment by piwi82** [comment]
_Alle_ doesn't display community packages, select _Community_ to see the ownCloud package.

**Comment by cavemaster** [comment]
Ah that make sense: "alle" doesn't mean "alle".
Thanks for your help I got it.
