### ISSUE TITLE
[Package Request]Squash TM 1.14

### ISSUE THREAD

**Issue by pmassu** [SynoCommunity/spksrc#2499]
Hello,

Would it be possible to have a package for Squash TM software (http://www.squashtest.org/telechargements/category/13-version-stable-tm?lang=fr) version 1.14

I'm using a NAS DS215J which is up to date (DSM 6.0.2-8451 Update 2).

Regards.

**Comment by Dr-Bean** [comment]
See https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#package-requests. Fill out the [Package Request template](https://github.com/SynoCommunity/spksrc/issues/new?title=%5BPackage%20Request%5D%20&body=Name%3A%0ADescription%3A%0AWebsite%3A%0ASoftware%20documentation%3A%0ABuild%2FInstallation%20documentation%3A%0ASource%20Code%3A%0ALicense%3A) please.

**Comment by cytec** [comment]
no need to make a new issue just edit it here...
anyway since you made a new one over here: https://github.com/SynoCommunity/spksrc/issues/2524 im gonna close this one
