### ISSUE TITLE
Boost broken (?) for arm, marvel archs

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2513]
Boost seems "broken" for marvel and arm (I didn't test all archs 'cos it takes ages).
In fact I was trying to upgrade Boost and Glib without success until I noticed the behavior is rather the same with current spksrc version.

### Setup
_Package Name:_ Boost
_Package Version:_ 1.59.0

_NAS Model:_
_NAS Architecture:_88f6281, alpine
_DSM version:_5.2

### Expected behavior
Boost should be cross-compile 88f6281 and alpine.

### Actual behavior
Error: "platform not supported".

### Steps to reproduce
_1._Clone git spksrc (master branch)
_2._Cross compile boost

#### Other logs
gcc.compile.c++ bin.v2/libs/context/build/gcc-4.6.4/release/threading-multi/unsupported.o
libs/context/src/unsupported.cpp:7:2: error: #error "platform not supported"

    "/home/debian/Synology/spksrc-syno/toolchains/syno-88f6281-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-g++"  -ftemplate-depth-128 -I/home/debian/Synology/spksrc-syno/toolchains/syno-88f6281-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -I/home/debian/Synology/spksrc-syno/cross/boost/work-88f6281-5.2/install//usr/local/include  -O3 -finline-functions -Wno-inline -Wall -pthread -fPIC  -DBOOST_ALL_NO_LIB=1 -DBOOST_CHRONO_DYN_LINK=1 -DBOOST_CONTEXT_DYN_LINK=1 -DBOOST_CONTEXT_SOURCE -DBOOST_DISABLE_ASSERTS -DBOOST_SYSTEM_DYN_LINK=1 -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_THREAD_BUILD_DLL=1 -DBOOST_THREAD_POSIX -DBOOST_THREAD_USE_DLL=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/context/build/gcc-4.6.4/release/threading-multi/unsupported.o" "libs/context/src/unsupported.cpp"

...failed gcc.compile.c++ bin.v2/libs/context/build/gcc-4.6.4/release/threading-multi/unsupported.o...
...skipped <pbin.v2/libs/context/build/gcc-4.6.4/release/threading-multi>libboost_context.so.1.59.0 for lack of <pbin.v2/libs/context/build/gcc-4.6.4/release/threading-multi>unsupported.o...
...skipped <pstage/lib>libboost_context.so.1.59.0 for lack of <pbin.v2/libs/context/build/gcc-4.6.4/release/threading-multi>libboost_context.so.1.59.0...
...skipped <pstage/lib>libboost_context.so for lack of <pstage/lib>libboost_context.so.1.59.0...
...skipped <pbin.v2/libs/coroutine/build/gcc-4.6.4/release/threading-multi>libboost_coroutine.so.1.59.0 for lack of <pbin.v2/libs/context/build/gcc-4.6.4/release/threading-multi>libboost_context.so.1.59.0...
...skipped <pstage/lib>libboost_coroutine.so.1.59.0 for lack of <pbin.v2/libs/coroutine/build/gcc-4.6.4/release/threading-multi>libboost_coroutine.so.1.59.0...
...skipped <pstage/lib>libboost_coroutine.so for lack of <pstage/lib>libboost_coroutine.so.1.59.0...
gcc.compile.c++ bin.v2/libs/context/build/gcc-4.6.4/release/link-static/threading-multi/unsupported.o
libs/context/src/unsupported.cpp:7:2: error: #error "platform not supported"

    "/home/debian/Synology/spksrc-syno/toolchains/syno-88f6281-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-g++"  -ftemplate-depth-128 -I/home/debian/Synology/spksrc-syno/toolchains/syno-88f6281-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -I/home/debian/Synology/spksrc-syno/cross/boost/work-88f6281-5.2/install//usr/local/include  -O3 -finline-functions -Wno-inline -Wall -pthread  -DBOOST_ALL_NO_LIB=1 -DBOOST_CHRONO_STATIC_LINK=1 -DBOOST_CONTEXT_SOURCE -DBOOST_DISABLE_ASSERTS -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SYSTEM_STATIC_LINK=1 -DBOOST_THREAD_BUILD_LIB=1 -DBOOST_THREAD_POSIX -DBOOST_THREAD_USE_LIB=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/context/build/gcc-4.6.4/release/link-static/threading-multi/unsupported.o" "libs/context/src/unsupported.cpp"

...failed gcc.compile.c++ bin.v2/libs/context/build/gcc-4.6.4/release/link-static/threading-multi/unsupported.o...
...skipped <pbin.v2/libs/context/build/gcc-4.6.4/release/link-static/threading-multi>libboost_context.a(clean) for lack of <pbin.v2/libs/context/build/gcc-4.6.4/release/link-static/threading-multi>unsupported.o...
...skipped <pbin.v2/libs/context/build/gcc-4.6.4/release/link-static/threading-multi>libboost_context.a for lack of <pbin.v2/libs/context/build/gcc-4.6.4/release/link-static/threading-multi>unsupported.o...
...skipped <pstage/lib>libboost_context.a for lack of <pbin.v2/libs/context/build/gcc-4.6.4/release/link-static/threading-multi>libboost_context.a...
...failed updating 2 targets...
...skipped 9 targets...
Makefile:44: recipe for target 'myCompile' failed
make[1]: *** [myCompile] Error 1
make[1]: Leaving directory '/home/debian/Synology/spksrc-syno/cross/boost'
../../mk/spksrc.cross-cc.mk:122: recipe for target 'arch-88f6281' failed
make: [arch-88f6281] Error 2 (ignored)

**Comment by GoodOmens83** [comment]
Are you compiling python separately?  You need to.

From the spksrc folder
`cd native/python`
`make clean && make`

**Comment by vkostas** [comment]
Yes, I compile first native/python then native/glib and then cross/boost.
Can someone try to compile boost so at least I know it is my virtual os (Debian 64bit Jessie 8.6 stable) and not spksrc itself.

**Comment by Dr-Bean** [comment]
I was sure I had answered a similar question from you in the past, and indeed I have: https://github.com/SynoCommunity/spksrc/issues/2064#issuecomment-169944967 ;)

It is expected that boost does not compile succesfully when compiled on its own, for probably the majority of arches. 
Not all the [libraries](http://www.boost.org/doc/libs/) in boost will be supported by any particular arch. That is one of the reasons for this comment: https://github.com/SynoCommunity/spksrc/blob/master/cross/boost/Makefile#L18. We initially aim to build all libraries included in Boost as it allows us to test a range of different libraries during testing, but that does result in errors like you're seeing for a number of arches.
Apart from testing new versions, there's no need to compile Boost on its own, so there's no issue there.

For _using_ Boost in other packages, we override `BOOST_LIBRARIES`, and set (just) the necessary libraries for a particular cross package in that Makefile. See https://github.com/SynoCommunity/spksrc/blob/master/cross/libtorrent/Makefile#L27 or https://github.com/SynoCommunity/spksrc/blob/master/cross/domoticz/Makefile#L20.
