### ISSUE TITLE
Newbie: SynoCommunity Headphones Query

### ISSUE THREAD

**Issue by GuyManning** [SynoCommunity/spksrc#2516]
Why does it not allow us to include LIVE albums for an artists?
Sorry if this is the wrong place - i.e. for general queries

_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_
_Package Version:_

_NAS Model:_
_NAS Architecture:_
_DSM version:_

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by cytec** [comment]
we only provide an SPK for Headphones, any feature requests/issues regarding the software itself should be reported/requestd upstream. check: https://github.com/rembo10/headphones or if you use the custom SPK use the url of that fork
