### ISSUE TITLE
Transmission

### ISSUE THREAD

**Issue by KeizerSauze** [SynoCommunity/spksrc#2517]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Transmission
_Package Version:_2.92-12

_NAS Model:DS916+
_NAS Architecture:_
_DSM version:_6.0.2-8451 Update 2

### Expected behavior
Transmission should run

### Actual behavior
I have a pop that said run was not possible

### Steps to reproduce
_1._Launch Transmission
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
No logInsert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by cytec** [comment]
see https://github.com/SynoCommunity/spksrc/issues/2434 or https://github.com/SynoCommunity/spksrc/issues/2355
