### ISSUE TITLE
[Package Request] lsof

### ISSUE THREAD

**Issue by junkb** [SynoCommunity/spksrc#2519]
Name: lsof
Description: lsof  lists on its standard output file information about files opened by processes

Website: https://people.freebsd.org/~abe/
Software documentation: provided in source distribution
Build/Installation documentation: provided in source distribution
Source Code: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof
License: bsd license-compatible [ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ]

**Comment by KaraokeStu** [comment]
You can get this easily by bootstrapping your synology and installing via ipkg. I'm not sure what use this would be without bootstrapping for other commands

**Comment by junkb** [comment]
lsof is a fundamentally useful tool, regardless of what other programs might or might not be available.  it would be nice if it were available as a "native" package, without the bootstrapping/ipkg dependency

**Comment by cytec** [comment]
this might be something for the CLI Essentials im "planing" see: https://github.com/SynoCommunity/spksrc/issues/2261 feel free to leave a comment there too ;)

**Comment by junkb** [comment]
thanks, i'll do that

**Comment by publicarray** [comment]
Closing as `lsof` is part of busybox which is included in the `synocli-monitor` package
