### ISSUE TITLE
COPS/BicBucStriim Install

### ISSUE THREAD

**Issue by p2635** [SynoCommunity/spksrc#2520]
Hi guys,

This is a general install issue, I've recently bought a synology ds216j and so I'm not very experienced. I want to set up a way to access my ebooks hence the above subject line.

So I added the source for SynoCommunity successfully, went through the install wizard for COPS and BicBucStriim but when I try to run them it just brings me to a page with the Synology logo and says beneath it 'The page cannot be found'. Not sure what I'm doing wrong.

Phil

**Comment by cytec** [comment]
please fill out the Issue template so package maintainers know something more about your device. I'm guessing you run DSM 6 so it may be because of that: https://github.com/SynoCommunity/spksrc/issues/2216

**Comment by p2635** [comment]
Sorry about that, I was in a rush to log it.

_For new Package Requests, see the guidelines_  

### Setup
_Package Name:BicBucStriim, COPS
_Package Version:1.3.6-5, 1.0.RC2-3

_NAS Model:_Synology DS216j
_NAS Architecture:_Not sure
_DSM version:_DSM 6.0.2-8451 Update 3

### Expected behavior
Not sure, it's the first time I installed these packages

### Actual behavior
When I try to run them it just brings me to a page with the Synology logo and says beneath it 'The page cannot be found'

### Steps to reproduce
_1._Install packages as normal
_2._Run packages as normal
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
No data in either of the package logs
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```
Nothing interesting I can see, just successful package install confirmations.

**Comment by KaHooli** [comment]
I believe that the Web Station needs to be installed as per the notes at https://github.com/seblucas/cops/wiki/Howto---Synology , but I haven't got it to work yet either, keep getting another error with COPS, and BitBucStriim gives a 403 error.

**Comment by p2635** [comment]
Thanks Kahooli, this got me a step further and I got a new page to actually come up which is promising! I still am have problems, it looks like something to do with step 3 of that link you gave me.

The page says "Check if Calibre database file exists and is readable
File /volume1/homes/philipw/books/metadata.db not found, Please check "

But I can't do step 3 because I don't know where to find the file config_local.php

**Comment by Dr-Bean** [comment]
Cops 1.0.1-5 has been published on the repository as a beta package. 
You'll probably end up having to reinstall, as I don't think a package update can repair the situation you're in right now.

**Comment by p2635** [comment]
I'll just wait for the proper release, i'm in no rush

**Comment by Dr-Bean** [comment]
The final release won't have any changes wrt the issue you described though. If feedback is positive, this is the exact same package, just without the `beta` tag. 
Retroactively fixing the permissions issue is simply not feasible, especially with a reinstall being as easy as it is for Cops.

**Comment by mreid-tt** [comment]
We have received several requests to upgrade the BicBucStriim version in the repository. This task has been pending for a while due to the package not being updated for the latest DSM versions. A new release is currently in draft, featured as part of PR #5952. We welcome individuals who are interested in contributing to the testing and feedback process for the upcoming release. Early builds can be downloaded at [this link](https://github.com/SynoCommunity/spksrc/pull/5952/checks). Your assistance in testing and providing feedback would be greatly appreciated.
