### ISSUE TITLE
Please update Shairport-Sync to version 2.8.5

### ISSUE THREAD

**Issue by mbedarff** [SynoCommunity/spksrc#2529]
### Setup
_Package Name:_ Shairport-Sync
_Package Version:_ 2.3.11

_NAS Model:_
_NAS Architecture:_ DS212 Marvell Kirkwood ARMv5TE compliant
_DSM version:_ DSM 6.0.1-7393 Update 2

### Expected behavior
HTC introduced AirPlay streaming in its HTC Connect app. Thus I expected to stream music to my NAS via the Shairport-Sync package.

### Actual behavior
Wehn using my HTC 10 smartphone to stream music via the HTC Connect app the shairport-sync process is terminated on the NAS.

The reason is that the packet size is different to the hard coded one in player.c. Mike Brady fixed this with the release 2.4.8.5.

Please update the shairport-sync package to an newer version of Mike's shairport-sync.

Thank you a lot in advance!

#### Other logs
shairport-sync verbose output:
> admin@DiskStation:~$ sudo /usr/local/shairport-sync/bin/shairport-sync -v -c /usr/local/shairport-sync/var/shairport-sync.conf
> Looking for the configuration file "/usr/local/shairport-sync/var/shairport-sync.conf".
> startup
> sending announce for _raop._tcp.local.
> 
> data from=192.168.0.30 size=313
> 
> (no questions in packet)
> 
> 
> data from=192.168.0.193 size=77
> 
> flags = 0000, qn = 1, ans = 1, add = 0
> 
> qn #0: type PTR (0c) _raop._tcp.local. -
> added 1 answers
> 
> 
> 
> data from=192.168.0.30 size=262
> 
> (no questions in packet)
> 
> 
> data from=192.168.0.193 size=77
> 
> flags = 0000, qn = 1, ans = 1, add = 0
> 
> qn #0: type PTR (0c) _raop._tcp.local. -
> added 1 answers
> 
> 
> 
> data from=192.168.0.30 size=262
> 
> (no questions in packet)
> 
> 
> data from=192.168.0.21 size=321
> 
> (no questions in packet)
> 
> 
> new RTSP connection.
> Play connection from user agent "iTunes/10.6 (Macintosh; Intel Mac OS X 10.7.3) AppleWebKit/535.18.5".
> Active-Remote string seen: "1986535575".
> Connection from IPv4: 192.168.0.193:42675
> unrecognised parameter: "progress: 10000/10000/10000" (27)
> 
> shairport-sync: player.c:247: alac_decode: Assertion `outsize == (4 * frame_size)' failed.
> Aborted

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #3040.
