### ISSUE TITLE
[Framework] Enhance steps "Correcting pkg-config/libtool file"

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2532]
I faced cases when libtool file came with $(INSTALL_DIR) joined twice (/home/../spksrc/cross/<cross_pkg>/install/home/.../spksrc/cross/<cross_pkg>/install/...) which couldn't be fixed by only adapting Makefile.
I normalized the such path cases with two new lines (one for PKG and one for .la files)
> **include mk/spksrc.install.mk**
...
install_correct_lib_files: $(INSTALL_PLIST)
	@for pc_file in `grep -e "^lib/pkgconfig/.*\.pc$$" $(INSTALL_PLIST)` ; \
	do \
	  $(MSG) "Correcting pkg-config file $${pc_file}" ; \
	  sed -i -e 's#\($(INSTALL_PREFIX)\)#$(INSTALL_DIR)\1#g' \
+++	         -e 's#\($(INSTALL_DIR)\)\1#\1#g' \
	         -e 's#$$(libdir)#$${libdir}#g' $(INSTALL_DIR)/$(INSTALL_PREFIX)/$${pc_file} ; \
	done
	@for la_file in `grep -e "^lib/.*\.la$$" $(INSTALL_PLIST)` ; \
	do \
	  $(MSG) "Correcting libtool file $${la_file}" ; \
	  perl -p -i -e 's#(?<!\Q$(INSTALL_DIR)\E/)$(INSTALL_PREFIX)#$(INSTALL_DIR)/$(INSTALL_PREFIX)#g' $(INSTALL_DIR)/$(INSTALL_PREFIX)/$${la_file} ; \
+++	  sed -i -e 's#\($(INSTALL_DIR)\)\1#\1#g' $(INSTALL_DIR)/$(INSTALL_PREFIX)/$${la_file} ; \
	done
>

Comments are welcome. I have included this change into my current project but if it can be done with a separate pull request.

**Comment by Dr-Bean** [comment]
Generally, this should be fixable by setting/correcting the prefix or DESTDIR (wording depends on the software, could be something else entirely). Have you verified that this is not the case with the project you're setting up?

**Comment by vkostas** [comment]
I was pointing the **dependency_libs** mainly in **.la** "installed" libraries. A considerable part of existing syno cross packages includes the double path. Check **libvorbisenc.la** lib of **libvorbis** package f.e.
>dependency_libs=' -L/home/../spksrc/toolchains/syno-88f6281-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/lib -L/home/../spksrc/cross/libvorbis/work-88f6281-5.2/install//usr/local/lib /home/../spksrc/cross/libvorbis/work-88f6281-5.2/install//usr/local/lib/libvorbis.la -L/home/debian/Synology/arches/cross/libvorbis/work-88f6281-5.2/install/home/../spksrc/cross/libvorbis/work-88f6281-5.2/install//usr/local/lib -lm /home/../spksrc/cross/libvorbis/work-88f6281-5.2/install//usr/local/lib/libogg.la'
>
**libogg** has same behaviour.
One new dependent package with similar behaviour triggered my investigation (**libdir** was correct always) as the system failed to compile the upper package. I can find it if you think it is really necessary.

**Comment by Dr-Bean** [comment]
I see you're looking at the values after compiling the cross packages. Check the values after building the SPK, you should see the correct values then. That's why INSTALL_PREFIX is set in the SPKs Makefile.

**Comment by Dr-Bean** [comment]
@vkostas have you been able to verify that what I said works for you?

**Comment by vkostas** [comment]
@Dr-Bean Hi. Probably I was doing something wrong. I couldn't reproduce it again or at least it didn't complain again (**after make clean**).
