### ISSUE TITLE
Synology does not want to sleep nzbget

### ISSUE THREAD

**Issue by AirRailey** [SynoCommunity/spksrc#2537]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: nzbget 
_Package Version: 16.4.22

_NAS Model: Synology
_NAS Architecture: ds216play
_DSM version: 6.0.2-8451 Update 4

Hello everybody

Since I have installed nzbget on my synology ds216play, the ds does not sleep anymore! She's running 24/7!
Has anyone here advice?

greetz

**Comment by cytec** [comment]
you should report this upstream... also you should check if you have any settings that prevent sleeping in general (like automatically fetching of RSS feeds every 30 minutes)

**Comment by AirRailey** [comment]
i dont have rss fedds installed! check for nzb automatically is also off
