### ISSUE TITLE
rutorrent not seeing symlinks

### ISSUE THREAD

**Issue by slicepaperwords** [SynoCommunity/spksrc#2538]
### Setup
_Package Name:_ruTorrent
_Package Version:_3.7-8

_NAS Model:_RS816
_DSM version:_DSM 6.0.2-8451 Update 4

### Expected behavior
when setting download directory when starting torrent, it should recognize symlinks.

### Actual behavior
shows other directories, but not symlinks

### Steps to reproduce
_1._Don't know how

#### Package log
no data in logs

**Comment by Dr-Bean** [comment]
We only package the software. I have no idea if rutorrent supports symlinks the way you want to use them, so you would probably want to report this upstream. Before doing that, make sure it's not permissions related.
