### ISSUE TITLE
[Package Request] COPS Update

### ISSUE THREAD

**Issue by Manowar43** [SynoCommunity/spksrc#2541]
Name: COPS
Description: Calibre OPDS (and HTML) PHP Server
Website: http://blog.slucas.fr/en/oss/calibre-opds-php-server
Software documentation: https://github.com/seblucas/cops/wiki
Build/Installation documentation: https://github.com/seblucas/cops
Source Code: https://github.com/seblucas/cops
License: GPL https://github.com/seblucas/cops/blob/master/COPYING

The package has not been updated for a while. The community is still at version 1.0.0RC2-3 which has been released in 2014.
The latest version is 1.0.1 from oct. 2016.

**Comment by Dr-Bean** [comment]
I'll see if I can make the package more DSM6 compatible before publishing an update. Should help with #1937 and #2520 too.

**Comment by Manowar43** [comment]
That's great. Thank you very much.

**Comment by Dr-Bean** [comment]
Cops 1.0.1-5 has been published on the repository as a beta package.

**Comment by Manowar43** [comment]
Thanks a lot. I installed it and briefly tried it today and it seems to work well.

**Comment by Dr-Bean** [comment]
Thanks for the feedback :) Can you provide some details? It'll help a lot in deciding when we can release the package on the stable channel.

- What DSM version are you using?
- What is the path to your calibre database (just an indication is sufficient: `/volume1/calibre`, or nested on or more levels deeper, such as `/volume1/level1/level2`)? 
- Was this an upgrade or a clean install of the package?

**Comment by Manowar43** [comment]
> On 13 Dec 2016, at 21:18, Dr-Bean <notifications@github.com> wrote:
> 
> Thanks for the feedback :) Can you provide some details? It'll help a lot in deciding when we can release the package on the stable channel.
> 
> 	• What DSM version are you using?

I am using the latest DSM version (if I am not wrong) DSM 6.0.2-8451 Update 6 


> 	• What is the path to your calibre database (just an indication is sufficient: /volume1/calibre, or nested on or more levels deeper, such as /volume1/level1/level2)?


My calibre database can be found in /volume1/books (which is the path I added in’Web Station/PHP Settings/open_basedir)

Now I actually have a few libraries in Calibre. I had to add their paths in /web/cops/config_local.php

$config['calibre_directory'] = array ("Computers" => "/volume1/books/Computers/", 
"Astronomy" => "/volume1/books/Astronomy/);


> 	• Was this an upgrade or a clean install of the package?

It was an upgrade. I initially installed COPS a few years ago.(On DSM 5). If I remember well I simply followed the instructions from the wiki.
https://github.com/seblucas/cops/wiki/Howto---Synology <https://github.com/seblucas/cops/wiki/Howto---Synology>

I haven’t changed any settings or config files after updating to the latest beta.

I hope it helps.

**Comment by desolat** [comment]
Meanwhile COPS 1.1 has been released. Anyhow I can help to speed up an update of the COPS package?

**Comment by Manowar43** [comment]
Would it be possible to push COPS 1.1.2 on the repository ? Thanks.

**Comment by yche2990** [comment]
Could someone please update the COPS to the newest version 1.1.2. This is a really useful app for synology and I do hope an update to work. Thanks.

**Comment by riks5** [comment]
Could someone please update the COPS to the newest version 1.1.2. Cops is a very useful app for synology. Thanks alot.

**Comment by hgy59** [comment]
> Could someone please update the COPS to the newest version 1.1.2. Cops is a very useful app for synology. Thanks alot.

WIP in #5653
