### ISSUE TITLE
[SABnzbd] Request: Update SABnzbd to Version 1.1.1

### ISSUE THREAD

**Issue by krazun** [SynoCommunity/spksrc#2545]
Hello,

It would be very nice if the SABnzbd Package, which is Version v1.1.0-18 at the moment, could be updated to the new Version 1.1.1.

And thank you very much for making so many great software running on my synology nas ;)

Additional Question: Is it possible for me to Update the SABnzbd version by myself in an easy way, without working with spksrc and create a complete new package? Maybe only with copying the content of SABnzbd-1.1.1-src.tar.gz to the SABnzbd directory of the package on my nas or something similar?

thank you and greets,
krazun

**Comment by mrhedstrom** [comment]
+1

**Comment by KaraokeStu** [comment]
I'll get on this now

**Comment by krazun** [comment]
Thank you very much for your effort and the fast reaction !

**Comment by KaraokeStu** [comment]
Building for publishing now :)

**Comment by Dr-Bean** [comment]
I don't think we need [this warning](https://github.com/SynoCommunity/spksrc/blob/master/spk/sabnzbd/src/wizard/upgrade_uifile) anymore, right? Maybe something to remember for next update, @KaraokeStu?

**Comment by KaraokeStu** [comment]
Yup - you're right - I'll remove the warning as I think everyone has moved to 1.x by now!

**Comment by Dr-Bean** [comment]
Cool :) That'll make the changelog look slightly cleaner as well :)
