### ISSUE TITLE
Can't install any package due to unknown developper error

### ISSUE THREAD

**Issue by nlamirault** [SynoCommunity/spksrc#2548]
### Setup
_Package Name:_ ALL
_Package Version:_

_NAS Model:_ 212J
_NAS Architecture:_
_DSM version:_ 6.0

### Expected behavior
Tell us what should happen

### Actual behavior

I've added Syno community like that : 

Step 1
Log into your NAS as administrator and go to Main Menu → Package Center → Settings and set Trust Level to Synology Inc. and trusted publishers.

Step 2
In the Package Sources tab, click Add, type SynoCommunity as Name and http://packages.synocommunity.com/ as Location and then press OK to validate.

Step 3
Go back to the Package Center and enjoy SynoCommunity's packages in the Community tab.

Can't install any package. I've got this error for all installations : 

Failed to install "xxx". This package is published by an unknown publisher.

### Steps to reproduce
Install a package from Synocommunity.

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
==> /var/log/synopkg.log <==
2016/12/09 23:13:38	(system) trigger	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/htop/@SYNOPKG_DOWNLOAD_htop -C /volume1/@tmp/584B2C920 INFO --no-same-owner
2016/12/09 23:13:38	(system) trigger	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/htop/@SYNOPKG_DOWNLOAD_htop -C /volume1/@tmp/584B2C920 INFO --no-same-owner	ret=[0]
2016/12/09 23:13:38	(system) trigger	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/htop/@SYNOPKG_DOWNLOAD_htop -C /volume1/@tmp/584B2C920 conf --no-same-owner
/bin/tar: conf: Not found in archive
/bin/tar: Exiting with failure status due to previous errors
2016/12/09 23:13:38	(system) trigger	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/htop/@SYNOPKG_DOWNLOAD_htop -C /volume1/@tmp/584B2C920 conf --no-same-owner	ret=[2]
2016/12/09 23:13:38	(system) trigger	htop 1.0.1-1:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/htop/@SYNOPKG_DOWNLOAD_htop -C /volume1/@tmp/584B2C920 scripts/start-stop-status --no-same-owner --no-same-permissions
2016/12/09 23:13:39	(system) trigger	htop 1.0.1-1:

```

```
==> /var/log/messages <==
2016-12-09T23:13:44+01:00 DiskStation php: This package is signed by unknown developer.


```

**Comment by nlamirault** [comment]
After set the level to "Any  publisher", i can install packages.

**Comment by Dr-Bean** [comment]
It's not an issue on our end. Can you check that SynoCommunitys certificate is imported (Package Center>Settings>Certificate) and that the time is set correctly on the device (Control Panel>Regional Options)?
It could be an issue with reaching Synology's timeserver maybe, not sure if that's checked during package install or not.

**Comment by nlamirault** [comment]
Yes it is correctly imported. (in Package Center>Settings>Certificate).
Yes time is correctly set too. (using pool.ntp.org)

**Comment by interlynx** [comment]
I'm really new. Just bought the server DS216play. All the synology packages work fine but none of the packages here work. I tried about 5 different ones and a couple twice. They either fail to install (couch potato) or they do install but wont start (domoticz). Or one starts, but when you click the icon to use it, opens new window and says can't find the page (bicBucStriim). And MediaInfo installs, says it's running but doesn;t show up anywhere. Can't see anywhere to show\run the program. I've obviously done something wrong I just have no idea what. :-(

**Comment by cytec** [comment]
@interlynx mediainfo is a CLI app... so you'll have to ssh into your DS and use it from there, some packages can't be run correctly on DSM 6 due to changes synology made to the way user creation is handled... btw failed install and not running packages is a little off in this issue ;) you might create a new one or use the search and check if there already is one... for now: there are a lot of DSM 6 related issues see: https://github.com/SynoCommunity/spksrc/issues?q=is%3Aissue+is%3Aopen+label%3A%22dsm+6.0%22

**Comment by interlynx** [comment]
Thanks for the info. It was very helpful. Appreciate it!

**Comment by Safihre** [comment]
Closing due to age, also seems to be a system issue and not SynoCommunity issue.
