### ISSUE TITLE
Horde 5.1.0-2 does not have a digital signature

### ISSUE THREAD

**Issue by rteppp** [SynoCommunity/spksrc#2549]
Synology DS414
DSM 6.0.2-8451 Update 5

When you try to install the Horde get a message that
does not have a digital signature, you can not install...

**Comment by rteppp** [comment]
Sorry, typing error :-(
be **HORDE**, not Horse.

**Comment by Dr-Bean** [comment]
Huh. Guess we still have unsigned packages...then again, the Horde package hasn't been updated in a long time.

Signed now, try again please.

**Comment by Dr-Bean** [comment]
Btw, for DSM6, see https://github.com/SynoCommunity/spksrc/issues/2333. It probably won't work on that version of DSM.

**Comment by rteppp** [comment]
Thank you,
you're right.
Error on the root password. I have it Correctly (verified via phpMyAdmin),
but ...
--
tnx

Rtepp

2016-12-10 18:40 GMT+01:00 Dr-Bean <notifications@github.com>:
