### ISSUE TITLE
Bump Jackett to new version v0.7.797 to fix torrentday breaking

### ISSUE THREAD

**Issue by GazzaHazza** [SynoCommunity/spksrc#2559]
Can Jackett be bumped up a version?

I would attmept to do myself but not sure on the process... will read docs properly in the morning and see if i can get a dev env up and running and do myself.

Thanks

**Comment by Dr-Bean** [comment]
Not sure if you've discovered this by yourself, but you can update Jackett via Jackett's interface.
Every once in a while, we'll still want to release a package update to keep somewhat in sync, so feel free to continue with trying to package it yourself :)

**Comment by GazzaHazza** [comment]
I have not seen this... where in jackett do you do that? I will give that a try but i would also like to carry on with updating the packing in the SynoCommunity as you have to give back right? :)

**Comment by Dr-Bean** [comment]
Perfect :)
Doesn't you Jackett interface have something like an update button in the main interface, near the bottom?

**Comment by GazzaHazza** [comment]
Cant access at the moment, but when i get home i will try and see :) Thanks for the support! Hopefully will get the building/compiling down so i can stop bothering you!

**Comment by Dr-Bean** [comment]
No problem. Just checked, the button is actually called `Check for updates`. Can't miss it, it's bright orange ;)

**Comment by GazzaHazza** [comment]
Fingers crossed i will find it still then :P
