### ISSUE TITLE
Request: Soulseek client package

### ISSUE THREAD

**Issue by dries83** [SynoCommunity/spksrc#256]
Hi all,

Thanks for all the terrific work you have done! 

I am looking for an implementation of a Soulseek client in DSM, since the supply at Soulseek is much greater and of a better quality than emule.

I conducted some work myself, but since I am not a IT-expert I became stuck.

Therefore I wanted to request it as a package via you guys.

My efforts concentrated on two Soulseek clients:
- Nicotine+: it is written in Python. It is also available via Fedora and Debian distributions. Unfortunately I lack the skills and knowledge to transfer the program to DSM and make it install.
- Museek+: it is written in C++. I tried to use spksrc to compile and package it but I failed. Perhaps because Museek+ uses CMake. Even after installing the CMake package on my virtual Linux computer and following the instructions, I could not get to work it.

I am willing to help, but I am now stuck at what to do. Thanks in advance for considering to create a Soulseek client as package.

KR
##

**Comment by electricessence** [comment]
So what happened here?  There was a Museek+ package and it never worked, then disappeared. :(

**Comment by Diaoul** [comment]
What happened is that nobody tested the binaries and I cannot do it myself as I have no knowledge on Museek+.
