### ISSUE TITLE
Unable to download or update any packages

### ISSUE THREAD

**Issue by achandab** [SynoCommunity/spksrc#2561]
All packages - particulary Sonarr and GIT

_NAS Model:_DS415+
Architecture: avoton
_DSM version: DSM 6.0.2-8451 Update 6

### Expected behavior
Able to install or update apps

### Actual behavior
Files are downloading to 100% and then starting over from 0 in a loop. Downloads are extremely slow to reach 100%. I have tried download the packages in windows and can see it times out after it reaches a certain %. Different % each time. Tried with my home network and also hotspot so not network related. This started occurring about 5 days ago. Was installing and updating fine prior to then. Did update to the latest version since then however not sure if its DSM related because as previously mentioned cant even download packages on my windows desktop

### Steps to reproduce
Try to install or update Sonaar or GIT

#### Package log
This is the error received from the Synology support tech

2016-12-15T13:17:37+11:00 AhmedsMedia synoscgi_SYNO.Core.Package.Installation_1_install[6871]: pkgserver.cpp:607 Failed to curl perform, code=42, err=Error, url=http://packages.synocommunity.com/git/10/git.v10.f4458%5Bx86-braswell-bromolow-cedarview-avoton%5D.spk?build=8451&arch=avoton

```

```
Have tried removing and re-adding repository as a troublshooting step. Also tried changing DNS server but dont think its related due to the steps taken above.

**Comment by achandab** [comment]
Okay after about 10 attempts GIT finally managed to update. Leads me to believe there might be a possible issue with the hosting server? I am located in Australia, not sure if there is a mirror here? Sonaar still downloading really slowly and then going into a loop.

**Comment by Dr-Bean** [comment]
@Diaoul might be able to provide more info, we're still using Cloudflare afaik. No issues on https://www.cloudflarestatus.com though, and it's certainly not a general issue.

**Comment by Ashkaan** [comment]
![image](https://cloud.githubusercontent.com/assets/5667978/21290208/7298fb54-c466-11e6-9bd8-adacc8817555.png)
![image](https://cloud.githubusercontent.com/assets/5667978/21290211/8202e280-c466-11e6-9f3a-8694c38c1e1c.png)

**Comment by achandab** [comment]
Ashkaan i can still remove and re-add the repo. Maybe try removing the / at the end

**Comment by achandab** [comment]
Is there anyway to find the download link for one of the other packages such as Sonaar to see if i can download it on my Windows desktop and manually install?

**Comment by Ashkaan** [comment]
Why can't I add it.. so weird

**Comment by Dr-Bean** [comment]
Don't hijack someone elses issue please. Unrelated problems in a new issue. But before you do, check the FAQ:
https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#im-getting-invalid-location-when-trying-to-add-the-repository
https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#im-seeing-a-400-bad-request-the-browser-or-proxy-sent-a-request-that-this-server-could-not-understand

**Comment by achandab** [comment]
Any update on this? Still having the same issue a week later

**Comment by KaraokeStu** [comment]
Try using **https**://packages.synocommunity.com

**Comment by achandab** [comment]
Thanks, have already tired HTTPS and same issue. However i was eventually able to install Sonarr after about 30 retries, it just didnt tie out at the end but very slow. However this leads me back to my inital issue as to why i uninstalled Sonarr. When i try to update it within the app i get an error 


Message
Error occurred while executing task ApplicationUpdate: The operation has timed out.

Exception
System.Net.WebException: The operation has timed out.
  at System.Net.WebConnectionStream.Read (System.Byte[] buffer, Int32 offset, Int32 size) [0x00055] in /spksrc/native/mono/work-native/mono-3.10.0/mcs/class/System/System.Net/WebConnectionStream.cs:337 
  at System.Net.WebClient.DownloadFileCore (System.Uri address, System.String fileName, System.Object userToken) [0x00093] in /spksrc/native/mono/work-native/mono-3.10.0/mcs/class/System/System.Net/WebClient.cs:330 
  at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x00035] in /spksrc/native/mono/work-native/mono-3.10.0/mcs/class/System/System.Net/WebClient.cs:303 


Not sure if this is related to me updating and installing packages from Synocommunity. I take it the update files are located on the same server as the package?

**Comment by KaraokeStu** [comment]
The updates for within the actual Sonarr application come directly from github, so it has nothing to do with the SynoCommunity servers. This is leading me to think there may be an issue with the network configuration or network port on your NAS.

If you can SSH into your nas, please can you try the following commands:
```
wget https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
chmod a+rx speedtest.py
./speedtest.py

```

Then report back the speeds you get.
For example, my output is as follows:
```
Retrieving speedtest.net configuration...
Testing from Virgin Media (82.2.44.152)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Virgin Media (Manchester) [54.38 km]: 30.865 ms
Testing download speed................................................................................
Download: 97.10 Mbit/s
Testing upload speed...................................................................................................
.Upload: 5.85 Mbit/s

```

**Comment by achandab** [comment]
speed test below

Retrieving speedtest.net configuration...
Testing from Optus (114.74.105.39)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Telstra (Sydney) [55.91 km]: 15.283 ms
Testing download speed................................................................................
Download: 90.21 Mbit/s
Testing upload speed....................................................................................................
Upload: 32.67 Mbit/s

**Comment by achandab** [comment]
can i somehow ping the server hosting the update files to see if i get a response?

**Comment by KaraokeStu** [comment]
ok, so now I'm officially stumped! 👎 

The update servers are on github, so you could try to checkout the code (not run it, but it would test the fetching of updates)

`git checkout https://github.com/Sonarr/Sonarr.git`

**Comment by achandab** [comment]
thanks, sorry im a real Linux novice. How should i execute the command above?

**Comment by cytec** [comment]
well github sometimes takes it's time when checking out/cloning repos... sometimes even the DL takes a while... just try it again in a few minutes and if it still doesn't work open an issue on the sonarr issue tracker... im not really sure how their updater works :/

**Comment by achandab** [comment]
cheers Cytec, can you link me where i can raise the issue?

**Comment by cytec** [comment]
https://github.com/Sonarr/Sonarr/issues

**Comment by achandab** [comment]
thanks mate. Seems to have updated now, again after trying to update about 10 times. Strange. guess this can be close off for now.

**Comment by richierichman** [comment]
Hi I'm having the same issue and I am also in Australia. When I use a VPN and download the same file it downloads in minutes as opposed to hours. My DS416j takes forever to download the file and it keeps resetting back to 0%. Any help in how to fix this issue?
Cheers
Richard

**Comment by Dr-Bean** [comment]
Maybe a peering/connectivity issue between Optus/Telstra/your_ISP and Cloudflare. Especially since you don't have a problem via VPN. I don't think we can provide a solution...

**Comment by achandab** [comment]
Finally some confirmation, i thought i was going crazy :)

So its definitely an Australia thing then. That's fine Dr Bean just wanted clarification that it wasn't my setup. How can i test the connectivity between my ISP and cloudflare? When i check the status page it shows its fine.

**Comment by Dr-Bean** [comment]
I doubt that Cloudflares status page would mention a connectivity issue with an ISP.
You could try and contact your ISP, see if they know anything...although if my ISP is any indication, that probably won't help ;)

CF mentions a couple of things on their support pages, e.g.:
https://support.cloudflare.com/hc/en-us/articles/200169986-Which-CloudFlare-data-center-do-I-reach- to determine the CF site you're using, and
https://support.cloudflare.com/hc/en-us/articles/200167696-My-website-seems-slower-or-I-m-having-performance-issues-What-should-I-do-
Maybe that's a start?

**Comment by achandab** [comment]
Thanks DrBean i'll have a look 

Richie, just as a check who is your ISP? I'm with Optus and having this issue both on my home internet and when i tether from my mobile which is also Optus

**Comment by richierichman** [comment]
@achandab I'm with Optus too. So it looks like it might be an Optus issue as I have the same thing happen at work which also uses Optus as an ISP. :-(

**Comment by achandab** [comment]
hmm well its good news we seem to be determining the root cause. I'll try to find another ISP to confirm that is the issue and post back

**Comment by achandab** [comment]
Yep confirmed with optus. TPG downloads lightning fast. Now i guess what to do from here? Do i tell my ISP to check the connection to cloudflare? Would they even know what that is?

**Comment by achandab** [comment]
Okay just tested another pc at my brothers house who is also optus and he was very fast to. 

Any chance they have limited our speed to that certain server for any reason?

**Comment by richierichman** [comment]
I'm on optus via NBN, are you also on NBN may be an NBN issue. I don't have any other problems downloading. I will try re-booting my optus modem and see if it makes a difference.

**Comment by achandab** [comment]
could be right, i am nbn and my brother is cable

**Comment by richierichman** [comment]
Yeah so it might be an NBN issue rather than Optus it's self. I'll try and reboot when I get home and see if it helps.

**Comment by achandab** [comment]
rebooted and did not resolve it. I'll speak to optus today and see what they say

**Comment by achandab** [comment]
Optus NBN usueless, wont escalate call pass level 1 and say to check with the server

**Comment by achandab** [comment]
is there anyway i can download the packages for an offline install rather than through the NAS?

**Comment by Dr-Bean** [comment]
We don't provide that capability. You can set up your own development environment, see the [README](https://github.com/SynoCommunity/spksrc#setup-development-environment) for instructions. Once setup, you can build the packages you want locally.

**Comment by achandab** [comment]
okay thank you

**Comment by richierichman** [comment]
What I have done is ssh into my Syno box and run tail /var/logs/messages as root and get the http location of the file that the syno device is trying to download as it gives an error when it fails. Then I downloaded the spk file via vpn on my pc. I then do a manual update via package center on the syno box and all is good. If you have access to a VPN connection you can set one up on the syno box and then try and update or do the steps I did above to get the spk file. Hope this makes sense.

**Comment by achandab** [comment]
Thanks Richie. Was hopeing to get the http address and just download it manually. I'll try to find it via the logs. I'm not a linux guy by any means however :)

**Comment by richierichman** [comment]
No probs. Also which package are you trying to get the update for. from your original post you had the link in there for git. Are you trying to get the link for Sonarr or mono?

**Comment by Dr-Bean** [comment]
I'm sorry, but while that may work, I'm going to close and lock this issue.

Maintainers put in free time and other resources to create packages, provide the source code, and everything that you need to create packages yourself. We provide a package repository free of charge to you. What we don't provide is direct downloads. That's our choice. Please respect that.
