### ISSUE TITLE
Python: bcrypt compile error for PowerPC/Qoriq

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2562]
Discovered after running into the following errors while cross-compiling for PowerPC/Qoriq:
```
src/_csrc/sha2.c: In function 'SHA256Final':
src/_csrc/sha2.c:484: error: expected ')' before ';' token
src/_csrc/sha2.c:485: error: expected ')' before '}' token
src/_csrc/sha2.c:485: error: expected ';' before '}' token
```
PR opened upstream: https://github.com/pyca/bcrypt/pull/99

We'll have to wait with releasing a new Python package until upstream releases a new version or I'll just add a patch for it. Because Python 2.7.13 is scheduled to release today/tomorrow, might as well wait.

**Comment by Dr-Bean** [comment]
Bug already fixed upstream.

While we're at it, the the maintainers of bcrypt would like to know if the test suite runs on PowerPC/Qoriq arches. 
@Decipher, @piejanssens I believe you both had one of these models. Still have it and interested to check this out? It involves some work to set up a virtualenv, installing a Python module/wheel in it (I can provide it), and running the test.

**Comment by piejanssens** [comment]
@Dr-Bean Sure, happy to help out. Just let me know what to do.
I'm on DSM 5.2 btw.

**Comment by Dr-Bean** [comment]
Thanks, that would be great :)

I'm currently building an updated Python package (probably released tomorrow), and once you have that installed, follow the next steps.

Enter this via CLI as root/equivalent (or choose a dir where the user you've logged in with has permissions to create a directory to test in):
```
cd /volume1
# Create a dir to test in
mkdir -p /volume1/testbcrypt
# Creates a virtualenv at /volume1/testbcrypt/env
/usr/local/python/bin/virtualenv --system-site-packages /volume1/testbcrypt/env
# Clone bcrypt
/usr/local/git/bin/git clone https://github.com/pyca/bcrypt /volume1/testbcrypt/bcrypt
# Enter the dir
cd /volume1/testbcrypt/bcrypt
# Will fail with an error: Can't rollback bcrypt, nothing uninstalled.
../env/bin/pip install -e .[tests]
 # Start the tests
../env/bin/pytest
```
After tests are completed (couple seconds), you should end up with something that looks like this:
```
ash-4.3# ../env/bin/pytest
================================================ test session starts ================================================
platform linux2 -- Python 2.7.13, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /volume1/testbcrypt/bcrypt, inifile: 
collected 143 items 

tests/test_bcrypt.py ...............................................................................................................................................

============================================ 143 passed in 13.24 seconds ============================================
```
...or it fails one or more tests, and it'll show that output as well. Add that here (or directly in a new issue on github.com/pyca/bcrypt), and we can go from there.

Once done, you can delete the dir with something like this:
```
cd /volume1
rm -rf testbcrypt
```
if you have any questions, let me know.

**Comment by Dr-Bean** [comment]
@piejanssens The new Python package has just been activated, so it should show up in your Package Center in, at most, a couple of hours. Once installed, you should be able to do the tests. Thanks again :)

**Comment by piejanssens** [comment]
```
DiskStation> ../env/bin/pytest
============================================================= test session starts ==============================================================
platform linux2 -- Python 2.7.13, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /volume1/testbcrypt/bcrypt, inifile:
collected 143 items

tests/test_bcrypt.py ...............................................................................................................................................

========================================================== 143 passed in 5.09 seconds ==========================================================
```

**Comment by Dr-Bean** [comment]
Perfect, thanks a lot. So that's a resounding success ;)

**Comment by GldRush98** [comment]
Can we get a direct link to the spk files for Python since it's impossible to build it off the code submitted to github?

**Comment by KaraokeStu** [comment]
Python builds perfectly and, as @Dr-Bean has stated before, we only offer downloads through the repository directly from your synology device. We do not, nor will we, supply direct links to downloads

**Comment by Dr-Bean** [comment]
@GldRush98 Please open a new issue, instead of posting in closed ones. Please see some tips [here](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issues) before you do.
Some additional points, because people run into this with every Python update (and every other package update where a `native` package was updated): 
- Make sure you re-make `native/python` before anything else. (`make clean && make` would do). Obviously, you'll want to run a `make clean` on `spk/python` as well.
- If that doesn't work, please provide us with the exact output you're getting, and which command(s) you ran to get there.

**Comment by GldRush98** [comment]
The last ticket I had open for python failing to build was ignored for months, then closed without the issue being resolved. I can go that route again though if that's what you desire.

**Comment by Dr-Bean** [comment]
Either this particular issue is related, and you should show that it is, based off of logging/output/anything, or it's not related, and then your problem belongs in a new issue anyway.

The original issue that you ran into, #2410, has been resolved. As for ignoring your issue, that's not necessarily on purpose. Sometimes, people who might be able to fix or explain things simply don't have an opportunity to do so. Don't take it personally.
