### ISSUE TITLE
Synce python2 upgrade, deluge failes to start

### ISSUE THREAD

**Issue by sferi** [SynoCommunity/spksrc#2573]
Hi!

Today I upgraded the python2 package, and since then, deluge fails to start on a DS 212j with latest DSM update. Anybody experienced similar? I've tried to install trasmission, but it won't start.

Update: a reboot solved the issue, deluge now runs.

Frank

**Comment by Dr-Bean** [comment]
Good to hear it's already solved.
For future reference, please don't delete the issue template, but instead, keep it and fill it out. Thanks.
