### ISSUE TITLE
there isn't Firefox Sync Server 1.5 v1.5.2-3 in Synology Package Center 

### ISSUE THREAD

**Issue by Dalifas** [SynoCommunity/spksrc#2578]
### Setup
_Package Name: Firefox Sync Server 1.5
_Package Version: Firefox Sync Server 1.5 v1.5.2-3

_NAS Model: DS509+
_NAS Architecture: ppc853x
_DSM version: 4.2

I can't find the Firefox Sync package 1.5 into Synology Packages Center on my NAS, but I can see another Beta packages from SynoCommunity repository. Please, can You check the supporting and explain why I can't install this one from Your repository? Thank You in advance.

```

**Comment by Dr-Bean** [comment]
DSM 4.2 is old and no longer supported: We've stopped publishing packages for that version on the repository a while ago. See https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support.

You can set up a build environment as per the [README](https://github.com/SynoCommunity/spksrc#setup-development-environment), and build the package yourself, see the [Developers HOW-TO](https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO#build-a-package). If you run into problems with that (not unlikely unfortunately): let us know, maybe we can help fix it.
