### ISSUE TITLE
invalid location on DSM 6.0 via DOCKER (DS916+)

### ISSUE THREAD

**Issue by tparvais** [SynoCommunity/spksrc#2579]
_NAS Model:_ 916+
_DSM version:_ DSM 6.0.2-8451 Update 7

### Expected behavior
When trying to add http://packages.synocommunity.com/ as packet source, I get "Invalid Location"

This works on my DSM default, but not via Docker-DSM

Of course, I checkled DNS issue, etc... it's ok

Any idea ?

**Comment by Dr-Bean** [comment]
Correct. Duplicate of https://github.com/SynoCommunity/spksrc/issues/1889

**Comment by tparvais** [comment]
that's a pity as virtualDSM is a nice tool to test different packages without endangering the generic install...

**Comment by Dr-Bean** [comment]
I'm not saying it won't be added, but there are other dependencies that need to be handled first.
