### ISSUE TITLE
DSM 6.0, rutorrent not starting

### ISSUE THREAD

**Issue by A----** [SynoCommunity/spksrc#2584]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ rutorrent
_Package Version:_ 3.7-8

_NAS Model:_ DS416j
_NAS Architecture:_ armada38x
_DSM version:_ 6.0

### Expected behavior
Clicking open right after install should launch the app.

### Actual behavior
It does not. Tried it before installing Webstation but I though it might be a dependency, so I installed it, reinstalled rutorrent, same thing.
Customized open_dir is *not* checked.
Is there other requirements (apache instead of nginx, …) ?

`ps aux | grep rtorrent` shows its running, as the interface tells us is does.

### Steps to reproduce
_1._ Install
_2._ ???
_3._ Profit!

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

**empty**

#### Other logs
Things that looks like errors in `/var/log/synopkg.log`_
```
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/rutorrent/@SYNOPKG_DOWNLOAD_rutorrent -C /volume1/@tmp/586FA7050 conf --no-same-owner
/bin/tar: conf: Not found in archive
/bin/tar: Exiting with failure status due to previous errors
```

```
            Begin:  postinst
/var/packages/rutorrent/scripts/installer: line 78: /etc/php/conf.d/com.synocommunity.packages.rutorrent.ini: No such file or directory
sed: can't read /etc/php/conf.d/user-settings.ini: No such file or directory
```

**Comment by Dr-Bean** [comment]
Rutorrent issues with DSM6 is tracked in https://github.com/SynoCommunity/spksrc/issues/2215. Closing as duplicate.
