### ISSUE TITLE
[Deluge] Cannot install plugins

### ISSUE THREAD

**Issue by stanstrup** [SynoCommunity/spksrc#2592]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Deluge
_Package Version: 1.3.13-6

_NAS Model: DS412+
_NAS Architecture: cedarview (x86_64)
_DSM version:DSM 6.0.2-8451 Update 7

### Expected behavior
I should be able to install and enable deluge plugins either with the webui interface or by putting the egg file in the right place.

### Actual behavior
The plugin seems to be completely ignored. Installing through the webui seems to copy the egg file but doesn't allow me to enable it.

I tried putting the egg in all these positions manually too:
/volume1/@appstore/deluge/share/deluge/deluge/plugins
/volume1/@appstore/deluge/share/deluge/build/lib/deluge/plugins
/volume1/@appstore/deluge/var/plugins
/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-1.3.13-py2.7.egg/deluge/plugins

### Steps to reproduce
1. Try to install any deluge plugin. Example: http://forum.deluge-torrent.org/viewtopic.php?f=9&t=33995
2. Observe that it is not listed under plugins so it cannot be enabled.

#### Package log
Log shows nothing about plugins except one of the default plugins and works and I have enabled.
```
#### Other logs

```

**Comment by Dr-Bean** [comment]
Please read the following link carefully, and make sure the plugin has a name that will be accepted. SynoCommunity's Deluge package runs on our Python 2.7 package: http://dev.deluge-torrent.org/wiki/Plugins#InstallingPluginEggs.

You can use either the web interface to install an egg, or place the file in `/usr/local/deluge/var/plugins` (which points to `volumeX/@appstore/deluge/var/plugins` in the background), but for the latter to work you'll have to restart the package.

**Comment by stanstrup** [comment]
Thanks!
