### ISSUE TITLE
FFmpeg Error With SABNZDB Post Processing 

### ISSUE THREAD

**Issue by HPMSGEN8** [SynoCommunity/spksrc#2593]
Hi,

Please see the below i logged and issue here See Post `https://github.com/clinton-hall/nzbToMedia/issues/1163` and he stated i needed to post here as well. 

### Setup
_Package Name: FFmpeg
_Package Version: 3.1.2-4

_NAS Model: DS3615xs
_NAS Architecture: 
_DSM version:DSM 6.0.2-8451 Update 6

### Expected behavior
No errors in logs and the information to get shown.

### Actual behavior

When it does the Post Processing i get this in the SABNZDB Logs of the Item.

`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`
`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`
`[12:34:15] [INFO]::TRANSCODER: Checking [FILENAME S01E01..mkv] for corruption, please stand by ...`
`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`
`/volumeX/@appstore/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)`

### Steps to reproduce
It happens for every Item that is getting processed. 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
N / A
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
N / A
```

Thanks

**Comment by cytec** [comment]
i'd guess thats because you use DSM 6 and ffmpeg was compiled with the 5.2 toolchain so your libstdc version does not match \cc @GuillaumeSmaha

**Comment by HPMSGEN8** [comment]
Thanks for the reply and the information. I take it there is not much i can do but just wait until this is resolved.

**Comment by cytec** [comment]
first you should make sure that it's really broken so try something like:

`/usr/local/ffmpeg/bin/ffprobe /path/to/a/video.file`

if that gives the error above try this:

`LD_LIBRARY_PATH=/usr/local/ffmpeg/lib /usr/local/ffmpeg/bin/ffprobe /path/to/a/video.file`

but i don't think that makes a difference since afaik we don't include `libstdc` at all... might be because of what i said above: we used 5.x toolchains which might have another version... 
Strange thing is, that you're the first with that problem. i can't verify cause im on 5.x still but if i remember correctly some people reported ffmpeg to work on dsm 6 as well...

**Comment by HPMSGEN8** [comment]
Ok thanks alot will give this an go

**Comment by HPMSGEN8** [comment]
@cytec do you have any update please on when this will get fixed / compilied for DSM6.x

**Comment by cytec** [comment]
no ETA. keep an eye on https://github.com/SynoCommunity/spksrc/issues/2216

**Comment by KaraokeStu** [comment]
Hi @HPMSGEN8 , it does complain that there is no version information available, however the command still works perfectly.

`/usr/local/ffmpeg/bin/ffprobe Firefly\ -\ S01E01-02\ -\ The\ Train\ Job\ +\ Bushwhacked\ Bluray-720p.mkv
/usr/local/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)
/usr/local/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)
ffprobe version 3.1.2 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 4.7.3 (crosstool-NG 1.18.0) 20130102 (prerelease)
  configuration: --target-os=linux --cross-prefix=/home/spksrc/syno/toolchains/syno-x64-5.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/usr/local/ffmpeg --extra-cflags=-I/home/spksrc/syno/spk/ffmpeg/work-x64-5.2/install/usr/local/ffmpeg/include --extra-ldflags=-L/home/spksrc/syno/spk/ffmpeg/work-x64-5.2/install/usr/local/ffmpeg/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/home/spksrc/syno/toolchains/syno-x64-5.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-optimizations --enable-pthreads --enable-gpl --enable-version3 --enable-nonfree --enable-fontconfig --enable-libass --enable-libbluray --enable-libfdk-aac --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-openssl --disable-debug --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-static --disable-txtpages --arch=x86_64 --enable-thumb
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, matroska,webm, from 'Firefly - S01E01-02 - The Train Job + Bushwhacked Bluray-720p.mkv':
  Metadata:
    encoder         : libebml v0.7.9 + libmatroska v0.8.1
    creation_time   : 2013-01-12 15:34:14
  Duration: 01:26:42.19, start: 0.000000, bitrate: 9238 kb/s
    Chapter #0:0: start 0.000000, end 306.515000
    Metadata:
      title           : 00:00:00.000
    Chapter #0:1: start 306.515000, end 658.783000
    Metadata:
      title           : 00:05:06.515
    Chapter #0:2: start 658.783000, end 710.710000
    Metadata:
      title           : 00:10:58.783
    Chapter #0:3: start 710.710000, end 1006.797000
    Metadata:
      title           : 00:11:50.710
    Chapter #0:4: start 1006.797000, end 1326.825000
    Metadata:
      title           : 00:16:46.797
    Chapter #0:5: start 1326.825000, end 1657.990000
    Metadata:
      title           : 00:22:06.825
    Chapter #0:6: start 1657.990000, end 2060.100000
    Metadata:
      title           : 00:27:37.990
    Chapter #0:7: start 2060.100000, end 2164.496000
    Metadata:
      title           : 00:34:20.100
    Chapter #0:8: start 2164.496000, end 2532.488000
    Metadata:
      title           : 00:36:04.496
    Chapter #0:9: start 2532.488000, end 2863.903000
    Metadata:
      title           : 00:42:12.488
    Chapter #0:10: start 2863.903000, end 3026.523000
    Metadata:
      title           : 00:47:43.903
    Chapter #0:11: start 3026.523000, end 3180.302000
    Metadata:
      title           : 00:50:26.523
    Chapter #0:12: start 3180.302000, end 3410.991000
    Metadata:
      title           : 00:53:00.302
    Chapter #0:13: start 3410.991000, end 3535.657000
    Metadata:
      title           : 00:56:50.991
    Chapter #0:14: start 3535.657000, end 3699.988000
    Metadata:
      title           : 00:58:55.657
    Chapter #0:15: start 3699.988000, end 3866.863000
    Metadata:
      title           : 01:01:39.988
    Chapter #0:16: start 3866.863000, end 4402.940000
    Metadata:
      title           : 01:04:26.863
    Chapter #0:17: start 4402.940000, end 4839.668000
    Metadata:
      title           : 01:13:22.940
    Chapter #0:18: start 4839.668000, end 5148.476000
    Metadata:
      title           : 01:20:39.668
    Chapter #0:19: start 5148.476000, end 5202.187000
    Metadata:
      title           : 01:25:48.476
    Stream #0:0: Video: h264 (High), yuv420p, 1280x720, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s (default)
    Stream #0:2(dut): Subtitle: subrip (default)
`

**Comment by HPMSGEN8** [comment]
@cytec Thanks will do :) 

@KaraokeStu Thanks for the info :)

**Comment by KaraokeStu** [comment]
Closed as just a warning
