### ISSUE TITLE
[Package Request] Watcher (CouchPotato alternative)

### ISSUE THREAD

**Issue by nkean** [SynoCommunity/spksrc#2596]
Name: Watcher
Description: Watcher is an automated movie NZB searcher and snatcher. You can add a list of wanted movies and Watcher will automatically send the NZB to Sabnzbd or NZBGet. Watcher also has basic post-processing capabilities such as renaming and moving.
Website:  https://github.com/nosmokingbandit/watcher
Software documentation: https://github.com/nosmokingbandit/watcher/blob/master/README.md
Build/Installation documentation:  see above
Source Code:  https://github.com/nosmokingbandit/watcher

Currently running the docker container linked on the github page. Software works well.  Much better than CouchPotato in my experience. I think an SPK would make it easier for most to get this up and running.

**Comment by cytec** [comment]
FYI: if anyone want's to try and create a SPK couchpotato should be a good starting point. from a quick scrim, the git clone url and some variables should be changed and this should work

**Comment by Dr-Bean** [comment]
@nkean Please don't skip any of the requested fields for package requests: missing license.
`
LICENSE = Apache 2.0
`

**Comment by Dr-Bean** [comment]
Software seems _very_ new though. Might be best to wait until it settles down a bit.

**Comment by medom** [comment]
personally I would opt for Radarr (Sonarr movie fork) instead: https://github.com/Radarr/Radarr/

**Comment by KaraokeStu** [comment]
I'll look to create something for this over the next few days and see if it works.

@medom Can you open a new request to ask for a Radarr package and I'll see what I can do there too?

**Comment by fredrike** [comment]
Watcher is no longer supported, should adopt to #2879 and follow Watcher3.

I suggest this issue gets closed.
