### ISSUE TITLE
Octoprint package fails to start - dependecy `unidecode` missing

### ISSUE THREAD

**Issue by nblake989** [SynoCommunity/spksrc#2599]
Initial Diagnosis: `spk/octoprint/src/requirements.txt` has a new dependency of `unidecode` that is missing at package runtime. `unidecode` is referenced once in the repo and was added in commit [`a72eb7e0d7135bd90eb6b7fa9e70cf967753e88f`](https://github.com/SynoCommunity/spksrc/commit/a72eb7e0d7135bd90eb6b7fa9e70cf967753e88f)

New install of Octoprint is unable to launch from Package Center.

`unidecode` was added to `spk/octoprint/src/requirements.txt` but is not installed and causes OctoPrint installations to throw an exception on startup of the container because `unidecode` is not found. Apologies for the screenshot, DS doesn't allow for copy/paste of the Package Log.

![screen shot 2017-01-13 at 5 45 40 pm](https://cloud.githubusercontent.com/assets/8633545/21951276/20ea80e4-d9b9-11e6-86ea-742f9f0aec02.png)

**Comment by Dr-Bean** [comment]
The `unidecode` addition isn't released in a package yet, I just added it to be sure it would be included in a future package update.
As a workaround, you can install it locally: `/usr/local/octoprint/env/bin/pip install unidecode` should do it.

I believe Octoprint as a whole could use an update (1.3.x is released, for example). @markbastiaans, @Decipher Can one of you handle that and create a PR?

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #3128.
