### ISSUE TITLE
[SABnzbd] Request: Update SABnzbd to Version 1.2.0

### ISSUE THREAD

**Issue by krazun** [SynoCommunity/spksrc#2600]
Hello Community,

SABnzbd Version 1.2.0 is out now and it would be really cool if someone would be so nice to update the package to the newest version.

Thank you very much!

**Comment by HPMSGEN8** [comment]
I see that someone has pushed the updated to v1.2.0-20.

**Comment by KaraokeStu** [comment]
Yup merged, built, and pushed!
