### ISSUE TITLE
[Package Request] Ombi

### ISSUE THREAD

**Issue by G1zm0** [SynoCommunity/spksrc#2601]
Name: Ombi

Description: Previous known as Plex Request. Ombi allows you to host your own Plex Request and user management system. If you are sharing your Plex server with other users, allow them to request new content using an easy to manage interface! Manage all your requests for Movies and TV with ease, leave notes for the user and get notification when a user requests something. Allow your users to post issues against their requests so you know there is a problem with the audio etc.Even automatically sent them weekly newsletters of new content that has been added to your Plex server! Integration with Emby is planned.

Website: [http://ombi.io](http://ombi.io)

Software documentation: [https://github.com/tidusjar/Ombi/wiki](https://github.com/tidusjar/Ombi/wiki)

Build/Installation documentation: [http://www.htpcguides.com/install-plex-requests-net-ubuntu-14-x/](http://www.htpcguides.com/install-plex-requests-net-ubuntu-14-x/) (Needs .Net (Mono))

Source code: [https://github.com/tidusjar/Ombi](https://github.com/tidusjar/Ombi)

License: [GPLv2](https://github.com/tidusjar/Ombi/blob/master/LICENSE)

**Comment by sirjaymz** [comment]
+1

**Comment by Re4mstr** [comment]
I'd love this.. :+1:

**Comment by ycflash** [comment]
+1

**Comment by hgy59** [comment]
@ycflash there is a new PR for ombi #5384.
If you want to test it, you can download the artifacts created by github build action (under checks - build - artifacts) 
Please note, that the armv7 generic packages do not include the unsupported archs:  armada370 alpine monaco armadaxp.

**Comment by ycflash** [comment]
@hgy59 seams working for me on DSM 7.1 x64. Thank you!

**Comment by hgy59** [comment]
@ycflash thanks for the feedback.

Anyone here who can test the integration with other packages?
- media server (Jellyfin)
- TV (sonarr)
- Movies (Radarr, CouchPotato)
- Music (Lidarr)

**Comment by ycflash** [comment]
@hgy59 I have being using with sonarr 20217171-19, radarr 20220515-18; works for me.
