### ISSUE TITLE
SabNZBD: Remove update wizard, update changelog

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2603]
As discussed here: https://github.com/SynoCommunity/spksrc/issues/2545#issuecomment-265782654.

The [update wizard](https://github.com/SynoCommunity/spksrc/blob/master/spk/sabnzbd/src/wizard/upgrade_uifile) should be removed, and the [changelog](https://github.com/SynoCommunity/spksrc/blob/master/spk/sabnzbd/Makefile#L18) should be kept in sync with changes in the package.

**Comment by Dr-Bean** [comment]
@KaraokeStu, can you handle this? :)

**Comment by Hubfront** [comment]
Sry for offtopic, but is it possible to install SabNZBD on a fresh installed DSM 6 and make it run without any workarounds? Just wonder because i just readed 

https://github.com/SynoCommunity/spksrc/issues/2416

Sab would be all i need as app.

**Comment by Dr-Bean** [comment]
#2416 would be the correct place to ask though :)
From there, I would forward you to #2216, because that contains the latest info wrt general package changes for DSM6. See https://github.com/SynoCommunity/spksrc/issues/2216#issuecomment-271852804 in particular.
Once there are specifics for the sabnzbd package, I'll update #2416. For the record, the current answer is "No, you can't. We're working on it".

**Comment by Hubfront** [comment]
Sorry again :)
and btw. it's nice, that you are here again on spksrc.

**Comment by Dr-Bean** [comment]
Done with c84b15f19b79e5612eaaf588f3b4ef0f93a36fa7
