### ISSUE TITLE
ffmpeg versions & libx264 on DS215j

### ISSUE THREAD

**Issue by dg2000r** [SynoCommunity/spksrc#2604]
Hi

I've installed ffmpeg from the Community tab in package manager. When I try to use it though (to convert video to mp4) I'm still getting errors because it can't find libx264. Do I need to do something extra to enable that, or should it just be there already? Also is there any way to check that I'm actually using the newly installed ffmpeg, and not the old version that I had on there already? 

Apologies for the noob questions!

Thanks

**Comment by cytec** [comment]
synocommunity's ffmpeg is installed to `/usr/local/ffmpeg/bin/ffmpeg` if you use that it should work...

**Comment by dg2000r** [comment]
Perfect - I eventually figured that out last night, and it's all working great now. Thanks!
