### ISSUE TITLE
synocommunity.com blocked in Russia

### ISSUE THREAD

**Issue by minzdrav** [SynoCommunity/spksrc#2609]
Hi Syno Community team.
I've noticed, that your site no longer available in Russia. Your ip address [104.31.94.179] is blocked by a court decision. Site vulkan-igry.com used same ip and contain forbidden information: https://reestr.rublacklist.net/search/?q=104.31.94.179

Do you guys have mirror or something that can help? Maybe I can manually download packages somehow?
Thank you.

**Comment by Diaoul** [comment]
This is the IP address of CloudFlare, a popular CDN service. I'm very surprised the whole CDN is blocked in Russia.
We don't have a mirror.

**Comment by piwi82** [comment]
This is an IP address from the CDN [CloudFlare](https://www.cloudflare.com/), other websites uses the same front servers from CloudFlare.
This is just about a stupid operator blocking CDN IP addresses without verification.
Could you give a feedback to rublacklist.net ?

**Comment by piwi82** [comment]
I don't know who applies the court decisions in Russia, but blocking an IP address without verifying whether it's owned by a CDN or not is just stupid  :man_facepalming:

**Comment by minzdrav** [comment]
I'm totally agree that it's stupid.

**Comment by minzdrav** [comment]
@piwi82 I've contacted roskomnadzor: http://rkn.gov.ru/
They responsible for blocking in Russia. Answer: "Основания для исключения сетевого адреса из Единого реестра отсутствуют в силу доступности запрещенной инофрмации."
Translation: "We can't remove ip address from Unified Register because forbidden information still available".

I can't resolve this problem with roskomnadzor or my internet provide :(

**Comment by piwi82** [comment]
Have you told them that this IP address is not dedicated to vulkan-igry.com ? There are other sites being this IP address that are being blocked for no reason. They should filter on domain names, not on IP addresses (it is done this way in France, and very easy to bypass 😄 ).
On your side, you should consider using a VPN (don't forget to activate the firewall).

**Comment by minzdrav** [comment]
"Have you told them that this IP address is not dedicated to vulkan-igry.com ? There are other sites behind this IP address that are being blocked for no reason."
Yes. They don't care. Or just stupid...

"They should filter on domain names, not on IP addresses"
I think they don't have hardware for that.

"you should consider using a VPN"
Yes, I have vpn on my pc. But not on synology. Maybe I can configure vpn on synology, I'll check.

**Comment by minzdrav** [comment]
Thanks. Good idea with vpn. I've configured vpn on synology and now I can update and install packages.
It's  not perfect, but better  that nothing :)

**Comment by KaraokeStu** [comment]
Issue resolved with workaround. Closing 👍
