### ISSUE TITLE
ffmpeg for evansport

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#2612]
### Setup
_Package Name:_ ffmpeg
_Package Version:_ 3.1.2-4

_NAS Model:_ DS214play
_NAS Architecture:_ evansport
_DSM version:_ 6.0.2

### Expected behavior

Package availability for evansport architecture. After applying PR #2606 and #2608 on branch `dsm6`, I successfully built and deployed ffmpeg 3.1.2 package on my system.

### Actual behavior

Package is not available for evansport architecture

**Comment by Dr-Bean** [comment]
Weird...Either I cleaned up to much when I removed a number of old packages recently, or it never existed in the first place, can't tell.
@cytec, maybe you can take a look at compiling the missing package(s)?

**Comment by cytec** [comment]
@ymartin59 a little more information would be nice. something like the actual error you are getting or where it fails at all... i've only compiled it with 5.2 toolchains so far...

**Comment by Dr-Bean** [comment]
@cytec It's not that (or at least, I don't think so; the ffmpeg packages on the repo should work for DSM6 afaik). 
The thing is, there's no Evansport package for ffmpeg on the repository. I recently cleaned up old versions of the ffmpeg package, seeing as the 2.x package was badly broken, and I don't _think_ I made a mistake, but I could have. It's either that, or the package was never uploaded at all.

**Comment by cytec** [comment]
ah now i see... you are correct: i've never uploaded a 3.1.2 spk for evansport...
which seems strange i'm sure i did run `publish-all-supported` gonna check that and compile a version for evansport too

**Comment by Dr-Bean** [comment]
Just guessing, but if you're on x86 (-32), maybe build fails for Evansport, as it's the only x86 arch?

**Comment by cytec** [comment]
might be a problem but for some reason it seemed to have stopped when verifying `nasm`... running again now i'd keep an eye on that... but i guess you are right and it'll fail because im still on a 32bit host

**Comment by Dr-Bean** [comment]
Otherwise I'll start a build over the weekend, np.

**Comment by cytec** [comment]
SPK is published
