### ISSUE TITLE
[Package Request] FTP Client / Server

### ISSUE THREAD

**Issue by HPMSGEN8** [SynoCommunity/spksrc#2613]
Hi,

I wonder if there is an FTP Package some where that i can use on my Synology. Reason for this is that i have an SeedBox with `https://seedboxes.cc` and i would like to sync my data or just get files i need.

I have logged an support ticket with them to see if there is an package i can use or get added to the community.

Name: FileZilla
Description: FTP Client / Server
Website: https://filezilla-project.org/
Software documentation: https://wiki.filezilla-project.org/Documentation
Build/Installation documentation: https://wiki.filezilla-project.org/Main_Page
Source Code: https://filezilla-project.org/

**Comment by cytec** [comment]
wget can download from ftp, and is already present on your DS.

**Comment by HPMSGEN8** [comment]
@cytec can you please explain an bit more is this an Add-On or part of the OS

**Comment by cytec** [comment]
@HPMSGEN8 afaik wget is part of synology's default OS so you don't need to install anything, just ssh into your DS and rung `wget` i've use it like this:

`wget --ftp-user=USERNAME --ftp-password=PASSWORD --timestamping --no-remove-listing --recursive ftp://server/path/to/dir`

which recursive mirrors the server directory to my DS check out https://www.gnu.org/software/wget/manual/wget.html#FTP-Options for more options/infos

**Comment by HPMSGEN8** [comment]
Thanks alot for this :)

**Comment by ymartin59** [comment]
FTP protocol is supported in Download Station. With proper URL added to "downloads" you get your files transfered. See topic https://forum.synology.com/enu/viewtopic.php?t=55698

You also refer to FTP server in your title. Such service is available in DSM: https://www.synology.com/en-us/knowledgebase/DSM/tutorial/File_Sharing/How_to_access_files_on_Synology_NAS_via_FTP
(even if SFTP over SSH is highly recommended)

**Comment by HPMSGEN8** [comment]
@ymartin59 thanks for this as well i will check this out. my main goal is to get my seedbox to sync with my NAS in the end.

**Comment by ymartin59** [comment]
@HPMSGEN8 you confirm you use https://www.seedbox.fr/fr/ services, right ?

To sync files, "rsync" is the well known tool on Linux/Synology but it cannot work with neither FTP or WebDAV protocol. Technical alternative I have found is to mount a folder with FUSE / curlftpfs...  but I doubt FUSE is already available in DSM 5 or DSM 6 Linux kernels, which mean it may be a "hard" solution to your need.

A simpler way would be to use FTP or WebDAV mirroring tool which operates incrementally by delta and run it regularly with cron.

Still thinking about it...

**Comment by cytec** [comment]
@ymartin59 well... or just use wget's fpt mirror function like i mentioned above ;)

**Comment by HPMSGEN8** [comment]
@ymartin59 it is https://seedboxes.cc who is use

**Comment by ymartin59** [comment]
Right. "wget" can do incremental mirroring. Automating with a crontab entry may be far enough.

**Comment by ymartin59** [comment]
But I wonder if using Syncthing on both seedboxes and Synology may be a "better" option. Opinion about it ?

**Comment by cytec** [comment]
well... you could install Syncthing on both devices and set that up i guess. I didn't do it because well... why bother with another app to configure and setup when wget already has everything i need? This might come in handy when you want a 2 way sync or something like that. But in my case i only need remote to local sync and decided to go with the easiest/quickest solution

**Comment by ymartin59** [comment]
@cytec OK but my proposal targets @HPMSGEN8 situation. From my point of view this request should be closed as FTP client are already available on Synology and Filezilla does not sound to be an option for a "regular" user. (I do not expect anyone to run a X server and connect with SSH and X11 forward to open Filezilla)

**Comment by cytec** [comment]
@ymartin59 correct ;)
