### ISSUE TITLE
Error building ffmpeg for armada370

### ISSUE THREAD

**Issue by Pilou44** [SynoCommunity/spksrc#2617]
Hello,
I'm trying to build ffmpeg for my Synolgy NAS. I need version 3.2 at least.
I've followed the steps described here : https://github.com/SynoCommunity/spksrc
Then I've done:
cd spksrc/
make setup
cd spk/ffmpeg
make arch-armada370

Build failed here : 
===>  Configuring for openjpeg
cd /home/wechantloup/workspace/spksrc/spk/ffmpeg/work-armada370-5.2/openjpeg-2.1.0 && env PKG_CONFIG_LIBDIR=/home/wechantloup/workspace/spksrc/spk/ffmpeg/work-armada370-5.2/install//usr/local/ffmpeg/lib/pkgconfig WORK_DIR=/home/wechantloup/workspace/spksrc/spk/ffmpeg/work-armada370-5.2 INSTALL_PREFIX=/usr/local/ffmpeg TC=syno-armada370-5.2  LD="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ld" LDSHARED="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-gcc -shared" CPP="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-cpp" NM="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-nm" CC="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-gcc" AS="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-as" RANLIB="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ranlib" CXX="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-g++" AR="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ar" STRIP="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-strip" OBJDUMP="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-objdump" READELF="/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-readelf" CFLAGS="-I/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -mhard-float -mfpu=vfpv3-d16 -I/home/wechantloup/workspace/spksrc/spk/ffmpeg/work-armada370-5.2/install//usr/local/ffmpeg/include " CPPFLAGS="-I/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -mhard-float -mfpu=vfpv3-d16 -I/home/wechantloup/workspace/spksrc/spk/ffmpeg/work-armada370-5.2/install//usr/local/ffmpeg/include " CXXFLAGS="-I/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -mhard-float -mfpu=vfpv3-d16 -I/home/wechantloup/workspace/spksrc/spk/ffmpeg/work-armada370-5.2/install//usr/local/ffmpeg/include " LDFLAGS="-L/home/wechantloup/workspace/spksrc/toolchains/syno-armada370-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/lib -mhard-float -mfpu=vfpv3-d16 -L/home/wechantloup/workspace/spksrc/spk/ffmpeg/work-armada370-5.2/install//usr/local/ffmpeg/lib -Wl,--rpath-link,/home/wechantloup/workspace/spksrc/spk/ffmpeg/work-armada370-5.2/install//usr/local/ffmpeg/lib -Wl,--rpath,/usr/local/ffmpeg/lib " cmake -DCMAKE_INSTALL_PREFIX=/home/wechantloup/workspace/spksrc/spk/ffmpeg/work-armada370-5.2/install/usr/local/ffmpeg
env: «cmake»: Aucun fichier ou dossier de ce type

I'm using French but it could be translated by "cmake: no such file or directory"
Have I done something wrong ?

Moreover, can you tell me how to build ffmpeg on tag "n3.2.2" ?

Thank you for your help.

**Comment by cytec** [comment]
seems like you are missing cmake...
have you tried installing it by running `sudo apt-get install cmake` ?

**Comment by Pilou44** [comment]
And you, it solved my compilation issue. But I still don't get how to specify the ffmpeg version I want to buid. I realy need 3.2.2 which is on "n3.2.2" tag. Can someone help me with this ?

**Comment by Pilou44** [comment]
I've finally found how to do that.
