### ISSUE TITLE
Allow download of packages for manual installation

### ISSUE THREAD

**Issue by Magissia** [SynoCommunity/spksrc#2622]
### Setup
_Package Name:_ Any
_Package Version:_ Any

_NAS Model:_ RT1900AC
_NAS Architecture:_ northstarplus
_DSM version:_ SRM 1.1.3-6447 Update 1

### Expected behavior
Tell us what should happen
Looking at http://packages.synocommunity.com/ with a web browser allows to download packages for manual installation

### Actual behavior
Tell us what happens instead
Looking at http://packages.synocommunity.com/ with a web browser doesn't show any packages

### Steps to reproduce
_1._ Visit http://packages.synocommunity.com/ with a web browser
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Not applicable, RT1900AC doesn't support 3rd repositories
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Not applicable
```

**Comment by Magissia** [comment]
RT1900AC doesn't allow end user to add new repositories, but SynoCommunity doesn't allow downlaod of packages for manual installer neither, while t he RT1900AC allows manual install.

**Comment by cytec** [comment]
we don't provide direct DL links, see: https://github.com/SynoCommunity/spksrc/issues/2561#issuecomment-268912270 you can still set up your own Development Environment and compile the needed SPK's on your own see https://github.com/SynoCommunity/spksrc#setup-development-environment
