### ISSUE TITLE
Add FAQ entry covering manual download questions

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2623]
Title says it all.

**Comment by cytec** [comment]
I'm with you on that. But i'm not 100% sure where it would fit best.

Maybe on the Website? And additionally in the Wiki?
Doesn't really belong in the readme i guess...

**Comment by Dr-Bean** [comment]
I was thinking in the actual FAQ: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions.
CONTRIBUTING (so, the Guidelines that are shown when opening an issue) links to it from [issues](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issues).
We don't directly link to the FAQ from the README, but we do have a link to CONTRIBUTING in there. (I don't want to link back and forth between various documents, that doesn't make a whole lot of sense)

**Comment by cytec** [comment]
Might wanna add something about DSM 6 too?
seeing there are a lot of issues targeting `xyz not running on DSM 6` i know we already have something like that here https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support ...

**Comment by cytec** [comment]
How about this for the download's part: 

### I cant access SynoCommunity Repo could you provide a direct download for {package}

Make sure you checked your DNS Settings and that you have set the  Trust Level to `Synology Inc. and trusted publishers`.

We don't provide any direct/manual download links for any of our Packages, we do provide the source code, and everything that you need to create packages yourself.  
You are free to build the package you are looking for useing `spksrc` free of charge. For a starting point see: https://github.com/SynoCommunity/spksrc#setup-development-environment

**Comment by Dr-Bean** [comment]
Sure, we could, but I hope that the dsm6 issues will be largely resolved in the next couple of weeks or so (depends on how soon the repo backend is updated, and how fast I can get packages out). So we might not need to update the FAQ anymore... ;)

The thing with DSM6 is that ultimately, I want one (1) open issue per non-working package. That issue will be used to track working DSM6 compatibility, once I push out changes to packages on the `dsm6` branch. 
So my idea with that is that I'll compile a list of those packages + their open issues, put that in #2216 and #2207, lock #2207, and instruct people to use those individual issues to report on whether the updated packages are working or not. And instruct people to stop manually adjusting packages...

**Comment by cytec** [comment]
Nice, wasn't aware that DSM6 support is just around the corner ;) just ignore what i said about that then :)

**Comment by Dr-Bean** [comment]
Well, I'm probably halfway there, but since I'm mostly scripting the changes for all packages at once, there's no point in pushing it out...and a lot of packages need manual checking afterwards to make sure I didn't miss anything...kind of tedious :/

The text looks okay. Starting with your text, how does this sound?
Do you provide a direct download for {package}?

We don't provide direct/manual download links for packages published on the SynoCommunity package repository.
However, all of the source code of out packages is published, allowing you to build the packages yourself. See the [README](https://github.com/SynoCommunity/spksrc#setup-development-environment) for instructions on how to set up a development environment, and see the [Developers HOW-TO](https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO#build-a-package) for information on how to build packages.

**Comment by Dr-Bean** [comment]
As I understand it, there seem to be several reasons people ask for manual downloads, so I left that part out :)

**Comment by cytec** [comment]
looks good to me ;)

**Comment by Dr-Bean** [comment]
Done: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#do-you-provide-directmanual-downloads-for-packages
Slightly edited once more ;)
Thanks for the input, @cytec :)
