### ISSUE TITLE
flexget package build broken since "new wheel approach"

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#2625]
Current master version produces an invalid "flexget" package. It is 30 KiB and contains only `var/config.yml`.

Building "flexget" at commit 1a6f563f3f8547bf5c0c8158272f18819a1db17b creates a non empty package weighting 6 MiB which sounds correct.

Related to my upgrade try for request #2551

I report this issue in case other python packages are affected to by commit a72eb7e0d7135bd90eb6b7fa9e70cf967753e88f, in that case, issue title should be "generalized".

**Comment by Dr-Bean** [comment]
Just an oversight on my part, we should drop https://github.com/SynoCommunity/spksrc/blob/master/spk/flexget/Makefile#L23.
There might be some other packages that are affected, I can't remember if I checked that, or just forgot for Flexget.

**Comment by Dr-Bean** [comment]
Fixed with https://github.com/SynoCommunity/spksrc/commit/af51e31a559de37976b5bbdad9514158c66bad42

**Comment by ymartin59** [comment]
Thanks for the quick fix. It would have took me a pair of hours to understand and fix myself.
