### ISSUE TITLE
[Update Request] libtorrent_rasterbar_1.1.1-1 for Deluge

### ISSUE THREAD

**Issue by bamtan** [SynoCommunity/spksrc#2634]
I'm not sure about the current version of libtorrent_rasterbar, according to `/usr/local/deluge/lib` it's on `8.0.0` but [here](https://github.com/SynoCommunity/spksrc/tree/master/cross/libtorrent) it's on 1.0.10

Either way -- I'm having SSL handshake errors when seeding/downloading from https trackers with the current libtorrent version. 

Is there any way I can update this for the time being?

**Comment by Dr-Bean** [comment]
We haven't updated to the libtorrent 1.1 tree because of http://dev.deluge-torrent.org/ticket/2852: it's not supported.

If you want to update/test anyway, set up a development environment, fork spksrc, edit `cross/libtorrent` to your needs (+update digests and PLIST), then compile the Deluge package for your architecture.
More details are available on https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO

**Comment by bamtan** [comment]
@Dr-Bean what about 1.0.10?

**Comment by Dr-Bean** [comment]
It _is_ 1.0.10: https://github.com/SynoCommunity/spksrc/blob/master/cross/libtorrent/Makefile#L2.
You're looking at the shared library version: the two versioning schemes don't necessarily have to be the same. More likely then not, they aren't :)

**Comment by Dr-Bean** [comment]
Having said that, I don't know that the current Deluge package has 1.0.10 in it..it's probably 1.0.6. Not sure what the changelog looks like between 1.0.6 and 1.0.10.

**Comment by bamtan** [comment]
@Dr-Bean Do you know how I could manually get 1.0.10 by any chance? I'm on an armv7 (DS216J). Thanks for the information 😃

**Comment by Dr-Bean** [comment]
See my first comment: you'll have to compile the Deluge package yourself, and after that, you can install it via Package Center.

**Comment by bamtan** [comment]
@Dr-Bean I can't do this ☹️

**Comment by Dr-Bean** [comment]
Please explain what you mean with that. We don't mind that you ask questions, so why not try it?
It's either that, or you'l have to wait until one of the maintainers releases a new package.

**Comment by bamtan** [comment]
@Dr-Bean I guess I could give it a try. Debian 8 on a Virtual machine right? I'll read through the wiki.

**Comment by Dr-Bean** [comment]
Yep, that's it :)

**Comment by Dr-Bean** [comment]
As mentioned in the other issue: I'm working on it, if all goes well, I'll push out an updated package later today.

**Comment by Dr-Bean** [comment]
Next release we should probably take the package out of beta.

**Comment by bamtan** [comment]
@Dr-Bean good to hear, thanks!

**Comment by Dr-Bean** [comment]
Deluge 1.3.13-7 has been published on the repository. It should show up in Package Center between now and an hour or two. Let me know if you run into issues :)
