### ISSUE TITLE
Retire Jappix package?

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2635]
As per https://github.com/jappix/jappix, Jappix is no longer maintained, and jappix.org is no longer available.
While PR's are still accepted, according to upstream, there's not all that much activity going on (even though a release has been cut a couple of days ago...not sure how that works)

Releases are now available on github (https://github.com/jappix/jappix/releases), so if we want to continue with the package, PKG_DIST_SITE needs an update.

**Comment by GuillaumeSmaha** [comment]
I don't know if a lot of people use it but there is only one dependence `cross/jappix` (it will be easy to keep it updated).

**Comment by hgy59** [comment]
removed from repo
