### ISSUE TITLE
Retire oscam package?

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2636]
Note sure if the software is still maintained, but since the current version is probably outdated, and we can't release packages for it anyway, might as well retire it.

@schumi2004, I think you used this (in the past anyway): any input?
@Diaoul As the maintainer, same question for you :)

**Comment by schumi2004** [comment]
I have my own version now and like you said it's not allowed to release i would just drop it.

**Comment by Dr-Bean** [comment]
So it's still maintained? Because the other option is that we keep oscam in sync with upstream (whatever version it is), and just not publish the package on the SynoCommunity package repository. That enables people to build the package directly from spskrc for themselves.

**Comment by schumi2004** [comment]
OSCam itself is still maintained.
I can upload my version of it, it's equal to upstream. 
It also contains http://www.streamboard.tv/oscam-addons/wiki/Envi_WebIf_Template

**Comment by ymartin59** [comment]
OSCam is maintained http://www.streamboard.tv/oscam/browser but no new tag since years... According to what I understood, current versioning is 1.20-svnrevision

If package in not visible in repository, nobody will find it here. For information, a OSCam package is available at http://synology.nimloth.pl/

Why stop publishing OSCam in synocommunity repository ?

**Comment by hgy59** [comment]
@Dr-Bean what is the reason for ".. we can't release packages for it anyway ..."?
@schumi2004 is there any reason why is is not allowed to release the OSCam package?

As stated in the [README file](http://www.streamboard.tv/oscam/browser/trunk/README), OSCam is licensed under GPLv3. So is there any other (proprietary) software required for OSCam to work?

**Comment by Diaoul** [comment]
See #243

**Comment by Diaoul** [comment]
Some ideas of disclaimer that was sent to me a long time ago:

> Dutch (NL)
** Waarschuwing **
In sommige landen gelden beperkingen voor het gebruik van de Software. Het behoort tot uw eigen verantwoordelijkheid om u ervan te verzekeren dat het u wettelijk is toegestaan om op uw locatie van de Software gebruik te maken.

> German (D)
** Warnung **
In einigen Ländern gibt es Einschränkungen bei der Nutzung der Software. Sie müssen prüfen, ob Sie die Software an Ihrem Standort legal nutzen dürfen.

> French (F)
** Attention **
Dans certains pays, des restrictions pèsent sur l'utilisation du Logiciel. Il vous incombe de vous assurer que vous êtes autorisé légalement à utiliser le Logiciel où vous vous trouvez.

> Spain (ES)
** Advertencia **
En algunos países, existen restricciones sobre el uso del Software. Es su responsabilidad garantizar que en el lugar donde reside esté legalmente permitido el uso del Software.

> Italy (I)
** Avviso **
In alcuni Paesi sono vigore alcune limitazioni relative all'utilizzo del Software. È responsabilità dell'utente assicurarsi che sia possibile utilizzare legalmente il Software nel Paese in cui si trova.

> Polish: (PL)
** Warning **
W niektórych krajach obowiązują ograniczenia dotyczące użytkowania Oprogramowania. Użytkownik jest odpowiedzialny za sprawdzenie, czy prawo pozwala mu korzystać z Oprogramowania w miejscu jego pobytu.

> Russian: (RU)
** предупреждение **
В некоторых странах действуют ограничения на использование Программного обеспечения. Ответственность за определение, имеете ли Вы законное право использовать Программное обеспечение в стране, в которой Вы находитесь, лежит на Вас.

**Comment by hgy59** [comment]
@Diaoul thanks for clarifying this.
IMHO a disclaimer at installation time would resolve it.
I think this is comparable to the Disclaimer of the official download station package from synology.com (disclaimer is not at installation time but in the configuration section for the actuvation of "Xunlei-Lixian" - but this does not matter).

**Comment by hgy59** [comment]
@ymartin59  I recommend to retire OSCam on SynoCommunity spksrc.

> OSCam is maintained http://www.streamboard.tv/oscam/browser but no new tag since years... According to what I understood, current versioning is 1.20-svnrevision

The trunk there is still under active development, although no tags are provided.
http://www.streamboard.tv/svn/svnstyle/open/log/?base=oscam&target=//trunk/

> If package in not visible in repository, nobody will find it here. For information, a OSCam package is available at http://synology.nimloth.pl/
> 
The packages on the nimloth repository are still maintained and updated. 
AFAIK these are not based on SynoCommunity spksrc. 

Therefore I prefer to remove the OSCam package from spksrc against further investigations for a disclaimer and for updates.

This is related to #2661, #3637 and #3869
