### ISSUE TITLE
[Package Request] GazelleUI (Headphones alternative)

### ISSUE THREAD

**Issue by bamtan** [SynoCommunity/spksrc#2637]
Name: GazelleUI
Description: Similar to Headphones, it is a lightweight web based torrent manager, with mobile support.
Website: https://github.com/XanderStrike/GazelleUI
Software documentation: https://github.com/XanderStrike/GazelleUI/blob/master/readme.md
Build/Installation documentation: see above
Source Code: https://github.com/XanderStrike/GazelleUI

I nearly got this to run on my DS216j (non-Docker supported) but encounter the following when running:

```
* Running on http://0.0.0.0:2020/ (Press CTRL+C to quit)
* Restarting with stat
Traceback (most recent call last):
  File "GazelleUI.py", line 31, in <module>
    scheduler.init_app(app)
  File "/usr/lib/python2.7/site-packages/flask_apscheduler/scheduler.py", line 68, in init_app
    self._load_jobs()
  File "/usr/lib/python2.7/site-packages/flask_apscheduler/scheduler.py", line 269, in _load_jobs
    self.add_job(**job)
  File "/usr/lib/python2.7/site-packages/flask_apscheduler/scheduler.py", line 129, in add_job
    return self._scheduler.add_job(**job_def)
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 411, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 905, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 890, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/lib/python2.7/site-packages/apscheduler/triggers/interval.py", line 37, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/lib/python2.7/site-packages/apscheduler/util.py", line 84, in astimezone
    'Unable to determine the name of the local timezone -- you must explicitly '
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (such as Europe/Helsinki).
```

Is this an easy fix?

**Comment by Dr-Bean** [comment]
Ask upstream for that issue. It's their software...

**Comment by Dr-Bean** [comment]
Besides, you're not using our Python package, but Synology's. Take a look at some of the existing Python-based packages in spksrc, that may be simpler in the long run.

**Comment by bamtan** [comment]
@Dr-Bean I am using Diaoul's Python 2.7.13-16 package from the Synocommunity. 
Also, I've asked upstream -- but unfortunately he doesn't have a Synology to test with. Are you familiar with this error? I couldn't find much by Googling.

**Comment by Dr-Bean** [comment]
You might have the SynoCommunity Python package installed, but you are definitely not _using_ it to run this package. You can tell by the paths you're using: our Python package is installed in `/usr/local/python`, not `/usr/lib/python2.7`
Fix that first (and preferably use a virtualenv instead of installing directly into Python's system site, see existing Python packages on this repo), and then I might have some suggestions.

**Comment by cytec** [comment]
This isn't really an error with GazelleUI but timezone issue...
Synology tends to report the timezone as `local` which isn't handled by apscheduler and produces the Error you see, see: https://github.com/agronholm/apscheduler/blob/master/apscheduler/util.py#L82-L87

What might help: 
1. Try set your Timezone in DSM to GMT+0 and try starting the package if that works you should be able to restore the Timezone to the original value
2. Ask upstream (GazelleUI) to implement some kind of "catch" for this or the ability to set a timezone in config manually...

**Comment by bamtan** [comment]
Problem has been fixed upstream, thanks for the help!
