### ISSUE TITLE
Update deluge with a newer version of libTorrent.

### ISSUE THREAD

**Issue by decon89** [SynoCommunity/spksrc#2639]
Deluge v1.3.13-6 by Dr-Bean with libtorrent 1.0.6.0
on
1515+ with DSM 6.0.2

I'm having troubles getting connection to torrent that requires SSL handshakes. I'm getting this "Error: Network is unreachable" on my torrents. From searching the web, it seems that libtorrent 1.0.6.0 is too old to handle SSL. I've looked at the DSM package log, and it says "core:85 Starting libtorrent 1.0.6.0 session", thus I recon the synocommunity Deluge package uses libtorrent 1.0.6.0.

On my desktop PC, I use the same version of deluge, but it comes with libtorrent: 1.0.9.0. The SSL handshake works without any problems.

I would love to know if it's possible to have an update on the deluge package to include this newer version of libtorrent?

Any help is appreciated - Thanks!

**Comment by Dr-Bean** [comment]
See https://github.com/SynoCommunity/spksrc/issues/2634, that happens to be the exact same request.
I'll close this one. I'm working on it, if all goes well, I'll push out an updated package later today.

**Comment by Dr-Bean** [comment]
...thought I closed it already, guess not ;) Deluge 1.3.13-7 has been published on the repository.

**Comment by decon89** [comment]
Thanks man! will try it out now 👍
