### ISSUE TITLE
PlexPy does not start

### ISSUE THREAD

**Issue by mrsorbate** [SynoCommunity/spksrc#2640]
Hey,

PlexPy does not start

I have installed the PleyPy application from the Communityhub.

However, I do not get this started. "The package can not be run" <- Always the same error.

In the log is unfortunately nothing!

I am on DSM 6 (latest version). Admin account is enabled.

I need help :(

**Comment by palmfighter** [comment]
same here, no logging found, only this message:
{"last_check":"2017-02-06T10:02:32Z","pypi_version":"9.0.1"}

**Comment by ymartin59** [comment]
I will have a look

**Comment by cytec** [comment]
seems like the known "DSM 6 user creation bug": https://github.com/SynoCommunity/spksrc/issues/2216 PlexPy isn't DSM 6 ready yet

**Comment by mrsorbate** [comment]
This Error Shows up try to start on my other DS with DSM 5.2

https://cloud.githubusercontent.com/assets/25298257/22748126/6142791a-ee29-11e6-89c3-83f1bcbad272.png

I Dont know what i doing wrong :(

**Comment by mrsorbate** [comment]
This Error Shows up try to start on my other DS with DSM 5.2

https://cloud.githubusercontent.com/assets/25298257/22748126/6142791a-ee29-11e6-89c3-83f1bcbad272.png

I Dont know what i doing wrong :( 





I Dont know what i doing wrong :(

**Comment by ymartin59** [comment]
Your capture on DSM 5.2 is exactly what to expect as log content when everything goes right, no error visible there.

What seems wrong is the reported state after "Run". It is still show as "Stopped" whereas process is really running:
```
ps | grep plex
21988 plexpy-c 1019m S    /usr/local/plexpy-custom/env/bin/python /usr/local/plexpy-custom/var/plexpy/PlexPy.py --daem
```

Is it possible `dsm-control.sh` failed to report process availability based on PID file with `wait_for_status` and `daemon_status` ?

**Comment by cytec** [comment]
hm strange... might have an error in there somewhere... gonna check that tomorrow

**Comment by mbnn** [comment]
So this package will not work on DSM6 for now or?

**Comment by cytec** [comment]
@mbnn correct

**Comment by SuperDOS** [comment]
I got it running now but DSM telling me it is stopped.

**Comment by mbnn** [comment]
Would it now be possible to make this work with DSM6.1? :) How?

**Comment by SuperDOS** [comment]
@mbnn I modifed the /var/packages/plexpy-custom/scripts/start-stop-status and changed the start stop command. still it doesn't report back to DSM that it's runnig but it is :)

```
start_daemon ()
{
#    su ${USER} -s /bin/sh -c "HOME=${INSTALL_DIR}/var PATH=${PATH} ${PYTHON} ${PLEXPY} --daemon --pidfile ${PID_FILE} --config ${CFG_FILE} --datadir ${INSTALL_DIR}/var/"
    PATH=${PATH} ${PYTHON} ${PLEXPY} --daemon --pidfile ${PID_FILE} --config ${CFG_FILE} --datadir ${INSTALL_DIR}/var/
}

```

**Comment by mbnn** [comment]
Thx @SuperDOS :) This works now, got it running on DSM 6.1 (although indeed the DSM interface says its not running, it works fine!)

**Comment by ymartin59** [comment]
Running service as root is the only work-around available for the moment. Follow #2216

**Comment by mbnn** [comment]
The way @SuperDOS wrote, is working fine for me so.

**Comment by SuperDOS** [comment]
anyone know how to get status back running?
Guess daemon_status doesn't return back 1
`
daemon_status ()
{
if [ -f ${PID_FILE} ] && kill -0 `cat ${PID_FILE}` > /dev/null 2>&1; then
        return
    fi
    rm -f ${PID_FILE}
    return 1
}
`

**Comment by olloT** [comment]
any update on it? cytec? still doesnt work

**Comment by cytec** [comment]
i think DSM Support has been added to the repo and also spksrc lately but i think most of the packages still need to be transformed to the new generic installer format.

**Comment by Safihre** [comment]
Package converted for DSM6 support. Get it in #3138 and give us feedback there if it doesn't work.
After it's final release it will auto-update again via the official SynoCommunity repository.
