### ISSUE TITLE
domoticz does not appear in listing of package center

### ISSUE THREAD

**Issue by JosEikhout** [SynoCommunity/spksrc#2642]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_domoticz
_Package Version:_v2

_NAS Model:_ds214=play
_NAS Architecture:_
_DSM version:_DSM 6.0.2-8451 Update 9

### Expected behavior
Tell us what should happen i expected to see domoticz as one of the options to install in the package center but it does not appear

### Actual behavior
Tell us what happens instead i can see various synocommunity apps but not domoticz

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Dr-Bean** [comment]
Sorry, we currently do not provide a Domoticz package on our repository (well, besides the one package that I'll remove shortly...not sure how that came about)
