### ISSUE TITLE
After updating Deluge to version v1.3.13-7 it doesn't start running

### ISSUE THREAD

**Issue by rpgdev** [SynoCommunity/spksrc#2644]
After updating deluge doesn't want to start running now. Can I still get the previous version from anywhere?

### Setup
_Package Name:_ deluge
_Package Version:_  v1.3.13-7

_NAS Model:_ DS213j
_NAS Architecture:_ ARM
_DSM version:_ DSM 5.2-5967 Update 2

### Expected behavior
App should start after running it.

### Actual behavior
It never starts to run, it remains in the stopped state.

### Steps to reproduce
_1._ Update to latest version
_2._ Try to run the application

**Comment by bamtan** [comment]
Navigate to `/var/packages/deluge/scripts/` as root and run `./start-stop-script start`

**Comment by Theli93** [comment]
@bamtan  did you intend that instruction to be `./start-stop-status start` ?

`./start-stop-script start` yields:
> -ash: ./start-stop-script: No such file or directory

Using, `./start-stop-status start` yields:

> Starting Deluge ...
> /usr/local/deluge/env/lib/python2.7/site-packages/deluge-1.3.13-py2.7.egg/deluge/_libtorrent.py:59: RuntimeWarning: to-Python converter for boost::shared_ptr<libtorrent::alert> already registered; second conversion method ignored.
>   import libtorrent as lt

Though it still appears in Package Center as stopped and attempting to start from there (even after reboot) yields:
> Failed to run the package service.

 Your (modified) instruction does get it running, accessible and operating normally. It also appears to be required, manually, after a reboot.


**P.S.**
I know it's an inappropriate place for this, but this also appears to work for LazyLibrarian; which also seems to have ceased normal operation. The only notable difference being in the response:
>  Starting LazyLibrarian ...

**Comment by rpgdev** [comment]
I think in the end I just had to do the whole modification of the scripts that I seem to need to do (changing the user that executes it, etc.). I assumed I wouldn't need to do that after an update.
