### ISSUE TITLE
Radarr - In app update killed the app. 

### ISSUE THREAD

**Issue by madvtak** [SynoCommunity/spksrc#2652]
Hi all,

Anyone experiencing this issue? There was a new update tonight so i updated, within the app. After the updated downloaded completed, i was presented with the app has been updated click here to reload the page. I reload the page and it never loads. I check the package.

![image](https://cloud.githubusercontent.com/assets/18261123/22724318/2d6aa81a-ed7a-11e6-96d2-c89de4cab960.png)

I try to run the package, it says its starting but it never runs. 

![image](https://cloud.githubusercontent.com/assets/18261123/22724366/6d20b3a0-ed7a-11e6-8b4a-13e484e972e7.png)

I try to refresh the page a min or two later just in case it actually did start.

![image](https://cloud.githubusercontent.com/assets/18261123/22724377/8019b6f0-ed7a-11e6-87e4-c663765aec36.png)

The only way to fix this is to uninstall and start over from scratch again.

```
admin@Syno:/var/packages/radarr/scripts$ ./start-stop-status start
Starting Radarr ...
admin@Syno:/var/packages/radarr/scripts$
```

```
radarr@Syno:/var/packages/radarr/scripts$ ./start-stop-status start
Starting Radarr ...
radarr@Syno:/var/packages/radarr/scripts$
```

I try to start from SSH and this is what i am presented with.

In case someone wants to see the logs, not a lot of info /shrug

![image](https://cloud.githubusercontent.com/assets/18261123/22724561/e79fd33a-ed7b-11e6-9d7a-8af62ffca2b2.png)

**Comment by KaraokeStu** [comment]
Hi, please can you confirm your current installed dsm version?

**Comment by madvtak** [comment]
![image](https://cloud.githubusercontent.com/assets/18261123/22729160/59b06eb6-ed96-11e6-8e8b-32fb37a251bf.png)

**Comment by Fieze** [comment]
Same problem, DSM 6.0.2-8451 Update 9

**Comment by cytec** [comment]
https://github.com/SynoCommunity/spksrc/issues/2216

**Comment by KaraokeStu** [comment]
Your logs should be in /var/packages/radarr/target/var/.config/Radarr/UpdateLogs

**Comment by KaraokeStu** [comment]
@cytec since this installed originally without issue on both DSM 5 and 6, I don't think it is linked to #2216

**Comment by cytec** [comment]
yeah saw that on the second read too... nevermind than

**Comment by newkind** [comment]
Ok, so on my latest DSM 6 reboot actually helped but there is definitely conflict with Sonarr. I'm having issues with running both at the same time. If Sonarr is working, I can't connect to Radar. If I stop both and start firstly Radarr and then Sonarr - I can access Radarr but Sonarr rejects my connection. Odd.

**Comment by cytec** [comment]
@newkind sound's like something you should report upstream maybe? maybe thats something that comes from the "fork/renaming" stuff

**Comment by newkind** [comment]
They claim that SynoCommunity package is the culprit.

https://github.com/Radarr/Radarr/issues/663#issuecomment-278356094

**Comment by cytec** [comment]
hm... would be strange... afaik they don't use same ports or anything... can you run both apps on your local pc side by side?

**Comment by newkind** [comment]
I don't have idea, got them installed only on my NAS.

**Comment by KaraokeStu** [comment]
I can whip up a VM and try running them both side by side on both Windows and Ubuntu...

**Comment by KaraokeStu** [comment]
That said, I have both running side by side on my DSM 6 VM, but I have changed the ports on both (one uses 8081, the other 8083)

**Comment by cytec** [comment]
now im even more confused ^^
can't be package related and isn't an upstream problem then... might just reinstall those SPK`s and try again?

**Comment by newkind** [comment]
Ok, I found the culprit. They changed the default port from 8989 (Sonarr) to 7878 (Radarr), but they forgot to switch the default SSL port on which Radarr operates. By default is 8989 so the same as Sonarr thus the conflict.

**Comment by KaraokeStu** [comment]
@newkind Nicely done! Good spot!

**Comment by ressu** [comment]
Good catch. The reason why I didn't see a conflict was because I don't use SSL (on either). I'll be sure to update those both when I change the defaults for the package.

**Comment by ressu** [comment]
There is a branch that addresses this issue. It is a blind fix, since I'm in an airport and just about to hop in to a plane (so can't test whether upgrade wipes your config or if it even compiles) I just wanted to get this started so I don't forget about it.

**Comment by MostDefiantly** [comment]
Any word on the port defaults making it back into the parent package?

**Comment by ressu** [comment]
I will create the PR as soon as I have a chance to test the changes properly. I was out of the country for a week with limited possibilities for testing the changes. That's why the PR is still pending.

**Comment by KaraokeStu** [comment]
Drop a message here when its done and I'll get the changes compiled and published ASAP - in the mean time, good work @ressu !
