### ISSUE TITLE
(re)Start properly crediting package authors on synocommunity.com

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2657]
The `author` field on the package view on synocommunity.com/package/$package is set to the uploader by default (not the Maintainer in INFO, as those don't necessarily have the same value). Over time, that means that a lot of authors aren't properly credited for their work. So, let's fix that. 

How it works:
- Make sure you use your Github account name in the package Maintainer field;
- Use your Github account name to register on synocommunity.com/register;
- Tell me that you've registered, so we can link the two.

Started with some people here: https://github.com/SynoCommunity/spksrc/pull/2643#issuecomment-278968908
I'll have to start comparing packages with the original PR's for the rest...

**Comment by Dr-Bean** [comment]
@yeled for `ncdu`
@peeter123 for `rsnapshot`
@rjblake for `plexpy-custom`

**Comment by Dr-Bean** [comment]
@KaraokeStu for `sabnzbd-testing` ;)

**Comment by Dr-Bean** [comment]
@eelcohn for `tcl`
@biyiklioglu for `fdupes`
@adchevrier for `nzbhydra`
@markbastiaans for `curaengine`

**Comment by KaraokeStu** [comment]
Aaaaaw thanx 👍

**Comment by Dr-Bean** [comment]
@KaraokeStu Well, on the flipside, packages that you're currently credited for will be taken away :P

**Comment by cytec** [comment]
@Dr-Bean you've got that working already? chromaprint is still crediting you ;)

**Comment by Dr-Bean** [comment]
Well, it's not like this is automated...I'm actually checking who registered, and changing the author based on it. Who created that package? You? :D

**Comment by Dr-Bean** [comment]
@ressu for `radarr`...done :)

**Comment by cytec** [comment]
yup. ah i see. thought you changed it to do this on some kind of automation ^^
So basically its still the same? the one who publishes the first package will be credited untill the maintiner registers after the upload? 

We should fix that stuff on the repo side once @Diaoul finished moving ;)

**Comment by Dr-Bean** [comment]
yep. For the record, since I have no clue: can you change the author of any package yourself, just for your own uploads , or none at all?

**Comment by cytec** [comment]
ah... lol... seems like i can actually do that myself :D well... never checked that anyways ... im good than thanks :D

**Comment by adchevrier** [comment]
I have registered

**Comment by Dr-Bean** [comment]
`nzbhydra` is done. 
@adchevrier, @ressu, you both should have received an email to confirm your accounts (check spam if not otherwise visible)

**Comment by markbastiaans** [comment]
Registered.

**Comment by ressu** [comment]
@Dr-Bean nope, never received one. Checked SPAM when I registered and again now.
