### ISSUE TITLE
Sabnzbd 1.2.0-20 Shows error un executing postdownload Python script.

### ISSUE THREAD

**Issue by WalterBorgstein** [SynoCommunity/spksrc#2659]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Sabnzbd
_Package Version: 1.2.0-20

_NAS Model: Synology DS413
_NAS Architecture:_Synology?
_DSM version:_DSM 6.0.2-8451 Update 9

### Expected behavior
Sabnzbd should execute a script called /usr/local/sabnzbd/var/scripts/sabToSickBeard.py to update Sickbeard after the download in Sabnzbd

### Actual behavior
Python script "/usr/local/sabnzbd/var/scripts/sabToSickBeard.py" does not have execute (+x) permission set
Since the new version it will show the error above.

<img width="785" alt="schermafbeelding 2017-02-10 om 23 57 30" src="https://cloud.githubusercontent.com/assets/15366175/22847351/bb94b2ec-efec-11e6-9679-badf66355cd8.png">

More information can be found at https://forums.sabnzbd.org/viewtopic.php?t=22359
I would expect an update is required of the Sapnzbd package for Synology to cope with this. I don't have the knowledge or access to perform that, but am more than willing to help someone who can!
Thanks!

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by KaraokeStu** [comment]
This is not a bug with the package, but with your installation of the scripts. You'll need to ssh in and set the permissions yourself.

**Comment by WalterBorgstein** [comment]
Thanks for responding to my issue. I did not change anything on the system. I don't ssh in on it. In the last update this behaviour changed. In the link I attached I read that it had nothing to do with the permissions on the script files. However, to exclude it, I will try and ssh in today and check for you. I will get back later.

**Comment by WalterBorgstein** [comment]
I changed the chmod of the scripts. I'm not sure why they were incorrect. I did not change them myself. All is working now. Thanks.
