### ISSUE TITLE
Meta: Package list, DSM6 status and their associated issues.

### ISSUE THREAD

**Issue by Dr-Bean** [SynoCommunity/spksrc#2661]
In preparation for DSM6 packages being made ready and published, here's an overview of the status. I'll correct and add as I work through the packages.

DSM-related problems/questions for a particular package should be discussed in the mentioned issues. Where an issue currently does not exist, one can be created.

PACKAGE|STATUS|ISSUE|COMMENT|
----|----|----|----|
adminer|No known issues|#2662|WEB, PHP(?), Check dependency on webstation/php packages|
beets|No known issues|-|CLI|
bicbucstriim|-|-|WEB, Check dependency on webstation package|
~bitlbee~|Retired|#2552|USER, see #2216, retired with #4208|
boxbackup-client|No known issues|-|CLI|
chromaprint|No known issues|-|CLI|
cops|Beta published|#2520|WEB, PHP, Check dependency on webstation/php packages|
couchpotatoserver|-|#2104|USER, see #2216|
couchpotatoserver-custom|-|-|USER, see #2216|
curaengine|No known issues|-|CLI|
darkstat|No known issues|-|Uses root|
ddrescue|No known issues|-|CLI|
debian-chroot|-|#1910|Interface broken|
deluge|-|-|USER, see #2216|
diskutils|No known issues|-|CLI|
domoticz|-|-|USER, see #2216|
duplicity|No known issues|-|CLI|
ejabberd|-|#2260|USER, see #2216|
fdupes|No known issues|-|CLI|
fengoffice|-|#2348|WEB, MYSQL, Release with version bump to fix mysql commands, outdated|
ffmpeg|-|-|Release with version bump to fix warnings|
ffsync|-|#2093|WEB, MYSQL, Release with version bump to fix mysql commands|
flexget|-|-|USER, see #2216|
full-text-rss|-|-|USER, see #2216|
gateone|-|#2340|USER, see #2216|
gentoo-chroot|-|-|Interface broken|
git|No known issues|-|CLI|
git-server|-|#2255|USER, see #2216|
gnupg|No known issues|-|CLI|
haproxy|-|#2159|USER, see #2216|
headphones|-|-|USER, see #2216|
headphones-custom|-|-|USER, see #2216|
homeassistant|-|-|USER, see #2216|
horde|-|#2333|WEB, MYSQL, Release with version bump to fix mysql commands, outdated|
htop|No known issues|-|CLI|
htpcmanager|-|-|USER, see #2216|
icecast|-|-|USER, see #2216|
imagemagick|No known issues|-|CLI|
irssi|No known issues|-|CLI|
jackett|-|#2635|USER, see #2216|
jappix|-|#2635|Retire, see #2635|
lazylibrarian|-|#2336|USER, see #2216|
links|No known issues|-|CLI|
lirc|-|-|Unknown|
mantisbt|-|-|WEB, MYSQL, Check dependency on webstation package, Release with version bump to fix mysql commands|
maraschino|-|-|USER, see #2216|
mc|No known issues|-|CLI|
mediainfo|No known issues|-|CLI|
memcached|-|-|USER, see #2216|
mercurial|No known issues|-|CLI|
monit|-|-|USER, see #2216|
mono|Published|#2298|Update+Version bump for final fix|
mosquitto|-|#2581|USER, see #2216|
museek-plus|Retired|-|USER, see #2216|
mutt|No known issues|-|CLI|
mylar|-|-|USER, see #2216|
nano|No known issues|-|CLI|
ncdu|No known issues|-|CLI|
nmap|No known issues|-|CLI|
nzbget|-|#2526|#2420 to update to 17.x+|
nzbget-testing|-|-|#2185 to update to 17.x+|
nzbhydra|-|-|USER, see #2216|
nzbmegasearch|-|-|USER, see #2216|
octoprint|-|#2386||
oscam|-|#2636|Retire?, see #2636|
owncloud|-|#2136|WEB, MYSQL, Check dependency on webstation package, Release with version bump to fix mysql commands|
plexivity|-|-|USER, see #2216|
plexpy-custom|-|-|USER, see #2216|
plowshare|No known issues|-|CLI|
pyload|-|#2259|USER, see #2216|
python|No known issues|-|CLI|
python3|No known issues|-|CLI|
radarr|-|-|USER, see #2216; NEW|
rdiff-backup|No known issues|-|CLI|
redis|-|-|USER, see #2216|
roundcube|-|-|WEB, MYSQL, Check dependency on webstation package, Release with version bump to fix mysql commands|
rsnapshot|No known issues|-|CLI|
rutorrent|-|#2215|WEB+USER|
sabnzbd|-|#2416|USER, see #2216|
sabnzbd-testing|Retired|#2309|USER, see #2216|
salt-master|-|-|Uses root|
saltpad|-|-|USER, see #2216|
selfoss|-|#2052, #2210|WEB, MYSQL, Check dependency on webstation package, Release with version bump to fix mysql commands|
shairport-sync|-|#1877|USER, see #2216|
sickbeard-custom|-|#2099|USER, see #2216|
sickrage|-|-|Not published|
sonarr|-|#2444|USER, see #2216, Set config dir|
squidguard|-|-|USER, see #2216|
sshfs|No known issues|-|CLI|
sslh|-|-|Uses root|
subliminal|-|#2107|Interface broken|
syncthing|-|-|USER, see #2216, add install/upgrade wizard|
syncthing-inotify|-|-|USER, see #2216; NEW|
tcl|No known issues|-|CLI|
testdisk|No known issues|-|CLI|
tmux|No known issues|-|CLI|
transmission|-|#1880, #2434|USER, see #2216|
tt-rss|-|#2052, #2210|WEB, Check dependency on webstation package, Release with version bump to fix mysql commands|
tvheadend|-|-|USER, see #2216|
umurmur|-|-|USER, see #2216|
vim|No known issues|-|CLI|
znc|-|#2294|USER, see #2216|
zsh|No known issues|-|CLI|

**Comment by th0ma7** [comment]
Closing in favor of DSM7 package status.
