### ISSUE TITLE
Sonarr Service Fails to Start after NAS Reboot

### ISSUE THREAD

**Issue by mydevpeeps** [SynoCommunity/spksrc#2663]
### Package
_Package Name:_ Sonarr
_Package Version:_ 20170106-9

### Supporting Package(s)
_Package Name:_ Mono
_Package Version:_ 3.10.0-4

### Setup
_NAS Model:_ DS1512+
_NAS Architecture:_ Intel Atom Dual-Core 64-bit w/3G RAM
_DSM version:_ 6.0.2-8451 Update 9

### Expected behavior
Installed Sonarr w/mono as pre-setup admin user "seedbox". Setup and Configured Sonarr. Config to be retained post-reboot of NAS.

### Actual behavior
After reboot of NAS, configuration was gone and was unable to start Sonarr service.

### Steps to reproduce
_1._ Install Sonarr/Mono from Community as a pre-setup admin user other than nzbdrone.
_2._ Configure Sonarr.
_3._ Restart NAS.
_4._ Attempt to Load Sonarr UI/Start Service via Synology DSM UI.

### Steps for workaround
_#### NOTE: Next upgrade may revert these changes, requiring it to be modified again_
_1._ Edit /var/packages/nzbdrone/scipts/start-stop-status.
_2._ Change USER="${PACKAGE}" to USER="seedbox" (because that's the user I chose).
_3._ Save the changes. Ensure via SSH it is not running: "ps -ef | grep -i nzbdrone" and kill the process if it is.
_4._ Start the Sonarr Package Service via the Synology DSM UI.

_(Additional Info):_
I am not entirely sure if the steps I took to restore the back from /<home_dir>/.config/NzbDrone/Backups to /<home_dir>/.config/NzbDrone was a required step, so I will mention it here just in case. This step would be implemented prior to step _4_ above.

### Suggested Fixes
_1._ Add logic to /var/packages/nzbdrone/scripts/postinst to replace username with chosen user after installation. 
_2_. Add logic to /var/packages/nzbdrone/scripts/preupgrade to store the selected username to the side, to be re-injected back into the above script using /var/packages/nzbdrone/scripts/postupgrade.
_3_. Alternative to 1 & 2: Require the installation user to be a user called nzbdrone with admin rights and implement pre-install checks to prevent installation if this requirement is not met.

#### Package log
```
|| Installing package version="20170106-9" - Thu Jan 26 21:12:58 EST 2017 ||
|| Package Install Completed - Thu Jan 26 21:12:59 EST 2017 ||
```

**Comment by cytec** [comment]
uhm... why are you messing with the user who runs the spk in the first place? every spk runs either under it's own user... or root for some i guess.
No need to "choose" a username or anything at all... if you'd like to... i don't get it...

**Comment by mydevpeeps** [comment]
the value of this USER variable in the script determines where all of the config files go, what user it attempts to write to the directories as.. and what user the service runs as. It's a VERY important value, and it being defaulted to "nzbdrone", just because that's the package name, assuming that user actually exists, is asinine. When i installed it I specifically told it to run as this user, and it ended up running as root anyway (as I noticed only the directors sonarr created were owned by root). After I changed it back to seedbox where it was supposed to be, I had to go back and recursively change the owner of my share to get it to be able to write again when it picks up the files for rename/move.  Why even ask me what user if it's just going to ignore it anyway?

**Comment by cytec** [comment]
uhm... Sonarr isn't asking you for any user to specify. It's using the `nzbdrone` user and should be creating it when it's installed... that's how SPK's work and that's how Synology tells developers to handle it... where config is stored should be handled by the start-stop script by passing it as arg or something like that... i don't know why thats not the case i didn't create that package but for every other Package we save the config and stuff inside the packages var folder...

The reason there is no user created might be because you are on DSM6 and sonarr isn't yet DSM6 compatible... because user creation methods changed and thus no user is created on install time.

**Comment by Dr-Bean** [comment]
Already changed the user to `sc-sonarr` in the `dsm6` branch, but for backwards-compatibility reasons, we can't just switch over for existing packages. So the legacy user will continue to be `nzbdrone`.

Wrt to the home dir for Sonarr, the configuration dir (`.config`) is auto set to the user's home dir on DSM5 (see the `adduser` command in installer.sh), appended with `.config`. That amounts to `/usr/local/nzbdrone/var/.config`.
For DSM6, this (again...) is handled differently. I haven't gotten to that yet: we need to specify the actual location where the config is located for a subset of packages. It applies to Sonarr for example, probably Radarr as well, but luckily, a lot of other packages already specify the config dir in one way or another.

**Comment by mydevpeeps** [comment]
OK. Thanks. So what I experienced, I think, is what I have read with the bug that doesn't create that user correctly on DSM 6, and then on reboot the DSM startup cleanup scripts delete the user (nzbdrone) and that could be why a bunch of folders were owned by userid 100 (because I understand it deletes users that aren't in both password & shadow - memory is a little fuzzy). I wonder, then, if this could be used as some kind of workaround until we are DSM 6 qualified. 

One last point of interest - once it is DSM 6.0 qualified, can I upgrade, backup, uninstall, install, restore from my current install to get the perms right?

**Comment by Dr-Bean** [comment]
@mydevpeeps Sonarr allows you to make a backup that you can restore, so if you follow that method, a cautious yes _if_ Sonarr effectively chowns restored files to the current user...I assume it does, but I've never had a need to find out.

As for a workaround, people have been coming up with all sorts of methods that might or might not work when updated packages will be released. We can only do our best to provide a working upgrade path from vanilla packages, and even that is difficult enough. All other bets are off.

**Comment by Shmp** [comment]
Sonarr won't start anymore here either. Just updated to DSM 6.1-15047 Update 1. Can't get any logs that tells why it crashed...

**Comment by KaraokeStu** [comment]
Logs should be in /var/packages/nzbdrone/target/var/. config/NzbDrone

Note: that path is from memory... It might be a tiny bit wrong!

**Comment by krishjuh** [comment]
@Dr-Bean is there a timeline when Sonarr is going to be fixed for DSM 6.1?

**Comment by mydevpeeps** [comment]
This is exactly why I'm sitting here on DSM 6.0 and not on DSM 6.1. I knew it would crash. I was told prior that Sonarr isn't even qualified to work property on DSM 6.0 because of the way users are registered much less DSM 6.1. If you find a solution let us all know so we can upgrade to DSM 6.1 :-)

**Comment by mydevpeeps** [comment]
These are the items in the DSM 6.1 Release Notes that scared me away from upgrading (because I use Sonarr):

- Due to infrastructure update, packages will need re-initialization after upgrading to DSM 6.1. The process will occupy a higher CPU usage and can take up to an hour depending on the number of packages installed.

- Automatically updates incompatible packages after the installation of DSM 6.1 to boost your upgrading experience.

- Some of DSM’s built­-in features have been modularized into packages to ensure better system maintenance and update flexibility.

**Comment by krishjuh** [comment]
Hi mydevpeeps: i've got this working now and it is stable for a week on the latest version of DSM6.1
I did allot, so don't know what the right setting is.. and i think security minded this isn't the right sollution.. but it works :-)

install Sonarr with the automatic install of mono from synocommunity.
After that install the mono version of synology itself (it is a beta so tick the beta box in package center)

Change the mono line in:
/var/packages/nzbdrone/scripts/start-stop-status

MONO_PATH="/var/packages/Mono/target/usr/local/bin"

this is the mono path of the mono version from synology.. 
This worked for me.. 

also in shared folders / permissions, gave the groups: sc-downoads and sc-media read/write permissions on al my folders.

**Comment by Safihre** [comment]
DSM6 compatible version of the package is expected to be released soon. It can already be installed by downloading it from here #3138.
After the official release on SynoCommunity, the package will auto-update from the official release.
