### ISSUE TITLE
[Duplicity] Unable to encrypt using gnupg

### ISSUE THREAD

**Issue by yuroller** [SynoCommunity/spksrc#2670]
### Setup
_Package Name:_ duplicity
_Package Version:_ v0.7.11-5
_Package Name 2:_ gnupg
_Package Version 2:_ v2.1.6-2

_NAS Model:_ DS212+
_NAS Architecture:_ 88f6282 (armv5)
_DSM version:_ DSM 6.0.2-8451 Update 9

### Expected behavior
Being able to encrypt backup archive

### Actual behavior
duplicity exits because passes to gnupg the unrecognized option:
```
--pinentry-mode=loopback
```

### Steps to reproduce
_1._ Create a backup profile with encryption
_2._ duply profle backup
_3._

### Workaround
Commented some lines in /usr/local/duplicity/env/lib/python2.7/site-packages/duplicity/gpg.py

```
        if globals.use_agent:
            gnupg.options.extra_args.append('--use-agent')
        elif profile.gpg_major == 2:
            pass
            # This forces gpg2 to ignore the agent.
            # Necessary to enforce truly non-interactive operation.
            #if platform.platform().startswith('Linux'):
            #    gnupg.options.extra_args.append('--pinentry-mode=loopback')
```

**Comment by Dr-Bean** [comment]
Please add actual steps to reproduce, thanks.
It looks like you're not using the correct `gpg2` binary. Please confirm you're using `/usr/local/gnupg/bin/gpg2`, not `/usr/bin/gpg2`.

**Comment by yuroller** [comment]
You are right: did not know there was also a system gnupg package /bin/gpg.
That was first in the PATH.
$ which gpg
/bin/gpg

$ gpg --version
gpg (GnuPG) 2.0.28
libgcrypt 1.6.5
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA, RSA, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB

**Comment by Dr-Bean** [comment]
Perfect. The problem is that there's not really a nice way to tell Duplicity to use our gpg binary, so you end up with setting PATH yourself. We can patch gpg.py to force the correct binary I suppose, although I'm not really a fan of that approach here. @adrien-delhorme Opinions?

**Comment by yuroller** [comment]
I am running duplicity with the DSM provided gpg (runs weekly using DSM scheduled operations) which seems not supporting --pinentry-mode option and it works correctly.
Probably the check of gpg version inside duplicity is not correct, because gpg 2.1.6 synocommunity package seems to support pintentry-mode option while DSM provided 2.0.28 does not.
```
$ /usr/local/gnupg/bin/gpg2 --pinentry-mode=ddd
gpg: invalid pinentry mode 'ddd'
$ /bin/gpg2 --pinentry-mode=ddd
gpg: invalid option "--pinentry-mode=ddd"
```
Probably a bug in duplicity.

**Comment by Dr-Bean** [comment]
No, Synology just compiled their gpg binary without the correct compiler options enabled.

**Comment by yuroller** [comment]
The alternative to patching gpg.py for using synocommunity gnupg package is to have a guide somewhere inside duplicity package helping people configuring with the right gpg binary, but I do not know how many people would read it or even notice it.

**Comment by Dr-Bean** [comment]
A guide of sorts is certainly an option, and maybe not a bad idea regardless.
The two options we have for that are an install wizard or a wiki page. 
The install wizard looks a bit like this approach: https://github.com/SynoCommunity/spksrc/blob/master/spk/couchpotatoserver/src/wizard/upgrade_uifile. It has limitations in # of characters, but also in visibility: one click and you won't see it again.

The second option could be adding a new wiki page and link to it from HELPURL so it shows up in Package Center as a link. In it, you can explain the ins and outs of the package (more detailed than just a wizard entry: can't have too). Examples of that approach at https://github.com/SynoCommunity/spksrc/wiki/Package-Documentation-Index

The second option would probably fit better for cases where people didn't read the wizard (or forgot what it said) and open an issue: we can point to a wiki page, rather then an old issue or something.

**Comment by yuroller** [comment]
A guide on the wiki, in my opinion, would be great because it is not so easy to set up duply and duplicity in DSM.
For example, in order to schedule unattended runs of duply, you need to set HOME variable before executing the command in DSM scheduled operations.

**Comment by Dr-Bean** [comment]
Well, go right ahead and create the page if you have knowledge to help others :) As a user, you're probably more familiar with duplicity then I am, I just update packages and break them in the process...

Start with whatever thing you ran into, and it can be expanded from there. When it's setup, we can add the URL to the package for the next release.
