### ISSUE TITLE
Update NZBget to v18

### ISSUE THREAD

**Issue by d-zalewski** [SynoCommunity/spksrc#2675]
v18 is out https://github.com/nzbget/nzbget/releases/tag/v18.0

**Comment by bjornwahman** [comment]
Yes please update to v18

**Comment by Dark2004** [comment]
Yes please if it's possible as i have seen that for some product i can not be done easily

**Comment by Trapperjohn61** [comment]
I would also appreciate an update to v18. There was a v17 that was not pkgd. 
Thank you for your help, 
Bryan

**Comment by cytec** [comment]
still not sure if v18 compiles with synologys gcc version

**Comment by DoctorX666** [comment]
A jump from v16 to v18 would be greatly appreciated. Many thanks!

**Comment by bjornwahman** [comment]
Running v18 on my synology nas 415+ installed manually through cli.

**Comment by Trefex** [comment]
Agreed. Please provide update to this great package!

**Comment by cytec** [comment]
spamming this issue won't make it happen any sooner... Synologys Toolchains use GCC 4.9 (afaik) which doesn't fully support C++11 which is needed since v17. Basically you'll have to wait till DSM6 support is added to spksrc or install it manually

**Comment by KaraokeStu** [comment]
@bjornwahman If you fancied putting together a temporary guide to the steps required to install through the CLI, this might help some people until we have the DSM 6 toolchains released to us

**Comment by Trapperjohn61** [comment]
I appreciate that the Synology toolchains are not available yet for dsm6 as mentioned by @cytec
I would also appreciate as @KaraokeStu has requested a guide to install through the cli.
If @bjornwahman would create one it would be very helpful of course anyone that can help the community would be appreciated. 
Normally I would not ask but we are now 2 full versions behind and the 3rd v19 is already being worked on. 
Thank you for your help, 
Bryan

**Comment by bjornwahman** [comment]
I followed the guide on https://github.com/nzbget/nzbget/wiki/Installation-on-Linux
Here is the step I took to get it running on my Synology DS415+, I take no responibility for below guide, I am sure there is better ways to do it but this worked for me.
SSH into your nas and login as admin.
Create a folder under /usr/local/ I called it nzbgetb
`cd /usr/local/`
`sudo mkdir nzbgetb`
`cd nzbgetb`
Now use wget to donwload the install script from github.
`sudo wget https://github.com/nzbget/nzbget/releases/download/v18.0/nzbget-18.0-bin-linux.run`
Chmod it so you can execute the script.
`chmod +x nzbget-18.0-bin-linux.run`
now run it with
sudo ./nzbget-18.0-bin-linux.run
`cd nzgetb`
This step requires some basic knowledge about vi, you can use another text editor if you have one.
`sudo vi nzbgetb.conf`
scroll down in this file until you see
> # Port which NZBGet server and remote client use (1-65535).
#
# NOTE: The communication via this port is not encrypted. For encrypted
# communication see option <SecurePort>.
ControlPort=6789
Change this to something else I used 6969 but you can use what you want but not a port that anything else is listening on offcourse, 
save the file
Ok time to test things out
run nzbget in on the console
`sudo ./nzbget -s`
you should see "ready to receive nzb" or something.
quit out from this (ctrl c?, dont remember)
for easy startup I created a script (lol "I creted" I found it somewhere cant remember where but credits goes out to that person.
you should still be in /usr/local/nzbgetb/nzbget
sudo vi nzbget.sh
_#!/bin/sh
# Start/stop the NZBget daemon.
#
case "$1" in
start)   echo -n "Start services: NZBget"
/usr/local/nzbgetb/nzbget/nzbget -D
;;
stop)   echo -n "Stop services: NZBget"
/usr/local/nzbgetb/nzbget/nzbget -Q
;;
*)   echo "Usage: $0 start|stop"
exit 1
;;
esac
exit 0_

Cut and paste the italic part above in the file we created and then save it.
make it executeable
`sudo chmod +x nzbget.sh`
If you want you can try it out
`sudo ./nzbget.sh start`
`sudo ./nzbget.sh stop`
This should start nzbget in daemon form (the way we like it :))
Now go to your diskstations GUI and create a triggered task (Control panel > scheduled tasks >create triggered task > user defined script.
On Genral name: NZBget
On User: Root
On general event: Boot-up
On task settings point out the script we created:
/usr/local/nzbgetb/nzbget/nzbget.sh start
Optional If you want you can send email when its triggered.
If its not running now you can trigger the script by right clicking it and select run.
you should now be able to connect to it through your favorite browser.
http://ip-of-nas:6969 (ofcourse the port you choose earlier)
Thats it.

For the sake of this guide I run everything as root this isnt optimal so you should create a user and then in the triggered task set that user to start the script there are other guides that covers this so I wont cover it here.

**Comment by cytec** [comment]
shouldn't it work by just downloading the correct binary and replace the old one? if that works, i think that's the "simplest" solution... no need to change any script's or something like that

**Comment by superost** [comment]
I was in the same situation, wanting to upgrade to v18 stable and I followed the advice from @cytec. I take no responsibility, if you mess up though. Backup your nzbget folder just in case (for me it was /volume1/@appstore/nzbget). The steps I took:
1. Download the binary release from [here](https://github.com/nzbget/nzbget/releases/download/v18.0/nzbget-18.0-bin-linux.run)
2. Extract the installer (on Ubuntu it's `sh ./nzbget-18.0-bin-linux.run --unpack`)
3. Pick the right binary (depends on your cpu architecture)
4. Replace the binary and webui/script files on the DS (directory structure on DS is slightly different)
5. Start nzbget from Package Manager

And it works... so far. I didn't replace unrar and 7z, since they were newer in the SynoCommunity release.

**Comment by Trapperjohn61** [comment]
Hi, 
   Do you use sonarr with nzbget? If so do you see this error after upgrading to 18 by just doing the copy procedure you described? 
Component	Message	Time
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	1:28pm
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	1:16pm
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	1:05pm
EpisodeSearchService	Episode search completed. 1 reports downloaded.	12:56pm
DownloadService	Report sent to Nzbget. Scorpion.S02E08.Area.51.720p.WEB-DL.DD5.1.H.264-NTb-Chamele0n	12:56pm
Nzbget	Adding report [Scorpion.S02E08.Area.51.720p.WEB-DL.DD5.1.H.264-NTb-Chamele0n] to the queue.	12:56pm
DownloadDecisionMaker	Processing 113 releases	12:55pm
Newznab	http://www.nzbstars.com/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=25&rid=40717&season=2&ep=8: No such item	12:55pm
Newznab	Usenet-crawler extra (nzedb) HTTP request failed: [500:InternalServerError] [GET] at [https://nzedb.usenet-crawler.com/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=281630&rid=40717&tvmazeid=44&season=2&ep=8]	12:55pm
HttpClient	HTTP Error - Res: [GET] https://nzedb.usenet-crawler.com/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=281630&rid=40717&tvmazeid=44&season=2&ep=8: 500.InternalServerError	12:55pm
NzbSearchService	Searching 14 indexers for [Scorpion : S02E08]	12:55pm
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	12:42pm
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	12:41pm
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	12:36pm
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	12:31pm
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	12:30pm
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	12:22pm
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	12:18pm
RssSyncService	RSS Sync Completed. Reports found: 3970, Reports grabbed: 0	12:03pm
DownloadDecisionMaker	Processing 3970 releases	11:56am
Newznab	Indexer Usenet Crawler rss sync didn't cover the period between 03/08/2017 15:50:15 and 03/08/2017 16:56:03 UTC. Search may be required.	11:56am
Newznab	An error occurred while processing feed. https://nzbnoob.com/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100: '', hexadecimal value 0x08, is an invalid character. Line 642, position 62.	11:55am
Newznab	Usenet-crawler extra (nzedb) HTTP request failed: [500:InternalServerError] [GET] at [https://nzedb.usenet-crawler.com/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100]	11:55am
HttpClient	HTTP Error - Res: [GET] https://nzedb.usenet-crawler.com/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100: 500.InternalServerError	11:55am
RssSyncService	Starting RSS Sync	11:55am
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	11:46am
SceneMappingService	Updating Scene mappings	11:31am
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	11:16am
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	11:13am
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	11:12am
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	11:09am
EpisodeSearchService	Episode search completed. 1 reports downloaded.	10:50am
DownloadService	Report sent to Nzbget. Scorpion.S02E07.Crazy.Train.720p.WEB-DL.DD5.1.H.264-NTb	10:49am
Nzbget	Adding report [Scorpion.S02E07.Crazy.Train.720p.WEB-DL.DD5.1.H.264-NTb] to the queue.	10:49am
DownloadDecisionMaker	Processing 509 releases	10:46am
Newznab	http://www.nzbstars.com/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=25&rid=40717&season=2&ep=7: No such item	10:45am
NzbSearchService	Searching 14 indexers for [Scorpion : S02E07]	10:45am
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	10:39am
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	10:37am
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	10:31am
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	10:28am
DownloadMonitoringService	Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.	10:18am
ExistingExtraFileService	Found 0 extra files	10:12am
ExistingOtherExtraImporter	Found 0 existing other extra files	10:12am
ExistingSubtitleImporter	Found 0 existing subtitle files	10:12am
ExistingMetadataImporter	Found 0 existing metadata files	10:12am
DiskScanService	Completed scanning disk for The Young Indiana Jones Chronicles	10:12am
DiskScanService	Scanning disk for The Young Indiana Jones Chronicles	10:12am
RefreshSeriesService	Skipping refresh of series: The Young Indiana Jones Chronicles	10:12am
ExistingExtraFileService	Found 0 extra files	10:12am
1 / 112
5,561
×

Unable to retrieve queue and history items from Nzbget: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.

**Comment by superost** [comment]
Not sure about that one - I googled that error, and it could be an incompatibility involving Mono.. But that's out of my league really. So I can't really help ya with that.

**Comment by Safihre** [comment]
Test package for new-style NZBGet has been released: #3138.
We no longer compile it here on the repo, but fetch the latest official installer from NZBGet.
During package installation you can choose if you want the latest stable or testing release. After this you can use NZBGet's internal update system to do updates. It also includes updates to user-management.
We hope to soon publish this on the official repo.
