### ISSUE TITLE
Meta: Package list, DSM6.1 status and their associated issues

### ISSUE THREAD

**Issue by abraxxa** [SynoCommunity/spksrc#2677]
Similar to issue #2661 I'd like to start a list of packages with info if they work on DSM 6.1 or have issues.
I'll upgrade to 6.1 soon and will report back my findings.
If someone already upgraded and found something please add it to this issue.

**Comment by abraxxa** [comment]
Transmission works as far as I can tell.

**Comment by Dr-Bean** [comment]
There shouldn't be that much of a difference between DSM6.0 and DSM6.1. You can read the other issue as DSM6.* ;)

**Comment by Dr-Bean** [comment]
I'm going to close this one, seeing as the other issue will serve as a central point for any version of DSM6.

If a problem pops up for a package, please use #2661 to find the associated issue. When you comment in there, follow  the [Guidelines](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issue-content) for the information that you should add.

If an issue does not already exist for a package, you can open a new issue. Make sure to fill out the template you're shown, and link back to #2661 somewhere.

Thanks.
