### ISSUE TITLE
Issue building https://github.com/sabnzbd/sabyenc with wheels

### ISSUE THREAD

**Issue by KaraokeStu** [SynoCommunity/spksrc#2681]
This is being used as part of the sabnzbd-testing package for 2.0.0 Alpha 1

I'm trying to get this building, but it is failing:

> Running setup.py clean for sabyenc
> Failed to build sabyenc
> Installing collected packages: sabyenc
>   Running setup.py install for sabyenc ... error
>     Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_irIOY/sabyenc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-GdRl00-record/install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build
>     running build_ext
>     building 'sabyenc' extension
>     creating build
>     creating build/temp.linux-x86_64-2.7
>     creating build/temp.linux-x86_64-2.7/src
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/sabyenc.c -o build/temp.linux-x86_64-2.7/src/sabyenc.o -O2
>     In file included from src/sabyenc.c:22:0:
>     src/sabyenc.h:22:20: fatal error: Python.h: No such file or directory
>      #include <Python.h>
>                         ^
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 

Any tips on getting this working, @Dr-Bean or @cytec ?

**Comment by KaraokeStu** [comment]
@Safihre is there a reason that you're using Python.h - I've not seen it in other wheels (Not that I've looked that much!)

**Comment by Safihre** [comment]
It's needed for any Python wheels that have C-code, it has all the Python headers. 
Normally it comes in packages like `python-dev` or `python-devel`.

**Comment by Safihre** [comment]
I just pushed new precompiled-wheels to PyPi using Manylinux1, maybe you can try again just using `pip install sabyenc`? 
No need for extra headers then!

**Comment by KaraokeStu** [comment]
This does work well, however I'll need to check it works for all archs

**Comment by Safihre** [comment]
Doubt it will work for the ARM based ones.. 
But this doesn't work: https://github.com/SynoCommunity/spksrc/wiki/Using-wheels-to-distribute-Python-packages#packages-with-c-extensions ?
It specifically talks about using `python-cc.mk`, so I imagine it includes these headers of course?

**Comment by KaraokeStu** [comment]
Managed to sort this, it was trying to use Python 2.7.13, when I hadn't recompiled the native python (I was still on 2.7.11)
