### ISSUE TITLE
[multiple packages] Won't run on a fresh install of DSM 6.1

### ISSUE THREAD

**Issue by waterdog1234** [SynoCommunity/spksrc#2682]
### Setup
Reproduced with these packages: Couchpotato, SABnzbd, Sonarr

_NAS Model: DS412+
_NAS Architecture: intel
_DSM version: DSM 6.1-15047

### Expected behavior
Packages should be able to run

### Actual behavior
Packagecenter cannot run the packages after the install...

### Steps to reproduce
_1._ Install a fresh copy of DSM on a new harddrive
_2._ Install any of the mentioned packages
_3._ Try to run the packages > error
_4._ Trying to run the packages from SSH using the "start-stop-status" just result in a "su: permission denied"...

I know it is possible to do a work-around on this issue by changing the username in the "start-stop-status" script... this allow packages to run but in my case this still result in some strange behavior of the packages... 

#### Package log
```
There is no log available on the packages
```
#### Other logs
[synopkg.log](https://gist.github.com/waterdog1234/1830f39d58af2ba16782cd5b57b3e062)

[messages](https://gist.github.com/waterdog1234/a97a68e1264b712b23077001f87efa30)

**Comment by KaraokeStu** [comment]
Most packages still aren't DSM 6.x compatible yet, please keep an eye on the issue https://github.com/SynoCommunity/spksrc/issues/2661
