### ISSUE TITLE
Update mediainfo to v0.7.93

### ISSUE THREAD

**Issue by rednoah** [SynoCommunity/spksrc#2689]
Please update the `mediainfo` package the latest version `0.7.93`.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=42598666)](https://www.bountysource.com/issues/42598666-update-mediainfo-to-v0-7-93?utm_source=42598666&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by cytec** [comment]
@rednoah i've created a PR for this, might take some time till i'm able to upload a new build to the repo

**Comment by rednoah** [comment]
No worries. Take your time.

**Comment by KaraokeStu** [comment]
Just building it now
