### ISSUE TITLE
Tmux 2015 version

### ISSUE THREAD

**Issue by meffect** [SynoCommunity/spksrc#2695]
it's 2.1 https://github.com/tmux/tmux/releases

I can get 2.3 from entware ng

**Comment by KaraokeStu** [comment]
This will be resolved with https://github.com/SynoCommunity/spksrc/pull/2691 once it has been reviewed

**Comment by meffect** [comment]
cool ty :)

**Comment by KaraokeStu** [comment]
Just publishing now! 👍

**Comment by meffect** [comment]
should I see v 2.3 on the synology now? I't still says 2.1-2

**Comment by cytec** [comment]
make sure you updated the spk and using the correct binary (/usr/local/bin/tmux)

**Comment by meffect** [comment]
hmm... what's the update spk process?

This is what I have now

![screenclip2](https://cloud.githubusercontent.com/assets/1799758/23873036/e03a640c-07ed-11e7-8cf1-f9a6bbf825e1.png)

![screenclip1](https://cloud.githubusercontent.com/assets/1799758/23873039/e3bed1a8-07ed-11e7-942f-2874cb80f1b8.png)

**Comment by meffect** [comment]
Any advice on this one?

**Comment by meffect** [comment]
?
