### ISSUE TITLE
dockern Win10 set up toolchain fails

### ISSUE THREAD

**Issue by mtonnie** [SynoCommunity/spksrc#2702]
It seems that verifying checksum fails when I use docker for windows.

### Steps to reproduce
1. Installed Docker for Windows (Version 17.03.0-ce-win1 (10296))
2. Shared Drive D:
3. pulled docker image (docker pull synocommunity/spksrc)
4. cloned the repository (git clone https://github.com/SynoCommunity/spksrc.git spksrc_org)
5. started the docker image (docker run -it -v D:\spksrc_org:/spksrc synocommunity/spksrc /bin/bash)
6. make setup
7. cross build a packe e.g. pip (cd /spksrc/cross/pip & make arch-monaco)

The result I get is:
root@b4a4f11a4e49:/spksrc/cross/pip# make SHELL='sh -xv' arch-monaco
+ pwd
+ echo ===>  Building package for arch monaco
===>  Building package for arch monaco
+ MAKEFLAGS= make ARCH=monaco TCVERSION=5.2
make[1]: Entering directory '/spksrc/cross/pip'
===>  Set up toolchain
===>    Downloading files for syno-monaco
wget http://sourceforge.net/projects/dsgpl/files/DSM%205.2%20Tool%20Chains/STMicroelectronics%20Monaco%20Linux%203.10.35
/monaco-gcc483_glibc219_hard-GPL.txz
2017-03-11 10:36:02 URL:https://excellmedia.dl.sourceforge.net/project/dsgpl/DSM%205.2%20Tool%20Chains/STMicroelectronic
s%20Monaco%20Linux%203.10.35/monaco-gcc483_glibc219_hard-GPL.txz [47120332/47120332] -> "monaco-gcc483_glibc219_hard-GPL
.txz.part" [1]
===>    Verifying files for syno-monaco
===>      Checking sha1sum of file monaco-gcc483_glibc219_hard-GPL.txz
sha1sum: standard input: no properly formatted SHA1 checksum lines found
===>        Wrong sha1sum for file monaco-gcc483_glibc219_hard-GPL.txz
===>        Renamed as monaco-gcc483_glibc219_hard-GPL.txz.wrong
===>        Download cookie removed to trigger the download again
../../mk/spksrc.checksum.mk:42: recipe for target 'checksum_target' failed
make[2]: *** [checksum_target] Error 1
/spksrc/cross/pip/work-monaco-5.2/tc_vars.mk:1: *** An error occured while setting up the toolchain, please check the me
ssages above.  Stop.
make[1]: Leaving directory '/spksrc/cross/pip'
../../mk/spksrc.cross-cc.mk:122: recipe for target 'arch-monaco' failed
make: [arch-monaco] Error 2 (ignored)
root@b4a4f11a4e49:/spksrc/cross/pip#

**Comment by mtonnie** [comment]
In the mean time I figured out the problem by myself.
This was cause by the fact that I use git for windows to clone the repository and I checked out "windows style". Since I changed the behaviour to "as is" I'm generally able to install the toolchain.

**Comment by Windman1320** [comment]
So weired , I check out with Git Bash for Windows, and then scp to vmware debian, found same question as you mentioned above. Windows is so annoying.

**Comment by tdedobbeleer** [comment]
This issue saved me from googling for hours.
The fast solution, update git:
`git config --global core.autocrlf false`
