### ISSUE TITLE
Icecast IPV6 not working

### ISSUE THREAD

**Issue by DennisHeerema** [SynoCommunity/spksrc#2703]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_icecast
_Package Version:_2.4.1-1

_NAS Model:_DS2415+
_NAS Architecture:_INTEL Atom C2538
_DSM version:_DSM 6.1-15047 Update 1

### Expected behavior
Tell us what should happen
When browsing to the ipv6 adress of the NAS at port 8000 i should be getting the icecast website or i should be able to stream a mountpoint. 
My browser shows message : Unable to connect

http://[2001:470:1f15:4f:xxxx:xxxxx:xxxx:xxxx]:8000/
I can reach the ipv4 version though
(mind you binding should bed disabled or 0 or :: in the icecast config)

And yes ipv6 is working in my network and on the nas, because i can get to the main  DSM page at ipv6
http://[2001:470:1f15:4f:xxxx:xxxxx:xxxx:xxxx]:5000/

### Actual behavior
Tell us what happens instead
My browser shows message : Unable to connect
### Steps to reproduce
_1._configure ipv6 on your nas
_2._set bind in icecast conf to "::"
_3._browse to http://[2001:470:1f15:4f:xxxx:xxxxx:xxxx:xxxx]:8000/

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
No error found related to this
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by KaraokeStu** [comment]
Could you try and find your Icecast config file, stop Icecase and change the bind address to the following:
`<bind-address>::</bind-address>`
If this works, I'll look to update the default config file shipped with Icecast to enable both IPv4 and IPv6

**Comment by yverry** [comment]
The documentation in icecast2.4.x said "all interface".
In fact it's ipv4 only. You're suggestion works perfectly, this is an old post but just push the modification and clos this issue

**Comment by 0d0a** [comment]
Force-reload not working when changing binding ... a Restart is neceassary

**Comment by ymartin59** [comment]
Icecast has been updated. Please report new defect to new issue.
