### ISSUE TITLE
Syncthing "Stopped" in package GUI, but running - and won't start after reboot issue

### ISSUE THREAD

**Issue by majorsl** [SynoCommunity/spksrc#2704]
_Package Name: syncthing
_Package Version: 0.14.23-12

_NAS Model: DS415+
_NAS Architecture: INTEL Atom C2538
_DSM version: DSM6.1-15047 Update 1

### Expected behavior
Syncthing should start after reboot.

### Actual behavior
Doesn't start, trying to click "Run" for the package results in "failed to run the package service".

### Steps to reproduce
_1. install Syncthing package, setup, works great after initial install
_2. reboot NAS
_3. fails to start.

Possibly related to #2176, please close and reference if so.

I did get it to start, eventually, based on one of the last posts. I didn't have a syncthing user. Once I created it and gave it proper permissions, I could manually start syncthing with:

/var/packages/syncthing/scripts/start-stop-status start

However, the GUI is still showing syncthing as "stopped" which, as an aside, is preventing me from updating the syncthing-inotify package which requires syncthing's status to be running, apparently.

While I can manually start Syncthing from the CLI, it still won't start via the Package Center GUI, exhibiting the same "failed to run the package service" error message.

Update: After a 2nd reboot, Syncthing now starts. It doesn't have permission to a few of the files, maybe due to whatever user it was running under previously, but that should be fixable...

**Comment by o0v7r0o** [comment]
I would say that it is related to the user-issue #2216. It will be a huge update with DSM6+ support for all packages.

**Comment by FR86** [comment]
To clarify, what worked for me on a DS216j was to:

1. Use the web gui to create a user named `syncthing`, part of groups `users`, `root `and `sc_syncthing`
1. Dial in as admin via ssh
1. run `sudo chown -R syncthing:root /usr/local/syncthing`
1. reboot

**Comment by lubomski** [comment]
Have a DS2415+ (Avoton) and this issue is happening to me also; the only way I can restart Syncthing is to uninstall / reinstall. Manually attempting to start the service does not work.

**Comment by ymartin59** [comment]
syncthing package has been updated
