### ISSUE TITLE
Issue Downloading Packages (ASIA)

### ISSUE THREAD

**Issue by rp4k** [SynoCommunity/spksrc#2706]
i have noticed that being in asia the ping to the repo is horrible. most time the package fails to download at least 10 times before i can download it or sometimes i can't even download it at all.   is there another way i can access the repo inside of Asia (china)  because it is very very hard to download packages from the repo without being on a VPN.

**Comment by piwi82** [comment]
The SynoCommunity repository server is hosted behind _Cloudflare_ and we don't have the resources to provide downloads distributed through a CDN to our users.
If downloading packages works well using a VPN, I think there is a problem of peering/QoS filtering with your ISP.

**Comment by KaraokeStu** [comment]
As @piwi82 has stated, the repo is behind Cloudflare. Unfortunately, the Chinese "Walled Garden" causes many problems, therefore VPNs will likely be the only way to break through the wall.

Closing as there is nothing we can do to resolve this
