### ISSUE TITLE
Python 2.7 version?

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#2717]
### Setup
_Package Name: Python
_Package Version: 2.7.13-16

_NAS Model:_
_NAS Architecture: DS715 (Alpine)
_DSM version: DSM 6.1-15047 Update 1

### Expected behavior
When entering command python --version from CLI i would expect to see version 2.7.13 but instead it shows 2.7.12

### Actual behavior
When performing cmd python --version it displays 2.7.12 

### Steps to reproduce
root@DS715:/volume1/@appstore/scripts/tvgrabpyAPI# /volume1/@appstore/python/bin/python --version
Python 2.7.13
root@DS715:/volume1/@appstore/scripts/tvgrabpyAPI# python --version
Python 2.7.12

Did something in the upgrade process to package version 2.7.13-16 go wrong with creating symlinks or something else? I doesn't look like the Synology version either.

**Comment by superost** [comment]
Same here, but I think that that python binary is included with DSM to begin with. You can find it in /usr/bin/. Same applies to many other binaries in that folder. ffmpeg is the same. Just a guess though.

**Comment by Safihre** [comment]
The SynoCommunity version is separate from the Synology version. 
The actual Python is in: `/usr/local/python/bin/python`

For every package we also create a virtualenv, for example then the package-user `python` will be in `/volume1/@appstore/sabnzbd/env/bin/python` that also has it's own package-specific `pip` packages.
