### ISSUE TITLE
[Package Request] Deluge 1.3.14

### ISSUE THREAD

**Issue by Madj42** [SynoCommunity/spksrc#2719]
Name: Deluge 1.3.14
Description: Deluge torrent client
Website:  http://dev.deluge-torrent.org/
Software documentation:  http://dev.deluge-torrent.org/wiki/UserGuide
Build/Installation documentation:  http://dev.deluge-torrent.org/wiki/Development
Source Code:  http://git.deluge-torrent.org/deluge/
License:  GPL v3

This should be a high priority as there is a bug in the web UI that can be used to compromise a system.

Note from the release notes page for this version:  WebUI users: Highly recommended to upgrade to this release as it contains a fix for CSRF vulnerability that has the real potential to compromise your machine.

**Comment by Madj42** [comment]
I was able to build my own package to upgrade my system but I figured this should be put in the repo since it has a vulnerability.

**Comment by Madj42** [comment]
Uploaded my changes to the remote repository located here: https://github.com/Madj42/deluge-spksrc

Everything builds correctly and I'm running the version on my Synology 1512+.

**Comment by superost** [comment]
You might want to update libtorrent to 1.0.11 when you are at it. I am no good with github, so here you are:

`libtorrent-rasterbar-1.0.11.tar.gz SHA1 8ddf7f7c614986acdbdd4cc293b01844e4dc8fd5
libtorrent-rasterbar-1.0.11.tar.gz SHA256 828d686770346f6da2c143c5a2844c5f5e407eb4a37982e90022763508abd62f
libtorrent-rasterbar-1.0.11.tar.gz MD5 f49e43286a64e8bbdef9ea59baa78b55
`

and the Makefile of course:

`PKG_VERS = 1.0.11`

The newer libtorrent 1.1.2 does not work afaik.

**Comment by superost** [comment]
oh and I tested that on my DS216j and it works fine for that arch

**Comment by KaraokeStu** [comment]
Updated and pending publish
