### ISSUE TITLE
DS1515+

### ISSUE THREAD

**Issue by andoyin** [SynoCommunity/spksrc#2726]
Hello we have problem whit start in ds is not work always starting, can you help me. sending you link to screenshot - Загрузка is a loading https://s.mail.ru/4Qeb/1cPnzjBnW

**Comment by andoyin** [comment]
andranik@DS:~$ sudo su -
Password:
root@DS:~# /var/packages/debian-chroot/scripts/start-stop-status chroot
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
root@DS:/#

**Comment by ymartin59** [comment]
@andoyin Please add more details in issue title. What is your DSM version ?

**Comment by andoyin** [comment]
DSM 6.1-15047 Update 2

**Comment by ymartin59** [comment]
As far as I know there is still no package for DSM 6 available in package repository. Have you build package from sources branch `dsm6` yourself ?

**Comment by andoyin** [comment]
no, im updated system and synology install it

**Comment by ymartin59** [comment]
OK so you probably installed DSM 5.2 `debian-chroot` package first before a DSM upgrade to 6.1. But package has not been upgraded itself because no DSM 6.x version is available in repository yet. Still have to wait...

**Comment by andoyin** [comment]
ok  im waiting

**Comment by ymartin59** [comment]
As far as I have tested, package `debian-chroot` works as expected. Please read https://github.com/SynoCommunity/spksrc/wiki/Debian-Chroot

- Connect through `ssh` as `admin` user
- Switch to root with `sudo -s`
- Invoke `/var/packages/debian-chroot/scripts/start-stop-status chroot`

**Comment by Safihre** [comment]
Closing this due to age and no feedback from topic starter.
