### ISSUE TITLE
Homeassistant for Braswell?

### ISSUE THREAD

**Issue by kalety** [SynoCommunity/spksrc#2728]
_For new Package Requests, see the guidelines_  

### Setup
Homeasistant
_Package Version:_

DS716+
Braswell
DSM 6.1
### Expected behavior

Homeassistant is available for x86 platforms but not to braswell (same?). Where I get the x86 spk?, through my spk synology center not appears because 
### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
Sounds like package has been ported to DSM 6.x in `dsm6` branch. Thanks to my PR #2727 providing DSM 6.1 toolchains, I have been able to build `homeassistant` package for Braswell. Here it is, packed as zip because of GitHub.
May you please do beta-testing of it and report in comments here if it works well or if you have any trouble ?

**Comment by ymartin59** [comment]
@Dr-Bean Is there any specific reason to build and embed Python 3.5 with homeassistant ? If no I may propose a PR to depend on Synology Python package instead.

**Comment by kalety** [comment]
@ymartin59
![image](https://cloud.githubusercontent.com/assets/19465177/24697650/36cae5c8-19ee-11e7-83f2-982fc4583cf6.png)
 The spk archive, doesn't installs, I leave the fork fields exactly shows the screen capture, then next and then "not avaliable"

**Comment by ymartin59** [comment]
OK package is buggy. I have to fix some stuff and do really testing before delivering another package. Sorry.

**Comment by kalety** [comment]
If x86 package exists, then run in braswell... Could you get me any direct link to this spk. Thank you in advance.

**Comment by ymartin59** [comment]
Now published even if work is still in progress to make components available.
