### ISSUE TITLE
openHAB Sensors

### ISSUE THREAD

**Issue by andoyin** [SynoCommunity/spksrc#2729]
Hello where can i get sensors list for connect openHAB 

1. we need to implement (installation ) a door phone (the number of collars is sliding)
2. 2-contact closure sensor (ventilation error)
3. a sensor for hacking or opening windows and doors

**Comment by KaraokeStu** [comment]
Hi,

You would have to check with the developers of OpenHAB, as we only create the package from their code here.

https://www.openhab.org/
