### ISSUE TITLE
SABnzbd version update

### ISSUE THREAD

**Issue by bassho** [SynoCommunity/spksrc#2739]
### Setup
_Package Name:_ SABnzbd
_Package Version:_ 1.2.3 [d34e143]

_NAS Model:_
_NAS Architecture:_ HP Micro Gen8
_DSM version:_ 5.2 update 5

### Expected behavior
SABnzbd has released version 2.0.0 which improves the downloadspeed.

### Actual behavior
The downloadspeed is currently reduced by the processor. This is a bug in SABnzbd and is resolved.

**Comment by byronmccollum** [comment]
See commentary in #2734

**Comment by bassho** [comment]
Thanks. Luckily more peope ask for it :)

**Comment by byronmccollum** [comment]
Fix released via #2742
