### ISSUE TITLE
SABnzbd shows old version number - not upgraded?

### ISSUE THREAD

**Issue by Pokersut** [SynoCommunity/spksrc#2740]
NAS Model: DS-413
DSM version: 6.1-15047 Update 2

I have just upgraded to v2.0.0-23 of SABnzbd, and in the Package Center in DSM it says "Installed version: 2.0.0-23", but when I start the web interface, it still shows version 1.2.3 in the title bar, and the log says "Starting SABnzbd.py-1.2.3"

I have tried completely uninstalling the package and re-installing it from scratch, but it still shows the same - so I am not sure if the package has been upgraded at all?

Any advice?

**Comment by byronmccollum** [comment]
See commentary in #2734
