### ISSUE TITLE
Syncthing never connects with other client

### ISSUE THREAD

**Issue by PepsiBlue14** [SynoCommunity/spksrc#2741]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Syncthing
_Package Version:_v0.14.26

_NAS Model:_1815+
_NAS Architecture:_synology_avoton_1815+
_DSM version:_DSM 6.1-15047 Update 2

### Expected behavior
Tell us what should happen
Syncthing should connect to my other client and begin syncing files

### Actual behavior
Tell us what happens instead
This client discovers my other client but never syncs; even after restarts on both clients

### Steps to reproduce
_1._Add IDs to both systems and share folders for both systems
_2._
_3._
#### Package log
no logs present in path or in package log from DSM

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

Messages log
[https://gist.github.com/PepsiBlue14/7b4d89ff0419acc67b3af3ea9adef422](url)

synopkg log
[https://gist.github.com/PepsiBlue14/c80814ea5b2d86abf721262c12537ebc](url)

**Comment by piwi82** [comment]
Is the NAS firewall active ?

**Comment by PepsiBlue14** [comment]
No; just DOS protection

**Comment by ymartin59** [comment]
syncthing package has been updated
