### ISSUE TITLE
No Such File or directory - when trying to start SAB

### ISSUE THREAD

**Issue by ccfc1986** [SynoCommunity/spksrc#2744]
### Setup
_Package Name:  SABNZB 2.0.0.24
_Package Version: 2.0.0-24

_NAS Model: 1812+
_DSM version: DSM 6.1-15047 Update 2

### Expected behavior
Clicking 'Run' for the SAB package would start the application and leave it in a running state - accessible through a web gui on the configured port etc.

### Actual behavior
When trying to start the SAB application from the package area of DSM i get the following error message:
'Failed to run the package Service'

When i log into the NAS via the CLI with my administer account and sudo to root, and run the following command i get the following:

ash-4.3# ./start-stop-status start
Starting SABnzbd ...
env: /usr/local/sabnzbd/env/bin/python: No such file or directory

I have read else where that the issue is because of a missing 'env' directory in the '/var/packages/sabnzbd' directory ... I have no such 'env' directory in that location.

I recently (today) updated the package to the version listed above (this was before i noticed the lack of downloads). So i can't say the new update fixed OR caused the initial issue. According to the logs for SAB, the app has been running and accepting API calls up to this morning when i performed the latest update... so the latest update seems to be the reason for this issue...as API calls couldn't be accepted if the web service was down/unavailable like it is now. So it seems when SAB was updated then attempted to be restarted, it failed to restart correctly due to the above errror. 

If you guys could help me troubleshoot this that would be excellent - reviewing forums online i cannot find anything all that similar ... and workarounds for the 'env' directory (such as copying from another directory like sickbeard of headphones etc) doesn't work for me because I do not have that directory anywhere in those package directories (again, this may not be a valid fix, but just trying to say i've tried to see other solutions elsewhere!).

If i can supply you with any pertinent data please let me know. Thanks in advance.

** Update
- I attempted to create a symlink to /usr/bin/python to the path /usr/local/sabnzb/env/bin/python and this then returned the following error:
ash-4.3# ./start-stop-status start
Starting SABnzbd ...
The Python module Cheetah is required
I would rather not go too far down the rabbit hole - so I will just stop here for now. Thanks again

**Comment by KaraokeStu** [comment]
Thanks for your info, I'll take a further look into this tomorrow for you and, once fixed, will republish with build 2.0.0-25

**Comment by ccfc1986** [comment]
Excellent. Thank you for the time and review. If you need any additional
details please let me know.

I attempted a reinstall from scratch and had the same issue. Just an FYI.

Thanks once again for all the support and excellent work on the project.

**Comment by KaraokeStu** [comment]
Currently testing

[x] DSM 5.2-5644 (Clean Install)
[] DSM 6.1-15407 (Clean Install)
[] DSM 6.1-15407 Update 2 (Clean Install)

**Comment by KaraokeStu** [comment]
I've looked into this further and it is, unfortunately, all down to https://github.com/SynoCommunity/spksrc/issues/2216

Take a look in that thread for workarounds (I use one of them, and have an "apps" user that I run all my apps as - involves editing start-stop-status scripts every time I upgrade and chown'ing to apps:users) as a short-ish term fix.

We are working on a full solution and we do have a DSM6 branch - we hope to have a full solution soon.

**Comment by ccfc1986** [comment]
After further searching i found this link to a ticket here:
https://github.com/SynoCommunity/spksrc/issues/282
I can't see how this is a permissions issue if i am missing folders required for the application to work (missing /env folder for python in the SAB directory). Are people actively using SAB without issue on DSM6? 

I am on 6.1-15047 Update 2. 

Thanks
