### ISSUE TITLE
Error while installing the packages for 'Firefox Sync Server 1.5 BETA' on Synology DS213

### ISSUE THREAD

**Issue by ghost** [SynoCommunity/spksrc#2747]
### Setup
_Package Name:_ffsync
_Package Version:_1.5.2_3

_NAS Model:_DS213+
_NAS Architecture:_MARVELL Kirkwood 88F6282
_DSM version:_DSM 6.1-15047 Update 2

### Expected behavior
The ffsync package should install properly

### Actual behavior
An error occured during the installation with a dialog displaying "Incorrect MySQL root password"

### Steps to reproduce
_1._Go in the package center (included synocommunity packages on http://packages.synocommunity.com
_2._Click on install packages "Firefox Sync Server 1.5 BETA"
_3._Enter correct password for root user and a password for ffsync
_4._Enter public url
_5._Install

#### Other logs
I tried to debug the installer.sh file that I found on https://github.com/SynoCommunity/spksrc/blob/master/spk/ffsync/src/installer.sh and I get the following error while executing it :

/usr/syno/mysql/bin/mysql: No such file or directory
/usr/syno/mysql/bin/mysqldump: No such file or directory

Actually my mysql binaries are located in /bin/mysql and /bin/mysqldump on my machine and the script failed when executing the line 33. I guess there is something wrong on the line 21 and 22 :

MYSQL="$([ $(/bin/get_key_value /etc.defaults/VERSION buildnumber) -ge 7135 ] && echo -n /bin/mysql || echo -n /usr/syno/mysql/bin/mysql)"
MYSQLDUMP="$([ $(/bin/get_key_value /etc.defaults/VERSION buildnumber) -ge 7135 ] && echo -n /bin/mysqldump || echo -n /usr/syno/mysql/bin/mysqldump)"

Thx you for trying to fix that issue, it is probably nothing hard to do.

**Comment by ymartin59** [comment]
In fact this package should be reworked to depend on Synology official MySQL package declared as a "resource".

**Comment by fgerrits** [comment]
It's not the database, the installer in the script folder has an old mysql path.

You could change the path in the installer from; 
'MYSQL="/usr/syno/mysql/bin/mysql"
MYSQLDUMP="/usr/syno/mysql/bin/mysqldump" '
to
'MYSQL="/usr/bin/mysql"
MYSQLDUMP="/usr/bin/mysqldump" '
