### ISSUE TITLE
RuTorrent Downloads Stalling Out

### ISSUE THREAD

**Issue by NotNearUganda** [SynoCommunity/spksrc#2751]
I've had the RuTorrent/RTorrent package from SynoCommunity installed on my DS413 for several months now, with no issues other than some hiccups during the initial install. 

Recently however, all my downloads are stalling out. When I load them, they peak and will max out my available bandwidth (100mbps cable) for several seconds to several minutes. Then connections to peers will dry up and download speeds will plummet, sometimes to 0, for minutes, hours, or longer. Stopping and starting the torrent will bump the speed to what it should be, but then it will drop again. Previously, using the same trackers, downloads would blaze through at full speed.

A few pictures to illustrate:
https://i.imgur.com/TTxWAl3.png
Initial connection to swarm, with subsequent drop.

https://i.imgur.com/lnqK3Oy.png
Stopping/starting the torrent increases speeds.

https://i.imgur.com/vVXdk9P.png
A more extreme example.

This is happening across the trackers I use.

I've tried restarting my DS413, my router, my cable modem, restarting RuTorrent. I use my NAS primarily for direct media serving when I am at home, and as a VPN when I am at work.

Help? What should I do/try. I have very basic command line knowledge; I can follow directions and understand them, but am not knowledgable enough to go off on my own.

And then random speedups and drops again? http://imgur.com/gSUjtI4
http://imgur.com/NKtI48k

A few notes, or possibly relevant details.
I have also seen slow downs on the VPN I run on the Synology that only has one or two connections at any time; I used to be able to Speed Test at 20/30 mbps up and down, now I hit in the single digits.
The connection itself tests fine with no slow downs.
When doing a direct download, like for a package or bringing down something via SFTP, there are no perceived speed issues.

_For new Package Requests, see the guidelines_  

### Setup
_Package Name: rutorrent_
_Package Version: 3.7-8_

_NAS Model: DS413
_NAS Architecture:_
_DSM version: DSM 6.1-15047 Update 2_

### Expected behavior
Previously, all downloads would run at full speed from start to end.

### Actual behavior
Now they start full speed, then quickly lose connections to peers and slow down to a crawl. Stopping/restarting torrent will get speed to normal until it crashes again.

### Steps to reproduce
Start any torrent, observe speed spike, then crash.

#### Package log
None.

**Comment by ymartin59** [comment]
Sorry but SynoCommunity provides packages for applications developed and maintained by their respective team. As packaging for DSM does not seem to be source of described issues, I propose you open an issue there: https://github.com/Novik/ruTorrent/issues and so close this one.

**Comment by ymartin59** [comment]
Advice: try to check CPU and memory consumption... if OK, it may be possible your internet provider now applies quality-of-service policies to avoid unfare bandwidth consumption.

I already faced some company internet proxy slowing down large file "standard" HTTP download after few minutes, but a simple stop/resume in Firefox allowed me to retrieve initial throughput for another slot - as a new TCP connection is created then.

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #2215 and maybe PR #3175.
