### ISSUE TITLE
[Package Request] expect

### ISSUE THREAD

**Issue by lillereven** [SynoCommunity/spksrc#2752]
Name: expect
Description: interaction automation tool
Website: http://expect.sourceforge.net/
Software documentation:
Build/Installation documentation:
Source Code:
License: 17 USC 105 (public domain)

**Comment by ymartin59** [comment]
From my point of view, even if SynoCommunity provides a TCL package, I am so excited to port this old "expect" implementation. Reading https://en.wikipedia.org/wiki/Expect I would really prefer to provide "Pexpect" which is a pure-Python alternative. What is your opinion about it ?

**Comment by 3ntranced** [comment]
Any progress on Pexpect or Expect?

**Comment by hgy59** [comment]
No meant to cross compile. Not a candidate for a package...

```
 configure: error: Expect can't be cross compiled
```
