### ISSUE TITLE
Shairport Sync to be updated

### ISSUE THREAD

**Issue by dude32** [SynoCommunity/spksrc#2754]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Shairport Sync installed via Synology package managment from SynoCommunity
_Package Version:_2.3.11-2

_NAS Model:_DS 211
_NAS Architecture:_MARVELL Kirkwood 88F6282
_DSM version:_6.1.1-15101 Update 1

### Expected behavior
Using Audio Station (6.1.0-3254) on DSM ( 6.1.1-15101 Update 1) with MARVELL Kirkwood 88F6282 When I use "shairport sync on mediastation" as output in the Audio Station, that should be work with continous sound on this output.

### Actual behavior
The output is stuttering; better explained as a 20 second cycle of quitness and one second of sound.
There is a new version of Shairport out: vers. 3, maybe that helps.

Using the same setup with an external source, not Audio Station but Spotify works fine.

### Steps to reproduce
_1._Run Audio Station
_2._Select "shairport sync on mediastation" as output
_3._Start music from lokal stored NAS/Synology

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #3040.
