### ISSUE TITLE
Deluge update to 1.3.14

### ISSUE THREAD

**Issue by deadlyknapsack** [SynoCommunity/spksrc#2755]
@Diaoul 

Is it possible to have Deluge for Synology updated to the latest version (1.3.14)? There has been a couple of important fixes, one of which is quite crucial:

http://dev.deluge-torrent.org/ticket/2149#comment:31

Deluge was ignoring Proxy settings, which caused users not to be anonymous, although they thought they were. This issue has been pending for quite some and has - most likely - finally been resolved by the Deluge team. I would like to test this on my DS716+.

Thanks in advance!

**Comment by Theli93** [comment]
Current revision is now 1.3.15; as of May 12, 2017

**Comment by lemohol** [comment]
Is it possible to have Deluge for Synology updated to the latest version (1.3.15)? :)

**Comment by Clandaries** [comment]
My problem with actual Deluge version is, that it stucks after a while.

I have to restart Deluge and it works for a while and then it stucks again

DS26J

Greetings

**Comment by lemohol** [comment]
The only issues I have with downloads getting stuck is when the file parts aren't available. If you genuinely think it's an application fault then I would raise a thread on the Deluge official forum - http://forum.deluge-torrent.org

Saying that, if the latest version was available on Synology it may fix the issue ;)

**Comment by Clandaries** [comment]
Not the download get stuck, the whole UI get stuck i cant open the web-UI anymore. But the Torrents are in seed, i can see it on the tracker.

I dont know why because the DS is running smooth.

**Comment by deepfriedmind** [comment]
It's been a long time now since Deluge was last updated on SynoCommunity. Can anyone recommend an alternative way of staying up to date?

**Comment by KaraokeStu** [comment]
Updated and pending publish
