### ISSUE TITLE
[Package Request] ffmpeg on armada38x

### ISSUE THREAD

**Issue by acatinon** [SynoCommunity/spksrc#2756]
On the page https://synocommunity.com/package/ffmpeg, I saw ffmepg is not avaliable on armada38x architecture.

Is there a particular reason for that, or maybe there is an oversight ?

**Comment by BenjV** [comment]
Waarschijnlijk omdat bij de armada modellen standaard ffmpeg meegeleverd wordt door Synology.

**Comment by acatinon** [comment]
"Probably because of the armada models standard ffmpeg is included by Synology."

You are right, but unfortunately the ffmpeg included by Synology is not compiled with "--enable-libx264"

**Comment by ymartin59** [comment]
If interested, here is package built for `armada38x-5.2` packed in zip because of GitHub restrictions. As far as I know it should work on DSM 6.x too.
[ffmpeg_armada38x-5.2_3.1.2-4.spk.zip](https://github.com/SynoCommunity/spksrc/files/999486/ffmpeg_armada38x-5.2_3.1.2-4.spk.zip)

**Comment by acatinon** [comment]
Thanks !
