### ISSUE TITLE
deluge autostart after reebot?

### ISSUE THREAD

**Issue by labaland** [SynoCommunity/spksrc#2757]
is it possible to add deluge to autostart after reboot?

**Comment by labaland** [comment]
I just tried to reinstall deluge. now deluge wont save anyting i do to it, so i cant connect to it with remote connection :/ what to do ? :(

**Comment by labaland** [comment]
now i do fabric reset on my ds916+ :(

**Comment by labaland** [comment]
After fabric reset, i cant still make changes in deluge, when i press ok under Preferences nothing happens, windows wont close :(

**Comment by KaraokeStu** [comment]
In order to help us debug this, please provide all the requested information.
Please see the contributing guide here:
https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issue-content

**Comment by Theli93** [comment]
Unless someone else is seeing otherwise, the last update resolved this issue on mine.

**Comment by ymartin59** [comment]
I have checked with latest version published.
