### ISSUE TITLE
Unable to See Radarr within Synology Community

### ISSUE THREAD

**Issue by naikdipe** [SynoCommunity/spksrc#2759]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Radarr
_Package Version:_ ?

_NAS Model:_ Synology DS413
_NAS Architecture:_ FREESCALE QorIQ P1022
_DSM version:_DSM 5.2-5644

### Expected behavior
I have enabled the 'beta' packages in options. I should be able to see the Radarr application.

### Actual behavior
The Radarr application is not visible.

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by schumi2004** [comment]
QorIQ is not supported because mono doesn't work correctly on it.

Same for Sonarr, you wont see that package either.

**Comment by Safihre** [comment]
@schumi2004 is right, nothing we can do. PPC-archs are just not supported anymore.

**Comment by piejanssens** [comment]
It happened: https://github.com/SynoCommunity/spksrc/issues/3470#issuecomment-468365359
