### ISSUE TITLE
Headphones doesn't start (not the timezone issue)

### ISSUE THREAD

**Issue by foxmajik** [SynoCommunity/spksrc#2761]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Headphones
_Package Version:_ 2015102-7

_NAS Model:_ DS916+
_NAS Architecture:_ Intel x86
_DSM version:_ DSM 6.1.1-15101 Update 2

### Expected behavior
Tell us what should happen

After the package is installed I should be able to "run" the "service"

### Actual behavior
Tell us what happens instead

An error is presented: 

Failed to run the package service.

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

Only contains 'config.ini'

```
Insert the package log here

[General]
config_version = 2
launch_browser = 0
folder_permissions = 0777
http_port = 8181
git_path = /usr/local/git/bin/git
http_host = 0.0.0.0


```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

2017-05-14T15:55:54-05:00 nastynas synoscgi_SYNO.Core.Package.Installation_1_install[18846]: resource_api.cpp:163 Acquire service-cfg for headphones when 0x0001 (done)
2017-05-14T15:56:23-05:00 nastynas [380891.852964] init: pkgctl-headphones pre-start process (19683) terminated with status 1
2017-05-14T15:56:23-05:00 nastynas synoscgi_SYNO.Core.Package.Control_1_start[19549]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-headphones][0xD900 privilege.cpp:60]
2017-05-14T15:56:23-05:00 nastynas synoscgi_SYNO.Core.Package.Control_1_start[19549]: service_initjob_action.c:27 InitJobStart failed, [0xD900 privilege.cpp:60]
2017-05-14T15:56:23-05:00 nastynas synoscgi_SYNO.Core.Package.Control_1_start[19549]: pkgstartstop.cpp:273 Failed to start pkgctl-headphones (err=-1) [0xD900 privilege.cpp:60]
2017-05-14T15:59:53-05:00 nastynas synoscgi_SYNO.Core.Package.Uninstallation_1_uninstall[21525]: resource_api.cpp:231 Release service-cfg for headphones when 0x0004 (done)
2017-05-14T15:59:53-05:00 nastynas synoscgi_SYNO.Core.Package_1_list[21527]: servicecfg_enum.c:26 Failed to mkdir [/usr/syno/etc/synoservice.d/error] errno=17/File exists
2017-05-14T15:59:53-05:00 nastynas synoscgi_SYNO.Core.Package_1_list[21527]: servicecfg_enum.c:29 Failed to move file [/usr/syno/etc/synoservice.d/pkgctl-headphones.cfg] to [/usr/syno/etc/synoservice.d/error/pkgctl-headphones.cfg] errno=2/No such file or directory
2017-05-14T16:06:16-05:00 nastynas synoscgi_SYNO.Core.Package.Installation_1_install[24368]: resource_api.cpp:163 Acquire service-cfg for headphones when 0x0001 (done)
2017-05-14T16:06:54-05:00 nastynas [381523.202619] init: pkgctl-headphones pre-start process (25628) terminated with status 1
2017-05-14T16:06:54-05:00 nastynas synoscgi_SYNO.Core.Package.Control_1_start[25490]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-headphones][0xD900 privilege.cpp:60]
2017-05-14T16:06:55-05:00 nastynas synoscgi_SYNO.Core.Package.Control_1_start[25490]: service_initjob_action.c:27 InitJobStart failed, [0xD900 privilege.cpp:60]
2017-05-14T16:06:55-05:00 nastynas synoscgi_SYNO.Core.Package.Control_1_start[25490]: pkgstartstop.cpp:273 Failed to start pkgctl-headphones (err=-1) [0xD900 privilege.cpp:60]

```
Insert log here
```
2017/05/14 15:55:51	install headphones 20151012-7 Begin preinst
2017/05/14 15:55:51	install headphones 20151012-7 End preinst ret=[0]
2017/05/14 15:55:51	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/headphones
2017/05/14 15:55:51	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/headphones ret=[0]
2017/05/14 15:55:51	install headphones 20151012-7 Begin /bin/rm -rf /var/packages/headphones
2017/05/14 15:55:51	install headphones 20151012-7 End /bin/rm -rf /var/packages/headphones ret=[0]
2017/05/14 15:55:54	install headphones 20151012-7 Begin /bin/mkdir -p /var/packages/headphones
2017/05/14 15:55:54	install headphones 20151012-7 End /bin/mkdir -p /var/packages/headphones ret=[0]
2017/05/14 15:55:54	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/headphones/INFO
2017/05/14 15:55:54	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/headphones/INFO ret=[0]
2017/05/14 15:55:54	install headphones 20151012-7 Begin /bin/rm -rf /var/packages/headphones/scripts
2017/05/14 15:55:54	install headphones 20151012-7 End /bin/rm -rf /var/packages/headphones/scripts ret=[0]
2017/05/14 15:55:54	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/headphones/scripts
2017/05/14 15:55:54	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/headphones/scripts ret=[0]
2017/05/14 15:55:54	install headphones 20151012-7 Begin /bin/rm -rf /var/packages/headphones/conf
2017/05/14 15:55:54	install headphones 20151012-7 End /bin/rm -rf /var/packages/headphones/conf ret=[0]
2017/05/14 15:55:54	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/headphones/conf
2017/05/14 15:55:54	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/headphones/conf ret=[0]
2017/05/14 15:55:54	install headphones 20151012-7 Begin postinst
2017/05/14 15:56:14	install headphones 20151012-7 End postinst ret=[0]
2017/05/14 15:56:14	install headphones 20151012-7 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2017/05/14 15:56:14	install headphones 20151012-7 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2017/05/14 15:56:14	install headphones 20151012-7 successfully
2017/05/14 15:56:22	start headphones: begin to start version 20151012-7
2017/05/14 15:56:22	start headphones 20151012-7 Begin pre-load apparmor
2017/05/14 15:56:22	start headphones 20151012-7 End pre-load apparmor ret=[0]
2017/05/14 15:56:22	start headphones 20151012-7 Begin start-stop-status start
Starting Headphones ...
su: Permission denied
2017/05/14 15:56:23	start headphones 20151012-7 End start-stop-status start ret=[1]
2017/05/14 15:56:23	(system) trigger headphones 20151012-7 Begin start-stop-status stop
Headphones is not running
2017/05/14 15:56:23	(system) trigger headphones 20151012-7 End start-stop-status stop ret=[0]
2017/05/14 15:56:23	(system) trigger headphones 20151012-7 Begin unload apparmor
2017/05/14 15:56:23	(system) trigger headphones 20151012-7 End unload apparmor ret=[0]
2017/05/14 15:56:23	stop headphones: begin to stop version 20151012-7
2017/05/14 15:56:23	stop headphones: stop version 20151012-7 successfully, result 0
2017/05/14 15:56:23	start headphones: start version 20151012-7 failed, result 1
2017/05/14 15:59:52	uninstall headphones 20151012-7 Begin preuninst
delgroup: can't find headphones in /etc/group
deluser: can't find headphones in /etc/group
2017/05/14 15:59:52	uninstall headphones 20151012-7 End preuninst ret=[0]
2017/05/14 15:59:53	uninstall headphones 20151012-7 Begin /bin/rm -rf /volume1/@appstore/headphones
2017/05/14 15:59:54	uninstall headphones 20151012-7 End /bin/rm -rf /volume1/@appstore/headphones ret=[0]
2017/05/14 15:59:54	uninstall headphones 20151012-7 Begin postuninst
2017/05/14 15:59:54	uninstall headphones 20151012-7 End postuninst ret=[0]
2017/05/14 15:59:55	uninstall headphones: Uninstall 20151012-7 successfully
2017/05/14 16:06:14	install headphones 20151012-7 Begin preinst
2017/05/14 16:06:14	install headphones 20151012-7 End preinst ret=[0]
2017/05/14 16:06:14	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/headphones
2017/05/14 16:06:15	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/headphones ret=[0]
2017/05/14 16:06:15	install headphones 20151012-7 Begin /bin/rm -rf /var/packages/headphones
2017/05/14 16:06:15	install headphones 20151012-7 End /bin/rm -rf /var/packages/headphones ret=[0]
2017/05/14 16:06:16	install headphones 20151012-7 Begin /bin/mkdir -p /var/packages/headphones
2017/05/14 16:06:16	install headphones 20151012-7 End /bin/mkdir -p /var/packages/headphones ret=[0]
2017/05/14 16:06:16	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/headphones/INFO
2017/05/14 16:06:16	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/headphones/INFO ret=[0]
2017/05/14 16:06:16	install headphones 20151012-7 Begin /bin/rm -rf /var/packages/headphones/scripts
2017/05/14 16:06:16	install headphones 20151012-7 End /bin/rm -rf /var/packages/headphones/scripts ret=[0]
2017/05/14 16:06:16	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/headphones/scripts
2017/05/14 16:06:16	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/headphones/scripts ret=[0]
2017/05/14 16:06:16	install headphones 20151012-7 Begin /bin/rm -rf /var/packages/headphones/conf
2017/05/14 16:06:16	install headphones 20151012-7 End /bin/rm -rf /var/packages/headphones/conf ret=[0]
2017/05/14 16:06:16	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/headphones/conf
2017/05/14 16:06:16	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/headphones/conf ret=[0]
2017/05/14 16:06:16	install headphones 20151012-7 Begin postinst
2017/05/14 16:06:44	install headphones 20151012-7 End postinst ret=[0]
2017/05/14 16:06:44	install headphones 20151012-7 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2017/05/14 16:06:44	install headphones 20151012-7 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2017/05/14 16:06:44	install headphones 20151012-7 successfully
2017/05/14 16:06:53	start headphones: begin to start version 20151012-7
2017/05/14 16:06:53	start headphones 20151012-7 Begin pre-load apparmor
2017/05/14 16:06:53	start headphones 20151012-7 End pre-load apparmor ret=[0]
2017/05/14 16:06:53	start headphones 20151012-7 Begin start-stop-status start
Starting Headphones ...
su: Permission denied
2017/05/14 16:06:54	start headphones 20151012-7 End start-stop-status start ret=[1]
2017/05/14 16:06:54	(system) trigger headphones 20151012-7 Begin start-stop-status stop
Headphones is not running
2017/05/14 16:06:54	(system) trigger headphones 20151012-7 End start-stop-status stop ret=[0]
2017/05/14 16:06:54	(system) trigger headphones 20151012-7 Begin unload apparmor
2017/05/14 16:06:54	(system) trigger headphones 20151012-7 End unload apparmor ret=[0]
2017/05/14 16:06:55	stop headphones: begin to stop version 20151012-7
2017/05/14 16:06:55	stop headphones: stop version 20151012-7 successfully, result 0
2017/05/14 16:06:55	start headphones: start version 20151012-7 failed, result 1

**Comment by jamesstout** [comment]
Think this is the [adduser issue](2216). Your log has a few: `su: Permission denied`

I'm not sure if the issue is resolved, well, it isn't, I just tried installing headphones and got the same issue. I added:
````
headphones-custom:*:10933:0:99999:7::: 
````
to `/etc/shadow`

and then restarted the package and it started. Not sure if the user in `/etc/shadow` will survive a reboot though.

**Comment by Safihre** [comment]
DSM6 compatible version of the package is expected to be released soon. It can already be installed by downloading it from here #3138.
After the official release on SynoCommunity, the package will auto-update from the official release.
