### ISSUE TITLE
[znc] best practice for enabling access to network shares?

### ISSUE THREAD

**Issue by Argon-** [SynoCommunity/spksrc#2762]
### Setup
_Package Name:_ znc
_Package Version:_ 1.4-10 (latest)

_NAS Model:_ DS414
_NAS Architecture:_ MARVELL Armada XP MV78230
_DSM version:_ 6.1.1-15101 (package was installed on DSM 5)

This is not a bug report, more like a question regarding best practices.
I have znc installed and running successfully and now I would like it to create log files. The default log directories where user `znc` has access work without problem.

However, I'd like it to write these logs on a network share ('Shared Folder'). Within DMS I cannot grant the user `znc` any access (it's not selectable). Unfortunately, granting `znc` access using `chmod` on the respective folders doesn't work either so I guess there is more access magic going on. 
I don't know about the internals of DMS access management, therefore I'd like to ask if there is a preferred way to achieve what I'm trying to do?

**Comment by Safihre** [comment]
Closing due to age, needs DSM6 conversion and then you could use `sc-znc`. 
Further DSM6 compatibility in #2977.
