### ISSUE TITLE
rutorrent beta, webui redirects to synology manager

### ISSUE THREAD

**Issue by plasmacutter** [SynoCommunity/spksrc#2766]
_For new Package Requests, see the guidelines_  

### Setup
ruTorrent
3.7-8

DS1815+
Current DSM version:
DSM 6.1.1-15101 Update 2

### Expected behavior
Upon startup, clicking http://ip.of.nas.device/rutorrent/ should produce rutorrent webui

### Actual behavior
Instead, httpd redirects back to synology management ui
(login via ssh confirms rtorrent is still running and listening, scripts recommended from previous issue threads show it's still active - synopkg.log indicates a failure to install some web components?)

### Steps to reproduce
Install ruTorrent successfully from sinocommunity package source in package center
Launch application
click on URL present in package center once install is complete and status shows "Running"

#### Package log
(log is empty)

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
2017/05/18 20:04:39 install rutorrent 3.7-8 Begin preinst
2017/05/18 20:04:39 install rutorrent 3.7-8 End preinst ret=[0]
2017/05/18 20:04:39 install rutorrent 3.7-8 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/rutorrent
2017/05/18 20:04:39 install rutorrent 3.7-8 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/rutorrent ret=[0]
2017/05/18 20:04:39 install rutorrent 3.7-8 Begin /bin/rm -rf /var/packages/rutorrent
2017/05/18 20:04:39 install rutorrent 3.7-8 End /bin/rm -rf /var/packages/rutorrent ret=[0]
2017/05/18 20:04:40 install rutorrent 3.7-8 Begin /bin/mkdir -p /var/packages/rutorrent
2017/05/18 20:04:40 install rutorrent 3.7-8 End /bin/mkdir -p /var/packages/rutorrent ret=[0]
2017/05/18 20:04:40 install rutorrent 3.7-8 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/rutorrent/INFO
2017/05/18 20:04:40 install rutorrent 3.7-8 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/rutorrent/INFO ret=[0]
2017/05/18 20:04:40 install rutorrent 3.7-8 Begin /bin/rm -rf /var/packages/rutorrent/scripts
2017/05/18 20:04:40 install rutorrent 3.7-8 End /bin/rm -rf /var/packages/rutorrent/scripts ret=[0]
2017/05/18 20:04:40 install rutorrent 3.7-8 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/rutorrent/scripts
2017/05/18 20:04:40 install rutorrent 3.7-8 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/rutorrent/scripts ret=[0]
2017/05/18 20:04:40 install rutorrent 3.7-8 Begin /bin/rm -rf /var/packages/rutorrent/WIZARD_UIFILES
2017/05/18 20:04:40 install rutorrent 3.7-8 End /bin/rm -rf /var/packages/rutorrent/WIZARD_UIFILES ret=[0]
2017/05/18 20:04:40 install rutorrent 3.7-8 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/rutorrent/WIZARD_UIFILES
2017/05/18 20:04:40 install rutorrent 3.7-8 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/rutorrent/WIZARD_UIFILES ret=[0]
2017/05/18 20:04:40 install rutorrent 3.7-8 Begin /bin/rm -rf /var/packages/rutorrent/conf
2017/05/18 20:04:40 install rutorrent 3.7-8 End /bin/rm -rf /var/packages/rutorrent/conf ret=[0]
2017/05/18 20:04:40 install rutorrent 3.7-8 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/rutorrent/conf
2017/05/18 20:04:40 install rutorrent 3.7-8 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/rutorrent/conf ret=[0]
2017/05/18 20:04:40 install rutorrent 3.7-8 Begin postinst
/var/packages/rutorrent/scripts/installer: line 78: /etc/php/conf.d/com.synocommunity.packages.rutorrent.ini: No such file or directory
sed: can't read /var/services/web/rutorrent/conf/config.php: No such file or directory
sed: can't read /etc/php/conf.d/user-settings.ini: No such file or directory
chown: cannot access '/var/services/web/rutorrent': No such file or directory
2017/05/18 20:04:41 install rutorrent 3.7-8 End postinst ret=[0]
2017/05/18 20:04:41 install rutorrent 3.7-8 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2017/05/18 20:04:41 install rutorrent 3.7-8 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2017/05/18 20:04:41 install rutorrent 3.7-8 successfully
2017/05/18 20:04:42 install rutorrent: begin to start version 3.7-8
2017/05/18 20:04:42 install rutorrent 3.7-8 Begin pre-load apparmor
2017/05/18 20:04:42 install rutorrent 3.7-8 End pre-load apparmor ret=[0]
2017/05/18 20:04:42 install rutorrent 3.7-8 Begin start-stop-status start
Starting ruTorrent ...
2017/05/18 20:04:42 install rutorrent 3.7-8 End start-stop-status start ret=[0]
2017/05/18 20:04:42 install rutorrent: start version 3.7-8 successfully, result 0

**Comment by jamesstout** [comment]
On the very latest DSM right? Is apache running? Try these with sudo or as root:
````bash
synoservice --list | egrep '(apache|http)'
ps aux | egrep '(apache|httpd)' | grep -v grep
````
Is nginx running and listening on port 80?
````bash
synoservice --list | grep nginx 
ps aux | grep nginx  | grep -v grep
nginx -T | grep listen
````
I have a similar issue with adminer: #2767

**Comment by plasmacutter** [comment]
I'm new to synology so am not familiar with the platform's expected default packages:
are apache and nginx supposed to be present by default?
I'm able to confirm nginx running, but not apache

**Comment by Clandaries** [comment]
Something new to this?

I am stuck at error 403.

Thank you.

**Comment by melchoir55** [comment]
Has anyone figured this out?

**Comment by plasmacutter** [comment]
Still poking at this. If anyone has managed a work-around please post here. I'll update thread if/when I find anything useful.

**Comment by Clandaries** [comment]
There was a firmwareupdate for my DS216J and now rutorrent is working. Not 100% but i can download and upload.
There are some permissions missing to some dirs but i dont know how to set them but it isa working, so ok...

**Comment by adamwinn** [comment]
I'm having this same issue too

**Comment by king8084** [comment]
to fix this issue, just enable web station app

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #2215 and maybe PR #3175.
