### ISSUE TITLE
adminer install error and URL redirect

### ISSUE THREAD

**Issue by jamesstout** [SynoCommunity/spksrc#2767]
### Setup
_Package Name:_ adminer
_Package Version:_ 4.2.4-1

_NAS Model:_ Synology DS1817+
_NAS Architecture:_ x86_64
_DSM version:_ DSM 6.1.1-15101 Update 2

### Expected behavior
Adminer should start on `http://my-ip/adminer`

### Actual behavior
I'm redirected to the Diskstation desktop on port 5000

### Steps to reproduce
_1._ Use package manager to install adminer 4.2.4-1. then click run
_2._ go to `http://my-ip/adminer`

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
/usr/local/adminer/var/ doesn't exist
```
#### Other logs
Link to [synopkg.log](https://ghostbin.com/paste/qg6d5)
```
<snip>
2017/05/19 17:47:06	install adminer 4.2.4-1 Begin postinst
chown: cannot access '/var/services/web/adminer': No such file or directory
2017/05/19 17:47:06	install adminer 4.2.4-1 End postinst ret=[0]
```
It fails to [chown](https://github.com/SynoCommunity/spksrc/blob/master/spk/adminer/src/installer.sh#L30) the adminer dir from root to http, the strange thing, is, it does exist:
````
root@dusky2:/var/log# ls -l /var/services/web/adminer
total 436
-rw-r--r-- 1 root root  27959 May 19 18:07 adminer.css
-rw-r--r-- 1 root root  27959 May 19 18:05 adminer.css.bak
-rw-r--r-- 1 root root 387223 Apr 13  2016 index.php
````
Also, the package depends on `apache`, which isn't installed or running:

````
root@dusky2:/usr/syno/sbin# synoservice --list | egrep '(apache|http)'
root@dusky2:/usr/syno/sbin#
root@dusky2:/usr/syno/sbin# ps aux | egrep '(apache|httpd)' | grep -v grep
root@dusky2:/usr/syno/sbin#
````

`nginx` is installed and running:

````
@dusky2:/usr/syno/sbin# ps aux | grep nginx  | grep -v grep
root     13497  0.0  0.0  34540  2540 ?        S<s  00:14   0:00 nginx: master process /usr/bin/nginx -g pid /run/nginx.pid; daemon on; master_process on;
http     18390  0.0  0.0  34544  3900 ?        S<   00:15   0:06 nginx: worker process
<snip>
root@dusky2:/usr/syno/sbin# synoservice --list | grep nginx
nginx
````
And there is already something listening on [port 80](https://ghostbin.com/paste/pebb2#L242), (full [nginx conf here](https://ghostbin.com/paste/pebb2)):

````nginx
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
       <snip>
        location ~ ^/$ {
            rewrite / http://$host:5000/ redirect;
        }
    }
````
You can see the 302 redirect in the nginx log:
````
192.168.1.201 - - [19/May/2017:21:08:29 +0800] "GET /adminer/ HTTP/1.1" 302 154 "http://192.168.1.13:5000/?dc=1493737127183" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "-"
````

I'll try changing some of the nginx conf files to pick up `/var/services/web/adminer`, but should apache get installed? Be indicated as a dependancy, and not run on port 80? (for this DSM build)

Thanks

**Comment by jamesstout** [comment]
Just noticed I don't have WebStation installed. That might be an issue.

**Comment by plasmacutter** [comment]
hi, please keep me updated on your efforts. 
Have updated on my end. Will continue to research.
