### ISSUE TITLE
[Package Request] Nyuu

### ISSUE THREAD

**Issue by sirjaymz** [SynoCommunity/spksrc#2769]
Name: Nyuu
Description: Nyuu is a command-line binary usenet poster.
Nyuu is designed primarily to be fast/efficient, reliable and customizable, exposing all the interesting bits and pieces. From what I’ve seen, Nyuu excels more than any other usenet posting client in these aspects.
Website: https://github.com/animetosho/Nyuu
Software documentation: https://github.com/animetosho/Nyuu/blob/master/help.txt
Build/Installation documentation: https://github.com/animetosho/Nyuu
Source code: https://github.com/animetosho/Nyuu/archive/v0.3.2.tar.gz
License: Public Domain

**Comment by ymartin59** [comment]
OK I will give it a try. What is your target platform of interest ?

**Comment by sirjaymz** [comment]
DS 1813+

**Comment by ymartin59** [comment]
In fact it is not so simple... It requires to setup cross-compiling tooling for NPM modules. Interesting challenge but time is lacking

**Comment by cytec** [comment]
@ymartin59 @sirjaymz have a look at https://github.com/madcowfred/GoPostStuff which can be easily compiled for DSM... in fact i already did that a while ago for my DS... not sure if i can find the Makefiles anywhere... i'll have a look

**Comment by cytec** [comment]
Update: here we go: https://github.com/cytec/spksrc/tree/cytec-5.0/spk/gopoststuff may need some finetuning and testing for the most recent go version in spksrc but should be good to go ;)

**Comment by ymartin59** [comment]
@cytec So for a package request concerning a tool written for NodeJS where difficulty is to cross-compiled NPM module, you propose another tool to run on Go ?

**Comment by cytec** [comment]
@ymartin59 exactly. gopoststuff does mainly the same thing (posting stuff to usenet) so it would be an alternative in my opinion. and as i mentioned above: it's pretty easy to compile gopoststuff for DSM

**Comment by sirjaymz** [comment]
I would like to thank you both for taking a look at this and seeing if we can make it happen. I really appreciate all the support and work you all do for the Synology platform and the persistent support you have provided to the community. :)
It's unfortunate Nyuu is unable to be cross-compiled, however, i do appreciate you all taking a look at it and providing me a definitive answer and alternative for the tool. 
Maybe in the future with different methods, we can make progress on this and others apps. 
I have really come to rely on the Synocommunity and the expansions we have all done in making the platform a goto solution.

**Comment by cytec** [comment]
@sirjaymz if you'd like to post to usenet from your DS i'd take a look at my gopoststuff SPK and see if i can get that one merged in here ;)
