### ISSUE TITLE
SHOUTcast server for Synology

### ISSUE THREAD

**Issue by jjLDN** [SynoCommunity/spksrc#277]
I was just wondering if there is any chance to port Shoutcast server for  Synology. I know there is icecast in ipkg repository, but it is not the same.
How about that?

**Comment by Dr-Bean** [comment]
Icecast has become available as beta package, see https://synocommunity.com/package/icecast. See https://github.com/SynoCommunity/spksrc/issues/1663 for a bit more information, and the associated PR: https://github.com/SynoCommunity/spksrc/pull/1680.

**Comment by Goldtraige** [comment]
this projetc is abandonned ?
i really need this one ^^
