### ISSUE TITLE
Instructions on how to create spk from DSM6 tree

### ISSUE THREAD

**Issue by oliroe** [SynoCommunity/spksrc#2774]
Hi

Any chance someone could write instructions on how to compile an spk for apps in the DSM6 tree? I'm able to do it for the master tree but want to compile Radarr for DSM6

Thanks

**Comment by m4tt075** [comment]
cd spksrc
git checkout dsm6                 # This switches to the dsm6 branch, which contains DSM6 fixes
git branch radarr-dsm6         # Copy that branch into a new one to play with
git checkout radarr-dsm6     # Make sure you are on the new branch
git cherry-pick 975dbe1687acf714b5e31e8c97378ce7de884fe1
                                              # This gives you the latest 6.1 toolchains (corresponding PR not merged yet)
cd spk/radarr
make arch-[yourarch]-6.1     # Compiles radarr using the 6.1 toolchains you have just cherry-picked

Untested, as I don't use Radarr. Good luck...

**Comment by oliroe** [comment]
thanks for that but getting a fatal :bad object error when doing git cherry-pick PR

**Comment by m4tt075** [comment]
git fetch --all
and try again...

**Comment by Safihre** [comment]
Not applicable anymore, we are all on `master` now!
