### ISSUE TITLE
ffmpeg compiled with --disable-encoder=ac3

### ISSUE THREAD

**Issue by E-t-z** [SynoCommunity/spksrc#2775]
It would be quite helpful if ac3 encoder would be available as well, so if you modify TransProfile you would be able to do DTS to AC3 conversion, to have multichannel audio.

**Comment by KaraokeStu** [comment]
Please could you let us know which platform you are looking to run this on, to ensure that we won't have issues enabling this for other platforms (there may be a reason why it was disabled, you see!)

**Comment by E-t-z** [comment]
Synology DS916+, it has Pentium N3710 so I believe it is braswell

**Comment by E-t-z** [comment]
Any general idea, could it be done, or I should start building and maintaining my own package?

**Comment by ymartin59** [comment]
According to `Makefile`, https://github.com/SynoCommunity/spksrc/blob/master/cross/ffmpeg/Makefile#L19
ac3 encoder is not disabled explicitely but seems disabled by default.

I am testing build with `--enable-encoder=ac3` on all supported platform, but I cannot test binary at runtime... we will have to wait for users' feedback and bug report if relevant

**Comment by ymartin59** [comment]
@E-t-z I am over with ffmpeg/chromaprint upgrade (#2865). Which DSM version is your DS916+ running ?

**Comment by E-t-z** [comment]
@ymartin59 DSM 6.1.3-15152 Update 1

**Comment by ymartin59** [comment]
Here is the requested package, packed as zip because of github attachment restrictions
[ffmpeg_braswell-6.1_3.3.3-7.spk.zip](https://github.com/SynoCommunity/spksrc/files/1221558/ffmpeg_braswell-6.1_3.3.3-7.spk.zip)

Let me know if it works well or if you have any issue

**Comment by E-t-z** [comment]
Will test it out in couple of days...

**Comment by E-t-z** [comment]
Seems to be working fine...

**Comment by ymartin59** [comment]
OK so please close this issue.
