### ISSUE TITLE
radarr crashing

### ISSUE THREAD

**Issue by M0UL** [SynoCommunity/spksrc#2777]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Radarr
_Package Version:_20170226-2

_NAS Model:_ds415+
_NAS Architecture:_avaton
_DSM version:_6.1.1

### Expected behavior
raddarr should not crahs
### Actual behavior
raddar keeps crashing

```
#### Other logs
17-6-4 13:31:13.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe] > [/tmp/radarr_update/Radarr.Update.exe]
17-6-4 13:31:13.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe.config] > [/tmp/radarr_update/Radarr.Update.exe.config]
17-6-4 13:31:13.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe.mdb] > [/tmp/radarr_update/Radarr.Update.exe.mdb]
17-6-4 13:31:13.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/SocksWebProxy.dll] > [/tmp/radarr_update/SocksWebProxy.dll]
17-6-4 13:31:13.7|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update.exe
17-6-4 13:31:13.7|Info|InstallUpdateService|Radarr will restart shortly.
17-6-4 13:31:13.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-6-4 13:31:13.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-6-4 13:31:13.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-6-4 13:31:14.6|Info|InstallUpdateService|Updater Arguments: 18882 /tmp/radarr_update /volume1/@appstore/radarr/share/Radarr/Radarr.exe /nobrowser
17-6-4 13:31:14.6|Debug|mono|Starting mono --debug /tmp/radarr_update/Radarr.Update.exe 18882 /tmp/radarr_update /volume1/@appstore/radarr/share/Radarr/Radarr.exe /nobrowser
17-6-4 13:31:14.6|Trace|CommandQueueManager|Updating command status
17-6-4 13:31:14.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-6-4 13:31:14.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-6-4 13:31:14.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-6-4 13:31:14.8|Trace|EventAggregator|Publishing CommandExecutedEvent
17-6-4 13:31:14.8|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-6-4 13:31:14.8|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Update.Commands.ApplicationUpdateCommand
17-6-4 13:31:14.8|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-6-4 13:31:14.8|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-6-4 13:31:14.8|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-6-4 13:31:14.8|Trace|CommandExecutor|ApplicationUpdateCommand <- InstallUpdateService [00:00:12.2074130]

**Comment by KaraokeStu** [comment]
Could you let us know when it crashes, what you are doing when it crashes etc.

Also DSM 6.x is not officially supported yet, so we can only do a "best guess" fix.

That said, I'm running DSM 6.x and haven't had any issues, but then I'm running x64

**Comment by M0UL** [comment]
the logs i posted are the last logs i have. currently i can not ever start the radarr without it crashing.

**Comment by KaraokeStu** [comment]
Can you try uninstalling and then reinstalling it?

I have a feeling it may well be a DSM 6 issue (I run my version under a specific user I created as a workaround) but it's not ideal.

It could also be that the update it automatically installed broke some stuff - that shouldn't be the case any more.

Give it a whirl and let me know

**Comment by jghaanstra** [comment]
Not sure if this is related and deserves it's own issue but for me Radarr does not actually crash but causes disk and volume usage of 100%. This results in the whole Diskstation becoming unresponsive and I can only get back in by pulling the plug, rebooting and quickly kill the app through shell and htop before it freezes up the diskstation again. The moment I start the app after killing it disk and volume usage are back up to 100% again. Strange thing is that it initially did work, perhaps I have messed up something with the settings. Already tried uninstalling and reinstalling again but this did not help. Is there any way to troubleshoot this better or make sure no setting remain after uninstalling?

# Setup
**Package Name**: Radarr
**Package Version**:_20170226-2
**NAS Model**: ds111
**NAS Architecture**: Marvell Kirkwood 88F6282
**Kernel**: 2.6.32.12 #15047 Tue Feb 14 02:38:24 CST 2017 armv5tel GNU/Linux synology_88f6282_111
**DSM version**: DSM 6.1.1-15101 Update 4

**Comment by M0UL** [comment]
@KaraokeStu  i have reinstalled radarr. it is running fine for now.  i hope it keeps running.

**Comment by KaraokeStu** [comment]
@jghaanstra Please raise your own issue (perhaps try reinstalling, like @M0UL did...)

I'll close this issue for now

**Comment by coenboomkamp** [comment]
@jghaanstra i"m experiencing the exact same issue as you. Were you able to fix it?

**Comment by jghaanstra** [comment]
> i"m experiencing the exact same issue as you. Were you able to fix it?
Nope, I bought a faster Synology. But I'm not even sure the issue was Radarr related. It seemed my Synology DS111 was having troubles with the overall load I was putting on it.

**Comment by coenboomkamp** [comment]
> Nope, I bought a faster Synology. But I'm not even sure the issue was Radarr related. It seemed my Synology DS111 was having troubles with the overall load I was putting on it.

There seems to be something going on that is causing the same issue you had:
https://github.com/Radarr/Radarr/issues/1580#issuecomment-388238537

I'm running in docker, you too?

**Comment by jghaanstra** [comment]
> I'm running in docker, you too?

Now I do without issues. But when I reported this I was using a package (the DS111 does not support Docker).

**Comment by coenboomkamp** [comment]
> > I'm running in docker, you too?
> 
> Now I do without issues. But when I reported this I was using a package (the DS111 does not support Docker).

Okay, i'll do some more digging, thnx for the quick replies 👍
