### ISSUE TITLE
SynoCommunity.com Package Version Discrepancy

### ISSUE THREAD

**Issue by byronmccollum** [SynoCommunity/spksrc#2789]
### Setup
_Package Name:_ SABnzbd
_Package Version:_ v2.0.0-24

_DSM version:_ DSM 5.2-5644

### Issue

On SynoCommunity.com, SABnzbd has a discrepancy between the version displayed on the [list of packages](https://synocommunity.com/packages) (v2.0.0-24), and on the [package details](https://synocommunity.com/package/sabnzbd) (v2.0.1-28).

My Synology alerts that an update is available, but when I go to Package Center, it says everything is up-to-date.

I don't know if these are two separate issues, or are somehow related. Not knowing how a SPK repository actually works, I can only guess there is some discrepancy between the index, and the actual package that is published.

**Comment by KaraokeStu** [comment]
Hi,

I pulled a couple of versions down that had a partially broken par2 binary.

This should now have been resolved and you should find it all works as expected now :)
