### ISSUE TITLE
SABnzbd updates not showing

### ISSUE THREAD

**Issue by Tiwas** [SynoCommunity/spksrc#2794]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_SABnzbd
_Package Version:_2.0.1-28

_NAS Model:_DS412+
_NAS Architecture:_Intel Atom
_DSM version:_DSM 6.1.1-15101 Update 4

### Expected behavior
Show available updates

### Actual behavior
Nothing

### Steps to reproduce
_1._N/A

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Tiwas** [comment]
Isn't it possible to update these packages? Under packages center, settings, auto update the synocommunity packages are greyed out, but I would expect (well - hope, as I truly love the effort by you guys) to be able to update packages. I probably could make a backup, remove the installation, install the new version and restore - but if there's some way to update that would obviously be better.

Thanks!

**Comment by KaraokeStu** [comment]
Updates work, but you still have to push the "Update" button when a new version is available.

Auto update does not work, however, as I think that is reserved for official packages.

**Comment by Tiwas** [comment]
I'm sorry, but as far as I can see 2.1.0 is released, but there's no update. Please correct me if I'm incorrect, but shouldn't it show up in package center as an available update?

**Comment by KaraokeStu** [comment]
Hi, it will do, as soon as we have merged and built the changes and then applied them to the repository.

The package repos need to be built once a new version of the software comes out

**Comment by Tiwas** [comment]
Ok, thanks. First synocommunity update ever for me and I just assumed the status meant something was wonky with my setup. I'll sit back down, then.

Thanks, and thanks for the effort :)

**Comment by KaraokeStu** [comment]
@Tiwas Just so you know, @Safihre is one of the developers of sabnzbd and between the two of us, we help maintain the package here at SynoCommunity.

FYI 2.0.1 has been uploaded for sabnzbd-testing and it'll be up for stable within the next couple of hours 👍

**Comment by Tiwas** [comment]
Cool! Good to know we're in the best hands :D
