### ISSUE TITLE
pyextdirect.configuration issue when launching debian-chroot package

### ISSUE THREAD

**Issue by Avataar120** [SynoCommunity/spksrc#2799]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Debian-chroot
_Package Version:_ 8.4

_NAS Model:_ DS1815+
_NAS Architecture:_ Avoton
_DSM version:_6.1

### Expected behavior
I have successfully compiled python package with spksrc DSM 6.1 toolchain (avoton-gcc493_glibc2​20_linaro_x86_64-GPL) + installed the package on my NAS
I have successfully compiled debian-chroot with the same toolchain and installed it on my NAS

I except to be able to launch debian-chroot on my NAS

### Actual behavior

When I click on start package, after few seconds, I get a popup : failed to repair the package
If I try to launch it in SSH window I get the following result :

Traceback (most recent call last):
  File "./start.py", line 2, in <module>
    from application.direct import Services
  File "/volume1/@appstore/debian-chroot/app/application/direct.py", line 1, in <module>
    from pyextdirect.configuration import create_configuration, expose, LOAD, STORE_READ, STORE_CUD
ImportError: No module named pyextdirect.configuration

### Steps to reproduce
_1._ Compile and install python
_2._ Compile and install debian-chroot
_3._ launch debian-chroot in SSH

Thanks for your help.
Nota : 
If I try to compile and install the packages manually, it's because I cannot anymore add the package source synocommunity on my NAS (I don't understand why) ...
My NAS is able to contact packages.synocommunity.com (nslookup is OK) but when I try to add the source I get a message : invalid location.
Any idea on this issue also ?

**Comment by VinxItak** [comment]
@Avataar120 "I just had to install pyextdirect module and another one to make it works."

Which was "another one" ?
I have installed pyextdirect, now i no more have "ImportError: No module named pyextdirect.configuration". But still not able to launch Debian Chroot

**Comment by VinxItak** [comment]
@jvdassen 
Yeah i'm sure, first i imported it using "python -m pip install pyextdirect", but still have "ImportError: No module named pyextdirect.configuration". (python --version = 2.7.13)
Then I used python from devian chroot path (2.7.12) to install it, with success.
I tried again to launch debian chroot, I don't have anymore the error "ImportError: No module named pyextdirect.configuration", but it doesn't start. (and no error message)

**Comment by jvdassen** [comment]
@VinxItak 
>  I don't have anymore the error "ImportError: No module named pyextdirect.configuration", but it doesn't start. (and no error message)

I used the same approach that you stated to solve the Import issue. The chroot not starting must then be somewhere else. How are you starting the chroot?

**Comment by VinxItak** [comment]
@jvdassen 

good point for you :+1: 
 
pyextdirect was installed here :
/usr/lib/python2.7/site-packages/pyextdirect
/volume1/@appstore/debian-chroot/env/lib/python2.7/site-packages/pyextdirect

but was missing here :
/volume1/@appstore/python/lib/python2.7/site-packages/pyextdirect

after import, debian chroot starts normaly

thank you !
