### ISSUE TITLE
Filebot Missing From Synocommunity Packages?

### ISSUE THREAD

**Issue by stoic74** [SynoCommunity/spksrc#2802]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Filebot
_Package Version:_?

_NAS Model:_DS412+
_NAS Architecture:_
_DSM version:_6.1.2

### Expected behavior
Package Center-->Community should list Filebot as it always had in the past.

### Actual behavior
All typical packages I've seen before are present but no Filebot.

### Steps to reproduce
_1._ Tried several times.
_2._ Deleted existing Filebot and Filebot Node but nothing to reinstall from.
_3._ Updated Java SE from 1.8.0_111 to 1.8.0_131

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_Checked package center at SynoCommunity and no availability was listed.
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by KaraokeStu** [comment]
Filebot has not been available via SynoCommunity for a number of years now.

Please follow the instructions here:

https://www.filebot.net/forums/viewtopic.php?t=1802
