### ISSUE TITLE
No torrent clients

### ISSUE THREAD

**Issue by xadonxander** [SynoCommunity/spksrc#2804]
There are no torrent clients listed. I really need a torrent client and do not have access to docker.

**Comment by KaraokeStu** [comment]
Hi, you'll need to give us a bit more information, I'm afraid...

What system are you using?
What version of DSM are you using?

We currently have the following clients supported within SynoCommunity:

- Transmission
- Deluge
- Flexget
- ruTorrent

You can also use the Synology Download station (which is based off Transmission anyway)

**Comment by xadonxander** [comment]
intel based server
DSM 6.1.2-15132

None of those come up in the list. Download station is a PITA to use.

**Comment by KaraokeStu** [comment]
Can you let us have your exact model please? 

Sounds as though you may have one of the new architecture systems and dsm 6, neither of which are officially supported yet

**Comment by piwi82** [comment]
XPEnology ? 😅

**Comment by xadonxander** [comment]
NAS Model: DS3617xs
NAS Architecture: x86_64
DSM version: 6.1.2

**Comment by Safihre** [comment]
Test packages for DSM6.1 and various architectures are available here #3138. They also include a new way of handling permissions.
We hope to publish the packages to the official repo soon and appreciate all testing and reports on the functioning of these packages.
