### ISSUE TITLE
Adding synocommunity repo issue

### ISSUE THREAD

**Issue by Avataar120** [SynoCommunity/spksrc#2806]
_NAS Model:_ DS1815+
_NAS Architecture:_ Avoton
_DSM version:_ 6.1

Hello, I'm trying to add http://packages.synocommunity.com as a new packet source on my NAS.
It was working perfectly until I decide to re-install my NAS from scratch 2-3 days ago.

DNS are ok : 

Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   packages.synocommunity.com
Address: 104.31.95.179
Name:   packages.synocommunity.com
Address: 104.31.94.179

I have authorized all packet sources in the general tab of package center

But when I try to install synocommunity package source, I get the message : invalid location.

has anybody an idea on this issue ?

Thanks a lot.

**Comment by Trapperjohn61** [comment]
Hi, 
  I have the name as synocommunity
The address as: http://packages.synocommunity.com/
With this setting I am able to download packages from the community. 
Thanks, 
Bryan

**Comment by KaraokeStu** [comment]
Hi, try to use https instead,

Cheers,

Stu

**Comment by Avataar120** [comment]
Hello, I already tried, but forgot to tell it in the description ... :)

**Comment by auanasgheps** [comment]
Hi, I have the same issue on DS215j (DSM 6.1.2-15132)
No matter if i try http://packages.synocommunity.com/ or https://packages.synocommunity.com/, I get **Invalid Location**

**Comment by rugebiker** [comment]
In my case the packages don't even show up in the package center =/ I tried both http and https. 

DSM 6
DS216j

**Comment by rugebiker** [comment]
oh my bad, I had to enable the Beta ones separately. I don't have this issue then.

**Comment by initramfs** [comment]
Experiencing the same issue on a DS215j (DSM 6.1.3-15152).

**Comment by ilatimerP** [comment]
Same with DDSM on a DS415+
Any updates?
Cheers

**Comment by auanasgheps** [comment]
Can anybody help please? 
Thanks

**Comment by Safihre** [comment]
This is usually a local issue with DNS lookups or certificate problems.
Make sure those are up to date (via latest DSM).
