### ISSUE TITLE
Python IPv6 support

### ISSUE THREAD

**Issue by devJayden** [SynoCommunity/spksrc#2810]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Python
_Package Version:_2..7.13-16

_NAS Model:_DS412_
_NAS Architecture:_
_DSM version:_6.X

### Expected behavior
SabNZB can't take IPV6 download services. 

### Actual behavior
Error message.

### Steps to reproduce
1. Use any ipv6 downloader after testing you can contact IPv6 on the internet on the synology. 

I am looking to have the python package compiled with --enable-ipv6.  My understanding is it is disabled without this.

**Comment by KaraokeStu** [comment]
Not to the best of my knowledge, it worked perfectly well with ipv6 for me on my synology device.

Have you tested you can ping the host via ipv6 and that your ipv6 setup is correct?

**Comment by devJayden** [comment]
Got it working.  Turns out I have to manually resolve using nslookup on the synology then use the ipv6 address.  So this is more an issue thatnewszilla6.xs4all.nl <http://newszilla6.xs4all.nl/> has both a ipv6 and ipv4 address that resolve.  No way to force to ipv6 within sabnzbd. 

Jayden

**Comment by KaraokeStu** [comment]
There is an option in sabnzbd to prefer ipv6 addresses when multiple addresses are found for the same ip.

That said, if they resolve to the same server, there is no additional benefit to using ipv6.

If your address isn't resolving properly, try using the opendns ipv6 name servers

**Comment by Safihre** [comment]
@devJayden yes you can force sabnzbd to only use IPv6, it's a Special setting `ipv6_servers` (bottom of page) 
https://sabnzbd.org/wiki/configuration/2.1/special
