### ISSUE TITLE
NZBGet update to latest stable v19

### ISSUE THREAD

**Issue by SavellM** [SynoCommunity/spksrc#2811]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ NZBget
_Package Version:_ Stable version: 19.0 (25 June 2017)

Please could you update NZBget to the latest stable version.

**Comment by scelestic** [comment]
For the dsm6 branch I've updated nzbget-testing to 19.0 final, compiled tested and tested on armadaxp as fully functional. See my nzbget 18.0 pull request if interested in compiling it yourself.

**Comment by janbal** [comment]
any chance we will have the final availble soon?

**Comment by Aimhere2k** [comment]
Any word on when v19 will hit the DSM6 Package Center?

**Comment by Safihre** [comment]
Test package for new-style NZBGet has been released: #3138.
We no longer compile it here on the repo, but fetch the latest official installer from NZBGet.
During package installation you can choose if you want the latest stable or testing release. After this you can use NZBGet's internal update system to do updates. It also includes updates to user-management.
We hope to soon publish this on the official repo.
