### ISSUE TITLE
Building Chromaprint for armada38x

### ISSUE THREAD

**Issue by gravelld** [SynoCommunity/spksrc#2812]
I'm trying to build Chromaprint for the armada38x in DSM 6.1. I can build and install it, but when I run it I get:

    /usr/local/chromaprint/bin/fpcalc: error while loading shared libraries: libx264.so.148: cannot open shared object file: No such file or directory

I think this is because of #2756 - the ffmpeg bundled in 216j does not have H.264 support.

Is there a way of building Chromaprint to work, maybe to statically include Synocommunity's ffmpeg (which I believe does have `libx264.so`)?

Sorry, bit of a noob.

**Comment by ymartin59** [comment]
Hello
Here is the package I produced for upgraded version to 1.3.2 for armada38x DSM 6.1
[chromaprint_armada38x-6.1_1.3.2-4.spk.zip](https://github.com/SynoCommunity/spksrc/files/1220349/chromaprint_armada38x-6.1_1.3.2-4.spk.zip)
Let me know if it works well or if you faced any issue when testing/using

**Comment by gravelld** [comment]
Yep, works!

Should this ticket only be considered closed when the changes have been merged into master?

**Comment by ymartin59** [comment]
I would appreciate that this issue is closed as soon as possible. DSM 6.x support is a track on its own.

**Comment by gravelld** [comment]
Is there a consolidated ticket or PR that is the canonical way of tracking DSM 6.x support? Bit confused...

**Comment by ymartin59** [comment]
Not really. A label "dsm6" is available for issues: https://github.com/SynoCommunity/spksrc/issues?page=1&q=is%3Aissue+is%3Aopen+dsm+label%3A%22dsm+6.0%22
