### ISSUE TITLE
New NAS, packages only show up partially?

### ISSUE THREAD

**Issue by spacekiek** [SynoCommunity/spksrc#2813]
### Setup
_Package Name:_ Synocommunity repo

_NAS Model:_ DS3617xs
_NAS Architecture:_ x86
_DSM version:_ 6.1.2

### Expected behavior
Need to instally "GIT & Python" before I can install Couchpotato

### Actual behavior
Only a few packages show up in my community Tab 
For example:  Couchpotato / Headphones / Cops / Beets / Mono ...

**Comment by KaraokeStu** [comment]
Hi,

This is due to the new Braswell architecture.

I'm waiting on @Diaoul and @Dr-Bean to sort this out.

**Comment by spacekiek** [comment]
Hi

DS3617xs is Broadwell apparently. But I guess the same issue.
Also see: https://github.com/SynoCommunity/spksrc/issues/2509#issuecomment-312887011

**Comment by nicduch** [comment]
Same with my DS918+ (Celeron J3455)

**Comment by Safihre** [comment]
Test-packages with new DSM6 compatibility and for all architectures are available in #3138. Please report any problems there.
After the official release on SynoCommunity, the package will auto-update from the official release.
