### ISSUE TITLE
Synology Router

### ISSUE THREAD

**Issue by ScoobyJD** [SynoCommunity/spksrc#2814]
### Expected behavior
Install SynoCommunity on Synology Router

### Actual behavior
Epic sadness

### Steps to reproduce
_1._Go to SynoCommunity.com
_2._See there is no way to install on Synology Router
_3._Go cry in corner

**Comment by ymartin59** [comment]
I would say - known issue: #1869

See also: https://synopackages.wordpress.com/2016/02/21/synocommunity-packages-for-rsm/
