### ISSUE TITLE
When is it planned to update Apache HTTP Server from version 2.2 to 2.4?

### ISSUE THREAD

**Issue by SeppPenner** [SynoCommunity/spksrc#2821]
I just wanted to know when it's planned to officially update Apache HTTP Server from version 2.2 to 2.4 since the package is already available from Apache and in the Syno-Package-Store?

**Comment by cytec** [comment]
Uhm... we don't provide a SPK for Apache see https://synocommunity.com/packages for all available Packages we provide.

**Comment by SeppPenner** [comment]
So where do this packages come from? 
![grafik](https://user-images.githubusercontent.com/9639361/28165689-24ff1924-67d5-11e7-8ee4-3d1fc4a6f2b1.png)

**Comment by SeppPenner** [comment]
@cytec Ah, I see. This is a package provided by Synology directly and is developed by another third party vendor. Sorry for the inconveniences here... Just got a little confused here...
