### ISSUE TITLE
When is it planned to update PHP from version 5.6 to 7.0?

### ISSUE THREAD

**Issue by SeppPenner** [SynoCommunity/spksrc#2822]
I just wanted to know when it's planned to officially update PHP from version 5.6 to 7.0 since the package is already available from Apache and in the Syno-Package-Store?

**Comment by cytec** [comment]
we don't provide a SPK for PHP see https://synocommunity.com/packages for all available Packages we provide.

**Comment by SeppPenner** [comment]
Same as for the Apache HTTP server... Where do this packages come from then?
![grafik](https://user-images.githubusercontent.com/9639361/28165721-4bf97196-67d5-11e7-9252-1cb163d97dce.png)

**Comment by SeppPenner** [comment]
@cytec Ah, I see. This is a package provided by Synology directly and is developed by another third party vendor. Sorry for the inconveniences here... Just got a little confused here...
