### ISSUE TITLE
[Package Request] rhash

### ISSUE THREAD

**Issue by skydiver** [SynoCommunity/spksrc#2823]
Name: rhash
Description: RHash (Recursive Hasher) is a console utility for computing and verifying hash sums of files.
Website: http://rhash.anz.ru/
Software documentation: http://rhash.anz.ru/manpage.php
Build/Installation documentation: https://sourceforge.net/projects/rhash/files/rhash/
Source Code: https://sourceforge.net/projects/rhash/files/rhash/
License: http://rhash.anz.ru/license.php

(I'm using this [standalone bin](http://files.venture37.com/pkgsrc/packages/Linux/Debian/armv7l/All/rhash-1.3.4.tgz))

**Comment by m4tt075** [comment]
Well, it has been some time. I'm looking into merging @frerike's work on `rhash` as part of a bigger `SynoCLI-file` package. If you are interested, please feel free to track any progress in issue #3250 and PR #3598. 

For everyone, test-builds of the `SynCLI-file` package for all currently supported DSM5.2, 6.1 and 6.2 platforms are available here:  https://github.com/m4tt075/spksrc/releases/tag/synoclifile-2
Please report any issues in #3250, not here.
