### ISSUE TITLE
create package: mosquitto-authentification-plugin

### ISSUE THREAD

**Issue by chipec84** [SynoCommunity/spksrc#2826]
Name: mosquitto-authentification-plugin

Description: 
This is a plugin to authenticate and authorize Mosquitto users from one of several distinct back-ends:

MySQL
PostgreSQL
CDB
SQLite3 database
Redis key/value store
TLS PSK (the psk back-end is a bit of a shim which piggy-backs onto the other database back-ends)
LDAP
HTTP (custom HTTP API)
JWT
MongoDB
Files

Source Code: https://github.com/jpmens/mosquitto-auth-plug.git

Thank you
Pierre.

**Comment by ymartin59** [comment]
Sounds relevant to be included to Mosquitto package itself with next update.

**Comment by chipec84** [comment]
Thank you for your reply. Can't wait for the next update!

**Comment by ymartin59** [comment]
mosquitto has been updated

**Comment by chipec84** [comment]
Thank you for the update, I found my way around by building a Docker image.

**Comment by hgy59** [comment]
As the mosquitto-auth-plug project is archived per 2019-03-11, I will not include it in the next update with #5810
