### ISSUE TITLE
Can't find comskip?

### ISSUE THREAD

**Issue by keithah** [SynoCommunity/spksrc#2830]
I see the previous commits, but I don't see it in the source tree, has it been removed? Any I missing something?

Thanks!

**Comment by KaraokeStu** [comment]
It depends on what version of dsm and which architecture you are using.

Could you let us know please?

**Comment by cytec** [comment]
@keithah comskip was not merged yet see: https://github.com/SynoCommunity/spksrc/pull/2673

**Comment by ymartin59** [comment]
@KaraokeStu @cytec OK so now `comskip` has been merge to `master`, may it be possible to publish it in repository (for DSM 5.2 only) so that this issue can be closed ?

**Comment by cytec** [comment]
@ymartin59 it's currently building

**Comment by cytec** [comment]
published

**Comment by ymartin59** [comment]
@cytec great thanks. for information, I am updating "chromaprint" to use latest "ffmpeg". when over I will publish both after PR
