### ISSUE TITLE
Redis "Failed to run the package service."  DS116

### ISSUE THREAD

**Issue by ilmtr** [SynoCommunity/spksrc#2832]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Redis
_Package Version:_ 3.0.5-5

_NAS Model:_ DS116
_NAS Architecture:_ ARM
_DSM version:_ DSM 6.1.3-15152 Update 1

### Expected behavior
Redis should run

### Actual behavior
"Failed to run the package service."

### Steps to reproduce
_1._ Install Redis from SynoCommunity, - Package Center
_2._ Press Run

#### Package log
_Check Package Center or `/usr/local/redis/var/`_
there is no log available

#### Other logs
`/var/log/synopkg.log`_
2017/07/21 09:49:20 (system) trigger redis 3.0.5-5 End start-stop-status stop ret=[0]
2017/07/21 09:49:20 (system) trigger redis 3.0.5-5 Begin unload apparmor
2017/07/21 09:49:20 (system) trigger redis 3.0.5-5 End unload apparmor ret=[0]
2017/07/21 09:49:20 stop redis: begin to stop version 3.0.5-5
2017/07/21 09:49:20 stop redis: stop version 3.0.5-5 successfully, result 0
2017/07/21 09:49:20 start redis: start version 3.0.5-5 failed, result 1
2017/07/21 09:56:22 start redis: begin to start version 3.0.5-5
2017/07/21 09:56:22 start redis 3.0.5-5 Begin pre-load apparmor
2017/07/21 09:56:22 start redis 3.0.5-5 End pre-load apparmor ret=[0]
2017/07/21 09:56:22 start redis 3.0.5-5 Begin start-stop-status start
Starting Redis ...
su: Permission denied
2017/07/21 09:56:23 start redis 3.0.5-5 End start-stop-status start ret=[1]
2017/07/21 09:56:24 (system) trigger redis 3.0.5-5 Begin start-stop-status stop
Redis is not running
2017/07/21 09:56:24 (system) trigger redis 3.0.5-5 End start-stop-status stop ret=[0]
2017/07/21 09:56:24 (system) trigger redis 3.0.5-5 Begin unload apparmor
2017/07/21 09:56:24 (system) trigger redis 3.0.5-5 End unload apparmor ret=[0]
2017/07/21 09:56:24 stop redis: begin to stop version 3.0.5-5
2017/07/21 09:56:24 stop redis: stop version 3.0.5-5 successfully, result 0
2017/07/21 09:56:24 start redis: start version 3.0.5-5 failed, result 1

**Comment by ymartin59** [comment]
Known issue with DSM 6.1 - packages have not been built for DSM 6.1 yet

**Comment by SirSiggi** [comment]
Solution: Replace the su line 19 in the start-stop-script with

sudo -u ${USER} ${REDIS} ${CFG_FILE}

Before it used "su" but that does not seem to work any longer.

**Comment by nover** [comment]
The mentioned start-stop-script is located at `/var/packages/redis/scripts/start-stop-status`

**Comment by hgy59** [comment]
fixed with v5.0.7-6
