### ISSUE TITLE
SiCKRAGE package at https://synocommunity.com/package/sickrage outdated

### ISSUE THREAD

**Issue by echel0n** [SynoCommunity/spksrc#2840]
I noticed our package located at https://synocommunity.com/package/sickrage is a much older version and we've recently merged our latest version to spksrc a few days ago.

Would it be possible to get this up dated and also added to show up on https://synocommunity.com/packages page please.

Thanks!

**Comment by echel0n** [comment]
I've recently updated the requirements.txt as well and made PR for it as previous requirements.txt had lxml which wasn't needed and caused issues with compiling the spk, PR is https://github.com/SynoCommunity/spksrc/pull/2843

**Comment by KaraokeStu** [comment]
I'll get this published later today

**Comment by KaraokeStu** [comment]
Published
