### ISSUE TITLE
SiCKRAGE package wheel requirements don't seem to be installing

### ISSUE THREAD

**Issue by echel0n** [SynoCommunity/spksrc#2847]
I don't have a Syno device to test with but the package that recently got published seems to install fine other then the wheels as the app starts up and complains about import issues

No module named apscheduler.schedulers.tornado

Could you please confirm the wheels are being properly installed or point me in the right direction so I can, thanks!

**Comment by MattDevo** [comment]
I can confirm that the current package is broken / doesn't start  =/

**Comment by echel0n** [comment]
Currently just getting a DSM device setup over here so I can make a few tests with the package and see what's holding this up, if a member from this repo has insight I'm happy to read as well :)

**Comment by echel0n** [comment]
So after further testing of the package building it appears as if the wheels are not getting added into the package, can anyone confirm this please and explain why ?

**Comment by pkroeze** [comment]
The new build doesn't start with me either
