### ISSUE TITLE
Disk Utils keeps 'Stopped'

### ISSUE THREAD

**Issue by EdKo66** [SynoCommunity/spksrc#2854]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Disk Utils
_Package Version:_

_NAS Model:_ 413j
_NAS Architecture:_Armv5 (I think
_DSM version:_  6.1

### Expected behavior
App should be running

### Actual behavior
Doesn't run, stays on 'stopped'.

### Steps to reproduce
_1._ Install
_2._ Activate
_3._ wait

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
No such directroy /var/ in package
Insert the package log here
No log
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
[messages.txt](https://github.com/SynoCommunity/spksrc/files/1184053/messages.txt)

**Comment by Diaoul** [comment]
This package contains disk utilities available in `/usr/local/disk-utils`, in subfolders `bin` and `sbin`. It is not runnable.

**Comment by EdKo66** [comment]
Thanks. Had hoped it was runnable

**Comment by ymartin59** [comment]
Package metadata contains `STARTABLE = no`. I really wonder why DSM still proposes to run a package, maybe because start/stop scripts are available ?

**Comment by Diaoul** [comment]
Maybe newer DSMs ignore that.

**Comment by KaraokeStu** [comment]
Closing as not an issue
