### ISSUE TITLE
Unable to start Headphones

### ISSUE THREAD

**Issue by mnervik** [SynoCommunity/spksrc#2859]
Brand new DS1517+ running DSM 6.1. Installed Headphones package but unable to start it. Fails with the message "Failed to run the package service."

Running "/var/packages/headphones/scripts/start-stop-status start" command returns the error message saying: "user headphones does not exist". Do I need to manually create a headphones user, or is there somthing else I need to do?

**Comment by ymartin59** [comment]
Known issue. DSM 6.x support is not yet available.

**Comment by Safihre** [comment]
DSM6 compatible version of the package is expected to be released soon. It can already be installed by downloading it from here #3138.
After the official release on SynoCommunity, the package will auto-update from the official release.
