### ISSUE TITLE
PyLoad doesn't launch : error while repairing 

### ISSUE THREAD

**Issue by Nemrod7** [SynoCommunity/spksrc#2861]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_pyLoad
_Package Version:_v0.4.9-2

_NAS Model:_
_NAS Architecture:_
_DSM version:_DSM 6.0.3-8754 Update 4

### Expected behavior Running Pyload
PyLoad should run

### Actual behaviorError message, unable to run PyLoad
I get an error message : "error while repairing package".

### Steps to reproduce
_1._Download PyLoad
_2._Launch Pyload
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Safihre** [comment]
Further PyLoad updates (like DSM6 compatibility) via #2259.
