### ISSUE TITLE
Problem with rutorrent, torrents doesn't appear as completed

### ISSUE THREAD

**Issue by magicgg91** [SynoCommunity/spksrc#2862]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ rutorrent
_Package Version:_ 3.8

_NAS Model:_ 2413+
_NAS Architecture:_
_DSM version:_ 6.1

### Expected behavior
Tell us what should happen

Torrents dosen't appear as completed on tracker

### Actual behavior
Tell us what happens instead

Torrends are downloading and seeding well, but not appears as completed on the tracker website

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by th0ma7** [comment]
New and update to `rutorrent` version 3.10 uploaded on https://synocommunity.com/package/rutorrent
