### ISSUE TITLE
resize2fs bug in "Disk Utils" 1.42.6 (kindly ask to to update the package)

### ISSUE THREAD

**Issue by endelight** [SynoCommunity/spksrc#2863]
### Setup
Package Name: Disk Utils
Package Version: 1.42.6-1

NAS Model: 1813+
NAS Architecture: x86_64 INTEL Atom D2700 // cedarview
DSM version: 6.1.3

### Expected behavior
resize2fs work properly on large (15 TB) ext4 partition. 

### Actual behavior
I can't resize my partition as I get the following error message:

resize2fs 1.42.6 (21-Sep-2012)
resize2fs: /dev/vg1/volume_2: The combination of flex_bg and
        !resize_inode features is not supported by resize2fs.

### Steps to reproduce
1. Have an ext4 partition using flex_bg and !resize_inode.
2. Try to shrink it.
3. Above error appears.

### Bug actually fixed
In the release note of e2fsprogs here:

[http://e2fsprogs.sourceforge.net/e2fsprogs-release.html#1.42.8](http://e2fsprogs.sourceforge.net/e2fsprogs-release.html#1.42.8)

it is mentioned that the above bug has been fixed. The solution of my problem (and probably for others too) would be to just update the SynoCommunity package "Disk Utils" at least to 1.42.8 (June 20, 2013). The newest release is 1.43.4 (January 31, 2017).

Thank you very much,
endelight

**Comment by ymartin59** [comment]
Surpringly, DSM 6.1 comes in standard with `/sbin/resize2fs` in version 1.42.6.
Sounds possible to provide latest release of `e2fsprogs`. I try to get `screen` updated to even if original bundle does not support cross-compiling.

**Comment by jortkeldert** [comment]
Any news on porting resize2fs? A new version helps to overcome the 16TB limit

**Comment by hgy59** [comment]
The package synocli-disk contains `e2fsprogs 1.45.6` (the package "Disk Utils" is abandoned).
