### ISSUE TITLE
Can't add the SynoCommunity source to Docker DSM (DDSM)

### ISSUE THREAD

**Issue by miguelmmm** [SynoCommunity/spksrc#2866]
Hi, I setup a Docker DSM (DDSM) and I'm trying to add the SynoCommunity source to the Package Center within the DDSM. Every time I try, I get an "Invalid Location" message.
I contacted Synology about this and this is their response: Unfortunately this is an issue in which the community server http://packages.synocommunity.com/ does not recognize Docker DSM's model, so it cannot return the package list correctly. Essentially synocommunity did not develop packages for Docker platform. Therefore, no available package list is sent. You would need to contact the developers at synocommunity to resolve this issue.
Are there any plans to support Docker DSM or is there a way to make it work?

Thanks for the help!

**Comment by ymartin59** [comment]
First we have to fix support for DSM 6.x before investigating how to extend to Docker DSM or SRM...

**Comment by ilatimerP** [comment]
Is there any update on this issue.  Is there anyway we can install the package manually or is that not an option.
Cheers

**Comment by ilatimerP** [comment]
Hi ymartin59
I was looking at using Transmission, SquidGuard, Adminer.
Thanks for the quick response.
Cheers

**Comment by ymartin59** [comment]
OK toolchain is identical to x64, so it is easy to produce packages. I have no Docker support on my x86 synology, so if there is a way to run "Docker DSM" on a regular Linux distribution, let me know !

Here is `transmission` package from `dsm6` branch for "Docker DSM". Warning: Not tested at all...
[transmission_dockerx64-6.1_2.92-12.spk.zip](https://github.com/SynoCommunity/spksrc/files/1223300/transmission_dockerx64-6.1_2.92-12.spk.zip)

**Comment by ymartin59** [comment]
@ilatimerP  I did a quick response. May I expect any feedback about your tests of the provided package ?

**Comment by ilatimerP** [comment]
@ymartin59 Sorry about the late response.  I did install it as soon as you posted it and it installed without any issues.  I was also able to log in via the Web gui.  I will download the latest CentOS via transmission to confirm.
Cheers
Isaac

**Comment by ilatimerP** [comment]
@ymartin59 I have tested it and it is running well.  Do you think the repo will ever be added to DDSM?

**Comment by ymartin59** [comment]
To be honest, I am working on repository performance tuning and testing to get DSM 6.x support online... and that is time consuming. If DDSM is no different from DSM 6.x, it may be added then easily.

**Comment by ymartin59** [comment]
@ilatimerP As you requested for Adminer, which is platform independant, this one should run properly on Docker DSM. Let me know if anything wrong.
[adminer_noarch-all_4.2.5-2.spk.zip](https://github.com/SynoCommunity/spksrc/files/1282463/adminer_noarch-all_4.2.5-2.spk.zip)

**Comment by nelissuh** [comment]
I have also tested the transmission_dockerx64-6.1_2.92-12.spk.zip by ymartin59 and it is running fine on DDSM.

**Comment by ymartin59** [comment]
Thanks for betatesting. I am working on squidGuard but it is a complex one. My best option is to resurrect #1676 which has not been merged (for obscure raison) but then I have to adapt installer script to DSM 6.x...

**Comment by ymartin59** [comment]
You should find `mosquitto` as first package specifically available for Docker DSM architecture

**Comment by Safihre** [comment]
Docker support seems to be fine now, closing this.

**Comment by nelissuh** [comment]
Thanks!
