### ISSUE TITLE
[Request] ffmpeg with libsoxr

### ISSUE THREAD

**Issue by ruiumbelino** [SynoCommunity/spksrc#2868]
### Setup
_Package Name: ffmpeg
_Package Version: 3.1.2-4

_NAS Model: Synology DS215j
_NAS Architecture: Armada375
_DSM version: DSM 6.1.3-15152 Update 1

### Request
It's possible to build this package with libsoxr?

Thanks

**Comment by ymartin59** [comment]
Update already in progress: #2865

**Comment by ymartin59** [comment]
Hello

Here is the requested package, packed as zip because of github attachment restrictions
[ffmpeg_armada375-6.1_3.3.3-7.spk.zip](https://github.com/SynoCommunity/spksrc/files/1221290/ffmpeg_armada375-6.1_3.3.3-7.spk.zip)

Let me know if it works well or if you have any issue

**Comment by ruiumbelino** [comment]
How can I call the ffmpeg process?

I'm trying to use 'ffmpeg' as stream.converter, inside MinimServer, but for now still show that is not compatible with convOut setting.

Thanks

Thanks

**Comment by ruiumbelino** [comment]
After some search, using this command '/volume1/@appstore/ffmpeg/bin/ffmpeg' it's working... :)

**Comment by ymartin59** [comment]
Correct. ffmpeg is not added to PATH by default as Synology DSM provides a old version.
Please close this issue.
