### ISSUE TITLE
Synology with XPenology missing packages (DS3617xs)

### ISSUE THREAD

**Issue by Miicker** [SynoCommunity/spksrc#2870]
I wan't to install Python from the SynoCommunity Repository on my home made NAS. It runs XPenology and simulates a DS3617xs. The DSM version i'm running is: 6.1.3 15152 update 1.

I had a DS216Play with the same DSM version, and at that machine way more packages were visible in the package center.

Screenshots:
I've trusted installations from third parties:
https://i.imgur.com/DpCJSTZ.png

I've added the Syno as a repo:
https://i.imgur.com/nwIehHx.jpg

The SynoCommunity certificate is installed:
https://i.imgur.com/jyL3CNO.png

All packages from the community (as you can see a few are visible from the SynoCommunity):
https://i.imgur.com/auh5F3P.png

When I look at all packages starting with a P (looking for Python), no Python package from the SynoCommunity is shown:
https://i.imgur.com/1JzFW0q.png

I've saw more people with this problem, but haven't found a solution.

**Comment by M0UL** [comment]
DSM 6 is not supported yet on SynoCommunity.

**Comment by Miicker** [comment]
@M0UL Then why where all those packages available on my old DS216Play with DSM 6?

**Comment by M0UL** [comment]
probably because you updated from 5.

**Comment by BenjV** [comment]
Has nothing to do with DSM 6 support
On my new NAS which was installed from scratch with DSM 6 I see all the packages asl well as on my old NAS which was upgraded from DSM 5.

The  DS3617xs is probably not yet added to the SynoCommunity.

The

**Comment by ymartin59** [comment]
At the moment, package repository server does not support upload of DSM 6.x packages (and DS2617xs has no DSM 5.2 toolchain). A patch is available but has to be reviewed and tested before going to production. Job is in progress.

@Miicker I am interested to know where you find instructions to run DSM 6 on XPenology. May you point me references you used ?

**Comment by Stealth401** [comment]
I have the similar issue with Git and Python are missing.

This is what i am running 

https://xpenology.com/forum/topic/7507-tutorial-installmigrate-dsm-52-to-602-juns-loader/#comment-56071

**Comment by Miicker** [comment]
@ymartin59 the way @Stealth401 uses it is the exact same way I installed DSM 6.

**Comment by m4vr0x** [comment]
I confirm
I have a Proxmox VM with DSM 6.1 and DS3617xs definition and the packages are not all present (debian-chroot for example).
I have the same VM with DSM 6.1 and **DS3615xs** and all the packages are there.

I have assumed it could be caused by the CPU arch definition :
- 3615 has Bromolow CPU
- 3617 has Broadwell CPU wich is not supported by Debian-Chroot on the same expample

What do you think ? Aren't just packages not compatible with Broadwell wich are not displayed on 3617 ?

**Comment by ymartin59** [comment]
Probably the only difference is package metadata containing target platform. I have recently added "Broadwell" 6.1 toolchain but no package has been published yet as repository lacks DSM 6.x support.

**Comment by BenjV** [comment]
The noarch packages like Python should be available.
They are not DSM version dependant.

**Comment by Stealth401** [comment]
I have just installed from scratch and this is all i see after adding the Synocommunity packages. 

![image](https://user-images.githubusercontent.com/31005940/29366990-63d0fb08-8293-11e7-8005-d958fbd5187d.png)

**Comment by ymartin59** [comment]
If interested, I may build Python 3.4.1 SynoCommunity package which provides "pip" and "wheels" requirements for python-based application packages.

**Comment by Drakuhl** [comment]
I also recently upgraded to a DS3617xs and was disappointed to find my favorite applications no longer work, so any help in getting support for this machine going would be appreciated.

**Comment by ruiqiu** [comment]
I have the same issues here. only show up some apps. not all when I had dsm5

**Comment by R1cco** [comment]
I'm having this same issue on my RS3617RPxs;

I'm trying to load Sonarr on my RS3617RPxs but no matter what I try and can't get the package to show up in Package center. I have the Synocommunity repo loaded and all publishers are trusted and checked the box for Beta's. I also have a DS1815+ running the exact same version of DSM 6.1.3-15152 and it shows up there just fine. What am I missing? Is there something about this box that would not allow it to install? AFAIK there shouldn't be any difference as it's an x86 platform.

Several packages show up but Sonarr and Transmission dont (the two that I want of course).

**Comment by XDomanX** [comment]
Hello.

Did anyone manage to install SyncThing on DS3617xs (XPenology)? I wonder if there is a workaround or should I revert back to DS3615xs?

**Comment by GranManuel** [comment]
Exact same problem here with DS3617xs (XPenology) running on Microserver G8. I think we can only wait. Reinstall using another type of Syno for boot is not an option now.

**Comment by Rhubarb1** [comment]
Reverted from Ds3617xs to Ds3615xs months ago to get the Synocommunity apps to work again.  I'm still waiting for the apps to be supported for DS3617xs before I go back to DS3617xs to get the benefits of my Xeon processor.

**Comment by BenjV** [comment]
What doe you think the benefit would be?
The physical cpu is still the same and the emulation does not add performance.
It would make no difference at all.

**Comment by Miicker** [comment]
@Rhubarb1 is it easy to revert? (Without data loss)

**Comment by vladimir-poleh** [comment]
@Miicker, yes, it is very easy, just replace loader with image for Ds3615xs (copy new image for VM, write it to the USB for barebone) and run. It will ask to migrate and install new DSM. Wait about 10 minutes and your system is ready. Just did it on my Microserver G8 with ESXi.

**Comment by Drakuhl** [comment]
Sadly, this does not help those of us with the actual machine in their house.

**Comment by sojab0on** [comment]
same here, my xpenology box runs on a Xeon quad core cpu, but my box doenst seen to get the install for GIT en Python working, so couchpotato and sickbeard wont install even cant find sabnzbd and nzbget to install them

**Comment by Miicker** [comment]
@sojab0on 
Your problems can be solves in a easy way: Use Docker.
Python is another story, I am still waiting for this request/bug/future to be fixed.

**Comment by sojab0on** [comment]
Docker is not useable, just because it uses the same dsm version als the basic box it runs on.
and there is a docker issue with multiple packages as well. ( correct me if i am wrong).

Already tried docker on the ds3617xs xpenology box, but the docker ddsm also register as ds3617xs so packages still remain gone.

**Comment by BenjV** [comment]
Why not use the DS3615xs version of Xpenology?
For that model are packages available.
Also you should use DSM 5, because there are no packages for DSM 6 yet available.

**Comment by Miicker** [comment]
@BenjV you know that's bullshit right?
I had a DS216Play with DSM6 and all packages were available from the SynoCommunity. Also saw people with DS3615xs version of Xpenology on DSM 6 where all packages where available.

**Comment by BenjV** [comment]
@Miicker 
Thanks for the bullshit compliment, always nice that people are polite when you are tring to help.

Of course the packages are available on all DSM version, they just don't work correct on DSM 6.
They are build for DSM 5.
Which means that on DSM 6 a lot of them don't work at all, others not correctly and a few work fine.

**Comment by Miicker** [comment]
@BenjV sorry, I did not intend to insult you. It’s just that I have ran several packages on DSM6 and they just worked fine. Also you mentioned about the same in this post: https://github.com/SynoCommunity/spksrc/issues/2870#issuecomment-322048524
What I’m trying to say is that changing to DS3615xs is not a real solution, it’s more like a work around as DS3615xs is basically the same as DS3617xs, so the SynoCommunity repo should just support it.

**Comment by BenjV** [comment]
No the DS3617xs has a different toolchain which is not yet release by Synology and if it is released there still has to be someone who will incorporate this toolchain in the spksrc environment and build packages for this architecture and also the spkrsc must be able to support DSM 6 packages.
But all effort from the SynoCommunity is now spent at creating DSM 6 capable spksrc environment.

As long as all those "if's" are not met, everybody who uses Xpenology should use DS3615xs and not DS3717xs. 
As I said before it will not make any difference at all, there is nothing to gain to use the DS3717xs.

And for the reason I mentioned before, use DSM 5 and not DSM 6 until the SynoCommunity is ready to support DSM 6.
Unfortunately people with the real hardware don't have that choice.

**Comment by vladimir-poleh** [comment]
@BenjV I'm using some packages from SynoCommunity with DSM 6.1.3 without any problems. At least Transmission and Syncthing are working. XPenology DS3615xs via ESXi on HP Microserver Gen 8 with Xeon 1220L.

**Comment by BenjV** [comment]
Sure some packages will work, but that just means that they build wrong and are running as root which is a big security issue (as it is in DSM 5)
Especially a package like Transmission which gets files from the internet should not run as root.

The whole change Synology made to the package centre in DSM 6, is not to have packages run as root with all the security risks involved with that.
Remember the Synolocker virus.

**Comment by sojab0on** [comment]
shure as hell do know that one, had to reformat both drive from my old ds212j nas in a linux mashine and reinstall everything on the ds212j again. 
back on topic, the DS365XS loader works flawlessly and al packages i need are back in the synocommunity repo.

Hope synology will release the toolchain for the 3617xs soon so the packages can be rebuild for that version as well.

**Comment by Safihre** [comment]
Updated test package-list with support for DS3617xs `broadwell` here: https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-357008518

**Comment by Safihre** [comment]
Packages for DS3617 are available more and more via the repo, testing packages can be found here #3138.
After final release packages will auto-update again via the official SynoCommunity repository.
