### ISSUE TITLE
Wallabag -- installed, but nothing happens

### ISSUE THREAD

**Issue by csgnyc** [SynoCommunity/spksrc#2875]
Saw Wallabag in Synocommunity and tried to install on synology.  By way of background, I'm no  expert in these things, but I have other web station programs up and running that use php and MariaDB -- for example, Tiny Tiny RSS. Installation of Wallabag appears successful (and I see the Wallabag folder in my web folder), but when I try the URL [mysynologyIP]/wallabag/web/, nothing seems to happen.   Anyone who has successfully installed Wallabag -- what other steps did you take?

**Comment by ymartin59** [comment]
What are your Synology hardware and DSM version ?

**Comment by csgnyc** [comment]
DS1515+ running DSM  6.1.3-15152 Update 3

**Comment by arakeis** [comment]
On DSM 5.2 no problem running it, any logs any where to narrow down the bug ?

**Comment by ymartin59** [comment]
wallabag package is new and has not been tested on DSM 6.1 yet

**Comment by ymartin59** [comment]
@tolkonepiu @arakeis May you please have a try to deploy on DSM 6.x ?

**Comment by ymartin59** [comment]
In fact it runs perfectly on my DSM 6.1. @csgnyc have you "web station" and "php" installed on your system ?

**Comment by csgnyc** [comment]
Yes. I'm running other apps with php (Tiny Tiny RSS, among others).

**Comment by ymartin59** [comment]
OK and MariaDB package is installed too, right ? If so, try uninstall and re-install... database configuration takes some time.

**Comment by arakeis** [comment]
@ymartin59 sorry not on DSM 6, I can only help with DSM 5.2

**Comment by tolkonepiu** [comment]
@csgnyc, you use nginx on webstation?

**Comment by csgnyc** [comment]
MariaDB is installed and while Nginx is installed on webstation, my http backend server is Apache 2.2.  Just tried reinstalling Wallabag and now I have a different problem -- I get this error message

Warning: simplexml_load_file(): I/O warning : failed to load external entity "/volume1/web/wallabag/vendor/friendsofsymfony/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml" in /volume1/web/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814 Warning: simplexml_load_file(): I/O warning : failed to load external entity "/volume1/web/wallabag/vendor/friendsofsymfony/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml" in /volume1/web/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814 Fatal error: Uncaught exception 'Doctrine\Common\Persistence\Mapping\MappingException' with message 'Invalid mapping file 'FOS.OAuthServerBundle.Entity.Client.orm.xml' for class 'FOS\OAuthServerBundle\Entity\Client'.' in /volume1/web/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86 Stack trace: #0 /volume1/web/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\Common\Persistence\Mapping\MappingException::invalidMappingFile('FOS\\OAuthServer...', 'FOS.OAuthServer...') #1 /volume1/web/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\Common\Persistence\Mapping\Driver\FileDriver->getElement('FOS\\OAuthServer...') #2 /volume1/web/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMetadataForClass('FOS\\OAuthServer...', Object(Doctrine\ORM\Mapping\ClassMetadata)) #3 /volume1/web/wallabag in /volume1/web/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php on line 86

**Comment by ymartin59** [comment]
I may be possible some files are corrupted. Did your "volume1" run out of disk space recently ?

**Comment by csgnyc** [comment]
No.  multiple terabytes available.

**Comment by Safihre** [comment]
Package needs updating, tracking in #3113.
