### ISSUE TITLE
[Package Request] SABnzbd update 2.2.0

### ISSUE THREAD

**Issue by richardlhughes** [SynoCommunity/spksrc#2876]
Name: SABnzbd 2.2.0
Description: This package is in need of updating the current version
Website: https://sabnzbd.org/downloads.html
Software documentation: https://sabnzbd.org/wiki/
Build/Installation documentation: https://sabnzbd.org/wiki/configuration/2.2/configure
Source Code: https://github.com/sabnzbd/sabnzbd
License: The SABnzbd software is covered by the GPL2 license or any later release (at your choice).
Original copyright by tdian@users.sourceforge.net (upto release 0.2.5)
All subsequent releases copyright by The SABnzbd-Team, consisting of the above listed members.
This Wiki Site is covered by "Creative Commons Attribution-ShareAlike 3.0 License" (see bottom of this page).
Copyright by The SABnzbd-Team

SABnzbd is free open source software, but the name, logos and icons are not.
The SABnzbd team is the copyright holder of these.
However, we do permit use of name and icons in a specific situation.
When you build an application that interfaces with SABnzbd through its API you can:

Mention the name SABnzbd in configuration pages of your application
Mention SABnzbd-compatibility in describing your application
Use our icon(s) or your own (accurate) rendering of our icon(s) in your application
You should state in your application's license section (typically connected to an About page), that name and icon(s) are copyrighted by the SABnzbd Team. This does not mean that the SABnzbd team endorses your application nor that we are obliged to keep our API compatible with your application.

**Comment by KaraokeStu** [comment]
Hi,

If you take a look at the latest merged pull requests, you'll see that 2.2.0 final was merged either the day or or the day after 2.2.0!

I've just got around to activating the new package which finished building yesterday afternoon :)
