### ISSUE TITLE
Provider t411.si don't work in Jackett

### ISSUE THREAD

**Issue by solspire** [SynoCommunity/spksrc#2881]
I change the wrong url in jackett in "site link" 
because isn't https://t411.al/ but now is https://t411.si/
I need jackett + mylar for have an automated ebook downloader and is it the only french comics provider !

Can you make T411 work ?

For now I have this for t411 (the others work fine):
"Configuration failed: Unexpected character encountered while parsing value: <. Path '', line 0, position 0." and this also "Configuration failed: Sequence contains no matching element"

Nas synology DS414 last update of DSM and package of synocomunity.

**Comment by ymartin59** [comment]
Related to #3070

**Comment by m4tt075** [comment]
@solspire Thanks to @kaso17 's fixes, `Jackett 0.8.490` has been merged into master. That means that the packages for `DSM 5.2` systems should be available via the SynoCommunity repo shortly (if they aren't already). For the time being, you can find `DSM 6.1` builds for `Jackett` on [this link here](https://github.com/m4tt075/spksrc/releases/tag/Jackett-0.8.490). Once installed, you can run further upgrades via the Jackett web-interface. These are beta packages. Therefore, please do report any kind of issues you should encounter.

**Comment by ymartin59** [comment]
Mono and Jackett updates published
