### ISSUE TITLE
Update duplicity (0.7.13.1 released)

### ISSUE THREAD

**Issue by EleRas** [SynoCommunity/spksrc#2882]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ duplicity
_Package Version:_ 0.7.11-5

_NAS Model:_ DS2413+
_NAS Architecture:_
_DSM version:_ 6.1.3

Please update duplicity, this should also fix the problems with GPG mentioned in the wiki

**Comment by ymartin59** [comment]
I will have a look at it

**Comment by vobujs** [comment]
hi, anyone (still) on it? b/c there's 0.7.14 out in the meantime. I'd also be able to help out w/ building/updating.
