### ISSUE TITLE
Syncthing Package Missing from repository

### ISSUE THREAD

**Issue by Vinblastine** [SynoCommunity/spksrc#2892]
### Setup
_Package Name:_ Syncthing
_Package Version:_ v0.14.23-12

_NAS Model:_ DS216play and DS214
_NAS Architecture:_ Monaco & Armada370
_DSM version:_ 6.1.3-15152 Update 3

### Expected behavior
Package should be available for install. 

### Actual behavior
Attempted to re-install syncthing package yesterday on DS216 play however after I uninstalled it and I went to re-install the package it has disappeared from the repo. 
I have attempted re-adding the syno community repo and restarting NAS. Have enabled beta releases and also any publishers in settings however is it not available for install.

**Comment by ymartin59** [comment]
Packages installed on DSM 5.2 remains in place after upgrade to DSM 6.
As repository does not support DSM 6 yet, native packages are not visible for fresh install on DSM 6.

Repository interface lacks a way to get direct download of a package binary... it may help in such situation so that manual installation may be possible

**Comment by GabrielaKprivate** [comment]
I have the same DSM version like Vinblastine (DSM 6.1.3-15152 Update 3) and the syncthing package installed just fine under that version (fresh installation). Now, I don't dare to make any updates to my Synology NAS, as syncthing is a crucial part of my backup procedure. Manual installation isn't an option for me. Please solve this problem as soon as you can, thanks.

**Comment by ndroftheline** [comment]
i noted that syncthing coudln't be found via the search function in either the latest DSM or an older version I run via xpenology. howeer it showed up under the "community" tab and installed just fine in the older DSM. won't start in DSM6, which i'mopening a separate issue for.

**Comment by ymartin59** [comment]
... as you want... we have already far enough issues there...

**Comment by ymartin59** [comment]
Package update has been published
