### ISSUE TITLE
FFmpeg - error while loading shared libraries

### ISSUE THREAD

**Issue by The-MAD-Virus** [SynoCommunity/spksrc#2895]
_For new Package Requests, see the guidelines_  

### Setup
Package Name: ffmpeg
Package Version: 3.3.3 and previews one

NAS Model: DS413
NAS Architecture: qoriq
DSM version: 6.1

I get this message when i try to use ffmpeg.

thanks in advance

```bach
root@DS413:/volume1/@appstore/ffmpeg/bin# /usr/local/ffmpeg/bin/ffmpeg -version
/usr/local/ffmpeg/bin/ffmpeg: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)
/usr/local/ffmpeg/bin/ffmpeg: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)
/usr/local/ffmpeg/bin/ffmpeg: error while loading shared libraries: /usr/local/ffmpeg/lib/libx265.so.87: R_PPC_REL24 relocation at 0x0dd2d648 for symbol `gettimeofday' out of range
```

**Comment by ymartin59** [comment]
Known issue. I suppose you built package from `master` with DSM 5.2 tool chain.

Here is qoriq build for DSM 6.1

[ffmpeg_qoriq-6.1_3.3.3-7.spk.zip](https://github.com/SynoCommunity/spksrc/files/1261610/ffmpeg_qoriq-6.1_3.3.3-7.spk.zip)

If it works well. Please close this issue. It will be published on repository when DSM 6.x support is deployed there.

**Comment by The-MAD-Virus** [comment]
Sorry my bad for the version error, but i still get the last error.

```bash
admin@DS413:~$ /usr/local/ffmpeg/bin/ffmpeg -version
/usr/local/ffmpeg/bin/ffmpeg: error while loading shared libraries: /usr/local/ffmpeg/lib/libx265.so.95: R_PPC_REL24 relocation at 0x0da786c4 for symbol `gettimeofday' out of range
```

**Comment by ymartin59** [comment]
OK looks like compilation `libx265.so` was not compiled with `-fPIC`. I will fix and generate another package

**Comment by ymartin59** [comment]
Here is another built for qoriq DSM 6.1. I hope it will goes further. Let me know.
[ffmpeg_qoriq-6.1_3.3.3-7.spk.zip](https://github.com/SynoCommunity/spksrc/files/1264791/ffmpeg_qoriq-6.1_3.3.3-7.spk.zip)

**Comment by The-MAD-Virus** [comment]
Perfect !!! all seems to work.

Thanks
