### ISSUE TITLE
Syncthing-inotify does not prevent scanning directories

### ISSUE THREAD

**Issue by aurelg** [SynoCommunity/spksrc#2901]
### Setup

_Package Name:_ syncthing-inotify
_Package Version:_ 0.8.5-2

_Package Name:_ syncthing
_Package Version:_ 0.14.36

_NAS Model:_ DS710+
_NAS Architecture:_ x86 (Intel Atom D410)
_DSM version:_ DSM 5.2-5967 Update 4

### Expected behavior

The installation of `syncthing-inotify` should considerably reduce the disk activity induced by `syncthing`.

### Actual behavior

The disk activity does not seems to be significantly reduced. 

### Steps to reproduce

_1._ Install `syncthing`
_2._ Install `syncthing-inotify`
_3._ Observe the disk activity

#### Package log

No logs, neither in the package center nor in `/usr/local/{package}/var/`. Perhaps related: I noticed that `syncthing` was started with the following command line : `/usr/local/syncthing/bin/syncthing -home=/usr/local/syncthing/var -reset-deltas`. According to the man page, the `-reset-deltas` flag forces a full index exchange. I'm not sure why it is set.

Just ask me how to investigate further, I'm very happy to help. And, BTW, thanks a lot!

Aurélien.

**Comment by ymartin59** [comment]
syncthing-inotify package is now deprecated and replaced by syncthing updated version which includes such support
