### ISSUE TITLE
Syncthing won't start

### ISSUE THREAD

**Issue by ndroftheline** [SynoCommunity/spksrc#2907]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_
syncthing
_Package Version:_
0.14.23-12 (latest)

_NAS Model:_
DS2015xs
_NAS Architecture:_
Alpine
_DSM version:_

DSM 6.0.2-8451

### Expected behavior
Tell us what should happen
After installing Syncthing, selecting Run from the dropdown on the Syncthing page under the Package Center should start Syncthing, so I can view the config page. 

### Actual behavior
Tell us what happens instead
"Loading" animation pops up briefly, then goes away. No change to service status. 

### Steps to reproduce
_1._
Install Syncthing from SynoCommunity repo
_2._
Try to run Syncthing
_3._
It doesn't run

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

Package log on the UI shows "No data"; /usr/local/syncthing/var has no logs only two config files, one of which is empty and the other of which is here: 

```
<configuration version="18">
    <gui enabled="true" tls="false">
        <address>0.0.0.0:7070</address>
    </gui>
    <options>
        <listenAddress>default</listenAddress>
        <globalAnnounceServer>default</globalAnnounceServer>
        <globalAnnounceEnabled>true</globalAnnounceEnabled>
        <localAnnounceEnabled>true</localAnnounceEnabled>
        <localAnnouncePort>21027</localAnnouncePort>
        <maxSendKbps>0</maxSendKbps>
        <maxRecvKbps>0</maxRecvKbps>
        <reconnectionIntervalS>60</reconnectionIntervalS>
        <relaysEnabled>true</relaysEnabled>
        <relayReconnectIntervalM>10</relayReconnectIntervalM>
        <startBrowser>false</startBrowser>
        <urAccepted>0</urAccepted>
        <urUniqueID></urUniqueID>
        <urURL>https://data.syncthing.net/newdata</urURL>
        <urPostInsecurely>false</urPostInsecurely>
        <urInitialDelayS>1800</urInitialDelayS>
        <restartOnWakeup>true</restartOnWakeup>
        <autoUpgradeIntervalH>12</autoUpgradeIntervalH>
        <upgradeToPreReleases>false</upgradeToPreReleases>
        <keepTemporariesH>24</keepTemporariesH>
        <cacheIgnoredFiles>true</cacheIgnoredFiles>
        <progressUpdateIntervalS>5</progressUpdateIntervalS>
        <symlinksEnabled>true</symlinksEnabled>
        <limitBandwidthInLan>false</limitBandwidthInLan>
        <minHomeDiskFreePct>1</minHomeDiskFreePct>
        <releasesURL>https://upgrades.syncthing.net/meta.json</releasesURL>
        <overwriteRemoteDeviceNamesOnConnect>false</overwriteRemoteDeviceNamesOnConnect>
        <tempIndexMinBlocks>10</tempIndexMinBlocks>
        <weakHashSelectionMethod>auto</weakHashSelectionMethod>
    </options>
</configuration>
```

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
root@NAS:/var/log# cat /var/log/messages | grep syncthing
2017-09-05T14:21:35+12:00 NAS synoscgi_SYNO.Core.Package.Installation_1_install[5328]: resource_api.cpp:163 Acquire service-cfg for syncthing when 0x0001 (done)
2017-09-05T14:25:18+12:00 NAS synoscgi_SYNO.Core.Package.Log_1_get[10849]: pkgtool.cpp:2622 Failed to query package status, syncthing
```

`
root@NAS:/var/log# cat /var/log/synopkg.log | grep syncthing
2017/09/05 14:50:49	start syncthing: begin to start version 0.14.23-12
2017/09/05 14:50:50	start syncthing: start version 0.14.23-12 successfully, result 0
`

Even after getting the "start...successfully" message, the UI is unavailable (launching from the Syncthing icon in the Synology menu) and the Status under the Syncthing entry in Package Center always shows Stopped. 

I had this running on an Xpenology install using DSM 5.2 a while ago, and it "just worked" - I've struggled a bit with an actual Synology in production though. All help appreciated. I wonder if something was misconfigured with the wrong IP address; the config file above shows the UI as 0.0.0.0:7070 which doesn't seem right. If you can get this working can you please share if that IP is the same on your config file? 

Thanks!

**Comment by ndroftheline** [comment]
FYI, tried to follow the instructions here to no avail. There was no syncthing user created automatically though. https://github.com/SynoCommunity/spksrc/issues/2176#issuecomment-217963227

**Comment by ymartin59** [comment]
Package published
