### ISSUE TITLE
Duplicity seems not installed correct

### ISSUE THREAD

**Issue by mnsgs** [SynoCommunity/spksrc#2908]
Hi,

I tried to install duplicity but it appears to have failed - I am not able to find the executable

### Setup
_Package Name:_ duplicity
_Package Version:_ 0.7.11.5

_NAS Model:_ Synology 211j
_NAS Architecture:_ ?
_DSM version:_ 6.1.3-15152 Update 4

### Expected behavior
Executable found (I would expect under "/volume1/@appstore"

### Actual behavior
symbolic link broken, or executable missing:

martin@DiskStation:/usr/local/duplicity/env/bin$ ls -la /usr/local/duplicity/
bin/   env/   lib/   share/
martin@DiskStation:/usr/local/duplicity/env/bin$ ls -la /usr/local/duplicity/bin/
total 1448
drwxr-xr-x 2 root root    4096 Feb 10  2017 .
drwxr-xr-x 6 root root    4096 Sep  8 21:26 ..
-rwxr-xr-x 1 root root 1211348 Feb 10  2017 bash
lrwxrwxrwx 1 root root       3 Feb 10  2017 captoinfo -> tic
-rwxr-xr-x 1 root root    4368 Feb 10  2017 clear
-rwxr-xr-x 1 root root   68388 Feb 10  2017 infocmp
lrwxrwxrwx 1 root root       3 Feb 10  2017 infotocap -> tic
-rwxr-xr-x 1 root root   24080 Feb 10  2017 rdiff
lrwxrwxrwx 1 root root       4 Feb 10  2017 reset -> tset
-rwxr-xr-x 1 root root   12380 Feb 10  2017 tabs
-rwxr-xr-x 1 root root   89548 Feb 10  2017 tic
-rwxr-xr-x 1 root root   13340 Feb 10  2017 toe
-rwxr-xr-x 1 root root   12416 Feb 10  2017 tput
-rwxr-xr-x 1 root root   20300 Feb 10  2017 tset
martin@DiskStation:/usr/local/duplicity/env/bin$

martin@DiskStation:/volume1/@appstore$ find . -type f -name duplicity
martin@DiskStation:/volume1/@appstore$

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
"/var/log/synopkg.log"
2017/09/08 21:17:18 uninstall duplicity: begin to stop version 0.7.11-5
2017/09/08 21:17:27 uninstall duplicity 0.7.11-5 Begin start-stop-status stop
2017/09/08 21:17:27 uninstall duplicity 0.7.11-5 End start-stop-status stop ret=[0]
2017/09/08 21:17:29 uninstall duplicity: stop version 0.7.11-5 successfully, result 0
2017/09/08 21:17:29 uninstall duplicity 0.7.11-5 Begin preuninst
2017/09/08 21:17:30 uninstall duplicity 0.7.11-5 End preuninst ret=[0]
2017/09/08 21:17:30 uninstall duplicity 0.7.11-5 Begin /bin/rm -rf /volume1/@appstore/duplicity
2017/09/08 21:17:34 uninstall duplicity 0.7.11-5 End /bin/rm -rf /volume1/@appstore/duplicity ret=[0]
2017/09/08 21:17:36 uninstall duplicity 0.7.11-5 Begin postuninst
2017/09/08 21:17:38 uninstall duplicity 0.7.11-5 End postuninst ret=[0]
2017/09/08 21:17:38 uninstall duplicity: Uninstall 0.7.11-5 successfully
2017/09/08 21:25:24 install duplicity 0.7.11-5 Begin preinst
2017/09/08 21:25:30 install duplicity 0.7.11-5 End preinst ret=[0]
2017/09/08 21:25:30 install duplicity 0.7.11-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/duplicity
2017/09/08 21:25:33 install duplicity 0.7.11-5 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/duplicity ret=[0]
2017/09/08 21:25:33 install duplicity 0.7.11-5 Begin /bin/rm -rf /var/packages/duplicity
2017/09/08 21:25:33 install duplicity 0.7.11-5 End /bin/rm -rf /var/packages/duplicity ret=[0]
2017/09/08 21:25:36 install duplicity 0.7.11-5 Begin /bin/mkdir -p /var/packages/duplicity
2017/09/08 21:25:38 install duplicity 0.7.11-5 End /bin/mkdir -p /var/packages/duplicity ret=[0]
2017/09/08 21:25:38 install duplicity 0.7.11-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/duplicity/INFO
2017/09/08 21:25:38 install duplicity 0.7.11-5 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/duplicity/INFO ret=[0]
2017/09/08 21:25:38 install duplicity 0.7.11-5 Begin /bin/rm -rf /var/packages/duplicity/scripts
2017/09/08 21:25:38 install duplicity 0.7.11-5 End /bin/rm -rf /var/packages/duplicity/scripts ret=[0]
2017/09/08 21:25:38 install duplicity 0.7.11-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/duplicity/scripts
2017/09/08 21:25:39 install duplicity 0.7.11-5 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/duplicity/scripts ret=[0]
2017/09/08 21:25:39 install duplicity 0.7.11-5 Begin /bin/rm -rf /var/packages/duplicity/conf
2017/09/08 21:25:39 install duplicity 0.7.11-5 End /bin/rm -rf /var/packages/duplicity/conf ret=[0]
2017/09/08 21:25:39 install duplicity 0.7.11-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/duplicity/conf
2017/09/08 21:25:41 install duplicity 0.7.11-5 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/duplicity/conf ret=[0]
2017/09/08 21:25:47 install duplicity 0.7.11-5 Begin postinst
2017/09/08 21:52:46 install duplicity 0.7.11-5 End postinst ret=[0]
2017/09/08 21:53:04 install duplicity: begin to start version 0.7.11-5
2017/09/08 21:53:05 install duplicity 0.7.11-5 Begin start-stop-status start
2017/09/08 21:53:05 install duplicity 0.7.11-5 End start-stop-status start ret=[0]
2017/09/08 21:53:05 install duplicity: start version 0.7.11-5 successfully, result 0
2017/09/08 21:53:05 install duplicity 0.7.11-5 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2017/09/08 21:53:05 install duplicity 0.7.11-5 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2017/09/08 21:53:05 install duplicity 0.7.11-5 successfully

Thanks,
Martin

**Comment by DavBE** [comment]
Hello,

Same here, DS411j running DSM 6.1-15047 Update 1

```root@DiskStation:~# cd /usr/local/bin
root@DiskStation:/usr/local/bin# ll duplicity
lrwxrwxrwx 1 root root 38 Nov 24 14:03 duplicity -> /usr/local/duplicity/env/bin/duplicity
root@DiskStation:/usr/local/bin# ll /usr/local/duplicity/env/bin/duplicity
ls: cannot access /usr/local/duplicity/env/bin/duplicity: No such file or directory
root@DiskStation:/usr/local/bin#
```

Any help ? 

Regards,

David
