### ISSUE TITLE
lot of apps not in App Store on DS3617xs

### ISSUE THREAD

**Issue by stefsegers** [SynoCommunity/spksrc#2909]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ added packetsources http://packages.synocommunity.com

_NAS Model:_DS3617xs
_NAS Architecture:_simple 1 volume, raid5, btrfs, 2x ssd cache
_DSM version:_6.1

### Expected behavior
added the packet source and gone to community. From here I only have 27 apps. 
Something simple as python 2.7.3-3, Sonarr, Radarr,  nzbget, autosub all not available 

### Actual behavior
I can install python 3.15 and not an easier version (which seems to be neccecary for some apps)

### Steps to reproduce
_1._add pcketsource
_2._tick the BETA enable function
_3._accept every publisher
_4._go to community and see just 27 apps (on my 1512+ I have a lot more!)

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
No idea how to get this with FileStation?

Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
``` same for other logs

Insert log here
```
I am a simple rookie and know how DSM works but no idea how to get logs etc. sorry :(
![schermafbeelding 2017-09-10 om 16 44 12](https://user-images.githubusercontent.com/31842392/30263007-9ad6e30c-96d3-11e7-8233-ba8ca0cbb0eb.png)

**Comment by ymartin59** [comment]
Know issue. This arch is lacking because of pending DSM 6 support in repository.

**Comment by stefsegers** [comment]
Thanks Martin for your quick reply!
The strange thing is that I use DSM 6 on both machines.... Is it something to do with the 3617 compared to the older 1512?
Is there something I can do about it?

**Comment by cytec** [comment]
@stefsegers the 3617 is a different arch (broadwell) then the 1512 (cedarview) and the repo doesn't have broadwell support till DSM 6 support is added.

**Comment by henrikwallinder** [comment]
I've a DiskStation DS3617xs as well and would love to install DarkStat, which I used on my previous NAS.

Would be awsome if you could add support for broadwell on more packages.

**Comment by stefsegers** [comment]
I am not a progrmmer, just a creative noob... but does the software has to be programmed differently for each processor?
Is there any outlook when Broadwell will be supported? Love to shut down the old NAS, it is getting really slow :(

**Comment by ymartin59** [comment]
Hello. To answer no, not "programmed differently" but compile/built specifically for each platform, so there are specific packages for broadwell in repository. I now have a procedure to publish broadwell packages (there was a mistake when adding to SynoCommunity support)... but (there is always one) I have to build and publish them for broadwell.

If you select most important packages for you, I may provide them - but (there is another one) these will be prepared for DSM 5.2 and may not be compatible with DSM 6.x - I will warn you if I am already aware they are not compatible

**Comment by stefsegers** [comment]
Thanks Martin for your quick reply. Wow this is pretty intense programming :(
Thankfully I am a photographer and know how to work with an camera hihi

So the software I use now on the 1512+:
- autosub (for subtitles)
- nzbget
- sonarr
- radarr
- subliminal
- Transmission

I think Mono, Python 2.7 is needed for these to make it work?

**Comment by henrikwallinder** [comment]
Thanks Martin!

If it is possible to compile/build Darkstat, that would be great. :)

**Comment by RheinNerd** [comment]
Another DS3617XS here, would love to see ffmpeg in the list.
Thank you!

**Comment by XDomanX** [comment]
Please add **Syncthing** to the priority list :) Appreciate.

**Comment by lennvilardi** [comment]
I'm interested in Transmission, thanks in adavance :)

**Comment by sojab0on** [comment]
intrested as wel in ffmpg,sabnzbd and sickbeard 
DS3617XS here.

**Comment by stefsegers** [comment]
Hi yMartin59,

Love to hear what the status is of all the apps?

**Comment by spacekiek** [comment]
Hi

Me too! Can't wait to retire the old NAS ... 

Or should we go the Docker route ? No experience with that, but it seems more future proof?

**Comment by roysbike** [comment]
i need ffmpeg for  broadwell DS3617xs

**Comment by kuryak1n** [comment]
Another vote for DarkStat.  This time for the DS918+ / Celeron J3455.

**Comment by roysbike** [comment]
I make ffmpeg for broadwell 6.1 DS3617

**Comment by Safihre** [comment]
Packages for DS3617 are available more and more via the repo, testing packages can be found here #3138.
After final release packages will auto-update again via the official SynoCommunity repository.
