### ISSUE TITLE
ZNC - crypto libraries are too old to connect to Freenode via SSL/TLS

### ISSUE THREAD

**Issue by luckman212** [SynoCommunity/spksrc#2911]
I'm writing about the ZNC package (https://synocommunity.com/package/znc). I've been using it for years and it's one of my favorites. 

Recently, I encountered a major issue w/ the latest ver 1.6.0-11 on my system: I was no longer able to connect to Freenode via SSL. After MUCH trial and error I figured out that it was the crypto libraries which were too outdated to support the LetsEncrypt certs they are now using.

When I manually replaced:
`/usr/local/znc/lib/libssl.so.1.0.0` and
`/usr/local/znc/lib/libcrypto.so.1.0.0`
with the "system" ones from `/usr/lib/` - it started working again. This was quite tedious to figure out. I assume it's something that's been solved in more recent versions.

Would it be possible to get this package updated? Who is maintaining it? The latest version at this time is 1.6.5 (https://wiki.znc.in/ChangeLog/1.6.5)

Thanks!!

**Comment by jelmerj** [comment]
I'm playing with the developer environment to see if I can be of any help to the community. The issue reported by @luckman212 is not directly an issue with ZNC but openssl. While an upgrade of ZNC would be nice, I believe that a rebuild of the current package would be enough to have it use the latest openssl included with the synocommunity sources, am I correct? I'm guessing the currently uploaded package has been build and uploaded before the latest openssl but I'm unsure how to check for that other than comparing commit dates of the znc and openssl folders.

**Comment by ymartin59** [comment]
Current openssl version "ported" is 1.0.2l... Question to answer: is that version recent enough to fix issue. If yes, then a package rebuilt with ZNC update will use that newer version and everything should be OK.
If version 1.1.x is required, it will be another story I have already tried upgrade and port latest few weeks ago and patches are required for cross-compilation to ARM or PPC.

**Comment by ymartin59** [comment]
@luckman212 What is your system architecture (model and DSM version) ? I may built an update just for you to test and confirm fix.

**Comment by luckman212** [comment]
Happy to test! I’ve got a DS712 (x86) and a DS1515 (avoton). Currently ZNC running on the DS712.

**Comment by ymartin59** [comment]
@luckman212 Which DSM versions please...

**Comment by luckman212** [comment]
Sorry. Latest- 6.1.3-15152 update 5

**Comment by ymartin59** [comment]
Hello. I have rebuilt current version 1.6.0 for DSM 6.1 and x86... it is built against openssl 1.0.2l: http://dl.free.fr/rKdt08DpT
In not successful, you will have to wait for a "real" update.

**Comment by luckman212** [comment]
Thanks - I’ll give it a try today & report back!

**Comment by luckman212** [comment]
@ymartin59 Sorry but that did not work for me. Once I manually installed your version, I could again no longer connect to Freenode via SSL. I had to again copy the `libssl.so.1.0.0` and `libcrypto.so.1.0.0` libraries from /usr/lib/ and restart ZNC to get it going.

**Comment by meiser79** [comment]
It's not that the libraries are too old, they just don't find the CA certificates under /etc/ssl.

```
diff --git a/spk/znc/Makefile b/spk/znc/Makefile
index 44507f8..311bbff 100644
--- a/spk/znc/Makefile
+++ b/spk/znc/Makefile
@@ -42,3 +42,4 @@ znc_extra_install:
        install -m 644 src/znc.conf $(STAGING_DIR)/var/configs/znc.conf
        install -m 755 -d $(STAGING_DIR)/app
        install -m 644 src/app/config $(STAGING_DIR)/app/config
+       ln -sf /etc/ssl/certs $(STAGING_DIR)/certs
```

**Comment by Safihre** [comment]
Further DSM6 compatibility and updates will be part of #2977.

**Comment by luckman212** [comment]
Still having this issue with the new [v1.7.1](https://github.com/SynoCommunity/spksrc/pull/3466), fyi...

**Comment by m4tt075** [comment]
@luckman212 Did you try @meiser79 's fix above by any chance?

**Comment by luckman212** [comment]
Not sure what to do with that. Do I need to copy the LetsEncrypt root cert to `/etc/ssl/certs`? 

in the [Makefile](https://github.com/m4tt075/spksrc/blob/master/spk/znc/Makefile#L44) I don't see the above referenced line: `ln -sf /etc/ssl/certs $(STAGING_DIR)/certs`. I also have no idea where the `$STAGING_DIR` variable is being set.

I don't see a `certs` directory at all in my znc appdir at `/var/packages/znc/target`. Should I manually create that symlink? `ln -sf /etc/ssl/certs /var/packages/znc/target/certs`?

Confused, sorry.

**Comment by m4tt075** [comment]
Don't worry. Ignore this and look at my message for you in #2977. We will continue there...
