### ISSUE TITLE
tvheadend: got old version 3.4.27-6

### ISSUE THREAD

**Issue by mg-ds213j** [SynoCommunity/spksrc#2917]
### Setup
_Package Name:_tvheadend
_Package Version:_3.4.27-6

_NAS Model:_DS213j
_NAS Architecture:_Marvell Armada 370 
_DSM version:_DSM 6.1.3-15152 Update 3

### Expected behavior
I installed tvheadend using the description from https://synocommunity.com/#easy-install.
I found installed the version 3.4.27-6.
Expected Version v4.2.3-10 like described on Page https://synocommunity.com/packages 

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
Log doesn't exists:
root@DS1:/usr/local/tvheadend/var# ls -al
total 20
drwxr-sr-x 3 tvheadend root 4096 Sep 19 18:19 .
drwxr-xr-x 7 tvheadend root 4096 Sep 19 18:07 ..
drwxr-xr-x 2 tvheadend root 4096 Sep 19 18:13 accesscontrol
-rwx------ 1 tvheadend root   43 Sep 19 18:19 config
-rw-r--r-- 1 root      root    5 Sep 19 18:08 tvheadend.pid

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by m4tt075** [comment]
It's a beta package. You might have to enable beta packages in your package manager to see it.

**Comment by ymartin59** [comment]
Lack of log is explained because packages available in repository (either old or last one) are built for DSM <= 5.2 - there is still no support for DSM 6.x - as tvheadend depends on native tool, none of these is expected to work on your system.

I have just built for your arch and DSM 6.1: http://dl.free.fr/vNnAbfyOk

**Comment by mg-ds213j** [comment]
@m4tt075:
It works, new version found and installed. Afterwards tvheadned found my SAT>IP device.
Thanks!

**Comment by mg-ds213j** [comment]
@ymartin59
I installed version from repository and it works. What is the advantage of your built?
Only the logfile or any more?

**Comment by ymartin59** [comment]
@m4tt075 @mg-ds213j tvheadend depends on ffmpeg libraries which have C++ code. libstdc++ version has changed between DSM 5.x and DSM 6.x. You can check that ffmpeg and chromaprint packages built for DSM 5.2 from online repository have some troubles (ffmpeg --version complains about libstdc++). So from my point of view, even if tvheadend "seems" to work, it may fail to process some operations when ffmpeg libraries are invoked. I would recommend you to use the package I built for DSM 6.1.

**Comment by m4tt075** [comment]
@mg-ds213j : @ymartin59 is right. I overlooked that you are on DSM 6+. Just install his build over the one from the repo you have got now and you are safe. Backup before you do this, just in case, but I would not expect problems as all the configuration files are identical.

**Comment by mg-ds213j** [comment]
@ymartin59 : Install of your package failed. 

I did the following steps:
1. Deinstall the version from m4tt075
2. Start "manual installation" of your package (downloaded to local disk)
3. DSM shows warning "no digital signature"
4. asks for Basic configuration (i leaved user and password empty)
5. DSM shows summary (package name Tvheadend and version ...)
6. start installation, need ca. 14 seconds and ends in error message "Nicht verfügbar" (not available)
Thats all


/var/log/synopkg.log

2017/09/21 17:56:36     stop tvheadend: begin to stop version 4.2.3-10
2017/09/21 17:56:37     stop tvheadend 4.2.3-10 Begin start-stop-status stop
Stopping Tvheadend ...
2017/09/21 17:56:39     stop tvheadend 4.2.3-10 End start-stop-status stop ret=[0]
2017/09/21 17:56:40     stop tvheadend 4.2.3-10 Begin unload apparmor
2017/09/21 17:56:40     stop tvheadend 4.2.3-10 End unload apparmor ret=[0]
2017/09/21 17:56:40     stop tvheadend: stop version 4.2.3-10 successfully, result 0
2017/09/21 18:02:13     uninstall tvheadend 4.2.3-10 Begin preuninst
deluser: can't find sc-tvheadend in /etc/group
2017/09/21 18:02:14     uninstall tvheadend 4.2.3-10 End preuninst ret=[0]
2017/09/21 18:02:14     uninstall tvheadend 4.2.3-10 Begin /bin/rm -rf /volume1/@appstore/tvheadend
2017/09/21 18:02:16     uninstall tvheadend 4.2.3-10 End /bin/rm -rf /volume1/@appstore/tvheadend ret=[0]
2017/09/21 18:02:16     uninstall tvheadend 4.2.3-10 Begin postuninst
2017/09/21 18:02:16     uninstall tvheadend 4.2.3-10 End postuninst ret=[0]
2017/09/21 18:02:16     uninstall tvheadend: Uninstall 4.2.3-10 successfully
2017/09/21 18:14:42     install tvheadend 4.2.3-10 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2017/09/21 18:14:45     install tvheadend 4.2.3-10 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2017/09/21 18:14:45     install tvheadend 4.2.3-10 failed
2017/09/21 18:15:16     install tvheadend 4.2.3-10 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2017/09/21 18:15:18     install tvheadend 4.2.3-10 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2017/09/21 18:15:18     install tvheadend 4.2.3-10 failed
2017/09/21 18:15:41     install tvheadend 4.2.3-10 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2017/09/21 18:15:43     install tvheadend 4.2.3-10 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2017/09/21 18:15:43     install tvheadend 4.2.3-10 failed

**Comment by m4tt075** [comment]
@mg-ds213j : This looks strange. Could you please try the package from here:
https://www.dropbox.com/sh/jr7732yrwcxa2gr/AADJ3k-2_cGShPrX39OEbnXka/Tvheadend%20Release%20(4.2.x)/DSM%206.1?dl=0
Do you run into the same issues or does it work then?

**Comment by mg-ds213j** [comment]
@m4tt075 : This one works. I can install and log-in through the web-interface. More i can't test now, because i sent back my telestar digitbit sat>ip and ordered a new sundtek skytv utlimate usb to plug directly on my NAS. 

After the stick arrives i will give more informationen...

**Comment by m4tt075** [comment]
@mg-ds213j : Thanks for your feedback. 
@ymartin59 : The packages I linked were built from the same source here, cross-compiled within a VM Ubuntu environment. No idea what went wrong with your build...

**Comment by ymartin59** [comment]
@m4tt075 I built it in Docker from current `dsm6` branch

**Comment by m4tt075** [comment]
@ymartin59 : But that should not make a difference, should it?

**Comment by mg-ds213j** [comment]
It takes more time to receive new tuner (SundTek SkyTV 6) than i thought, and afterwards i got problems with some channel. So i tried first to findout whether stick is ok or not tohether with the supplier. But right now everthing is going fine for me. TVHeadend ist working fine on my NAS. 

Thank you for your help!
