### ISSUE TITLE
FlexGet

### ISSUE THREAD

**Issue by Jeltel** [SynoCommunity/spksrc#292]
Flexget is a package to automatically download torrent files and put them in the watch folder of (for example) Transmission. It can download torrents via a rss feed. http://flexget.com/

There is a installation guide for Synology, although it uses ipkg.

I request a package for the Synology NAS (in particulair the DS411, because that's the one I'm using).

I have no other linux installation besides the NAS (and Openelec) and have very little idea how I would be able to compile the package. That being said, I would like to participate where I can.

Thx

**Comment by bonebox** [comment]
Not sure this is the same issue that others were having, but I just installed FlexGet v1.2.415 on my DS414 from a package that I successfully built using spksrc and got a lot of errors when attempting to run it (mainly for missing modules).  I was able to resolve it by manually running `/usr/local/flexget/env/bin/pip install flexget --upgrade`.

**Comment by Slim1234slim** [comment]
I managed to install it on my ds916+ and upgraded it as well (2.10.76).
How can I run the WebUI?

**Comment by cytec** [comment]
@Slim1234slim have you checked flexget docu? https://flexget.com/Web-UI

**Also from there:**
> Web UI is currently experimental and is not recommended for new users!
