### ISSUE TITLE
DS918+ "Invalid location."?

### ISSUE THREAD

**Issue by masterpae** [SynoCommunity/spksrc#2921]
_NAS Model:DS918+
_NAS Architecture:_
_DSM version:6.1

### Expected behavior
Being able to add the SynoCommunity package source to DSM.

### Actual behavior
When trying to add http://packages.synocommunity.com/ package source in Package Center i always get the "Invalid location." error.

I have followed the FAQ and everything should be fine.
Was there a downtime of the site lately?
Is adding the package source affected by the fact this is a new product?

**Comment by benjamin1081** [comment]
Same issue here with my new DS918+

**Comment by lennvilardi** [comment]
I was looking to buy a new DS918+ but without apps is useless :(
Any ETA ?

**Comment by masterpae** [comment]
There is always the option to install everything you need with Docker.
Not sure if all synocommunity apps are available as docker images but the vast majority for sure are there.
Some are arguing that deploying apps with with Docker is the superior option...

**Comment by jochemdu** [comment]
I have the same problem. Migrated my old disks from DS414 to new DS918+. Some packages where not available (greyed out in installed applications list) and could not start. Re-adding repository give the error: invalid location.

Probably the model isnt added to supported models yet..

**Comment by bvh1977** [comment]
If the architecture_name is needed I have found a thread at forums.plex.tv that discussed this problem.

User 'jsemroc' said the following in this topic [(https://forums.plex.tv/discussion/288118/new-synology-compatibility-ds418-ds418play-ds918)](url)

> I downloaded DSM 6.1.3 .pat file for the DS918+ and used 7-zip to extract the VERSION file which contained the line:
unique="synology_apollolake_918+"
I checked this against the DSM 6.1.3 download for the 1815+ whose VERSION file shows:
unique="synology_avoton_1815+"
So it appears that Synology's codename for the 918+ is apollolake
> 
Maybe this helps?

Docker works fine by the way. Thanks for the suggestion @masterpae.

**Comment by benjamin1081** [comment]
I have moved my applications to Docker. Works very well.

**Comment by ymartin59** [comment]
Your model is even not yet listed in Synology page: https://www.synology.com/en-us/knowledgebase/DSM/tutorial/General/What_kind_of_CPU_does_my_NAS_have
But it is referred https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model
I am waiting for SourceForge to recover to know if "appollolake" toolchains are already available or not.

**Comment by ymartin59** [comment]
I have just declared "apollolake" architecture into repository. SynoCommunity repository registration should work now

**Comment by IBNobody** [comment]
Thank you @ymartin59 . It works now.
