### ISSUE TITLE
Nzbget not working on DS216play

### ISSUE THREAD

**Issue by Erci76** [SynoCommunity/spksrc#2922]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Nzbget
_Package Version:_16.4-22

_NAS Model:_ DS216 Play  
_NAS Architecture:_
_DSM version:_DSM 6.1.3-15152 Update 4

### Expected behavior
I'm using nzbget package for a while on my nas (ds216play). Till yesterday it worked without a problem. Today it's not working 

### Actual behavior
Package stopped and restart via Packagecenter. It's still not working.

### Steps to reproduce
_1._ Same settings (nzbserver) set in download station, it's working 
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
Have you applied DSM upgrade between yesterday and package service failure ?

**Comment by Safihre** [comment]
Test package for new-style NZBGet has been released: #3138.
We no longer compile it here on the repo, but fetch the latest official installer from NZBGet.
During package installation you can choose if you want the latest stable or testing release. After this you can use NZBGet's internal update system to do updates. It also includes updates to user-management.
We hope to soon publish this on the official repo.
