### ISSUE TITLE
Sabnzbd - URL wrong how to update

### ISSUE THREAD

**Issue by voyager168** [SynoCommunity/spksrc#2925]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Sabnzbd
_Package Version:_2.2.1-31

_NAS Model:_ DS-416
_NAS Architecture:_
_DSM 
 I am using SABNZBD and i noticed that the URL lists the port as 8080. I need this to be 8086 is there a way to update this

**Comment by ymartin59** [comment]
Port allocation is done to avoid conflicts between packages and Synology DSM standard ports: https://github.com/SynoCommunity/spksrc/wiki/SynoCommunity-Used-Ports

To change port number, you have to clone project, edit port at location https://github.com/SynoCommunity/spksrc/blob/master/spk/sabnzbd/Makefile#L16 and build your own package for your target architecture.

@Safihre any opinion about this request ?

**Comment by Safihre** [comment]
@voyager168 What happens if you just change the port in the SABnzbd config? Or the package is really allowed to only use port 8080?

**Comment by ignoremenow** [comment]
@Safihre looks like it's hardcoded in with that makefile. Tried jumping to another port on my install and it reset it back to 8080.

**Comment by Safihre** [comment]
What if you enable HTTPS? Can you set a different port for that one? (click Advanced)
I can't see anywhere in the code that would force it back to 8080.

**Comment by ignoremenow** [comment]
I haven't messed with it but there is a file on the box called sabnzbd.sc which has

[sabnzbd]
title="SABnzbd"
desc="SABnzbd"
port_forward="yes"
dst.ports="8080/tcp"

There is also the INFO file which may or may not have any change over it. Which lists the port but that might just be cosmetic in the package page.

So maybe if you shutdown sab. Update the sab config to the port u want. update the sabnzbd.sc file, and the INFO file. That might work.

**Comment by Safihre** [comment]
@ignoremenow could you try that? I would be interested to see what happens, if it sticks if you set it in the ini.

**Comment by ignoremenow** [comment]
So I stopped the service 

Then I edited all these files to 8081

vim /var/packages/sabnzbd/INFO
vim /volumename/@appstore/sabnzbd/var/config.ini
vim /usr/local/etc/services.d/sabnzbd.sc
vim /var/packages/sabnzbd/scripts/sabnzbd.sc

In the package center it even lists 8081 and the site pulls up properly.

@voyager168 the downside to this that any upgrade to sab is probabyl going to require you to make all these changes again. Or fork the project and make your own package.

**Comment by ignoremenow** [comment]
Or perhaps setup a reverse proxy like apache 2.4. I see that in the repos.

**Comment by ignoremenow** [comment]
or if you use the firewall functionality it might let you do a port forward, dunno looks like possibly various ways of doing this without updating the file, but I don't think this fall's under a bug/request for sab.

**Comment by Safihre** [comment]
Unfortunately nothing we can do really. These are the ports we always use.
In case it needs changes, follow the suggestions: https://github.com/SynoCommunity/spksrc/issues/2925#issuecomment-331993495.
