### ISSUE TITLE
DS 218+ Invalid Location

### ISSUE THREAD

**Issue by frostjay** [SynoCommunity/spksrc#2930]
Just received a DS218+ to replace my dead DS215+.  Trying to add the SynoCommunity via package center using http://packages.synocommunity.com/ as the address and it comes back as invalid.  

I updated the DNS server to google (8.8.8.8) and still failing.  Any ideas?

**Comment by ymartin59** [comment]
May you please test again. Probably you will see only few "non arch" packages by the way.

**Comment by frostjay** [comment]
Seems to be working now.  Thanks. 

J

⁣Sent from BlueMail ​

**Comment by frostjay** [comment]
So none of the packages I use…Couchpotato, Sick Rage or SABNZB work.  They all deliver the error that git,python are missing from the package server.  

I installed them directly thru synology package center but still receive the error.

Any advice?

J

**Comment by ymartin59** [comment]
Packages have to re-built specifically for your architecture "apollolake" and DSM 6. As online repository does not support publishing for DSM 6 version yet, you should have to built them on your own - as soon as I have added "apollolake" toolchain into `dsm6` branch - as soon as sourceforge gets full up and running...
