### ISSUE TITLE
Is Deluge with forgetting configuration already resolved on DSM 6.x?

### ISSUE THREAD

**Issue by Vilscon** [SynoCommunity/spksrc#2931]
Hey guys,

For as long as DSM 6.0 exists, all third party packages have problems, as pretty known worldwide. As Deluge is the only one those and, sadly, the only one that supports proxies. 

For at least my situation, Deluge always forgets it's configuration after every reboot, even when used with Docker. Months have passed since my last investigation around any solution, but [this comment](https://github.com/SynoCommunity/spksrc/issues/2904#issuecomment-327292086) suggests it is resolved.

So simply in short: Is there already a solution for Deluge forgetting it's configuration files after every reboot?

- - - 

DS216+
DSM 6.1.2-15132, ready for update to DSM 6.1.3-15152

**Comment by mattgphoto** [comment]
I was starting to wonder why my email notifications weren't working! Good to know it's some sort of bug. :-/

**Comment by Safihre** [comment]
In case any of you are still interested, 
New-style Deluge test-package available in #3138.
In case of problems, please post:
`/volume1/@appstore/deluge/var/delug.log` and
`/volume1/@appstore/deluge/var/delug_install.log`

**Comment by ymartin59** [comment]
Deluge update has been published
