### ISSUE TITLE
[Deluge] Label Assignation and Move/Delete based on ratio...

### ISSUE THREAD

**Issue by ExorDG** [SynoCommunity/spksrc#2938]
**### Setup**
**_Package Name:_** Deluge (Beta)
**_Package Version:_** 1.3.15-8

**_NAS Model:_** DS916+
**_NAS Architecture:_** Intel Pentium N3710, Quad Core, 1.6GHz, 2GB RAM
**_DSM version:_** 6.1.3-15152 Update 5

**### Expected behavior**
Labels will assign specific torrents and they should move to specific paths I set them to and one of label should remove torrents from list automatically at 0 ratio after complete. (Currently have only two labels).

**### Actual behavior**
What happen is that torrents do get assigned to label like they are suppose to but the problem that they did not stop seeding at 0 ratio and move to specific path I set them to and then delete it from the torrent list. For example:
- Download to /volume1/downloads
- Stop Complete from seeding at 0 ratio
- Move Complete to /volume1/video/movies
- Delete the moved complete movie from torrent list (not data)

I have two labels. Both of them are set to move to different location. One label will stay seeding and other label will remove after moved.

**### Steps to reproduce**
**_1._** Restart DiskStation
**_2._** Open Deluge WebUI
**_3._** Find a movie to download
**_4._** It is downloaded
**_5._** It will not stop seeding at 0 ratio, move to specific path and then remove from torrent list

**#### Package log**

```
There is no error in the package log for Deluge. I don't know how to paste it in here since it is limited in SSH. I can't access to log in FTP as I cannot find the var folder in there. It would only show my personal folder in the "shared folder".
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
No error related to Deluge as well.
```

I just want to head up that this same settings on RPI works perfectly but on Synology NAS does not work at all. My setup requires this for automation. I would switch to Transmission but it does not have label feature.

**Comment by ExorDG** [comment]
2 weeks and no comment?

**Comment by ymartin59** [comment]
Deluge application is only package and distributed for Synology DSM. Your request looks like a bug to report upstream... except if version update is expected to fix it.

**Comment by ExorDG** [comment]
Thank you for reply. I will be watching this issue to see if there is any fix to it.

**Comment by ExorDG** [comment]
Still watching this issue.

**Comment by ExorDG** [comment]
I tested by putting the path that I wanted them to move into automatically in the "Move Storage" to "/volume1/video/movies" it will work but label will not move it automatically with the same path.

**Comment by Safihre** [comment]
This issue is Deluge specific, not specific to the package. You should ask Deluge, not us 👍
