### ISSUE TITLE
sonarr/nzbdrone hangs  is unresponsive

### ISSUE THREAD

**Issue by marcodings** [SynoCommunity/spksrc#2946]
### Setup
_Package Name:_ sonarr / nzbdrone
_Package Version:_ 2.0.0.4949 Mono Version:  4.6.2
_NAS Model:_ds1513
_NAS Architecture:_ cedarview (x86_64)
_DSM version:_  DSM 6.1.3-15152 Update 5

### Expected behavior
Expect sonarr to keep running and be accessible via the web interface.

### Actual behavior
Every few days sonarr fails to respond via the web interface. It also fails a performing any of  the background tasks in fetching nzb files etc.

Note1: that the process is still running, its just not responding
Note2:  I run sonarr "behind" the DSM reverse proxy

I tried to mitigate the impact by trying to autamically restart sonarr ( see https://github.com/SynoCommunity/spksrc/issues/2916 ) this has been unsuccessful.

I can only stop / start using the diskstation gui in the package center :(

### Steps to reproduce
_1._ ? Run and wait
_2._ gateway timeout
_3._ no series nzb are fetched or downloaded

#### Package log
bash-3.2# cat /usr/local/nzbdrone/var/install.log
|| Installing package version="20170106-9" - Thu Aug 24 13:39:34 CEST 2017 ||
|| Package Install Completed - Thu Aug 24 13:39:37 CEST 2017 ||

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
nothing in the log
see also https://github.com/SynoCommunity/spksrc/issues/2916

bash-3.2# tail /var/log/upstart/pkgctl-nzbdrone.log
2017-09-26T13:40:40+0200 ======== stop nzbdrone ========
2017-09-26T13:43:23+0200 ======== start nzbdrone ========
2017-09-26T23:37:35+0200 ======== stop nzbdrone ========
2017-09-26T23:37:36+0200 ======== start nzbdrone ========
2017-09-29T09:27:01+0200 ======== stop nzbdrone ========
2017-09-29T09:27:11+0200 ======== start nzbdrone ========
2017-10-02T00:32:46+0200 ======== stop nzbdrone ========
2017-10-02T00:32:58+0200 ======== start nzbdrone ========
2017-10-05T15:59:01+0200 ======== stop nzbdrone ========
2017-10-05T15:59:29+0200 ======== start nzbdrone ========

bash-3.2# tail /var/log/nginx/error.log
2017/10/03 19:02:20 [error] 18670#18670: *1145718 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.43.100, server: sonarr.nas, request: "GET /signalr/ping?apiKey=8f41f76aa2814ba0a05f42b2e43c426d&_=1506950636814 HTTP/1.1", upstream: "http://127.0.0.1:8989/signalr/ping?apiKey=8f41f76aa2814ba0a05f42b2e43c426d&_=1506950636814", host: "sonarr.nas", referrer: "http://sonarr.nas/system/backup"
2017/10/03 19:03:23 [error] 18670#18670: *1145718 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.43.100, server: sonarr.nas, request: "GET /signalr/ping?apiKey=8f41f76aa2814ba0a05f42b2e43c426d&_=1506950636815 HTTP/1.1", upstream: "http://127.0.0.1:8989/signalr/ping?apiKey=8f41f76aa2814ba0a05f42b2e43c426d&_=1506950636815", host: "sonarr.nas", referrer: "http://sonarr.nas/system/backup"
2017/10/05 15:55:19 [error] 18667#18667: *1170140 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.43.100, server: sonarr.nas, request: "GET /system/backup HTTP/1.1", upstream: "http://127.0.0.1:8989/system/backup", host: "sonarr.nas"
2017/10/05 15:56:19 [error] 18667#18667: *1170140 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.43.100, server: sonarr.nas, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8989/favicon.ico", host: "sonarr.nas"
2017/10/05 16:11:52 [error] 17591#17591: *1173411 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.43.100, server: sonarr.nas, request: "GET /signalr/reconnect?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA4E&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=9&_=1507212028551 HTTP/1.1", upstream: "http://127.0.0.1:8989/signalr/reconnect?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA4E&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=9&_=1507212028551", host: "sonarr.nas", referrer: "http://sonarr.nas/activity/queue"
2017/10/05 16:13:11 [error] 17591#17591: *1173686 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.43.100, server: sonarr.nas, request: "GET /signalr/poll?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA57&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=1&_=1507212028565 HTTP/1.1", upstream: "http://127.0.0.1:8989/signalr/poll?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA57&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=1&_=1507212028565", host: "sonarr.nas", referrer: "http://sonarr.nas/activity/queue"
2017/10/05 16:15:04 [error] 17591#17591: *1173806 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.43.100, server: sonarr.nas, request: "GET /signalr/poll?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA68&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=9&_=1507212028594 HTTP/1.1", upstream: "http://127.0.0.1:8989/signalr/poll?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA68&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=9&_=1507212028594", host: "sonarr.nas", referrer: "http://sonarr.nas/activity/queue"
2017/10/05 16:16:11 [error] 17591#17591: *1173806 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.43.100, server: sonarr.nas, request: "GET /signalr/reconnect?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA69&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=0&_=1507212028601 HTTP/1.1", upstream: "http://127.0.0.1:8989/signalr/reconnect?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA69&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=0&_=1507212028601", host: "sonarr.nas", referrer: "http://sonarr.nas/activity/queue"
2017/10/05 16:17:47 [error] 17591#17591: *1173992 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.43.100, server: sonarr.nas, request: "GET /signalr/poll?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA6E&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=9&_=1507212028611 HTTP/1.1", upstream: "http://127.0.0.1:8989/signalr/poll?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA6E&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=9&_=1507212028611", host: "sonarr.nas", referrer: "http://sonarr.nas/activity/queue"
2017/10/05 16:18:47 [error] 17591#17591: *1173992 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.43.100, server: sonarr.nas, request: "GET /signalr/reconnect?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA6E&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=0&_=1507212028613 HTTP/1.1", upstream: "http://127.0.0.1:8989/signalr/reconnect?transport=longPolling&connectionToken=d3FWGGtch0mXzHl0Ylg%2Fetj%2Fkja2hdGueRVAzmmUQxz17c94K4ovetGB%2FhyNwg48o%2Bn3ADs974RY%2BuUYKrffHKc8wq4MZBe7PzcIBROMbVZeHkPIZd7VVx8KFUpMi4hEQzk69wY69o9yfassuVugRBG%2FcVw3jSoUbIOElfufne9Gsc3Mys7XRz6TUC1GP3H6bONvOh1iDzMeLyeDeUgaheAmXJMVCpKDPkEwtNuW%2BjoErwUc1rMSu3eOfGypLJIuy0UvdLudIaQivS26c8twultKJtmo1tHzEEtUyz1w%2Bo1pZL%2FGkS9qUQ3spbx1COTt&messageId=d-6F2E4689-B%2CA6E&apiKey=8f41f76aa2814ba0a05f42b2e43c426d&tid=0&_=1507212028613", host: "sonarr.nas", referrer: "http://sonarr.nas/activity/queue"

**Comment by Safihre** [comment]
Please try the package in #3138, maybe it will fix this.

**Comment by Safihre** [comment]
Closing due to age and lack of response. Issue can be re-opened of course if newer Sonarr and `mono` packages have not solved this issue.
