### ISSUE TITLE
Sonarr & jackett not appear in synocommu repo (DSM 6.1.3)

### ISSUE THREAD

**Issue by nicduch** [SynoCommunity/spksrc#2948]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Sonarr & Jackett
_Package Version: latest

_NAS Model: DS918+
_NAS Architecture:Intel Celeron J3455
_DSM version: 6.1.3

### Expected behavior
After add repo synocommunity, check beta version, accept all contain of tiers, sonnar and jackett doesn’t appear 

### Actual behavior
Same
### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ThomasClemenceau** [comment]
Hi ! Issue already reported at https://github.com/SynoCommunity/spksrc/issues/2945 👍

**Comment by Safihre** [comment]
More and more packages are added for this arch, test packages can also be found in #3138 (after the official release on SynoCommunity, the package will auto-update from the official release).
Please create separate issues for specific packages if they are not already in #3138.
