### ISSUE TITLE
Transmission, git, python needed for DSM6.1.3-15152

### ISSUE THREAD

**Issue by edjanssen** [SynoCommunity/spksrc#2950]
Hi 

are the packages Transmission, git, python going to be available any time soon on DSM6.1.3-15152?

**Comment by Safihre** [comment]
Test packages for DSM6.1 and various architectures are available here #3138. They also include a new way of handling permissions.
We hope to publish the packages to the official repo soon and appreciate all testing and reports on the functioning of these packages.
