### ISSUE TITLE
transmission cannot be found in installed 

### ISSUE THREAD

**Issue by felix0926** [SynoCommunity/spksrc#2954]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_
_Package Version:_

_NAS Model:_synology ds 216+II
_NAS Architecture:_x86
_DSM version:_6.2 beta and the latest stable version

### Expected behavior
Tell us what should happen
The Transmission should be found in main menu and can run properly.

### Actual behavior
Tell us what happens instead
I cannot find the icon in main menu, but in fact I have installed the Transmission and can find the Transmission in Installed tab.
### Steps to reproduce
_1._install Transmission
_2._Open main menu
_3._Cannot find the icon.

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```

Information | 系统 | 2017/10/09 15:46:40 | admin | Package [Transmission] has been successfully
-- | -- | -- | -- | --

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Safihre** [comment]
Please try the test-packages in #3138 if this issue still persists. 
Closing this for now, please provide feedback in the testing-issue.
