### ISSUE TITLE
Midnight Commander cannotbe installed on DS1517+

### ISSUE THREAD

**Issue by Mevrouw-Marijke** [SynoCommunity/spksrc#2956]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Midnight Commander
_Package Version: 4.8.15-3

_NAS Model:_ DS1517+
_NAS Architecture: INTEL Atom C2538
_DSM version: DSM 6.1.3-15152

### Expected behavior
Installation of Midnight Commander

### Actual behavior
Installation attempt of Midnight Commander failed with message: "Midnight Commander" could not be installed. This package was not provided by Synology Inc.

### Steps to reproduce
_1. reinstall - same message

#### Package log
n/a

**Comment by ymartin59** [comment]
Package published in repository
