### ISSUE TITLE
DS3018xs "Invalid location."?

### ISSUE THREAD

**Issue by fazuw** [SynoCommunity/spksrc#2957]
_NAS Model:_DS3018xs
_NAS Architecture:_Broadwellnk
_DSM version:_6.1

### Expected behavior
Being able to add the SynoCommunity package source to DSM.

### Actual behavior
When trying to add http://packages.synocommunity.com/ package source in Package Center i always get the "Invalid location." error.

I was wondering when the new DS3018xs would be supported?

**Comment by ymartin59** [comment]
This device uses yet-another-architecture "Broadwellnk" for which toolchain is not yet available: https://www.synology.com/en-us/knowledgebase/DSM/tutorial/General/What_kind_of_CPU_does_my_NAS_have

**Comment by fazuw** [comment]
Thanks for the quick reply, do you have any idea when it will be available?

**Comment by ymartin59** [comment]
No... It took months before DSM 6.1 has been published. It was faster for recent "apollolake" and "deventon". I guess a request on Synology forum may help.

**Comment by wcannon44** [comment]
Anyone know if this was ever resolved? This unit has been out for a while now and im still getting this error.  Im running the latest of 6.1.

**Comment by ymartin59** [comment]
May you please refresh Package Center and report feedback ?

**Comment by wcannon44** [comment]
Ha I swear this wasn’t working before but it added fine this morning. The only weird thing now is only about half of the advertised apps show up. Missing things like sabnzbd and sonarr.

**Comment by ymartin59** [comment]
OK. Just expected. All architecture specific packages have to be rebuilt and published for Broadwellnk.

**Comment by Safihre** [comment]
More and more packages are added for this arch, test packages can also be found in #3138 (after the official release on SynoCommunity, the package will auto-update from the official release).
Please create separate issues for specific packages.
