### ISSUE TITLE
Chromaprint/media info dont appear

### ISSUE THREAD

**Issue by romanoh** [SynoCommunity/spksrc#2963]
on Synology 216j, i have installed the sources.

**Comment by m4tt075** [comment]
@romanoh Is this issue still present? If so, could you please provide some more details on what the issue actually is?

**Comment by ymartin59** [comment]
Sure. armada38x is not available: https://synocommunity.com/package/chromaprint
I forgot it in my target list... It will be fixed with future updates publish.

**Comment by ymartin59** [comment]
Package published with ffmpeg 4.1 dependency.
