### ISSUE TITLE
No packages are listed in Community Tab DSM 6.2 beta

### ISSUE THREAD

**Issue by leotzian** [SynoCommunity/spksrc#2964]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: No packahes exists in Community Tab
_Package Version:_

_NAS Model:_Ds416Play
_NAS Architecture:_braswell (x86_64)
_DSM version:_ 6.2 beta

### Expected behavior
Hi I don't know if this is the correct location to post the problem but I had installed 6.2 beta in my new Ds416Play and when I try to access your packages I have the error   " check your network settings".
I had contacted synology but they say that is community problem and try contact you.
I had checked my dns servers I had tried Googles and Open but no success, In synology forum some models has this problem some hasn't.
If I run "nslookup packages.synocommunity.com"  I have result 104.31.94.179 and 104.31.95.179 

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
This will be addressed as #2966

**Comment by spoelly** [comment]
A reboot of my NAS did the trick, but not all the syno packages are listed, beta's are missing.

**Comment by ymartin59** [comment]
May you please be more explicit about which packages are lacking?

**Comment by spoelly** [comment]
For example Sabnzbd beta is missing.

**Comment by spoelly** [comment]
huh what happend they are now listed...??

**Comment by m4tt075** [comment]
OK, probably just caching of your browser or something. Closing this one. Please open another issue, if you should encounter problems again.
