### ISSUE TITLE
Support for DSM 6.2 (firmware version): jackett...

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#2966]
Probably additional behaviors has to be added in synospk repository code.

**Comment by leotzian** [comment]
I want to let you know that although on my Ds416Play running DSM6.2 beta in the Community Tab no Packages are shown , ( Check you Network Settings Error ) in my old Ds212j with the same beta synocommunity Packages are all there.

**Comment by mnervik** [comment]
On my 2 nas devices (DS415play and DS1517+) I'm missing all the beta packages, not getting any network-settings-error though

**Comment by ymartin59** [comment]
May you please be more explicit. Which packages are available, which ones are not? Please upload a screenshot, and confirm you checked "beta versions" option in Package Center.

**Comment by mnervik** [comment]
I'm spesifically looking for jackett...but I can't see it or any other beta packages.
Beta packages checkbox is checked, and I've also checked the beta tab...but no synocommunity packages there either.
![ds1517](https://user-images.githubusercontent.com/15329600/41626159-a6c834c4-741b-11e8-9dd6-8c692a6955fd.png)

**Comment by ymartin59** [comment]
These are SynoCommunity packages. And for instance "ZNC" is beta: https://synocommunity.com/package/znc
Jackett is not beta: https://synocommunity.com/package/jackett
I am investigating

**Comment by mloureiro** [comment]
I have far less.
Version `DSM 6.2-23739` on DS918+

![available packages](https://snag.gy/q9kUyX.jpg)

**Comment by ymartin59** [comment]
From my point of view, issue is not related to DSM 6.2 but "architecture" support. DS918+ is `apollolake` and most packages have not been rebuilt for it yet.
If you are interested some lacking packages, please create a dedicated issue to request one specific package (one issue per package please), with reason you expect it for `apollolake`.

I now investigate why `jackett` is lacking on `apollolake` (DS918+), `evansport` (DS415play) and `avoton` (DS1517+) whereas it should be available.

**Comment by mloureiro** [comment]
I'm currently interested in `jackett`, which you're already on it, thanks 👍

**Comment by ymartin59** [comment]
This seems related to "firmware" version INFO property, deprecated from DSM 6.1, which has to be replaced by "os_min_ver". @publicarray To keep support with previous DSM versions, both should be present in file. https://developer.synology.com/developer-guide/synology_package/INFO_necessary_fields.html

@m4tt075 Does it sound relevant to update Jackett to latest version before publishing again?

**Comment by publicarray** [comment]
Ah sorry that I messed this up. To explain why I changed it I'll include the reply I got when I submitted my package for review to synology. This is when both fields where present in the INFO file.
 
> Hi Publicarray, 
> 
> 
>We have found an issue in your new build (version 2.0.14).
>
>INFO: failed
>Please correct the firmware and os_min_ver in INFO.
>For example: In 5-2 spk, it do not support DSM 6-1, so you cannot write os_min_ver="6.1-14715".
>In 6-1 spk, firmware="3.1-1594" is wrong.
>In addition, please remove useless key in INFO (e.g.,  reloadui)
>
>conf: failed
>Resource is not json format, please fix it.
> 
>Please fix it and provide the new build.
>Thanks.

I realise now that publishing to SynoCommunity is different and ideally the packages should be build separately for 6.1 and previous DSM versions. Yes to workaround this we can add both fields to the INFO file but I'm guessing this is not fully "supported" or something.

**Comment by ymartin59** [comment]
@publicarray If a package contains binary working in DSM 5.2, 6.0, 6.1, 6.2 (typically nano or mutt...), I expect to publish a single package.

**Comment by publicarray** [comment]
@ymartin59 Yea I would do the same thing and since this is a community package repository you can do what you like. On the other hand Synology is pretty clear on what they want.

**Comment by ymartin59** [comment]
I still do not understand what happens here. Lacking "os_min_vers" may not be the "root" cause of lacking Jackett... because recent packages like "PlexPy Custom" or "LazyLabrarian" do not have that attribute but are visible in DSM 6.2.

**Comment by publicarray** [comment]
From what I understand if the `os_min_vers` key is missing than the DSM 6.1+ will follow `firmware` or just ignore the `firmware` setting. However if the DSM version is less than 6.1 and the firmware key is missing it might refuse to install (It doesn't know about `os_min_vers` at all)

**Comment by ymartin59** [comment]
@publicarray @Safihre OK if it refuses to install. At least error message is clear. Previous DSM versions are not aware of `os_min_vers` and I think unknown properties are simply ignored.
What I do not understand is: package does not fail to install because of INFO properties... package is simply not available in Package Center list. So DSM 6.2 may not accept spkrepo returns here.

**Comment by publicarray** [comment]
spkrepo might not know about `os_min_vers` and instead relies on `firmware`?

**Comment by ymartin59** [comment]
@Safihre @BenjV @publicarray Right. Protocol may have changed between DSM 6.2 and online repository... Package Center may no longer send "firmware" but "os_min_vers", so a patch in spkrepo is required. I have backups so that I can upgrade to DSM 6.2 and test on my own.

**Comment by ymartin59** [comment]
@Safihre Because of that issue and #3339, we can consider all packages have to be republished. My option is to discard "transitional" busybox dependency from non-arch package, typically like Jackett, to reduce volume... To notice, most users do not complain because their packages were already installed with DSM 6.1 (like Mono dependency or Python...). Holders of brand new Syno with DSM 6.2 pre-installed will probably be less happy.

**Comment by ymartin59** [comment]
Notice "View log" and "admin" URL link have been removed from Package Center.

**Comment by ymartin59** [comment]
I just registered an new architecture 6.2-23739 in spkrepo... whereas it was already known as 6.2-22259.
No idea was is wrong in spkrepo in its way to browse package for an architecture and firmware...
Probably this issue can be closed.

**Comment by Safihre** [comment]
So the problem was the version number?

> Notice "View log" has been removed from Package Center.

I contacted Synology about that when I saw it during the beta back in February, but they responded that they "did not consider it usefull" and that I could submit a change request (which I did). Posted that somewhere in a comment here, somewhere 🌥

**Comment by BenjV** [comment]
@Safihre 
See my remarks here https://github.com/SynoCommunity/spkrepo/issues/17

**Comment by ymartin59** [comment]
@mloureiro May you please confirm you get Jackett back? Thank you for your feedback

**Comment by Safihre** [comment]
@mloureiro you can look at any of the recent packages (check the commit history).
There you can see examples of new-style packages where we try to use the framework @ymartin59 made as much as possible. On the wiki of this Github page and the main README you can find info how to setup the developer environment (just gets the right docker image).

**Comment by ymartin59** [comment]
@mloureiro you can inspire from recent merged PRs. About jDownloader, a request is already pending: #2773

**Comment by BenjV** [comment]
On my DS116 with DSM 6.2 there are still missing packages.
Like Jackett and Deluge

**Comment by ymartin59** [comment]
These two packages are not available for PPC architectures (like Mono) but DS116 is `armada_38x`, so ARM if I do not mistaken...

**Comment by BenjV** [comment]
This morning those packages showed up in my package center along with a lot of other packages I missed on my DSM 6,2 machine.
So did you do something this morning or does the repro has some overnight batch job that does things?

**Comment by ymartin59** [comment]
Not this morning... two days ago. So I guess Package Center just refreshed.

**Comment by BenjV** [comment]
Cannot have anything to do with the Package Centre on my DSM because I of course did several refreshes of my package center.
Must be something on the repro site.

**Comment by publicarray** [comment]
CloudFlare caching perhaps? Although the according to the response headers they should expire in 1 day.

**Comment by solabc16** [comment]
FYI... whilst we've been looking at other issues surrounding Package Center under DSM 6.2:-

"Package Center under DSM 6.2 also appear to suffer from a caching/non-updating issue which was seen on earlier versions of DSM; in that it simply does not connect to the configured package sources. This happens regardless of whether the system has been rebooted and/or the refresh triggered manually. As before, changing the network settings, applying them, then setting them back as they were seems to bring Package Center 'back to life' and it will connect to the package source and display the available packages."
