### ISSUE TITLE
Ffmpeg 3.3.3 for DSM 6.1 x64 (like avaton)

### ISSUE THREAD

**Issue by Nexius2** [SynoCommunity/spksrc#2967]
Latest ffmpeg version not available for DS1815+ and 1817+

### Setup
_Package Name:_ ffmpeg
_Package Version:_ 3.3.3

_NAS Model:_ 1817+
_NAS Architecture:_ avoton
_DSM version:_6.1

### Expected behavior
Package not available but is ok for DS115j

**Comment by ymartin59** [comment]
`ffmpeg` should be visible in package manager for `avoton` architecture... but cannot be run after installation as it requires specific compilation for DSM 6.1
I have just built it manually, you can get it at: http://dl.free.fr/v8G2U6LHn
If OK, please close this issue.

**Comment by Nexius2** [comment]
Thanks for the help.
Package doesn’t install
It says « failed to install ffmpeg »

**Comment by ymartin59** [comment]
My fault. I built on wrong branch. Here it is (I hope I did right that time): http://dl.free.fr/jJqQnktV5
Please close if OK

**Comment by Nexius2** [comment]
That’s better. It seems to be working (tryied on 6 movies).
Thanks for the update

**Comment by mansu1423** [comment]
1517+ isn't work on 1517+

tested 5 movies and ac3 codec movies doesn't play

**Comment by Nexius2** [comment]
Just tested 4 ac3, working for me, no problem.
But a hevc seems to be not working. I have to check with other files

**Comment by repmeer** [comment]
@Nexius2 Which version of videostation are you running?

**Comment by Nexius2** [comment]
I’m now running latest version (2.3.6-1475) without any issues

**Comment by repmeer** [comment]
@Nexius2 You probably tested it wit AC3 codec files and not with EAC3 codec files

**Comment by Nexius2** [comment]
Yes, I messed up.
I searched for a EAC3 to have a check, but I have none.
If you have a file to share, I can check if it’s working or not on my side

**Comment by Nexius2** [comment]
I just downloaded a e-ac3 file to check.
I have the same issue, transcoding doesn't work.
but I have no idea if it worked before

**Comment by cytec** [comment]
to get this straight:
We __do not__ provide VideoStation, nor is our Version of ffmpeg used by VideoStation. If you can't play E-AC3 Audio Files in VideoStation that's most likely because the ffmpeg version that comes with VideoStation doesn't contain any eac3 codec... There is no way _we_ can fix this, since that's an official synology SPK. You might want to ask their support about this. See https://github.com/SynoCommunity/spksrc/issues/2952#issuecomment-335637764 and following for more Info

**Comment by zunami** [comment]
the links does not work http://dl.free.fr/jJqQnktV5
a new Link? or new version?

**Comment by ymartin59** [comment]
Please report to #3138
