### ISSUE TITLE
Ds418 available (RTD1296), but package Sabnzb and Sonar not

### ISSUE THREAD

**Issue by banshee1971** [SynoCommunity/spksrc#2971]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:Sonar, Sabnzb
_Package Version:all

_NAS Model:DS418
_NAS Architecture:Realtek RTD1296
_DSM version:6

### Expected behavior
Sabnzb, sonar, python 2 not available (only 3)

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by mixuk** [comment]
HAve same issue with DS918+

**Comment by bservet** [comment]
For me as well, on a new DS918+ packages are missing, for example Midnight Commander. Is (perhaps) the x64 processor not recognised as x86 compatible?

**Comment by Producermark** [comment]
Hi! Please check out: 
https://github.com/SynoCommunity/spksrc/issues/2945

**Comment by banshee1971** [comment]
I check, but for now, not working.
I test the package there (Mono + Radar), but Mono not compatible with my NAS.
The CPU of the DS418 is Realtek RTD 1296

So i need to be patient ! For now, i have a dedicated PC that run Sabnzb and Radar. After download and extract the file, it push them to the NAS.

**Comment by WodKa78** [comment]
I was able to compile some packages for arch-rtd1296 and run them succesfully (so far...) 
Sonarr, Radarr, Git and Mono(external link) can be found in my repository if anybody is interested. 

For both Sonarr and Radarr you will need to edit the start-stop-status:
_sudo vi /var/packages/radarr/scripts/start-stop-status
and change MONO_PATH  to MONO_PATH="/var/packages/Mono/target/usr/local/bin/"_ + 
_sudo vi /var/packages/nzbdrone/scripts/start-stop-status
and change MONO_PATH  to MONO_PATH="/var/packages/Mono/target/usr/local/bin/"_

I am a complete noob and just tried to make it work for myself so please take the packages as they are for now.

**Comment by rafieek** [comment]
@WodKa78 I am more of a complete noob to all this, and I have a DS218play(with rtd1296) and was hoping your packages would work for me as well.

I installed mediainfo and Mono and they are both running. But when I installed sonarr, I changed the mono path like you said. But when I try to start the package it doesnt start. So I decided to uninstall the package and try again. After trying to manually install the package again, it gets all the way to the last step but fails with a dialog message of "Not available".

Any ideas?

**Comment by EniDurb** [comment]
I have the ds418play for 5 days now and I don't find any solution to get sonarr any idea to help me ?

**Comment by Producermark** [comment]
Hi @EniDurb,
The sabnzb file that's being shared here multiple times is actually the sonarr spk when you install it.
Yes, exactly, that confused me too.
You can download it and use upload manually to install Sonarr.

Hope I've helped,

**Comment by WodKa78** [comment]
nzbdrone_rtd1296-6.1_20171112-10.spk is the file you need from my repo. Read the readme first before installing

**Comment by EniDurb** [comment]
@Producermark Oh yeah didnt get it !
Thanks you I am happy there are people like you !
@WodKa78 Thanks you too its very friendly to make your own repo and share it for free, will check that.
By the way is it safe ?
I guess yeah but I mean why the "official" or  the "synocommunity" dont have it ?
Thanks again, both of you, made my day better.

**Comment by sandval** [comment]
@WodKa78 Thanks for your enthusiasm, it's really cool that you compiled these packages. Is there a chance that you will compile ffmpeg #2997? That would be even cooler. :)

**Comment by EniDurb** [comment]
@WodKa78 when I try to install nzbdrone (rtd1296-6.1_20171112-10) 
I have this result : https://cl.ly/2O1c3V0p3918
And of course "mono beta" from "package center" and stopped, installed your mono, and running.
So ....

**Comment by WodKa78** [comment]
@EniDurb i see now you have the play version which has Intel cpu and so this package will not work as compiled for ARM.

**Comment by WodKa78** [comment]
@sandval your welcome, good to see people appriciate it :-) 
As for ffmpeg package seems its not just a matter of compiling but there are more issue if i read @ymartin59 comments in https://github.com/SynoCommunity/spksrc/issues/2886#issuecomment-334266794 well. 
I cannot be at help with those specific issues as i am not a programmer of any kind, just learned a bit how to compile with spksrc to satisfy my needs. if those issues will be solved i am ofcourse more then happy to try compiling it for us rtd1296 users.

**Comment by banshee1971** [comment]
Did you find a Docker package working for RTD1296 CPU ? (just in case...)

About the Mono part, i try to stop it after the installation, but this option not there. Only Uninstall.
I did the 2 modification using Putty, and also reboot the NAS.

I reboot the NAS, same result, Mono only have "uninstall" in his action tab !

**Comment by banshee1971** [comment]
I try some package from here... just in case, but none of them works (probably they will with the Play version)

https://usdl.synology.com/download/Package/spk/Docker/

**Comment by WodKa78** [comment]
Docker is only available for machines running on Intel cpu, not (yet) available for ARM devices

**Comment by WodKa78** [comment]
@banshee1971 first install run/stop the "official" Synology version of Mono (Beta) then install the one from my repo (which cannot be stopped just uninstalled)

**Comment by sandval** [comment]
Thanks @WodKa78, I saw @ymartin59's post, but I hoped the best. :)

**Comment by hogendoorn** [comment]
@WodKa78 Thanks for compiling these packages. Following your short manual works great! Any chance you could compile a package like Sabnzbd? That would make is complete  :)

**Comment by EniDurb** [comment]
@WodKa78 there is no docker in packagecenter ... :/

**Comment by EniDurb** [comment]
@banshee1971 Thanks docker.spk worked will try to find sonarr now :/

**Comment by banshee1971** [comment]
you are lucky ! I cant use Docker yet (hope it will be available with non-intel cpu)...

**Comment by banshee1971** [comment]
![sans titre](https://user-images.githubusercontent.com/7092486/33157079-60888d30-cfcd-11e7-834e-22b03ae77266.png)

I un-install everything.. Then Install Mono (from Syno), stop !
Install the new Mono, mediainfo, then nzbdrone and i got an error message (with no message on it).
any clue ?

**Comment by WodKa78** [comment]
restart the machine and start again the procedure, had this also before ones

**Comment by WodKa78** [comment]
@hogendoorn Sabnzbd requires Python to run an i still am not able to compile that package. I suggest you use Nzbget instead. In issue https://github.com/SynoCommunity/spksrc/issues/2886 user [BidorffOL](https://github.com/bidorffOL) presented that package. Works like a charm...

**Comment by WodKa78** [comment]
https://github.com/SynoCommunity/spksrc/issues/3009 @Safihre made a great effort and got Python running. Works with the packages on my repo so you can try Sabnzbd if you want. @hogendoorn

**Comment by Johnito** [comment]
@WodKa78 you rock ! This is really an early christmas to me :-) 

Well, i dont feel good asking for this, since you obviously do not use it yourself, but ... would it be complicated to compile the transmission package ? Apart from the official Synology thing, there isnt any torrent downloader available on RTD1296.

**Comment by Safihre** [comment]
Already done 👍 
https://github.com/Safihre/spksrc/releases/tag/transmission-1-dsm61

**Comment by Johnito** [comment]
Nice !!! But i actually meant rutorrent. This one is a it more complciated right ?

**Comment by WodKa78** [comment]
@Johnito thanks but all credits belong to the developers here who made and maintain spksrc, I am just using their tools an publish :-)

**Comment by WodKa78** [comment]
For rutorrent I suggest you open an package request (read the contribute guidelines how to proper request a new package) and hope someone will pick it up.

**Comment by Safihre** [comment]
Unfortunately the build is failing:
https://travis-ci.org/Safihre/spksrc/jobs/307825942

But it is due to problems with `curl`, probably simple to fix if you know where to look. Seems some library needs to be updated.

**Comment by Johnito** [comment]
@Safihre after some time testing, except RSS on RTD1296, the package you compiled works very well. I do not know either whats wrong with curl libs, but AFAIC what you were able to provide is just perfect. I hope many will find those packages easily.

BTW, I also installed your GIT and PYTHON packages in order to run "sickbeard-custom" (noarch). It doesn't want to install since it cannot see your compiled packages (probably because it is expecting SynoCommunity versions ?). Can you add sickbeard-custom to your list too if it's possible ? 

[https://synocommunity.com/package/sickbeard-custom](https://synocommunity.com/package/sickbeard-custom)

**Comment by WodKa78** [comment]
@Johnito try [this one](https://github.com/WodKa78/-syno-packages/blob/master/couchpotatoserver-custom_noarch-all_20171129-4.spk) i can't test right now so please check and comment

**Comment by WodKa78** [comment]
@Johnito [try this one](https://github.com/WodKa78/-syno-packages/blob/master/sickbeard-custom_noarch-all_20171129-4.spk) i can't test at the moment so please check and comment.

**Comment by Johnito** [comment]
@WodKa78 your compilation is working well 👍 

Tested (install + few tests) on both Avoton and RTD1296 based Synos without any issues. Logs inspection also confirm there is no issues whatsoever.

**Comment by Safihre** [comment]
Cross-post from #2945, new packages for Python and SABnzbd.

> So, it has taken days of compiling, liters of coffee and moments of pulling my own hairs, but I think I have working packages now.
> Who feels like trying?
> Python: https://github.com/Safihre/spksrc/releases/tag/python-dsm61-new-all
> SABnzbd: https://github.com/Safihre/spksrc/releases/tag/sabnzbd-dsm61-new-all

**Comment by Francis2b** [comment]
@Safihre is this mean Sonarr is now working on rtd1296 ?

**Comment by Safihre** [comment]
**New packages converted for generic service account, DSM6 compatibility and new architecture compatibility. [All are still in testing](https://github.com/SynoCommunity/spksrc/pulls)!**

If you experience problems (not requests for other packages), please send me logs at safihre@sabnzbd.org

- [NZBGet](https://github.com/Safihre/spksrc/releases/tag/nzbget-dsm61-new-all)
- [Python](https://github.com/Safihre/spksrc/releases/tag/python-dsm61-new-all) _(Updated since last post! Please update to this one)_
- [SABnzbd](https://github.com/Safihre/spksrc/releases/tag/sabnzbd-dsm61-new-all) _(Updated since last post! Please update to this one)_
- [Git](https://github.com/Safihre/spksrc/releases/tag/git-dsm61-new-all)
- [CouchPotato](https://github.com/Safihre/spksrc/releases/tag/cp-dsm61-new-all)
- [Sickrage](https://github.com/Safihre/spksrc/releases/tag/sickrage-dsm61-new-all)
- [Syncthing](https://github.com/Safihre/spksrc/releases/tag/syncthing-dsm61-new-all)

**Comment by Francis2b** [comment]
Is NZBGet still changing the name of the group sc-media ?

**Comment by Safihre** [comment]
No, it's now in `sc-download` and doesn't touch anything else.

**Comment by Francis2b** [comment]
Yes sorry it was sc-download that was renamed. I'm home not home so I wasn't able to check. So now  NZBGet doesn't rename anything? Great! But what happens it the group was rename by the previous version?

**Comment by Safihre** [comment]
I'm sorry but I don't understand what you mean. Rename in what way? The description?
It will create the group if it doesn't exist and ads the `sc-nzbget` user to it if it's nog already in the group.

**Comment by Francis2b** [comment]
In a previous version, my `sc-download` got renamed in `sc-download__PKG__` or something like that I can't check I'm not home

**Comment by Safihre** [comment]
It might create a new `sc-download` if only this modified one exists. 
I wasn't aware of this potential side-effect and haven't see it in my testing so far.

**Comment by Francis2b** [comment]
As soon as I get home I post a picture

**Comment by Francis2b** [comment]
Here is the screenshot:
<img width="1920" alt="screen shot 2018-01-12 at 16 50 40" src="https://user-images.githubusercontent.com/21141137/34883101-e44a5bfe-f7b8-11e7-8158-7d59cdeff185.png">

**Comment by Safihre** [comment]
`sc-media` is not related to NZBget, but to one of the media related packages. So one of  couchpotato, sonarr, radarr, tvheaded, etc.

**Comment by Safihre** [comment]
I doubt this new package does this too. There is just no way it could do that. 
Unless other people report it, I would like to end the discussion about it for now.

**Comment by Safihre** [comment]
New package list here (just added Sonarr/Radarr): https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-357008518

**Comment by simoneves** [comment]
@Safihre and others, I have had a DS418j (rtd1296) for several months now, after many happy years with a DS213+ and all sorts of SynoCommunity packages, but most of them are still unavailable for this architecture. Even some of the few that are (e.g. CouchPotato) won't install because they say that "python" is missing, even though if I ssh in I can run Python 2.7 just fine in a shall (and I tried installing Python Modules and Python3 and it made no difference). I am comfortable with most of the tech involved here, but I just don't really know where to start. I'd be happy for now with just a compatible build of Transmission or some other decent BT client, but I can't even get that far. Please advise. Thx.

**Comment by Safihre** [comment]
@simoneves please follow [my link to the package list](https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-357008518)  where you can download the available test packages for your platform. We work on a package by package basis and those are the ones available at the moment.

**Comment by PolliSoft** [comment]
@Safihre, @m4tt075 I looked at https://github.com/m4tt075/spksrc/releases/tag/Tvheadend-4.2.5 for a TVHeadEnd for DS418j, RTD1296 architecture. It's not out yet, is it possible for you guys to compile a version? I'm happy to help with testing.

**Comment by TonVH** [comment]
@PolliSoft 
At https://github.com/m4tt075/spksrc/releases/tag/TVH-4.2.5-recrecov there is a .spk for the RTD cpu. I can install it but for unknown reason it will not run. Maybe you have better luck.

**Comment by PolliSoft** [comment]
@TonVH, yes I have been using it for 3 weeks. I also have problems starting it. Usually it takes me around 5 tries before it starts. And if I stop the package, I have to restart the NAS before being able to run it again.

**Comment by TonVH** [comment]
You’re right. Very strange behavior.
