### ISSUE TITLE
Remove sabnzbd-testing and nzbget-testing packages

### ISSUE THREAD

**Issue by Safihre** [SynoCommunity/spksrc#2973]
As discussed here https://github.com/SynoCommunity/spksrc/issues/2926#issuecomment-331712765, the `sabnzbd-testing` and `nzbget-testing` packages are not really needed.
Is there a way to transition the users of these packages automatically to the regular packages, is there a sort of "symlink" in the system?

While probably not a priority right now with all the work going on for DSM6, I just wanted to note it somewhere for the future. I will soon submit the update for SABnzbd 2.3.1, but that will still be for both packages.

**Comment by ymartin59** [comment]
We have to take care that both packages (stable and testing) run with same background user and permission. My idea is to a latest update of "testing" with wizard notification to install stable version, check everything is OK before uninstalling "testing". Either both use same database configuration or else data has to be "migrated" to stable thanks to an automated backup/restore process.

**Comment by Safihre** [comment]
Yes there would need to be an automated copy of the settings etc for easy transition.
That sounds complicated.

**Comment by hgy59** [comment]
@ymartin59 it is as simble as removing the nzbget-testing from the repository.
I would not spend any time in a database/settings migration from nzbget-testing to nzbget, not even for a note in a wizard.

**Comment by Safihre** [comment]
Agreed! Remove!

**Comment by ymartin59** [comment]
I have disabled all versions for these packages in spkrepo. After few months, I will delete for space cleanup.
