### ISSUE TITLE
ffmpeg missing from DS216j (armada38x) with DSM 6.1

### ISSUE THREAD

**Issue by xnaveira** [SynoCommunity/spksrc#2975]
### Setup
_Package Name:_ ffmpeg
_Package Version:_ ?

_NAS Model:_ DS216j
_NAS Architecture:_ MARVELL Armada 385 88F6820
--

_DSM version:_ DSM 6.1.3-15152 Update 8

### Expected behavior
ffmpeg in the list available for install

### Actual behavior
ffmpeg is NOT in the list available for install

**Comment by ymartin59** [comment]
I did a specific build. Here it is: http://dl.free.fr/fC7oZSoFQ
If OK, please close this issue

**Comment by xnaveira** [comment]
Well what I was trying to solve by installing this package is to get rid of the "eac3" sound not supported, and that's still an issue for me after installing the package. Any info regarding that would be very much appreciated. Thank you for making the package ayway!

**Comment by ymartin59** [comment]
Ok. So is that 3.3.3 package provides EAC3 support or not ? I guess typical usage is to play or stream from Video Station. By the way, recent Video Station seems like to ignore alternate ffmpeg: https://github.com/SynoCommunity/spksrc/issues/2952

**Comment by xnaveira** [comment]
Ok, I should have stated the whole problem i guess. Yes, the usage case is to play video from DS Video. And no, the package that you provided didn't solve the issue which seems to be consistent with the issue that you linked.

So I guess this is one of those silly cases where copyrights prevale over functionality and synologic doesn't want to include the support for eac3.

**Comment by ymartin59** [comment]
Synology is probably reluctant to pay royalities for each played stream in Video Station... The probably is previous version gets ffmpeg from PATH and SynoCommunity package was used... I propose you downgrade video station to 2.3.4 as explained at https://github.com/SynoCommunity/spksrc/issues/2952#issuecomment-337214013
If OK then, please close issue.

**Comment by xnaveira** [comment]
Thank you for your help!

**Comment by kurtn2005** [comment]
@ymartin59 May I know how to build ffmpeg for armada38x? Any specific configuration or parameters while building? Thanks!

**Comment by m4tt075** [comment]
@ka1je Sorry, but we had to revise the `ffmpeg` package. Please see #3564 for background and rationales. If you are interested, progress on addressing the issue and a complete overhaul of our `ffmpeg` and associated packages can be tracked in #3575.
