### ISSUE TITLE
Ffmpeg 3.3.3 for DSM 6.1.3 (1517+) 

### ISSUE THREAD

**Issue by mansu1423** [SynoCommunity/spksrc#2980]
### Setup
_Package Name:_ffmpeg 
_Package Version:_3.3.3

_NAS Model:_1517+
_NAS Architecture:_avoton (INTEL Atom C2538)
_DSM version:_DSM 6.1.3-15152 Update 8

### Expected behavior
ffmpeg is not working in 1517+ 
package center shows 3.1.2-4

**Comment by ymartin59** [comment]
Please get it from here: https://github.com/SynoCommunity/spksrc/issues/2967#issuecomment-338370705

**Comment by mansu1423** [comment]
before i made this issue already check and use it #2967  but it won't work

so i made this issue

**Comment by ymartin59** [comment]
So please explain explicitely what "is not working" with http://dl.free.fr/jJqQnktV5

**Comment by mansu1423** [comment]
thank you for your help

it is installed successfully but not working on some codec movies

tested 5 movies and eac3 movies doesn't play

**Comment by ymartin59** [comment]
If your problem is Video Station update... Follow downgrade info at https://github.com/SynoCommunity/spksrc/issues/2952#issuecomment-337214013

**Comment by ymartin59** [comment]
I propose you downgrade video station to 2.3.4 as explained at https://github.com/SynoCommunity/spksrc/issues/2952#issuecomment-337214013
If OK then, please close issue.
