### ISSUE TITLE
[Package Request] Update Jackett

### ISSUE THREAD

**Issue by ErwanNumb** [SynoCommunity/spksrc#2986]
Name: Jackett

The latest version of Jackett brings - a lot - of new torrent sources, could you please update it?

Thanks

**Comment by ErwanNumb** [comment]
still no interest in doing this?

**Comment by Safihre** [comment]
From what I understand Jackett can just use the in app updater?

**Comment by ymartin59** [comment]
Related to #3070

**Comment by m4tt075** [comment]
@ErwanNumb Thanks to @kaso17 's fixes, `Jackett 0.8.490` has been merged into master. That means that the packages for `DSM 5.2` systems should be available via the SynoCommunity repo shortly (if they aren't already). For the time being, you can find `DSM 6.1` builds for `Jackett` on [this link here](https://github.com/m4tt075/spksrc/releases/tag/Jackett-0.8.490). Once installed, you can run further upgrades via the Jackett web-interface. These are beta packages. Therefore, please do report any kind of issues you should encounter.

**Comment by ymartin59** [comment]
Mono and Jackett updates published
