### ISSUE TITLE
Syncthing WebUI won't load but the service is running

### ISSUE THREAD

**Issue by fruser** [SynoCommunity/spksrc#2987]
### Setup
_Package Name:_ Syncthing
_Package Version:_ 0.14.23-12

_NAS Model:_ DS211j
_NAS Architecture:_ ARM
_DSM version:_ DSM 6.1.3-15152 Update 8

### Expected behavior
Tell us what should happen
When SyncThing service is running, WebUI should be accessible via http://NAS_IP:7070
It is unclear to me as to why SyncThing just stopped working. There were no log files available for `/usr/local/syncthing/var/` directory to review.

### Actual behavior
Tell us what happens instead
`ERR_CONNECTION_REFUSED` error message appears upon attempt to access WebUI

### Steps to reproduce
_1._ Start SyncThing service from Synology Package Center
_2._ Try to open http://NAS_IP:7070
_3._ Observe the error

#### Package log
_Check Package Center or `/usr/local/syncthing/var/`_
```
Unfortunately, there are no log files available
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
# /var/log/synopkg.log
start syncthing: begin to start version 0.14.23-12
start syncthing: 0.14.23-12 Begin start-stop-status start
start syncthing: 0.14.23-12 End start-stop-status start ret=[0]
start syncthing: start version 0.14.23-12 successfully, result 0
```

**Comment by glarue** [comment]
I have this same issue, but I have noticed another quirk:

Immediately after reinstalling SyncThing, the web GUI is accessible for me on the local network at http://NAS_IP:7070. After attempting to add a username/password, however, the connection fails (and reports that another service is using the port). Thereafter, any attempt to launch the web GUI return the error described by @fruser

**Comment by ymartin59** [comment]
Package has been updated and published

**Comment by rohrbachger** [comment]
The package installs fine, I changed the port like described.
But I can not enter a Password.
From Linux / Firefox.  Any special trick to put in user ID and password?
No characters, no asterisks in the password field when I enter something.
