### ISSUE TITLE
No SABNZBD updates since version  2.2.1 on DS116

### ISSUE THREAD

**Issue by brassica77** [SynoCommunity/spksrc#2988]
### Setup
_Package Name : SABNZBD
_Package Version : 2.2.1

_NAS Model: DS116
_NAS Architecture: 32 bits
_DSM version: 6.1.3-15152 Update 8

### Expected behavior
SABNZBD should update to the latest version (2.3.1)

### Actual behavior
No new update appears since 2.2.1, although other packages are updating, and Synocommunity lists 2.3.1 as the latest version.

### Steps to reproduce
_1. Go to Packages Center
_2. Refresh packages list

**Comment by enigma2k** [comment]
Exact same here on our DS116.

**Comment by brassica77** [comment]
Synocommunity showed version 2.3.1 and SABNZBD was correctly updated to it last night, no idea what happened or changed.
Am I the only one noticing it? Did something changed somewhere? Can I close the ticket now?

**Comment by ymartin59** [comment]
Correct PR #2976 has updated version and cytec has built and published it. You can close.

**Comment by Safihre** [comment]
@ymartin59 what went wrong with the 2.3.0 push before? It wasn't build for all archs?
