### ISSUE TITLE
Help Wanted: test DSM 6 support in spkrepo - Python & SQLAlchemy

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#2991]
Patches have been added in spkrepo application - running online packages repository https://synocommunity.com/packages - for DSM 6 support, but it lacks testing.

Diaoul running production complains about CPU usage. My hypothesis is lack of indexes to speed up database requests when DSM connects to repository.

Any contributor with Python competencies, and even better SQLAlchemy, may help. Here is a starting point task list:
- build and start application, see https://github.com/ymartin59/spkrepo/blob/updates-dsm6/README.rst
- publish some packages for testing into local repository
- register it into DSM 5.2 and/or DSM 6.1
- log or profile SQL activity
- propose indexes for SQLAlchemy

A Dockerfile to build Docker image with spkrepo application may be interesting too.

Thank you in advance for your help

**Comment by Safihre** [comment]
Ah I missed this one. So the @Dr-Bean changes already make it DSM6 compatible, it is just too CPU-heavy?
Does it need a DSM-system to test, or just calling `http://localhost:5000/nas` is the same as a DSM system would do?

**Comment by ymartin59** [comment]
Thanks for helping. Do not hesitate to submit PR with fixes targeting branch `updates-dsm6`
https://github.com/ymartin59/spkrepo/commits/updates-dsm6

**Comment by m4tt075** [comment]
@GuillaumeSmaha Hi! Please excuse my direct approach. I know you have not been too active on spksrc recently, but we are looking for help with finally getting DSM6+ support off the ground. Getting spkrepo up and running is probably the last significant bottleneck we are facing. If I remember correctly, you might have the skills to help us here. Would you be able and willing to do so?

**Comment by Safihre** [comment]
@ymartin59 besides server loads being heavy, is there something really stopping the initial deployment of DSM6 support to the server?
Would it help if we (SABnzbd) donate? Or it's not really a financial issue? 

With your new spk service support, it seems really close to getting the first fully functioning DSM5/6 packages out.

**Comment by cytec** [comment]
@SynoCommunity/developers just a guess into the blue but... could it be that the CPU usage increases because there are way more Devices with DSM 6 out there? so it's not really the new code but just a general increase in requests?

**Comment by ymartin59** [comment]
In fact to avoid too much impact on system (and have a way to rollback), @Diaoul proposal is to deliver new version as Docker image to include recent python and libraries and connect to existing postgresql database

**Comment by ymartin59** [comment]
@Diaoul Target `publish-arch-x64-5.2` fails to upload `mosquitto` package from current `master`... whereas all other architectures are uploaded properly. Only information I have is `502 Bad Gateway`, even if I guess it comes from architecture alias list in `INFO`, may you please review `spkrepo` logs to point me what is wrong ? Last tentatives:  `Sun, 24 Dec 2017 14:31:12 GMT` and `Wed, 27 Dec 2017 10:16:28 GMT`.
Thank you in advance for your help

**Comment by Diaoul** [comment]
Sadly not very helpful without application logging...

> 2017/12/27 11:16:28 [error] 588#0: *139736702 upstream prematurely closed
connection while reading response header from upstream, client:
188.154.215.204, server: api.synocommunity.com, request: "POST /packages
HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi/app/spkrepo/socket:", host:
"api.synocommunity.com"

2017-12-27 11:17 GMT+01:00 Yves Martin <notifications@github.com>:

**Comment by ymartin59** [comment]
OK so I really have to dive into `spkrepo` to reproduce that issue locally, confirm it is fixed with @Dr-Bean patches... and get it deploy as Docker image on your server.

**Comment by hgy59** [comment]
this is related to spkrepo and should be solved there, if still relevant.
