### ISSUE TITLE
Syncthing v0.14.40 installed, but Package Center still reports 0.14.21

### ISSUE THREAD

**Issue by stephanvierkant** [SynoCommunity/spksrc#2992]
### Setup
_Package Name:_ Syncthing 
_Package Version:_ v0.14.40 / 0.14.21-10

_NAS Model:_ DS216play
_NAS Architecture:_ STM Monaco STiH412
_DSM version:_ DSM 6.1.4-15217

### Expected behavior
Package center should report right version (v0.14.40) so Syncthing-Inotify can be installed (requires 0.14.23).

### Actual behavior
Package center reports 0.14.21-10 installed, but the Syncthing web interface reports v0.14.40.

**Comment by cytec** [comment]
well... the spk version can differ from the version installed if you use syncthings internal updater. the last spk version of syncthing is 14.30 so you should be able to update the spk via package center, install syncthing-inotify and update syncthing over its build in updater.

That beeing said: @SynoCommunity/developers we should either change the version to something other then upstream (like we do for most python SPK's) or disable the internal updater and publish SPK's to avoid this kind of confusion in the future. Any thoughts?

**Comment by stephanvierkant** [comment]
Just removed Syncthing completely, but it still says `0.14.21-10` is the newest version.

**Comment by cytec** [comment]
uhm... https://synocommunity.com/package/syncthing shows `0.14.23-12` as actual version. seems like the last update wasn't published... also your arch is missing might be the reason why you cant see that version (`0.14.21-10` was compiled for monaco) ...

**Comment by stephanvierkant** [comment]
Aha, that explains why I don't get an update. Any idea why it isn't published for my arch?

**Comment by cytec** [comment]
Nope might be because the last one who published the last SPK did miss to compile it for your arch. anyways i've pushed the last version to the repo so it should work now ;)
