### ISSUE TITLE
Z shell (with modules) service will not start

### ISSUE THREAD

**Issue by gambit07** [SynoCommunity/spksrc#2993]
### Setup
_Package Name: Z shell (with modules)
_Package Version: 5.4.2-1

_NAS Model: DS214+/DS1517+
_NAS Architecture: Marvell Armada XP MV78230/Intel Atom C2538
_DSM version: DSM 6.1.3-15152 Update 7/DSM 6.1.4-15217

### Expected behavior
Package should start after selecting Run in Package Center

### Actual behavior
Package does not start. I don't get an error or notification as to why, but package will not start on either device and status always shows 'Stopped'.

### Steps to reproduce
_1. Open Package Center
_2. Download/Install Z shell (with modules)
_3. Select Run from package dropdown

**Comment by ymartin59** [comment]
From my point of view, the bug is that "zsh" is declared as startable package, as there is nothing to start... I will fix that at next update.

**Comment by ymartin59** [comment]
On DSM 6, "startable=no" option is deprecated and it is required to add "ctl_stop=no", to prevent package center to propose run/stop actions on such a non-startable package

**Comment by gambit07** [comment]
Thanks for the update. Unfortunately, I can't get the package to work through Task Scheduler. If I try to use a command, I get the output 'command not found'. Any thoughts?

**Comment by ymartin59** [comment]
Fixed and published
