### ISSUE TITLE
LiveCode Community Server

### ISSUE THREAD

**Issue by JohnAllijn** [SynoCommunity/spksrc#2994]
Name: LiveCode Community Server

Description: 

LiveCode is a programming-language with IDE (that runs on a desktop) that lets you write applications. One application can be deployed, built for, Mac/Windows/iOS/Android and Linux without any major adjustments in the code. The code is perfect for beginners. Easier than basic to get started with, but almost as powerful as Swift when it comes to writing applications for desktop and mobile devices. 
A while ago the software got an open-source ('Community') version, published with a GPL license. 
One part of LiveCode is LiveCode Community Server. This server version is a bit different than the normal LiveCode application. It runs, like PHP, on a server and is ideal for making backend applications. It can interface with databases and is, like PHP embedded in HTML. 
I would like to request a Synology package for this server-version of Livecode, so that I can build a backend for my mobile apps in the same language as my apps are written. 
Thank you for considering this request!

General websites: Livecode.com (commercial version) and Livecode.org (opensource version)
Downloads at: http://downloads.livecode.com/livecode/

Software documentation: http://livecodestatic.com/downloads/livecode/9_0_0/LiveCodeNotes-9_0_0_dp_10.pdf

Build/Installation documentation: http://livecodestatic.com/downloads/livecode/9_0_0/LiveCodeNotes-9_0_0_dp_10.pdf

Source code: https://livecode.org/contribute/

License:  General Public License (GPL), version 3.

**Comment by ymartin59** [comment]
Source code at GitHub: https://github.com/livecode/livecode
To be honest, it is far from our priorities to support additional software stack - knowing we already have Python, Perl, PHP, Erlang, Go, Mono stack and applications to maintain...
One day, it may change if a LiveCode application is interested to run on Synology.

**Comment by JohnAllijn** [comment]
Thank you!
It was worth a try :)

**Comment by hgy59** [comment]
There is a documentation on how to install LiveCode Server here: [How do I install Livecode Server with Apache 2.4 on a Synology with x86 CPU and DSM7](https://lessons.livecode.com/m/4070/l/1660935-how-do-i-install-livecode-server-with-apache-2-4-on-a-synology-with-x86-cpu-and-dsm7)
