### ISSUE TITLE
Testdisk Segfaulting on DS414

### ISSUE THREAD

**Issue by alesser** [SynoCommunity/spksrc#3003]
### Setup
_Package Name:_  **TestDisk**
_Package Version:_ **7.0-2**

_NAS Model:_   **DS414**
_NAS Architecture:_  **ARMADAXP**
_DSM version:_  **DSM 6.1.4-15217 Update 1**

### Expected behavior

The testdisk application should not segfault after installing.  Suggests that it's somehow being built for the wrong ARCH ?

### Actual behavior

```
ash-4.3# ./testdisk 
TestDisk 7.0, Data Recovery Utility, April 2015
Christophe GRENIER <grenier@cgsecurity.org>
http://www.cgsecurity.org
Segmentation fault (core dumped)

```

### Steps to reproduce

Install testdisk on a DS414 from the package center, and then login via SSH and run the binary installed at /volume1/@appstore/testdisk/bin/testdisk  to get the segfault.

#### Package log
```
N/A, package installs OK, no

```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
nothing here to report.
```

**Comment by alesser** [comment]
I've tried in vain to compile the package myself on a fresh ubuntu box, but i keep running into problems with libraries i'm not sure how to resolve.  I'm hoping a master can help me get this package running on the ArmadaXP arch that my DS414 and other NAS's use!

**Comment by alesser** [comment]
@cytec :  FYI, you are marked as the original contributor here :)

**Comment by ymartin59** [comment]
I have prepared an update of "disk utils" package which contains testdisk. As I tried to update "screen" too, I faced troubles with ARM platforms...

**Comment by cytec** [comment]
might be because it was build with the 5.2 Toolchains, if i remember correctly i've tested it on my ds211j and it did run fine back in the day...

**Comment by ymartin59** [comment]
@alesser I have rebuilt package as-is for DSM 6.1 and your arch. May you please test it and report feedback: http://dl.free.fr/j2ZE3KFMu

**Comment by alesser** [comment]
Link seems dead ?  I’ve recompiled with the 6.0.2 toolchain myself after finally figuring out a docker on Ubuntu setup , and did get it to work !

On Nov 25, 2017, at 2:45 PM, Yves Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


@alesser<https://github.com/alesser> I have rebuilt package as-is for DSM 6.1 and your arch. May you please test it and report feedback: http://dl.free.fr/j2ZE3KFMu

**Comment by ymartin59** [comment]
Great to know. I would have saved minutes if I was notified about it. No idea what is wrong with free, I do not care...

**Comment by alesser** [comment]
Only figured it out today myself !  Anyways does this mean it will be fixed for Everyone by default in the future ?

**Comment by ymartin59** [comment]
It should be in a future I expect as near as possible except if I died before

**Comment by julienbenjamin** [comment]
What about Photorec?

**Comment by cytec** [comment]
@julienbenjamin well `libjpeg` isn't in the requirements. 
If i recall correctly my main goal back in the day was to get testdisk working as this was the tool i needed, never really thought about `photorec`
