### ISSUE TITLE
FFmpeg not working with DSM 6.1.4 | DS Video 1468 | NAS; DS216J

### ISSUE THREAD

**Issue by Mindyourbeeswax** [SynoCommunity/spksrc#3004]
### Setup
_Package Name: FFMPEG
_Package Version: 3.1.2-2
_DS Video Version: 2.3.4-1468

_NAS Model: DS216J
_NAS Architecture: Marvell Armada 385 88F6820
_DSM version: 6.1.4-15217 Update 1

### Expected behavior
Playing HVEC.x265 encoded videos casted to a Chromecast Ultra from the DS video app on IOS.

### Actual behavior
HVEC.x265 encoded videos cannot play being casted to a Chromecast Ultra - or being directly played from the browser.

### What i have tried so far
1. Downgrading to DS VIDEO 1468 (as recommended here: https://github.com/SynoCommunity/spksrc/issues/2952#issuecomment-337214013 ) - download link here: https://usdl.synology.com/download/Package/spk/VideoStation/2.3.4-1468/
2. Downloading FFmpeg from here: https://guillaume.smaha.net/syno/ (armada38x-6.0_3.1.2-2.spk) 
3. Downloading FFmpeg from here: https://nunobhorta.com/enable-ffmpeg-dts-synology-video-station/ 
I cannot download from the Syno repo, as the app is not showing up for me - as shown here: https://imgur.com/a/B5bxW (i have tried to refresh).

Here is a sample i have tried with (besides my own content): http://video.webmfiles.org/video-h265.mkv

Thanks a bunch in advance. Let me know if any other information is required!

**Comment by Mindyourbeeswax** [comment]
## Just tried this with no luck
1. Deleted all previous versions of DS video and FFmpeg -> and restarted the NAS. 
2. Installed DS video (without starting the service) from here: https://usdl.synology.com/download/Package/spk/VideoStation/2.3.4-1468/ 
3. Restarted the NAS. 
4. Installed FFmpeg 3.3.3-7 using the link: http://dl.free.fr/getfile.pl?file=/C7oZSoFQ 
(from this post: https://github.com/SynoCommunity/spksrc/issues/2975 ). 
5. Restarted the NAS, and then started the DS video service.                                                                     
6. Tested with my own HVEC.X265 content, and the sample here: http://video.webmfiles.org/video-h265.mkv

Do i need to reset my NAS device completely? **ANY HELP AT ALL is much appreciated!**

**Comment by cytec** [comment]
VideoStation __does not__ support hvec.x265 codec.
Since VideoStation comes with it's own ffmpeg version, i don't think installing any other ffmpeg will make a difference... you might "overwrite" the provided binary with another one but i don't recommend to do that!

Since you've already found and linked the other issue, why create a new one instead of posting in the one that's already there?
