### ISSUE TITLE
how do i start the LINKS package please ? 

### ISSUE THREAD

**Issue by sithlord68** [SynoCommunity/spksrc#3005]
Hi,

The LINKS package is installed and running, but I find no way to use it...

Can someone please help me ?

I have DSM 6.1.4-15217 Update 1.

NAS Model: DS214Play

Plase help. I am not a unix specialist, sorry... 

Regards,
Pascal

**Comment by piwi82** [comment]
Take a look at the official website : http://links.twibright.com/user_en.html#subch-browser_calibration
