### ISSUE TITLE
TVHeadend crashes instantly when configuring or leaving GUI

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#3006]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Tvheadend
_Package Version:_4.2.4-11

_NAS Model:_DS715
_NAS Architecture:_Alpine
_DSM version:_6.1.4-15217 Update 1

### Expected behavior
Run normal without issues.

### Actual behavior
Package installed and started configuring but suddenly package has stopped.
Restarted package and continued configuring and again it crashes.
When package runs all is fine but when you browse to TVHeadend GUI and close browser it crashes again it crashes after a few minutes.
When you schedule a recording and it starts , it crashes.
It mostly seems to happen when you leave GUI (browser independent)

### Steps to reproduce
Just switch bewteen different browser windows during configuration.
When it crashes, cleanup var folder and add superuser file there to start from scratch and repeat configuration.

#### Package log
Not available , needs to be configured in Configuration -> Debug

TVHeadend itself replies with:
There seems to be a problem with the live update feed from Tvheadend. Trying to reconnect...

#### Other logs
root@DS715:~# tail -f /var/log/synopkg.log
2017/11/22 11:08:35     start tvheadend 4.2.4-11 End unload apparmor ret=[0]
2017/11/22 11:08:35     start tvheadend 4.2.4-11 Begin pre-load apparmor
2017/11/22 11:08:35     start tvheadend 4.2.4-11 End pre-load apparmor ret=[0]
2017/11/22 11:08:35     start tvheadend 4.2.4-11 Begin start-stop-status start
Starting Tvheadend ...
/usr/local/tvheadend/bin/tvheadend: /lib/libstdc++.so.6: no version information available (required by /usr/local/tvheadend/lib/libx265.so.130)
/usr/local/tvheadend/bin/tvheadend: /lib/libstdc++.so.6: no version information available (required by /usr/local/tvheadend/lib/libx265.so.130)
/usr/local/tvheadend/bin/tvheadend: /lib/libstdc++.so.6: no version information available (required by /usr/local/tvheadend/lib/libx265.so.130)
2017/11/22 11:08:35     start tvheadend 4.2.4-11 End start-stop-status start ret=[0]
2017/11/22 11:08:35     start tvheadend: start version 4.2.4-11 successfully, result 0

**Comment by m4tt075** [comment]
@schumi2004 The version on the repo is for 5.2. You will find 6.1 builds here if you want to give it a try:
https://www.dropbox.com/sh/jr7732yrwcxa2gr/AACZUsii82FTExVmTTb3SSVZa?dl=0
Or have you used a 6.1 version already?

**Comment by schumi2004** [comment]
@m4tt075 what's the difference with 6.1 builds besides the toolchain used?
I did compile TVH myself some time ago but it did not make any difference.
This issue is there for a long time already and i think it only effects Alpine architecture.

Anyway, i will try your build this evening and see if it makes any difference.

**Comment by ymartin59** [comment]
@schumi2004 libstdc++ differs between DSM 5 and DSM 6 stacks. That is why a specific compilation for DSM 6 is required for ffmpeg and related packages

**Comment by schumi2004** [comment]
@m4tt075 
Sorry for my late reply but it seems your version doesn't crash (so far).
Will keep you updated if it changes.

**Comment by schumi2004** [comment]
@ymartin59 
Were can i find the source code to compile it myself?

**Comment by m4tt075** [comment]
@schumi2004 You can either take spksrc's master and cherry-pick the 6.1 toolchains from the dsm6 branch you need, or you take my branch, where I do just that:
https://github.com/m4tt075/spksrc/tree/master-6.1

**Comment by schumi2004** [comment]
Thanks @m4tt075 ,
More then a year now i'm struggling with this issue and it seems your package fixed it! ;)
And thanks @ymartin59 for explaining the differences 

I think we can close this for now, thanks again both.
