### ISSUE TITLE
ldap and ssh access not allowed

### ISSUE THREAD

**Issue by hdd** [SynoCommunity/spksrc#3008]
Hi guys, I would like to bring to your attention this issue:
https://wrgms.com/reverse-engineering-synology-openssh/

It seems that ldap users (or any which is not local to the machine) replace the shell with /sbin/nologin internally while trying to do the authentication. This result in a Permission error.

### Setup
_Package Name:_ LDAP
_Package Version:_ Latest

_NAS Model:_ DS612Play
_NAS Architecture:_ ARM
_DSM version:_ 6.2b

### Expected behavior
should be able login with ssh as ldap user

### Actual behavior
error as : Permission denied

### Steps to reproduce
_1._ create an ldap user
_2._ try to log in with ssh

other way :
_1._ ssh with an admin user
_2._ sudo -i to become root
_3._ su - ldapuser@ldap.domain

**Comment by ymartin59** [comment]
Hello. From my point of view, it is not an issue from any SynoCommunity third party package.
Please report to Synology forum to get any help about it, and confirm it may be a bug: https://forum.synology.com/

**Comment by hdd** [comment]
true sorry for the noise.
