### ISSUE TITLE
What is package availability based on?

### ISSUE THREAD

**Issue by Idus** [SynoCommunity/spksrc#3011]
Well, I finally got to upgrade from my DS412+ to a DS918+ - not only for the extra space - but to pass down the old one. My plan was also to go from SABnzbd to NZBget, from SickBeard to Sonarr and from CouchPotato to Radarr

However - all of these packages fom SynoCommunity are not available on my new DS918+. Neither the ones that I have been using or the ones that was planning on using.

Sure, I am truly out of my depth here since I am a very low-level user (read: naive and lack of knowledge) but if a package works on one Synology Intel platform - should it not be available on another?

Until then I have a very expensive black cube standing in the corner! ;)

Thank you for your time! :)

### Setup
_NAS Model: DS918+
_NAS Architecture: INTEL Celeron
_DSM version: 6.1.4-15217 Update 2

### Expected behavior
To show me the applications that I can see in my former NAS

### Actual behavior
Not seeing any of the applications that I want to use. :-(

**Comment by ymartin59** [comment]
Hello. Please refer to FAQ: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions
There is no SynoCommunity DSM 6 packages available in repository yet.
Sorry for that, working on it.

**Comment by Idus** [comment]
Hello again,

It still does not satisfy my curiosity... What makes the limits? A windows software works on several hardware as long as Windows works on the hardware. Why cannot a DSM software work on several hardware as long as DSM works on that hardware?

_[..]There is no SynoCommunity DSM 6 packages available in repository yet[..]_

...but I see several of them in the SynoCommunity on my DS412+ - that runs the latest DSM 6 - why can´t I see the packages on my DS918+ that runs the same version of DSM 6?

Follow-up question would be if I can run a generic Linux software distribution - that some developers provide of their software?

Sorry for nagging - but just curious to know if there is a way for me to at least experiment to get it to work - since my new NAS is useless without working software - so I gotto try! ;)

Thank you for your time!

**Comment by ymartin59** [comment]
I invite you to look for other "apollolake" related issues here and look for comments referring to "beta" packages delivered for testing. Other details are too long to explain.
Regards
