### ISSUE TITLE
no Transmission available for DS218Play (rtd1296) 

### ISSUE THREAD

**Issue by insane307** [SynoCommunity/spksrc#3012]
### Setup
Package Name: Transmission
Package Version: 2.92

NAS Model: DS218Play
NAS Architecture: rtd1296
DSM version: 6.1.4.

### Expected behavior
Transmission is available for download & install

### Actual behavior
there is no Transmission available for download & install

**Comment by ymartin59** [comment]
Hello. Please refer to FAQ: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions
There is no SynoCommunity DSM 6 packages available in repository yet.
Sorry for that, working on it.
