### ISSUE TITLE
[Package Request] ruTorrent (RTD1296 compilation)

### ISSUE THREAD

**Issue by Johnito** [SynoCommunity/spksrc#3016]
```
Name: ruTorrent
Description: SynoCommunty package providing rutorrent/rtorrent for Synology DSM 6.x

Website: https://github.com/Novik/ruTorrent
Software documentation: https://github.com/Novik/ruTorrent/wiki
Build/Installation documentation: https://synocommunity.com/package/rutorrent
Source Code: https://github.com/Novik/ruTorrent
```

Currently, rutorrent isnt available for newest Synology NASes using the RTD1296 arch. A few great contributors already compiled several packages (see [https://github.com/WodKa78/-syno-packages](https://github.com/WodKa78/-syno-packages) and [https://github.com/Safihre/spksrc/tags](https://github.com/Safihre/spksrc/tags))...

... _But_ it seems there is an issue with rutorrent compilation : https://github.com/SynoCommunity/spksrc/issues/2971#issuecomment-347190157

I barely undestand what this is about so i am not able to correct it myself, but ... i hope this helps !

**Comment by Safihre** [comment]
I fixed the compilation problem.
Maybe you can test?
https://github.com/Safihre/spksrc/releases/tag/curl-test2 (don't mind the name, it's really about rutorrent)

**Comment by Johnito** [comment]
Tested : It WORKS :-)

There's a Curl related error though : rtorrent says that "_rss : some functionalities may not be available. The web server cannot access to the external program : curl_". This doesnt prevent the software from being installed nor used. Maybe RSS wont work.

**Comment by Safihre** [comment]
Well, the curl still doesn't :o

**Comment by ymartin59** [comment]
@Safihre You said you fix compilation issue. May you please provide more information and if needed a PR with required changes. Thank you in advance

**Comment by Safihre** [comment]
Unfortunately my fix seems to only fix complete compilation, and not actually give a working curl based on comments above. 
Will have to dig deeper and get a testing system to resolve it I think.

**Comment by ymartin59** [comment]
It may be interesting to already have first steps with a "WIP" draft PR.

**Comment by Safihre** [comment]
Sure!
This would also help for `spk/python` since it depends on `pycurl` which also depends on `cross/curl`, which I had to disable to get `spk/python` to compile (@m4tt075).

**Comment by Safihre** [comment]
I worked on new DSM5/6 compatibility but got stuck, I did the basic work but need some help to figure out the right paths to config files etc. If you want, you can help me here: #3175.

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #2215 and maybe PR #3175.
