### ISSUE TITLE
Most packages not showing in Package Manager

### ISSUE THREAD

**Issue by bolhaskutya** [SynoCommunity/spksrc#3018]
- Only 26 packages are listed in the community tab of package manager, yet there are 101 packages listed on synocommunity.com
- DSM 6.1.4-15217 Update 2
- NAS DS918+
- Option: "Any publisher" (ticked)
- Option: "I want to see beta versions!" (ticked)
- Option: http://packages.synocommunity.com/ added to package source
- ruTorrent doesn't show up for example

**Comment by ymartin59** [comment]
Duplicates with #2945. Please follow that issue and comment if needed
