### ISSUE TITLE
transmission - pinging weird address

### ISSUE THREAD

**Issue by Sonophis** [SynoCommunity/spksrc#3020]
Hello

Transmission keeps pinging a weird website.

### Setup
_Package Name:_Transmission
_Package Version:_2.92-12 

_NAS Model:_DS415+
_DSM version:_6.1.4-15217 Update 2

### Actual behavior
Problem is not the package which is installed and working fine since a few months

Since the 11-21-2017 my router began to throw some trojan alerts every hour.
The router alert message is :
```
The following suspicious network event is dropped:

Event Type: A Network Trojan was Detected
Signature: ET CNC Feodo Tracker Reported CnC Server group 6
Severity: High
Source IP: 192.168.1.21 <- nas address
Destination IP: 163.172.81.35
```
I did a tcpdump and wireshark gave me some insight on the culprit :

Through it's peer port transmission keeps pinging the port 1337 on 163.172.81.35 which returns a phpMyAdmin login page.

I'm not extremely paranoiac but something pinging every hour a phpmyadmin login page on the 1337 port every hour seems fishy.

### Steps to reproduce
_1._Install transmission package from the SynoCommunity repo
_2._Run transmission
_3._wait for the weird ping to 163.172.81.35 every hour

Thank you for any insight, i stopped the package in the meantime.

**Comment by cytec** [comment]
ok, so i've installed transmission, started it and it run for almost 12 Hours now... still not a single ping to that given IP. 

i guess that might be a tracker or something? a quick trace provides a server sitting in france and yup it occures in several malware databases (fedotracker, abuseipdb etc)... a little bit of google and you'll get several hits ex: https://github.com/ngosang/trackerslist/blob/master/trackers_best_ip.txt#L17-L19

**Comment by Sonophis** [comment]
Hi

You're right, it' comes from one of the tracker.

In the meantime i've made some tests.

With the actual package installed : 
- stopped transmission and got not intrusion alert 
- running transmission without downloading anything and got no intrusion alert
- running transmission and launching a download gave me intrusion alerts which repeated every hour

Made a copy of the installed package for backup measure
Removed the package and cleaned the conf files etc.
Installed a brand new transmission package from the repository.

With the new package installed : same behavior as the previous one.

I'll keep monitoring the thing.

Since it seems it does not have anything to do with the package, i think this issue can be closed.

Thanks again
