### ISSUE TITLE
DS718+ Mosquitto

### ISSUE THREAD

**Issue by crispy78** [SynoCommunity/spksrc#3022]
_For new Package Requests, see the guidelines_  

### Setup
Package Name: Mosquitto
Package Version:

NAS Model: DS718+
NAS Architecture: Apollolake
DSM version: 6.1.4-15217 Update 2

I was wondering if Mosquitto would be made available for the DS718+?

**Comment by ymartin59** [comment]
@crispy78 I propose you to beta-test my DSM 6 experiments. Please try to install and run following package: http://dl.free.fr/hvTr3z4UT
In any case, please report content from log files in `/var/packages/mosquitto/target/var/`

**Comment by ymartin59** [comment]
Has been published. Please create new specific issue to report any trouble
