### ISSUE TITLE
DS218+ missing packages

### ISSUE THREAD

**Issue by EnigmaNL** [SynoCommunity/spksrc#3023]
I just got a shiny new DS218+ yesterday and one of the first things I did was add the SynoCommunity package source.

For some reason I am unable to see all packages, I've set the trust level to Synology and trusted publishers and checked beta but when I search for packages that should be on SynoCommunity I can't find them. I have updated to DSM 6.1.4-15217 Update 2 but no luck.

How can I make it show all packages that are on there? I want to install Sonarr!

This is all it's showing:
![packages](https://user-images.githubusercontent.com/8877533/33470874-d872fcb0-d66a-11e7-8afc-baae18736754.PNG)

Never mind, apparently the packages aren't available for this model. I installed them using Docker.

**Comment by Piero87** [comment]
Hi, I have the same problem, any news?
