### ISSUE TITLE
Do I understand this correctly?

### ISSUE THREAD

**Issue by Idus** [SynoCommunity/spksrc#3024]
Running a new DS918+ (Apollolake) - moving from a DS412+ that will be handed down to a friend.

So
NAS Model: **DS918+**
NAS Architecture: **Apollolake**
DSM version: **6.1.4-15217 Update 2** (latest per 2nd Dec, 2017)

However - it turns out that none of the SynoCom. packages I have been using on my DS412+ are available to the DS918+. :-/

In my question-threads how this is and by reading other threads - I am trying to figure out how this is and what I can do to get my DS918+ up and running with:

- **NZBget** (or **SABnzbd**)
- **Sonarr**
- **Radarr**

BUT - there seems to be a "**_speciall_**" issue with the new Apollolake-hardware that makes it even harder to make a package. Something about actually being written for DSM 6.x - even though many (most?) previously compiled packages works with it - they have been built by a DSM 5.x API (not well versed in programming, so might got this wrong).

SO, based on the feedback I got - do I understand this correctly if the conclusion is that 

> **I cannot really do anything to get this up and running on my DS918+ until these packages are re-compiled with a lot of extra effort than normally?**

 I barely understand how much time and effort it takes to do this - so if it needs to be done in a new way - I can understand that it will take considerably longer time before anything happens.

Thank you for the time and effort the authors do and the rest that helps out in the forums.

Cheers! :)

Guess a similar issue is:
#3022

**Comment by ymartin59** [comment]
Problem is not Apollolake hardware itself but online repository does not support DSM 6.x package yet. Please refer to https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support for details.

**Comment by Idus** [comment]
Is _"online repository"_ (no clue as to what it is) something that Synology is providing? Would it be useful if I bark up their tree about to get this available then? What exactly should I tell them to provide?

Thanx!

**Comment by ymartin59** [comment]
"online repository" is service running https://synocommunity.com/packages you registered in your DSM (well I hope so). See also #2991
