### ISSUE TITLE
problem with cross/glib compiling

### ISSUE THREAD

**Issue by bsdcpp** [SynoCommunity/spksrc#3034]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_  cross/glib
_Package Version:_ latest

_NAS Model:_ all
_NAS Architecture:_ all
_DSM version:_all

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ any spk depends on the cross/glib will cause problem when you want to compile it
_2._I find the cross/glib is indepent with native/glib, it works fine after remove native/glib depends
_3._some new autoconf program didn't support --host --build now, like qemu-2.10, shuld modify
     spksrc/mk/spksrc.tc.mk(I have no idea how to do this), qemu works fine with 
@echo TC_CONFIGURE_ARGS := --cross-prefix=$(TC_TARGET)-

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Safihre** [comment]
I can confirm that packages depending on `cross/glib` compile fine, at least with the DSM6.1 toolchains.
