### ISSUE TITLE
[Package Request] Update FlexGet

### ISSUE THREAD

**Issue by TheMile** [SynoCommunity/spksrc#3035]
I'd appreciate it if the FlexGet package was updated.  The present SynoCommunity package is v2.9.14-6, from February 2017, and the current version of FlexGet is v2.11.8.

https://flexget.com/ChangeLog

Thanks.

**Comment by bencheg** [comment]
Please!

**Comment by bolhaskutya** [comment]
Yes, please update Flexget!

**Comment by bolhaskutya** [comment]
It installs, but says failed to run the package service.
