### ISSUE TITLE
ffmpeg on DS216play crash (core dump)

### ISSUE THREAD

**Issue by Alkadia67** [SynoCommunity/spksrc#3037]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ffmpeg
_Package Version:_3.3.3-7

_NAS Model:_DS216play
_NAS Architecture:_
_DSM version:_DSM 6.1.4-15217 Update 2

### Expected behavior
Tell us what should happen
when I launch this command 
root@MaCnas:/volume1/homes/cam1/20160101# /usr/local/ffmpeg/bin/ffmpeg -i new.jpg video.mp4
or
/usr/local/ffmpeg/bin/ffmpeg -r 1/3 -pix_fmt yuv420p -i new.jpg video.mp4

### Actual behavior
Tell us what happens instead
root@MaCnas:/volume1/homes/cam1/20160101# /usr/local/ffmpeg/bin/ffmpeg -r 1/3 -pix_fmt yuv420p -i new.jpg video.mp4
/usr/local/ffmpeg/bin/ffmpeg: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.130)
/usr/local/ffmpeg/bin/ffmpeg: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.130)
/usr/local/ffmpeg/bin/ffmpeg: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.130)
ffmpeg version 3.3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.8.3 (crosstool-NG git+85622fd-dirty) 20140106 (prerelease)
  configuration: --target-os=linux --cross-prefix=/spksrc/toolchains/syno-monaco-5.2/work/arm-cortexa9hf-linux-gnueabi/bin/arm-cortexa9hf-linux-gnueabi- --prefix=/usr/local/ffmpeg --extra-cflags=-I/spksrc/spk/ffmpeg/work-monaco-5.2/install/usr/local/ffmpeg/include --extra-ldflags=-L/spksrc/spk/ffmpeg/work-monaco-5.2/install/usr/local/ffmpeg/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/spksrc/toolchains/syno-monaco-5.2/work/arm-cortexa9hf-linux-gnueabi/bin/arm-cortexa9hf-linux-gnueabi-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-optimizations --enable-pthreads --enable-gpl --enable-version3 --enable-nonfree --enable-fontconfig --enable-libass --enable-libbluray --enable-avresample --enable-libfdk-aac --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-openssl --disable-debug --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-static --disable-txtpages --arch=arm --disable-neon --disable-armv6 --disable-armv6t2 --disable-vfp --disable-armv5te --disable-yasm --disable-asm
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, image2, from 'new.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 8295 kb/s
    Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 640x480 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn, 25 tbc
File 'video.mp4' already exists. Overwrite ? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
Press [q] to stop, [?] for help
No pixel format specified, yuvj422p for H.264 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
[libx264 @ 0x18d6eb0] using SAR=1/1
[libx264 @ 0x18d6eb0] using cpu capabilities: none!
[libx264 @ 0x18d6eb0] profile High 4:2:2, level 2.2, 4:2:2 8-bit
[libx264 @ 0x18d6eb0] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'video.mp4':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuvj422p(pc), 640x480 [SAR 1:1 DAR 4:3], q=-1--1, 0.33 fps, 16384 tbn, 0.33 tbc
    Metadata:
      encoder         : Lavc57.89.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
Segmentation fault (core dumped)

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
There's no log on that directory
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
nothing related to ffmpeg

**Comment by m4tt075** [comment]
@Alkadia67 This is most likely because you are using a 5.2 package on a 6.1 system. DSM6+ support has not yet been fully implemented here (see Wiki, or other issue threads). 
I have compiled a `monaco` `ffmpeg` version with 6.1 toolchains for you. You will find it [here](https://www.dropbox.com/s/1a10fyc85yyyisf/ffmpeg_monaco-6.1_3.3.3-7.spk?dl=0). Install it manually and see if it fixes the issue. BUT: Report back on what you find, ok?

**Comment by Alkadia67** [comment]
Hi m4tt075,
I'm totally newbie on DSM and Synology NAS.
I test this package and than I'll feedback you.
Thanks for your help,

**Comment by Alkadia67** [comment]
Hi,
this new version for DSm 6 of ffmpeg seems to work fine. 
no issue at moment
Thanks

**Comment by m4tt075** [comment]
Very well. Thanks for your feedback. Please close this issue then and just open a new one if you should run into trouble in the future...
