### ISSUE TITLE
uMurmur package for DS3018xs

### ISSUE THREAD

**Issue by mikhnal** [SynoCommunity/spksrc#3041]
### Setup
Package Name: uMurmur
Package Version: v0.2.16-6

NAS Model: DS3018xs
NAS Architecture: broadwellnk
DSM version: 6.2-22259 beta

### Expected behavior
Please make a package for new model DS3018xs and CPU architecture broadwellnk.

### Actual behavior
Any current package is not working.

**Comment by hgy59** [comment]
@mikhnal Still looking for this?
I have built it with the 6.2-22259 toolchain. Can you test please?
download at:
https://ziba-systems.net/downloads/umurmur_broadwellnk-6.2_0.2.16-6.spk

**Comment by mikhnal** [comment]
Hi!
It works perfectly, thank you for the effort!

**Comment by ymartin59** [comment]
@hgy59 Not really a good idea as this package has not been ported to DSM 6 generic service support

**Comment by m4tt075** [comment]
Just created PR #3132 adding generic service support.

**Comment by m4tt075** [comment]
DSM6-compatible test packages are available [here](https://github.com/m4tt075/spksrc/releases/tag/umu-0.2.17) now. Please test and report back.

**Comment by ymartin59** [comment]
uMurmur has been published. Please report any trouble in new issue
