### ISSUE TITLE
Unable to run npm under chroot

### ISSUE THREAD

**Issue by khandelwalpiyush** [SynoCommunity/spksrc#3044]
Hi

I am trying to install homebridge on Synology DS214play running DSM v6.2 beta

I am following steps here https://medium.com/@gregwym/setup-homebridge-on-synology-nas-without-docker-f42edd174d0e

I have done the following

1) Added SynoCommunity as package source
2) Installed Debian Chroot via pkg manager
3) Installed Node.js v4 via pkg manager
5) SSH'd into Synology
6) when I run "npm install -g --unsafe-perm homebridge" as admin or root it fails as it can't find "make"
7) Then I run the command "/var/packages/debian-chroot/scripts/start-stop-status chroot" and prompt changes
8) When I run step 6 again - this time it can't find npm (located in /usr/local/bin/npm)

What is going on here and what am I doing wrong?

**Comment by khandelwalpiyush** [comment]
I think I understand the problem.. Node.js needs to be installed inside debian chroot.. the make install for it took 11 hrs.. but after that when i ran node / npm command it found it but returned nothing.. no errors .. just back to prompt

**Comment by ymartin59** [comment]
Debian chroot is dangerous to use on DSM 6. Users reported full data loss of them DSM after trying to install that package. So be careful.

**Comment by ymartin59** [comment]
From my point of view, debian-chroot is no longer maintain. Another issue #2793 concerns creation of NodeJS/NPM support to package node-based application
