### ISSUE TITLE
Git missing from package center

### ISSUE THREAD

**Issue by EsX77** [SynoCommunity/spksrc#3045]
Hi,
I'm trying to (re)install the Git package for my DS409+ (running DSM 4.2-3259), but the package is not showing up in the package center anymore. Is there an other way to install Git?

**Comment by BetaLeaf** [comment]
Same

**Comment by imjamiecrosby** [comment]
same 👍

**Comment by cytec** [comment]
DSM 4 isn't supported by the repo anymore for ~1.5 - 2 years now!
you might still be able to compile it on your own!

**Comment by ymartin59** [comment]
You should get tag `pre-dsm6` for higher chance of success: https://github.com/SynoCommunity/spksrc/releases/tag/pre-dsm6
