### ISSUE TITLE
Include Bluepy in Home Assistant

### ISSUE THREAD

**Issue by martijnvdwoude** [SynoCommunity/spksrc#3052]
Name: Bluepy
Description: Python interface to Bluetooth LE on Linux
Website: https://github.com/IanHarvey/bluepy
Software documentation: https://ianharvey.github.io/bluepy-doc/
Build/Installation documentation: https://github.com/IanHarvey/bluepy
Source code: https://github.com/IanHarvey/bluepy
License: GNU Public License

**Comment by ymartin59** [comment]
May you please point me what Bluetooth LE hardware is available for Synology hardware running DSM ?

**Comment by kenand1970** [comment]
Domotiz run on Synology, Miflora and Xiaomi LCD BT sensonsor requires bluepy.

**Comment by ymartin59** [comment]
Just re-open because I may include it for Home Assistant #3462 and https://community.home-assistant.io/t/some-sort-oft-bluetooth-gateway-possible/49723

**Comment by mreid-tt** [comment]
@ymartin59, just following up on this. Is the direction to have this included in Home Assistant as stated (in which case the label should change to `enhancement`) or should this revert to be a new package (in which case the label should change to `request`)?

**Comment by hgy59** [comment]
This issue is outdated. Latest version of bluepy (1.3.0) is allmost 5 years old and for Python <= 3.4.

Current Homeassistant package (2023.7.3-22) has a `bluetooth` integration and some related wheels installed
```
bluetooth-adapters==0.15.3
bluetooth-auto-recovery==1.2.0
bluetooth-data-tools @ file:///volume1/%40appstore/homeassistant/share/wheelhouse/bluetooth_data_tools-1.3.0-cp311-cp311-linux_x86_64.whl#sha256=333c3c348a317e697c51684a9297f4fd9a5ccfc24fc260f870d3a633ebc67aa1
home-assistant-bluetooth @ file:///volume1/%40appstore/homeassistant/share/wheelhouse/home_assistant_bluetooth-1.10.0-cp311-cp311-linux_x86_64.whl#sha256=8da6cf9953f68541976bfa80746e4bbe385316c7902c6a008d35bc069e392ee8
```

It seems to work (no missing dependencies) but I have no bluetooth device for verification.

The real problem will be to find a bluetooth adapter that works on DSM (7).
