### ISSUE TITLE
Synology DS118 Sonnar, Jackett and Mono Missing

### ISSUE THREAD

**Issue by UDSHQ** [SynoCommunity/spksrc#3056]
Hey Guys. Looks like the 2018 line of Synology NAS units haven't been added to the supported architecture for Sonnar, Mono and Jackett. Or at least the DS118 that is. 

### Setup
Package Name: Sonnar
Package Version: 20170106-9

Package Name: Mono
Package Version: 4.6.2.7-8

Package Name: Jackett
Package Version: 0.7.1483-4

NAS Model: Synology DS118
NAS Architecture: rtd1296
DSM version: 6.1.4-15217 Update 5

### Expected behavior
Applications normally show up for install.

### Actual behavior
The listed applications are not available for install from within the community resource.

**Comment by WodKa78** [comment]
I suggest to respect the [contributing guidelines](https://github.com/SynoCommunity/spksrc) as a search would have helped you also. Anyhow those packages are made available for offline installation [by Safhire](https://github.com/Safihre/spksrc/releases) and some others can be found [here](https://github.com/WodKa78/-syno-packages)

**Comment by UDSHQ** [comment]
Hey!

Sorry I went full blown enduser there and didn't search. Thank you so much.

**Comment by WodKa78** [comment]
Your welcome, i sugest to close the issue so the list stays clean ;)
