### ISSUE TITLE
[Syncthing] fails to start after system update to DSM 6.1.4-15217 Update 5

### ISSUE THREAD

**Issue by jkbecker** [SynoCommunity/spksrc#3058]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Syncthing
_Package Version:_ 0.14.30-13

_NAS Model:_ DS1517+
_NAS Architecture:_ ?
_DSM version:_ DSM 6.1.4-15217 Update 5

### Expected behavior
I've been running Syncthing 0.14.30-13 flawlessly for the last couple days, with no manual intervention. I was on DSM 6.1.4 Update 3.

### Actual behavior
After upgrading to DSM 6.1.4-15217 Update 5, the service won't start and fails a generic "Failed to run the package service" error in Package Center when I run it manually

### Steps to reproduce
_1._ update to DSM 6.1.4-15217 Update 5
_2._ (Syncthing not starting)
_3._ Attempt to start Syncthing in Package Center

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

There are no logs on this except the (irrelevant):
```
Level | Log | Date & Time | User | Event
-- | -- | -- | -- | --
Information | System | 2017/12/18 17:49:14 | origin | Package [Syncthing] has been successfully installed.
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by SirAce135** [comment]
Having same exact issue with NZBGET

**Comment by jkbecker** [comment]
Ok, so who could help with this? I'm really depending on my data sync setup... I'd fix it myself if I had any experience with synology packaging, but I've just owned the box for a couple of weeks now. It should be something pretty simple that prevents syncthing from running... and reading from @SirAce135 's comment, Synology seems to have put out an update that messes with more than one installs. Can I provide anything else that would facilitate the troubleshooting?

**Comment by michaelschufi** [comment]
Same problem here (but already with DSM version `DSM 6.1.4-15217 Update 1`)

`/var/log/messages` reads:

```
2018-01-10T17:51:58+01:00 myhostname [348517.143660] init: pkgctl-syncthing pre-start process (27133) terminated with status 1
2018-01-10T17:51:58+01:00 myhostname synoscgi_SYNO.Core.Package.Control_1_start[26619]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-syncthing][0xD900 privilege.cpp:60]
2018-01-10T17:51:59+01:00 myhostname synoscgi_SYNO.Core.Package.Control_1_start[26619]: service_initjob_action.c:27 InitJobStart failed, [0xD900 privilege.cpp:60]
2018-01-10T17:51:59+01:00 myhostname synoscgi_SYNO.Core.Package.Control_1_start[26619]: pkgstartstop.cpp:277 Failed to start pkgctl-syncthing (err=-1) [0xD900 privilege.cpp:60]
```

**Comment by jkbecker** [comment]
Reinstalling fixed it for me as well. Could this issue be prevented though?
