### ISSUE TITLE
rutorrent's mistake: rss with https problem

### ISSUE THREAD

**Issue by bsdcpp** [SynoCommunity/spksrc#3062]
We've got a depressing problem when we add rss url with ssl, it always faild.
Today I reported this to the rutorrent repo:[Rss with ssl problem found](https://github.com/Novik/ruTorrent/issues/1622#issuecomment-354431576)
at the end, the author give me the conclusion:
 
https://github.com/SynoCommunity/spksrc/blob/7eb99825da1496647c93178e3d895f5f5b293bb8/spk/rutorrent/src/installer.sh#L118

this Line should be 
```bash
-e "s|tempDirectory = null;|tempDirectory = '${INSTALL_DIR}/tmp/';|g" \
```

because the rutorrent config.php had tell us to add the slash
```php
$tempDirectory = '/usr/local/rutorrent/tmp';            // Temp directory. Absolute path with trail slash. If null, then autodetect will be used.
```

**Comment by Safihre** [comment]
Can you submit a PR for it maybe? Then it can be incorporated in the future development of the package :)

**Comment by ymartin59** [comment]
Update is pending: #2968
Will fix with switch to generic service support.

**Comment by alxlaxv** [comment]
I hope this will be fixed soon :)
Is it only when the value is not null?

**Comment by th0ma7** [comment]
New and update to `rutorrent` version 3.10 uploaded on https://synocommunity.com/package/rutorrent
