### ISSUE TITLE
Transmission : use Combustion Web UI

### ISSUE THREAD

**Issue by rroblik** [SynoCommunity/spksrc#3066]
Hi,

I asked myself after having installed Combustion Web UI from @Secretmapper : why to not use it as default web UI for our NAS ?

Please see https://github.com/Secretmapper/combustion ; it can be easily done !

Regards

**Comment by mreid-tt** [comment]
@rroblik with the release of Transmission v4, it seems that the interface looks very much like Combustion. Can this issue be closed now?

**Comment by mreid-tt** [comment]
Closing this longstanding issue due to a lack of recent updates.
