### ISSUE TITLE
Cloudflare captcha

### ISSUE THREAD

**Issue by Max13** [SynoCommunity/spksrc#3067]
### Setup
_NAS Model:_ R815+
_NAS Architecture:_ x86_64
_DSM version:_ DSM 6.1.3-15152

### Expected behavior
When I add the SynoCommunity repo, I expect it to be added in DSM

### Actual behavior
Instead, I get the error message "Incorrect location"

### Steps to reproduce
_1._ Add a repo location

### Other info
My idea is that it's because of Cloudflare captcha.

I live in Congo and I'm the CTO in a Hotel, so the IP is shared between all the customers. Everytime we try to view a cloudflare protected website, we are redirected to a captcha, which isn't an issue itself, but when I add `http://packages.synocommunity.com/` as the location repository to our NAS, it says "Incorrect location", and I wonder if it's not because the NAS is hitting the captcha and obviously can't pass it.

Is there a way to check if I'm correct, and if so, a way to still add the repo?

**Comment by Diaoul** [comment]
Thanks for the report and analysis. I didn't know Cloudflare put Captcha on their websites... This could explain a lot of similar issues.
For now there is no way to bypass Cloudflare as it absorbs a lot of the requests.

Ideally I want to move to containers on the cloud but we're not there yet.

**Comment by Max13** [comment]
The question could be, is the repo really using http? Because cloudflare (for untrustworthy IPs) is showing captcha obviously only on http.

If i could use a repo using FTP (for instance), it would bypass the captcha.

--
Cordialement, Adnan RIHAN

GPG: 5675-62BA (https://keybase.io/max13/key.asc)
⇒ If you are not using GPG/PGP but want to send me an encrypted e-mail: https://encrypt.to/0x567562BA.
________________________________
