### ISSUE TITLE
compile glib with pcre only for certain package

### ISSUE THREAD

**Issue by Vancion** [SynoCommunity/spksrc#3069]
Hi, I am trying to compile open-vm-tools and encountered a problem that could be solved if I compile cross/glib/ with --with-pcre. However, I do not want to edit cross/glib/Makefile directly since it could affect other packages depend on cross/glib/. How should I edit my Makefile so that I could add --with-pcre for glib for open-vm-tools package only? Thank you.

**Comment by m4tt075** [comment]
I would not expect breakage of other packages if you enabled the `pcre` option in the `glib` cross-package. Just amend the `glib` cross-package by adding that option and - if needed - the dependency to `pcre`, ensure that `cross/glib` still compiles for all platforms, and add those changes to your PR as a separate commit. That should be all that's needed. Good luck!

**Comment by Safihre** [comment]
@Vancion Could you maybe explain what you added? I see in the [docs](https://developer.gnome.org/glib/stable/glib-building.html) that it needs an option, so either: `--with-pcre=system` or `--with-pcre=internal`. By default it will use `internal`.
