### ISSUE TITLE
jackett wont start (rtd1296)

### ISSUE THREAD

**Issue by kianrafiee** [SynoCommunity/spksrc#3071]
### Setup
_Package Name:_ Jackett
_Package Version:_ 8.490

_NAS Model:_ DS218play
_NAS Architecture:_ rtd1296
_DSM version:_ 6.1

newly installed jackett package for rtd1296 from @Safihre repo will not start. it was starting fine yesterday and updated. but now it wont start. not sure if there was a jackett update yesterday that broke it

**Comment by ymartin59** [comment]
Related to #3070

**Comment by m4tt075** [comment]
@kianrafiee I would re-install the package from @Safihre 's repo again, without removing your installation. This should "downgrade" your package again. If it works, it might have been the update. If not, it would be something else. At least you will get some certainty on the root cause...

**Comment by kianrafiee** [comment]
Yep I reinstalled and all seems well now. Not sure what happened. Other people seem to have had the same issue so I'm wondering if it's something that will be ongoing.

**Comment by jkbecker** [comment]
Sounds related to #3058

**Comment by kianrafiee** [comment]
I was on update 1 or 2 when this was happening and then resolved.
