### ISSUE TITLE
Deluge package not shown

### ISSUE THREAD

**Issue by tassadar81** [SynoCommunity/spksrc#3074]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Deluge
_Package Version:_ any

_NAS Model:_ DS218play
_NAS Architecture:_ Realtek RTD1296 SoC
_DSM version:_ DSM 6.1.4-15217 Update 5

### Expected behavior
I've added the http://packages.synocommunity.com/ as package source and enabled the beta versions but the deluge package doesn't shows on comunity section of packet manager

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by kianrafiee** [comment]
DSM6 hasn't been yet supported for our NAS. I have the same DS218play. You'll have to build the package yourself(which can be tedious your first time) or find someone that has built it. Also make sure there aren't any issues with Deluge in this repo as that may prevent you from even getting to use it. I don't have time to build it myself to let you try, sorry.

**Comment by tassadar81** [comment]
Thanks, i could give it a try... but there's any guide to build the package myself?

**Comment by kianrafiee** [comment]
Your staring at it :) This repo's main page shows you how to build packages. Let me warn you, its going to take you a few hours so I'd advise to do it when you have lots of free time like on the weekend.

**Comment by Safihre** [comment]
Test-package available in #3818.
In case of problems, please post:
`/volume1/@appstore/deluge/var/delug.log` and
`/volume1/@appstore/deluge/var/delug_install.log`

**Comment by tassadar81** [comment]
Safihre, during install it ask me for python 2.7.6-8 but i've installed both python's packages from packet manager. I'm not sure how to reach the logs from file station... i'll check from ssh when i return home

**Comment by Safihre** [comment]
You should also install the Python listed in that post, it's a newer version.

**Comment by tassadar81** [comment]
Ok i was able to install python and deluge but during deluge start at the end of installation i had a failure. Tried to watch on log centre but it doesn't show anything. Guess i've to check through ssh

**Comment by tassadar81** [comment]
Safihre i guess there's something to fix here, the installation corrupted the permission over filesystem. Not only for the directories chosen for deluge but some system's too. Now i can't update any configuration on DSM control panel. Hope i can fix in someway otherwise i have to reinstall again

**Comment by Safihre** [comment]
Could you tell what's happening? As in what permissions were set on which folders?
You should be able to see this through ssh. 
This is very unfortunate..

**Comment by tassadar81** [comment]
Safihre i've investigated more and the my report about system permission is wrong. I was thinking about that because the permission of the working directories was corrupted (i choose /volume1/public/torrent where to move the complete file and /volumne1/public/download where to download the torrent files) and changes to configurations in DSM control panel didn't save with a generic error (can't save...).
The real problem was the the connection to the VPN died and nothing notice that, even in the connections settings was reported as active.

Anyway i can confirm that the permissions on working directory were set with 000 preventing access to that files. I was able to change this with a sudo chmod 755. I'll check installations error log late today.

Sorry for the partial wrong report

**Comment by tassadar81** [comment]
Here the logs

[deluge.log](https://github.com/SynoCommunity/spksrc/files/1732054/deluge.log)
[deluge_install.log](https://github.com/SynoCommunity/spksrc/files/1732055/deluge_install.log)

**Comment by Safihre** [comment]
@tassadar81 I see in the logs that `sc-download` was given permissions on `/volume1/public/downloads`.
But you found that Deluge was not able to access the data?
(linux permissions are semi-separate from Synology permissions, which makes it very complicated)

**Comment by tassadar81** [comment]
@Safihre honestly i didn't know that Synology permissions and linux are semi-separated... Can you explain this better or just link a url where this is explained?
What i found after installation is that /volume1/public/ and all the sub-folders had the permissions set to 000

**Comment by Safihre** [comment]
That indeed sounds like Synology permissions doing their thing.
I am myself not even sure how it works, but somewhere it stores the "ACL" information that links files/folders to Synology users and groups. 
What's more important for us is to know if it actually allows Deluge to touch the files? Or you only started Deluge after doing the `chmod`? In theory the Synology permissions should be more important than linux ones.

**Comment by Safihre** [comment]
This problem was indeed caused by our installer, the new installer in #3138 now handles permissions properly so it doesn't result in `000` anymore!
