### ISSUE TITLE
wallabag fails to install

### ISSUE THREAD

**Issue by ilakast** [SynoCommunity/spksrc#3081]
### Setup
Package Name:wallabag
Package Version:2.2.3-2

NAS Model:DS216j
DSM version:6.1.4-15217 Update 5

### Expected behavior
I have Web Station, PHP 5.6 and MariaDB 5 installed
I have checked all modules under Web Station > PHP Settings > Extensions

### Actual behavior
Wallabag fails to install

#### Package log
Installing wallabag...

Step 1 of 4. Checking system requirements.
+------------------------+--------+--------------------------------------------------------------------------------------+
| Checked                | Status | Recommendation                                                                       |
+------------------------+--------+--------------------------------------------------------------------------------------+
| PDO Driver (pdo_mysql) | ERROR! | Database driver "pdo_mysql" is not installed.                                        |
| Database connection    | ERROR! | Can't connect to the database: An exception occured in driver: could not find driver |
| Database version       | OK!    |                                                                                      |
| curl_exec              | ERROR! | You need the curl_exec function activated                                            |
| curl_multi_init        | ERROR! | You need the curl_multi_init function activated                                      |
+------------------------+--------+--------------------------------------------------------------------------------------+

                                                                               
  [RuntimeException]                                                           
  Some system requirements are not fulfilled. Please check output messages an  
  d fix them.                                                                  
                                                                               

Exception trace:
 () at /volume1/web/wallabag/src/Wallabag/CoreBundle/Command/InstallCommand.php:166
 Wallabag\CoreBundle\Command\InstallCommand->checkRequirements() at /volume1/web/wallabag/src/Wallabag/CoreBundle/Command/InstallCommand.php:62
 Wallabag\CoreBundle\Command\InstallCommand->execute() at /volume1/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /volume1/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:853
 Symfony\Component\Console\Application->doRunCommand() at /volume1/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:200
 Symfony\Component\Console\Application->doRun() at /volume1/web/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /volume1/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /volume1/web/wallabag/bin/console:29

wallabag:install [--reset] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

#### Other logs
php56 -m gives:
[PHP Modules]
Core
ctype
date
dom
ereg
fileinfo
filter
hash
json
libxml
mbstring
mhash
mysqlnd
pcntl
pcre
PDO
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

php -m gives:
[PHP Modules]
bcmath
bz2
Core
ctype
curl
date
dom
ereg
filter
hash
iconv
json
ldap
libxml
mbstring
mcrypt
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
syno_compiler
xml
xmlreader
xmlwriter
zip
zlib

**Comment by Safihre** [comment]
Package needs updating for proper DSM6 support, tracked in #3113.
