### ISSUE TITLE
DS418j missing git package needed for CouchPotato Mylar

### ISSUE THREAD

**Issue by mreillyorg** [SynoCommunity/spksrc#3082]
### Setup
_Package Name:_ Git
_Package Version:_ any

_NAS Model:_ DS418j
_NAS Architecture:_ Realtek RTD1293 SoC
_DSM version:_  6.1.4-15217 Update 5
--

### Expected behavior
Git package can't be found. I think it is due missing

### Actual behavior
Git package can't be found. I think it is due to missing Realtek architecture.

### Steps to reproduce
_1._ Setup SynoCommunity in DSM
_2._ Search for Mylar
_3._ Click install
_4._ Says git missing

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
no mention of package
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
no mention of package
```

**Comment by ward0** [comment]
nothing found on github for 'CouchPotato Mylar' ??

**Comment by WodKa78** [comment]
[here](https://github.com/WodKa78/-syno-packages) you can find what i was able to compile for own use. All this comes with no support, i am not a programmer of any kind.

**Comment by suave123** [comment]
Do you have sonarr and radarr for apollolake as well?

**Comment by Safihre** [comment]
Please check here for all new packages:
https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-357008518

**Comment by Safihre** [comment]
Test packages for DSM6.1 and various architectures are available here #3138. They also include a new way of handling permissions.
We hope to publish the packages to the official repo soon and appreciate all testing and reports on the functioning of these packages.
