### ISSUE TITLE
tvheadend rtd1296 

### ISSUE THREAD

**Issue by kianrafiee** [SynoCommunity/spksrc#3083]
### Setup
_Package Name:_ tvheadend
_Package Version:_

_NAS Model:_ ds218play
_NAS Architecture:_ rtd1296
_DSM version:_ 6.1

There is a closed issue here that @m4tt075 posted a link to several architecture version packages of tvheadend for dsm 6.1. It did not include rtd1296. 

I was wondering if @m4tt075 or someone else could upload the rtd1296 package version?

**Comment by Safihre** [comment]
Closing this due to lack of feedback.
Test packages of Tvheaded for all platforms are available in #3138.
After final release packages will auto-update again via the official SynoCommunity repository.
