### ISSUE TITLE
testdisk on synology, lack of NTFS support ?

### ISSUE THREAD

**Issue by mraskin** [SynoCommunity/spksrc#3086]
Hi,

_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_testdisk
_Package Version:_7.0-2 (beta)

_NAS Model:_DS1515+
_NAS Architecture:_INTEL Atom C2538 2GB RAM
_DSM version:_DSM 6.1.4-15217 Update 5

### Expected behavior
I'm trying to copy some files from a disk which is no longer recognized correctly, but NTFS partition seems not supported in the testdisk version I've installed using package installation on the synology)

### Actual behavior
I'm getting this error message
Support for this filesystem hasn't been enable during compilation.
So looks like something was no activated when testdisk was compiled for synology

### Steps to reproduce
_1._plug a external Windows NTFS disk on the syno USB port 
_2._start testdisk, as root (/usr/local/testdisk/bin/tesdisk)
_3._select create
_4._select the disk on the USB port + Proceed
_5._select Intel
_6._select analyze
_7._select Quick Search => your partition should be green highlighted at this point, and type NTFS
_8._type on 'P' to list the files => you should get the error message

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

thanks and best regards.
Michel.

**Comment by hgy59** [comment]
fixed since synocli-disk v3.0-3
