### ISSUE TITLE
DS918+ missing SABnzbd, Sonarr and git/python

### ISSUE THREAD

**Issue by sibyy** [SynoCommunity/spksrc#3096]
SABnzbd and Sonarr are not available for the DS918+ running DSM 6.1.
Also git/python are missing and Couchpotato Custom will not install because of these prerequisites.

### Setup
_Package Name: SABnzbd, Sonarr, git, python
_Package Version: latest

_NAS Model: DS918+
_NAS Architecture: apollolake (x86_64)
_DSM version: 6.1.4

**Comment by Safihre** [comment]
We are testing the new packages, please see here for the links: https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-357008518.
Sonarr is coming, just give us a bit of time.
Close this issue and follow #2945 👍

**Comment by sibyy** [comment]
Got it.
Thank you
