### ISSUE TITLE
Home Assistant: How to configure it?

### ISSUE THREAD

**Issue by iBobik** [SynoCommunity/spksrc#3098]
### Setup
_Package Name:_ Home Assistant
_Package Version:_ 20150526-1

### Expected behavior
It tells me how to access and edit config files for HASS.

### Actual behavior
It has been installed, web interface is running, but no message or README how to configure it.

**Comment by Safihre** [comment]
SynoCommunity only provides the package, you should look at the official website of the package how to configure it.

**Comment by iBobik** [comment]
But where is website or repository of this package? (I do not mean homeassistant.io but maintainer of this package.)

**Comment by Safihre** [comment]
If the web interface is running, you can configure it from there right?
All this package does is make sure it's running, not the configuring.

**Comment by iBobik** [comment]
No, it was needed to configure a file what was created somewhere to enable web interface.



Honza Pobořil
https://honza.poboril.cz

**Comment by Safihre** [comment]
In that case I misunderstood.
Could you explain what file the package should create when installing so that it can be used right away?

**Comment by iBobik** [comment]
In configuration.yml there should be key http enabled.

Jan Pobořil
https://honza.poboril.cz/

19. 2. 2018 v 14:07, Safihre <notifications@github.com>:

**Comment by ymartin59** [comment]
I wrote a small documentation as a starting point, but it requires minimum Linux system skills you will have to acquire: https://github.com/SynoCommunity/spksrc/wiki/FAQ-HomeAssistant

**Comment by Safihre** [comment]
Let's make this part of #2525.

**Comment by ymartin59** [comment]
To anyone interested in Home Assistant, what are components you are interested ? Please comment in #3115
