### ISSUE TITLE
[tvheadend-testing] on synology crashes at playback from Kodi

### ISSUE THREAD

**Issue by BuzzDoet** [SynoCommunity/spksrc#3100]
**Setup:**
Package Name: tvheadend-testing
Package Version: 4.4.20180107

**NAS Model: ds412**
NAS Architecture: synology_cedarview_412+
DSM version: DSM 6.1.4-15217 Update 5

**Expected behavior**
I use Kodi to playback recorded programs. Up until the previous version of tvheadend that worked perfect. I was able to start/stop/pause/delete recorded programs.

**Actual behavior**
With the last version of tvheadend installed tvheadend crashes on the synology as soon as I try to playback a recorded program using Kodi.

**Steps to reproduce**
1. In Kodi (v17.6) go to Opnames (Recorded programs)
2. Choose an item from the list for playback
3. Kodi seems to be hanging (will continue later) and reports that the server cannot be reached.
4. Checking the synology reveals that tvheadend has been stopped.

Note: watching live programs works perfect, including pauze/resume.

**Package log**
Unfortunately I cannot find any  log file.

**Comment by Safihre** [comment]
@m4tt075 Do you maybe know what could be wrong?

**Comment by BuzzDoet** [comment]
@Safihre : this is a known bug in this version of  tvheadend-testing (Package Version: 4.4.20180107).
It is fixed in a newer version.
I'm now running 4.4.20180116 and that is working fine again.
