### ISSUE TITLE
Mosquito fails to start since update

### ISSUE THREAD

**Issue by andyfitter** [SynoCommunity/spksrc#3101]
_For new Package Requests, see the guidelines_  

### Setup
Mosquitto
1-4-14.8

3615
Intel X64
DSM 6.1.4-15217 Update 5

### Expected behavior
Updated Mosquitto to latest version via package manager, expected to restart without any intervention

### Actual behavior
Package remains 'stopped', restart does not fix.

### Steps to reproduce
Update from previous version

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

Insert the package log here

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
Sun Jan 14 22:25:39 GMT 2018
Starting mosquitto command /volume2/@appstore/mosquitto/sbin/mosquitto -d -c /volume2/@appstore/mosquitto/var/mosquitto.conf 

Insert log here
2018/01/14 11:20:45	upgrade mosquitto: begin to stop version 1.4.9-5
2018/01/14 11:20:46	upgrade mosquitto 1.4.9-5 Begin start-stop-status stop
Stopping Mosquitto ...
2018/01/14 11:20:47	upgrade mosquitto 1.4.9-5 End start-stop-status stop ret=[0]
2018/01/14 11:20:47	upgrade mosquitto 1.4.9-5 Begin unload apparmor
2018/01/14 11:20:47	upgrade mosquitto 1.4.9-5 End unload apparmor ret=[0]
2018/01/14 11:20:48	upgrade mosquitto: stop version 1.4.9-5 successfully, result 0
2018/01/14 11:20:48	upgrade mosquitto 1.4.9-5 Begin preupgrade
/volume2/@tmp/pkginstall/scripts/service-setup: line 18: type: service_preupgrade: not found
/volume2/@tmp/pkginstall/scripts/service-setup: line 18: type: service_save: not found
2018/01/14 11:20:49	upgrade mosquitto 1.4.9-5 End preupgrade ret=[0]
2018/01/14 11:20:49	upgrade mosquitto 1.4.9-5 Begin preuninst
2018/01/14 11:20:49	upgrade mosquitto 1.4.9-5 End preuninst ret=[0]
2018/01/14 11:20:49	upgrade mosquitto 1.4.9-5 Begin /bin/rm -rf /volume2/@appstore/mosquitto
2018/01/14 11:20:49	upgrade mosquitto 1.4.9-5 End /bin/rm -rf /volume2/@appstore/mosquitto ret=[0]
2018/01/14 11:20:49	upgrade mosquitto 1.4.9-5 Begin postuninst
2018/01/14 11:20:49	upgrade mosquitto 1.4.9-5 End postuninst ret=[0]
2018/01/14 11:20:49	upgrade mosquitto: Uninstall 1.4.9-5 successfully
2018/01/14 11:20:58	upgrade mosquitto 1.4.14-8 Begin preinst
/volume2/@tmp/pkginstall/scripts/service-setup: line 18: type: service_preinst: not found
2018/01/14 11:20:58	upgrade mosquitto 1.4.14-8 End preinst ret=[0]
2018/01/14 11:20:58	upgrade mosquitto 1.4.14-8 Begin /bin/mv -f /volume2/@tmp/pkginstall/package /volume2/@appstore/mosquitto
2018/01/14 11:20:58	upgrade mosquitto 1.4.14-8 End /bin/mv -f /volume2/@tmp/pkginstall/package /volume2/@appstore/mosquitto ret=[0]
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 Begin /bin/mkdir -p /var/packages/mosquitto
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 End /bin/mkdir -p /var/packages/mosquitto ret=[0]
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 Begin /bin/mv -f /volume2/@tmp/pkginstall/INFO /var/packages/mosquitto/INFO
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 End /bin/mv -f /volume2/@tmp/pkginstall/INFO /var/packages/mosquitto/INFO ret=[0]
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 Begin /bin/rm -rf /var/packages/mosquitto/scripts
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 End /bin/rm -rf /var/packages/mosquitto/scripts ret=[0]
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 Begin /bin/mv -f /volume2/@tmp/pkginstall/scripts /var/packages/mosquitto/scripts
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 End /bin/mv -f /volume2/@tmp/pkginstall/scripts /var/packages/mosquitto/scripts ret=[0]
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 Begin /bin/rm -rf /var/packages/mosquitto/conf
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 End /bin/rm -rf /var/packages/mosquitto/conf ret=[0]
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 Begin /bin/mv -f /volume2/@tmp/pkginstall/conf /var/packages/mosquitto/conf
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 End /bin/mv -f /volume2/@tmp/pkginstall/conf /var/packages/mosquitto/conf ret=[0]
2018/01/14 11:20:59	upgrade mosquitto 1.4.14-8 Begin postinst
delgroup: can't find mosquitto in /etc/group
deluser: 'sc-mosquitto' still has 'mosquitto' as their primary group!
2018/01/14 11:21:00	upgrade mosquitto 1.4.14-8 End postinst ret=[0]
2018/01/14 11:21:00	upgrade mosquitto 1.4.14-8 Begin postupgrade
/var/packages/mosquitto/scripts/service-setup: line 18: type: service_restore: not found
/var/packages/mosquitto/scripts/service-setup: line 18: type: service_postupgrade: not found
2018/01/14 11:21:01	upgrade mosquitto 1.4.14-8 End postupgrade ret=[0]
2018/01/14 11:21:02	upgrade mosquitto: begin to start version 1.4.14-8
2018/01/14 11:21:02	upgrade mosquitto 1.4.14-8 Begin pre-load apparmor
2018/01/14 11:21:02	upgrade mosquitto 1.4.14-8 End pre-load apparmor ret=[0]
2018/01/14 11:21:02	upgrade mosquitto 1.4.14-8 Begin start-stop-status start
Starting mosquitto ...
/var/packages/mosquitto/scripts/service-setup: line 18: type: service_prestart: not found
2018/01/14 11:21:02	upgrade mosquitto 1.4.14-8 End start-stop-status start ret=[0]
2018/01/14 11:21:03	upgrade mosquitto: start version 1.4.14-8 successfully, result 0
2018/01/14 11:21:03	upgrade mosquitto from 1.4.9-5 to 1.4.14-8 successfully
2018/01/14 11:21:03	upgrade mosquitto 1.4.14-8 Begin /bin/rm -rf /volume2/@tmp/pkginstall
2018/01/14 11:21:03	upgrade mosquitto 1.4.14-8 End /bin/rm -rf /volume2/@tmp/pkginstall ret=[0]
2018/01/14 22:16:41	start mosquitto: begin to start version 1.4.14-8
2018/01/14 22:16:42	start mosquitto 1.4.14-8 Begin start-stop-status stop
mosquitto is not running
2018/01/14 22:16:42	start mosquitto 1.4.14-8 End start-stop-status stop ret=[0]
2018/01/14 22:16:42	start mosquitto 1.4.14-8 Begin unload apparmor
2018/01/14 22:16:42	start mosquitto 1.4.14-8 End unload apparmor ret=[0]
2018/01/14 22:16:43	start mosquitto 1.4.14-8 Begin pre-load apparmor
2018/01/14 22:16:43	start mosquitto 1.4.14-8 End pre-load apparmor ret=[0]
2018/01/14 22:16:43	start mosquitto 1.4.14-8 Begin start-stop-status start
Starting mosquitto ...
/var/packages/mosquitto/scripts/service-setup: line 18: type: service_prestart: not found
2018/01/14 22:16:43	start mosquitto 1.4.14-8 End start-stop-status start ret=[0]
2018/01/14 22:16:43	start mosquitto: start version 1.4.14-8 successfully, result 0
2018/01/14 22:25:38	start mosquitto: begin to start version 1.4.14-8
2018/01/14 22:25:38	start mosquitto 1.4.14-8 Begin start-stop-status stop
mosquitto is not running
2018/01/14 22:25:38	start mosquitto 1.4.14-8 End start-stop-status stop ret=[0]
2018/01/14 22:25:38	start mosquitto 1.4.14-8 Begin unload apparmor
2018/01/14 22:25:38	start mosquitto 1.4.14-8 End unload apparmor ret=[0]
2018/01/14 22:25:39	start mosquitto 1.4.14-8 Begin pre-load apparmor
2018/01/14 22:25:39	start mosquitto 1.4.14-8 End pre-load apparmor ret=[0]
2018/01/14 22:25:39	start mosquitto 1.4.14-8 Begin start-stop-status start
Starting mosquitto ...
/var/packages/mosquitto/scripts/service-setup: line 18: type: service_prestart: not found
2018/01/14 22:25:39	start mosquitto 1.4.14-8 End start-stop-status start ret=[0]
2018/01/14 22:25:39	start mosquitto: start version 1.4.14-8 successfully, result 0

**Comment by ymartin59** [comment]
May you please copy content visible from "View Log" action in Package Center ?

**Comment by ymartin59** [comment]
May you also please report explicitly your DSM model and architecture name

**Comment by andyfitter** [comment]
DS3615xs - bromolow architecture.

View Log gives the following:

Sun Jan 14 23:29:23 GMT 2018
Starting mosquitto command /volume2/@appstore/mosquitto/sbin/mosquitto -d -c /volume2/@appstore/mosquitto/var/mosquitto.conf

**Comment by stelgenhof** [comment]
I have the same issue. After a little investigating, it turned out that the password file I used in my mosquitto configuration is no longer present:

```
1516001261: mosquitto version 1.4.14 (build date 2017-12-24 11:37:35+0000) starting
1516001261: Config loaded from /volume1/@appstore/mosquitto/var/mosquitto.conf.
1516001261: Error: Unable to open pwfile "/volume1/@appstore/mosquitto/etc/passwd".
1516001261: Error opening password file "/volume1/@appstore/mosquitto/etc/passwd".
```

Not sure how, but looks like my passwd file was deleted upon upgrading.

**Comment by andyfitter** [comment]
I can confirm that recreating/restoring the password file and restarting mosquito fixes the problem for me.

**Comment by stelgenhof** [comment]
Also I can confirm recreating the password file fixed the issue for me.

**Comment by ymartin59** [comment]
OK. May you please move password file in `var` (along side with `mosquitto.conf`) so that it is restored in upgrade process.

**Comment by stelgenhof** [comment]
@ymartin59 Sure! Can you tell which particular folder in /var these files should be stored? Or is any place fine?

Just a side note: I don't recall the configuration and password file where supposed to be in the /var directory. Was this always the case?

Cheers! Sacha

**Comment by ymartin59** [comment]
In fact, I recommend to store it in same directory where `mosquitto.conf` is - to avoid volume specific reference, please use: `/var/packages/mosquitto/target/var/`
My hypothesis is that package has never been updated on your system since you introduced password file...

**Comment by stelgenhof** [comment]
@ymartin59 Ok, will put the files there.

Strange thing is that I haven't done any particular odd: I've always updated the latest Mosquitto version via the Package Manager. In addition the configuration file that is used upon starting isn't in the directory you mentioned. See my log output from the Package Manager:

![screen shot 2018-01-15 at 20 25 57](https://user-images.githubusercontent.com/529544/34940390-b6cdbbfe-fa32-11e7-965e-51f83d67c9d7.png)

Before this latest upgrade, the only thing I've done was adding a password file in the same folder as the configuration was stored.

**Comment by ymartin59** [comment]
Yes it is the same directory as I mentioned.... as far as you follow Unix symbolic links.

**Comment by stelgenhof** [comment]
@ymartin59 Ah, I didn't notice there were symlinks :) Perfect!

**Comment by ymartin59** [comment]
Updated version is online.
