### ISSUE TITLE
Unable to install mosquitto 1.4.14-8

### ISSUE THREAD

**Issue by sjoswig** [SynoCommunity/spksrc#3103]
### Setup
_Package Name:_ mosquiotto
_Package Version:_ 1.4.14-8

_NAS Model:_ DS214play
_NAS Architecture:_ INTEL Atom CE5335
_DSM version:_ DSM 6.1.4-15217 Update 5

### Expected behavior
Installation works fine.

### Actual behavior
No error. Package did not install.

### Steps to reproduce
_1._ Search for package
_2._ Try to install *it is doing something*
_3._ Installation possible again

#### Package log
mosquitto directory not present.

#### Other logs
nothing mosquitto specific was logged.

**Comment by ymartin59** [comment]
I have DS214play too and it runs properly there. Is it a fresh install or update from previous version ? Please send `/tmp/mosquitto_install.log` you should find on system.

**Comment by sjoswig** [comment]
@ymartin59 I try a fresh installation. It says "Download" ... "getting installed" and then status is "Install" again. As mentioned in the above post there is no log file being created:

$ sudo find /tmp -iname *mosq* | wc -l 
$ 0

Yes, I have rebooted my Syno :-)

**Comment by ymartin59** [comment]
May you please inspect and report content of /var/log/messages and /var/log/synopkg.log just after installation trial

**Comment by piotr-tobolski** [comment]
I have the same issue. I see nothing related to mosquitto in `/tmp`. Nothing is added to `/var/log/synopkg.log` after installation trial and in `/var/log/messages` only one line is appended:
> 2018-01-16T13:05:44+01:00 Tobol-DS216 php: This package is broken.
I have DS216+ with latest stable DSM.

**Comment by kratz00** [comment]
I also have issues installing 1.4.14-8, upgrading from 1.4.9-5.

Like the others I could not find any hints in any of the log files. The only hint I found is that one in the webinterface:

`Failed to update "Mosquitto". The package file is corrupt. Please download it again or contact the package developer.`

**Comment by Elkorana** [comment]
Like kratz00 - Same to me

**Comment by gpgekko** [comment]
Same here as well. Can't find anything in the logs, clicking the update button gives the "package file is corrupt" message. Tried rebooting, removing the package and reinstalling, double checked the package source url, but still getting that message.

**Comment by radvanCZ** [comment]
The same problem for me.  I get "installation file is  corrupted"  message 
Nothing in /var/log/synopkg.log, /tmp/mosquitto_install.log doesnt exist . 

Model : DS212+
processor : MARVELL Kirkwood 88F6282
DSM version  :  DSM 6.1.4-15217 Update 5

**Comment by Heavy-Dee** [comment]
The same problem by installation.

Previous version was running.
Automatic update -> "installation file is corrupted"
Uninstall previous version, restart DS , new installation of mosquitto package ->FAIL
**_"Mosquitto" konnte nicht installiert werden. Die Paketdatei ist fehlerhaft. Bitte laden Sie die Paketdatei noch einmal herunter oder kontaktieren Sie den Entwickler des Pakets._**

Please fix the version or activate a previous version for download. (necessary for my openHAB)

Synology: DS216+II
DSM version : DSM 6.2-22259

**Comment by ymartin59** [comment]
Sorry for the inconvenience. I do not understand what is wrong. By the way, previous version is back online.
- Backup /var/packages/mosquitto/target/var/ content (your configuration files)
- Uninstall package
- Install again from repository
- Do not start service
- Restore configuration
- Start service

**Comment by ymartin59** [comment]
@Diaoul I have checked original mosquitto package on my disk and signed version on api.synocommunity.com server and archives I tested for evansport and x64 are installable and runnable.

I do not understand why users report corrupted packages. The only clue I have is strange file links in tar file:

```
tar tvf mosquitto.v8.f4458\[x86_64-x86-braswell-bromolow-cedarview-avoton-apollolake-broadwell-denverton-grantley\].spk 
-rw-r--r-- root/root   5182676 2018-01-13 23:33 package.tgz
-rw-r--r-- root/root       592 2018-01-13 23:33 INFO
drwxr-xr-x root/root         0 2017-12-24 12:37 scripts/
-rw-r--r-- root/root      1152 2018-01-13 23:33 scripts/service-setup
-rwxr-xr-x root/root      2986 2018-01-13 23:33 scripts/start-stop-status
-rwxr-xr-x root/root        73 2017-12-24 12:37 scripts/preupgrade
-rwxr-xr-x root/root        73 2017-12-24 12:37 scripts/postuninst
-rwxr-xr-x root/root      9905 2018-01-13 21:59 scripts/installer
-rwxr-xr-x root/root        73 2017-12-24 12:37 scripts/postupgrade
-rwxr-xr-x root/root        73 2017-12-24 12:37 scripts/preinst
-rwxr-xr-x root/root        73 2017-12-24 12:37 scripts/preuninst
-rwxr-xr-x root/root        73 2017-12-24 12:37 scripts/postinst
drwxr-xr-x root/root         0 2017-12-24 12:37 conf/
-rw-r--r-- root/root       391 2018-01-13 23:33 conf/privilege
-rw-r--r-- root/root        87 2018-01-13 23:33 conf/mosquitto.sc
drwxr-xr-x root/root         0 2017-12-24 12:37 conf/
hrw-r--r-- root/root         0 2018-01-13 23:33 conf/privilege link to conf/privilege
hrw-r--r-- root/root         0 2018-01-13 23:33 conf/mosquitto.sc link to conf/mosquitto.sc
-rw-r--r-- root/root      5036 2018-01-13 23:33 PACKAGE_ICON.PNG
-rw-r--r-- root/root     27929 2018-01-13 23:33 PACKAGE_ICON_256.PNG
-rw-r--r-- 0/0            1133 2018-01-13 23:34 syno_signature.asc
```

I wonder where these may come from. I am looking to produce archive without such links... Any hint ?

**Comment by Diaoul** [comment]
Is this specific to the one on the server or is your local one the same?

**Comment by ymartin59** [comment]
I listed files on server signed archive but links are present in both... And I probably found why it works on my DSM systems: my Package Center Settings Trust Level was "Any publisher". Conclusion: signature is invalid...
Just a question without checking first, is certificate expired ?

**Comment by ymartin59** [comment]
For links, I think I have also hint: `SPK_CONTENT` for `tar` command contains `conf` twice...

**Comment by ymartin59** [comment]
Version 1.4.14-9 has been published. I checked content and digital signature that prevented previous version installation (with corruption message you got)

**Comment by kratz00** [comment]
@ymartin59 I have just updated the package to version 1.4.14-9 successfully, thank you very much!
