### ISSUE TITLE
SABnzbd - can't see update 2.3.1 on DSM5 with DS1010+

### ISSUE THREAD

**Issue by kongomongo** [SynoCommunity/spksrc#3105]
Currently running DSM 5.2-5967 Update 6 on my DS1010+. I am currently running SABnzbd 2.3.0-32 from SynoCommunity and found that it has some bugs related to Direct **Unpacking**. I wanted to update to at least 2.3.1 to see if the bugs are fixed. Unfortunately I cannot see any updates (wether beta is enabled or not) beyond the currently installed 2.3.0.

I tried looking in the source of the package but I cannot figure out if theres now (opposed to whats written in the FAQ) a requirement for DSM6 to see the updated package? My arch x86_x64 should be supported.

I am clueless here. I can't find any info or maybe I am using the wrong search terms. Can someone help? Many thanks in advance.

PS: On my DS1010+ I cannot install DSM6 as it is not supported anymore.

**Comment by kongomongo** [comment]
any info missing that I should provide?

**Comment by kongomongo** [comment]
hmm seems like it is my arch x86? if i query http://packages.synocommunity.com/? with arch cedarview I get offered 2.3.1.

Unfortunately I still dont understand what it means

**Comment by kongomongo** [comment]
http://packages.synocommunity.com/?package_update_channel=stable&unique=synology_x86_1010%2B&build=15217&language=ger&major=6&micro=4&arch=x86&minor=1&timezone=Amsterdam&nano=5  === max 2.3.0

http://packages.synocommunity.com/?package_update_channel=stable&unique=synology_x86_1010%2B&build=15217&language=ger&major=6&micro=4&arch=cedarview&minor=1&timezone=Amsterdam&nano=5 === 2.3.1

**Comment by ymartin59** [comment]
Your system is declared as `x86` and this architecture has been forgotten when publishing 2.3.1.
Sorry for that but we are focused on DSM 6 package updates - SABnzbd update is waiting for Python minor fixes.
If you cannot wait for it few days, you can get `spk` file, unarchive with `tar xvf`, remove signature file `syno_signature.asc`, edit `INFO` to append `x86` to architecture list and repack everything again to install manually (with trust level to any publisher in settings)

**Comment by kongomongo** [comment]
Ahh, many thanks for your reply and the instructions. I was getting mad thinking what I could have done wrong. I will try and use your instructions for a workaround and happily wait for the official fix. Thanks again.

**Comment by Safihre** [comment]
Test packages for DSM6.1 and various architectures are available here #3138. They also include a new way of handling permissions.
We hope to publish the packages to the official repo soon and appreciate all testing and reports on the functioning of these packages.
