### ISSUE TITLE
Automatic updating in Package Center on DS214play

### ISSUE THREAD

**Issue by RicheeThree** [SynoCommunity/spksrc#3106]
First of all, thank you for all you do!

Second, on my DS214play, I am currently running ffmpeg v3.3.3-7 and looking for an updated package. I have successfully added the SynoCommunity apps to my server, so I see them in the Package Center. I'm just curious though: will I see updated versions of these apps when updates become available as I do with the other apps? Or will I have to manually update apps when the time comes?

**Comment by ymartin59** [comment]
Package Center will propose SynoCommunity package updates as soon as they are available online. We are currently building and publishing DSM 6 packages (recently git, python and mono has been published)

**Comment by RicheeThree** [comment]
Ok. Thank you very much, and thank you for your efforts! Keep up the great work!!!
