### ISSUE TITLE
SABNZBD/CouchPotato/Sickbeard won't start. Failed to run the package service. Python update issue?

### ISSUE THREAD

**Issue by Puntoboy** [SynoCommunity/spksrc#3107]
### Setup
_Package Name:_ Sabnzbd
_Package Version:_ 2.1.3-33

_NAS Model:_ DS1515+
_NAS Architecture:_ 
_DSM version:_ DSM 6.1.4-15217 Update 2

### Expected behavior
Package starts correctly

### Actual behavior
Error received - Failed to run the package service.

### Steps to reproduce
This morning there was an update for Python - to version 2.7.14-17. This required SABnzbd, CouchPotato and Sickbeard Custom to stop running which the update was installed. Once this has finished I noticed they did not restart and when I do this manually I receive the error "Failed to run the package service".

This could be completely unreleated to Python, but as they all need it to run, there was an update and it was fine before the update, it could be all related. 

I'm not at home currently and cannot access the DSM via SSH, I can only access the GUI so any additional logs I will get once I can connect.

**Comment by Futerix** [comment]
Same problem, aftar updating Python Deluge not working, other are working fine.

**Comment by Puntoboy** [comment]
I managed to get them all working again using this https://nzbusenet.com/sabnzbd-werkend-krijgen-op-dsm-6/

**Comment by TheConen** [comment]
Same problem for me, only with Deluge and Transmission. Basically, it seems, that after the Python update, no applications that rely on Python work anymore.

@Puntoboy Since most of us probably don't understand Dutch, would you mind translating that for us. Though the proper fix would probably be an update of the Python package, ASAP.

**Comment by jrac86** [comment]
The "fix" posted earlier has you change the package to run under the root user. After updating Python, I tried this with Deluge and it still would not start back up. The other packages like sonarr, radarr, and sabnzbd I already had running under the root user and they were working fine after the python update.

**Comment by TheConen** [comment]
Well, having stuff running under root that doesn't have to run under root is not something I want to do. Can we get a proper fix for the Python package, please?

**Comment by TheConen** [comment]
From what I could gather, @Safihre is the main Python developer here. Is there a chance you can give us the Python 2.7.13 SPK or another workaround to get our applications going again while a bug fix is in the works?

**Comment by TheConen** [comment]
Apparently, the 2.7.14-17 update has been revoked, the newest version available in the Package Centre is 2.7.13-16 again. However, in order to reinstall Python, I'd have to uninstall Deluge, too - which I'd like to avoid since I would like to keep my configuration. Is there a way to downgrade to the 2.7.13-17 package without uninstalling Deluge?

**Comment by Futerix** [comment]
Solution here. The eazy way to make backup is to install WinSCP, login with root and make bkp.

https://github.com/SynoCommunity/spksrc/issues/3108#issuecomment-358270497

**Comment by Safihre** [comment]
Can any of you give the appropriate logging?
Need to see what errors it throws. 
We tested this package extensively so it's really strange.

**Comment by TheConen** [comment]
I haven't down the downgrade yet, so just tell me what you need and where I can get it and I'll try to get it for you. I'd also be willing to give you access via TeamViewer to my PC so you can get the information you need yourself if that helps you more.

**Comment by TheConen** [comment]
Ok, so here are some logs (excerpts):

```
usr\local\deluge\var\deluged.log

[INFO    ] 12:52:33 torrentmanager:737 Saving the state at: /usr/local/deluge/var/state/torrents.state
[INFO    ] 12:52:33 torrentmanager:780 Successfully loaded fastresume file: /usr/local/deluge/var/state/torrents.fastresume
[INFO    ] 12:52:33 torrentmanager:826 Saving the fastresume at: /usr/local/deluge/var/state/torrents.fastresume
[INFO    ] 12:52:40 pluginmanagerbase:170 Plugin AutoAdd disabled..
[INFO    ] 12:52:42 pluginmanagerbase:170 Plugin Blocklist disabled..
[INFO    ] 12:52:42 pluginmanagerbase:170 Plugin AutoRemovePlus disabled..
[INFO    ] 12:52:42 pluginmanagerbase:170 Plugin Label disabled..
[INFO    ] 12:52:42 pluginmanagerbase:170 Plugin CopyCompleted disabled..
[INFO    ] 12:52:42 pluginmanagerbase:170 Plugin WebUi disabled..
[INFO    ] 12:52:42 rpcserver:226 Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 12:52:42 daemon:196 Waiting for components to shutdown..
```

```
usr\local\deluge\var\deluge-web.log

[INFO    ] 12:52:33 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 12:52:33 pluginmanagerbase:170 Plugin CopyCompleted disabled..
[INFO    ] 12:52:33 pluginmanagerbase:170 Plugin AutoAdd disabled..
[INFO    ] 12:52:33 pluginmanagerbase:170 Plugin AutoRemovePlus disabled..
[INFO    ] 12:52:33 pluginmanagerbase:170 Plugin Blocklist disabled..
[INFO    ] 12:52:33 pluginmanagerbase:170 Plugin Label disabled..
[INFO    ] 12:52:33 server:696 Shutting down webserver
```

```
var\log\messages

2018-01-17T13:53:08+01:00 theconen-nas0 [89932.646799] init: pkgctl-deluge pre-start process (29582) terminated with status 1
2018-01-17T13:53:08+01:00 theconen-nas0 synoscgi_SYNO.Core.Package.Control_1_start[29390]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-deluge][0xD900 privilege.cpp:60]
2018-01-17T13:53:09+01:00 theconen-nas0 synoscgi_SYNO.Core.Package.Control_1_start[29390]: service_initjob_action.c:27 InitJobStart failed, [0xD900 privilege.cpp:60]
2018-01-17T13:53:09+01:00 theconen-nas0 synoscgi_SYNO.Core.Package.Control_1_start[29390]: pkgstartstop.cpp:277 Failed to start pkgctl-deluge (err=-1) [0xD900 privilege.cpp:60]
2018-01-17T13:55:47+01:00 theconen-nas0 [90091.018420] init: pkgctl-deluge pre-start process (32163) terminated with status 1
2018-01-17T13:55:47+01:00 theconen-nas0 synoscgi_SYNO.Core.Package.Control_1_start[32025]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-deluge][0xD900 privilege.cpp:60]
2018-01-17T13:55:48+01:00 theconen-nas0 synoscgi_SYNO.Core.Package.Control_1_start[32025]: service_initjob_action.c:27 InitJobStart failed, [0xD900 privilege.cpp:60]
2018-01-17T13:55:48+01:00 theconen-nas0 synoscgi_SYNO.Core.Package.Control_1_start[32025]: pkgstartstop.cpp:277 Failed to start pkgctl-deluge (err=-1) [0xD900 privilege.cpp:60]
2018-01-17T14:24:29+01:00 theconen-nas0 synoscgi_SYNO.Core.Package.Control_1_start[24929]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-deluge][0xD900 privilege.cpp:60]
2018-01-17T14:24:29+01:00 theconen-nas0 [91814.487184] init: pkgctl-deluge pre-start process (25067) terminated with status 1
2018-01-17T14:24:30+01:00 theconen-nas0 synoscgi_SYNO.Core.Package.Control_1_start[24929]: service_initjob_action.c:27 InitJobStart failed, [0xD900 privilege.cpp:60]
2018-01-17T14:24:30+01:00 theconen-nas0 synoscgi_SYNO.Core.Package.Control_1_start[24929]: pkgstartstop.cpp:277 Failed to start pkgctl-deluge (err=-1) [0xD900 privilege.cpp:60]
```

```
var\log\synopgk.log

2018/01/17 14:24:26	start deluge: begin to start version 1.3.15-8
2018/01/17 14:24:26	start deluge 1.3.15-8 Begin pre-load apparmor
2018/01/17 14:24:26	start deluge 1.3.15-8 End pre-load apparmor ret=[0]
2018/01/17 14:24:26	start deluge 1.3.15-8 Begin start-stop-status start
/var/packages/deluge/scripts/start-stop-status: line 47: start-stop-daemon: command not found
/var/packages/deluge/scripts/start-stop-status: line 49: start-stop-daemon: command not found
Starting Deluge ...
/var/packages/deluge/scripts/start-stop-status: line 26: start-stop-daemon: command not found
/var/packages/deluge/scripts/start-stop-status: line 29: start-stop-daemon: command not found
2018/01/17 14:24:29	start deluge 1.3.15-8 End start-stop-status start ret=[127]
2018/01/17 14:24:29	(system) trigger deluge 1.3.15-8 Begin start-stop-status stop
/var/packages/deluge/scripts/start-stop-status: line 47: start-stop-daemon: command not found
/var/packages/deluge/scripts/start-stop-status: line 49: start-stop-daemon: command not found
Deluge is not running
2018/01/17 14:24:29	(system) trigger deluge 1.3.15-8 End start-stop-status stop ret=[0]
2018/01/17 14:24:29	(system) trigger deluge 1.3.15-8 Begin unload apparmor
2018/01/17 14:24:29	(system) trigger deluge 1.3.15-8 End unload apparmor ret=[0]
2018/01/17 14:24:30	stop deluge: begin to stop version 1.3.15-8
2018/01/17 14:24:30	stop deluge: stop version 1.3.15-8 successfully, result 0
2018/01/17 14:24:30	start deluge: start version 1.3.15-8 failed, result 1
```

I hope this helps you.

**Comment by ymartin59** [comment]
Thanks for details.

**Comment by Safihre** [comment]
I recompiled Python 2.7.14 package but now with the correct `start-stop-deamon` and hopefully a fix for other crashes related to `cryptography`. [Would you like to give it a try?](https://github.com/Safihre/spksrc/releases/tag/python-recompile3)

Now that we also got your attention, we have new packages that we are testing for [NZBGet, SABnzbd, CouchPotato, Sickrage, SickBeard Custom, Syncthing, Mono, Jackett, Tvheaded, Sonarr and Radarr](https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-357008518).
Would you be willing to try those? If you have Python 2.7.13 or 2.7.14, we want to know if they work in all cases. Let us know if you test 👍 Others tested these packages already, but more testing is better clearly!
Thank you! 🥇

**Comment by Safihre** [comment]
Closing this, the new Python package should fix these problems.
If you still experience problems after the `2.7.14-18` update, please create a new issue.
