### ISSUE TITLE
Unable to install Mosquitto on Synology: Error in Package

### ISSUE THREAD

**Issue by Hekoweb** [SynoCommunity/spksrc#3112]
Hello,

I tried to install the Mosquitto Package on my Diskstation, but without success. The following message appears (in german as my DSM is configured):

"Mosquitto" konnte nicht installiert werden. Die Paketdatei ist fehlerhaft. Bitte laden Sie die Paketdatei noch einmal herunter oder kontaktieren Sie den Entwickler des Pakets.

Retry also without same message. Whats going wrong?

Today I tried it again but right now I can't find the package any more...

### Setup
Mosquitto

DS218+
apollolake (x86_64)
DSM 6.1.4-15217 Update 5

### Expected behavior
Package should be installed

### Actual behavior
Error in Package

**Comment by ymartin59** [comment]
Under investigation

**Comment by ymartin59** [comment]
Fixed and update version published
