### ISSUE TITLE
Wallabag : mySQL root password issue

### ISSUE THREAD

**Issue by pfml** [SynoCommunity/spksrc#3113]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Wallabag
_Package Version:_ 2.2.3-2

_NAS Model:_ DS411+
_NAS Architecture:_ Intel Atom D510
_DSM version:_ DSM 6.1.4-15217 Update 5

### Expected behavior
Try to install package wallabag on my Syno (php 5.6 & 7.0, MariaD B10 and WebStation enabled)

### Actual behavior
Got an error msg : "failed to install "wallabag". Incorrect MySQL root password"
Using phpMyAdmin and MariaDB root password, I'm able to create/delete account

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

found no log in the mentioned places

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

in /var/log/messages :
```
2018-01-18T14:55:07+01:00 cezoffnas02 synoscgi_SYNO.Core.Package.Server_1_list[12263]: pkgcurltool.cpp:456 http://packages.missilehugger.com, Failed to request packages, httpResponseCode=404
2018-01-18T15:07:02+01:00 cezoffnas02 synoscgi_SYNO.Core.Package.Installation_1_install[2283]: pkginstall.cpp:466                                                             Failed to run preinst script for wallabag, 1

```
in /var/log/synopkg.log 
````
2018/01/18 15:07:02     install wallabag 2.2.3-2 Begin preinst
2018/01/18 15:07:02     install wallabag 2.2.3-2 End preinst ret=[1]
2018/01/18 15:07:02     install wallabag 2.2.3-2 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2018/01/18 15:07:28     install wallabag 2.2.3-2 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2018/01/18 15:07:28     install wallabag 2.2.3-2 failed
````

**Comment by MysteryWoMan** [comment]
Have you tried this? :
Log in on your Synology device using telnet or SSH (with your admin account).

```
mkdir /usr/syno/mysql
mkdir /usr/syno/mysql/bin 
ln -s /usr/bin/mysql /usr/syno/mysql/bin/mysql
```
or
```
mkdir /usr/syno/mysql
mkdir /usr/syno/mysql/bin
ln -s /volume1/@appstore/MariaDB10/usr/bin/mysql /usr/syno/mysql/bin/mysql
```
#2093 #2217 #2304 #2307

**Comment by pfml** [comment]
Many thanks for the reply.
Tried both, without success 😟 

Having installed MariaDB10, I made a search in the directories to find the most relevant link to establish. Tried /volume1/@appstore/MariaDB10/usr/local/mariadb10/bin/mysql, without success.
Made a try with MariaDB 5 : made a fresh install of the database package, and tried to install wallabag package. It takes a while, but I didn't got any error message. Wallabag is up and running. Will try to made a more thourough test of Wallabag next days.

**Comment by sandrotavares** [comment]
Have the same issue on a DS918+ With MariaDB10 and PHPMyAdmin 4.6.6

**Comment by Sigawan** [comment]
Installation of the wallabag package on the latest  DSM 6.1.5 15254 fails with the same error as most other packages hosted at synocommunity 'incorrect mysql root password'

Is any work being done on this generic problem in the years since it was first reported?

**Comment by pbalthasar** [comment]
Same here (DS416play, DSM 6.1.5, PhpMyAdmin 4.6.6, MariaDB10, Wallabag 2.2.3-2).

**Comment by arakeis** [comment]
try with this 👍 
ln -s /volume1/@appstore/MariaDB10/usr/local/mariadb10/bin/mysql /usr/bin/mysql
and
ln -s /volume1/@appstore/MariaDB10/usr/local/mariadb10/bin/mysqldump /usr/bin/mysqldump

this should walk you a little further

**Comment by Sigawan** [comment]
Switched to FreeNAS. Synology units ebay'd off.

**Comment by arakeis** [comment]
found out wallabag is looking for a MySQL connection on 3306, but mariadb10 seemed set up with 3307 by default, anyone knows how to alter the preferences.yml file from wallabag once downloaded ?

**Comment by arakeis** [comment]
with the correct path for mysql and mysqldump + the correct mysql (mariadb10) port set to 3307, my non working package, was able to fix it self. my setup is working !

**Comment by astacus27** [comment]
Hi arekeis, what steps did you take exactly to get wallabag working and in what order? Its still a bit unclear to me. Your help is much apreciated because you seem to have found workaround to get wallabag working.

**Comment by astacus27** [comment]
thanks in advance, looking forward to it

2018-06-08 14:23 GMT+02:00, arakeis <notifications@github.com>:
> I'll try to sum it up from scratch to be sure.
>

**Comment by zyphlar** [comment]
It would be super cute if the package could be updated with @arakeis 's strings. I've been trying to hack things together like this for days and MySQL straight-up doesn't seem available for the newest DSM so any SynoCommunity MySQL stuff is probably useless on those platforms. Seems like a straightforward fix, but due to code signing we can't do it ourselves (and most people aren't gonna hunt around on their NAS via SSH.)

**Comment by lotth** [comment]
Synology just released a new MariaDB10 version 10.3.11-0054. It now allows changing the default port in the MariaDB10 application. I did not test yet reverting to port 3306 to install Wallabag, but it should help.

**Comment by lotth** [comment]
Well, now database connection seems good but installer complains about curl_exec and curl_multi_init missing.

**Comment by croontje** [comment]
> Well, now database connection seems good but installer fails. From /var/services/web/wallabag/install.log it appears curl_exec and curl_multi_init are missing.

I solved this by enabling the curl extension in the webstation PHP advanced settings.

**Comment by ErikMonten** [comment]
> Ok, to have it work on a setup with mariadb10 installed (with the 3307 port used)
> you must add the previous links to your setup (ssh connection needed) :
> `ln -s /volume1/@appstore/MariaDB10/usr/local/mariadb10/bin/mysql /usr/bin/mysql`
> `ln -s /volume1/@appstore/MariaDB10/usr/local/mariadb10/bin/mysqldump /usr/bin/mysqldump`
> (while installing) change the mysql port from two files :
> `sudo vi /var/services/web/wallabag/app/config/parameters.yml`
> change : database_port: 3306 => database_port: 3307
> `sudo vi /volume1/@appstore/wallabag/share/wallabag/app/config/parameters.yml`
> change : database_port: 3306 => database_port: 3307
> 
> I know that the "while installing" is quiet imprecise but that the imperfect way I got it working

I followed this advice, and after installation continues with following error -->

Cannot install 'wallabag'
unable to migrate database schema. Please check the log -->
/var/services/web/wallabag/migration.log

In the log I find -->

Migrating up to 20170127093841 from 0

  ++ migrating 20160410190541

Migration 20160410190541 failed during Execution. Error There is no table with name 'wallabag.wallabag_entry' in the schema.


  [Doctrine\DBAL\Schema\SchemaException (10)]
  There is no table with name 'wallabag.wallabag_entry' in the schema.


Exception trace:
 () at /volume1/web/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:43
 Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist() at /volume1/web/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:197
 Doctrine\DBAL\Schema\Schema->getTable() at /volume1/web/wallabag/vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(65) : eval()'d code:62
 ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated2e01a7af5663aaa6f05dbe19bed007fa->getTable() at /volume1/web/wallabag/vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/Eval
uatingGeneratorStrategy.php(65) : eval()'d code:62
 ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated2e01a7af5663aaa6f05dbe19bed007fa->getTable() at /volume1/web/wallabag/app/DoctrineMigrations/Version20160410190541.php:35
 Application\Migrations\Version20160410190541->up() at /volume1/web/wallabag/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:290
 Doctrine\DBAL\Migrations\Version->execute() at /volume1/web/wallabag/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:183
 Doctrine\DBAL\Migrations\Migration->migrate() at /volume1/web/wallabag/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:142
 Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand->execute() at /volume1/web/wallabag/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:55
 Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() at /volume1/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /volume1/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:853
 Symfony\Component\Console\Application->doRunCommand() at /volume1/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:200
 Symfony\Component\Console\Application->doRun() at /volume1/web/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /volume1/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /volume1/web/wallabag/bin/console:29

**Comment by lxne** [comment]
> Well, now database connection seems good but installer fails. From /var/services/web/wallabag/install.log it appears curl_exec and curl_multi_init are missing. Curl extension is activated in Webstation default PHP parameters.

Same problem with MariaDB10 and port set to 3306.

**Comment by knapovsky** [comment]
I tried to solve this issue, but there's no success. I'm just going to use docker. My problem is that I cannot uninstall the synology wallabag package. It always gives me 'Incorrect root MySQL password'. Is there a way how to forcefully remove a Synology package?

**Comment by GitJamz** [comment]
omg what a disaster..
I have latets package of mariaDB 10 and phpmyadmin as well on my synology. And Also get wrong root password with the current wallabag package.
Difference is that I came from docker and that did not work well either.. The official wallabag container runs very bad on a synology.. Unable to fetch most articles and also the container has to run as root.

**Comment by Framstag** [comment]
I'm also interested in using Wallabag and get the same error regarding root password. Is anybody actively working on package fixes or am I on my own? It looks like the problem is not a principle problem, but "just" bad adjustment of all the required packages?

**Comment by andrewchenshx** [comment]
DS218, DSM 6.2.2-24922 Update 4
same error.

**Comment by jshum** [comment]
I've followed the instructions above
(installed mariadb10, phpmyadmin, php56)

- firstly, it required me to install `php56` even though I had `php72` installed previously. otherwise, it would say it can't find php56
- used `ln -s` to link to mariadb executables
- changed the port to `3307` while installation is happening
- but it is now unable to run the migration as it is throwing an exception from PDO it cannot find the driver
- I think this is due to the fact that php56 doesn't come with the php-mysql driver?
- I couldn't find a way to force it to use php72. If anyone has thoughts, would really appreciate it?

**Comment by publicarray** [comment]
Hi everyone I know it's been a long time. If you are still interested in wallabag and would like to test the latest build It's over here:
#4179

Please leave any feeback.
