### ISSUE TITLE
Radarr Access denied!

### ISSUE THREAD

**Issue by ghost** [SynoCommunity/spksrc#3114]
### Setup
_Package Name:_ Radarr
_Package Version:_ 0.2.0.910 

_NAS Model:_ Synology DS916+
_DSM version:_ DSM 6.1.4-15217 Update 5

### Expected behavior
I have installed and configure Radarr which I was using on a debian system before.
Radarr is launched by the synology user called "radarr" member of users
I want to be able to add the "radarr" user to the group "sc-media" which has been created because users don't have read access everywhere.

### Actual behavior
Couldn't import movie /volume1/Family/myfile.mkv: Access to the path is denied.

### Steps to reproduce
_1._ Grab a torrent
_2._ Download
_3._ Stuck for importing, stays in Activity tab

**Comment by ymartin59** [comment]
There is no SynoCommunity package version 0.2.0.910.
Please report your package version which should be date-stamp YYYYMMDD.

**Comment by ymartin59** [comment]
Does `/volume1/Family/` writable to group `sc-media` and/or to group `sc-download` ?

**Comment by raspdealer** [comment]
The package version is the last one: 20170226-2
Yes both group have a read / write access on the volume.

Additionnaly,  the files which can't be grabbed have been downloaded with the rutorrent synology package.

**Comment by raspdealer** [comment]
The package version is the last one: 20170226-2
Yes both group have a read / write access on the volume.

Additionnaly,  the files which can't be grabbed have been downloaded with the rutorrent synology package.

**Comment by Safihre** [comment]
The packages now in #3138 all use `sc-download` for anything related to downloading. I would suggest updating to the Sonarr/Radarr there and then adding the download-user (in this case `rutorrent`) to the `sc-download` group. This should give shared access to all.

**Comment by guillaume86** [comment]
I have a similar issue with the sonarr package. After updating it from the Synology package manager, Sonarr can't access my downloads folder (`Import failed, path does not exist or is not accessible by Sonarr: /volume1/downloads/complete/series/my_downloaded_episode`). 

I checked everything that I could, via the DSM UI and via SSH and I can't find the issue.
I tried restarting the NAS, I checked sc-nzbdrone is in the sc-download group, I checked the sc-download group has R/W access to /volume1/downloads/, I checked the sonarr process is running under the sc-nzbdrone user.
I even tried changing the owner of the downloaded folder to sc-download and it didn't work.
If anyone has an idea, I'm getting desperate.

**Comment by Safihre** [comment]
Everything should be done via File Station, not ssh. Permissions "Linux style" are not the same as the Synology ones.
Try stopping all services and then doing again the `sc-download` permissions on the download folder and set it to be applied to files and folders to.
