### ISSUE TITLE
Home Assistant package update

### ISSUE THREAD

**Issue by chasers37** [SynoCommunity/spksrc#3115]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Home assistant
_Package Version:_

_NAS Model:_ DS216j
_NAS Architecture:_Synology
_DSM version:_6.1.4-15217  update5

### Expected behavior
 pouvez vous me dire si je peux installer le paquet home assistant et comment ? 
merci

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Francis2b** [comment]
Tu devrais ecrire ton message en anglais si tu veux augmenter tes chances d'avoir une solution à ton problème.

Cordialement

**Comment by cytec** [comment]
@chasers37 please use english since not everyone speaks french... if i understand correctly you are unable to find/install home assistant?

From what i can tell it seems like Hame Assistant isn't available for your arch (armada38x) currently. Most likely someone will have to rebuild the Package with the latest toolchains

**Comment by Francis2b** [comment]
@cytec yes it is what he asked ;)

**Comment by chasers37** [comment]
thanks for your reponce @Francis2b and @cytec 
@Dr-Bean  make a packet and i don't find home assistant or Dokers on my syno

**Comment by cytec** [comment]
@chasers37 the package @Dr-Bean made/published is from 2015 and needs a rebuild

**Comment by ymartin59** [comment]
More than a rebuild in fact as support for DSM 6 has to be added to package. Plan for update

**Comment by chasers37** [comment]
Thanks for your job

**Comment by jjanderson** [comment]
would be great if a hassio version could be built as this will negte the need for updates. (Home assistant core currently on 2 week release cycle) I currently run min in docker, but having a native install would be much better...

**Comment by ymartin59** [comment]
Home Assistant now requires at least Python 3.5.3, so we should run a Python 3 package upgrade first.

**Comment by chickenandpork** [comment]
I've got an update to Home Assistant but occasionally it gives this opaque "Not available" error popup on install without any additional info.  Remediation is a reboot of NAS without any other installs/uninstalls so it's a transient state of some kind.  It's been frustrating me for a while, not resolved yet.

**Comment by ymartin59** [comment]
To anyone interested in Home Assistant, what are components you are interested ? Please comment in #3115
