### ISSUE TITLE
Can't see all packages

### ISSUE THREAD

**Issue by Piero87** [SynoCommunity/spksrc#3116]
_NAS Model: DS218+
_DSM version:  6.1.4-15217 Update 5

Hi, I have added the repository and in the Community tab i can see some packages but not all, for example I can't see pyLoad or Transmit, any help? I have also checked this: Yes, I want to see beta versions. Any idea?

**Comment by Piero87** [comment]
I think it’s related to this: https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-359128804

**Comment by ymartin59** [comment]
Please refer to FAQ. Job is in progress: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support
