### ISSUE TITLE
Octoprint not start

### ISSUE THREAD

**Issue by HubsiKU** [SynoCommunity/spksrc#3118]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Octoprint
_Package Version:_ 20160321-4

_NAS Model:_ DS216j
_CPU:_ Marvell Armada 385 88F6820
_DSM version:_6.2 - 23511

### Expected behavior
when I itsall octoprint and the requird pagage

### Actual behavior
Octoprint wont start. wehn i press "Run" in the Package-Center it ty to reinstall/update Octoprint and try to start but nothing work

**Comment by ymartin59** [comment]
Please refer to FAQ: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support
All packages require updates to support DSM 6
