### ISSUE TITLE
Firefox Sync Server doesn't run : files missing after install

### ISSUE THREAD

**Issue by MysteryWoMan** [SynoCommunity/spksrc#3124]
### Setup
_Package Name: ffsync_
_Package Version: 1.5.2_

_NAS Model: 415+_
_NAS Architecture: x86_64 (avoton)_
_DSM version: 6.1.4-15217 Update 5_

### Expected behavior
all files installed and ffsync can be run

### Actual behavior
files are missing and ffsync cannot be run

### Steps to reproduce
_1. install ffsync from synology package center in the DSM webinterface_
_2. run it_

#### Package log
_/usr/local/ffsync/var/install.log_
```
Ignoring indexes: https://pypi.python.org/simple
Collecting cef (from -r /usr/local/ffsync/share/wheelhouse/requirements.txt (line 5))
  Could not find any downloads that satisfy the requirement cef (from -r /usr/local/ffsync/share/wheelhouse/requirements
.txt (line 5))
```
- source url from installer not configured correctly? I think the installation already stops/aborts there

#### Other logs
_/var/log/synopkg.log_
```
2018/01/23 22:41:05     install ffsync 1.5.2-3 Begin postinst
unable to write 'random state'
2018/01/23 22:41:12     install ffsync 1.5.2-3 End postinst ret=[0]
```
- Probably this comes from `installer.sh` --> `postinst ()` --> `Line 66`
When i run `openssl rand -base64 20` (in real environment) as any user, no error is thrown. 

```
2018/01/23 22:41:13     install ffsync 1.5.2-3 Begin start-stop-status start
Starting Firefox Sync Server 1.5 ...
/var/packages/ffsync/scripts/start-stop-status: line 19: /usr/local/ffsync/env/bin/pserve: No such file or directory
2018/01/23 22:41:14     install ffsync 1.5.2-3 End start-stop-status start ret=[0]
2018/01/23 22:41:14     install ffsync: start version 1.5.2-3 successfully, result 0
```

- Last lines of ffsync/share/wheelhouse/requirements.txt are:
`mozsvc==0.8
tokenserver==1.2.7
SyncStorage==1.5.5
syncserver==1.5.2`
~~This should be updated with _requirements.txt_ from the github repository as these packages are not on _https://pypi.python.org/simple/_ anymore.~~ 
_UPDATE: Makefile changes this at the end, so there is nothing wrong with requirements.txt_

**Second try** : Download github repository and install
```===>  Processing dependencies of ffsync
make[1]: Entering directory '/volume1/storage/temp/git/spksrc/cross/python'
===>  Downloading files for python
wget http://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
2018-01-24 06:57:38 URL:https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz [12495628/12495628] -> "Python-2.7
.13.tar.xz.part" [1]
===>  Verifying files for python
===>    Checking sha1sum of file Python-2.7.13.tar.xz
sha1sum: standard input: no properly formatted SHA1 checksum lines found
===>      Wrong sha1sum for file Python-2.7.13.tar.xz
===>      Renamed as Python-2.7.13.tar.xz.wrong
===>      Download cookie removed to trigger the download again
../../mk/spksrc.checksum.mk:42: recipe for target 'checksum_target' failed
make[1]: *** [checksum_target] Error 1
make[1]: Leaving directory '/volume1/storage/temp/git/spksrc/cross/python'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make: *** [depend_target] Error 2
```

**Third try** installing in real environment (not virtual)
- Replaced _requirements.txt_ with  https://github.com/SynoCommunity/spksrc/blob/dsm6/spk/ffsync/src/requirements.txt 
- Removed Pastescript from requirements because of this error (full log: [pastescript_install_log.txt](https://github.com/SynoCommunity/spksrc/files/1658578/pastescript_install_log.txt)). 
`ValueError: '/tmp/easy_install-aA9NHI/Paste-2.0.3' is not in list`
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-t8STVm/PasteScript/`
- Removed `Jinja2` `Mako` `PasteScript` `nose` `simplejson` `requests` `six` from the requirements because they are already installed (same version or higher subversion) and gives an error when there is tried to uninstall them (for reinstalling it back immediately after anyway).)

`pip install -U -r requirements.txt`

All packages are collected..... seems good... until
``` 
Installing collected packages: umemcache, six, unittest2, simplejson, mozsvc, tokenserver, idna, urllib3, certifi, reque
sts, SyncStorage, syncserver, markupsafe, Mako, Jinja2, pytz, babel, setuptools, zope.interface
  Running setup.py install for umemcache ... error
    Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-BSoaUj/umemcach
e/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code,
 __file__, 'exec'))" install --record /tmp/pip-1JQqR9-record/install-record.txt --single-version-externally-managed --co
mpile:
    running install
    running build
    running build_ext
    building 'umemcache' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/python
    creating build/temp.linux-x86_64-2.7/lib
    /usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc -fno-strict-aliasing -DSYNOPLAT_F_X86_64 -O2 -incl
ude /usr/syno/include/platformconfig.h -DSYNO_ENVIRONMENT -DBUILD_ARCH=64 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -
DSYNO_RUNNING_DSM_BUILD_SYSTEM -g -pipe -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -D_FORTIF
Y_SOURCE=2 -O2 -Wno-unused-result -DOPENSSL_NO_SSL3 -I/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root//usr/l
ib/libffi-3.2.1/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWIN32_LEAN_AND_MEAN -I./lib/ -I/usr/in
clude/python2.7 -c ./python/umemcache.cpp -o build/temp.linux-x86_64-2.7/./python/umemcache.o
    unable to execute '/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc': No such file or directory
    error: command '/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc' failed with exit status 1

    ----------------------------------------
Command "/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-BSoaUj/umemcache/setup.py';f=getattr(to
kenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" ins
tall --record /tmp/pip-1JQqR9-record/install-record.txt --single-version-externally-managed --compile" failed with error
 code 1 in /tmp/pip-build-BSoaUj/umemcache/
``` 

I guess that the installation (activated in DSM) is done in an isolated environment with Virtualenv. This explains the different errors when doing a regular install.

What can I do about this? Am i doing something wrong?
~~There is a chance that it will work again when the _requirements.txt_ file whitin the synology package (spk) is updated, because now the most important packages are not downloaded.~~ _UPDATE: no need to change_
Any help  or advice is much appreciated!

**Comment by MysteryWoMan** [comment]
I compiled the ffsync package with spksrc (for avoton-6.1). 
Had to change some minor things to finish the compilation with no errors (libev version from 4.22 -> 4.24, python unittest2 version from 0.6 -> 0.5.1)
When I installed it (in DSM) i get exactly the same errors

```
2018/01/25` 06:38:46     install ffsync 1.5.2-3 Begin postinst
unable to write 'random state'
2018/01/25 06:38:55     install ffsync 1.5.2-3 End postinst ret=[0]
```
```
2018/01/25 06:39:11     start ffsync 1.5.2-3 Begin start-stop-status start
Starting Firefox Sync Server 1.5 ...
/var/packages/ffsync/scripts/start-stop-status: line 23: /usr/local/ffsync/env/bin/pserve: No such file or directory
2018/01/25 06:39:12     start ffsync 1.5.2-3 End start-stop-status start ret=[0]
```
Can someone point me where the problem lies?
Does this fail only on my device or is this general? Can someone accomplish to successfully install Firefox Sync server?

Oh and there was nothing really wrong with requirements.txt (as these involved application- and version-references are replaced at the end in the Makefile). Didn't noticed that first.

Thank you! 😃

**Comment by MysteryWoMan** [comment]
Update: compiled the spk package of Firefox Sync Server for dockerx64-6.1 and installed it on (Virtual)  DDSM 6.1.4-15217 Update 1

This time it installs with no serious errors. Everything seems installed (including /usr/local/ffsync/env/bin/pserve)
It still cannot be run because (as in my other compiled spk) the root password for MariaDB and other settings are not asked before install. So there is an error connecting to the database during install (even when no root password is set on MariaDB). How can I set this up? Is there a manual or extended developers guide for spksrc?

_/usr/local/ffsync/var/install.log_ 
Does not exists (i guess that means: no errors)

_/usr/local/ffsync/var/pserve.log_
```
  File "/usr/local/ffsync/env/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/ffsync/env/lib/python2.7/site-packages/pymysql/connections.py", line 626, in __init__
    self._connect()
  File "/usr/local/ffsync/env/lib/python2.7/site-packages/pymysql/connections.py", line 818, in _connect
    2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e))
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, 'Can\'t connect to MySQL server on u\'localhost\'
 ((1045, u"Access denied for user \'ffsync\'@\'localhost\' (using password: YES)"))') (Background on this error at: http
://sqlalche.me/e/e3q8)
Removing PID file /usr/local/ffsync/var/ffsync.pid
```

_/var/log/synopkg.log_
```
2018/01/25 22:58:17     install ffsync 1.5.2-3 Begin postinst
Enter password: unable to write 'random state'
2018/01/25 22:59:07     install ffsync 1.5.2-3 End postinst ret=[0]
```
The other error (pserve: No such file or directory) is not present.

Even if ffsync can be run on DDSM, that doesn't solve my original problem. I like to run it on a native DSM.

Is here anyone who can install or has installed Firefox Sync Server (1.5) on one of the following Synonolgy Diskstation models?:

- DS1817+
- RS2416(RP)
- DS415+
- DS1515+
- DS1815+
- DS2415+
- RS815(RP)+

Please, let me know!

**Comment by Sigawan** [comment]
Installation of the firefoxsync package on the latest  DSM 6.1.5 15254 fails with the same error as most other packages hosted at synocommunity 'incorrect mysql root password'

Is any work being done on this generic problem in the years since it was first reported?

**Comment by mreid-tt** [comment]
The original Firefox Sync Server, as indicated in its [source repository](https://github.com/mozilla-services/syncserver), is no longer actively maintained. Instead, it has been redeveloped in Rust and is now hosted in a new repository called [Syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs). The upcoming release, associated with the Pull Request [5942](https://github.com/SynoCommunity/spksrc/pull/5942) in the SynoCommunity/spksrc repository, will soon replace all prior versions of the package due to their deprecated functionality.

We invite interested individuals to explore the Checks tab at [this link](https://github.com/SynoCommunity/spksrc/pull/5942/checks) for the opportunity to download a pre-release version for testing purposes. Your valuable feedback is highly appreciated and encouraged before the final release.
