### ISSUE TITLE
mediainfo package for apollolake DSM 6

### ISSUE THREAD

**Issue by kianrafiee** [SynoCommunity/spksrc#3125]
Requesting mediainfo package for apollolake NASes like DS218+

Thank you.

**Comment by hgy59** [comment]
Hi @kianrafiee 
I successfully build mediainfo with the current spksrc for arch-apollolake-6.1
Then I installed it on my DS918+ and status is running.
How can I test that it is working? I did not find any GUI on the diskstation. How will you use mediainfo?

**Comment by kianrafiee** [comment]
No gui. Its used for things like sonarr to get better info about your media. Honestly im not sure how big of w difference it makes, i just saw it was recommmened by someone. Do you have the package link?

**Comment by hgy59** [comment]
you can download here:
https://ziba-systems.net/downloads/mediainfo_apollolake-6.1_0.7.93-3.spk

**Comment by kianrafiee** [comment]
Thanks! Will install later today. I appreciate you taking the time to compile it. Hopefully it will help you out if your using radarr/sonarr.
