### ISSUE TITLE
Octoprint - service cannot be started

### ISSUE THREAD

**Issue by CarstenPueschel** [SynoCommunity/spksrc#3128]
Octoprint service won't start on DS-416play.
Protocol is empty ...
Version is 20160321-4

**Comment by ymartin59** [comment]
Package has to be updated to DSM 6 generic service support. Related with #2599 and #2386

**Comment by broken-limiter** [comment]
#2599 has a workaround for missing unidecode
I'll test later today on my DS214play

thanks ymartin59 for the reference.

regards, broken

**Comment by Nickwren** [comment]
Is there any further progress on the octoprint issue?
I have tried the workaround but it doesn't seem to fix the issue.
This is such a useful tool for me.

Thanks.

**Comment by waazdakka** [comment]
One year later :) Any chance Octoprint could make a move to DSM6 ?

**Comment by vlotho** [comment]
hi,
I am also interested in this package.
I tried to modify the user in the octoprint.default file where
  it was set to "pi" and even adding "octoprint" to the sudoers file, nothing helps, it still does not start....

**Comment by Knedlos** [comment]
Hi there,
I'm another one, who will be very happy to be able to use Octoprint on my DS 214 :-). Any chance to move this issue forward?
Thanks
