### ISSUE TITLE
Does spksrc perl package have make dependency?

### ISSUE THREAD

**Issue by kianrafiee** [SynoCommunity/spksrc#3130]
The one in Package Center does not so I was wondering if the one provided by SynoCommunity has the make dependency I need in order to run a perl script I have. If it does, can someone please compile one for apollo lake DSM 6?

**Comment by ymartin59** [comment]
What do you mean by "make dependency" ? Have you got any error messages from or references to your "perl script I have" ?

**Comment by hgy59** [comment]
As far as I can see there is no perl package here at SynoCommunity/spksrc

**Comment by m4tt075** [comment]
Well, there is an official Perl package from Synology, [here for instance](https://www.synology.com/en-global/dsm/packages/Perl), but should appear in your package center anyways.

**Comment by ymartin59** [comment]
"make" (GNU make) is a compilation tool processing Makefile and it is not (and will never be) available on DSM. So there is little chance "your perl script" has been designed to run on DSM.
