### ISSUE TITLE
ffmpeg - enable eac3 to ac3 conversion

### ISSUE THREAD

**Issue by enchained** [SynoCommunity/spksrc#3134]
_Package Name:_ ffmpeg
_Package Version:_ 3.3.3-7

_NAS Model:_ DS216+II
_NAS Architecture:_ braswell
_DSM version:_ DSM 6.1.4-15217 Update 5

I'm trying to setup a shell script to convert my videos audio from eac3 to ac3, using this command:
`ffmpeg  -y -i "input.mkv" -map 0 -c:s copy -c:v copy -c:a ac3 -b:a 640k "output.mkv"`

However, in the end, it just removes the audio completely from the file. I checked out `ffmpeg -codecs`, and it looks like ac3 only has a 'Decode', and eac3 has neither. Also, judging by `ffmpeg -encoders | grep ac3` looks like those were disabled.

I really need to be able to run ffmpeg locally (not in docker), so is there any way for me to make it work?

**Comment by hgy59** [comment]
are your shure, you run ffmpeg version 3.3.3-7?

it is located in /usr/local/ffmpeg/bin and default ffmpeg runs the diskstation version off ffmpeg.

use ffmpeg -version 

as mentioned in #2939 I have built the current package for apollolake.

`sudo /usr/local/ffmpeg/bin/ffmpeg -codecs`
shows
`DEA.L. ac3                  ATSC A/52A (AC-3) (decoders: ac3 ac3_fixed ) (encoders: ac3 ac3_fixed )`

and
`sudo /usr/local/ffmpeg/bin/ffmpeg -encoders | grep ac3`
gives:
```
 A..... ac3                  ATSC A/52A (AC-3)
 A..... ac3_fixed            ATSC A/52A (AC-3) (codec ac3)
 A..... eac3                 ATSC A/52 E-AC-3
```

**Comment by ymartin59** [comment]
Notice, there is no need to run these commands as root with `sudo`...

**Comment by enchained** [comment]
Oh, stupid me. I was using the diskstation version indeed. It worked, thank you so much!
