### ISSUE TITLE
[Package Request] Lidarr

### ISSUE THREAD

**Issue by DamienGZ** [SynoCommunity/spksrc#3135]
Can we get Lidarr added to the SynoCommunity?

Setup
Package Name: Lidarr - https://github.com/lidarr/Lidarr
Package Version: Latest?

NAS Model: DS1815+

I've noticed that this package has already been placed on https://synology.nzbusenet.com/?arch=x86
However when I try to install that package, it is incompatible with my Synology. The package is also on Docker.

I'm not sure how to go about making it work with Synology or how to add it to the SynoCommunity and am hoping one of you more technically minded individuals will be able to help in getting this added.

**Comment by Safihre** [comment]
I can add it easily, but [I need these things to happen first](https://github.com/SynoCommunity/spksrc/pull/3123#issuecomment-364740501). Otherwise it's yet _another_ open PR..

**Comment by Safihre** [comment]
Actually I have to take that back.. It seems they use AppVeyor to distribute releases, but that's not really reliable. Even right now I can't download the files.
They should use the GitHub-releases or some other distribution platform that also has more reliable URLs, but seeing how they are in Alpha stage it doesn't seem to be their priority.

**Comment by DamienGZ** [comment]
Thank you for looking into it @Safihre.

I'll catch them on their discord and ask if they can put out an alpha github-release.

**Comment by ltomes** [comment]
@DamienGZ any progress on this? I am in a similar boat with a DS414 that cannot run docker.

I see they don't have [any releases](https://github.com/lidarr/Lidarr/releases) yet, and there is not an open issue either.

**Comment by hikaricore** [comment]
You honestly don't even want to be running it in Docker. There's a fairly disruptive issue (connection lost) that a number of people experience with Lidarr and Docker that makes it very difficult to use. Having tested Lidarr on other systems without Docker, I'm pretty certain that Lidaar isn't the problem.  https://www.reddit.com/r/Lidarr/comments/7w15nv/connection_lost_when_importing/

Our best hope is for Lidarr to make a git release and this to get packaged.  XD

**Comment by ltomes** [comment]
Awesome to hear!

@Safihre, initial lidar release [here](https://github.com/SynoCommunity/spksrc/releases/tag/pre-dsm6).

**Comment by hikaricore** [comment]
Looks like beta was released: https://github.com/lidarr/Lidarr/releases  :D

**Comment by mbnn** [comment]
Any update on the Synology package for this? :)

**Comment by G1zm0** [comment]
Tracking this issue with interest

**Comment by FinalAngel** [comment]
+1 please

**Comment by Safihre** [comment]
@ymartin59 is it alright if I put together the package for Lidarr? It's basically Sonarr/Radarr.

**Comment by ymartin59** [comment]
OK for me. I just wonder how many "similar" (from my point of view) forks of same application packages we "can" support/maintain...

**Comment by Safihre** [comment]
Test packages will be available here: https://github.com/Safihre/spksrc/releases/tag/lidarr-build

**Comment by hikaricore** [comment]
Thank you for the test packages.  Installed and working fantastically here on x64.

For anyone trying to run the package as a different user (I know this isn't meant to be changed), you can edit whatever your architecture’s equivalent path of /var/packages/lidarr/conf/privilege is, then update the ownership permissions for application path under your equivalent path of /volume/@appstore/lidarr.

**Comment by jnags** [comment]
@Safihre thanks for posting the Lidarr test packages.  Any chance of also getting an AoplloLake version to test out?  Thank you for your time and help in getting these packages out and working.

**Comment by Safihre** [comment]
`Apollolake`==`X64`.

**Comment by hikaricore** [comment]
Thank you so much for making this happen Safihre!  It looks like the first post-test release is out now.  :D  You're the best.

**Comment by Safihre** [comment]
@hikaricore it installed successfully on your device? :)

**Comment by Webreaper** [comment]
Installed fine on my 916+ running DSM 6.2. Thanks!

**Comment by Safihre** [comment]
Strange, I will test upgrade path again and check versions.

**Comment by darionmapp** [comment]
@Safihre  Port Undefined configured for this package is either in use or reserved by the system. Disable/reconfigure conflicting service or ask the developer to modify the package configuration.

DS218+ DSM 6.2-23739

**Comment by Safihre** [comment]
@darionmapp  this is a local problem. You should reboot the NAS and double check you don't have any special port scanning or defending software active.

**Comment by hgy59** [comment]
Package was published as v20190320-2
