### ISSUE TITLE
ffmpeg on DS216Play

### ISSUE THREAD

**Issue by ntempel2018** [SynoCommunity/spksrc#3137]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_FFmpeg
_Package Version:_3.3.3.-7

_NAS Model:_DS216Play
_NAS Architecture:_? Synology
_DSM version:_DSM 6.1.5-15254

### Expected behavior
Tell us what should happen
See the application on the normal way (headmenu) on my DSM

### Actual behavior
Tell us what happens instead
Don''t see where and how to use the application
### Steps to reproduce
_1._installed ffmpeg_monaco-6.1_3.3.3-7.spk
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by cytec** [comment]
after installation the binary file of ffmpeg is located in `/usr/local/ffmpeg/bin/`

**Comment by ymartin59** [comment]
I have created a FAQ page about it https://github.com/SynoCommunity/spksrc/wiki/FAQ-FFmpeg
