### ISSUE TITLE
SABnzbd - not updating from 2.3.1 to 2.3.2

### ISSUE THREAD

**Issue by Ltek** [SynoCommunity/spksrc#3140]
I'm on 2.3.1 [f1695ec] (regular package, not test) and the notifications has shown 2.3.2 available for a while not but it is not updating?

Does it no long auto update?

How do I update the package?

thx

**Comment by Safihre** [comment]
You can use the test-package and let us know if the upgrade went well!
See here: #3138

We had to implement many changes to all packages in general, so we appreciate feedback.
