### ISSUE TITLE
Setting Deluge download paths results in deluge being unable to allocate files.

### ISSUE THREAD

**Issue by awiebe** [SynoCommunity/spksrc#3141]
### Setup
_Package Name:_ Deluge
_Package Version:_1.3.15-8

_NAS Model:_ DS416j
_NAS Architecture:_
_DSM version:_ 6.1.4-15217

### Expected behavior
Setting download and completion locations of deluge should allow deluge to download files to those paths.

### Actual behavior
Setting download and completion path to locations other than the defaults results in deluge being unable to allocate the file.  In particular I tried shares, and user folders.
### Logs
The deluge log doesn't report anything interesting, as far as it seems concerned,the torrent was added successfully.

**Comment by Safihre** [comment]
You need to give the deluge-user or group permissions to access the files from within File Station.

**Comment by awiebe** [comment]
Do you mean I should create a user in the control panel, and grant access to the share?  Should it be named `deluge` as I would under debian(that's not quite clear from your comment)?

I'll try that, but that should definitely be part of the setup wizard.

**Comment by Safihre** [comment]
Could you maybe try the Deluge package in the #3138 thread? It should indeed do all this for you.

**Comment by awiebe** [comment]
In the requested package version, the group `sc-download` is automatically only granted only on the download folder:
- Read
  - Traverse/Execute

Additionally
- No permission is granted to read the watch folder.
- No permission is granted to read or write the completion folder
- Subfolders created by deluge do not properly inherit permissions of the download folder, resulting in additional permission errors until fixed manually and recheck run.

**Comment by Safihre** [comment]
@awiebe You used the version in #3138?  I cannot reproduce that. 
I see that `sc-download` has read/write and traverse on the share. When applying the update from #3138 it should also extract your watched and incomplete folders and apply the same permissions.

**Comment by Safihre** [comment]
Closing due to lack of response.

**Comment by awiebe** [comment]
Yes did use revision #3138 as asked.  Your comment suggests you may have just used the root of a share as your target directories.  I tried to use a subfolder of the share rather than the root of the share.  If the logic depends on me choosing the root of the share as a folder this may have been the problem.

I tried:
```` bash
aShare/
 torrent/
  complete/
  downloaing/
  inbox/
 
````

**Comment by ymartin59** [comment]
May you please review following documentation: https://github.com/SynoCommunity/spksrc/wiki/Permission-Management
and check your folders permissions.
