### ISSUE TITLE
Synology Virtual DSM - Package Source cannot be added.

### ISSUE THREAD

**Issue by rheckly** [SynoCommunity/spksrc#3142]
Hi
I try to add your package source to my synology virtual DSM 6.1.5-15254 - but with no luck.
While I cann add this package source  http://packages.synocommunity.com/  in a physical DSM the virtual doesn't accept this.
Answer from Synology:
_After confirming with the developer, the root cause is that the third party package doesn't recognize Virtual DSM, the **third party server should add the synology_kvmx64_virtualdsm to the list**. But we are working on it with our developer and PM, hope we can make it work soon! Thanks for your report. We are really sorry for your inconvenience. If there is anything I can do for you, please let me know_.  

Is there a way you could add this to the server?
Thx

**Comment by ymartin59** [comment]
Great, yet another arch !
@hgy59 As our "arch" specialist now ;) are you interested in submitting a PR with its support ? Would be really helpful

**Comment by hgy59** [comment]
Working on it. Will name it kvmx64 as synology does (not kvm64 as defined yet in spksrc.common.mk)

@ymartin59 Is there anything to add in spkrepo? As you added fixes to Diaoul/spkrepo I assume that this is the code that is used for production? Can see there only a 3 years old create_db script under migrations/versions so it is likley the new archs and TC Versions are auto updated in the database.
So I hope the kvmx64 arch will be recognized by the diskstations ;-)

@rheckly I do not use die Virtual Machine Manager and I don't know whether the virtual DSM can be used in test mode without paying a lincense and how easy it will be to uninstall it. 
What package you are insterested to do a test with? and is it possible to manually install packages?

**Comment by ymartin59** [comment]
@hgy59 I have added `kvmx64` architecture from repository administration interface... Do not care about database script in spkrepo sources, not a priority.

**Comment by rheckly** [comment]
I'm able now to add the package source http://packages.synocommunity.com/ to my Virtual DSM 6.1.5-15254.
Thank you
However some packages are not available - e.g. the REDIS package is not selectable.

@hgy59: the virtual DSM can be installed with the virtual manager package - 1 virtual DSM licence is included in a Synology Box. 
Uninstalling the package also asks for deleting the virtual machines.

**Comment by Safihre** [comment]
Amazes me always how Synology doesn't help this project _at all_.

**Comment by ymartin59** [comment]
@rheckly May you please check Midnight Commander is available and works on Virtual DSM ? https://synocommunity.com/package/mc

**Comment by hgy59** [comment]
@ymartin59 have just installed virtual DSM and added synocommunity package center in the VM.
The following sc packages are available for installation:
- Adminer
- BicBucStriim
- COPS
- CouchPotato
- CouchPotato Custom
- Full-Text RSS
- Headphones
- HTPC-Manager
- Maraschino
- Midnight Commander
- Mylar
- Roundcube Webmail
- Salt Master
- SaltPad
- SickBeard Custom
- SiCKRAGE

I installed Midnight Commander and status is running.

With SSH into the virtual DSM as admin:user there is an error when I run mc:
``Failed to run:``
``Cannot create /var/services/homes/admin/.config/mc directory``

After activating the "user home service" it runs as expected.

**Comment by ymartin59** [comment]
@hgy59 Thanks for testing. I consider support for arch is OK. Additional packages will come with updates.
