### ISSUE TITLE
Transmission package not available for installation 

### ISSUE THREAD

**Issue by Jayeahyeah** [SynoCommunity/spksrc#3145]
Hi,
so I wanted to set up Transmission on my very first NAS and followed this guide:
https://www.youtube.com/watch?v=RPVs-Gt44dg&t=11s
While I was able to add SynoCommiunity as a package source, only few (~15) packages actually showed up in the community tab, Transmission not beeing one of them.
Any idea why this is and how to fix it?

### Setup
_Package Name:_Transmission 
_Package Version:_v2.92-12

_NAS Model:_
_NAS Architecture:_DS218play
_DSM version:_DSM 6.1.5-15254

**Comment by ymartin59** [comment]
Your DSM model architecture is recent and packages have to be rebuilt for it. You may test packages generated for `rtd1296` at https://github.com/SynoCommunity/spksrc/issues/3138
