### ISSUE TITLE
FFMPEG Evansport issue with AAC/ALAC/AIFF transcoding? 

### ISSUE THREAD

**Issue by bigdogJW** [SynoCommunity/spksrc#3146]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_FFmpeg
_Package Version:_3.3.3-7

_NAS Model:_DS214play
_NAS Architecture:_INTEL Atom CE5335 Evansport
_DSM version:_6.1.5-15254

### Expected behavior:
When called from within the Subsonic web-based music streamer package, FFmpeg should be transcoding both lossless (AIFF/ALAC) music files as well as lossy (AAC/MP3) music files

### Actual behavior
See screenshots below.  When selecting the pre-installed 'default' ffmpeg path included from synology, AIFF and ALAC files transcode and play (via the subsonic player in a web browser) fine, but AAC (in .m4a container) and MP3 files **do not play** & just buffer endlessly.

When selecting the FFmpeg 3.3.3-7 package from the SynoCommunity, AAC and mp3 files **do** transcode and play, but AIFF and ALAC files **do not play** & just buffer endlessly.

Any help getting all formats (AIFF/ALAC/AAC/MP3) to transcode and play would be greatly appreciated!!

### Steps to reproduce
_1._ See attached screenshots
_2._Launch Subsonic
_3._Select 'default' transcoder setting to use synology FFmpeg (and play AIFF/ALAC files) but not AAC
_4._Select any of the 'SYNOCOM1, 2, or 3' transcoder settings to try to utilize FFMPEG 3.3.3-7 - but only will play AAC and not AIFF/ALAC.
_5._Play (or attempt to play) music files.

![screen shot 2018-02-09 at 8 35 17 am](https://user-images.githubusercontent.com/10822526/36031561-1fee7660-0d79-11e8-991f-ce409e9f8705.png)

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by m4tt075** [comment]
By specifying `ffmpeg` without path you are likely using the version Synology is shipping. Try adding the path as `/usr/local/ffmpeg/bin/ffmpeg ...` in the `Downsample Command` field and see whether it works then...

**Comment by bigdogJW** [comment]
thanks - yes tried it already- and the behavior is the same.  In addition, eventhough there does appear to be the limited, inconsistent transcoding, now I get an error message indicating "Notice: transcoders does not appear to be installed."  (See screen shots below.)

The same downsample command results in different behaviors depending on which transcoder is selected - that is, the "default" setting resultings in transcoding of AIFF and ALAC, but not AAC or MP3.  Changing to any of the other "SYNCON1, 2,or 3" transcoder settings results in transcoding of AAC & MP3 only (but not ALAC or AIFF).

Screenshot - changed downsample command:

![screen shot 2018-02-09 at 1 28 40 pm](https://user-images.githubusercontent.com/10822526/36044748-a1796622-0da1-11e8-9a2e-a30faeeb7202.png)

Screenshot - error message:

![screen shot 2018-02-09 at 1 54 16 pm](https://user-images.githubusercontent.com/10822526/36044790-c4192c26-0da1-11e8-89a9-eab0c53be931.png)

**Comment by m4tt075** [comment]
Purely speculating, but I would try the following:
- Remove all transcoding profiles but two.
- Edit the `default` profile as follows: Remove the `AIF` formats in the `Convert from` box and add the path `/usr/local/ffmpeg/bin/` to `Step 1`
- Edit the second profile as follows: Only keep `AIF` in the `Convert from` box and add the path `/bin/` to `Step 1`.
- Remove the `downsampling command` for the time being.
Try again...

**Comment by bigdogJW** [comment]
Thanks - good thought.  

When I try that, AAC files play but AIFF/ALAC do not play at all.   This same behavior occurs with either transcoder setting (default or SYNOCON) or both of them toggled on.  See screenshots below.

Removing the downsample command seems to be preventing the lossless (AIFF/ALAC) files from being transcoded.  (Adding the /bin/ path to the downsample command makes no difference, and also gives the same error message as above: "Notice: Transcoders does not appear to be installed.")

![screen shot 2018-02-10 at 8 13 38 am](https://user-images.githubusercontent.com/10822526/36062464-2aaa571e-0e3b-11e8-8494-ccfab4a09e90.png)

![screen shot 2018-02-10 at 8 13 57 am](https://user-images.githubusercontent.com/10822526/36062468-33c609ba-0e3b-11e8-8d37-70ab84dd1461.png)

**Comment by m4tt075** [comment]
OK, I really don't know. I would probably `ssh` into the box and try to convert sample files manually on the command line to check whether the `ffmpeg` commands actually work (check separately for `/bin/ffmpeg` (the original version) and `/usr/local/ffmpeg/bin/ffmpeg` (SynoCommunity version). If that works, the problem is "just" to configure `Subsonic` correctly. And for that, I'd ask on some forum there.

**Comment by ghenry22** [comment]
A suggestion to try for anyone that is testing.  If one version off FFMPEG does FLAC & AIFF.  Set the first transcoder to these.  In the convert from box but just those 2 extensions.

Now add a transcoder under that, point it to the alternative version of ffpmeg the plays everything else, in the from field put in all relevant extensions but NOT AIFF or FLAC.

Now fire it up and it should use one version for FLAC and AIFF only and the other version for everything else.

If this works let me know.  I can bundle FFMPEG or any other transcoder with the build and preset the transcoders appropriately, the only catch is if it's not an x86 processor in the box I will only have x86 compiled transcoders so would have to find a way to fall back.  But then transcoding is probably less of an issue on those boxes with the more limited processors anyway?

**Comment by bigdogJW** [comment]
OK - I tried this.  See screenshots of settings and players below.

My results are as follows:
1. MP3s play in all cases.
2. With 'default' set as the only active transcoder, AIFF and ALAC files play, but AAC do not.
3. With 'others' set as the only active transcoder, AAC files play, but AIFF and ALAC do not.
4. With **both** 'default' and 'others' set as active transcoders, AIFF and ALAC files play, but AAC do not. (same as #2).

Questions:
1. do ffmpeg settings/downsample commands look correct?  Any suggestions to improve?
2. Could this somehow have do with the fact that both ALAC and AAC files are in an .m4a container? 
3. If someone else has an AAC file (downloaded from iTunes store) to try out, would be interested to know if you get the same results -- or if somehow this is particular to the DS214play unit.  I wouldn't think this is unique to the DS214play since all formats **do** transcode -- just not with a single path.

Thanks.

![screen shot 2018-02-13 at 8 29 22 am](https://user-images.githubusercontent.com/10822526/36152627-a44803c2-1099-11e8-800d-8710cb69d821.png)

![screen shot 2018-02-13 at 8 28 56 am](https://user-images.githubusercontent.com/10822526/36152644-acede85c-1099-11e8-8422-0c074d4e1396.png)

**Comment by m4tt075** [comment]
I have just checked the SynoCommunity ffmpeg version and ALAC encoders and decoders are compiled in here as well. I don't see a reason why it should not work (other than fancy Subsonic configuration options). Last suggestion from my side:

1. Add the "CONVERT FROM" formats of "Others" to the "Default" "CONVERT FROM" field 
2. In "Default": Add the "/usr/local/ffmpeg/bin/" path in front of the ffmpeg command in "STEP 1"
3. Delete the "Others" profile
4. In "Downsample Command": Add the "/usr/local/ffmpeg/bin/" path in front of the ffmpeg command as well

Try again.

**Comment by bigdogJW** [comment]
Tried m4tt075's suggestions.  Results and screenshots as follows:

1.  MP3 files play
2. AAC files play
3. ALAC and AIFF files do not play.
4. Get an error message indicating "Notice: Transcoders does not appear to be installed." (even though AAC files are playing somehow). See my comment in screenshot #2 below.

Subsonic does not seem to be recognizing the downsample command "/usr/local/ffmpeg/bin/ffmpeg..."

I also wonder if somehow AAC and MP3 files are playing natively through the web browser and bypassing any transcoder setting...?

![screen shot 2018-02-13 at 2 42 41 pm](https://user-images.githubusercontent.com/10822526/36170205-bf7796ca-10cc-11e8-8ede-0ee227ba7258.png)

![screen shot 2018-02-13 at 2 42 53 pm](https://user-images.githubusercontent.com/10822526/36170388-3e1d607c-10cd-11e8-9fb3-689c6dcb6dca.png)

**Comment by m4tt075** [comment]
I'm sorry, but from all your reports I very much doubt the problems you are facing are due to the SynoCommunity ffmpeg package. If standard Unix paths are not recognized, I'm pretty sure this is a problem with the Subsonic configuration. I strongly suggest to consult some Subsonic forum instead...

**Comment by bigdogJW** [comment]
Thanks M4tt075.  I suspect you're right.  Ghenry22, who commented above, is the developer of the Subsonic package for Synology - so let's see what is response is.

**Comment by ymartin59** [comment]
FFmpeg package update published
