### ISSUE TITLE
[Update Request] Transmission

### ISSUE THREAD

**Issue by Stanzilla** [SynoCommunity/spksrc#3147]
https://github.com/transmission/transmission/releases/tag/2.93 was released 16 days ago and has important security fixes.

**Comment by Safihre** [comment]
Now included with #3144.
Available here; https://github.com/Safihre/spksrc/releases/tag/transmission-dsm61-all

**Comment by ymartin59** [comment]
@Safihre I noticed a previous PR #3014 proposed to include https://github.com/ronggang/transmission-web-control as an alternative Web UI: https://github.com/SynoCommunity/spksrc/pull/3014/commits/509e879f100f85c9f496c817d5d3daba71f27de6 - code was really draft (which explains it has been closed without merge) but such addition may be relevant for users experience.

**Comment by Safihre** [comment]
Considering this 'fixed' with the release of the test-packages in #3138. The version is updated, we are now just smoothing out these permission problems.
