### ISSUE TITLE
can't see radarr on synology under community

### ISSUE THREAD

**Issue by AhmedOsama** [SynoCommunity/spksrc#3148]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ radarr
_Package Version:_

_NAS Model:_ DS215j
_NAS Architecture:_
_DSM version:_ 6.1

### Expected behavior
to install radarr package as displayed on https://synocommunity.com/packages

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ open package center
_2._ click on community
_3._ can't find radarr package to install 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by AhmedOsama** [comment]
Found the solution its a beta package I had to enable beta first

**Comment by ymartin59** [comment]
Package available online is designed for DSM 5 only. You should get test package for DSM 6 from https://github.com/SynoCommunity/spksrc/issues/3138
