### ISSUE TITLE
Jackett doesnt work on my Synology

### ISSUE THREAD

**Issue by alxlaxv** [SynoCommunity/spksrc#3150]
### Setup
_Package Name:_ Jackett
_Package Version:_ 0.7.1483-4

_NAS Model:_ DS916+
_DSM version:_ DSM 6.1.5-15254

### Expected behavior
Adding indexers and searching

### Actual behavior
Error is displayed

#### Package log
```
2018-02-11 11:42:40.5104 Error Exception in test_indexer System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: TrustFailure (One or more errors occurred.) ---> System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /spksrc/spk/mono/work-x64-6.1/mono-5.4.1.6/external/boringssl/ssl/handshake_client.c:1132
  at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00047] in /spksrc/native/mono/work-native/mono-5.4.1.6/mcs/class/System/Mono.Btls/MonoBtlsContext.cs:201 
  at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status) [0x0003c] in /spksrc/native/mono/work-native/mono-5.4.1.6/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:615 
  at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream:ProcessHandshake (Mono.Net.Security.AsyncOperationStatus)
  at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00000] in /spksrc/native/mono/work-native/mono-5.4.1.6/mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs:282 
  at Mono.Net.Security.AsyncProtocolRequest+<ProcessOperation>d__24.MoveNext () [0x000ff] in /spksrc/native/mono/work-native/mono-5.4.1.6/mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs:221 
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by hgy59** [comment]
Error says it is a problem with certificate validation. 
May be related to mono cert-sync? #3033

**Comment by m4tt075** [comment]
@alxlaxv Have you updated your DSM or changed anything else before that error occured? 
Independent of that, please do the following:

1.  `ssh` into your box, check whether the folder `/usr/share/.mono` exists and if so, list it's content with `ls -l` and share it here.
2.  After you have done that, please manually update to the `mono-5.8.0` package from [here](https://github.com/m4tt075/spksrc/releases/tag/Mono-5.8.0-fixed).  Let me know whether it fixed the issue. 
3. Independent of whether it did, please repeat the `ssh` exercise from above and share the `.mono` folder content again.

**Comment by ymartin59** [comment]
@m4tt075 is there a way to relocate `/usr/share/.mono` into package content, for instance `/var/packages/mono/target/var/.mono`, so that it is kept after upgrade ?

**Comment by m4tt075** [comment]
@ymartin59 Yes, I had the same thought. `cert-sync` has a `--user` option, which is supposed to populate the per-user store in the user's home directory. The path cannot be specified, so we'd have to set the user home directory to `/usr/local/mono/var`. However, I would absolutely not expect Synology to overwrite the `/usr/share/` folder during DSM updates. I was wondering to report it to them if they do. What do you think?

**Comment by ymartin59** [comment]
@m4tt075 Definitely location `/usr/share/.mono` is really weird to store application specific stuff. According to LFS, `/var/lib/mono/` would be more relevant.
As `/usr/local/mono` symbolic link is an helper for end-user, I would create a patch on official release to replace that location to `/var/packages/mono/target/var/.mono`.
If not available, I would request upstream a `configure` option to set this location without patching.

**Comment by m4tt075** [comment]
@ymartin59 It seems others have asked before. I found [this](http://lists.dot.net/pipermail/mono-devel-list/2017-July/044458.html). I have started looking at the source files, but this seems anything but straight-forward. I have asked for advice on mono's IRC channel. Let's see how it goes, but not sure I can do it.

An alternative would be to remove the `cert-sync` command from `post-install` and `post-upgrade`, and add it to `pre-start` instead. Worst case, you'd just have to re-start the package rather than re-installing it, but not really nice either. Thoughts?

**Comment by alxlaxv** [comment]
Have you updated your DSM or changed anything else before that error occured?
--> I never had Jackett installed on my Syno before. 
--> I made the recent Mono update and all DSM updates
--> I installed Jackett yesterday, never worked

ssh into your box, check whether the folder /usr/share/.mono exists and if so, list it's content with ls -l and share it here.
--> There is no .mono folder in /usr/share
--> /usr/share$ sudo find / -name .mono
/volume1/@appstore/nzbdrone/var/.config/.mono
/volume1/@appstore/radarr/var/.config/.mono

After you have done that, please manually update to the mono-5.8.0 package from here. Let me know whether it fixed the issue.
--> I never installed spk like this, Can you please explain it to me? which one should I take?


Thanks

**Comment by m4tt075** [comment]
OK. Please do the following:

1) Deinstall the `Jackett` version you have
2) (Ideally) deinstall `Mono` as well. If you have dependencies, and the package manager asks you to deinstall other packages first, don't do it for now, and just keep Mono instead.
3) Download the appropriate `Mono 5.8.0` package for your NAS model from [here](https://github.com/m4tt075/spksrc/releases/tag/Mono-5.8.0-fixed) and install it manually following the instructions from [here](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Application/How_to_install_applications_with_Package_Center#t2.3)
4) Check whether you find the `.mono` folder within `/usr/share` now.
5) Download the appropriate `Jackett` package for your NAS platform from [here](https://github.com/m4tt075/spksrc/releases/tag/Jackett-0.8.490) and install it manually following the instructions from [here](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Application/How_to_install_applications_with_Package_Center#t2.3)
6) Report back.

**Comment by alxlaxv** [comment]
I can't deinstall Mono, I will try your steps.
How can I know which package to download?
It's a DS916+ INTEL Pentium N3710 8Go RAM
Thanks

**Comment by m4tt075** [comment]
You want the braswell packages.

**Comment by alxlaxv** [comment]
1. Deinstall the Jackett version you have
DONE
2. (Ideally) deinstall Mono as well. If you have dependencies, and the package manager asks you to deinstall other packages first, don't do it for now, and just keep Mono instead.
NOT DONE because of dependancies
3. Download the appropriate Mono 5.8.0 package for your NAS model from here and install it manually following the instructions from here
DONE
4. Check whether you find the .mono folder within /usr/share now.
Still not...
5. Download the appropriate Jackett package for your NAS platform from here and install it manually following the instructions from here
DONE
6. Report back
Jackett is working fine now, Thanks.
How can I manage Mono and Jackett packages updates now? It will remains manual?

Thanks

**Comment by m4tt075** [comment]
Glad it is working, but I would like to dive deeper on 4. as the `.mono` folder should be there now and as I would not expect your setup to work without the certificates being stored there. Please `ssh` into your box again and do the following:

1. Execute `sudo su -` and enter the admin (= root) password to obtain root privileges.
2. Execute `cd /usr/share` followed by `ls -la` and share the output.
3. If the `.mono` folder is really not there, execute
`/var/packages/mono/target/bin/cert-sync /etc/ssl/certs/ca-certificates.crt` 
and share the output.
4. Repeat 2. and share the output. 

No worries about future updates: The DSM package manager will ask you to update `Mono` once a more up-to-date version will be published via SynoCommunity. The new `Jackett` version is able to update itself. When you connect to the `Jackett` web-interface there is some `update` or `upgrade` button. Click it and give it some time (a couple of minutes, you won't get any kind of messages). When you reload the web-interface you should see an updated version number at the very bottom of the page.

**Comment by abienz** [comment]
I had the same issue and following step 3 from @m4tt075 last comment fixed the issue for me.

Running version 5.4.1.6-9 of Mono and 0.8.670.0 of Jackett

**Comment by m4tt075** [comment]
@abienz Same question to you: Have you updated your DSM recently, i.e. before `Jackett` "broke" or did you change anything else? Or was it a clean install?

**Comment by abienz** [comment]
I think it was last weekend I updated to the latest DSM I hadn't checked
anything until today and noticed it was broken.

**Comment by m4tt075** [comment]
Thanks.
@ymartin59 Yep, I think your hypothesis is confirmed. But I have not been able to figure out how to patch the sources to make it work. How about adding a check for the `/usr/share/.mono` folder into `pre_start` and execute `cert-sync` conditionally on that?

**Comment by ymartin59** [comment]
@m4tt075 That is a relevant work-around... but I really want to try to fix path in sources first

**Comment by ymartin59** [comment]
I inspect sources search for handling of `.mono/keypairs`: 
- mcs/class/Mono.Security/Mono.Security.Cryptography/KeyPairPersistence.cs:246
- external/corefx/src/System.Runtime.Extensions/src/System/Environment.Unix.cs:101
May you please give a try to return `/var/packages/mono/target/var/` ?

Another option may to set `HOME` to `/var/packages/mono/target/var/` and prepare `.config/mono` there. `cert-sync --user` should be used then. BUT it prevents an application to relocate `HOME` for its own needs.

**Comment by m4tt075** [comment]
@ymartin59 I fully agree and think patching the sources would be the best way forward, only, I'm not able to do it. I learned coding on Locomotive Basic and Turbo Pascal. The mono code is way above my head. It would take me ages to get it right and would require me to recompile the whole package all the time. I cannot do that efficiently and, thus, don't want to spend the time.

I went upstream though and we are not alone. Others have requested an environment variable to specify the store location. The related `mono` issue is [here](https://github.com/mono/mono/issues/6388). Following my request, @baulig has kindly opened a [new issue](https://github.com/mono/mono/issues/7019), which should provide that option eventually. I will be happy to watch these developments and implement them here in terms of patches, once they are available, but I'm not in a position to solve this from scratch myself. I'm sorry, but if anyone else is able and willing to pick it up, more than wellcome...

**Comment by kaso17** [comment]
I'm not a syno expert but I assume that the OS is wiping /usr/share/.mono is somehow a problem?
Maybe adding a sym link check/creating script in the post-update and pre-start sections might help to workaround the problem?

**Comment by kaso17** [comment]
@ymartin59 the keypairs stuff shouldn't be a problem (at least for jackett). The file should already be stored in the Jackett HOME.

To change the /usr/share path for the the root certificates at /usr/share/.mono you probably only have to adjust the SpecialFolder.CommonApplicationData constant here:
https://github.com/mono/mono/blob/d1649e90fcb80410b888edd6e5d20493c08e9a56/mcs/class/corlib/System/Environment.cs#L742

**Comment by ymartin59** [comment]
@m4tt075 @kaso17 I do not understand why mono code evaluate which operating system it is running on at "runtime". It does not make sense. These settings like os specific tuning and path should be compilation-time configuration options.
I will propose a PR to set location into `var` package specific location to be synology compliant. Then you may rebuild and submit packages to testers to validate it fixes troubles.

**Comment by ymartin59** [comment]
I just wonder if it makes sense to redirect `/usr/share/templates/` and `/usr/share/mime` too ?

**Comment by ymartin59** [comment]
Here is PR #3154 - I have just tested quickly in xpenology 5.2 but seems OK

**Comment by Safihre** [comment]
Test-builds of @ymartin59's new version available here: #3138.
Tested it on my NAS and did not notice anything strange.

**Comment by ymartin59** [comment]
@alxlaxv @abienz May you please manually install latest Mono 5.8 package from #3138 and report some feedback... at least after next DSM update.

**Comment by ymartin59** [comment]
@alxlaxv Just published Mono and Jackett update in repository. May you please update and report feedback.

**Comment by alxlaxv** [comment]
Seems fine. I will let you know if something changes.

**Comment by m4tt075** [comment]
OK, I think we can close this issue. Please just open a new one if you should run into trouble.

**Comment by alxlaxv** [comment]
Hello there,

I just did a DSM update yesterday + all packages you pushed.
Today I can run jackett but few indexers don't work in Jackett.
The answer i got is here: https://github.com/Jackett/Jackett/issues/2649 

Seems to be the same problem, kind of.

**Comment by ymartin59** [comment]
May you please generate file list with `find /var/packages/mono/var/ > /tmp/mono-var-content.log` and upload produced log file here.

**Comment by alxlaxv** [comment]
I have not the last var folder.
Only:
- conf
- enabled
- etc
- INFO
- scripts
- target

**Comment by Safihre** [comment]
Try this path:
/var/packages/mono/target/var

**Comment by alxlaxv** [comment]
Here we go: [mono-find.log](https://github.com/SynoCommunity/spksrc/files/1770140/mono-find.log)

**Comment by Safihre** [comment]
Problem solved: https://github.com/Jackett/Jackett/issues/2649#issuecomment-369556852
Unrelated to Synology package.
