### ISSUE TITLE
[bug] python 2.7.14 build patches cross/pyyaml/setup.cfg

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#3159]
When building python, the cross/pyyaml/setup.cfg got patched with the arch specific library path in the arch specific staging folder.
The patch replaces `@STAGING_INSTALL_PREFIX@` in the setup.cfg file.
If you continue to build python for further archs (e.g. with all-supported), the folloing python spks have all the libraries of the first built arch in the package, since `@STAGING_INSTALL_PREFIX@` does not exist anymore in the setup.cfg file.
I Suppose this is the cause of several python 2.7.14 issues here (#3111, #3109, #3107)
(the library folder contains arch specific *.pc and *.so files).

@safihre as you introduced the `library_dirs=@STAGING_INSTALL_PREFIX@/lib` in setup.cfg
Maybe a solution would be to copy the setup.cfg to the staging folder to patch it for each arch and use this file...

As a workaround until fixed, we have to revert the modified setup.cfg after each build.

**Comment by Safihre** [comment]
Damn, you are right and it's stupid.
Will fix this.
@ymartin59 Seems you [only released `88f628x`](https://synocommunity.com/package/python) so that should be fine (weird it's listed twice). Just do a `make clean` before next builds.

**Comment by Safihre** [comment]
@ymartin59 Sorry, I meant do a `git reset --hard origin/master` to correct the wrong patch, a `make clean` of course isn't enough.
I also updated the Python SPK_REV like you mentioned yesterday :)

**Comment by ymartin59** [comment]
@Safihre Architecture is listed twice probably because of DSM 5.2 and DSM 6.1 builds. `spkrepo` interface is quite too simple - it should be reworked to list details about packages and also provide access to old revisions.

**Comment by Safihre** [comment]
No I just commited directly to `master` since it's such a simple change. Was that bad?
I can make PR's of everything if you prefer for any future things? 👍
