### ISSUE TITLE
Transmission 2.93 not available

### ISSUE THREAD

**Issue by Devillegi** [SynoCommunity/spksrc#3169]
_Package Name:_ Transmission
_Package Version:_ 2.92/2.93

I see a closed pull request for Transmission 2.93, but available in the repo is only 2.92. 2.93 fixes important vulnerabilities and has been available for over one month.

Considering the severity of the vulnerabilities in 2.92, I and I'm sure all other users of this package would greatly appreciate an updated version.
Thanks a lot in advance!

**Comment by Safihre** [comment]
Use the test-release listed in #3138 and install it manually.
As soon as it's released officially it will auto-update to the official version.
