### ISSUE TITLE
Request: Sonarr for apollolake (x64)

### ISSUE THREAD

**Issue by Haringstad** [SynoCommunity/spksrc#3174]
Hello y'all! I first want to thank you for the hard work you all are doing to make great software available to our systems! I don't think that I have to request a "New" software Package, because it is already in the Repo for other architectures.

I have a request, is it possible to make Sonarr available for the apollolake (x64) architecture? That would make me so incredible happy!

Thanks in advance!

**Comment by Safihre** [comment]
You are in luck, it's pretty much done!
Release-candidate packages are available for download here: #3138
These will auto-update to the official SynoCommunity release after it comes out.

**Comment by Haringstad** [comment]
Thank you so much! Will install, and inform if I find any issues!

Regards,

Jacco van Koll
