### ISSUE TITLE
Couchpotato Stops immediately after run 

### ISSUE THREAD

**Issue by arabianhex** [SynoCommunity/spksrc#3184]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Couchpotato
_Package Version:_20180226-7

_NAS Model:_DS1515+
_NAS Architecture:_
_DSM version:_DSM 6.0.3-8754 Update 5

### Expected behavior
Tell us what should happen
Couchpotato should run without stopping
### Actual behavior
Tell us what happens instead
after running couchpotato it stops immediately
log is attached below
[error.log](https://github.com/SynoCommunity/spksrc/files/1767153/error.log)

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Safihre** [comment]
From the log it says:
```
raise IOError("Storage doesn't exists!")
```
If I Google that it seems the database is corrupted, which seems to match your experience that it just suddenly stopped.
https://github.com/needo37/couchpotato/issues/7

So I would suggest you try and remove the `database` folder:
```
sudo rm -rf /volume1/@appstore/couchpotatoserver/var/database
```
And then start it again.

**Comment by arabianhex** [comment]
You are the man my Friend its working again 💯 can i send you a US amazon gift card for your help

**Comment by Safihre** [comment]
Hahah, you can always make a little donation to SynoCommunity on the main website.
Mostly glad it's not our new package system but a couchpotato problem  😀

**Comment by arabianhex** [comment]
Done 💃
