### ISSUE TITLE
cannot install nzbhydra, phyton is missing

### ISSUE THREAD

**Issue by silv3r23** [SynoCommunity/spksrc#3187]
### Setup
_Package Name:_ nzbhyrda
_Package Version:_ -

_NAS Model:_ DS418j
_DSM version:_ DSM 6.1.5-15254 Update 1

### Actual behavior
unable to install nzbhydra, while "phyton" (2.7) nor "pyhton3" is installed. sabnzbd works fine with pyhton (2.7)

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

![image](https://user-images.githubusercontent.com/28316411/36839005-faa0591e-1d40-11e8-8aa3-4e75da844aa2.png)

![image](https://user-images.githubusercontent.com/28316411/36839108-5bfba1fa-1d41-11e8-8287-c40608388e22.png)

**Comment by Safihre** [comment]
Are all these packages from the testing release, or from the official repo? 
Unfortunately they can't really be combined.

**Comment by silv3r23** [comment]
@Safihre Python and Python3 are from the stock repo. nzbhydra is from community repo, but neither can I install nzbhydra (nzbmegasearch also) nor I can find a python package within the community repo.
![image](https://user-images.githubusercontent.com/28316411/37138441-56b65424-22aa-11e8-8932-f32917d134e0.png)
![image](https://user-images.githubusercontent.com/28316411/37138466-6e0b49cc-22aa-11e8-88a8-b85cd1973172.png)

**Comment by silv3r23** [comment]
I installed nzbhydra from #3138 manually and Git + Python from **stock** repo. It works, thanks!

**Comment by DrTrustfate** [comment]
I have a new Synology DS918+ running DSM 6.1.5-15254 Update 1. I have added the SynoCommunity repo. My ultimate goal is to install SickRage. Just as some people have stated, I am unable to install it and get a message that python is missing or python 2.7.9 or later is needed. I have tried to install NZBHydra and other packages named on this thread. I have also tried with Python Module and Python3 installed from the Developer Tools.

Please help.
Thanks!

**Comment by Safihre** [comment]
If you have read this thread then you should have seen that for now the surest way to get it to work is get all packages from the list in #3138. All of the packages.

**Comment by DrTrustfate** [comment]
Thanks for your quick response Safihre. I did read that and I did try those packages. All of which said that it wasn't compatible with my DSM version (see below). Online I read that my architecture is the apollolake (x64) for my DS918+. I didn't see that architecture explicitly listed on that link. Would you be able to send me links to the exact packages that I need to install for my model? Sorry for the hassle, I have tried everything that I know of. 

![image](https://user-images.githubusercontent.com/17515930/37242801-39d7810e-243d-11e8-85f9-7f1ed3562cc8.png)

Thank you,

**Comment by Fairlane56** [comment]
Hi, first of all: Thank you for this forum. It´s fantastic! Great job!

I have an new 218+ (apollolake) and I have exactly the same problem as **DrTrustfate**. It´s not possible to install because  an error massage pops up "_..not supported with my DSM version". I also have tried everything what I know. Could someone help us here.... Thanks!

**Comment by Safihre** [comment]
Be careful, there is the `x64-6.1` and `x64-5.2`. Make sure to download the correct one for your DSM version.

**Comment by DrTrustfate** [comment]
Thanks. I tried them all. :) Could you provide a direct link to the one that you think will work for my version? I don't see the x64-6.1 that you mentioned. 

Again, thank  you.

**Comment by Safihre** [comment]
https://github.com/Safihre/spksrc/releases/download/python-all/python_x64-6.1_2.7.14-18.spk

**Comment by Fairlane56** [comment]
Thank you very much! It works!

**Comment by DrTrustfate** [comment]
Thanks so much Safihre. That is working perfectly!
