### ISSUE TITLE
Transmission 2.93

### ISSUE THREAD

**Issue by USRGH** [SynoCommunity/spksrc#3188]
Hello,
when will be available 2.9.3 in package? Some torrent trackers announced they will ban 2.92 version.

Thank you.

**Comment by Safihre** [comment]
It's been published this morning, should come to your device soon.

**Comment by punkrockjack** [comment]
I got the update, but it appears to try to be loading its settings.json file from the wrong location:

`JSON parse failed in /volume1/@appstore/transmission/var//settings.json at pos 0: SPECIAL_EXPECTED -- remaining text "d13:activity-dat"
`

There's an extra `/` in the path there, after `var`. How do I fix the path?

**Comment by Safihre** [comment]
I don't think that slash matters, also looking at the error it just seems like it doesn't understand the json format for some reason.
If it couldn't open the file, it would have said so.

**Comment by USRGH** [comment]
Got this update uesterfay, it updates without problems. Seems it works fine, thank you

**Comment by punkrockjack** [comment]
@Safihre I tried to `cat` the settings file, and the output looked like garbage. Is that normal? Is there anyway for me to salvage this install (like grabbing a fresh settings file)?

**Comment by Safihre** [comment]
Seems the program might have been shutdown at a wrong moment, very unfortunate of course..

**Comment by maxromanovsky** [comment]
There's no build for armada38x: https://github.com/SynoCommunity/spksrc/issues/3213
