### ISSUE TITLE
Start Stop Status Script BROKEN After Transmission Update

### ISSUE THREAD

**Issue by coolboiime** [SynoCommunity/spksrc#3194]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Transmission
_Package Version:_ 2.93-13

_NAS Model:_ DS3615xs
_NAS Architecture:_ ARM
_DSM version:_ 5.2-5967 Update 6

### Expected behavior
The script should start and stop Transmission

### Actual behavior
Terminal shows "sh: 6: unknown operand"

### Steps to reproduce
_1._ Login to SSH
_2._ /var/packages/transmission/scripts/start-stop-status stop
_3._ "sh: 6: unknown operand"

**Comment by coolboiime** [comment]
Found workaround:

Instead of using the start-stop-status script, I will be using the command line package manager.

synopkg start transmission
synopkg stop transmission
synopkg status transmission

**Comment by ymartin59** [comment]
Sorry for this trouble. I probably "missed" testing on DSM 5.2 before publishing. I am investigating

**Comment by Safihre** [comment]
You cannot call the script like this.
This is not a bug. 
The script is supposed to be called from the Package Center by synology, it doesn't work from command line due to all the missing environment variables.

**Comment by ymartin59** [comment]
@Safihre Please let requester answer my investigation query. `synopkg` command is underlying support (based on upstart if I guess right) for which DSM Package Center is just a UI.

**Comment by Safihre** [comment]
And he's saying these commands do the job, so it's fixed.

**Comment by coolboiime** [comment]
@ymartin59 Transmission runs normally. It's just when I call the script, it doesn't actually do anything. This didn't happen when the version was 2.92-12.

@Safihre Ah, no wonder. I was doing it wrong the whole time. Cool! I'll update my script and have Package Manager call the script instead.

Gonna close it now. Thanks, guys!

**Comment by ymartin59** [comment]
@Safihre Sorry about my mistake. I misunderstood the situation and I have not noticed the reported command line `/var/packages/transmission/scripts/start-stop-status stop`, which is wrong of course.
