### ISSUE TITLE
Deluge 1.3.15-9 not starting - OpenSSL problem

### ISSUE THREAD

**Issue by tonabnehmer** [SynoCommunity/spksrc#3201]
### Setup
_Package Name:_ Deluge from #3138 
_Package Version:_ 1.3.15-9

_NAS Model:_ DS215j
_NAS Architecture:_ armada375
_DSM version:_ DSM 6.1.5-15254 Update 1

--

### Expected behavior
Deluge starting

### Actual behavior
Deluge not starting, with Python from #3138, version: 2.7.14-18 see attached log
Seems like it does not find the imports for openssl or crypto packages? 

#### Package log
```
[INFO    ] 17:05:30 configmanager:70 Setting config directory to: /volume2/@appstore/deluge/var/
[ERROR   ] 17:05:31 main:248 /var/packages/python/target/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: pthread_atfork
Traceback (most recent call last):
  File "/volume2/@appstore/deluge/env/lib/python2.7/site-packages/deluge-1.3.15-py2.7.egg/deluge/main.py", line 240, in start_daemon
    from deluge.core.daemon import Daemon
  File "/volume2/@appstore/deluge/env/lib/python2.7/site-packages/deluge-1.3.15-py2.7.egg/deluge/core/daemon.py", line 47, in <module>
    from deluge.core.rpcserver import RPCServer, export
  File "/volume2/@appstore/deluge/env/lib/python2.7/site-packages/deluge-1.3.15-py2.7.egg/deluge/core/rpcserver.py", line 47, in <module>
    from twisted.internet import ssl, reactor, defer
  File "/var/packages/python/target/lib/python2.7/site-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
  File "/var/packages/python/target/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/var/packages/python/target/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/var/packages/python/target/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/var/packages/python/target/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /var/packages/python/target/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: pthread_atfork

```

**Comment by Safihre** [comment]
It's worse than missing, there's a cross compile problem problem: `undefined symbol: pthread_atfork
`.
I tried something else, could you try installing this version?
https://github.com/Safihre/spksrc/releases/tag/python-retest2

**Comment by tonabnehmer** [comment]
Thanks for the quick update. Reinstalled the python package, deluge still reports the same error.

**Comment by Safihre** [comment]
Google seems to [indicate](https://www.google.nl/search?q=undefined+symbol%3A+pthread_atfork&client=ms-android-samsung&sourceid=chrome-mobile&ie=UTF-8) that it's a problem in the compilation of OpenSSL.
Have to dig deeper to find what switches are in the wrong order :/

**Comment by Safihre** [comment]
@tonabnehmer Do you have time to test another one for me?
https://github.com/Safihre/spksrc/releases/tag/python-retest3

This will be a trial-and-error process, since I don't have a device with `armada375`.

**Comment by tonabnehmer** [comment]
Sure no problem, tried with new python package, but the error remains...

**Comment by Safihre** [comment]
I now tried to compile with an older toolchain, could you see if this ones does something?
https://github.com/Safihre/spksrc/releases/tag/python-retest3

**Comment by kantjer** [comment]
FYI

I'm getting the exact same error in the log on my DS216PLAY
Package Name: Deluge and Python from #3138
Package Version: 1.3.15-9/2.7.14-8

NAS Model: DS216PLAY
NAS Architecture: STM STiH412 (Monaco)
DSM version: DSM 6.1.5-15254 Update 1

```
[INFO    ] 15:49:10 configmanager:70 Setting config directory to: /volume1/@appstore/deluge/var/
[ERROR   ] 15:49:11 main:248 /var/packages/python/target/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: pthread_atfork
Traceback (most recent call last):
  File "/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-1.3.15-py2.7.egg/deluge/main.py", line 240, in start_daemon
    from deluge.core.daemon import Daemon
  File "/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-1.3.15-py2.7.egg/deluge/core/daemon.py", line 47, in <module>
    from deluge.core.rpcserver import RPCServer, export
  File "/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-1.3.15-py2.7.egg/deluge/core/rpcserver.py", line 47, in <module>
    from twisted.internet import ssl, reactor, defer
  File "/var/packages/python/target/lib/python2.7/site-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
  File "/var/packages/python/target/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/var/packages/python/target/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/var/packages/python/target/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/var/packages/python/target/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /var/packages/python/target/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: pthread_atfork
```

**Comment by Safihre** [comment]
And could you try the release I linked above?

**Comment by kantjer** [comment]
That's not complied for Monaco

**Comment by qbone** [comment]
I am also having the exact same problem.
**System:**
DS218play
Realtek RTD1296 SoC
DSM 6.1.5-15254 Update 1

Deluge 1.3.15-9 installed from https://github.com/SynoCommunity/spksrc/issues/3138
Python 2.7.14-18 - first installed from repo, and also tried installing it from https://github.com/SynoCommunity/spksrc/issues/3138

**Comment by tonabnehmer** [comment]
Tested the last version of python, error remains the same :/

**Comment by Safihre** [comment]
@ymartin59 could you un-publish Python again? Seems it's still bad :(

**Comment by ymartin59** [comment]
I have unpublished all architectures... users will have to re-install application packages.

**Comment by ymartin59** [comment]
@Safihre I just noticed I probably made a mistake with Python 2.7.14-18 for x64 architecture - I published compiled version for DSM 5.2. Question: is it expected it should run on DSM 6 too (because does not rely on libstdc++) ?

**Comment by qbone** [comment]
If you compile a version of 2.7.14-18 for RTD1296 x64 I would be happy to test, if the compilation was the problem :)

**Comment by qbone** [comment]
Hey guys, I have an update on the issue.

I just returned my DS218play and got a DS218+ instead. For various reasons. Anyways, I thought I remembered that Deluge was working fine for a brief moment, on the DS218play, but never got it to work again.
I have now just freshly installed my new NAS, and I havent updated anything. It is running DSM 6.1.5-15254 and I have NOT updated to "Update 1".
I installed Deluge and Python from https://github.com/SynoCommunity/spksrc/issues/3138 and both are running fine now.
It seems "Update 1" is ruining it, so I will hesitate to update my DSM.
I don't know if you can use this information, or already knew it. But maybe it can help you locate the issue :)

Ask away, if you need more information og need me to test something.

**Comment by Safihre** [comment]
@qbone Unfortunately (for us) the reason is simpeler: your DS218play is `rtd1296` while the DS218+ is a `x64`. That's a "safe" arch that is easiest. 
https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model

**Comment by qbone** [comment]
Arh shoot. I thought I was on to something :)
I have updated my DSM and it is all still running fine - so I rushed a bit to conclusions. My bad.

**Comment by ymartin59** [comment]
@pbone Here is a test package for rtd1296/DS218play, I hope include proper fix for cryptography / openssl / pthread to work: http://dl.free.fr/kwT4PmoNE
May you please install it manually and test again Deluge to confirm it fixes this issue?

**Comment by DownbeatK** [comment]
@ymartin59 I installed that on my DS418/RTD1296 and Deluge still won't run.

**Comment by ymartin59** [comment]
@tonabnehmer Deluge with fixed Python for ARM architecture have been published. Please confirm.

**Comment by tonabnehmer** [comment]
@ymartin59 Can confirm working. Thanks for the update. Issue can be closed.
