### ISSUE TITLE
Mono/Sonarr Debug high cpu

### ISSUE THREAD

**Issue by jonskoglund** [SynoCommunity/spksrc#3202]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Mono
_Package Version:_ 5.8.0.108-11

_NAS Model:_ DS414
_NAS Architecture:_ Armada XP MV78230
_DSM version:_ DSM 6.1.5-15254 Update 1

--
### Expected behavior
Normal CPU load. 

### Actual behavior
High CPU load with spikes in the range of 90-115%
![cpu high](https://user-images.githubusercontent.com/593324/36966662-ca78604a-205d-11e8-8adb-86402a4a5337.png)

### Steps to reproduce
_1._ Install Mono and Sonarr SynoCommunity packages with DSM Package Center
_2._ Make sure both are running after installation.
_3._ Update Sonarr from the Web UI: System>Updates

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
-- Can't find any log for Mono. Only install.log in location /usr/local/mono/var/. Any tips?
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Safihre** [comment]
Yes I saw this too, but this only happens after Sonarr restarts itself after an update.
When we start the package it's not run with debug.

**Comment by jonskoglund** [comment]
Restarting Sonarr doesn't fix the issue. I'm looking for a way to restart Mono form the terminal. DSM doesn't let me stop it from the DSM Package Center.

**Comment by Safihre** [comment]
I am able to shut it down from Package  center, it just takes a while. You can also use the command line `synopkg` command.
Not sure where this Debug is coming from, it's not anywhere in our package code. Maybe it's in the `mono` somewhere? Do you know @m4tt075 / @ymartin59?

**Comment by m4tt075** [comment]
Hmh, strange. I don't think this comes from `mono`, but I could reproduce what you wrote, @Safihre . On clean install `Sonarr` starts `mono` without `--debug` option, after updating it automatically restarts with `--debug` enabled. Stopping and restarting `Sonarr` again from the DSM package center, and the `--debug` option is gone again. @jonskoglund You don't really stop and start `mono`. It is started by the applications using it, `Sonarr` in this case. Maybe just try to stop and start it from the package center again?

**Comment by jonskoglund** [comment]
@Safihre Unfortunately the debug process didn't disappear after shutting down the Sonarr for more than 12 hours. @m4tt075 I will wait for an update of Sonarr. In the mean time is there a way to kill the  process from terminal?

**Comment by jonskoglund** [comment]
I can kill the process with: `kill PID` in my case `kill 7881` But it starts again within a few seconds. And Sonarr package is stopped. I will wait for the next update. At least this killing lowers the CPU load for the time being.

**Comment by Safihre** [comment]
Nothing will change with next updates if it's not reported. 
Maybe you should complain on the Sonarr forums?

**Comment by jonskoglund** [comment]
I will ;-)

**Comment by Safihre** [comment]
I see they even write in the Wiki that it should be used with `--debug`. Strange.
