### ISSUE TITLE
[Package Request] tmux, htop and ncdu for DS118 (synology_rtd1296)

### ISSUE THREAD

**Issue by koegs** [SynoCommunity/spksrc#3203]
It would be nice if the packages tmux, htop and ncdu could be compiled for the DS118

_NAS Model:_ DS118
_NAS Architecture:_ rtd1296
_DSM version:_ DSM 6.1.5-15254 Update 1

**Comment by Safihre** [comment]
@ymartin59 Could you give some feedback if you want to compile these packages for the new archs? 
They don't need any service-approach (command-line utils) and since progress on #2261 is non-existing, maybe we should just make them available for the new archs?

**Comment by ymartin59** [comment]
@Safihre You're right, these "CLI" oriented packages in my mind will not be ready soon...
@koegs Published, but without any testing. So please report any feedback about them.

**Comment by koegs** [comment]
ncdu and tmux are working. :+1: 

htop is already built in and did not know that so i did not test the package from synocommunity.
