### ISSUE TITLE
ffmpeg vaapi intel braswell? native / cross package ?

### ISSUE THREAD

**Issue by MrSpoocy** [SynoCommunity/spksrc#3207]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ ffmpeg
_Package Version:_ master

_NAS Model:_ DS416Play
_NAS Architecture:_ braswell-x64
_DSM version:_ 6.1

Hi everyone,

currently i try to extend the ffmpeg pack with vaapi support for intel. But the HOW-TO is incomplete. I can't find anything about "native" package. What is the difference to "cross"?

I build successfully libdrm-intel, cmrt, libva on Ubuntu 16 native. But when i try to do it with spksrc  there is a huge dependence chain. Do i really have to implement every dependence chain with own cross/XY ?

E.g. libpicaccess, libdrm2, libc6, lib ...

**Comment by ymartin59** [comment]
I wish you good luck.. I have started that path and run away for the main reason that I will not be able to deliver such support for any other platform than Intel ones. And loading an additional kernel module is not piece of cake. That is why I suspended investigation about vaapi: https://github.com/ymartin59/spksrc/issues/6

**Comment by MrSpoocy** [comment]
What about my question native vs. cross? I think every user with a Intel Synology will be happy about vaapi. Plex & Synology was able to build a ffmpeg with vaapi. We can do it! ;)

**Comment by cytec** [comment]
The difference between native and cross is that native is build natively on the build box and will never ever even come close to your DS... so basically native is stuff you'll need to have on you Buildbox in order to be able to build some of the cross packages... 

cross packages are packages which are compiled using the coresponding synology toolchains of the selected arch

Example: go
There is go native, which installs go on the buildbox and bootstraps it so you'll have a working compiler to create the syncthing package.

**Comment by m4tt075** [comment]
@MrSpoocy I like your attitude! Synology publishes their sources, see here for instance:
https://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/22259branch/apollolake-source/
It contains `ffmpeg`. If you log into your NAS, you can get the compile options from the binary, but you probably know this already. Go for it...    👍

**Comment by Safihre** [comment]
@m4tt075 so why can't we use it?

**Comment by m4tt075** [comment]
@Safihre They use very old versions (they are on 2.7.x), and depending on the toolchain they are heavily patched. I had the ambition to look into evansport HW support some months ago. Agreed, with proprietary HW decoder that was probably the worst case to start. Anyways, I lost half of my vaccation and the empathy of my wife and my kids in the process. More recently, I felt already very brave and proud to find the `rtd` fixes. Now I'm still struggling to get this bloody `TVH` package out of the door. Getting a reliable DSM6 compatible `TVH´ version was the very reason I engaged in all of this `spksrc´ stuff. Crikey, probably two years ago now...  :smirk:

**Comment by ymartin59** [comment]
@MrSpoocy What are your clues to say Plex and Synology uses VAAPI? I really doubt Synology backported VAAPI to such an old FFmpeg 2.7 version instead on upgrading it - according to https://github.com/FFmpeg/FFmpeg/blob/master/Changelog VAAPI is first mention in 2.8 version.

**Comment by ymartin59** [comment]
@m4tt075 Same history here - came for openHAB and even not started that task - my wife is already angry. SynoCommunity package set is almost a small Linux distribution on its own and requires specific competencies for each application - really hard to maintain with such a small team. So please have some rest and restrict your weekly workload...

**Comment by m4tt075** [comment]
@ymartin59 Looking at the workload carried, I guess that last statement should probably rather go to @Safihre and you...  :smiley:

**Comment by MrSpoocy** [comment]
On my Synology was some version ago from Video Station in the bin folder 2 files ... ffmpeg and ffmpeg-vaapi. ffmpeg was flag with version 2.7.1 and the file ffmpeg-vaapi show this ..


> /volume1/@appstore/VideoStation/bin/ffmpeg-vaapi
> ffmpeg version VideoStation-2.3.1-1449-170515-107-g4278f9b Copyright (c) 2000-2017 the FFmpeg developers
> built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
> configuration: --prefix=/usr/pkg --incdir='${prefix}/include/ffmpeg' --arch=x86_64 --target-os=linux --cross-prefix=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-version3 --enable-encoders --enable-pthreads --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffplay --disable-ffserver --disable-doc --disable-devices --disable-bzlib --disable-altivec --enable-libmp3lame --disable-decoder=amrnb --disable-encoder=zmbv --cc=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc --disable-shared --enable-static --extra-cflags=-I/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/pkg/include --extra-ldflags=-L/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/pkg/lib --enable-yasm --enable-libx264 --enable-vaapi --enable-encoder=h264_vaapi --enable-encoder=libx264
> libavutil 55. 58.100 / 55. 58.100
> libavcodec 57. 89.100 / 57. 89.100
> libavformat 57. 71.100 / 57. 71.100
> libavdevice 57. 6.100 / 57. 6.100
> libavfilter 6. 82.100 / 6. 82.100
> libswscale 4. 6.100 / 4. 6.100
> libswresample 2. 7.100 / 2. 7.100
> libpostproc 54. 5.100 / 54. 5.100

and now there is no ffmpeg-vaapi anymore. But there is still under /volume1/@appstore/VideoStation/lib/libva/ follow files:

- VideoStation VideoStation 4266815 Feb 21 11:03 dri/i965_drv_video.so
- VideoStation VideoStation      21 Feb 21 11:03 libdrm_intel.so -> libdrm_intel.so.1.0.0
- VideoStation VideoStation      21 Feb 21 11:03 libdrm_intel.so.1 -> libdrm_intel.so.1.0.0
- VideoStation VideoStation  141472 Feb 21 11:03 libdrm_intel.so.1.0.0
- VideoStation VideoStation      23 Feb 21 11:03 libdrm_nouveau.so -> libdrm_nouveau.so.2.0.0
- VideoStation VideoStation      23 Feb 21 11:03 libdrm_nouveau.so.2 -> libdrm_nouveau.so.2.0.0
- VideoStation VideoStation   29083 Feb 21 11:03 libdrm_nouveau.so.2.0.0
- VideoStation VideoStation      22 Feb 21 11:03 libdrm_radeon.so -> libdrm_radeon.so.1.0.1
- VideoStation VideoStation      22 Feb 21 11:03 libdrm_radeon.so.1 -> libdrm_radeon.so.1.0.1
- VideoStation VideoStation   45275 Feb 21 11:03 libdrm_radeon.so.1.0.1
- VideoStation VideoStation      15 Feb 21 11:03 libdrm.so -> libdrm.so.2.4.0
- VideoStation VideoStation      15 Feb 21 11:03 libdrm.so.2 -> libdrm.so.2.4.0
- VideoStation VideoStation   70403 Feb 21 11:03 libdrm.so.2.4.0
- VideoStation VideoStation      15 Feb 21 11:03 libkms.so -> libkms.so.1.0.0
- VideoStation VideoStation      15 Feb 21 11:03 libkms.so.1 -> libkms.so.1.0.0
- VideoStation VideoStation   12451 Feb 21 11:03 libkms.so.1.0.0
- VideoStation VideoStation      22 Feb 21 11:03 libpciaccess.so -> libpciaccess.so.0.11.1
- VideoStation VideoStation      22 Feb 21 11:03 libpciaccess.so.0 -> libpciaccess.so.0.11.1
- VideoStation VideoStation   33251 Feb 21 11:03 libpciaccess.so.0.11.1
- VideoStation VideoStation      16 Feb 21 11:03 libudev.so -> libudev.so.1.3.5
- VideoStation VideoStation      16 Feb 21 11:03 libudev.so.1 -> libudev.so.1.3.5
- VideoStation VideoStation   69661 Feb 21 11:03 libudev.so.1.3.5
- VideoStation VideoStation      21 Feb 21 11:03 libva-drm.so -> libva-drm.so.1.4000.0
- VideoStation VideoStation      21 Feb 21 11:03 libva-drm.so.1 -> libva-drm.so.1.4000.0
- VideoStation VideoStation    8315 Feb 21 11:03 libva-drm.so.1.4000.0
- VideoStation VideoStation      17 Feb 21 11:03 libva.so -> libva.so.1.4000.0
- VideoStation VideoStation      17 Feb 21 11:03 libva.so.1 -> libva.so.1.4000.0
- VideoStation VideoStation  127594 Feb 21 11:03 libva.so.1.4000.0
- VideoStation VideoStation      21 Feb 21 11:03 libva-tpi.so -> libva-tpi.so.1.4000.0
- VideoStation VideoStation      21 Feb 21 11:03 libva-tpi.so.1 -> libva-tpi.so.1.4000.0
- VideoStation VideoStation    4147 Feb 21 11:03 libva-tpi.so.1.4000.0

I think, yes Synology use vaapi with older ffmpeg version.

**Comment by ymartin59** [comment]
OK. I wonder if Synology refrains to upgrade ffmpeg because of licensing troubles... Our best option may be to link ffmpeg to VideoStation existing libraries "libva*.so", in order to avoid to build again all the dependencies from ground up.

**Comment by hgy59** [comment]
I am working on the vaapi for ffmpeg and just got the first sucessfully build.
Following are the new features listed with `ffmpeg -decoders` and `ffmpeg -encoders` for the `--enable-vaapi` configuration running on my DS918+ (built with: make arch-apollolake-6.1)

```
Encoders:
 V..... h263_v4l2m2m         V4L2 mem2mem H.263 encoder wrapper (codec h263)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)
 V..... h264_vaapi           H.264/AVC (VAAPI) (codec h264)
 V..... hevc_vaapi           H.265/HEVC (VAAPI) (codec hevc)
 V..... mjpeg_vaapi          MJPEG (VAAPI) (codec mjpeg)
 V..... mpeg2_vaapi          MPEG-2 (VAAPI) (codec mpeg2video)
 V..... mpeg4_v4l2m2m        V4L2 mem2mem MPEG4 encoder wrapper (codec mpeg4)
 V..... vp8_v4l2m2m          V4L2 mem2mem VP8 encoder wrapper (codec vp8)
 V..... vp8_vaapi            VP8 (VAAPI) (codec vp8)
 V..... vp9_vaapi            VP9 (VAAPI) (codec vp9)

Decoders:
 V..... h263_v4l2m2m         V4L2 mem2mem H.263 decoder wrapper (codec h263)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 decoder wrapper (codec h264)
 V..... mpeg1_v4l2m2m        V4L2 mem2mem MPEG1 decoder wrapper (codec mpeg1video)
 V..... mpeg2_v4l2m2m        V4L2 mem2mem MPEG2 decoder wrapper (codec mpeg2video)
 V..... mpeg4_v4l2m2m        V4L2 mem2mem MPEG4 decoder wrapper (codec mpeg4)
 V..... vc1_v4l2m2m          V4L2 mem2mem VC1 decoder wrapper (codec vc1)
 V..... vp8_v4l2m2m          V4L2 mem2mem VP8 decoder wrapper (codec vp8)
```
The additional encoders and decoders are exactly the same as reported by the VideoStation version.

So far I only added `libva`, `libva-drm`, `libdrm `and `libpciaccess`.
Now I am wondering whether the following libraries that where built, must be added to the package too - since they exist in the VideoStation libva folder. Maybe these are dynamically loaded at runime?
- libdrm_intel (intel specific DRM functions)
- libdrm_nouveau (nVidia specific DRM functions)
- libdrm_radeon (AMD Radeon specific DRM functions)
- libkms (API functions for kernel mode setting abstraction)

other libs of VideoStation that my build did not create: 
- libudev
- libva-tpi (libva third pary interface)

Maybe `libudev` and `libva-tpi` are used for VideoStation only.

How can I test that the vaapi really works?

**Comment by MrSpoocy** [comment]
Try to convert a video with ffmpeg. One time without -hwaccel and other time with. Normally you must see big difference in the time. But use a x264 video! Not every Synology support x265. 

https://trac.ffmpeg.org/wiki/Hardware/VAAPI

**Comment by hgy59** [comment]
@MrSpoocy Thank you for the tips. Found out, that it does not work yet (have to build the driver too: lib/dri/i965_drv_video.so). 
Already compared the ffmpeg 3.2.4 (synocommunity) without va vs. ffmpeg of VideoStation 2.4.0 with -hwaccel.
And the winner is SynoCommunity (204s vs 280s for a short full hd clip).
So I am looking forward to the ffmepg 3.2.4 with vaapi support.

**Comment by stefaang** [comment]
FYI, Emby also ships with a fully loaded mpeg binary (e.g. vaapi included).

**Comment by ymartin59** [comment]
VAAPI is now included in FFmpeg 4 packages. I consider it as closed.
