### ISSUE TITLE
Sonarr permissions no longer working with Sabnzbd

### ISSUE THREAD

**Issue by JZNine** [SynoCommunity/spksrc#3212]
Hi all, I am having permission problems since the latest Sonarr update, I am now getting the access denied errors on post download processing files provided by Sabnzbd. Any help would be greatly appreciated as I've tried everything I can see here, including a fresh Sonarr install, but still no luck.

I have set permissions on the download location to RW for sc-download, but Sabnzbd seems to always set downloads to the Users group. 

### Setup
_Package Name:Sonarr
_Package Version:2.0.0.5153

_NAS Model:DS916+
_NAS Architecture:x64
_DSM version:6.2-23511

### Expected behavior
Sonarr picks up downloaded task from Sabnzbd, and renames and files correctly. 

### Actual behavior
Sonarr sends download to Sabnzbd, download completes, Sonarr fails to process with an access denied error

### Steps to reproduce
1: Select wanted episode to download and send to Sabnzbd (manually or automatically)
2: Let download
3: Check in Sonarr for error

#### Package log
Import failed, path does not exist or is not accessible by Sonarr: /volume1/media/Videos/TV/This.Country.S02E02.Threatening.Letters.720p.iP.WEB-DL.AAC2.0.H.264-RTN-Obfuscated.1/fdef9d629ed74c96a552581cdcc7cac2.mkv
![image](https://user-images.githubusercontent.com/37171600/37138087-d0be7c2c-22fc-11e8-9179-a73f3a6543f8.png)
![image](https://user-images.githubusercontent.com/37171600/37138131-fd18a07c-22fc-11e8-98fd-9138a5311886.png)

**Comment by GoodOmens83** [comment]
Getting similar issues.

**Comment by ymartin59** [comment]
May I ask you to please test this new package http://dl.free.fr/h4mI2xmkm with a "fix tentative" ? Thank you in advance for your feedback

**Comment by JZNine** [comment]
Thanks. Still fails to process in Sonarr after downloading, unfortunately.

**Comment by ymartin59** [comment]
May you please review your Shared Folder permissions according to the following documentation: https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by JZNine** [comment]
Thanks for that comprehensive wiki article. After following that, Sonarr is now correctly processing, renaming and storing Sabnzbd downloads again.
