### ISSUE TITLE
Transmission 2.93 not available for armada38x

### ISSUE THREAD

**Issue by maxromanovsky** [SynoCommunity/spksrc#3213]
Transmission 2.93 not available for `armada38x`, but available for `armada370` & `armada375`:
https://synocommunity.com/package/transmission

**Comment by Safihre** [comment]
Seems same in #3208 @ymartin59, not build for all armada's.

**Comment by ymartin59** [comment]
Copy that. By the way, I have to re-publish Transmission with permission/ACL fix.

**Comment by Safihre** [comment]
@ymartin59 Do we have a fix? 🎉

**Comment by ymartin59** [comment]
@hgy59 Hello. Sorry to ask you such specific request - but may you please investigate if some of the following architectures armada370 armada375 armadaxp armada38x may be aggregated into a single compatible "armada" arch alias (the same way as for x64) ? Thank you in advance for your help

**Comment by Safihre** [comment]
@ymartin59 I doubt it, looking at the toolchain makefiles they seem to really have specific options.

**Comment by jasonmotec** [comment]
Thank you so much guys - it is now updated :)

By the way, for @mouski87 and @maxromanovsky - to refresh the Package Center to see the new updates... in Package Center, click on 'Community' to show all the packages coming from packages.synocommunity.com, then click on the 'Refresh' button, and this will then show all required packages that have updates

**Comment by maxromanovsky** [comment]
@jasonmotec, Mono & Sonarr got updated, but as for Transmission -  still no updates. And `armada38x` is still not in the list of supported arch: https://synocommunity.com/package/transmission

Still thank you very much though :)

**Comment by ymartin59** [comment]
Transmission suffers a blocking bug... so I consider wiser not to provide you with it before fixed
