### ISSUE TITLE
Permissions Issue Sonarr

### ISSUE THREAD

**Issue by forepj** [SynoCommunity/spksrc#3215]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Sonaar
_Package Version:_20180303-13

_NAS Model:_DS-1515+
_NAS Architecture:_
_DSM version:_DSM 6.1.5-15254 Update 1

### Expected behavior  Choose folder to import tv shows
Tell us what should happen  select folder from finder

### Actual behavior Cannot select folder
Tell us what happens instead 
Invalid request Validation failed:  -- Folder is not writable by user sc-nzbdrone

### Steps to reproduce
_1._I have given the shared folder volume1/video/tv shows r/w permission to sc-media and sc-download in Local Group via Control Panel and File Station  
_2._I have given the shared folder volume1/video/ r/w to sc-nzbdrone in  System internal user
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```Invalid request Validation failed:  -- Folder is not writable by user sc-nzbdrone
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here

**Comment by forepj** [comment]
Am I doing something wrong or should I wait for another update? I've uninstalled and reinstalled several times making sure to restart the NAS every time to no avail.  Other Syno packages SAB Transmission, Couchpotato, Headphones, Lazy Librarian are all currently up and running with r/w access to shared folders.

**Comment by ymartin59** [comment]
Please try to give full "read" access to `/volume1/video` to group `sc-download`... it should work. Please submit some screenshots to confirm how you set permissions.

**Comment by alxlaxv** [comment]
I had the same issue because I was pretty sure Sonarr and radio were in the “sc-media” group.. and as “users” has no rw access it went crazy.
Changing “sc-download” permissions fix it.

**Comment by forepj** [comment]
![28d31c3c-611d-4101-bca3-54e72158e65c](https://user-images.githubusercontent.com/8423708/37250092-6f3a0bac-24a9-11e8-953d-99fdb6705563.png)
![d0c230bb-eae7-4f52-bfe8-431dfa2a1b36](https://user-images.githubusercontent.com/8423708/37250093-6f63659c-24a9-11e8-816d-aa2b438add99.png)
![217aeead-4bec-4a5c-8bf1-0896771de363](https://user-images.githubusercontent.com/8423708/37250095-6f8c5308-24a9-11e8-8775-6f62d505fa27.png)
![shared volume1-video](https://user-images.githubusercontent.com/8423708/37250096-6fa7b800-24a9-11e8-9b9f-6e4edde91faa.png)

**Comment by forepj** [comment]
![tv shows](https://user-images.githubusercontent.com/8423708/37250141-7b9bb174-24aa-11e8-8737-94e00c69b4e6.png)

**Comment by forepj** [comment]
This is how I currently have permissions set for the /volume1/video/tv shows.

**Comment by forepj** [comment]
Sonaar won't write to any existing shared /volume1 folder, however it will write to new shared folder?

**Comment by forepj** [comment]
OK...Converted the folder to Windows ACL and now I have permissions.  Is this something I need to do with all shared folders that are associated with Synocommunity packages?

**Comment by ymartin59** [comment]
May you please review your permission settings according to following documentation: https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by forepj** [comment]
The new wiki is excellent stuff, however in my case not the root of my issue.  Not all of my shared folders associated with synocommunity packages had Windows ACL privileges enabled.  Once I converted all those shared folders, and then granted the correct permissions as described in the wiki I was then able to get Sonaar back to normal operation. Thanks for all you do!

**Comment by ymartin59** [comment]
Thanks for tip. @BenjV has provided screenshots so I added details on https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by Safihre** [comment]
Closing, documentation is good now.
