### ISSUE TITLE
I can't find Home Assistant package to install

### ISSUE THREAD

**Issue by egermano** [SynoCommunity/spksrc#3221]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Home Assistant
_Package Version:_ any ou latest

_NAS Model:_ DS216j
_NAS Architecture:_ ARM
_DSM version:_ DSM 6.1.5-15254 Update 1

### Expected behavior
When I access the Package Center to install Home Assistant, I go to Community tab and can find the package. The `beta` flag already set true. 

### Actual behavior
There is no Home Assistant listed in packages of Community tab.

### Steps to reproduce
_1._ Open Package Center
_2._ Open Community tab

**Comment by ymartin59** [comment]
Please refer to #3115

**Comment by ymartin59** [comment]
To anyone interested in Home Assistant, what are components you are interested ? Please comment in #3115
