### ISSUE TITLE
Make tmux available for x64 architecture on DSM 6?

### ISSUE THREAD

**Issue by pdblood** [SynoCommunity/spksrc#3223]
Can the tmux package be made available for x64 architectures? Specifically, I have a DS218+ running  DSM 6.1.5-15254 Update 1. It looks like tmux is currently only available for the rtd1296 architecture.

**Comment by ymartin59** [comment]
I missed tmux update because it has been committed/merged at the same time as zsh !
If I was aware there was a pending update, I would have not published only requested rtd1296.
Thanks for reporting.

**Comment by ralph** [comment]
I'm sorry that I don't know exactly how packages are published on http://packages.synocommunity.com, but as far as I can tell tmux is not available for the DS218+ yet.

Is there anything we can do, or do we just have to wait some more? Are there any code changes necessary? Or is it up to a contributor to release a new version that includes support for the DS218+?

Sorry for asking, I'm still new to the Synology universe, and tmux is such an essential tool for me.

**Comment by ymartin59** [comment]
`tmux` package is marked as "beta". Please check you have enabled "beta" packages: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#a-package-should-be-available-for-my-model-and-dsm-version-but-i-cant-find-it-in-package-center-what-do-i-do

**Comment by ralph** [comment]
Hi @ymartin59, that worked, thank you very much! 👍
