### ISSUE TITLE
Deluge not available on apollolake

### ISSUE THREAD

**Issue by CoolsJoris** [SynoCommunity/spksrc#3227]
Setup
Package Name: Deluge
Package Version: any

NAS Model: DS418play
NAS Architecture: Apollolake
DSM version: DSM 6.1.5-15254 Update 1

Expected behavior
I've added the http://packages.synocommunity.com/ as package source and enabled the beta versions but the deluge package doesn't shows on comunity section of packet manager.

**Comment by Safihre** [comment]
See #3138 for test packages for your platform.
Will be released on main repository after this testing-phase.

**Comment by CoolsJoris** [comment]
Oh now I get it, the apollolake is part of the 64x package. Thx bro!
