### ISSUE TITLE
Couchpotato: Permissione denied on start

### ISSUE THREAD

**Issue by hennesph** [SynoCommunity/spksrc#3228]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Couch Potato
_Package Version:_ 20141013-6

_NAS Model:_ DS418play
_NAS Architecture:_ INTEL Celeron J3355
_DSM version:_ DSM 6.1.5-15254 Update 1

### Expected behavior
Installed couchpotato automatically with all dependencies and it should start

### Actual behavior
couchpotato is not starting. Error displayed: "Der Paketdienst konnte nicht ausgeführt werden" / "The package service cannot be executed"
-> Permission denied, see log

### Steps to reproduce
_1._ Install couchpotato via packagemanager with all dependencies (happens automatically) 
_2._ Start manually or automatically 
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_ 
```
Insert the package log here
```
#### Other logs
2018/03/18 08:41:36 start couchpotatoserver 20141013-6 End start-stop-status start ret=[1]
2018/03/18 08:41:36 (system) trigger couchpotatoserver 20141013-6 Begin start-stop-status stop
CouchPotato is not running
2018/03/18 08:41:36 (system) trigger couchpotatoserver 20141013-6 End start-stop-status stop ret=[0]
2018/03/18 08:41:36 (system) trigger couchpotatoserver 20141013-6 Begin unload apparmor
2018/03/18 08:41:36 (system) trigger couchpotatoserver 20141013-6 End unload apparmor ret=[0]
2018/03/18 08:41:37 stop couchpotatoserver: begin to stop version 20141013-6
2018/03/18 08:41:37 stop couchpotatoserver: stop version 20141013-6 successfully, result 0
2018/03/18 08:41:37 start couchpotatoserver: start version 20141013-6 failed, result 272
2018/03/18 08:47:07 start couchpotatoserver: begin to start version 20141013-6
2018/03/18 08:47:07 start couchpotatoserver 20141013-6 Begin pre-load apparmor
2018/03/18 08:47:07 start couchpotatoserver 20141013-6 End pre-load apparmor ret=[0]
2018/03/18 08:47:07 start couchpotatoserver 20141013-6 Begin start-stop-status start
Starting CouchPotato ...
su: Permission denied
2018/03/18 08:47:08 start couchpotatoserver 20141013-6 End start-stop-status start ret=[1]
2018/03/18 08:47:08 (system) trigger couchpotatoserver 20141013-6 Begin start-stop-status stop
CouchPotato is not running
2018/03/18 08:47:08 (system) trigger couchpotatoserver 20141013-6 End start-stop-status stop ret=[0]
2018/03/18 08:47:08 (system) trigger couchpotatoserver 20141013-6 Begin unload apparmor
2018/03/18 08:47:08 (system) trigger couchpotatoserver 20141013-6 End unload apparmor ret=[0]
2018/03/18 08:47:09 stop couchpotatoserver: begin to stop version 20141013-6
2018/03/18 08:47:09 stop couchpotatoserver: stop version 20141013-6 successfully, result 0
2018/03/18 08:47:09 start couchpotatoserver: start version 20141013-6 failed, result 272

**Comment by Safihre** [comment]
The current version isn't DSM 6 compatible. Install the test release from #3138.
