### ISSUE TITLE
Octoprint and Anet A8

### ISSUE THREAD

**Issue by HubsiKU** [SynoCommunity/spksrc#3234]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Octoprint
_Package Version:_20160321-4

_NAS Model:_ DS214j
_NAS Architecture:_
_DSM version:_ 6

### Expected behavior
I have Run Octoprint in DSM 6 now it run but i cant connect to my printer. i need in Serialport: /dev/ttyUSB0

but i have only: /dev/ttyACM0

the Error message is:

Unhandled firmware error
The firmware reported an unhandled error. Due to that OctoPrint disconnected. Error: Connection error, see Terminal tab

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #3128.
