### ISSUE TITLE
[Package Request] dathttpd

### ISSUE THREAD

**Issue by piwi82** [SynoCommunity/spksrc#3235]
Name: **[dathttpd](https://github.com/beakerbrowser/dathttpd)**
Description: A P2P Web server for [Dat](https://datproject.org/) and HTTPS, with zero-config TLS.
Website: https://github.com/beakerbrowser/dathttpd
Software documentation: https://github.com/beakerbrowser/dathttpd/blob/master/README.md
Build/Installation documentation: https://github.com/beakerbrowser/dathttpd#getting-started
Source Code: https://github.com/beakerbrowser/dathttpd
License:  MIT License https://github.com/beakerbrowser/dathttpd/blob/master/LICENSE

**dathttpd** is like a _SyncThing_ or _Resilio Sync_ node for static web content. [Beaker](https://beakerbrowser.com/) is the Web browser that can handle the `dat://` protocol.
**dathttpd** is a node that can be hosted on a NAS, thus providing better availability of the content than Beaker.

**Comment by ymartin59** [comment]
Thanks for idea. But spksrc has no NodeJS support to cross-compile native NPM packages - which are often used in applications or their dependencies.
