### ISSUE TITLE
armv8 missing?

### ISSUE THREAD

**Issue by moooztar** [SynoCommunity/spksrc#3236]
Hi!

I have a new DS218Play in hope of installing SyncThing. I found the beta channel (GREAT WORK!) but cannot seem to find a version working (installing). DS218play - synology_rtd1296_ds218play armv8.

Any help in a compile? Would mean a lot! Thanks guys!!

**Comment by Safihre** [comment]
Still a work in progress. You can download the current test version in #3138.

**Comment by moooztar** [comment]
Thank you so much!!

**Comment by moooztar** [comment]
Sorry to ask: tried the link and still don't see the "armv8 download. Could you help me specifying the .apk name to use on DS218Play?

**Comment by Safihre** [comment]
rtd1296!

**Comment by moooztar** [comment]
Wonderful!! "It works out of the box". Is it safe to use this version as a sync client as of now or should I wait? I know the app can be buggy as it is not launched yet, but "if working" is it "safe to sync"?
