### ISSUE TITLE
NZBGet Update Corrupt

### ISSUE THREAD

**Issue by jeremysbrain** [SynoCommunity/spksrc#3237]
### Setup
Package Name: NZBGet
Package Version: 20180319-23

NAS Model: DSM713+
NAS Architecture: cedarview (x64)
DSM version: DSM 6.1.5-15254 Update 1

### Expected behavior
Package downloads and updates to version above

### Actual behavior
Package downloads, and I suspect fails a CRC check.  The message "The package file is corrupt.  Please download it again or contact the package deveolper.  Are you sure you want to continue?" is displayed.

### Steps to reproduce
Attempt to update from version 16.4-22 to version 20180319-23

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
nzbget-2018-03-20.log
Tue Mar 20 11:06:37 2018	INFO	Stopping, please wait...
Tue Mar 20 11:06:39 2018	INFO	Deleting lock file
Tue Mar 20 11:09:40 2018	INFO	nzbget 16.4 daemon-mode

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
synopkg.log attached
[synopkg.log](https://github.com/SynoCommunity/spksrc/files/1830649/synopkg.log)

Please let me know if there is any further information that would be useful.

**Comment by ymartin59** [comment]
Thanks for reporting. I tried to sign again published package but no luck, still in trouble. I have temporarily "unpublished" this version. It will be back I soon as I understood and fixed.

**Comment by kantjer** [comment]
FYI, on my DS216PLAY the update from 20180223-23 (#3138) to 20180319-23 did go without any problem.

**Comment by ymartin59** [comment]
@kantjer Thanks for your feedback. I confirmed DSM reports package is corrupted for both `x64` and `evansport` architecture when Package Center Settings is configured Trust Level to Synology Inc. and trusted publishers. I guess your settings is set to "any publisher" to allow you to install non-signed test/beta packages.

**Comment by kantjer** [comment]
Yes, my system is set to "any publisher"

**Comment by ymartin59** [comment]
Published again. Signature OK. Hope it is better

**Comment by jeremysbrain** [comment]
Unfortunately same result as the initial comment.  I see the new version of 20180321-24, but still receive the message "The package file is corrupt. Please download it again or contact the package deveolper. Are you sure you want to continue?"

I've attempted the update on a different DS713+ as well, unfortunately it is the same model, same architecture, and same OS version, so it doesn't help all that much.

Please let me know if there is any further information that could be useful.

**Comment by HansGr00ber** [comment]
Still showing as corrupt on my DS216j but I installed it anyway and it appears to work ok

**Comment by ymartin59** [comment]
Sorry for that. I know where was my mistake.

**Comment by ymartin59** [comment]
Published again... I improperly fixed #3241. I hope it is OK now.

**Comment by jeremysbrain** [comment]
###All good now!###
Now off to troubleshoot and resolve permissions!
Thanks for the attention to this issue!

**Comment by Teryon** [comment]
It's working now.

**Comment by Safihre** [comment]
👍 👍 💯
