### ISSUE TITLE
[Package Request] rsnapshot and nano for DS418 (synology_rtd1296)

### ISSUE THREAD

**Issue by mooks42** [SynoCommunity/spksrc#3240]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: rsnapshot and nano

_NAS Model: DS118, DS218, DS218play, DS418j, DS418
_NAS Architecture: rtd1296

Next time i'll check the architecture when i buy a new Synology :)
Especially rsnapshot would be a huge help, all my backupscripts depend on it :(

**Comment by ymartin59** [comment]
I published both quickly without testing. Please report if any trouble, or close this issue if OK.

**Comment by mooks42** [comment]
Wow thank you! I'll test it ASAP :)
