### ISSUE TITLE
Package declared as corrupted by DSM

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3241]
spksrc produces invalid package for spkrepo

Inconsistency between `spksrc` packaging logic:
- https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.spk.mk#L280

And `spkrepo` signature generation does not include full content of `WIZARD_UIFILES`
- https://github.com/Diaoul/spkrepo/blob/master/spkrepo/utils.py#L39
 
As a result, any additional files in `WIZARD_UIFILES` like editor backup files are not included in signature generated by `spkrepo` and DSM reports package as corrupted

**Comment by Safihre** [comment]
Bug fixed? :)

**Comment by ymartin59** [comment]
@Safihre Not yet, I have to improve `mk/spksrc.spk.mk` Makefile to prevent it to build non-signable archives.
