### ISSUE TITLE
Updated Sonarr and Radarr and neither will start - DS215j

### ISSUE THREAD

**Issue by Adamski730** [SynoCommunity/spksrc#3243]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Sonarr
_Package Version:_20180303-13

_NAS Model:_Synology DS215j
_NAS Architecture:_Armada375
_DSM version:_DSM 6.1.5-15254 Update 1

### Expected behavior
Sonarr starts

### Actual behavior
Sonarr tries to start but doesn't

### Steps to reproduce
_1._Go to package centre
_2._Select Run in Sonarr package
_3._It doesn't run

#### Package log
_Starting nzbdrone command env PATH=/usr/local/mono/bin:/volume2/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume2/@ap
pstore/nzbdrone/var LD_LIBRARY_PATH=/volume2/@appstore/nzbdrone/lib /usr/local/mono/bin/mono /volume2/@appstore/nzbdrone/share/NzbDrone/NzbDrone.exe

#### Other logs
None seem to exist

**Comment by Safihre** [comment]
Did you wait a while?
It takes also like 5 minutes on my NAS before it's finally finished starting.

**Comment by Adamski730** [comment]
Yup, rebooted this morning again and neither package started so tried to start them both manually. 2 hours later and still not running. 
Is it likely to be anything to do with permissions? When the packages updated a text box popped up saying something about change in permissions and having to use sc-download. I have basically given sc-download full access to everything but still no joy.

**Comment by imran0** [comment]
I too am having this issue with Sonarr, it appears if I remove the package and reinstall it works again. But the problem is I lose my settings and database, when I turn off the package to restore using the details on the Sonarr wiki it refuses to turn on again.

**Comment by ymartin59** [comment]
Is it an upgrade from previous version? Is your system has been upgraded from DSM 5?
May you please review this documentation about permissions settings: https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by Safihre** [comment]
What if you manually try to run the listed command via SSH? Should give some error.

**Comment by Adamski730** [comment]
Sorry, been away for the weekend, thanks for the replies. I have already followed the instructions in the permission management wiki so I'm pretty sure that is all OK even though I only upgraded from DSM6 to 6.1 and Sonarr stopped working after the package update not after the DSM update.

I have run the command manually in SSH just now and got "segmentation fault (core dumped)"

**Comment by Adamski730** [comment]
Anybody got any ideas please? Really want to get Sonarr up and running again. I've tried to look up the segmentation fault error but none of it really seems relevant to my issue

**Comment by Safihre** [comment]
What is your mono-package version?

**Comment by Adamski730** [comment]
It's 5.8.0.108-11

**Comment by Safihre** [comment]
Can you make a backup of your settings and then uninstall Sonarr, Radarr and Mono.
Then reinstall them, see if it will start.

**Comment by Adamski730** [comment]
Please excuse my ignorance but how do I make a backup of the settings if I can't open the package? Not too familiar with Synology commands and how to do stuff through SSH. Can I backup files to my PC via SSH?

**Comment by tmarkwardt** [comment]
Use scp or from putty package (windows) nscp.exe to transfer file(s) over sah.

**Comment by Adamski730** [comment]
Thanks, hopefully got a backup of Radarr now, had already re-installed Sonarr before knowing I could back it up so will un-install everything now and re-install and report back. Might need some pointers for restoring my Radarr settings if this works.

**Comment by Adamski730** [comment]
Success! Re-installed everything and Sonarr/Radarr are back up and running. I have re-configured Sonarr and tested and all seems OK on that front thanks.

Radarr works with a new config but when I try to copy my old config file over and restart it won't then start up. The commands I am running are:

rm -r /usr/local/radarr/var/.config/Radarr/nzbdrone.db
cp -f /volume2/homes/Backup/radarr_backup/Radarr/nzbdrone.db /usr/local/radarr/var/.config/Radarr/

I can see it delete the .db file and then copy the old one in but it won't start up. If I then delete it again and restart Radarr it runs fine.

I would really like to keep my settings and movie watch list if possible (watch list is more important) so if anyone can give me some things to try I would appreciate it.

**Comment by Safihre** [comment]
You should fix the permissions of these files.
`chmod -R 777 /usr/local/radarr/var`

**Comment by Adamski730** [comment]
All back up and working it would seem, thanks for all the help.
