### ISSUE TITLE
url SABnzbd in Package Center points to wrong port

### ISSUE THREAD

**Issue by sandokanfirst** [SynoCommunity/spksrc#3247]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: SABnzbd_
_Package Version: 2.3.1-33_

_NAS Model: DS 214_
_NAS Architecture: Marvell Armada XP MV78230_
_DSM version: 6.0.2-8451_

### Expected behavior
The url in Package Center for SABnzbd should point to the _actual_, _user-defined_ port, in my case port 8081.

### Actual behavior
 The url in Package Center for SABnzbd points to SABnzbd's default port, 8080.

### Steps to reproduce
_1._ Just open the SABnzbd package in Package Center.

Attached are 2 pictures, one of SABnzbd in Package Center, and one of the address bar with the URL to the webinterface of SABnzbd with the correct port number. 

![image](https://user-images.githubusercontent.com/36963445/37865758-75381e12-2f81-11e8-9a3a-87d8b650366b.png)
![image](https://user-images.githubusercontent.com/36963445/37865761-7ecc8486-2f81-11e8-9ea2-c96e9b559276.png)

**Comment by Safihre** [comment]
That's not possible, it's hard-coded.
DSM doesn't let us change that.

**Comment by Safihre** [comment]
Oh and you should really switch to Glitter, Plush skin is ancient 😋

**Comment by sandokanfirst** [comment]
Wow, this was my first issue in GitHub ever and it is closed lightning fast. ;)
My Sickbeard package in Package Center _does_ point to my custom port, so I was under the impression that it can't be hard-coded.

(and btw, I use Plush, as it allows me to see which nzb's have been fed manually and which by an indexer at one fell swoop. AFAIK this is not possible in Glitter?)

![image](https://user-images.githubusercontent.com/36963445/37865937-bcdcc0d6-2f83-11e8-8f66-a96392561dc9.png)

**Comment by Safihre** [comment]
That's not a custom port, but the default one of the package: https://github.com/SynoCommunity/spksrc/blob/master/spk/sickbeard-custom/Makefile 😋

Not sure how you see it's manual or automatic? From the category? 
You can add extra columns to Queue and or History in Status and Interface settings window in Glitter.

**Comment by sandokanfirst** [comment]
I stand corrected! Thanks for that. And me thinking I had looked at this so
carefully... it's a good thing I left IT a few years ago, I think. ;)
In my defence, the SickRage interface says "web port to browse and access
SickRage (default:8081)". I know, I know, "use the source, Luke"!

The Plush interface has a white star as a symbol which shows "Open
Informational URL" and the indexer used when you hover over it.  I will
look at the Glitter interface (again) and see if I can customise it. I'm a
bit conservative in these things, but your gentle push motivates me to
adapt. ;)

Cheers again,
Sando

2018-03-24 17:44 GMT+01:00 Safihre <notifications@github.com>:

**Comment by Safihre** [comment]
Aaah yes, the star is indeed one of those small things that weren't ported directly to Glitter. True!
