### ISSUE TITLE
Transmission JSON file access

### ISSUE THREAD

**Issue by slammmed** [SynoCommunity/spksrc#3248]
Im not very familiar with linux, I am looking for a way to edit the .json file but I cannot access @appstore. I'm very inexperienced with ssh and i dont want to cause major issues by doing something wrong in there. What would be the best way for me to access @appstore?

Thanks in advance :) 

### Setup
Transmission
2.93-14

DS3617XS
_NAS Architecture:_
DSM 6.1.5-15254 Update 1

### Expected behavior
I want to be able to edit the .json file

### Actual behavior
I cannot locate the @appstore folder

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
For SSH connection and file edition, refer to FAQ I wrote for Home Assistant: https://github.com/SynoCommunity/spksrc/wiki/FAQ-HomeAssistant
Concerning Transmission itself, you have to edit file with
`sudo nano /var/packages/transmission/target/var/settings.json`

**Comment by Safihre** [comment]
Closing due to lack of response.
