### ISSUE TITLE
[Package Request] socat

### ISSUE THREAD

**Issue by mysteriouss** [SynoCommunity/spksrc#3249]
Name: socat

Description:  "netcat++" (extended design, new implementation)

Website: http://www.dest-unreach.org/socat/

Software documentation: http://www.dest-unreach.org/socat/doc/socat.html

Build/Installation documentation: http://www.dest-unreach.org/socat/doc/README #install

Source Code: http://www.dest-unreach.org/socat/download/

License: socat is distributed under the terms of the GNU GPLv2 http://www.dest-unreach.org/socat/doc/README #license

**Comment by ymartin59** [comment]
Candidate to be included in "SynoCli network" package
