### ISSUE TITLE
Design: new package "SynoCli file"

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3250]
Create a package for small command line utilities dedicated to file manipulation.
Revival of #2261
Tools candidates:
- less #2075, #2818 
- Tree #3242
- fdupes #2257 or jdupes #3030
- RHash #2823 #2944
- mc
- nano

Potential extension (TBD):
- rmlint #3482 (proposed by cytec) <- Requires `scons` build package (python3 based)
- detox #2199 

Not to be included:
- coreutils [cross package](https://github.com/SynoCommunity/spksrc/blob/master/cross/coreutils/) as almost all commands available already or installable via `synogear install` 
- rename (proposed by adithyabenny) <-- Part of `linux-util` package. Maybe later as part of a separate package.

Package icon: Kindly provided by @publicarray. Many thanks!

**Comment by MrSpoocy** [comment]
mc ;)

**Comment by hgy59** [comment]
@MrSpoocy mc is not a command line tool IMHO
I would like to keep the SynoCli packages small.

**Comment by h-q** [comment]
I cannot wait for these SynoCli packages. I missed them since the Bootstrap days. Thank you so much!

**Comment by ymartin59** [comment]
I also would like to provide "entware" first... to avoid to introduce (new) duplicated tools in `spksrc`

**Comment by m4tt075** [comment]
Chaps, I just remembered the "synogear" package, which is actually provided by Synology. See
http://www.synology-wiki.de/index.php/Synogear:_weitere_Tools
for documentation and the list of commands included (only on German, but I did not find another source). We could provide an English translation on our Wiki page and refer to it. Not sure it covers everything, but I feel a lot of the tools requested. Just for consideration...

**Comment by ymartin59** [comment]
@m4tt075 Thanks for the hint. Here it is: https://github.com/SynoCommunity/spksrc/wiki/FAQ-synogear
Interesting because some tools are painful to build... but some will complain most tools versions are quite old.

**Comment by jbruchon** [comment]
I'm the maintainer of `jdupes` and the one who opened #3030. I'd like to voice my support for integrating `jdupes` by whatever means is necessary. A Synology user requested my effort to make an SPK for it 4 months ago and I've had other users since express interest in it for their NASes. As far as the age concern, I maintain the code regularly and try to be responsive to issue reports. If I need to do anything to assist in inclusion, please let me know how I can help.

**Comment by adithyabenny** [comment]
`rename`? I use it often to batch rename files with a regex.

**Comment by m4tt075** [comment]
@adithyabenny I'm looking into your request, but am struggling to find source code for the `rename` command you mention. Is there some official source? Where can I find it? 

@cytec `rmlint` seems to use `scons`, some non-standard build system I'm not familiar with, which depends on `python3` which I'm not familiar with. I'll keep this as possible extension for the future for now. Anyways, if you are interested and you have some time, please do look at it.

**Comment by adithyabenny** [comment]
@m4tt075  The official source I believe is at CPAN over [here](https://metacpan.org/pod/distribution/File-Rename/rename.PL), but that doesn't have a direct URL to the version control repo, so the Debian mirror over [here](https://salsa.debian.org/perl-team/modules/packages/rename) should do.

**Comment by m4tt075** [comment]
@adithyabenny Yikes! Tried to make `rename` work today, got the package, got it built in our framework, got it to install into the $(STAGING_INSTALL_PREFIX) directory, everything looks nice. But I'm not able to integrate the required module files into the `perl` version that is running on the NAS. `perl` just cannot find them in `@INC`. Found some advice how to deal with this on the internet. Everything failed. `perl` is driving me crazy! Isn't there something like that, which has been written in C?

**Comment by m4tt075** [comment]
`rhash` has been broken and (hopefully) fixed (could only test `x64` platform), `rename` (perl) has been added. 
New test builds here: https://github.com/m4tt075/spksrc/releases/tag/synoclifile-3
Please test and report back.

**Comment by m4tt075** [comment]
@publicarray I've temporarily included your "SynoCLI" icon without any text. Could you please create one for this "SynoCLI-File" package, like the one you have created for "SynoCLI-Net"?

**Comment by publicarray** [comment]
Hi @m4tt075, 
Should be easy enough. I have a [svg file](https://seby.io/files/SynoPackagegreen-shell.svg) which is easy to edit in Inkskape, Adobe Illustrator, Affinity Designer, etc.

Here is the requested png: ![synocli-file](https://user-images.githubusercontent.com/5497998/52095490-cea79e80-260e-11e9-93c8-094157761ac5.png)

**Comment by adithyabenny** [comment]
@m4tt075 There is indeed a C variant of `rename` that ships with `util-linux`. [Here's](https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git) the source repo, and [here's](https://en.wikipedia.org/wiki/Util-linux) more info on the package.

**Comment by m4tt075** [comment]
@publicarray I really suck with graphics stuff. I don't even know what svg files are. So many thanks for doing it! ;-)
@adithyabenny Cool. We have a cross package for `util-linux` already and can reuse it. Happy to integrate it. Just seen that it contains all kind of CLI tools, which brings me to the next question:
@ymartin59 Anything other than `rename` from `util-linux` you'd want to integrate into our `SynoCLI-file` (or other `SynoCLI-*`) packages?

**Comment by ymartin59** [comment]
@m4tt075 Interesting question... some commands are already provided by DSM. But according to https://en.wikipedia.org/wiki/Util-linux it is difficult to only select "files related tools". I think util-linux is included in "test disk" for fsck and partitioning tools.
Here are some I often use as a "old-style-Unixer": cal, column, fallocate, hexdump, script, scriptreplay
I just wonder if it would not make sense to deliver most of them in a dedicated "util-linux" package.

**Comment by m4tt075** [comment]
@ymartin59 I agree. A lot of those tools probably also are not necessarily required by typical Synology users. Let's keep those separate.
@adithyabenny, that would mean that we'll keep `rename` out of the official package for now. Hope that's fine for you. If you want, let me know your DS platform and firmware version, and I'll build a package with the perl `rename` version for you. I've spent a lot of time implementing it. So it can at least benefit you... ;-)

**Comment by ymartin59** [comment]
@m4tt075 Just find it in package listing, please include ncdu in synocli-file.

**Comment by ymartin59** [comment]
Working on applications update, testing and packaging...

**Comment by ymartin59** [comment]
Many thanks to all contributors for this package !
Published.
Available from Package Center or https://synocommunity.com/package/synocli-file
