### ISSUE TITLE
Design: new package "SynoCli dev"

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3253]
Create a package for small command line utilities dedicated to development tasks.
Revival of #2261
Tools candidates:
- ldd (provided by [synogear](https://www.synology-wiki.de/index.php/Synogear:_weitere_Tools))
- nice
- gcc
- gdb [cross package](https://github.com/SynoCommunity/spksrc/blob/master/cross/gdb/)  (provided by [synogear](https://www.synology-wiki.de/index.php/Synogear:_weitere_Tools))
- bc [available with #4037)
- binutils
- strace (provided by [synogear](https://www.synology-wiki.de/index.php/Synogear:_weitere_Tools))

Any other ideas?
Wanted contribution: an generic icon for "SynoCli" package group, with "dev" text addition for category

**Comment by ymartin59** [comment]
@hgy59 Do you have ever started this package?

**Comment by hgy59** [comment]
@ymartin59 I have started in january but didn't even create a branch. Only `bc` is integrated (into diyspk).
While trying to add `gdb` I left this aside...

**Comment by michealespinola** [comment]
`bc` would be very useful so we could use diagnostic scripts like `dnsperftest`, etc.

**Comment by cmencore** [comment]
+1 for bsdmainutils.. I'm trying to use [transcrypt](https://github.com/elasticdog/transcrypt) for git encryption, which requires the column command

**Comment by hgy59** [comment]
> +1 for bsdmainutils.. I'm trying to use [transcrypt](https://github.com/elasticdog/transcrypt) for git encryption, which requires the column command

@cmencore what about the `column` command from **util-linux**? Would this solve your issue too?

**Comment by hgy59** [comment]
closing this, as we now have syncli-devel (and synocli-misc).
The missing tool is gcc, but this will need to be delivered as non generic packages due to the dependency of kernel.

**Comment by michealespinola** [comment]
Thank you very much for your continued efforts, and for both of these latest toolset packages. This helps further reduce my reliance on Entware.

**Comment by hgy59** [comment]
> > closing this, as we now have syncli-devel (and synocli-misc). The missing tool is gcc, but this will need to be delivered as non generic packages due to the dependency of kernel.
> 
> Is `gcc` available anywhere for Synology?
> 
> (Sorry if this is not the place)

gcc is not and will not be included in synocli-devel as it must be different for each dedicated architecture.
And it is still in (slow) progress in #4469.

**Comment by th0ma7** [comment]
@jbsilva no, not yet as we've struggled to generate a working build of gcc.  Although what you have available is the LLVM project part of the `synocli-devel` package provided by our SynoCommunity.  LLVM includes `clang` c compiler along with `clang++` and `clang-cpp` and all relevant toolset that can be used in place of gcc.

Otherwhise, you can use this `spksrc` project as a container and cross-compile working binaries for your NAS archs.  This involves learning how to use this framework and is a good opportunity to enhance existing packages we provide or help so we can publish new ones that you're interested in (so you don't have to compile locally from your NAS anymore).  Documentation is available from the from page https://github.com/SynoCommunity/spksrc

Hope this helps, good luck!

**Comment by jbsilva** [comment]
@hgy59 @th0ma7 Thank you very much for the quick answers. I'll take a look at the links.
Also thank you a lot for the great work! The currently available packages already help me a lot.
