### ISSUE TITLE
Design: new package "SynoCli net"

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3254]
Create a package for small command line utilities dedicated to network/remote access.
Revival of #2261
Tools candidates:
- screen (from testdisk)
- tmux (replace standalone package)
- mosh #2936 #2483
- socat #3249 
- nmap 
- sshfs
- ~~aria2~~ dedicated package planned #2959 

Any other ideas?
Wanted contribution: an generic icon for "SynoCli" package group, with "net" text addition for category

**Comment by publicarray** [comment]
How about [iftop](http://www.ex-parrot.com/pdw/iftop/), [mtr](https://github.com/traviscross/mtr), [nethogs](https://github.com/raboof/nethogs) ? or should those be a separate group (including nmap)?

I've used created an Icon but I've used Font Awesome so inclusion of their licence is needed: https://fontawesome.com/license

[icons.zip](https://github.com/SynoCommunity/spksrc/files/1892667/icons.zip)

**Comment by ymartin59** [comment]
@publicarray Thanks for these icons... I still wonder if `spksrc` is really the right place to provide "simple" command line tools than may be already available with entware-ng #3255.
There is already a lot of volume to maintain here, so I would be pleased to "delegate" to keep our list of applications "relevant" and as short as possible.

**Comment by publicarray** [comment]
I see your point. Hm the packages that I suggested are more aimed for router users/network people anyway. I don't have an answer either. However I do think that we could combine all current CLI packages together into one meta CLI package (or maybe just two, one that is more lightweight version). The current proposal with CLI categories is also a good idea. I don't know..

Another option for NAS users (I don't think the hardware in the Router is quite enough) is to install [Debian-Chroot](https://github.com/SynoCommunity/spksrc/wiki/Debian-Chroot)

**Comment by publicarray** [comment]
So here is how I see it. People can install Debian-Chroot and have access to "everything". Or they can install Entware (once ready) to get the vast majority of things a dev would need. Or they can install SynoCommunity's own "limited" selection of existing CLI packages (whether a meta, category or individual package, I wouldn't worry too much about duplicates. Worrying about duplicates can course more of a maintenance burden than it tries to solve).

**Comment by ymartin59** [comment]
I partly agree. I would care about "duplicates" only when a "new package request" triage... to avoid volume to grow.

**Comment by ymartin59** [comment]
@publicarray I am back here and I wonder if Font Awesome may be used according Free license: https://fontawesome.com/license/free

**Comment by ymartin59** [comment]
@publicarray Sorry, OK for free license, I wonder where it should be noticed in our package (credits in description or in install wizard? 
I am interested to get your "green shell" logo as svg with parts splitted as layers - I use Inkscape - after switch "Net" and ">_" so that "Net" is straight horizontal and have space to replace easily "Net" with "Files", "Disk", "Dev"...
Add your own copyright in SVG metadata and I will take care it is preserved in PNG.

**Comment by publicarray** [comment]
@ymartin59 Yea, good question about where to put the licence. I think both options you listed are good.

I don't use Inkscape but I think this is what you are after: https://seby.io/files/SynoPackagegreen-shell.svg I don't particularly care about the metadata (does anyone actually read them?) instead, how would you feel if you add a link to this issue in the commit message? (only for the first upload of the files)

P.S. I used [Fira Sans](https://github.com/mozilla/Fira) for the font, but you are free to choose any font you like :)

**Comment by ymartin59** [comment]
@publicarray Great. I like it ! And I can edit text on my own. OK to credit your work and refer to license from commit message.

**Comment by publicarray** [comment]
@ymartin59 Sounds good to me 👍 but, I'm not sure about the licence. I do think that Font Awesome licence needs to be in the source code somewhere. Happy to help :)
