### ISSUE TITLE
MC mouse is not working anymore

### ISSUE THREAD

**Issue by gielie** [SynoCommunity/spksrc#3258]
### Setup
_Package Name:_midnight commander
_Package Version:_4.8.20

_NAS Model:_415play
_NAS Architecture:_evansport (x86)
_DSM version:_6.2

### Expected behavior
before the update i was able to select files with the mouse and go to directories

### Actual behavior
The mouse is not working at all

### Steps to reproduce
_1._reinstalled mc, no luck

**Comment by gielie** [comment]
I tried both.
[code]
ash-4.3# echo $TERM
xterm-256color[/code]

after `export TERM=xterm`

[code]
ash-4.3# echo $TERM
xterm
[/code]

I have 2 different synology's and the one i updated version of mc doesn't have mouse support, the older version of mc works fine. I also tried putty on pc and  terminal on osx with the same result.

Where can i find the old version of mc?

**Comment by ymartin59** [comment]
So you run `screen`, is that right? Have you without starting `screen`.
If `mc -x` works, trouble comes from your "terminal emulation" context: http://midnight-commander.org/wiki/doc/faq
Latest package runs properly with mouse support from a linux terminal emulator, so issue is not in package/application itself.

**Comment by hgy59** [comment]
@gielie maybe this is related to the DSM version.
After update to DSM 6.1.6-15266 I can not reproduce this behavior. 
I remember to have the mouse problem too, i.e. when clicking the mouse, some ESC-sequences appeared on the commandline, and the `home` key had a delay of about 2 seconds.

- May be related to the DSM 6.2 beta version?
- Or may be the evansport arch? (works for me now with DSM 6.1.6 on apollolake and armada370)

**Comment by hgy59** [comment]
just found that the mouse works find with regular admin user. But when running with `sudo mc` the mouse does not work and the home key has the delay as mentioned above.
But strange is, that when running  `sudo mc` I got a `$` prompt instead of a `#` prompt on the mc command line. (On other systems there is a  `#` prompt when running  `sudo mc`).
@gielie please verify whether this behavior is the same for yours.

**Comment by ymartin59** [comment]
@gielie Please also compare with separate `sudo -s` and then use of `mc`.

**Comment by gielie** [comment]
After the latest DSM update (DSM 6.1.6-15266 Update 1) my mc is working normal, i can start mc with sudo or with -s -c all variations work normally
