### ISSUE TITLE
Missing many packages on 918+

### ISSUE THREAD

**Issue by Tigerdrachen** [SynoCommunity/spksrc#3261]
Only seeing 40 Packages in the community-tab on my DS918+. A friend of mine with a DS415+ got 110 packages (incl. Beta). I need the icecast package. What can i do?

**Comment by Safihre** [comment]
Synology made changes in DSM6, meaning we have to re-design all packages.
https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support

You can download test packages of this new style here: #3138.

**Comment by Tigerdrachen** [comment]
THX, can you fix icecast first ;-)
