### ISSUE TITLE
Known issue: Transmission upgrade fails in French, switch to English as work-around

### ISSUE THREAD

**Issue by labrache** [SynoCommunity/spksrc#3262]
### Setup
_Package Name:_ Transmission
_Package Version:_ 2.93

_NAS Model:_ DS416j
_NAS Architecture:_ 
_DSM version:_ DSM 6.1.6-15266

### Expected behavior
Transmission updating

### Actual behavior
Transmission can't update

### Steps to reproduce
_1._ Have transmission
_2._ Update transmission
_3._ Observe ¯\\\_(ツ)\_/¯

#### Other logs
/var/log/messages

2018-03-29T23:25:18+02:00 NAS synoscgi_SYNO.Core.Package.Installation.Download_1_check[12780]: pkgtool.cpp:1547 /volume1/@tmp/drYtc5/WIZARD_UIFILES/upgrade_uifile_fre: * Line 3, Column 6
  Missing ',' or '}' in object declaration

Seem like the file  spksrc/spk/transmission/src/wizard/upgrade_uifile_fre miss a close quote on "step_title" value

**Comment by Safihre** [comment]
Oops, that's my fault. Stupid!
@ymartin59 I can fix, but maybe if you do it and directly create a new release? 😢

**Comment by Teryon** [comment]
You can upgrade setting language of the NAS to english et put french language back

**Comment by labrache** [comment]
Sorry for my baguette :) problem fixed!
Great work on this repository BTW.

**Comment by ymartin59** [comment]
@Safihre I am away from keyboard for one week vacation...

**Comment by ymartin59** [comment]
@Safihre I have not identify why french wizard files are incorrect and make install/upgrade fails. Do you already what is wrong?

**Comment by ymartin59** [comment]
@Safihre Probably found it: uppercase letter in "Step_title", right?
