### ISSUE TITLE
No e4defrag in Disk Utils package

### ISSUE THREAD

**Issue by AlainSabban** [SynoCommunity/spksrc#3263]
### Setup
_Package Name:_ Disk Utils 
_Package Version:_ 1.42.6-1

_NAS Model:_ Synology DS414
_NAS Architecture:_ armadaxp armv7l
_DSM version:_ 6.1.6-15266

### Expected behavior

After 5 years of run with many writes, I'd like to check the level fragmentation of my DS414 ext4 formated.  I installed package Disk Utils v.1.42.6-1 but the e4defrag binary is not included.

### Actual behavior

e4defrag not included in package

Please update Disk Utils package with e4defrag included.

Thanks

**Comment by ymartin59** [comment]
I propose you to run fsck without any change (dry-run -n). As far as I remember, it reports file system fragmentation.
I wonder if it is really wise to run defrag when DSM operates...

**Comment by hgy59** [comment]
e4defrag is included in synocli-disk (and in "do it yourself" diskutils).
It is not added to the path so you have to use full qualified path:
`/var/packages/synocli-disk/target/sbin/e4defrag`
