### ISSUE TITLE
[update] Update Tvheadend to v4.2.6

### ISSUE THREAD

**Issue by manuelrn** [SynoCommunity/spksrc#3264]
Hi, thank you very much for your fantastic work.

I would appreciate it if you could update Tvheadend to v4.2.6: https://github.com/tvheadend/tvheadend/releases/tag/v4.2.6

Thank you very much!

**Comment by m4tt075** [comment]
OK, I'm on it. Need to test though and will be AFK for a week from tomorrow. Will take some days...

**Comment by manuelrn** [comment]
Thanks @m4tt075!

**Comment by m4tt075** [comment]
If you can test while I'm away, let me know your Syno platform and DSM version, please...

**Comment by manuelrn** [comment]
Yes, I can test these:

  * _**NAS Model:**_ DS3615xs
  * _**NAS Architecture:**_ Bromolow
  * _**DSM version:**_ 6.0.2-8451-11

<br/>

  * _**NAS Model:**_ DS918+
  * _**NAS Architecture:**_ Apollolake
  * _**DSM version:**_ 6.1.6-15266

**Comment by m4tt075** [comment]
@manuelrn OK, 4.2.6 test-builds for your systems are here:
https://www.dropbox.com/sh/zl67clwy5rio8kn/AADpWJhkHQ6RgqaCbLxbNIJoa?dl=0
They are basically untested though. Please backup before you upgrade and report any issues you may find.

**Comment by davidmuma** [comment]
I have a DS116, armada 385, can you compiled 4.2.6 for my NAS.

Thank you very much
