### ISSUE TITLE
[Package Request] Aria2

### ISSUE THREAD

**Issue by cnrat** [SynoCommunity/spksrc#3269]
Name: Aria2
Description: aria2 is a lightweight multi-protocol & multi-source command-line download utility. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink. aria2 can be manipulated via built-in JSON-RPC and XML-RPC interfaces.
Website: https://aria2.github.io/
Software documentation: https://aria2.github.io/manual/pt/html/index.html
Build/Installation documentation: https://aria2.github.io/
Source Code: https://github.com/aria2/aria2
License: https://github.com/aria2/aria2/blob/master/LICENSE.OpenSSL

**Comment by Safihre** [comment]
See #2959, seems it was never continued.

**Comment by cnrat** [comment]
@Safihre I tried to merge his branch manually but could not compile correctly. Orz...

**Comment by cnrat** [comment]
@Safihre Finally got this compiled correctly. But there is still a lot of work to be done.
- dsm-control.sh is now nearly empty.
- a daemon is needed.
- a firewall control(.sc) file is need.
- no default aria2.conf
...

**Comment by cnrat** [comment]
I'm quite new to spksrc. I'v made a new branch and built successful. Could anyone help?
https://github.com/cnrat/spksrc/tree/aria2

**Comment by ymartin59** [comment]
I really think it may be interesting to use such command line tools from entware-ng-3x - see #3255

**Comment by hgy59** [comment]
closed by #6068
