### ISSUE TITLE
Headphones fails to start on DS416j

### ISSUE THREAD

**Issue by Goetz** [SynoCommunity/spksrc#3272]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_headphones_noarch-all_20180228-7
_Package Version:_ (see package name)

_NAS Model:_DS416j
_NAS Architecture:_armada38x (x16 series)
_DSM version:_DSM 6.1.6-15266

### Expected behavior
Package should start when "run package" is selected in package manager

## Actual behavior
Error message generated: "failed to run the package service"

### Steps to reproduce
_1._open package manager
_2._click run
_3._voila! reproduced

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```cannot access log (sorry)
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by rouslanovitch** [comment]
==> synopkg.log <==
2018/04/07 15:13:37	start headphones: begin to start version 20151012-7
2018/04/07 15:13:38	start headphones 20151012-7 Begin pre-load apparmor
2018/04/07 15:13:38	start headphones 20151012-7 End pre-load apparmor ret=[0]
2018/04/07 15:13:38	start headphones 20151012-7 Begin start-stop-status start
Starting Headphones ...
su: user headphones does not exist
2018/04/07 15:13:38	start headphones 20151012-7 End start-stop-status start ret=[1]

==> messages <==
2018-04-07T15:13:38+02:00 syno kernel: [793036.298329] init: pkgctl-headphones pre-start process (15010) terminated with status 1
2018-04-07T15:13:38+02:00 syno synoscgi_SYNO.Core.Package.Control_1_start[14515]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-headphones][0xD900 manager.cpp:204]

==> synopkg.log <==
2018/04/07 15:13:39	(system) trigger headphones 20151012-7 Begin start-stop-status stop
Headphones is not running
2018/04/07 15:13:39	(system) trigger headphones 20151012-7 End start-stop-status stop ret=[0]
2018/04/07 15:13:39	(system) trigger headphones 20151012-7 Begin unload apparmor
2018/04/07 15:13:39	(system) trigger headphones 20151012-7 End unload apparmor ret=[0]

==> messages <==
2018-04-07T15:13:39+02:00 syno synoscgi_SYNO.Core.Package.Control_1_start[14515]: service_initjob_action.c:27 InitJobStart failed, [0xD900 manager.cpp:204]
2018-04-07T15:13:39+02:00 syno synoscgi_SYNO.Core.Package.Control_1_start[14515]: pkgstartstop.cpp:377 Failed to start pkgctl-headphones (err=-1) [0xD900 manager.cpp:204]

==> synopkg.log <==
2018/04/07 15:13:39	stop headphones: begin to stop version 20151012-7
2018/04/07 15:13:39	stop headphones: stop version 20151012-7 successfully, result 0
2018/04/07 15:13:39	start headphones: start version 20151012-7 failed, result 272

**Comment by rouslanovitch** [comment]
saw this during the installation 

==> synopkg.log <==
2018/04/07 18:39:36	install headphones 20151012-7 Begin preinst
2018/04/07 18:39:36	install headphones 20151012-7 End preinst ret=[0]
2018/04/07 18:39:36	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/headphones
2018/04/07 18:39:36	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/headphones ret=[0]
2018/04/07 18:39:36	install headphones 20151012-7 Begin /bin/rm -rf /var/packages/headphones
2018/04/07 18:39:37	install headphones 20151012-7 End /bin/rm -rf /var/packages/headphones ret=[0]
2018/04/07 18:39:37	install headphones 20151012-7 Begin /bin/mkdir -p /var/packages/headphones
2018/04/07 18:39:37	install headphones 20151012-7 End /bin/mkdir -p /var/packages/headphones ret=[0]
2018/04/07 18:39:37	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/headphones/INFO
2018/04/07 18:39:37	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/headphones/INFO ret=[0]
2018/04/07 18:39:37	install headphones 20151012-7 Begin /bin/rm -rf /var/packages/headphones/scripts
2018/04/07 18:39:37	install headphones 20151012-7 End /bin/rm -rf /var/packages/headphones/scripts ret=[0]
2018/04/07 18:39:37	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/headphones/scripts
2018/04/07 18:39:37	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/headphones/scripts ret=[0]
2018/04/07 18:39:37	install headphones 20151012-7 Begin /bin/rm -rf /var/packages/headphones/conf
2018/04/07 18:39:37	install headphones 20151012-7 End /bin/rm -rf /var/packages/headphones/conf ret=[0]
2018/04/07 18:39:37	install headphones 20151012-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/headphones/conf
2018/04/07 18:39:38	install headphones 20151012-7 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/headphones/conf ret=[0]

==> messages <==
2018-04-07T18:39:38+02:00 syno synoscgi_SYNO.Core.Package.Installation_1_install[5692]: resource_api.cpp:163 Acquire service-cfg for headphones when 0x0001 (done)

==> synopkg.log <==
2018/04/07 18:39:38	install headphones 20151012-7 Begin postinst

==> messages <==
2018-04-07T18:41:42+02:00 syno synoscgi_SYNO.Core.Package.Server_1_check[8425]: pkgtool.cpp:2908 Package is broken: incomplete installation, headphones



==> synopkg.log <==
/var/packages/headphones/scripts/installer: line 61: adduser: command not found
/var/packages/headphones/scripts/installer: line 32: addgroup: command not found
chown: invalid user: 'headphones:root'
2018/04/07 18:42:13	install headphones 20151012-7 End postinst ret=[0]
2018/04/07 18:42:13	install headphones 20151012-7 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2018/04/07 18:42:13	install headphones 20151012-7 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2018/04/07 18:42:13	install headphones 20151012-7 successfully

**Comment by Safihre** [comment]
That's strange. Those commands shouldn't be in the package. What could be going wrong here @ymartin59?

**Comment by rouslanovitch** [comment]
Working perfectly now Thx!

**Comment by Safihre** [comment]
Sigh.. In the original post you said you used `20180228-7`...
