### ISSUE TITLE
Jackett - access to path in var

### ISSUE THREAD

**Issue by JuGuSm** [SynoCommunity/spksrc#3276]
### Setup
_Package Name:_ Jackett
_Package Version:_ 0.8.490-6

_NAS Model:_ DS1812+
_DSM version:_ DSM 6.1.3-15152 Update 8

### Expected behavior
Indexer added.

### Actual behavior
Impossible to add an indexer, I get this error message:
Access to the path "/usr/local/jackett/var/.config/Jackett/Indexers/yggtorrent.json.685df9eb7cae402f9f44d939c6cab490.tmp" is denied.
I resolve it by doing a sudo chown -R jackett /usr/local/jackett/var/.config/Jackett but this bug have to be fixed.

### Steps to reproduce
_1._ Open Jackett app
_2._ Add an indexer

**Comment by ymartin59** [comment]
May you please report content of `/etc/passwd` and `/etc/group`, and `ps -ef | grep jackett` output.

DSM 6 package is expected to run with user account `sc-jackett`, not `jackett` as mentioned in your `chown` command...

**Comment by Safihre** [comment]
Closing due to lack of response.
