### ISSUE TITLE
[Package Request] bsdmainutils (synology apollolake) 

### ISSUE THREAD

**Issue by sturla78** [SynoCommunity/spksrc#3277]
Setup
_Package Name:_ bsdmainutils
_Package Version:_ (not present)

_NAS Model:_ DS218+
_NAS Architecture:_ Apollolake (Intel Celeron J3355)
_DSM version:_ 6.1.6-15266

Hello,
i'm not sure if this is the correct location for post request for new package, i try to do.
It would be very interesting having the bsdmainutils ready to use with apollolake, above all the command "column" that is in the bsdmainutils packages a very helpfull command for format bash output and that it allows creation of table.

**Comment by ymartin59** [comment]
I propose you check entware-ng-3x https://github.com/Entware-for-kernel-3x/Entware-ng-3x

**Comment by hgy59** [comment]
may be integrated into synocli-dev #3253
