### ISSUE TITLE
[Package Request] ZNC update for DS218play

### ISSUE THREAD

**Issue by mpj-ttp** [SynoCommunity/spksrc#3278]
Name: ZNC
Description: IRC bouncer (already on Synocommunity)
Website: https://wiki.znc.in/ZNC

Please could I request a version for the rtd1296 architecture, suitable for a DS218play. Thanks!

**Comment by Safihre** [comment]
See #2977.
We need someone also to port it to new DSM6 framework.
Maybe @ymartin59 wants to compile it for new archs?
