### ISSUE TITLE
Syncthing not showing up

### ISSUE THREAD

**Issue by Freefall01** [SynoCommunity/spksrc#3282]
### Setup
_Package Name:_ Syncthing 
_Package Version:_ any

_NAS Model:_ DS218play
_NAS Architecture:_ x64
_DSM version:_ DSM 6.1.6-15266 Update 1

### Expected behavior
I should be able to see the Syncthing pkg and install it

### Actual behavior
Its not in the list despite being available on synocommunity.com

**Comment by Safihre** [comment]
You can try the test package in #3138.
It was being worked on for DSM6 conversion but then got delayed...
