### ISSUE TITLE
problemi with irssi script

### ISSUE THREAD

**Issue by burghy86** [SynoCommunity/spksrc#3284]
hello. i have install irssi package from synocommunity store. works perfectly whith my ds115j but i dont find the correct folder where put a script *.pl find here: https://scripts.irssi.org/

i tried to put here: volume1/homes/admin/.irssi/scripts/autorun
here: root/.irssi/scripts/autorun
here: volume1/@appdata/irssi/scripts
but not work and irssi not load a script.

please help me

**Comment by Safihre** [comment]
Sorry we don't really provide application support.
Maybe the package creators can help?
