### ISSUE TITLE
Sonarr won't start after update mono, sonarr

### ISSUE THREAD

**Issue by jerrevds** [SynoCommunity/spksrc#3285]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ sonarr 
_Package Version:_ 20180303-13 (mono: 5.8.0.108-11)

_NAS Model:_
_NAS Architecture:_ DS213J
_DSM version:_DSM 6.0.3-8754 Update 6

### Expected behavior
Tell us what should happen
Sonarr should start
### Actual behavior
Tell us what happens instead
sonarr gets in starting mode and then "stops"

### Steps to reproduce
_1._ update mono
_2._update sonarr
_3._ start sonar

#extra steps taken (same result
_4._ unsinstall sonar
_5._ unsinstall mono
_6._ install monor
_7._ install sonar
_8._ start sonar

##and more extra
_8._ adapt mono path
```
#MONO_PATH="/usr/local/mono/bin"
MONO_PATH="/var/packages/mono/target/bin"
MONO="${MONO_PATH}/mono"
```

_9._
adapt error for if not correct read

```
#if [ ${SYNOPKG_DSM_VERSION_MAJOR} -lt 6 ]; then EFF_USER="${SYNOUSER_PREFIX}${USER}"; else EFF_USER="${PRIV_PREFIX}${USER}"; fi
 EFF_USER="${SYNOUSER_PREFIX}${USER}";
```

this gives;
`ash-4.3# /var/packages/nzbdrone/scripts/start-stop-status start
Starting  ...
/var/packages/nzbdrone/scripts/service-setup: line 19: type: service_prestart: not found
/var/packages/nzbdrone/scripts/start-stop-status: line 29: [: too many arguments
`

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
/volume1/@appstore/nzbdrone/
`Starting nzbdrone command env PATH=/var/packages/mono/target/bin:/volume1/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/nzbdrone/var LD_LIBRARY_P$
`

install
`Sun Apr 15 18:05:28 CEST 2018
===> Step preinst. USER=nzbdrone GROUP=sc-download SHARE_PATH=
Sun Apr 15 18:05:30 CEST 2018
===> Step postinst. USER=nzbdrone GROUP=sc-download SHARE_PATH=
Installing service configuration /var/packages/nzbdrone/conf/nzbdrone.sc
Adding 'sc-nzbdrone' to 'sc-download'
Group Name: [sc-download]
Group Type: [AUTH_LOCAL]
Group ID:   [65538]
Group Members:
0:[sc-nzbdrone]
Invoke service_postinst
Granting 'sc-nzbdrone' unix permissions on /volume1/@appstore/nzbdrone/var/.config
`

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

synoservice
`2018-04-15T19:36:35+02:00 nas synoscgi_SYNO.Core.Package.Control_1_start[15815]: service_start.c:74 synoservice: [pkgctl-nzbdrone] starting ...
2018-04-15T19:36:36+02:00 nas synoscgi_SYNO.Core.Package.Control_1_start[15815]: service_start.c:178 synoservice: [pkgctl-nzbdrone] started.
`
synopkg
```
2018/04/15 18:55:26     start nzbdrone: begin to start version 20180303-13
2018/04/15 18:55:30     start nzbdrone: start version 20180303-13 successfully, result 0
2018/04/15 19:35:07     start CloudSync: begin to start version 2.3.6-1018
2018/04/15 19:35:15     start CloudSync: start version 2.3.6-1018 successfully, result 0
2018/04/15 19:36:29     start nzbdrone: begin to start version 20180303-13
2018/04/15 19:36:41     start nzbdrone: start version 20180303-13 successfully, result 0
```

**Comment by ymartin59** [comment]
Please stop and start package from Package Center interface.
Or else apply following procedure: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#how-to-query-package-status-from-command-line

**Comment by jerrevds** [comment]
result from
```admin@nas:~$ synopkg status nzbdrone
nzbdrone package is stopped
Status: [1]
```


```
ash-4.3# /var/packages/nzbdrone/scripts/start-stop-status start
Starting  ...
/var/packages/nzbdrone/scripts/service-setup: line 19: type: service_prestart: not found
/var/packages/nzbdrone/scripts/start-stop-status: line 29: [: too many arguments
```


If I revert the change 
#if [ ${SYNOPKG_DSM_VERSION_MAJOR} -lt 6 ]; then EFF_USER="${SYNOUSER_PREFIX}${USER}"; else EFF_USER="${PRIV_PREFIX}${USER}"; fi
 EFF_USER="${SYNOUSER_PREFIX}${USER}";


```/var/packages/nzbdrone/scripts/service-setup: line 6: [: -lt: unary operator expected
Starting  ...
/var/packages/nzbdrone/scripts/service-setup: line 19: type: service_prestart: not found
/var/packages/nzbdrone/scripts/start-stop-status: line 29: [: too many arguments
```

**Comment by Safihre** [comment]
You cannot start it on the command-line like that anymore. It has to be done from the package manager.

**Comment by jerrevds** [comment]
Hi
If I start from the package manager it shows a minute starting and it jumps
then to stopped without any logs

**Comment by Leempi** [comment]
I have the same issue as Jerrevds. Starting from package manager doesn't work.

**Comment by techhitnz** [comment]
I have the same problem too.  And I'm running DSM 5.2

**Comment by ymartin59** [comment]
What content is available in "View log" action when viewing package in Package Center?

**Comment by jerrevds** [comment]
The message in the log is just "starting NZB env PATH = "...."

[image: image.png]

(see also screenshot)


Op ma 25 jun. 2018 om 21:41 schreef Yves Martin <notifications@github.com>:
