### ISSUE TITLE
debian-chroot: Permissions to shared folders on volume1

### ISSUE THREAD

**Issue by Caleb9** [SynoCommunity/spksrc#3286]
Hi, sorry if this was answered before but I could not find a solution. I installed debian-chroot (8.4-7) on my DS415+ (DSM 6.1.6-15266 Update 1) and managed to overcome most of the hurdles with starting services on boot etc. but there's one thing I can't figure out, i.e. permissions on the shared folders in mounted /volume1. I edited the start-stop-status script and added the `grep -q "${CHROOTTARGET}/volume1 " /proc/mounts || mount -o bind /volume1 ${CHROOTTARGET}/volume1` line so it mounts. In non-chroot environment permissions on the shares look as follows:
```
$ ls -l /volume1/
total 1.9M
drwxr-xr-x  1 root            root            154 Apr 16 17:45 @appstore/
drwxr-xr-x  1 admin           users            58 Apr  7 16:36 @database/
drwxr-xr-x  1 DownloadStation DownloadStation  64 Apr 18 10:31 @download/
drwxrwxrwx+ 1 root            root             48 Apr 18 19:12 @eaDir/
drwxr-xr-x  1 root            root              8 Apr 11 22:26 git/
drwxrwxrwx+ 1 root            root             66 Apr 16 21:07 homes/
drwxrwxrwx+ 1 root            root             38 Apr 16 21:07 music/
drwxrwxrwx+ 1 root            root             22 Apr 16 21:07 photo/
d---------+ 1 root            root             56 Apr 16 21:07 Plex/
drwxr-xr-x  1 root            root             24 Apr  7 16:37 @S2S/
-rw-------  1 root            root            21M Apr 17 08:17 @syslog-ng.core
drwxrwxrwt  1 root            root             32 Apr 18 19:09 @tmp/
drwxrwxrwx+ 1 root            root             22 Apr 16 21:07 video/
```
but in chroot it looks like this:
```
$ ls -l /volume1/
total 1,9M
drwxr-xr-x 1 root   root   154 Apr 16 17:45 @appstore/
drwxr-xr-x 1   1024 users   58 Apr  7 16:36 @database/
drwxr-xr-x 1 125560 125560  64 Apr 18 10:31 @download/
drwxrwxrwx 1 root   root    48 Apr 18 19:12 @eaDir/
drwxr-xr-x 1 root   root     8 Apr 11 22:26 git/
drwx--x--x 1 root   root    66 Apr 16 21:07 homes/
d--------- 1 root   root    38 Apr 16 21:07 music/
d--------- 1 root   root    22 Apr 16 21:07 photo/
d--------- 1 root   root    56 Apr 16 21:07 Plex/
drwxr-xr-x 1 root   root    24 Apr  7 16:37 @S2S/
-rw------- 1 root   root   21M Apr 17 08:17 @syslog-ng.core
drwxrwxrwt 1 root   root    32 Apr 18 19:09 @tmp/
d--------- 1 root   root    22 Apr 16 21:07 video/
```
so all the shares have no access whatsoever. All the files/folders underneath those shares have also no access. Is there any way to change that?
Thanks in advance.

**Comment by ymartin59** [comment]
debian-chroot package has never been updated for DSM 6 - unexpected behavior have already been reported, typically trying to uninstall package may put your full DSM system into troubles.
That package is really complex and is not our top priority at the moment.

**Comment by Caleb9** [comment]
Ok, that's a pity but thanks.

**Comment by luckman212** [comment]
Without checking github issues first, I installed Debian Chroot on my DS1515+ (DSM 6.2-23739). After it wouldn't start, I realized the package doesn't work with DSM6 and I also saw uninstalling it can brick your DSM 👎 

So - now what do you suggest? Is there a safe or manual way to remove this package? Thank you

**Comment by ymartin59** [comment]
@luckman212 I recommend you to let package "as-is" on your DSM. I think the few MiB consumed on your disk is "afordable".

**Comment by luckman212** [comment]
Ok, I will leave it. But, in case anyone knows a safe way to remove it, that would be great to know still.

**Comment by Caleb9** [comment]
@luckman212 It bothered me to leave this thing installed. I gave up on using it and to be safe I made a backup and did a reset of my DS (i.e. reinstalled the DSM). Hope there are some alternatives enabling installation of Linux tools such as Screen and Emacs on DS, but for now I will just have to live without them 👎

**Comment by ymartin59** [comment]
@Caleb9 "screen" is available in "Disk Utils" package (ok not obvious... we have planned to refactor packages) and emacs is in progress #3352
