### ISSUE TITLE
Transmission won't upgrade/install

### ISSUE THREAD

**Issue by gargamon2** [SynoCommunity/spksrc#3289]
### Setup
_Package Name:_Transmission 
_Package Version:_2.93-14

_NAS Model:_DS413
_NAS Architecture:_Qoriq
_DSM version:_DSM 6.1.6-15266 Update 1

### Expected behavior
Update transmission

### Actual behavior
Attempted upgrade of transmission which failed and removed existing version. Attempts to reinstall give error:
"Port undefined configured for this package is either used by another service or reserved for system use. Please disable or modify the conflicting service, or contact the developer to modify the package configuration" 

_Package Version:_

### Steps to reproduce
_1._Try to upgrade transmission
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
nothing
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_nothjing
Insert log here
```

**Comment by Safihre** [comment]
Restart NAS and try again.

**Comment by gargamon2** [comment]
The NAS has been restarted numerous times and the behavior does not change. Transmission will not install.

**Comment by Safihre** [comment]
I remember a similar bug from before where it turned out to be chroot or some other DNS/firewall application that was blocking installs. Do you have some of those packages installed?

**Comment by gargamon2** [comment]
Nothing like that has been installed. Any chance I can get the old version back?

**Comment by gargamon2** [comment]
Additionally, I can install other packages fine. This is a transmission specific issue.

This NAS has been running fine for a while. There has been very little activity installing packages. 

Is it possible to get a copy of the package so I can try to manually install it to see where it craps out? Which the lack of info installing it through the GUI, it may be a way to get further information.

**Comment by BenjV** [comment]
Just use Download Station, for Bittorent it is also transminsion under the hood.

**Comment by gargamon2** [comment]
I've tried Download Station in the past and found it, like most of the Synology packages, to be bloated and unusable. Transmission has been working for years, and is tightly integrated with the rest of my network using flexget, etc. There should be no reason it stops because of a failed update.

I prefer to use the basic utilities like transmission, flexget and hook them together to accomplish what I want, not what some Synology engineer thinks the average dumb user needs.

**Comment by BenjV** [comment]
The average "dumb" user is very happy not to need to use the stupid userinterface of Transmission.

But besides that you most likely have a leftover of the Transmission and DSM thinks the Transmission port is still in use.

Log into your Nas with putty as admin and check the in use ports with the following command.

> sudo servicetool --runtime-port-conflict-check --tcp --all-used-ports

**Comment by Teryon** [comment]
change regional setting to english, update and change regionnal setting back to your language.

**Comment by gargamon2** [comment]
Thanks for all the tips. I won't be back to where the NAS is for at least a month so cannot test any of the suggestions.

BenjV, the NAS was running transmission fine, an attempt to upgrade it failed and removed the old version. I'm just trying to get back to what was functioning. If there are remnants of the old transmission there, its due to the upgrade not cleaning up after itself.

Teryon, it should be English already. If it isn't, I'll try your suggestion.

**Comment by BenjV** [comment]
Has nothing to do with Transmission itself.
It is the package that does this.

And no, you cannot go back to the old package because that can only be installed on DSM versions before  DSM 6.
Because you migrated from a DSM 5 to a DSM 6 version with the old packages already installed it kept working.

**Comment by gargamon2** [comment]
So the big mistake then was to upgrade DSM. This seems to be a recurring theme with Synology. What's  the procedure to downgrade back to DSM 5?

**Comment by BenjV** [comment]
It is not possible to downgrade to DSM 5 without extended tweaking.
It would also not very smart to do so.

DSM 6 upgraded the security concept to prevent things like synolocker and other hacks, just like all other systems like windows did.
In the past (pre DSM 6) all data was accessible to everybody and that was a very big exposure.

The biggest problem is that most users don't have a clue how security and privileges work and don't bother to read wiki's the SynoCommunity has created.
It just has to work and only when they get hacked they are shouting "shame on the lack of security".

**Comment by BenjV** [comment]
If you are so smart why ask it here?
And if you got good advise why ignore it and keep on whining.
