### ISSUE TITLE
[Package Request] Debian chroot for DS218play

### ISSUE THREAD

**Issue by christophe-lyon** [SynoCommunity/spksrc#3290]
Hello,

I've just purchased a DS218play NAS, replacing my old DS209...
I now need something to replace ipkg and I wanted to use the Debian chroot provided by the SynoCommunity, but it seems it's not available for this architecture. DS218play uses an AArch64 processor.

Maybe I can help with the package generation?

Thanks

**Comment by Safihre** [comment]
See comment of @ymartin59 here: #3031

**Comment by christophe-lyon** [comment]
Hmm, yes I did see that other request (which isn't closed BTW).

I did manage to build it on my side, but couldn't install it because DSM says there's a dependency on python, which I wasn't able to build so far because pip complains:
`pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.`
(Which is probably a problem on my side)

**Comment by Safihre** [comment]
Try using the Python package from #3138 and link `python` to `/usr/local/python/bin/python`.
There is also `pip` in there.
