### ISSUE TITLE
Transmission 2.93-14: permissions issues

### ISSUE THREAD

**Issue by aitorbear** [SynoCommunity/spksrc#3291]
### Setup
_Package Name:_Transmission 
_Package Version:_2.93-14

_NAS Model:_DS415play
_NAS Architecture:_Intel Atom Dual Core 1.6GHz
_DSM version:_DSM 6.1.6-15266 Update 1

### Expected behavior
Change location folder

### Actual behavior
Since lastest update cannot change files location/folder.
In previous version wasn't any problem, I could change file's folder .

### Steps to reproduce
_1._Select file & right click on it
_2._Select "Set Location" option, type the new folders path and Apply
_3._When open again "Set Location" window there appears the previous folder
_4._Rebooted NAS nut same behaivour.

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
And did you give the group sc-download read/write access to that location?

**Comment by aitorbear** [comment]
This was my fault. I didn't expected I had to do it. Is this something new of this version?
I just change the permissions and now is working well.

Thank you

**Comment by BenjV** [comment]
As of DSM 6 the packages are run as with an hidden user, that cannot been seen in the DSM gui.
Also in the past (pre DSM 6) all users were member of the group users and so all users had access to alle files of every package.
That is not very secure, so Synology changed that and now you have to grant those privs yourself.

As a result a lot of packages did not work if they were installed new on DSM 6.
Now the SynoCommunity has adapted the framework for this change and starting to role out these new packages.

**Comment by Safihre** [comment]
What @BenjV says 👍
