### ISSUE TITLE
Couch Potato renamer.scan script no longer has permission to downloads folder

### ISSUE THREAD

**Issue by kevox** [SynoCommunity/spksrc#3307]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Couch Potato
_Package Version:_ 20141013-6

_NAS Model:_ DS1513+
_NAS Architecture:_ INTEL Atom D2700
_DSM version:_ DSM 6.1.6-15266 Update 1

### Expected behavior
After SABnzbd has completed a download and is named in a way that Couch Potato is expecting (i.e. Hot.New.Movie.2018.cp(tt0000000)), the renamer.scan should be able to rename the movie (if required) and move it to the apropriate folder for your PVR application to be able to access it.

### Actual behavior
Since updating SABnzbd (and introducing sc-download group), the Couch Potato renamer.scan cannot even "see" the folder and the log file reports this and instructs the user to create it. 

### Steps to reproduce
_1._ Download a movie using SABnzbd, or place a completed download in the /downloads/complete/Movies directory
_2._ Manually trigger the renamer.scan script using the API key of Couch Potato
_3._ Note that the movie does not get processed, and CP logs record the inability to see the downloads directory.

#### Package log
```05-07 08:31:57 ERROR
[tato.core.plugins.renamer] The from folder "/volume1/downloads/complete/Movies" doesn't exist. Please create it.```
#### Other logs
05-06 15:04:16 ERROR
[tato.core.plugins.browser] Failed getting directory "/volume1/downloads/" : Traceback (most recent call last): File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/browser.py", line 96, in view dirs = self.getDirectories(path = path, show_hidden = show_hidden) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/browser.py", line 60, in getDirectories for f in os.listdir(path): OSError: [Errno 13] Permission denied: '/volume1/downloads'
```

**Comment by ymartin59** [comment]
Please get Couch Potato for your architecture from #3138
Publish is pending because of troubles with some archs.

**Comment by ymartin59** [comment]
I have published Couch Potato (and Custom variant) in online repository. It should fix your troubles. May you please report feedback about this you version and close this issue if relevant.

**Comment by aelkaim** [comment]
I'm facing the same problem with 20180513-7 Couchpotato version on Syno 1817.
Logs shows that it is unable to create a folder, or move the movie, it has identified after complete download.
It says PERMISSION DENIED (errno 11 or 13 ? can't remind)

**Comment by mreid-tt** [comment]
Based on the readme at https://couchpota.to/:

> CouchPotato is not maintained anymore
> Please use any of the alternatives like [Radarr](https://synocommunity.com/package/radarr)

As such, this ticket will be closed.
