### ISSUE TITLE
sickbeard cannot find sabnzdb download folder  -  same NAS

### ISSUE THREAD

**Issue by jmuk10** [SynoCommunity/spksrc#3308]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Sickbeard & SABnzbd
_Package Version:_
alpha (master) -- source : 31ceaf1b5cab1884a280fe3f4609bdc3b1fb3121
Version: | 2.3.3 [1f04343]

_NAS Model:_DS413
_NAS Architecture:_
_DSM version:_Latest

Sickbeard cannot find the folder to run the post process:

All non-absolute folder locations are relative to /usr/local/sickbeard/var
Post-Processing
Settings that dictate how Sick Beard should process completed downloads.
tried to set this to this folder: /volume1/Downloads/complete/TV but it keeps on trying to find it. 

Both sickbeard and SABnzbd are on the same nas/same IP address.

any ideas?

**Comment by ymartin59** [comment]
Please get Sickbeard for your architecture from #3138
Publish is pending because of troubles with some archs.

**Comment by Safihre** [comment]
@ymartin59 Really? Why do these packages depend on the Python upgrade? Just like SAB I don't  know why Sickbeard/CP/Headphones/etc can't be updated, not depended on Python version.

**Comment by Safihre** [comment]
@ymartin59 Can you please publish Couchpotato/Mylar/etc/etc?
Even headphones should work just fine..

**Comment by mreid-tt** [comment]
@jmuk10... checking on some older issues... is this still an ongoing concern or can this ticket be closed?

**Comment by jmuk10** [comment]
Hi,

This can be closed – thank you
