### ISSUE TITLE
Description with quotes break menu/icon shortcut

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3309]
When description contains quotes, there is trouble with `INFO` file but `app/config` is expected to be JSON and quotes in `desc` definitely prevents it to be loaded.
So shortcut is not available.
Options:
- fail build if description contain quotes
- silently remove quotes when generating `app/config`

Found when testing CouchPotato

**Comment by publicarray** [comment]
Or maybe escape quotes with `\"` ?
