### ISSUE TITLE
SABNZBD 2.3.3-34: Update broke my share permissions

### ISSUE THREAD

**Issue by hackgrid** [SynoCommunity/spksrc#3312]
Sabnzbd works fine. 

But the update assistant said it wanted to "fix my permissions".
After that all my users can not access the share which Sabnzbd downloads my files to.

All users, which are member of the default "users" group, can not access the share anymore.
The group had no permissions, I assigned the permission per user. All users still have the permissions, but it does not work.

I can not find a "block access" permission assigned to the default user group either.

Only fix I found that works is to assign the users to the new sc-media and sc-download groups.

Did the update execute some shell-command which results does not get shown in the web gui?

it would be nice if i could fix my permissions somehow. my other shares, which sabnzbd does not access, still work fine.

**Comment by BenjV** [comment]
Now that DSM 6.
The hidden users which run the package are no longer part of the group users.
This is of course a security measure.
In the past all users had access to everything a package created and that is of course not desirable.

And the fix you already found, so what's your issue?

**Comment by hackgrid** [comment]
The issue is, that the upgrade script broke my volume share (the one on which the incomplete and completed folders is located). All user can not access it anymore via SMB.
All users still have the same permission on the share, but it does not work anymore.

I never gave the "users" group permissions.

Somehow the upgrade process broke the share, my user can not access it via SMB, FTP or others, although the users still have permissions.

I do not want to add all remaining users to the "sc-download" group, because they should have only read-only access like before.

I think a update of the sabnzbd addon should not break access to a share completely.

**Comment by BenjV** [comment]
You still don't understand what i was saying.
All normal users created via the DSM GUI are part of the group "users" and so were the package users which run the packages.
But the package users are no longer member of the group users and so the files and folder they create are no longer part of the group "users".

I don't know the SanNzbd package very well but I doubt that the upgrade changed the share itself only the permissions on the folder below it.

You say you don't want to add users to the group "sc-download" because they should have only read-only access but in the past they also had full access via the group "users".

To give them read-only go to FileStation, select the folder you want to give the user access to, rightclick and choose properties, then permissions, if the user is not there click on create and add the desired permissions for that user.

Also read the wiki, especially these pages:
https://github.com/SynoCommunity/spksrc/wiki/Permission-Concept
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by BenjV** [comment]
Still not reading what I say or you do not understand.

It is just a fact that you have to change things and saying "I did not change anything" won't resolve anything.
And your user don't have these permissions and just saying that they have is pointless.

You either follow advice and stop complaining or stop using packages from the SynoCommunity.

**Comment by hackgrid** [comment]
Then please tell me how to fix this.

My users have the permission to access the volume.
But it does not work.

Only way to gain access is to be member of the sc-download group.
It seems somehow the permission changed so, that only the new group can access and no other user/group. Even if permissioned directly. And this is not correct.

It seems you don't understand.

This has nothing to with these topics

https://github.com/SynoCommunity/spksrc/wiki/Permission-Concept
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

The wizard broke something while trying to "fix" the permissions of the volume.

**Comment by hackgrid** [comment]
This user has readonly access ("Nur Lesen") to "web" and "webshare".
"webshare" is the volume on which the sabnzbd folders were created.

![user](https://user-images.githubusercontent.com/54060/39965523-0f172e7a-569b-11e8-8c08-ddf00378c316.PNG)

As this user, accessing "web" in File Station works.

![works](https://user-images.githubusercontent.com/54060/39965527-1a8bdce2-569b-11e8-807e-1b02fac6bdea.PNG)

Accessing "webshare" does not work.

![error](https://user-images.githubusercontent.com/54060/39965529-2b7a6e24-569b-11e8-9a81-3d5ff57c69d0.PNG)

("user has no right to execute this action")

I guess the upgrade script changed the sole ownership of the volume to the "sc-download" group.
You can not change or view that with the web gui. Do you know how i could change this via SSH?

https://github.com/SynoCommunity/spksrc/blob/master/spk/sabnzbd/src/service-setup.sh

Since this script tries to get the folder paths and change permission I think it is very possible that something went wrong here.

**Comment by BenjV** [comment]
As I said ( and as you can see in the link you posted) this script does not change the access to (in this case) webshare, just to the folders below them.

Remember that a deny has always precedent over allow, so if allow read/write access for a user but the group has a deny access the result will be a deny. 

Did you check the ACL settings of your share as explained in the wiki?

**Comment by ymartin59** [comment]
@hackgrid What is your DSM version and architecture? If upgraded from DSM 5, confirm that `webshare` has ACL enabled.
Then you have to grant at least read permissions to group `sc-download` to your `webshare` shared folder and read-write to specific subfolder where sabnzbd expects to write - should be ok already, just confirm opening file properties and permissions settings.
For your regular non-admin users, group `users` has to be granted read access to `webshare` with ACL too.

**Comment by jbl85** [comment]
Same problem here...

Upgrading to 2.3.3-34 breaks the permission folder where sab download content. According to DSM, users can access to the folder but when i try, it says denied.
--------------
DSM 6.2
sc-download has access to the folder and can download
users can't access the folder
NFS is not allowed anymore
-------------

Any help are welcome :)

**Comment by BenjV** [comment]
Read this wiki and remember that setting permissions does not change permissions on existing folders and files, you have to change them with File Station.
And the groep users is for DSM users not for applications anymore.

https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by jbl85** [comment]
Thank you ! ACL conversion fixed the problem
