### ISSUE TITLE
Sickrage 20180228-5 not starting at install: raven problem

### ISSUE THREAD

**Issue by fgibaux** [SynoCommunity/spksrc#3314]
### Setup
_Package Name:_ Sickrage from #3138 
_Package Version:_ 20180228-5 
_Python version:_  python_rtd1296-6.1_2.7.14-18.spk from #3138

_NAS Model:_ DS418
_NAS Architecture:_ rtd1296
_DSM version:_ DSM 6.1.6-15266 Update 1

### Expected behavior
sickrage to start

### Actual behavior
sickrage doesn't start; see package log

### Steps to reproduce
_1._ install package with default options
_2._ a message says "launch manually the package to restore package" (approximately from my memory)
_3._ the log says there is no module raven
_4._ clicking on launch button try to start the package but fail

#### Package log
```
Sat May 12 18:05:36 WEST 2018
Starting sickrage command /volume1/@appstore/sickrage/env/bin/python /volume1/@appstore/sickrage/var/SickRage/SiCKRAGE.py --daemon --pidfile /volume1/@appstore/sickrage/var/sickrage.pid --config /volume1/@appstore/sickrage/var/config.ini --datadir /volume1/@appstore/sickrage/var/ 
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickrage/__init__.py", line 219, in main
    from sickrage.core import Core
  File "/volume1/@appstore/sickrage/var/SickRage/sickrage/core/__init__.py", line 53, in <module>
    from sickrage.core.logger import Logger
  File "/volume1/@appstore/sickrage/var/SickRage/sickrage/core/logger.py", line 29, in <module>
    import raven
ImportError: No module named raven
Failed to import required libs, please run 'pip install --user -U -r /volume1/@appstore/sickrage/var/SickRage/requirements.txt' from console
```

for the context: I got it working a few month ago, then last month after apparently some changes in my config it wouldn't start complaining about an openssl problem. I think at that time I uninstalled it and reinstalled, was working until my change in the config. forgot about it for a while, and today, while investigating the issue, trying the uninstall/reinstall I get this raven error instead.

I did not try to run the pip command in the console as I'm not sure if it's safe to do so. should I run it in the sickrage env after a `source bin/activate` ?

**Comment by ymartin59** [comment]
This a known bug for ARM architectures. Under investigation: #3201 #3246

**Comment by ymartin59** [comment]
@Safihre Is it possible an internal Sickrage "auto-update" leads to a new version with different "requirements" that prevents built package to run it?

**Comment by BenjV** [comment]
Just get rid of that stupid echelon version and use Sickbeard-Custom to install the real SickRage.

**Comment by fgibaux** [comment]
Hi, Thanks for your inputs.

Indeed in the installation steps, there is a prompt for which fork to use.
Default value is master branch of `https://git.sickrage.ca/sickrage/sickrage.git`. @BenjV is that what you're referring to as the echelon version ? is `https://github.com/SickRage/SickRage` the real SickRage ?

Looking at the tags on both repo shows a lot of version since 20180228, I suppose the package auto-update to latest master at install ?

**Comment by Safihre** [comment]
Exactly. It fetches the latest master during the install (that's why it takes a while) and then installs the dependencies (another reason it takes long).

**Comment by ymartin59** [comment]
@Safihre You already know I consider such "auto-update" feature a bad idea for users (may break for many reasons, cannot revert to an original tested version) and here is another situation which prevents package to be reliable: some "new" requirements may not be available as wheels because it requires compilation (what DSM is not ready for)...

**Comment by fgibaux** [comment]
Ok, Following @BenjV advice, I switched to Sickbeard-Custom package using `git://github.com/SickRage/SickRage.git` fork url. I'll see how it goes, but for now seems to do what I need.
Thanks again for your help.

**Comment by Dark2004** [comment]
Hello,
for me it's not working with DSM 6.2-23731 even if it take the version 3138 and change the to it://github.com/SickRage/SickRage.git fork url package does not want to start
