### ISSUE TITLE
sc-syncthing user isn't part of syncthing group

### ISSUE THREAD

**Issue by Magissia** [SynoCommunity/spksrc#3321]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Syncthing
_Package Version:_0.14.43.14

_NAS Model:_DS918+
_NAS Architecture:_Apollolake
_DSM version:_6.1.6-15266 Update 1

### Expected behavior
Package created user sc-syncthing being part of package created group syncthing
### Actual behavior
sc-syncthing is not part of syncthing group when installing the package.
### Steps to reproduce
_1._Install Syncthing
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Sun May 13 19:44:22 CEST 2018
Step preinst. USER=syncthing GROUP= SHARE_PATH=
Sun May 13 19:44:22 CEST 2018
Step postinst. USER=syncthing GROUP= SHARE_PATH=
Installing service configuration /var/packages/syncthing/conf/syncthing.sc
Invoke service_postinst

```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
sudo ./synogroup --member syncthing
Group Name: [syncthing]
Group Type: [AUTH_LOCAL]
Group ID:   [104555]
Group Members: 


```

**Comment by BenjV** [comment]
Why should you expect/need a syncthing group?

**Comment by Magissia** [comment]
I don't expect one, but one is created with the package and not used,
either don't create one, or use it properly.

**Comment by BenjV** [comment]
Why create an issue about something you don't see?

This package is not yet update to the new package requirements of DSM 6 so DSM creates a hidden group sc-syncthing.
It also creates an hidden user to run the package.
If you don't like it you should complain to Synology not here.

**Comment by ymartin59** [comment]
@BenjV This package comes from #3138 and has been adapted to DSM 6
@Magissia Service user and group are created by DSM 6 package framework. We conform to guidelines to avoid to run application services as root: https://developer.synology.com/developer-guide/privilege/preface.html
