### ISSUE TITLE
nzbget build-in updater does not work

### ISSUE THREAD

**Issue by M0UL** [SynoCommunity/spksrc#3323]
### Setup
_Package Name:_ nzbget
_Package Version:_20180322-25

_NAS Model:_ DS415+
_NAS Architecture:_avaton
_DSM version:_DSM 6.1.6-15266 Update 1

### Expected behavior
That nzbget build-in updater works when updating.

### Actual behavior
The nzbget updater does not work (to test version) due to permission errors.

### Steps to reproduce
try to update.

#### Other logs
nzbget build in updater log:
```
Executing update-script /volume1/@appstore/nzbget/bin/install-update.sh
Downloading version information...
nzbget.conf(55): Invalid value for option "TempDir" (/volume1/@appstore/nzbget/bin/downloads/tmp): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/tmp: errno 13, Permission denied
nzbget.conf(52): Invalid value for option "QueueDir" (/volume1/@appstore/nzbget/bin/downloads/queue): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/queue: errno 13, Permission denied
nzbget.conf(46): Invalid value for option "NzbDir" (/volume1/@appstore/nzbget/bin/downloads/nzb): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/nzb: errno 13, Permission denied
Downloading verification signature...
nzbget.conf(55): Invalid value for option "TempDir" (/volume1/@appstore/nzbget/bin/downloads/tmp): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/tmp: errno 13, Permission denied
nzbget.conf(52): Invalid value for option "QueueDir" (/volume1/@appstore/nzbget/bin/downloads/queue): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/queue: errno 13, Permission denied
nzbget.conf(46): Invalid value for option "NzbDir" (/volume1/@appstore/nzbget/bin/downloads/nzb): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/nzb: errno 13, Permission denied
Downloading nzbget-20.0-testing-r2181-bin-linux.run...
nzbget.conf(55): Invalid value for option "TempDir" (/volume1/@appstore/nzbget/bin/downloads/tmp): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/tmp: errno 13, Permission denied
nzbget.conf(52): Invalid value for option "QueueDir" (/volume1/@appstore/nzbget/bin/downloads/queue): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/queue: errno 13, Permission denied
nzbget.conf(46): Invalid value for option "NzbDir" (/volume1/@appstore/nzbget/bin/downloads/nzb): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/nzb: errno 13, Permission denied
Verifying package authenticity...
nzbget.conf(55): Invalid value for option "TempDir" (/volume1/@appstore/nzbget/bin/downloads/tmp): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/tmp: errno 13, Permission denied
nzbget.conf(52): Invalid value for option "QueueDir" (/volume1/@appstore/nzbget/bin/downloads/queue): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/queue: errno 13, Permission denied
nzbget.conf(46): Invalid value for option "NzbDir" (/volume1/@appstore/nzbget/bin/downloads/nzb): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/nzb: errno 13, Permission denied
Updating NZBGet...
...
Installer for nzbget-20.0-testing-r2181
Verifying package...
Checking system...
CPU-Architecture: x86_64
Unpacking...
/volume1/share/config/nzbget/tmp/nzbget-20.0-testing-r2181-bin-linux.run: line 249: /volume1/@appstore/nzbget/bin/installer.tmp: Permission denied
Update failed, installer terminated with error status
```

**Comment by BenjV** [comment]
Read the wiki.

https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by ymartin59** [comment]
@Safihre I wonder if "bin/downloads/" is a relevant location for files? Isn't it a incorrect package setup that prevents auto-update to work?

**Comment by M0UL** [comment]
@BenjV how does that apply here? most of the locations are not even accessible from the dsm web ui.

**Comment by Safihre** [comment]
I updated the starting post to print the log correctly and as you can see @M0UL has placed his downloads folder inside the package program folder...... 
That's a super bad idea and something one should never do and something we don't support. 
It's also something the user has to actively choose to do. By default the package will use the folder you set during the wizard.

@M0UL please fix your paths to a location on your shares, not in the app folder.

**Comment by Safihre** [comment]
It's a bad and unsupported location because if we ever publish an update to the package, you will loose all your downloads. Since the Synology package updater removes the whole package folder in `@appstore/nzbget` during an update.

**Comment by M0UL** [comment]
al my nzbget config en download are located in my share. (/volume1/share/). 
![image](https://user-images.githubusercontent.com/5436726/40266297-fec25d3a-5b48-11e8-9573-95ab6d645678.png)

**Comment by Safihre** [comment]
That's strange, the log shows something else.

Can you run the commands:
```
ls -al /volume1/@appstore/nzbget
ls -al /volume1/@appstore/nzbget/bin
```
When I do so it nicely shows that they are owned by the `sc-nzbget` user and updating works. Something must have broken those permissions on your system, otherwise I would have expected many more bug reports here..

**Comment by BenjV** [comment]
I did not completely analyse the package but during a normal installation these locations are set by the wizard.
During upgrade that is not the case, so does the package read the nzbget condig file in that case?
If not they will most likely be set to the same as the application location.

**Comment by M0UL** [comment]
toren@DISKSTATION:~$ ls -al /volume1/@appstore/nzbget
total 28
drwxr-xr-x  7 sc-nzbget nzbget 4096 Mar 24 11:58 .
drwxr-xr-x 24 root      root   4096 May 14 20:55 ..
drwxr-xr-x  3 sc-nzbget nzbget 4096 Mar 18 20:15 app
drwxr-xr-x  5 sc-nzbget nzbget 4096 May 15 19:43 bin
drwxr-xr-x  3 sc-nzbget nzbget 4096 Mar 18 20:14 lib
drwxr-xr-x  3 sc-nzbget nzbget 4096 Mar 18 20:14 share
drwxr-xr-x  2 sc-nzbget nzbget 4096 May 12 15:36 var
toren@DISKSTATION:~$ ls -al /volume1/@appstore/nzbget/bin
total 7796
drwxr-xr-x 5 sc-nzbget nzbget    4096 May 15 19:43 .
drwxr-xr-x 7 sc-nzbget nzbget    4096 Mar 24 11:58 ..
-rwxr-xr-x 1 sc-nzbget nzbget      59 Mar 18 20:14 7z
-rwxr-xr-x 1 sc-nzbget nzbget 1197856 Jul  8  2017 7za
-rwxr-xr-x 1 sc-nzbget nzbget      60 Mar 18 20:14 7zr
-rwxr-xr-x 5 sc-nzbget nzbget   27584 Mar 18 20:14 addgroup
-rwxr-xr-x 5 sc-nzbget nzbget   27584 Mar 18 20:14 adduser
-rwxr-xr-x 5 sc-nzbget nzbget   27584 Mar 18 20:14 busybox
-rw-r--r-- 1 sc-nzbget nzbget  256008 Jul  8  2017 cacert.pem
-rw-r--r-- 1 sc-nzbget nzbget  169390 Jul  8  2017 ChangeLog
-rw-r--r-- 1 sc-nzbget nzbget   18009 Jul  8  2017 COPYING
-rwxr-xr-x 5 sc-nzbget nzbget   27584 Mar 18 20:14 delgroup
-rwxr-xr-x 5 sc-nzbget nzbget   27584 Mar 18 20:14 deluser
d--------- 2 sc-nzbget nzbget    4096 Apr 14 15:11 downloads
-rw-r--r-- 1 sc-nzbget nzbget      24 Mar 24 11:59 installer.cfg
---------- 1 sc-nzbget nzbget      12 May 15 19:43 installer.tmp
-rwxr-xr-x 1 sc-nzbget nzbget    5167 Jul  8  2017 install-update.sh
-rw-r--r-- 1 sc-nzbget nzbget    1878 Jul  8  2017 license-7zip.txt
-rw-r--r-- 1 sc-nzbget nzbget    1976 Jul  8  2017 license-unrar.txt
-rwxr-xr-x 1 sc-nzbget nzbget 5538816 Jul  8  2017 nzbget
-rw-r--r-- 1 sc-nzbget nzbget   67276 Mar 24 11:59 nzbget.conf
-rw-r--r-- 1 sc-nzbget nzbget     451 Jul  8  2017 pubkey.pem
-rw-r--r-- 1 sc-nzbget nzbget   15876 Jul  8  2017 README
drwxr-xr-x 2 sc-nzbget nzbget    4096 Jul  8  2017 scripts
-rwxr-xr-x 1 sc-nzbget nzbget  499744 Jul  8  2017 unrar
drwxr-xr-x 4 sc-nzbget nzbget    4096 Jul  8  2017 webui

**Comment by Safihre** [comment]
Try removing the `installer.cfg` and `installer.tmp` files.

**Comment by M0UL** [comment]
that breaks the updater:
Executing update-script /volume1/@appstore/nzbget/bin/install-update.sh
File "installer.cfg" is missing in the installation directory. Please reinstall NZBGet.

**Comment by Safihre** [comment]
Well, that's something. I thought the `installer.cfg` was ours. Oops.
