### ISSUE TITLE
SABNZBD 2.3.3-34 update: Cannot start package service

### ISSUE THREAD

**Issue by Huppeltje16** [SynoCommunity/spksrc#3325]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_SABNZBD 
_Package Version:_2.3.3-34

_NAS Model:_DS412+
_NAS Architecture:_
_DSM version:_6.1.6-15266

### Expected behavior
Update and restart SABNZBD

### Actual behavior
Update and unable to start package service

### Steps to reproduce
_1._Running previous package version (unsure which version)
_2._Update using package center
_3._Package refuses tot start.

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
Tue May 15 15:16:19 CEST 2018
Starting sabnzbd command env LANG=en_US.UTF-8 /volume1/@appstore/sabnzbd/env/bin
/python /volume1/@appstore/sabnzbd/share/SABnzbd/SABnzbd.py -f /volume1/@appstor
e/sabnzbd/var/config.ini --pidfile /volume1/@appstore/sabnzbd/var/sabnzbd.pid -d

Error:
Can't write to logfile

Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
2018/05/15 14:49:05     start sabnzbd: begin to start version 2.3.3-34
2018/05/15 14:49:06     start sabnzbd 2.3.3-34 Begin pre-load apparmor
2018/05/15 14:49:06     start sabnzbd 2.3.3-34 End pre-load apparmor ret=[0]
2018/05/15 14:49:06     start sabnzbd 2.3.3-34 Begin start-stop-status start
Starting sabnzbd ...
/var/packages/sabnzbd/scripts/service-setup: line 20: type: service_prestart: not found
2018/05/15 14:49:32     start sabnzbd 2.3.3-34 End start-stop-status start ret=[1]
2018/05/15 14:49:33     (system) trigger sabnzbd 2.3.3-34 Begin start-stop-status stop
sabnzbd is not running
2018/05/15 14:49:33     (system) trigger sabnzbd 2.3.3-34 End start-stop-status stop ret=[0]
2018/05/15 14:49:33     (system) trigger sabnzbd 2.3.3-34 Begin unload apparmor
2018/05/15 14:49:33     (system) trigger sabnzbd 2.3.3-34 End unload apparmor ret=[0]
2018/05/15 14:49:34     stop sabnzbd: begin to stop version 2.3.3-34
2018/05/15 14:49:34     stop sabnzbd: stop version 2.3.3-34 successfully, result 0
2018/05/15 14:49:34     start sabnzbd: start version 2.3.3-34 failed, result 272
2018/05/15 15:16:18     start sabnzbd: begin to start version 2.3.3-34
2018/05/15 15:16:19     start sabnzbd 2.3.3-34 Begin pre-load apparmor
2018/05/15 15:16:19     start sabnzbd 2.3.3-34 End pre-load apparmor ret=[0]
2018/05/15 15:16:19     start sabnzbd 2.3.3-34 Begin start-stop-status start
Starting sabnzbd ...
/var/packages/sabnzbd/scripts/service-setup: line 20: type: service_prestart: not found
2018/05/15 15:16:42     start sabnzbd 2.3.3-34 End start-stop-status start ret=[1]
2018/05/15 15:16:42     (system) trigger sabnzbd 2.3.3-34 Begin start-stop-status stop
sabnzbd is not running
2018/05/15 15:16:42     (system) trigger sabnzbd 2.3.3-34 End start-stop-status stop ret=[0]
2018/05/15 15:16:42     (system) trigger sabnzbd 2.3.3-34 Begin unload apparmor
2018/05/15 15:16:42     (system) trigger sabnzbd 2.3.3-34 End unload apparmor ret=[0]
2018/05/15 15:16:43     stop sabnzbd: begin to stop version 2.3.3-34
2018/05/15 15:16:43     stop sabnzbd: stop version 2.3.3-34 successfully, result 0
2018/05/15 15:16:43     start sabnzbd: start version 2.3.3-34 failed, result 272
Insert log here
```

**Comment by BenjV** [comment]
Read these wiki pages and take action as written there.

https://github.com/SynoCommunity/spksrc/wiki/Permission-Concept
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by Huppeltje16** [comment]
@ymartin59 Thx for the comment.
I am reluctant at reinstalling sabnzbd because I have quite some specific settings, bat after changing the group on the current log directory and the database directories, sabnzbd now runs again.
An alternate approach would have been to change the log and database settings in the config.ini file.
