### ISSUE TITLE
No tvheadend in the repo?

### ISSUE THREAD

**Issue by sylvio2000** [SynoCommunity/spksrc#3328]
Hi.
I am absolutely new to Synology and would like to install tvh. I added the community repo http://packages.synocommunity.com/ but there is no tvh package.

What can I do to get the package?

I am using a DS418play with DSM 6.2

**Comment by ymartin59** [comment]
Package is available for apollolake as "beta": https://synocommunity.com/package/tvheadend
You have to edit Package Center settings and allow beta packages.

**Comment by ymartin59** [comment]
SynoCommunity package "tvheadend 4.2.6-13" is flagged as beta until we receive more feedbacks about its usage on DSM.
