### ISSUE TITLE
Deluge - watch folder not working

### ISSUE THREAD

**Issue by ghost** [SynoCommunity/spksrc#3332]
Hello,
DSM shows me deluge update today (v 1.3.15-9). I updated deluge and found some problems:

- all torrents were red with error about permissions so I edit group permissions for sc-download in DSM (works fine now)
- watch folder doesn't work. Have checked it in settings but if I add some torrent, nothing happened.

Any fix?

**Comment by USRGH** [comment]
just checked /volume1/@appstore/deluge/var/core.conf and watch folder is there but it still doesn't load any torrents.
"autoadd_location": "/volume1/Downloads/_watch",

**Comment by m4tt075** [comment]
Look here and see whether that fixes your problems:
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by USRGH** [comment]
checked (option 1 and option 2). have all permission there for sc-download group but watch folder still doesn't work

**Comment by m4tt075** [comment]
When you edited group premissions for sc-download in DSM (prior to looking at the Wiki), what did you change?

**Comment by m4tt075** [comment]
Or is this an old (DSM5) shared folder, which needs to be converted to ACL permissions first (see the bottom of the page I linked above)?

**Comment by ymartin59** [comment]
@USRGH May you please copy logs here from /var/packages/deluge/target/var/*.log ? Thanks.

**Comment by kantjer** [comment]
Deluge 1.3.15-9 watch folder is working fine for me on DSM

**Comment by USRGH** [comment]
@m4tt075 : didn't change nothing. Have write/read permissions for Downloads folder.
watch folder is in download folder so it's subfolder.

@ymartin59 : found something like this in logs:
WARNING ] 21:27:45 torrentmanager:531 Unable to save torrent file: [Errno 13] Permission denied: u'/volume1/Downloads/_watch/_loaded/tmpSMMlXS.torrent'
[ERROR   ] 21:34:31 core:330 Disabling '/volume1/Downloads/_watch', error during update: [Failure instance: Traceback: <type 'exceptions.OSError'>: [Errno 13] Permission denied: '/volume1/Downloads/_watch'
[INFO    ] 21:35:38 torrentmanager:780 Successfully loaded fastresume file: /volume1/@appstore/deluge/var/state/torrents.fastresume
[INFO    ] 21:35:39 torrentmanager:826 Saving the fastresume at: /volume1/@appstore/deluge/var/state/torrents.fastresume
[INFO    ] 21:35:48 pluginmanagerbase:158 Plugin AutoAdd enabled..
[ERROR   ] 21:35:53 core:330 Disabling '/volume1/Downloads/_watch', error during update: [Failure instance: Traceback: <type 'exceptions.OSError'>: [Errno 13] Permission denied: '/volume1/Downloads/_watch'

**Comment by USRGH** [comment]
some screenshots
![snimka obrazovky 2018-05-31 o 18 11 47](https://user-images.githubusercontent.com/20722830/40801065-4f6e6580-6512-11e8-9ff4-ad7ad1108017.png)
![snimka obrazovky 2018-05-31 o 18 11 50](https://user-images.githubusercontent.com/20722830/40801066-4f922808-6512-11e8-9251-bbebe8895b28.png)
![snimka obrazovky 2018-05-31 o 18 12 10](https://user-images.githubusercontent.com/20722830/40801068-4fb1fbb0-6512-11e8-9128-5d9e4eed4fda.png)
![snimka obrazovky 2018-05-31 o 18 12 50](https://user-images.githubusercontent.com/20722830/40801069-4fd26a1c-6512-11e8-8968-df5aaf2b020d.png)
![snimka obrazovky 2018-05-31 o 18 13 01](https://user-images.githubusercontent.com/20722830/40801071-4ff4ea6a-6512-11e8-9636-06058c944ea3.png)

**Comment by ymartin59** [comment]
@USRGH Strange. May you please do same checking on "_watch" folder itself, opening its properties and specific permissions settings? Also check with ssh and `ls -ld _watch` and report here command output.

**Comment by DylanBeijersbergen** [comment]
@ymartin59 ah thank you for some reason the parent folder permissions weren't inherited. Fixed it manually now...

**Comment by BenjV** [comment]
Two remarks:

One:
Did you checked this:
https://github.com/SynoCommunity/spksrc/issues/3332#issuecomment-393301801

Two:
The "_watch" folder was already created and permissions are set on creation time, so you have to use FileStation to correct the permissions for als subfolder and files of the "Downloads" share who already existed before the upgrade.

**Comment by hgy59** [comment]
@USRGH is this still an open issue for you?

**Comment by th0ma7** [comment]
New version of deluge is being published.  Please reopen the issue if its still occurring.  Thnx in advance.
