### ISSUE TITLE
[Update Request] borgmatic 1.1.15 (part of borg)

### ISSUE THREAD

**Issue by kBite** [SynoCommunity/spksrc#3334]
`borg` `v1.1.5-2` bundles `borgmatic` version `1.0.3`, latest is `1.1.15`. Can someone please update the package?

I was able to successfully build `borgbackup_rtd1296-6.1_1.1.5-2.spk` with Docker, so bumping `borgmatic` version seems uncomplicated:

```
diff --git a/spk/borgbackup/src/requirements.txt b/spk/borgbackup/src/requirements.txt
index 93406ef..2136059 100644
--- a/spk/borgbackup/src/requirements.txt
+++ b/spk/borgbackup/src/requirements.txt
@@ -3,4 +3,4 @@
 #msgpack-python==0.4.8
 
 # Downloaded dependencies
-borgmatic==1.0.3
+borgmatic==1.1.15
```

**Comment by ymartin59** [comment]
@yuroller Hello Yuri. May you please propose a PR with borgmatic update? Thank you in advance.
