### ISSUE TITLE
Jackett Package not showing up with DSM5.2

### ISSUE THREAD

**Issue by dirkr07** [SynoCommunity/spksrc#3335]
Not sure if I can report this here but it's more of a question I guess.
i'm running an older Synology (DS410) with DSM5.2 (latest supported version).

I've added the Synocommunity repo and enabled beta packages but still Jackett is not showing up.
Is this due to DSM being too old or something else?

Thanks!

**Comment by wutr** [comment]
I believe that is indeed the issue. I ran into problems with Jackett a while back, for which uninstalling and re-installing the packages seemed the solution. Unfortunately it was then no longer available for DSM 5, so I had to upgrade to DSM 6, which caused all sorts of issues on its own. I'm sorry this is not an option for you, but at least you now know you can't install it from Synocommunity anymore.

**Comment by ymartin59** [comment]
@m4tt075 According to Mono project, PowerPC is supposed to be supported for Linux. It tries to compile it but fails quite immediately. Would it be possible to enable PPC support upgrading to 5.8.1 or 5.12 at the same ?

```
Making all in metadata
make[6]: Entering directory '/spksrc/spk/mono/work-ppc853x-5.2/mono-5.8.0.108/mono/metadata'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/spksrc/spk/mono/work-ppc853x-5.2/mono-5.8.0.108/mono/metadata'
Making all in sgen
make[6]: Entering directory '/spksrc/spk/mono/work-ppc853x-5.2/mono-5.8.0.108/mono/sgen'
  CC       libmonosgen_la-sgen-debug.lo
sgen-scan-object.h: In function 'check_consistency_callback':
../../mono/metadata/sgen-client-mono.h:168: sorry, unimplemented: inlining failed in call to 'sgen_client_array_data_start': function body not available
sgen-scan-object.h:57: sorry, unimplemented: called from here
../../mono/metadata/sgen-client-mono.h:174: sorry, unimplemented: inlining failed in call to 'sgen_client_array_length': function body not available
sgen-scan-object.h:57: sorry, unimplemented: called from here
../../mono/metadata/sgen-client-mono.h:168: sorry, unimplemented: inlining failed in call to 'sgen_client_array_data_start': function body not available
sgen-scan-object.h:57: sorry, unimplemented: called from here
../../mono/metadata/sgen-client-mono.h:174: sorry, unimplemented: inlining failed in call to 'sgen_client_array_length': function body not available
sgen-scan-object.h:57: sorry, unimplemented: called from here
../../mono/metadata/sgen-client-mono.h:168: sorry, unimplemented: inlining failed in call to 'sgen_client_array_data_start': function body not available
sgen-scan-object.h:57: sorry, unimplemented: called from here
../../mono/metadata/sgen-client-mono.h:174: sorry, unimplemented: inlining failed in call to 'sgen_client_array_length': function body not available
sgen-scan-object.h:57: sorry, unimplemented: called from here
../../mono/metadata/sgen-client-mono.h:161: sorry, unimplemented: inlining failed in call to 'sgen_client_array_element_size': function body not available
sgen-scan-object.h:81: sorry, unimplemented: called from here
../../mono/metadata/sgen-client-mono.h:168: sorry, unimplemented: inlining failed in call to 'sgen_client_array_data_start': function body not available
sgen-scan-object.h:81: sorry, unimplemented: called from here
../../mono/metadata/sgen-client-mono.h:174: sorry, unimplemented: inlining failed in call to 'sgen_client_array_length': function body not available
sgen-scan-object.h:81: sorry, unimplemented: called from here
Makefile:848: recipe for target 'libmonosgen_la-sgen-debug.lo' failed
make[6]: *** [libmonosgen_la-sgen-debug.lo] Error 1
make[6]: Leaving directory '/spksrc/spk/mono/work-ppc853x-5.2/mono-5.8.0.108/mono/sgen'
```

**Comment by m4tt075** [comment]
@ymartin59 I looked into this when I updated Jackett and mono some months ago. Spent several hours but could not get it to work for ppc platforms. I then realized that ppc platforms were already excluded in the old mono versions and skipped it. Not sure how difficult it is.. I have seen that @publicarray just enabled ppc architectures for his new package. @publicarray: Mind taking a look at this?

**Comment by m4tt075** [comment]
@ymartin59 @publicarray Dug a little deeper. According to 
http://www.mono-project.com/docs/compiling-mono/linux/
the required gcc version is 4.8+. The 5.2 toolchains for `ppc853x` do not meet these requirements. 
@dirkr07 Not looking good, I'm afraid. Thought about upgrading your NAS?

**Comment by ymartin59** [comment]
In code, there is already gcc 4.8, C11 and BTLS mention: https://github.com/SynoCommunity/spksrc/blob/master/cross/mono/Makefile#L20
According to Mono release notes and supported platforms, PowerPC support has been improved in recent versions (for Linux, AIX, but now deprecated for PS3 and Wii) but code is now moving forward C/C++ 11, making more and more difficult to build on older gcc.

Really it does not sound a relevant effort to try to get Mono running on PowerPC... there are many other challenging user requests to achieve here with better success chance. Sorry but I prefer to close.

**Comment by m4tt075** [comment]
Agreed. Sorry, @dirkr07.

**Comment by dirkr07** [comment]
No problem! Thanks already for all the investigative effort you guys put in to this :)
guess I'll have to find an alternative or convince myself to upgrade to a more recent NAS!
