### ISSUE TITLE
 Firefox Sync can not be uninstalled (Incorrect MySQL root password) DSM 6.2

### ISSUE THREAD

**Issue by glomme** [SynoCommunity/spksrc#3336]
_For new Package Requests, see the guidelines_  

### Setup
Firefox Sync
V1.5.2-3

DS214+
DSM 6.2-23739

### Expected behavior
When I click on uninstall it should remove the package
### Actual behavior
Doesn't matter if I reset the maria DB password and leave it blank or if I set a password (also checked it with mysql admin and it works) I get the error message: 
Failed to uninstall package.
Incorrect MYSQL root password.
### Steps to reproduce
Go to Firefox sync 1.5
Click on uninstall
type root password
Get error message

#### Package log
 File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 392, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/ffsync/env/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/ffsync/env/lib/python2.7/site-packages/pymysql/connections.py", line 626, in __init__
    self._connect()
  File "/usr/local/ffsync/env/lib/python2.7/site-packages/pymysql/connections.py", line 818, in _connect
    2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e))
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, 'Can\'t connect to MySQL server on u\'localhost\' ((1045, u"Access denied for user \'ffsync\'@\'lo
```

Hope someone can help me with my problem.

**Comment by Magissia** [comment]
The uninstaller tried to connect using the ffsync user and not the root one.
If you do not have the ffsync database user password, you may want to try a blank one, or connect as root user to the database directly and reset the ffsync user password to something you can give to the uninstall wizard.

**Comment by glomme** [comment]
Must have deleted in the mean time the maria db 5 database. Is there any way to setup a new database that I can delete Firfox Sync 1.5. To create a ffsync user is not a real problem. Also if it is a little bit confusing because if you click on delete the mask is asking for the root mysql password like you can see on the screenshot.

https://www.dropbox.com/s/kk229ab040emvjn/2018-06-04_08-28-17.png?dl=0

After you type in the root password (I used the same for the ffsync user I created) a message comes up that the root password is wrong.

Thank you for your help Magissia.
