### ISSUE TITLE
Sickbeard-Custom cannot Start

### ISSUE THREAD

**Issue by BenjV** [SynoCommunity/spksrc#3338]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Sickbeard-Custom
_Package Version: 20151220-4

_NAS Model:_
_NAS Architecture: Noarch
_DSM version: 6.1

### Expected behavior
Non of the sickbeard forks creates a pidfile with the name Sickbeard_custom
The priviledge file is missing, so the package cannot start

### Actual behavior
Package won't start

### Steps to reproduce
_1. Install SickRage from https://github.com/SickRage/SickRage.git
_2. Run the package
_3. Package Centre will report "Failed to run the package service"

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
`/var/log/synopkg.log`_
```
Insert log here
2018/06/04 15:01:05	start sickbeard-custom: begin to start version 20151220-4
2018/06/04 15:01:06	start sickbeard-custom 20151220-4 Begin pre-load apparmor
2018/06/04 15:01:06	start sickbeard-custom 20151220-4 End pre-load apparmor ret=[0]
2018/06/04 15:01:06	start sickbeard-custom 20151220-4 Begin start-stop-status start
Starting SickBeard Custom ...
su: Permission denied
2018/06/04 15:01:07	start sickbeard-custom 20151220-4 End start-stop-status start ret=[1]
2018/06/04 15:01:07	(system) trigger sickbeard-custom 20151220-4 Begin start-stop-status stop
SickBeard Custom is not running
2018/06/04 15:01:07	(system) trigger sickbeard-custom 20151220-4 End start-stop-status stop ret=[0]
2018/06/04 15:01:07	(system) trigger sickbeard-custom 20151220-4 Begin unload apparmor
2018/06/04 15:01:07	(system) trigger sickbeard-custom 20151220-4 End unload apparmor ret=[0]
2018/06/04 15:01:08	stop sickbeard-custom: begin to stop version 20151220-4
2018/06/04 15:01:08	stop sickbeard-custom: stop version 20151220-4 successfully, result 0
2018/06/04 15:01:08	start sickbeard-custom: start version 20151220-4 failed, result 272

**Comment by BenjV** [comment]
@Safihre 
Ok I tested your package and that one does create the correct privilege file.

But the pidfile is still a problem.

@ymartin59 
To me the easiest way seems to make a little table of fork versus package name because normally the package name is equal to the pidfile name.
If you want I can create a wizard_uifile so users can select the correct fork and get the corresponding Package Name to be used.
Maybe it could even be used for all NoArch package that can be downloaded from github.

**Comment by Safihre** [comment]
@BenjV So the forks ignore the `--pidfile` command-line switch? 
Seems for example SiCKRAGE does listen to it: https://github.com/SiCKRAGETV/SiCKRAGE/blob/master/runscripts/init.systemd#L27

**Comment by BenjV** [comment]
I am sorry, I meshed up.
I mixed up the version in the repro and the test version from you.
Your version creates the correct pidfile, namely sickbeard-custom,pid

By the way your version also does not have the problem described in #3339 beeing the '\' in the description line of the config file.
