### ISSUE TITLE
Building zsh-static throws error because zsh.org changed the url for download

### ISSUE THREAD

**Issue by iwestlin** [SynoCommunity/spksrc#3340]
Hi, I was looking for [zsh(with modules) package](https://synocommunity.com/package/zsh-static) for my DS218j, but this package does not support `Marvell Armada 385 88F6820` architecture, so I built it with `make arch-armada38x`, and it thrown error says `http://www.zsh.org/pub/zsh-5.4.2.tar.gz not found`.

It turns out that zsh.org changed the download url of the old version to `http://www.zsh.org/pub/old/...`, so I change [this line](https://github.com/SynoCommunity/spksrc/blob/master/cross/zsh/Makefile#L5) to `PKG_DIST_SITE = http://www.zsh.org/pub/old` and build again...it successfully built out `zsh-static_armada38x-6.1_5.4.2-1.spk`

Then I manually installed this file on my device, it worked! Thanks to this amazing repo and the detailed FAQ, thanks to all your hard work~ 😆

**Comment by Safihre** [comment]
It seems it's being worked on, soon the new version should be in the package center :)
https://github.com/SynoCommunity/spksrc/pull/3331
