### ISSUE TITLE
several packages / services unable to start after update of SabNzbd : "/usr/local/sabnzbd/env/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by SirApokalypse** [SynoCommunity/spksrc#3341]
Please help ! 

After an update of  Sabnzbd from 2.3 .4.34 to version 2.3.4.36 1st my Sabnzbd wouldn't start because id didn't have the right permisions on /var/packages/sabnzbd/......

Last time I've coorected the permissions manually through ssh and it would start.

This time e new error message came up after the permissions seemd to be corrected : Mon Jun  4 21:17:43 CEST 2018
Starting sabnzbd command env LANG=en_US.UTF-8 /volume1/@appstore/sabnzbd/env/bin/python /volume1/@appstore/sabnzbd/share/SABnzbd/SABnzbd.py -f /volume1/@appstore/sabnzbd/var/config.ini --pidfile /volume1/@appstore/sabnzbd/var/sabnzbd.pid -d 
/volume1/@appstore/sabnzbd/env/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

And the WORST scenanrio became a reality because the same error I get with sickbeard-custom (using for sickrage) and for couchpotato-custom etc. all the packages the has been stoppen by the package app before the update.

It was running perfect before that update for years/months. HELP PLEASE !

I only pushed the update button at sabnzbd in the package center ! 
Now everything python (2.7) related won't start anymore ! even not Midnight commander. also not after a reinstall of sabnzbd or sickberad-custum (with the sickrage git).

I've found something from some years ago here but can't make it work with this (old & incomplete) info any more : [369](https://github.com/SynoCommunity/spksrc/issues/369)

_NAS Model:_ DS1512+
_NAS Architecture:_ Cedarview / Intel Athom D2700
_DSM version:_DSM 5.2-5967 Update 7

### Expected behavior
Tell us what should happen

A step by step guide to or quick fix it would be very appreciated.
(I'm not in the mood or have time ,because of a tragic loss in the family last week , right now to test many things.   
```
By the way: imho : you are focussing too much on the (permissions) of DSM 6.0 /6.0 so that update cause problem on older DSM versions & nas devices/models that have been running for years. Stable updates in the package center  became (at least for me)  some what like russian roulette.

**Comment by SirApokalypse** [comment]
could'nt find /usr/local/sabnzbd/sabnzbd_install.log with SSH by putty on my DSM 5.2

tried to uninstall sazbnzbd and restart and install again. 
But right after/at instll I get : "failed to start package service"

and the log in the package center says again : "/usr/local/sabnzbd/env/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory"

**Comment by BenjV** [comment]
Take a look at the package install log of DSM.
You can find it here:
/var/log/synopkg.log

**Comment by ymartin59** [comment]
@SirApokalypse Sorry for that but we also tested package upgrade on DSM 5.2 (with standard regular usage) and upgrade path from DSM 5 to DSM 6... not simple at all.
If you were comfortable to run applications as root with eventually access from internet, we were not.
I have two options for you:
- either un-install python applications package and python package itself, and install them again from repository
- either report some diagnostic information so that we have a chance to provide some commands to try to fix

Please report output of:
- `/usr/local/python/bin/python -v`
- `ls -l /usr/local/python/lib/libpython*`

**Comment by hgy59** [comment]
I think two years later, nobody bothers about migration from DSM 5
