### ISSUE TITLE
mutt does not start

### ISSUE THREAD

**Issue by xaozai** [SynoCommunity/spksrc#3342]
### Setup
_Package Name:_ mutt
_Package Version:_ 1.5.24 (2015-08-30)

_NAS Model:_ DS213air
_NAS Architecture:_ MARVELL Kirkwood 88F6282
_DSM version:_ 6.1.7-15284

### Expected behavior
Starting mutt

### Actual behavior
Get this message:
/usr/local/bin/mutt: line 3:  8126 Aborted                 LC_ALL=en_US.UTF8 /usr/local/mutt/bin/mutt "$@"

### Steps to reproduce
_1._ $ mutt -F $HOME/mutt/.my@gmail.com.rc

### Conf
set sendmail="/usr/bin/ssmtp"
set realname="xaozai"
set from="my_email@gmail.com"
set use_from=yes
set envelope_from="yes"
set record="=Sent"
set postponed="=Drafts"
set imap_user="my_email@gmail.com"
set imap_pass="my_pass"
set folder="imaps://imap.gmail.com:993"
set spoolfile="+INBOX"
set ssl_force_tls=yes
bind index G imap-fetch-mail
set editor="vi"
set charset="utf-8"

**Comment by ymartin59** [comment]
I guess you should avoid '@' in your configuration file name ".my@gmail.com.rc"... Choose an alternative name for your configuration file.

**Comment by xaozai** [comment]
Unfortunately, a simple filename doesn't work either. I tried this: mutt -F my.rc
The error is the same: 
/usr/local/bin/mutt: line 3:  7841 Aborted                 LC_ALL=en_US.UTF8 /usr/local/mutt/bin/mutt "$@"

**Comment by xaozai** [comment]
GNU bash, version 4.3.48(1)-release (armle-unknown-linux-gnu)

**Comment by ymartin59** [comment]
I cannot reproduce... What about `bash -x /usr/local/bin/mutt -F my.rc` ?

**Comment by xaozai** [comment]
`bash -x /usr/local/bin/mutt -F my.rc`
the output is:
+ LC_ALL=en_US.UTF8
+ /usr/local/mutt/bin/mutt -F my.rc
/usr/local/bin/mutt: line 3:  7072 Aborted                 LC_ALL=en_US.UTF8 /usr/local/mutt/bin/mutt "$@"

I use the same configuration file in my Ubuntu and there mutt starts normally...

**Comment by ymartin59** [comment]
Does mutt start properly without configuration?
Please report output of `/usr/local/mutt/bin/mutt -v`
If failing, please install diagnostic tools: https://github.com/SynoCommunity/spksrc/wiki/FAQ-synogear
```
sudo synogear install
strace /usr/local/mutt/bin/mutt -v 2> strace-mutt.log
```
And please upload strace-mutt.log file as comment attachment here.

**Comment by xaozai** [comment]
Hello, ymartin59!

Yes, without specifying a configuration file, mutt starts up properly and shows the letters in my mail directory (I have Synology Mail Server installed).

But beyond that, I'd like to use mutt with other email servers, particularly GMail.

By using synogear, I got two log files:
[strace-mutt.log](https://github.com/SynoCommunity/spksrc/files/2120332/strace-mutt.log) is the output of the command: strace /usr/local/mutt/bin/mutt -v 2> strace-mutt.log
[strace2-mutt.log](https://github.com/SynoCommunity/spksrc/files/2120334/strace2-mutt.log) is the output of the command: strace /usr/local/mutt/bin/mutt -F my.rc 2> strace2-mutt.log

And [mutt-v.log](https://github.com/SynoCommunity/spksrc/files/2120335/mutt-v.log)  is the output of the command: /usr/local/mutt/bin/mutt -v> mutt-v.log

I will be grateful for your help.

**Comment by BenjV** [comment]
It is not clear how you create the config file but remember that (strangely) the terminal input on a Synology does not support UTF-8.
It seems from the error message that you have created a non utf-8 config file.
Please use an editor like Notepad++ to create config files and make sure to same it as an utf-8 file.

**Comment by xaozai** [comment]
**BenjV,** usually I use vi editor to create and edit text files. vi correctly creates files in UTF-8.
But I tried to create files in notepadqq - mutt still won't start (tried UTF-8, UTF-8 w/o bom).

![my_rc](https://user-images.githubusercontent.com/8542452/41776096-138352aa-762f-11e8-9cfd-4aabaca8b30c.png)

**Comment by ymartin59** [comment]
By the way I do not expect `mutt` to crash silently if its configuration file is malformed... that is really strange

**Comment by ymartin59** [comment]
@xaozai I just wonder if your DSM system lacks "en_US.utf-8" locale. Please report output of `locale` command with your account and as root after `sudo -s` from an administrative account.

**Comment by ymartin59** [comment]
@xaozai Please also check supported locale on your system with `locale -a`

**Comment by xaozai** [comment]
**@ymartin59**, locale under ordinary user and under root are the same:
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8

locale -a are also the same:
C
cs_CZ.utf8
da_DK.utf8
de_DE.utf8
en_US.utf8
es_ES.utf8
fr_FR.utf8
hu_HU.utf8
it_IT.utf8
ja_JP.utf8
ko_KR.utf8
nb_NO.utf8
nl_NL.utf8
pl_PL.utf8
POSIX
pt_BR.utf8
pt_PT.utf8
ru_RU.utf8
sv_SE.utf8
tr_TR.utf8
zh_CN.utf8
zh_TW.utf8

With root privileges, mutt also does not start. The error is the same...

**Comment by xaozai** [comment]
Here is my [mutt.core.zip](https://github.com/SynoCommunity/spksrc/files/2196806/mutt.core.zip)

**Comment by leotzian** [comment]
Hi I had installed mutt on my synology DS416Play with the latest DSM 6.2
I had installed mutt from the synocommunity repo, through synology package center, it is installed correctly, but when I press " run" button after 10 sec it stops and the button is still in run option 
Thanks in advance
