### ISSUE TITLE
Couchpotato doesn't start (and shows no error)

### ISSUE THREAD

**Issue by pamporo** [SynoCommunity/spksrc#3344]
### Setup
_Package Name:_ Couchpotato 
_Package Version:_ 20181305-5

_NAS Model:_ Synology 918+
_NAS Architecture:_ Apollolake
_DSM version:_ 6.1.7-15284

### Behavior
After upgrading Couchpotato to version 20181305-5, the package won't run. It shows no error neither, after I click "Run", it loads for a few seconds but then keeps showing the status as "Stopped".

#### Package log
Wed Jun 13 20:09:38 CEST 2018
Starting couchpotatoserver-custom command /volume1/@appstore/couchpotatoserver-custom/env/bin/python /volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/CouchPotato.py --daemon --pid_file /volume1/@appstore/couchpotatoserver-custom/var/couchpotatoserver-custom.pid --config_file /volume1/@appstore/couchpotatoserver-custom/var/settings.conf

**Comment by ymartin59** [comment]
Online version is 20180513-7. Please update first: https://synocommunity.com/package/couchpotatoserver

**Comment by mreid-tt** [comment]
@pamporo... checking on some older issues... is this still an ongoing concern or can this ticket be closed?

**Comment by pamporo** [comment]
@mreid-tt I have moved to docker a while ago and haven't encountered any issue afterwards. Thanks for following up!
