### ISSUE TITLE
Deluge for 218play

### ISSUE THREAD

**Issue by BoKKeR** [SynoCommunity/spksrc#3347]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Deluge
_Package Version:_ Any

_NAS Model:_ DS218play
_NAS Architecture:_ Realtek RTD1296 64-bit
_DSM version:_ 6.1.3-15152

Deluge is missing. Is this because of a missing toolchain or the package needs to be manually built?

**Comment by ymartin59** [comment]
Deluge 1.3.15 is available for rtd1296: https://synocommunity.com/package/deluge
You should find also "nano" for instance... if none is visible, I can only tell you to check your repository configuration: https://synocommunity.com/

**Comment by BoKKeR** [comment]
I do have nano but not deluge

**Comment by ymartin59** [comment]
That is really weird. I remember a previous similar issue. As far as I remember, user enforces "Refresh" in Package Center and gets its willing package pop up. Let's try this... or maybe wait for a DSM restart at updates...

**Comment by BoKKeR** [comment]
finally managed to fix it. Its a new machine and I needed to activate the Beta packages. After that Deluge appeared with many other missing packages. Thanks for the help
