### ISSUE TITLE
[Info] CircleCI

### ISSUE THREAD

**Issue by publicarray** [SynoCommunity/spksrc#3349]
TL:DR I moved to CircleCI for build and deployment. Example: [.circleci/config.yml](https://github.com/publicarray/spksrc/blob/master/.circleci/config.yml)
 
For fellow developers I've migrated from travis to circleci.  My main reason was the builds on travis would randomly fail due to networking issues or similar. For example when travis was unable to pull the docker image. Also the build times can still be a bit long at times. CircelCi takes about 15-20 minutes for dnscrypt-proxy: https://circleci.com/gh/publicarray/workflows/spksrc

**Comment by ymartin59** [comment]
Thanks for feedback. Just notice restriction for free opensource projects: "1500 monthly build minutes"

**Comment by publicarray** [comment]
Ah yes that slipped my mind. If a build takes 50 "build minutes" you can do 1 a day for 30 days. So not bad. I don't think many package developers will hit that limit. I'm not sure but I think this limit might be per account not per repository. Just something to keep in mind.

**Comment by ymartin59** [comment]
We will see. I grab your configuration from your fork... I am interested to know if it is possible to implement my idea to detect modified spk/* packages from commits added by a PR.

**Comment by ymartin59** [comment]
Related to #2990

**Comment by publicarray** [comment]
Since we switched to GitHub Actions, and it can 
> detect modified spk/* packages from commits added by a PR 

This can be closed.
