### ISSUE TITLE
[DNSCrypt proxy] dnscrypt-proxy_alpine-6.1_2.0.15-0.spk fails to install with package center

### ISSUE THREAD

**Issue by WesternRollers** [SynoCommunity/spksrc#3357]
### Setup
_Package Name:_
DNSCrypt proxy
_Package Version:_
dnscrypt-proxy_alpine-6.1_2.0.15-0.spk

_NAS Model:_
ds416

_NAS Architecture:_
ANNAPURNALABS Alpine AL212

_DSM version:_
DSM 6.1.7-15284

### Expected behavior

Attempting to manually install dnscrypt-proxy_alpine-6.1_2.0.15-0.spk in the package center.

### Actual behavior

'failed to install "DNSCryopt-proxy".' 
After clicking apply at the end of the wizard.

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
package not here  yet

```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
2018/06/24 23:59:31 uninstall dnscrypt: begin to stop version 1.9.5-1
2018/06/24 23:59:32 uninstall Begin start-stop-status stop
2018/06/24 23:59:32 uninstall dnscrypt 1.9.5-1 End start-stop-status stop ret=[0]
2018/06/24 23:59:32 uninstall dnscrypt 1.9.5-1 Begin unload apparmor
2018/06/24 23:59:32 uninstall dnscrypt 1.9.5-1 End unload apparmor ret=[0]
2018/06/24 23:59:32 uninstall dnscrypt: stop version 1.9.5-1 successfully, result 0
2018/06/24 23:59:32 uninstall dnscrypt 1.9.5-1 Begin preuninst
2018/06/24 23:59:32 uninstall dnscrypt 1.9.5-1 End preuninst ret=[0]
2018/06/24 23:59:32 uninstall dnscrypt 1.9.5-1 Begin /bin/rm -rf /volume1/@appstore/dnscrypt
2018/06/24 23:59:32 uninstall dnscrypt 1.9.5-1 End /bin/rm -rf /volume1/@appstore/dnscrypt ret=[0]
2018/06/24 23:59:32 uninstall dnscrypt 1.9.5-1 Begin postuninst
2018/06/24 23:59:32 uninstall dnscrypt 1.9.5-1 End postuninst ret=[0]
2018/06/24 23:59:32 uninstall dnscrypt: Uninstall 1.9.5-1 successfully

/// should be here, no log entry here attempting attempting to install package spk

```

**Comment by WesternRollers** [comment]
Trying using terminal maybe more helpful:

```
sudo synopkg install /volume1/homes/admin/dnscrypt-proxy_alpine-6.1_2.0.15-0.spk
synopkg: json_value.cpp:1470: const Json::Value& Json::Value::operator[](const char*) const: Assertion `type_ == nullValue || type_ == objectValue' failed.
Aborted

```

**Comment by ymartin59** [comment]
May you please point where you downloaded this package? As far as I know, it is not yet officially published in repository.

**Comment by WesternRollers** [comment]
@ymartin59 https://github.com/publicarray/spksrc/releases
From the wiki page.
Oh i see, i may have posted in the wrong area.
Should i move or delete these posts? I'm not sure of the process.

**Comment by publicarray** [comment]
Hi @WesternRollers,

I've just pushed a fix to fix the invalid json in https://github.com/publicarray/spksrc/commit/814a602daf9156d7842ea187dcce2dd0f942b609, hopefully this will fix this. Would you mind trying the newer build?

You are probably the first to run the package on a NAS. Unfortunately I don't have a NAS I only have the RT2600ac router. So there could be some slight differences and probably is why I didn't catch this one earlier. Thanks for reporting 👍

**Comment by publicarray** [comment]
@WesternRollers

> I have a couple other issues, see you on publicarray/spksrc

Still waiting :) or did you sort everything out?
