### ISSUE TITLE
midnight commander package does not install mcedit executable in path

### ISSUE THREAD

**Issue by ssbarnea** [SynoCommunity/spksrc#3361]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Midnight Commander
_Package Version:_ 4.8.20-4

### Expected behavior
mcedit should be in path, currently only "mc" is added to /usr/local/bin/mc as a symlink to 

    /usr/local/bin/mc -> /volume1/@appstore/mc/bin/mc-utf8

It would be needed to symlink all executables: mcedit, mcdiff, mcview in addition to mc.

**Comment by Safihre** [comment]
Maybe you can create a PR? 👍
I could try but maybe I forget some tool.
