### ISSUE TITLE
TVHeadend for DS418/RTD1296

### ISSUE THREAD

**Issue by TonVH** [SynoCommunity/spksrc#3362]
Where can I find a .SPK for this? It is not in packages.synocommunity.com and all other references I found lead to dead pages.

**Comment by m4tt075** [comment]
According to
https://synocommunity.com/package/tvheadend
the `rtd1296` version should be available.
Are beta packages enabled on your DSM?
If yes, which firmware version do you use?

**Comment by TonVH** [comment]
Really weird.  TVH pops up when is turn Beta on.
