### ISSUE TITLE
Syncthing missing

### ISSUE THREAD

**Issue by CUCO-Ultimate** [SynoCommunity/spksrc#3366]
### Setup
_Package Name:_ Syncthing
_Package Version:_ Latest

_NAS Model:_ DS3617xs Xpenology
_NAS Architecture:_ x64
_DSM version:_ 6.1.7-15284

### Expected behavior
Package should be there

### Actual behavior
package is not there

### Steps to reproduce
Install package feed as ususal
Show all community packages
Syncthing is not there

**Comment by Safihre** [comment]
It's a work in progress. Test package in #3138. 
Kind of stuck on it for a long while..
