### ISSUE TITLE
DSM 6.2 reports System Event "Malware detected on DiskStation"

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3367]
Security Advisor reports "old" SynoCommunity package service accounts created by `busybox` as Critical alert: "One or more abnormal users have been found in the authentication file" 
![selection_024](https://user-images.githubusercontent.com/2196184/42121736-b2fd21c0-7c34-11e8-83d2-dbe6096e1649.png)

ToDo: document such account removal in wiki

**Comment by BenjV** [comment]
That's wat I was pointing out when we started to develop the new framework and I advised to get rid of busybox.
If you create users without the Synology tools like "synouser" then DSM has no knowledge of them and like I predicted it will react on that.
For now it is just a security alert, but maybe in the future the just remove those "illegal" users.

**Comment by Teryon** [comment]
Is it the only problem with DSM 6.2 so far ?

**Comment by ymartin59** [comment]
The only one I am aware of as far as packages have been upgraded and published for DSM 6.x - but there are still many of them left to process...

**Comment by Teryon** [comment]
I've just updated to 6.2 nothing reported by security advisor, but I have restore from scratch with all new package, and not the ones mentioned on your screenshot.

**Comment by BenjV** [comment]
Of course not.
That only happens when old packages are still installed.
The old packages created the users with busybox and the new ones with the synology tools.
Users created with busybox are seen as unknown users by DSM 6.2
