### ISSUE TITLE
duplicity fails with "FatalBackendException: Bucket cannot be created" when backing up to B2, which is fixed in 0.7.17

### ISSUE THREAD

**Issue by afunix** [SynoCommunity/spksrc#3368]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ duplicity
_Package Version:_ 0.7.11

_NAS Model:_ DS916+
_NAS Architecture:_ x86
_DSM version:_ 6.2

### Expected behavior
Backup to B2 should be successful if B2 bucket exists.

### Actual behavior
duplicity fails with "FatalBackendException: Bucket cannot be created"

### Steps to reproduce
_1._ Create B2 bucket
_2._ backup for the first time
_3._ try to backup again

#### Other logs
```
Authtoken expired, will reauthenticate with next attempt
FatalBackendException: Bucket cannot be created
```

This issue is reported to be fixed with duplicity >= 0.7.17

**Comment by hgy59** [comment]
fixed as v0.7.19-6 is available in the synocommunity package repo.
