### ISSUE TITLE
ruTorrent problems

### ISSUE THREAD

**Issue by Saidou83** [SynoCommunity/spksrc#3370]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ruTorrent
_Package Version:_3.7-8

_NAS Model:_DS412+
_NAS Architecture:_cedarview (x64)
_DSM version:_6.1.7-15284

### Expected behavior
No errors with settings and access to folders

### Actual behavior
I'm getting several errors in the ruTorrent GUI

![image](https://user-images.githubusercontent.com/3101877/42324369-520318b0-8063-11e8-801c-2e314c63186a.png)

1. Permissions problems
2. Plugin crash
3. Can't navigate through tabs on bottom screen in Chrome. (works on IE, Edge, Safari)

Also where can I find the config files?
In the [Wiki](https://wiki.archlinux.org/index.php/RTorrent#Port_configuration) it says:
> Before running rTorrent, copy the example configuration file /usr/share/doc/rtorrent/rtorrent.rc to ~/.rtorrent.rc, and check out the related rTorrent wiki page that has a modern basic configuration file.

I'd like to provide logs, but there aren't just any...

#### Package log

_--> Log file is empty:_

> root@J-JsDS412:/usr/local/rutorrent/var# ls -l
>    _total 4
>    -rwxrwxrwx 1 rutorrent root 0 Jul  5 14:36 rtorrent.log
>    -rwxrwxrwx 1 root      root 6 Jul  4 00:35 rtorrent.pid_

> root@J-JsDS412:/usr/local/rutorrent/var# du -h /usr/local/rutorrent/var/rtorrent.log
>    _**0**       /usr/local/rutorrent/var/rtorrent.log_

Thanks,

J-J

**Comment by th0ma7** [comment]
New and update to `rutorrent` version 3.10 uploaded on https://synocommunity.com/package/rutorrent
