### ISSUE TITLE
Home Assistant availability DSM 6

### ISSUE THREAD

**Issue by hubudavs** [SynoCommunity/spksrc#3373]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Home Assistant
_Package Version:_20150526-1

_NAS Model:_DS213J
_NAS Architecture:_Armada370
_DSM version:_6.2-23739

### Expected behavior
I could install, but I'm not able to start it. 

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
Please refer to #3115

**Comment by ymartin59** [comment]
To anyone interested in Home Assistant, what are components you are interested ? Please comment in #3115
