### ISSUE TITLE
ZSH for x86_64 architecture

### ISSUE THREAD

**Issue by cdalvaro** [SynoCommunity/spksrc#3374]
I'm trying to install ZSH on my DS918+ with an Intel Celeron processor but I cannot see the package listed in the Package Center. (I have activated the support for beta packages too).

Is there any plans to add x86_64 support for this package?

Thank you in advance!

**Comment by ymartin59** [comment]
Correct. ZSH has not been published for `apollolake` architecture. Sounds relevant to fix with a package update.

**Comment by ymartin59** [comment]
I have just published updates. Should be OK for you.

**Comment by cdalvaro** [comment]
Thank you very much for your efficiency!
