### ISSUE TITLE
Can't find git for DSM 4.2

### ISSUE THREAD

**Issue by SinneDsOnline** [SynoCommunity/spksrc#3375]
Hi i'm running DSM 4.2 on my DS509+. This is the latest version available. After a lot of searching the internet I can't find a good git package for my synology.

Tried installing git with ipkg but I got still issues with installing sickbeard and couchpotato.

**Comment by ymartin59** [comment]
Sorry but we no longer support DSM < 5 here and so git has not been published for your device.

**Comment by ymartin59** [comment]
Please check your DSM version... I do not expect it is 4.2. It should be upgradable to 5.2, which is recommended.

**Comment by ymartin59** [comment]
Have you registered SynoCommunity package source in your DSM Package Center? If not, just do and you may get Git.
If it is not satisfying, you may get package for `ppc853x` from https://synocommunity.com/package/git

**Comment by SinneDsOnline** [comment]
Unfortunately it's not possible to upgrade to DSM version 5.2. The ds509+ is to old. I did register to the synocummonity source.

https://www.synology.com/en-global/support/download/DS509+#utilities

I was hoping someone would have a git package for DSM 4.2.

Thanks for the respond!

**Comment by hgy59** [comment]
@SinneDsOnline are you looking for `git` or `git-server` package?
For `git` it would be easy to manage repositories on diskstation shared folders with another system (even Windows).
Maybe you want to host a `git-server` on the diskstaion?
I tried both, but had some issues with `git` and for `git-server` mktemp.org for dependent source code was not reachable.

Maybe it would be worth to create branches for older diskstations that can not be updated to DSM 5.2.

Latest DSM Versions as of July 2018:
- 4.2-3259 for the x09 Series
- 3.2-1983 for USB Station 2
- 3.1-1639 for the x07 Series
- 2.0-0731 for the x06 Series _(don't know whether spk installation is supported)_

If we have such branches, it would be possible to adjust the build for specific packages on branches only.
Does anybody know how to find which packages ever worked on which archs on DSM versions before 5.2?

**Comment by SinneDsOnline** [comment]
Thanks for the git package ! This one is working perfectly on my ds509+.

**Comment by hgy59** [comment]
no need for branches for older DSM versions since toolchain 4.0 is based on DSM 3.1 firmware.
Built git and some other packages for arch-powerpc-4.0 on the master branch and successfully installed and run on my old DS-107e with DSM 3.1.
Only manual installation is supported on DSM 3.1 so no need to add old packages to any repository.
About 50% of the packages failed due not supported arch or too old toolchain (compiler).
To build git I had to modify the makefile for cross/openssl. Used the original OPENSSL_ARCH linux-ppc instead of synology-ppc of the patched Configuration.
Maybe it is worth to validate whether the patches in openssl are still needed, but this is another topic.

Thanks for all the information here.

**Comment by bittner** [comment]
(I know this is not exactly the same topic, but I want to avoid to open a separate issue ...)

I've activated the SynoCommunity sources as [described on the website](https://synocommunity.com/), and installed the [Git package](https://synocommunity.com/package/git) via the DSM GUI. The user interface said "installing" for a while, and later the Git package showed up in the "Installed packages".

However, `git` is not available on the command line when I log in with SSH. And idea what's going on? Did I do something wrong?

**Comment by hgy59** [comment]
I have a DS-918+ too.
Installed git and the installation is successful, but there is not link created in the `/usr/local/bin` directory to run from commanline.
you can manually test the git command with:
`/volume1/@appstore/git/bin/git --version`

create the missing link with:
`sudo ln -s /volume1/@appstore/git/bin/git /usr/local/bin/git`

same on my DS-210+ (DSM Version 5.2)
had to login with root to create the link (sudo not available)

may be there is an error in the git installation scripts...

**Comment by bittner** [comment]
> may be there is an error in the git installation scripts...

Can we try to fix that? Where is the related source code?

**Comment by bittner** [comment]
If figured out the Git 2.15.1-11 Git community package installs `git` as `/usr/local/bin/git`, which is fine, but non-root users don't seem to have that in their `PATH`.
```console
$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin
```
In other words, the _actual_ problem is that the user's `PATH` variable is not initialized nicely. You can fix this in a simple way: By adding a `~/.bashrc` file to the home directory of your login user.
```bash
export PATH="$PATH:/usr/local/bin"
```
