### ISSUE TITLE
Python 3 upgrade

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3379]
This issue tracks activity around Python 3 package upgrade to 3.7.0
Required for Home Assistant #3115

**Comment by chickenandpork** [comment]
Cutting a PR for 3.5.5 update; I was going to move to 3.7.0 thereafter

**Comment by codexown** [comment]
If possible, add cross compiled lxml lib for python3.5. Is missing in python3 package but included in python2
