### ISSUE TITLE
Deluge randomly stopping and unable to run again without resetting the NAS (pid error in start-stop)

### ISSUE THREAD

**Issue by djhifi** [SynoCommunity/spksrc#3381]
My Deluge randomly stops and I can only run it again by restarting my Synology (DS 1813+). It throws pid already running in some logs (see attachments in the end of this post) but thats not all.

Running versions :

- DSM 6.2-23739 Update 1

- Python 2.7.14-19

- Deluge 1.3.15-9

I've seen that back in January a Python update broke start-stop-daemon and @Safihre closed such issue (#3108) in Feb, 26 and pointed to this page. Has the fix been pushed into Synocommunity repo or the correct procedure would be to remove everything and reinstall?

Excerpt from "synopkg.log" (before restarting the nas and after clicking "run" in the package center):

2018/07/12 01:42:34 **start deluge: begin to stop version 1.3.15-9**
2018/07/12 01:42:35 **start deluge 1.3.15-9 Begin start-stop-status stop**
**start-stop-daemon: warning: killing process 2694: No such process
start-stop-daemon: warning: killing process 2670: No such process
deluge is not running**
2018/07/12 01:42:35 **start deluge 1.3.15-9 End start-stop-status stop ret=[0]**
2018/07/12 01:42:35 **start deluge 1.3.15-9 Begin unload apparmor**
2018/07/12 01:42:35 **start deluge 1.3.15-9 End unload apparmor ret=[0]**
2018/07/12 01:42:35 **start deluge: stop version 1.3.15-9 successfully, result 0**
2018/07/12 01:42:35 **start deluge: begin to start version 1.3.15-9**
2018/07/12 01:42:35 **start deluge 1.3.15-9 Begin pre-load apparmor**
2018/07/12 01:42:35 **start deluge 1.3.15-9 End pre-load apparmor ret=[0]**
2018/07/12 01:42:35 **start deluge 1.3.15-9 Begin start-stop-status start**

After restarting the Synology, Deluge starts but some "unhandled exceptions" are traced in the 

synopkg.log like this one:

**Unhandled Error
Traceback (most recent call last):
File "/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-1.3.15-py2.7.egg/deluge/main.py", line 241, in start_daemon
Daemon(options, args)**

Full log here:

[synopkg.log](https://github.com/SynoCommunity/spksrc/files/2195349/synopkg.log)

----
Other logs attached (these logs below are BEFORE restarting the NAS):

[deluge.log](https://github.com/SynoCommunity/spksrc/files/2195345/deluge.log)
[deluged.log](https://github.com/SynoCommunity/spksrc/files/2195346/deluged.log)
[deluge-web.log](https://github.com/SynoCommunity/spksrc/files/2195347/deluge-web.log)

```

**Comment by djhifi** [comment]
I've already posted this issue on #3138 (see end of thread) but per recommendation I opened as a single issue.

I have also re-done the steps @BenjV recommended on that same thread and cannot find the pid file even when I manually stop my Deluge. I will have to wait for it to randomly stop again and check if the .pid's are left behind.

@BenjV suggested the following:


> @Safihre @ymartin59

I am not a deluge user but I dived into this issue and it seems that deluge also creates a process that writes its pid into a pidfile called deluged.pid.
It would be wise to add killing this process and removing this pid to add to the start-stop-status script.
So for this package there should be three pid files handled:
deluge.pid
deluged.pid
deluge-web.pid

**Comment by BenjV** [comment]
I did some extra checking and the pidfile deluged.pid is not your problem.
In start-stop-status uses a deluge API to stop it and then deluged stops itself and cleans up the pid file.

By the way on my test Nas I installed deluge en start stop just works fine.

**Comment by ymartin59** [comment]
@djhifi How do you start service? From Package Center, or from command line?
For command line, here is FAQ about how to use new generic start-stop-daemon: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#how-to-query-package-status-from-command-line

**Comment by djhifi** [comment]
@BenjV My deluge stopped again and I checked the var, I have deluge.pid and deluge-web.pid. No deluged.pid. I deleted both PIDs nevertheless and still cannot run deluge again without restarting the synology :(

@ymartin59 Im starting it from the package center. The problem is this:

When I restart my Synology after deluge randomly stops, I can start and or stop the package freely from the package center. The only issue occurs when deluge randomly stops again. I'm unable to start it from package center and I have to restart my NAS.

Regarding the command line, I've just ran it and I get this:

"/var/packages/deluge/scripts/start-stop-status status
" /var/packages/deluge/scripts/service-setup: line 6: [: : integer expression expected is not running"

At this time I'm even trying to understand why my Deluge package is randomly stopping after a few days online and I cant. This is annoying me. Having to restart the NAS should not be the workaround

[deluge.log](https://github.com/SynoCommunity/spksrc/files/2198885/deluge.log)
[deluged.log](https://github.com/SynoCommunity/spksrc/files/2198886/deluged.log)

**Comment by djhifi** [comment]
EDIT: Ok I've not found anything in the logs but I think my Deluge crashing is happening whenever I access it from outside my LAN (i.e. through the internet)

**Comment by BenjV** [comment]
In that case it is a deluge problem.
You better take it up with the deluge developers.

**Comment by ymartin59** [comment]
About `/var/packages/deluge/scripts/start-stop-status status`, error message comes from lacking variables to be set before invocation. Please refer to
https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#how-to-query-package-status-from-command-line
