### ISSUE TITLE
How to compile a new ZNC module?

### ISSUE THREAD

**Issue by luckman212** [SynoCommunity/spksrc#3385]
I'm not sure how close a 1.7 release is from #2977 and also am not sure if the maintainer of the znc package is still @Diaoul (or if @ymartin59 or @Safihre have taken over?) Basically I was wondering if it's simple enough that I could try to compile my own .spk for my avoton-based DS1515+? Anything special beyond the [Developers-HOW-TO](https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO)?

**Comment by ymartin59** [comment]
Package has to be migrated to new generic installer and service support. I work on it.

**Comment by m4tt075** [comment]
Test builds available in issue #2977. Please test and report back there. I'll be closing this one to avoid duplication...
