### ISSUE TITLE
Jackett missing Armada 38x arch. compile in Repo?

### ISSUE THREAD

**Issue by cerulliulliulli** [SynoCommunity/spksrc#3388]
### Setup
_Package Name:_ Jackett
_Package Version:_ v0.8.490-6

_NAS Model:_ DS216j
_NAS Architecture:_ Armada 385
_DSM version:_ DSM 6.1.7-15284 Update 1

Have seen @Dr-Bean referenced a lot since he seems to have been the one to compile Jackett for the SynoCommunity repo, hopefully he's around to help. I noticed the Jackett package on SynoCommunity was updated for everything but Armada 38x? The package is available for other lesser Armada architectures, but that one is missing. There is a critical failure in the previous versions that was resolved in v0.8.490-6 and was hoping for some insight into why Armada 38x support seems to be missing. Or if someone could compile Jackett v0.8.490-6 for Armada 38x, it would be greatly appreciated.

**Comment by ymartin59** [comment]
A mistake of mine when publishing my first packages in repository. Just published for armada38x.
