### ISSUE TITLE
Support for install_uifile.sh, upgrade_uifile.sh and uninstall_uifile.sh files

### ISSUE THREAD

**Issue by Anonym-tsk** [SynoCommunity/spksrc#3389]
Please add support for these files to spksrc.spk.mk

Documentation: https://developer.synology.com/developer-guide/synology_package/WIZARD_UIFILES.html

install_uifile.sh, upgrade_uifile.sh, uninstall_uifile.sh and *.sh scripts to generate the wizard dynamically are only supported in DSM 5.2 or newer.

**Comment by ymartin59** [comment]
I just guess the question is "where to provide `x_uifile.sh` scripts with `spksrc` framework.
Answer is at the same place than constant `x_uifile` when `WIZARDS_DIR = src/wizard/` is set in spk `Makefile`, so in `src/wizard/`.

I have planned to write some of them for NextCloud to select varia database support between embedded postgresql or mariadb (with resources) or custom mariadb to provide migration path from ownCloud or manual installation.

**Comment by Anonym-tsk** [comment]
@BenjV I created new package and it contains src/wizard/install_uifile.sh. But when i build spk, i did not find the file WIZARD_UIFILES/install_uifile.sh. After patching [this line](https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.spk.mk#L293) build was correct.

**Comment by BenjV** [comment]
It does not help if you give only half the information what's needed to understand your problem.

A lot of packages have uifiles and they are all made with the framework so if it is not working for you, you have to be doing something different.
You said you patched line 293 in the spksrc.spk.mk, but I don't see any difference in the link you gave to the one in the repro.
So what did you changed?

**Comment by Anonym-tsk** [comment]
@BenjV https://github.com/SynoCommunity/spksrc/compare/master...Anonym-tsk:mtproxy#diff-93babb8aca8f10daaac201d6641f6d13

**Comment by ymartin59** [comment]
Sorry I forgot about regular expression used to copy... important point as spkrepo also limits files included in signature thanks to regex. So both has to be extended to scripts so that packages can be published

**Comment by Anonym-tsk** [comment]
@ymartin59 Please do it quickly as possible. I want to publish pull request with new package and i need support for install_uifile.sh
