### ISSUE TITLE
[Update Request] latest Jackett (v0.9.16 at the moment, but updates frequently)

### ISSUE THREAD

**Issue by enchained** [SynoCommunity/spksrc#3394]
There was quite a few critical updates since v0.8.490, and some things don't work there anymore, so it would be nice to get the repo updated too.

**Comment by enchained** [comment]
@kaso17 maybe you could help with this?
I'm not sure if it's as simple as replacing versions in Makefiles and checksums in digests.
Or were there any important dependency changes for Jackett, etc?
I don't even know how could I test it before doing a PR.

**Comment by m4tt075** [comment]
`Jackett` has an internal update function. Go to the web-interface after you have installed it, click on `Update`, wait and you will have the latest version. Repeat at will. No need to change anything here until the package breaks.

**Comment by enchained** [comment]
@m4tt075 Internal update was the first thing I tried, but it never worked, giving a js error about request result. I thought that was one of the bugs.
Right now I tried to reinstall Jackett and the update finally worked, thank you.
