### ISSUE TITLE
Use HTTPS for package repository

### ISSUE THREAD

**Issue by bittner** [SynoCommunity/spksrc#3397]
The setup [instructions on the website](https://synocommunity.com/) state to use `http://packages.synocommunity.com/` as a repository URL. It has been proven that HTTP is vulnerable to man-in-the-middle attacks, hence we should use HTTPS. If this is already possible we should update the instructions and also redirect from HTTP to HTTPS.

**Comment by Diaoul** [comment]
I think it is already possible although the certificate is not up-to-date. Now that there's LetsEncrypt, this is a good free alternative compared to the paid SSL cert I had.

**Comment by Diaoul** [comment]
Also, packages are signed so I don't think there's an actual risk here.

**Comment by stsquad** [comment]
While the packages may be signed there is still and information leak if using http to fetch packages as an attacker can then identify what you might have installed on your NAS. 

FWIW I added the package URL as https://packages.synocommunity.com/ and everything works fine so I think all is needed is the doc update.

**Comment by aodj** [comment]
This really needs to be the default; if the signing key is exposed, then it could potentially snowball access to every NAS that uses SynoCommunity.

**Comment by Diaoul** [comment]
Why would the signing key be exposed? It is securely stored and never transmitted.
