### ISSUE TITLE
Start Gitter chat room

### ISSUE THREAD

**Issue by bittner** [SynoCommunity/spksrc#3398]
It would be helpful to have an easy option for quick questions. Questions that don't necessarily require to open an issue on GitHub, and just general discussions. Gitter has been helpful for me in the past. It has a very low entry level (for both repo owners and users).

Would you be ready to set up a Gitter room for this repository? And add a Gitter badge to the top of the README. This is a matter of minutes.

The URL would be: https://gitter.im/SynoCommunity/spksrc
Organization members can immediately create the room by logging in.

**Comment by ymartin59** [comment]
If you really want answers and increase chance your question is visible, please create a dedicated issue - instead of commenting closed issue or PR.
I have no idea how Gitter works but I fear that "statistically" anyone entering room will find it empty.

**Comment by bittner** [comment]
I knew this reasoning would come. (I don't worry about my own questions.)

Let's create the Gitter chart room and see how it performs. If it doesn't we can simply delete it again. Easy.

I assure you it will be a good experience, though.

**Comment by BenjV** [comment]
chatboxes are hardly ever used for good communication.
And this community is about creating and delivering Synology packages, nothing more and nothing less.

You can see that this issue is starting into a chatbox conversation which no result at all.

**Comment by ymartin59** [comment]
I agree with @BenjV probably because I passed over 4 decades... chat is not efficient - users write first before thinking about content.
Issues and PR are from my point of view best ways to interact asynchronously in team and content persists for anyone interested.
