### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by mparents2007** [SynoCommunity/spksrc#3401]
Is anyone please able to help with getting Home Assistant running on my Synology?

### Setup
Package: Home Automation
Ver: 20150526-1

DS415+
INTEL ATOM C2538
6.2-23739 Update 2

### Expected behavior
Package to run 

### Actual behavior
package attempts to run and then fails, no notification or errors that I have noticed

### Steps to reproduce
Setup NAS with above version of DSM
Install Home Assistant
Attempt to run

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
Only one file in this locaiton homeassistant.pid
```
29422
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
2018/07/26 17:26:21	start homeassistant: begin to stop version 20150526-1
2018/07/26 17:26:21	start homeassistant 20150526-1 Begin start-stop-status stop
Home Assistant is not running
2018/07/26 17:26:21	start homeassistant 20150526-1 End start-stop-status stop ret=[0]
2018/07/26 17:26:21	start homeassistant 20150526-1 Begin unload apparmor
2018/07/26 17:26:21	start homeassistant 20150526-1 End unload apparmor ret=[0]
2018/07/26 17:26:21	start homeassistant: stop version 20150526-1 successfully, result 0
2018/07/26 17:26:21	start homeassistant: begin to start version 20150526-1
2018/07/26 17:26:22	start homeassistant 20150526-1 Begin pre-load apparmor
2018/07/26 17:26:22	start homeassistant 20150526-1 End pre-load apparmor ret=[0]
2018/07/26 17:26:22	start homeassistant 20150526-1 Begin start-stop-status start
Starting Home Assistant ...
2018/07/26 17:26:22	start homeassistant 20150526-1 End start-stop-status start ret=[0]
2018/07/26 17:26:22	start homeassistant: start version 20150526-1 successfully, result 0
[synopkg.log](https://github.com/SynoCommunity/spksrc/files/2232803/synopkg.log)


```

**Comment by ymartin59** [comment]
Duplicates #3115

**Comment by ymartin59** [comment]
To anyone interested in Home Assistant, what are components you are interested ? Please comment in #3115
