### ISSUE TITLE
Cannot install Radarr, Sabnzbd, and Sonarr. Port undefined configured for this package is either used by another service

### ISSUE THREAD

**Issue by JorenRapini** [SynoCommunity/spksrc#3402]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Radarr, Sonarr, and Sabnzbd are all doing the same thing. Mono and Lidarr installed fine
_Package Version:_

_NAS Model:_ DS918+
_NAS Architecture:_ Quad core celeron J3455
_DSM version:_ 6.2-23739 Update 2

### Expected behavior
Should install  :)  

### Actual behavior
Doesn't!

### Steps to reproduce
_1._ Click install
_2._ ??
_3._ No Profit

"Port undefined configured for this package is either used by another service or reserved for system use. Please disable or modify the conflicting service, or contact the developer to modify the package configuration."

Recently formatted volume 1 and am reinstalling packages when I ran into this. Tried disabling the Synology firewall. I currently don't have much installed, and I did try to top most of them but it didn't make a difference. Seems like for some reason these packages don't have their port defined any longer?

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Will post log as soon as I can, for some reason am unable to SSH in from the location I'm at right now
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
Most likely you did not uninstall the packages before removen the volume.
So there are all kinds of leftovers from the previous installs.

Best thing to do is reinstall DSM.

**Comment by ymartin59** [comment]
Strange error message "Port undefined"... generally it refers to a port number, which helps to understand which package is in trouble.
Before reinstalling full system, you may try to uninstall packages and do manual cleanup as root in `/usr/local/etc/services.d`.
Good luck

**Comment by JorenRapini** [comment]
Ok, this makes sense, Lidarr worked which I didn't originally have installed before this volume1 format (was using headphones), but the rest of them I did have installed. Gives me a lead to look into thanks.

**Comment by JorenRapini** [comment]
Thanks @ymartin59 , clearing those entries out of services.d did the trick! Saved me a ton of time.

**Comment by peterclauterbach** [comment]
> Before reinstalling full system, you may try to uninstall packages and do manual cleanup as root in `/usr/local/etc/services.d`.

+1 to @ymartin59 

I had the same symptoms when installing the Domotz network monitoring package.

`Package Center`
`Port 3000 configured for this package is either used by another service or reserved for system use. Please disable or modify the conflicting service, or contact the developer to modify the package configuration.`

This error was caused by an old unused docker image of grafana assigned to port 3000, which I only could find by inspecting `/usr/local/etc/services.d`
Deleting the docker container and image allowed me to install the Domotz package.

**Comment by Eldinnie** [comment]
I have a similar problem.
I used to have Radarr installed. After an update I cannot install with the error: 
```Port undefined configured for this package is either used by another service or reserved for system use. Please disable or modify the conflicting service, or contact the developer to modify the package configuration.```
Looking in services.d I found no entry for radarr or it;s default port. anything else I can do?

**Comment by BenjV** [comment]
Try a reboot of DSM
