### ISSUE TITLE
Install packages from the command line

### ISSUE THREAD

**Issue by bittner** [SynoCommunity/spksrc#3403]
I have a general question about managing packages on a Synology NAS. I own a 918+ running DSM 6.2, currently.

Is there a documented way to install packages from the CLI, e.g. using the `syno*` commands?

If not, where do I find the sources of the DSM Package Center, so that I can trace down which commands the UI is issuing to configure sources and install packages?

Related forum posts
-------------------------

- [Package installation from terminal command line](https://forum.synology.com/enu/viewtopic.php?f=90&t=144513) (Jul 2018)
- [Syno Command Documentation](https://forum.synology.com/enu/viewtopic.php?t=126516) (Jan 2017)
- [Technical Questions on Packages & Packaging](https://forum.synology.com/enu/viewtopic.php?f=115&t=127195) (Jan 2017)

**Comment by BenjV** [comment]
I don't see why you should want to do it, but you can use the synopkg command to install packages from the commandline.

sudo synpkg install <package.spk>

**Comment by BenjV** [comment]
Simple do a wget of the package and install it.
It seems to me that you want things without the basic knowledge needed.

And why should you want to do such things when DSM supplies that functionality and if you want that for other Nasses you could use CMS for that.

**Comment by ymartin59** [comment]
And to get URL of your package of interest, package view provides location for each version/architecture: https://synocommunity.com/packages
DSM system is far for a standard Linux distribution... so you have to do it the way Synology proposes.

**Comment by BenjV** [comment]
As I already mentioned Synology provide CMS for such functionality.
No need to develop it yourself,
See:

https://www.synology.com/en-global/knowledgebase/DSM/help/CMS/cms_desc

**Comment by bittner** [comment]
Thank you for the information about the Synology CMS. IIUC, this requires that you set up at least the NAS running the CMS component manually.

I respect that we have different mindsets. (Note that I'm trying to automate _everything_. In the business I do I cannot afford to do things manually.)

My original question was: Is there documentation on how to do things with CLI commands (instead of the Web UI)? And if not, where can I find the (source code of the) DSM Package Center, i.e. the web application, on my NAS?

**Comment by BenjV** [comment]
It is not documented en the DSM source can be found here.
https://sourceforge.net/projects/dsgpl/

**Comment by bittner** [comment]
@BenjV thanks for the link!

Can you help me find the source code of the Package Center? I don't think it's in there.

If the source code is not included in the SF repo where on the NAS should I look to find it?

**Comment by ymartin59** [comment]
@bittner You probably should have guessed Synology DSM is not open source, neither is Package Center. Synology only publish some components sources to comply with GPL.

**Comment by bittner** [comment]
> Is there a tool that would download the package file for a package name and install the package? (Something like `apt-get install <package>` on Debian.)

To answer my own question, the `synopkg` tool now provides an `install_from_server` command that does the trick. The package sources have to be added via "Package Center" > "Settings" beforehand, though. There doesn't seem to be a way neither to do this nor to get a list of available packages (from remote sources) in the terminal.

```console
$ sudo su -
# cat /usr/syno/etc/packages/feeds
[{"feed":"https://packages.synocommunity.com/","name":"SynoCommunity"}]
# synopkg install_from_server Git
# synopkg uninstall Git
```

I have added some more details to an answer in Synology's [official community forum](https://community.synology.com/enu/forum/1/post/160366?page=1&reply=513790), if you're interested.
