### ISSUE TITLE
Build python 2.7 for ipq806x

### ISSUE THREAD

**Issue by Yfksw65** [SynoCommunity/spksrc#3405]
Sorry we found it on : https://seby.io/download/synology-rt2600ac/python_ipq806x-1.1_2.7.15-18.spk

**Comment by ymartin59** [comment]
@publicarray According to this message, you have built Python 2.7.15. Is it possible for you to submit a PR so that this version upgrade can be published?

**Comment by publicarray** [comment]
Sure will do. Since it was a minor version bump I didn't think it was that useful.

**Comment by publicarray** [comment]
Ah in my version I removed cheetah==2.4.4 and markdown==2.6.11 from requirements.txt as I was unable to build with them.

**Comment by ymartin59** [comment]
Thanks for checking. So we will see later if update is useful.
