### ISSUE TITLE
Implement imagemagick with php on synology nas

### ISSUE THREAD

**Issue by Marthaarman** [SynoCommunity/spksrc#3407]
### Setup
_Package Name:_ ImageMagick
_Package Version:_ 7.0.7-3

_NAS Model:_ DS214+
_NAS Architecture:_
_DSM version:_ DSM 6.1.6-15266

### Expected behavior
Ok apparently the imagemagick is a base for other packages?
This means that when installed an webserver operating on the synology nas using webstation will still not be able to use imagemagick?
Is there a way to link this?

**Comment by ymartin59** [comment]
Synology WebStation already uses ImageMagick even if an old version of it.

SynoCommunity package is a newer version build and provides support for other audio/video encodings.

According to reports, it works well for most encodings but not all: #3209 #3206

**Comment by hgy59** [comment]
@Marthaarman you have to modify your web app to call the magick commands in /var/packages/imagemagick/target/bin for using the package of SynoCommunity.
Or you create symlinks for imagemagick commands in /usr/local/bin and modify the path for your web app to include /usr/local/bin before /bin and /usr/bin.

e.g. for the convert command:
```
sudo ln -s /var/packages/imagemagick/target/bin/convert /usr/local/bin/convert 
```
