### ISSUE TITLE
No Desktop Icon with Synology Package?

### ISSUE THREAD

**Issue by knopserl** [SynoCommunity/spksrc#3408]
No option to create a Desktop-Icon for TVHeadend?
In the past, when I have installed TVHeadend, it appeared in the Synology main menu and from there you can create a desktop icon.
I installed the version 4.2.6-13 from the repsoitory as described and it works but it does not appear in the main menu and I have no option to create a desktop icon.
Any idea why this happens?

**Comment by ymartin59** [comment]
Yes... probably config file has a JSON incorrect syntax...

**Comment by knopserl** [comment]
@ymartin59 Thanks, it's not a tragedy but very inconvinient. So I hope this can be quickly fixed, then I reinstall it and report back.

**Comment by BenjV** [comment]
No the package is fine and the icon is created when you run it.

That icon only appears if it is running and you are 'admin'.
All others have to be granted access rights in the 'privilege portal' from the configuration panel before they get to see the package icon.

**Comment by knopserl** [comment]
yes, I can confirm that. It is a priviledge issue. I have found that info and changed the access rights and now it works.

I'll close the thread now. Thanks everyone!

**Comment by m4tt075** [comment]
@BenjV It seem you have nailed it down, but am just wondering why the priviledge has to be set manually in the first place. The TVH config file looks like this:
```
{
    ".url": {
        "com.synocommunity.packages.tvheadend": {
            "title": "Tvheadend",
            "desc": "Tvheadend Web UI",
            "icon": "images/tvheadend-{0}.png",
            "type": "url",
            "protocol": "http",
            "port": "9981",
            "url": "/",
            "allUsers": true,
            "grantPrivilege": "local"
        }
    }
}
```
Since `allUsers` is set to `true` I actually would expect everything to work from scratch. I checked the documentation and don't understand why it doesn't. Do you?

**Comment by BenjV** [comment]
According to the developers guide this setting will create an icon for all users who have administrators rights (members of the group administrators), just like the admin account.
Normal users have to be granted rights via the privileges wizard in the control panel.

See this text from the developers guide about this key

> This key determines whether or not the menu items can be seen by users when they log in with an admin
> account. If you would like to have all users see the menu items, please set the key value as below:
> "allUsers": true
> The default setting is that only the admin can find the application.

**Comment by m4tt075** [comment]
Yes, I have read that too. But I did set `"allUsers": true` in the config file above as outlined. I'm no native speaker. Maybe I'm just getting it wrong.

**Comment by m4tt075** [comment]
Edit: I think I get it now. Thanks, @BenjV . Gee, what a strange key that is...

**Comment by BenjV** [comment]
I agree it should be called something like allAdminUsers.
Or not exists at all.
In my opinion the default should be all administrators should get the icon and all normal user should be granted the icon via the privileges wizard.

By the way I am Dutch, so also not a native speaker.
