### ISSUE TITLE
It is ok to play DTS tracks in DS Video or VideoStation 2.4.2-1561, but jump to paragraph is invalid.

### ISSUE THREAD

**Issue by kuenming** [SynoCommunity/spksrc#3413]
### Setup
_Package Name:_ffmpeg
_Package Version:_3.4.1-9

_NAS Model:_DS918+
_NAS Architecture:_Intel
_DSM version:_6.2-23739 Update 2

### Expected behavior
Playback of  video with DTS tracks in DS Video or VideoStation work without issue

### Actual behavior
It is ok to play DTS tracks in DS Video or VideoStation 2.4.2-1561, but jump to paragraph is invalid.
Playback of AC3 tracks in DS Video or VideoStation 2.4.2-1561 work without issue
Playback of DTS tracks in DS Video or VideoStation 2.4.1-1554 work without issue
Playback of AC3 tracks in DS Video or VideoStation 2.4.1-1554 work without issue

### Steps to reproduce
_1._Launch DS Video or VideoStation
_2._Select video with DTS audio
_3._Play

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
cat ffmpeg_install.log
Mon Aug  6 15:36:40 CST 2018
===> Step preuninst. USER= GROUP= SHARE_PATH=
Mon Aug  6 15:36:40 CST 2018
===> Step postuninst. USER= GROUP= SHARE_PATH=
Mon Aug  6 15:43:28 CST 2018
===> Step preinst. USER= GROUP= SHARE_PATH=
Mon Aug  6 15:43:31 CST 2018
===> Step postinst. USER= GROUP= SHARE_PATH=
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
sudo tail /var/log/messages
2018-08-07T10:51:37+08:00 NAS synopkgctl: resource_api.cpp:163 Acquire webapi-desc for VideoStation when 0x0002 (done)
2018-08-07T10:51:37+08:00 NAS synopkgctl: resource_api.cpp:163 Acquire webapi-desc for VideoStation when 0x0002 (done)
2018-08-07T10:51:37+08:00 NAS synopkgctl: SYSTEM:       Last message 'resource_api.cpp:163' repeated 1 times, suppressed by syslog-ng on NAS
2018-08-07T10:51:37+08:00 NAS synopkgctl: resource_api.cpp:163 Acquire data-share for VideoStation when 0x0002 (done)
2018-08-07T10:51:37+08:00 NAS synopkgctl: resource_api.cpp:163 Acquire web-config for VideoStation when 0x0002 (done)
2018-08-07T10:51:37+08:00 NAS synopkgctl: resource_api.cpp:163 Acquire csp-rule for VideoStation when 0x0002 (done)
2018-08-07T10:51:38+08:00 NAS synopkgctl: resource_api.cpp:163 Acquire media-index for VideoStation when 0x0002 (done)
2018-08-07T10:51:40+08:00 NAS kernel: [431042.684673] IR keymap rc-it913x-v1 not found
2018-08-07T10:51:58+08:00 NAS synocrtregister: synocrtregister.cpp:162 Register certificate for WebStation/vhost_21e91ed9-11e9-4263-b9ee-8d597b7c3fa7(pkg)
2018-08-07T10:51:58+08:00 NAS synomustache: synomustache.cpp:88 Failed to load /var/packages/Spreadsheet/target/etc/Spreadsheet.mustache [No such file or directory]

sudo tail /var/log/synopkg.log
cat: /var/run/synodtvd.pid: No such file or directory
cat: /var/run/synodtvd.pid: No such file or directory
cat: /var/run/synodtvd.pid: No such file or directory
cat: /var/run/synodtvd.pid: No such file or directory
cat: /var/run/synodtvd.pid: No such file or directory
2018/08/07 10:51:56     upgrade VideoStation 2.4.2-1561 End start-stop-status start ret=[0]
2018/08/07 10:51:57     upgrade VideoStation: start version 2.4.2-1561 successfully, result 0
2018/08/07 10:52:00     upgrade VideoStation from 2.4.1-1554 to 2.4.2-1561 successfully
2018/08/07 10:52:00     upgrade VideoStation 2.4.2-1561 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2018/08/07 10:52:00     upgrade VideoStation 2.4.2-1561 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]

```

**Comment by kuenming** [comment]
Just reflected this problem
FFMPEG version 3.4.1-9 in the video station version 2.4.21-1561, there is a problem jumping to the paragraph

**Comment by BenjV** [comment]
As I said this is the wrong place.
If you have a problem with VideoStation and/or Ds Video contact Synology support about it.

**Comment by m4tt075** [comment]
There have been some reports in #2952 that the Synology `ffmpeg` version is bypassed for DTS codecs for some NAS platforms in certain situations. This does not seem to be consistent though. As such, your problem might(!) be related to the `fffmpeg` version we are currently distributing. We are in the process of updating it. We'll come back with test-builds at some stage. If so, let's see whether that fixes your problems. NO ETA though. Just wanted to let you know that we are looking into your issue now...

**Comment by BenjV** [comment]
Synology has patched a version of ffmpeg to support DTS on DS Video to be able to play DTS content and ships this with DSM.
It does not support VideoStation.

If you replace this ffmpeg version packed with DSM, with the one created by the SynoCommunity then no DTS support is available, because DTS needs to be licensed from Dolby.

To my knowledge Synology created an illegal hack, because they do not pay royalties to Dolby for this hack, but if am wrong and they do pay this fee to Dolby, then it is most likely they only payed for use in DS Video and not for other use.

If you just installed the ffmpeg from the SynoCommunity and left the ffmpeg distributed with DSM alone, then DS Video will still use the one from Synology and not the SynoCommunity version.

So the answer is still, contact Synology for this issue.

**Comment by th0ma7** [comment]
Pull request #3778 might have a working fix for this issue but would require testers to confirm it actually does.

**Comment by th0ma7** [comment]
Is this issue still existing?  Please consider reopening as you see fit but after testing out latest version available (e.g. 4.2.4) and potentially @BenjaminPoncet helper script he provided at:
* https://gist.github.com/BenjaminPoncet/bbef9edc1d0800528813e75c1669e57e
