### ISSUE TITLE
FDupes not available on Apollo Lake

### ISSUE THREAD

**Issue by jvallery** [SynoCommunity/spksrc#3415]
### Setup
_Package Name:_  fdupes (https://synocommunity.com/package/fdupes)
_Package Version:_  1.51-2

_NAS Model:_   Synology 918+
_NAS Architecture:_   Apollo Lake
_DSM version:_  6.2

### Expected behavior
Ability to install fdupes on 918+

### Actual behavior
The fdupes manual install fails due to architecture incompatibility.   Package not available.

### Steps to reproduce
_1._  Review community packages (fdupes not listed)
_2._  Manual install via SPK fails

**Comment by Rhubarb1** [comment]
Looking to install FDupes on DS3617xs compatible system (running Xeon E3-1240v6 Quad Core 8 threads - not the D-1527 Quad Core 8 threads) CPU. The Xeon E3-1240v6 is Kaby Lake achitecture.  The platform is running DSM 6.2.2-24922 Update 4.  
Steps to reproduce:  
1. Review community packages (fdupes not listed)
2. Unable to source SPK for DS3617xs or for Kaby Lake CPU.

**Comment by ymartin59** [comment]
fdupes is a "beta" package, old version 1.51. It is no longer maintained.
You will find "jdupes" in SynoCLI-File package: https://synocommunity.com/package/synocli-file
