### ISSUE TITLE
username and PW of Aria2 from cytec

### ISSUE THREAD

**Issue by yanyingjie007** [SynoCommunity/spksrc#3416]
hello all,

i just installed the Aria 2 from cytec,

and i want to know how to configure it

as i open the webpage <NAS IP:6800>, it prompt username and password to login.

I don't have these such info, could you guys let me know how to configure it or the default username and passwd

thanks in advanced.

**Comment by BenjV** [comment]
This is not a SynoCommunity package so you ask the question at the wrong place.

Besides that, during installation you were ask to supply a username and password.
So use them.

If you didn't paid attention and just did the "windows style" next, next, finish, then the default username/password is used
That would be admin/admin or (depending on your input) both empty.
