### ISSUE TITLE
Tiny Tiny uninstall

### ISSUE THREAD

**Issue by merlin2105** [SynoCommunity/spksrc#3419]
Hello

I would like to uninstall tiny tiny RSS When I try to uninstall it I have to enter the root password for the MariaDB, this password is no longer known to me or what I think what is correct is displayed as false, how can I delete it nue... the MariaDB I can't delete either, since tiny tiny's use

thanks

**Comment by BenjV** [comment]
If you click on MariaDb in the main menu of DSM you get an screen which give you the possibility to change the root password.

**Comment by merlin2105** [comment]
Hi, I've already done everything, password changed and reset, still says tiny tiny the password is wrong

**Comment by hgy59** [comment]
This work with #4923.
you need the mysql root password for uninstall only (not the db password of ttrss).
