### ISSUE TITLE
No ffmpeg for armada38x architecture

### ISSUE THREAD

**Issue by BenjV** [SynoCommunity/spksrc#3422]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: ffmpeg
_Package Version:_

_NAS Model: DS116
_NAS Architecture: armada38x
_DSM version: DSM 6.2

### Expected behavior
ffmpeg package for the armada38x architecture is not available

Please make it available for this architecture.

**Comment by ymartin59** [comment]
A mistake of mine. I think it is worth to work on ffmpeg 4.0.2 upgrade and some related expected fixes
