### ISSUE TITLE
How to set a password for the mosquitto password? Perhaps password should be enabled by default?

### ISSUE THREAD

**Issue by olskar** [SynoCommunity/spksrc#3423]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Mosquitto

How does one set a password for mqtt on synology NAS installed via community package?

Also, perhaps password should be enabled by default?

**Comment by cytec** [comment]
see: http://mosquitto.org/man/mosquitto-conf-5.html
Config file should be located here: `/usr/local/mosquitto/var/`

**Comment by ymartin59** [comment]
Answered by https://github.com/SynoCommunity/spksrc/wiki/FAQ-Mosquitto
Regards
