### ISSUE TITLE
Bzip points to a dead url

### ISSUE THREAD

**Issue by dragon2611** [SynoCommunity/spksrc#3425]
### Setup
PKG_NAME = bzip2
PKG_VERS = 1.0.6

### Expected behavior
should download/compile bzip2

### Actual behavior
fails to download as bzip.org is dead (points to a parking page)

### Steps to reproduce
try and make bzip or any other package the has it as a dependency

**Comment by ymartin59** [comment]
Thanks for report. Fixing it.
