### ISSUE TITLE
DTS read but not 5.1 on Apple TV 4K

### ISSUE THREAD

**Issue by Vinky41** [SynoCommunity/spksrc#3432]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: ffmpeg
_Package Version: 3.4.1-9

_NAS Model: DS415play
_NAS Architecture: evansport
_DSM version: 6.2-23739 Update 2

### Expected behavior
DS Video play the file DTS in 5.1

### Actual behavior
DS Video play the file in 2.0

### Steps to reproduce
_1. Play a video in DTS 5.1 with DS Video on Apple TV 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here

un Aug 26 01:31:35 CEST 2018
===> Step postuninst. USER= GROUP= SHARE_PATH=
Sun Aug 26 01:34:20 CEST 2018
===> Step preupgrade. USER= GROUP= SHARE_PATH=
Sun Aug 26 01:34:21 CEST 2018
===> Step preinst. USER= GROUP= SHARE_PATH=
Sun Aug 26 01:34:22 CEST 2018
===> Step postinst. USER= GROUP= SHARE_PATH=
Sun Aug 26 01:34:22 CEST 2018
===> Step postupgrade. USER= GROUP= SHARE_PATH=
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
DS Video is a Synology package so if there is a problem you have to create a ticket on the Synology website.
This is the SynoCommunity and not Synology.

**Comment by Vinky41** [comment]
Thx for your answer.

I know that it's a synoCommunity, but it's ffmpeg that do the transcodage DTS, not DS Video (it's only the player). I think the bug is in the ffmpeg, no ?

ffmpeg do a 2.0 transcodage when the original file it's an 5.1 channel.

I haven't another player for test, but I don't think that DS Video do this transcodage alone.

**Comment by BenjV** [comment]
ffmpeg from the SynoCommunity is not used by Ds Video.
Transcoding is done by VideoStation and Synology installs it own version of ffmpeg along with Video Station and uses that one.

**Comment by Vinky41** [comment]
Thx for your answer.

Hum... I'm not sur of that. If I uninstall ffmpeg, it's impossible to play a file with DTS audio. After install, DS Video can play the file. So DSVideo use ffmpeg SynoCommunity. 

I don't know if the bug is new or not (I have just bought my Apple TV) and before I played the movie only with stereo player (ipad/iphone/computer).

**Comment by Vinky41** [comment]
obviously I installed Video Station. but I confirm that DS Video (or Video Station) use SynoCommunity ffmpeg when installed.

The behavior of player is different if it's installed or not (see above).

Regards

**Comment by BenjV** [comment]
That's is simply not possible.
How could those Synology packages know where to find the ffmpeg of the SynoCommunity.

VideoStation has its own ffmpeg and can be found here:
/var/packages/VideoStation/target/bin/ffmpeg

**Comment by Vinky41** [comment]
Video station is intalled.

And I confirm the behavior. It's so possible and verify. (check yourself if you want).

Video station use ffmpeg of the SynoCommunity if installed for the DTS audio Files.

I don't know why or how it's work, but it's work like that.

**Comment by BenjV** [comment]
It is simply impossible.
VideoStation has it's own ffmpeg and it is impossible (without hacking) that VideoStation uses another version.

How do you conclude that VideoStation uses the SynoCommunity version?
You cannot remove the ffmpeg version that VideoStation uses without removing VideoStation in total.

**Comment by Vinky41** [comment]
Hi,

and yet, it's that DS Video do.

I do not hack Video Station and I always used it like that (4 years ago). If I uninstall ffmpeg of SynoCommunity, I can not play DTS, if I install, I can. So, DSVideo uses it.

I'm not alone since I saw this information on the web forum 4 years ago.

**Comment by BenjV** [comment]
I am very sorry but to be extra sure I did what you suggested and remove the ffmpeg of the SynoCommunity from my Nas and the VideoStation kept on working perfectly.

The point is most likely that you have a ffmpeg that is not from the SynoCommunity, but an old Chinese hacked version who replaced the standard ffmpeg from VideoStation with the Chinese hacked version.

The normal VideoStation does not support playing DTS video at all, because Synology did not buy the license for DTS to add it to VideoStation.
Also the ffmpeg of the SynoCommunity has no DTS capabilities because of the license issue.
Dolby does not grant licenses to public domain software as you can understand and ffmpeg is public domain software.

And by the way that Chinese hack is totally abandoned by the guy who made a Package for it because of all kind of problems with it as you experienced.

**Comment by drej1** [comment]
Hi @BenjV ,
I must support @Vinky41 here... I just bought my synology nas recently and I also have the problem with DTS transcoding... before installing ffmpeg, movies with dts played via Media Server on my PS4 said not supported audio format and the Video Station didn't event start the movie.
After installing ffmpeg, the Media Server still doesn't work, but the Video Station now plays the movie with working audio...

@BenjV Maybe you have some other ffmpeg installed or copied or whatever on your NAS if your Video station continues to work after uninstalling synocomunity ffmpeg?

**Comment by BenjV** [comment]
I have investigated some more and it seems that the ffmpeg package also replaced some link libraries in a shared library folder.
In the past those libraries where also used by VideoStation, but the newer VideoStation releases only use their own library and not the common one anymore.
There was no success in trying to rename the libraries, VideoStation did not accept them.
So no luck for you.

**Comment by Vinky41** [comment]
Hi @drej1 and @BenjV,

@drej1:  Thx for your help. I'm not crazy :) :) :)

@BenjV: Thx for your investigation. So, now we know that VideoStation use fffmpeg.

The problem can be fixed or not? It's strange that audio 5.1 channels has been transfomed 2.0 channel.

It's a real bug, not ?

**Comment by BenjV** [comment]
No it is a license issue.

The max that can be done is converting DTS to stereo.
And no, ffmpeg is not used just some part of its libraries and that also not anymore.
Synology cut off that possibility, most likely because they don't want a license battle with Dolby who owns the rights for DTS.

**Comment by m4tt075** [comment]
@Vinky41 Your issue is closely related to #2952. You can scroll down to the bottom for some "interim conclusions" on the situation and to track potential future progress. Closing this issue as duplicate for now.
