### ISSUE TITLE
sabnzbd permissions?

### ISSUE THREAD

**Issue by Djangox** [SynoCommunity/spksrc#3433]
### Setup
_Package Name:_sabnzbd
_Package Version:_2.3.4-36

_NAS Model:_DS1815
_NAS Architecture:_X64
_DSM version:_6.2

### Expected behavior
shouldn't files & folders be created as sc-sabnzbd:sc-download?

### Actual behavior
mine are being created as sc-sabnzbd:sabnzbd. Post processing by other apps (couchpotato,mylar,sonarr) are leaving folders behind. in attached screenshot "sc-sabnzbd:sc-download" was accomplished in applying ACL to parent dir and inheriting. new folders & files are always sc-sabnzbd:sabnzbd

![capture](https://user-images.githubusercontent.com/42706448/44623994-4c23f180-a8ae-11e8-9902-ad6f4c6440ae.PNG)

### Steps to reproduce
I tried updating pre-DSM6 install, and then totally removing Sab & any leftover sab users and doing a fresh install.

**Comment by BenjV** [comment]
No,.
Dsm 6 packages are running as an hidden user and that user is not available to the DSM gui.
Permissions must be granted via the groups.

Read this and act on it.
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

And remember existing folders/subfolders and files  have to be given permissions with FileStation to the correct groups.

**Comment by Djangox** [comment]
(This reply began as an epic undertaking, picture Homer's Odyssey. Luckily for all, I have deleted all that drivel and the below survived the cut!)

As a test (while typing up this reply), I manually moved a dir/files into download directory and chown'd to "sc-sabnzbd:users" and couchpotato was able to cleanup. I then tried a few more tests chowning various users/groups, ending with "sc-sabnzbd:sabnzbd". All worked. 

I notice on the other end, it DID change permissions to "sc-couchpotatoserver:couchpotatoserver" on the destination. I then let sabnzbd pull a few downloads and what do you know? All cleanup performed as expected. So go figure...

**Comment by BenjV** [comment]
You should not do it that way.
It is not supported by DSM and only possible from the commandline and with the next DSM release or package release it is possible it will not work anymore.
And at this moment DSM wil begin to complain about it in the security log.

As I said, read the wiki use the groups sc-download and sc-media for granting permissions and don't forget to convert the share to ACL support if you have old shares.
You are messing with the basics of DSM 6 and the security rules.
Synology has rightly made de user which are running the package hidden and removed from the group "users" and you are reversing this which is a very bad idea.
If you put the package user in the group users then every user on the Nas has access to anything that package creates.
That's a big security hole, but maybe you like a synolocker virus to be able to access everything on your Nas.

Leave the package user at peace.
Why is it so difficult to read a wiki and act accordingly just like everybody else who are using these packages?

**Comment by Djangox** [comment]
I guess I should have left my epic (which started off with.. is "please consult this link on permissions" the only answer given? and "does everyone just assume that people that asks questions never read or search prior?") intact because you are seriously misunderstanding. I'm not sure what "you should not do it that way" is referring to.

Some details that I deleted..

1. sc-download group has always been (you can read that as "since at least 2015") read-write at share folder level 
2. a lot of blah blah blah about the various errors from apps (access denied, "sc-download" unknown, etc.)
3. even more blah blah blah about how I read the docs long ago and understood about hidden users, etc.
4. A second DS was used to test fresh installs (no users, no existing app expected dirs, etc.) of sabnzbd to replicate the behavior I was seeing.
5. I spent at least 2 hours as I was typing the post detailing everything I was trying. By the time I got to the end of my reply everything was "magically" working, so I removed all the ramblings that I had done.
6. oh and the biggie.. I removed the rundown on all the degrees,diplomas,certificates, etc in the field of computers,electronics,400meter freestyle swimming that I own to prove I don't know what I'm talking about (grin)

Now... just so you know, to put things in perspective, I NEVER touched the package user as you seem to think. I only changed permissions "chown" on files and folders that I was manually moving in and out of the "downloads" directory that is shared by all synocommunity apps and observing the results.

I do appreciate you taking time to even bother responding. In this instance, my system is just as it was yesterday (no actual changes to packages or users, etc.). Things just decided to work after all the testing with my "content" manipulations. No "process" changes were made. The one thing I hate is how typing on the internet comes off the wrong way sometimes. If I was directly talking to you, your first reply may have been more along the lines of "Oh, ok... try this" or "are you seeing this?" or "hmmm... that doesn't sound right" and not "go speak to Manuel" GRIN.

Thanks again for your time.

**Comment by BenjV** [comment]
I am sorry you feel this way, I just try to help and I can only see what you tried and what not if you write it here,
And I my opinion the wiki states clearly how it has to be done and if you think otherwise please tell us so we can improve things.

The point is that, you tried to give permissions by adding access to the package user e.g. "sc-couchpotatoserver on folders and files.
And that should be done by giving those folders group permisssions.

In the past pre DSM 6 all users were part of the group "users" and so every package had access to all the files created by the user which runs any package.
So every account on the Nas had access to those files.

As of DSM 6 the package users are hidden and no longer part of the group "users".
This was done on purpose by Synology the created more security and the idea behind is that giving permissions should be done by a group, so the package users are made part of that group.

If you are changing the permissions of folder  and files to give the package user access then you defy the architecture.
Meaning that there is a good change that with a next upgrade of DSM or the package things are not working anymore.
But if you can live with that, it's fine by me I just wanted to help.
