### ISSUE TITLE
HE853 on DSM6.2

### ISSUE THREAD

**Issue by pitekkkk** [SynoCommunity/spksrc#3434]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Home Easy HE853
_Package Version:_1.0.0-1

_NAS Model:_Xpenology (DS3615xs)
_NAS Architecture:_baremetal synology
_DSM version:_6.2

### Expected behavior
Be installed, work by ssh

### Actual behavior
after istalling and starting, button will change again on install
by ssh there is no function of HE853

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
piotr@Hell-DS:/usr/local$ ls
bin  etc  lib  libexec  node  packages  share  SynologyApplicationService

???

```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
2018/08/26 07:53:40     start he853: begin to stop version 1.0.0-1
2018/08/26 07:53:40     start he853 1.0.0-1 Begin start-stop-status stop
2018/08/26 07:53:40     start he853 1.0.0-1 End start-stop-status stop ret=[0]
2018/08/26 07:53:40     start he853 1.0.0-1 Begin unload apparmor
2018/08/26 07:53:40     start he853 1.0.0-1 End unload apparmor ret=[0]
2018/08/26 07:53:40     start he853: stop version 1.0.0-1 successfully, result 0
2018/08/26 07:53:40     start he853: begin to start version 1.0.0-1
2018/08/26 07:53:40     start he853 1.0.0-1 Begin pre-load apparmor
2018/08/26 07:53:40     start he853 1.0.0-1 End pre-load apparmor ret=[0]
2018/08/26 07:53:40     start he853 1.0.0-1 Begin start-stop-status start
2018/08/26 07:53:40     start he853 1.0.0-1 End start-stop-status start ret=[0]
2018/08/26 07:53:40     start he853: start version 1.0.0-1 successfully, result 0
2018/08/26 07:53:50     upgrade he853: begin to stop version 1.0.0-1
2018/08/26 07:53:50     upgrade he853 1.0.0-1 Begin start-stop-status stop
2018/08/26 07:53:50     upgrade he853 1.0.0-1 End start-stop-status stop ret=[0]
2018/08/26 07:53:50     upgrade he853 1.0.0-1 Begin unload apparmor
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End unload apparmor ret=[0]
2018/08/26 07:53:51     upgrade he853: stop version 1.0.0-1 successfully, result 0
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin preupgrade
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End preupgrade ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin preuninst
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End preuninst ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin /bin/rm -rf /volume1/@appstore/he853
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End /bin/rm -rf /volume1/@appstore/he853 ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin postuninst
rm: cannot remove '/usr/local/he853/': Is a directory
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End postuninst ret=[0]
2018/08/26 07:53:51     upgrade he853: Uninstall 1.0.0-1 successfully
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin preinst
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End preinst ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/he853
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/he853 ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin /bin/mkdir -p /var/packages/he853
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End /bin/mkdir -p /var/packages/he853 ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/he853/INFO
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/he853/INFO ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin /bin/rm -rf /var/packages/he853/scripts
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End /bin/rm -rf /var/packages/he853/scripts ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/he853/scripts
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/he853/scripts ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin /bin/rm -rf /var/packages/he853/conf
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End /bin/rm -rf /var/packages/he853/conf ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/he853/conf
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/he853/conf ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin postinst
ln: failed to create symbolic link '/usr/local/bin/he853': File exists
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End postinst ret=[0]
2018/08/26 07:53:51     upgrade he853 1.0.0-1 Begin postupgrade
2018/08/26 07:53:51     upgrade he853 1.0.0-1 End postupgrade ret=[0]
2018/08/26 07:53:51     upgrade he853: begin to start version 1.0.0-1
2018/08/26 07:53:52     upgrade he853 1.0.0-1 Begin pre-load apparmor
2018/08/26 07:53:52     upgrade he853 1.0.0-1 End pre-load apparmor ret=[0]
2018/08/26 07:53:52     upgrade he853 1.0.0-1 Begin start-stop-status start
2018/08/26 07:53:52     upgrade he853 1.0.0-1 End start-stop-status start ret=[0]
2018/08/26 07:53:52     upgrade he853: start version 1.0.0-1 successfully, result 0
2018/08/26 07:53:52     upgrade he853 from 1.0.0-1 to 1.0.0-1 successfully
2018/08/26 07:53:52     upgrade he853 1.0.0-1 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2018/08/26 07:53:52     upgrade he853 1.0.0-1 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2018/08/26 07:54:06     upgrade he853: begin to stop version 1.0.0-1
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin start-stop-status stop
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End start-stop-status stop ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin unload apparmor
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End unload apparmor ret=[0]
2018/08/26 07:54:06     upgrade he853: stop version 1.0.0-1 successfully, result 0
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin preupgrade
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End preupgrade ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin preuninst
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End preuninst ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin /bin/rm -rf /volume1/@appstore/he853
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End /bin/rm -rf /volume1/@appstore/he853 ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin postuninst
rm: cannot remove '/usr/local/he853/': Is a directory
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End postuninst ret=[0]
2018/08/26 07:54:06     upgrade he853: Uninstall 1.0.0-1 successfully
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin preinst
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End preinst ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/he853
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/he853 ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin /bin/mkdir -p /var/packages/he853
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End /bin/mkdir -p /var/packages/he853 ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/he853/INFO
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/he853/INFO ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin /bin/rm -rf /var/packages/he853/scripts
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End /bin/rm -rf /var/packages/he853/scripts ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/he853/scripts
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/he853/scripts ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin /bin/rm -rf /var/packages/he853/conf
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End /bin/rm -rf /var/packages/he853/conf ret=[0]
2018/08/26 07:54:06     upgrade he853 1.0.0-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/he853/conf
2018/08/26 07:54:06     upgrade he853 1.0.0-1 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/he853/conf ret=[0]
2018/08/26 07:54:07     upgrade he853 1.0.0-1 Begin postinst
ln: failed to create symbolic link '/usr/local/he853/he853': File exists
ln: failed to create symbolic link '/usr/local/bin/he853': File exists
2018/08/26 07:54:07     upgrade he853 1.0.0-1 End postinst ret=[0]
2018/08/26 07:54:07     upgrade he853 1.0.0-1 Begin postupgrade
2018/08/26 07:54:07     upgrade he853 1.0.0-1 End postupgrade ret=[0]
2018/08/26 07:54:07     upgrade he853: begin to start version 1.0.0-1
2018/08/26 07:54:07     upgrade he853 1.0.0-1 Begin pre-load apparmor
2018/08/26 07:54:07     upgrade he853 1.0.0-1 End pre-load apparmor ret=[0]
2018/08/26 07:54:07     upgrade he853 1.0.0-1 Begin start-stop-status start
2018/08/26 07:54:07     upgrade he853 1.0.0-1 End start-stop-status start ret=[0]
2018/08/26 07:54:07     upgrade he853: start version 1.0.0-1 successfully, result 0
2018/08/26 07:54:07     upgrade he853 from 1.0.0-1 to 1.0.0-1 successfully
2018/08/26 07:54:07     upgrade he853 1.0.0-1 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2018/08/26 07:54:07     upgrade he853 1.0.0-1 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2018/08/26 07:59:54     start he853: begin to stop version 1.0.0-1
2018/08/26 07:59:54     start he853 1.0.0-1 Begin start-stop-status stop
2018/08/26 07:59:54     start he853 1.0.0-1 End start-stop-status stop ret=[0]
2018/08/26 07:59:54     start he853 1.0.0-1 Begin unload apparmor
2018/08/26 07:59:54     start he853 1.0.0-1 End unload apparmor ret=[0]
2018/08/26 07:59:54     start he853: stop version 1.0.0-1 successfully, result 0
2018/08/26 07:59:54     start he853: begin to start version 1.0.0-1
2018/08/26 07:59:55     start he853 1.0.0-1 Begin pre-load apparmor
2018/08/26 07:59:55     start he853 1.0.0-1 End pre-load apparmor ret=[0]
2018/08/26 07:59:55     start he853 1.0.0-1 Begin start-stop-status start
2018/08/26 07:59:55     start he853 1.0.0-1 End start-stop-status start ret=[0]
2018/08/26 07:59:55     start he853: start version 1.0.0-1 successfully, result 0

```
Insert log here
```

I am using he853 on RPi and now I check if it would be possible to move on synology.
I am quite new on synology and maybe it is quite easy to fix, please let me some tips then.
Finally I need this from SSH because I want to use php exec function and use my current www control panel 

I would be grateful for fix this to 6.2 version.
Thanks in advance!

**Comment by BenjV** [comment]
This is a bug in the package, but only a cosmetic problem.
This software can only be installed and not run and the package center should reflect that.
So if you click on "Run" nothing will happen.
Other software could use this package but it does not do anything on its own.

@ymartin59 
Another example of a package return a 3 instead of a 0 in the start-stop-status script.

**Comment by pitekkkk** [comment]
I don't get it, "Other software could use this package but it does not do anything on its own" 
I suppose that button run is pointless without parameters, But it should work from SSH command but it isn't (or I don't know how to do this) and according to the log, as for me it seems that app isn't "registered" so command he853 will not work. I have no idea how to fix .pkg file.

Thanks in advance for tips.

**Comment by pitekkkk** [comment]
Hi,
thanks for help, It is working from your path but not correctly:
./he853 2222 1
./he853: /lib/libstdc++.so.6: no version information available (required by ./he853)
./he853: /lib/libstdc++.so.6: no version information available (required by ./he853)
HE853 USB device (04d9:01357 Holtek Semiconductor, Inc.) not fully accessible
I guess something haven't installed correctly and because of this there is a bug.

I hope it was working before for somebody and because DSM 6.2 it is not working correctly for me.
Is it possible to make it working correctly?

**Comment by BenjV** [comment]
Has nothing to do with DSM 6.2.
It is just a non functioning package.
It only places the binary and nothing else and it needs also some libraries

It is a beta package

**Comment by pitekkkk** [comment]
Update:
I checked as sudo, it works, but with some errors:
piotr@Hell-DS:/var/packages/he853/target/bin$ sudo ./he853 1111 0 A
./he853: /lib/libstdc++.so.6: no version information available (required by ./he853)
./he853: /lib/libstdc++.so.6: no version information available (required by ./he853)
Sending command[0] to deviceId[1111] with protocol AnBan

I don't know what should be in /lib/libstdc++.so.6 - can I fill this manually, or during installation it should be filled?
During making normal installation in main.cpp is required to choose protocol, here I guess not possible, but not big issue. 
So as you wrote before when it starts from /var/packages... you can help me to fix it.
Could you? :D thanks in advance!

**Comment by BenjV** [comment]
It seems no use to be able top start it from the package center
This application has no GUI so starting it from the GUI won't work.

As I said before I don't know wat the purpose of the package is, because it seen to me that it does not do anything at all. 
Maybe you can tell me what it's function is?
Does it keep running like a daemon or is it just a one time run?

If you want to try it, you can change the start-stop-status script
It is located here:
/var/packages/he853/scripts/start-stop-status
After the label start) and before the next exit 0 you insert the following line:
/var/packages/he853/target/bin/he853

It will still show as not running but it will run once.
If it is a daemon and keeps running we can make more changes to the script, so let me know.

**Comment by pitekkkk** [comment]
OK, so maybe step by step: https://github.com/hphde/he853-cli
This is cli software and it isn't deamon, application you run with parameters and dongle on USB is sending signal and close, so running this from package list has no sense - true, but after clicking "run" it changes into "installing" so I guess it catch that app isn't installed correctly - it is not registered to just use this by SSH: 
he853 [port] [on] [protocol] - and then make it possible to run from for example by php exec function. 
In my opinion installing crashes here:
ln: failed to create symbolic link '/usr/local/he853/he853': File exists
ln: failed to create symbolic link '/usr/local/bin/he853': File exists
and because of this it is not installed till the end.
I thought that "/lib/libstdc++.so.6" means that something should appears there during installation, but according to your comment it will not.
I am only not sure what should be linked during instalation to /usr/local... (above)
Anyway, even with this error, it works form "/var/packages/he853/target/bin" so only to do is register new function and Beta will be working correctly

PS. For future there would be good to let choose protocol EU/AnBan/Kaku in main.cpp during instalation or change from E to L for all protocols working

**Comment by BenjV** [comment]
It is not a windows system,.
Nothing gets registered on Linux systems.

The failed to create symbolic link is because the package tries to create a symbolic link to a file on the same location as staht files, that is useless.
Symbolic links are links that looks like a file but are links to the real file.

I have taken a look at the package itself but it is not a functional package at all.
It tries to use:

> /usr/local/

 as the base location but that does not exists if you don't create it.
The package should use:
> /var/packages/${SYNOPKG_PKGNAME}/target/

**Comment by pitekkkk** [comment]
To close topic and give solution for future:
It is enough to by SSH put line:
`sudo ln -s /volume1/@appstore/he853/bin/he853 /usr/local/bin/`
then you can use from SSH:
`sudo he853 2222 1 A`
sudo is required for permission of using USB key
to use this from php exec you have to define in /etc/sudoers additional line:
`http ALL = NOPASSWD: /volume1/@appstore/he853/bin/he853`

**Comment by ymartin59** [comment]
Hello @pitekkkk 
I may adapt package to compile and run as a service on DSM 6... but as I have not such a device, I will request your help for testing...

**Comment by pitekkkk** [comment]
perfect, it will for sure would be helpful for other users
This what I wrote above is one topic (I am not sure if you would be able to change permission to acces usb without sudo, fill libstdc++ to avoid errors in commend line and let to choose protocol in main.cpp or just change this for L=All according to documentation.
I forgot also about one thing:
in `/usr/local/bin/` there was smbolic link which was wrong (it was like combination 2 paths together and it doesn't exists and because of this instalation package couldn't define new symbolic
Anyway, if you test app from SSH without USB tool, application gives feedback like "Holtek device not found" or something similar, so you can check this on your side if installs correctly, if you wan't, I acan confirm working with USB and sudo.
Thanks!

**Comment by BenjV** [comment]
The package center starts packages with root privileges so sudo is not needed but @ymartin59 knows that well enough.

**Comment by pitekkkk** [comment]
yes, you can run app, but without sudo you don't get access to device or it is wrongly working in my case, so... it seems like required.

**Comment by BenjV** [comment]
Of course you have to configure the device from the commandline because nobody made a gui interface to do that.
But my understanding is (correct me if I am wrong) is that you configure it once and then is just has to be run and keeps on running so it can be use by other applications.
Like a driver.
So the package center just has to run it everytime the Nas boots?

**Comment by pitekkkk** [comment]
No, it is not a bot, not a driver, not service.
It is simple console app where you need to run with parameters every time (that's the reason why it is pointless to run from package center). You have to define port (every device in your house has different one) and value - 0/1 on of or 0-9 for dimmer. at the end is also protokol type EU/AnBan/Kaku/All.
You run this from SSH every time when you want to change state of your lamp on/off. In my case php exec is calling ssh function.

**Comment by ymartin59** [comment]
Hello @pitekkkk May you please install manually following package (ignore lack of signature) and confirm it works as expected on your system: 
[he853_x64-6.0.2_1.0.3-2.spk.zip](https://github.com/SynoCommunity/spksrc/files/2358732/he853_x64-6.0.2_1.0.3-2.spk.zip)

**Comment by ymartin59** [comment]
I published package update
