### ISSUE TITLE
Syncthing: Use system certificates for Web GUI

### ISSUE THREAD

**Issue by acolomb** [SynoCommunity/spksrc#3436]
_Package Name:_ syncthing
_Package Version:_ 0.14.49-15

### Expected behavior
Syncthing should show up under _Control Panel - Security - Certificates - Configure_ as an application whose server certificate can be configured.  This should especially allow to use the "system default" certificate that the DSM GUI uses as well.

At least point it at the "system default certificate" at `/usr/syno/etc/certificate/system/default/cert.pem` instead of the self-signed certificate that is generated upon Syncthing first start.

### Actual behavior
The Syncthing GUI uses its own self-signed SSL certificate. 

This has previously been discussed at https://github.com/SynoCommunity/spksrc/pull/3391#issuecomment-406567682 and https://github.com/SynoCommunity/spksrc/pull/3395#issuecomment-407229308.  Probably needs additional input / documentation from Synology on the service resource configuration.

Maybe the changes in https://github.com/SynoCommunity/spksrc/pull/3431 can give some inspiration, as GateOne seems to use the system default certificate after that PR.  Such an approach (copying the certificate and key) does not survive a renewal, though and probably has horrible security implications (copy of the private key in application directory).

**Comment by acolomb** [comment]
After some trial and error, I have a package that includes the `certificate-config` block in its `resource` file, accompanied by a no-op "reloader script" which just exits with return code 0. The package can be installed, but is then in an "Error" state, after a dialog stating "Failed to install the package". Nothing shows up in the certificate management GUI yet. I could not find anything in the install logs why it fails. Any clues where to look further?

I have sent an inquiry to Synology's developer program requesting documentation for the certificate resource specification format. Let's see what they come up with.

**Comment by BPtLNfxZWo** [comment]
Is there any update on this issue. I've installed the package on the latest DSM 7 version and it still using the self-signed certificate.
Thanks

br

**Comment by acolomb** [comment]
Unfortunately no progress to report. I never understood the spksrc mechanisms well enough to even find a way to copy the system default certificate to the package directory e. g. during installation. There were some bigger changes regarding permissions of the setup scripts as well. Might have made this issue easier or harder to solve.

Regarding the package "resource" of hooking into the certificate management GUI, there might be better documentation by now, as the developer guide was extended with the DSM7 beta release. So I've heard, no time to read up on it.

**Comment by acolomb** [comment]
I recently checked the updated Package Developer Guide, but there is still no mention of the Certificate Center or how to integrate with it from a third-party package.  I opened a new ticket with Synology's support now, let's see what help they can offer.

**Comment by acolomb** [comment]
There's some good progress toward solving this.  After some more reverse engineering (still waiting for documentation from Synology), I have at least a prototype running where Syncthing shows up under Certificates in the Control Panel and when changing the certificate, Syncthing gets reloaded automatically and uses the chosen certificate via symlink.

Still a bit rough around the edges, but we're getting closer.  Will open a PR once it's in a more polished state.
