### ISSUE TITLE
[REQUEST] Transmission x86-64 packages compatible with DSM 6.2 on Avoton ( x64 /  syno-avoton-6.2 architecture )

### ISSUE THREAD

**Issue by Hedda** [SynoCommunity/spksrc#3440]
I do not see any Transmission bittorrent client x64 package in DSM 6 when use http://packages.synocommunity.com as community packages sources?

I am currently using DSM 6.2 (DSM 6.2-23739 Update 2) on a Synology DiskStation DS1817+ which have an Intel Atom C2538 (Avalon) CPU.

Does SynoCommunity publish DSM6 x64 packages for Intel’s Atom C2000 family (better known by the codenames Avoton and Rangeley)?

PS: Know that Synology's DownloadStation is based on Transmission but I'm not happy with their implementation and want to use Transmission.

**Comment by ymartin59** [comment]
Package is available... but repository server no longer... Looks like it suffer intensive requestings

**Comment by ymartin59** [comment]
Please try to refresh Package Center list and check if packages are visible
