### ISSUE TITLE
Jackett not available in package centre 

### ISSUE THREAD

**Issue by Valo265** [SynoCommunity/spksrc#3451]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Jackett
_Package Version:_N/A

_NAS Model:_DS916+
_NAS Architecture:_
_DSM version:_DSM 6.2-23739 Update 2 

### Expected behavior
According to instructions I have seen I should be able to see Jackett as a available package in the package centr. I currently have the following community set up: 
http://packages.synocommunity.com/

### Actual behavior
Package is lot listed in package centre.

### Steps to reproduce
_1._ Open Package Center 
_2._click community
_3._ attempt to find Jackett listed in community packages

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```n/a no package to check log
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
It is there but the package server is lately overloaded.
Do a refresh of the page with the refresh button (not a refresh of your browser).
If it still does not appear you can download it here and do a manual install.
https://packages.synocommunity.com/jackett/6/jackett.v6.f4458[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-grantley-kvmx64-x86-x86_64].spk
