### ISSUE TITLE
Ipkg on dsm 6.2 via SSH from China on DS414j

### ISSUE THREAD

**Issue by Klemich** [SynoCommunity/spksrc#3453]
Hi all, 

I'm in a loop of problem : 
My NAS is a DS414j, the only one of its family with a Comcerto2k CPU...
I'm now in China, and there for at least a year, and of course, no vpn and my quickaccess via https (sadly on 443) has been blocked by the technicians of the Great Firewall.

So, I can only rely on my sftp access and my ssh access, but I can't download anymore or manage the server via the GUI. 

Hence, I would like to install the download station via command line, but for that I need ipkg.
Start of the problem : you probably know that ipkg cannot be installed on Comcerto 2k CPUs, so I need something like Optware or Entware, and there I am, trying to find a solution, because the ebi bootstrap I found on the cphub.net is for DSM 5, I'm under 6, and the the command line won't let me install it (error = [258]). 
 
Can someone help me please？
Thanks a lot.

**Comment by m4tt075** [comment]
Not sure I understand you correctly or if there are specifics with your platform I'm not aware of, but if you just want to install the standard `download station` package manually, I think the `sudo synopkg install [...]` command should do. Which specific commands from `ipkg` do you need?

**Comment by ymartin59** [comment]
@Klemich We had already discussion about it at #3403... You also should post question at https://forum.synology.com/enu/

Have you heard about SSH tunneling features?
- ssh -L 7443:localhost:443 user@mydsm.mydomain.ltd
- register in your "hosts" file 127.0.0.1 as mydsm.mydomain.ltd (after that, previous ssh command will fail, so it is a good idea to connect with IP address after DNS resolution with "nslookup" or "host")
- then point your browser to https://mydsm.mydomain.ltd:7443/ and TCP will go through your SSH tunnel to point system 443 port
Hope this helps
