### ISSUE TITLE
No tmux for DS1817+?

### ISSUE THREAD

**Issue by xnaas** [SynoCommunity/spksrc#3454]
### Setup
_Package Name:_ [tmux](https://synocommunity.com/package/tmux)
_Package Version:_ v2.3-3 (all versions)

_NAS Model:_ DS1817+
_NAS Architecture:_ x86_64
_DSM version:_ DSM 6.2-23739 Update 2

### Expected behavior
tmux should appear in Package Center.

### Actual behavior
tmux does not appear in Package Center, even with Beta packages enabled.

Note: Unsure how relevant #3223 is.

### Steps to reproduce
_1._ Have SynoCommunity added.
_2._ Enabled beta packages.
_3._ Search for tmux.

**Comment by xnaas** [comment]
Note: Installing the [5.0 avoton](https://packages.synocommunity.com/tmux/3/tmux.v3.f4458[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-grantley-kvmx64-x86-x86_64].spk) package manually _appears_ to work fine, but the package should show in Package Center, yes? :)

**Comment by BenjV** [comment]
You can try a refresh in the package center, but the SynCommunity server is overloaded lately.

**Comment by xnaas** [comment]
Fair enough.

**Comment by MatthiasLohr** [comment]
@xnaas Did you do a manual install or could you download it via package manager? I cannot find the package in package manager...

**Comment by BenjV** [comment]
The SynoCommuity server is still having severe problems and is often not reachable.
Just keep tying after an few hours waiting.

**Comment by xnaas** [comment]
@MatthiasLohr, per https://github.com/SynoCommunity/spksrc/issues/3454#issuecomment-419788429 I just installed the (seemingly) correct package for my box and it's been working fine thus far. Had an rcloen backup running for over 2 weeks in a tmux window without any issues. :D

**Comment by mastre** [comment]
`tmux` still not showing up in Package Manager with beta enabled on `x86_64` (I'm using a DS918+) as of now.  Is the only workaround to install manually?  What is failing in the selection process which decides not to display it?

**Comment by MatthiasLohr** [comment]
Same problem here. Built a solution for myself: https://github.com/MatthiasLohr/tmux-spk/releases

Right now working on a full build environment based on Docker.

**Comment by mastre** [comment]
I figured it out how to have it show in [Package Manager](https://i.imgur.com/X8H0ZBZ.png) -- you need to enable `Yes, I want to see beta versions!` *before* adding the Synocommunity source.  Simply enabling betas and refreshing did not work for me.  This points to a bug in DSM rather than in SC.  Note that the `tmux` package will show in the `Community` tab, not `Beta` as you'd expect -- I assume the `Beta` tab is only for official `Beta` packages.

**Comment by MatthiasLohr** [comment]
Synology support:
> After confirming by our developer, this is a known issue that our developers are studying and looking for a solution. Please kindly stay tuned for the update, and in the meantime, we apologize for any inconvenience caused.

**Comment by ymartin59** [comment]
Meanwhile, it is still possible to download package for your architecture from https://synocommunity.com/packages by browsing package versions.
