### ISSUE TITLE
Syncthing package does not work on DS213+

### ISSUE THREAD

**Issue by pilcru** [SynoCommunity/spksrc#3456]
### Setup
_Package Name:_ Syncthing
_Package Version:_ 0.14.49-15

_NAS Model:_ DS213+
_NAS Architecture:_ e500v2 (freescale qoriq p1022)
_DSM version:_ 6.2

### Expected behavior
Clicking on run package should start syncthing

### Actual behavior
Package status stays on stopped

### Steps to reproduce
_1._ Install syncthing from DSM GUI
_2._ Run it

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Wed Sep 12 19:15:27 EDT 2018
Starting syncthing command /volume1/@appstore/syncthing/bin/syncthing -home=/volume1/@appstore/syncthing/var
```
#### Other logs
It looks like it was not compiled for the correct architecture:
```
> file /volume1/@appstore/syncthing/bin/syncthing
syncthing: ELF 64-bit MSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), statically linked, not stripped
```
When it should say:
```
ELF 32-bit MSB executable, PowerPC or cisco 4500, version 1 (SYSV)
```

Maybe it's just not getting the correct package? I tried manually installing the .spk for qoriq but got the same results.

**Comment by cytec** [comment]
PPC isn't supported by go so there is no way to compile it for 32bit ppc.
Not sure why it even shows up in Package center afaik we only provide a 64bit ppc version \cc @Safihre

**Comment by pilcru** [comment]
Ah I see, that's too bad! I think the issue is when the arch is selected [here](https://github.com/SynoCommunity/spksrc/blob/82b71c5278e3f7e81149f74a96fac990de677a7b/cross/syncthing/Makefile#L44-L46), `$(PPC_ARCHES)` matches `qoriq` even though that's not going to be compatible with the `ppc64` that's defined in that case.

**Comment by ymartin59** [comment]
Sure that was a mistake - I have just disabled package... Please vote here https://github.com/golang/go/issues/22885 for ppc32 support in Go
