### ISSUE TITLE
ruTorrent for Apollolake on DS 918+

### ISSUE THREAD

**Issue by lordvalium** [SynoCommunity/spksrc#3457]
Please update ruTorrent for Appollolake architecture on DS918. Thank you very much

**Comment by ymartin59** [comment]
Work is in progress: #3175

**Comment by lordvalium** [comment]
Great ! That would help a lot, even DS GET/Download is not available anymore on iOS. I have no need for download station at all. So rutorrent would be absolutely amazing. I used it on DS 411+II for many years.

**Comment by bolhaskutya** [comment]
Yes, please!

**Comment by alex300414** [comment]
How is the current progress?

**Comment by lordvalium** [comment]
@alex300414 unfortunately no progress at all

**Comment by lordvalium** [comment]
> How is the current progress?

Does somebody know any other project for rutorrent on apollolake?

**Comment by th0ma7** [comment]
New and update to `rutorrent` version 3.10 uploaded on https://synocommunity.com/package/rutorrent
