### ISSUE TITLE
framework: prevent root execution which leads to invalid file owners

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3461]
Some users still run from `root` package `start-stop-status` command even when it is designed to be run as non-privileged service account thanks to DSM 6 `privilege` framework.

Script should fail with error message if run as `root` when non expected.
The same way, it should fails when `root` is expected for busybox `start-stop-daemon`

**Comment by BenjV** [comment]
Good idea.
The simplest way to do this is may be just checking one of the environment variables set by the packagecenter.
That way you can make sure the scripts will only run by the package center and just exit when the variable is not present.

**Comment by hgy59** [comment]
This is implemented by PR #4389
This PR enforces that synopgk is used to start/stop services (for any variant of calling service-setup script).
