### ISSUE TITLE
http://synocommunity.com is currently down.

### ISSUE THREAD

**Issue by sirjaymz** [SynoCommunity/spksrc#3465]
http://synocommunity.com
http://packages.synocommunity.com/

are both down at this time. 

Confirmed with 
http://www.isitdownrightnow.com/synocommunity.com.html
http://www.isitdownrightnow.com/packages.synocommunity.com.html

CloudFlare reports
Error 502 Ray ID: 45c577e28d581177 • 2018-09-18 17:17:50 UTC
Bad gateway

**Comment by nj** [comment]
Still seems to be down - only partly on due to CloudFlare 😕

**Comment by BenjV** [comment]
Seems to be online again.

**Comment by seewaldjan** [comment]
> Seems to be online again.

no

**Comment by BenjV** [comment]
It's on and off reachable, at this moment it is not reachable.
At the time I wrote that it was online again it was of course reachable otherwise I would not have written it.
I even updated SABnzb at that time.

**Comment by sirjaymz** [comment]
Sites seems to be back online. Closing.
