### ISSUE TITLE
Redis 4.0

### ISSUE THREAD

**Issue by flip111** [SynoCommunity/spksrc#3469]
Redis from SynoCommunity is on version 3.0.5-5

Redis 4.0:

Redis 4.0 was released as GA in July 2017. Contains several big improvements: a modules system, much better replication (PSYNC2), improvements to eviction policies, threaded DEL/FLUSH, mixed RDB+AOF format, Raspberry Pi support as primary platform, the new MEMORY command, Redis Cluster support for Nat/Docker, active memory defragmentation, memory usage and performance improvements, much faster Redis Cluster key creation, many other smaller features and a number of behavior fixed. 

I think 1 year is enough to mature version 4.0 (which is now 4.0.11), work on redis 5.0 is already underway.

I don't understand "Bleeding Edge" advertisement on https://synocommunity.com/ bleeding edge is 5.0 or last commit on master repository.

**Comment by flip111** [comment]
I'm just saying that "bleeding edge" sets expectations which are not true for this package. It's not my fault that i have this expectation as it says so on the front page. If you want me or any other users not to expect packages to be up to date that don't put it on the front page. Simple.

I read the FAQ and afaik i can make this package request (update). I'm not even addressing any particular people, the ones you refer to as "people who do the work in their free time for no payment at all". It's common on github to say "Pull Request are welcome" (meaning: do it yourself). Since Redis 4.0 package is not there yet, it's not provided. I'm sure the Redis 3.0 package is tip top.

**Comment by Diaoul** [comment]
There is no need for harsh words.
SynoCommunity is as the name suggests, community-based, most popular packages are frequently updated thanks to involved members (sometimes also users) of the said packages.
Keeping track of all upstream changes is a heavy task that is not currently done by maintainers and never will.
If you have a package update request, it will not be rejected for backward compatibility reasons. In that regard, the statement is correct.
Backward compatibility is always sought but it must not be a reason for holding a package release forever.

You can ask for a package update politely as someone will work on it for free, submit a Pull Request or just don't use SynoCommunity if you're not happy with it and don't want to contribute.

**Comment by flip111** [comment]
Maybe you guys would be happy if i dropped in "please" and "with sugar on top" in a few places. That would have been nice for sure. However i didn't call out to any people and the things i said are factually true. To say:

* have attitude
* difficulty to be polite
* unsocial media
* harsh words

is too much!! Because what i've written may not be nice, but it's not these accusations either. I feel all this stems from my comment about "bleeding edge" which is (like i said before) not my fault that i have this expectation. Maybe you can start with this "politeness" yourself and set a good example for people new to the community. Now i don't feel welcome anymore.
