### ISSUE TITLE
[Package Request] Paperless

### ISSUE THREAD

**Issue by dadosch** [SynoCommunity/spksrc#3472]
Name: Paperless
Description: Scan, index, and archive all of your paper documents
Website: https://github.com/danielquinn/paperless
Software documentation: https://paperless.readthedocs.io/en/latest/
Build/Installation documentation: [requirements](https://paperless.readthedocs.io/en/latest/requirements.html) and [setup](https://paperless.readthedocs.io/en/latest/setup.html)
Source code: https://github.com/danielquinn/paperless
License: GPL

**Comment by mtonnie** [comment]
I have almost finished a very first beta version. 
It‘s a quite limited concerning configuration options, it‘s just possible to specify how one directory for files storage.

**Comment by iwconfig** [comment]
This is much appreciated! :+1: 

However, since [the-paperless-project/paperless](/the-paperless-project/paperless) is no longer maintained, you should maybe look into continuing with [jonaswinkler/paperless-ng](/jonaswinkler/paperless-ng) instead.

**Comment by hgy59** [comment]
Outdated and obsoleted by #6286, but not suitable for Synology Package(s) anyway.
