### ISSUE TITLE
IceCast not in PackageCenter

### ISSUE THREAD

**Issue by MatthK** [SynoCommunity/spksrc#3475]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ https://synocommunity.com/package/icecast 
_Package Version:_ 2.4.1-1

_NAS Model:_ DS1511+ and DS918+
_NAS Architecture:_
_DSM version:_ 6.2-23739 Update 2

### Expected behavior
I have added the packages.synocommunity.com to the package center and also enable beta versions. I would expect to see the Icecast package in package center for installation.

### Actual behavior
Even if I set "Any publisher" can install packages I cannot see the Icecast package.

### Steps to reproduce
_1._ Open package center
_2._ Set the settings accordingly (add http://packages.synocommunity.com/)
_3._ Search for the Icecast package

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
This beta package requires update and support for DSM 6.

**Comment by mortenkn** [comment]
Hi, could you update the IceCast package to the latest release? It contains serval security fixes.
Thanks

**Comment by hgy59** [comment]
fixed with #4628 (or before...)
