### ISSUE TITLE
Request for Tvheadend package update

### ISSUE THREAD

**Issue by vaggvisa** [SynoCommunity/spksrc#3476]
### Setup
_Package Name:_ Tvheadend
_Package Version:_ v4.2.6-13

_NAS Model:_ DS115
_NAS Architecture:_ arm375
_DSM version:_ 6.1.2

### Expected behavior
Tvheadend used as SAT>IP client to receive streams from DVB-C Tuner FRITZ!Box 6490

### Actual behavior
see two already resolved issues in Tvheadend project: [SAT>IP broken after FRITZ!Box 6490 Firmware Update v7](https://tvheadend.org/issues/5231) and [Devices Implementing Sat>Ip Specification v1.2.2 for DVB-C do not work](https://tvheadend.org/issues/5157)

### Solution
issue is solved in recent Tvheadend-Version, see [Fixed in v4.3-1394-g37f9f6b08](https://tvheadend.org/issues/5231#note-5)

### Request

**Please update the Tvheadend-Package to include the latest patches. Thanks!**

**Comment by fLaSkin** [comment]
Just for a complete story,
The guy was commited here:

https://github.com/tvheadend/tvheadend/commit/37f9f6b08666c7f18eab2befd4d28e96f484aabb

**Comment by m4tt075** [comment]
Sorry, but I'm not able to maintain an unstable testing version for `tvheadend` on this repo. Having said that, @jdierkse has posted testing versions [here](http://syno.dierkse.nl/) from time to time. If you are lucky, the next one contains the fix you are looking for. It also seems that @perexg has committed the same fix to his [4.2 release branch](https://github.com/tvheadend/tvheadend/tree/release/4.2). As such, it should be contained in any upcoming 4.2.7 maintenance release as well. I will update the SynoCommunity `tvheadend` package again, once @perexg releases 4.2.7. Until then, I'm afraid, you have to be patient or fork the `spksrc` repo and try to update it yourself.

**Comment by fLaSkin** [comment]
thanks for your reply m4tt075.
my progress on updating by myself: did manage to setup the dev. environment, but dont have any skill / experience on (cross-) compiling at all - so failed to get any further after that.
have to shame for, but I'm more the kind of linux-noob and "dumb" user.

**Comment by m4tt075** [comment]
Yes, will look at it...

**Comment by m4tt075** [comment]
OK, chaps. You will find 6.1/6.2 test builds here: https://github.com/m4tt075/spksrc/releases/tag/tvh-4.2.7-1
Do **not** forget to backup your installations **before** upgrading. Otherwise, as usual, please do report **all** test results, the good, the bad and the ugly. All feedback will help and be appreciated...

**Comment by vaggvisa** [comment]
Thanks a lot! Works like a charm on my DS115 - and actually serves to solve my original problem.

**Comment by roesl** [comment]
Hello,

is there a description, how to backup the old TVH config and update version 4.2.6.13 to 4.2.7.14 ?

at my Diskstation I only can remove the old installation and install the new version but I´m not able to  make an update.

Georg

**Comment by m4tt075** [comment]
A backup never hurts. You need to `ssh` into your NAS. The configuration is stored in `/usr/local/tvheadend/var`. Just tar it and put it in a save place, e.g. some shared folder, as the /usr/local/tvheadend folder will be nuked during the deinstallation process. Untar it after the installation and you should be fine.

However, You SHOULD be able to upgrade on any NAS. Simply install the new version over the old one. Unless you have messed around with different package sources, that should work. In any case, backup first, just in case...

**Comment by m4tt075** [comment]
Package has been updated to 4.2.8 in the meantime. Closing...
