### ISSUE TITLE
Jackett not available for DSM 6.1 in many architectures

### ISSUE THREAD

**Issue by davidcava** [SynoCommunity/spksrc#3480]
### Setup
_Package Name: Jackett
_Package Version: v0.8.490-6 

_NAS Model: DS214play
_NAS Architecture: evansport
_DSM version: 6.1

### Expected behavior
Find Jackett in the package center and in [https://synocommunity.com/package/jackett](https://synocommunity.com/package/jackett) for architecture evansport in version 6.1

### Actual behavior
Jackett is not visible in package center.
Direct link also does not exist: [https://packages.synocommunity.com/jackett/6/jackett.v6.f15047[evansport].spk](https://packages.synocommunity.com/jackett/6/jackett.v6.f15047[evansport].spk)

**Comment by m4tt075** [comment]
Hmh, just logged into my DS415Play (`evansport`, just like yours) and `Jackett` is available via the repo. We have had problems with the SynoCommunity server lately. Please just check back from time and time, always refreshing your package center. It should show up eventually...

**Comment by m4tt075** [comment]
The 5.0 `evansport` version is the one you want. The package does not depend on the specific toolchain. The `rtd1296` and `docker64` platforms were only introduced with DSM 6.0/6.1, which is the only reason why there are no 5.x versions for them. The DSM package manager sorts these things out automatically for you. I'm still surprised that you do not seem to be able to access `Jackett` there...

**Comment by davidcava** [comment]
ok thanks, installed manually from 5.0/evansport and working indeed.
No idea why it does not appear with the other SynoCommunity packages. I tried to remove the repo and re-add it, no difference.
![capture d ecran de 2018-10-09 20-03-56](https://user-images.githubusercontent.com/30037186/46668398-e215a080-cbfe-11e8-9cae-0d60d41eb435.png)
