### ISSUE TITLE
MQTT Armada 3720 request

### ISSUE THREAD

**Issue by michass** [SynoCommunity/spksrc#3481]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Mosquitto
_Package Version:_ actual

_NAS Model:_DS119j
_NAS Architecture:_Armada37x
_DSM version:_6.2.1-23824

### Expected behavior
Please add Maosquitto for new device

### Actual behavior
I can't use MQTT

**Comment by ymartin59** [comment]
This new arch `armada37xx` is not yet supported here.

**Comment by ymartin59** [comment]
Depends on #3477

**Comment by ymartin59** [comment]
Published at https://synocommunity.com/package/mosquitto
It should be available in your DSM Package Center.
