### ISSUE TITLE
No running status for Radarr in DSM

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#3483]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Radarr
_Package Version:_20180303-6

_NAS Model:_
_NAS Architecture:_DS715
_DSM version:_DSM 6.2-23739 Update 2

### Expected behavior
See Radarr as runnign in DSM

### Actual behavior
It shows as stopped and manual restarting gives error's.
Strange thing is that the Sonarr package runs normally and has the same start-stop-status script.
It will eventually run but shows stopped in DSM

./service-setup: line 6: [: -lt: unary operator expected
Starting  ...
./service-setup: line 18: type: service_prestart: not found
./start-stop-status: line 29: [: too many arguments

### Steps to reproduce
_1._lauch from CLI /var/packages/radarr/scripts# ./start-stop-status start
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Wed Oct 10 11:35:33 CEST 2018
Starting radarr command env PATH=/usr/local/mono/bin:/volume1/@appstore/radarr/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/lo
cal/sbin:/usr/local/bin HOME=/volume1/@appstore/radarr/var LD_LIBRARY_PATH=/volume1/@appstore/radarr/lib /usr/local/mono/bin/mono /volume1/@appstore/
radarr/share/Radarr/Radarr.exe 
[Info] Bootstrap: Starting Radarr - /volume1/@appstore/radarr/share/Radarr/Radarr.exe - Version 0.2.0.1198 
[Info] Router: Application mode: Interactive 
[Info] MigrationLogger: *** Migrating data source=/volume1/@appstore/radarr/var/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;jour
nal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationLogger: *** Migrating data source=/volume1/@appstore/radarr/var/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal 
mode=Wal;pooling=True;version=3 *** 
[Info] OwinHostController: Listening on the following URLs: 
[Info] OwinHostController:   http://*:7878/ 
[Info] NancyBootstrapper: Starting NzbDrone API 
[Info] CommandExecutor: Starting 2 threads for tasks. 
[Info] PreDBService: Starting PreDB Sync 
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
Trying to run packages from the commandline with the start-stop-status script is no option anymore.
The package center set some environment variables before the script is started and the script is using these.
So once you tried to do that you have messed up everything and this cannot be undone without a reboot.

If yo want to start a package from the commandline you need to use the synopkg start  command like this.
sudo /usr/syno/bin/synopkg start <packagename>

**Comment by schumi2004** [comment]
Okay that explains a lot, thanks for clarifying.
I wasn't aware of the commandline way of starting done by me was not supported anymore.
