### ISSUE TITLE
problem using mercurial

### ISSUE THREAD

**Issue by fabioparodi** [SynoCommunity/spksrc#3485]
### Setup
_Package Name:_ Mercurial
_Package Version:_ 4.0.1-4

_NAS Model:_ RS818RP+
_NAS Architecture:_ intel
_DSM version:_ DSM 6.2.1-23824

### Expected behavior
I did install mercurial on my RS818. The package installed and reports to be running fine.
I would like to start using it, for example by cloning a repository:

 hg clone . ssh://fabio.parodi@192.168.185.5//home/hg/BM2

Expected behavior is: clone the repo so that people can start pushing revisions.

### Actual behavior
hg answers: 
Permission denied, please try again.

### Steps to reproduce
install the mercurial package
try to clone a repository to the remote server

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
Let's try following "scp" command from another system:  scp -r fabio.parodi@192.168.185.5:/home/hg/BM2 .

I expect it answers "permission denied" too, meaning user account "fabio.parodi" has no read permission on folder /home/hg/BM2. So grant read/write permission for users on your repository first.

**Comment by ymartin59** [comment]
Mercurial update has been published.
Because of no feedback/reply, I close this issue.
