### ISSUE TITLE
[Package Request] sshfs for DS418j (arch rtd1296)

### ISSUE THREAD

**Issue by DrSpaldo** [SynoCommunity/spksrc#3489]
Name: sshfs
Description: filesystem client based on the SSH File Transfer Protocol

These packages currently exist on the SynoCommunity site:

https://synocommunity.com/package/sshfs

However, I am not sure if another one needs to be built for the rtd1296 Architecture or if I can use one of the current ones. 

If anyone can help it would be much appreciated.

**Comment by DrSpaldo** [comment]
Hi ymartin59. Thanks for the post. Excuse my ignorance but is your spk one that has a bundle of commands/programs in it? And you are going to add sshfs as well?

 If so, great! 

Is it available already?

**Comment by ymartin59** [comment]
Yes that is exactly what is planned. I try to get it available soon.

**Comment by DrSpaldo** [comment]
Great, looking forward to it. Thank you

**Comment by ymartin59** [comment]
You will find sshfs for your arch in packag https://synocommunity.com/package/synocli-net
Not the latest version but should work.

**Comment by DrSpaldo** [comment]
Great, thank you 👍
