### ISSUE TITLE
Change Start Up User

### ISSUE THREAD

**Issue by Rio-D** [SynoCommunity/spksrc#3493]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_sickbeard-custom
_Package Version:_20180629-7

_NAS Model:_DS716+
_NAS Architecture:_
_DSM version:_6.2-23739 Update 2

### Expected behavior
Tell us what should happen
I modified the service-setup file to set the user to "Extension"
I also modiied the ifstatement to make sure it is set to only Extension

USER="Extension"
PRIV_PREFIX=sc-
SYNOUSER_PREFIX=svc-
if [ -n "${SYNOPKG_DSM_VERSION_MAJOR}" -a "${SYNOPKG_DSM_VERSION_MAJOR}" -lt 6 ]; then EFF_USER="${USER}"; else EFF_USER="${USER}"; fi

Now when I start sickbeard, I expect it to use the username I created called 'Extension' to run as. 
### Actual behavior
When I check -htop, the user it is run as is: sc-sickbeard-custom

**Comment by m4tt075** [comment]
Sorry, doesn't work like this. If you want to change the user, you need to clone our github repository, change the sources and compile the spk yourself. But why do you want to change the user for the package?

**Comment by Rio-D** [comment]
> Sorry, doesn't work like this. If you want to change the user, you need to clone our github repository, change the sources and compile the spk yourself. But why do you want to change the user for the package?

I was under the impression, this was possible in the past. 

As for why, I'd prefer if all 3rd party applications were set to one user. I am unable to find where in the code it starts up as the user.

**Comment by ymartin59** [comment]
In the "past", service was running as "root" so it can access (and potentially leak) any file.

Please read details at https://github.com/SynoCommunity/spksrc/wiki/Permission-Management
and how to configure permissions - as far as I know link was provided at package installation wizard.

Service user is manage by DSM packaging itself. Please refer to https://originhelp.synology.com/developer-guide/privilege/preface.html if you are still thinking your best option is to run all services with same user account...
