### ISSUE TITLE
After install Syncthing its not listed in main menu

### ISSUE THREAD

**Issue by NoOneAtHome** [SynoCommunity/spksrc#3494]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Syncthing 
_Package Version: 0.14.49-15

_NAS Model: DS918+
_NAS Architecture: x64
_DSM version: DSM 6.2.1-23824

### Expected behavior
After installing and clicking Main Menu in top left Syncthing logo should appear and when clicked take you to the Syncthing Web UI

### Actual behavior
Syncthing icon/link not in Main menu, but can navigate manually to http://ipaddress:8384

### Steps to reproduce
_1. install Syncthing
_2. go to main meno 
[syncthing_install.log](https://github.com/SynoCommunity/spksrc/files/2489961/syncthing_install.log)

_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
Forget previous comment. Menu only appears to admin first. It is required to grant other users privilege to access application, so that menu item is visible. Please refer to https://www.synology.com/en-us/knowledgebase/DSM/help/DSM/AdminCenter/application_appprivilege

**Comment by bocekm** [comment]
Thanks for writing the issue, @ymartin59. Before reading it, I didn't know the port changed from 7070 to 8384 and about the need to grant additional permissions.

**Comment by hgy59** [comment]
@bocekm is anything open on this issue or can we close this?

An update is on the way with #4685

**Comment by hgy59** [comment]
This is fixed by #4685 (except for DSM7).
And there is a link in `PackageCenter - Installed Packages - Syncthing` for all DSM version.
