### ISSUE TITLE
nzbget for apollolake?

### ISSUE THREAD

**Issue by monkiibiz** [SynoCommunity/spksrc#3495]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ nzbget
_Package Version:_ v20180322-25

_NAS Model:_ DS918+
_NAS Architecture:_ apollolake
_DSM version:_ 6.2.1-23824

### Expected behavior
able to install nzbget

### Actual behavior
package is not displayed - https://synocommunity.com/package/nzbget does not show support for apollolake on DSM 6

**Comment by ymartin59** [comment]
As far as I know, Package Center will grab apollolake build for DSM 5.x which is fully compatible with DSM 6.
What is wrong exactly with your Package Center setup?

**Comment by monkiibiz** [comment]
Interesting - nowhere to be found for me.
![image](https://user-images.githubusercontent.com/4595037/47256528-44ce2e00-d482-11e8-8963-ea24528ee922.png)
![image](https://user-images.githubusercontent.com/4595037/47256552-84951580-d482-11e8-9d93-a83f75821b1a.png)

**Comment by ymartin59** [comment]
You can compare with zsh package which is published the same way: https://synocommunity.com/package/zsh
I have no idea why nzbget does not show in Package Center.
By the way, you can download package file from https://packages.synocommunity.com/nzbget/25/nzbget.v25.f4458[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-grantley-kvmx64-x86-x86_64].spk and install it manually.

**Comment by monkiibiz** [comment]
Manual install worked without any problems - thanks!

**Comment by m4tt075** [comment]
I've heard about the "missing package" issue in other threads as well. Experienced it myself. They are gone, you refresh 20 minutes later, they are there, and then, sometimes they are gone again. Might be an issue with the server. Just FYI, as we might encounter those problems more frequently in the future...
