### ISSUE TITLE
Debian Chroot package is missing

### ISSUE THREAD

**Issue by agross** [SynoCommunity/spksrc#3496]
I needed to reinstall my DSM, hence I also need to reinstall Debian Chroot. I've added the package source (and installed zsh ;-), but Debian Chroot is no listed. The package is also missing in the [package directory web site](https://synocommunity.com/packages).

### Expected behavior

Package is listed and installable.

### Actual behavior

Package is not listed.

**Comment by ymartin59** [comment]
I have unpublish debian-chroot package as it has not properly tested for DSM 6 and some reports mention system corruption requiring full reinstall...

**Comment by agross** [comment]
> system corruption requiring full reinstall

That sounds familiar. Thanks for the information. I suggest we keep this ticket open, such that others find it easily. Once these issues are fixed, we can close it. OK?

**Comment by ymartin59** [comment]
There are already lots of open issues about it. I simply preferred to mask package even some contributors try to work-around issues: https://github.com/SynoCommunity/spksrc/wiki/Debian-Chroot#manual-example-ssh-server

**Comment by agross** [comment]
I only used Debian chroot for netdata. In the meantime, I was able to get it up and running with docker. You may close this issue if you prefer that.

**Comment by lordvalium** [comment]
I guess this is related to my issue or? https://github.com/SynoCommunity/spksrc/issues/3507
That would explain why its not visble in the package manager
