### ISSUE TITLE
Can't add Syno to DS119J

### ISSUE THREAD

**Issue by William0702** [SynoCommunity/spksrc#3497]
Please add support for DS119J. 

Add availability Syno. community for ds119j

_NAS Model:_ DS119J
_NAS Architecture: Marvell Armada 370
_DSM version:_6.2.1-23824

**Comment by ymartin59** [comment]
This new architecture is not yet supported.

**Comment by michass** [comment]
jadahl.com can compile packages for DS119j

**Comment by ymartin59** [comment]
Duplicates #3477
