### ISSUE TITLE
[Jackett] Upgrade to latest version

### ISSUE THREAD

**Issue by martindanielson** [SynoCommunity/spksrc#3500]
### Setup
_Package Name:_ Jackett
_Package Version:_ 0.8.490-6

_NAS Model:_ DS1512+
_NAS Architecture:_ cedarview
_DSM version:_ 6.2.1-23824

### Expected behavior
I am trying to use The Pirate Bay and RARBG but these have issues in Jackett; that have been fixed in later versions. I.e. https://github.com/Jackett/Jackett/issues/2753

### Actual behavior
I would like to be able to use the public trackers and other features/fixes that comes with more recent version of Jackett :puppyeyes:

### Steps to reproduce
_1._ Add the Jackett package available through DSM
_2._ Add indexers The Pirate Bay or RARBG in the Jackett interface
_3._ Press test, observer error message

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Its not really an investigatory type of task, so I have omitted the log. But if you need it let me know and I will post relevant logs.
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Its not really an investigatory type of task, so I have omitted the log. But if you need it let me know and I will post relevant logs.
```

**Comment by enchained** [comment]
Try the internal update function
https://github.com/SynoCommunity/spksrc/issues/3394

**Comment by martindanielson** [comment]
That worked like a charm!
