### ISSUE TITLE
Integrate into DSM help -  URL's broken

### ISSUE THREAD

**Issue by fgma** [SynoCommunity/spksrc#3503]
I"m currently in the process of creating a new package on DSM 6.2.1. I'd like to integrate some documentation in DSM help. I tried to use dnscrypt-proxy [spksrc/spk/dnscrypt-proxy/src/service-setup.sh]( ../blob/master/spk/dnscrypt-proxy/src/service-setup.sh
) as a template by adding
 
```
echo "Install Help files" >> "${INST_LOG}"
pkgindexer_add "${SYNOPKG_PKGDEST}/app/index.conf" >> "${INST_LOG}" 2>&1
pkgindexer_add "${SYNOPKG_PKGDEST}/app/helptoc.conf" >> "${INST_LOG}" 2>&1
```

and the matching pkgindexer_del into my setup script. This basically adds my help files to DSM help when using offline mode. The problem is all the links in the tree are wrong. They point to

"http://...:5000/3rdparty/my-package/help/enu/index.html"

instead of

"http://...:5000/webman/3rdparty/my-package/help/enu/index.html"

which actually works when manually entering it into the browser.

I also tried using a conf/resource file as stated in the official DSM developer documentation which does not work at all.

```
{
	"indexdb": {
		"app-index"  : {
			"conf-relpath": "app/index.conf",
			"db-relpath": "indexdb/appindexdb"
		},
		"help-index": {
			"conf-relpath": "app/helptoc.conf",
			"db-relpath": "indexdb/helpindexdb"
		}
	}
}
```

Is there any up to date guide on how to add you own help files?

**Comment by publicarray** [comment]
I take it that you have read the developer guide? https://originhelp.synology.com/developer-guide/integrate_dsm/dsm_help.html

I found the German wiki more helpful https://www.synology-wiki.de/index.php/Integration_einer_Hilfe_in_DSM_5.1-#Ressource_Spezifikation_.28resource.29_erstellen_.28nur_DSM_.3E.3D_6.0.29 you can usev google translate :)

**Comment by ymartin59** [comment]
Any news? Still ned some help?

**Comment by fgma** [comment]
I solved the issues somehow by restarting from a working package. I still don"t understand where the actual problem was. I hope I get some time over holidays to continue packaging.
