### ISSUE TITLE
Why is debian chroot not working on my DS918+?

### ISSUE THREAD

**Issue by lordvalium** [SynoCommunity/spksrc#3507]
Hi, 
i try to install rar2fs and for that i would try debian chroot. 
But i cant find it in the packages. Do i need special permission settings or is it not available anymore?

**Comment by lordvalium** [comment]
Hi @xnaas any plan to enable and fix it again?

**Comment by xnaas** [comment]
I'm not the package maintainer, but see additional latest comments on #3055. Someone has a link.

**Comment by lordvalium** [comment]
Thank you @xnaas  that is a great project!
