### ISSUE TITLE
Cannot schedule sickbeard-custom to start or stop since Synology DSM 6.0

### ISSUE THREAD

**Issue by GGMalone** [SynoCommunity/spksrc#3508]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Sickbeard Custom
_Package Version:_ 20180629-7

_NAS Model:_
Synology 415 Play
_DSM version:_ DSM 6.2.1-23824 Update 1

### Expected behavior
I have 2 tasks in Task Scheduler to start and stop sickbeard-custom.
1) Runs this to start: /var/packages/sickbeard-custom/scripts/start-stop-status start
2) Runs this to stop: /var/packages/sickbeard-custom/scripts/start-stop-status stop

Prior to DSM 6 these worked perfectly.

### Actual behavior
Since DSM 6 it no longer does anything.

I have manually run the script in putty and get the following error message:

**/var/packages/sickbeard-custom/scripts/service-setup: line 6: [: : integer expression expected**

### Steps to reproduce
_1._ Create a scheduled task (user defined script) in Task Scheduler running as root.
_2._  Enter in the script /var/packages/sickbeard-custom/scripts/start-stop-status start or /var/packages/sickbeard-custom/scripts/start-stop-status stop depending on which way you want to test.
_3._ Run the script manually.

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Nothing in the package log as the script is not working.
```
#### Other logs
Nothing in any other logs that I can find related the script not working.

**Comment by BenjV** [comment]
You cannot use that script because that is exclusive used by the package center
The package center creates environment variables which are used by the script, so if you want you start or stop a package in the task scheduler you have to use the following commands:

> synopkg start sickbeard-cutom
> and
> synopkg stop sickbeard-costum

**Comment by GGMalone** [comment]
Perfect!

Thank you sir!

**Comment by ymartin59** [comment]
Refer also to FAQ: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#how-to-query-package-status-or-start-it-from-command-line
