### ISSUE TITLE
NZBGet Package updated to 20.0, Communication Error invalid status 401

### ISSUE THREAD

**Issue by Teryon** [SynoCommunity/spksrc#3509]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_nzbget
_Package Version:_v25.f4458[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-grantley-kvmx64-x86-x86_64]

_NAS Model:_DS1513+
_NAS Architecture:_Cedarview
_DSM version:_DSM 6.2.1-23824 Update 1

### Expected behavior
When I click on some action it should make it, like "delete" in history or "clear" in messages.

### Actual behavior
All I have is : 
Communication error!
Invalid Status: 401

### Steps to reproduce
_1._Click settings, Check for updates, update to last stable official release (20.0)
_2._Try to delete history, clear messages or other commands.
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Starting nzbget command /volume1/@appstore/nzbget/bin/nzbget -c /volume1/@appstore/nzbget/var/nzbget.conf -o WebDir=/volume1/@appstore/nzbget/bin/webui -o LockFile=/volume1/@appstore/nzbget/var/nzbget.pid -D
Fri Nov  2 23:22:03 2018    INFO    nzbget 20.0 daemon-mode
Fri Nov  2 23:22:04 2018    DETAIL  Downloading NZBs Cart
Fri Nov  2 23:22:05 2018    DETAIL  Download NZBs Cart completed
Fri Nov  2 23:22:05 2018    DETAIL  Scheduling update for feed NZBs Cart in 15 minute(s)
Fri Nov  2 23:22:05 2018    DETAIL  NZBs Cart has no new items


```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
2018/11/02 19:45:27 stop nzbget: begin to stop version 20180322-25
2018/11/02 19:45:28 stop nzbget 20180322-25 Begin start-stop-status stop
Stopping nzbget ...
/var/packages/nzbget/scripts/service-setup: line 20: type: service_poststop: not found
2018/11/02 19:45:29 stop nzbget 20180322-25 End start-stop-status stop ret=[0]
2018/11/02 19:45:29 stop nzbget 20180322-25 Begin unload apparmor
2018/11/02 19:45:29 stop nzbget 20180322-25 End unload apparmor ret=[0]
2018/11/02 19:45:29 stop nzbget: stop version 20180322-25 successfully, result 0
2018/11/02 19:45:41 start nzbget: begin to start version 20180322-25
2018/11/02 19:45:41 start nzbget 20180322-25 Begin pre-load apparmor
2018/11/02 19:45:41 start nzbget 20180322-25 End pre-load apparmor ret=[0]
2018/11/02 19:45:41 start nzbget 20180322-25 Begin start-stop-status start
Starting nzbget ...
/var/packages/nzbget/scripts/service-setup: line 20: type: service_prestart: not found
2018/11/02 19:45:41 start nzbget 20180322-25 End start-stop-status start ret=[0]
2018/11/02 19:45:41 start nzbget: start version 20180322-25 successfully, result 0

```

**Comment by Teryon** [comment]
![annotation 2018-11-02 231917](https://user-images.githubusercontent.com/36746074/47943331-d6638400-def5-11e8-8471-b9d2110d732e.jpg)

**Comment by BenjV** [comment]
If you update from within Nzbget, you get a general binary from the Nznget developers and not a binary that is compiles and build specific for your Nas by the SynoCommunity.

So it could not work and issues with it should be discussed on their website on not here.

**Comment by Teryon** [comment]
Already done same output. :/

**Comment by BenjV** [comment]
I installed nzbget but did not get any problem, but I have a diffferent architecture (armada and not X64).

**Comment by Teryon** [comment]
did you update the package from nzbget ?

**Comment by Teryon** [comment]
This is crazy, happens with Edge but not Firefox !

**Comment by Teryon** [comment]
I've been able to delete hsitory from Firefox but always an error from Edge !

**Comment by BenjV** [comment]
I suggest you put this issue on the table at the nzbget github because it is not a package issue but an nzbget issue.
https://github.com/nzbget/nzbget/issues

**Comment by ymartin59** [comment]
There is a chance your credentials stored in Edge browser and no longer valid if you have change account password...

**Comment by Teryon** [comment]
I can log in, my credential never changed.

**Comment by ymartin59** [comment]
Updates have been published. Re-open if issue is still relevant.
