### ISSUE TITLE
TestDisk doesn't work on synology ds115j (dsm 6.1, armada370)

### ISSUE THREAD

**Issue by mav1** [SynoCommunity/spksrc#3513]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_TestDisk
_Package Version:_v7.0-2

_NAS Model:_DS115j
_NAS Architecture:_armv7l
_DSM version:_DSM 6.1.1-15047

### Expected behavior
After running  /usr/local/testdisk/bin/testdisk a console application should start normally

### Actual behavior
After running  /usr/local/testdisk/bin/testdisk it shows:
TestDisk 7.0, Data Recovery Utility, April 2015
Christophe GRENIER <grenier@cgsecurity.org>
http://www.cgsecurity.org
Segmentation fault (core dumped)

### Steps to reproduce
Run installed binary:
/usr/local/testdisk/bin/testdisk

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
None
```
#### Other logs
none
```
Insert log here
```

**Comment by ymartin59** [comment]
Here is package for DSM 6.1 armada370 
[testdisk_armada370-6.1_7.0-2.spk.zip](https://github.com/SynoCommunity/spksrc/files/2569393/testdisk_armada370-6.1_7.0-2.spk.zip)

**Comment by mav1** [comment]
Thanks a lot, it works!!!

Best Regards, Alexander


>Воскресенье, 11 ноября 2018, 16:50 +03:00 от Yves Martin <notifications@github.com>:
>
>Here is package for DSM 6.1 armada370
>testdisk_armada370-6.1_7.0-2.spk.zip
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Alexander
