### ISSUE TITLE
unrar "operation failed" on folders transmission downloaded

### ISSUE THREAD

**Issue by lordvalium** [SynoCommunity/spksrc#3514]
Folders downloaded by transmission have strange behaviour. Right click on *.rar file in Filestation on DSM brings that error
![image](https://user-images.githubusercontent.com/2970225/48281738-cdc00000-e457-11e8-881b-c71e55705ad4.png)

I ssh'ed that folder, "sudo unrar e *.rar" was working. Please help me. That sc-download thing is quite strange

**Comment by BenjV** [comment]
Most likely the user that you use to run FileStation does not have permissions on those .rar files.
Add the user to the group sc-download to fix this.

**Comment by mreid-tt** [comment]
With the permissions for SynoCommunity packages well documents in the [FAQ](https://github.com/SynoCommunity/spksrc/wiki/Permission-Concept), should this issue now be closed?
