### ISSUE TITLE
Synology DSM Transmission : temporary folder doesn't exist

### ISSUE THREAD

**Issue by Nemrod7** [SynoCommunity/spksrc#3515]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Transmission
_Package Version:_v2.94-16

_NAS Model:_DS916+
_NAS Architecture:_braswell (x64)
_DSM version:_DSM 6.2.1-23824 Update 1

### Expected behavior
Installation of transmission

### Actual behavior
I'm trying to install transmission package but the installation is blocked with the following error message : "temporary folder doesn't exist". Of course, the shared folder exist.

<img width="700" alt="capture d ecran 2018-11-12 a 19 57 31" src="https://user-images.githubusercontent.com/9394310/48371496-563eda80-e6bc-11e8-8c3c-3031fdffdf05.png">

### Steps to reproduce
Click on install from package center

#### Package log
N/A

Insert the package log here
N/A

#### Other logs
N/A

Insert log here
N/A

**Comment by publicarray** [comment]
Are you sure you don't mean `/volume1/Temp`? shared folders are top level by default, normal folders are where you'd expect them to be.

**Comment by Nemrod7** [comment]
> Are you sure you don't mean `/volume1/Temp`? shared folders are top level by default, normal folders are where you'd expect them to be.

My downloads are located in the shared folder  /Volume1/Downloads, so I tried /Volume1/Downloads & /Volume1/Downloads/Temp.

**Comment by Nemrod7** [comment]
> If the folder "downloads" already existed and was not created by the package then you first have to give the group sc-download permissions to that folder.

It already has the permission, It is used by Sonarr & Download Station.

**Comment by Nemrod7** [comment]
The shared folder is "/Volume1/Downloads", I added a "Temp" folder for temporary files. I just tested the installation, without specifying this temporary folder, it worked

**Comment by BenjV** [comment]
The installation is asking for a Shared folder and not for a Subfolder.
You cannot create a Subfolder during installation only a Shared Folder.
If you want to use a Subfolder you have to created that Subfolder with FileStation and change in tarnsmission the path to use.

**Comment by Nemrod7** [comment]
> The installation is asking for a Shared folder and not for a Subfolder.
> You cannot create a Subfolder during installation only a Shared Folder.
> If you want to use a Subfolder you have to created that Subfolder with FileStation and change in tarnsmission the path to use.

I created the subfolder before trying to install Transmission.

**Comment by BenjV** [comment]
Does not matter, you put in this SubFolder name during installation and the package tries to create a Shared folder named /volume1/Downloads/Temp which cannot be done.

**Comment by Nemrod7** [comment]
Ok, i understand know, thanks !

**Comment by ymartin59** [comment]
@BenjV May be good idea but code does not test if path exists, as installer creates Share Folder if lacking... My option would be to create subfolder too.

**Comment by mreid-tt** [comment]
Is this issue considered resolved and can be closed?

**Comment by Nemrod7** [comment]
Yes
