### ISSUE TITLE
Transmission : incorrect download folder

### ISSUE THREAD

**Issue by Nemrod7** [SynoCommunity/spksrc#3516]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Transmission
_Package Version:_v2.94-16

_NAS Model:_DS916+
_NAS Architecture:_braswell (x64)
_DSM version:_DSM 6.2.1-23824 Update 1

### Expected behavior
I expect Transmission to downloads in /volume1/downloads 

### Actual behavior
The  folder doesn't contain the files downloaded by Transmission, i suspect it use another folder.

### Steps to reproduce
_1._Add a torrent
_2._Check the folder

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
How can I access to the folder from DSM ? Thanks

**Comment by BenjV** [comment]
Check Transmission itself were it puts the downloads and correct it.
You most likely messed this up during installation of the package by trying to create a SubFolder which is not allowed so no folder at all is set in the config of Transmission.

**Comment by Nemrod7** [comment]
> Check Transmission itself were it puts the downloads and correct it.

<img width="349" alt="capture d ecran 2018-11-13 a 12 03 10" src="https://user-images.githubusercontent.com/9394310/48409459-30591a80-e73c-11e8-9696-c2cde5af16de.png">

**Comment by Nemrod7** [comment]
Transmission :
<img width="1652" alt="capture d ecran 2018-11-13 a 12 05 08" src="https://user-images.githubusercontent.com/9394310/48409628-a067a080-e73c-11e8-8056-3d5f17ff861a.png">


/Volume1/Downloads
<img width="1652" alt="capture d ecran 2018-11-13 a 12 05 26" src="https://user-images.githubusercontent.com/9394310/48409633-a493be00-e73c-11e8-8321-8c68a7c05cd2.png">

**Comment by Nemrod7** [comment]
So, I have no idea where the downloaded files are.

**Comment by BenjV** [comment]
You are messing up the capitals.
/volume1/downloads is a different location then /volume1/Downloads

**Comment by Nemrod7** [comment]
Ok, so I put /volume1/downloads instead of /volume1/Downloads, how can I know where the files are ? Thanks.

**Comment by BenjV** [comment]
They should be in /volume1/downloads but you cannot see that folder because it is not a Shared Folder

**Comment by Nemrod7** [comment]
Ok, can I check the folder and delete it to use the right one ?

**Comment by BenjV** [comment]
No, just do a rightclick on a torrent in Transmission and change the location to the correct folder.

**Comment by Nemrod7** [comment]
It's not workin, the folder is still empty,I guess I need to check permissions.

**Comment by BenjV** [comment]
I am sure but I think that Tansmission is storing the file in his own temp location until the are finished.

**Comment by Nemrod7** [comment]
Here is what I get :
<img width="1659" alt="capture d ecran 2018-11-13 a 12 54 15" src="https://user-images.githubusercontent.com/9394310/48411908-533afd00-e743-11e8-9942-2483e790a35d.png">

**Comment by Nemrod7** [comment]
Ok, I gave permission to sc-download, I saw to torrent then :
<img width="1659" alt="capture d ecran 2018-11-13 a 12 58 21" src="https://user-images.githubusercontent.com/9394310/48412133-060b5b00-e744-11e8-9658-a61b7e26b743.png">

**Comment by BenjV** [comment]
You have probably messed up your Capitals more often.

**Comment by Nemrod7** [comment]
Any idea on what to do to correct it please ?

**Comment by BenjV** [comment]
Is it still not working correctly now?

**Comment by Nemrod7** [comment]
I'm still missing something :
<img width="1651" alt="capture d ecran 2018-11-13 a 13 31 00" src="https://user-images.githubusercontent.com/9394310/48413587-75834980-e748-11e8-8f85-bdf675585adf.png">

**Comment by Nemrod7** [comment]
Any idea of where to check ? Thanks

**Comment by BenjV** [comment]
You have change the group permissions after the file already was created.
So set the permissions correct for those files with File Station.
Select file, right click, choose properties and then permissions.

**Comment by Nemrod7** [comment]
The files aren't created because Transmission doesn't have permission on /Volume1/Downloads

**Comment by BenjV** [comment]
You said you have given the group sc-download the correct permission on /volume1/Downloads
The hidden user which is running Transmission is part of that group so Transmission has permission there.

The problem is that the file already was created and Transmission most likely tries to move the file including the file permission which are wrong in this case.
I think this is becoming to complicated for you, so I would suggest to remove those torrents and start them new.
Or even better remove Transmission after you have removed the torrents and install Download Station

**Comment by Nemrod7** [comment]
I already deleted the files downloaded in /Volume1/downloads, what I'm trying to do is to download new files on /Volume1/Downloads. I have the permission issue since I changed the path.

I've searching the net I see that is is/were permission issues.

Why not, does the uninstall of the package will delete all files ?

Thanks

**Comment by Nemrod7** [comment]
> I already deleted the files downloaded in /Volume1/downloads, what I'm trying to do is to download new files on /Volume1/Downloads. I have the permission issue since I changed the path.

A friend a mine had the same issue.

**Comment by Nemrod7** [comment]
> Why not, does the uninstall of the package will delete all files ?

<img width="687" alt="capture d ecran 2018-11-14 a 15 41 22" src="https://user-images.githubusercontent.com/9394310/48489768-12ff7b80-e824-11e8-98c2-766d4352a85c.png">

Can you help me ?

**Comment by BenjV** [comment]
I use Sonarr, SickRage and Download Station and all are working fine together (and many, many others too).
And showing Linux permissions does not help at all.
Synology and also the current SynoCommunity are using ACL's for the permissions and not the Linux permisssion system.

**Comment by Nemrod7** [comment]
Like I said, I was asking for help to clean my mess...

**Comment by BenjV** [comment]
Ok the temporary location were Download Station an also Transmission store there files is /volume1/@download.
So you can stop Transmission and/or Download Station, remove al numbered subfolders, then remove the wrong folder (the one starting with a lower capital) and then start the application again.

**Comment by Nemrod7** [comment]
You suggested that I use Download Station instead of Transmission and that seems wise to me, considering the fact that I am just an "end user".

So I have to delete the **d**ownloads folder, which I created by mistake, and its content and set the permissions in DSM for Download Station

**Comment by BenjV** [comment]
No not Download Station, just the group sc-download.

**Comment by Nemrod7** [comment]
Ok, thanks

**Comment by Nemrod7** [comment]
Can you please tell me how to suppress the download folder is created by mistake ? I guess there is only on : /Volume1/download ? Thanks again !

**Comment by BenjV** [comment]
You can delete it in the control panel (click on "shard folder")

**Comment by Nemrod7** [comment]
Thanks for your answer, I don't want to to delete this shared folder, used by DS thanks to your help, but the folder created by mistake during Transmission installation, when I messed up with **d**ownloads instead of **D**ownloads.

**Comment by BenjV** [comment]
Is that folder not a shared folder?
If not then you have to login with putty, go to /volume1 (cd /volume1) and remove that folder (rm -r /downloads)

**Comment by ymartin59** [comment]
@Nemrod7 May you please report content from /var/packages/transmision/target/var/transmission_installer.log

So I guess installer should check path is a Share Folder in preinst instead of only directory is present...

**Comment by hgy59** [comment]
@Nemrod7 is this still an open issue for you?

**Comment by publicarray** [comment]
@hgy59 @Nemrod7 there hasn't been any activity here for years. Closing as stale. Please reopen or create a new issue if you still require help.
