### ISSUE TITLE
Sonarr : Download Station isn't grabbing files from the download shared folder 

### ISSUE THREAD

**Issue by Nemrod7** [SynoCommunity/spksrc#3517]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Sonarr
_Package Version:_v20180303-13

_NAS Model:_DS916+
_NAS Architecture:_braswell (x64)
_DSM version:_DSM 6.2.1-23824 Update 1

### Expected behavior
With Sonarr, the file is downloaded by Download station on the download shared folder, moved to the Video shared folder and then the download history is cleared.

### Actual behavior
Files are downloaded, but not moved to the Video shared folder. Sonarr display the following error message :"Import failed, path does not exist or is not accessible by Sonarr: /volume1/Downloads/Series/The.Flash.2014.S05E04.News.Flash.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg" but the file is downloaded.

### Steps to reproduce
_1._Let Sonarr check if a file available for download and download it

#### Package log
http://pasted.co/c888d4b4

**Comment by Nemrod7** [comment]
Hi,

I've been trying to make it work for weeks now, does the maintainer of the package can help ?

Thanks

**Comment by BenjV** [comment]
First of all you don't seem to understand what the function of those application are and how they should work.
Sonarr is scanning the internet for wanted video's.
If found it will download the .torrent and give this to the download applicatien in this cas DownloadStation.
Then DownloadStation downloads the video to the download folder.
Sonarr is scanning every minute or so that folder and will pickup any video it find there and will match it with the one Sonarr wants to have and if found copy (or move) it to its final destination.

So a question like yours ( "Let Sonarr check if a file available for download and download it") is silly.
So you first have to check if Download Station has finised downloading the file, because before that it won't appear in the Downloads folder

**Comment by Nemrod7** [comment]
> First of all you don't seem to understand what the function of those application are and how they should work.
> Sonarr is scanning the internet for wanted video's.
> If found it will download the .torrent and give this to the download applicatien in this cas DownloadStation.
> Then DownloadStation downloads the video to the download folder.
> Sonarr is scanning every minute or so that folder and will pickup any video it find there and will match it with the one Sonarr wants to have and if found copy (or move) it to its final destination.
> 
> So a question like yours ( "Let Sonarr check if a file available for download and download it") is silly.
> So you first have to check if Download Station has finised downloading the file, because before that it won't appear in the Downloads folder

I'm using Sonarr for years now so I know how it works.

**Comment by Nemrod7** [comment]
> > First of all you don't seem to understand what the function of those application are and how they should work.
> > Sonarr is scanning the internet for wanted video's.
> > If found it will download the .torrent and give this to the download applicatien in this cas DownloadStation.
> > Then DownloadStation downloads the video to the download folder.
> > Sonarr is scanning every minute or so that folder and will pickup any video it find there and will match it with the one Sonarr wants to have and if found copy (or move) it to its final destination.
> > So a question like yours ( "Let Sonarr check if a file available for download and download it") is silly.
> > So you first have to check if Download Station has finised downloading the file, because before that it won't appear in the Downloads folder
> 
> I'm using Sonarr for years now so I know how it works.

It's a short way to describe what Sonarr does, like you previously wrote it.

**Comment by BenjV** [comment]
Ok good luck then.

**Comment by Nemrod7** [comment]
> First of all you don't seem to understand what the function of those application are and how they should work.
> Sonarr is scanning the internet for wanted video's.
> If found it will download the .torrent and give this to the download applicatien in this cas DownloadStation.
> Then DownloadStation downloads the video to the download folder.
> Sonarr is scanning every minute or so that folder and will pickup any video it find there and will match it with the one Sonarr wants to have and if found copy (or move) it to its final destination.
> 
> So a question like yours ( "Let Sonarr check if a file available for download and download it") is silly.
> So you first have to check if Download Station has finised downloading the file, because before that it won't appear in the Downloads folder

Yes they are downloaded, but not "moved" to the video shared.

**Comment by Nemrod7** [comment]
> Ok good luck then.

I put the error message and the log, I can also put a screenshot of ht in the download shared ?

**Comment by Nemrod7** [comment]
FYI : "Import failed, path does not exist or is not accessible by Sonarr: /volume1/Downloads/Series/The.Flash.2014.S05E04.News.Flash.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg" but the file is downloaded.

**Comment by Nemrod7** [comment]
I used to use Sonarr (Synology) and Transmission (macOS). It worked as you describe it, the downloaded files were transferred to another directory and then deleted from the download directory.

For quite some time now I've been trying to use Download Station, but I have this problem. 

I think so, but you understand that I'm a novice, that this is an permission problem with DSM..

I asked for help on the official Sonarr forum which, after analyzing the log, sends me here.

Could you tell me how to set up permissions in DSM? Thank you.

**Comment by BenjV** [comment]
I already told you that.
1. Give the group sc-download permissions on the /volume1/Downloads folder.
2. Use FilesStation to set the correct permission for the group sc-download for the existing Folder, Subfolder and Files(so for everything in the folder /volume1/Downloads

**Comment by Nemrod7** [comment]
My bad, I didn't understand, it's all new to me

Here is what I have

Point 1:
<img width="773" alt="capture d ecran 2018-11-14 a 16 53 23" src="https://user-images.githubusercontent.com/9394310/48494441-2ca5c080-e82e-11e8-9af8-a07a6c72056a.png">

Point 2
<img width="769" alt="capture d ecran 2018-11-14 a 16 55 17" src="https://user-images.githubusercontent.com/9394310/48494448-2fa0b100-e82e-11e8-9753-d15cd3f66dd1.png">

**Comment by BenjV** [comment]
No not permissions for FileStation .
You must use FileStation to set permissions for existings folder.

Start FileStation
Select the folder "Downloads"
Right Click on it and select properties.
Click on permissions.
Select sc-download (it should be there and have read/write permisssions)
Find in the corner left below a tickbox which says "Apply this to this folder, subfolder and files.
Tick that box en click on ok.

**Comment by Nemrod7** [comment]
Thanks
> Find in the corner left below a tickbox which says "Apply this to this folder, subfolder and files.
> Tick that box en click on ok.

I don't see the tickbox you mentionned :
<img width="747" alt="capture d ecran 2018-11-14 a 19 01 40" src="https://user-images.githubusercontent.com/9394310/48502485-f1ac8880-e83f-11e8-8188-19f130d82274.png">

**Comment by BenjV** [comment]
Aha, now I am getting the problem.
You have an old Share created pre DSM 6.

It has to be converted to support ACL's
Read this wiki, especially the last part about hou to convert the Share to ACL support.
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by Nemrod7** [comment]
Finally, it's working, many thanks !!!

Question, is there any interest to convert every shared, even the one not used by sc-download ?

**Comment by BenjV** [comment]
I have done that myself for all my shares except one.
That one I have saved to be able to test strange situaties like you encountered.
All packages from the SynoCommunity that use shares need shares that support ACL's

In my opinion Synology has made the decision to do more and more with ACL's and less with Linux permissions, so I would say yes convert all shares.

**Comment by Nemrod7** [comment]
Ok, tanks for you advice.

**Comment by BenjV** [comment]
Your'e welcome, glad to be able to help.

**Comment by Nemrod7** [comment]
Indeed you helped me, I couldn't have done it without you !

**Comment by ymartin59** [comment]
Sounds fixed as far as I understand.
