### ISSUE TITLE
Arp-scan for synology?

### ISSUE THREAD

**Issue by mav1** [SynoCommunity/spksrc#3519]
There is a good utility in Linux called arp-scan. It shows computers in networks (ip, hostname, MAC). Is it possible to build spk with arp-scan? It might be very helpful.

**Comment by publicarray** [comment]
Would nmap be good enough? There already are make files that compile it see https://github.com/SynoCommunity/spksrc/pull/3267. However we are trying to create a bundled package for command line utilities

**Comment by publicarray** [comment]
synogear installs nmap too -> https://github.com/SynoCommunity/spksrc/wiki/FAQ-synogear

**Comment by mav1** [comment]
As for me, arp-scan shows network elements in short and clear format

**Comment by xaozai** [comment]
nmap is also present here: https://synocommunity.com/package/synocli-net
