### ISSUE TITLE
Port fdupes to ARM platforms (armada38x)

### ISSUE THREAD

**Issue by obourdon** [SynoCommunity/spksrc#3525]
### Setup
_Package Name:_ fdupes
_Package Version:_

_NAS Model:_ DS218j
_NAS Architecture:_ armada38x
_DSM version:_ 6.1/6.2

### Expected behavior
fdupes package should compile

### Actual behavior
error when compiling fdupes

### Steps to reproduce
_1._ use docker dev env
_2._ cd spk/fdupes && make arch-armanda38x

#### Other logs
_E.g. `command output`_
```
/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory
 # include <gnu/stubs-soft.h>
                             ^
compilation terminated.
```

**Comment by ymartin59** [comment]
There is no missing file in armada38x toolchain. fdupes is a old beta package that has never been ported to ARM platforms: https://synocommunity.com/package/fdupes
Reference: https://stackoverflow.com/questions/49139125/fatal-error-gnu-stubs-soft-h-no-such-file-or-directory

**Comment by ymartin59** [comment]
I guess you have done an effort to "look at" (I do not dare to say "read") StackOverflow reference...
gcc is invoked with improper arguments for ARM target.
Not a problem of toolchain but fdupes make statements.
Period.

**Comment by BenjV** [comment]
I agree

**Comment by obourdon** [comment]
@ymartin59 yes I did read it and think I understood its contents but as stated in my previous comment it is not because adding compilation flag(s) makes the issue go away means that there is nothing wrong in all the other cases. Furthermore comparing this toolchain with the others (some also ARM based) where the issue is not present tends to confirm this. But may be I am way too biased due to my past experiences ;-)

**Comment by ymartin59** [comment]
OK why not, but that is not the right place to complain about it. Toolchains are provided by Synology... So post of their forum https://forum.synology.com/ and/or open a support request...

**Comment by obourdon** [comment]
Done [https://community.synology.com/forum/14/post/121082](https://community.synology.com/forum/14/post/121082)
