### ISSUE TITLE
New Couchpotato 3.01 for Synology DSM6.1+

### ISSUE THREAD

**Issue by bchocotoff** [SynoCommunity/spksrc#3532]
**Request for latest CouchPotato version**

I was hoping someone could compile the latest couchpotato version? It has a complete new look and minimal upgrades. 

### Setup
_Package Name:_ couchpotato
_Package Version:_ 3.01 from 31st of Aug 2018

_NAS Model:_ DS918+
_NAS Architecture:_ ARM
_DSM version:_ 6.1

Expected behavior:
Couchpotato is not finding the latest update already released. Seems that there is no new SPK created for it yet.

### Actual behavior:
Couchpotato is not finding the latest update already released. Seems that there is no new SPK created for it yet.

### Steps to reproduce
- Open Couchpotato
- Settings > About > Check for updates

**Comment by BenjV** [comment]
Has nothing to do with the SPK.
If it does not update it is an internal CouchPotato issue not an package issue.

**Comment by mreid-tt** [comment]
@bchocotoff... checking on some older issues... is this still an ongoing concern or can this ticket be closed?

**Comment by mreid-tt** [comment]
Based on the readme at https://couchpota.to/:

> CouchPotato is not maintained anymore
> Please use any of the alternatives like [Radarr](https://synocommunity.com/package/radarr)

As such, this ticket will be closed.
