### ISSUE TITLE
nc

### ISSUE THREAD

**Issue by expert-geeks** [SynoCommunity/spksrc#3534]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_
_Package Version:_

_NAS Model:_
_NAS Architecture:_
_DSM version:_

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
Really. You are not able to send more that two keystrokes ?

**Comment by expert-geeks** [comment]
er.. I don't remember submitting this and if I had I'd have provided a lot more information!! I don't even recall the last time I used netcat. No idea what happened here. I'll close this issue ?!
