### ISSUE TITLE
[Package Request] Bazarr

### ISSUE THREAD

**Issue by Shinoli** [SynoCommunity/spksrc#3535]
Name: Bazarr
Description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements. You define your preferences by TV show or movies and Bazarr takes care of everything for you.

Website: https://github.com/morpheus65535/bazarr
Source code: https://github.com/morpheus65535/bazarr
License: GNU GPL v3

**Comment by morpheus65535** [comment]
I'm the developer of Bazarr. If you need help during the packaging process, just ask! :-)

**Comment by G1zm0** [comment]
I fully support this Package Request 👍

**Comment by deepfriedmind** [comment]
It would make a lovely addition.

**Comment by mesquitafmr** [comment]
I support this package request too!

**Comment by iap3tos** [comment]
This is a much needed package for Synology users that don't have docker

**Comment by deepfriedmind** [comment]
I just gave in finally and installed it via Docker, which took all but 10 minutes, so I'd recommend that approach rather than waiting for this to happen.

**Comment by smaarn** [comment]
> I'm the developer of Bazarr. If you need help during the packaging process, just ask! :-)

Come to think of it: a nice feature would be to be able to ensure that when killing the python bazarr.py script the underlying python process gets killed (or shutdown) :).
I currently need to do a curl on the shutdown endpoint to kill it smoothly (well...) :)

**Comment by hgy59** [comment]
please use #3788 for further conversation, locking this...

**Comment by publicarray** [comment]
This has  been addressed by #4916
