### ISSUE TITLE
Status of Mosh Support?

### ISSUE THREAD

**Issue by marlowe310** [SynoCommunity/spksrc#3538]
Just wondering if there's a package currently to install Mosh on Synology -- I see a number of references to it being near completion late last year, but can't find anything about how it turned out. Thanks much for any info!

**Comment by ymartin59** [comment]
mosh is now available in synocli-net: https://synocommunity.com/package/synocli-net

**Comment by sn00pster** [comment]
Sorry, I’ve just got mosh up and running on the Synology and can connect to it via blink with mosh, but, it’s not showing detached sessions message.

Having a quick look around the code it would appear that this is based on the ifdef “HAVE_UTMPX_H”.  

Is this not available on Synology or was it just not compiled with this option?

Great to have mosh working though! Thanks for the effort.

**Comment by sn00pster** [comment]
Ok, so with a lot of hackery (I know nothing about the build system for spksrc) I managed to get libutempter built and mosh using it and linked to it.

However, I still don’t see the message about detached sessions, so there’s obviously something else not working to do with this. :(

**Comment by ymartin59** [comment]
Please open a dedicated issue about it - and do not hesitate to submit a PR with your changes. I am not a mosh user myself, I have simply included mosh PR created by another contributor.
