### ISSUE TITLE
Jackett support for DS418Play - DSM 6.2.1 Apollolake

### ISSUE THREAD

**Issue by TotteAnnerbrink** [SynoCommunity/spksrc#3539]
### Setup
_Package Name:_ Jackett
_Package Version:_ 0.10.492

_NAS Model:_ DS418Play
_NAS Architecture:_ Apollolake
_DSM version:_ 6.2.1-23824 Update 1

### Expected behavior
Find Jackett in the package center for architecture Apollolake.

### Actual behavior
Jackett is not visible in Synocommunity package center.

**Comment by m4tt075** [comment]
There is an apollolake version available:
https://synocommunity.com/package/jackett#
The 5.0 should work with 6.2 as well. After installing Jackett you can use the internal upgrade function and be up-to-date.

**Comment by TotteAnnerbrink** [comment]
Thank you. That worked wonderfully!
