### ISSUE TITLE
Request: Darkstat on apollolake (x64)

### ISSUE THREAD

**Issue by CrowMash** [SynoCommunity/spksrc#3541]
Hello to the community! First, thank you all for the hard work you put on this project! I would like to know if a version of Darkstat on apollolake was planned?

Thanks in advance!

**Comment by oriddlero** [comment]
This.  Would love an apollolake version.  I just migrated and i miss it!

**Comment by oriddlero** [comment]
Please?

**Comment by oriddlero** [comment]
Here you go:  http://www.jadahl.com/drivers_6.2/?arch=apollolake#

**Comment by hgy59** [comment]
see #5224
