### ISSUE TITLE
Home Assistant - HomeKit - Failed building wheel for gmpy2

### ISSUE THREAD

**Issue by slavkobrzeg** [SynoCommunity/spksrc#3543]
Unable to install package homekit==0.10: Failed building wheel for gmpy2
  Failed building wheel for py25519
Command "/volume1/@appstore/homeassistant/env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-2yedr0w2/gmpy2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4nza2eer/install-record.txt --single-version-externally-managed --compile --install-headers /volume1/@appstore/homeassistant/env/include/site/python3.5/gmpy2" failed with error code 1 in /tmp/pip-install-2yedr0w2/gmpy2/

I installed the Home Assistant beta package and everything was fine since when I wanted to turn on homekit component and also enable homekit for discover component. Did you see the same issue? 

### Setup
Package Name: Home Assistant
Package Version: 0.82.1-2

NAS Model: DS216j
NAS Architecture: MARVELL Armada 385 88F6820
DSM version:  DSM 6.2.1-23824 Update 1
--

### Expected behavior
homekit==0.10 should be installed

### Actual behavior
error

### Steps to reproduce
1. install Home Assistnat Beta
2. add into discovery component
enable:
  -homekit

#### Package log
2018-12-09 01:42:26 ERROR (Thread-10) [homeassistant.util.package] Unable to install package homekit==0.10: Failed building wheel for gmpy2
  Failed building wheel for py25519
Command "/volume1/@appstore/homeassistant/env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-2yedr0w2/gmpy2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4nza2eer/install-record.txt --single-version-externally-managed --compile --install-headers /volume1/@appstore/homeassistant/env/include/site/python3.5/gmpy2" failed with error code 1 in /tmp/pip-install-2yedr0w2/gmpy2/
2018-12-09 01:42:26 ERROR (MainThread) [homeassistant.requirements] Not initializing homekit_controller because could not install requirement homekit==0.10
2018-12-09 01:42:26 ERROR (MainThread) [homeassistant.setup] Setup failed for homekit_controller: Could not install all requirements.

**Comment by ymartin59** [comment]
Related to #3462

**Comment by slavkobrzeg** [comment]
I'm sorry but I don't understand where in the #3462 I can see the solution for this problem, but I'm sure it's my lack of knowledge. 
Could you point me the correct explanation there?

**Comment by ymartin59** [comment]
Sorry - I got sick so I have been stopped in publishing additional commits to that PR to support pure-python module installation. By the way, there is no hope to compile native dependencies in DSM

**Comment by bverkron** [comment]
Any update on this? I'm also running into the error described here, although I'm running on Windows 7 in a python virtual environment
```
2019-01-04 19:33:13 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package homekit==0.10: Failed building wheel for py25519

  Failed building wheel for gmpy2
```

**Comment by ymartin59** [comment]
This issue only concerns support on Synology DSM. In your case, you should request support for windows on forum: https://community.home-assistant.io/

**Comment by hgy59** [comment]
@slavkobrzeg we are about to redesign the wheel build. As in #4980 we have issues with ARMv5 archs (i.e. 88f682x or 88f6281 and 88f6280).
Do you still have your DS216j? I so, we would be very happy when you can ssh into your DS216j and report the output of the command `uname -m`. This helps us to correctly name the cross compiled python wheels.
Thanks in advance.
