### ISSUE TITLE
Problem - Compile Python rtd1296-6.1 ̶a̶a̶r̶c̶h̶6̶4̶-̶6̶.̶1̶

### ISSUE THREAD

**Issue by KosakAlmighty** [SynoCommunity/spksrc#3546]
Hi guys,
I tried to compile Python for new architectures, using aarch64 toolchain.

But after couple minutes it ends on this: 

```
===>  Processing dependencies of cffi
make[3]: Entering directory '/spksrc/spksrc/cross/pycparser'
make[3]: Leaving directory '/spksrc/spksrc/cross/pycparser'
make[3]: Entering directory '/spksrc/spksrc/cross/libffi'
===>  Configuring for libffi

<skiped part, some configuration is going here>

checking build system type... i686-pc-linux-gnu
checking host system type... aarch64-unknown-linux-gnueabi
checking target system type... aarch64-unknown-linux-gnueabi
continue configure in default builddir "./aarch64-unknown-linux-gnueabi"
....exec /bin/bash .././configure "--srcdir=.." "--enable-builddir=aarch64-unknown-linux-gnueabi" "linux
gnueabi"
.././configure: line 2356: config.log: Invalid argument
.././configure: line 2366: config.log: Invalid argument
../../mk/spksrc.configure.mk:50: recipe for target 'configure_target' failed
make[3]: *** [configure_target] Error 1
make[3]: Leaving directory '/spksrc/spksrc/cross/libffi'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[2]: *** [depend_target] Error 2
make[2]: Leaving directory '/spksrc/spksrc/cross/cffi'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory '/spksrc/spksrc/spk/python'
../../mk/spksrc.spk.mk:452: recipe for target 'arch-aarch64-6.1' failed
make: [arch-aarch64-6.1] Error 2 (ignored)
```

So the problem is seems to be with libffi, but even after couple hours of digging I wasn't able to find any error. 
```
.././configure: line 2356: config.log: Invalid argument
.././configure: line 2366: config.log: Invalid argument
```

I took look in configure file for libffi and at these lines is this: 
```
2356 cat >config.log <<_ACEOF
2357 This file contains any messages produced by compilers while
2358 running configure, to aid debugging if configure makes a mistake.
2359
2360 It was created by libffi $as_me 3.2.1, which was
2361 generated by GNU Autoconf 2.69.  Invocation command line was
2362
2363  $ $0 $@
2364
2365 _ACEOF
2366 exec 5>>config.log
```

So another step was take look in config.log, in whole log file there is any mention of any error.

I'm really newbie in this, so if you could just show me way, where or how to find error why it stopped, I would really appreciate it.

[config.log](https://github.com/SynoCommunity/spksrc/files/2677684/config.log)

[configure.txt](https://github.com/SynoCommunity/spksrc/files/2677689/configure.txt)

**Comment by BenjV** [comment]
Why are you triying to do this?
There is a python package for this architecture available.
https://packages.synocommunity.com/python/19/python.v19.f4458[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-grantley-kvmx64-x86-x86_64].spk

**Comment by KosakAlmighty** [comment]
Well, oh. I see I misunderstand in #3477, that this toolchain is also compatible with armada37xx. 
In that case I will try different tool chain.

**Comment by retrography** [comment]
@BenjV The precompiled package is not available for aarch64 and rtd1296 anymore. This has broken many other packages for me. I am also struggling with compiling it.

**Comment by BenjV** [comment]
I know, my mistake I though he was looking for the x64 architecture.

**Comment by ymartin59** [comment]
Package no longer builds because of cross-side effects of python3 updates.
I am working on full python 2.7 updates and related applications because of vulnerability reports on requests and other modules

**Comment by ymartin59** [comment]
But there is a risk all python2 applications have to be updated and published again too

**Comment by ymartin59** [comment]
You should find 2.7.14 for both rtd1296 and armada37xx in repository

**Comment by KosakAlmighty** [comment]
I can confirm that works, thank you sir.
