### ISSUE TITLE
Rutorrent not showing up in DS1819+

### ISSUE THREAD

**Issue by sunbiker** [SynoCommunity/spksrc#3547]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Rutorrent
_Package Version:_ruTorrent v3.7-8

_NAS Model:_Ds 1819+
_NAS Architecture:_Denverton INTEL Atom C3538
_DSM version:_DSM 6.2.1-23824 Update 2

### Expected behavior
Change from 1817+ to 1819+ and Rutorrent is not working anymore, if i deinstall there is not showing up any rutorrent package

```

**Comment by ymartin59** [comment]
rutorrent has not been upgraded for DSM 6 support yet...

**Comment by bolhaskutya** [comment]
Yeah, same here. It is really sad that nobody updated the package. I'm on DS918+.

**Comment by th0ma7** [comment]
New and update to `rutorrent` version 3.10 uploaded on https://synocommunity.com/package/rutorrent
