### ISSUE TITLE
Roundcube not accessible after fresh install

### ISSUE THREAD

**Issue by The-H23** [SynoCommunity/spksrc#3549]
### Setup
_Package Name:_ Roundcube Webmail
_Package Version:_ 1.1.4-4

_NAS Model:_ DS918+
_NAS Architecture:_
_DSM version:_ DSM 6.2.1-23824 Update 2

### Expected behavior
The Roundcube app is accessible after installing the package with Package Center.

### Actual behavior
During the install process I got few questions asked about mariadb and answered that. The installation went further and finally seemed fine. No error messages.  But after the click on the newly created Roundcube icon my box redirects me from http://diskstation/roundcube back to http://diskstation:5000.

I than thought Webstation is a missing dependency nowadays and installed it. But I'm unable to set /volume1/@appstore/roundcube/share/roundcube as a document root in Webstation. I guess it's  because it's not a shared folder. 

How I'm supposed to reach my installed roundcube app for initial configuration? 

I'm on a vanilla DSM with no additional packages installed.

### Steps to reproduce
_1._ Install Roundcube Webmail from SynoCommunity
_2._ Click at the roundcube icon
_3._ get redirect to http://diskstation:5000

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
unfortunately there are none
```

**Comment by ymartin59** [comment]
Package requires update and rework to run properly on DSM 6. No plan yet for that one.

**Comment by TheeSamSquamch** [comment]
Package Name: Roundcube Webmail
Package Version: 1.1.4-4

I appear to have the above issue.

Installed on DS918+ 6.2.2-24922 Update 4.

Redirected to DSM page after install.
