### ISSUE TITLE
Cross compile sqlite

### ISSUE THREAD

**Issue by iherbak** [SynoCommunity/spksrc#3553]
Hi! 

Pulled down the docker image and started. 
Tried to cross compile sqlite for arch-northstarplus but at the sqlite package it says: 
Libtool library used but 'LIBTOOL' is undefined.

What is missing? I thought what is already inside is compiling without any additional steps.

Thanks in advance,

**Comment by cytec** [comment]
have you tried `sudo apt-get install libtool` ?

most of the software included compiles, some may need additional packages to be installed, also things might break... sqlite isn't a package that has to be compiled often...

**Comment by iherbak** [comment]
Hi thanks for the response.
Under the docker there is no sudo, however the apt-get install says the libtool is the newest.
Also i tried to ./configure & make & make install the package which went fine.
But when i start the process inside the /spksrc/cross/sqlite with make arch-northstarplus it brakes

**Comment by iherbak** [comment]
Hi! Solved the issue. I just wiped out docker and fired up a VM with debian. All the strange behaviors disappeared. I successfully cross compiled Minidlna and replaced the media server. No more issue with up-to-date video list :)
