### ISSUE TITLE
uMurmur for RTD1296

### ISSUE THREAD

**Issue by papptallriik** [SynoCommunity/spksrc#3554]
Hello! I'm totally new to GitHub and not sure if I'm doing this right, but I'm trying my best.

I have a DS418 and can't install uMurmur because my architecture doesn't seem to be supported. Can this be fixed/added somehow?

### Setup
_Package Name:_ uMurmur
_Package Version:_ ?

_NAS Model:_ DS418
_NAS Architecture:_ RTD1296SoC
_DSM version:_ 6.2.1-23824 Update 2

### Expected behavior
A version for this architecture

### Actual behavior
...not found ;-)

**Comment by ymartin59** [comment]
That is right. New architectures come, but at the moment, we only build and publish packages "on demand". Should come soon

**Comment by ymartin59** [comment]
Just published
