### ISSUE TITLE
DNS on wrong port

### ISSUE THREAD

**Issue by Crazee** [SynoCommunity/spksrc#3558]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_dnscrypt-proxy
_Package Version:_2.0.19

_NAS Model:_DS218+
_NAS Architecture:_
_DSM version:_

### Expected behavior
should work as a DNS proxy endpoint

### Actual behavior
Serves DNS on a non-standard port (10053) which is useless.

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
According to https://github.com/SynoCommunity/spksrc/wiki/FAQ-DNSCrypt-proxy custom port is not an issue when DHCP announces properly DNS server to network devices. @publicarray What is your opinion about it?

**Comment by publicarray** [comment]
Ok let me explain the algorithm. 

The start up script from dncrypt-proxy checks if the port 53 (DNS) is already in use or if dnsmasq is running. If this is the case fallback to port 10053 and than tell dnsmasq to forward DNS queries to dnscrypt-proxy. If not use port 53

This is done to as not to break normal DHCP operation and other Synology’s features e.g. web filtering.

If you feel that you want a different port just open up the GUI interface and change the `listen_addresses` in the configuration file. But be warned that it is likely that dnscrypt-proxy wont start if the port is already in use.

**Comment by publicarray** [comment]
@ymartin59 since there is no response can we close this?

**Comment by ymartin59** [comment]
I agree, yes close it. Wiki page is enough IMO.

**Comment by publicarray** [comment]
@ymartin59 hm I can't close this issue 🙊 but maybe you can 😄
