### ISSUE TITLE
Medusa can't get locale settings

### ISSUE THREAD

**Issue by neojoe666** [SynoCommunity/spksrc#3563]
### Setup
_Package Name:_ Sickbeard custom
_Package Version:_latest

_NAS Model:_
_NAS Architecture:_DS213j
_DSM version:_DSM 6.2.1-23824 Update 2

Medusa should get the locale settings with the user sc-sickbeard-custom
If I execute it with root it works:
sudo -u "root" /volume1/@appstore/sickbeard-custom/env/bin/python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --daemon --pidfile /volume1/@appstore/sickbeard-custom/var/sickbeard-custom.pid --config /volume1/@appstore/sickbeard-custom/var/config.ini --datadir /volume1/@appstore/sickbeard-custom/var/

See details on an issue I opened at Medusa:
https://github.com/pymedusa/Medusa/issues/5930

**Comment by BenjV** [comment]
It is a Medusa problem.
Try this command on the commandline to see if the locale are set for the user which is running the applicatie e.g. "sc-sickbear-custom"

[code] sudo -u sc-sickbeard-custom sh -c locale[/code]

Most likely the Medusa is not using the correct username which is running the application to get the locale.
They should get te correct username the application is running under.
Something like this:
[code=python]
from getpass import getuser
UserName = getuser()
[/code]

**Comment by neojoe666** [comment]
here is what the command line returns:
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8

**Comment by BenjV** [comment]
So you see the locale are correctly set by DSM for this user and so the problem is Medusa and not the package.
So you can close this issue and report an issue at the Medusa github.

**Comment by neojoe666** [comment]
Thanks for your help.
Unfortunately, the Medusa team doesn't want to hear about it...

**Comment by BenjV** [comment]
Switch to SickChill, that works fine.
You can use the package I created for that.
You can download it here and do a manual install.
https://github.com/BenjV/SYNO-packages/blob/master/SickChill%20noarch%20V1.1.spk

**Comment by neojoe666** [comment]
I switched from sickrage to medusa last year. It takes a lot of time to make everything works smoothly after the migration...

**Comment by neojoe666** [comment]
@BenjV Is it possible to import a Medusa database on sickchill? When I did it last year from sickrage to Medusa, it didn't work.

**Comment by BenjV** [comment]
No that is not possible anymore.
When they started as a fork it was but in the meantime they changed the layout.
