### ISSUE TITLE
Build fails with Docker image on MacOS

### ISSUE THREAD

**Issue by adrianblakey** [SynoCommunity/spksrc#3570]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ git
_Package Version:_

_NAS Model:_ ds418
_NAS Architecture:_ rtd1296
_DSM version:_

### Expected behavior
make arch-rtd1296
Make succeeds

### Steps to reproduce
_1._ Install docker.
_2._ Run docker environment
_3._ Git clone the tree
_4._ cd spk/git
_5._ make arch-rtd1296

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
root@f6dcda86815a:/spksrc/spksrc/spk/git# make arch-rtd1296
===>  Building package for arch rtd1296
make[1]: Entering directory '/spksrc/spksrc/spk/git'
===>  Set up toolchain 
===>    Extracting for syno-rtd1296
tar -xpf /spksrc/spksrc/toolchains/syno-rtd1296-6.1/../../distrib/toolchains/6.1/rtd1296-gcc494_glibc220_armv8-GPL.txz -C /spksrc/spksrc/toolchains/syno-rtd1296-6.1/work 
tar: aarch64-unknown-linux-gnueabi/build.log.bz2: Cannot open: Permission denied
tar: aarch64-unknown-linux-gnueabi/aarch64-unknown-linux-gnueabi: Cannot mkdir: Permission denied
tar: aarch64-unknown-linux-gnueabi/aarch64-unknown-linux-gnueabi: Cannot mkdir: Permission denied
...
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
There is no need to build Git as it is published:
- https://synocommunity.com/package/git
- https://packages.synocommunity.com/git/11/git.v11.f15047[rtd1296-armada37xx-aarch64].spk

By the way, docker on MacOS is known to have such permission troubles. No plan to investigate further, other MacOS users decided to run a Linux VM and docker over it.

**Comment by adrianblakey** [comment]
I'll give it a shot on linux. The git tree was just an example - I tried transmission first - same issue. Plan is to make sure I have a working build before adding my own code ...

**Comment by adrianblakey** [comment]
btw - this works just fine - make arch-88f6281make arch-88f6281

no permission issues at all.

**Comment by BenjV** [comment]
Surely you are realizing that the permissions issue is a docker issue?

**Comment by adrianblakey** [comment]
This is the result of running the same test on a RHEL linux - docker CE.

$ docker pull synocommunity/spksrc                                                                                                     
Using default tag: latest                                                                                                                                   
latest: Pulling from synocommunity/spksrc                                                                                                                   
ff144d3c0ab1: Pull complete                                                                                                                                 
a6429e90a8e7: Pull complete                                                                                                                                 
5a1b738ba18b: Pull complete                                                                                                                                 
be42538d7299: Pull complete                                                                                                                                 
0c929307a750: Pull complete                                                                                                                                 
a7db208018b5: Pull complete                                                                                                                                 
7095ea3d03f9: Pull complete                                                                                                                                 
Digest: sha256:3b1be74859df976c927e6b5834ed2ec9f35eea36599c2272e50849cd703b9515                                                                             
Status: Downloaded newer image for synocommunity/spksrc:latest                                                                                              
$ mkdir spksrc                                                                                                                         
$ docker run -it -v ~/spksrc:/spksrc:rw synocommunity/spksrc /bin/bash                                                                 
root@ffdba332b86d:/spksrc# git clone https://github.com/SynoCommunity/spksrc.git                                                                            
Cloning into 'spksrc'...                                                                                                                                    
remote: Enumerating objects: 61, done.                                                                                                                      
remote: Counting objects: 100% (61/61), done.                                                                                                               
remote: Compressing objects: 100% (40/40), done.                                                                                                            
remote: Total 29314 (delta 27), reused 45 (delta 20), pack-reused 29253                                                                                     
Receiving objects: 100% (29314/29314), 12.22 MiB | 2.88 MiB/s, done.                                                                                        
Resolving deltas: 100% (15186/15186), done.                                                                                                                 
Checking connectivity... done.                                                                                                                              
root@ffdba332b86d:/spksrc# cd spksrc/                                                                                                                       
root@ffdba332b86d:/spksrc/spksrc# make setup                                                                                                                
k/transmissionCreating local configuration "local.mk"...                                                                                                    
Setting default toolchain version to DSM-6.1                                                                                                                
root@ffdba332b86d:/spksrc/spksrc# cd spk/transmission                                                                                                       
root@ffdba332b86d:/spksrc/spksrc/spk/transmission# make arch-rtd296                                                                                         
===>  Building package for arch rtd296                                                                                                                      
make[1]: Entering directory '/spksrc/spksrc/spk/transmission'                                                                                               
===>  Set up toolchain                                                                                                                                      
make[2]: Entering directory '/spksrc/spksrc/spk/transmission'                                                                                               
make[2]: *** ../../toolchains/syno-rtd296-6.1: No such file or directory.  Stop.                                                                            
make[2]: Leaving directory '/spksrc/spksrc/spk/transmission'                                                                                                
/spksrc/spksrc/spk/transmission/work-rtd296-6.1/tc_vars.mk:1: *** An error occured while setting up the toolchain, please check the messages above.  Stop.  
make[1]: Leaving directory '/spksrc/spksrc/spk/transmission'                                                                                                
../../mk/spksrc.spk.mk:452: recipe for target 'arch-rtd296' failed                                                                                          
make: [arch-rtd296] Error 2 (ignored)                                                                                                                       
root@ffdba332b86d:/spksrc/spksrc/spk/transmission#  make arch-88f6281
===>  Building package for arch 88f6281
make[1]: Entering directory '/spksrc/spksrc/spk/transmission'
===>  Set up toolchain
===>    Downloading files for syno-88f6281
wget https://sourceforge.net/projects/dsgpl/files/DSM%206.1%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32/6281-gcc464_glibc215_88f6281-GPL.txz
2019-01-10 00:10:04 URL:https://pilotfiber.dl.sourceforge.net/project/dsgpl/DSM%206.1%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32/6281-gcc464_glibc215_88f6281-GPL.txz [35293008/35293008] -> "6281-gcc464_glibc215_88f6281-GPL.txz.part" [1] make arch-88f6281
===>  Building package for arch 88f6281
make[1]: Entering directory '/spksrc/spksrc/spk/transmission'
===>  Set up toolchain
===>    Downloading files for syno-88f6281
wget https://sourceforge.net/projects/dsgpl/files/DSM%206.1%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32/6281-gcc464_glibc215_88f6281-GPL.txz
2019-01-10 00:10:04 URL:https://pilotfiber.dl.sourceforge.net/project/dsgpl/DSM%206.1%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32/6281-gcc464_glibc215_88f6281-GPL.txz [35293008/35293008] -> "6281-gcc464_glibc215_88f6281-GPL.txz.part" [1]
...

**Comment by ymartin59** [comment]
Thanks for references. I will try to improve situation with Debian Stretch image #3569. I would really appreciate that my container runs with my own user instead of "root".

**Comment by sn00pster** [comment]
> @adrianblakey please have a look at https://github.com/SynoCommunity/spksrc/pull/3524/files which solves this on MacOSX

That didn't work as is for me, but changing the extract "rmdir" to "rm -rf" did fix it for me.

Many thanks for a fix, really didn't want to install a VM just to install docker to use spksrc!

**Comment by ixs** [comment]
The problem is not _just_ a docker issue.

For example building on MacOS for the target `88f6281` works fine but fails for the `x86_64` target.

Looking at the tarball for the toolchain shows that the directories are not created with 755 perms in one tarball and 555 in another:

```
$ tar tvfz distrib/toolchain/6.1/6281-gcc464_glibc215_88f6281-GPL.txz  | grep ^d | head -n 5
drwxr-xr-x  0 2609   users       0 Feb  4  2015 arm-marvell-linux-gnueabi/
drwxr-xr-x  0 2609   users       0 Feb  4  2015 arm-marvell-linux-gnueabi/marvell-doc/
drwxr-xr-x  0 2609   users       0 Feb  4  2015 arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/
drwxr-xr-x  0 2609   users       0 Feb 12  2015 arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/
drwxr-xr-x  0 2609   users       0 Feb  4  2015 arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/var/
$ tar tvfz distrib/toolchain/6.2.4/x64-gcc493_glibc220_linaro_x86_64-GPL.txz | grep ^d | head -n 5
dr-xr-xr-x  0 root   root        0 Jan  1  1970 x86_64-pc-linux-gnu/
dr-xr-xr-x  0 root   root        0 Jan  1  1970 x86_64-pc-linux-gnu/include/
dr-xr-xr-x  0 root   root        0 Jan  1  1970 x86_64-pc-linux-gnu/share/
dr-xr-xr-x  0 root   root        0 Jan  1  1970 x86_64-pc-linux-gnu/share/locale/
dr-xr-xr-x  0 root   root        0 Jan  1  1970 x86_64-pc-linux-gnu/share/locale/da/
$
```

Looking at an strace of the tar process shows the following error:

```
openat(AT_FDCWD, "/spksrc/spksrc/toolchain/syno-x86-6.1/work", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 4
mkdirat(4, "x86_64-pc-linux-gnu", 0500) = 0
mkdirat(4, "x86_64-pc-linux-gnu/share", 0500) = -1 EPERM (Operation not permitted)
```

the first mkdirat() call is working fine, the second one is failing because the user does not actually have write permissions to the directory. On Linux, this would work fine because we're running as root inside the container and no rules apply to root. It seems the translation layer on MacOS enforces permissions even for root.
