### ISSUE TITLE
gateone quickconnect

### ISSUE THREAD

**Issue by graingert** [SynoCommunity/spksrc#3571]
### Setup
_Package Name:_ GateOne
_Package Version:_ 20171125-8

_NAS Model:_ ds418play
_NAS Architecture:_ x86_64
_DSM version:_ 6 ish?

### Expected behavior
Supported over quickconnect

### Actual behavior
Tell us what happens instead

### Steps to reproduce
Dialog says:

Sorry, this package cannot be accessed while connected via QuickConnect.

**Comment by ymartin59** [comment]
... like most tools published as package here. I think it is far from simple to get it work. Your opinion @m4tt075 ?

**Comment by m4tt075** [comment]
Difficult. I've never used Quickconnect. I don't know how it works and how it interacts with the network configuration on the actual systems. Essentially, `Gateone` is just a 3rd-party service running via https on port 8271 (unless you've changed the default configuration).

@graingert I'd recommend sharing this information with Synology and ask them what the dialog means and whether they can guide you on some workaround. I'd take it from there...

**Comment by ymartin59** [comment]
Thanks. That was my opinion. Probably most users here do not use QuickConnect - I don't neither - not fan of the idea Synology knows where my DSM runs... so I built my own "internet access"...

QuickConnect looks like an dynamic internet proxy which forward traffic to private IP that DSM regularly sends to the service. It is designed to allow additional access that basic DSM, according to "Advanced" permission application list visible at https://www.synology.com/en-uk/knowledgebase/DSM/tutorial/Network/How_to_make_Synology_NAS_accessible_over_the_Internet

On my test system "GateOne" does not appear in "Advanced" permission application list - BUT Synology documentation does not provide any hints about how a third-party may declare itself as "QuickConnect" application (of course Synology packages/applications does !)

A guy already dive into technical details. May be a good starting point: http://www.thomastheunen.eu/2017/07/diving-into-synology-quickconnect-and.html

**Comment by DuerrundSteidle** [comment]
Is it still not possible?

**Comment by hgy59** [comment]
proper link to "A guy already dive into technical details."
https://thomastheunen.eu/2017/07/04/diving-into-synology-quickconnect-and-creating-a-javascript-library/

**Comment by hgy59** [comment]
this is not possible by design.
