### ISSUE TITLE
Understanding spksrc: tmux version

### ISSUE THREAD

**Issue by MatthiasLohr** [SynoCommunity/spksrc#3574]
Hey,

I'm thinking of starting contributing to this project, since I really like the work you are doing. Especially I'm looking for the tmux project, but I found a "inconsistency" - so I opened this ticket just for understanding reasons.
https://github.com/SynoCommunity/spksrc/blob/f8c4d538664748b147435084ef53007db271a436/spk/tmux/Makefile#L2
vs.
https://github.com/SynoCommunity/spksrc/blob/f8c4d538664748b147435084ef53007db271a436/cross/tmux/Makefile#L2

Shouldn't that be the same? Or is there any reason for the difference?

Best regards
Matthias

**Comment by m4tt075** [comment]
You are absolutely right and you will be more than welcome to contribute! Do you want to fix it, test it and PR your fix?

**Comment by ymartin59** [comment]
tmux is now published in https://synocommunity.com/package/synocli-net

**Comment by ymartin59** [comment]
I have though about the folder name to keep non-published package in repository for "advanced users". Why not "diyspk" - for "do it yourself" of course?

**Comment by MatthiasLohr** [comment]
Maybe just keep a package tmux for people want to install only tmux?

**Comment by ymartin59** [comment]
Cannot fulfill anybody request. I decided to group small command line tools to large packages to reduce workload overhead of updating/building/testing/publishing process. https://github.com/SynoCommunity/spksrc/issues?q=is%3Aissue+is%3Aopen+synocli

**Comment by MatthiasLohr** [comment]
However, I see a number of drawbacks:
* If you only need one of these tools, you still need to install Perl as a dependency - and all the other tools as well. This is a massive overhead.
* screen and tmux are not network tools
* You use either Screen or tmux, but not both

Does it make more sense to optimize the build chain than to have to make this kind of package compromise because of a non-optimal build chain? In fact, by summarizing tools in one package, you achieve the opposite of what you want to achieve: When updating a tool (e.g. tmux), you have to build, test and publish not just one tool, but all tools in this package.

**Comment by ymartin59** [comment]
DSM is not a Linux distribution and if you consider spksrc is not optimal, do not hesitate to review and improve it thanks to PRs.

**Comment by MatthiasLohr** [comment]
Whatever. Since the inconsistency is fixed, I think we should close this ticket.
