### ISSUE TITLE
SABnzbd now 2 versions behind

### ISSUE THREAD

**Issue by RainmakerRaw** [SynoCommunity/spksrc#3579]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_SABnzbd
_Package Version:_2.3.5-37

_NAS Model:_DS218+
_NAS Architecture:_x86
_DSM version:_6.2.1-23824 update 4

The SABnzbd package is now 2 versions behind [1].

Would someone please kindly push an update? If you can spare the time to link me to a resource or briefly outline how to push updates myself, I'll happily help keep it maintained if I'm able.

[1] https://github.com/sabnzbd/sabnzbd/releases/tag/2.3.7

**Comment by rp4k** [comment]
bump. +1  

someone please update this package and the beta package

**Comment by genefyx** [comment]
> Would someone please kindly push an update? If you can spare the time to link me to a resource or briefly outline how to push updates myself, I'll happily help keep it maintained if I'm able.

https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO

**Comment by ymartin59** [comment]
Update published.
