### ISSUE TITLE
OwnCloud Missing

### ISSUE THREAD

**Issue by Satu7nine** [SynoCommunity/spksrc#3580]
Hello,

Sorry to be a nuisance. I'm running a little DS118. I'm in the Community tab of the Package Center, but ownCloud is missing. Has it been withdrawn?

Thanks.

**Comment by ymartin59** [comment]
This package is part of our "DSM 6" upgrade plans but has not been processed yet. I will try to find time to work on it.

**Comment by jjahnat** [comment]
is it still missing od missing again?
