### ISSUE TITLE
any future update to include mr2200ac?

### ISSUE THREAD

**Issue by jefrytm** [SynoCommunity/spksrc#3593]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_
_Package Version:_

_NAS Model:_
_NAS Architecture:_
_DSM version:_

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by m4tt075** [comment]
To your very broad question, the answer is no. Most of the packages we maintain are server packages and not supposed and frequently not able to run on (weaker) router platforms. Some of our lighter weight packages might run on those devices, but you might have to tweak those packages to make them work. 

So, unless...
- there is some developer, who owns such a device
- AND has specific needs to run some of our packages on it
- AND looks at accomodating those packages to the platform
- AND succeeds
- AND bothers to share those insights here
- AND those packages are also what you are looking for

... the answer is no. If there is a specific package you are looking for I'd ask for that specifically.

**Comment by hgy59** [comment]
synology has published the toolchain (at least the gcc) for MR2200ac in January. Synology has named the package arch 'dakota' (CPU IPQ4019).

synology delivers some spk for this mesh router (cloud station server, dns server, download station, media server, ...)

If I had such a device, I would appreciate the dnscrypt-proxy package.

@jefrytm and all owning a synology MR2200ac Router. Please tell which package you expect (as m4tt075 already recommended).

Just updated the wiki today with supported [architectures](https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures).
The architectures (ipq806x and northstarplus) for the older (weaker) routers are actually supported by our community. At least the thoolchains are integrated, but honestly I don't know whether any package is built and was downloaded for such archs.

**Comment by m4tt075** [comment]
@hgy59 Hey! Welcome back!!!  :-)

**Comment by anamewing** [comment]
Do we have any progress on supporting MR2200ac? 
I would like to use the `syncthing` package on my router. However, there is only `northstarplus` and `ipq806x` in the package [release page](https://synocommunity.com/package/syncthing) so far.

Besides, these released packages are for SRM-1.1, which is not supported by MR2200ac, since this router only supports SRM-1.2 or higher version. Thus updating toolchains to include SRM-1.2 (#3647) might be related.

**Comment by ymartin59** [comment]
@anamewing You can find syncthing package for MR2200ac (dakota) at: https://synocommunity.com/package/syncthing
It has not been tested at all. We are interested in any report about tests you do.
Regards

**Comment by anamewing** [comment]
@ymartin59 Thanks for notifying me. I have installed syncthing `Version 1.3.4-18` for `1.2 dakota` on my MR2200ac, and it works well so far. After installation, it automatically upgrades to `v1.4.0`.
 
My SRM version is `1.2.3-8017 Update 4`.

**Comment by ymartin59** [comment]
Thanks for feedback. I consider issue as closed as project now has a compatible toolchain.
