### ISSUE TITLE
Debian Chroot on armada 83x

### ISSUE THREAD

**Issue by wixaw** [SynoCommunity/spksrc#3599]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ debian-chroot
_Package Version:_ v8

_NAS Model:_ ds218j
_NAS Architecture:_ armada 83x
_DSM version:_ 6

### Expected behavior
Debian chroot should be available

### Actual behavior
Debian chroot is not available

### Steps to reproduce
_1._ go to packages community
_2._ not available

I wish I had Debian Chroot to run jeedom on my NAS

Thank you in advance for the availability
William

**Comment by m4tt075** [comment]
Just take a look at #2758, please. There has been too much trouble with this...
Closing this issue as duplicate.
