### ISSUE TITLE
[Package Request] etherwake

### ISSUE THREAD

**Issue by xaozai** [SynoCommunity/spksrc#3602]
**Name:** etherwake
    **Description:** tool to send magic Wake-on-LAN packets
	This program generates and transmits a Wake-On-LAN (WOL)
	"Magic Packet", used for restarting machines that have been
	soft-powered-down (ACPI D3-warm state).
	It currently generates the standard AMD Magic Packet format, with
	an optional password appended.
    **Website:** https://packages.debian.org/jessie/etherwake
    **Software documentation:** 
	usage: etherwake [-i <ifname>] [-p aa:bb:cc:dd[:ee:ff]] 00:11:22:33:44:55
	Options:
		-b	Send wake-up packet to the broadcast address.
		-D	Increase the debug level.
		-i ifname	Use interface IFNAME instead of the default 'eth0'.
		-p <pw>		Append the four or six byte password PW to the packet.
					A password is only required for a few adapter types.
					The password may be specified in ethernet hex format
					or dotted decimal (Internet address)
		-p 00:22:44:66:88:aa
		-p 192.168.1.1
**Build/Installation documentation:** deb-package
**Source code:** http://deb.debian.org/debian/pool/main/e/etherwake/etherwake_1.09-4.debian.tar.gz
**License:** GNU General Public License

**Comment by ymartin59** [comment]
Depending on size and dependencies, may be included in synocli-net package
