### ISSUE TITLE
[TVheadend] add basic configuration info to package description

### ISSUE THREAD

**Issue by kekukui** [SynoCommunity/spksrc#3603]
**In the Package Manager description field, could you include a URL for the TVH setup instructions
 (or state the default port for the web interface)**

**Comment by m4tt075** [comment]
@kekukui Hmh, a regular user should not even have to know the port. After installing `Tvheadend`, an icon should be created in the DSM Web-UI programs menu (top left of your screen). If you click the icon, you should be redirected to the `Tvheadend` web-UI automatically. Does that not work for you?

**Comment by kekukui** [comment]
The icon did not appear after installation.  I think this was caused by a browser bug that interferes with page rendering: https://github.com/brave/brave-browser/issues/1896

I tried a different browser and it works now.

**Comment by m4tt075** [comment]
OK. Thanks for coming back. Coud you please close this issue as resolved then?

**Comment by kekukui** [comment]
As the setup wizard is invoked upon first run, I still think a link to the user guide would be helpful - but maybe it belongs in the TVH server core, so closing.

(Another consideration for the future - if the setup wizard can detect and display local subnet as default netmask)
