### ISSUE TITLE
Syncthing needs to be restarted 

### ISSUE THREAD

**Issue by darlac** [SynoCommunity/spksrc#3615]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Syncthing 
_Package Version:_ v0.14.49-15

_NAS Model:_ DS216+II
_NAS Architecture:_ INTEL Celeron N3060
_DSM version:_ DSM 6.2.1-23824 Update 4

### Expected behavior
While Syncthing is running should stay connected to other devices on network with syncthing also running

### Actual behavior
Although Syncthing is running on NAS, after sometime it looses connection with other devices (I have a desktop constantly on, and a laptop on/off as needed). I need to stop the syncthing process (through DSM, not the syncthing home webpage)  and restart it; then it connects fine again

### Steps to reproduce
_1._ Start syncthing
_2._ wait some time (usually a few hours) until it looses connection
_3._ stop and restart syncthing

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

Insert the package log here

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

Insert log here

**Comment by ymartin59** [comment]
Syncthing package update has been published. Please try after update.
