### ISSUE TITLE
Review and document publish process

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3619]
Reference: https://github.com/SynoCommunity/spksrc/wiki/Update-Policy

**Comment by ymartin59** [comment]
@m4tt075 To be granted repository management and publish permissions, may you please register yourself with "m4tt075" as username at https://synocommunity.com/register

**Comment by m4tt075** [comment]
Thank You for your trust! I've completed my registration and will review the Update Policy Wiki.

**Comment by ymartin59** [comment]
Now you should be able to browse https://synocommunity.com  /admin/   after using /login  - sorry but spkrepo is quite "obfuscated", I guess it is to prevent spam/robots...

**Comment by ymartin59** [comment]
I have to remember how I get my API key for local.mk
```
PUBLISH_URL=https://api.synocommunity.com
PUBLISH_API_KEY=
```

**Comment by m4tt075** [comment]
@ymartin59 OK, I'm able to browse the admin pages. I'd like to republish `Jackett` (merged already), as our current version is broken. I've reviewed the Wiki pages now. Do I really have to build all packages I want to publish locally first? Asking because that would essentially kill my good old laptop for several days...

**Comment by ymartin59** [comment]
@m4tt075 In fact I do build locally so that I can test package in xpenology and in my own DSM before publishing... If you find a wait to publish from Travis, do it that way... Have you been able to generate an API token for your spkrepo account?

**Comment by m4tt075** [comment]
@ymartin59 I do the same. I build for XPE5.2 and 6.1 (`x64`) and my actual `evansport-6.1` device for testing. But that is different than building all supported 5.2 and 6.1/6.2 platforms locally. I have to figure out how to do it with Travis. To answer your question: No, I haven't. Can you let me know what to do to generate such an API token, please?

**Comment by ymartin59** [comment]
@m4tt075 I just find myself stupid... I have found no note or email about API token... But I have not thought I may have find information in documentations:
- https://spkrepo.readthedocs.io/en/latest/api.html
- https://github.com/SynoCommunity/spkrepo/blob/master/docs/api.rst
So just open https://synocommunity.com  /profile  (also hidden page without link to it - that is why I split it here) and you can get an API token

**Comment by m4tt075** [comment]
@ymartin59 Many thanks. But stupid me, I'd say. I had found the profile page but did not scroll down...  ;-)
OK, I'll try publishing `Jackett` in the next couple of days. Hope I won't screw up...

**Comment by ymartin59** [comment]
@m4tt075 Looks good. You have to select "version" and "activate" it now.

**Comment by hgy59** [comment]
The publish process was updated in #6247 and is intergrated into github workflow some time ago.
