### ISSUE TITLE
Standard Docker build environment broken?

### ISSUE THREAD

**Issue by m4tt075** [SynoCommunity/spksrc#3625]
### Setup
_Package Name:_ `Tvheadend` (for example)
_Package Version:_ 4.2.8-fixes (see PR #3623)

_NAS Model:_ Various
_NAS Architecture:_ Various
_DSM version:_ 6.1

### Expected behavior
Should compile in standard Docker build environment
[Edit: Formerly reported problems with VirtualBox builds had different rationale. Removed as obsolete.]

### Actual behavior
Builds on Standard Docker image (pulled via travis) fail with:
```
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
  CMake 3.1 or higher is required.  You are running version 3.0.2
``` 
See https://travis-ci.org/m4tt075/spksrc/builds/492410154 for more examples

### Steps to reproduce
Try building `tvh-4.2.8-fixes` with standard Docker image (pulled in via travis)

**Comment by m4tt075** [comment]
@ymartin59 I'm afraid that is exactly what @chickenandpork predicted. I'm stuck and cannot develop effectively anymore. I keep replicating the build errors I've reported earlier. The fixes I pushed were rejected. I know that you don't face these issues, I believe(!), because you build (and publish?) with some upgraded Docker image. However, I'm unable to access it using the build methods I have access to (see issue report). If I knew how to address it without the fixes I proposed in the past, I would have tried. Therefore, can you please fix the build environment problems instead? Otherwise, I'm stranded...

**Comment by m4tt075** [comment]
@ymartin59 Virtualbox / Evansport issue resolved (I think!), but my broader development issues persist due to the Docker / travis problems.

**Comment by ymartin59** [comment]
Stretch Docker image is ready since a while at #3569 @Diaoul May you please grant my Docker account write access to SynoCommunity registry? Thanks in advance.

**Comment by Diaoul** [comment]
@ymartin59 you need to give me your Docker ID so I can add you to the Docker team.

**Comment by ymartin59** [comment]
@Diaoul I had chance "ymartin59" was still available.

**Comment by ymartin59** [comment]
@m4tt075 @hgy59  You will find new Docker image as "latest" == "stretch" tags in Hub: https://hub.docker.com/r/synocommunity/spksrc/tags
I have tagged previous image as "jessie" to confirm failure may come from lacking components in "stretch" image I have tried to create the lightest as possible.
CC @Diaoul

**Comment by m4tt075** [comment]
@ymartin59 Nope. Does not work (yet). Travis fails with the following error:
```
$ docker run -it -v `pwd`:/spksrc synocommunity/spksrc:latest /bin/bash -c "cd /spksrc && make setup && cd spk/$PKG && make $SYNOARCH>/dev/null";
Creating local configuration "local.mk"...
Setting default toolchain version to DSM-6.1
../../mk/spksrc.tc.mk:16: *** Recursive variable 'DISTRIB_DIR' references itself (eventually).  Stop.
/spksrc/spk/tvheadend/work-88f6281-6.1/tc_vars.mk:1: *** An error occured while setting up the toolchain, please check the messages above.  Stop.
make: [arch-88f6281-6.1] Error 2 (ignored)
```
I assume this is related to your other framework-related changes. Please just let me know, when you believe things should be stable again...

**Comment by ymartin59** [comment]
What is the branch you try to build? Does it include latest commit c7655084cf9865087981a7a12429b8d4139a9d6b?

**Comment by m4tt075** [comment]
Nope. I rebased and now it seems to be working again. Thanks,  @ymartin59.
