### ISSUE TITLE
Sickbeard-custom -> 'Incorrect Fork'

### ISSUE THREAD

**Issue by rmndizzle** [SynoCommunity/spksrc#3634]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: SickBeard Custom
_Package Version: 20180629-7

_NAS Model: RS2212+
_NAS Architecture: INTEL Atom D2700
_DSM version: DSM 6.2.1-23824 Update 4

### Expected behavior
Sickbeard Custom should install based on specified fork URL/Branch.

### Actual behavior
Immediate Error: Failed to install "SickBeard Custom" Incorrect fork

### Steps to reproduce
1. Find and run 'Sickbeard Custom' from Package Center
2. Accept default fork url/branch or specify SickGear (git://github.com/SickGear/SickGear.git / master).    
3. Click 'Accept' to install

It errors out almost immediately before it even gets to checking the fork.  I just can't find any more information.  Sickbeard (prior to sickbeard custom) was installed on this Synology and I uninstalled it prior to attempting to load via sickbeard custom.  I did a 'sudo find . -name "*sick*"' and removed any lingering sickbeard files from the old install as well as manually removing the sickbeard hidden user.  No dice..

#### Package log
It doesn't get far enough to create a package log.
It does create an install log.. but not much info there.

`/tmp/sickbeard-custom_install.log`
Tue Feb 19 09:50:20 PST 2019
===> Step preinst. USER=sickbeard-custom GROUP=sc-download SHARE_PATH=
Invoke service_preinst

#### Other logs
`/var/log/messages` 
2019-02-19T10:15:07-08:00 cBackup synoscgi_SYNO.Core.Package.Installation_1_install[30469]: pkginstall.cpp:476 Failed to run preinst script for sickbeard-custom, 1

`/var/log/synopkg.log`
2019/02/19 10:15:06	install sickbeard-custom 20180629-7 Begin preinst
2019/02/19 10:15:07	install sickbeard-custom 20180629-7 End preinst ret=[1]
2019/02/19 10:15:07	install sickbeard-custom 20180629-7 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2019/02/19 10:15:07	install sickbeard-custom 20180629-7 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2019/02/19 10:15:07	install sickbeard-custom 20180629-7 failed

**Comment by BenjV** [comment]
It is unclear what you filled in the filed but it should be:
Fork URL:
git://github.com/SickGear/SickGear.git
Fork Branch:
master

**Comment by rmndizzle** [comment]
Thanks for the reply.  I listed what I entered for URL/Branch under Step #2 of How to Reproduce.  

git://github.com/SickGear/SickGear.git / master

The same error occurs with the default URL/Branch as well as others.  I've used the same settings on a different Synology and it works fine.

**Comment by BenjV** [comment]
If the error message is "incorrect fork" and of returns very fast then you made a typo.

**Comment by rmndizzle** [comment]
That's what I assumed.. except that I did not.  I copied the fork URL and branch from the instructions from SickGear and pasted...  I also pasted to another Synology and it worked on another Synology.

For giggles, I also cp'd from your post above.  No dice.

**Comment by ymartin59** [comment]
URL as git:// means you expect to access Git repository thanks to SSH protocol, which requires at least to submit a GitHub user SSH key to server.
Please try that one instead: https://github.com/SickGear/SickGear.git

**Comment by rmndizzle** [comment]
Thanks for the response @ymartin59.  I tried that already as well as dropping prefix altogether and just using github.com/SickGear/SickGear.git.  No luck.  I tried again just now to be sure..

Any other ideas?  Is there a way to see more logging of what's going on behind the scenes?

**Comment by BenjV** [comment]
@ymartin59 
That SSH key is send to GitHub by the gitclient installed on the Nas, so that could not have been the probleem.

@rmndizzle 
My guess is that something wrong with the git client on that Nas.
So I would suggest removing git form the Nas and reinstalling it.

**Comment by rmndizzle** [comment]
That was it!  Thanks @BenjV!
