### ISSUE TITLE
Error when building sabnzbd

### ISSUE THREAD

**Issue by lsf3og** [SynoCommunity/spksrc#3636]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:sabnzbd
_Package Version:2.3.7

_NAS Model: Synology DS 418play
_NAS Architecture:_arch-88f6281
_DSM version:6.2.1-23824 update 4

### Expected behavior
Tell us what should happen
The build process should have run through?

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1. I tried running make on my Ubunutu server and got this:
_2. 

===>  Building package for arch 88f6281
make[1]: Entering directory '/spksrc/spk/sabnzbd'
===>  Stripping binaries and libraries of sabnzbd
Stripping bin/7z... failed!
Stripping bin/7za... failed!
Stripping bin/7zr... failed!
Stripping bin/busybox... ok
Stripping bin/par2... ok
Stripping bin/unrar... chmod: cannot access '/spksrc/spk/sabnzbd/work-88f6281-6.1/staging/bin/unrar': No such file or directory
../../mk/spksrc.strip.mk:49: recipe for target 'strip_target' failed
make[1]: *** [strip_target] Error 1
make[1]: Leaving directory '/spksrc/spk/sabnzbd'
../../mk/spksrc.spk.mk:452: recipe for target 'arch-88f6281' failed
make: [arch-88f6281] Error 2 (ignored)

_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
No log since i build it and wasn't running the package
Insert the package log here
No log since i build it and wasn't running the package
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
see futher discussion in  #4035
