### ISSUE TITLE
Oscam build // missing -lssl & -lcrypto & -lusb-1.0

### ISSUE THREAD

**Issue by teminvictus** [SynoCommunity/spksrc#3637]
hi, I am trying to build Oscam but kind of stuck at one point.
at the building process its missing -lssl & -lcrypto & -lusb-1.0 and I can't get it right. 

I know Nimloth is providing oscam for different synology architectures, but still would like to figure that thing out.

### Setup
Package Name: **Oscam**
Package Version: **11504**

NAS Model: **DS 1513+**
NAS Architecture: **cedarview**
DSM version: **6.2.1**

SSH Output:

> make[3]: Entering directory '/spksrc/spksrc/spk/oscam/work-cedarview-6.1/oscam-r11504'
+-------------------------------------------------------------------------------
| OSCam ver: 1.20_svn rev:  target: x86_64-pc-linux-gnu-ssl-libusb
| Tools:
|  CROSS    = /spksrc/spksrc/toolchains/syno-cedarview-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-
|  CC       = /spksrc/spksrc/toolchains/syno-cedarview-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc
| Settings:
|  CONF_DIR = /usr/local/oscam/etc
|  CC_OPTS  = -O2 -ggdb -pipe -ffunction-sections -fdata-sections
|  CC_WARN  = -W -Wall -Wshadow -Wredundant-decls -Wstrict-prototypes -Wold-style-definition
|  CFLAGS   = -I/spksrc/spksrc/toolchains/syno-cedarview-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/spksrc/spk/oscam/work-cedarview-6.1/install//usr/local/oscam/include -DWITH_SSL=1 -DWITH_LIBCRYPTO=1 -DWITH_LIBUSB=1
|  LDFLAGS  = -Wl,--gc-sections -DWITH_SSL=1 -DWITH_LIBCRYPTO=1 -DWITH_LIBUSB=1
|  LIBS     = -lssl -lcrypto -lusb-1.0 -lrt -lm -lpthread -ldl
|  UseFlags = USE_SSL=1 USE_LIBCRYPTO=1 USE_LIBUSB=1
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY WITH_SSL READ_SDT_CHARSETS IRDETO_GUESSING CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE_CHECK
|  Protocols: CAMD33 CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX SCAM
|  Readers  : NAGRA NAGRA_MERLIN IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : PHOENIX INTERNAL SC8IN1 MP35 SMARGO DB2COM STAPI STAPI5 STINGER DRECAS SMART
|  Compiler : x86_64-pc-linux-gnu-gcc (crosstool-NG 1.20.0) 4.9.3 20150311 (prerelease)
|  Config   : build/x86_64-pc-linux-gnu-ssl-libusb/config.mak
|  Binary   : Distribution/oscam-1.20_svn-x86_64-pc-linux-gnu-ssl-libusb
+-------------------------------------------------------------------------------
HOSTCC  webif/pages_gen
GEN     webif/pages.c
GEN     Compressed 423568 template bytes into 171669 bytes. 251899 saved bytes (59.47%).
CC      cscrypt/des.c
CC      cscrypt/i_cbc.c
CC      cscrypt/i_ecb.c
CC      cscrypt/i_skey.c
CC      cscrypt/md5.c
CC      cscrypt/rc6.c
CC      cscrypt/mdc2.c
CC      cscrypt/fast_aes.c
CC      cscrypt/sha256.c
CC      csctapi/atr.c
CC      csctapi/icc_async.c
CC      csctapi/io_serial.c
CC      csctapi/protocol_t0.c
CC      csctapi/protocol_t1.c
CC      csctapi/ifd_db2com.c
CC      csctapi/ifd_mp35.c
CC      csctapi/ifd_phoenix.c
CC      csctapi/ifd_drecas.c
CC      csctapi/ifd_sc8in1.c
CC      csctapi/ifd_sci.c
CC      csctapi/ifd_smargo.c
CC      csctapi/ifd_smartreader.c
CC      csctapi/ifd_stinger.c
CC      minilzo/minilzo.c
CC      module-anticasc.c
CC      module-cacheex.c
CC      module-camd33.c
CC      module-camd35-cacheex.c
CC      module-camd35.c
CC      module-cccam-cacheex.c
CC      module-cccam.c
CC      module-cccshare.c
CC      module-csp.c
CC      module-cw-cycle-check.c
CC      module-gbox-helper.c
CC      module-gbox-sms.c
CC      module-gbox-remm.c
CC      module-gbox-cards.c
CC      module-gbox.c
CC      module-ird-guess.c
CC      module-monitor.c
CC      module-newcamd.c
CC      module-newcamd-des.c
CC      module-scam.c
CC      module-stat.c
CC      module-webif-lib.c
CC      module-webif-tpl.c
CC      module-webif.c
CC      webif/pages.c
CC      reader-common.c
CC      reader-bulcrypt.c
CC      reader-conax.c
CC      reader-cryptoworks.c
CC      reader-dgcrypt.c
CC      reader-dre.c
CC      reader-dre-cas.c
CC      reader-dre-common.c
CC      reader-dre-st20.c
CC      reader-griffin.c
CC      reader-irdeto.c
CC      reader-nagra-common.c
CC      reader-nagra.c
CC      reader-nagracak7.c
CC      reader-seca.c
CC      reader-tongfang.c
CC      reader-viaccess.c
CC      reader-videoguard-common.c
CC      reader-videoguard1.c
CC      reader-videoguard12.c
CC      reader-videoguard2.c
CC      oscam-aes.c
CC      oscam-array.c
CC      oscam-hashtable.c
CC      oscam-cache.c
CC      oscam-chk.c
CC      oscam-client.c
CC      oscam-conf.c
CC      oscam-conf-chk.c
CC      oscam-conf-mk.c
CC      oscam-config-account.c
CC      oscam-config-global.c
CC      oscam-config-reader.c
CC      oscam-config.c
CC      oscam-ecm.c
CC      oscam-emm.c
CC      oscam-emm-cache.c
CC      oscam-failban.c
CC      oscam-files.c
CC      oscam-garbage.c
CC      oscam-lock.c
CC      oscam-log.c
CC      oscam-log-reader.c
CC      oscam-net.c
CC      oscam-llist.c
CC      oscam-reader.c
CC      oscam-simples.c
CC      oscam-string.c
CC      oscam-time.c
CC      oscam-work.c
CC      oscam.c
CONF    build/x86_64-pc-linux-gnu-ssl-libusb/config.c
LINK    Distribution/oscam-1.20_svn-x86_64-pc-linux-gnu-ssl-libusb.debug
/spksrc/spksrc/toolchains/syno-cedarview-6.1/work/x86_64-pc-linux-gnu/bin/../lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lssl
/spksrc/spksrc/toolchains/syno-cedarview-6.1/work/x86_64-pc-linux-gnu/bin/../lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lcrypto
/spksrc/spksrc/toolchains/syno-cedarview-6.1/work/x86_64-pc-linux-gnu/bin/../lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lusb-1.0
collect2: error: ld returned 1 exit status
Makefile:404: recipe for target 'Distribution/oscam-1.20_svn-x86_64-pc-linux-gnu-ssl-libusb.debug' failed
make[4]: *** [Distribution/oscam-1.20_svn-x86_64-pc-linux-gnu-ssl-libusb.debug] Error 1
Makefile:373: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/spksrc/spksrc/spk/oscam/work-cedarview-6.1/oscam-r11504'
Makefile:30: recipe for target 'myCompile' failed
make[2]: *** [myCompile] Error 2
make[2]: Leaving directory '/spksrc/spksrc/cross/oscam'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory '/spksrc/spksrc/spk/oscam'
../../mk/spksrc.spk.mk:452: recipe for target 'arch-cedarview' failed
make: [arch-cedarview] Error 2 (ignored)

here is even more from the output [pastebin](https://pastebin.com/msXaGvu8 )

**Comment by m4tt075** [comment]
@teminvictus I'd look at the `ADDITIONAL_LD_FLAGS` variable in the `Makefile`. But: I've just looked at the history of this package. It seems it has last been updated in 2012. I actually believe it should have been removed from our repo a long time ago, especially as there is someone else maintaining and hosting it elsewhere. @ymartin59 Are you fine with removing it?

**Comment by chickenandpork** [comment]
Do we need lusb for the HA work you’re doing, @ymartin59?  (Cuz I hope to use my usb zwave on that when you’re done :) )

**Comment by ymartin59** [comment]
@m4tt075 From my point of view, it is difficult to keep a package here if there is not at least one maintainer who is also an effective user himself of his own package...
@chickenandpork Yes I have exactly same need for HA. At the moment I run Domoticz to check my zwave network

**Comment by schumi2004** [comment]
I thought the original owner had some issues oscam being shared/hosted on other sites then their own?

**Comment by schumi2004** [comment]
@teminvictus could you drop me a email, maybe i can help you.
My email is my nickname [at]gmail.com

**Comment by hgy59** [comment]
retire oscam package
