### ISSUE TITLE
HomeAssistant 0.87.1-3 won't start

### ISSUE THREAD

**Issue by dotvav** [SynoCommunity/spksrc#3643]
### Setup
_Package Name:_ HomeAssistant
_Package Version:_ 0.87.1-3

_NAS Model:_ DS418j
_NAS Architecture:_ synology_rtd1293_ds418j
DSM version:_ DSM 6.2.1-23824 Update 6

### Problem
HomeAssistant won't start. It is missing env files. I have tried updating the package from previous version (0.82.1-2) and uninstalling/reinstalling the whole package.

#### Package log
```
Fri Mar  1 07:36:53 CET 2019
Starting homeassistant command /volume1/@appstore/homeassistant/env/bin/hass -v --config /volume1/@appstore/homeassistant/var/config --pid-file /volume1/@appstore/homeassistant/var/homeassistant.pid --log-file /volume1/@appstore/homeassistant/var/homeassistant.log --daemon
/var/packages/homeassistant/scripts/start-stop-status: line 49: /volume1/@appstore/homeassistant/env/bin/hass: No such file or directory
```

**Comment by ymartin59** [comment]
May you please upload file `/var/packages/homeassistant/target/var/homeassistant_install.log` as comment attachment.

**Comment by ymartin59** [comment]
Please also report content from `/var/packages/python3/target/var/python3_install.log`

**Comment by dotvav** [comment]
[python3_install.log](https://github.com/SynoCommunity/spksrc/files/2921827/python3_install.log)
[homeassistant_install.log](https://github.com/SynoCommunity/spksrc/files/2921828/homeassistant_install.log)
Here you go.

**Comment by ymartin59** [comment]
Issue comes from Python3 package. Please follow #3644

**Comment by rogervdf** [comment]
Fixed on my ds218+ as follows:

1) hard-remove python2/3
2) python3 from spk, add to path
3) add missing _sysconfigdata_(d)m_linux_aarch64-linux-gnu.py at requested location (this is obviously not a proper fix)
4) add missing requirements virtualenv and markupsafe by pip3 
5) install new homeassistant by spk

2019-03-04 17:08:21 ERROR (MainThread) [homeassistant.auth.providers] Unable to load auth provider homeassistant: No module named '_cffi_backend'
2019-03-04 17:08:21 ERROR (MainThread) [homeassistant.bootstrap] Home Assistant core failed to initialize. Further initialization aborted

that last error seems related to cffi/cryptography and am still trying to figure it out

**Comment by ymartin59** [comment]
@rogervdf Not so simple. You should look at python3_install.log and homeassistant_install.log and check if virtualenv creation and wheels installation have succeeded. Probably not, so you have to replay commands from service-setup.sh script. Good luck but there is low hope to succeed in my opinion.
I go on with investigations to fix cross-compilation.

**Comment by miklosandras** [comment]
Python upgraded to 3.6.8 via https://github.com/SynoCommunity/spksrc/pull/3833

And I got these errors:

2020-01-02 13:18:00 ERROR (MainThread) [homeassistant.auth.providers] Unable to load auth provider homeassistant: No module named '_cffi_backend'
2020-01-02 13:18:00 ERROR (MainThread) [homeassistant.bootstrap] Home Assistant core failed to initialize. Further initialization aborted

cffi installed, what would be the problem? @rogervdf Did you solve this problem?

**Comment by rogervdf** [comment]
@miklosandras No, I never solved this problem directly. The python3 cross-compilation process for spksrc has turned out to be complex, and I think this has not been upgraded towards newer versions of python3 since. It was cheaper for me in terms of time to just upgrade the NAS to one that supported running containers.
