### ISSUE TITLE
[synocli-net] not available for ppc538x

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#3652]
When building synocli-net with `make all-supported`, there is no package generated for ARCH=ppc538x (and TCVERSION=5.2)
The dependency /cross/fuse fails to build for ARCH=ppc538x and the build is aborted.

On the [download site](https://synocommunity.com/package/synocli-net) the package for ppc538x is missing too.

**Comment by cytec** [comment]
Thought we dropped ppc support all together a while ago?

**Comment by hgy59** [comment]
I dont think so
`ppc538x-5.2` and `qoriq-6.1` are still built with `make all-supported`

Active Models with ppc538x:
- DS110+, DS210+, DS410

Active Models with qoriq:
- DS213+, DS413

**Comment by cytec** [comment]
OIC... we did drop support for older ppc models which didn't get the 5.x update... nevermind
