### ISSUE TITLE
Jackett requires a version upgrade

### ISSUE THREAD

**Issue by flightlevel** [SynoCommunity/spksrc#3653]
The Jackett team has been working over the last year to remove Jackett's dependency on Mono. From Jackett v0.11, the recommended method of running Jackett is without Mono (Mono builds will still be available for the foreseeable future)

Due to changes made to Jackett's self updater, we've found that the self updater will no longer work if your Jackett version is older than v0.10.648 (from about 2 months ago)

Some options for SynoCommunity that I can think of:
1. Easiest for now. Upgrade Jackett to v0.11.1 or above using the Mono version of Jackett. Should be a very minor change but you are going to still have the headache of all users remaining on Mono
2. Switch to the .NET Core version of Jackett. Mono is not required and it supports AMDx64 and ARMv7 or above. Not sure if you have or many ARMv6 users though
3. Hybrid/conditional of option 1 and 2

Publishing this version will pointless now https://github.com/SynoCommunity/spksrc/pull/3572 and reference https://github.com/Jackett/Jackett/issues/4858

**Comment by ymartin59** [comment]
@m4tt075 I have found you have uploaded Jackett 0.10.589-7 packages into spkrepo. You should "activate" the "version" entity so that all this gets published. Well done.

**Comment by m4tt075** [comment]
@ymartin59 Yes, and I was pretty proud at that time. And then I realized that based on @flightlevel 's comment above, there is no use in activating this version as  we'll have to update `Jackett` again. 

I've just returned from a business trip, but believe that we really have to think what to do with `mono` and all depending packages. The release cycles of `mono` are very quick and - IMO - frequently insufficiently tested. The depending packages change frequently as well. It's all too much of a moving target. It would be ok if a lot of people would test those packages, but the download rates for my test packages are underwhelming (15 for mono, 1-2 for all the *arr packages). As such, the return on invested time for maintenance is very low. In light of that, maybe we should just focus on keeping `mono` up-to-date and leaving the rest "unmaintained", waiting for upstream or volunteers to ensure consistency with whatever mono version we are shipping...

**Comment by bolhaskutya** [comment]
@m4tt075 
I'm in the same situation. I see version 0.10.589-7 on synocommunity.com, but it doesn't appear within my synology's package manager. I don't quite understand the plans, what will be the fate of the synology package?

**Comment by m4tt075** [comment]
I'll update it again. But if not contributors, we'll at least need people who test those packages and report back. Are you willing to do that?

**Comment by bolhaskutya** [comment]
Absolutely! Send any package any time :)

**Comment by m4tt075** [comment]
@flightlevel @bolhaskutya OK, addressed with #3657. Test-builds (including DS918+) and testing reports in #3470, please. Please test in conjunction with the updated `mono` test packages that are listed in #3470 as well.

**Comment by bolhaskutya** [comment]
@m4tt075 
You're awesome, I'll get to testing. Which package should I download? As far as I know DS918+ is apollolake. Perhaps "aarch64"?

**Comment by m4tt075** [comment]
For `apollolake` you'll need the `x64` one. Please be patient after the installation. The package needs some time to initiatialize after installation before it states that it is "running", and even more before you can access its web-interface (a couple of minutes in my VirtualBox test environment). The same is true, after you have triggered an internal upgrade from within the web-interface.

**Comment by malinwa001** [comment]
next update was released yesterday

**Comment by m4tt075** [comment]
With the new package, the internal upgrade mechanism should work again. It can be triggered via the `Jackett` web-interface...

**Comment by iFredOS** [comment]
If I apply any changes to the configuration and I apply, it crash the process and I cannot access it anymore more. I tried to kill the process and/or stop it from the Package Center but it won't work anymore. I needed to uninstall twice because I cannot change any settings without screwing up the installation. I can only add the indexers without touching anything else.

**Comment by m4tt075** [comment]
OK, what does the log say?

**Comment by iFredOS** [comment]
> OK, what does the log say?
> Edit: And which DSM version are you running and what is your NAS model?

Model name: DS918+
DSM version: 6.2.1-23824 Update 6

**Comment by m4tt075** [comment]
Closing this issue, as `Jackett` has been upgraded. Seems to work for `x64` and `ARM7` users, not for `aarch64` unfortunately (see #3666). 
@iFredOS Not sure you solved your issue in the meantime. If not, please just open a new issue thread.

**Comment by iFredOS** [comment]
> Closing this issue, as `Jackett` has been upgraded. Seems to work for `x64` and `ARM7` users, not for `aarch64` unfortunately (see #3666).
> @iFredOS Not sure you solved your issue in the meantime. If not, please just open a new issue thread.

It fixed by itself. What I didn't know it update itself. I checked on the official Jackett repo and all is good. Thanks. If don't touch the config this is fine. I added a proxy SOCK5 and now it works. I think they fixed a few things related to the proxy, because now I see a warning message if I use one.
