### ISSUE TITLE
[Request] FFmpeg for qoriq

### ISSUE THREAD

**Issue by The-MAD-Virus** [SynoCommunity/spksrc#3654]
Hi there,

When i use the FFmpeg package i get "Illegal instruction (core dumped)" so is it possible to add --cpu=e500v2 for qoriq architecture to prevent  this problem ?

### Setup
Package Name: FFmpeg
Package Version: 4.1 (rev: 11)

NAS Model: DS413
NAS Architecture: Qoriq
DSM version: 6.1

**Comment by ymartin59** [comment]
Hello. Thanks for that hint. I have rebuilt and replace package in repository with same version (to do it fast...) but then you will have to either download https://packages.synocommunity.com/ffmpeg/11/ffmpeg.v11.f15047[qoriq].spk and install package manually to replace your installed one - or else uninstall/re-install from Package Center

**Comment by The-MAD-Virus** [comment]
thanks for your fast reply, but it still doesn't work.
i'll try to setup a new vm to test further parameter.

can just tell me how did you make a distinction between other ppc and qoriq ?

**Comment by The-MAD-Virus** [comment]
ok in fact you also need to disable asm for e500v2 cpu and now it work fine.

--cpu=e500v2 --disable-asm

**Comment by hadess** [comment]
Isn't the problem that qoriq doesn't have the LWSYNC instead? I'm pretty certain that Altivec availability is supposed to be runtime checked in ffmpeg, and the problem might be the same as:
https://github.com/SynoCommunity/spksrc/issues/834

**Comment by hadess** [comment]
That instruction doesn't seem to be used in libavcodec, and I'm not certain the runtime detection gets used either, so forget I said anything ;)
