### ISSUE TITLE
Make Domoticz compile again

### ISSUE THREAD

**Issue by rogervdf** [SynoCommunity/spksrc#3656]
So I've been trying to get Domoticz to compile again, here's the work in progress which I might resume at a later stage.

_New top part for Makefile_

PKG_NAME = domoticz
PKG_VERS = 4.9700
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/domoticz/domoticz/archive
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

_PLIST_

bin:bin/domoticz
rsc:www
rsc:Config
rsc:scripts
rsc:var

_digests_

4.9700.tar.gz SHA1 cd5b80f485cc968b969b7d25022ab28fe7693c59
4.9700.tar.gz SHA256 c31f185a1ffac01b86a77bf33e059a4403d814e826c9d6639c63c2e9afa55a46
4.9700.tar.gz MD5 726d838d5d80eed4335b0dfeefb2af6c

_Additions to environment_ 

g++-multilib
python3-dev 
libcurl4-gnutls-dev
boost 1.68 from source (not sure if necessary)

When running make for my arch it gets stuck at which point I can push it a little forward with this cmake in the work directory in domoticz folder

cmake CMakeLists.txt -DPYTHON_LIBRARY=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5.so -DZLIB_LIBRARY=/usr/include/zlib.h -DCURL_INCLUDE_DIR=/usr/include/x86_64-linux-gnu/curl/

... which indicates make/cmake have issues finding libraries for some reason. I thought it was because of a multi-python setup (2.7-minimal comes with base build) but it might be more than that.

**Comment by hgy59** [comment]
Hi @rogervdf 
I have work in progress with `domiticz` update that compiles. Newer domiticz like 4.9700 compile with python 3 only. So the dependency `cross/boost` must use python 3 too.
Unfortunatly the `deluge` package depends on cross/boost too, but needs python 2. Maybe there will be deluge 2.0 somewhere in the future with python 3 support [(see this long thread)](https://forum.deluge-torrent.org/viewtopic.php?f=8&t=54338).

Therefore, to not break the deluge package now, we might splitt cross/boost into two packages: one that binds to python 2 and one to python 3.
But to keep this repository as clean as possible it's time to say goodbye to packages that depend on python 2 (see #3633).

**Comment by ymartin59** [comment]
To notice:
- I am working on included openzwave for use with HomeAssistant #3638
- http://www.jadahl.com/ provides Domoticz with openzwave and many USB drivers for dongles packaged. It looks like it comes first from spksrc...

**Comment by hgy59** [comment]
This is fixed with commit c4f7229.
