### ISSUE TITLE
[Question] Medusa ugprade  requires python3

### ISSUE THREAD

**Issue by alexey-pimenov** [SynoCommunity/spksrc#3661]
The medusa team have switched over to python3 in recent update.
But since medusa is based on `sickbeard-custom` in is not possible to upgrade because base spk and service relies on python 2 only.

Question is should be this issue resolved by creating separate spk package for medusa only or it's better to generify `sickbeard-custom`?

**Comment by BenjV** [comment]
Medusa is running on both python 2.7 and python 3.5.
So sickbeard-custom can be used for running it on python 2.7.
Changing sickbeard-custom will prohibit others sickbeard forks which cannot run under python 3.5 to be used anymore.

Ading a new package for running Medusa under python 3.5 would be the best idea I think.
That way everybody can use his or hers own preference.

**Comment by Jamyz** [comment]
@BenjV i create the package and you can download [here](https://mega.nz/#!XxYC3Ybb!cdKtWua9x51afjJDeUt1cHKzvy0FH3vlPIGTogk_nSI)
Thanks @alexey-pimenov

**Comment by alexey-pimenov** [comment]
Closing because question was answered
