### ISSUE TITLE
ffmpeg CPU Usage with sub error.

### ISSUE THREAD

**Issue by beramodes** [SynoCommunity/spksrc#3664]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ffmpeg
_Package Version:_4.1-11

_NAS Model:_918+
_NAS Architecture:_ intel j3455
_DSM version:_6.2.1-23824 update 6

### Expected behavior
(UTF-8)SRT Subtitle should be appear on movie on transcoding.
And CPU Usage  should be 40~60% at single transcoding.

### Actual behavior
(UTF-8)SRT Subtitle breakdown to appear as like this "ㅁㅁㅁ ".
And CPU Usage is too high that i cannot run single 1080p mkv movie on synology 918+.

As so, I had uninstall ffmpeg however, subtitle and cpu usage was not replace to as before installation.

What should i do for restoring this codec.

If there is noway, I'm seriously thinking Synology factory reset .

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
![image](https://user-images.githubusercontent.com/47095492/54893178-ec4f0100-4ef7-11e9-8c2f-bd8175c00b1f.png)

Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```
ffmpeg_install.log
Fri Mar 22 14:10:40 KST 2019
===> Step preinst. USER= GROUP= SHARE_PATH=
Fri Mar 22 14:10:40 KST 2019
===> Step postinst. USER= GROUP= SHARE_PATH=

**Comment by BenjV** [comment]
What application do you use to play the video?

If it is Video Station it has nothing to do with the ffmpeg package of the SynoCommunity.
VideoStation uses its own bundled and specially patches ffmpeg from Synology itself and not the package from the SynoCommunity.

**Comment by beramodes** [comment]
I use to play plex app on android phone and also tested samsung smart tv plex app(2018). And I also my friends who are registered at my plex server say that they cannot play plex video on web version too.

**Comment by BenjV** [comment]
Plex installed from Synology Servers does the same thing and uses an patches versie of ffmpeg which bundled by Synology.

Transcoding is very cpu intensive depending from what exactly has to be transcoded so that is logical.
Wrong subtitles can be anything.
The subs in the video can be incorrect or plex assume the wrong format for the substitles.

**Comment by beramodes** [comment]
why i think that ffmpeg is the problom is. Before the installation, not only transcoring but also subtitle were ok on same movie. However, after the installation, the issue have happoned. As you say that plex also use ffmpeg bundled by Synology. But after the installation, it will use this package. Isn't it?

**Comment by BenjV** [comment]
No it will use the bundled ffmpeg.
It won't even be able to find the ffmpeg from the SynoCommunity.

In the case of Synology it will be a special version lacking functionality like eac audio because Synology did not buy the license from Dolby.

**Comment by beramodes** [comment]
I research Synology's bundle that Synology doesn't have any ffmpeg. So most users who want to play DTS or AC3, download ffmpeg from synocommunity.

**Comment by BenjV** [comment]
You are wrong. the ffmpeg they ship is inside the shipped library files.
In older releases they use to call the ffmpeg binary but they do not do that anymore.
Besides they  build in a check so you cannot replace the library.
If you don't belive me read these two threads: #3437 and #2952.

**Comment by beramodes** [comment]
@BenjV Thank you for your comments. I will try to figure out what is the reason for this problems. Your comments was so helpful for me.
