### ISSUE TITLE
Download Station Magnet uninstallation error.

### ISSUE THREAD

**Issue by beramodes** [SynoCommunity/spksrc#3665]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Download Station Magnet
_Package Version:_1.0-2

_NAS Model:_918+
_NAS Architecture:_intel j3455
_DSM version:_6.2.1-23824 update 6

### Expected behavior
I uninstalled the  app "Download Station Magnet" however,the app steels link to Download Station. So, I cannot use magnet link on my computer to run torrent program.

### Actual behavior
magnet was working when i run download station.
But i change Download Station to Transmission.
Problem are appear.  I uninstalled the  app "Download Station Magnet" however,the app steels link to Download Station. So, I cannot use magnet link on my computer.
How do i disable this app.  i tried to find "regedit", i cannot find it.
Could you help me to solve this? thank you.

**Comment by ymartin59** [comment]
@neykov Hello. May you please help about this issue? Thank you in advance.

**Comment by BenjV** [comment]
Never heard of the application "Download Station Magnet" for Synology where did you get it from.
Most likely is an browser add-on that redirect the magnetlinks when downloading them.

**Comment by ymartin59** [comment]
@BenjV As far as I remember about this package code, you're right - it registers Magnet URI protocol in browser to redirect into Download Station
@beramodes Please review your browser's application association, you should find magnet:// protocol associated with your DSM URL, try to discard such entry.

**Comment by beramodes** [comment]
@ymartin59 Thanks for the solution.  I will try to discard this option.

**Comment by neykov** [comment]
Oops just saw this ticket, apologies for missing it.
I'll see if I can add more detailed instructions for unregistering the magnet protocol association.
