### ISSUE TITLE
Update SABnzbd to 2.3.8

### ISSUE THREAD

**Issue by kc6108** [SynoCommunity/spksrc#3667]
Package Name: SABnzbd
Package Version: 2.3.7-38 (latest)

NAS Model: DS1812+
NAS Architecture: cedarview (x64)
DSM version: DSM 6.2.1-23824 Update 6 (latest)

Please update SABnzbd to 2.3.8

https://github.com/sabnzbd/sabnzbd/releases/tag/2.3.8

**Comment by ymartin59** [comment]
Hello @Safihre May you have some time to help about it? Thanks in advance
