### ISSUE TITLE
[Radarr] Bulk import doesn't work

### ISSUE THREAD

**Issue by AthAshino** [SynoCommunity/spksrc#3675]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ radarr
_Package Version:_ 20190320-8

_NAS Model:_ DS218+
_NAS Architecture:_ 
_DSM version:_ 6.2

### Expected behavior
When I use "bulk import" on my folder (which contains one folder per movie as excepted), I must import all of my movies on Radarr

### Actual behavior
When I use bulk import, this message appears: "No movies found in folder"

**Comment by BenjV** [comment]
Is internal functionality of Radarr and has nothing to do with the Synology Package of the SynoCommunity.
Please make an issue on the github of the Radarr developers.

**Comment by ymartin59** [comment]
@m4tt075 Hello. May you please help about it? Thank you in advance

**Comment by m4tt075** [comment]
Not a lot to add. Probably @BenjV is right. Or there is an issue with folder permissions. In that case our [Wiki](https://github.com/SynoCommunity/spksrc/wiki/Permission-Management) should help.
