### ISSUE TITLE
Jackett does not appear in search results (Beta packages enabled)

### ISSUE THREAD

**Issue by mullinmax** [SynoCommunity/spksrc#3677]
### Setup
Package Name: Jacket
Package Version: NA

NAS Model: DS918+
NAS Architecture: 
DSM version: DSM 6.2.1-23824 Update 6 

### Expected behavior

Once Package source has been added and beta packages enabled Jacket (and other beta packages) should appear in one of the tabs of the package center.

### Actual behavior
Jacket does not show up in any of the tabs
### Steps to reproduce
1. Setup community source 
2. Enable Beta packages
3. [¯\\_(ツ)_/¯](https://giphy.com/gifs/3o7aTskHEUdgCQAXde/html5)

#### Package log
NA

#### Other logs
NA

**Comment by m4tt075** [comment]
Hmh, that should be an `apollolake` model. The package is available here:
https://synocommunity.com/package/jackett#
Might be a refresh problem. Anyways, if it still doesn't show up, you can download and manually install it from that page...

**Comment by janusn** [comment]
Thanks @m4tt075 !

I have a DS918+ as well. Neither can I find the jackett package in mine running firmware DSM 6.2.2-24922 Update 2. It does not show up even after I deleted the source and added Synocommunity again. Therefore it is not a refresh problem.

**Comment by kswedberg** [comment]
I have a DS718+ running same firmware as @janusn. Same problem.

**Comment by ymartin59** [comment]
Correct. Both are `apollolake`. Have enabled "beta" flag in Package Center? Is "Mono" available already?

**Comment by ymartin59** [comment]
I propose you manually install packages:
- https://packages.synocommunity.com/mono/12/mono.v12.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-grantley-kvmx64-x86-x86_64].spk
- https://packages.synocommunity.com/jackett/8/jackett.v8.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-grantley-kvmx64-x86-x86_64].spk

**Comment by janusn** [comment]
@ymartin59 

Thank you for your suggestion of enabling beta in package center. I didn't aware of this option.

Unfortunately, Jackett is still not showing up on either "Beta Packages" pane nor "Community" pane.

Yes, I have already installed the Jackett and it works fine so far. I was just trying to report an issue to let developer aware of the it.

**Comment by ymartin59** [comment]
Package is visible from DSM 6.2 as far as "beta" option is checked.
By default, server settings have "auto-update" enabled, a simple stop/run package restart will update Jackett version.
