### ISSUE TITLE
Update Tiny Tiny RSS

### ISSUE THREAD

**Issue by update-freak** [SynoCommunity/spksrc#3678]
It would be great if someone could update the Tiny Tiny RSS app (https://synocommunity.com/package/tt-rss) to the latest version.
Currently the version is from 2016 (v20160102-10).
There are a few bugs that need fixing:
https://github.com/SynoCommunity/spksrc/issues/2217
https://www.synology-forum.de/showthread.html?96698-Einrichtung-von-Tiny-Tiny-RSS/page2

**Comment by tjaadvd** [comment]
This would make Tiny tiny rss work without having to SSH into your nas. I can imagine some people do not like to tweak their nas too much (like me).

**Comment by update-freak** [comment]
I want to point out again that this app urgently needs an update to the current version!

**Comment by Teryon** [comment]
I'm waiting for some help on this package I can't even uninstall it now :/

**Comment by mateMathieu** [comment]
+1

**Comment by notflip** [comment]
Is anyone else having issues running this? It immediatly stops again
PHP5.6 and MariaDB5 are installed

**Comment by smaarn** [comment]
Hello @notflip 

Could you please check using binaries available here: https://github.com/smaarn/spksrc/releases/tag/tt-rss-20201114 ? (It's basically the contents of PR #4274 and contains - among others - a few packaging changes with a new version of tiny tiny rss)

It should provide with more detailed logs under `/var/packages/tt-rss/target/var/logs/` directory and it should run the upgrade script automatically.

Best case scenario it works out of the box.
Worst case scenario... we may have some more information about where it failed.

**Comment by notflip** [comment]
Great! I'll give it a shot thanks.

**Comment by notflip** [comment]
@smaarn I see the following errors in the log

```
jq: error: Could not open file /var/packages/WebStation/etc/WebStation.json: No such file or directory
Failed identifying php profile name.
Failed computing PHP profile name
jq: error: Could not open file /var/packages/WebStation/etc/WebStation.json: No such file or directory
Failed identifying php profile name.
Failed computing PHP profile name
```

Should Webstation be enabled to use this package?

**Comment by smaarn** [comment]
> @smaarn I see the following errors in the log
> 
> 
> 
> ```
> 
> jq: error: Could not open file /var/packages/WebStation/etc/WebStation.json: No such file or directory
> 
> Failed identifying php profile name.
> 
> Failed computing PHP profile name
> 
> jq: error: Could not open file /var/packages/WebStation/etc/WebStation.json: No such file or directory
> 
> Failed identifying php profile name.
> 
> Failed computing PHP profile name
> 
> ```
> 
> 
> 
> Should Webstation be enabled to use this package?

@notflip I must confess I didn't know you could actually install Tiny Tiny RSS without WebStation. I'll try having a look tonight to ensure this doesn't happen.
To answer your question: yes you need WebStation.

**Comment by notflip** [comment]
@smaarn Thanks for getting back, I did manage to get it running although I'm receiving a "403 There was an error processing this request".

**Comment by smaarn** [comment]
> @smaarn Thanks for getting back, I did manage to get it running although I'm receiving a "403 There was an error processing this request".

Which request? You were trying to open the tt-rss page without going through the index page?

**Comment by notflip** [comment]
> > @smaarn Thanks for getting back, I did manage to get it running although I'm receiving a "403 There was an error processing this request".
> 
> Which request? You were trying to open the tt-rss page without going through the index page?

By going to the link it's proposing me: mynas.synology.me/tt-rss. What do you mean with going through the index page? Thank you

**Comment by notflip** [comment]
I do notice now that if, in webstation I switch nginx to apache, it's getting passed that error, now it's showing a PDO error, maybe I'm missing some packages that need to be installed?

**Comment by smaarn** [comment]
> > > @smaarn Thanks for getting back, I did manage to get it running although I'm receiving a "403 There was an error processing this request".
> 
> > 
> 
> > Which request? You were trying to open the tt-rss page without going through the index page?
> 
> 
> 
> By going to the link it's proposing me: [mynas].synology.me/tt-rss. What do you mean with going through the index page? Thank you

I must confess I never managed to use that link on my side.
Have you tried accessing it directly using the URL of your NAS without going through the synology helper ?

**Comment by notflip** [comment]
@smaarn I got it working! 

Needed to enable php extensions for my chosen PHP profile (PHP7.2)
In case anyone wonders, these are the extensions that need to be enabled

- intl
- mysqli
- pdo_mysql

**Comment by smaarn** [comment]
> @smaarn I got it working! 
> 
> 
> 
> Needed to enable php extensions for my chosen PHP profile (PHP7.2)
> 
> In case anyone wonders, these are the extensions that need to be enabled
> 
> 
> 
> - intl
> 
> - mysqli
> 
> - pdo_mysql

Actually there are several more but I'll recheck.
I believe I should add a little message about that. I had tried to check if it was possible to programmatically add those to the current profile but couldn't make it work.
