### ISSUE TITLE
WHY I can play dts in VideoStation，when I installed FFMPEG in SynoCommutity

### ISSUE THREAD

**Issue by jindaxia** [SynoCommunity/spksrc#3684]
I recognised that VideoStation has its own  ffmpeg which is 3.7.x，and use it as default，
seems  it‘s nothing to do with my installed  ffmpeg from synoCommutity

who can tell me why？

**Comment by BenjV** [comment]
Because Synology desides that.
Otherwise they must buy a licence from Dolby for all Nasses they chip and in the end we "the buyers" must pay more for a Nas.

**Comment by ymartin59** [comment]
Right. According to what I read when investigating, Dolby requests per-view fees "by default" - so requiring devices to collect DTS usage and report it to either Synology or Dolby for payment.
But I guess it may be possible to negotiate flat-fees...

By the way, replacement of embedded ffmpeg in VideoStation is discussed at https://github.com/SynoCommunity/spksrc/issues/3654#issuecomment-472307001
