### ISSUE TITLE
transmission 2.94-16 on DSM5.2 - after uexpected power fail do not connecting to any tracker

### ISSUE THREAD

**Issue by andylevi16** [SynoCommunity/spksrc#3696]
transmission 2.94-16 on DSM5.2 - after uexpected power fail do not connecting to any tracker

WEB UI Tellls Port is Closed
Remote GUI 5.16.0 tells Port Tested: HTTP Error 0: No Response

**Comment by BenjV** [comment]
Most likely a file got corrupted during the power fail.
Take a look at this file:
 /usr/local/etc/services.d/transmission.sc

This should be in that file:
[transmission]
title="Transmission"
desc="Transmission"
port_forward="yes"
dst.ports="9091/tcp"

If that does not work remove transmission and reinstall it.

**Comment by andylevi16** [comment]
Already realized very last suggestion two weeks ago. really works

**Comment by mreid-tt** [comment]
Is this issue considered resolved and can be closed?

**Comment by mreid-tt** [comment]
@andylevi16, seems that this issue has gone stale and I'll be closing it. feel free to re-open if the issue comes up again.
