### ISSUE TITLE
UPDATE: Jackett

### ISSUE THREAD

**Issue by Theli93** [SynoCommunity/spksrc#3697]
New message appearing in Jackett header.
I don't know if it will require any action from SynoCommunity

> Standalone version of Jackett is now available - Mono not required 
> To upgrade to the standalone version of Jackett, click here for install instructions. Upgrading is straight forward, your indexers and configuration will carry over. Benefits include: increased performance, improved stability and no dependency on Mono.

**Comment by ymartin59** [comment]
@m4tt075 Hello. May I ask you for a short answer, please. Thank you in advance

**Comment by m4tt075** [comment]
@Theli93 Yes, apparently the `Jackett` developers have been fed up with `mono` (can't blame them) and decided to offer an alternative version which runs without it. They offer binary and mono versions in parallel for the time being. Our package can just deal with the (partially problematic) mono version. Changing that would require adapations on our end. I stepped in maintaining those packages for some time as nobody else did it, but actually never used them myself. I'm sorry, but I neither have the time nor the motivation to look into this right now...

**Comment by Theli93** [comment]
@m4tt075, I understand. 
I won't say I'm not disappointed, but I earnestly do understand. 
Thank you for responding.

**Comment by Theli93** [comment]
related to #3715

**Comment by bolhaskutya** [comment]
I'd also like to to see this happen.
I offer my beta-testing services if someone steps up.

**Comment by BangisBanginis** [comment]
Currently jackett version is 0.12.1028. When running it I get warning that this package is seriously outdated and I need to update, but update is not available.
----
Synology DS218+

**Comment by Casuallynoted** [comment]
Would also be interested in this on my DS918+

**Comment by SpudR** [comment]
Can this please be updated? It's a few versions out of date now...

**Comment by publicarray** [comment]
If you have an Intel 64bit NAS I've just re-packaged Jackett standalone you can try it out here: https://github.com/publicarray/spksrc/releases/tag/Jackett-0.16.979

**Comment by Fogest** [comment]
You also should be able to download the old one too. As long as it is v3 you can just use the built-in Sonarr updater to update it. That's what I have been doing to keep it up to date and I've had no issues.

**Comment by mnervik** [comment]
Can confirm that this is working on DS1517+

**Comment by ymartin59** [comment]
@publicarray Is there a PR with Jackett standalone here?

**Comment by publicarray** [comment]
Not yet since it severely reduces architecture support at the moment. I hope to have time to do more on the weekend

**Comment by defaultsecurity** [comment]
It is working on DS918+. Thank you @publicarray for your work, time and consideration.

**Comment by hgy59** [comment]
done by #4207
