### ISSUE TITLE
Jabber / XMPP

### ISSUE THREAD

**Issue by pedalofilo** [SynoCommunity/spksrc#370]
Hello!
thanks for your work!

I've found you when searching for having a xmpp server running on my DS211j.

The goal is to have a transport/gateway for facebook running, so that I can use bind other im accounts on gtalk inside of gmail website or on android phone. All following concept of multi-protocol IM'ing through server opposed to clients.
There's already a couple of open servers with transports, but you have to always trust your passwords to them. And when we have a powerful NAS like these, why not to have our own!?

I already have ejabberd running under Debian chroot (thanks for that package!), but I'm having trouble with getting Spectrum 2 installed. Basically I don't know how to build it from source to ARM :(

Thanks,
##

**Comment by Zorgonaute84** [comment]
Hello,

MissileHunger had shut down at the begining of the year, so OpenFire is no longer available. Is the OpenFire integration to SynoCommunity is scheduled for the nexts months ?

**Comment by Diaoul** [comment]
If there is a request for it then I guess yes we can add it. I don't know the ETA though, developers work on their free time.
