### ISSUE TITLE
Transmission: High CPU usage caused by high speed download

### ISSUE THREAD

**Issue by nopoz** [SynoCommunity/spksrc#3700]
When the Download speed is high enough (20+ MB/s), Transmission (2.94-16) uses all the CPU and the UI becomes unresponsive. I have a Synology DS1815+ running DSM 6.2.1-23824 Update 4. This is already raised with the Transmission team at https://github.com/transmission/transmission/issues/888 but wondering if there is anything about the DSM specific transmission package that can be fixed/optimized to prevent this from happening?

**Comment by BenjV** [comment]
High speed means high cpu usage.
Only way to use less cpu is to limit the maximum downloadspeed within Transmission.

**Comment by doucheymcdoucherson** [comment]
I don't experience high CPU with transfer speeds in any other program. I can transfer files using CIFS to my NAS at 1Gb/s (the 1 gigabit network is the bottleneck) and I don't see this kind of CPU usage. I'm not downloading at near that speed with Transmission.

**Comment by ymartin59** [comment]
I propose to test using DSM traffic bandwidth limitation on Transmission ports to 10 MiB/s to at least confirm CPU is no longer overwhelm. Reference: https://www.synology.com/en-us/knowledgebase/DSM/help/DSM/AdminCenter/connection_network_trafficcontrol

**Comment by ymartin59** [comment]
There is also option to "renice" Transmission process to lower its priority over other processes.

**Comment by doucheymcdoucherson** [comment]
So my bad, I was misreading the top output. It's set to display CPU usage per core. Transmission only uses 1 core at 100% (25% overall on my 4 core CPU). If I type Shift+i in top, the CPU usage display will change to show overall usage across all cores. It would be nice if transmission could use all cores instead of keeping 1 at 100%.

**Comment by BenjV** [comment]
Why would dat be usefull?
Only if 100% of 1 core would limit the download speed it would be usefull to use more core's.
Just spreading the load among cores is useless and would hinder other applications more then keeping the load of transmission on one core.

By the way comparing CIF's filetransfer to downloading torrents is comparing apples with pears.
A torrent client has to deal with very small packets of data and has to do a lot of processing to build a file with all those packets.

If you try a CIFS file transfer with lots of very small files you get for or less the same effect.

**Comment by 1265578519** [comment]
https://github.com/transmission/transmission/issues/894

**Comment by L422Y** [comment]
In my 20+ years of working in technology as a developer and network engineer, I've never seen something quite like this before, my 2019 eight core MacBook Pro at running at 165º

It definitely feels like a problem with the way the buffers are handled, or resources are locked... my two cents.

**Comment by BenjV** [comment]
No sure what a MacBook problem has to do with a Synology Transmission package.
Maybe post this in a Mac forum?

**Comment by chickenandpork** [comment]
I think he’s saying “the application seems to generate a lot of busywait cycles, maybe there’s a problem”.  It’s possible that some versions of Linux or BSD also have a problem but if you don’t hear the fans spin up, you wouldn’t realize, for example.

Posting in a Mac forum would earn “doesn’t happen on any other app, seems like a Transmission problem”, which doesn’t get us anywhere either  :(

**Comment by BenjV** [comment]
Without posting cpu type , speed (up and download) , number of used slots enz. this is just wild guessing.
If there are enough seeders and leechers and you have a fast enough internet connection, then it will eat up any cpu power available  (when you don't limit transmission with the correct setting ).

Like I said before, a torrent client like transmission has a lot of processing to do and if the topic starter had a download speed of 20 MB/s which amount of 160Mbit/sec it seems very normal to me that this will need a lot of cpu power.

**Comment by nopoz** [comment]
I had to switch to Deluge because of this issue. I can max out my connection (75 MB/sec) with Deluge and it uses a lot of CPU but certainly doesn't max it out. The DS1815+ has a Intel Atom C2538 - which is a quad core cpu.

**Comment by L422Y** [comment]
totally wrong repo – not sure how that happened!

**Comment by mreid-tt** [comment]
Is this issue considered resolved and can be closed?

**Comment by mreid-tt** [comment]
@nopoz, seems that this issue has gone stale and I'll be closing it. feel free to re-open if the issue comes up again.
