### ISSUE TITLE
https support for ffmpeg

### ISSUE THREAD

**Issue by matthieumary** [SynoCommunity/spksrc#3701]
_For new Package Requests, see the guidelines_  

### Setup
package ffmpeg 4.1.11

Synology 918+
Architecture i686
DSM version 6..2.1

### Expected behavior
ffmpeg -protocols include both in input and output https. 

### Actual behavior
ffmpeg -protocols
ffmpeg version 2.7.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
  configuration: --prefix=/usr --incdir='${prefix}/include/ffmpeg' --arch=i686 --target-os=linux --cross-prefix=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-shared --disable-static --enable-version3 --enable-nonfree --enable-libfaac --enable-encoders --enable-pthreads --disable-bzlib --disable-protocol=rtp --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffserver --disable-ffplay --disable-devices --disable-bzlib --disable-altivec --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --disable-vaapi --disable-decoder=amrnb --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-encoder=zmbv --disable-encoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=dca --disable-decoder=eac3 --disable-decoder=truehd --cc=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc --enable-yasm --enable-libx264 --enable-encoder=libx264
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Supported file protocols:
Input:
  cache
  concat
  crypto
  data
  ffrtmphttp
  file
  ftp
  gopher
  hls
  http
  httpproxy
  mmsh
  mmst
  pipe
  rtmp
  rtmpt
  subfile
  tcp
  udp
  udplite
  unix
Output:
  crypto
  ffrtmphttp
  file
  ftp
  gopher
  http
  httpproxy
  icecast
  md5
  pipe
  rtmp
  rtmpt
  tcp
  udp
  udplite
  unix

### Steps to reproduce
install ffmpeg from the package center
open a terminal on the synology nas
ffmpeg -protocols

**Comment by BenjV** [comment]
ffmpeg does not support http or https as in -or output protocol so it is not possible.
Only way is to ask for a change request at the ffmpeg developers on, but I am not sure what use https would have for a package as ffmpeg.


Not sure what you want.

**Comment by ymartin59** [comment]
@matthieumary Please notice "ffmpeg" output: `ffmpeg version 2.7.1 Copyright (c) 2000-2015 the FFmpeg developers`
- `which ffmpeg` will answer /bin/ffmpeg which is DSM embedded ffmpeg 2.7 version
- SynoCommunity ffmpeg package is accessible at `/usr/local/ffmeg/bin/ffmpeg`
- `/usr/local/ffmeg/bin/ffmpeg -protocols` reports https as expected

We prefer not to replace original ffmpeg at package installation to prefer side-effects and potential failures with other DSM tools or packages.
