### ISSUE TITLE
gevent compilation fails

### ISSUE THREAD

**Issue by ghost** [SynoCommunity/spksrc#3704]
### Setup
Package Name: gevent
Package Version: 

NAS Architecture: armada370
DSM version: 6.1 

### Expected behavior
Executing `make arch-armada370` in the directory `spksrc/cross/gevent` should normally compile the gevent module

### Actual behavior
Compilation of the dependencies works successful. The compilation of gevent fails with the error message:
`env: '-c': No such file or directory`

### Steps to reproduce
_1._ Clone the spksrc repository from GitHub
_2._ `cd spksrc/cross/gevent` 
_3._ `make arch-armada370`

**Comment by ymartin59** [comment]
Related to #3648, #3346 and #3672

**Comment by hgy59** [comment]
This is the case with all cross builds that include `../../mk/spksrc.python-wheel.mk` (except libtorrent)
reproduced with:
- borgbackup
- duplicity
- gevent
- greenlet
- immutables
- _libtorrent_ (has a lot of dependencies, fails on a dependency, but on retry it continues to build, but finally fails with different error)
- lxml
- m2crypto
- mercurial
- msgpack-python
- pillow
- pocketsphinx
- pyalsa
- pyaudio
- pycurl
- pyyaml
- pyzmq
- ruamel.yaml
- sphixbase
- umemcache
- uwsgi

Good for analysis are greenlet, immutables, mercurial and others that have no dependencies and fail fast.

**Comment by hgy59** [comment]
it is not possible to build packages that build with spksrc.python-wheel.mk in the cross/package folder. This is by design of spksrc.
