### ISSUE TITLE
Personal dvb channel list file location?

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#3705]
### Setup
_Package Name:_ tvheadend
_Package Version:_ 4.2.8-16

_NAS Model:_ 918+
_NAS Architecture:_ apollolake 
_DSM version:_ 6.2.2

### Expected behavior
Unable to find a location where to put my dvb channel list file so it gets loaded and selectable in the pre-defined mux list configuration web interface for channel scanning.

### Actual behavior
Tried dropping my dvb channel list to:
`/volume1/@appstore/tvheadend/share/tvheadend/data/dvb-scan/atsc/`
and
`/usr/local/tvheadend/share/tvheadend/data/dvb-scan/atsc`
but the configuration interface doesn't list it.
On my Ubuntu version I used to drop it into:
`/usr/share/tvheadend/data/dvb-scan/atsc/`
And my dvb channel list file gets detected and is made available through the pre-defined mux list select box (I don't recall even restarting tvh).

### Steps to reproduce
_1._ Drop the new channel list and ensure permissions are ok:
```
$ sudo cp -p dvb_channel.conf /volume1/@appstore/tvheadend/share/tvheadend/data/dvb-scan/atsc/ca-QC-saint-jean-sur-richelieu
$ sudo chmod 0644 /volume1/@appstore/tvheadend/share/tvheadend/data/dvb-scan/atsc/ca-QC-saint-jean-sur-richelieu
$ sudo chown sc-tvheadend:tvheadend /volume1/@appstore/tvheadend/share/tvheadend/data/dvb-scan/atsc/ca-QC-saint-jean-sur-richelieu
```
_2._ Restart tvheadend:
```
$ sudo synoservice --restart pkgctl-tvheadend
```
_3._ Try selecting the dvb channel list in the configuration wizard or through force scan

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
@m4tt075 May you please help about it? Thank you in advance

**Comment by th0ma7** [comment]
I did ended-up finding where to put the file:
```
$ sudo cp -p dvb_channel.conf /volume1/@appstore/tvheadend/share/tvheadend/data/dvb-scan/atsc/ca-QC-myplace
```
OR, same location (due to higher-level symlink)
```
$ sudo cp -p dvb_channel.conf /usr/local/tvheadend/share/tvheadend/data/dvb-scan/atsc/ca-QC-myplace
```
Then adjust permissions:
```
$ sudo chmod 0644 /volume1/@appstore/tvheadend/share/tvheadend/data/dvb-scan/atsc/ca-QC-myplace
$ sudo chown sc-tvheadend:tvheadend /volume1/@appstore/tvheadend/share/tvheadend/data/dvb-scan/atsc/ca-QC-myplace
```
For it to appear in the web interface **you must** logout/login.
