### ISSUE TITLE
[Request] Mediainfo update

### ISSUE THREAD

**Issue by WodKa78** [SynoCommunity/spksrc#3708]
It would be great if someone can update Mediainfo to 17.12-06--->19.04
Thanks in advance....

**Comment by hgy59** [comment]
the mediainfo spk uses the source code from sourceforge.net. The package is already updated to the newest version available at sf.net (Version 18.08.1). 
It was updated with the sonarr update for v3 (upgrade compatibility) but the packages on the synocommunity download page are not uptodate.
@ymartin59 can you publish the current version of mediainfo?

It looks like the sf.net repository is not updated anymore and we should switch to the [github](https://github.com/MediaArea/MediaInfo/) repository.

**Comment by ymartin59** [comment]
Update published

**Comment by WodKa78** [comment]
Thanks a lot
