### ISSUE TITLE
sslh - common.c:216:setsockopt: Operation not permitted

### ISSUE THREAD

**Issue by linuxdep** [SynoCommunity/spksrc#3714]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ sslh
_Package Version:_ 1.19c-3

_NAS Model:_ DS918+
_NAS Architecture:_ 
_DSM version:_ DSM 6.2.2-24922

### Expected behavior
Tell us what should happen
can you pease update to new version? I think with 
make USELIBCAP=1
sudo make install

i found this issue https://github.com/yrutschle/sslh/issues/217, but i think you understand this better..

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
...
connecting to localhost:8443 family 2 len 16
common.c:216:setsockopt: Operation not permitted

**Comment by th0ma7** [comment]
Can you check if issue still exists with updated package that was just published (1.21c-4)
Package should be available shortly (e.g. hours/days) once proxy cache updates.

**Comment by th0ma7** [comment]
@linuxdep  I've re-looked at the issue and may have a possible fix.
I've created temporary packages for you to test at: 
https://github.com/th0ma7/synology/tree/master/packages/sslh-linuxdep

**Comment by th0ma7** [comment]
Updated packages with `libcap` supported uploaded.
Should be available shortly once proxy cache updates.

**Comment by linuxdep** [comment]
i test it this week... but istall ...21c-4 has not correct status in packetcenter
VPN was not work, but short test...

**Comment by th0ma7** [comment]
An updated package version `1.21c-5` is now available and should appear shortly as an update (or download directly from https://synocommunity.com/package/sslh).  That new version has libcap support included.
