### ISSUE TITLE
Add .Net Core support for SynoCommunity packages

### ISSUE THREAD

**Issue by epheterson** [SynoCommunity/spksrc#3715]
Mono has lead to lots of instability with Jackett on Synology NAS (fortunately not as much lately!), so it's refreshing to see there's a variant of Jackett which doesn't use Mono.

Unfortunately, the de-facto way to install Jacket on Synology is via the SynoCommunity package installer source, which is still pointing to the Mono variant.

Can we please get a SynoCommunity update that removes the dependence on Mono?

Thanks!

**Comment by BenjV** [comment]
I suspect you hoped you could use Jacket with .net core instead of mono but unfortunately there is no .net core for Synology so mono is the only option at the moment.

**Comment by publicarray** [comment]
Jackett has been moved to .net. Still remaining is Sonarr

**Comment by hgy59** [comment]
done by #4207
