### ISSUE TITLE
ffmpeg dts wav failed due to -write_info_tag option

### ISSUE THREAD

**Issue by xkyo** [SynoCommunity/spksrc#3716]
Package Name: FFMPEG
Package Version: 4.1

NAS Model: DS918+
NAS Architecture: X86
DSM version: DSM 6.2.1

in audio station, when transcode is set to WAV, the ffmpeg running command in DSM server is something like this:
ffmpeg -v 0 -ss 0 -t 365 -i test.wav  -vn -f wav -c:a pcm_s16le -af aresample=resampler=soxr -ar 44100 -ac 2 -write_info_tag 0 out.wav
with ffmpeg4.1, nothing is generated. If you remove -write_info_tag 0, the out.wav is generated as expected, looks like latest ffmpeg package does not support -write_info_tag

**Comment by cytec** [comment]
the ffmpeg package we provide and the one used by audio/video station is not the same!

for AudioStation:

```
/volume1/@appstore/AudioStation/bin/ffmpeg -buildconf
ffmpeg version 3.3.7 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
  configuration: --arch=i686 --target-os=linux --cross-prefix=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --enable-cross-compile --enable-optimizations --enable-pic --enable-shared --disable-static --enable-version3 --enable-encoders --enable-pthreads --enable-libmp3lame --enable-libsoxr --disable-swscale-alpha --disable-postproc --disable-ffserver --disable-ffplay --disable-bzlib --disable-altivec --disable-indev=alsa --disable-outdev=alsa --disable-encoder=zmbv --disable-encoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-decoder=amrnb --disable-decoder=dca --disable-decoder=eac3 --disable-decoder=truehd --enable-avresample --disable-doc --enable-openssl
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100

  configuration:
    --arch=i686
    --target-os=linux
    --cross-prefix=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-
    --enable-cross-compile
    --enable-optimizations
    --enable-pic
    --enable-shared
    --disable-static
    --enable-version3
    --enable-encoders
    --enable-pthreads
    --enable-libmp3lame
    --enable-libsoxr
    --disable-swscale-alpha
    --disable-postproc
    --disable-ffserver
    --disable-ffplay
    --disable-bzlib
    --disable-altivec
    --disable-indev=alsa
    --disable-outdev=alsa
    --disable-encoder=zmbv
    --disable-encoder=dca
    --disable-encoder=ac3
    --disable-encoder=ac3_fixed
    --disable-encoder=eac3
    --disable-decoder=ac3
    --disable-decoder=ac3_fixed
    --disable-decoder=amrnb
    --disable-decoder=dca
    --disable-decoder=eac3
    --disable-decoder=truehd
    --enable-avresample
    --disable-doc
    --enable-openssl
```

also ffmpeg versions shipped by Audi/Video Station are (or at least they where) (heavily) patched by Synology

**Comment by ymartin59** [comment]
@cytec Welcome back. If you have some spare time to investigate how to improve ffmpeg pacakges, I recommend to look at #2952 where idea to report Synology patch (which does not look so large) into ffmpeg SynoCommunity package is "in progress"...

**Comment by th0ma7** [comment]
@xkyo,
I may have a [patch](https://github.com/th0ma7/spksrc/blob/ffmpeg-evansport/cross/ffmpeg/patches-reject/104-REJECT-SYNO-write-riff-info-tag-to-wav.patch) for this which could be relatively trivial to add to my next build.  Will keep you posted at next round of packages.

**Comment by th0ma7** [comment]
@xkyo and @cytec ,
Having new packages ready for testing here:
* https://github.com/th0ma7/synology/tree/master/packages

Use package version `-25` which should now contain the fix you are looking for.

**Comment by Xeroxxx** [comment]
Hello,
I searched through different issues. Is the new ffmpeg package not symlinking/replacing the ffmpeg delivered with VideoStation or am I doing something wrong? If this should work I'm happy to create an issue and post logfiles.

**Comment by th0ma7** [comment]
I recommend you to have a look at the script wrapper that was created by @BenjaminPoncet located here: https://gist.github.com/BenjaminPoncet
There are multiple variant depending of your arch one might work better than the other.
Log files would definitively help to understand what's going on as otherwise it's simply impossible.
Thnx in advance.

**Comment by th0ma7** [comment]
@Xeroxxx , @xkyo or @cytec any updates on this?

**Comment by th0ma7** [comment]
Closing, no updates.
Should normally be fixed with upcoming new release.
