### ISSUE TITLE
[package request] Synology Chat for unsupported DiskStation models

### ISSUE THREAD

**Issue by kekukui** [SynoCommunity/spksrc#3721]
The **Synology Chat** application does not appear in the official Synology repo for some of the cheaper DiskStation models.  Is it really incompatible, or could the installer be hosted here ?

https://www.synology.com/en-us/dsm/packages/Chat
https://www.androidpolice.com/2016/10/13/synology-chat-instant-messaging-application-runs-off-private-server/

**Comment by BenjV** [comment]
It is a Synology Package, so ask them!

**Comment by ymartin59** [comment]
Please submit request at https://forum.synology.com/
