### ISSUE TITLE
Povray successfully compiled for braswell arch but binary generate a core dump

### ISSUE THREAD

**Issue by digitalbox94** [SynoCommunity/spksrc#3724]
### Setup
_Package Name:_ 
_Package Version:_ 

_NAS Model:_  DS716+II
_NAS Architecture:_ braswell
_DSM version:_ 6.1

### Expected behavior
Povray binary should run successfully like on my ubuntu machine

### Actual behavior
Povray binary is generating a core dump when run on my DS716+II NAS (braswell)

### Steps to reproduce
_1._ Create a new package in the cross directory :

Makefile to create : 

PKG_NAME = povray
PKG_VERS = 3.7.0.8
PKG_EXT = tar.gz
PKG_DIST_NAME = v$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/POV-Ray/povray/archive
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/zlib cross/boost cross/libjpeg cross/libpng cross/libtiff

HOMEPAGE = http://www.povray.org/
COMMENT  = This is POV-Ray v3.7.0.8, a maintenance update of POV-Ray v3.7.0, intended to further improve source code compatibility with Mac OS builds.
LICENSE  = GPLv2

CONFIGURE_TARGET = myConfigure

GNU_CONFIGURE = 1

CONFIGURE_ARGS = COMPILED_BY="DigitalBox" --disable-debug --disable-dependency-tracking --without-libsdl --without-x --without-openexr --with-boost=$(WORK_DIR)/install/var/packages/target/ --host=i486-pc-linux --build=x86_64

include ../../mk/spksrc.cross-cc.mk

.PHONY: myConfigure
myConfigure:
        @cd $(WORK_DIR)/$(PKG_DIR)/unix && ./prebuild.sh
        $(RUN) ./configure $(CONFIGURE_ARGS)

PLIST file to create : 

bin:bin/povray

_2._  Launch the below command : 
make digests
make arch-braswell

_3._ Once the program is compiled, create a tar.gz file of the whole "target" directory (located in "work" directory) and transfer this tar.gz file on your Nas then on the NAS : 
export LD_LIBRARY_PATH=/volume1/homes/yoursuser/target/lib
cd target/bin
povray --help

#### Other logs
A core dump is generated but I'm unable to identify the root cause

**Comment by digitalbox94** [comment]
I've been able to do a quick debug with gdbserver and I have the below details : 
Program received signal SIGILL, Illegal instruction.
0x000000000041d2b4 in boost::exception_ptr boost::exception_detail::get_static_exception_object<boost::exception_detail::bad_alloc_>() ()

**Comment by digitalbox94** [comment]
I've made an investigation by comparing executable format between "htop" generated with Spksrc from cross and I have the below difference on my NAS with poverty : 

file ./povray 
./povray: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped

file ./htop 
./htop: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped

Is it an issue to have GNU/Linux instead of SYSV format ?

**Comment by digitalbox94** [comment]
I'm closing this issue, as it might be a VM memory issue because now I have POV-Ray compiled successfully for braswell : 

./povray --help
Persistence of Vision(tm) Ray Tracer Version 3.7.0.8.unofficial
 (x86_64-pc-linux-gnu-g++ 4.9.3 @ x86_64-pc-none)
This is an unofficial version compiled by:
 DigitalBox
 The POV-Ray Team is not responsible for supporting this version.

POV-Ray is based on DKBTrace 2.12 by David K. Buck & Aaron A. Collins
Copyright 1991-2013 Persistence of Vision Raytracer Pty. Ltd.

**Comment by digitalbox94** [comment]
<img width="1077" alt="povray-nas-synology" src="https://user-images.githubusercontent.com/25862070/60116298-0e1a8700-9778-11e9-85ea-6326408b388b.png">

**Comment by ymartin59** [comment]
@digitalbox94 You have decided to close your DKB-Tracer PR. I do not know what is your motivation to run POV-Ray on Synology DSM - but in my opinion such a tool is far from what users expect to do with a NAS which is "storage oriented".
