### ISSUE TITLE
Synology developes, can you help me with a package?

### ISSUE THREAD

**Issue by sbhoopesh** [SynoCommunity/spksrc#3727]
_For new Package Requests, see the guidelines_  

_NAS Model: 218
_NAS Architecture: dont know
_DSM version: 6.2.2

I need a Synology package that will search for image files from selected drives/folders and pull it (cut and paste) to selected folder, but paste it based on given criteria (example to folders based on year, month of the exif data or file name data).

**Comment by BenjV** [comment]
The SynoCommunity does not write applications.
Here we just package existing applications for installation on a Synology Nas.

**Comment by ymartin59** [comment]
@sbhoopesh I propose you write a script with your "images move logic" either in Bash, Perl or Python and trigger it regularly as task in scheduler or cron job. As a starting point, you may refer to: http://www.nicnocquee.com/2016/01/13/organize-photos-via-command-line.html

For photo management, you may refer to http://www.techblogger.io/2018/05/automatically-catalog-years-of-photos-with-synology-moments/

**Comment by hgy59** [comment]
out of topic
