### ISSUE TITLE
Is "DSM_UI_DIR" broken?

### ISSUE THREAD

**Issue by fredrike** [SynoCommunity/spksrc#3730]
I'm building a new package with support for hass.io and it seems like `DSM_UI_DIR` is ignored when building the package.

**Comment by ymartin59** [comment]
Hello. I hope you mean a new version based on https://github.com/SynoCommunity/spksrc/tree/master/spk/homeassistant

I am not aware of any issue with `DSM_UI_DIR`: https://github.com/SynoCommunity/spksrc/wiki/Makefile-variables

Please check files generated in `staging/app` if `DSM_UI_DIR=app` which is defaults.

**Comment by fredrike** [comment]
No, hass.io is a wrapper for homeassistant that uses Docker with support for addons. It have a slightly other use.

The generated package does not create ui shortcuts (and none ot the spk packages do have that).

**Comment by fredrike** [comment]
> Please check files generated in `staging/app` if `DSM_UI_DIR=app` which is defaults.

Yes you are right, images are generated but the `config` in `DSM_UI_DIR` does not follow and it is unclear how to make the `app` show up in Synology (I've not seen one single SynoCommunity package that creates an icon).

**Comment by BenjV** [comment]
You should check the .spk 
Within the .spk there is a file package.tgz and within that .tgz  a file called package.tar.
In that file there should be a folder "\app\images" where the icons should be located.
In the INFO file in the root of the .spk his line should be available
dsmuidir="app"

If all that is correct the problem is most likely the fact that you are using docker.

**Comment by fredrike** [comment]
The transmission spk doesn't have an shortcut either (on DSM 6.1). 

My issue here is trying to reflect the case that shortcuts (icons) from synocommunity does not seem to work.

**Comment by BenjV** [comment]
Then you are the only one.
I have dozens of packages form the SynoCommunity on my Test Nas and all are having shortcut icons.

If you are not logged in as admin and you did not give permissions to that user to use the package then you will not see the icons.

**Comment by fredrike** [comment]
I'm logged in as admin.

OK, I'll investigate more.
