### ISSUE TITLE
Comskip can not open file.

### ISSUE THREAD

**Issue by lost101** [SynoCommunity/spksrc#3735]
I am trying to get Comskip going, but it looks like I am hitting a roadblock.
I verified that permission allow to access DVR folders but still no go. DVR folder permission is set to  0777.
After the attempt to start comskip i get a comskip.txt that is empty inside DVR folder.
I am following install process from [https://github.com/SynoCommunity/spksrc/wiki/Comskip ](https://github.com/SynoCommunity/spksrc/wiki/Comskip ) 
Any advice or known issues?
### Setup
_Package Name:_ comskip 
_Package Version:_ 0.82.006

_NAS Model:_DS 918+
_NAS Architecture:_ apollolake (x64)
_DSM version:_  6.2

### Expected behavior
 Process file in the folder
 

### Actual behavior
/volume1/@appstore/comskip/bin/comskip.ini: Can not open file

### Steps to reproduce
_1._  launch  manually

#### Package log

```
NA
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
root@DiskStation:~# comskip /volume1/@appstore/comskip/bin/comskip.ini /volume1/downloads/DVR/Nature
Comskip 0.82.006, made using ffmpeg
Donator build
The commandline used was:
comskip /volume1/@appstore/comskip/bin/comskip.ini /volume1/downloads/DVR/Nature

Using /volume1/@appstore/comskip/bin/comskip.ini for initiation values.
/volume1/@appstore/comskip/bin/comskip.ini: Can not open file
/volume1/@appstore/comskip/bin/comskip.ini: Can not open file
/volume1/@appstore/comskip/bin/comskip.ini: Can not open file
/volume1/@appstore/comskip/bin/comskip.ini: Can not open file
/volume1/@appstore/comskip/bin/comskip.ini: Can not open file


OR

root@DiskStation:~# comskip /volume1/downloads/DVR/Nature
Comskip 0.82.006, made using ffmpeg
Donator build
The commandline used was:
comskip /volume1/downloads/DVR/Nature

No INI file found in current directory.  Searching PATH...
INI file found at comskip.ini
No INI file found anywhere!!!!
/volume1/downloads/DVR/Nature: Can not open file
/volume1/downloads/DVR/Nature: Can not open file
/volume1/downloads/DVR/Nature: Can not open file
/volume1/downloads/DVR/Nature: Can not open file
/volume1/downloads/DVR/Nature: Can not open file
/volume1/downloads/DVR/Nature: Can not open file
/volume1/downloads/DVR/Nature: Can not open file



```

**Comment by BenjV** [comment]
Most likely you need to be root to do this.
Try sudo in front of the command.

**Comment by lost101** [comment]
> Most likely you need to be root to do this.
> Try sudo in front of the command.

It is root user and I also tried with sudo in front but same outcome. 
I am really puzzled  here because to me this is pointing to a permission issue but permission is set o 0777 for the whole (download) folder and subfolders .

**Comment by BenjV** [comment]
That is not possible, on a DSM system you cannot be the user root, admin is the max you can be.
You can only use root privs via the sudo command.

But the real problem is that your command is faulty.
You obvious did not read the commandspecs of comskip.

So use this command:

> comskip --ini=/var/packages/comskip/target/var/comskip.ini /volume1/downloads/DVR/Nature

or:

> comskip --ini=/volume1/@appstore/comskip/bin/comskip.ini/volume1/downloads/DVR/Nature

The first command is preferable because this will always work, even if you installed the comskip package on a diferent volume

**Comment by lost101** [comment]
> That is not possible, on a DSM system you cannot be the user "root"(unless you have a very old DSM version), "admin" is the max you can be.
> You can only use root privs via the sudo command.
> 
> But the real problem is that your command is faulty.
> You obvious did not read the commandspecs of comskip.
> 
> So use this command:
> 
> > comskip --ini=/var/packages/comskip/target/var/comskip.ini /volume1/downloads/DVR/Nature
> 
> or:
> 
> > comskip --ini=/volume1/@appstore/comskip/bin/comskip.ini/volume1/downloads/DVR/Nature
> 
> The first command is preferable because this will always work, even if you installed the comskip package on a diferent volume

Thank you so much! finally some success for me.
Is this the correct command in TVH for  post process?
`comskip --ini=/volume1/@appstore/comskip/bin/comskip.ini "%f"
`
I have followed [https://github.com/SynoCommunity/spksrc/wiki/Comskip](url) to the best of my abilities but  is not working. TVH initiates the script after recording but something fails.
 
`tvheadend-pp.sh`

#!/bin/sh
 
INPUTVIDEO="$1"  # Full path to recording, i.e. /home/user/Videos/News.ts
 
BASENAME=`/usr/bin/basename $INPUTVIDEO .mkv`
 
DIRNAME=`/usr/bin/dirname $INPUTVIDEO`
EDLFILE="$DIRNAME/$BASENAME.edl"
LOGFILE="$DIRNAME/$BASENAME.log"
TXTFILE="$DIRNAME/$BASENAME.txt"
LOGOFILE="$DIRNAME/$BASENAME.logo.txt"
COMSKIPPATH="/volume1/@appstore/comskip/bin/comskip"
COMSKIPINI="/volume1/@appstore/comskip/var/comskip.ini"
COMSKIPLOGS="/volume1/downloads/Logs/comskip/comskip"
TVHEADENDPP="/volume1/downloads/Logs/tvheadend/tvheadend"
 
CreateLog(){
    echo "***** CREATE LOG *****" >> ${TVHEADENDPP}/tvheadendpp$$.log
    echo "*****" > ${TVHEADENDPP}/tvheadendpp$$.log
    echo "***** INPUT = $INPUTVIDEO *****" >> ${TVHEADENDPP}/tvheadendpp$$.log
    echo "*****" >> ${TVHEADENDPP}/tvheadendpp$$.log
}
 
FlagCommercials(){
    echo "Starting Commercial Flagging" >> ${TVHEADENDPP}/tvheadendpp$$.log
    echo "*****" >> ${TVHEADENDPP}/tvheadendpp$$.log
    echo "***** OUTPUT = "$EDLFILE" *****" >> ${TVHEADENDPP}/tvheadendpp$$.log
    echo "*****" >> ${TVHEADENDPP}/tvheadendpp$$.log
    /usr/bin/whoami >> ${TVHEADENDPP}/tvheadendpp$$.log    # for debugging purposes, who is running this script?
    echo "Started at `/bin/date`" >> ${TVHEADENDPP}/tvheadendpp$$.log
    echo "*****" >> ${TVHEADENDPP}/tvheadendpp$$.log
    echo "*****" >> ${TVHEADENDPP}/tvheadendpp$$.log
 
    $COMSKIPPATH --ini=$COMSKIPINI $INPUTVIDEO 2>&1 </dev/null >> ${TVHEADENDPP}/tvheadendpp$$.log
 
    echo "*****" >> ${TVHEADENDPP}/tvheadendpp$$.log
    echo "*****" >> ${TVHEADENDPP}/tvheadendpp$$.log
 
    echo "EDL for $INPUTVIDEO:" >> ${TVHEADENDPP}/tvheadendpp$$.log
}
 
CleanUp(){
    echo "***** CLEAN UP *****" >> ${TVHEADENDPP}/tvheadendpp$$.log
    echo "[[ ! -f $LOGFILE ]] || /bin/mv $LOGFILE $COMSKIPLOGS"
    echo "[[ ! -f $TXTFILE ]] || /bin/mv $TXTFILE $COMSKIPLOGS"
    /bin/mv $LOGFILE $COMSKIPLOGS
    /bin/mv $TXTFILE $COMSKIPLOGS
}      
 
CreateLog
FlagCommercials
CleanUp
 
echo "Finished at `/bin/date`" >> `${TVHEADENDPP}/tvheadendpp$$.log`

**Is this where the script goes?** 
`TVHEADENDPP="/volume1/downloads/Logs/tvheadend/tvheadend" `

**Comment by BenjV** [comment]
I cannot help you with this.
I don't use tvheadend or comskip at all.
You are on your own now.

**Comment by ymartin59** [comment]
@m4tt075 May you please help about it?

**Comment by lost101** [comment]
I am still grinding at this, but so far no progress. 
Any suggestions or pointers are very welcome.

**Pointed to correct folder for comskip, comskip.ini, **
TVH command is `/usr/local/comskip/var/tvheadend-pp.sh %f`
tvheadend-pp.sh  
```
#!/bin/sh
INPUTVIDEO="$1"  # Full path to recording, i.e. /home/user/Videos/News.ts
COMSKIPPATH="/usr/local/comskip/bin/comskip"
COMSKIPINI="/usr/local/comskip/var/comskip.ini"

FlagCommercials(){
    $COMSKIPPATH --ini=$COMSKIPINI "$INPUTVIDEO"
}

FlagCommercials

```
Manual initiation doe work by using ` comskip --ini=/volume1/@appstore/comskip/bin/comskip.ini "/volume1/downloads/DVR/Dateline NBC/Dateline NBC-15.ts"`

**Comment by BenjV** [comment]
If the tvheadend-pp.sh not starts from Tvheadend when a recording is finished you better ask this in a tvheadend forum.
If it is started, post the logfile created by the script.
Maybe add a redirection of stdout and stderr to a file so you can see what is going on.
For that you add these lines to the beginning of the script as the first 3 lines.

> set -x 
> exec >> /volume1/downloads/Logs/tvheadend/test.log
> exec 2>&1

**Comment by lost101** [comment]
BenjV thank you for your help.
Unfortunately there is no log file created when TVH indicates that script was started. It looks like the script fails to execute and that is probably my issue here.  
This is from TVH:
```
2019-07-16 18:22:22.214 spawn: Executing "/usr/local/comskip/var/tvheadend-pp.sh"
2019-07-16 18:22:22.216 dvr: "Heartland" on "33.4 KMUMCD4": End of program: Completed OK
```

just this alone also fails

```
#!/bin/sh

set -x
exec >> /volume1/downloads/Logs/tvheadend/test.log
exec 2>&1

```
no log file created in the ` /volume1/downloads/Logs/tvheadend/test.log`

**Comment by BenjV** [comment]
Then the conclusion is that TVheadend does not run the script at all.
Could be a permission problem.

**Comment by lost101** [comment]
At this point I am giving up as changing permissions did not help.
Original problem was solved.
