### ISSUE TITLE
Shared folder does not exist

### ISSUE THREAD

**Issue by Nemrod7** [SynoCommunity/spksrc#3736]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Sonarr
_Package Version:_ 20190320-15

_NAS Model:_ DS916+
_NAS Architecture:_ Intel Pentium N3710
_DSM version:_ 6.2.2-24922

### Expected behavior
Downloaded files should be transferred from the share [Downloaded] to the share [Video], subfolder [Series].

### Actual behavior
Since yesterday evening the downloaded files are no longer transferred to the shared directory [Video], in the subdirectory [Series]. The transfer is done if I remove the Series category from Sonarr.

This used to work before, I don't see any Sonarr or DSM updates. I checked the dedicated user account, it has good access to the directories [Download] & [Video], as well as DS, FS & Sonarr.

### Steps to reproduce
_1._ Download a file

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
http://pasted.co/45748845

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
You cannot use what you call "the dedicated user account" for giving access rights, it has to be done via the group sc-download.

**Comment by Nemrod7** [comment]
I have created a dedicated user account in order to no longer use my administrator account. This new account is used to identify me at the Sonarr / Client Download level, as well as Infuse....

I created this user account a few weeks ago and until yesterday everything was working perfectly.

**Comment by Nemrod7** [comment]
I made another test, just in case of, I put another category, witch correspond to another sub-folder of the share [Video], the name is [Films], it's working 🧐

**Comment by BenjV** [comment]
The user within Sonarr is something different then a DSM user even if you use the same name/password.
If you create a shared folder where Sonarr must have access, then the only way to give Sonarr access permissions is to give the group sc-download access permissions on that folder in DSM.

By the way, not using the admin account is but another one is useless idea which is for some reason widely spread and has no extra security value at all and also there are some actions on DSM that can only be done with the real admin account.

**Comment by Nemrod7** [comment]
I didn't modified the permission of the group sc-downloads so it should be another point.

Sonarr isn't working with 2FA, with a dedicated user I can activate it on my admin user and it works even if it display the warning.

**Comment by BenjV** [comment]
No it does not work at all.
But if you think you know it all, then by all means ignore my comments.

**Comment by cytec** [comment]
Like @BenjV said, just assign your "dedicated user" to the sc-downloads group should work... if it doesn't it might help to check the sonarr log files for some more information (might not be an access problem at all)

**Comment by Nemrod7** [comment]
I deleted the sub folder and created a new one, with a different name, it’s working again. Maybe a problem with DSM.

I seem to remember that when Sonarr was installed there was a message explaining that this group is no longer used, but it's just a vague memory.

Whether it is my administrator account or the dedicated account, none of them are in this g

**Comment by cytec** [comment]
FFS dude. if you won't even consider listening why should be even bother? 
it's still most likely a permission thing, but what do we know...

btw the package states: 

Permissions for all download-related packages are managed with the group **'sc-download'** in DSM.
The group 'users' is no longer used as of DSM 6.
Package user will not appear on most UI settings.

And since you won't belive me this time either here's a link to the source: https://github.com/SynoCommunity/spksrc/blob/master/spk/sonarr/src/wizard/install_uifile#L9

**Comment by BenjV** [comment]
RTFM

https://github.com/SynoCommunity/spksrc/wiki/Permission-Concept
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by hgy59** [comment]
As @Nemrod7 has solved the issue by creating a new folder I am closing this.
