### ISSUE TITLE
[Package Request] Python 3.7+

### ISSUE THREAD

**Issue by Deuxgod** [SynoCommunity/spksrc#3737]
Name: Python 3.7

Description: Python 3.7.0 is the newest major release of the Python language, and it contains many new features and optimizations.

Website: https://www.python.org/

Software documentation: https://www.python.org/doc/

Source code: https://www.python.org/downloads/source/

License: https://docs.python.org/3/license.html

Many new modules were added with python 3.7+. Releasing an updated version would benefit for the entire community.

**Comment by chickenandpork** [comment]
When #3673 is complete, it'll do most of the lifting for this effort.  @roleo has just `spksrc` repository visible and I think has nearly resolved, but he's detected a problem when checking against `home assistant`.  I would prefer FWIW that his effort be extended for 3.7.0.

**Comment by Agalin** [comment]
@chickenandpork is there any reason not to add newer python releases for those who need them? Like, I don't care for other python packages, so I've nearly (ctypes so doesn't copy into spk) finished spk for python 3.8 Apollo Lake as a separately versioned package Python38 for my own usage. But is there a point of creating a pull request?

Fun fact: Python 3.8 is a little easier to build due to pure python reimplementation of pgen.

**Comment by chickenandpork** [comment]
We ran into complexities related to building `virtualenv` From the resulting package.  Phorm was no real problem, but the attempts to use that package were:
1.  Copying the build env as the target env (which don’t match in crosscompile), and
1.  It can’t build a virtual env from any wheels needing recompilation.

Spksrc has a slow release cycle, so we wanted something we could version-bump/test relatively quickly, but then we have a non-automatic validation.  Wouldn’t it be awesome if you had people willing to confirm select things such as “python -V runs and shows the right things”?  ..but how to do that at scale inside of a developer build or a circleci run?

**Comment by Agalin** [comment]
Ok. I'll try to clean it up a little and start PR in a few days. One more question: By virtual env issues you meen `virtualenv`, `venv` or both?
