### ISSUE TITLE
RTD1296 ffmpeg video station

### ISSUE THREAD

**Issue by pitiqui** [SynoCommunity/spksrc#3738]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ ffmpeg
_Package Version:_ 4.1-11

_NAS Model:_ DS218play
_NAS Architecture:_ RTD1296
_DSM version:_ 6.2.2

### Expected behavior
Opens an mkv file with DTS/EAC3 sound, plays nicely

### Actual behavior
Get an error, can't play because audio source is not compatible

### Steps to reproduce
_1._ Install ffmpeg from synocommunity (4.1)
_2._ Install Video station
_3._ Load MKV file with DTS/AC3 sound

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
None
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
None
```

#### Notes
I searched everywhere for a solution, like downgrading video station but there are only recent versions because of the new architecture... And no, I won't use Plex or Emby because premium is required to use the hardware transcoding capabilites.
Thanks for looking into it!

**Comment by cytec** [comment]
Like statet numerous times, our ffmpeg packages is not in any way used by video station. you might ask synology directly to add DTS/EAC3 support
