### ISSUE TITLE
TVheadend build error - Libnettle 3.4 was not found

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#3745]
### Setup
_Package Name:_ tvheadend
_Package Version:_ 4.2.8

_NAS Model:_ DS-918+
_NAS Architecture:_ apollolake
_DSM version:_ 6.2.2

### Expected behavior
Unable to rebuild package from source using Debian 10

### Actual behavior
Fails at the following:
```
  *** Libnettle 3.4 was not found.
```
### Steps to reproduce
_1._ Installed Debian 10 VM and followed well done documentation online at:
* https://github.com/SynoCommunity/spksrc
Needed small adjustment for dependencies:
```
$ sudo apt install build-essential debootstrap python-pip automake libgmp3-dev libltdl-dev libunistring-dev libffi-dev libcppunit-dev libncurses-dev imagemagick libssl-dev pkg-config zlib1g-dev gettext git curl subversion check intltool gperf flex bison xmlto php expect libgc-dev mercurial cython lzip cmake swig libc6-i386 libmount-dev libpcre3-dev libbz2-dev
```
_2._ Followed this doc, again well made:
* https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO
_3._ Invoked the build for tvheadend:
```
$ cd spksrc/spk/tvheadend/
$ make arch-apollolake
```

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
...
checking for threads.h... no
checking for getrandom... no
checking for getentropy... no
checking for NETTLE... no
configure: error: 

  *** Libnettle 3.4 was not found.

make[4]: *** [../../mk/spksrc.configure.mk:50: configure_target] Error 1
make[4]: Leaving directory '/home/th0ma7/spksrc/cross/gnutls'
make[3]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[3]: Leaving directory '/home/th0ma7/spksrc/cross/ffmpeg'
make[2]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[2]: Leaving directory '/home/th0ma7/spksrc/cross/tvheadend'
make[1]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[1]: Leaving directory '/home/th0ma7/spksrc/spk/tvheadend'
make: [../../mk/spksrc.spk.mk:453: arch-apollolake] Error 2 (ignored)
```

**Comment by ymartin59** [comment]
To be honest, we mostly build on Docker container... I should discard documentation about Debian "stable" OS (moreover if specific version is not mentioned)

**Comment by th0ma7** [comment]
Thnx for the hint.  I'll try using docker later and see how thing goes.
But still odd as nettle 3.4.1 is installed
```
$ dpkg -l | grep -i nettle
ii  libnettle6:amd64                  3.4.1-1                      amd64        low level cryptographic library (symmetric and one-way cryptos)
ii  nettle-dev:amd64                  3.4.1-1                      amd64        low level cryptographic library (development files)
```
Unless the configuration scripts is script on versioning and must be =3.4 and not >=3.4 or nettle needs to be built within the build environment and is missing?

**Comment by th0ma7** [comment]
Further looking into it, seems it's not processing the dependencies for `gnutls` where it should have gone over `nettle` prior but somewhat it didn't:
```
DEPENDS = cross/libunistring cross/libtasn1 cross/nettle cross/zlib
```

**Comment by th0ma7** [comment]
Partially found why the issue is happening, nettle libraries are going into lib64 instead of lib directory, hence, `gnutls` cannot find them at configuration time:
```
$ ls -lad lib64/*
-rw-r--r-- 1 th0ma7 th0ma7 12230176 jui 28 14:48 lib64/libhogweed.a
lrwxrwxrwx 1 th0ma7 th0ma7       17 jui 28 14:48 lib64/libhogweed.so -> libhogweed.so.4.4
lrwxrwxrwx 1 th0ma7 th0ma7       17 jui 28 14:48 lib64/libhogweed.so.4 -> libhogweed.so.4.4
-rw-r--r-- 1 th0ma7 th0ma7   756456 jui 28 14:48 lib64/libhogweed.so.4.4
-rw-r--r-- 1 th0ma7 th0ma7  8568754 jui 28 14:48 lib64/libnettle.a
lrwxrwxrwx 1 th0ma7 th0ma7       16 jui 28 14:48 lib64/libnettle.so -> libnettle.so.6.4
lrwxrwxrwx 1 th0ma7 th0ma7       16 jui 28 14:48 lib64/libnettle.so.6 -> libnettle.so.6.4
-rw-r--r-- 1 th0ma7 th0ma7   767888 jui 28 14:48 lib64/libnettle.so.6.4
drwxr-xr-x 2 th0ma7 th0ma7     4096 jui 28 14:48 lib64/pkgconfig
```

**Comment by ymartin59** [comment]
I have recently merged change in Dockerfile with addition of "g++-multilib" (for nodejs build) which may be source of this trouble...

**Comment by ymartin59** [comment]
Or your VM Debian system is 32 bits... which has impact on installation path. Build chain expects 64 bits system.

**Comment by th0ma7** [comment]
I doubt it's that.
I've been able to apply fixes in order to get `nettle` and `gnutls` to compile.
Patches are available in my guthub fork I've created.
Currently testing to see how far after that it can get :)

BTW, I'm using Debian 10 64-bit:
```
$ uname -a
Linux debian-dev 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux
```

**Comment by th0ma7** [comment]
yup, got it to work!
All patches available in my forked repository:
https://github.com/th0ma7/spksrc

**Comment by th0ma7** [comment]
I haven't yet got into that as I'm relatively new to this but, is there a way for me to submit my patches so the fixes get applied upstream?

**Comment by ymartin59** [comment]
Great. I am interested to know what was wrong.
You have to create a Pull Request from your repository fork (ideally from a dedicated branch, but I see your committed in master directly - should work by the way): https://help.github.com/en/articles/creating-a-pull-request

**Comment by th0ma7** [comment]
Ok, I think I was able to play with my git repository properly in order to send out a first pull request.
I didn't do a build `all-supported` ??
That would probably take hours & hours..!?!?

**Comment by ymartin59** [comment]
@th0ma7 Correct. It take hours. I have a parallel variant with selection of architecture, but it still long to process. I will build to confirm.

**Comment by th0ma7** [comment]
Thnx a lot!
In the meantime I did ended-up recompiling using `all-supported` for my two other pull requests successfully (#3751 and #3750) both on top of my debian 10 build fixes.

I'm in the mist of recompiling specifically for `arch-apollolake` and test upgrades and new installation for the two pull requests.

**Comment by th0ma7** [comment]
Pull request merged.  Issue can be closed.
