### ISSUE TITLE
DSM-6.2.2 toolchain available

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#3746]
I noticed that the toolchain was updated for 6.2.2 and packages are available online at:
* https://sourceforge.net/projects/dsgpl/files/DSM%206.2.2%20Tool%20Chains/

I'm simply wondering (as new using this) if there was value updating arch definitions in order to use the updated toolchain?
```
$ make setup
Creating local configuration "local.mk"...
Setting default toolchain version to DSM-6.1
```

**Comment by ymartin59** [comment]
As far as I know, packages built here with DSM 6.1 toolchains works on any DSM 6.1 and 6.2 versions. So we do not bother to include minor versions of toolchains, nor to build package DSM-variants

**Comment by th0ma7** [comment]
Good, thnx for the info.
