### ISSUE TITLE
[BUG?] NPM not working from updated Node.js 

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#3757]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Node.js
_Package Version:_  10.15.3-1

_NAS Model:_ 
_NAS Architecture:_ Alpine
_DSM version:_ 6.2.2-24922

### Expected behavior
Install packages with NPM

### Actual behavior
Returns an error:
root@DS715:/volume1/@appstore/node/bin# ./npm
/usr/bin/env: node: No such file or directory

### Steps to reproduce
_1._ Install Node.js package from repo
_2._ Launch NPM from CLI (/volumeX/@appstore/node/bin/npm)

#### Solution
I resolved it by adding Node path to $PATH like this and now it works.
PATH=$PATH:/volume1/@appstore/node/bin

**Comment by ymartin59** [comment]
I consider NodeJS as a stack support for other packages (like Mono for .Net applications) so I do not expect node and npm to be available in PATH for end users.

By the way, I recommend this way to be setup-independant: `PATH=$PATH:/var/packages/nodejs/target/bin`

Notice published package name is `nodejs`, not `node` so I wonder if you really installed package from synocommunity repository...

**Comment by schumi2004** [comment]
Ow i thought i was running the repo version turns out i'm still on the last package provided from PR.
Anyway, installed repo version but the reported issue is the same.
Reading your reply I think we can close this issue, stack support it is ;)
