### ISSUE TITLE
How to use wizard information in SERVICE_COMMAND

### ISSUE THREAD

**Issue by mtonnie** [SynoCommunity/spksrc#3758]
I like to use some information from wizard as parameter for my SERVICE_COMMAND.
For example I like to define a folder to be used by the service and I have to pass it as parameter.

How can this be done, is there any simple way to do this?

Thanks in advance

**Comment by BenjV** [comment]
You can find the 3rd party development guide her:
https://www.synology.com/en-global/support/developer#tool
Start reading at page 72 (WIZARD_UIFILES).

Create a wizard ui file and add in the correct location to the package.
The variables used in that UI file are available in the SERVICE_COMMAND script.

**Comment by mtonnie** [comment]
Shave already created Thema wizard_uifile anderer Thema wizard_uifile seems to Work well, it ist Show during Installation.

But when I try to use the variables for SERVICE_COMMAND for example 
SERVICE_COMMAND = /path/to/my/binary --option $${my_wizard_variable} it doesn't seems to work.

So I have to Sue a Script? 
Are there any examples I can take a look at?

Thanks in advance

**Comment by BenjV** [comment]
I am not sure what you are trying to do, but I assume that you try to create a package for your own application based on one of the SynoCommunity packages.
In that case you are now talking about the variable "SERVICE-COMMAND" in the script "service-setup"
All command you use in a script have to be a correct bash command and what you put in you post above is that not at all.
You can only use wizard ui files with one of the following names and nothing else:
install_uifile
upgrade_uifile
uninstall_uifile

So if you have created a "install_uifile" in the "WIZARD_UIFILES" folder and in that file you have created a json item with the key "my_wizard_variable".
Then you line in de "service_setup" script should look something like:

> SERVICE_COMMAND="/path/to/my/binary --option ${my_wizard_variable}"

So you forgot the "" around the command, not two $ signs and you must lose the spaces around the = sign

**Comment by ymartin59** [comment]
Idea is correct, the problem is that wizard variables are only available in installer script. So post_install should implement logic to store and startup to load, like what has been done in PR #3689: https://github.com/SynoCommunity/spksrc/blob/b256d8fff38a6a90607aa7dcc888026cad9dfa13/spk/minio/src/service-setup.sh

I am working on a generic support in framework so that wizard variables persist in "etc/variables" and become available in start-stop-status script.
Another benefit is to pre-fill wizard with previously set values when upgrade requires a review of application parameters.
I will let you know.

**Comment by BenjV** [comment]
@ymartin59 
I don't know if etc/variables will survive a DSM upgrade.
Maybe it would be better to use a location Synlogy suggest in it development guide to store bootup scripts (e.g. /usr/local/etc), that location is garanteed to survive a DSM upgrade.
So maybe better to use /usr/local/etc/variables

**Comment by mtonnie** [comment]
Thanks to @ymartin59, I'm now using service_prestart function from service-setup.sh to add the parameters to SERVICE_COMMAND variable.

This works for me quite well
