### ISSUE TITLE
[Update Request] ffmpeg 4.2

### ISSUE THREAD

**Issue by CrabThug** [SynoCommunity/spksrc#3759]
Motivation: Upgrade ffmpeg to the latest available version
https://github.com/FFmpeg/FFmpeg/releases/tag/n4.2

**Comment by CrabThug** [comment]
up ?

**Comment by th0ma7** [comment]
See pending pull request #3778.

**Comment by CrabThug** [comment]
so I ll wait the #3778.

**Comment by CrabThug** [comment]
But can we use av1 (encode and decode) with this release ?

**Comment by th0ma7** [comment]
That's a totally different issue than what the title of this bug refers to.
Can you modify the title of the bug to reflect this?

I took time to look over AV1, which is part of `libaom`.
It needs much more work than anticipated.  I did started something and was able to create ffmpeg packages with AV1 support.  Although there are still a few details to be iron out as I wasn't able to cross-build for all architectures and it needed more testing to confirm all is ok.

I'll try to come back on this issue when I have a few more spare cycles and see wetter it can be included in upcoming ffmpeg 4.2 release or in it's subsequent.

**Comment by CrabThug** [comment]
Ok Ty
