### ISSUE TITLE
Python won't run on Synology

### ISSUE THREAD

**Issue by Pokersut** [SynoCommunity/spksrc#376]
On my DS-413 with DSM 4.2-3160, I cannot run the Python package from SynoCommunity.

It seems to install successfully, but when I try to install other packages that require Python (e.g. Sickbeard), I get the message "Please run Python before installing this package".

Since there is no "Run" command for the Python package, I don't know what to do. I have tried installing Synology's own Python package (v. 2.7.3-011), and it installs and runs without problems - but Sickbeard will not install under with version.

I had the same problem last time I upgraded the firmware, but then I could fix the problem by uninstalling, rebooting and re-installing Python - but this hasn't worked this time.

Any ideas?

**Comment by cognopatrick** [comment]
hey guys,

Ik have succesfully installed python in my synology nas but i can't find how to add libraries for python. can anyone help me?

**Comment by Diaoul** [comment]
@cognopatrick: Use virtualenv to create yourself an isolated environment to work with. On your NAS, virtualenv is located at `/usr/local/python/bin/virtualenv`.
