### ISSUE TITLE
[Update Request] Jackett to standalone

### ISSUE THREAD

**Issue by CrabThug** [SynoCommunity/spksrc#3760]
Motivation: Upgrade Jackett to the latest available version with standalone cause mono is little greedy
https://github.com/Jackett/Jackett#install-on-linux-amdx64

**Comment by CrabThug** [comment]
up ?

**Comment by ymartin59** [comment]
It sounds relevant to provide package thanks to a dotnet core build support in framework #3715

**Comment by CrabThug** [comment]
ok ty
