### ISSUE TITLE
[Package Request] Deluge 2.0.3

### ISSUE THREAD

**Issue by gerarts** [SynoCommunity/spksrc#3762]
Would it be possible to update Deluge to the latest 2.0.3? Deluge received a [version 2 update in June 2019](https://git.deluge-torrent.org/deluge/refs/tags) with loads of [bug fixes](https://dev.deluge-torrent.org/query?type=bug&resolution=Fixed&milestone=2.x&or&type=bug&resolution=Fixed&milestone=2.1.x&or&type=bug&resolution=Fixed&milestone=2.0.0&or&type=bug&resolution=Fixed&milestone=2.0.2&or&resolution=Fixed&type=bug&milestone=2.0.3&groupdesc=1&group=priority&max=500&col=id&col=summary&col=type&col=priority&col=component&col=version&order=priority) and [new features](https://dev.deluge-torrent.org/query?type=feature-request&resolution=Fixed&milestone=2.x&or&type=feature-request&resolution=Fixed&milestone=2.1.x&or&type=feature-request&resolution=Fixed&milestone=2.0.0&or&type=feature-request&resolution=Fixed&milestone=2.0.2&or&resolution=Fixed&type=feature-request&milestone=2.0.3&groupdesc=1&group=priority&max=500&col=id&col=summary&col=type&col=priority&col=component&col=version&order=priority) and the current SynoCommunity package (version 1.3.15) is a [version from May 2017](https://git.deluge-torrent.org/deluge/tag/?h=deluge-1.3.15).

Thanks!

**Comment by meolite** [comment]
Yes, it would be great, please!

**Comment by digitalbox94** [comment]
Not tested but get deluge 2.0.3 compiling OK and having a package generated with SPKSRC
Let me know if you are interested, I will propose a PR (I had to repair the geoid dependency first)

**Comment by meolite** [comment]
Sure, thank you so much!

**Comment by digitalbox94** [comment]
Compiling is ok, however after launching deluge 2.0 : 
pkg_resources.DistributionNotFound: The 'setproctitle' distribution was not found and is required by deluge

Not sure about the correct approach : cross compile setproctitle ?  (https://files.pythonhosted.org/packages/5a/0d/dc0d2234aacba6cf1a729964383e3452c52096dc695581248b548786f2b3/setproctitle-1.1.10.tar.gz) other method ?

**Comment by labaland** [comment]
Please add new version on deluge! now deluge is missing in the package center :/

**Comment by djhifi** [comment]
Any updates on this? Deluge version on Package Center has been v1.3.15-9 for ages (with all it's known issues). Getting a little old now :(

**Comment by meolite** [comment]
DigitalBox ran into problems, soliciting help, which never came.
--
dima.
http://www.northeastern.edu/dima/

**Comment by djhifi** [comment]
Thanks about the update. That's actually sad.

**Comment by djhifi** [comment]
> Compiling is ok, however after launching deluge 2.0 :
> pkg_resources.DistributionNotFound: The 'setproctitle' distribution was not found and is required by deluge
> 
> Not sure about the correct approach : cross compile setproctitle ? (https://files.pythonhosted.org/packages/5a/0d/dc0d2234aacba6cf1a729964383e3452c52096dc695581248b548786f2b3/setproctitle-1.1.10.tar.gz) other method ?

How about talking directly with Deluge dev?

**Comment by meolite** [comment]
thanks much!
but am i missing something?
it's still Deluge v1.3.15-9 here
https://synocommunity.com/packages
--
dima.
http://www.northeastern.edu/dima/

**Comment by thijsvanderkraan** [comment]
The deluge in package 2.0.3-13 uses python 2.7 instead of python 3.7. This creates a problem when trying to install 3rd party plugins which are packaged in the egg format. The plugins for deluge 2 are build for python 3.7 and 3.8, which is reflected in the file name. The deluge client will only install a plugin if the egg file names matches the deluge python version. Renaming the egg gets it installed, but doesn't get it to work (to be expected).
Is the 2.0.3 deluge package going to be updated to use python 3.7?
