### ISSUE TITLE
Cannot install TVHEADEND - Error: Port undefined configured for this package is used by...

### ISSUE THREAD

**Issue by ClausB-P** [SynoCommunity/spksrc#3768]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ TVheadend
_Package Version:_ 4.2.8-16

_NAS Model:_ Synology DS216 Play
_NAS Architecture:_Monaco 
_DSM version:_ DSM 6.2.2-24922 Update 3

### Expected behavior
The package should update the existing TVHeadend version

### Actual behavior
I have now TVHeadend 4.0.8-1 installed and when I try to install  4.2.8-16 I ger the error:
Port undefined configured for this package is used by...

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by th0ma7** [comment]
Having any log outputs we can dig into?  There is not enough information as is to be able to provide you with solutions nor analysis of the problem.

**Comment by ClausB-P** [comment]
Thanks for your answer!

I resolved the issue by uninstalling the original TVHeadend version completely.

I wanted to avoid that because I would loose my settings and maybe my recordings.

I backup’ed the recordings but after the new TVHeadend installations the old recordings are no longer part of my TVHeadend univers which is a shame.

Best regards

Claus

**Comment by ymartin59** [comment]
Probably you were running a beta/test package. I expect this issue to be fixed.
The "var" folder is expected to contain all application settings and databases... So you may get it from a backup if available.

**Comment by ClausB-P** [comment]
Thanks ymartin59! 
I will take a look at the "var" folder. I of course have the actual recordings in a folder. 
I use KODI and after the new version of TVHeadend the TV recording list in KODI has 2 lines for each recording which gives a bad overview. - there is always something to fix :-)
Claus

**Comment by hgy59** [comment]
I know it's too late now ;-)
but for anyone having similar issues:
1.  use `netstat` and `ps` commands to retrieve the service using the desired port(s)
2. Kill the process that is using the port(s) - maybe it is the service you want to update, and is not properly terminated by the package center

**Comment by ClausB-P** [comment]
Thanks anyway :-)

Claus
