### ISSUE TITLE
[Package Request] Make NCDU available for x64 devices - DS918+

### ISSUE THREAD

**Issue by nitantsoni** [SynoCommunity/spksrc#3769]
Name: NCDU
Website: https://synocommunity.com/package/ncdu

This package is unavailable for the DS918+ due to missing x64 Arch. Could I please request you to make it available for that as well!

**Comment by hgy59** [comment]
ncdu will be available within the synocli-file package.
It will not be updated as individual package anymore. You can build ncdu version 1.14.1 of your own as contained in PR #3773 (see diyspk folder).

**Comment by ymartin59** [comment]
Published. Available from Package Center or https://synocommunity.com/package/synocli-file
