### ISSUE TITLE
SPK for Greenbureau

### ISSUE THREAD

**Issue by remylpat** [SynoCommunity/spksrc#377]
Hi All, 
Do you know greenbureau (https://greenbureau.fr) if not I really advise you to test it.

I am in contact with them and they are working on an API that will be available next month for "restricted/selected" person who will be interested of developing a SPK for synology (this is not the original purpose of this API but they will allow us to use it).

The idea is to have all your bills collected by Greenbureau and have an spk running on our synology to "regularly" download the bills ans save them locally on  your syno

Does this make some interest for one of you.
Unfortunately I am not a developer since years so if some of you is interested do not hesitate to contact me.

Rgds

./Rémy
##

**Comment by slybreiz** [comment]
Hello

there have t he new to a greenbureau spk under synology?
it is an API?

bonjour 

y as t il du nouveau  pour un spk greenbureau sous synology ? 
une api existe  elle ?

**Comment by remylpat** [comment]
Unfortunately no.
Malheureusement non
