### ISSUE TITLE
erlang compilation is failing

### ISSUE THREAD

**Issue by digitalbox94** [SynoCommunity/spksrc#3770]
### Setup
_Package Name:_ Erlang
_Package Version:_ R16B03-1

_NAS Model:_  DS 716+II
_NAS Architecture:_ braswell
_DSM version:_ 6.1

### Expected behavior
The Erlang compilation in the cross directory should compile fine

### Actual behavior
The error appear below : 
In file included from beam/erl_threads.h:267:0,
                 from beam/erl_smp.h:27,
                 from beam/sys.h:416,
                 from hipe/hipe_bif0.c:27:
hipe/hipe_amd64_primops.h:21:13: erreur: «am_inc_stack_0» non déclaré ici (hors de toute fonction)
 PRIMOP_LIST(am_inc_stack_0, &nbif_inc_stack_0)
             ^

### Steps to reproduce
_1._ In the Spksrc directory : make setup
_2._ cd native/erlang
_3._ make
_2._ cd cross/erlang
_3._ make arch-braswell

**Comment by digitalbox94** [comment]
Investigation on going and moving forward : in native/erlang, even if the definition of "am_inc_stack_0" is available in erl_atom_table.h, the cross part can't find it 

So next step is to indicate where the "erl_atom_table.h" is : it might be a missing option in the configure of cross/erlang

Relative path is : ./work-native/otp_src_R16B03-1/erts/emulator/x86_64-unknown-linux-gnu/erl_atom_table.h:961:#define am_inc_stack_0 make_atom(951)

**Comment by ymartin59** [comment]
@digitalbox94 Thanks for your investigations. Do not hesitate to submit PR with fix proposal, even in draft version as "work-in-progress", so that we may review and/or go further....

**Comment by digitalbox94** [comment]
Moving forward : I didn't identified so far the root cause of the error in the cross compilation process. 
I decided to not use spksrc as a first step and cross-compile from scratch Erlang. The good news is that it cross-compiled fine for braswell arch. My aim was to compile rabbitmq-server, where I have also succeed in compiling it once Erlang compiler was available. rabbitmq-server seems to launch without any error :)
Now I have a good comparison criteria between cross compilation via spksrc and cross compilation without to understand where the things go wrong with spksrc and Erlang

**Comment by digitalbox94** [comment]
<img width="554" alt="rabbitmq" src="https://user-images.githubusercontent.com/25862070/65835956-180ad380-e2ed-11e9-8717-ec44e30454fe.png">

**Comment by digitalbox94** [comment]
Moving forward, I have the below : 

- cross compilation from linux-x86_64 to braswell (64 bits) without spksrc : ok
- cross compilation from linux-x86_64 to evansport (32 bits) without spksrc : ok
- cross compilation from linux-x86_64 to braswell (64 bits) with spksrc : ok
- cross compilation from linux-x86_64 to evansport (32 bits) with spksrc : ko

=> Erlang cross compilation is expecting  "--host" and "--build" options defined during the configure phase, however for an unknown reason SPKSRC doesn't "like" these options as I have the below error message for evansport :

LD	../priv/lib/x86-unknown-none/dyntrace.so
[...]/bin/i686-pc-linux-gnu-ld : option « -Wl,--rpath-link,[...]work-evansport-6.1/install//usr/local/erlang/lib » non reconnue

The same error is also raised when using the "--host" and "--build" options for braswell.

I can give more details or propose a PR if someone wants to look at it.

**Comment by digitalbox94** [comment]
<img width="520" alt="rabbitmq erlang" src="https://user-images.githubusercontent.com/25862070/66773763-13831500-eec0-11e9-94bd-8000b2ac25af.png">
It's possible to have both Erlang and RabbitMQ as separate packages. Unfortunately I didn't use spksrc due to the above reasons.

**Comment by hgy59** [comment]
A PR would be welcome.
If you define `GNU_CONFIGURE = 1` in the Makefile, the --host and --build parameters should be set in the configure step. To solve other issues one can use `CONFIGURE_ARGS`. And sometimes a custom pre-configure step is needed to call autoconf or similar tool.
If the projects are not created with cross compilation in mind, sometimes patching configure or make files is needed.

**Comment by digitalbox94** [comment]
Not sure to understand at which level the --host will be deduced here : is it by the SPKSRC tool or is it by the configure script included in the source of the software to port ?

One possibility is to have a mapping between each synology arch (braswell, evansport, etc) and the corresponding "--host" variable : it could be done at SPKSRC level and it might solve some issues in the cross compilation process :)

I will continue to have a look at it, because by "hardcoding" the --host / --build part, I have much more software passing the cross compilation (Erlang, RabbitMQ, IOQuake, PostgreSQL, ...) at least for my NAS model :)

**Comment by hgy59** [comment]
Erlang and RabbitMQ are released with #4437
