### ISSUE TITLE
[Package Request] Lossless Image Compression Package like: Trimage (Ideally available for x64 devices - DS918+)

### ISSUE THREAD

**Issue by jwest75674** [SynoCommunity/spksrc#3774]
Name: Trimage 
Description: Trimage is a cross-platform GUI and command-line interface to optimize image files for websites, using optipng, pngcrush, advpng and jpegoptim, depending on the filetype (currently, PNG and JPG files are supported). It was inspired by imageoptim. 
Website: https://trimage.org/
Software documentation: https://github.com/Kilian/Trimage
Build/Installation documentation: https://github.com/Kilian/Trimage
Source code: https://github.com/Kilian/Trimage
License: https://github.com/Kilian/Trimage/blob/master/COPYING

Personal Request Description: Trying to match the guidelines, but wanted to add a quick comment. I am specifically trying to make available the ability to losslessly compress images on my DS918+. Trimage is the software I came across first, but there may be other solutions in place to compress both PNG and JPG images. (Cover art images in very very large libraries, or images needing to be served on websites, etc. can benefit both in storage and bandwidth requirement, while avoiding lossy compression). My apologies if a solution already exists and I've overlooked it!

**Comment by ymartin59** [comment]
@jwest75674 As a replacement, you may use ImageMagick command line tools: https://synocommunity.com/package/imagemagick
By the way, Synology cannot run a Qt5 graphical interface... if package is build, it will only provide command line tools.

**Comment by hgy59** [comment]
avoiding Qt5 we could could provide the related tools as a synocli-package (synocli-optim - for optimize images?)
- advpng
- jpegoptim
- optipng
- pngcrush

Or we could include those in the imagemagick package, as we already do for jpegoptim.
