### ISSUE TITLE
[Lidarr] Download client is unavailable

### ISSUE THREAD

**Issue by mnervik** [SynoCommunity/spksrc#3775]
### Setup
Lidarr
0.7.1.1381

DS1517+
Avoton (x64)
6.2.2-24922

### Expected behavior
Lidarr should start downloading using Synology Download Station

### Actual behavior
- Adding download to download queue from wanted-section
`Torrent Download client isn't configured yet `

- Add to download queue from download-queue gives a red icon, illustrating an error
- Hovering over the status of a download in the download-queue
`Pending - Download client is unavailable`

- Under Edit Download Client (Download Station) I have run the test without recieving an error

### Screenshot
![](https://user-images.githubusercontent.com/15329600/58513694-5c039580-81a0-11e9-8b6b-b800817e51f7.jpg)

**Comment by BenjV** [comment]
see https://github.com/SynoCommunity/spksrc/issues/3702

**Comment by mnervik** [comment]
@BenjV I'm guessing you are referencing your comment about having to set the same location in lidarr as in downloadStation. Currently I am using the default location (empty location field in lidarr), but I have tried entering the folder in lidarr, still get's the same issue though.

- Download station default folder: **/downloads**
- Lidarr download-station location: **/downloads**

**Comment by BenjV** [comment]
No I was referring to the comment of @ta264 that it is a Lidarr problem and that was fixed in version 0.6.2.
So it seems to me that the Lidarr package needs an update.

**Comment by mnervik** [comment]
Well I'm using version 0.7.1...so then should not this issue already not exist anymore? If not, what do I have to do to update to a version where this if fixed?

**Comment by ta264** [comment]
You've likely added the usenet download station client not the torrent one

**Comment by mnervik** [comment]
Omg it was. Thanks for help @ta264

**Comment by ralphdt** [comment]
hahahaha. I was debugging my lidarr instance after a bottle of prosecco and had the same problem
