### ISSUE TITLE
Reopen this - MC mouse is not working anymore #3258 - 

### ISSUE THREAD

**Issue by Merwenus** [SynoCommunity/spksrc#3783]
Same issue as below
https://github.com/SynoCommunity/spksrc/issues/3258

Midnight Commander 4.8.21-5

When you start normally it works great, but when you open elevated:
sudo MC

You cant use the mouse, it writes random characters in the bottom, and clicks do not work.

**Comment by hgy59** [comment]
Did some debugging now.
as elevated user (root, admin) on my diskstation the /bin/ash shell is used.
Then found that it is not an issue with the shell, but when missing the TERMINFO export the mouse does not work in mc.
Solved this with `export TERMINFO=/usr/share/terminfo` before running mc.
Hope this helps.

**Comment by hgy59** [comment]
This is finally solved with #3837
