### ISSUE TITLE
Following Developers How To fails building transmission using current docker image for arch-denverton-6.1

### ISSUE THREAD

**Issue by jackemuk** [SynoCommunity/spksrc#3791]
Title pretty much states the issue. 

Running docker ce 2.1.0.3 on mac 10.14.6 and fails extracting the tar file under distrib/tookchains. 

make arch-denverton-6.1
===>  Building package for arch denverton-6.1
make[1]: Entering directory '/spksrc/spk/transmission'
===>  Set up toolchain
===>    Extracting for syno-denverton
tar -xpf /spksrc/toolchains/syno-denverton-6.1/../../distrib/toolchains/6.1/denverton-gcc493_glibc220_linaro_x86_64-GPL.txz -C /spksrc/toolchains/syno-denverton-6.1/work
tar: x86_64-pc-linux-gnu/test-suite: Cannot mkdir: Permission denied
tar: x86_64-pc-linux-gnu/test-suite: Cannot mkdir: Permission denied
tar: x86_64-pc-linux-gnu/test-suite/gcc: Cannot mkdir: No such file or directory
tar: x86_64-pc-linux-gnu/test-suite: Cannot mkdir: Permission denied
tar: x86_64-pc-linux-gnu/test-suite/gcc/testsuite: Cannot mkdir: No such file or directory
tar: x86_64-pc-linux-gnu/test-suite: Cannot mkdir: Permission denied
tar: x86_64-pc-linux-gnu/test-suite/gcc/testsuite/objc: Cannot mkdir: No such file or directory
tar: x86_64-pc-linux-gnu/test-suite: Cannot mkdir: Permission denied
tar: x86_64-pc-linux-gnu/test-suite/gcc/testsuite/objc/execute: Cannot mkdir: No such file or directory
tar: x86_64-pc-linux-gnu/test-suite: Cannot mkdir: Permission denied
tar: x86_64-pc-linux-gnu/test-suite/gcc/testsuite/objc/execute/load.m: Cannot open: No such file or directory
tar: x86_64-pc-linux-gnu/test-suite: Cannot mkdir: Permission denied
tar: x86_64-pc-linux-gnu/test-suite/gcc/testsuite/objc/execute/function-message-1.m: Cannot open: No such file or directory
tar: x86_64-pc-linux-gnu/test-suite: Cannot mkdir: Permission denied
tar: x86_64-pc-linux-gnu/test-suite/gcc/testsuite/objc/execute/class_self-2.m: Cannot open: No such file or directory

**Comment by jackemuk** [comment]
It seems there is an issue with permissions in the gcc tar libraries that are downloaded from sourceforge. Modifying the spksrc.extract.mk file to not have the -p flag to tar doesn't cause the make to fail.

**Comment by ymartin59** [comment]
It is a known issue when running our Debian docker on macOS... and it is not planned to fix it.
Options are either to setup a Debian VM to compile directly there or run the docker image.

**Comment by ymartin59** [comment]
@jackemuk Thanks for investigations. I have no macOS for testing. May you please propose a PR with removal of `-p` tar flag you confirmed to work.

**Comment by hgy59** [comment]
@jackemuk can you please validate the build of /spk/python (includes /native/python) with your modified *.mk files.
I removed -p from all tar commands and run spksrc container with non root user under Debian. With this setting, building wheels showed the following error:
`WARNING: Building wheel for pycparser failed: [Errno 13] Permission denied: '/.cache'`

This may be related to the non root user, but I suppose the permission errors with MacOS are also user related. I too have no access to a macOS system, so it is better you validate as much builds as possible with your modifications on macOS, before others start to validate the builds on Debian.

Note:
_There where no problems building non python-wheel realted packages with the same setting_

**Comment by hgy59** [comment]
> It seems there is an issue with permissions in the gcc tar libraries that are downloaded from sourceforge. Modifying the spksrc.extract.mk file to not have the -p flag to tar doesn't cause the make to fail.

@jackemuk looks like you solved the same issue as  #3524
If so, I would prefer your solution

**Comment by ludovicchabant** [comment]
I was running into this problem (using macOS and the provided Docker image) so I went looking for information around here. Unless I didn't do it right, removing `-p` for the `tar` commands didn't solve it, but the fix in #3524 did work.

**Comment by hgy59** [comment]
@ludovicchabant did you try to run the container without root user (i.e. your own user) after removing -p for the tar commands, like this:
```
docker run -it --user $(id -u):$(id -g) -v ~/spksrc:/spksrc synocommunity/spksrc /bin/bash
```
_You have to recursivly change ownership to you for ~/spksrc to have access to the already downloaded and created files - or use a new clone_.

**Comment by ludovicchabant** [comment]
@hgy59 I didn't, I just followed the instructions in the [spksrc setup guide](https://github.com/SynoCommunity/spksrc#setup-development-environment), which don't include those extra arguments. I'll try tonight!
