### ISSUE TITLE
Recursive Permissions fail

### ISSUE THREAD

**Issue by raako71** [SynoCommunity/spksrc#3792]
I have tried [this](https://automatica.com.au/2016/11/recursively-propagate-permissions-on-a-synology-nas-with-synoacltool/) fix for recursive inherited permissions, including steps in the comments (below), although there always is parts of the folder hirachy where inherited permissions arent applied, which makes for a total pain trying to give the SyncThing user group all permissions.

`find /volume1/Share\ Point -mindepth 1 ! -path '*/@eaDir*' ! -path '*/#recycle*' ! -path '*/#snapshot*' -execdir synoacltool -enforce-inherit {} \;`
Is there a solution for this?!

**Comment by hgy59** [comment]
Your referenced fix seems outdated (is from 2016), so it may be valid for DSM <= 5.2 only.
This repository is ment for building packages for DSM.
Please use a synoloy user forum for asking questions about synology tools.
