### ISSUE TITLE
Jackett package for Synology DSM 6.2

### ISSUE THREAD

**Issue by LukasRa** [SynoCommunity/spksrc#3796]
Hello,

I did not found Jackett for DSM 6.2, only for 6.1.
Is it planned to build for 6.2?
Or here is any other options how to install Jackett on DSM 6.2?

Lukas

**Comment by ymartin59** [comment]
Hello. Same package works on DSM 6.2, and Package Center is "expected" to discover and install it... If not, proceed to manual download and installation including required Mono package.

**Comment by LukasRa** [comment]
I tried to install manually, I get error:
![Capture](https://user-images.githubusercontent.com/15182293/68332884-30d28a00-00e0-11ea-8705-05d268e1905d.PNG)
Also, Jakett is not in the list of packages in Package center..

**Comment by ymartin59** [comment]
What is your DSM model? Which package-architecture have you downloaded?

**Comment by LukasRa** [comment]
DS415play
DSM 6.2.2-24922 Update 3
I downloaded from: 
https://synocommunity.com/package/jackett
6.1 x86
File name which downloads:
jackett.v8.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-grantley-kvmx64-x86-x86_64].spk

**Comment by ymartin59** [comment]
That package is for 64 bits Intel CPU.
Wiki refers architecture for each model: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model
Please retry with "evansport" packages for Mono and Jacket.

**Comment by LukasRa** [comment]
It works!
Thanks a lot for help. My assumption that version of DSM and not very informative error led me to wrong way.
Thanks once again.

**Comment by LukasRa** [comment]
BTW is here a way to upgrade Jackett?
It says now:
"Your version of Jackett v0.11.43.0 is very old. Multiple indexers are likely to fail when using an old version. Update to the latest version of Jackett."

**Comment by Diaoul** [comment]
Just use the built-in updater.
Closing as the initial issue is resolved.

**Comment by ymartin59** [comment]
There is an "auto-update" feature in application that "may happen" (or "is known") to work...
