### ISSUE TITLE
Jackett v0.11.43-8 for DSM 5.2

### ISSUE THREAD

**Issue by Cyxi** [SynoCommunity/spksrc#3797]
Hi,
is it possible to upgrade the 0.10.589-7 version for 5.2 to v0.11.43-8

DS1010+
DSM 5.2-5967 Update 9

Cheers

**Comment by ymartin59** [comment]
@Cyxi Have you tried embedded update feature in Jackett?

**Comment by Cyxi** [comment]
Auto update is activated, but not working
will try this https://github.com/Jackett/Jackett/issues/4858

**Comment by jeremymeyers** [comment]
Dropping a note to say thatt this is still more than a version behind and that the version on synocommunity does not communicate correctly with the Jackett server in order to update internally

**Comment by hgy59** [comment]
@jeremymeyers just uploaded jacket 0.16.1340-12 for DSM 5.2.
The packages are not activated for package center yet. Please use manual download. With your positive feedback I will activate the DSM 5.2 packages.
I suppose the current version is ok (or do you need the old v0.11.43-8 as originally requested?)

**Comment by jeremymeyers** [comment]
see https://github.com/Jackett/Jackett/issues/4858#issuecomment-761535017

**Comment by mreid-tt** [comment]
@Cyxi... checking on some older issues... is this still an ongoing concern or can this ticket be closed?

**Comment by mreid-tt** [comment]
Hi there! It looks like this issue has been open for some time without any recent updates. Since then, a new version of Jackett (v0.20.3521-16) has been released which may have resolved this issue. Can you please test with the latest version and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!

**Comment by hgy59** [comment]
@mreid-tt sorry to reopen this. We did not publish jacket for DSM 5.2 yet.

**Comment by hgy59** [comment]
I have now built and published jackett v0.20.3521-16 for DSM 5.2 and SRM 1.2.
It takes the known delay of up to 48h to be visible in DSM Package Center.
