### ISSUE TITLE
[Package Request] ripgrep (rg)

### ISSUE THREAD

**Issue by acherunilam** [SynoCommunity/spksrc#3799]
Name: ripgrep (rg)
Description: Command line search tool that combines the usability of The Silver Searcher (an ack clone) with the raw performance of GNU grep
Website: https://blog.burntsushi.net/ripgrep/
Software documentation: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md
Build/Installation documentation: https://github.com/BurntSushi/ripgrep#building
Source Code: https://github.com/BurntSushi/ripgrep
License: MIT

It's like a modern-day grep but much much faster, [here](https://blog.burntsushi.net/ripgrep/#code-search-benchmarks) are the benchmarks.

**Comment by hgy59** [comment]
ripgrep is built with Rust, so the development environment (Dockerfile) must be enhanced for this.
