### ISSUE TITLE
ffmpeg - image2 muxer not functional, how to work around this?

### ISSUE THREAD

**Issue by StrikeAgainst** [SynoCommunity/spksrc#3812]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ ffmpeg
_Package Version:_ 4.1-11

_NAS Model:_ DS218play
_NAS Architecture:_ rtd1296 (armv8)
_DSM version:_ 6.2.2-24922 Update 4

### Expected behavior
Running
`ffmpeg -ss 00:00:01.00 -i video.mp4 -vframes 1 thumbnail.png`
or
`ffmpeg -ss 00:00:01.00 -i video.mp4 -vframes 1 -f image2 thumbnail.png`
should create me a thumbnail of `video.mp4` at second 1.

### Actual behavior
Trying to create a video thumbnail like
`ffmpeg -ss 00:00:01.00 -i video.mp4 -vframes 1 thumbnail.png`
gets me the error

> [NULL @ 0x306ee420] Unable to find a suitable output format for 'thumbnail.png'
thumbnail.png: Invalid argument

Explicitly addressing the format like
`ffmpeg -ss 00:00:01.00 -i video.mp4 -vframes 1 -f image2 thumbnail.png`
then tells me

> [NULL @ 0x260a5400] Requested output format 'image2' is not a suitable output format
thumbnail.png: Invalid argument

...which is no surprise since the `image2` muxer is disabled (see below). Why is it though?
AFAIK enabling it requires me to compile the package myself, which I have absolutely no experience with. How would I do this on my NAS? Is there maybe another way for me to create a video thumbnail without having to do so?

### Steps to reproduce
_1._ Install `ffmpeg` via Package Center
_2._ Make sure `video.mp4` is an actual file
_3._ Run command as above

#### Package log
Seemingly none available yet, since it's a fresh install and wasn't able to run it yet.
Running `ffmpeg` returns this:

> ffmpeg version 2.7.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.4 (crosstool-NG crosstool-ng-1.22.0-169-g87eb166) 20150629 (prerelease)
  configuration: --prefix=/usr --incdir='${prefix}/include/ffmpeg' --arch=arm64 --target-os=linux --cross-prefix=/usr/local/aarch64-unknown-linux-gnueabi/bin/aarch64-unknown-linux-gnueabi- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-shared --disable-static --enable-version3 --enable-nonfree --enable-libfaac --enable-encoders --enable-pthreads --disable-bzlib --disable-protocol=rtp --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffserver --disable-ffplay --disable-devices --disable-bzlib --disable-altivec --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --disable-vaapi --disable-decoder=amrnb --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-encoder=zmbv --disable-encoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=dca --disable-decoder=eac3 --disable-decoder=truehd --cc=/usr/local/aarch64-unknown-linux-gnueabi/bin/aarch64-unknown-linux-gnueabi-ccache-gcc --enable-yasm --enable-libx264 --enable-encoder=libx264
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100

**Comment by BenjV** [comment]
If you don't specify the location of the ffmpeg binary the command you gave will search the "path" environment variable to locate ffmpeg and it will use the standard ffmpeg bundled with your Nas.
If you want to use the ffmpeg of the SynoCommunity from the commandline you must use the full location. e.g.

> /var/packages/ffmpeg/target/bin/ffmpeg  -ss 00:00:01.00 -i video.mp4 -vframes 1 thumbnail.png


or if you know the volume you installed the package for example volume1

> /volume1/@appstore/ffmpeg/bin/ffmpeg  -ss 00:00:01.00 -i video.mp4 -vframes 1 thumbnail.png

**Comment by StrikeAgainst** [comment]
Oh well, I had no idea that the NAS already was coming with a ffmpeg bundle which I was using all along by mistake. Working with the right ffmpeg finally does it. Guess this issue can be marked as resolved. Thanks a bunch!
