### ISSUE TITLE
Git for virtual dsm (kvmx64)

### ISSUE THREAD

**Issue by tombro007** [SynoCommunity/spksrc#3821]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ git.  Not the server
_Package Version:_ 

_NAS Model:_ ds916+
_NAS Architecture:_ kvmx64
_DSM version:_ viruale dsm

### Expected behavior
Tell us what should happen
Hi I wand to instal nzbHydra but I need git for and  there is no for viruale dsm
### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
No idea what you mean by virual DSM ( maybe virtual DSM?).
But Git is available for your NAS.
Maybe you tried to search for Git Server (which you don't need), that one is only available as beta package.

**Comment by tombro007** [comment]
yes I meant virtual DSM. And I don't need the git server but only git
In the package center from Synology it is not available in the virtual dsm.It is available in the regular DSM
But I was able to solve it by installing git manually. That I found on https://synocommunity.com/package/git
The 5.0 x86_64 appears to work.Thanks anyway!

**Comment by hgy59** [comment]
@tombro007 you are right, in the synocommunity package repository the arch `kvmx64` is missing for the git package.
The generic `x86_64` arch is used to build all intel x64 archs. Version 5.0 does not contain `dockerx64` and `kvmx64` archs.
For DSM 6.1 the `dockerx64` git package was added but `kvmx64` not.

**Comment by ymartin59** [comment]
I propose (someone) to prepare a package update for Git, then it will be published for kvm64 too.

**Comment by tombro007** [comment]
thanks!

**Comment by ymartin59** [comment]
Package update has just been published

**Comment by tombro007** [comment]
thanks!!!
