### ISSUE TITLE
Midnight Commander: SFTP Support

### ISSUE THREAD

**Issue by chrisellsworth** [SynoCommunity/spksrc#3834]
### Setup
_Package Name:_ Midnight Commander (mc)
_Package Version:_ 4.8.21-5

_NAS Model:_ DS1019+
_NAS Architecture:_ x64
_DSM version:_ 6.2.2-24922 Update 4

### Expected behavior
`SFTP link...` option exists in the PullDn menu

![Screen Shot 2019-12-27 at 21 24 40](https://user-images.githubusercontent.com/1240464/71539352-fde29080-28ef-11ea-95d4-0ad245fc62b8.png)
(screenshot from `mc` on macOS via homebrew)

### Actual behavior
`SFTP link...` option does not exist in the PullDn menu

![Screen Shot 2019-12-27 at 21 24 45](https://user-images.githubusercontent.com/1240464/71539353-fde29080-28ef-11ea-8d37-8d606c42e493.png)

### Steps to reproduce
_1._ Press F9
_2._ Examine menu options

If I were to guess, this is because the version of `mc` on my Mac was compiled with `'--enable-vfs-sftp'` (per `mc --configure-options`)

**Comment by hgy59** [comment]
This is finally solved with #3837

**Comment by chrisellsworth** [comment]
Thank you @hgy59 for working on this!

**Comment by ymartin59** [comment]
Available with 1.1-2: https://synocommunity.com/package/synocli-file
