### ISSUE TITLE
ruTorrent for rtd1296 / DS218play

### ISSUE THREAD

**Issue by gnomelibre** [SynoCommunity/spksrc#3835]
hello,

I have tried many clients (Download Station, Deluge, Transmission...) but the one that best suits my needs is ruTorrent. Unfortunately, it is not available for my NAS model :(

DS218play
Realtek RTD1296 SoC

It would be great if someone could make a package for this architecture. Thanks in advance :)

**Comment by koziygorokh** [comment]
I support, there is not enough ruTorrent

**Comment by th0ma7** [comment]
New and update to `rutorrent` version 3.10 uploaded on https://synocommunity.com/package/rutorrent
