### ISSUE TITLE
SynoCommunity/spksrc - zabbix-spk

### ISSUE THREAD

**Issue by ianwebster7713** [SynoCommunity/spksrc#3838]
Would love to have a deverton version of the zabbix spk for synology.  At a pinch a x86 version would do.  Happy to contribute $ if this will help.

I am not sure whether this involves changes to zabbix-spk or spksrc or both.

### Setup
_Package Name:_ zabbix-spk
_Package Version:_ ?

_NAS Model:_ 1819+
_NAS Architecture:_ deverton (Trying as x86)
_DSM version:_ 6.2

@zabbix-spk
@DONCIEUX-CAMILLE
@mcdull
@nckdnhm
@jborg 
@thetuxinator

### Expected behavior
Would love to have a deverton version of the zabbix spk for synology.  At a pinch a x86 version would do.

Have had a crack at a x86 version myself but lack skills and/or knowledge to make it work

### Actual behavior
Compilation for x86 failed on
1) zlib in cross - I created new Makefile, PLIST and digests for latest version
2) MYSQL in cross  - I created new Makefile, PLIST and digests for latest version
3) MYSQL in native - I tried a new Makefile but this didn't really work

Now I just get it crashing for lack of memory on mysql directory operations.

make[6461]: Entering directory '/home/osboxes/spksrc/native/mysql5'
make[6461]: ../../mk/spksrc.directories.mk:12: fork: Resource temporarily unavailable

### Steps to reproduce
_1._ Run compile operation on debian box per https://zabbix.org/wiki/InstallOnSynology

#### Package log
N/A
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by DONCIEUX-CAMILLE** [comment]
Hello

Please have a look on the compiled package in 4.4.4 branch
https://github.com/DONCIEUX-CAMILLE/zabbix-spk

The 6.2 toolchain is not available for Denverton. So I've compiled it with 6.1 instead, and don't worry, it's ascendant compatible.

Happy new year

Camille

**Comment by ymartin59** [comment]
SynoCommunity does not provide this package. If you expect so, please submit a PR with sources.

**Comment by gianlucaromito** [comment]
> Hello
> 
> Please have a look on the compiled package in 4.4.4 branch
> https://github.com/DONCIEUX-CAMILLE/zabbix-spk
> 
> The 6.2 toolchain is not available for Denverton. So I've compiled it with 6.1 instead, and don't worry, it's ascendant compatible.
> 
> Happy new year
> 
> Camille

Hi Camille, can you provide the "source" on how to cross compile zabbix spk? I need the proxy for the synology (and in your spk I can only see agent and server...) but I have some problems creating an spk.
Thanks for your help!
Gianluca
