### ISSUE TITLE
MUTT seems to not have been compiled with SASL support

### ISSUE THREAD

**Issue by CINJ** [SynoCommunity/spksrc#3840]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ MUTT
_Package Version:_ 1.5.24-2

_NAS Model:_ RS212
_NAS Architecture:_ ARM5
_DSM version:_ DSM 6.2.2-24922 Update 4

### Expected behavior
Using GMAIL SMTPS I should be able to send email 

### Actual behavior
Scenario 1: using SMTPS in the protocol of the config as follows
```
set smtp_url = 'smtps://joe@xxx.com@smtp.gmail.com/'
```
provides a message upon attempting to send that SASL is required

Scenario 2: using SMTP protocol as follows 
```
set smtp_url = 'smtp://joe@xxx.com@smtp.gmail.com:587/'
```
will just cause a core dump...

### Steps to reproduce
_1._ Set up a GMAIL imap account with smtps for the outbound mail 
```
set smtp_url = 'smtps://joe@xxx.com@smtp.gmail.com/'
```

_2._ start `mutt` and attempt to send an email

_3._ a TLS connection occurs, however a message is displayed...
```
SMTP authentication requires SASL
```
and the message is not sent. 

I have installed SASL as follows:
```
sudo /opt/bin/ipkg install cyrus-sasl-libs
sudo /opt/bin/ipkg install cyrus-sasl
```
and the system is happy and thinks it is installed fine.
setting `SASL_PATH` has no effect

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
no logs available

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```
Nothing of interest here either.

**Comment by ymartin59** [comment]
mutt package is still beta and has not been tested on DSM 6. By the way, "ipkg" is for optware/entware and is not related to SynoCommunity packages.
