### ISSUE TITLE
Python 3.5 instead of Python 3.6 is found via DSM Package Center for DS918+

### ISSUE THREAD

**Issue by programatix** [SynoCommunity/spksrc#3841]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ python3
_Package Version:_ v3.6.8-9

_NAS Model:_ DS918+
_NAS Architecture:_ apollolake 
_DSM version:_ 6.2.2-24922 Update 4

### Expected behavior
The DSM Package Center should find and install Python 3.6.8-9

### Actual behavior
The DSM Package Center only sees Python 3.5.6-8

### Steps to reproduce
_1._ Run Package Center
_2._ Select Python3 by Allan Clark
_3._ Newest version found is 3.5.6-8

#### Manual install
I manually downloaded Python 3.6.8-9 from https://synocommunity.com/package/python3 using the link https://packages.synocommunity.com/python3/9/python3.v9.f4458[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-grantley-kvmx64-x86-x86_64].spk and manually install it using Package Center. It installed fine and Python 3.6.8-9 works without any issue.

It now shows as below. Note the ```installed version``` and the ```newest version```.
![image](https://user-images.githubusercontent.com/3293865/71610394-8b153600-2bcb-11ea-8110-ddf03c87e6a1.png)

**Comment by ymartin59** [comment]
Packages for Python 3.6 has been "unpublished" because bugs with cross-compilation. Only x64 variant is functional. Work is in progress: #3833

**Comment by TekGamer** [comment]
Same issue on a Synology DS1817+, Package Center only sees Python3 3.5.6-8 instead 3.6.8-9

**Comment by NateEaton** [comment]
Same issue on a Synology DS216play. Package Center shows Python 3.5.6-8. After ssh into server, executing /volume1/@appstore/python3/bin/python3 --version and /usr/local/python3/bin/python3 --version both return 3.5.6. Another issue however is that the path to Python 3 (/usr/local/python3/bin) is not added to the PATH environment variable so unable to reference python3 at command line without explicit path.

**Comment by ymartin59** [comment]
@NateEaton As an additional reminder: NO, Python 3.6 is not published yet as cross-compiled applications fail to run #3944 and NO, Python 3 will never by added to PATH: #3899

**Comment by hgy59** [comment]
It's confusing that on this page https://synocommunity.com/package/python3 you can download Python3 3.6.8-9. On the Overview Page https://synocommunity.com/packages Python 3 is labeled with v3.5.6-8. It looks like version 3.6.8-9 is disabled for the Package-Download by Diskstations but not for manually downloads.
I would expect to hide inactive Versions on the detail pages - or to mark such versions as _Inactive_.
Overview:
![Python3_overview](https://user-images.githubusercontent.com/12009964/79261419-158a5880-7e90-11ea-9a13-ae435334326a.png)
Details:
![Python3_details](https://user-images.githubusercontent.com/12009964/79261434-1ae7a300-7e90-11ea-8a42-652fe0e1e0b1.png)

**Comment by ymartin59** [comment]
@hgy59 I confirm. Good idea but "active" flag is on per-architecture build. https://github.com/SynoCommunity/spkrepo/issues/41

**Comment by TekGamer** [comment]
any update on this?  Will Python 3.5 on SynoCommunity get updated from 3.5.6 to 3.7.8 or 3.8.5 ?

**Comment by ymartin59** [comment]
Trouble is not the Python package version itself but also related applications where wheels requirements have to be built for the same version.
Python 3.7.7 should come, as soon as applications have been updated: beet, homeassistant, rdiff-backup, borgbackup

**Comment by webpatrick** [comment]
When is python 3.8 coming? The next version of HomeAssistant core needs it

**Comment by hgy59** [comment]
#4287

**Comment by hgy59** [comment]
Python v3.7.7-15 is active and Python 3.8 is WIP
