### ISSUE TITLE
git: SSL certificate problem, unable to get local issuer certificate

### ISSUE THREAD

**Issue by Mickroz** [SynoCommunity/spksrc#3843]
after updating to Git 2.24.1-12, i keep getting for example:
```
fatal: unable to access 'https://github.com/SickChill/SickChill.git/': SSL certificate problem: unable to get local issuer certificate
```
This happens aswell when i manually pull a git, or clone a git.
I've tried reinstalling Git, but didn't work.

**Comment by Mickroz** [comment]
Ok, so after many tries, and posting this issue, i finally fixed this by running this as root on my diskstation:
```
git config --system http.sslCAInfo /etc/ssl/certs/ca-certificates.crt
```
now, everything works again.

**Comment by ymartin59** [comment]
@Mickroz Thanks for reporting. I will look for a way to include fix in package itself.

**Comment by hgy59** [comment]
@ymartin59 I fixed this and am working on updates of curl and git

**Comment by BatyaGurAriye** [comment]
I had the same error, I ran the command you gave and this is what I got
```
error: could not lock config file C:/Program Files/Git/etc/gitconfig: Permission denied
```
