### ISSUE TITLE
Python Issues & SABnzdb

### ISSUE THREAD

**Issue by HPMSGEN8** [SynoCommunity/spksrc#3845]
Setup
Package Name: Python
Package Version: 2.7.14-19

Package Name: Python
Package Version: v3.5.6-8

Package Name: SABnzdb
Package Version: 2.3.9-40 [03c10dc]

NAS Model: Synology
NAS Architecture: Synology
DSM version: DSM 6.2.2-24922 Update 4

I started to see the below errors in SABnzdb - ```Exit(1) Python 2.7 is no longer supported```. When i open to more info i get the below:

```
Please use a newer version of Python.
Python End-of-Life for current versions:
v3.5 in  252 days
v3.6 in  718 days
v3.7 in 1269 days
Python 2.7 is no longer supported.
```

I did run ```pip install --upgrade pip``` and this removed v9.0.1 and install v19.3.1

Any help on this please.

Thanks

**Comment by BenjV** [comment]
First of all pip has nothing to doe with Sabnzbd and pip is not used at all for any SynoCommunity package.

Secondly to my knowledge SabNzbd only runs on Python 2.7 so it seems not possible that this error is from SabNzbd.

**Comment by chickenandpork** [comment]
> pip is not used at all for any SynoCommunity package.

I forget if pip is used to unpack python wheels during install.

**Comment by BenjV** [comment]
As far as I know all Python application in the packages are using a virtual environment and not pip.
Besides that, it would not be needed to upgrade pip and without specifying the correct path it will not upgrade the pip of the SynoCommunity python.

Besides all that pip has nothing to do with the python version used by SabNzbd.

**Comment by ymartin59** [comment]
I confirm `pip` is used to install cross-compiled (or pure python) wheels into application specific virtual environment: https://github.com/SynoCommunity/spksrc/blob/master/spk/sabnzbd/src/service-setup.sh#L20

Application package is generated for a specific Python version - most for 2.7 or 3.5 for borg, beeets and homeassistant at the moment. So a full package update, testing and publishing is required to move to Python 3 and more recent pip version.

It seems that Python 3.6 will be available soon as SynoCommunity package, so then it will be possible to update applications to that version - as far as it is supported by application itself.

**Comment by ymartin59** [comment]
Now the question is where does this "End-of-Life" brutal exit comes from? Probably from Python 2.7 code itself... I am working on ffsync and only 2.7 is supported too. Looks like we will have to work again on 2.7 package to discard that behavior #3648.
CC @hgy59

**Comment by ymartin59** [comment]
Answer: this message and "fatal exit" comes from pip itself https://github.com/pypa/pip/issues/6207
Options are available to ignore deprecation. Must be tested and included in application installation script.

**Comment by HPMSGEN8** [comment]
I seem to of found the issue. It was with the nzbToMedia scripts. I have updated this and it fixed my issue.
