### ISSUE TITLE
unable to install redis on DS214+ (DSM 6.2.2)

### ISSUE THREAD

**Issue by vosegro** [SynoCommunity/spksrc#3850]
Hi

trying to install redis from SynoCommunity gives:
"Nicht verfügbar" (not available)

### Setup
_Package Name:_ redis
_Package Version:_ 5.0.7-6

_NAS Model:_ DS214+
_NAS Architecture:_ Marvell Armada XP MV78230
_DSM version:_ DSM 6.2.2-24922 Update 4

### Expected behavior
redis should install via package center

### Actual behavior
Error message: 'not available'
### Steps to reproduce
_1._ try to install redis via package center

#### Package log
no direcotry /usr/local/redis

#### Other logs
/var/log/synopkg.log:
2020/01/10 16:10:56 install redis 5.0.7-6 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2020/01/10 16:10:56 install redis 5.0.7-6 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2020/01/10 16:10:56 install redis 5.0.7-6 failed

**Comment by vosegro** [comment]
After a 3d reboot and a tenth install attempt, 
redis has installed.
Very strange.

**Comment by hgy59** [comment]
While developing packages sometimes I get the error message 'not available' too and the only solution I found so far is to reboot the diskstation.
I saw this issue only with local installation from spk and not from package center download.
I assumed an uncomplete/bad uninstall but any further hint would be appreciated.

**Comment by vosegro** [comment]
Actually it is not complete tracable to me.
As far as I remember:
I first tried several time to install it via package center.
Then I rebooted the station and tried again via package center without success.
After that I downloaded the spk and tried manually from command line without success.
Thereafter I uninstalled redis again on command line, rebooted, then it installed via package center.
If I should do a guess: Perhaps the uninstall on the command line cleaned up everything?

**Comment by ymartin59** [comment]
Based on hint that command `/bin/rm -rf /volume1/@tmp/pkginstall` failed, I would emit the hypothesis a previous package installation (either from spk or package center) has not succeeded properly and left inconsistent files at that location...
And probably reboot has cleaned up `/volume1/@tmp`, making it possible subsequent installation then.
