### ISSUE TITLE
NextCloud 17.0.2

### ISSUE THREAD

**Issue by DigitalBox98** [SynoCommunity/spksrc#3851]
Anyone interested to test NextCloud 17.0.2 package on Synology ?

Inspired from OwnCloud package, I've created one and tested it with PostgreSQL 11.6 or SQLite on DS716+II (not tested with Maria DB).

It requires Apache HTTP Server 2.4 and PHP 7.3 with extensions enabled. It's still in beta but is useable.

### Setup
_Package Name:_  NextCloud 
_Package Version:_ 17.0.2

<img width="831" alt="NextCloud" src="https://user-images.githubusercontent.com/57635141/72182088-099f7e00-33eb-11ea-84e4-b549c99e8e4e.png">
<img width="437" alt="DB" src="https://user-images.githubusercontent.com/57635141/72182091-0c9a6e80-33eb-11ea-8794-1ea2c9183d33.png">

**Comment by ymartin59** [comment]
@DigitalBox98 Great job really ! May you please submit a PR so that I can review it?
My device is an quite old one and I would prefer to use embedded PostgreSQL instance to preserve memory... do you think it may be possible?

**Comment by DigitalBox98** [comment]
Ok I will check to submit a PR for NextCloud.

Embedded PostgreSQL seems to be accepted as well, I've made a quick check and it's OK :

<img width="423" alt="DB-syno" src="https://user-images.githubusercontent.com/57635141/72208499-99086800-34a3-11ea-9340-1c84563d03eb.png">

**Comment by DigitalBox98** [comment]
I close this as PR was published :)
