### ISSUE TITLE
TVheadend 4.3 for cedarview 

### ISSUE THREAD

**Issue by pepeEL** [SynoCommunity/spksrc#3863]
Is any chance to share file spk for platform cedarview with latest new version 4.3 >?

**Comment by th0ma7** [comment]
cedarview is a `x86_64` arch so the generic `x64` should normally work.

Individual packages are available here (but really you should use the package manager and add SynoCommunity package channel):
* https://synocommunity.com/package/tvheadend

But I did noticed that there are a few missing, including the one you are looking for.
I'll check if we can fix that.

**Comment by pepeEL** [comment]
Ok thanks. I am waiting for info.

**Comment by ymartin59** [comment]
Sorry for that, a failure when publishing... x64 architectures are now available.

@th0ma7 Notice tvheadend compilation fails for 88f6281-6.1 because of
```
src/imagecache.c:271:9: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result [-Werror=unused-result]
src/imagecache.c: At top level:
cc1: error: unrecognized command line option "-Wno-stringop-overflow" [-Werror]
cc1: error: unrecognized command line option "-Wno-stringop-truncation" [-Werror]
```

**Comment by th0ma7** [comment]
@ymartin59 I thought it always did... humm, will have a second look at it.

**Comment by th0ma7** [comment]
Opened-up a bug here:
* https://tvheadend.org/issues/5849

**Comment by hgy59** [comment]
> 
> 
> Opened-up a bug here:
> 
>     * https://tvheadend.org/issues/5849

@th0ma7 IMHO this is not a bug related to tvheadend. The error log tells, that the 88f6281 cross compiler (of the synology toolchain) does not support the command line options to disable these two warnings.
```
cc1: error: unrecognized command line option "-Wno-stringop-overflow" [-Werror]
cc1: error: unrecognized command line option "-Wno-stringop-truncation" [-Werror]
```
So we need to patch the make file either to not treat warnings as errors or to remove the two options for arch-88f6281.

**Comment by hgy59** [comment]
BTW I have a similar error (-Wno-unused-result) with cffi for python3 for arch-ppc853x, but cannot find the Makefile that is used with spksrc.python-module.mk and setup.py... (related to #3229)

**Comment by th0ma7** [comment]
@hgy59 I believe you are poiting towards the right direction... I also found a few places online where this type of error got fix with a simple trivial patch to the code but I didn't found anything close enough to point me with a valid fix... Reason why I ended-up opening a bug entry...

Playing with the `Makefile` and testing a few compile option is next on my list...  If I find something I'll let you know, duno, could be useful for your python3 error?

**Comment by th0ma7** [comment]
@pepeEL where you able to install the 4.3.x package through regular synology package update?

@hgy59 I've found a workaround from the `configure` script where it's possible to add `--nowerror` which does build without `-Werror` CFLAGS.  Using that it now build on `88f6281` arch as well.

Will push a new pull request shortly to permanently fix that.
