### ISSUE TITLE
TVHeadend/Surveillance Station/DSCam

### ISSUE THREAD

**Issue by megahorst** [SynoCommunity/spksrc#3868]
_For new Package Requests, see the guidelines_  

### Setup
Tvheadend v4.3.20191128~221c29b-17
ffmpeg v4.2.1-23

DS115
_NAS Architecture:_ 
DSM 6.2.2-24922 Update 4

### Expected behavior
When trying to play a video recorded by the Surveillance Station in DS Cam it shoud play.
Before installing TVHeadend and ffmpeg this has worked without any problems

### Actual behavior
When trying to play a video recorded by the Surveillance Station in DS Cam you see just a moving circle after you have tried to start it.
In  the desktop version of the surbeillance station it still works fine.

### Steps to reproduce
_1._ Move to recordings into DSCam
_2._ Try to start a recording
_3._ see the moving circle

Any suggestions how to debug this?

**Comment by th0ma7** [comment]
Having a good lead on the possible cause which probably relates to ffmpeg.
Working on new sets of packages.
May take a few cycles before getting there, will let you know once ready for testing.

This bug also relates to:
* https://github.com/SynoCommunity/spksrc/issues/3861
* https://github.com/SynoCommunity/spksrc/issues/3862

**Comment by th0ma7** [comment]
@megahorst ,
New testing packages available here:
* https://github.com/th0ma7/synology/tree/master/packages

Give it a shot at version `4.3.20191128~221c29b-18` and let me know if this solves your issue.

**Comment by megahorst** [comment]
I gave it a try. It seems to work.
DSCam is fine, no issues seen in TVHeadend.

Thx for your effort!!!

**Comment by th0ma7** [comment]
This is great!  Thnx for testing.
I'll close the issue and in the meantime keep the packages available in my github account until new ones are officially made available using regular SynoCommunity channels.
If you're interested at testing keep on eye on it as I may build new updated packages.
Cheers!

**Comment by megahorst** [comment]
Hello it seems that with the current release 4.32-37 running on DS718+ the problem is back.
Is there any help from your side possible?
