### ISSUE TITLE
No free adapter available with more than one Input

### ISSUE THREAD

**Issue by Surkel** [SynoCommunity/spksrc#3870]
Hi,

my Tvheadend (HTS Tvheadend 4.3.99rc1~221c29b) runs very good, but I can't use my second adapter.
it is shown in the dvbinput section and I configured it such as the first adapter, but when I try to use 2 streams parallel then I got the error message No free adapter available, when the first stream is running.
Any idea?

**Comment by Surkel** [comment]
After restart of synology, the connected usb dvb-s Receiver is shown in config, but the section „universal lnb“ is missing

**Comment by BenjV** [comment]
Seems to me a question for a TvHeadend forum.

**Comment by Surkel** [comment]
In my first solution I used an raspberry with 2 usb dvb-s Inputs and I had no problems, maybe a config problem?
In video Station both inputs where shown but in tvheadend the second universal lnb is missing at the second input

**Comment by Surkel** [comment]
I think it has to do with the input config, for the raspberry I can reset the config with this command
sudo rm -rf /home/hts/.hts/tvheadend/input

But where are the files on the Syno?

**Comment by BenjV** [comment]
I am not a tvheadend user but the installation location of tvheadend can be found in the folder:

> /var/packages/tvheadend/target

**Comment by Surkel** [comment]
Find the solution!
Following steps I do;
1. Login via ssh
2. root access via: sudo -i 
3. go to folder /usr/local/tvheadend/var/input/linuxdvb/adapters
4. rm *
5. restart tvheadend
