### ISSUE TITLE
RClone mounting GDrive fails due to missing FUSE

### ISSUE THREAD

**Issue by Lonli-Lokli** [SynoCommunity/spksrc#3875]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ 	
SynoCli Network Tools
_Package Version:_ 1.0-1

_NAS Model:_ Synology 918+
_NAS Architecture:_ x64
_DSM version:_ DSM 6.2.2-24922 Update 4
--

### Expected behavior
I should be able to use rclone with fuse libraries installed

### Actual behavior
So I've installed rclone in docker from this package https://github.com/romancin/rclonebrowser-docker which internally do all the stuff with installing https://github.com/romancin/rclonebrowser-docker/blob/master/Dockerfile.
Actually mounted GDRives opens fine with RClone but whenIm trying to mount happens this error
07:01:51 mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first
07:01:51 Fatal error: failed to mount FUSE fs: fusermount: exit status 1

FUSE libraries are required for mounting GDrive on Syno (Im following this guide https://bitbucket.org/fusebit/plex-and-google-drive/wiki/Install%20rclone%20on%20Synology%20NAS)

**Comment by BenjV** [comment]
I fail to see what this has to do with the SynoCommunity.
Docker problems have nothing to do with the packages her provided.

**Comment by hgy59** [comment]
@Lonli-Lokli for FUSE you have to install `synocli-disk` and not `synocli-net`.

**Comment by Lonli-Lokli** [comment]
@hgy59 thanks a lot!
I know it might be not the correct place but now I get error while.mounting with rclone --allow-other
option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf

But on my syno /etc/fuse.conf already have this line uncommented

**Comment by Lonli-Lokli** [comment]
Nevermind, I solved it.
Thanks for your help and all your work!
