### ISSUE TITLE
SynoCli Disk Tools testdisk missing e2fsprogs option

### ISSUE THREAD

**Issue by vizbird** [SynoCommunity/spksrc#3879]
testdisk appears to not be compiled with e2fsprogs. This was noticed when accessing a ext4 partition via testdisk on Windows/Ubuntu but gives a compilation message when accessing via DSM. I have tried compiling the package with some settings added but have not been successful. Requesting that e2fsprogs be added to the build or some advice on compiling it.

### Setup
_Package Name:_ SynoCli Disk Tools
_Package Version:_ 1.0-1

_NAS Model:_ DS218+
_NAS Architecture:_ apollolake
_DSM version:_ 6.2.2-24922 Update 4 (package compiled as 6.1)

### Expected behavior
testdisk should be able to access a ext4 partition

### Actual behavior
testdisk is not able to access a ext4 partition

### Steps to reproduce
_1._ `:$ sudo testdisk -v`
_2._ notice ext2fs lib: none
_3._ edit makefile for cross/testdisk ([https://www.cgsecurity.org/wiki/TestDisk_Compilation](https://www.cgsecurity.org/wiki/TestDisk_Compilation)):
`DEPENDS = cross/ncursesw cross/libuuid cross/e2fsprogs`
`DEP_E2FSPROGS = $(WORK_DIR)/e2fsprogs-1.45.4`
`DEP_E2FSPROGS_LIB = $(DEP_E2FSPROGS)/lib/`
`DEP_E2FSPROGS_INCLUDE = $(DEP_E2FSPROGS)/include/`
`CONFIGURE_ARGS = --with-ext2fs-lib=$(DEP_E2FSPROGS_LIB) --with-ext2fs-includes=$(DEP_E2FSPROGS_INCLUDE)`
_4._ uninstall, compile, and install new spk
_5._ `:$ sudo testdisk -v`
_6._ still ext2fs lib: none

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
NA
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
NA
```

**Comment by vizbird** [comment]
I may have found an issue:
`In file included from ext2_dir.c:38:0:
/spksrc/spk/testdisk/work-apollolake-6.2.2/install//var/packages/testdisk/target/include/ext2fs/ext2fs.h:66:5: warning: "EXT2_FLAT_INCLUDES" is not defined [-Wundef]
 #if EXT2_FLAT_INCLUDES
     ^`

It looks like something is causing a // to occur instead of a / in "install//var/packages". This is happening in all of the ext2 files.

**Comment by hgy59** [comment]
`//` are not a problem in this build environment.
The package is not built with e2fsprogs as dependency.
You can validate this with `testdisk -v`
```
$ /var/packages/testdisk/target/bin/testdisk  -v
TestDisk 7.0, Data Recovery Utility, April 2015
Christophe GRENIER <grenier@cgsecurity.org>
http://www.cgsecurity.org

Version: 7.0
Compiler: GCC 4.6
Compilation date: 2015-07-22T09:30:10
ext2fs lib: none, ntfs lib: none, reiserfs lib: none, ewf lib: none, curses lib: ncurses 5.9
OS: Linux, kernel 3.2.40 (#24922 Mon Aug 19 12:09:30 CST 2019) armv7l
```

I am working on adding all the missing dependencies (ext, ntfs, reiser, ewf)
this gives the following output:
```
$ which testdisk
/usr/local/bin/testdisk
$ testdisk -v
TestDisk 7.1, Data Recovery Utility, July 2019
Christophe GRENIER <grenier@cgsecurity.org>
https://www.cgsecurity.org

Version: 7.1
Compiler: GCC 4.9
ext2fs lib: 1.45.4, ntfs lib: libntfs-3g, reiserfs lib: 0.3.1-rc8, ewf lib: 20171104, curses lib: ncurses 6.1
OS: Linux, kernel 3.2.40 (#24922 Mon Aug 19 12:09:30 CST 2019) armv7l
```

**Comment by vizbird** [comment]
Awesome! I have been trying for the past few days to get it to work.

**Comment by ymartin59** [comment]
@hgy59 how have you progressed about file systems support for testdisk? may you please submit a PR if ready.
