### ISSUE TITLE
ImageMagick not converting SVG to Bitmap

### ISSUE THREAD

**Issue by philrich123** [SynoCommunity/spksrc#3881]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ ImageMagick
_Package Version:_ 7.0.8-4

_NAS Model:_ DS413
_NAS Architecture:_ FREESCALE QorIQ P1022
_DSM version:_ DSM 6.2.2-24922 Update 4

### Expected behavior
Possibility to convert SVG files to bitmap

### Actual behavior
Not possible to convert SVG files to Bitmap one. Trying to do so generate errors.

### Steps to reproduce
_1._ loggin  with ssh client
_2._ have a svg file to convert : "my_drawing.svg" for example
_3._ try command : convert my_drawing.svg my_drawing.jpg
_4._ you'll get the error :

`convert: UnableToOpenConfigureFile 'delegates.xml' @ warning/configure.c/GetConfigureOptions/677.
convert: NotAuthorized 'MVG' @ error/constitute.c/IsCoderAuthorized/408.
convert: NoImagesDefined 'dessin.jpg' @ error/convert.c/ConvertImageCommand/3258.`

**Comment by DigitalBox98** [comment]
Convert SVG format from ImageMagick requires rsvg-convert (from librsvg)
I don't think rsvg-convert is available for Synology (not cross compiled so far)

**Comment by hgy59** [comment]
I can confirm that librsvg will be a huge task to add. It depends on additional libraries and some of them are hard to build.
- cross/glib 
- cross/libxml2
- cross/libroco (not yet available, succeded to build for x64)
- cross/gdk-pixbuf (has other dependencies, needs meson build system)
  - cross/libjpeg-turbo (not yet available, includes asm code/depends on NASM and yasm)
  - cross/libpng
  - cross/shared-mime-info (not yet available)
- cross/cairo (available with PR #3856)
- cross/pango (available with PR #3856)
- rustc (oh yes! libsrvg was ported from c to rust)

hard facts:
- meson build for spksrc is still under construction (PR #3820)
- rust build for spksrc is under construction too (PR #3883)
- both needs update of the environment (Dockerfile)

So there is little hope, that there will be an update of imagemagick spk to support svg image conversion.

**Comment by ymartin59** [comment]
@hgy59 So only remains Meson build support for cross-compilation to hope to get it available...

**Comment by hgy59** [comment]
@philrich123 hold on, an update is on the way with #5414 and svg is supported incl. for qoriq (only ARMv5_ARCH and OLD_PPC_ARCHS will not support svg in imagemagick)
