### ISSUE TITLE
Mutt is not runnin after installing

### ISSUE THREAD

**Issue by leotzian** [SynoCommunity/spksrc#3882]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ mutt
_Package Version:_ 1.5.24-2

_NAS Model:_ DS416PLAY
_NAS Architecture:_ 
_DSM version:_ DSM 6.2.2-24922 Update 4 

### Expected behavior
Installing but not running

### Actual behavior
Press Run and it doent start and returns to run again

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
No package log
Insert the package log here
`There is no package log there
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
mutt is a command line tool that has no real `running` state.
As mutt is not yet migrated to DSM 6 it does not display `running` and cannot be started. Anyway on the command line mutt is executable and IMHO fully working.
When migrated to DSM 6 the status will be running (and have no start/stop function provided).

While working on #3840 I already fixed this.

**Comment by leotzian** [comment]
Hi thanks from the answer, because I am not a experienced user, please I want a little help.
I had installed mutt through package center.
It had installed ok but it is not starting, you say it is normal and mutt s working in the CLI.
I want to use mutt to sent emails through CLI .
Please can you provide me a link how the syntax must be in the CLI.
I want to make a script in Jdownloader to make mutt to sent a email about download finished.
I want the message to have subject and small body.
Thanks you very much in advance.

**Comment by BenjV** [comment]
As always.
This is not the place to get support on the application themselves.
The SynoCommunity is only packaging application into a Synology package.
For support you have to ask the developers of the application.

For mutt see:
http://www.mutt.org/#doc
