### ISSUE TITLE
[Package Request] Adminer 4.7.6

### ISSUE THREAD

**Issue by DigitalBox98** [SynoCommunity/spksrc#3888]
Name: Adminer
Description: Propose Adminer to latest version 4.7.6

I got it working and connecting to embedded PostgreSQL. If someone is interested let me know (I only have an issue with git and the PR process: I have created a new branch for Adminer but this PR is mixed with a previous one (postgresql))

<img width="709" alt="adminer" src="https://user-images.githubusercontent.com/57635141/74884397-62abeb80-5373-11ea-9e56-ebf6d5e41593.png">

**Comment by hgy59** [comment]
@DigitalBox98 did you remove the patch file to enable connection to embedded PostgreSQL - or is such a patch still required?

**Comment by DigitalBox98** [comment]
I have applied the same patch again on this version but I haven't tested if it was OK without it :)

**Comment by hgy59** [comment]
@DigitalBox98 so you adapted the patch file for the current Version? Otherwise the patch cannot be applied due modified source file and the build would fail.

**Comment by DigitalBox98** [comment]
yes correct it was adapted :)

**Comment by hgy59** [comment]
@DigitalBox98 and the reason for this patch is written in the patch file:
```
# See https://github.com/SynoCommunity/spksrc/issues/2662
# Remove the extension pgsql because the extension pgsql does not work with the PostgreSQL server from DSM. The Extension pdo_pgsql works perfectly.
```

**Comment by hgy59** [comment]
@DigitalBox98 did you use the information in the [wiki](https://github.com/SynoCommunity/spksrc/wiki/Adminer) to connect to the internal postgresql?

**Comment by hgy59** [comment]
@DigitalBox98 in my PR I switched to a different adminer design. As you can see in your screenshot above, the links to select data from tables is missing the icon. It shows `select` as text instead. Before the update the `nette` design showed icons here.

**Comment by DigitalBox98** [comment]
To connect to the internal postgresql, I have created an additional admin user (pgadmin) so that I can choose the correct password to have access to all the databases. This part is not included in the package :)
Thanks for the hint about the design icon.
