### ISSUE TITLE
TVHEADEND CANT LOGIN 403 forbidden

### ISSUE THREAD

**Issue by Jethro68** [SynoCommunity/spksrc#3889]
Not sure why this is happening
Synology NAS 918

**Comment by th0ma7** [comment]
Weird..No clue either.  Are you using on the default port :9981 ?
You can have a look at: https://tvheadend.org/projects/tvheadend/wiki/Faq
They provide options to disable ACL so you can adjust/recreate user and passwords as needed.

There is a log file locate at:
`/var/packages/tvheadend/target/var/tvheadend.log`

It tells how your tvheadend was started.   Mine shows the following:
```
Starting tvheadend command /volume1/@appstore/tvheadend/bin/tvheadend -f -u sc-tvheadend -g tvheadend --http_port 9981 --htsp_port 9982 -c /volume1/@appstore/tvheadend/var -p /volume1/@appstore/tvheadend/var/tvheadend.pid 
```

So I guess that manually you could do the following to disable ACL and reset your password:
1) Stop tvheadend:
```
sudo synoservice --stop pkgctl-tvheadend
```
2) Start with ACL disabled:
```
sudo su -s /bin/bash sc-tvheadend -c '/volume1/@appstore/tvheadend/bin/tvheadend -f -u sc-tvheadend -g tvheadend --http_port 9981 --htsp_port 9982 -c /volume1/@appstore/tvheadend/var -p /volume1/@appstore/tvheadend/var/tvheadend.pid --noacl'
```
3) Make the required adjustments from the web interface
4) CTRL-C to stop temporary running tvheadend
5) restart tvheadend normally
```
sudo synoservice --restart pkgctl-tvheadend
```

**Comment by McBochi** [comment]
This also happens to me from time to time, didn't do any further debugging though...
Clearing cache or using a private tab resolves the issue for me.

**Comment by th0ma7** [comment]
Thnx @McBochi for the info.
Closing the issue.
