### ISSUE TITLE
python 3.6 does not create symlinks in /usr/local/bin

### ISSUE THREAD

**Issue by Magissia** [SynoCommunity/spksrc#3890]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Python3
_Package Version:_ 3.6.8-11

_NAS Model:_ 918+
_NAS Architecture:_Apollolake 
_DSM version:_ 6.2.2

### Expected behavior
Package creates symlinks of python3 and pip3 in /usr/local/bin

### Actual behavior
Both symlinks are absent.

### Steps to reproduce
_1._ Install package
_2._ 
_3._ 

Why is it reported as an issue ?
The cli packages creates the symlinks, hence should be possible for python3 too.
If creating symlink myself there will be leftovers after an uninstall.

**Comment by BenjV** [comment]
Why would you want to create such simlink?
DSM applications are build as packages and if a package needs Python3 then it will find it by using the full path.
Simlink and "path" environment variable for this purpose are antiek and created for lazy commandline users who don't want to type to much characters.

So if you insist to use a simlink you have to create them yourself and if desired remove them yourself..

**Comment by Magissia** [comment]
I guess one could use /volume1/@appstore/python3.6/bin/python3 /path/to/script each time to execute a script ?

What if the python3 package is installed on volume2 and the package requiring it is on volume1, will it find it on volume2 ?

Why would nano from the cli package get a symlink then ? One could write /volume1/@appstore/synocli-file/bin/nano /path/to/file each time too ?

Official Syno virtualization package has this behavior too, they add qemu symlink to /usr/local/bin, same story for node.

It goes even as far as, if one jumps throug and goes `sudo -H /volume2/@appstore/python3.6/bin/pip3 youtube-dl`, you won't be able to use youtube-dl after, you will have to use `/volume2/@appstore/python3.6/bin/python3 /volume2/@appstore/python3/lib/python3.6/site-packages/youtube_dl/__main__.py` and this starts to get ridiculous.

I doubt it is wrong to stay consistent and follow how Synology started, and how this project started with the cli package.

**Comment by BenjV** [comment]
You should use:

> /var/packages/python3/target/bin/python3

That will always point to the correct location regardless on which volume python3 was installed.

**Comment by ymartin59** [comment]
Here at SynoCommunity, we avoid to put commands in PATH except when tools are expected to be used from command line by end-users AND it does not replace already existing command in DSM system.

**Comment by Magissia** [comment]
It is not expected to use youtube-dl from command line ?

**Comment by BenjV** [comment]
Correct. 
DSM and all the packages are is gui driven.
If you want a commandline interface it would be a better idea tof to use a standard Linux environment and not a Synology Nas.

**Comment by hgy59** [comment]
@Magissia you can run python code when you install the Python3 package from synology. If you want to use python3 of synocommunity you have to setup the environment (path, etc.) yourself for the same result.
For this approach the python installation knows nothing about your module. You can uninstall python without warning and your module will not run anymore - or you update the python installation and your module might not run anymore.
If you want to avoid this, you have to develop an spk that depends on python and optionally links your command line tool to /usr/local/bin.

**Comment by ymartin59** [comment]
@Magissia I am using youtube-dl as a all-in-one single binary. No need for Python or other module dependencies... And as easy to update as youtube-dl -U. But only available for Intel x46 architectures or evansport. For other architectures, I doubt youtube-dl module requirements are all pure-Python code - but if not, it requires cross compilation and so a SynoCommunity package for that.
