### ISSUE TITLE
[Package Request] DotNet Core 3.1

### ISSUE THREAD

**Issue by or29544** [SynoCommunity/spksrc#3892]
_Package Name:_ Microsoft .NET Core
_Package Version:_ 3.1

_NAS Model:_ DS218
_NAS Architecture:_ rtd1296 (armv8)
_DSM version:_ DSM 6.2.2-24922 Update 4

**Comment by szyb** [comment]
Please consider this architecture as well:

NAS Model: DS718+
NAS Architecture: x86_64 (apollolake)
DSM version: DSM 6.2.2-24922 Update 4

**Comment by ymartin59** [comment]
From my point of view, but I may be wrong, adding .Net Core support to framework allows to compile applications like Jellyfin #3660 or Bitwarden #3712 for DSM but it does not make to deliver a package with .Net Core itself.

**Comment by szyb** [comment]
Adding .Net Core SDK will allow you to compile (from source) other software that is targeted to .Net Core. The runtime version of the .Net Core will only allow to run binaries, however it could cover most use cases but only when vendor is providing compiled version of the software. 
Both SDK & runtime should have the same complexity to build it as a package to DSM.

**Comment by or29544** [comment]
Ah, the request is not about compiling .NET Core applications. It's rather to have it as a runtime for the DSM web server like there is now nginx and PHP and whatnot. The point is to be able to enable the DSM Web Server, copy a .NET Core application in a folder on the NAS and then allow the Web Server to run that application by having the .NET Core package installed. It's just like you have nodejs - exactly the same idea. What we have now for DSM in relation to nodejs - that exactly what I want for .NET Core. That way I could run my .NET Core web applications from the DSM and host them there in the DSM Web Server.

**Comment by ymartin59** [comment]
I have already received generated application which embedded .Net Core runtime, which may be a relevant to publish DSM packages, as framework already rebuilds all dependencies... It depends how large is runtime. I am not a .Net developer, so contributor will decide how to deliver, as far as cross-compilation is OK.
We are already in a mess with Python 3 and all python-based applications...

**Comment by szyb** [comment]
I have a little update concerning running .NET Core on DSM 6.2. 
As pointed out at [this dotnet runtime issue](https://github.com/dotnet/runtime/issues/33384), there are some problems with running dotnet core runtime on DSM by using precompiled binaries provided by the dotnet community. There is an error with incompatible version of `libstdc++.so`. The DSM 6.2 has it in version 6.0.20 while dotnet core runtime expects 6.0.22 (at least using this version dotnet runtime works fine). This library is not distributed together with dotnet core runtime binary package, so it rely on the library already installed on the system.

I can see two options to build SPK (I even started to do that in my spare time, but failed due to above problem):
1) in the SPK build there must be compilation (in proper architecture) of libstdc++ in proper version and distributed inside the SPK. (BTW: anyone have already try this in any other SPK package?)
2) wait for DSM 7 in hope Synology will upgrade this library in this release.

I will try to send the ticket to Synology to upgrade this library, but I doubt that it will arrive soon.

**Comment by or29544** [comment]
Uh, not a priority anymore for me at least. I moved my web server away from the Synology unit...I don't think it's a good idea to have it there anyway.

**Comment by szyb** [comment]
Closing this issue will open another one for the same thing. Dotnet Core is more and more popular and sooner or later it would be good to have it on DSM. I already have (by using workaround), but for now it is hard to create SPK for this.
Another problem (as you pointed out earlier) is to make it work together with Web Station. But this is just another step, when it will be possible to build SPK from binaries that are provided by the community.

BTW: to make it work with nginx you can just run the dotnet application on some port (i.e. 8080) and then tell nginx in config file to pass all the traffic to this local port. I didn't try it on DSM (just only on standalone debian instance) and don't know if such nginx config will not be overwritten after system restarts. Maybe I will check that some day.
```
location / 
{ 
proxy_pass http://localhost:8080; 
//other config
}
```

**Comment by szyb** [comment]
I've just received reply from Synology, that they have already upgraded libstdc++ in DSM 7.0. The version is 6.0.24, so it should be enough for dotnet core runtime in the future

**Comment by hgy59** [comment]
@szyb dotnet-runtime 6.0.4 is now available as synocommunity package (will be shown in the DSM package center withing about 48h).
I do not recommend to create a dotnet core 3.1 package anymore, as it will get EOL at December 03, 2022.

Only armv7 (32-bit), armv8 (64-bit) and x64 models with DSM 6 and DSM 7 are supported - no evansport = x86 (32-bit), no ppc and no armv5 archs.

> I've just received reply from Synology, that they have already upgraded libstdc++ in DSM 7.0. The version is 6.0.24, so it should be enough for dotnet core runtime in the future

For DSM 7 the libstdc++ of the system is used. For DSM 6 libstdc++ 6.0.22 is included in the package and dotnet is patched to use this version.

**Comment by szyb** [comment]
@hgy59 Thanks! 6.0.4 is far more better than 3.1 :) this request originally pointed to the newest .Net version at that time. 
I will check this out.
Meanwhile, I installed .NET SDK 6.x manually
