### ISSUE TITLE
HAProxy ds418play support

### ISSUE THREAD

**Issue by skalle** [SynoCommunity/spksrc#3893]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: HAProxy 
_Package Version: any 

_NAS Model: ds418play
_NAS Architecture: appollolake(x64) x18
_DSM version: DSM 6.2.2-24922 Update 4

### Expected behavior
Ability to install HAProxy

### Actual behavior
HAProxy is not avail for ds418play

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
HAProxy is not yet available for DSM 6.0+.
Further HaProxy updates (like DSM6 compatibility) will be handled in #2712.
