### ISSUE TITLE
Error installing packages: mono

### ISSUE THREAD

**Issue by etune** [SynoCommunity/spksrc#3895]
### Setup
_Package Name:_ Sonarr
_Package Version:_ 20190320-15 

_NAS Model:_ DS120j
_NAS Architecture:_ 64-bit
_DSM version:_ 6.2.2-24922-4

### Expected behavior
Should be able to install Sonarr from Community tab in Package Center. 

### Actual behavior
Won't install. Getting error.
![image](https://user-images.githubusercontent.com/2109780/75123235-af453e80-5673-11ea-8aa6-aa00c7fefca7.png)

Didn't see `mono` in the community list. Installed Mono Beta Package. Same error. SABnzbd installed fine.

### Steps to reproduce
_1._ Click Install

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
 I'm sorry. I'm new. I don't know how.
```

**Comment by hgy59** [comment]
@etune packages of SynoCommunity do not work with Mono from synology, you need the SynoCommunity package for Mono. If you cannot see the Package in the PackageCenter (but see other packages), than you can manually download it from https://synocommunity.com/package/mono,
Or you can download a prerelease of Mono 5.20 here: https://github.com/hgy59/spksrc/releases/tag/mono_v5.20-pre (#3865).
The DS120j has aarch64 architecture, so you need the respective package.
But there are known issues for Mono on aarch64 platforms (#3666, #3470).

**Comment by etune** [comment]
@hgy59 Thanks for that info. I'm new to all of this. 

If you don't mind me asking, do you think I would be better off swapping out the DS120j for the DS118? Is the architecture on the older model just going to lead to headaches for me?
