### ISSUE TITLE
Pulseaudio fails to start after update

### ISSUE THREAD

**Issue by flygrmn51** [SynoCommunity/spksrc#3907]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Hassio
_Package Version:_ 106.4

_NAS Model:_ 918+
_NAS Architecture:_ 
_DSM version:_ 6.2.2-24922 update 4

### Expected behavior
I ran the upgrade from supervisor and hassio failed to restart.

### Actual behavior
I found that the supervisor ended up going into a loop restarting the hassio_audo container. This container the stops and supervisor tries to restart, creating a continuous loop. 

### Steps to reproduce
_1._ start upgrade to 106.4
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
hassio.log:
Tue Mar  3 08:02:57 PST 2020
Starting hassio command  
Starting hass.io at /volume1/@appstore/hassio
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[16:03:04] INFO: [32mUpdate udev informations[0m
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[32m20-03-03 16:03:07 INFO (MainThread) [__main__] Initialize Supervisor setup[0m
[32m20-03-03 16:03:07 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 207[0m
[32m20-03-03 16:03:07 INFO (MainThread) [__main__] Setup Supervisor[0m
[33m20-03-03 16:03:07 WARNING (MainThread) [supervisor.dbus.systemd] No systemd support on the host. Host control has been disabled.[0m
[33m20-03-03 16:03:07 WARNING (MainThread) [supervisor.dbus.hostname] No hostname support on the host. Hostname functions have been disabled.[0m
[33m20-03-03 16:03:07 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.[0m
[33m20-03-03 16:03:07 WARNING (MainThread) [supervisor.dbus.nmi_dns] No DnsManager support on the host. Local DNS functions have been disabled.[0m
[32m20-03-03 16:03:07 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information[0m
[32m20-03-03 16:03:07 INFO (MainThread) [supervisor.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}[0m
[32m20-03-03 16:03:07 INFO (MainThread) [supervisor.host.apparmor] AppArmor is not enabled on host[0m
[32m20-03-03 16:03:07 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-audio with version 5[0m
[32m20-03-03 16:03:07 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-dns with version 1[0m
[32m20-03-03 16:03:07 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:03:07 INFO (SyncWorker_5) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:03:07 INFO (MainThread) [supervisor.misc.forwarder] Start DNS port forwarding to 172.30.32.3[0m
[32m20-03-03 16:03:07 INFO (SyncWorker_3) [supervisor.docker.interface] Restart homeassistant/amd64-hassio-dns[0m
[32m20-03-03 16:03:23 INFO (SyncWorker_5) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[32m20-03-03 16:03:23 INFO (SyncWorker_9) [supervisor.docker.interface] Attach to homeassistant/qemux86-64-homeassistant with version 0.106.2[0m
[32m20-03-03 16:03:23 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/7ad98f9c repository[0m
[32m20-03-03 16:03:23 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository[0m
[32m20-03-03 16:03:23 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository[0m
[32m20-03-03 16:03:23 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/15ef4d2f repository[0m
[32m20-03-03 16:03:23 INFO (MainThread) [supervisor.store] Load add-ons from store: 69 all - 69 new - 0 remove[0m
[32m20-03-03 16:03:23 INFO (MainThread) [supervisor.addons] Found 6 installed add-ons[0m
[32m20-03-03 16:03:23 INFO (SyncWorker_14) [supervisor.docker.interface] Attach to hassioaddons/influxdb-amd64 with version 3.6.0[0m
[32m20-03-03 16:03:23 INFO (SyncWorker_5) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-mosquitto with version 5.1[0m
[32m20-03-03 16:03:23 INFO (SyncWorker_9) [supervisor.docker.interface] Attach to hassioaddons/grafana-amd64 with version 4.2.0[0m
[32m20-03-03 16:03:23 INFO (SyncWorker_17) [supervisor.docker.interface] Attach to dwelch2101/zigbee2mqtt-amd64 with version 1.11.0[0m
[32m20-03-03 16:03:23 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-mariadb with version 2.0[0m
[32m20-03-03 16:03:23 INFO (SyncWorker_13) [supervisor.docker.interface] Attach to esphome/esphome-hassio-amd64 with version 1.14.3[0m
[32m20-03-03 16:03:23 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.snapshots] Found 1 snapshot files[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.discovery] Load 1 messages[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.ingress] Load 1 ingress session[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.secrets] Load Home Assistant secrets: 31[0m
[32m20-03-03 16:03:24 INFO (MainThread) [__main__] Run Supervisor[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.addons] Phase 'initialize' start 0 add-ons[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.core] Supervisor reboot detected[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.tasks] All core tasks are scheduled[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.hwmon] Start Supervisor hardware monitor[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.core] Supervisor is up and running[0m
[32m20-03-03 16:03:24 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information[0m
[33m20-03-03 16:03:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:03:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:03:44 INFO (SyncWorker_8) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:03:51 INFO (SyncWorker_8) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:04:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:04:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:04:04 INFO (SyncWorker_18) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:04:11 INFO (SyncWorker_18) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:04:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:04:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:04:24 INFO (SyncWorker_13) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:04:30 INFO (SyncWorker_13) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:04:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:04:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:04:44 INFO (SyncWorker_2) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:04:51 INFO (SyncWorker_2) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:05:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:05:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:05:04 INFO (SyncWorker_5) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:05:11 INFO (SyncWorker_5) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:05:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:05:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:05:24 INFO (SyncWorker_13) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:05:31 INFO (SyncWorker_13) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:05:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:05:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:05:44 INFO (SyncWorker_2) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:05:50 INFO (SyncWorker_2) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:06:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:06:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:06:04 INFO (SyncWorker_9) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:06:10 INFO (SyncWorker_9) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:06:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:06:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:06:24 INFO (SyncWorker_8) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:06:31 INFO (SyncWorker_8) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:06:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:06:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:06:44 INFO (SyncWorker_7) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:06:46 INFO (MainThread) [supervisor.auth] Auth request from core_mosquitto for iotdev[0m
[31m20-03-03 16:06:46 ERROR (MainThread) [supervisor.homeassistant] Error on call http://172.30.32.1:8123/api/: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused][0m
[32m20-03-03 16:06:46 INFO (MainThread) [supervisor.auth] Home Assistant not running, check cache[0m
[32m20-03-03 16:06:46 INFO (MainThread) [supervisor.auth] Cache hit for iotdev[0m
[32m20-03-03 16:06:51 INFO (SyncWorker_7) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:07:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:07:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:07:04 INFO (SyncWorker_5) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:07:10 INFO (SyncWorker_5) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:07:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:07:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:07:24 INFO (SyncWorker_3) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:07:30 INFO (SyncWorker_3) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:07:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:07:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:07:44 INFO (SyncWorker_11) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:07:50 INFO (SyncWorker_11) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:08:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:08:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:08:04 INFO (SyncWorker_13) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:08:10 INFO (SyncWorker_13) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:08:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:08:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:08:24 INFO (SyncWorker_16) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:08:30 INFO (SyncWorker_16) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:08:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:08:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:08:44 INFO (SyncWorker_10) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:08:51 INFO (SyncWorker_10) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:09:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:09:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:09:04 INFO (SyncWorker_12) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:09:10 INFO (SyncWorker_12) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:09:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:09:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:09:24 INFO (SyncWorker_18) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:09:30 INFO (SyncWorker_18) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:09:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:09:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:09:44 INFO (SyncWorker_5) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:09:50 INFO (SyncWorker_5) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:10:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:10:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:10:04 INFO (SyncWorker_2) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:10:10 INFO (SyncWorker_2) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:10:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:10:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:10:24 INFO (SyncWorker_11) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:10:31 INFO (SyncWorker_11) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:10:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:10:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:10:44 INFO (SyncWorker_8) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:10:51 INFO (SyncWorker_8) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:11:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:11:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:11:04 INFO (SyncWorker_16) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:11:10 INFO (SyncWorker_16) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:11:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:11:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:11:24 INFO (SyncWorker_11) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:11:31 INFO (SyncWorker_11) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:11:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:11:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:11:44 INFO (SyncWorker_19) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:11:50 INFO (SyncWorker_19) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:12:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:12:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:12:04 INFO (SyncWorker_7) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:12:11 INFO (SyncWorker_7) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:12:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:12:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:12:24 INFO (SyncWorker_14) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:12:30 INFO (SyncWorker_14) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:12:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:12:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:12:44 INFO (SyncWorker_9) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:12:50 INFO (SyncWorker_9) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:13:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:13:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:13:04 INFO (SyncWorker_4) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:13:10 INFO (SyncWorker_4) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:13:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:13:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:13:24 INFO (SyncWorker_5) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:13:30 INFO (SyncWorker_5) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:13:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:13:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:13:44 INFO (SyncWorker_3) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:13:50 INFO (SyncWorker_3) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:14:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:14:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:14:04 INFO (SyncWorker_4) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:14:10 INFO (SyncWorker_4) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:14:24 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:14:24 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:14:24 INFO (SyncWorker_6) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:14:30 INFO (SyncWorker_6) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:14:44 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:14:44 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:14:44 INFO (SyncWorker_2) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:14:50 INFO (SyncWorker_2) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
[33m20-03-03 16:15:04 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin![0m
[32m20-03-03 16:15:04 INFO (MainThread) [supervisor.audio] Start Audio plugin[0m
[32m20-03-03 16:15:04 INFO (SyncWorker_10) [supervisor.docker.interface] Clean hassio_audio application[0m
[32m20-03-03 16:15:10 INFO (SyncWorker_10) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 5 - 172.30.32.4[0m
Tue Mar  3 08:15:18 PST 2020
Stopping hassio service 12587 
[32m20-03-03 16:15:18 INFO (MainThread) [__main__] Stopping Supervisor[0m
[32m20-03-03 16:15:18 INFO (MainThread) [supervisor.hwmon] Stop Supervisor hardware monitor[0m
[32m20-03-03 16:15:18 INFO (MainThread) [supervisor.api] Stop API on 172.30.32.2[0m
[cont-finish.d] executing container finish scripts...
[32m20-03-03 16:15:18 INFO (MainThread) [supervisor.misc.forwarder] Stop DNS forwarding[0m
[32m20-03-03 16:15:18 INFO (MainThread) [supervisor.core] Supervisor is down[0m
[32m20-03-03 16:15:18 INFO (MainThread) [__main__] Close Supervisor[0m
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
``
Insert the package log here
```
Hassio_install.log:
Wed Feb 26 18:56:01 PST 2020
===> Step preinst. USER= GROUP= SHARE_PATH=
Wed Feb 26 18:56:01 PST 2020
===> Step postinst. USER= GROUP= SHARE_PATH=
Installing service configuration /var/packages/hassio/conf/hassio.sc
Invoke service_postinst
Wed Feb 26 19:00:38 PST 2020
===> Step preuninst. USER= GROUP= SHARE_PATH=
Removing service configuration hassio.sc
Invoke service_preuninst
Wed Feb 26 19:00:48 PST 2020
===> Step postuninst. USER= GROUP= SHARE_PATH=
Wed Feb 26 19:04:58 PST 2020
===> Step preinst. USER= GROUP= SHARE_PATH=
Wed Feb 26 19:04:59 PST 2020
===> Step postinst. USER= GROUP= SHARE_PATH=
Installing service configuration /var/packages/hassio/conf/hassio.sc
Invoke service_postinst
Wed Feb 26 20:31:21 PST 2020
===> Step preuninst. USER= GROUP= SHARE_PATH=
Removing service configuration hassio.sc
Invoke service_preuninst
Wed Feb 26 20:31:27 PST 2020
===> Step postuninst. USER= GROUP= SHARE_PATH=
Wed Feb 26 20:35:03 PST 2020
===> Step preinst. USER= GROUP= SHARE_PATH=
Wed Feb 26 20:35:04 PST 2020
===> Step postinst. USER= GROUP= SHARE_PATH=
Installing service configuration /var/packages/hassio/conf/hassio.sc
Invoke service_postinst


#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here

2020/03/03 06:56:04	stop hassio: begin to stop version 20191224-1
2020/03/03 06:56:04	stop hassio 20191224-1 Begin start-stop-status stop
2020/03/03 06:56:18	stop hassio 20191224-1 End start-stop-status stop ret=[1]
2020/03/03 06:56:18	stop hassio 20191224-1 Begin unload apparmor
2020/03/03 06:56:18	stop hassio 20191224-1 End unload apparmor ret=[0]
2020/03/03 06:56:18	stop hassio: stop version 20191224-1 failed, result 273
2020/03/03 08:02:57	start hassio: begin to start version 20191224-1
2020/03/03 08:02:57	start hassio 20191224-1 Begin pre-load apparmor
2020/03/03 08:02:57	start hassio 20191224-1 End pre-load apparmor ret=[0]
2020/03/03 08:02:57	start hassio 20191224-1 Begin start-stop-status start
2020/03/03 08:02:57	start hassio 20191224-1 End start-stop-status start ret=[0]
2020/03/03 08:02:57	start hassio: start version 20191224-1 successfully, result 0
2020/03/03 08:15:18	stop hassio: begin to stop version 20191224-1
2020/03/03 08:15:18	stop hassio 20191224-1 Begin start-stop-status stop
2020/03/03 08:15:28	stop hassio 20191224-1 End start-stop-status stop ret=[1]
2020/03/03 08:15:28	stop hassio 20191224-1 Begin unload apparmor
2020/03/03 08:15:28	stop hassio 20191224-1 End unload apparmor ret=[0]
2020/03/03 08:15:28	stop hassio: stop version 20191224-1 failed, result 273
``

**Comment by dosceroseis** [comment]
Hola, a mi me pasa lo mismo "hassio:audio" desde la actualizacion 106.4 no inicia. En el registro de HA el error que me da es el siguiente: WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin!

**Comment by jyz0501** [comment]
Me too。

**Comment by dosceroseis** [comment]
> Yo también.

Tienes que crear en grupo de usuarios, pero sin ningún usuario , una carpeta llamada "audio" , reinicia y listo

**Comment by fredrike** [comment]
The newer versions of the supervisor does not have this issue.

Here is a temporary fix for old versions: https://www.dropbox.com/s/9qb9wsi01t6s48t/hassio_x64-6.1_20200330-1.spk?dl=0
