### ISSUE TITLE
Update vim package

### ISSUE THREAD

**Issue by z0rc** [SynoCommunity/spksrc#3910]
Packaged vim version is quite old. Any chance to update it to latest version and promote the package from beta to main channel?

**Comment by hgy59** [comment]
really?

Please give any hint (what feature are you missing?).
This package is provided for old DSM (< 5.?) that have no vim installed by default.

**Comment by z0rc** [comment]
Okay I see now. I though that there is a way to upgrade DSM bundled vim, which is also old v7.4. As of features, lots of them, since there were couple of major vim releases since 2013.

**Comment by DigitalBox98** [comment]
If you really need the last version of vim, you can check my repo which is indicated on my profile.

**Comment by ymartin59** [comment]
@DigitalBox98 May you please submit a Pull Request with Vim update so that can be published
