### ISSUE TITLE
请问git密码是什么呀？？

### ISSUE THREAD

**Issue by lvjinqiao** [SynoCommunity/spksrc#3913]
您好，我是个小白，想要编译一个自己能用的spk，但是git的时候需要密码，请问密码是什么呀，或者从哪里可以下载您编译好的spk

**Comment by hgy59** [comment]
Sorry, but we cannot help, if you don't write in English.

**Comment by chickenandpork** [comment]
SynoCommunity的git没有密码。 用https：”git clone https://github.com/SynoCommunity/spksrc.git”, 以后看看那个spksrc/README.rst

**Comment by hgy59** [comment]
@chickenandpork everyting done in #3914

**Comment by chickenandpork** [comment]
Ok
