### ISSUE TITLE
Failed to build shairport-sync

### ISSUE THREAD

**Issue by lvjinqiao** [SynoCommunity/spksrc#3914]
make[2]: Nothing to be done for 'default'.
make[2]: Leaving directory '/spksrc/spksrc/cross/busybox'
make[2]: Entering directory '/spksrc/spksrc/cross/shairport-sync'
===>  Processing dependencies of shairport-sync
make[3]: Entering directory '/spksrc/spksrc/cross/libtool'
make[3]: Nothing to be done for 'default'.
make[3]: Leaving directory '/spksrc/spksrc/cross/libtool'
make[3]: Entering directory '/spksrc/spksrc/cross/libconfig'
make[3]: Nothing to be done for 'default'.
make[3]: Leaving directory '/spksrc/spksrc/cross/libconfig'
make[3]: Entering directory '/spksrc/spksrc/cross/popt'
===>  Downloading files for popt
wget http://rpm5.org/files/popt/popt-1.16.tar.gz
wget: unable to resolve host address ‘rpm5.org’
make[3]: *** [../../mk/spksrc.download.mk:57: download_target] Error 4
make[3]: Leaving directory '/spksrc/spksrc/cross/popt'
make[2]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[2]: Leaving directory '/spksrc/spksrc/cross/shairport-sync'
make[1]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[1]: Leaving directory '/spksrc/spksrc/spk/shairport-sync'
make: [../../mk/spksrc.spk.mk:463: arch-armada370] Error 2 (ignored)

**Comment by hgy59** [comment]
welcome @lvjinqiao 
a lot of contributors here are not native english speaking, so there might always be some communication issues, but let's try...

from your logs, I read that you want to build the shairport-sync package for armada370 architecture.

what I cannot see is, whether you are using the docker image or a debian environment for the build.

you have two options (see readme: Setup Development Environment)
1. (the prefered one) use the dockerimage
2. use a pysical or virtual debian linux and install all the required dependencies

Instructions to build shairport.sync for armada370 6.1 with the docker image:
Prerequisite is a linux system with docker installed.
```
# navigate into a working folder
cd ~
mkdir syno
cd syno

# clone the spksrc repository
git clone https://github.com/SynoCommunity/spksrc.git spksrc

# run the spksrc environment as a docker container
docker run -it -v $(pwd)/spksrc:/spksrc synocommunity/spksrc /bin/bash

# verify the volume mount
# output of pwd should be /spksrc
pwd
# ls -la sould list all files and folder of the root folders in the repository (files: Makefile, ...; folders: cross, spk, ...)
ls -la 

# within the running container: execute make setup to initialize some default values like TCVERSION=6.1
make setup

# change path to desired spk
cd spk/shairport-sync

# build for specific arch 
# or call make all-supported to build packages for all supported architectures
make arch-armada370

# if the build succeeds, the spk package is in
# /spksrc/packages                 # in the container
# $(HOME)/syno/spksrc/packages     # on the host computer
```

Some Remarks
- the first build takes longer time, since the source code and the toolchain packages must be downloaded (once)
- the shairport-sync package is outdated and build might fail
- you find a more current version of shairport-sync on [hgy59:fix_shairport](https://github.com/hgy59/spksrc/tree/fix_shairport) see PR #3866

**Comment by lvjinqiao** [comment]
> welcome @lvjinqiao
> a lot of contributors here are not native english speaking, so there might always be some communication issues, but let's try...
> 
> from your logs, I read that you want to build the shairport-sync package for armada370 architecture.
> 
> what I cannot see is, whether you are using the docker image or a debian environment for the build.
> 
> you have two options (see readme: Setup Development Environment)
> 
> 1. (the prefered one) use the dockerimage
> 2. use a pysical or virtual debian linux and install all the required dependencies
> 
> Instructions to build shairport.sync for armada370 6.1 with the docker image:
> Prerequisite is a linux system with docker installed.
> 
> ```
> # navigate into a working folder
> cd ~
> mkdir syno
> cd syno
> 
> # clone the spksrc repository
> git clone https://github.com/SynoCommunity/spksrc.git spksrc
> 
> # run the spksrc environment as a docker container
> docker run -it -v $(pwd)/spksrc:/spksrc synocommunity/spksrc /bin/bash
> 
> # verify the volume mount
> # output of pwd should be /spksrc
> pwd
> # ls -la sould list all files and folder of the root folders in the repository (files: Makefile, ...; folders: cross, spk, ...)
> ls -la 
> 
> # within the running container: execute make setup to initialize some default values like TCVERSION=6.1
> make setup
> 
> # change path to desired spk
> cd spk/shairport-sync
> 
> # build for specific arch 
> # or call make all-supported to build packages for all supported architectures
> make arch-armada370
> 
> # if the build succeeds, the spk package is in
> # /spksrc/packages                 # in the container
> # $(HOME)/syno/spksrc/packages     # on the host computer
> ```
> 
> Some Remarks
> 
> * the first build takes longer time, since the source code and the toolchain packages must be downloaded (once)
> * the shairport-sync package is outdated and build might fail
> * you find a more current version of shairport-sync on [hgy59:fix_shairport](https://github.com/hgy59/spksrc/tree/fix_shairport) see PR #3866

hello，I use the dockerimage,but my system is debian linux.you means i must use the dockerimage on syno to compile the spk??because i am in chinad so i think maybe i cannot wget some things.

**Comment by lvjinqiao** [comment]
> > welcome @lvjinqiao
> > a lot of contributors here are not native english speaking, so there might always be some communication issues, but let's try...
> > from your logs, I read that you want to build the shairport-sync package for armada370 architecture.
> > what I cannot see is, whether you are using the docker image or a debian environment for the build.
> > you have two options (see readme: Setup Development Environment)
> > 
> > 1. (the prefered one) use the dockerimage
> > 2. use a pysical or virtual debian linux and install all the required dependencies
> > 
> > Instructions to build shairport.sync for armada370 6.1 with the docker image:
> > Prerequisite is a linux system with docker installed.
> > ```
> > # navigate into a working folder
> > cd ~
> > mkdir syno
> > cd syno
> > 
> > # clone the spksrc repository
> > git clone https://github.com/SynoCommunity/spksrc.git spksrc
> > 
> > # run the spksrc environment as a docker container
> > docker run -it -v $(pwd)/spksrc:/spksrc synocommunity/spksrc /bin/bash
> > 
> > # verify the volume mount
> > # output of pwd should be /spksrc
> > pwd
> > # ls -la sould list all files and folder of the root folders in the repository (files: Makefile, ...; folders: cross, spk, ...)
> > ls -la 
> > 
> > # within the running container: execute make setup to initialize some default values like TCVERSION=6.1
> > make setup
> > 
> > # change path to desired spk
> > cd spk/shairport-sync
> > 
> > # build for specific arch 
> > # or call make all-supported to build packages for all supported architectures
> > make arch-armada370
> > 
> > # if the build succeeds, the spk package is in
> > # /spksrc/packages                 # in the container
> > # $(HOME)/syno/spksrc/packages     # on the host computer
> > ```
> > 
> > 
> > Some Remarks
> > 
> > * the first build takes longer time, since the source code and the toolchain packages must be downloaded (once)
> > * the shairport-sync package is outdated and build might fail
> > * you find a more current version of shairport-sync on [hgy59:fix_shairport](https://github.com/hgy59/spksrc/tree/fix_shairport) see PR #3866
> 
> hello，I use the dockerimage,but my system is debian linux.you means i must use the dockerimage on syno to compile the spk??because i am in chinad so i think maybe i cannot wget some things.

And this is my steps:
first, docker run -it -v ~/spksrc:/spksrc synocommunity/spksrc /bin/bash
second, cd /spksrc/spk/shairport-sync
next,make arch-armada370
and it will tell me this
root@570305cb0f6d:/spksrc/spksrc/spk/shairport-sync#  make arch-armada370
===>  Building package for arch armada370
make[1]: Entering directory '/spksrc/spksrc/spk/shairport-sync'
===>  Processing dependencies of shairport-sync
make[2]: Entering directory '/spksrc/spksrc/cross/busybox'
make[2]: Nothing to be done for 'default'.
make[2]: Leaving directory '/spksrc/spksrc/cross/busybox'
make[2]: Entering directory '/spksrc/spksrc/cross/shairport-sync'
===>  Processing dependencies of shairport-sync
make[3]: Entering directory '/spksrc/spksrc/cross/libtool'
make[3]: Nothing to be done for 'default'.
make[3]: Leaving directory '/spksrc/spksrc/cross/libtool'
make[3]: Entering directory '/spksrc/spksrc/cross/libconfig'
make[3]: Nothing to be done for 'default'.
make[3]: Leaving directory '/spksrc/spksrc/cross/libconfig'
make[3]: Entering directory '/spksrc/spksrc/cross/popt'
===>  Downloading files for popt
wget http://rpm5.org/files/popt/popt-1.16.tar.gz
wget: unable to resolve host address ‘rpm5.org’
make[3]: *** [../../mk/spksrc.download.mk:57: download_target] Error 4
make[3]: Leaving directory '/spksrc/spksrc/cross/popt'
make[2]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[2]: Leaving directory '/spksrc/spksrc/cross/shairport-sync'
make[1]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[1]: Leaving directory '/spksrc/spksrc/spk/shairport-sync'
make: [../../mk/spksrc.spk.mk:463: arch-armada370] Error 2 (ignored)
root@570305cb0f6d:/spksrc/spksrc/spk/shairport-sync# 

but when i download the tar ,and put it in the folder ,it not work.

**Comment by hgy59** [comment]
That is the same environment that I use

The dockerimage is officially supported on docker hub.
If you not already have, you can get it on the command line with:
`docker pull synocommunity/spksrc`

the command `docker image ls` must list synocommunity/spksrc:latest when the pull succeeded.

**please follow each step of my instructions above.**

Log entries like `make[2]: Nothing to be done for 'default'.` are hints, that you did not call `make setup`

I have no idea, whether the download of the cross modules source code is available in your country.
If the download of some cross modules works and for some others not, it might be that these are outdated (these are fixed on my branch I noted above).
If the download of cross-source-code does not work at all, you can try to download manually. Therefore you have to evaluate the download links in each cross module Makefile. If the manual download succeeds, you need to put the downloaded files into the folder spksrc/digests. The file name must be the same as listed in the digests file of the cross module.

And please do not quote the whole message, we have the history available here.

**Comment by hgy59** [comment]
If you do not run `make setup` in the /spksrc folder, you need to specify the TC-VERSION for the build like:
`make arch-armada370-6.1`

**Comment by lvjinqiao** [comment]
i run make setup,i think the problem is because "wget http://rpm5.org/files/popt/popt-1.16.tar.gz" in 
 my country cannot succeds,and the manual download succeeds, but i can't find the folder spksec/digests,so i made a folder with name digests,and it not work...do you understand me hhh

**Comment by lvjinqiao** [comment]
oh, i solve the problem, maybe the folder is not digests ,the folder name is distrib,and thank you very much ,do you know thank you very much ?? thank you very much

**Comment by hgy59** [comment]
yes the folder is distrib (I am out and have no access to my system at home).

currently http://rpm5.org/files/popt/ is not reachable for me too. So it is not a restriction for your location. May be you should try later (some hours, or even days) or we must find a mirror or other source for popt source code.

**Comment by hgy59** [comment]
this works for me:
ftp://anduin.linuxfromscratch.org/BLFS/popt/popt-1.16.tar.gz

**Comment by lvjinqiao** [comment]
YEAH!! I am already compile the spk succeeds. thank you very much! Our country has a super big network firewall. You can't use Google or watch YouTube here. It's terrible

**Comment by hgy59** [comment]
I gave this issue a more descriptive title ;-)

**Comment by hgy59** [comment]
you're welcome and I am happy too, that you succeeded.

**Comment by hgy59** [comment]
It is not the first time rpm5.org is not reachable:
https://github.com/osresearch/heads/issues/421

So it is better update PR #3866 to use ftp://anduin.linuxfromscratch.org/BLFS/popt/popt-1.16.tar.gz for cross/popt
