### ISSUE TITLE
ffmpeg 4.2.2

### ISSUE THREAD

**Issue by cnjack** [SynoCommunity/spksrc#3926]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ ffmpeg
_Package Version:_  4.2.2

### log

```
.....
error ogg/ogg.h not found
```

### solution

```
apt install ogglib-dev
```

**Comment by th0ma7** [comment]
i really don't get what your issue is.
you seems to be using a debian/ubuntu based distribution, not a synology nas.

**Comment by cnjack** [comment]
build with docker
