### ISSUE TITLE
uMurmur does not work anymore?

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#3929]
### Setup
_Package Name:_ umurmur
_Package Version:_ 

_NAS Model:_ any
_NAS Architecture:_  any
_DSM version:_ any (tested with DSM 5.2 and 6.2.2)

### Expected behavior
When clicking on the umurmur icon in DSM Main Menu: nothing happens

### Actual behavior
I suppose that the umurmur UI should appear

### Remarks
- no errors are displayed in log files (package log, installer log, /var/log/messages)
- wenn manually executing `umurmur.cgi` an error appears
```
./umurmur.cgi
Can't locate CGI.pm in @INC (you may need to install the CGI module) (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/local/lib/perl5/vendor_perl /usr/local/share/perl5/vendor_perl /usr/local/lib/perl5/core_perl /usr/local/share/perl5/core_perl .) at ./umurmur.cgi line 4.
BEGIN failed--compilation aborted at ./umurmur.cgi line 4.
```

I did not find any CGI.pm on the tested Diskstations.
internet search results tell me that CGI.pm is no longer bundled with Perl core.

@Diaoul  can you fix this umurmur.cgi.pl file?

**Comment by ymartin59** [comment]
My point of view is that should be easy to emit such a redirect with anything else... It may not be wise to require PHP to do so, but probably some more lines of Perl code would replace CGI usage.

**Comment by ymartin59** [comment]
For instance: https://stackoverflow.com/questions/19690370/how-to-redirect-a-page-in-perl-script

**Comment by hgy59** [comment]
I already did the redirect with a shell script. But I miss a UI for the configuration of uMurmur, and I didn't find any information whether such an UI exists and how to reach it.

**Comment by hgy59** [comment]
There is no configuration UI in uMurmur. The link on the uMurmur redirects to the associated app with `mumble://{server}/?version=1.2.4`

**Comment by spock99** [comment]
yes this would be good to see work again with DSM 7
