### ISSUE TITLE
[Package Request] RAR

### ISSUE THREAD

**Issue by Kick4U2** [SynoCommunity/spksrc#3935]
Name: RAR
Description: RAR is a powerful archive manager.
Website: https://www.rarlab.com/
Software documentation: https://github.com/alexisatkinson/nbdn/blob/master/build_tools/winrar/Rar.txt
Build/Installation documentation: https://www.win-rar.com/download.html?L=0
Source Code: Would need to obtain (https://www.win-rar.com/distpartners.html?&L=0)
License: $29 per computer

I tried copying the Linux variant of rar within '/usr/bin/' and it works via SSH, I do get this error though (still works for my use)
`rar: /lib/libstdc++.so.6: no version information available (required by rar)
`

I'm using rar to repair broken or missing '.rar' files using '.rev' files and am fine to only have access to this program via SSH, but think it would be really cool to have a 'Repair' feature within File Station for '.rar', '.rev', and '.par' file extensions.  The second feature your program could provide is a setting to store passwords and automatically try the list before asking the user to manually enter it.  Currently I see this dialog when a password is required:
`Enter password (will not be echoed) for ***********.rar:`

Also, all I can imagine that needs to be done for configuration is to allow the user to "upload" the license and move that to '/usr/bin/' along side the rar file.

**Comment by hgy59** [comment]
Since there is no open source code available, it is not possible to include such a package into spksrc.

**Comment by Kick4U2** [comment]
Hello and thank you for the response.  I think I explained this incorrectly as the request isn't to create a rar package, but more of a plugin to call the rar package.  Currently, Synology File Manager can extract files from a '.rar' file via '/usr/bin/unrar'.  I'm asking if it is possible to add an on the  context menu [Repair] within File Manager or an app similar.  This entry would call 'rar rc filename.ext' rather than the current 'unrar e filename.ext'.

If a plugin is not possible than please disregard my request.  Thank you again!

**Comment by BenjV** [comment]
The only one who could do this is Synology themselves so "ask them" would be my advice

The SynoCommunity is a bunch of private people who are only packing opensource software into a package that can be used on a Synology.

**Comment by ymartin59** [comment]
I let it open if there is anyone interested in implementing such an integration.

**Comment by hgy59** [comment]
Closing this, it seems that no one is interested...
