### ISSUE TITLE
Davfs2 not using secrets

### ISSUE THREAD

**Issue by TheAkki** [SynoCommunity/spksrc#3943]
### Setup
_Package Name:_  SynoCli Disk Tools
_Package Version:_ 1.0-1

_NAS Model:_ DS218+
_NAS Architecture:_ 
_DSM version:_ 6.2-23739

### Expected behavior
Davfs2 do not ask for credentials when it stored in secrets file.
I have tried locations
 - /etc/davfs2/secrets
 - /opt/etc/davfs2/secrets

Maybe i only use the wrong path. To avoid this the installer should create dummy files for config and secrets.

### Actual behavior
Davfs2 do not use secrets file and ask for credentials when mount wevdav.

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by TheAkki** [comment]
Stored in 

**/var/packages/synocli-disk/target/etc/davfs2/davfs2.conf**

 and **/var/packages/synocli-disk/target/etc/davfs2/secrets**

**Comment by ymartin59** [comment]
Notice these locations are not preserved at package upgrade.
You should put files hierarchy in /var/packages/synocli-disk/target/var/etc/ and refers to it with a symbolic link.
