### ISSUE TITLE
Radarr not starting after update to new mono

### ISSUE THREAD

**Issue by affer** [SynoCommunity/spksrc#3947]
DSM version DSM 6.2.2-24922 Update 6

updated Radarr to version 2020040909 and mono to version 5.20.1.34-13 

After this Radarr returns this error from the log, and refuses to start:
/volume2/@appstore/radarr/../mono/bin/mono: No such file or directory

Sonarr updated at same time and is working fine.

can u guys figure out ?

**Comment by ymartin59** [comment]
What is your Synology model / architecture?

**Comment by affer** [comment]
Sorry, it is RS1219+ 

:-D

**Comment by ymartin59** [comment]
It is good to know, even I think that package issue is not related to model architecture.

**Comment by ymartin59** [comment]
Do I guess right you have installed "mono" and "radarr" packages on different volumes?

**Comment by affer** [comment]
Yes apparently i have.

**Comment by ymartin59** [comment]
May you please test with this package: 
[radarr_x64-6.1_20200411-9.spk.zip](https://github.com/SynoCommunity/spksrc/files/4464634/radarr_x64-6.1_20200411-9.spk.zip)

**Comment by affer** [comment]
Perfect, that was the solution.

my system is a mess with all the different install locations :-D

thanks for your help.
