### ISSUE TITLE
Framework: CMake generic targets

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3955]
The same way Go compilation targets have been collected into re-usable Makefiles in `mk/`
It would be interesting to do same operation for CMake configure, compile and install targets.

Concerned components:
- cross/libwebsockets
- cross/intel-media-driver
- cross/intel-media-sdk
- cross/libmysqlclient
- cross/libaom
- cross/gmmlib
- cross/chromaprint
- cross/x265
- cross/umurmur
- cross/museek+

**Comment by ymartin59** [comment]
In progress: #3998

**Comment by th0ma7** [comment]
@ymartin59 is it possible to merge `ffmpeg` first as many packages will interfere with updates pending in PR #3965 .

**Comment by th0ma7** [comment]
@ymartin59 this is the second time it happens to me: git rebase ends-up included already merged patches from master as part of my PR.  Good news: conflict is solved.  Bad news: I have no clue on how to clean-up my branch besides creating a new PR and loosing comments from this one.

Any idea how to fix that?  and any suggested rebasing method to ensure I don't do this again?

**Comment by ymartin59** [comment]
@th0ma7 First you have to take care to keep your local "master" (and so "master" branch of your GitHub own fork) in sync with "upstream" master at SynoCommunity/spksrc. If you made a mistake when commiting to "master", immediately create feature branch with that commit and do a "reset --hard origin/master" (or upstream/master) to revert your local "master" back in sync.

For that specific PR, you should give a try to "rebase --interactive master" and you can use "drop" action to remove redundant (and probably empty) commits. Do not expect to succeed at first trial, so keep your original PR commits accessible thanks to a "backup branch" (or else you will have to learn how to use reflogs to retrieve previous commits hash)

In any case, there is an easy work-around to keep PR: you may push force an local branch with proper content (even if branch name is different) targeting "origin/cross-cmake" branch in your own fork. GitHub will be happy, but you will have to take care for a while that your local branch has a different name.

Hope this helps.
CC @hgy59

**Comment by ymartin59** [comment]
@th0ma7 Do you consider this issue is achieved now your PR has been merged?

**Comment by th0ma7** [comment]
Totally and been working quite well, closing.
