### ISSUE TITLE
Problems while building stockfish

### ISSUE THREAD

**Issue by mayweed** [SynoCommunity/spksrc#3957]
Hello all
I'm trying to compile stockfish for my ds216j (armv7). But i can't get past a problem with configure. I tried to unset GNU_CONFIGURE (to 0), i tried not to mention it. But whatever I tried it always went through the configure step stockfish does not have

I always end up with : 
```
env: ‘./configure’: No such file or directory
make[1]: *** [../../mk/spksrc.configure.mk:50: configure_target] Error 127
make[1]: Leaving directory '/spksrc/cross/stockfish'
```
Does anyone please could tell me how to get rid of the configure step (if possible here...)? I want to go directly to my compile rule (make ARCH=armv7)

Thx
Guillaume

_NAS Model:_ ds216j
_NAS Architecture:_ Armada 385 88F6820
_DSM version:_ 6.2.2-24922 Update 4

**Comment by publicarray** [comment]
> how to get rid of the configure step

Try `CONFIGURE_TARGET = nope`

**Comment by publicarray** [comment]
> To submit a new package like this one you simply pull a request on master at the given time

Yes, once submitted and reviewed it will be build & published.

instead of `cd $(PKG_WORK_DIR) && $(MAKE) build ARCH=armv7` did you try `$(RUN) $(MAKE)`? it includes the correct ARCH variable.

Also since this is a very standard way to build, the myCompile and myInstall targets may not be required. the default is `$(RUN) $(MAKE)` and `$(RUN) $(MAKE) install prefix=$(INSTALL_PREFIX)` 

We try to use the following convention: `stockfish_compile`, `stockfish_install`. myCompile & myInstall where left from older packages. 

Why not use official-Stockfish? https://github.com/official-stockfish/Stockfish

**Comment by mayweed** [comment]
Lo
Thx for your answer, yes i tried `$(RUN) $(MAKE)` and got the error : `make[2]: *** No targets specified and no makefile found.  Stop.` Then I tried with only  build and i got a no target found. That's when i cd in src and only with $(MAKE) or $(MAKE) build i got the result of make help that is:
```
make[2]: Entering directory '/spksrc/cross/fishnet/work-armada38x-6.1/Stockfish-fishnet-180120/src'

To compile stockfish, type: 

make target ARCH=arch [COMP=compiler] [COMPCXX=cxx]

Supported targets:

build                   > Standard build
profile-build           > PGO build
strip                   > Strip executable
install                 > Install executable
clean                   > Clean up

Supported archs:

x86-64-bmi2             > x86 64-bit with pext support (also enables SSE4)
x86-64-modern           > x86 64-bit with popcnt support (also enables SSE3)
x86-64                  > x86 64-bit generic
x86-32                  > x86 32-bit (also enables SSE)
x86-32-old              > x86 32-bit fall back for old hardware
ppc-64                  > PPC 64-bit
ppc-32                  > PPC 32-bit
armv7                   > ARMv7 32-bit
general-64              > unspecified 64-bit
general-32              > unspecified 32-bit
```
So to compile stockfish one must specifies the target **and** the arch that's what i infered...I tried with ARCH=$(ARCH) to no avail...(armada38x is not an arch for stockfish). I changed it a bit to take into account others arch (i test it with denverton). Here is the new makefile, i got a doubt for ppc (32 or 64?) and for others arms arch...If you got a clue to mirror more closely syno arch wrt stockfish target, will be more than welcome :)
```
PKG_NAME = fishnet
PKG_VERS = 180120
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/niklasf/Stockfish/archive/
PKG_DIR = Stockfish-$(PKG_NAME)-$(PKG_VERS)
PKG_WORK_DIR = $(WORK_DIR)/$(PKG_DIR)/src/

HOMEPAGE = https://github.com/niklasf/Stockfish/tree/fishnet
COMMENT  = Stockfish engine for lichess which supports variants and can be used with fishnet (http://lichess.org/get-fishnet)
LICENSE  = GPLv2/GPLv3

CONFIGURE_TARGET = nope
COMPILE_TARGET = stockfish_compile
INSTALL_TARGET = stockfish_install

include ../../mk/spksrc.cross-cc.mk

.PHONY: stockfish_compile
stockfish_compile:
ifeq ($(findstring $(ARCH),$(ARM7_ARCHES)),$(ARCH))
	cd $(PKG_WORK_DIR) && $(MAKE) build ARCH=armv7
endif

ifeq ($(findstring $(ARCH),$(x86_ARCHES)),$(ARCH))
	cd $(PKG_WORK_DIR) && $(MAKE) build ARCH=general-32
endif

ifeq ($(findstring $(ARCH),$(x64_ARCHES)),$(ARCH))
	cd $(PKG_WORK_DIR) && $(MAKE) build ARCH=general-64
endif

ifeq ($(findstring $(ARCH),$(PPC_ARCHES)),$(ARCH))
	cd $(PKG_WORK_DIR) && $(MAKE) build ARCH=ppc-32
endif

.PHONY: stockfish_install
stockfish_install:
	cd $(PKG_WORK_DIR) && $(MAKE) install
```
And your last question why not use the official one? Because it's the one lichess uses and I want to use it with fishnet (lichess.org/get-fishnet for details) which allows users to contribute with cpu cycles to Lichess by analyzing games. Moreover this one got variants (Crazyhouse, Horde etc...) while vanilla sf is just for standard chess.

Many thx for your help

**Comment by mayweed** [comment]
So i finally build it, install it and bim does not work...Exec file format error!
I built it with make arch-armada38x-6.1, in config i clearly see
```
make[3]: Entering directory '/spksrc/spk/stockfish-fishnet/work-armada38x-6.1/Stockfish-fishnet-180120/src'
Config:
debug: 'no'
sanitize: 'no'
optimize: 'yes'
arch: 'armv7'
bits: '32'
kernel: 'Linux'
os: 'GNU/Linux'
prefetch: 'yes'
popcnt: 'no'
sse: 'no'
pext: 'no'
```
But in the end, when i check my binary i got:
```
root@d639aa638d9f:/spksrc/cross/stockfish-fishnet# file /usr/local/bin/stockfish 
/usr/local/bin/stockfish: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=595aa54e45636a414624f04fbcca2762b32de9ce, stripped
```
I don't get why it announces in config 32bits and gives me a 64bits binary. Does anyone got an hint on what i missed?
Thx

**Comment by publicarray** [comment]
The custom make file uses different variables to get the compiler. Give this a go: https://github.com/publicarray/spksrc/commit/9714c8a17b19b45ba88eb3103e22686eab36b961

**Comment by mayweed** [comment]
Lo Sebastian
Many thanks for you help!! In the end i chose to package the official stockfish and the stockfish fishnet one. 

See [stockfishes](https://github.com/mayweed/spksrc/commit/a569eb703c6db0333e15083ce12d910ef2420921) . On my laptop it always build for 64bits because, i suppose, my laptop is 64b so i can't even use all that work on my own syno which is 32b. No luck.

Hope it will be useful for some :)

**Comment by publicarray** [comment]
Nice 👍

When you build you can select the arch like so ‘make arch-x64-6.1’ make sure you’re in the spk/stockfish directory

Thank you for your work on this.

**Comment by mayweed** [comment]
Mine is a 32bits Arm... And it compiles with armada in 64b 😢😢

**Comment by publicarray** [comment]
Huh that’s not how that’s supposed to work. I’m going to try to find out what’s going on.

**Comment by publicarray** [comment]
So I've build with `/spksrc/spk/fishnet# make arch-x64-6.1`, `make arch-ipq806x-1.2` and `make arch-armada38x-6.1` and I get the expected binary after extracting the `fishnet.spk` and `package.tgz`:

```sh
$ pwd
/spksrc/packages/fishnet_x64-6.1_180120-/package/bin
 
$ file stockfish
stockfish: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped

$ file stockfish 
stockfish: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, stripped

$ file stockfish
stockfish: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, stripped
```

See: https://github.com/publicarray/spksrc/releases/tag/fishnet-180120

**Comment by publicarray** [comment]
When changing the Makefile a clean rebuild is often required.

**Comment by mayweed** [comment]
Lo
So, first my setup is the docker one. Each time i use the command line given in the readme (docker it etc...). I cleaned everything and rebuild the package stockfish-fishnet from spk/ with the makefiles given in the PR I made yesterday. And i got the infamous 'exec file format' . After that i removed the package and test with yours and it works. I will erase my current setup and start fresh to see if it changed something...But it's definitely weird...

**Comment by publicarray** [comment]
It looks to me that you added an underline here. should be `COMPCXX`

```sh
cd $(PKG_WORK_DIR) && $(ENV) $(MAKE) build ARCH=$(BUILD_ARCH) COMP_CXX=$(CXX)
```

https://github.com/publicarray/spksrc/commit/9714c8a17b19b45ba88eb3103e22686eab36b961#diff-4763ecd8105724c875e2c343e2a38224R41

https://github.com/SynoCommunity/spksrc/pull/3964/files#diff-845081a4d02460fbb97f724db638e4b1R41

**Comment by mayweed** [comment]
Argh #!#$# you're damn right!! Haven't seen this one, i just correct it in my latest commit. Thx a lot!!
