### ISSUE TITLE
Framework: provide DSM toolkit SDK usage

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#3958]
Introduced by #3873 to take benefits of evansport specific optimisation through intel libraries, cross/ds.evansport is not at the right place.

Moreover these toolkit are heavy to download. It would be relevant to split its original content as Conan packages to only retrieve required files (headers, object files...)

**Comment by hgy59** [comment]
This issue is outdated and `cross/ds.evansport` does not exist anymore.
The ffmpeg* videodrivers for intel are extracted to synocli-videodriver package.
