### ISSUE TITLE
[Update request] Update jackett to standalone version

### ISSUE THREAD

**Issue by Danimal4326** [SynoCommunity/spksrc#3960]
Jackett now has a standalone version which removed the dependency on Mono.  Please update the jackett package to this new version.  The standalone version is claimed to have increased performance and stability.

**Comment by Numble01** [comment]
Please, please, please update jackett!

**Comment by hgy59** [comment]
"standalone" can be missinterpreted. For ARMv6 and for ppc you still need mono >= 5.8. for ARMv7, ARM64 and X86_64 you need a .netcore toolchain. With dotnet core you can build a self container executable that one can intepret as `standalone`. There is still a dependeny of .net core.

Closing this ad duplicate of #3697 and #3715
