### ISSUE TITLE
[TV Headend] SSL peer verification failed - X509 20

### ISSUE THREAD

**Issue by kekukui** [SynoCommunity/spksrc#3963]
**Package Name:** TVheadend
**Package Version:** 4.3.20191128~221c29b-20

**NAS Model:** DS111
**NAS Architecture:** ARMv5
**DSM version:** 6.2.2-24922 Update 4

**Steps to reproduce**
Install IPTV automatic network / local M3U file
Play IPTV channels from Muxes menu

**Package log**
**`Starting tvheadend command /volume1/@appstore/tvheadend/bin/tvheadend -f -u sc-tvheadend -g tvheadend --http_port 9981 --htsp_port 9982 -c /volume1/@appstore/tvheadend/var -p /volume1/@appstore/tvheadend/var/tvheadend.pid`**

**Summary**

Can only play HTTP streams.  All HTTPS encrypted connections fail with error:
**`SSL peer verification failed - X509 20`**

Using OpenSSL version 1.0.2r-fips (26 Feb 2019)

X509 Error 20 - Issuer certificate could not be found
https://help.fortinet.com/fweb/551/log/Content/FortiWeb/fortiweb-log/SSL_TLS_error_messages.htm

**Comment by ymartin59** [comment]
@th0ma7 @hgy59 DSM certificates store is at a custom location, I remember it has been explicitly replaced in Mono built. I guess there is such a requirement to implement for TVheadend too.

**Comment by th0ma7** [comment]
@ymartin59 I had a quick look at `mono` package and besides `service-setup.sh` script I didn't find much related to certificates.

Searching for this specific issue with `tvheadend` led me to this bug entry so trail points towards a potentially existing software bug:
* https://tvheadend.org/issues/3388

On the other hand, could this be related to the configuration of the underlying `cross/openssl` ?  There is a resulting `/var/packages/tvheadend/target/openssl.cnf` file provided within the `tvheadend` package coming from openssl `PLIST` such as `rsc:openssl.cnf`.  There may be an option in there to circumvent the issue?

**Comment by th0ma7** [comment]
@kekukui is this still an issue?  There are updated version of DSM that incluse certificate updates + newer version of TVH now available.

**Comment by Stanzilla** [comment]
Yeah that's the same mono cert issue that sonarr etc has as well

**Comment by th0ma7** [comment]
@Stanzilla can you provide me with details on how I can reproduce this?  My setup at home is using kodi + tvheadend but I'd need to reproduce your issue to find a proper fix.

**Comment by Stanzilla** [comment]
For me it was a combination of mono 5.20.1.34-18 and DSM 7.1 that broke it, 

there are several issues and PRs about it:
- https://github.com/SynoCommunity/spksrc/pull/5070
- https://github.com/SynoCommunity/spksrc/issues/5130
- https://github.com/SynoCommunity/spksrc/issues/5051

downgrading mono fixed it for me.

**Comment by mreid-tt** [comment]
Hey @kekukui, @Stanzilla, with a newer package for Mono Version 5.20.1.34-19 published to the repository can we validate if this issue is still happening? The current version also resolved #5051 and superseded #5051. Looking forward to your feedback.

**Comment by Stanzilla** [comment]
> Hey @kekukui, @Stanzilla, with a newer package for Mono Version 5.20.1.34-19 published to the repository can we validate if this issue is still happening? The current version also resolved #5051 and superseded #5051. Looking forward to your feedback.

I currently have an edited version mine installed that is also version 19, to test your version 19 I would have to edit it to 20. Is that okay or would that prevent some upgrade code from working?

**Comment by mreid-tt** [comment]
> I currently have an edited version mine installed that is also version 19, to test your version 19 I would have to edit it to 20. Is that okay or would that prevent some upgrade code from working?

If you are comfortable with SSH, you can try this method from our FAQ -- [Downgrade a package without uninstalling (Advanced)](https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#downgrade-a-package-without-uninstalling-advanced).

**Comment by Stanzilla** [comment]
> > I currently have an edited version mine installed that is also version 19, to test your version 19 I would have to edit it to 20. Is that okay or would that prevent some upgrade code from working?
> 
> If you are comfortable with SSH, you can try this method from our FAQ -- [Downgrade a package without uninstalling (Advanced)](https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#downgrade-a-package-without-uninstalling-advanced).

Looks to be working so far!

**Comment by mreid-tt** [comment]
> Looks to be working so far!

Great! Hopefully we can get similar feedback from @kekukui soon and then this issue can be closed.

**Comment by th0ma7** [comment]
Issue seems fixed and no input provided by user, closing.
