### ISSUE TITLE
Unable to execute Octoprint - Synology 216+

### ISSUE THREAD

**Issue by Cuerdas** [SynoCommunity/spksrc#3966]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_  20160321 - 4 
_Package Version:_ 20160321 - 4 

_NAS Model:_  216+
_NAS Architecture:_ DSM 6.2.2-24922 Update 4
_DSM version:_ DSM 6.2.2-24922 Update 4

### Expected behavior
Tell us what should happen

Start Octoprint

### Actual behavior
Tell us what happens instead

Can't Execute package

### Steps to reproduce
_1._ Install
_2._ Execute
_3._ Cant Execute

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
Octoprint has not been ported to DSM 6 yet. So package only runs properly on DSM 5.

**Comment by Cuerdas** [comment]
> Octoprint has not been ported to DSM 6 yet. So package only runs properly on DSM 5.

Oh! Ty forma the info! Any plans forma DSM6??
