### ISSUE TITLE
TVheadend on Synology tvgrabber tab does not appear

### ISSUE THREAD

**Issue by johnm0101** [SynoCommunity/spksrc#3970]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ tvheadend 
_Package Version:_ 4.3~221c29b

_NAS Model:_ DS718+
_NAS Architecture:_ 
_DSM version:_ 622.249

### Expected behavior
I installed tv headend on my syn 718+  (I have tried twice before but defeated by complexity and limited linux knowledge. However this time I successfully scanned muxes and mapped services - Great!  but no epg for the satellite services (OTA works) I have another linux box running tvheadend 4.2.8-36~g5bdcfd8ac (an earlier version) On this I am able to list and configure tv grabbers 
I have read other threads about putting the tv_grab files in hte volume1/@appstore/tvheadend/bi folder and changing permissions. Have tried this with files copied from the linux installation which shows the 'epg grabber modules' tab on the 'channels/epg'  'configuration' tabs. no luck

#### Package log
[tvheadend.log](https://github.com/SynoCommunity/spksrc/files/4515494/tvheadend.log)
[tvheadend_install.log](https://github.com/SynoCommunity/spksrc/files/4515495/tvheadend_install.log)

_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by th0ma7** [comment]
Try setting the interface mode to expert and the tab should then appear.

**Comment by johnm0101** [comment]
many thanks - sorted (up to a point)   If I can prevail on your kind help a little further. Where are the egggrab files located on synology   - on my ubuntu rig the are in /usr/bin 
I have tried putting one grabber I am insterested in  tv_grab_uk_bleb    into the /volume1/@appstore/tvheadend/bin  directory but it does not appear on the grabbers tab in browser.
Also although I moved that file tv_grab_uk_bleb - I cannot run it from command line - on the ubuntu machine one runs it first time to create a conf file then it grabs the xml listings - doesnt work on Synology - says 'command not found'  (Perl .244 is installed

**Comment by th0ma7** [comment]
On my wiki I sort of documented that here:
* https://github.com/th0ma7/synology/wiki

More precisely here:
* https://github.com/th0ma7/synology/wiki/TVHeadend:-5)-Guide-t%C3%A9l%C3%A9

Basically you have to 
1. setup a basic "perl" environment within the `sc-tvheadend` account.
2. From there you can drop your perl epg grabber in `/var/packages/tvheadend/target/bin`
3. You will require a shell script to start the perl program so it knows your perl environment.
4. Then you restart `tvheadend` so it capture the new epg grabber:
```
$ sudo synoservice --restart pkgctl-tvheadend
```
But more details are available in my wiki page which should allow you to do some mileage.  Note that default perl provided by Synology dates quite a bit so not all epg's will work and Perl `cpan` dependencies may not all install properly.  It's the reason I had started working at providing a newer version of perl but I never completed that work:
* https://github.com/th0ma7/spksrc/tree/perl-5.30

**Comment by johnm0101** [comment]
Hi I'm completely stuck - read your wiki which suggests how to download the tv_grab_file but the directories/folders do not match my set up on my DS718+ I have tried adapting but nothing seems to happen  tvheadend on my synology is installed in \volume1\@appstore\tvheadend
the suggested path in your wiki /var/packages/tvheadend/target/bin/tv_grab_file
does not exist - I presume one changes the var/packages/ to volume1/@appstore  ? but then again the installation does not contain a 'target' subfolder

I tried downloading the tv_grab_file to  volume1/@appstoer/tvheadend/bin  but the grabber rdoes not appear in the  'epg grabber modules' tab. Indeed that shows a number of OTA grabbers but none appear to work. onthe Channels tab where one is supposed to be able to assign a grabber to a channel, there are no grabber options.

I can download an xmllistings.xml file, I am able to put on a cron job - Simple question how do I get TVheadend(in this synology icarnation) to read teh tvlist.xml file and where should this be saved to 

I really appreciate your help   but as you can see although I am competent in some areas some others are a mystery to me

**Comment by th0ma7** [comment]
Long overdue follow-up here:  Since then I've added additional tv_grabbers that are already part of the default package that may solve your issue.  By default there are now:
- tv_grab_zap2epg to grab directly from zap2it.com
- tv_grab_file to read a default ~/.xmltv/tv_grab_file.xmltv file
- 2x tv_grab_url to read from a URL

**Comment by th0ma7** [comment]
Note that in the latest version there where additional tv grabber added imported from the official docker version.  Hopefully you now have all you need to get things through.

In the meantime, please open-up a new issue if this problem still exists, closing this one due to lack of activity.
