### ISSUE TITLE
Allow volume path with mixed case (Volume1 for example)

### ISSUE THREAD

**Issue by odingalt** [SynoCommunity/spksrc#3974]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_  NZBGet from Diaoul that uses this source
_Package Version:_  16.4-22

_NAS Model:_ 
_NAS Architecture:_ 
_DSM version:_ 

### Expected behavior
My synology got a volume name of /Volume1/ which disallows all packages using this packager.  Synology does not allow volume name changes without destructing the underlying functionality of the whole NAS.  Feature request to allow mixed case volume names.

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
Can anyone else confirm that it is possible to have volumes with uppercate 'V'?
This is relativly easy to fix. It is just a validation in the wizard files.
I assume only the first letter might be uppercase?

**Comment by odingalt** [comment]
I would withdraw this perhaps.  I recently found my NAS is configured as such and certainly due to confusion on my part:

/volume1/Volume1/Downloads

**Comment by hgy59** [comment]
@odingalt minio is the first published package with this fix. May be you want to try it before the package server is offline for about one week.

**Comment by odingalt** [comment]
My mistake folks.  I can't confirm that uppercase is allowed.  I managed to confuse myself as my NAS for a long time has had volume1 with all items in folder Volume1.
