### ISSUE TITLE
FFMPEG update not available on synocommunity channels

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#3976]
### Setup
_Package Name:_ ffmpeg
_Package Version:_ 4.2.2-28

_NAS Model:_ DS-918+
_NAS Architecture:_ apollolake
_DSM version:_ 6.2.3

### Expected behavior
Expecting to see update being available though the channel list.

### Actual behavior
Only older version 4.2.1-23 shown as available.

### Notes
Currently running in-progress "ffmpe-next" version (4.2.2-29) retaled to PR #3965.  Normally the package show at the very least show the latest version available online 4.2.2-28.  Currently it only shows the older version 4.2.1-23.

![ffmpeg-old-version-available](https://user-images.githubusercontent.com/17141866/80320247-5ca71080-87e3-11ea-8c0d-9c12fbc7e2ff.png)

**Comment by th0ma7** [comment]
After double-checking packages available I noticed that quite a few are actually missing online:
```
  arch            4.2.1-23  4.2.2.28
6.1 qoriq            X          X
6.1 evansport        X          X
6.1 apollolake       X          -
6.1 avoton           X          -
6.1 braswell         X          -
6.1 broadwell        X          -
6.1 broadwellnk      X          -
6.1 bromolow         X          -
6.1 cedarview        X          -
6.1 denverton        X          -
6.1 dockerx64        X          -
6.1 grantley         X          -
6.1 kvmx64           X          -
6.1 x86              X          -
6.1 x86_64           X          -
6.1 88f628x          X          X
6.1 armada370        X          X
6.1 armada375        X          X
6.1 armada38x        X          X
6.1 alpine           X          X
6.1 alpine4k         X          X
6.1 armadaxp         X          X
6.1 comcerto2k       X          X
6.1 monaco           X          X
6.1 rtd1296          X          X
6.1 armada37xx       X          X
6.1 aarch64          X          X
6.1 hi3535           X          X
1.2 northstarplus    X          -
1.2 ipq806x          X          -
1.2 dakota           X          -
```

**Comment by ymartin59** [comment]
A failure at publish after addition in `x64` architectures of new arch `purley`  which was not known yet in `spkrepo` database... Sorry for that mistake and delay.

**Comment by th0ma7** [comment]
Thnx @ymartin59 !
