### ISSUE TITLE
IGMPv3 issue

### ISSUE THREAD

**Issue by sedland** [SynoCommunity/spksrc#3977]
### Setup
_Package Name: Tvheadend 
_Package Version: v4.3.20191128~221c29b-20

_NAS Model: synology_apollolake_620slim
_NAS Architecture:x86_64 
_DSM version: 6.2.2 upd4

### Expected behavior
_Tell us what should happen_

I had configured TVheadend just for IPTV, Providor in my case is Dt. Telekom.
Since 1.1.2020 the service will be provided via IGMPv3. TVheadend 4.3 can handle these 
protocol (My old QNAP  has no issues TVH 4.3.1792). Limited by DSL bandwith, 5 HD chanels are easily served with Clients and PVR. 

### Actual behavior
Tell us what happens instead
TVH 4.3.99 - Synology can handle just one HD channel or 3 SD channels.
When I opened the 2nd HD chanel - bandwith monitoring in  
Status Stream decreasis from ca 8000kb/s to 2500 kb/s and the numers of uncorrected packts increases dramatically.
TVH log show error in handling of channels.
The pictures on all the TV's freez.

### Steps to reproduce
_1._ Configure IPTV providor with IGMPv3 like Magenta TV (Telekom)
_2._ open 2 HD cahnnles
_3._ see logs

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

Adding 'sc-tvheadend' to 'sc-media'
Group Name: [sc-media]
Group Type: [AUTH_LOCAL]
Group ID:   [65536]
Group Members:
0:[sc-tvheadend]
Invoke service_postinst
Fixing fontconfig links

Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by th0ma7** [comment]
This is not an easy one.
I strongly presume this is a regression with tvheadend.
Have you opened up a bug entry on tvheadend bug tracking web site?
* https://tvheadend.org/issues/4229
Also, are you calling `ffmpeg` with rtp when profiling your IPTV setup?

**Comment by th0ma7** [comment]
Also, maybie unrelated, but can you give it a shot a upgrading ffmpeg using:
* https://github.com/th0ma7/synology/tree/master/packages

**Comment by sedland** [comment]
Hello th0ma7
solved, I had the new ffmpeg since one week in use.
No issues @all. Many Thanks

**Comment by th0ma7** [comment]
Thnx for reporting back on this, cheers!
