### ISSUE TITLE
libusb compile issues (udev support requested) after version upgrade

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#3980]
Hi all,

Currently the version used for libusb within spksrc is version 1.0.9 (Apr 20, 2012).
I think 2 years ago i upgraded to version 1.0.22 without issues but recently i needed to rebuild my virtual environment used for compiling.

Since then i'm constantly getting the following error when compiling any recent libusb release (1.0.18+)

I double checked all my configurations and backups made from repo before rebuilding VM.
Also installed libudev-dev on my Ubuntu VM since i thought that was missing but that didn't fixed it. Now it's breaking my head why it constantly fails with:

checking libudev.h usability... no
checking libudev.h presence... no
checking for libudev.h... no
configure: error: "udev support requested but libudev not installed"
make[1]: *** [../../mk/spksrc.configure.mk:50: configure_target] Error 1
make[1]: Leaving directory '/home/ubuntu/github/spksrc/cross/libusb'
make: [../../mk/spksrc.cross-cc.mk:110: arch-alpine-6.1] Error 2 (ignored)

It must be something simple but i'm checking things for a few hours now but can't find it so trying my luck here.
If this is not the appropriate place for this then you may close this but what i'm actually asking for is a upgraded version of libusb.

**Comment by hgy59** [comment]
@schumi2004 do you still have this issue?

I fixed this by definition of `--disable-udev` as parameter for autoconf __AND__ configure.
With this I successfully buit libusb version 1.0.23.

For libusb udev is enabled by default now, but I suppose it is not supported on DSM. And I dit not find a dedicated libudev source package (what I found is, that libudev is part of systemd source code).

**Comment by hgy59** [comment]
`cross/libusb` version 1.0.23 still builds successfully.
