### ISSUE TITLE
PSA: Server Migration

### ISSUE THREAD

**Issue by publicarray** [SynoCommunity/spksrc#3981]
### When?

~~Starting **30th of April** and we plan to have the migration completed within **7 days⌛️**~~
Migration is **ongoing**, current ETA is **May 24th**⌛️

### Why?

The server has been running on an old OVH instance type and OVH is deprecating the instance we where using. @Diaoul, @ymartin59 and many more @SynoCommunity/developers and [contributors](https://github.com/SynoCommunity/spksrc/graphs/contributors) are running the project in their spare time, so we naturally left it to the last minute 😅, please be patient as we migrate the site.

Huge thanks go to @Diaoul and @ymartin59 for keeping it updated and running for so long. (And restarting when it when it became overloaded 🔥)

## Current Status (2020-05-28 00:17 UTC)
- [x] Backup
  - [x] SPKs
  - [x] Database
  - [x] Configuration
- [x] Repository code refresh: [spkrepo](https://github.com/SynoCommunity/spkrepo)
  - [x] Update all dependencies and fix failing code
  - [x] Use [poetry](https://github.com/python-poetry/poetry) for packaging
  - [x] Make the test suite pass
  - [x] Use [pytest](https://docs.pytest.org/en/latest/) as test runner
  - [ ] Make [PyPI](https://pypi.org/) repository
  - [x] Use [pre-commit](https://pre-commit.com/) hooks for linting
    - [x] [black](https://github.com/psf/black)
    - [x] [flake8](https://flake8.pycqa.org/en/latest/)
    - [x] [isort](https://github.com/timothycrosley/isort)
    - [x] My own [poetry export](https://github.com/Diaoul/pre-commit-hooks-poetry)
  - [x] Create GitHub Actions CI
    - [x] Run linting
    - [x] Run tests
    - [ ] Build artifacts
    - [ ] Release on [PyPI](https://pypi.org/)
   - [x] Create Docker image
   - [x] Use Docker Hub as a CI step
- [x] Buy a new server
- [x] Configure the new server
- [x] Create a complete Docker stack based on configuration backup
- [ ] Publish the Docker compose file
- [x] Restore Database and SPKs
- [x] Deploy the stack on the server
- [x] Test everything is OK
- [x] Route traffic to the new server
  - [x] Packages
  - [x] Website
  - [x] API
- [x] Monitor server performance

**Comment by MrSparklle** [comment]
Does migration finished? I still have issues to download packages from Synocommunity.

**Comment by publicarray** [comment]
Not yet but @Diaoul in on the job. If all goes well, by the end of the weekend we’ll be up and running. But don’t hold me to it. The site is returning stale items from Fastly CDN so some popular devices/packages might still work.

**Comment by thehoff** [comment]
long term if you want/need another admin to help support this project let me know. happy to share my details in private.

**Comment by raymondtrueman** [comment]
Any updates regarding the migration? @Diaoul

**Comment by Diaoul** [comment]
I've updated the issue with current status and will try to keep that updated. I think I can finish the docker stack tonight and initiate SPK transfer to the server this evening.

I can only work on this during the evenings (11PM-4AM) so please be patient :hourglass_flowing_sand:

**Comment by Diaoul** [comment]
Just updated the status. Tests ongoing. Looking good so far.

**Comment by matrixn** [comment]
I am still unable to access the package repo .. not sure how @Diaoul was able to test and report a success :)) 
I've even tried different dsn's like google ones and 1.1.1.1 so far no luck to get them working on Virgin Broadband in London....

**Comment by hgy59** [comment]
@matrixn please read the provided status in the "Current Status List". The traffic is not yet routed to the new server.

**Comment by DcMcIx** [comment]
Hello, Thanks for the great job you're doing to make our NAS's more user friendly 
In the mean time I was able to compile (with your framework) the synocli-monitor and it just worked.
sure the package center is more simple to use, can't wait to add it again in my Addon center :)

**Comment by Stanley008** [comment]
When will be the server online again? Thx

**Comment by ljstronge** [comment]
Looking forward to this being back on. I was going to set up my full media stack today (Sabnzb etc) but noticed this was offline.

Keep up the good work and let us know if there is anything we can help with!

**Comment by Diaoul** [comment]
Packages are now available but the website is still down.

**Comment by ljstronge** [comment]
Thanks. I can add the Package Source but get failed to download on any app. Appreciate your work.

**Comment by psergiu** [comment]
Same here ... package source can be added, list of packages visible in Package Center but installs fail with: Failed to download "packagename".

/var/log/messages:
```
2020-05-26T17:38:07-05:00 NAS-DS1019 synoscgi_SYNO.Core.Package.Installation_1_install[16402]: pkgserver.cpp:698 Failed to curl perfor
m, code=3, err=Error, url=/tcl/4/tcl.v4.f4458%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx6
4-grantley-kvmx64-x86-x86_64%5D.spk?arch=apollolake&build=24922, mode=install
```

**Comment by Diaoul** [comment]
I've investigated this for hours now and I can't find a reason why we can download manually but not with the package center. Maybe it's just a DNS caching issue. I will continue tomorrow.

**Comment by szyb** [comment]
Hi @Diaoul ,
I look into the json response from the server and it looks like "link" node does not have full URL with protocol and server name.
i.e. for sslh package (DS718+, build 25423) there is:
`"Link": "/sslh/3/sslh.v3.f4458%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-grantley-kvmx64-x86-x86_64%5D.spk?arch=apollolake&build=25423",`

while for the same package (but for DS413) there was before (I get it from my website cache):
`"Link": "https://packages.synocommunity.com/sslh/3/sslh.v3.f4458%5Bqoriq%5D.spk?arch=qoriq&build=25423",`

Hope that help

**Comment by publicarray** [comment]
@Diaoul Thanks @szyb I think you found the crux of the issue.

Shame that Synology doesn't support relative links.

**Comment by Diaoul** [comment]
Thanks, I didn't touch that part so I don't know why this is now relative
links...
Will try to fix this.

Le mer. 27 mai 2020 à 09:44, Sebastian Schmidt <notifications@github.com> a
écrit :

**Comment by Vf58** [comment]
@Psergiu,

Thank you for the info. I download manualy  Transmission packages : with : 
https://packages.synocommunity.com//transmission/16/transmission.v16.f4458%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-grantley-kvmx64-x86-x86_64%5D.spk?arch=avoton&build=24922

@Diaoul,

Thank you for your job and good luck,

Philippe

**Comment by ljstronge** [comment]
How can I download packages manually (Nzbget & CouchPotato) in the interim? Thanks

**Comment by szyb** [comment]
@ljstronge until the fix is ready you may use [https://search.synopackage.com](https://search.synopackage.com), but first setup your model & version, find the package in the synocommunity source and click download icon. Just added and deployed such possibility as many people asking for that.

**Comment by prometheus247** [comment]
It is not possible to change a manual downloaded package back to a repository source, without re-installing, right?
But from settings migration perspective, it could be an easy copy & paste of the @appstore folder - nor?

**Comment by Safihre** [comment]
Just give @Diaoul a day or 2 more guys 🏎🏁

**Comment by ljstronge** [comment]
> Just give @Diaoul a day or 2 more days, guys 🏎🏁

Yep. Absolutely. Apologies for being inpatient!

**Comment by Diaoul** [comment]
I [addressed the issue](https://github.com/SynoCommunity/spkrepo/commit/cda0b056089d1c81f704594eb88ff3745e5126be) regarding relative links being sent instead of absolute ones.
Packages services should be completely restored, still working on the website and API.

**Comment by Diaoul** [comment]
Website is alive, API should be too. I've updated the status.

**Comment by publicarray** [comment]
Fastly now redirects all requests to HTTPS 🎊
@Diaoul What happened to the Fastly logo and sponsor message?

**Comment by Diaoul** [comment]
It was not part of the backup as it has been done after April 30th.

Le jeu. 28 mai 2020 à 10:55, Sebastian Schmidt <notifications@github.com> a
écrit :

**Comment by seaquake** [comment]
Thanks so much!

**Comment by ardenyang** [comment]
Website is alive,Thanks so much!

**Comment by ymartin59** [comment]
@Diaoul Great. My login seems to fail at https://synocommunity.com/login and I can no longer access to admin pages like https://synocommunity.com/admin/versionview/. May you please investigate? It may be an issue with my account only.
Please also create a system Linux account "yma" and register my public key for it?

**Comment by hgy59** [comment]
@Diaoul what is the schedule to update/fix the web page?
- Fastly logo and sponsor message
- Updated Easy Install section with screen shots
- all links to manually download packages are missing

**Comment by Diaoul** [comment]
Any code that is not part of spkrepo has been lost. The templates are the
ones from April 30th. I don't have an ETA on those fixes, probably next
week but ymartin has access so maybe sooner.

**Comment by hgy59** [comment]
@Diaoul thanks for your effort on spkrepo! I was not aware of links to manually download packages are not provided by spkrepo.

**Comment by th0ma7** [comment]
@Diaoul thnx for your work on this.
I was wondering (for my own geek curiosity), how things are in comparison with the previous setup?
My understanding is that it much more responsive and now running on an updated platform?

**Comment by ymartin59** [comment]
Notice publish is broken: https://github.com/SynoCommunity/spkrepo/issues/47
