### ISSUE TITLE
SynoCommunity down?

### ISSUE THREAD

**Issue by prometheus247** [SynoCommunity/spksrc#3994]
Hi, 

I am afraid, but something is offline:

1. I cannot add https://packages.synocommunity.com/ to my Repo:
![image](https://user-images.githubusercontent.com/5222920/82476842-e68a8680-9ace-11ea-96ab-5dcd6faaaadc.png)

2. I cannot download single .SPK from the https://synocommunity.com/packages Website.

2.a whether because its down at all:
![image](https://user-images.githubusercontent.com/5222920/82476645-ad521680-9ace-11ea-8706-42bf88a1da47.png)
URL: https://synocommunity.com/package/sickbeard-custom

2.b or its down when I hit the package I need:
![image](https://user-images.githubusercontent.com/5222920/82476465-6a903e80-9ace-11ea-9238-f8f8d47e58c4.png)
URL: https://packages.synocommunity.com/sabnzbd/40/sabnzbd.v40.f4458[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-grantley-kvmx64-x86-x86_64].spk

So the whole thing looks broken right now. Is your host having central issues? 
Ofc I tried a million different DNS Servers (pihole, router, 8.8.8.8, 8.8.4.4, 1.1.1.1).

What is odd: The source was working for me 5 years. Until I had to rebuild from scratch this week and out of the suddon, I cannot work with your brilliant Repo anyhow.

**Comment by hgy59** [comment]
#3981

**Comment by chaismus** [comment]
Is there a mirror where I can download packages from?

**Comment by hgy59** [comment]
Unfortunately there isn't a mirror. 
This is a community project where contributers invest their spare time. 
There are no sponsors so far (except maybe `fastly` the new hosting provider).

You can build the packages by yourself, or kindly ask whether someone can provide a specific package - when you cannot wait until the migration of the web site is completed (probably next Moday).

**Comment by Stanley008** [comment]
Hmm... I also needed a package. The GIT one :D .  Oh well... hopefully the server will be up and running soon.
