### ISSUE TITLE
dnscrypt proxy, how to do manual restarts?

### ISSUE THREAD

**Issue by sceutre** [SynoCommunity/spksrc#3995]
### Setup
_Package Name: dnscrypt-proxy_   @publicarray

### Actual behavior
First off, love the package, works great.

On the wiki page (https://github.com/SynoCommunity/spksrc/wiki/FAQ-DNSCrypt-proxy) it says `You need to manually restart dnscrypt-proxy to apply changes`.  How do I do that?  I can ssh into my synology as root but don't know the command/incantation to restart.  Right now whenever I change the blacklist, etc I restart the entire box. 

So I guess my bug report would be for clarification on the wiki page of how to restart, hopefully something I could do from the command line.

**Comment by publicarray** [comment]
In the package manager you can just stop and start the package.

Alternatively `synoservice --restart dnscrypt-proxy` or `synoservicectl –restart dnscrypt-proxy` should also work

Hope that clears it up.

**Comment by sceutre** [comment]
Thanks!  I do feel slightly like an idiot not realizing I could use the package manager ;-)
