### ISSUE TITLE
New architecture: Geminilake

### ISSUE THREAD

**Issue by szyb** [SynoCommunity/spksrc#3999]
Lately Synology released new models from x20 series. Some of them using geminilake architecture, which is in fact x64. I did response comparison from official package center for DS718+ (apollolake) and DS720+ (geminilake). For apollolake there are 141 packages, while for geminilake there are 131.  Most of them are having the same download link, so they are binary the same for apollolake and geminilake.
Some of them are missing in geminilake (total: 11)
```
Missing package 'Cloud Station Server'
Missing package 'Cloud Station ShareSync'
Missing package 'Data Deposit Box'
Missing package 'Domotz Network Monitoring'
Missing package 'Hasplm'
Missing package 'IDrive'
Missing package 'MEGAcmd'
Missing package 'NAKIVO Backup and Replication'
Missing package 'NAKIVO Transporter'
Missing package 'Resilio Sync'
Missing package 'TVMosaic'
```
Some of them has different download link
```
GoodSync Server: Different download link https://global.download.synology.com/download/Package/spk/GoodSync%20Server/10.10.19.9/goodsync-server-apollolake.spk - https://global.download.synology.com/download/Package/spk/GoodSync%20Server/10.10.19.9/goodsync-server-x86_64.spk
BRAVIA Signage: Different download link https://global.download.synology.com/download/Package/spk/Sony_BraviaSignage/1.7.8/Sony_BraviaSignage-x86_64-1.7.8.spk - https://global.download.synology.com/download/Package/spk/Sony_BraviaSignage/1.7.4/Sony_BraviaSignage-x86_64-1.7.4_3.spk
Moments: Different download link https://global.download.synology.com/download/Package/spk/SynologyMoments/1.3.5-0706/SynologyMoments-x86_64-1.3.5-0706.spk - https://global.download.synology.com/download/Package/spk/SynologyMoments/1.3.3-0700/SynologyMoments-x86_64-1.3.3-0700.spk
Video Station: Different download link https://global.download.synology.com/download/Package/spk/VideoStation/2.4.7-1603/VideoStation-x86_64-2.4.7-1603.spk - https://global.download.synology.com/download/Package/spk/VideoStation/2.4.8-1611/VideoStation-x86_64-2.4.8-1611.spk
```

and one of them is in geminilake but is not in apollolake
```
Missing in apollolake: Disaster Recovery
```

What do you think about supporting geminilake in synocommunity?

**Comment by BenjV** [comment]
Non of this packages are from the SynCommunity.

**Comment by szyb** [comment]
@BenjV I know. Those packages are from official Package Center just to show how different geminilake is from apollolake. And it seems to be the same (with some exceptions mentioned above)

**Comment by BenjV** [comment]
First of all Synology is always very late with releasing the toolchain for new cpu types and without a new toolchain the SynoCommunity cannot create dedicated packages for those cpu types until that toolchain arrives.

Secondly did you explore those packages to see if there are differences besides the name.
Because almost always all x64 cpu are compatible with a standard x86_64 package.

**Comment by szyb** [comment]
Yes, I've made some research and compared download links for geminilake and apollolake. They are the same in about 90% of cases, so they need to be compatible with x86_64. For other cases packages are missing or they are in different version.

**Comment by hgy59** [comment]
@szyb don't hurry. Synology does not even list the new models on their product page https://www.synology.com/en-us/products.
The geminilake models will be delivered with DSM 6.2.3 and synology did not yet publish any DSM 6.2.3 toolchain on sf.net

**Comment by szyb** [comment]
Ok, I think I jump the line a bit 😁 however I've seen official specs on this page https://www.synology.com/ja-jp/products/DS720+ as well as on https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Compatibility_Peripherals/What_kind_of_CPU_does_my_NAS_have and other Asia synology's pages. It looks like they will get new models from x20 earlier the Europe. 
Btw: in Germany we can pre-order those models with June shipping date.

**Comment by BenjV** [comment]
Here you can find the toolchains that Synology has released.
https://sourceforge.net/projects/dsgpl/files/DSM%206.2.2%20Tool%20Chains/
As you can see no geminilake available yet.

**Comment by McMottek** [comment]
uh ... unfortunate ...

just replaced my damaged DS218Play with a DS720+, and am using the Resilio Sync across all our machines

any idea how long it typically takes Synology to provide the chains and Resilio to create the respective package?

**Comment by hgy59** [comment]
For most packages we do not need the exact toolchain. As geminilake is contained in generic x64 you can build and use it now (since #4000 is merged into master).
For packages that require kernel sources to build, you have to wait for the toolchain published by synology.

@ymartin59 is there any schedule to rebuild and push all x64 packages to include geminilake arch?

**Comment by ymartin59** [comment]
@hgy59 I prefer to wait or trigger on demand package updates to publish additional arch,
By the way, spkrepo rejects package publishment because of invalid configuration since system migration.

**Comment by McMottek** [comment]
Ok. I must say - I consider myself savvy but not an IT expert. Can (should?) I use the x64 package for 2.7 from the resilio help pages?  https://help.resilio.com/hc/en-us/articles/206664850

**Comment by rongith** [comment]
I'm too waiting for new packages (Syncthing,...). My DS213+ died and a new DS420+ arrived on the 25th of june. Didn't know when buying I would have to wait. For the moment only noarch packages available. Thanks for your great work.

**Comment by rdebruin** [comment]
> uh ... unfortunate ...
> 
> just replaced my damaged DS218Play with a DS720+, and am using the Resilio Sync across all our machines
> 
> any idea how long it typically takes Synology to provide the chains and Resilio to create the respective package?

Resilio already has a geminilake packahe. However, it's not on their website yet. But if you ask support for a copy they will send it to you. I received it a week ago.

**Comment by oriddlero** [comment]
Any updates on this? I have a DS 220+ with Gemini Lake and I need Transmission to work and it is being a major pain in the ass with Docker!!

**Comment by BenjV** [comment]
You could also use Download Station that is also Transmission with a GUI from Synology so you could use that until Synology release the Toolchain.

**Comment by ymartin59** [comment]
Server publish process is now fixed. Packages for geminilake architecture should already be visible like dnscrypt-proxy, minio, git... others are coming in following days.

**Comment by MartinRothschink** [comment]
Any plan to release Mono for geminilake?
Or can I use the existing package?

**Comment by itsgooey** [comment]
Upgraded to DS1520+ here. FlexGet giving "Failed to run the package service" error on startup. Assuming this is an architecture issue?

**Comment by ymartin59** [comment]
FlexGet is beta and has not been updated since years: https://synocommunity.com/package/flexget
An update to Python 3 is pending.

**Comment by hgy59** [comment]
Please use #4211 as follow-up. Every package listed there will support geminilake arch when package is released.

And open a dedicated issue to request an update for a package not listed there and not published for geminilake yet.
