### ISSUE TITLE
tvheadend - no hibernation

### ISSUE THREAD

**Issue by jazzmaex** [SynoCommunity/spksrc#400]
I noticed some issues getting my DS109 into hibernation when tvheadend is running. There are continuously activities keeping the system alive, like:
Jan 24 22:33:40 kernel: [50471.270000] [/etc/localtime] opened by pid 8661 [u:(/usr/local/tvheadend/bin/tvhead), comm:(tvheadend)]
Jan 24 22:33:51 kernel: [50482.150000] [/etc/localtime] opened by pid 8664 [u:(/usr/local/tvheadend/bin/tvhead), comm:(tvheadend)]

I tried some settings in TVH without success.
I've seen some issues at lonelycoder.com about EPG avtivities which should have been fixed. But I'm not sure whether these fixes are already in latest synocomm package.

**Comment by pepeEL** [comment]
I have the same problem. WHen i have run package SPK TVheadend on my Synology DS713+ my synology is not go to Hibernation disk HDD. When turn OFF TVHeadend package , NAS with no problem go to Hibernation DIsk HDD.

I use spk TVheadend-testing 4.1.1556-2

Please help me...
