### ISSUE TITLE
node - 'npx: command not found' even after global install

### ISSUE THREAD

**Issue by StrikeAgainst** [SynoCommunity/spksrc#4002]
### Setup
_Package Name:_ Node.js v8
_Package Version:_ 8.9.4-0005

_NAS Model:_ DS218play
_NAS Architecture:_ rtd1296 (armv8)
_DSM version:_ 6.2.3-25426

### Expected behavior
After installing `npx` via `npm i -g npx`, I expected it to run globally...

### Actual behavior
...running a command with `npx`, simply gives me the error output `npx: command not found` though. I can run `npx` by path, which is very cumbersome though: `/volume1/@appstore/Node.js_v8/usr/local/bin/npx`. Any way to get this running as a global executable?

### Steps to reproduce
_1._ Install Node.js v8 via DSM
_2._ Run `npm i -g npx` via SSH
_3._ Run any command requiring `npx`, in my case `npx webpack`

**Comment by ymartin59** [comment]
As Node.js is a package from Synology and not from SynoCommunity, here is not the right place to complain about it. You should go to https://forum.synology.com/
