### ISSUE TITLE
Older packages mono/sonarr

### ISSUE THREAD

**Issue by padio3** [SynoCommunity/spksrc#4004]
With the new server, we have lost access to older packages. My DS213 - DSM 6.2.3 does not support the latest version of Mono and Sonarr. I had to reinitialize the NAS, I had all data backed up, but not the packages.

Please,  indicate where to find these older packages.

Thanks,

**Comment by richyboy1980** [comment]
I think I'm having the same issue.

Need some help with regarding to updating Mono on my Synology DS418j.
I have an error in Sonarr (v.3.0.3.834) which says "Currently installed Mono version 5.8.0.108 is no longer supported. Please upgrade Mono to version 5.20."
So I've tried and tried up date mono, via the SynoCommunity tab in Packages. It says that latest version is 5.8.0.108-11. However the SynoCommunity website states the latest version is v5.20.1.34-13.
I removed the SynoCommunity from the package sources page and readied it but it still won't show there is an updated version.
(Edit: my DSM version is 6.2.3-25426)
Any help would be appreciated!
Thanks for taking the time to read this.

**Comment by sinjinsmythe** [comment]
I also have the same issue on my 212+ as padio3
I'm using DSM 6.2.3-25426
I Installed the Beta version of mono but I had removed sonarr trying to reinstall it and now Sonorr wont run at all.

**Comment by richyboy1980** [comment]
Try Mono 5.20 here [https://github.com/hgy59/spksrc/releases/edit/mono_v5.20-pre](url)

**Comment by richyboy1980** [comment]
Try Mono 5.20 [](https://github.com/hgy59/spksrc/releases/tag/mono_v5.20-pre )

**Comment by sinjinsmythe** [comment]
> Try Mono 5.20 https://github.com/hgy59/spksrc/releases/tag/mono_v5.20-pre

Thanks, just tried to install this but its not supported on the architecture of the DSM, cpu on my DS is a MARVELL Kirkwood 88F6282

**Comment by hgy59** [comment]
@sinjinsmythe just uploaded `mono_88f6281-6.1_5.20.1.34-13.spk` (and armv7)

**Comment by sinjinsmythe** [comment]
> @sinjinsmythe just uploaded `mono_88f6281-6.1_5.20.1.34-13.spk` (and armv7)

Thank you so much for the upload @hgy59 ! I will try this later tonight and let you know how I got on 😊👍

**Comment by sinjinsmythe** [comment]
Looks like I have a similar issue from my logs.
now running the new mono package 5.20.1.34-13
sonarr v20200413-16

`Thu Jun  4 18:02:12 BST 2020
Starting nzbdrone command env PATH=/volume1/@appstore/nzbdrone/../mono/bin:/volume1/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/nzbdrone/var LD_LIBRARY_PATH=/volume1/@appstore/nzbdrone/lib /volume1/@appstore/nzbdrone/../mono/bin/mono /volume1/@appstore/nzbdrone/share/Sonarr/Sonarr.exe 
 r4_conv_to_r8 R47 <- R44
* Assertion: should not be reached at decompose.c:1891


=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/proc/self/maps:
00010000-00369000 r-xp 00000000 09:02 13371904   /volume1/@appstore/mono/bin/mono-sgen
00378000-0037f000 rwxp 00358000 09:02 13371904   /volume1/@appstore/mono/bin/mono-sgen
0037f000-004f8000 rwxp 00000000 00:00 0          [heap]
40000000-40020000 r-xp 00000000 09:00 13616      /usr/lib/ld-2.15.so
40020000-40023000 rwxp 00000000 00:00 0 
40023000-40024000 r-xp 00000000 00:00 0 
40024000-40025000 ---p 00000000 00:00 0 
40025000-40026000 rwxs 00000000 00:10 8196607    /dev/shm/mono.4672
40026000-4002f000 rwxp 00000000 00:00 0 
4002f000-40030000 r-xp 0001f000 09:00 13616      /usr/lib/ld-2.15.so
40030000-40031000 rwxp 00020000 09:00 13616      /usr/lib/ld-2.15.so
40031000-400c9000 r-xp 00000000 09:00 15001      /usr/lib/libm-2.15.so
400c9000-400d8000 ---p 00098000 09:00 15001      /usr/lib/libm-2.15.so
400d8000-400d9000 r-xp 00097000 09:00 15001      /usr/lib/libm-2.15.so
400d9000-400da000 rwxp 00098000 09:00 15001      /usr/lib/libm-2.15.so
400da000-400e0000 r-xp 00000000 09:00 15157      /usr/lib/librt-2.15.so
400e0000-400ef000 ---p 00006000 09:00 15157      /usr/lib/librt-2.15.so
400ef000-400f0000 r-xp 00005000 09:00 15157      /usr/lib/librt-2.15.so
400f0000-400f1000 rwxp 00006000 09:00 15157      /usr/lib/librt-2.15.so
400f1000-400f5000 r-xp 00000000 09:00 12692      /usr/lib/libdl-2.15.so
400f5000-40104000 ---p 00004000 09:00 12692      /usr/lib/libdl-2.15.so
40104000-40105000 r-xp 00003000 09:00 12692      /usr/lib/libdl-2.15.so
40105000-40106000 rwxp 00004000 09:00 12692      /usr/lib/libdl-2.15.so
40106000-4011b000 r-xp 00000000 09:00 15297      /usr/lib/libpthread-2.15.so
4011b000-4012b000 ---p 00015000 09:00 15297      /usr/lib/libpthread-2.15.so

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x40177fa0):0x40177f90  03 10 a0 e1 04 20 a0 e1 43 7f a0 e3 00 00 00 ef  ..... ..C.......
0x40177fa0  01 0a 70 e3 08 00 00 8a 90 40 bd e8 1e ff 2f e1  ..p......@..../.
0x40177fb0  00 00 50 e3 f5 ff ff ca 02 21 c0 e3 00 00 52 e3  ..P......!....R.
0x40177fc0  00 00 60 12 03 00 a0 01 f0 ff ff ea 00 10 60 e2  ..`...........`.

=================================================================
	Native stacktrace:
=================================================================
	0xf2164 - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)
	0xb39d4 - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)
	0x40179370 - /lib/libc.so.6 : __default_rt_sa_restorer_v2
	0x40177fa0 - /lib/libc.so.6 : gsignal
	0x4017bea8 - /lib/libc.so.6 : abort
	0x298cd0 - /volume1/@appstore/nzbdrone/../mono/bin/mono : monoeg_assert_abort
	0x2828e8 - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)
	0x27d350 - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)
	0x298c78 - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)
	0x298f14 - /volume1/@appstore/nzbdrone/../mono/bin/mono : monoeg_assertion_message
	0x7ddc4 - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)
	0xf8988 - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)
	0xf9218 - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)
	0x38ffc - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)
	0xb7184 - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)
	0xb7810 - /volume1/@appstore/nzbdrone/../mono/bin/mono : (null)

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x41d49450 from 0x400217c0
Entering thread summarizer pause from 0x400217c0
Finished thread summarizer pause from 0x400217c0.

Waiting for dumping threads to resume

Debug info from gdb:


=================================================================
	External Debugger Dump:
=================================================================
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Collections.Hashtable:.ctor <0x0002b>
	  at System.Configuration.Configuration:.ctor <0x0002f>
	  at System.Configuration.InternalConfigurationFactory:Create <0x00077>
	  at System.Configuration.ConfigurationManager:OpenExeConfigurationInternal <0x00383>
	  at System.Configuration.ClientConfigurationSystem:get_Configuration <0x00043>
	  at System.Configuration.ClientConfigurationSystem:System.Configuration.Internal.IInternalConfigSystem.GetSection <0x00017>
	  at System.Configuration.ConfigurationManager:GetSection <0x00047>
	  at System.Configuration.ConfigurationManager:get_AppSettings <0x0001b>
	  at NLog.Common.InternalLogger:GetAppSettings <0x00013>
	  at NLog.Common.InternalLogger:GetSettingString <0x0002b>
	  at NLog.Common.InternalLogger:GetSetting <0x0002b>
	  at NLog.Common.InternalLogger:Reset <0x00027>
	  at NLog.Common.InternalLogger:.cctor <0x00037>
	  at System.Object:runtime_invoke_void <0x00073>
	  at <unknown> <0xffffffff>
	  at NLog.Config.LoggingConfiguration:Dump <0x00053>
	  at NLog.LogFactory:set_Configuration <0x001b7>
	  at NLog.LogManager:set_Configuration <0x0002f>
	  at NzbDrone.Common.Instrumentation.NzbDroneLogger:.cctor <0x0002b>
	  at System.Object:runtime_invoke_void <0x00073>
	  at <unknown> <0xffffffff>
	  at NzbDrone.Console.ConsoleApp:.cctor <0x00017>
	  at System.Object:runtime_invoke_void <0x00073>
=================================================================
`

**Comment by padio3** [comment]
Hi,
Tried  mono_88f6281-6.1_5.20.1.34-13.spk, it does not work on DS213 - DSM 6.2.3.
Need an older version for 88f6281. Maybe 5.18?
Where is it available?

Thanks,

**Comment by sinjinsmythe** [comment]
Has anyone managed to get this working on the arm processor models yet?
Tempted to but a blank hard drive in and set up from scratch to see if this is leftover files from the previous version or DSM messing this up

**Comment by sinjinsmythe** [comment]
Guys
Just to update you all, I managed to get this working on my 212+ today, typically I just bought a new 716+ NAS today and now this is working.... Oh well, hope this fix helps the rest of you!
So basically, After installing the beta version of Mono, you have to edit the /var/packages/nzbdrone/scripts/service-setup file
Look for the line the MONO_PATH line in service-setup (not start-stop-status file) and this needs to be edited to read: MONO_PATH="/var/packages/Mono/target/usr/local/bin"

Save the changes to the file.
Now run Sonarr.  You will get there error that the package couldnt start.  Leave it for a few minutes and run the Sonarr package again.  It should run this time.  Worked for me! 

Credit for fix at the bottom of this page

https://forums.sonarr.tv/t/sonarr-fails-to-start-on-synology-after-latest-package-update/25396/15

**Comment by ymartin59** [comment]
You should now be able to retrieve previous versions of Mono and Sonarr packages for your arch:
- https://synocommunity.com/package/mono
- https://synocommunity.com/package/nzbdrone

**Comment by padio3** [comment]
Great! With Version 5.8.0.108-11 of Mono and Version 20180303-13 of Sonarr, I was able to install and launch Sonarr on my DS213 - DSM 6.2.3-25426 and then update Sonarr to version 2.0.0.5344 from inside the app. 
Works well, thanks a million.

**Comment by Zenuka** [comment]
How did you download the old packages? I don't see anything on https://synocommunity.com/package/mono

![image](https://user-images.githubusercontent.com/5391012/88459037-5ed84400-ce92-11ea-863d-fb85479b9a90.png)

**Comment by padio3** [comment]
You are right. Why did they take them down?
