### ISSUE TITLE
[github-actions] build-action cannot download due to certificate issues.

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#4017]
The build environment used for github-build-actions may not have up-to-date ca-certificates.

### Error logs
```
2020-06-07T22:02:23.5898363Z ===>  Downloading files for gmp
2020-06-07T22:02:23.5959230Z wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.lz
2020-06-07T22:02:24.1349414Z ERROR: The certificate of ‘gmplib.org’ is not trusted.
2020-06-07T22:02:24.1349839Z ERROR: The certificate of ‘gmplib.org’ has expired.
2020-06-07T22:02:24.1354885Z make[2]: *** [../../mk/spksrc.download.mk:57: download_target] Error 5
```

```
2020-06-07T22:03:05.4079158Z ===>  Downloading files for iperf3
2020-06-07T22:03:05.4139464Z wget https://downloads.es.net/pub/iperf/iperf-3.7.tar.gz
2020-06-07T22:03:05.6969774Z ERROR: The certificate of ‘downloads.es.net’ is not trusted.
2020-06-07T22:03:05.6970236Z ERROR: The certificate of ‘downloads.es.net’ doesn't have a known issuer.
2020-06-07T22:03:05.6983921Z make[1]: *** [../../mk/spksrc.download.mk:57: download_target] Error 5
```

### Remarks
For my personal build chains, I use a cache for downloaded packages (`distrib` folder) and share it between all my spksrc containers.

What about using a distrib-cache for github-actions? 
Such a cache should support manual upload of packages (and manuel delete of corrupted packages).
With a cache we could reduce bandwith and with manuel uploads bypass download errors.

**Comment by publicarray** [comment]
It's the docker image that is out of date

**Comment by hgy59** [comment]
@publicarray  do you mean the `synocommunity/spksrc` docker image?
This is only 9 days old:
```
synocommunity/spksrc                    latest              d5ac4cca5c5f        9 days ago          864MB
```

**Comment by publicarray** [comment]
hm yes but the commands are run in the docker image and I can confirm them locally so I think that is a legitimate failure.

```sh
docker run --name spksrc --rm -it -v (pwd):/spksrc:delegated -v :/root/.dotnet synocommunity/spksrc:latest /bin/bash
root@0297f1705412:/spksrc#  wget https://downloads.es.net/pub/iperf/iperf-3.7.tar.gz
--2020-06-07 23:48:26--  https://downloads.es.net/pub/iperf/iperf-3.7.tar.gz
Resolving downloads.es.net (downloads.es.net)... 198.128.152.12, 2001:400:210:152::c
Connecting to downloads.es.net (downloads.es.net)|198.128.152.12|:443... connected.
ERROR: The certificate of ‘downloads.es.net’ is not trusted.
ERROR: The certificate of ‘downloads.es.net’ doesn't have a known issuer.
root@0297f1705412:/spksrc# 
```

**Comment by publicarray** [comment]
They have chain issues, https://www.ssllabs.com/ssltest/analyze.html?d=downloads.es.net&s=198.128.152.12&latest

curl 7.64.0 in docker: `curl: (60) SSL certificate problem: unable to get local issuer certificate`

**Comment by hgy59** [comment]
I found an alternate download localtion for iperf3.

**Comment by publicarray** [comment]
I've send a generic email informing them of their misconfiguration. Not sure if anything will come of it but I wanted to be a good internet citizen :)

**Comment by publicarray** [comment]
https://gmplib.org/list-archives/gmp-discuss/2020-June/thread.html#6489

A few related bug reports thanks to Vincent Lefèvre -> https://gmplib.org/list-archives/gmp-discuss/2020-June/006492.html

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961907
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961889
https://gitlab.com/gnutls/gnutls/-/issues/1008

**Comment by hgy59** [comment]
@publicarray thanks for investigation into this issue.
I reverted the alternate url for gmplib. And for iperf3 I switched to the releases of the official github repo.

**Comment by publicarray** [comment]
For servers that implement GnuTLS this is a big issue: https://gitlab.com/gnutls/gnutls/-/issues/1011
https://www.debian.org/security/2020/dsa-4697
