### ISSUE TITLE
Transmission 2.94 - other folder

### ISSUE THREAD

**Issue by JardaH69** [SynoCommunity/spksrc#4019]
### Setup
_Package Name:_ Transmission
_Package Version:_ 2.94-16

_NAS Model:_ DS218j
_NAS Architecture:_ x86 (MARVELL Armada 385 88F6820)
_DSM version:_ DSM 6.2.3-25426

### Expected behavior
Can read form other folder than default

### Actual behavior
Cant read form other folder than default
### Steps to reproduce
_1._ create folder in nas - Control Panel - Shared folder - Create - new folder (eg. **D**ownloads)
_2._ set path for torrent /volume1/Downloads

**Comment by hgy59** [comment]
@JardaH69 can you give us more details?

I created a shared folder `volume/Transmission` and installed Transmission from the synocommunity repo (2.94-16).
I successfully downloaded a torrent with this configuration.

**Comment by BenjV** [comment]
More likely a right issue and certainly nothing to do with capital letters in foldernames.
Did you give the group sc-download accessrights to this folder?

**Comment by JardaH69** [comment]
> @JardaH69 can you give us more details?
> 
> I created a shared folder `volume/Transmission` and installed Transmission from the synocommunity repo (2.94-16).
> I successfully downloaded a torrent with this configuration.

Yes my default folder works fine. But if I use for example **volume2/test** as path for one torrent, it dont work. And yes I gave the group sc-download accessrights to **test** folder.

If I try to verify that torrent it starts verifying, but after verify it drops again to 0% and stoppend state.

![image](https://user-images.githubusercontent.com/62809719/84247192-01697d00-ab08-11ea-9c29-f22c89593d97.png)
![image](https://user-images.githubusercontent.com/62809719/84247243-19d99780-ab08-11ea-83f4-7b2484043131.png)
![image](https://user-images.githubusercontent.com/62809719/84247225-0f1f0280-ab08-11ea-81b1-49591e934b34.png)

**Comment by BenjV** [comment]
Did you stop and start the package after you created that folder?
I use my own (not the default) folder and have no problems.

**Comment by BenjV** [comment]
If that does not work it is a Transmission issue and you should ask the transmission developers.
Here we just build Synology packages with the transmission sources from upstream.

**Comment by JardaH69** [comment]
> If that does not work it is a Transmission issue and you should ask the transmission developers.
> Here we just build Synology packages with the transmission sources from upstream.

Ok. Anyway thanks for help.
