### ISSUE TITLE
No GUI after updating to Syncthing 1.4.0-19

### ISSUE THREAD

**Issue by juergent20** [SynoCommunity/spksrc#4026]
_For new Package Requests, see the guidelines_  

Syncthing
1.4.0-19

DS213A and DS213J
6.2.3-25426

I updated both machines from 1.3.something to 1.4.0-19. On both machines Syncthing doesn't start, hitting the run button in the package center gives very briefly a running state and then again stopped state.

 
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by juergent20** [comment]
Sorry hit the new issue button to early. The logs are not really helpful, one sees that the start command is issued, that's all.

Finally I tried to start it from the command line and got this:

[start] 14:34:42 INFO: syncthing v1.4.0 "Fermium Flea" (go1.13.8 linux-arm) root@eaf6d11355bb 2020-04-06 20:07:56 UTC
[JXVWZ] 14:34:43 INFO: My ID: JXVWZJE-BI5BHF6-37T6M7C-LTWVWJI-JPJLH6Y-BDMEWEM-CU7F6CB-NQ4IDAY
[JXVWZ] 14:34:43 INFO: Automatic upgrade (current "v1.4.0" < latest "v1.6.1")
[JXVWZ] 14:34:44 INFO: Single thread SHA256 performance is 12 MB/s using minio/sha256-simd (11 MB/s using crypto/sha256).
[JXVWZ] 14:34:45 INFO: Hashing performance is 5.33 MB/s
[JXVWZ] 14:34:45 WARNING: Database schema: Syncthing v1.6.0 required
[monitor] 14:34:45 INFO: Syncthing exited: exit status 1
[start] 14:34:47 INFO: syncthing v1.4.0 "Fermium Flea" (go1.13.8 linux-arm) root@eaf6d11355bb 2020-04-06 20:07:56 UTC
[JXVWZ] 14:34:49 INFO: My ID: JXVWZJE-BI5BHF6-37T6M7C-LTWVWJI-JPJLH6Y-BDMEWEM-CU7F6CB-NQ4IDAY
[JXVWZ] 14:34:49 INFO: Automatic upgrade (current "v1.4.0" < latest "v1.6.1")
[JXVWZ] 14:34:51 INFO: Single thread SHA256 performance is 3.3 MB/s using crypto/sha256 (2.3 MB/s using minio/sha256-simd).
[JXVWZ] 14:34:54 INFO: Hashing performance is 2.11 MB/s
[JXVWZ] 14:34:54 WARNING: Database schema: Syncthing v1.6.0 required
[monitor] 14:34:54 INFO: Syncthing exited: exit status 1
[start] 14:34:55 INFO: syncthing v1.4.0 "Fermium Flea" (go1.13.8 linux-arm) root@eaf6d11355bb 2020-04-06 20:07:56 UTC
[JXVWZ] 14:34:56 INFO: My ID: JXVWZJE-BI5BHF6-37T6M7C-LTWVWJI-JPJLH6Y-BDMEWEM-CU7F6CB-NQ4IDAY
[JXVWZ] 14:34:57 INFO: Automatic upgrade (current "v1.4.0" < latest "v1.6.1")
[JXVWZ] 14:34:58 INFO: Single thread SHA256 performance is 5.5 MB/s using minio/sha256-simd (4.8 MB/s using crypto/sha256).
[JXVWZ] 14:34:59 INFO: Hashing performance is 5.15 MB/s
[JXVWZ] 14:34:59 WARNING: Database schema: Syncthing v1.6.0 required
[monitor] 14:34:59 INFO: Syncthing exited: exit status 1
[start] 14:35:01 INFO: syncthing v1.4.0 "Fermium Flea" (go1.13.8 linux-arm) root@eaf6d11355bb 2020-04-06 20:07:56 UTC
[JXVWZ] 14:35:01 INFO: My ID: JXVWZJE-BI5BHF6-37T6M7C-LTWVWJI-JPJLH6Y-BDMEWEM-CU7F6CB-NQ4IDAY
[JXVWZ] 14:35:02 INFO: Automatic upgrade (current "v1.4.0" < latest "v1.6.1")
[JXVWZ] 14:35:03 INFO: Single thread SHA256 performance is 5.1 MB/s using minio/sha256-simd (4.9 MB/s using crypto/sha256).
[JXVWZ] 14:35:07 INFO: Hashing performance is 1.74 MB/s
[JXVWZ] 14:35:07 WARNING: Database schema: Syncthing v1.6.0 required
[monitor] 14:35:07 INFO: Syncthing exited: exit status 1
[monitor] 14:35:08 WARNING: 4 restarts in 25.684246372s; not retrying further

**Comment by acolomb** [comment]
Unfortunately it's the same problem as in #3941 again. We need to update the SPK to package v1.6.0 at least. Otherwise it will choke on the database schema when reinstalling, because that was changed after Syncthing auto-upgraded itself.

**Comment by acolomb** [comment]
I opened PR #4027 with a newer version that should fix this.  Could you test the attached SPK please?
[syncthing_armv7-6.1_1.6.1-20.spk.zip](https://github.com/SynoCommunity/spksrc/files/4771622/syncthing_armv7-6.1_1.6.1-20.spk.zip)

**Comment by acolomb** [comment]
Or try [this link](https://github.com/SynoCommunity/spksrc/suites/790440707/artifacts/8427033), pointing to the package built by GitHub on the PR.

**Comment by juergent20** [comment]
I'm new to this. I tried synopkg install with both and got error 290. There seems to be no update command, can I do a uninstall without loosing settings?

**Comment by acolomb** [comment]
There is a link in Package Center to install from an SPK file directly. If you don't uninstall the previous version, data should be retained.

**Comment by juergent20** [comment]
I get a platform not supported message for both. uname gives me armv5tel, the packages are for armv7. Is that the reason?

**Comment by juergent20** [comment]
Just found out the DS213J is armv7, will check the pkgs there.

**Comment by acolomb** [comment]
> Just found out the DS213J is armv7, will check the pkgs there.

Yes that's the one I looked up. Couldn't find a DS213A in the list.

**Comment by juergent20** [comment]
The pkg you sent first is working on the DS213J. Thank you very much!

**Comment by juergent20** [comment]
The other one is a DS213AIR.

**Comment by acolomb** [comment]
Then I think [this](https://github.com/SynoCommunity/spksrc/suites/790440707/artifacts/8427030) should be the right package. Please report in the pull request #4027 if it works.

**Comment by juergent20** [comment]
The link gives me a 404.

**Comment by juergent20** [comment]
Sorry, after login it's working ....

**Comment by juergent20** [comment]
Working! Again, thank you very much for fixing this!

**Comment by JensHae** [comment]
I think i'm having the same problem for my DS416PLAY. Where can I find the right package to fix it?

**Comment by acolomb** [comment]
According to the [Wiki](https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model), that one has a `braswell (x64)` architecture. [This package](https://github.com/SynoCommunity/spksrc/suites/790440707/artifacts/8427036) should work generically for all x64 CPUs. You can find all built "artifacts" on the [build details](https://github.com/SynoCommunity/spksrc/pull/4027/checks?check_run_id=765886664) page linked from the Pull Request.

**Comment by relaxpreppy** [comment]
> According to the [Wiki](https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model), that one has a `braswell (x64)` architecture. [This package](https://github.com/SynoCommunity/spksrc/suites/790440707/artifacts/8427036) should work generically for all x64 CPUs. You can find all built "artifacts" on the [build details](https://github.com/SynoCommunity/spksrc/pull/4027/checks?check_run_id=765886664) page linked from the Pull Request.

I am getting a 404 for the x64 link. Would like to try it since my package is currently broken after the upgrade.

**Comment by acolomb** [comment]
Yeah, not sure why some artifact links stop working after some time. Glad you found it, @relaxpreppy.

I hope that #4027 can finally be published soon. I'm trying to keep it up-to-date with upstream until then.

**Comment by relaxpreppy** [comment]
> Yeah, not sure why some artifact links stop working after some time. Glad you found it, @relaxpreppy.
> 
> I hope that #4027 can finally be published soon. I'm trying to keep it up-to-date with upstream until then.

Since Syncthing updates itself internally, is there a reason to ever attempt to update the synocommunity package through th Synology package manager?

**Comment by acolomb** [comment]
Not from Syncthing's side, but there might be a reason when packaging changes are required, e.g. for newer DSM versions. In addition anyone trying to reinstall the package while preserving their configuration state might hit this problem.

Though I think it will not be as critical anymore with recent changes to Syncthing's own error behavior.
