### ISSUE TITLE
Transmission 3.0 "Could not connect to tracker" and remote port is closed 

### ISSUE THREAD

**Issue by qubabos** [SynoCommunity/spksrc#4032]
Something is wrong with transmission 3.0. I always geyt " Could not connect to tracker" and remote port is closed (but is forwarded i my router). This version couldnt use proper network connection from my DSM. Version 2.94 works just fine. This is not file permission issue (torrents are adding to transmission and preallocate properly)

_Originally posted by @qubabos in https://github.com/SynoCommunity/spksrc/issues/3996#issuecomment-642884549_

**Comment by BenjV** [comment]
The SynoCommunity did  not release a version 3.0 of Transmission.
The latest available version is 2.94-16

So either ask the transmission developers or else the people who created that package.

**Comment by qubabos** [comment]
I know that there is no release for now, but I'm using this package : https://github.com/SynoCommunity/spksrc/actions/runs/131149788
hope this will be fixed till release.

**Comment by BenjV** [comment]
I tried that version on my test Nas and found no such problem.
I could download fine with the 3.0 version.

So most likely your network settings are blocking the transmission traffic or you are using a faulty torrent.

**Comment by qubabos** [comment]
weird issue, transmission 2.94-16 works just fine, this package doesn't.

**Comment by BenjV** [comment]
Which cpu version did you use?

The error is seems to suggest you cannot reach the tracker

Did you checked your firewall(s) (NAS and router).
Does your router allow all ports or is there for example a range limit?

**Comment by qubabos** [comment]
@BenjV 
cpu : Intel Pentium D1508
firewall set correctly
yes, it allows all ports
my router has public ip at WAN port.

**Comment by BenjV** [comment]
I also use ip4 only so that is not the problem.

There must be a setting in your network, because the message is saying that the tracker cannot be reached, so the outgoing traffic is blocked and normally only firewalls do that.

**Comment by Zialus** [comment]
I can reproduce the "Could not connect to tracker" problem but only with trackers using using https.

**Comment by qubabos** [comment]
> I can reproduce the "Could not connect to tracker" problem, but only with trackers using using https.
confirm, something is messed up with ssl:
![2020-06-22_072515](https://user-images.githubusercontent.com/2496350/85251562-e4af3c80-b459-11ea-93b2-7078f8a0318c.png)
![2020-06-22_072543](https://user-images.githubusercontent.com/2496350/85251574-eb3db400-b459-11ea-9fa0-70af1668a554.png)

**Comment by BenjV** [comment]
Transmission is using the cURL library (https://curl.haxx.se/) .
That library must be built with SSL support (and potentially against an SSL library that supports a particular SSL/TLS version in use by the tracker).

So maybe that is what went wrong.

I tried to find a torrent with a https tracker to test it but failed to find one,  so I could not test it.

**Comment by jabarel** [comment]
Its problem with https, i get the same error. with http works good

**Comment by zlhdd108** [comment]
![image](https://user-images.githubusercontent.com/16465666/86323177-f0c3a700-bc6e-11ea-81b8-4e4dffc0c6b1.png)

**Comment by hgy59** [comment]
@zlhdd108 
This is the same issue as reported for git (#3843)
The bundled cert.pem in transmission is missing some of the CA certificates. If you use /bin/curl instead of /var/packages/transmission/target/bin/curl there is no error reported.

We have to find a way to use the default curl or to force transmission/target/bin/curl to use the ca-certificates installed in the system (/etc/ssl/certs/ca-certificates.crt).

As for now packages using cross/curl install the downloaded cert.pem (with `mk-ca-bundle.pl`) at build time and this will never be updated without a package update.

We should modify `cross/curl` to not download cert.pem but instead use the ca-certificates.crt installed (and updated) by DSM.
All packages depending on `cross/curl` must be updated and validated whether the former cert.pem was referenced (as git did).

I didn't analyze why the cert.pem is missing some common Root CAs, but to avoid future problems, synocommunity packages should use the CA bundle of DSM anyway.

**Comment by ascii-ts** [comment]
i'm not so of a programmer or expert
so i thought i get a quick win in just replacing the curl binary after upgrade.
i tried it with several curl binary i have on the syno.
`bash-4.3# find / -iname curl
/etc/apparmor.d/abstractions/curl
/volume1/@appstore/DownloadStation/lib/curl
/volume1/@appstore/nzbdrone/bin/curl
/volume1/@appstore/python/lib/python2.7/site-packages/curl
/volume1/@appstore/python/bin/curl
/volume1/@appstore/transmission/bin/curl
/volume1/@appstore/jackett/bin/curl
/volume1/@optware/bin/curl
/volume1/@optware/share/curl
/volume1/@docker/aufs/diff/cc571fb0d9aefaebb68ad3c89fd040f5eb8992072a30c484a3aa98865109459c/usr/include/curl
/volume1/@docker/aufs/diff/0c70b9157529f2e5f6f07042ea7a73b26fc515afd33fe7e4d3409de1618a0c14/usr/bin/curl
/volume1/@docker/aufs/diff/0c70b9157529f2e5f6f07042ea7a73b26fc515afd33fe7e4d3409de1618a0c14/usr/share/doc/curl
/volume1/@docker/aufs/diff/7b144d3b770b8fe5cd47e069d61403acfa1856576eff9b246aff2d346ab28e07/usr/include/curl
/volume1/@docker/aufs/diff/66ac697e0a46f6a695505ed48f0598ff2d8977bafb3776dbad66ab15650bb110/usr/bin/curl
/volume1/@docker/aufs/diff/66ac697e0a46f6a695505ed48f0598ff2d8977bafb3776dbad66ab15650bb110/usr/share/doc/curl
/etc.defaults/apparmor.d/abstractions/curl
/usr/bin/curl
/opt/bin/curl
/opt/share/curl
bash-4.3# `

all ended up with "Could not connect to tracker" in transmission but ok on the cli
```
bash-4.3# /volume1/@appstore/transmission/bin/curl -v https://google.de
* Rebuilt URL to: https://google.de/
*   Trying 2a00:1450:4009:81c::2003...
* TCP_NODELAY set
* Connected to google.de (2a00:1450:4009:81c::2003) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /var/packages/python/target/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.google.de
*  start date: Jun 17 14:34:12 2020 GMT
*  expire date: Sep  9 14:34:12 2020 GMT
*  subjectAltName: host "google.de" matched cert's "google.de"
*  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: google.de
> User-Agent: curl/7.56.1
```
so i tried to swap the cert.pem file from working packages.
also no luck.
so could it be a problem inside transmission?

**Comment by hgy59** [comment]
Just created a pre-release on my [curl_ca-bundle](https://github.com/hgy59/spksrc/tree/curl_ca-bundle) branch for https://github.com/SynoCommunity/spksrc/pull/4066.
pre-release packages are [here](https://github.com/hgy59/spksrc/releases/tag/transmission-https-fix).

**Comment by qubabos** [comment]
> Just created a pre-release on my [curl_ca-bundle](https://github.com/hgy59/spksrc/tree/curl_ca-bundle) branch for #4066.
> pre-release packages are [here](https://github.com/hgy59/spksrc/releases/tag/transmission-https-fix).

work just fine, thanks a lot for this !

**Comment by ymartin59** [comment]
Published https://synocommunity.com/package/transmission
