### ISSUE TITLE
gevent build failure - missing rename

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#4043]
### Setup
_Package Name:_ `gevent`
_Package Version:_ n/a

_NAS Model:_ n/a
_NAS Architecture:_ n/a
_DSM version:_ n/a

### Expected behavior
While trying to figure out build failures against `ffsync` I ended-up noticing a `gevent` build issue due to missing `rename` command line utility.  Needs to be included in both the default Docker image and `README.rst`

### Log output
```
removing build/bdist.linux-x86_64/wheel
/bin/sh: 1: rename: not found
Makefile:20: recipe for target 'myInstall' failed
make[2]: *** [myInstall] Error 127
make[2]: Leaving directory '/home/spksrc/git-cmake2/spksrc/cross/gevent'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory '/home/spksrc/git-cmake2/spksrc/spk/ffsync'
../../mk/spksrc.spk.mk:434: recipe for target 'arch-apollolake' failed
make: [arch-apollolake] Error 2 (ignored)
```

**Comment by hgy59** [comment]
@ymartin59 is working on ffsync in #3849
