### ISSUE TITLE
Mosquitto package not available through the package center

### ISSUE THREAD

**Issue by Luuk2016** [SynoCommunity/spksrc#4044]
### Setup
_Package Name:_ Mosquitto
_Package Version:_  v1.4.14-9 

_NAS Model:_ DS720+
_NAS Architecture:_ x86-64
_DSM version:_ 6.2.3

### Expected behavior
Show the Mosquitto package as an available package

### Actual behavior
Mosquitto package not showing up in the package center
All other packages are showing up.
When checking my old DS215J the package is just showing up, is this maybe because of a different architecture (215J runs on ARM)?

**Comment by hgy59** [comment]
DS720+  - as well as DS220+, DS420+ and DS920+ - have processors of geminilake arch, that is not included in the generic x64 arch before June 2th 2020.
Therefore all packages for x64 arch have to be recreated and published to the synocommunity package repository to support these new NAS models.

**Comment by Luuk2016** [comment]
> 
> 
> DS720+ - as well as DS220+, DS420+ and DS920+ - have processors of geminilake arch, that is not included in the generic x64 arch before June 2th 2020.
> Therefore all packages for x64 arch have to be recreated and published to the synocommunity package repository to support these new NAS models.

Will this be done once in a while?
Or can i do this rebuild myself?

**Comment by hgy59** [comment]
fixed by #4191 (version 1.6.12-11)
