### ISSUE TITLE
Not available on DS420+

### ISSUE THREAD

**Issue by myca5a** [SynoCommunity/spksrc#4045]
Hello,

It seems that Hassio.io  in my NAS DS420+ by synocommunoty is not avaible ?
It is possible to add that model ?

Thanks

**Comment by BenjV** [comment]
Synology has not yet published the tools chain for the new models so until then it  is not possible to build packages for those model except packages that run from source (noarch) like python applications

**Comment by myca5a** [comment]
Oks thanks
So wait
