### ISSUE TITLE
Mono version

### ISSUE THREAD

**Issue by SeSie** [SynoCommunity/spksrc#4054]
Hi,

I received a message that I need to upgrade Mono in oder to rund Sonarr properly. I checkt the packages in package center an I am running the moste current version available (5.20.1.34).

However, when I check the Mono homepage, I noticed that there is already newer version (6.8.0) available. When will this package be available in the package center or how can I upgrade Mono directly (I would almost need a step by step instruction if the installation requires more than clicking through a installation programm). :-)

I am using DSM214+ with the lates DSM version.
Thanks.

**Comment by Slotracertje** [comment]
Hello,

I have run into the same problem, so i checked here and see this post.
Is it possible to upgrade Mono?

Model: DS214+
DSM version: 6.2.3-25426
Mono version: 5.20.1.34-13
Sonarr version: 20200409-16

Thank you.

**Comment by mreid-tt** [comment]
hey @SeSie, @Slotracertje, can you give some more details (logs and maybe screenshots if applicable) of the issue running with Sonarr? I've been using v5.20.1.34-18 for some time now with Sonarr v3. Perhaps I can help with your situation?
