### ISSUE TITLE
Missing toolchain ppc853x-4.2

### ISSUE THREAD

**Issue by amikot** [SynoCommunity/spksrc#4055]
My DS509+ has installed DSM4.2 which is most recent version for that model. I did try to compile new transmission using arch-ppc853x-4.3 but I'm unable to upload (upload failed - check network). 

Similar problem was highlighted in issue #2053, but nobody realised it may be wrong toolchain used for compilations. (actually someone mentioned this, but nobody checked that).

I know that 509+ is now old, but if that's not big problem, maybe someone could prepare exact toolchain for that hardware/software combination?

Thanks :)

**Comment by hgy59** [comment]
@amikot adding the toolchain was a tiny item and the bufix for the compile error a small one 😄 
anyway, you will have to build this by yourself, since such old devices are not supported in the synocommunity package repository.

**Comment by amikot** [comment]
@hgy59 : Thanks for your work. New Transmission is now installed on my DS509+.
Of course it wasn't too easy. For first I couldn't find new toolchain in cloned git. I found that your fork is not cloning with your changes, but actually is cloning main branch. Luckily I found that zip file contain updated version so I just downloaded it as it was.
No problems compiling transmission - all worked fine. 
Problem was with installation. From some reason web return error when installing. Now I think it may be permission error. Anyway I used console to install and it worked.
Last problem was with web UI authentication - from some reason newly compiled transmission is cannot handle DSM users credentials - I logged in using default user/password which was admin/admin.

Later I will try to compile other packages. Maybe there will be some more that gonna work.

**Comment by hgy59** [comment]
> Of course it wasn't too easy. For first I couldn't find new toolchain in cloned git. I found that your fork is not cloning with your changes, but actually is cloning main branch.

@amikot I never merge branches on my fork to keep the master in sync with upstream. So after you clone my repo you have to checkout the branch `transmission_ds509plus` to get the version with the 4.2 toolchain.

Regarding user and permissions: There was some redesign for DSM 6 and I suppose not everthing is really backwards compatible with DSM 4.x.

But congrats you worked it out 👍
