### ISSUE TITLE
The deluge package has vanished from the repository

### ISSUE THREAD

**Issue by bbappserver** [SynoCommunity/spksrc#4057]
### Setup
 deluge 1.3.15-9

_NAS Model:_  DS416j
_NAS Architecture:_ armv71
_DSM version:_ DSM 6.2.2-24922 Update 4

### Expected behavior
Deluge is listed in package centre community tab

### Actual behavior
Deluge is not listed in package centre community tab

### Steps to reproduce
Open package centre community tab

**Comment by ymartin59** [comment]
Update has been published
