### ISSUE TITLE
[Package Request] hashdeep

### ISSUE THREAD

**Issue by antoniomacri** [SynoCommunity/spksrc#4058]
Name: hashdeep
Description: A set of cross-platform tools to compute hashes
Website: https://github.com/jessek/hashdeep
Software documentation: https://github.com/jessek/hashdeep
Build/Installation documentation: https://github.com/jessek/hashdeep/blob/master/INSTALL
Source Code: https://github.com/jessek/hashdeep
License: Public domain/GPL (https://github.com/jessek/hashdeep/blob/master/COPYING)

**Comment by antoniomacri** [comment]
What can I do to contribute it myself?

With the following steps I was able to run hashdeep on my NAS (DS620slim).
```
> docker pull synocommunity/spksrc
> docker run -it synocommunity/spksrc /bin/bash
root@b7042d97ed81:/spksrc# git clone https://github.com/jessek/hashdeep.git
root@b7042d97ed81:/spksrc# cd hashdeep
root@b7042d97ed81:/spksrc/hashdeep# sh bootstrap.sh
root@b7042d97ed81:/spksrc/hashdeep# ./configure --prefix=/home/hashdeep LDFLAGS="-static"
root@b7042d97ed81:/spksrc/hashdeep# make
root@b7042d97ed81:/spksrc/hashdeep# make install
root@b7042d97ed81:/spksrc/hashdeep# ls -l /home/hashdeep/*
/home/hashdeep/bin:
total 40776
-rwxr-xr-x 1 root root 6955536 Jul  4 15:54 hashdeep
-rwxr-xr-x 1 root root 6955536 Jul  4 15:54 md5deep
-rwxr-xr-x 1 root root 6955536 Jul  4 15:54 sha1deep
-rwxr-xr-x 1 root root 6955536 Jul  4 15:54 sha256deep
-rwxr-xr-x 1 root root 6955536 Jul  4 15:54 tigerdeep
-rwxr-xr-x 1 root root 6955536 Jul  4 15:54 whirlpooldeep

/home/hashdeep/share:
total 4
drwxr-xr-x 3 root root 4096 Jul  4 15:54 man
```

Notice I had to specify `LDFLAGS="-static"` to `./configure` in order to link all libraries statically. Without that, I was getting:
```
hashdeep: /lib/libstdc++.so.6: no version information available (required by hashdeep)
hashdeep: /lib/libstdc++.so.6: no version information available (required by hashdeep)
hashdeep: /lib/libstdc++.so.6: no version information available (required by hashdeep)
hashdeep: /lib/libstdc++.so.6: no version information available (required by hashdeep)
hashdeep: /lib/libstdc++.so.6: no version information available (required by hashdeep)
hashdeep: /lib/libstdc++.so.6: no version information available (required by hashdeep)
hashdeep: /lib/libstdc++.so.6: no version information available (required by hashdeep)
hashdeep: relocation error: hashdeep: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

Is there a better way to solve this error?

**Comment by hgy59** [comment]
> What can I do to contribute it myself?

@antoniomacri Welcome and thanks for your contribution.

To contribute please regard [CONTRIBUTING](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md). In your case follow the [Pull Requests](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#pull-requests) section.

For hashdeep as this is a file related command line tool, we propose to include it in the `synocli-file` package.
For faster verification I propose a diyspk for hashdeep (such _do it yourself_ packages are not published. These build a single package that is part of a larger collection).

1. create cross/hashdeep Makefile and validate the download with `make digests` (this will also create the digests file that is to be added to the repo, use `make clean` before retry after error).
2. in cross/hashdeep build with arch-x64 and create PLIST file based on work-x64-6.1/hashdeep.plist
3. validate cross compilation with e.g. arch-armv7
4. create diyspk/hashdeep Makefile (use SPK_COMMANDS to link hashdeep binaries to /usr/local/bin)
5. build and test package with your Diskstation
6. validate `make all-supported` with diyspk/hashdeep
7. add cross/hashdeep to spk/synocli-file/Makefile and validate build with `make all-supported`.

**We already have `rhash` in synocli-file. Is there any benefit to include hashdeep?**

**Comment by antoniomacri** [comment]
Hi, I didn't know about rhash. I've been using it during these days and it seems very powerful.

I can emulate almost everything I was doing with hashdeep, so I think I'm just switching to it.

Thanks, for me you can close this issue.
