### ISSUE TITLE
icecast + ezstream: ID3v2 tags recognition

### ISSUE THREAD

**Issue by xaozai** [SynoCommunity/spksrc#4059]
https://synocommunity.com/package/icecast
This package includes ezstream, which does not recognize id3v2 tags.

Could you please rebuild ezstream with the libtagc0 library as described here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833314

I would like to have support for tags in UTF-8 encoding.
Currently, icecast displays file names instead of artist and track names from tags on the status page.

**Comment by hgy59** [comment]
@xaozai you find a pre-release [here](https://github.com/hgy59/spksrc/releases/tag/icecast_taglib_pre-1)
Can you validate with your diskstation that this works as expected (particulary the UTF-8 encoding)?

Thanks to _Add generic cmake helper mk (#3998)_ by @th0ma7 it was straight forward to add taglib with cmake build.

**Comment by hgy59** [comment]
As the github actions completed successfully you may download the packages [here](https://github.com/SynoCommunity/spksrc/actions/runs/158123286) too.

**Comment by xaozai** [comment]
Thank you very much! Now everything is fine! Id3v2 tags are recognized correctly in UTF-8.
And special thanks for your promptness! :)

**Comment by th0ma7** [comment]
> Thanks to _Add generic cmake helper mk (#3998)_ by @th0ma7 it was straight forward to add taglib with cmake build.

I'm really happy to hear that it worked all right!  Excellent news.
