### ISSUE TITLE
[FFmpeg] Request for update: Gemini Lake arch

### ISSUE THREAD

**Issue by THX723** [SynoCommunity/spksrc#4063]
I see that `geminilake` architecture is finally included in Master. Would like to request for an update/rebuild of the existing FFmpeg package so it is compatible with the newer DSx20 series on Gemini Lake CPU.

I do understand this build will only be leveraging the generic x64 sets. The Gemini Lake specifics will have to wait until Synology release and updated toolchain.

**Comment by th0ma7** [comment]
`geminilake` package of `ffmpeg` is on its way (version 4.2.4).  Leave me a day or two and it should be available.

**Comment by th0ma7** [comment]
Package are now published, closing.
