### ISSUE TITLE
Cannot download .spk-Files manually

### ISSUE THREAD

**Issue by eRaz3r** [SynoCommunity/spksrc#4064]
Have a big Problem too. I need the Syncthing-File for my 212+ because it is broken after updating. Are there any news, what is the problem with SynoCommunity about? I can't klick on my architecture to dowlad the .spk manually.

**Comment by ymartin59** [comment]
Corresponding code has not been included in current deployment: https://github.com/SynoCommunity/spkrepo/pull/46

**Comment by eRaz3r** [comment]
@acolomb thanks for your help. I was wrong and thougt, the issue is related to the server Problem. But it is different. In the past I can click on the architecture and download the .spk-File. Now I am not longer able to do this. 

@ymartin59 you are right. I deleted the reference.

I build the Package in a VM by myself. Poorly it doesn't work as a syncthing stopps after strating every time I try it. Now I uninstall it, reinstall it and configure it from the beginning.

**Comment by acolomb** [comment]
@eRaz3r tgat would not have been necessary when building from the version in the mentioned PR. Unfortunately Syncthing didn't handle some upgrade situations gracefully, which should be better with the recent version though.
