### ISSUE TITLE
NZBGET - Failed to download

### ISSUE THREAD

**Issue by madmaxnz** [SynoCommunity/spksrc#4072]
Setup
Package Name: nzbget
Package Version: v20180322-25

NAS Model: RS814+
NAS Architecture: 
DSM version: 6.2.3-25426

Expected behavior
**able to install nzbget**

Actual behavior

**Failed tto download "nzbget"**

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```

Not sure how to access the above log

I have downloaded Sonar and Mono just fine with no issues

**Comment by Diaoul** [comment]
Duplicate #4071

**Comment by madmaxnz** [comment]
Why do you close my post this is Not the samething as #4017 too different issues.

**Comment by madmaxnz** [comment]
![2020-07-17_16-30-21](https://user-images.githubusercontent.com/68407487/87755784-fd3d2780-c84a-11ea-9811-9a5f052fe2c4.png)
![2020-07-17_16-30-17](https://user-images.githubusercontent.com/68407487/87755788-fe6e5480-c84a-11ea-9774-a36aec5f591e.png)

**Comment by Diaoul** [comment]
Is this still happening? I can't see that kind of errors from the server logs

**Comment by madmaxnz** [comment]
@Diaoul yes still happing for me , I check few min ago.  Is there any logs i can provide ?

**Comment by Diaoul** [comment]
Caching issue, fixed by @publicarray

**Comment by madmaxnz** [comment]
thank you both fixed now
