### ISSUE TITLE
Synology DS218+ Failed to download "Python"

### ISSUE THREAD

**Issue by InfernoJaffa** [SynoCommunity/spksrc#4073]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: CouchPotato
_Package Version: 20180513-7

_NAS Model: DS218+
_NAS Architecture:_ 
_DSM version: DSM 6.2.3-25426

### Expected behavior
Click install CouchPotato package. Informed that Python & Git will be installed, click OK and the packages install.

### Actual behavior
Click install CouchPotato package. Informed that Python & Git will be installed, click OK and then receive a "Failed to download "Python"" message.

### Steps to reproduce
_1. Click Install CouchPotato and follow through menu.
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Diaoul** [comment]
Is this still happening? I can't see that kind of errors from the server logs

**Comment by Diaoul** [comment]
Caching issue, fixed by @publicarray
