### ISSUE TITLE
Synology DS220+(Gemini Lake) Transmission Package Request

### ISSUE THREAD

**Issue by oriddlero** [SynoCommunity/spksrc#4074]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Transmission
_Package Version:_ 

_NAS Model:_ 220+
_NAS Architecture:_ Gemini Lake
_DSM version:_ 6+

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by oriddlero** [comment]
Can someone please help with this, the transmission package in docker is also giving me major problems so will be really nice if the package could just work like it does on the other architectures

**Comment by BenjV** [comment]
https://github.com/SynoCommunity/spksrc/actions/runs/131149788
You can use the X64 package.

Or you could use Download Station from Synology, which is also Transmission with a Synology gui.

**Comment by ymartin59** [comment]
Published https://synocommunity.com/package/transmission
