### ISSUE TITLE
Nano not available for DS720+ DSM 6.2.3-25426 Update 2

### ISSUE THREAD

**Issue by mshipek** [SynoCommunity/spksrc#4075]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Nano
_Package Version:_ 2.9.8-5

_NAS Model:_ DS720+
_NAS Architecture:_ geminilake
_DSM version:_ 6.2.3-25426 Update 2

### Expected behavior
Tell us what should happen - Package should be available in the community area like it is for my other 5 Synology NAS boxes.  It's not visible in the list.  Other NAS boxes are RS814, RS815+, etc.. If this package hasn't been built for this Arch yet, would I request a new package?  Thank you,

### Actual behavior
Tell us what happens instead - Nano is missing from the list on this Synology Model

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
You can find nano in synocli-file package: https://synocommunity.com/package/synocli-file
