### ISSUE TITLE
[Package Request] PowerShell

### ISSUE THREAD

**Issue by janhsh** [SynoCommunity/spksrc#4076]
Name: PowerShell
Description: Microsoft PowerShell
Website: https://microsoft.com/powershell
Software documentation: https://docs.microsoft.com/powershell
Build/Installation documentation:  https://github.com/PowerShell/PowerShell
Source Code: https://github.com/PowerShell/PowerShell
License:  MIT license.

**Comment by ymartin59** [comment]
Related to #3892

**Comment by hgy59** [comment]
Build instructions for linux are found here:
https://github.com/PowerShell/PowerShell/blob/master/docs/building/linux.md

**Comment by leonpano2006** [comment]
that dosen't need dotnet 
follow to https://docs.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.2

with commands below

> # Download the powershell '.tar.gz' archive
> curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/powershell-7.2.1-linux-x64.tar.gz
> 
> # Create the target folder where powershell will be placed
> sudo mkdir -p /opt/microsoft/powershell/7
> 
> # Expand powershell to the target folder
> sudo tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
> 
> # Set execute permissions
> sudo chmod +x /opt/microsoft/powershell/7/pwsh
> 
> # Create the symbolic link that points to pwsh
> sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

**Comment by hgy59** [comment]
> that dosen't need dotnet follow to https://docs.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.2

@leonpano2006 please read the section **Dependencies** just above your installation extract.

> PowerShell builds portable binaries for all Linux distributions. But, .NET Core runtime requires different dependencies on different distributions, and PowerShell does too.

And in the **Imporatant** box
> ... Be sure to install any necessary dependencies. ...

So .net runtime is required to run `pwsh`. There exists no pwsh installation without .NET.

**Comment by hgy59** [comment]
closing due inactivity

**Comment by leonpano2006** [comment]
> closing due inactivity

Wow
I already forget this issue
