### ISSUE TITLE
Sabnzbd not available for DS220+ DSM 6.2.3-25426 Update 2

### ISSUE THREAD

**Issue by AaK1974** [SynoCommunity/spksrc#4082]
Could you please make Sabnzbd available for DS220+?

**Comment by BarettaNL** [comment]
When will there be an update about this issue? Would be great if SABNZBD, Radarr, Sonarr, Lidarr, Hass, and Mono are available. 

Thanks in advance!

**Comment by BarettaNL** [comment]
When can we expect a reply on this issue? Is there another way to get the package?

**Comment by JVlot** [comment]
Same for the DS920.
Package not available in Package Center after adding SynoCommunity.
Manual installation says: Not supported on Synology NAS or not compatible with current DSM version.
Is this a bug or did Synology block Sabnzbd

**Comment by BarettaNL** [comment]
> Same for the DS920.
> Package not available in Package Center after adding SynoCommunity.
> Manual installation says: Not supported on Synology NAS or not compatible with current DSM version.
> Is this a bug or did Synology block Sabnzbd

@JVlot seems we are the only ones having this problem. My hardware supplier told me because we own a 2020 model it can take a couple of weeks when the packages show up in package center. Till now I can’t find anything about this on the web.

**Comment by JVlot** [comment]
> > Same for the DS920.
> > Package not available in Package Center after adding SynoCommunity.
> > Manual installation says: Not supported on Synology NAS or not compatible with current DSM version.
> > Is this a bug or did Synology block Sabnzbd
> 
> @JVlot seems we are the only ones having this problem. My hardware supplier told me because we own a 2020 model it can take a couple of weeks when the packages show up in package center. Till now I can’t find anything about this on the web.

@BarettaNL We are not the only ones.
I just found that if you follow the arch  link from hgy59 you find several related issues about the 2020 models.
It seems the new models are using a different architecture.
They are working on a solution.
Just wait and see....

**Comment by ymartin59** [comment]
sabnzbd update has been published with python2.
