### ISSUE TITLE
Symlink for Midnight Commander not created during installation

### ISSUE THREAD

**Issue by HeylelTeomim** [SynoCommunity/spksrc#4083]
### Setup
_Package Name:_ 
SynoCLI Filetools

_Package Version:_ 
1.1.2

_NAS Model:_ 
DS3617xs

_NAS Architecture:_ 
x86

_DSM version:_ 
DSM 6.2.3-25426

### Expected behavior
Symlink for Midnight Commander should be created

### Actual behavior
Symlink for Midnight Commander is not created

### Steps to reproduce
_1._ Install package
_2._ SSH into NAS
_3._ Try to call mc,using 'mc'

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```
#### Remedy

Short term remedy until this is fixed (This is courtesy of one-eyed-king at synoforum.com):

Modify /var/packages/synocli-file/scripts/start-stop-status 

to this

`#!/bin/sh
SYNOPKG_PKGDEST=$(readlink /var/packages/synocli-file/target)
# fix missing file mc-utf8
if [ ! -e ${SYNOPKG_PKGDEST}/bin/mc-utf8 ];then
  pushd ${SYNOPKG_PKGDEST}/bin
  ln -s mc mc-utf8
  popd
fi
. $(dirname $0)/service-setup

case $1 in
    start)
        service_postinst
        exit 0
        ;;
    stop)
        service_postuninst
        exit 0
        ;;
    status)
        exit 0
        ;;
    log)
        exit 1
        ;;
    *)
        exit 1
        ;;
esac`

Execute with 'bash start-stop-status start'

From now on the symlinks will be created whenever the package is started and deleted when the package stops.

**Comment by hgy59** [comment]
@HeylelTeomim may it be, that you have installed an older mc standalone package before?

With the synocli-file package there is no mc-utf8 anymore (in the standalone mc package mc was a link to mc-utf8, i.e. it was the other way round).

**Comment by HeylelTeomim** [comment]
@hgy59 The NAS I am working on is one I just set up, so I don't think so. I went for the file tools since I wanted both Nano and MC.

**Comment by ymartin59** [comment]
I had both "mc" and "synocli-files" installed. After uninstalling "mc" and updating "synocli-files", "mc" link is OK

**Comment by HeylelTeomim** [comment]
I just uninstalled SynoCLI-files and reinstalled. Cannot run mc unless I assume root.

Cannot create /var/services/homes/heylel/.config/mc directory

user 'heylel' is part of administrator group.

**Comment by ymartin59** [comment]
@HeylelTeomim Have you enabled users home directory creation? https://www.synology.com/en-global/knowledgebase/DSM/help/DSM/AdminCenter/file_user_advanced

**Comment by HeylelTeomim** [comment]
@ymartin59 Yes, I had - but as I stated above, I disabled and re-enabled user homes and it now works.

Whether I did something wrong when setting that up, or permissions perhaps got refreshed when I disabled and re-enabled, I don't know. But the problem does seem directly linked to being able to write to user home.

**Comment by ymartin59** [comment]
There is a risk that `.config` was owned by root if you often run sudo there - as `Cannot create /var/services/homes/heylel/.config/mc directory` definitely sounds like permission trouble at file system level.
