### ISSUE TITLE
SSL library compilation for Transmission 3.0

### ISSUE THREAD

**Issue by terierul** [SynoCommunity/spksrc#4084]
Transmission 3.0 - seems in the last package for Synology the ssl library is not compiled so the https announce is not working
Some trackers are require this so for them connection is not working 
Is possible a new compilation with ssl included?

**Comment by ymartin59** [comment]
@hgy59 May you please help about it?

**Comment by hgy59** [comment]
There is still openssl linked with the transmission 3.00-17 spk.
The updated spk includes a fix for certificate validation that occurred with https sites. And it was reported to solve this (https://github.com/SynoCommunity/spksrc/issues/4032#issuecomment-657231679)

For further investigations the model of Diskstation and a sample torrent file would be useful.

**Comment by GertJanH** [comment]
I have the same problem with https trackers, trackers that use http working normal

i have a DS216play

![https tracker](https://user-images.githubusercontent.com/22355768/89107751-6750f180-d433-11ea-8ae9-e1100b569bde.png)

**Comment by hgy59** [comment]
Oh yes, I can reproduce.
The proplem is, that I have extracted the fix to a separate branch that is not yet merged (#4066)
