### ISSUE TITLE
[Package Request]  SABnzbd 2.3.9-41.spk and 3.0.0RC2.spk [Synology Architecture: rtd1296 (armv8)]

### ISSUE THREAD

**Issue by SPT212** [SynoCommunity/spksrc#4087]
Name: SABnzbd 2.3.9-41.spk and 3.0.0RC2.spk [Synology Architecture: rtd1296 (armv8)]
Description: SABnzbd makes Usenet as simple and streamlined as possible by automating everything we can. All you have to do is add an .nzb. SABnzbd takes over from there, where it will be automatically downloaded, verified, repaired, extracted and filed away with zero human interaction.
Website: http://sabnzbd.org
Software documentation: https://sabnzbd.org/downloads#
Build/Installation documentation: https://sabnzbd.org/wiki/installation/install-off-modules
Source Code: https://github.com/SynoCommunity/spksrc/tree/master/spk/sabnzbd/src
License: GPL

I do not have Docker functionality on my Synology NAS (DS118) so cannot create package myself. Any help from the community would be greatly appreciated. Thank you for your time, continued efforts, and consideration.

**Comment by ymartin59** [comment]
I have just published sabnzbd 2.3.9 and python 2.7.18 for your arch
