### ISSUE TITLE
Transmission v3.00-17 http error

### ISSUE THREAD

**Issue by TsuboiKlein** [SynoCommunity/spksrc#4088]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Transmission
_Package Version:_ 3.00-17

_NAS Model:_ DS718+
_NAS Architecture:_ apollolake (x64)
_DSM version:_ 6.2.3-25426 Update 2

### Expected behavior
In the v2.94 transmission perfectly work with download URLs but the updated v3.00 version got an error.
(Magnet links work perfectly on v3.00)

### Actual behavior
When I try to insert a download URL, an error message comes up.
The error: "gotMetadataFromURL: http error 0:No Response".

### Steps to reproduce
_1._  Try to install the package manually
_2._  I reinstall the 2.94 version

#### Package log
[transmission.log](https://github.com/SynoCommunity/spksrc/files/5010181/transmission.log)

#### Other logs
[transmission_install.log](https://github.com/SynoCommunity/spksrc/files/5010168/transmission_install.log)

**Comment by ymartin59** [comment]
Fix published as revision 18. Please confirm by closing this issue
