### ISSUE TITLE
Python v2.7.14-19 is missing for ArmadaXp architecture

### ISSUE THREAD

**Issue by BenjV** [SynoCommunity/spksrc#4090]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Python 2.7
_Package Version: v2.7.14-19

_NAS Model:_ DS414
_NAS Architecture: ArmadaXp
_DSM version: DSM 6.2.3-25426 Update 2

### Expected behavior
Expected the latest Python 2 Version to be also available for this DS414

### Actual behavior
Latest available version for ArmadaXP is Python 2.7.13-16

**Comment by ymartin59** [comment]
OK. Noticed. I will publish 2.7.18 and related packages all at the same time soon.

**Comment by ymartin59** [comment]
Python 2.7.18 and related applications have been published - including for armadaxp https://synocommunity.com/package/python
