### ISSUE TITLE
SynoCli DiskTools davfs2 missing

### ISSUE THREAD

**Issue by cwuensch** [SynoCommunity/spksrc#4098]
After installing SynoCli DiskTools on my DS418 (rtd1296 chipset), all tools are present, but davfs2 (which was my main reason for installing the package) is missing.
Can you fix this?
Or can I get a compiled version of davfs2 from anywhere else?

**Comment by ymartin59** [comment]
May you please provide commands you have invoked and failed to connect? Any message or error output is also interesting to notice here.

**Comment by cwuensch** [comment]
Sure.
I installed SynoCli DiskTools via the DSM Packet Manager. I did not use a specific "command" for that. I just clicked on "Install".
When I log in via SSH afterwards, I can access tools like "testdisk", but not "davfs2".
So, the command "davfs2" does not work. This is, as written before, because the binary has not been installed.

**Comment by ymartin59** [comment]
As it requires root, you will find commands at `/usr/local/sbin/mount.davfs` and `/usr/local/sbin/umount.davfs`
