### ISSUE TITLE
[Package Request] SABnzbd 3.0.0

### ISSUE THREAD

**Issue by sirjaymz** [SynoCommunity/spksrc#4099]
Name: SABnzbd 3.0.0
Description: SABnzbd makes Usenet as simple and streamlined as possible by automating everything we can. All you have to do is add an .nzb. SABnzbd takes over from there, where it will be automatically downloaded, verified, repaired, extracted and filed away with zero human interaction.
Website: http://sabnzbd.org
Software documentation: https://sabnzbd.org/downloads#
Build/Installation documentation: https://sabnzbd.org/wiki/installation/install-off-modules
Source Code: https://github.com/SynoCommunity/spksrc/tree/master/spk/sabnzbd/src
License: GPL

**Comment by sam43434** [comment]
its waiting to be merged https://github.com/SynoCommunity/spksrc/pull/4035

**Comment by ymartin59** [comment]
Update has been published: https://synocommunity.com/package/sabnzbd
