### ISSUE TITLE
Transmission 3.0 causes all tracker to fail to connect

### ISSUE THREAD

**Issue by yegle** [SynoCommunity/spksrc#4101]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Transmission
_Package Version:_ 3.0

_NAS Model:_ DS1515+
_NAS Architecture:_ x86_64 (?)
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
Tracker should connect successfully, as it was with the old 2.9.X version.

### Actual behavior
The status of tracker is just "Could not connect to tracker" without other additional information.

### Steps to reproduce
_1._ Update to 3.0
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
[2020-08-03 14:31:32.093] XXXXX Could not connect to tracker (announcer.c:1085)
[2020-08-03 14:31:32.093] XXXXX Retrying announce in 3604 seconds. (announcer.c:1094)
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
```

Note: running a curl on the NAS to the tracker announce address returns expected result:
```
$ curl -v https://tracker.xxxxx/announce.php                                           
...
< HTTP/2 200 
```

**Comment by yegle** [comment]
Hmm, if I modify the tracker from `https://` to `http://`, then it was able to connect to the server and get list of peers.

Looks like this is due to SSL certificate issue?

**Comment by yegle** [comment]
Yes, this is indeed lileky caused by certificate issue (lack of bundled certificate?)

```
/volume1/@appstore/transmission/bin
$ ./curl -v https://tracker.XXXXX/announce.php
*   Trying XXXXX:443...
* Connected to tracker.XXXXX (XXXXX) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by yegle** [comment]
I noticed the changelog of git (also from SynoCommunity repo) contains the following:

```
Fixed configuration of CA certificates (use DSM ca-certificates that hopefully will be updated by Synology
```

Does this mean Transmission also need some special configuration?

**Comment by yegle** [comment]
@hgy59 to raise awareness :-)

**Comment by yegle** [comment]
Workaround:

Edit `/var/packages/transmission/scripts/service-setup` and add the following line anywhere in this file:

```
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
```

This file will likely be overwritten the next time this packge is updated, hopefully by that time the SSL issue is fixed.

**Comment by listenfree** [comment]
update to transmission 3.0 -18 still can not support TLS 1.3, only under tls 1.2

**Comment by vjayer** [comment]
I've updated to v3.00-17 (the latest available to me) and aside from the tracker connection issue, which I also get and see in the log, I cannot add torrent via urls anymore. Opening via url always returns:

`Error adding "https://....": gotMetadataFromURL: http error 0: No Response`

is this the same issue?

**Comment by ymartin59** [comment]
@hgy59 May you please help about it?

**Comment by yegle** [comment]
@vjayer yes likely the same issue. The workaround in https://github.com/SynoCommunity/spksrc/issues/4101#issuecomment-668264688 should work.

@ymartin59 it would be faster to just use the same workaround.

**Comment by joaomvfsantos** [comment]
When I upgrade to 3.00-18 I can't access the web GUI anymore over the tradicional http://ip:9091 address. Could it be related to the issues mentioned?

**Comment by przemek808** [comment]
I have this issue, too.
Unfortunately the workaround did not work for me.
Any further ideas? Could you @yegle help me to find the issue?

**Comment by yegle** [comment]
@przemek808 can you verify using the command in https://github.com/SynoCommunity/spksrc/issues/4101#issuecomment-668255539 that this is the same issue? AFAIKT this bug should've been fixed.

**Comment by przemek808** [comment]
@yegle indeed it is not exact the same:
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.

**Comment by przemek808** [comment]
@yegle if you confirm that this is another issue I would open a new ticket.

**Comment by yegle** [comment]
Yes I think it's a different issue.
