### ISSUE TITLE
New binaries for BorgBackup

### ISSUE THREAD

**Issue by MatejKovacic** [SynoCommunity/spksrc#4102]
BorgBackup in Syno repositories is 1.1.7, however, current version of BorgBackup is 1.1.13. Since older versions had some serious vulnerabilities - is it possible to update Borg package?

**Comment by MatejKovacic** [comment]
Workaround:
```
wget https://github.com/borgbackup/borg/releases/download/1.1.13/borg-linux64
chmod +x borg-linux64
mv borg-linux64 borg
sudo scp borg /usr/local/bin/
```
And then:
```
borg -V
borg 1.1.13
```

**Comment by ymartin59** [comment]
Update has been published

**Comment by fuelflo** [comment]
Hey,

is there any chance to update the package to borg 1.1.16? Borg 1.1.16 includes new --noacls and --noxattrs options which makes it much easier to open and restore borg backups to non synology machines.

**Comment by auanasgheps** [comment]
+1. Please update borg and borgmatic packages!
