### ISSUE TITLE
Deluge 2.03 not start.(

### ISSUE THREAD

**Issue by hab-git** [SynoCommunity/spksrc#4106]
Deluge 2.03 not start.(

Deluge v2.0.3-11
6.1 x86_64

Synology DS418play
x64
6.2.3-25426 Update 2

**Comment by vw-joker** [comment]
Same for me

Deluge v2.0.3-11
Synology DS918+
DSM Version - 6.2.3-25426 Update 2

**Comment by ymartin59** [comment]
Check your Python 2.7 package version. Please provide screenshots and log details.

**Comment by hab-git** [comment]
![Screenshot-22](https://user-images.githubusercontent.com/69309875/89544370-b66b9d80-d80a-11ea-9192-2531abf0ea90.jpg)
2.7.18-23

**Comment by vw-joker** [comment]
exactly the same as you have posted
Developer Safihre, v 2.7.18-23

**Comment by vw-joker** [comment]
Which logs please?

**Comment by hab-git** [comment]
I already removed 2.03 (

**Comment by ymartin59** [comment]
At least `deluge_install.log` but all .log may be interesting

**Comment by hab-git** [comment]
deluge_install.log
[deluge_install.log](https://github.com/SynoCommunity/spksrc/files/5040079/deluge_install.log)

**Comment by almawdah** [comment]
I update deluge to 2.0.3-11 and it stopped I can't run it again , I want to go back to version 1.3.15-9 , with knowing I update also python to Version 2.7.18-23

there is any solution  without losing all seed torrent files in deluge

**Comment by almawdah** [comment]
how can I backup deluge torrent files and setting from synology ?
because I wont to downgrade back version of deluge and python , I must install them

**Comment by t0dor** [comment]
same problem here, is it possible to go back to the previous version, and if so - how?

**Comment by cesarfd** [comment]
Same problem with the same Python and Deluge versions (updated at once). Only the deluge web ui works.

**Comment by hab-git** [comment]
Only the deluge web ui works.( 
This is not necessary. (

**Comment by almawdah** [comment]
this is my log files:
[deluge_install.log](https://github.com/SynoCommunity/spksrc/files/5042558/deluge_install.log)
[deluged.log](https://github.com/SynoCommunity/spksrc/files/5042559/deluged.log)
[deluge-web.log](https://github.com/SynoCommunity/spksrc/files/5042560/deluge-web.log)
[deluge.log](https://github.com/SynoCommunity/spksrc/files/5042561/deluge.log)

**Comment by ajoakim** [comment]
I am getting the folloing error when I try to start the script!!

admin@XXXXX:/var/packages/deluge/scripts$ ./start-stop-status start
./service-setup: line 6: [: : integer expression expected
Starting  ...
env: /env/bin/deluged: No such file or directory
env: /env/bin/deluge-web: No such file or directory
admin@XXXXX:/var/packages/deluge/scripts$

**Comment by ymartin59** [comment]
Bad idea to expect to start service from command line... Package Center is the right place to operate.
Or else there is some magic to spell: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#how-to-query-package-status-or-start-it-from-command-line

**Comment by ymartin59** [comment]
@ajoakim Installation succeeded but service complains about `Couldn't listen on any:58846: [Errno 98] Address already in use.
` in `deluged.log`. No idea what it may come from, I would propose to reboot your DSM in case it may fix trouble.

**Comment by almawdah** [comment]
> Bad idea to expect to start service from command line... Package Center is the right place to operate.
> 
> Or else there is some magic to spell: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#how-to-query-package-status-or-start-it-from-command-line

Is there any chance to fix this problem?

**Comment by ajoakim** [comment]
I uninstalled Deluge, reinstalled, restarted the NAS still doesn't want to start. where is the start logs located?

**Comment by limnick** [comment]
just did the same paired upgrade of python and deluge. Now seeing the same issue(s) described above. `deluge-web` starts fine, `deluged` fails to start. Happy to provide any logs or try changes on my system as necessary

**Comment by Herrnobiz** [comment]
Same problem here, 2.03 does not start, so i reverted back to previous version 1.3.15-9 and it's running again

**Comment by almawdah** [comment]
> Same problem here, 2.03 does not start, so i reverted back to previous version 1.3.15-9 and it's running again

Me to I reverted back python & deluge and it run normally

**Comment by PuMa2006** [comment]
Same here. Reverted back deluge (and <10 torrent files, lucky me). No need to revert python. On the deluge forum there is info that deluge 2.0.3 need Python 3 (not Python 2). Patiently waiting while user here try this (don't wanna revert my deluge again)

**Comment by t0dor** [comment]
@PuMa2006 how did u revert deluge back? I can't seem to find the older version anymore..

**Comment by PuMa2006** [comment]
@t0dor You can find it @ official Syno repo for your architecture here: https://synocommunity.com/package/deluge

**Comment by almawdah** [comment]
> @t0dor You can find it @ official Syno repo for your architecture here: https://synocommunity.com/package/deluge
> 
> (at first you need to delete your deluge 2.0.3 and reboot NAS, then manually install older version of deluge)

will that good news about fix that problem 
waiting any user have tested python3 with deluge 2.0.3

**Comment by almawdah** [comment]
> Same here. Reverted back deluge (and <10 torrent files, lucky me). No need to revert python. On the deluge forum there is info that deluge 2.0.3 need Python 3 (not Python 2). Patiently waiting while user here try this (don't wanna revert my deluge again)

will that good news about fix that problem
waiting any user have tested python3 with deluge 2.0.3

**Comment by almawdah** [comment]
there is info that you can install python3 with python2.7 and it will support any python version of plugin egg
 link : https://deluge.readthedocs.io/en/latest/devguide/how-to/update-1.3-plugin.html

any one still in deluge 2.0.3 if  he can install python3 and test it with deluge

**Comment by ymartin59** [comment]
@hgy59 May you please help investigate this trouble with deluged daemon: `Couldn't listen on any:58846: [Errno 98] Address already in use`?

**Comment by sjw211** [comment]
Same here on Synology DS412+.
I updated to 2.0.3-11 and it stopped working, same as OP.
I installed Python 3 and it still didn't work. Rebooted - the same.
I then tried to uninstall Python 2.7 but it said Deluge was a Dependency of it and that needed uninstalling first.
I uninstalled Deluge and then Python 2.7.
I then installed Deluge again - and it gives a popup that Python is needed - and installs V 2.7 again! Why, if it needs V3? And I have V3 installed.
Anyway, installed version 2.0.3-11 again and it goes through the options of watch folder, download folder etc. but it won't start. :(
Why does the update appear (and rely on Python 2.7) if it doesn't work?

**Comment by ymartin59** [comment]
Deluge 2 does not need Python 3. @hgy59 has packaged it with python 2.7.18

**Comment by PuMa2006** [comment]
@ymartin59 idk with what he packaged it but it simply don't work. so...

**Comment by ymartin59** [comment]
@PuMa2006 That is why I have flagged this issue as a bug and request @hgy59 for help... Any relevant diagnostic is welcome.

**Comment by scottgshin** [comment]
I tried installing Python3, but no luck. Still cannot start the daemon for deluge. How does one backup a non working package and revert back to a working package?

**Comment by almawdah** [comment]
> I tried installing Python3, but no luck. Still cannot start the daemon for deluge. How does one backup a non working package and revert back to a working package?

You need to only to backup ur torrent files with core.conf

**Comment by ymartin59** [comment]
First elements, from `deluge_installer.log`: Warning: libtorrent (libtorrent-rasterbar) not found: Deluge 2.0.3 requires libtorrent >= 1.1.2.0
which is confirm when trying to start deamon alone (not to reproduce, may break your install):
```
bash-4.3# /var/packages/deluge/target/env/bin/deluged --config /var/packages/deluge/target/var
bash-4.3# Traceback (most recent call last):
  File "/var/packages/deluge/target/env/bin/deluged", line 11, in <module>
    load_entry_point('deluge==2.0.3', 'console_scripts', 'deluged')()
  File "/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-2.0.3-py2.7.egg/deluge/core/daemon_entry.py", line 90, in start_daemon
    from deluge.core.daemon import is_daemon_running
  File "/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-2.0.3-py2.7.egg/deluge/core/daemon.py", line 22, in <module>
    from deluge.core.core import Core
  File "/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-2.0.3-py2.7.egg/deluge/core/core.py", line 28, in <module>
    from deluge._libtorrent import LT_VERSION, lt
  File "/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-2.0.3-py2.7.egg/deluge/_libtorrent.py", line 32, in <module>
    'Deluge %s requires libtorrent >= %s' % (get_version(), REQUIRED_VERSION)
ImportError: Deluge 2.0.3 requires libtorrent >= 1.1.2.0
```

**Comment by ymartin59** [comment]
@hgy59 I am updating libtorrent and extend Boost requirements, a PR will come soon

**Comment by sjw211** [comment]
> 
> 
> Deluge 2 does not need Python 3. @hgy59 has packaged it with python 2.7.18

Sorry, I was going from a reply from the deluge-torrent site:
"Deluge 2 uses Python 3 and GTK 3, not Python 2 and GTK 2 like Deluge 1.3."
and what I thought to be the [official V2 Release Notes](https://deluge.readthedocs.io/en/latest/releases/2.0.html): - "Migrated to Python 3 with minimal support retained for Python 2.7."

**Comment by ymartin59** [comment]
I guess you have read https://synocommunity.com/ - I quote for being sure "Packages are provided for free and made by developers on their free time."
Here there are many to demand but only few to contribute. We are not working for Synology and are not paid for this work (yes, it is also hard work), sometimes it fail and as for many "free" things, patience is the best attitude.

**Comment by ymartin59** [comment]
But you are lucky, build of patch and upload to repository are just over, so I can go back to sleep.

**Comment by almawdah** [comment]
Is that mean you fix the bug 
We can use deluge 2.0.3 ?

**Comment by ymartin59** [comment]
The failing daemon startup has been fixed. I am not a Deluge user, so I cannot confirm all features.

**Comment by hab-git** [comment]
Thank you.

**Comment by almawdah** [comment]
> The failing daemon startup has been fixed. I am not a Deluge user, so I cannot confirm all features.

Thanks

**Comment by sjw211** [comment]
Thanks for your efforts!!!
Confirmed working @almawdah ?

**Comment by vasamaximov** [comment]
Same here: Deluge won't start after upgrade with the message in the  /var/log/packages/deluge.log
"ImportError: Deluge 2.0.3 requires libtorrent >= 1.1.2.0"

Is it possible to upgrade libtorrent?

My setup:
* DS214
* MARVELL Armada XP MV78230
* DSM 6.2.3-25426 Update 2
* Python 2.7.12 (default, May  7 2020, 04:32:37)

**Comment by sjw211** [comment]
When did you do the update?  My understanding (not tested yet) is this was fixed a few hours back.
If you upgraded just now then there is an issue still? I hope your update was before this..

**Comment by almawdah** [comment]
> Thanks for your efforts!!!
> 
> Confirmed working @almawdah ? 

Actually I reverted back to old deluge version 1.3 , Im working switch to transmission 

I think deluge is out of date.

**Comment by vasamaximov** [comment]
> When did you do the update? My understanding (not tested yet) is this was fixed a few hours back.

Ah, yes! Upgraded Deluge a day ago, and now the update banner popped up in the Package center asking to upgrade Deluge to 
2.0.3-12. (the previous version was 2.0.3-11). 

Upgraded, everything went well, Deluge starts now with no errors. Thank you!

**Comment by almawdah** [comment]
> > When did you do the update? My understanding (not tested yet) is this was fixed a few hours back.
> 
> 
> 
> Ah, yes! Upgraded Deluge a day ago, and now the update banner popped up in the Package center asking to upgrade Deluge to 
> 
> 2.0.3-12. (the previous version was 2.0.3-11). 
> 
> 
> 
> Upgraded, everything went well, Deluge starts now with no errors. Thank you!

Good to hear that
I hope there is no moro issue with new version

**Comment by sjw211** [comment]
I reverted back to the 1.3.15 release and it was fine.
It still reported the latest version as the 2.0.3-11.  I stopped and started Deluge and then rebooted the NAS.
Still only -11 available.  I don't know why - or if there is a way to force another check.
I manually updated to -12 from [here ](https://synocommunity.com/package/deluge)and all seems fine now.
Many thanks for your work guys.

**Comment by sjw211** [comment]
Usually, when I add a .torrennt file to a folder it is automatically downloaded.   While I don't remember doing it, maybe this is a plugin - AutoAdd?
Is that behaviour added through this plugin or is the 'watch folder' standard functionality now?
.torrent files are not auto downloading for me - and the plugin can't be ticked.  It adds the tick briefly and then removes it.

**Comment by almawdah** [comment]
> Usually, when I add a .torrennt file to a folder it is automatically downloaded.   While I don't remember doing it, maybe this is a plugin - AutoAdd?
> 
> Is that behaviour added through this plugin or is the 'watch folder' standard functionality now?
> 
> .torrent files are not auto downloading for me - and the plugin can't be ticked.  It adds the tick briefly and then removes it.
> 
> 
> 
> EDIT: It looks like this is supposed to be standard functionality now ( https://github.com/gazpachoking/deluge-autoadd-plugin/blob/master/README.md )
> 
> It no longer works for me.  The .torrent file is still there (would usually be removed after the download starts).  They can be added manually though.

Yes it's standard functionality you can assign Folder to be watch folder to download torrent files

**Comment by sjw211** [comment]
So it still works for you (Watch folder auto download)?
Where do you assign the folder(s) to be watched?

**Comment by sjw211** [comment]
I think I'll be rolling back to 1.3, it works well enough.
As soon as I switch my Socks 5 with Auth on they all gradually stop seeding.
![Annotation 2020-08-09 143434](https://user-images.githubusercontent.com/69398550/89733473-a8f22580-da4d-11ea-8033-57eccd8ed8ad.jpg)
If I toggle the socks5 off I need to deselect 'Force Use of Proxy' box (this is new - presumably to stop connections if the sockks5 connection is dropped).

When it happens, strangely, they all go to 0(222) for seeds and peers.
![222](https://user-images.githubusercontent.com/69398550/89734133-1738e700-da52-11ea-8170-0c3f329f7b8d.jpg)
I've never had proxy issues before but tried a few servers just in case.

**Comment by ymartin59** [comment]
> So it still works for you (Watch folder auto download)?
> Where do you assign the folder(s) to be watched?

@sjw211 Deluge 2.0.3-12 should appear in Package Center "after a while", no idea how long it may wait for refresh.

For a fresh install, wizard propose to set a "watch directory" location (a DSM volume folder) but after an upgrade, it is required to enable "AutoAdd" plugin and set it up manually.

Notice I will no longer reply to this closed issue. Please open a new one if needed.

**Comment by scottgshin** [comment]
The update that sjw211 linked to works like a charm. Thank you to ymartin59 for the fix.

**Comment by marikgl** [comment]
Hi All,

Have the same problem with starting Deluge 2.0.3. using Pi with lite OS
Can you please explain how to fix it ( I'm noob in this )

Regards,
