### ISSUE TITLE
Tvheadend on gemini lake architecture?  DS920+ or 20 series

### ISSUE THREAD

**Issue by Geekllem** [SynoCommunity/spksrc#4109]
Hi,

can I use this package:

tvheadend.v20.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-grantley-purley-kvmx64-x86-x86_64].spk

with my DS920+ (gemini lake architecture)?

or are you going to release a new version for gemini lake architecture?

Thank you very much...

### Setup
_Package Name:_   Tvheadend 
_Package Version:_ 4.3.x

_NAS Model:_  DS920+
_NAS Architecture:_ Gemini Lake
_DSM version:_  6.2.3-25426-2

**Comment by th0ma7** [comment]
it's on its way.  Leave me a day or two and it should be available.

**Comment by Friedhofsblond** [comment]
@th0ma7 
hello vincent,
that would be great.
Many users from the German synology community are waiting for this package.
TVmosaic has died, now many are switching to tvheadend.
I think the ffmeg package has to be updated?
Greetings and everyone stays healthy!

Arne ;)

**Comment by th0ma7** [comment]
Package is now available, cheers!

**Comment by Friedhofsblond** [comment]
Hello my friend,
thank you for your hard work. 😉
I installed the packages that evening.
So far I have no problems - everything works - for now.


Thank you so much

mit freundlichem Gruß
A.Matysik

///vergab.zukunft.geschirr
________________________________
Von: Vincent Fortier <notifications@github.com>
Gesendet: Montag, 10. August 2020 01:40
An: SynoCommunity/spksrc <spksrc@noreply.github.com>
Cc: Friedhofsblond <arnematysik@live.de>; Comment <comment@noreply.github.com>
Betreff: Re: [SynoCommunity/spksrc] Tvheadend on gemini lake architecture? DS920+ or 20 series (#4109)


Package is now available, cheers!
