### ISSUE TITLE
DS211 - Installed but getting a 404 Not Found error.

### ISSUE THREAD

**Issue by sproutlegal** [SynoCommunity/spksrc#4111]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Home Assistant Beta
_Package Version:_ 0.82.1-2

_NAS Model:_ DS211
_NAS Architecture:_ ARMV5
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
Clicking on the link after install should take me to the Home Assistant Web UI

### Actual behavior
I receive a message "404: Not Found"

### Steps to reproduce
_1._ Install Home Assistant Beta 
_2._ Click on the URL in the Package Page once installed.
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
@sproutlega have you tried the current version v0.114.2-7 ❓
