### ISSUE TITLE
Deluge 2.03-12 start. But after stop - start deluge preferences reset. (

### ISSUE THREAD

**Issue by hab-git** [SynoCommunity/spksrc#4112]
Deluge v2.0.3-12
6.1 x86_64

Synology DS418play
x64
6.2.3-25426 Update 2

Deluge 2.03-12 start. But after stop - start deluge preferences reset. (_For new Package Requests, see the guidelines_

**Comment by ymartin59** [comment]
@hgy59 May you help about it please?

**Comment by ymartin59** [comment]
As an immediate work-around, I recommend to save as a copy content of /var/packages/deluge/target/var where configuration lies.

**Comment by hab-git** [comment]
And in general it does not remember anything (

**Comment by ymartin59** [comment]
I am investigating. AutoAdd plugin https://dev.deluge-torrent.org/wiki/Plugins/AutoAdd is used to configure watch_dir

**Comment by ymartin59** [comment]
@hgy59 Notice I do not find folder `PYTHON_EGG_CACHE=${SYNOPKG_PKGDEST}/env/cache` on system... I wonder if it is of any use as `.pyc` files are written in `env/lib/python2.7`

**Comment by ymartin59** [comment]
@hab-git I have just tested with "Downloads Options" in "Preferences" to try to reproduce but stop/start maintains these options.
What are concerned options you noticed not to be persisted?
May you please provide output of `ls -lrta /var/packages/deluge/target/var/` from SSH session with admin privileged account (refer to for help with SSH: https://github.com/SynoCommunity/spksrc/wiki/FAQ-ssh)

**Comment by hab-git** [comment]
After the upgrade from 1.3.15-9 to 2.0.3-12, the settings were saved!)

**Comment by hab-git** [comment]
And also the Windows-client Deluge 2.03 works. Good job!)
