### ISSUE TITLE
Z shell not aviable.

### ISSUE THREAD

**Issue by xnxin** [SynoCommunity/spksrc#4117]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Z shell
_Package Version: 5.8-10 

_NAS Model: 720+
_NAS Architecture: x86_64 
_DSM version: 6.2.3-25426 Update 2

### Expected behavior
Not aviable

### Actual behavior
I can search it, and install

**Comment by ymartin59** [comment]
Hello @agross 
May you please help and submit a PR for zsh update?

**Comment by agross** [comment]
Hi @ymartin59,

I'm not sure what the problem is. Doesn't the build system ensure packages are compiled for all architectures?

**Comment by xnxin** [comment]
never mind，I install zsh with cmd opkg.

**Comment by ymartin59** [comment]
@agross In fact I take the opportunity to update application version when a new architecture requires to publish again...

**Comment by agross** [comment]
@ymartin59 The latest version is still 5.8 (as in #3887).  I still don't understand what you want me to do. :-)

**Comment by ymartin59** [comment]
@agross Sorry... I should have checked first... Nothing for you to do so.

**Comment by JayXon** [comment]
The issue is zsh is listed on the website, but doesn't show up in package center (this is on DS920+)
![image](https://user-images.githubusercontent.com/1552641/100530160-4c08af80-31a3-11eb-884b-b1ba99e61b22.png)
