### ISSUE TITLE
Radarr fails due to missing write permission that isn't actually missing

### ISSUE THREAD

**Issue by gramster** [SynoCommunity/spksrc#4118]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_  Radarr
_Package Version:_ 20190320-8

_NAS Model:_  DMS1517+
_NAS Architecture:_ Intel
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
I should be able to add a movie location folder.

### Actual behavior
I explicitly added R/W permission to the folder for the user sc-radarr (which I thought would not be needed as sc-download group has this permission).
<img width="861" alt="Screen Shot 2020-08-10 at 9 28 36 PM" src="https://user-images.githubusercontent.com/2762632/89857273-7aa93e80-db50-11ea-82c8-fc8b9c82a273.png">

<img width="853" alt="Screen Shot 2020-08-10 at 9 26 49 PM" src="https://user-images.githubusercontent.com/2762632/89857184-40d83800-db50-11ea-95d7-f5c2570f0572.png">

However, I get the error:

<img width="716" alt="Screen Shot 2020-08-10 at 9 25 01 PM" src="https://user-images.githubusercontent.com/2762632/89857125-0e2e3f80-db50-11ea-9891-d920be7327f9.png">

### Steps to reproduce
_1._ Install package
_2._ Set permissions as shown above
_3._ Restart package
_4._ Try to add the folder

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
This can be explained if you created the folder "Movies" before you had set the write permission for the group "sc-download" to the shared folder "video".

The only other explanation is that Radarr has added and explicite test to see if sc-radarr has write permissions on that folder.
In that case they broke the complete system of using group permissions.

Permissions to subfolders and files are granted the moment you create them and they inherit them from the parent folder.

You can check the actual permission in File Station.
Select the folder video/Movies
Right click and choose properties
Select permission
Choose Advanced Options and the permission inspector.
In the field "User or group" select sc-download

Now you can see the actual permissions of the group "sc-download" for this folder.

**Comment by gramster** [comment]
I have no right click action; right click brings up a menu from Chrome, not File Station. I can get to a Properties pane via left clicks and the menus, but that does not have 'Advanced Options'. The closest it has is:

<img width="751" alt="Screen Shot 2020-08-11 at 7 50 11 AM" src="https://user-images.githubusercontent.com/2762632/89912435-693f5100-dba7-11ea-8571-8ad6dcd83e66.png">

and I can select the checkbox to apply to subfolders and apply that, but it doesn't fix the problem.

**Comment by BenjV** [comment]
Ok, you have an shared folder created with an older DSM version.
Go to control panel, select the folder, choose the tab action and if it is not "greyed out" you should choose "Convert To Windows ACL"

As of DSM 6 the packages from the SynoCommunity are making use of Acl's so the shared folder must be able to use Acl's.
This is as of DSM 6 also the default when DSM creates a new shared folder.

**Comment by gramster** [comment]
Thank you! That worked. Interestingly the video folder seemed to be the
only one with that issue.

**Comment by BenjV** [comment]
Those shared folders must be created bye DSM 5 and the video folder is created when you install VideoStation.
