### ISSUE TITLE
Domoticz upgrade from 4.0.10717-8 to 4.0.9700-8?

### ISSUE THREAD

**Issue by Sven79** [SynoCommunity/spksrc#4124]
### Setup
_Package Name:_ Domoticz
_Package Version:_ 4.0.10717-8

_NAS Model:_ Synology DS216+
_NAS Architecture:_ 
_DSM version:_ DSM 6.2.3-25426 Update 2

### Actual behavior
I am currently running Domoticz 4.0.10717-8. (installed from http://www.jadahl.com/)
DSM Package center informed me to update the package to 4.0.9700-8, which is an older version. I would have expected an update to a 2020-version and not a downgrade?
(edit: newer version v2020.1.11804-8 is available from jadahl)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/31131918/90130548-ed8e0180-dd6a-11ea-8723-4a72b54eb268.png)

**Comment by BenjV** [comment]
This is not a SynCommunity package.
So you should ask Jahdal or ask it here:
https://www.domoticz.com/forum/viewtopic.php?f=47&t=7087&sid=12bd13c1eb0d680faa7ec36dc9a10ca1&start=540#top

**Comment by Sven79** [comment]
Tnx for your reply.
Yes, I know, but somehow it is seen as a SynoCommunity package; that is what is strange to me.
I cannot recall that I installed Domoticz through SynoCommunity; I'm pretty sure I installed it from Jahdal. But somehow package center detects it is installed and links it to Synocommunity...

**Comment by BenjV** [comment]
There is also a Domoticz package from the SynoCommunity and the package you have is made by Diaoul and not by Jahdal.
So you must have installed is from the SynoCommunity.

If you add this package center to your Nas you can install the latest package from Jahdal.

> http://www.jadahl.com/domoticz_stable_6.2_python/

or if you don't want python extensions

> http://www.jadahl.com/domoticz_stable_6.2/

**Comment by bassduh** [comment]
I am having the same issue here.
200% sure I had installed it via Jadahl's repository.

Output of:
`head -n 10 /var/packages/domoticz/INFO`

`package="domoticz"`
`dsmappname="com.synocommunity.domoticz"`
`thirdparty="yes"`
`version="4.0.10717-8"`
`description="Domoticz Home Automation System. This version includes OpenZwave and USB drivers.If you like and use my `domoticz package, you might consider a donation with paypal. https://www.paypal.me/jumbotroll"

`arch="apollolake"`
`maintainer="Domoticz"`
`maintainer_url="http://www.jadahl.com/"`
`distributor="Jadahl"`

So it seems Jadahl is using the same `dsmappname` as Synocommunity.

**Comment by BenjV** [comment]
That is correct, the SynoCommunity package is an older version of the Jahdal package.
If you add Jahdal to your package sources as I wrote before, then it will find the version from jahdal

**Comment by bassduh** [comment]
I have installed the Domoticz package from Jadahl's repository:

![image](https://user-images.githubusercontent.com/16839376/92334141-8f172300-f08b-11ea-9d94-131afbe1e048.png)

I guess this all happens because 4.9600-8 is higher 4.0(.10717-8), Jadahl's version should have been 4.10717-8.

**Comment by BenjV** [comment]
No you have an old Jahdahl version.

Jahdal creates a new repositary for every new major version.
Het has repositarries for 4.1, 2020.1 and 2020.2.

The latest version from Jahdal is 2020.2.1234-8

Don't ask me why he is doing this and if upgrading is possible, I just don't know.
You have to ask him, drop a question here.
https://www.domoticz.com/forum/viewtopic.php?f=47&t=7087
