### ISSUE TITLE
[Package Request] fd-find (fd)

### ISSUE THREAD

**Issue by acherunilam** [SynoCommunity/spksrc#4127]
Name: fd-find (fd)
Description: fd is a simple, fast and user-friendly alternative to find
Website: https://github.com/sharkdp/fd
Software documentation: https://github.com/sharkdp/fd#command-line-options
Build/Installation documentation: https://github.com/sharkdp/fd#development
Source Code: https://github.com/sharkdp/fd
License: MIT, Apache 2.0

It's like a modern-day find but much much faster, [here](https://github.com/sharkdp/fd#benchmark) are the benchmarks. It's written in Rust.

![Demo](https://github.com/sharkdp/fd/raw/master/doc/screencast.svg)

**Comment by ymartin59** [comment]
May we relevant to be packaged into `synocli-files`
