### ISSUE TITLE
[Package Request] fzf

### ISSUE THREAD

**Issue by acherunilam** [SynoCommunity/spksrc#4128]
Name: fzf
Description: fzf is a general-purpose command-line fuzzy finder
Website: https://github.com/junegunn/fzf
Software documentation: https://github.com/junegunn/fzf#table-of-contents
Build/Installation documentation: https://github.com/junegunn/fzf/blob/master/BUILD.md
Source Code: https://github.com/junegunn/fzf
License: MIT

It's an interactive Unix filter for command-line that can be used with any list; files, command history, processes, hostnames, bookmarks, git commits, etc. It's written in Go.

Demo: https://www.youtube.com/watch?v=qgG5Jhi_Els

**Comment by ymartin59** [comment]
May we relevant to be packaged into `synocli-files`
