### ISSUE TITLE
Transmission service fails to start since upgrading from 2.94 to 3.00

### ISSUE THREAD

**Issue by yitzhaq** [SynoCommunity/spksrc#4131]
### Setup
_Package Name:_ Transmission
_Package Version:_ 3.00-18

_NAS Model:_ DS1819+
_NAS Architecture:_ denverton
_DSM version:_ DSM 6.2.3-25426 Update 2
--

### Expected behavior
Service should start.

### Actual behavior
Service consistently does not start. Worked fine with 2.94, failed after upgrade to 3.00, and downgrading is not possible.
Error message from DSM "Failed to run the package service." Other packages still work fine, and I'm unsure how to debug.

### Steps to reproduce
_1._ Upgrade 2.94 to 3.00
_2._ Click Run
_3._ Watch it fail to start

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
No entries are logged, since the service fails before the package is able to start.
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
2020-08-14T20:05:47+02:00 nasse [2096048.610407] init: pkgctl-transmission pre-start process (24169) terminated with status 1
2020-08-14T20:05:47+02:00 nasse synoscgi_SYNO.Core.Package.Control_1_start[23583]: servicecfg_internal_lib.c:22 Failed to start job [pkgctl-transmission][0xD900 manager.cpp:204]
2020-08-14T20:05:47+02:00 nasse synoscgi_SYNO.Core.Package.Control_1_start[23583]: service_initjob_action.c:27 InitJobStart failed, [0xD900 manager.cpp:204]
2020-08-14T20:05:47+02:00 nasse synoscgi_SYNO.Core.Package.Control_1_start[23583]: pkgstartstop.cpp:371 Failed to start pkgctl-transmission (err=-1) [0xD900 manager.cpp:204]
2020-08-14T20:05:51+02:00 nasse synoscgi_SYNO.Core.Package.Server_2_list[25436]: list_onserver.cpp:177 failed to process icon
2020-08-14T20:05:51+02:00 nasse synoscgi_SYNO.Core.Package.Server_2_list[25436]: list_onserver.cpp:177 failed to process icon
2020-08-14T20:05:52+02:00 nasse synoscgi_SYNO.Core.Package.Server_2_list[25436]: list_onserver.cpp:177 failed to process icon

2020/08/14 20:05:25	start transmission: begin to start version 3.00-18
2020/08/14 20:05:26	start transmission 3.00-18 Begin pre-load apparmor
2020/08/14 20:05:26	start transmission 3.00-18 End pre-load apparmor ret=[0]
2020/08/14 20:05:26	start transmission 3.00-18 Begin start-stop-status start
2020/08/14 20:05:46	start transmission 3.00-18 End start-stop-status start ret=[1]
2020/08/14 20:05:47	(system) trigger transmission 3.00-18 Begin start-stop-status stop
2020/08/14 20:05:47	(system) trigger transmission 3.00-18 End start-stop-status stop ret=[0]
2020/08/14 20:05:47	(system) trigger transmission 3.00-18 Begin unload apparmor
2020/08/14 20:05:47	(system) trigger transmission 3.00-18 End unload apparmor ret=[0]
2020/08/14 20:05:47	stop transmission: begin to stop version 3.00-18
2020/08/14 20:05:47	stop transmission: stop version 3.00-18 successfully, result 0
2020/08/14 20:05:47	start transmission: start version 3.00-18 failed, result 272
```

**Comment by ymartin59** [comment]
Please report content of `/var/packages/transmission/target/var/transmission_install.log` and `/var/packages/transmission/target/var/transmission.log` if available

**Comment by yitzhaq** [comment]
As noted there's not much useful there, I'm afraid. transmission.log is 282MB and has not been written to since the upgrade.
transmission_install.log hasn't been written to since 2018, so I doubt there's much of value there either, but here it is anyway:

```
Tue May 15 16:17:18 CEST 2018
===> Step preupgrade. USER=transmission GROUP=sc-download SHARE_PATH=
Tue May 15 16:17:33 CEST 2018
===> Step preuninst. USER=transmission GROUP=sc-download SHARE_PATH=
Tue May 15 16:17:35 CEST 2018
===> Step postuninst. USER=transmission GROUP=sc-download SHARE_PATH=
Tue May 15 16:17:36 CEST 2018
===> Step preinst. USER=transmission GROUP=sc-download SHARE_PATH=
Invoke service_preinst
Tue May 15 16:17:38 CEST 2018
===> Step postinst. USER=transmission GROUP=sc-download SHARE_PATH=
Installing service configuration /var/packages/transmission/conf/transmission.sc
Invoke service_postinst
Granting 'sc-transmission' unix ownership on /volume7/@appstore/transmission/var
Tue May 15 16:17:38 CEST 2018
===> Step postupgrade. USER=transmission GROUP=sc-download SHARE_PATH=
Granting 'sc-transmission' unix ownership on /volume7/@appstore/transmission/var
Invoke service_postupgrade
```

**Comment by ymartin59** [comment]
May you please provide output of following command: `ls -la /var/packages/transmission/target/var/`

**Comment by yitzhaq** [comment]
Ah, nailed it down, finally. The var dir is symlinked elsewhere, but the upgrade seems to have removed this symlink, and the resulting half-baked dir was what it failed to start with. Once I restored the symlink, things seem to be back to normal.
Thanks for the pointer - I'll try to keep this in mind for future upgrades!

**Comment by ymartin59** [comment]
@ymartin59 DSM upgrade process discard content of `/var/packages/transmission/target/`, our service script backup and restore on `var` content. I guess you may have create a symlink because of downloads target folder inside `var` itself.
I recommend you to revert such a change and reconfigure application to download directly to shared folder in DSM volume.

**Comment by yitzhaq** [comment]
OK, that explains it - thanks again for the details. Then I definitely need to keep this in mind for future upgrades. Might be worth scripting, perhaps.
The download target is external to var, but I keep the var contents on an encrypted volume. Since I couldn't find a clean and/or "proper" way to achieve that, I just symlink var there. Guess I could file a feature request to support that officially somehow, but I dunno how easy that would be to accomplish with DSM constraints.

**Comment by ymartin59** [comment]
@yitzhaq When installing a package the first time, Package Center requests for target volume where to deploy application... it may be an option to put "transmission" fully inside encrypted volume.

**Comment by yitzhaq** [comment]
@ymartin59 Yes, that seems worth trying out - thanks.
