### ISSUE TITLE
Deluge v2.0.3-12 "Error Invalid Argument"

### ISSUE THREAD

**Issue by Strangelovian** [SynoCommunity/spksrc#4134]
### Setup
_Package Name:_ deluge
_Package Version:_ v2.0.3-12 

_NAS Model:_ DS 1819+
_NAS Architecture:_ x86_64
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
With version 1.3.15-9 torrent download normally.

### Actual behavior
With version 2.0.3-12 torrent error: Error Invalid Argument. Even after DSM reboot error persists.
When rolling back manually to 1.3.15-9, torrent download resumes normally.

### Steps to reproduce
_1._ Install version 2.0.3-12
_2._ Add torrent
_3._ Torrent stays in status "Error Invalid Argument"

#### Package log
Nothing related to this error in deluge.log.
Deluge daemon starts normally, the torrent is added, but stays with error status "Error Invalid Argument"

#### Other considerations
People have had this error with other OS: https://dev.deluge-torrent.org/ticket/3294
It seems related to the version of python3-libtorrent.
As the syno package embeds its own version of libtorrent, is there an issue there?

**Comment by Strangelovian** [comment]
FTR:
Within syno package, embedded libtorrent version seem to be python_libtorrent-1.1.14
But www.libtorrent.org last version is 1.27.

**Comment by ymartin59** [comment]
Deluge package still uses Python 2.7.18, it will move to Python 3 when ready.

**Comment by Strangelovian** [comment]
Thank you.
So if I understand correctly, it's not possible to upgrade libtorrent without upgrading to python 3 first?

**Comment by ymartin59** [comment]
Deluge 2 is expected to run on Python 2 with python_libtorrent-1.1.14 as declared in requirements file.
Without a proper diagnostic why it fails on your system, this is a chance an upgrade solves nothing.

**Comment by Strangelovian** [comment]
I just know that rolling back to previous package works. So my guess it's related to protocol handling as mentioned by similar previous experiences here: https://dev.deluge-torrent.org/ticket/3294

My test torrent is a simple one: a debian torrent linux torrent file.
In the logs, nothing relevant, except that the error status reported by the lib torrent : "Error Invalid Argument".

I also tried the usual IT stuff:
- remove the package / re-install it
- reboot the DSM

**Comment by ymartin59** [comment]
Package updates have been published with fix #4192. Please confirm and close if relevant

**Comment by VincentMasselis** [comment]
I'm facing the same issue, updating Python and then stop and restart Deluge changed nothing :/

**Comment by BelladonnaWitch** [comment]
Hello everyone

having the same issue since python 2.7.18-24
I couldn't downgrade to python 2.7.18-23 without uninstalling Deluge so I decided no to do that

Looking forward to a new version fixing this issue, since it is really blocking the seed :(

**Comment by th0ma7** [comment]
New version of deluge is being published.  Please reopen the issue if its still occurring.  Thnx in advance.
