### ISSUE TITLE
[Python] Latest update breaks https/ssl

### ISSUE THREAD

**Issue by blueflame2020** [SynoCommunity/spksrc#4137]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Python/SickBeard Custom 
_Package Version:_ 2.7.18-23/20200804-8

_NAS Model:_ DS415+
_NAS Architecture:_ Intel Atom C2538 (Avoton)
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
After upgrade to latest python version:
Sickbeard shuold work like previous python version (2.7.14-19)
Sickbeard should open when https is enabled and browsing to https://<NAS_IP>:8083
Sickbeard should be able to connect to tvdb and venomous.github.io/sb_tvdb_scene_exceptions/exceptions.txt without
```
URL error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```
errors.

### Actual behavior
SickBeard web page does not show.
Chrome reports "The connection was reset." when going directly to https://<NAS_IP>:8083
NGINX proxy server shows:
```
2020/08/10 11:18:37 [error] 13031#13031: *183858 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: <CLIENT_IP>, server: sickbeard.xxxx.nl, request: "GET /favicon.ico HTTP/1.1", upstream: "https://<NAS_IP>:8083/favicon.ico", host: "sickbeard.xxxx.nl", referrer: "https://sickbeard.xxxx.nl/home/"
```
Sickbeard does run. (service is started and running and the logs show startup and backlog entries indicating processing of files etc. is continuing.)
On stopping SickBeard via package center, disabling https in the config.ini file and starting SickBeard again, the webpage is reachable at http://NAS_IP>:8083 (but in plain text, without certificates).
This is the case with both SickBeard self signed certificates as with own valid certificates.
Sickbeard can't search new series because connection to tvdb fails with ssl error.

### Steps to reproduce
_1._ Previous versions of python and latest version of sickbeard installed and configured with own valid certificate or self signed certificate (https enabled)
_2._ Update Python package via package center
_3._ login to sickbeard and search for a show.

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
Sickbeard install log:
```
Mon Aug 10 08:56:25 CEST 2020
===> Step preuninst. USER=sickbeard-custom GROUP=sc-download SHARE_PATH=
Removing service configuration sickbeard-custom.sc
Mon Aug 10 08:56:26 CEST 2020
===> Step postuninst. USER=sickbeard-custom GROUP=sc-download SHARE_PATH=
Removing user sc-sickbeard-custom
Mon Aug 10 09:03:44 CEST 2020
===> Step preinst. USER=sickbeard-custom GROUP=sc-download SHARE_PATH=
Invoke service_preinst
Mon Aug 10 09:03:51 CEST 2020
===> Step postinst. USER=sickbeard-custom GROUP=sc-download SHARE_PATH=
Installing service configuration /var/packages/sickbeard-custom/conf/sickbeard-custom.sc
Adding 'sc-sickbeard-custom' to 'sc-download'
Group Name: [sc-download]
Group Type: [AUTH_LOCAL]
Group ID:   [65537]
Group Members:
0:[SB]
1:[sc-sickbeard-custom]
Invoke service_postinst
New python executable in /volume1/@appstore/sickbeard-custom/env/bin/python
Installing setuptools, pip, wheel...
done.
```
#### Other logs
No log entries in Logs/cherrypy.log after enabling weblogs via config.ini and https is enabled.
Log entry in Logs/sickbeard.log
```
2020-08-15 13:29:53 INFO     CHECKVERSION :: Check scene exceptions update
2020-08-15 13:29:54 WARNING  CHECKVERSION :: URL error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727) while loading URL http://venomous.github.io/sb_tvdb_scene_exceptions/exceptions.txt
2020-08-15 13:29:54 ERROR    CHECKVERSION :: Check scene exceptions update failed. Unable to get URL: http://venomous.github.io/sb_tvdb_scene_exceptions/exceptions.txt
```
and
```
2020-08-10 14:41:16 DEBUG    CP Server Thread-5 :: Trying to find Show on thetvdb.com with: Star Trek Strange New Worlds
2020-08-10 14:41:16 DEBUG    CP Server Thread-5 :: Searching for Show with searchterm: 'Star Trek Strange New Worlds' on URL http://thetvdb.com/api/GetSeries.php?seriesname=Star+Trek+Strange+New+Worlds&language=en
2020-08-10 14:41:16 WARNING  CP Server Thread-5 :: URL error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727) while loading URL http://thetvdb.com/api/GetSeries.php?seriesname=Star+Trek+Strange+New+Worlds&language=en
2020-08-10 14:41:16 ERROR    CP Server Thread-5 :: Unable to get URL: http://thetvdb.com/api/GetSeries.php?seriesname=Star+Trek+Strange+New+Worlds&language=en
```

**Comment by ymartin59** [comment]
@hgy59 May you please help about it.

**Comment by Hamuko** [comment]
Getting a similar error except on the Python3 package.

```
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
```

Python 3.7.7-12, DS920+, DSM 6.2.3-25426 Update 2.

**Comment by kukoarmas** [comment]
Same problem accessing AWS S3 with python3 boto package. I read it could happen with older versions of boto because it lacked SNI support, but I also tried with latest version. So if it's a generic problem it could be related with the CA bundle file packaged with some python package

**Comment by BenjV** [comment]
Has nothing to do with Python but with the applications written in python and website who do a changeover from optional to mandatory ssl verification.
If the application does not include a client certificate in the call to those website, it will fail instead of just warn.

In the past on a lot of websites this verification was not mandatory.

**Comment by blueflame2020** [comment]
Hi BenjV,

Thanks for your reply. Could you then please explain why it starts working again with the previous python package installed?

**Comment by BenjV** [comment]
That is because in older versions of python the ssl verification was not mandatory and ssl errors were just ignored
The python developers rightly so changed that in the latest release.
Ignoring an ssl verification failure is of course a major security risk.

The application should do a correct ssl verification with a correct certificate, but lots of application don't do that correctly.

**Comment by kukoarmas** [comment]
To "fix" the problem you need to specify a ca bundle file containing the CA that issued the server cert you are trying to connect.
For example, I'm using boto to send backups to S3, and I had to setup s3cmd to use the central CA bundle file with the following configuration in .s3cfg file:
ca_certs_file = /etc/ssl/certs/ca-certificates.crt

**Comment by BenjV** [comment]
This has nothing to do with this issue.

The log file states that the application is trying to use "http" and both sites are "https only" at this moment.
So it is not an issue of missing certificate but of a wrong call to those websites.

**Comment by Safihre** [comment]
@BenjV I think in this case the problem is that the certificates are not being correctly picked up in the new packages..
The change to SSL verification in Python-core has been implemented in Python 2 and 3 already a few versions ago, so this shouldn't suddenly become a problem.

**Comment by BenjV** [comment]
Hmm ...
I did some test on my test Nas, my production NAs and windows which all have the latest python installed and could not reproduce the problem.

I used the Url from the error message posted by @blueflame2020 :
[code]
import urllib
print urllib.urlopen("http://venomous.github.io/sb_tvdb_scene_exceptions/exceptions.txt").read()
[/code]

Then I checked the python version and got this:
[quote]
Python 2.7.12 (default, May 12 2020, 04:48:57)
[GCC 4.9.3 20150311 (prerelease)] on linux2
[quote}

While the package center tells me I have python 2.8.18-23

**Comment by Safihre** [comment]
Could you try with a httpS URL? And indeed with the right package :)

**Comment by BenjV** [comment]
I tried both http and https, both gave no problems.

And I have the latest python package installed but it contains an old python version, so the python 2 package for at least Arm cpu's is incorrect.

**Comment by BenjV** [comment]
If I use requests with a certificate file from certifi all is working OK.
This code works fine

> import certifi, requests
> print requests.get("http://venomous.github.io/sb_tvdb_scene_exceptions/exceptions.txt", verify=certifi.where()).content
>

**Comment by Hamuko** [comment]
Can confirm the same happening on the Python 3 version.
```
Python 3.7.7 (default, Aug 18 2020, 20:42:48)
[GCC 4.9.3 20150311 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> response = requests.get("http://venomous.github.io/sb_tvdb_scene_exceptions/exceptions.txt")
>>> response.status_code
200
>>> import urllib.request
>>> response = urllib.request.urlopen("http://venomous.github.io/sb_tvdb_scene_exceptions/exceptions.txt")
Traceback (most recent call last):
  ...
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
```

**Comment by BenjV** [comment]
If you start python on the commandline and give the following commands you see a list where ssl is looking for a certificate

> import ssl
> print ssl.get_default_verify_paths()
> 

So I have two solutions and a one workaround for this issue.
Solution 1:
Change the python packages and add a certificate file "cert.pem"to the package location (/var/packages/python/target/cert.pem)

Solution 2:
Change the Python package an create a simlink to the certificate of the certifi site-package.
So add this command to the installation script:

> ls -s /var/packages/python/target/lib/python2.7/site-packages/certifi/cacert.pem /var/packages/python/target/cert.pem
 

Workaround:
Create an environment variable to suppress the ssl verification just like the older python package did:

> export PYTHONHTTPSVERIFY=0

My preference would be solution 2, which could also be used as a workaround for users as long as the package is not changed.

**Comment by Safihre** [comment]
I think the previous packages used solution 1 and used the general DSM certificate store. I remember inspecting this long ago and it sort of worked out of the box that it looked in the right location. But can't find much of a reference to it now.

**Comment by th0ma7** [comment]
Other ideas...
**Solution 2b)** what if the symlink was pointing towards DSM default `/etc/ssl/certs/`
**Solution 3)** From the previous PR from @hgy59 he did the following (https://github.com/SynoCommunity/spksrc/pull/4066/commits/ca0f2807740930cbbfea6fe5fb179f2f23f663bd):
```
CONFIGURE_ARGS += --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt
```
**Workaround B)** `export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`

**Comment by BenjV** [comment]
@th0ma7 
Your Solution 4 is my Solution 2

The certifi package is included in the Python package as site-package so it is already present and a simlink to the cacert.pem of that certifi packge is in my opinion the best solution.

That way everything is included in the Python package and not dependent on system certificates, which could change.

**Comment by blueflame2020** [comment]
If you put yours in a script, the file will also contain all github http stuff ;)

And lets agree to disagree on https for local applications ;)

**Comment by BenjV** [comment]
No I tested mine and it just pulls only the one file so you probably made a mistake.
The command specifies the file so it is impossble that it pulls more.

**Comment by blueflame2020** [comment]
@BenjV 
```
 wget -O /var/packages/python/target/cert2.pem 'https://github.com/certifi/python-certifi/blob/master/certifi/cacert.pem'
--2020-08-26 13:54:32--  https://github.com/certifi/python-certifi/blob/master/certifi/cacert.pem
Resolving github.com... 140.82.121.4
Connecting to github.com|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: '/var/packages/python/target/cert2.pem'

/var/packages/python/target/cert2.pem                    [ <=>                                                                                                                   ]   1.16M  7.18MB/s    in 0.2s

2020-08-26 13:54:33 (7.18 MB/s) - '/var/packages/python/target/cert2.pem' saved [1214077]
```
Content of file (first ten lines):
```
head /var/packages/python/target/cert2.pem





<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
```

So, what am I doing wrong here?

**Comment by BenjV** [comment]
Apparently I did something wrong.
I tried it again with my link but now I got also a html file just like you.

So your link is the correct one and I shall change mine.

Sorry.

**Comment by ymartin59** [comment]
Package updates have been published with fix. Please confirm #4192

**Comment by groypalo** [comment]
> Package updates have been published with fix #4192. Please confirm and close if relevant

Not trying to be obnoxious but what exactly do you want us to check? Synology package showing no update available for Home Assistant from SynCommunity. Or manual upgrade through CLI?

Thanks in advance for clarifying!

**Comment by hgy59** [comment]
> Not trying to be obnoxious but what exactly do you want us to check? Synology package showing no update available for Home Assistant from SynCommunity. Or manual upgrade through CLI?

There is a new Python2 package available (Version 2.7.18-24) in the [synocommunity package center](https://synocommunity.com/package/python).
You can manually download and install the package while it is not updated in the package center view of your diskstation.

This should fix #4177 (related to home assistant).

**Comment by groypalo** [comment]
Can this fix be included in the Python3 package? I only had that one installed for Home Assistant. I tried installin the one you refer above but does not fix the issue.

**Comment by ymartin59** [comment]
hg59 made a mistake. You have to grab Python 3 package update

**Comment by groypalo** [comment]
> hg59 made a mistake. You have to grab Python 3 package update

Same error on my end

```
OpenSSL> s_client -crlf -connect api.sense.com:443 -servername www.sense.com -showcerts
CONNECTED(00000003)
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify error:num=19:self signed certificate in certificate chain
```

**Comment by BenjV** [comment]
This has nothing to do with the issue of this topic.

You have a problem in your own environment, most likely a you have put a self signed certificate in the system certificate path.

**Comment by ymartin59** [comment]
I consider it as fixed.
