### ISSUE TITLE
Transmission 3.00-18 bundle of issues

### ISSUE THREAD

**Issue by Section25** [SynoCommunity/spksrc#4146]
Transmission
3.00-18

Synology DS 213
MARVELL Kirkwood 88F6282
DSM 6.2.3 25426 Update 2

**1).** It was just recommended during a DSM Security Check that I should update Transmission to v 3.00-18. During the update, I was informed that I should check permissions for sc-download, which I did.

After restarting, several Transmission downloads have the text:
'Error: No data found! Ensure your drives are connected or use "Set Location". To re-download, remove the torrent and re-add it.

The data IS (are) there. Using "Set Location" merely confirms that the location is correct and as this only applies to some downloads, makes no sense.

**2).** None of the items in the Settings Menu (gear wheel) work. They highlight when the cursor hovers but nothing happens when they are clicked.

**3).** When the Edit Preferences (spanner) is clicked, the pop-up pane appears for a fraction of a second then fades away.

I'd be happy just to reinstall the previous version but having used the Package Center I cannot find anywhere to download it.

If it isn't compatible with my device etc., why was it recommended?

[edit] I should have also stated that I have rebooted the DS 213 and Transmission a number of times.

**Comment by Section25** [comment]
I just discovered that I can hardly do anything useful with this version of Transmission.

None of the buttons on any of the pop-up panes respond apart from the 'cancel' buttons so I cannot actually add or remove downloads.

**Comment by vjayer** [comment]
Just checking in the package page, all the other processors are supported so that's not it. I suspect it is the initial permission problem warning that you got for sc-download group. When I first installed from the 2.9x ver, I also had permission problem where almost nothing worked. I forgot exactly what I did, but I ended up making everything--transmission and users--part of the sc-download group and giving everything rw permission for it, as well as the explicitly adding the shares. It was definitely more than one place.

You can see where any errors are by ssh 'ing into your dsm and looking at /usr/local/transmission/var/transmission.log
(use more to view the whole thing or tail to view the last parts)

If there were issues installing 3.00-18 you can check /var/log/synopkg.log and others generally for dsm in /var/log/messages

**Comment by Section25** [comment]
I actually gave sc-download cascading rw permissions.

It feels very strange using Transmission now. Sometimes some of the things I mentioned work but only sometimes and a couple of times afterwards, the list of downloads is repeated, so if they are listed alphabetically, they would go A-Z then A-Z again. Some of the pop-up panes look wonky so I don't think it is entirely down to my local installation.

I will probably re-install Transmission at some point but I don't spend a lot of time lurking under the hood on my NAS so I will probably procrastinate to avoid having to find the right file to set the login and password etc.

**Comment by BenjV** [comment]
Two things to check.
1.Did you gave permission to the group sc-download for the share you are downloading to?
If that share already existed before you granted this permission you have to recursively give this permission to all subfolder and files.

2. Do you have ACL's enabled for the shared folder you are using?

**Comment by Section25** [comment]
Yes, the group sc-download has rw permission to the Transmission share.

I don't know about ACL. The only place I see ACL mentioned is under the Shares > Action menu where it says convert to Windows ACL (greyed out).

**Comment by BenjV** [comment]
If it is greyed out, it has already acl support.
By the way, I don't experience any problem with this version of transmission.

But if you keep problems I would suggest to use Download Station instead.
That uses under the hood also transmission.

**Comment by hgy59** [comment]
@Section25 do you still have the issues with the current version 3.00-19?

**Comment by Section25** [comment]
I'll update and get back.

**Comment by Section25** [comment]
I can't see any obvious problems at the moment, thanks.

I've added torrents and they are downloading.

**Comment by Section25** [comment]
This might sound weird but after updating, three torrents which had stalled weeks ago all completed or nearly completed.

It might be suggested that somebody just coincidentally started seeding all of a sudden but they were three different versions of the same thing I had been having trouble downloading so I doubt that the same seeder was seeding all three.

**Comment by hgy59** [comment]
@Section25 thanks for the feedback.

The updated package also updated openssl to 1.1.1.h.
The TLS issues seem to be fixed now.
