### ISSUE TITLE
homeassistant 0.114.2-7 still with issues with python 3 wheels build 

### ISSUE THREAD

**Issue by rgodinezp** [SynoCommunity/spksrc#4147]
@ymartin59 Sorry to bring bad news, but the homeassistant package release 0.114.2-7 still has the same problems in my DS214play (Intel Atom processor, DSM 6.2.3-25426 Update 2):
- It doesn't finish cleanly the initial config after installation,
`2020-08-24 00:40:33 ERROR (SyncWorker_36) [homeassistant.util.package] Unable to install package hass-nabucasa==0.35.0: ERROR: Command errored out with exit status 1:
   command: /volume1/@appstore/homeassistant/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wa7y4lp8/yarl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wa7y4lp8/yarl/setup.py'"'"';f=getattr(tok
enize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-f7x9emxg
       cwd: /tmp/pip-install-wa7y4lp8/yarl/
`
- web interface says "Home Assistant is starting, not everything will be available until it finishes."
- second screen (location) of "/onboarding.html" gives error "Failed to save: undefined" and cannot continue with initial setup.
- log excerpt with some of the errors:
`    /spksrc/toolchains/syno-evansport-6.1/work/i686-pc-linux-gnu/bin/i686-pc-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/spksrc/toolchains/syno-evansport-6.1/work/i686-pc-linux-gnu/i686-pc-linux-gnu/sy
s-root/usr/include -I/spksrc/spk/python3/work-evansport-6.1/install//var/packages/python3/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /spksrc/spk/python3/work-evansport-6.1/install/var/packages/python3/target/lib -I /sp
ksrc/spk/python3/work-evansport-6.1/install/var/packages/python3/target/include -I/spksrc/toolchains/syno-evansport-6.1/work/i686-pc-linux-gnu/i686-pc-linux-gnu/sys-root/usr/include -I/spksrc/spk/python3/work-evansport-6.1/install//var/pa
ckages/python3/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /spksrc/spk/python3/work-evansport-6.1/install/var/packages/python3/target/lib -I /spksrc/spk/python3/work-evansport-6.1/install/var/packages/python3/target/inc
lude -fPIC -I/volume1/@appstore/homeassistant/env/include -I/var/packages/python3/target/include/python3.7m -c yarl/_quoting.c -o build/temp.linux-i686-3.7/yarl/_quoting.o
    unable to execute '/spksrc/toolchains/syno-evansport-6.1/work/i686-pc-linux-gnu/bin/i686-pc-linux-gnu-gcc': No such file or directory
    error: command '/spksrc/toolchains/syno-evansport-6.1/work/i686-pc-linux-gnu/bin/i686-pc-linux-gnu-gcc' failed with exit status 1
`

Attached the logs 
[homeassistant.log](https://github.com/SynoCommunity/spksrc/files/5115551/homeassistant.log)
[homeassistant_install.log](https://github.com/SynoCommunity/spksrc/files/5115552/homeassistant_install.log)

Hope this helps finding root cause and fixing the issue.

_Originally posted by @rgodinezp in https://github.com/SynoCommunity/spksrc/issues/3944#issuecomment-678878409_

**Comment by smaarn** [comment]
Hello,

It seems that the issues aren't exactly the same as before.
Here the issue is that some wheels aren't shipped with the homeassistant package. Since the DSM cannot build native wheels (which is the error being reported here) so to fix this they need to be packaged at build time.

Attached a PR which should fix this issue. Would you be able to assist in validating it ? Personally I only validated the evansport package by starting it and checking that there were no errors reported in the logs.

**Comment by p2004r** [comment]
Please update the compiled packages on the community website  https://synocommunity.com/

**Comment by ymartin59** [comment]
Notice I have updated instructions at https://github.com/SynoCommunity/spksrc/wiki/FAQ-HomeAssistant

**Comment by pheudo** [comment]
At the moment, the most recurrent error about the building of the wheels for me is:

`ERROR: Failed building wheel for yarl`
