### ISSUE TITLE
Sabnzbd v3.0.1 Interface

### ISSUE THREAD

**Issue by whemever** [SynoCommunity/spksrc#4156]
I'm running SABNZBD and have been doing so for about a year, in the last few days it underwent an update to v3.0.1. I'm using it on a DS3617xs running DSM 6.2.3-25426 update 2 with 32Gb of memory.

The interface is, IMHO, a major step backwards, it does not scale with screen size (nor does there seem to be any way to change the font size) moving items on the download list is extremely haphazard as the grab area is minute, possibly due to the fact I'm running it on a screen that is 2560 x 1440. deleting an entry means ticking a box then going and clicking on an x that looks more like it should close down the menu, then being told it is deleing n nzb's - but not which ones. Also the nice layout option of being able to split active and finished downloads to separate screens has gone.

So please bring back some of the better aspects of the original interface - the ability to react to screen size and change font size, the ability to easily move items in a queue ( half of it does seem present, its just used to move specific download threads instead of whole nzb's.  I would love the ability to split the screen back for active and finished downloads.  Finally please address the deletion aspect, the current implementation is not just ugly but time consuming, as if you have 2 or more nzb's being deleted and you expected less, you have to go through each screen of downloads looking for a place where you may have accidently clicked on a box when trying to move something, or some other cause. The delete bin on each item was far easier to understand and made much more sense

**Comment by BenjV** [comment]
The SynocCommunity only package existing software for use on a Synology Nas.
Please direct this kind of questing to the developer webisite:
https://github.com/sabnzbd/sabnzbd/issues

**Comment by whemever** [comment]
Ok will do!
