### ISSUE TITLE
SABNZBD update

### ISSUE THREAD

**Issue by whemever** [SynoCommunity/spksrc#4157]
I'm running SABNZBD and have been doing so for about a year, in the last few days it underwent an update to v3.0.1. I'm using it on a DS3617xs running DSM 6.2.3-25426 update 2 with 32Gb of memory.

With the new implementation of SABNZBD, I am getting a 'Update Available!' message in the top left hand corner of the screen, clicking on it takes me to a page to download the update, unfortunately this update is not available on Synology!  I was wondering if like Sonarr (v3), updates would be done automatically (or with an option to enable this to happen) as it stands the current message is misleading there is an update, however it is not on Synology - better to either supress the message until the Synology version is available or totally delete it relying on the Synology package center to keep on top of the updates

**Comment by BenjV** [comment]
Applications that are not able to update themselves are dependent for updates on a SynoCommunity member to create a new package to includes this update.
So you simply have to wait until the SynoCommunity maintainer of this package has time to create an updated package for Synology.

Maybe you should ask the developers of SabNzbd to add functionality to upgrade itself.

**Comment by Safihre** [comment]
https://github.com/SynoCommunity/spksrc/pull/4154
