### ISSUE TITLE
DS216j and DSM 6.2.3-25426 Update 2 - Jackett 0.14.485.10

### ISSUE THREAD

**Issue by giospud** [SynoCommunity/spksrc#4162]
I get a warning message from jackett that the version installed is very old. There is any plan to release a version of jackett updated to the version that should be comiìpiled?

**Comment by mhurwood** [comment]
If your NAS has an Intel 64bit CPU then this link will help:

(https://github.com/SynoCommunity/spksrc/issues/3697#issuecomment-671318950)

**Comment by ymartin59** [comment]
Update published
