### ISSUE TITLE
git 2.26.-14 needs lower Previliges on DSM 7 beta for install

### ISSUE THREAD

**Issue by noyse27** [SynoCommunity/spksrc#4165]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: git
_Package Version:2.26.2-14

_NAS Model: 716+II
_NAS Architecture: intel
_DSM version: 7 Beta 

### Expected behavior
the package should be installed

### Actual behavior
the package wont't be install because of wrong package priviliges

### Steps to reproduce
_1. install DSM 7 Beta 
_2. click on repair
_3. error occurs that installation has failed due to to high priviliges
https://help.synology.com/developer-guide/privilege/preface.html

![2020_09_08_14 46 43_polze_j_](https://user-images.githubusercontent.com/25564572/92478320-47ef7600-f1e2-11ea-8874-6b1cebac61b7.png)

**Comment by hgy59** [comment]
Third party packages are currently not supported by DSM 7 Preview

You accepted the notes on installation:
> **Packages by 3rd Party**
> - Packages published by third-party developers are currently not supported. You can update the packages in Package Center when compatible versions are released.

But anyway, for DSM 7 all this privilege stuff must be fixed.

**Comment by noyse27** [comment]
no problem :) but for git it shows me repair, so i thought it would work. other packages are shown with incompatible

**Comment by hgy59** [comment]
And note, DSM 7 beta is not available yet. It is the first DSM 7 public preview release `DSM 7.0-40850` and (mine) was built on 2020/09/02 18:39:09

**Comment by hgy59** [comment]
I also got repair for redis (required by ntopng) and it showd me the same error as for git.
SynoCli File Tools are still working after preview installation, but the package center tells package is stopped.

**Comment by hgy59** [comment]
see  #4170
