### ISSUE TITLE
syncthing not working on dsm7?

### ISSUE THREAD

**Issue by eliasildi** [SynoCommunity/spksrc#4166]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ syncthing
_Package Version:_ 1.7.1-20

_NAS Model:_ 281+
_NAS Architecture:_ 
_DSM version:_ 7.0-40850

### Expected behavior
Tell us what should happen

### Actual behavior
version incompatible with your dsm version
### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
see #4170
