### ISSUE TITLE
ffmeg needs lower privileges

### ISSUE THREAD

**Issue by RoboPete** [SynoCommunity/spksrc#4167]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ ffmpeg
_Package Version:_ 4.2.4-34

_NAS Model:_ 218+
_NAS Architecture:_ Apollolake
_DSM version:_ 7 Beta

### Expected behavior
the package should be installed

### Actual behavior
the package wont't be install because of wrong package priviliges
### Steps to reproduce
_1._ install DSM 7 Beta
_2._ try install ffmpeg
_3._ error occurs that installation has failed due to to high priviliges
https://help.synology.com/developer-guide/privilege/preface.html

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
see  #4170
