### ISSUE TITLE
tvheadend needs lower privileges

### ISSUE THREAD

**Issue by Geekllem** [SynoCommunity/spksrc#4169]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_  tvheadend
_Package Version:_ v4.3.20200713~ce09077-24

_NAS Model:_  VirtualDSM 
_NAS Architecture:_
_DSM version:_ DSM 7.0-40850 (beta program)

### Expected behavior
the package should be installed

### Actual behavior
the package wont't be install because of wrong package privileges

### Steps to reproduce
1. install DSM 7 Beta
2. try install tvheadend - ask to install  ffmpeg first...
3. error occurs that installation has failed due to to high priviliges
https://help.synology.com/developer-guide/privilege/preface.html

Could you check this?

Thank you very much!!!

**Comment by hgy59** [comment]
see  #4170
