### ISSUE TITLE
DSM 7 - Packages reporting error due to high privileges

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#4170]
As the DSM 7 preview release is out, there are several synocommunity packages that fail installation with error due to high privileges.

Unfortunatly the development guide page about [Lower Privilege](https://help.synology.com/developer-guide/privilege/preface.html) does not solve this issue. The developer guide is outdated (last update was 2016/01/14).

~~Until an official solution is available, let's collect the affected packages here (instead of creating an issue for each).~~

### As there is no Information available on how to build spk packages compatible with DSM 7, there is no way to build 3rd party packages and the list of incompatible packages is obsolete for now.

---

## ~~Packages reporting error due to high privileges~~
- [ ] ...

## Remarks
Third party packages are currently not supported by DSM 7 Preview.

See installation notes:
>   **Packages by 3rd Party**
> - Packages published by third-party developers are currently not supported. You can update the packages in Package Center when compatible versions are released.

**Comment by hgy59** [comment]
## Warning
Currently none of the community packages can be installed - neither through package center nor manually.

Packages already installed before installation of DSM 7 prerelease stay installed.
Installed community packages show either status stopped with remark "not compatible with this DSM version" or status "needs repair" (but repairing does not work due to privileges).

**Comment by stephanvierkant** [comment]
> Until an official solution is available

Can we help? Does Synology about this issue?

**Comment by hgy59** [comment]
Just found the DSM 7 Preview forum on synology and posted about missing an updated development guide.
Now I am waiting for an answer about the Update of the third party package development guide, in particular for the updated spk format.


Findings so far:
- current 3rd party packages cannot be installed on DSM 7 Preview (error: high privileges)
- the spk format of the official DSM 7 beta packages is different to the documented DSM 6 format (it is not a simple tar archive anymore. It looks like some parts of an spk file are encoded (or encrypted, or signed). Only the INFO part is in clear-text. Maybe they use a proprietary archive format now.
- The official package center does not support navigation in the file structure anymore. One needs the exact link to download an spk including the version and arch (this is also for packages of DSM < 7).

Without the knowledge whether third party apps will need the new spk format - or this new format is for official packages only and the traditional format is only temporary disabled in the preview version - it is not possible to solve this.

**Comment by hgy59** [comment]
As you can see in the [DSM 7 community forum (for previewers only)](https://community.synology.com/enu/forum/19/post/136805) there is no public information available yet. 

_Conclusion:_

**At the moment there is no way to use 3rd party packages with DSM 7 preview.**

**Comment by publicarray** [comment]
While I have not installed DSM 7.0 yet I assume `dnscrypt-proxy` can be added to your "asking for higher privileges" list as it attempts to bind to a system port (53)

**Comment by hgy59** [comment]
You must not install DSM 7 preview when you want to use 3rd party packages.
May be the required information will be available with DSM 7 beta (not yet scheduled) or with official DSM 7 release (not yet scheduled, I do not expect it before 2021/01/01) or even later...

**Comment by publicarray** [comment]
Thanks @hgy59 I'm aware, I've even posed an [open question on their forum](https://community.synology.com/enu/forum/1/post/136925) if Synology has development documentation, but like you say it might be a while. (I got bit too exited 😉)

**Comment by hgy59** [comment]
@publicarray as you have access to the DSM 7 preview forum you can see the answer for my question about updated developer documentation here:
https://community.synology.com/enu/forum/19/post/136805

**Comment by stephanvierkant** [comment]
Any update on this? Does anybody had contact with Synology?

**Comment by ymartin59** [comment]
My position is clear - users choosing Synology devices often consider SynoCommunity package as part of "the offer" (even if it is not commercial - as an example guys are returning device to choose another one where packages of interest are already available) and I find Synology does not play fair with us, asking guaranties with NDA but provides no help nor even at least documentation for us to port (any) packages to DMS 7 "earlier" (because we would find a way "one day"). They seem only interested in porting current package list from their marketplace they consider a priority to get available on DSM 7.

**Comment by ymartin59** [comment]
And personally, I have a single Synology device I will not upgrade to DSM 7 until packages I run there have been ported and tested at least on an xpenology VM. Docker may be an option to avoid such dependency but its support is limited to most expensive devices not targeting individuals like most of SynoCommunity users.

**Comment by ymartin59** [comment]
From @baya44 at https://github.com/SynoCommunity/spkrepo/issues/55
<<
I'm actually testing DSM 7.0 on my DS1817+ and i have some packages who don't work because privilege issues.
Synology give this link for dev: https://help.synology.com/developer-guide/privilege/preface.html
The list of package: git, python, python3, plexpy custom, sickbeard-custom, ffmpeg and Gateone.
>>

**Comment by hgy59** [comment]
Good news, the DSM 7 Preview Toolchains are published at [sf.net](https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%207.0%20preview%20Tool%20Chains/)

**Comment by th0ma7** [comment]
This is great news... no kernel branch yet with build id but if your ok with this I volunteer myself to do the initial work to include this into the framework like I did with the previous, post PR #4200.

**Comment by hgy59** [comment]
@th0ma7 DSM 7 will need a lot of investigation and I propose to use a development branch for this and not touch the master until we reach a (more or less) stable stage. The same approach was used when DSM 6 was introduced.

I have the DSM 7 Preview Version installed on a DS218+ and my first experience was frustrating (I built the example package but it failed to install).

**Comment by hgy59** [comment]
Just wondering wether synology will create Diskstations with AMD Ryzen™ Embedded V1000 processors (as there is a toolchain called [Intel x86 Linux 4.4.59 (V1000)](https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.2.3%20Tool%20Chains/Intel%20x86%20Linux%204.4.59%20%28V1000%29/))

**Comment by th0ma7** [comment]
> Just wondering wether synology will create Diskstations with AMD Ryzen™ Embedded V1000 processors (as there is a toolchain called [Intel x86 Linux 4.4.59 (V1000)](https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.2.3%20Tool%20Chains/Intel%20x86%20Linux%204.4.59%20%28V1000%29/))

Interesting finding... :)

**Comment by hgy59** [comment]
The new Archs purley, geminilake and v1000 where added to the github repo of [Synology DSM6.0 package toolkit framework](https://github.com/SynologyOpenSource/pkgscripts-ng) just three days ago.

**Comment by hgy59** [comment]
> 
> 
> > Just wondering wether synology will create Diskstations with AMD Ryzen™ Embedded V1000 processors (as there is a toolchain called [Intel x86 Linux 4.4.59 (V1000)](https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.2.3%20Tool%20Chains/Intel%20x86%20Linux%204.4.59%20%28V1000%29/))
> 
> Interesting finding... :)

The secret is revealed: it's the new DS1621+ (without 'xs')


Model | CPU Model | Cores | Threads | FPU | Package Arch | RAM
-- | -- | -- | -- | -- | -- | --
DS1621+ | AMD Ryzen V1500B | Quad Core | 8 | Yes | V1000 | DDR4 ECC SODIMM 4GB

**Comment by stephanvierkant** [comment]
What's the status of this issue?

I see there is some information right now: https://community.synology.com/enu/forum/19/post/137228

**Comment by publicarray** [comment]
Current DMS7 support is: Work in progress.
ETA: When it's ready

Although this particular issue is mostly solved in my DSM-7 branch. It needs testing and some scripts need a rewrite. I still expect to see more subtle permission problems depending on the package.

**Comment by xhemp** [comment]
@publicarray I've been trying to get some packages to be installed but I am still hitting the high privileges error. What do you mean by "it's been mostly solved on your DSM7 branch"? Have you managed to install a package successfully without seeing that error on install? Can you share the privilege file and/or other files?  I've actually cloned your dsm7 branch to work with but it doesn't really matter how I modify the privileges file, I still get the same error.

**Comment by tmm1** [comment]
https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/7.0/enu/DSM_Developer_Guide_7_0_Beta.pdf

**Comment by publicarray** [comment]
Hi there, Good to see more people trying out DSM7 :+1:

"Mostly Solved" means that one instance of the specific privilege problem is solved. Package can now be installed without the error message but since a few packages and scripts assume they have root access now fail silently. This is like the symptoms you have described. Some packages may work and while some start up scripts need to be adjusted. I've tried to fix another instance in the generic service startup script but I've only tested 3 working packages.

Hope this clears that up. As @tmm1 alluded to, the developer documentation is the best place to learn more about the changes to DSM7 and develop your own package.

**Comment by xhemp** [comment]
Thansk, @tmm1 and @publicarray .
I will definitely give it a go, I managed to compile rutorrent (which I have running on 6.2) but it fails to start up, etc so I'm going through the changes it needs to see if I can get it working.

**Comment by mahisri1** [comment]
I have upgraded my spare one to DSM 7 and see this error: 
![image](https://user-images.githubusercontent.com/77031143/103713811-d30b2d80-4f82-11eb-856c-561408c13796.png)

![image](https://user-images.githubusercontent.com/77031143/103713933-16fe3280-4f83-11eb-8d24-74b263e1ebc4.png)

That means DSM7 is not for my production stuff. BTW, I liked the MFA (multi factor authentication) improvements... great job. Not sure, if the applications can be manually granted elevated permissions...  Thanks for all of your efforts.

**Comment by publicarray** [comment]
This particular issue is solved on the DSM7 branch. Some packages still have custom scripts that fail. Please see issue #4215 for further discussion.
