### ISSUE TITLE
Rename Home Assistant package to Home Assistant Core 

### ISSUE THREAD

**Issue by fredrike** [SynoCommunity/spksrc#4172]
It is indeed confusing but there is no Hass.io anymore. Home Assistant have been renamed to Home Assistant **Core**.

https://www.home-assistant.io/faq/ha-vs-hassio/

**Comment by ymartin59** [comment]
Only marketing... just annoying effort.

**Comment by fredrike** [comment]
> Only marketing... just annoying effort.

Yes, but it would be good to follow the naming convention.

**Comment by hgy59** [comment]
There is no way to migrate the spk package name (internal name, i.e. spk-filename and spk/folder name) without losing the ability to update installed packages. But we can change the `Display Name` that is displayed in DSM and the package center without trouble. 
Would this satisfy the issue?

**Comment by fredrike** [comment]
Yes, that would be good.

**Comment by hgy59** [comment]
done.
