### ISSUE TITLE
Sickbeard - How to install on Synology DSM 6

### ISSUE THREAD

**Issue by dragonslore** [SynoCommunity/spksrc#4176]
Hello,

Sickchill team redirected me to your repository for a fresh Sickchill install on my Syno as regular Sickbeard package is not working anymore for me.
I didn't find a proper way to install it, can you please help me ? I didn't find any .pkg

Here is my orignal message on Sickchill community: https://github.com/SickChill/SickChill/issues/6730

Thanks in advance for your help
Manu

**Comment by BenjV** [comment]
I am busy creating a Python 3 version package for SickChill.
Have a little patient

**Comment by dragonslore** [comment]
Hi Benjv, thank you so much for your work. I will be patient :-)

**Comment by BenjV** [comment]
I rewrote the complete installation package for SickChill for Python 3 and posted it on this repositary.
You can find it here.
https://github.com/BenjV/SYNO-packages
Download the package to your PC for a manual install.
Make sure you installed Python 3 from the SynCommunity first.

If you already have a SickChill version running, please make a backup from within SickChill.
Then remove that package, manual install the new one, start it and restore the backup from within SickChiil.

Enjoy.

**Comment by dragonslore** [comment]
Thank you BenjV I will check that. Can you please tell me the path of the installation on the Synology ? still /usr/local/ ?

**Comment by BenjV** [comment]
Never been /usr/local/?
That is the location there the simlinks for the package center are located, you should never use that.

The actual package is installed in.

> /var/packages/sickchill/target

The config and databses are in:

> /var/packages/sickchill/target/var

and the source in:

> /var/packages/sickchill/target/var/src

**Comment by dragonslore** [comment]
Ok understood.
Package is installed and configuration restored. Let's see how it is going from there. I will share my feebacks.

Thanks again BenjV :-)

**Comment by Nyaran** [comment]
I created this PR to add a SickChill package to SynoCommunity: https://github.com/SynoCommunity/spksrc/pull/4161

On first post you will be able to find the compiled spk to manual install it until the code is accepted.

**Comment by BenjV** [comment]
An .spk is not a compiled source, just a tar with inside scripts, settings and in case of a Python application the python code.
