### ISSUE TITLE
Duplicity - install error, package gnupg is need

### ISSUE THREAD

**Issue by vsc55** [SynoCommunity/spksrc#4180]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Duplicity
_Package Version:_ 0.7.19-6

_NAS Model:_ DS218+
_NAS Architecture:_ INTEL Celeron J3355
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
install

### Actual behavior
I get a message saying that the package "gnupg" is missing from the package system.

### Steps to reproduce
_1._ Click Install

**Comment by saschadd** [comment]
I have the same problem and have not found a way to install gnupg package.
Any help would be very appreciated.

**Comment by saschadd** [comment]
Hmm there is a beta package available but i cant see it in DSM 6 even after activating beta packages. The beta packages setting seems to activate only for Synology packages.

**Comment by hgy59** [comment]
gnupg update is published. This can take up to 48h until it is visible in DSM package center - or you can download from [here](https://synocommunity.com/package/gnupg).
