### ISSUE TITLE
Package "Nano" is missing / can't be installed on new machines via Package Manager

### ISSUE THREAD

**Issue by cmasterdelphi** [SynoCommunity/spksrc#4181]
I have the "nano" package installed on my existing NAS. After getting a new one, I noticed, that this package is not existing anymore. 

### Setup
Name: nano
Version: 2.9.8-5

DS3615xs
DSM 6.2.3-25426 Update 2

### Expected behavior
I want to be able to install "nano" package

### Actual behavior
On my existing NAS, the package is still installed but not visible anymore in the package manager.
On my new NAS, the package is not existing in the package manager (so cant be installed)

### Steps to reproduce
- Setup a new NAS
- Add SynoCommunity to Package MAnager
- See, that there is no "nano" package

![image](https://user-images.githubusercontent.com/56067322/93256675-f758b980-f79b-11ea-92ea-793cda47b151.png)

**Comment by hgy59** [comment]
nano is no longer supported as standalone package - it is contained in synocli-file.

**Comment by ymartin59** [comment]
Search for "nano" at https://synocommunity.com/packages and find https://synocommunity.com/package/synocli-file
