### ISSUE TITLE
Packages still not supported on geminilake architecture (DS x20)

### ISSUE THREAD

**Issue by icegunner** [SynoCommunity/spksrc#4184]
The following packages are currently not supported on DS 420, DS 920 (geminilake):

- Lidarr
- Mono
- nano
- Node.js v4
- Radarr
- Sonarr

_NAS Model:_ DS 920+
_NAS Architecture:_ geminilake
_DSM version:_ 6.2.2

### Expected behavior
Run Migration Assistant. During Initial System Check, for package compatibility, there should be no errors. Assuming that all packages properly installed from package source and no out-of-band updates/installs/changes.

### Actual behavior
When running Migration Assistant between DS 415+ and DS 920+, the following warning occurs:

> "The following packages are not supported on this device: Python 3, Radarr, Mylar, CouchPotato, Subliminal, PlexPy Custom, Sonarr, Lidarr, SABnzbd, Node,js v4, nano, Python, Tranmission, Mono, Git. However, the data in these packages can still be migrated."

However, I do see several of them in the Package Center -> Community. So, not sure why this is the case.

### Steps to reproduce
See previous section.

#### Package log
N/A

**Comment by ymartin59** [comment]
I am surprised that Migration Assistant reports these packages (I expect to be available for geminilake): Python3, CouchPotato, SABnzbd, Python, Transmission and Git.
Is your list "up to date"?
nano is now included in synocli-file: https://synocommunity.com/package/synocli-file

**Comment by ymartin59** [comment]
Notice SynoCommynity does not maintain Node.js v4 but provides this version: https://synocommunity.com/package/nodejs
If you expect Node.js v4 please complain to Synology: https://forum.synology.com/enu/

**Comment by icegunner** [comment]
> I am surprised that Migration Assistant reports these packages (I expect to be available for geminilake): Python3, CouchPotato, SABnzbd, Python, Transmission and Git.
> Is your list "up to date"?

So was I. Those you mentioned _are_ listed in Package Manager. That's why I didn't include them in the bulleted list.

> nano is now included in synocli-file: https://synocommunity.com/package/synocli-file

I forgot about nano moving. Good catch. Should be off the list.

> Notice SynoCommynity does not maintain Node.js v4 but provides this version: https://synocommunity.com/package/nodejs
> If you expect Node.js v4 please complain to Synology: https://forum.synology.com/enu/

Not too worried about Node.js v4. Just reporting what I saw in this scenario. It just happens that I have it on my old DS 415+. Don't really use it anymore anyway.

**Comment by ymartin59** [comment]
Following packages have been updated and/or published for geminilake: Mono, Lidarr, Radarr, Sonarr #4186
Please close this issue if relevant.
