### ISSUE TITLE
Python(2 and 3) build with Openssl version 1.1.1 (feature request)

### ISSUE THREAD

**Issue by BenjV** [SynoCommunity/spksrc#4185]
_Package Name: Pyton2 and Python 3
_Package Version:
Python2 2.7.18-23
Python3 3.7.7-13

_NAS Model: all
_NAS Architecture: all

Both Python2 and Python 3 are build with very old versions of open ssl (OpenSSL 1.0.2n  7 Dec 2017)
Can both Python versions packages be build with OpenSSSL version1.1.1 to enhance security for Python applications

**Comment by ymartin59** [comment]
See PR #4155

**Comment by ymartin59** [comment]
I have rebuilt Mono for geminilake and it seems to have resulted to regression with ssl support too.
