### ISSUE TITLE
SynoCLI File Tools failed to install on Synology DS1621xs+

### ISSUE THREAD

**Issue by opicron** [SynoCommunity/spksrc#4187]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ SynoCLI File Tools
_Package Version:_ 1-1-3

_NAS Model:_ DS1621xs+
_NAS Architecture:_ INTEL Xeon D-1527
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
Expected to install package

### Actual behavior
Failed to install package

### Steps to reproduce
Try to install package

#### Package log
No log present  `/usr/local/{package}/var/`_
#### Other logs
Nothing in  `/var/log/synopkg.log`_
`message.log` contains:
```
2020-09-23T11:30:42+02:00 TheHideout synoscgi_SYNO.Docker.Image_1_upload[15536]: image.cpp:727 Fail to Add image, _errMsg: [{"error":"Error processing tar file(exit status 1): archive/tar: invalid tar header","errorDetail":{"message":"Error processing tar file(exit status 1): archive/tar: invalid tar header"}}]
```

**Comment by ymartin59** [comment]
I see no reason it may fail, except one: your DSM system is out of free disk space to download and install package on target volume you requested for installation

**Comment by opicron** [comment]
Well-- I am stoopid it seems-- after searching extensively for an solution online it seems that I have to allow untrusted packages. Which was set at from synology only, the error message seems clear after all but it just did not register to me.

**Comment by opicron** [comment]
Closing ;)
