### ISSUE TITLE
Mono Update Broke Jackett

### ISSUE THREAD

**Issue by xxMayheMxx** [SynoCommunity/spksrc#4188]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Jackett
_Package Version:_ 0.14.485-10

_NAS Model:_ DS918+
_NAS Architecture:_ INTEL Celeron J3455
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
Connect to RSS feeds

### Actual behavior
An error occurred while testing this indexer
Exception (rarbg): The method or operation is not implemented.: The method or operation is not implemented.

A standalone Jackett with non-dependency Mono is now available.
An update to the Syno Package is necessary.

**Comment by mhurwood** [comment]
If your NAS has an Intel 64bit CPU then this link will help:

(https://github.com/SynoCommunity/spksrc/issues/3697#issuecomment-671318950)

**Comment by ymartin59** [comment]
I have just tested. A fresh install works as expected. By the way, I try to publish an update.

**Comment by ymartin59** [comment]
@xxMayheMxx May you please download and install manually this Mono package version https://packages.synocommunity.com/mono/15/mono.v15.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk
to confirm it fixes the issue I have probably guessed you have.

**Comment by ymartin59** [comment]
Updates have been published. Should fix your issue. If not just reopen.
