### ISSUE TITLE
Radarr v3 does not get killed correctly, process sc-rada+still existing and produces issues

### ISSUE THREAD

**Issue by Epyon83** [SynoCommunity/spksrc#4201]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Radarr
_Package Version:_ Any new 3.x version, currently installed 3.0.0.3840

_NAS Model:_ DS916+
_NAS Architecture:_ x64
_DSM version:_ 6.2.3-25426 Update 2

### Expected behavior
The process should be killed correctly by a) internal shutdown via the web interface and b) when the package gets stopped in DSM

### Actual behavior

Usually my NAS starts and stops this service per time (for years without any issues!) but since the new version v3 is installed the kill / stop doesn't work correctly anymore. There is always a process, even if the package has stopped, in the top overview called sc-rada+ which also prevents hibernation of the NAS and there are always some things happening on the HDD thanks to this process. I can kill this manually with sudo kill pid and the NAS goes sleeping again; afterwards I cannot start the package again in DSM, there is always an error message saying package could not be started. So the shutdown process needs to be fixed!

### Steps to reproduce
_1._ Install any Radarr v3 version
_2._ Stop the package either with the web interface of Radarr itself or with DSM package service
_3._ Go to console and do 'top' command, see process sc-rada+ still running

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Sat Oct  3 00:34:14 CEST 2020
Starting radarr command env PATH=/var/packages/mono/target/bin:/volume1/@appstore/radarr/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/radarr/var LD_LIBRARY_PATH=/volume1/@appstore/radarr/lib /var/packages/mono/target/bin/mono /volume1/@appstore/radarr/share/Radarr/Radarr.exe 
[Info] Bootstrap: Starting Radarr - /volume1/@appstore/radarr/share/Radarr/Radarr.exe - Version 3.0.0.3840 
[Info] SingleInstancePolicy: 1 instance(s) of Radarr are running 
[Warn] SingleInstancePolicy: Another instance of Radarr is already running. 
[Info] Bootstrap: Application is being terminated. Reason : Another instance is already running 
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Nothing to see there

2020/10/03 00:31:10	(system) trigger radarr 20200921-11 Begin start-stop-status stop
2020/10/03 00:31:10	(system) trigger radarr 20200921-11 End start-stop-status stop ret=[0]
2020/10/03 00:31:10	(system) trigger radarr 20200921-11 Begin unload apparmor
2020/10/03 00:31:10	(system) trigger radarr 20200921-11 End unload apparmor ret=[0]
2020/10/03 00:31:11	stop radarr: begin to stop version 20200921-11
2020/10/03 00:31:11	stop radarr: stop version 20200921-11 successfully, result 0
2020/10/03 00:31:11	start radarr: start version 20200921-11 failed, result 272
2020/10/03 00:34:13	start radarr: begin to start version 20200921-11
2020/10/03 00:34:13	start radarr 20200921-11 Begin pre-load apparmor
2020/10/03 00:34:13	start radarr 20200921-11 End pre-load apparmor ret=[0]
2020/10/03 00:34:14	start radarr 20200921-11 Begin start-stop-status start
2020/10/03 00:34:34	start radarr 20200921-11 End start-stop-status start ret=[1]
2020/10/03 00:34:34	(system) trigger radarr 20200921-11 Begin start-stop-status stop
2020/10/03 00:34:34	(system) trigger radarr 20200921-11 End start-stop-status stop ret=[0]
2020/10/03 00:34:34	(system) trigger radarr 20200921-11 Begin unload apparmor
2020/10/03 00:34:34	(system) trigger radarr 20200921-11 End unload apparmor ret=[0]
2020/10/03 00:34:35	stop radarr: begin to stop version 20200921-11
2020/10/03 00:34:35	stop radarr: stop version 20200921-11 successfully, result 0
2020/10/03 00:34:35	start radarr: start version 20200921-11 failed, result 272
```

**Comment by BenjV** [comment]
Verison 3 is not installed via a SynoCommunity package, so you should ask the Radar developers.

**Comment by Epyon83** [comment]
> Verison 3 is not installed via a SynoCommunity package, so you should ask the Radar developers.
> 
> A package just reads the pidfile created by Radarr and send a TERM signal to that process Id.
> If after 20 seconds the process is still running it kills the process with that process ID.
> All very simpel, so you should ask the Radarr developers.

You are right, I used the internal update function of Radarr to update it to the latest version, I did that for the past 2 years or more, also for Sonarr. Seems I missed the changelog and updated to v3 accidentally. Now I have to figure out how to roll back or reinstall without losing config etc. 
Radarr devs are silent about the issue; reported it on Reddit. But still, thanks for your reply.

**Comment by BenjV** [comment]
And Version 3 is still a development version and not a released version.
So you knew the risk.

**Comment by mbnn** [comment]
Version 3 is final now though ;) https://github.com/Radarr/Radarr

**Comment by houndtt** [comment]
I believe this may be related to the PID file change for V3. You can try these steps to test if it can workaround your issue: https://github.com/SynoCommunity/spksrc/issues/3987#issuecomment-738735358

**Comment by houndtt** [comment]
Hey @Epyon83, I've created a new Radarr v3 build which I believe will resolve this issue, do feel free to check it out here: https://github.com/SynoCommunity/spksrc/issues/3987#issuecomment-742138208

**Comment by bakerboy448** [comment]
this can be closed I'm pretty sure
