### ISSUE TITLE
Transmission 3.0 causes tracker to fail to connect

### ISSUE THREAD

**Issue by przemek808** [SynoCommunity/spksrc#4202]
_For new Package Requests, see the guidelines_  

### Setup
Package Name: Transmission
Package Version: 3.0.-18

NAS Model: DS916+
NAS Architecture: x86_64 (INTEL Pentium N3710)
DSM version: DSM 6.2.3-25426 Update 2

### Expected behavior
Tracker should connect successfully, as it was with the old 2.9.X version.

### Actual behavior
The status of tracker is just "Could not connect to tracker" without other additional information

### Steps to reproduce
1.  Update to 3.00-18

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```[2020-10-02 12:40:29.528] Transmission 3.00 (bb6b5a062e) started (session.c:769)
[2020-10-02 12:40:29.528] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:956)
[2020-10-02 12:40:29.528] RPC Server Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (rpc-server.c:1244)
[2020-10-02 12:40:29.528] RPC Server Password required (rpc-server.c:1254)
[2020-10-02 12:40:29.528] UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:97)
[2020-10-02 12:40:29.528] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:99)
[2020-10-02 12:40:29.528] UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:105)
[2020-10-02 12:40:29.528] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:107)
[2020-10-02 12:40:29.528] Using settings from "/volume1/@appstore/transmission/var/" (daemon.c:646)
[2020-10-02 12:40:29.528] Saved "/volume1/@appstore/transmission/var/settings.json" (variant.c:1221)
[2020-10-02 12:40:29.528] Saved pidfile "/volume1/@appstore/transmission/var/transmission.pid" (daemon.c:662)
[2020-10-02 12:40:29.528] transmission-daemon requiring authentication (daemon.c:674)
[2020-10-02 12:40:29.528] Watching "xxx" for new .torrent files (daemon.c:698)
[2020-10-02 12:40:29.528] Loaded 282 torrents (session.c:2170)
[2020-10-02 12:40:29.528] Port Forwarding (NAT-PMP) initnatpmp succeeded (0) (natpmp.c:73)
[2020-10-02 12:40:29.528] Port Forwarding (NAT-PMP) sendpublicaddressrequest succeeded (2) (natpmp.c:73)
[2020-10-02 12:40:29.528] Port Forwarding (UPnP) Found Internet Gateway Device "http://someIP:49000/igdupnp/control/WANIPConn1" (upnp.c:200)
[2020-10-02 12:40:29.528] Port Forwarding (UPnP) Local Address is "someIP" (upnp.c:201)
[2020-10-02 12:40:29.528] Port Forwarding (UPnP) Port forwarding through "http://someIP:49000/igdupnp/control/WANIPConn1", service "urn:schemas-upnp-org:service:WANIPConnection:1". (local address: someIP:52882) (upnp.c:276)
[2020-10-02 12:40:29.528] Port Forwarding State changed from "Not forwarded" to "Starting" (port-forwarding.c:107)
[2020-10-02 12:40:29.528] web will verify tracker certs using envvar CURL_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt (web.c:456)
[2020-10-02 12:40:29.528] web NB: this only works if you built against libcurl with openssl or gnutls, NOT nss (web.c:457)
[2020-10-02 12:40:29.528] web NB: invalid certs will show up as 'Could not connect to tracker' like many other errors (web.c:458)
[2020-10-02 12:40:29.528] Port Forwarding State changed from "Starting" to "???" (port-forwarding.c:107)
[2020-10-02 12:40:30.490] xxx Could not connect to tracker (announcer.c:1085)
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
2020-09-07T12:06:33+02:00 JAS synoscgi_SYNO.Core.Package.Installation_1_install[10484]: resource_api.cpp:289 Release service-cfg for transmission when 0x0002 (done)
2020-09-07T12:06:40+02:00 JAS synoscgi_SYNO.Core.Package.Installation_1_install[11361]: resource_api.cpp:190 Acquire service-cfg for transmission when 0x0002 (done)
---
2020/09/07 12:06:11 upgrade transmission: begin to stop version 2.94-16
2020/09/07 12:06:11 upgrade transmission 2.94-16 Begin start-stop-status stop
2020/09/07 12:06:12 upgrade transmission 2.94-16 End start-stop-status stop ret=[0]
2020/09/07 12:06:12 upgrade transmission 2.94-16 Begin unload apparmor
2020/09/07 12:06:12 upgrade transmission 2.94-16 End unload apparmor ret=[0]
2020/09/07 12:06:12 upgrade transmission: stop version 2.94-16 successfully, result 0
2020/09/07 12:06:13 upgrade transmission 2.94-16 Begin preupgrade
2020/09/07 12:06:33 upgrade transmission 2.94-16 End preupgrade ret=[0]
2020/09/07 12:06:33 upgrade transmission 2.94-16 Begin preuninst
2020/09/07 12:06:33 upgrade transmission 2.94-16 End preuninst ret=[0]
2020/09/07 12:06:33 upgrade transmission 2.94-16 Begin /bin/rm -rf /volume1/@appstore/transmission
2020/09/07 12:06:38 upgrade transmission 3.00-18 End /bin/rm -rf /volume1/@appstore/transmission ret=[0]
2020/09/07 12:06:38 upgrade transmission 3.00-18 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/transmission
2020/09/07 12:06:38 upgrade transmission 3.00-18 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/transmission ret=[0]
2020/09/07 12:06:39 upgrade transmission 3.00-18 Begin /bin/mkdir -p /var/packages/transmission
2020/09/07 12:06:39 upgrade transmission 3.00-18 End /bin/mkdir -p /var/packages/transmission ret=[0]
2020/09/07 12:06:39 upgrade transmission 3.00-18 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/transmission/INFO
2020/09/07 12:06:39 upgrade transmission 3.00-18 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/transmission/INFO ret=[0]
2020/09/07 12:06:39 upgrade transmission 3.00-18 Begin /bin/rm -rf /var/packages/transmission/scripts
2020/09/07 12:06:39 upgrade transmission 3.00-18 End /bin/rm -rf /var/packages/transmission/scripts ret=[0]
2020/09/07 12:06:39 upgrade transmission 3.00-18 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/transmission/scripts
2020/09/07 12:06:39 upgrade transmission 3.00-18 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/transmission/scripts ret=[0]
2020/09/07 12:06:39 upgrade transmission 3.00-18 Begin /bin/rm -rf /var/packages/transmission/WIZARD_UIFILES
2020/09/07 12:06:39 upgrade transmission 3.00-18 End /bin/rm -rf /var/packages/transmission/WIZARD_UIFILES ret=[0]
2020/09/07 12:06:39 upgrade transmission 3.00-18 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/transmission/WIZARD_UIFILES
2020/09/07 12:06:39 upgrade transmission 3.00-18 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/transmission/WIZARD_UIFILES ret=[0]
2020/09/07 12:06:39 upgrade transmission 3.00-18 Begin /bin/rm -rf /var/packages/transmission/conf
2020/09/07 12:06:39 upgrade transmission 3.00-18 End /bin/rm -rf /var/packages/transmission/conf ret=[0]
2020/09/07 12:06:39 upgrade transmission 3.00-18 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/transmission/conf
2020/09/07 12:06:39 upgrade transmission 3.00-18 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/transmission/conf ret=[0]
2020/09/07 12:06:40 upgrade transmission 3.00-18 Begin postinst
2020/09/07 12:06:40 upgrade transmission 3.00-18 End postinst ret=[0]
2020/09/07 12:06:40 upgrade transmission 3.00-18 Begin postupgrade
2020/09/07 12:06:45 upgrade transmission 3.00-18 End postupgrade ret=[0]
2020/09/07 12:06:49 upgrade transmission: begin to start version 3.00-18
2020/09/07 12:06:49 upgrade transmission 3.00-18 Begin pre-load apparmor
2020/09/07 12:06:49 upgrade transmission 3.00-18 End pre-load apparmor ret=[0]
2020/09/07 12:06:49 upgrade transmission 3.00-18 Begin start-stop-status start
2020/09/07 12:06:50 upgrade transmission 3.00-18 End start-stop-status start ret=[0]
2020/09/07 12:06:50 upgrade transmission: start version 3.00-18 successfully, result 0
2020/09/07 12:06:51 upgrade transmission from 2.94-16 to 3.00-18 successfully
2020/09/07 12:06:51 upgrade transmission 3.00-18 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2020/09/07 12:06:51 upgrade transmission 3.00-18 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2020/09/07 12:06:55 install transmission: begin to start version 3.00-18
2
```

**Comment by przemek808** [comment]
running a curl on the NAS to the tracker announce address returns this result:

TLSv1.2 (OUT), TLS header, Certificate Status (22):
TLSv1.2 (OUT), TLS handshake, Client hello (1):
TLSv1.2 (IN), TLS handshake, Server hello (2):
TLSv1.2 (IN), TLS handshake, Certificate (11):
TLSv1.2 (OUT), TLS alert, Server hello (2):
SSL certificate problem: unable to get local issuer certificate
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, the certificate verification probably failed due to a
problem with the certificate (it might be expired, or the name might
not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.

**Comment by hgy59** [comment]
This might be an issue with TLSv1.3. As this is WIP on #4155 I published a prerelase of the current source in my fork (https://github.com/hgy59/spksrc/releases/tag/transmission-update-openssl)

Can you provide the tracker url that you used to show the error messages?

**Comment by przemek808** [comment]
@hgy59 This is a private tracker so I can't share the domain in public.

**Comment by BenjV** [comment]
More likely you have a self signed certificate in your system installed and transmission will find that and use it and the tracker does not accept a self signed certificate.

I have tested this transmission version without experiencing any such issue.

**Comment by przemek808** [comment]
@BenjV it worked with the 2.9. I did not change any certificates.
I have installed 2 certificates. One from Let's Encrypt and one from Synology, which is self signed. I will try deleting the synology certificate.

**Comment by BenjV** [comment]
Don't delete those certificates.
Just move them both to a temporary location so you can test if this is the problem and if not move them back if it was not the problem.

And of course just deleting one self signed certificate has not much use.

**Comment by przemek808** [comment]
I installed Version: 3.0.-19 and still no change.
Any idea when the fix from #4155 will be available in an installable package?

**Comment by hgy59** [comment]
@przemek808 #4155 is integrated into the currently published version 3.00-19.

**Comment by przemek808** [comment]
@BenjV sorry, I somehow missed your last comment.
I tried this out and got this

`CONNECTED(00000004)                                                                                                                                                                                              depth=0 CN = *.tracker.domain                                                                                                                                                                                      verify error:num=20:unable to get local issuer certificate                                                                                                                                                       verify return:1                                                                                                                                                                                                  depth=0 CN = *.tracker.domain                                                                                                                                                                                      verify error:num=21:unable to verify the first certificate                                                                                                                                                       verify return:1                                                                                                                                                                                                  ---                                                                                                                                                                                                              Certificate chain                                                                                                                                                                                                 0 s:CN = *.tracker.domain                                                                                                                                                                                            i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = Encryption Everywhere DV TLS CA - G1 
---                                                                                                                                                                                                              No client certificate CA names sent                                                                                                                                                                              Peer signing digest: SHA256                                                                                                                                                                                      Peer signature type: RSA                                                                                                                                                                                         Server Temp Key: ECDH, P-256, 256 bits                                                                                                                                                                           ---                                                                                                                                                                                                              SSL handshake has read 2136 bytes and written 440 bytes                                                                                                                                                          Verification error: unable to verify the first certificate                                                                                                                                                       ---                                                                                                                                                                                                              New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384                                                                                                                                                              Server public key is 2048 bit                                                                                                                                                                                    Secure Renegotiation IS supported                                                                                                                                                                                Compression: NONE                                                                                                                                                                                                Expansion: NONE                                                                                                                                                                                                  No ALPN negotiated                                                                                                                                                                                               SSL-Session:                                                                                                                                                                                                         Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID:                                                                                                                                      
Session-ID-ctx:
    Master-Key: 
PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    Start Time: 1604679477
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)                                                                                                                                                  Extended master secret: no
---`

**Comment by BenjV** [comment]
Zoals je ziet wordt je self signed certificate geweigerd.

**Comment by przemek808** [comment]
It worked in the 2.9 versions and I did not touch that config. 
Can you @BenjV help me fixing this. I have absolutely no idea which certificate transmission uses.

**Comment by BenjV** [comment]
https://curl.haxx.se/docs/sslcerts.html

**Comment by mreid-tt** [comment]
Hi @przemek808, it looks like this issue has been open for some time without any recent updates. Since then, a new version of Transmission (v4.0.3-22) has been released which may have resolved this issue. Can you please test with the latest version and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!
