### ISSUE TITLE
Syncthing package not working after update on DS916+

### ISSUE THREAD

**Issue by Tomagori** [SynoCommunity/spksrc#4212]
### Setup
_Package Name:_ Syncthing
_Package Version:_ 1.7.1-20

_NAS Model:_ DS916+
_NAS Architecture:_ braswell (x64)
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
Clicking on run package should start syncthing

### Actual behavior
After running for a brief moment the package is stopped again after about 2 seconds

### Steps to reproduce
_1._ Install syncthing from DSM GUI
_2._ Run it

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Sat Oct 10 14:38:52 CEST 2020
Starting syncthing command /volume1/@appstore/syncthing/bin/syncthing -home=/volume1/@appstore/syncthing/var
```
#### Other logs
`/var/log/synopkg.log` shows the following
```
2020/10/10 14:28:48 start syncthing: begin to stop version 1.7.1-20
2020/10/10 14:28:48 start syncthing 1.7.1-20 Begin start-stop-status stop
2020/10/10 14:28:48 start syncthing 1.7.1-20 End start-stop-status stop ret=[0]
2020/10/10 14:28:48 start syncthing 1.7.1-20 Begin unload apparmor
2020/10/10 14:28:48 start syncthing 1.7.1-20 End unload apparmor ret=[0]
2020/10/10 14:28:48 start syncthing: stop version 1.7.1-20 successfully, result 0
2020/10/10 14:28:49 start syncthing: begin to start version 1.7.1-20
2020/10/10 14:28:49 start syncthing 1.7.1-20 Begin pre-load apparmor
2020/10/10 14:28:49 start syncthing 1.7.1-20 End pre-load apparmor ret=[0]
2020/10/10 14:28:49 start syncthing 1.7.1-20 Begin start-stop-status start
2020/10/10 14:28:49 start syncthing 1.7.1-20 End start-stop-status start ret=[0]
2020/10/10 14:28:49 start syncthing: start version 1.7.1-20 successfully, result 0
```
This is only happening since updating to v1.7.1-20. I'd appreciate any and all help

**Comment by 0x4a** [comment]
+1, have the same issue.

Also, the link to the syncthing-webinterface is missing from package-center

**Comment by pakro** [comment]
I'm also having this issue with a DS1517+.

**Comment by Magissia** [comment]
syncthing.log is not very talkative too :

```
Sun Oct 25 01:05:15 CEST 2020
Starting syncthing command /volume1/@appstore/syncthing/bin/syncthing -home=/volume1/@appstore/syncthing/var

```
Yes, that's it.
Two lines.

**Comment by acolomb** [comment]
The link is only shown when the package service is running, so that is an understandable consequence.

I don't have any idea what might be going wrong here, as my two NASes run the current package just fine.

Maybe try to enable Syncthing's own internal log through command line switches in `/var/packages/syncthing/target/var/options.conf`.  This is disabled by default but should indicate valuable error messages.  There might also be panic files in the same directory.

**Comment by Magissia** [comment]
Resolved for me, but unable to reproduce fix in a reliable way.
Copied whole Syncthing config and restored file by file, restarting syncthing after each file restore.

**Comment by BlackFloyd** [comment]
I had the same issue on my (t)rusty old DS213j. I tried running `/var/packages/syncthing/target/bin/syncthing` manually (which is probably a bad idea but yolo). I first ran it as root (yes, I know - it wasn't intentional) and then as sc-syncthing. Both times it seemed to perform an initial setup because I did not supply any configuration but somehow one of those two (probably the latter) seems to have fixed the issue.
I can now launch it using the Package Manager again. No idea what was going on...

The outputs of the two launches seem absolutely normal to me but I can supply them if you think they could help...

**Comment by plafue** [comment]
I can confirm that connecting via ssh to the machine, and then running
```
$ sudo su sc-syncthing -s /bin/bash
bash-4.3$ cd /var/packages/syncthing/target/bin/
bash-4.3$ ./syncthing
```
did something that allowed syncthing to "stay up". I can also launch it using the Package manager again.

FWIW: Some of the output (up to starting discovery) of the run that fixed the problem looks as follows:

```
[monitor] 12:45:48 INFO: Default folder created and/or linked to new config
[start] 12:45:49 INFO: syncthing v1.7.1 "Fermium Flea" (go1.14.6 linux-amd64) root@e2bd3b8155c2 2020-08-01 07:57:34 UTC
[start] 12:45:49 INFO: Generating ECDSA key and certificate for syncthing...
[start] 12:45:49 INFO: Default folder created and/or linked to new config
[start] 12:45:49 INFO: Default config saved. Edit /var/packages/syncthing/target/.config/syncthing/config.xml to taste (with Syncthing stopped) or
use the GUI
[start] 12:45:49 INFO: Upgrade available (current "v1.7.1" < latest "v1.11.1")
[start] 12:45:52 INFO: Upgraded to "v1.11.1", exiting now.
[monitor] 12:45:52 INFO: Restarting monitor...
[start] 12:45:52 INFO: syncthing v1.11.1 "Fermium Flea" (go1.15.3 linux-amd64) teamcity@build.syncthing.net 2020-11-03 11:29:54 UTC
[start] 12:45:52 INFO: Archiving a copy of old config file format at: /var/packages/syncthing/target/.config/syncthing/config.xml.v31
```

**Comment by acolomb** [comment]
That sounds like useful information.  Apparently the invocation from command line finally succeeded in upgrading to the most recent version using the Syncthing built-in upgrade machinery.  So apparently that part didn't work when you were trying to start it from the Package Manager.  Now the question remains why is that?  Would be great to get some logs after a fresh package installation, during the first service starting.  You can adjust the configuration file to enable logging to a file for catching the output.  See my [previous comment](https://github.com/SynoCommunity/spksrc/issues/4212#issuecomment-719991537).

**Comment by duncanam** [comment]
> I can confirm that connecting via ssh to the machine, and then running
> 
> ```
> $ sudo su sc-syncthing -s /bin/bash
> bash-4.3$ cd /var/packages/syncthing/target/bin/
> bash-4.3$ ./syncthing
> ```
> 
> did something that allowed syncthing to "stay up". I can also launch it using the Package manager again.
> 
> FWIW: Some of the output (up to starting discovery) of the run that fixed the problem looks as follows:
> 
> ```
> [monitor] 12:45:48 INFO: Default folder created and/or linked to new config
> [start] 12:45:49 INFO: syncthing v1.7.1 "Fermium Flea" (go1.14.6 linux-amd64) root@e2bd3b8155c2 2020-08-01 07:57:34 UTC
> [start] 12:45:49 INFO: Generating ECDSA key and certificate for syncthing...
> [start] 12:45:49 INFO: Default folder created and/or linked to new config
> [start] 12:45:49 INFO: Default config saved. Edit /var/packages/syncthing/target/.config/syncthing/config.xml to taste (with Syncthing stopped) or
> use the GUI
> [start] 12:45:49 INFO: Upgrade available (current "v1.7.1" < latest "v1.11.1")
> [start] 12:45:52 INFO: Upgraded to "v1.11.1", exiting now.
> [monitor] 12:45:52 INFO: Restarting monitor...
> [start] 12:45:52 INFO: syncthing v1.11.1 "Fermium Flea" (go1.15.3 linux-amd64) teamcity@build.syncthing.net 2020-11-03 11:29:54 UTC
> [start] 12:45:52 INFO: Archiving a copy of old config file format at: /var/packages/syncthing/target/.config/syncthing/config.xml.v31
> ```

Running these three lines in ssh, control-c ing, and then exiting and re-running from the Package Manager also solved this for me, thanks. Super odd.

**Comment by hgy59** [comment]
Did anyone reboot (restart) the diskstation after that update? It might solve this issue.

**Comment by Larostos** [comment]
@hgy59 I rebooted the system multiple times to no effect. The only thing "fixing" the issue, in the end, was a full reinstall.

**Comment by BlackFloyd** [comment]
Same here - reboots unfortunately did nothing... The only thing that helped was that manual launch.

**Comment by hgy59** [comment]
This issue is outdated as version 1.17.0 is published now.
 Should occur problems with newer version of syncthing, please create a new issue.

**Comment by timosperisen** [comment]
I had the same issue when upgrading the package from 1.17.* to 1.19.0-25 . 
Running syncthing via ssh temporarily and then starting it from the frontend seemed to fix the issue, too.
