### ISSUE TITLE
Latest Mediainfo 20.03 is reporting as 19.09

### ISSUE THREAD

**Issue by boretom** [SynoCommunity/spksrc#4216]
Since the DS920+ is a geminilake CPU I do have to manually install some packages, MediaInfo being one of them.

### Setup
_Package Name:_ Mediainfo
_Package Version:_ 20.03-10

_NAS Model:_ DS920+
_NAS Architecture:_ geminilake/x86_64
_DSM version:_ 6.2.3-25426 Update 2

### Expected behavior
`$ mediainfo --version`
MediaInfo Command line, 
MediaInfoLib - v20.03

### Actual behavior
`$ mediainfo --version`
MediaInfo Command line, 
MediaInfoLib - v19.09

### Steps to reproduce
_1._ Install mediainfo.v10.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-grantley-purley-kvmx64-x86-x86_64].spk from [Mediainfo@SynoComm](https://synocommunity.com/package/mediainfo)
_2._ Login in to NAS using SSH
_3._ run `mediainfo --version`

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Mon Oct 12 17:12:36 CEST 2020
===> Step preinst. USER= GROUP= SHARE_PATH=
Mon Oct 12 17:12:37 CEST 2020
===> Step postinst. USER= GROUP= SHARE_PATH=
Invoke service_create_links
create link: /usr/local/bin/mediainfo -> /volume1/@appstore/mediainfo/bin/mediainfo
```

**Comment by th0ma7** [comment]
There was a dependency that wasn't updated part of the last build.
This upcoming PR #4209 for rutorrent includes updates for mediainfo.
Updated package to follow in the next few days/weeks.

**Comment by boretom** [comment]
@th0ma7 perfect. Thanx for looking into it!

**Comment by vjayer** [comment]
I don't know where to ask, but is synocommunity pkg of mediainfo the cli version only?
Is there a GUI version, either standalone or intergrated into File Station?

**Comment by boretom** [comment]
@vjayer, this is the cli version only. Not sure a Web-Gui does exist for it.

**Comment by th0ma7** [comment]
New version published as part of Fall 2020 security package update #4211 
Updated package should be available in the next few days.
Closing.
