### ISSUE TITLE
FFMPEG: Play opus format video

### ISSUE THREAD

**Issue by tamkenrick** [SynoCommunity/spksrc#4228]
_For new Package Requests, see the guidelines_  

### Setup
Package Name: FFMPEG Package

NAS Model:DS218play

### Expected behavior
Able to play opus format in video station

### Actual behavior
Only DTS, EAC3 video can be play, while opus cannot play through video station

### Step to reproduce
1. Uninstaller Video Station
2. Install FFMPEG package
3. Install Video Station 2.3.4
4.Play the video with opus audio codec

**Comment by BenjV** [comment]
Seems to me that to be able to play audio that needs a opus encoder by means op Video Station this issue is a Vdeo Station issue and not a ffmpeg issue.

Video Station needs to call ffmpeg with the correct encoder.

**Comment by tamkenrick** [comment]
Will there be any documentation about how to call opus encoder in ffmpeg? So that I can better learn from it.

**Comment by BenjV** [comment]
https://ffmpeg.org/ffmpeg.html

But that won't help you.
If Video Station does not support the opus audio codec it will not use the codec available in ffmpeg.
And Video Station is a closed application from Synology themselves so that is no open source

**Comment by th0ma7** [comment]
Current ffmpeg do support opus:
```
$ ffmpeg -codecs | grep -i opus
 D.A.L. opus                 Opus (Opus Interactive Audio Codec)
```
We do not support ffmpeg usage through VideoStation as Synology provide its own set of ffmpeg binaries.  Although feel free to reach out to Synology to fix issue on their end.
