### ISSUE TITLE
Apollolake package for Feng Office requested

### ISSUE THREAD

**Issue by jmapoz** [SynoCommunity/spksrc#4230]
I can see Feng Office packages available for other architectures, but not for Apollolake.  Can this be made available for Apollolake to run on the DS918+?

Thanks in advance

_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Feng Office 
_Package Version:_ v2.5.1.2-3

_NAS Model:_ DS918+
_NAS Architecture:_ Apollolake
_DSM version:_ 6.2.3

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
Feng Office has not been packaged since 2015 and has to be migrated to DSM 6.

**Comment by hgy59** [comment]
feng office community edition is available on github since 2018 https://github.com/fengoffice/fengoffice

@mreid-tt since you fixed mysql integration (AFAICR in firefox sync server) shall we give the feng office package a try?

**Comment by mreid-tt** [comment]
> feng office community edition is available on github since 2018 https://github.com/fengoffice/fengoffice
> 
> @mreid-tt since you fixed mysql integration (AFAICR in firefox sync server) shall we give the feng office package a try?

Certainly, @hgy59, I'd be happy to assist. Please address the recent inquiry and/or give approval for Kavita so that we can proceed with the publication of the package.
