### ISSUE TITLE
[Package Request] Mylar 3

### ISSUE THREAD

**Issue by WedgeSparda** [SynoCommunity/spksrc#4232]
Name: Mylar 3
Description: New version of Mylar, an automated Comic Book (cbr/cbz) downloader program for use with NZB and torrents 
Website: https://forum.mylarcomics.com/
Software documentation: https://github.com/mylar3/mylar3
Build/Installation documentation: https://github.com/mylar3/mylar3
Source Code: https://github.com/mylar3/mylar3
License: GNU General Public License v3.0

**Comment by WedgeSparda** [comment]
Any update about this?

**Comment by Aimhere2k** [comment]
I'd also like to see the Mylar SC package updated to the Python3 version. I'd hate to have to install it by hand and mess something up...

**Comment by WedgeSparda** [comment]
Installed via Docker
