### ISSUE TITLE
autossh fails siliently

### ISSUE THREAD

**Issue by andrewchenshx** [SynoCommunity/spksrc#4250]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ SynoCli Network Tools
_Package Version:_ 1.5-5

_NAS Model:_ DS720+
_NAS Architecture:_ geminilake  x86_64
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
(1)command line output
(2)ssh tunnel established

### Actual behavior
the autossh command exited siliently without any message, and ssh tunnel was not established.  

### Steps to reproduce
_1._ install the SynoCli Network Tools
_2._ ssh login to nas (ssh 192.168.1.9 -p 222)
_3._ sudo -i
_4._ autossh (output the help as expected)
_5._ autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -i /volume1/data/_rsa -R 0.0.0.0:6690:127.0.0.1:6690 -p 2222 nas_tunnel@remote_ip
this command finished without any error massage, but no tunnel was established
#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
@andrewchenshx can you please test this issue with the updated synocli-net v1.5-6?

**Comment by Xiut** [comment]
Unfortunately I have the same problem. After a long time of trial and error maybe I got a hint for the error with AUTOSSH_DEBUG=7:

On my DS218play
Realtek RTD1296 SoC
DSM 6.2.3-25426 Update 2
```
autossh[12214]: port set to 0, monitoring disabled
autossh[12214]: checking for grace period, tries = 0
autossh[12214]: starting ssh (count 1)
autossh[12214]: ssh child pid is 12215
autossh[12214]: check on child 12215
autossh[12214]: clear alarm timer (0 secs left)
autossh[12214]: set alarm for 600 secs
autossh[12215]: child of 12214 execing /spksrc/spk/synocli-net/work-aarch64-6.1/install/var/packages/synocli-net/target/bin
autossh[12215]: /spksrc/spk/synocli-net/work-aarch64-6.1/install/var/packages/synocli-net/target/bin: No such file or directory
autossh[12214]: received signal to exit (15)
autossh[12214]: clear alarm timer (600 secs left)
```


On my DS412+
INTEL Atom D2700
DSM 6.2.3-25426 Update 2
```
autossh[13405]: port set to 0, monitoring disabled
autossh[13405]: checking for grace period, tries = 0
autossh[13405]: starting ssh (count 1)
autossh[13405]: ssh child pid is 13406
autossh[13405]: check on child 13406
autossh[13406]: child of 13405 execing /spksrc/spk/synocli-net/work-x64-6.1/install/var/packages/synocli-net/target/bin
autossh[13405]: clear alarm timer (0 secs left)
autossh[13405]: set alarm for 600 secs
autossh[13406]: /spksrc/spk/synocli-net/work-x64-6.1/install/var/packages/synocli-net/target/bin: No such file or directory
autossh[13405]: received signal to exit (15)
autossh[13405]: clear alarm timer (600 secs left)
```

**Comment by th0ma7** [comment]
@hgy59 I might have found where the issue is, changing `ac_cv_path_ssh=$(STAGING_INSTALL_PREFIX)/bin` to `CONFIGURE_ARGS += ac_cv_path_ssh=$(INSTALL_PREFIX)/bin` in the `Makefile` ensures the binary to points to the appropriate path from the `strings` output after build.

**Comment by th0ma7** [comment]
@Xiut I've uploaded testing packages for your NAS arches at https://github.com/th0ma7/synology/tree/master/packages/xiut
Let me know if it solves your issue.

**Comment by Xiut** [comment]
@th0ma7 Thank you.  On my DS218Play I get now following:
```
autossh[6522]: port set to 0, monitoring disabled
autossh[6522]: checking for grace period, tries = 0
autossh[6522]: starting ssh (count 1)
autossh[6522]: ssh child pid is 6524
autossh[6522]: check on child 6524
autossh[6522]: clear alarm timer (0 secs left)
autossh[6522]: set alarm for 600 secs
autossh[6524]: child of 6522 execing /var/packages/synocli-net/target/bin
autossh[6524]: /var/packages/synocli-net/target/bin: Permission denied
autossh[6522]: received signal to exit (15)
autossh[6522]: clear alarm timer (600 secs left)
```
With and without sudo. 

Maybe I did something wrong?

**Comment by th0ma7** [comment]
@Xiut thnx for testing it out.  I might have found out why... Test #2 available in my repository using same file name.

**Comment by Xiut** [comment]
@th0ma7 I have now tested it with my DS412+ and it looks good, seems to work. The tunnel is now built correctly and an autossh and ssh process is started.

Thank you!

**Comment by th0ma7** [comment]
Great, thnx for testing.  Official package being uploaded online.  Cheers!
