### ISSUE TITLE
SABNZB 3.1 Fails to start on Synology 1019

### ISSUE THREAD

**Issue by bcook177** [SynoCommunity/spksrc#4253]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ SABNZB
_Package Version:_ 3.1.0.44

_NAS Model:_  DS1019+
_NAS Architecture:_ 
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
Tell us what should happen - The package should start

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._  Installed new 3.1.0.44 Update
_2._  Start Service and it fails to start.
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
sh-4.3# cat sabnzbd.log 
Mon Nov  2 16:41:37 MST 2020
Starting sabnzbd command env LANG=en_US.UTF-8 /volume1/@appstore/sabnzbd/env/bin/python3 /volume1/@appstore/sabnzbd/share/SABnzbd/SABnzbd.py -f /volume1/@appstore/sabnzbd/var/config.ini --pidfile /volume1/@appstore/sabnzbd/var/sabnzbd.pid -d 
Not all required Python modules are available, please check requirements.txt
Missing module: sgmllib
You can read more at: https://sabnzbd.org/python3
If you still experience problems, remove all .pyc files in this folder and subfolders
sh-4.3# 
```

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
2020-11-02T16:23:43-07:00 NAS kernel: [   25.747640] Disabling lock debugging due to kernel taint
2020-11-02T16:32:02-07:00 NAS [  533.386765] init: pkgctl-sabnzbd pre-start process (11132) terminated with status 1
2020-11-02T16:32:02-07:00 NAS synoscgi_SYNO.Core.Package.Control_1_start[9898]: servicecfg_internal_lib.c:22 Failed to start job [pkgctl-sabnzbd][0xD900 manager.cpp:204]
2020-11-02T16:32:03-07:00 NAS synoscgi_SYNO.Core.Package.Control_1_start[9898]: pkgstartstop.cpp:371 Failed to start pkgctl-sabnzbd (err=-1) [0xD900 manager.cpp:204]
```

**Comment by Cpuroast** [comment]
Please update to 3.1.0.45.

The initial version of 3.1.0 for Synlogy was broken, see https://github.com/SynoCommunity/spksrc/commit/1be33472a119fd72ee4eb63f013681c6f42d752c

**Comment by dal221** [comment]
Ah, this will explain my same issue.  My Diskstation showed an update to -44 but it refuses to start since.  How do I force the update to -45?  Will this be pushed out again to the packages section of DSM or will I have to do it manually?  If manually... how do I do that?

**Comment by aidanwardman** [comment]
I would also like to know how to update to -45 , the available version is -44 as mentioned above

**Comment by aidanwardman** [comment]
It looks like -45 is now available through package center FYI

**Comment by dal221** [comment]
Interesting. There's no updates showing for me just yet. I'll give it a bit of time.

**Comment by haydg** [comment]
I have just successfully updated via DSM package centre and it is running again

**Comment by dal221** [comment]
that's great news, that it works again.  Just need to wait on the package appearing.  I'm in the UK... not sure if that makes a difference. 

You didn't need to reboot the Synology device or anything similar?

**Comment by haydg** [comment]
just hit the refresh in the DSM UI and then update, no restart needed.
I am UK based too

**Comment by dal221** [comment]
It's finally just appeared! Took it's time! :)

**Comment by bcook177** [comment]
Thanks updating to -45 worked perfectly.
