### ISSUE TITLE
[Package Request] gitea Server

### ISSUE THREAD

**Issue by hackxiu** [SynoCommunity/spksrc#4256]
Name: gitea
Description: The goal of this project is to make the easiest, fastest, and most painless way of setting up a self-hosted Git service. Using Go, this can be done with an independent binary distribution across all platforms which Go supports, including Linux, macOS, and Windows on x86, amd64, ARM and PowerPC architectures. Want to try it before doing anything else? Do it with the online demo! This project has been forked from Gogs since 2016.11 but changed a lot.

Website: https://docs.gitea.io/en-us/

Software documentation: https://docs.gitea.io/en-us/

Build/Installation documentation: https://docs.gitea.io/en-us/

Source Code: https://github.com/go-gitea/gitea

License: https://github.com/go-gitea/gitea/blob/master/LICENSE
..............................................................................................................................................................
SPK source code written

Post directly to the community, please manage and approve

Project address: https://github.com/jboxberger/synology-gitea-jboxberger

**Comment by hgy59** [comment]
Links: _https://github.com/SynoCommunity/spksrc/pull/3670#issuecomment-477482199_, #1522
