### ISSUE TITLE
Can't remove Jappix

### ISSUE THREAD

**Issue by dosch** [SynoCommunity/spksrc#4265]
### Setup
_Package Name:_ Jappix
_Package Version:_ 1.0.1-2

_NAS Model:_ DS220+
_NAS Architecture:_ Intel
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
I installed Web Station and added my HTML files to the www folder in my home directory. I expect to see my website. 

### Actual behavior
When I try to open that website in a browser, I get the installation screen for Jappix. 

### Steps to reproduce
I can't say. I (think I) installed Jappix in the past. But am not sure.

#### Package log
no relevant logs can be found...

**Comment by hgy59** [comment]
@dosch do you still have this issue?
I suppose the uninstall of jappix didn't complete sucessfully.
So login as admin with ssh to your diskstation and:
1. remove jappix installation with `rm -rf /var/packages/jappix`
2. remove jappix web ui integration with `rm -rf /usr/syno/synoman/webman/3rdparty/jappix` - this is normally a link to the app (or similar) folder in /var/packages/jappix/target/app

**Comment by dosch** [comment]
hey @hgy59, thnx for your answer and your solution. Sadly it does not help me... I checked `/var/packages/` and `/usr/syno/synoman/webman/3rdparty/` with `ls -la` and in both there is no jappix directory...

**Comment by hgy59** [comment]
@dosch did you check the /var/services/web folder?
_Just had this issue with adminer running in /var/services/web/adminer on a diskstation with DSM7 beta. The package was not installed anymore but the application was still running there._

**Comment by dosch** [comment]
@hgy59 I am sorry to say we will never know if your tip would have worked.

In the meantime I installed the DSM7 beta and reinstalled Webstation... and now Jappix has vanished...
