### ISSUE TITLE
Synocommunity Sonarr and NZBget permissions issues (seen an old post but could not resolve.

### ISSUE THREAD

**Issue by dobage** [SynoCommunity/spksrc#4271]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ NZBget, Sonarr
_Package Version:_  21 and 2.0.0.5344

_NAS Model:_ 1019+
_NAS Architecture:_ File shares
_DSM version:_ DSM 6.2.3-25436 U2

### Expected behavior
Sonarr passes an NZB to NZBget and the file should download and extract.  Manual upload of an NZB file works correctly.

### Actual behavior
If I do something through Sonarr it will send it to NZBget and download it but fails on the unrar (Unpack for file name here failed. Also shows Unrar error code: 9 and Could not create directory /Public/tv/file name here/_unpack: could not create directory). I added the switch "x -ai" no change.

### Steps to reproduce
tested with a number of Sonarr added NZB files
I have my downloads directory set to admin (now but also tried sc-download) as owner. sc-download, sc-radarr, sc-nzbdrone, sc-nzbget all have rw to the download directory. I see on another post talking about owner = admin group = sc-download (I do not see the group option)

. I can tell by the errors it is a permissions issue just can not figure it out. 

#### Package log

[Info] RssSyncService: Starting RSS Sync
[Warn] HttpClient: HTTP Error - Res: [GET] https://api.oznzb.com/api?t=tvsearch&                                                                                                                                                             cat=5030,5040&extended=1&apikey=c94454f9b5b10ec88a2dae084f3dade5&offset=0&limit=                                                                                                                                                             100: 504.GatewayTimeout
[Warn] Newznab: OZNZB HTTP request failed: [504:GatewayTimeout] [GET] at [https:                                                                                                                                                             //api.oznzb.com/api?t=tvsearch&cat=5030,5040&extended=1&apikey=c94454f9b5b10ec88                                                                                                                                                             a2dae084f3dade5&offset=0&limit=100]
[Info] DownloadDecisionMaker: Processing 400 releases
[Info] RssSyncService: RSS Sync Completed. Reports found: 400, Reports grabbed:                                                                                                                                                              0
[Info] RssSyncService: Starting RSS Sync
[Warn] HttpClient: HTTP Error - Res: [GET] https://api.oznzb.com/api?t=tvsearch&                                                                                                                                                             cat=5030,5040&extended=1&apikey=c94454f9b5b10ec88a2dae084f3dade5&offset=0&limit=                                                                                                                                                             100: 504.GatewayTimeout
[Warn] Newznab: OZNZB HTTP request failed: [504:GatewayTimeout] [GET] at [https:                                                                                                                                                             //api.oznzb.com/api?t=tvsearch&cat=5030,5040&extended=1&apikey=c94454f9b5b10ec88                                                                                                                                                             a2dae084f3dade5&offset=0&limit=100]
[Info] DownloadDecisionMaker: Processing 400 releases
[Info] RssSyncService: RSS Sync Completed. Reports found: 400, Reports grabbed:                                                                                                                                                              0
Wed Nov 25 06:58:10 2020        INFO    Deleting file /volume1/Public/Downloads/nzb/Storage.Wars.S02E01.HDTV.XviD-CRiMSON.nzb.queued
Wed Nov 25 06:58:10 2020        INFO    Collection Storage.Wars.S02E01.HDTV.XviD-CRiMSON removed from history
Wed Nov 25 07:24:27 2020        DETAIL  Downloading nzbget version info
Wed Nov 25 07:24:27 2020        DETAIL  URL http://nzbget.net/info/nzbget-version.json?nocache=1606310667386 redirected to https://nzbget.net/info/nzbget-version.json?nocache=1606310667386
Wed Nov 25 07:24:27 2020        DETAIL  Downloading nzbget version info
Wed Nov 25 07:24:28 2020        DETAIL  Downloading nzbget git revision info
Wed Nov 25 07:24:28 2020        DETAIL  Downloading nzbget git branch info
Wed Nov 25 07:24:29 2020        DETAIL  Downloading nzbget update info
Wed Nov 25 07:24:29 2020        DETAIL  URL http://nzbget.net/info/nzbget-version-linux.json redirected to https://nzbget.net/info/nzbget-version-linux.json
Wed Nov 25 07:24:29 2020        DETAIL  Downloading nzbget update info

Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.interna                                                                                                                                                             l.720p.web.h264-tastetv.sample.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.interna                                                                                                                                                             l.720p.web.h264-tastetv.sample.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.interna                                                                                                                                                             l.720p.web.h264-tastetv.sample.vol15+16.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.interna                                                                                                                                                             l.720p.web.h264-tastetv.vol00+01.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.interna                                                                                                                                                             l.720p.web.h264-tastetv.vol01+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.interna                                                                                                                                                             l.720p.web.h264-tastetv.vol31+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.interna                                                                                                                                                             l.720p.web.h264-tastetv.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.interna                                                                                                                                                             l.720p.web.h264-tastetv.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.interna                                                                                                                                                             l.720p.web.h264-tastetv.vol15+16.par2
Wed Nov 25 07:35:46 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.                                                                                                                                                             720p.WEB.h264-TASTETV added to history
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol15+16.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol00+01.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol01+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol31+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol15+16.par2
Wed Nov 25 07:35:46 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.720p.WEB.h264-TASTETV added to history
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol15+16.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol00+01.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol01+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol31+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol15+16.par2
Wed Nov 25 07:35:46 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.720p.WEB.h264-TASTETV added to history
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol15+16.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol00+01.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol01+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol31+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol15+16.par2
Wed Nov 25 07:35:46 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.720p.WEB.h264-TASTETV added to history
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol15+16.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol00+01.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol01+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol31+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol15+16.par2
Wed Nov 25 07:35:46 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.720p.WEB.h264-TASTETV added to history
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol15+16.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol00+01.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol01+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol31+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol15+16.par2
Wed Nov 25 07:35:46 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.720p.WEB.h264-TASTETV added to history
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol15+16.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol00+01.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol01+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol31+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol15+16.par2
Wed Nov 25 07:35:46 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.720p.WEB.h264-TASTETV added to history
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol15+16.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol00+01.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol01+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol31+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol15+16.par2
Wed Nov 25 07:35:46 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.720p.WEB.h264-TASTETV added to history
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol15+16.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol00+01.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol01+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol31+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol15+16.par2
Wed Nov 25 07:35:46 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.720p.WEB.h264-TASTETV added to history
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.sample.vol15+16.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol00+01.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol01+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol31+02.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol03+04.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol07+08.par2
Wed Nov 25 07:35:46 2020        DETAIL  Parking file storage.wars.s02e29.internal.720p.web.h264-tastetv.vol15+16.par2
Wed Nov 25 07:35:46 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.720p.WEB.h264-TASTETV added to history

admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:36:56 2020        INFO    Queueing Storage.Wars.S02E29.INTERNAL.480p.x264-mSD for post-processing
Wed Nov 25 07:36:56 2020        INFO    Loaded par2-file 54e298c64e11137b87e93586a005d48c.par2 for direct-rename
Wed Nov 25 07:36:56 2020        INFO    Checking renamed files for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD
Wed Nov 25 07:36:56 2020        INFO    Loaded par2-file 54e298c64e11137b87e93586a005d48c.vol0+1.par2 for direct-rename
Wed Nov 25 07:36:56 2020        INFO    No renamed files found for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD
Wed Nov 25 07:36:56 2020        INFO    Reordering files for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD
Wed Nov 25 07:36:56 2020        INFO    Loaded par2-file 54e298c64e11137b87e93586a005d48c.par2 for par-rename
Wed Nov 25 07:36:56 2020        INFO    No renamed files found for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD
Wed Nov 25 07:36:57 2020        INFO    Checking renamed archive files for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD
Wed Nov 25 07:36:57 2020        INFO    No renamed archive files found for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ tail nzbget.log
Wed Nov 25 07:37:00 2020        INFO    Verifying file 54e298c64e11137b87e93586a005d48c.part4.rar
Wed Nov 25 07:37:00 2020        DETAIL  Par: All files are correct, repair is not required.
Wed Nov 25 07:37:00 2020        INFO    Repair not needed for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD/54e298c64e11137b87e93586a005d48c
Wed Nov 25 07:37:00 2020        INFO    Second unpack attempt skipped for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD due to par-check not repaired anything
Wed Nov 25 07:37:00 2020        ERROR   Unpack for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD failed.
Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol00+1.par2
Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol01+2.par2
Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol03+4.par2
Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol07+5.par2
Wed Nov 25 07:37:01 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.480p.x264-mSD added to history
admin@Skynet-storage:/volume1/@appstore/nzbget/var$  INFO    Verifying file 54e298c64e11137b87e93586a005d48c.part4.rar
-sh: INFO: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:00 2020        DETAIL  Par: All files are correct, repair is not required.
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:00 2020        INFO    Repair not needed for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD/54e298c64e11137b87e93586a005d48c
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:00 2020        INFO    Second unpack attempt skipped for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD due to par-check not repaired anything
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:00 2020        ERROR   Unpack for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD failed.
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol00+1.par2
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol01+2.par2
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol03+4.par2
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol07+5.par2
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:01 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.480p.x264-mSD added to history
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$  INFO    Verifying file 54e298c64e11137b87e93586a005d48c.part4.rar
-sh: INFO: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:00 2020        DETAIL  Par: All files are correct, repair is not required.
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:00 2020        INFO    Repair not needed for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD/54e298c64e11137b87e93586a005d48c
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:00 2020        INFO    Second unpack attempt skipped for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD due to par-check not repaired anything
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:00 2020        ERROR   Unpack for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD failed.
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol00+1.par2
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol01+2.par2
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol03+4.par2
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:01 2020        DETAIL  Parking file 54e298c64e11137b87e93586a005d48c.vol07+5.par2
-sh: Wed: command not found
admin@Skynet-storage:/volume1/@appstore/nzbget/var$ Wed Nov 25 07:37:01 2020        INFO    Collection Storage.Wars.S02E29.INTERNAL.480p.x264-mSD added to history
-sh: Wed: command not found
![ds1](https://user-images.githubusercontent.com/65906851/100235179-a8dd3f00-2ef1-11eb-85aa-494261813f8e.png)
![ds2](https://user-images.githubusercontent.com/65906851/100235182-a975d580-2ef1-11eb-8b91-1798fa8835bd.JPG)

Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
Apparently Sonarr is using the folder /volume1/ Public/tv/ as an intermediate location for unrar.
So you need to give the group "sc-download" read/write access to that folder.

**Comment by dobage** [comment]
sc-download has full control of that folder also?

![ds3](https://user-images.githubusercontent.com/65906851/100249917-b5b65e80-2f02-11eb-8999-7423107a4c7a.JPG)

**Comment by dobage** [comment]
From putty

Group Name: [sc-download]

Group Type: [AUTH_LOCAL]

Group ID: [65536]

Group Members:

0: [nzb-admin]

1: [sc-nzbdrone]

2: [sc-nzbget]

3: [sc-radarr]

**Comment by BenjV** [comment]
Check if you still have an old DSM setting that inhibited the use of ACL's
Go to control panel, shared folder, select a folder  and choose the pulldown "Action'
If the command "Convert to Windows ACL" is not grayed out, then you have to convert this share.

Do this for all your shares.

**Comment by dobage** [comment]
Thank you for the feedback.  I am on DSM version: DSM 6.2.3-25436 U2 (current) my NAS was set up less then a year ago.  I did locate the settings and yes it is grayed out.

**Comment by ymartin59** [comment]
Hello
I see no "permission denied" error message in the only log part you have provided, as is:
```
Wed Nov 25 07:37:00 2020 INFO Verifying file 54e298c64e11137b87e93586a005d48c.part4.rar
Wed Nov 25 07:37:00 2020 DETAIL Par: All files are correct, repair is not required.
Wed Nov 25 07:37:00 2020 INFO Repair not needed for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD/54e298c64e11137b87e93586a005d48c
Wed Nov 25 07:37:00 2020 INFO Second unpack attempt skipped for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD due to par-check not repaired anything
Wed Nov 25 07:37:00 2020 ERROR Unpack for Storage.Wars.S02E29.INTERNAL.480p.x264-mSD failed.
Wed Nov 25 07:37:01 2020 DETAIL Parking file 54e298c64e11137b87e93586a005d48c.vol00+1.par2
Wed Nov 25 07:37:01 2020 DETAIL Parking file 54e298c64e11137b87e93586a005d48c.vol01+2.par2
Wed Nov 25 07:37:01 2020 DETAIL Parking file 54e298c64e11137b87e93586a005d48c.vol03+4.par2
Wed Nov 25 07:37:01 2020 DETAIL Parking file 54e298c64e11137b87e93586a005d48c.vol07+5.par2
Wed Nov 25 07:37:01 2020 INFO Collection Storage.Wars.S02E29.INTERNAL.480p.x264-mSD added to history
```

(Other content and "command not found" is a consequence of a copy-paste into shell terminal of lines starting by "INFO" and "Wed")

So it seems there is no permission issue to download file but to "Unpack" already downloaded archive ("Par: All files are correct, repair is not required")

So I have a naive question: would it be possible there is no space left on volume where you have downloaded them?
(notice that nzbget is not an easy to use tool)

**Comment by dobage** [comment]
The volume has about 15 TB free, so that should not be the issue.  I think the way it works is the download happen to the tmp directory (on the same volume) and the rar command is to the /volume1/Public/tv (specified by Sonarr) location and NZBget can not create the directory in that location for permission issues.  If I upload a stand alone NZB to NZBget it will download and extract the file to /volume1/Public/Downloads/downloads with out issue.

**Comment by BenjV** [comment]
The log says :
`-sh: INFO: command not found`
So to me it seams the the unrar command could not be found.
I am not a nzbget user but I installed it on my Test Nas and if I look in the nzbget.conf
I see:
`UnrarCmd=${AppDir}/unrar`

To my best knowledge ${AppDir} is pointing to /var/packages/nzbget/target/bin
And in that folder there is no urar to be found.

So it seem to me that this should be:

`UnrarCmd=unrar x -ai`
or
`UnrarCmd=/usr/bin/unrar x -ai`

**Comment by dobage** [comment]
Thank you for the feedback, I posted I already have added that to the unrar command.

**Comment by mreid-tt** [comment]
Hi there! It looks like this issue has been open for some time without any recent updates. Since then, new versions of Sonarr v3 (v20230217-22) and NZBGet (v20220406-29) have been released which may have resolved this issue. Can you please test with the latest versions and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!
