### ISSUE TITLE
Ombi Request

### ISSUE THREAD

**Issue by muzzy182uk** [SynoCommunity/spksrc#4281]
[Package Request] Ombi

Content: 

Name: Ombi
Description: Media Request Tool
Website: https://ombi.io/
Software documentation: https://github.com/tidusjar/Ombi
Build/Installation documentation: https://github.com/tidusjar/Ombi/releases
Source code: https://github.com/tidusjar/Ombi/releases
License: GPL, GPL-2.0 License

**Comment by ycflash** [comment]
+1

**Comment by hgy59** [comment]
duplicate of #2601
