### ISSUE TITLE
Hass.io: Impossible to update Home Assistant Core to version 0.113.1

### ISSUE THREAD

**Issue by projetsdiy** [SynoCommunity/spksrc#4283]
Hello, 
It is impossible to update Home Assistant Core from version 0.118.4 to 0.113.1

### Setup
Docker version 18.09.0-0513 (latest). Official package 
Package Hass.io v20200910-2 https://synocommunity.com/package/hassio

### NAS Model:
DS718+ 8Go RAM
INTEL Celeron J3455
DSM 6.2.3-25426 Update 2
 
### Actual behavior
Impossible to update Home Assistant Core from version 0.118.4 to 0.113.1
Errors displayed in the system tab
- You are running an unsupported installation.
- Your installtion is running in an unhealthy state.

#### Supervisor logs
WARNING (MainThread) [supervisor.jobs] 'HomeAssistantCore.update' blocked from execution, system is not healthy

Many thank's for your help
Christophe

**Comment by cerealeskiller** [comment]
Bonjour je suis dans le même cas...

**Comment by xavierleveille** [comment]
Bonjour a tous,
Je suis aussi dans le même cas et débutant pour simplifier les choses ... installé pour la premiere fois il y a 7 jours ...
D'après ce que j'ai pu lire et sauf erreur de ma part, il faudrait docker en version 19 (recommandé) mais pas dispo sur syno sans installation manuelle.

Config: 
Syno DS415+
Intel Atom C2538 2,4 Ghz
DSM 6.2.3-25426 Update 2
Docker version 18.09.0-0513 

Hass.io

Version | 0.118.5
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 3.10.105
CPU Architecture | x86_64
Timezone | Europe/Paris

Logged In | false
-- | --
Reach Certificate Server | ok
Reach Authentication Server | ok
Reach Home Assistant Cloud | ok

Host Operating System |  
-- | --
Update Channel | beta
Supervisor Version | 2020.12.6
Docker Version | 18.09.8
Disk Total | 7330.7 GB
Disk Used | 6140.6 GB
Healthy | Unhealthy – more info
Supported | Unsupported – more info
Supervisor API | ok
Version API | ok
Installed Add-ons

Merci du coup de main si une solution est trouvée

**Comment by Carlisa4** [comment]
Bonjour à tous, 
IDEM pour moi et novice en plus..!!!!
Merci pour le coup de main ;)

**Comment by xavierleveille** [comment]
Bonjour, et meilleurs vœux a tous !
pour passer se probleme de mise a jour, il est possible de placer un fichier jobs.json dans le repertoire de Hass  avec  le contenu suivant:
