### ISSUE TITLE
Deluge 2.0.3-12 fails to load Autoadd plugin

### ISSUE THREAD

**Issue by MrRalphMan** [SynoCommunity/spksrc#4290]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Deluge
_Package Version:_ 2.0.3-12

_NAS Model:_ DS215j
_NAS Architecture:_ 
_DSM version:_ 6.2.3-25426 Update 2

### Expected behavior
AutoAdd should enable.

### Actual behavior
When you check the box it auto unchecks and 

### Steps to reproduce
Open Web Page
Goto Plugins
Check AutoAdd

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
`Traceback: <type 'exceptions.ValueError'>: No JSON object could be decoded
/volume1/@appstore/python/lib/python2.7/site-packages/twisted/internet/defer.py:151:maybeDeferred
/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-2.0.3-py2.7.egg/deluge/plugins/init.py:27:enable
build/bdist.linux-armv7l/egg/deluge_autoadd/core.py:88:enable
/volume1/@appstore/deluge/env/lib/python2.7/site-packages/deluge-2.0.3-py2.7.egg/deluge/config.py:468:save
/var/packages/python/target/lib/python2.7/json/init.py:339:loads
/var/packages/python/target/lib/python2.7/json/decoder.py:364:decode
/var/packages/python/target/lib/python2.7/json/decoder.py:382:raw_decode

20:57:18 [WARNING ][deluge.pluginmanagerbase :246 ] Problems occured disabling plugin: AutoAdd
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Nothing written to messages or synopkg.log when it fails
```

**Comment by ChristopherW** [comment]
Also occurring on a DS918+ with same DSM and Deluge package.

**Comment by vincent-lgl** [comment]
also on DS920+ with same DSM and Deluge package.

**Comment by th0ma7** [comment]
New version of deluge is being published.  Please reopen the issue if its still occurring.  Thnx in advance.
