### ISSUE TITLE
Synology DSM 7 Beta | Lower Permissions

### ISSUE THREAD

**Issue by Kaelber** [SynoCommunity/spksrc#4298]
I tested the VMM DSM 7 Preview and since yesterday the DSM 7 Beta is available. I have installed the new Beta and all packages I try to install is with the same message:

I updated my VMM from DSM 7 from Preview to Beta with the same result as expected

![grafik](https://user-images.githubusercontent.com/12963736/101641981-bb4b9280-3a32-11eb-810f-caee70b42553.png)

or similar. My question is about your planning of activities about that.

**Comment by BenjV** [comment]
e https://github.com/SynoCommunity/spksrc/issues/4215

**Comment by hgy59** [comment]
@publicarray   has created the dsm7 branch in this repo. You can try to build packages using this branch

**Comment by hgy59** [comment]
duplicate of #4215
