### ISSUE TITLE
Can't start Radarr on Synology

### ISSUE THREAD

**Issue by severdia** [SynoCommunity/spksrc#4310]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Radarr
_Package Version:_ 20200921-11 (then with app update to v3.0.0.4204)

_NAS Model:_ Synology
_NAS Architecture:_ x64
_DSM version:_ 6.2.3-25426 Update 3

### Expected behavior
After running the built-in app update from version 0.2.0.1504 to version 3.0.0.4204 the app updates and the package in the Package Centre reports as 'Stopped' (Displays the 'Run' button only)

### Actual behavior
After running the built-in app update from version 0.2.0.1504 to version 3.0.0.4204 the app updates and the package in the Package Centre reports as 'Stopped' with an error 'Failed to run the package service' reported when the Run button is clicked. After trying the recommendations in this issue (https://github.com/SynoCommunity/spksrc/issues/4285) clicking the Run button has no visible effect and the Radarr menu item does nothing when clicked.

### Steps to reproduce
_1._ Install clean Radarr 20200921-11 from SynoCommunity
_2._ In the Radarr interface under System > Updates, click Install Latest to update to V3
_3._ Refresh the Radarr interface to show the new V3 UI and then Shutdown the app
_4._ From the Package Center click on Run for the Radarr app

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

Logs are same as reported in this issue here:

https://github.com/SynoCommunity/spksrc/issues/4285

@BenjV  I have the same issue as @wvkreg but I'm running the Synology package, not Docker. I tried the same things mentioned above and Radarr doesn't work at all anymore. When I click Run, nothing happens (I got the error before). This is what my result is so far:

```
root@XXXXXX:/var/packages/radarr/scripts# cat /var/packages/radarr/scripts/service-setup
### Package specific variables and functions
# Base service USER to run background process prefixed according to DSM
USER="radarr"
PRIV_PREFIX=sc-
SYNOUSER_PREFIX=svc-
if [ -n "${SYNOPKG_DSM_VERSION_MAJOR}" -a "${SYNOPKG_DSM_VERSION_MAJOR}" -lt 6 ]; then EFF_USER="${SYNOUSER_PREFIX}${USER}"; else EFF_USER="${PRIV_PREFIX}${USER}"; fi
# Service port
SERVICE_PORT="8310"
# start-stop-status script redirect stdout/stderr to LOG_FILE
LOG_FILE="${SYNOPKG_PKGDEST}/var/${SYNOPKG_PKGNAME}.log"
# Service command has to deliver its pid into PID_FILE
PID_FILE="${SYNOPKG_PKGDEST}/var/${SYNOPKG_PKGNAME}.pid"

# Invoke shell function if available
call_func ()
{
    FUNC=$1
    if type "$FUNC" 2>/dev/null | grep -q 'function' 2>/dev/null; then
        if [ -n "${INST_LOG}" ]; then
            echo "Invoke $FUNC" >> ${INST_LOG}
        fi
        eval ${FUNC}
    fi
}

PATH="${SYNOPKG_PKGDEST}/bin:${PATH}"
MONO_PATH="/var/packages/mono/target/bin"
MONO="${MONO_PATH}/mono"

# Check versions during upgrade
RADARR="${SYNOPKG_PKGDEST}/share/Radarr/Radarr.exe"
SPK_RADARR="${SYNOPKG_PKGINST_TEMP_DIR}/share/Radarr/Radarr.exe"

# Radarr uses custom Config and PID directories
HOME_DIR="${SYNOPKG_PKGDEST}/var"
CONFIG_DIR="${SYNOPKG_PKGDEST}/var/.config"
PID_FILE="${CONFIG_DIR}/Radarr/radarr.pid

# Some have it stored in the root of package
LEGACY_CONFIG_DIR="${SYNOPKG_PKGDEST}/.config"

# workaround for mono bug with armv5 (https://github.com/mono/mono/issues/12537)
if [ "$SYNOPKG_DSM_ARCH" == "88f8621" -o "$SYNOPKG_DSM_ARCH" == "88f8622" ]; then
    MONO="MONO_ENV_OPTIONS='-O=-aot,-float32' ${MONO_PATH}/mono"
fi

GROUP="sc-download"
LEGACY_GROUP="sc-media"

SERVICE_COMMAND="env PATH=${MONO_PATH}:${PATH} HOME=${HOME_DIR} LD_LIBRARY_PATH=${SYNOPKG_PKGDEST}/lib ${MONO} ${RADARR}"
SVC_BACKGROUND=y

service_postinst ()
{
    # Move config.xml to .config
    mkdir -p ${CONFIG_DIR}/Radarr
    mv ${SYNOPKG_PKGDEST}/app/config.xml ${CONFIG_DIR}/Radarr/config.xml
    set_unix_permissions "${CONFIG_DIR}"

    # If nessecary, add user also to the old group before removing it
    syno_user_add_to_legacy_group "${EFF_USER}" "${USER}" "${LEGACY_GROUP}"
    syno_user_add_to_legacy_group "${EFF_USER}" "${USER}" "users"

    # Discard legacy obsolete busybox user account
    BIN=${SYNOPKG_PKGDEST}/bin
    $BIN/busybox --install $BIN >> ${INST_LOG}
    $BIN/delgroup "${USER}" "users" >> ${INST_LOG}
    $BIN/deluser "${USER}" >> ${INST_LOG}
}

service_preupgrade ()
{
    # We have to account for legacy folder in the root
    # It should go, after the upgrade, into /var/.config/
    # The /var/ folder gets automatically copied by service-installer after this
    if [ -d "${LEGACY_CONFIG_DIR}" ]; then
        echo "Moving ${LEGACY_CONFIG_DIR} to ${INST_VAR}" >> ${INST_LOG}
        mv ${LEGACY_CONFIG_DIR} ${CONFIG_DIR} >> ${LOG_FILE} 2>&1
    else
        # Create, in case it's missing for some reason
        mkdir ${CONFIG_DIR} >> ${LOG_FILE} 2>&1
    fi

    # Is Installed Radarr Binary Ver. >= SPK Radarr Binary Ver.?
    CUR_VER=$(${MONO_PATH}/monodis --assembly ${RADARR} | grep "Version:" | awk '{print $2}')
    echo "Installed Radarr Binary: ${CUR_VER}" >> ${INST_LOG}
    SPK_VER=$(${MONO_PATH}/monodis --assembly ${SPK_RADARR} | grep "Version:" | awk '{print $2}')
    echo "Requested Radarr Binary: ${SPK_VER}" >> ${INST_LOG}
    if [ "${CUR_VER//.}" -ge "${SPK_VER//.}" ]; then
        echo 'KEEP_CUR="yes"' > ${CONFIG_DIR}/KEEP_VAR
        echo "[KEEPING] Installed Radarr Binary - Upgrading Package Only" >> ${INST_LOG}
        mv ${SYNOPKG_PKGDEST}/share ${INST_VAR}
    else
        echo 'KEEP_CUR="no"' > ${CONFIG_DIR}/KEEP_VAR
        echo "[REPLACING] Installed Radarr Binary" >> ${INST_LOG}
    fi
}

service_postupgrade ()
{
    # Restore Current Radarr Binary if Current Ver. >= SPK Ver.
    . ${CONFIG_DIR}/KEEP_VAR
    if [ "$KEEP_CUR" == "yes" ]; then
        echo "Restoring Radarr version from before upgrade" >> ${INST_LOG}
        rm -fr ${SYNOPKG_PKGDEST}/share >> $INST_LOG 2>&1
        mv ${INST_VAR}/share ${SYNOPKG_PKGDEST}/ >> $INST_LOG 2>&1
        set_unix_permissions "${SYNOPKG_PKGDEST}/share"
    fi
    set_unix_permissions "${CONFIG_DIR}"

    # If backup was created before new-style packages
    # new updates/backups will fail due to permissions (see #3185)
    set_unix_permissions "/tmp/radarr_backup"
    set_unix_permissions "/tmp/radarr_update"

    # Remove upgrade Flag
    rm ${CONFIG_DIR}/KEEP_VAR
}
root@XXXXXX:/var/packages/radarr/scripts# dir /var/packages/radarr/target/var/.config/Radarr
total 1500
drwxr-xr-x 1 sc-radarr radarr    186 Dec 13 16:15 .
drwxr-xr-x 1 sc-radarr radarr     22 Sep 26 07:42 ..
drwxr-xr-x 1 sc-radarr radarr     42 Jun 26 10:02 Backups
-rw-r--r-- 1 sc-radarr radarr    459 Dec 13 16:09 config.xml
drwxr-xr-x 1 sc-radarr radarr    164 Dec  2 17:05 logs
-rw-r--r-- 1 sc-radarr radarr 397312 Dec 13 16:15 logs.db
drwxr-xr-x 1 sc-radarr radarr     58 Dec  5 08:11 MediaCover
-rw-r--r-- 1 sc-radarr radarr 716800 Dec 13 16:15 radarr.db
-rw-r--r-- 1 sc-radarr radarr  32768 Dec 13 16:26 radarr.db-shm
-rw-r--r-- 1 sc-radarr radarr 379072 Dec 13 16:26 radarr.db-wal
-rw-r--r-- 1 sc-radarr radarr      5 Dec 13 16:10 radarr.pid
drwxr-xr-x 1 sc-radarr radarr    120 Dec  2 16:55 UpdateLogs
root@XXXXXX:/var/packages/radarr/scripts# ps aux | grep Radarr
root     24950  0.0  0.0  23144  2396 pts/13   S+   16:35   0:00 grep --color=auto Radarr
root@XXXXXX:/var/packages/radarr/scripts# 

```

I've also restarted a few times and still can't get Radarr to run. I could try uninstalling and reinstalling, but I'd lose all my info and don't want to do that.

**Comment by severdia** [comment]
@houndtt Here's the new issue. I can't seem to find any documentation on how to backup, reinstall, and restore Radarr on Synology. And I won't be able to update because, contrary to what the above shows, I can't run Radarr.

**Comment by houndtt** [comment]
@severdia, thanks lodging a new issue to treat with separately. I am particularly interested in the part of the log above where you have the following:

```
root@XXXXXX:/var/packages/radarr/scripts# dir /var/packages/radarr/target/var/.config/Radarr
total 1500
drwxr-xr-x 1 sc-radarr radarr    186 Dec 13 16:15 .
drwxr-xr-x 1 sc-radarr radarr     22 Sep 26 07:42 ..
drwxr-xr-x 1 sc-radarr radarr     42 Jun 26 10:02 Backups
-rw-r--r-- 1 sc-radarr radarr    459 Dec 13 16:09 config.xml
drwxr-xr-x 1 sc-radarr radarr    164 Dec  2 17:05 logs
-rw-r--r-- 1 sc-radarr radarr 397312 Dec 13 16:15 logs.db
drwxr-xr-x 1 sc-radarr radarr     58 Dec  5 08:11 MediaCover
-rw-r--r-- 1 sc-radarr radarr 716800 Dec 13 16:15 radarr.db
-rw-r--r-- 1 sc-radarr radarr  32768 Dec 13 16:26 radarr.db-shm
-rw-r--r-- 1 sc-radarr radarr 379072 Dec 13 16:26 radarr.db-wal
-rw-r--r-- 1 sc-radarr radarr      5 Dec 13 16:10 radarr.pid
drwxr-xr-x 1 sc-radarr radarr    120 Dec  2 16:55 UpdateLogs
```

In particular I am concerned about the database file ending in '[db-wal](https://www.sqlite.org/wal.html)'. These are usually present if the database is already running or was not shut down correctly.

To start I would backup this folder to a backup directory you can access similar to:
`sudo cp -r /volume1/@appstore/radarr/var/.config/Radarr/ /volume1/homes/[user]/home/backup`

Once you verify that the copy was successful, you can then examine what happened with the update (the 'UpdateLogs' folder looks promising) or just jump straight to see what happens when you attempt to start Radarr. I would suggest looking at the package log file when you start Radarr as suggested by the issue template above (just update your issue details to paste it in).

If you do need to do a reinstall the [Radarr FAQ](https://wiki.servarr.com/Radarr_FAQ#Restoring_from_Backup) has some good guidance on this. Essentially, you already completed a manual backup in the first step above. Then you just need to uninstall Radarr from your NAS and copy the files back. I would probably delete the 'radarr.pid' file since this should only exist if Radarr is running.

**Comment by severdia** [comment]
@houndtt I don't have a `home` directory at the path you mentioned:  `/volume1/homes/[user]/home/`. Instead of `home`, it's `Drive`. Is it OK to use that? This is my first time using terminal and diving in Synology innards.

**Comment by publicarray** [comment]
So it looks like the package is running but because the pid file changed the package center thinks it still stopped. I suggest going to the web interface and stop it and then run install the new package as @houndtt mentioned. If you can't  find the web interface you can use `Sido killall radarr`

**Comment by houndtt** [comment]
> @houndtt I don't have a `home` directory at the path you mentioned: `/volume1/homes/[user]/home/`. Instead of `home`, it's `Drive`. Is it OK to use that? This is my first time using terminal and diving in Synology innards.

@severdia, if you do not have a `home` folder it is likely because the user home service is disabled (Control Panel > User > Advanced). The location of the backup only needs to be a folder you have access to so that you can verify that the copy happened successfully.

You will need to do some research on your own to get familiar with Linux command line use as well as lookup individual commands for yourself using references like [Linux Commands](https://www.commandlinux.com) to build your understanding otherwise troubleshooting will be nearly impossible.

Also please upload the recommended log files. (e.g. package log can be output with `cat /usr/local/radarr/var/radarr.log`)

**Comment by severdia** [comment]
@houndtt I got a notice there was an update to Radarr so I updated to see if that fixed anything. It didn't seem to work at first, but seems to be working now. 

Here's the package log:

```
root@XXXXXXX:~# cat /usr/local/radarr/var/radarr.log
Wed Dec 16 13:03:58 PST 2020
Starting radarr command env PATH=/var/packages/mono/target/bin:/volume1/@appstore/radarr/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/radarr/var LD_LIBRARY_PATH=/volume1/@appstore/radarr/lib /var/packages/mono/target/bin/mono /volume1/@appstore/radarr/share/Radarr/Radarr.exe 
[Info] Bootstrap: Starting Radarr - /volume1/@appstore/radarr/share/Radarr/Radarr.exe - Version 3.0.0.4204 
[Info] Router: Application mode: Interactive 
[Info] MigrationController: *** Migrating data source=/volume1/@appstore/radarr/var/.config/Radarr/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/volume1/@appstore/radarr/var/.config/Radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] WebHostController: Listening on the following URLs: 
[Info] WebHostController:   http://*:8310 
[Info] RadarrBootstrapper: Starting Web Server 
[Info] CommandExecutor: Starting 2 threads for tasks. 
[Warn] MonoDebugCheck: Mono is not running with --debug switch 
```

I found three files in the UpdateLogs directory and attached them:

`2020.06.19-10.47.txt  2020.07.05-15.31.txt  2020.12.02-16.55.txt
`

I don't have a `home` directory even though it's enabled (Control Panel > User > Advanced).  It seems Radarr is now running, but the non-Synology items in the Synology menu aren't working  (clicking on them does nothing—Plex, Jackett, Radarr). I'll continue to test some more, but other than the menu items it seems to be working now. Let me know if there's anything else I can provide.

**Comment by houndtt** [comment]
@severdia, thanks for the update, glad your Radarr is up and running now. Looking back at the command I gave you are correct within the `/volume1/homes/[user]/` path this would be the user's home folder. As such there would be no `home` folder within this but rather the user's files. Apologies for that.

Looking at your update logs they seem consistent with what I have in my Synology unit. Nothing out of the ordinary in them that would suggest a previously failed upgrade to Radarr v3. At least with your Radarr currently running you can perform a manual backup and download the configuration so you have a good starting point should you have to reinstall anything.
