### ISSUE TITLE
Radarr 20200921-11 problems with synology DS216j   DSM 6.2.3-25426 Update 2

### ISSUE THREAD

**Issue by giospud** [SynoCommunity/spksrc#4312]
I installed the latest version of Radarr (see topic) on my DS216j with DSM 6.2.3-25426 Update 2  and it does not run anymore: If I try to run it it thinks for a while and then it says "Failed to run the package service" Any idea how to solve the problem?

**Comment by publicarray** [comment]
Latest version from synocommunity is v20201214-13

https://synocommunity.com/package/radarr

Please update and try again
