### ISSUE TITLE
[Question] tic command line tool

### ISSUE THREAD

**Issue by Sinderella** [SynoCommunity/spksrc#4325]
Hello,

I am not sure if the command [tic](https://linux.die.net/man/1/tic) is available anywhere as I cannot find it after searching. It should be part of ncurses, which is quite common. Please forgive me if this is something obvious.

I just wanted to install alacritty's terminfo with tic, so it's not acting weird.

Thank you!

**Comment by hgy59** [comment]
`tic` is installed with every spk that includes ncurses (or ncursesw).
But there is no symlink created for tic. E.g. with installed synocli-file you can call tic with:
`/var/packages/target/synocli-file/bin/tic`

Packages with ncurses included:
python2, python3, all synocli-packages, gnupg, lua, ....

**Comment by Sinderella** [comment]
Thank you for your help! I found it
