### ISSUE TITLE
Getting RuTorrent working

### ISSUE THREAD

**Issue by jandirk39** [SynoCommunity/spksrc#4326]
_For new Package Requests, see the guidelines_  

### Setup
RuTorrent
_Package Version:_ 

DS214+ 
DSM 6.0 

I installed RuTorrent but it wont load. When I click the icon it opens another window of my synology. In the description it says. Move configuration file to web drive. The annoying thing is we are not all computer wizards and I have no idea how to move this file. I cannot find any installation/package files on my NAS only the folders I created. So a bit more information on how to do this would help. Every solution I found on the internet was without any help just saying do this move that change this, again something only a computer wizard would know. can someone provide me an actual tutorial on how to do this?

**Comment by BenjV** [comment]
Use Download Station for torrents.
That is designed for non computer wizards.

**Comment by jandirk39** [comment]
That does not have the functionality that I need. You could just simply help instead of being a smart ass dick

**Comment by BenjV** [comment]
Tja, read your own comment and look in the mirror.

**Comment by jandirk39** [comment]
I’m asking for help here. If you van only give bullshit comments then shut up. Not for a lecture and smart ass comments. I know I can use ds get. But I want to use ru torrent. I’m just saying that the solutions people give is not always enough for the average synology user.

**Comment by smaarn** [comment]
> I’m asking for help here. If you van only give bullshit comments then shut up. Not for a lecture and smart ass comments. I know I can use ds get. But I want to use ru torrent. I’m just saying that the solutions people give is not always enough for the average synology user. 

Would you happen to have more details on the exact error? Logs could also help here understanding your issue.

Regarding tutorials for "non computer wizards" I won't be able to help unfortunately.

**Comment by zyrill** [comment]
@jandirk39 if you're still on DSM 6, would transmission be an alternative for you? Should provide similar functionality and it's easier to set up.

**Comment by jandirk39** [comment]
Thank you all for the help. I’m looking for a program that I can use with a vpn. And when the vpn gets disconnected I want the download to stop. With utorrent on my pc that is possible.

**Comment by BenjV** [comment]
Use your Synology for the VPN and configure it to use only the VPN for connection to the internet and no other connection.
Then use Download Station as you torrent client.

**Comment by mreid-tt** [comment]
Hi @jandirk39, it appears that this issue has been open for a while without any updates. Can you please provide us with an update on your experience with ruTorrent? If you're still facing difficulties, we recommend trying out the latest release, v4.1.5-15, as it might work better in your specific setup. However, if you've already tried it or if the issue has been resolved, please let us know.

**Comment by mreid-tt** [comment]
Closing the issue due to a lack of recent updates. However, please note that if the issue persists, it can be reopened for further investigation.
