### ISSUE TITLE
[Package Request] Pi Hole v5.0

### ISSUE THREAD

**Issue by c0154936** [SynoCommunity/spksrc#4330]
Name: Pi-Hole
Description: Software runs a DNS Service (it also provides ad blocking which is it's main feature)
Website: https://pi-hole.net/
Software documentation: https://docs.pi-hole.net/
Build/Installation documentation: https://docs.pi-hole.net/
Source code: https://github.com/pi-hole/pi-hole
License: https://github.com/pi-hole/pi-hole/blob/master/LICENSE

**Comment by hgy59** [comment]
duplicate of #2501
