### ISSUE TITLE
Sonarr V3: Ryzen Build

### ISSUE THREAD

**Issue by mikepaxton** [SynoCommunity/spksrc#4331]
Will there be a Sonarr V3 Ryzen build for the Synology DS1821 and DS1621?

**Comment by hgy59** [comment]
Sonarr V3 package is  under development, see #3803.
But until PR  #3803 is rebased to home@master, there will no Ryzen (arch v1000) varsion be available in arch-x64 generic package,

**Comment by hgy59** [comment]
#3803 is merged and version 20210329-19 was published on 2021/03/29 including arch v1000.
