### ISSUE TITLE
update sshfs of synocli-net

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#4334]
This is a followup of #2661

update sshfs to version 3.x
- depends on cross/libfuse version 3.x
- cross/libfuse version 3.x needs meson build (#4307)

**Comment by th0ma7** [comment]
I have an early prototype where I was able to compile `udev` from systemd-204 (same version as DSM-6) using the toolkit framework with a few modifications.  It applies on top of #4307.

I'll submit a [WIP] PR later today/tomorrow, please consider that code to be of prototype level at this early stage.
