### ISSUE TITLE
rutorrent reporting 100% CPU usage, system resources report much lower

### ISSUE THREAD

**Issue by IAm-ThePat** [SynoCommunity/spksrc#4342]
### Setup
_Package Name:_ ruTorrent
_Package Version:_ 3.10-10

_NAS Model:_ DS1815+
_NAS Architecture:_ avoton (x64)
_DSM version:_ DSM 6.2.3-25426 Update 3

### Expected behavior
ruTorrent should be able to access full system capabilities

### Actual behavior
ruTorrent appears to be limited in the resources that are accessible

### Steps to reproduce
_1._ Run ruTorrent
_2._ View CPU utilization
_3._ compare to system resource monitor / top / htop

#### Package log
_Check Package Center or /usr/local/rutorrent/var/rutorrent.log_
```
1609195737 W Ignoring rtorrent.rc.
```
#### Extended description

Since the upgrade to 3.10-10, ruTorrent seems to be limited in the system resources that it has available. The CPU graph is almost always pinned at 100%, even when everything is idle, but the actual system resources displayed in synology are much lower - typically around 20-30%. In the previous version, the CPU graph matched the actual system resources much more closely. 

While I may accept this this is just a display issue, tasks such as rescanning a torrent take far longer than the previous version, and sometimes appear to stall (revert to queued, despite no other queued tasks). Rescanning a TV Show season may take upwards of 15 minutes now, whereas it would only be 1-2 minutes previously. 

I don't have anything set in rtorrent.rc that would appear to set any sort of resource limit, but I can provide a copy of the file if anyone believes that may be helpful. It is the same as the rtorrent.rc I used with the previous version, but the values have been updated to the correct naming convention. Please let me know if there is any other information that can be used to help

![Screen_Shot_2020-12-29_11_46_35](https://user-images.githubusercontent.com/76750095/103310778-433b1180-49cd-11eb-80a1-e89d701f6d7f.png)

Thanks!

**Comment by BenjV** [comment]
Why post this here?
You should this post in the forum of the ru-torrent developers.
https://github.com/Novik/ruTorrent/issues

Here it is only about Synology packaging of applications others developed, not the applications themselves.

**Comment by IAm-ThePat** [comment]
@BenjV - that is totally a fair question. I guess my assumption was that this issue was related the way ruTorrent was working internal to Synology, and somehow being siloed. 

If I have an incorrect assumption, and this is actually an issue with the application itself, I will retract my question and ask in the actual application's git.

**Comment by BenjV** [comment]
If I must make an assumption I would say that rutorrent is not multithreaded and only use one core and also display the cpu used of that single core.

**Comment by IAm-ThePat** [comment]
Got'cha. Thanks @BenjV, and apologies for adding this issue here in error.
