### ISSUE TITLE
[Package Request] Ruby

### ISSUE THREAD

**Issue by tsutsu** [SynoCommunity/spksrc#4350]
We already had a Ruby package, but we removed it after #1844 (Synology began to distribute their own first-party Ruby package.)

But [in June of 2020, Synology EOLed their Ruby package, and removed it from their package source](https://community.synology.com/enu/forum/1/post/130768).

Can we "un-retire" the Ruby package, and get it building again?

(I'm guessing I don't need to follow the package-request format here — we already have the Ruby package spec in commit history, viewable as of its deletion in 799f368bd5d0f3dd8627df5049027d54cb8a145c.)

**Comment by hgy59** [comment]
I have this in focus for #2178
