### ISSUE TITLE
Home Assistant Core for Synology NAS and Python3 version issue

### ISSUE THREAD

**Issue by MarkusSacramento** [SynoCommunity/spksrc#4382]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Home Assistant Core
_Package Version: 0.118.5-11

_NAS Model: Synoogy NAS DS218Play
_NAS Architecture: ARM8 (Realtek RTD1296 SoC)
_DSM version: DSM 6.2.3-25426 Update 3
--

The PAckage requires Python3 to work.
If not installed it installs it during the installation of HomeAssistant Core package.
The problem is that the package requires the Python3 package create by Allan Clark which is only updated to 3.7.7-15.
It is also possible to install Python3 package created by Python Software Foundation which is updated to 3.8.2-0150 but this isn't supported by the Home Assistant Core package.

My suggestion is to let th Home Assistant Core package verify if python is installed and if as long as the version is at minimum what Home Assistant Core requires a third party package should not be needed.

 Allan Clarks python3 version is to old to run newer Home Assistant updates.

**Comment by hgy59** [comment]
All the synocommunity packages that depend on python3 need the synocommunity python3. It is not possible to support both python3 packages as dependency. The internal package names differ (python3: synocommunity, Python3: synology).
The synocommunity python3 is currently 3.7.7-15 (Maintainer is Allan Clark.) 
The homeassistant package 0.118.5-11 works well with python3 3.7.7-15.

The next homeassistant package needs python3 3.8.x when homeassistant is updated to a version > 0.118.5.
I cannot see the real issue. You didn't tell us about error messages or installation failures.
The only issue I see in my installation is a warning, that further homeassistant updates will not be supported for Python 3.7.

**Comment by iandarbey** [comment]
The ikea integration fails for me using HA core (with python errors). Is an update to python not currently WIP anyway?

**Comment by MarkusSacramento** [comment]
I don't have an issue more than it complains about Python version is out of date and that HA won't work if updated.
Just thought it would be easier working with relationship to the Internal package since it gets updated more frequently. Just a tip and a Heads Up.

**Comment by hgy59** [comment]
@MarkusSacramento thanks for claryfying this 👍 
Out experiance is, that synology is not so fast with updates, but I must confess that with python3 we are delayed due to the cross compiling issues we had with python 3.6...

**Comment by knag1** [comment]
Thank you for your great work! I run ha on a DS120j but now I miss the GOODWE integration and some other.
I also have no idea how to backup the system online. Currently I stop ha, copy the folder to another location and restart ha on DSM. Could you update the ha version to the latest for Sysnology and integrate supervisor function or some online backup solution, or can I do that myself?

**Comment by hgy59** [comment]
> I also have no idea how to backup the system online. Currently I stop ha, copy the folder to another location and restart ha on DSM. Could you update the ha version to the latest for Sysnology and integrate supervisor function or some online backup solution, or can I do that myself?

@knag1 a package update will backup and restore the whole var folder (`/var/packages/homeassistant/var`). But it will not install (restore) the manually installed python packages.
IMHO the supervisor of HA is not supported with HA core.

A further update of the Homeassistant package is blocked until we have rust support integrated into the cross wheel build process.

---

BTW you can manually install prerequisites for additional integrations, as long as those are available as pure python wheels (do not need cross compilation).
1. ssh into you diskstation
2. gain root access (`sudo su -`)
3. cd into `/var/packages/homeassistant/target/env/bin`
4. install the wheels like `./pip install goodwe`

You will have to redo this after every package update.

**Comment by knag1** [comment]
thank you! I did the -/pip steps on the diskstation with success msg, restarted ha - no goodwe integration visible. restarted the whole disk station - also not visible. any idea?

**Comment by hgy59** [comment]
> not visible. any idea?

The GoodWe Inverter integration was introduced in Home Assistant 2022.2

So maybe you can add this integration manually in the config file, but there is no documentation on how to do this https://www.home-assistant.io/integrations/goodwe/#configuration

**Comment by hgy59** [comment]
For further issues please create a new issue, as this one is outdated and already closed
