### ISSUE TITLE
Radarr V3 package (includes removal of .Net warning)

### ISSUE THREAD

**Issue by azz22** [SynoCommunity/spksrc#4398]
Title:

[Package Request] Radarr V3

Content: Radarr program that removes the .NET warning. For intel CPU.

Name: Radarr V3
Description: Film and Movie manager. Can be used to import files into other software.
Website: https://radarr.video/#home
Software documentation: https://github.com/Radarr/Radarr
Build/Installation documentation: https://github.com/Radarr/Radarr
Source code: https://github.com/Radarr/Radarr
License: https://github.com/Radarr/Radarr

This would be a really useful package for those who do not run docker. Please consider. 

Thanks for your time.

**Comment by Wuszek** [comment]
Quoting @publicarray from #4276  "Regarding the Please upgrade to the .NET Core version of Radarr I wouldn't worry about it for now. There are plans to add .NET build scripts to spksrc but I'm waiting for them to be reviewed and merged. (#4207)"

Also, a question from my side. Do You have problem with current Mono package v5.20.1.34-17?

**Comment by azz22** [comment]
Hi,

That’s great. Thanks.

It sometimes brings an error which says failed to load API and it won’t display any of my library. Is this anything your familiar with or can you recommend anything?

Regards
Aaron

**Comment by Wuszek** [comment]
I had the same error, just resolved it with downgrade to Mono version 5.8, and I'm still waiting for .NET package or something that would make Mono work properly :)

**Comment by azz22** [comment]
Thanks. I’ll try that. Appreciate your help.

**Comment by bakerboy448** [comment]
Now that #4207 is merged; are you guys finally going to provide net builds of radarr so Syno packages stop being a pain in everyone’s arse?

**Comment by Wuszek** [comment]
@bakerboy448 jackett NET update is deactivated as it is not working properly with DSM 6.
