### ISSUE TITLE
New Bacula SPK

### ISSUE THREAD

**Issue by Diaoul** [SynoCommunity/spksrc#44]
Bacula seems nice, with a web UI "webacula".
##

**Comment by MatthiasToberer** [comment]
PUSH

**Comment by mvreijn** [comment]
I have started this a while ago - but just getting the base packages to compile properly is quite a challenge. 
If someone is willing to lend a hand I will restart my project.

**Comment by jaithn** [comment]
i don't know how i could help - not that profund in linux, but i am willing to support, if possible...
