### ISSUE TITLE
[Feature request] ntopng config parameter addition

### ISSUE THREAD

**Issue by pandel** [SynoCommunity/spksrc#4404]
Hi!

@hgy59 
Many thanks for the ntopng package! I have a question:

Is it possible to add the parameter

**--ndpi-protocols /volume1/@appstore/ntopng/var/data/protos.txt**

to ntopng.conf along with an empty file

**/volume1/@appstore/ntopng/var/data/protos.txt** (Rights 600 sc-ntopng:ntopng)

to the package?

This enables the user to define custom protocols in the "Applications & Categories" section of ntopng.

Many thanks!

Regards,
Holger

**Comment by hgy59** [comment]
@pandel you can freely edit the ntopng.conf file of the installed package (you find it as `/var/packages/ntopng/target/var/ntopng.conf`). 
You can change the line `#--ndpi-protocols <file>.protos` to activate your protos.txt file.
To activate the configuration you need to restart ntopng. 
This configuration will stay active until you change it. It will survive a reboot, a DSM update or a ntopng package update.

We could adjust the installer to create an empty protos.txt file and to activate the configuration in the config file, but as you have to edit the protos.txt file anyway (and you have to know what you are doing) I think it is ok, that you have to edit the ntpng.conf file in this case by yourself.
