### ISSUE TITLE
Mosquitto on DSM 7.0

### ISSUE THREAD

**Issue by Jeugenius** [SynoCommunity/spksrc#4407]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Mosquitto
_Package Version:_ 1.6.12-11

_NAS Model:_ DS 718+
_NAS Architecture:_ INTEL Celeron J3455
_DSM version:_ 7.0-41222

### Expected behavior
Installing the Mosquitto package to work with Openhab 3

### Actual behavior
Unable to install Mosquitto, as it requires root user rights to run. Packages with root user rights can execute commands on behalf of the root user and violate the security of the system. Contact the package developer to change the package access rights settings.

**Comment by hgy59** [comment]
DSM 7 is still in progress here and packages are not ready. Please do not create issues of this kind.
see #4215

**Comment by ThierryM** [comment]
Hi,
I have updated to DSM 7.0 (version DSM 7.0-41890) on a DS 713+.
The Mosquitto package (version 1.6.15-12) doesn't work. The package repair doesn't work : 
![Sélection_428](https://user-images.githubusercontent.com/1470067/124841150-e4aeab80-df8c-11eb-9475-e76637003338.png)
Regards

**Comment by ThomasH-W** [comment]
At first I had the same error with this version.
But the old version must be removed completely using the option 
"Erase all of the package data files. (Not recoverable)"
Than install again and afterwards it launches w/o problems.

**Comment by ThorvaldAagaard** [comment]
I have the same problem, but even removing it completely and installing it again did not help me. Where can I find the log files (And is there a directory I can delete to make sure the old installation is deleted)

**Comment by Silas007** [comment]
I had the same issue on my 713+. I tried removing it completely but it did not work. I tried installing it via docker, that failed too. After a restart of the whole synology, I was able to install the package from the package center and it runs now without any problems. Good luck.

**Comment by Jeugenius** [comment]
> I have the same problem. Repairing, uninstalling and rebooting don’t work. Any suggestions? Thanks a lot!!

Hello. After a while it worked! Alternatively, you can run Mosquitto via Docker
