### ISSUE TITLE
FFsync install require MariaDB 5 but not 10 ?

### ISSUE THREAD

**Issue by The-MAD-Virus** [SynoCommunity/spksrc#4414]
### Setup
_Package Name:_ ffsync
_Package Version:_ 1.5.2

_NAS Model:_ DS413
_NAS Architecture:_ qoriq
_DSM version:_ 6.1

### Actual behavior
During the installation it requires MariaDB 5 to be installed, but MariaDB 10 was already installed.
Can't we use one or another ?

**Comment by hgy59** [comment]
ffsync is WIP in #3849
the whole mysql integration does not work yet, not only for ffsync package (see also #2816, #2093, #3400, #2136, #2333)

I was looking into this a few days ago and struggled with the following finding:

the command 
`mysql --user=${MYSQL_ROOT_USER} --password='${wizard_mysql_password_root}' --port=${MYSQL_PORT} --skip-column-names --batch --verbose --execute=quit` 
works in the shell on the diskstation but not in the service-setup script.

within the script functions it always returns:
`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`

**Comment by ymartin59** [comment]
@hgy59 My point of view was to discard MySQL support in package to provide SQLite by default - and maybe document manual MySQL setup for advanced users.

**Comment by publicarray** [comment]
@ymartin59 @hgy59 I've tried to create a package with MariaDB support using the documented resource worker, but I don't see a user or database being created. So I've emailed Synology a few days ago, sill waiting for a reply. What's wired is that their own packages, WordPress, follow a very differently formatted resource file.

**Comment by hgy59** [comment]
ffsync is outdated and will not supported anymore (requires python 2) (see #3849)
may be some day we will have a package for syncstorage-rs.
