### ISSUE TITLE
ci/dockercloud-stage fails

### ISSUE THREAD

**Issue by publicarray** [SynoCommunity/spksrc#4422]
### Expected behavior
Successful docker hub builds

### Actual behavior
I don't like to see all those red :x: s from build failures due to failed docker hub builds

### Steps to reproduce
_1._ open https://github.com/SynoCommunity/spksrc/commits/master
_2._ click on an :x: and scroll down

@ymartin59 do you have time to look at this?

**Comment by hgy59** [comment]
I suppose this is due to the restricted docker pull limits introduced November 1, 2020

We should ensure that updates are triggered only when Dockerfile was changed.

Unfortunately the prsented link to ci/dockercloud-stage is not valid (404).

**Comment by publicarray** [comment]
Thanks mate!

**Comment by publicarray** [comment]
@hgy59 The errors are happening again.
