### ISSUE TITLE
[Package Request] micro editor

### ISSUE THREAD

**Issue by muety** [SynoCommunity/spksrc#4423]
- Name: micro editor
- Description: Micro is an interactive command-line text editor like Vim or nano. It's modern, has syntax highlighting, mouse support and a plugin system. It's written in Go and is deployed as a single executable binary, so it should be fairly easy to compile it for different architectures and deliver it.
- Website: https://micro-editor.github.io/
- Software documentation: https://micro-editor.github.io/about.html
- Build/Installation documentation: https://github.com/zyedidia/micro#building-from-source
- Source code: https://github.com/zyedidia/micro
- License: MIT

**Comment by hgy59** [comment]
I have built a package with download of Version 2.0.8 from github releases. Unfortunately the executable reports the version:
```
Version: 0.0.0-unknown
Commit hash: fc2606bf
```
Any hint on how to build an official version would be appreciated.
