### ISSUE TITLE
[Question] Home assistant core python dependencies

### ISSUE THREAD

**Issue by rs1gg** [SynoCommunity/spksrc#4424]
After a safari trying to get a Zigbee gateway (Dresden ConBee II) working on my DS214+ (armadaxp, DSM 6.2.3, no docker), I'm finally running your 0.118 version of home assistant core. Thanks a lot for your decent work! There are still some non-docker Synology's out there...
Since I am and will be interested in a current version of home assistant core and have some (non-social) programming skills, I checked out github for my first time to see if I might help. Thanks to your great doc, I was able to cross-build the home assistant core 0.118 using your docker container toolchain.

Reading through the wiki, issues and PRs I learnt that python38 is on its way, and hgy59 and others are working on the 2021.1.5 update of home assistant core.

To proceed, I have the following questions. I hope not to ask the obvious - to me, also RTFM with link is helpful.

1. Why are you going for python 3.8 and not 3.9? 
1. AFAIK, synology has released a python 3.8 SPK (called py3k in the filesystem) - why do you need to build your own?
1. Why are the library requirements https://github.com/SynoCommunity/spksrc/blob/master/spk/homeassistant/src/requirements.txt different from the ones in https://github.com/home-assistant/core/blob/0.118.5/homeassistant/package_constraints.txt?
1. When does the public spk repository get updated packages? From the master branch?

FYI regarding (usb) kernel modules (also a topic for spksrc AFAIK) I used the modules from the UsbSerialDrivers package from http://www.jadahl.com/drivers_6.2/, GitHub https://github.com/jdel/sspks. They worked for me when I played with openHAB on the mentioned hardware. Perhaps he would be willing to share some know-how.

**Comment by Forge36** [comment]
1. I think your referring to #4413 from issue #4284
3.8 appears preferred as
>  it's now the oldest "stable" version

2. I'm not certain, but https://github.com/SynoCommunity/spksrc/pull/4413#issuecomment-772060725 might address that
> BTW: the creation of links like `/usr/local/{package-name} => /var/packages/{package-name}/target` or `/usr/local/{package-name} => /volume1/@appstore/{package-name}` will not work with DSM >= 7.0.

(I think that means if we can upgrade to 3.8 like this we can also support DSM 7 with greater confidence/speed)

If you're able to get HA updated to latest with an alternate method I'd love to help test your fix. Next free weekend I have I'm hoping to focus on moving the existing branches forward.

You may be able to get a better answer on those issues/merge requests.

3 and 4 I don't believe I can help with.

**Comment by rs1gg** [comment]
Thanks, I start to understand.
1. There are several applications dependent on python in spksrc. All with their own python dependency lifecycle. Home assistant 2021.1 requires python 3.8 and does not support python 3.9, only [2021.2 does](https://www.home-assistant.io/blog/2021/02/03/release-20212/) => starting with python 3.8, spksrc offers separate packages for all minor python versions. So we can probably expect a python39 module, etc. Applications can choose which python minor version to use and upgrade independently of each other. This also makes things more flexible to go for DSM>=7.0.
2. spksrc can't rely on synology's own python package, since it needs to compile application specific _native_ python wheels. Cross-compiling is the whole meaning of spksrc 🤦. When I tried to install 2021.1 home assistant in a python 3.8 env on my synology I exactly failed to compile the native wheels (unfixable errors started at cffi wheel, missing header files).
3. I still don't get 100% why there are different dependencies for home assistant in the spksrc package and home assistant core of its own. The spksrc [install wizard of HA core](https://github.com/SynoCommunity/spksrc/blob/master/spk/homeassistant/src/wizard/install_uifile) states that not all addons are included, so this is probably why some dependencies are missing in spksrc. But why are there different version specifications for the same dependency? spksrc seems to prefer exact version qualifiers (==), where homeassistant itself has some >= version qualifiers, e.g. `jinja2==2.11.2` vs. `jinja2>=2.11.2`.
4. Has nothing to do with home assistant -> skip for now.

As for HA core 2021.1.5, hgy54 already has a [branch prepared](https://github.com/hgy59/spksrc/tree/update_homeassistant_py38/spk/homeassistant).

**Comment by hgy59** [comment]
reagarding 3.
The synocommunity `requirement.txt` for home assistant core package is based on `home-assistant-core/requirement.txt` for the core packages and on `home-assistant-core/requirements_all.txt` for other dependencies. Some additional dependencies are added as they are missing at installtion, and only the packages needed for the default integrations are verified for successful installation.
So most of the packages for components are commented out. Only the dependencies that need a cross compiled wheel are left uncommented. Others are commented as they depend on cross compiled libraries or cross compiled wheels needing the toolchain (like cross/numpy).

As far as I understand we have cross compiled python modules, cross compiled wheels (compiled with toolchains), and cross compiled wheels with cython.
