### ISSUE TITLE
Minor error in readme (virtual machine instructions)

### ISSUE THREAD

**Issue by Marcoevich** [SynoCommunity/spksrc#4425]
Hello,

I'm setting up my build env and virtual machine according to your instructions in the readme. I'm getting started to build my own DSM7 packages. Thanks for your hard work so far! :)

There's a small error in the instructions in the readme. This line:

`wget https://bootstrap.pypa.io/get-pip.py -O - | sudo python2`

Must be replaced with this:

`wget https://bootstrap.pypa.io/2.7/get-pip.py -O - | sudo python2`

Otherwise I get a syntax error. This is because they dropped support for python 2.7.

See this link for more information: https://unix.stackexchange.com/questions/631244/why-does-get-pip-py-complain-about-invalid-syntax

Thanks!

**Comment by Marcoevich** [comment]
Can I use this issue to ask a support question? In the [Developers How To](https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO) the output of the command `make setup` is `Setting default toolchain version to DSM-6.1`

How do I set the toolchain version to DSM-7.0 ?

**Comment by hgy59** [comment]
documentation is updated (and Dockerfile fixed) this closes this issue.

**Comment by hgy59** [comment]
> 
> 
> Can I use this issue to ask a support question? In the [Developers How To](https://github.com/SynoCommunity/spksrc

It is bad practice to use an existing issue for an unrelated question...

> How do I set the toolchain version to DSM-7.0 ?

you need the dsm7 branch for dsm7 builds (see #4395), as the branch has not been merged yet.

On the dsm7 branch, in the spksrc folder call `make dsm-7.0`.
This will create a `local.mk` file, with `DEFAULT_TC=7.0`

When you call `make setup` the `local.mk` file is created/updated with `DEFAULT_TC=6.1` (the current default for DEFAULT_TC).

You don't need to have `local.mk` when you use the following kind of command to build specific packages in the spk folder:
`make arch-x64-7.0`
or
`make TCVERSION=7.0 ARCH=x64`

If you call only `make arch-x64` it will take the `TCVERSION` from `DEFAULT_TC` defined in `local.mk` (or it will fail if not exists or not defined).

**Comment by hgy59** [comment]
> 
> 
> Can I use this issue to ask a support question? In the [Developers How To](https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO) the output of the command `make setup` is `Setting default toolchain version to DSM-6.1`
> 

@Marcoevich I just updated the developers how to with a section about default toolchain versions.

**Comment by Marcoevich** [comment]
Thanks a lot @hgy59 ! All working now :)

**Comment by Marcoevich** [comment]
Hello @hgy59 just a heads up, the URL for pip has changed again. It's now `https://bootstrap.pypa.io/pip/2.7/get-pip.py`

See the message:

Hi there!

The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:

    https://bootstrap.pypa.io/pip/2.7/get-pip.py

Sorry if this change causes any inconvenience for you!

We don't have a good mechanism to make more gradual changes here, and this
renaming is a part of an effort to make it easier to us to update these
scripts, when there's a pip release. It's also essential for improving how we
handle the `get-pip.py` scripts, when pip drops support for a Python minor
version.

There are no more renames/URL changes planned, and we don't expect that a need
would arise to do this again in the near future.

Thanks for understanding!

- Pradyun, on behalf of the volunteers who maintain pip.
