### ISSUE TITLE
Add requests to python 3.7 for sabnzbd (but really sickbeard custom forks)

### ISSUE THREAD

**Issue by farmerbean** [SynoCommunity/spksrc#4426]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ sickbeard-custom 
_Package Version:_ sickgear-master (fork) 

_NAS Model:_  ds1515+
_NAS Architecture:_  intel 
_DSM version:_  6 latest 

### Expected behavior
Some sickbeard forks are now using/relying on python 3 in other apps for automation (specifically sabnzbd 3.11) to run processing scripts. Specifically, SickGear:master, has 2 scripts to run from sabszbd that need python3 requests module to execute.

### Actual behavior
Sickgear script fails 'need requests module'

### Steps to reproduce
_1._ Install Sickgear:master using custom fork of Sickbeard from DSM package manager 
_2._ Follow wiki instructions to symlink/copy sabsbzd scheduler scripts for sabnzbd compatibility 
_3._ pull tv episode in sickgear
_4._ sabsbzd starts/runs/completes
_5._ sabsbzd shows error from script (autoProcessTV.py)
_6._ error: needs requests module

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
NA
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
NA
```

**Comment by farmerbean** [comment]
I resolved this with the following steps:

ssh to Syno:

_1. /volume1/@appstore/sabnzbd$ source env/bin/activate
_2. sudo pip3 install requests
_3. deactivate

Can we get requests added to either sabnzbd requirements or python 3 requirements?

**Comment by BenjV** [comment]
There are thousands of external module like requests and it is impossible to include them all in the Python package.
So an application that needs a certain module should include it hemzelf or create a virtual environment with requests as a site-package.
If such modules are included in the Python package then it could create conflicts if different python applications need different versions of such a module.

So if an external script is used it should have the request module on board.

**Comment by farmerbean** [comment]
Absolutely agree, though requests seems fairly common. What's tricky in this case is that it's needed for a Sickgear script that extends Sabnzbd - but doesn't run inside Sickgear itself. These two apps are loosely related in the PVR world. Just flagging the issue and its resolution to help others and if there's a way to improve people's user experience of SynoCommunity packages.. surely that should be a goal?

**Comment by BenjV** [comment]
If you want to do it this way the only ssh command  you need after you have logged in as admin is:

>  sudo /var/packages/python3/target/bin/pip3 install requests

**Comment by hgy59** [comment]
Python 3.7 package is not maintained anymore.
