### ISSUE TITLE
Cops wil not open

### ISSUE THREAD

**Issue by HeinrichH** [SynoCommunity/spksrc#4430]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ COPS
_Package Version:_ 1.0.1-5

_NAS Model:_ Synology DS1819+
_NAS Architecture:_ X86
_DSM version:_ DSM 6.2.3-25426 Update 3

### Expected behavior
Tell us what should happen
The program should open in a webbrowser by typing: ipnumber NAS\Cops

### Actual behavior
Tell us what happens instead
Webowser gives a error, request fault

### Steps to reproduce
_1._ just try to open it again
_2._ same fault
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```No log to finf
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by nathan005** [comment]
[According to the Dev](https://github.com/seblucas/cops/wiki/Howto---Synology) the SynoCommunity Package is depreciated, and not actively maintained.

I'd recommend using docker to install the latest version
you can use [this package](https://hub.docker.com/r/linuxserver/cops)
Here is a [basic tutorial](https://www.synoforum.com/resources/calibre-book-manager-in-docker.78/)
_you will need to adjust as this one is directly for calibre_

I would recommend changing the ports form the defaults as well 
(80 is default web service so it may conflict so use something between 49152-65535 as the local port to 80 on the container port)

For PUID/PGID 
Follow [this Tut](https://drfrankenstein.co.uk/creating-users-and-obtaining-their-ids/)

Hope this is helpful to you.

**Comment by hgy59** [comment]
cops should be fixed with the latest release ( v1.4.2-7, 2023-09-04)

**Comment by mreid-tt** [comment]
Hi @HeinrichH, it looks like this issue has been open for some time without recent updates. As indicated by @hgy59, a new version of COPS (v1.4.2-7) has been released which may have resolved this issue. Can you please test with the latest version and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!
