### ISSUE TITLE
Please rename python3.8 to python3

### ISSUE THREAD

**Issue by BenjV** [SynoCommunity/spksrc#4441]
The newly release python3.8 should not have been named python3.8 because all packages that are build with python3 must now be changed before they can use the new python3.8

So please make the python3.8 an upgrade of python3 and not a new package.

**Comment by hgy59** [comment]
This is the intention to enable rolling updates.
Otherwise we have to update all packages that depend on python3 at the same time and when you install such a python3 update all installed packages that depend on python3 are broken.

This kind of versioning is the same as synology uses for php 7.

**Comment by BenjV** [comment]
This is a very wrong idea!
Python 3.8 is completely backward compatible with python3.7 (the current pyton3).
So you can treat it like an upgrade and not as a new package.
Every application that run on python3.7 will also run on python3.8 without any problem.

Now all python packages have to change and if you just upgrade the current python3 nothing has to change.
Creating a new python package every time an upgrade of python occurs you  end up just like the php mess with lots op php package and nobody know which one to use.

**Comment by Safihre** [comment]
I also thought it strange at first and opposed it, but then I remembered what a pain Python 2.x updates were.. It required @ymartin59 to update all the Python 2 packages at once. Updates would take months.
Yes Python 3.8 is backwards compatible, but the binary compiled wheels included in the SPK's are not. So that's why they require all packages to be rebuild and republished.

**Comment by BenjV** [comment]
That sounds strange to me, binaries distributed with python should also be backwards compatible in my opinion and application who are using these non backwards compatible binaries are "dead in the water" and cannot upgrade to a higher python version anymore.
With this methode we end up with loads of python packages in the future, just like the php mess.

**Comment by Safihre** [comment]
No, binary Python wheels have never been compatible between Python versions on any platform, not SynoCommunity specific. That's why on PyPi there's a separate wheel for every separate Python version.

**Comment by BenjV** [comment]
Backwards compatible is more or less the holy grail of python.
That was the reason they created python 3, a complete new major version not backward compatible with python 2.
Within a major release (so all 3 versions) everything should be backwards compatible.
When there are binaries which are not, they should not be packaged with python but should be release as a separate packages.
(Just my personal opinion)

Can you give me an example of a not backwards compatible binary?
Something for python 3.7which does not work on python 3.8 for example.

**Comment by Safihre** [comment]
I think you are misunderstanding. When we compile a package, say SABnzbd, we use the SynoCommunity cross compiler to compile the Python C extension `sabyenc` binary wheel. This wheel will only work on the Python major it was compiled on, so 3.7 for example, not on Python 3.8. This is the case for all C extensions, which there are a lot of.

**Comment by BenjV** [comment]
Python only applications do not have that problem and it goes against the idea that python applications should be portable without rebuilding.

But I predict this will create a complete mess of python versions and also python applications (one for every python release) 
We now have python 2, python 3.7, python 3.8, python 3. (3.8.2 from Synology ) and the current python version is python 3.9 so that will be the next one.

**Comment by Safihre** [comment]
Yes, that's true. I'm also not a fan, but then again, what does it really matter for the end user? Just a few more MB of storage for the extra Python version.
Ideally we would transition all packages over to the new Python release, but realistically, that probably won't happen for a while..

**Comment by BenjV** [comment]
The problem is that python applications can upgrade themselves, but that won't be possible on a Synology Nas anymore if the new version needs a higher python version.
When on the other hand python 3 will always be the latest version that problem is not there.

So I am now forced to stop using the SynoCommunity version and use the Synology version, they only use one python 3 for all 3.xx versions.

**Comment by smaarn** [comment]
> The problem is that python applications can upgrade themselves, but that won't be possible on a Synology Nas anymore if the new version needs a higher python version.
> 
> When on the other hand python 3 will always be the latest version that problem is not there.
> 
> 
> 
> So I am now forced to stop using the SynoCommunity version and use the Synology version, they only use one python 3 for all 3.xx versions.

Well, another problem is that we cannot make any assumption that other applications
1. do support the latest version (for example the current version of domoticz does not support python 3.8 as they actually broke backward compatibility on some C library code)
2. actually support change of python version (virtual env, for example, creates symbolic links which do account for python version)
3. actually perform upgrades on startup if required

If we manage to find a path for all the three points mentioned above (defining explicit max python versions? providing with virtualenv helpers or fake symbolic links?) then we could have a go, I guess.

**Comment by BenjV** [comment]
If you don't mind having lots of python versions, a solution would be to create a python 3 which always is the latest version along with python 3.7, python 3.8.python 3.9 etc.

And what about the micro versions like python 3.8.1, python 3.8.2 etc, don't they pose the same problems?

**Comment by smaarn** [comment]
> If you don't mind having lots of python versions, a solution would be to create a python 3 which always is the latest version along with python 3.7, python 3.8.python 3.9 etc.

Totally agree. The only requirement being to potentially have a mechanism to detect minor version changes and perform virtual environment redeployments when possible.

> 
> 
> 
> And what about the micro versions like python 3.8.1, python 3.8.2 etc, don't they pose the same problems?

Patch versions are fine actually.

**Comment by Safihre** [comment]
> And what about the micro versions like python 3.8.1, python 3.8.2 etc, don't they pose the same problems?

See also https://docs.python.org/3/c-api/stable.html why indeed only between major versions (3.7->3.8) this is a problem.

**Comment by BenjV** [comment]
Am I correct in concluding this is only a problem on Windows and not on Linux?

**Comment by Safihre** [comment]
This is platform independent, it has to do with the Python C-API, not the platform.

**Comment by BenjV** [comment]
> As a consequence, extension modules need to be recompiled for every Python release (although an exception is possible on Unix when none of the affected interfaces are used). In addition, on Windows, extension modules link with a specific pythonXY.dll and need to be recompiled to link with a newer one.

**Comment by Safihre** [comment]
Yes, but because of `although an exception is possible on Unix when none of the affected interfaces are used` for example pip will also install Python major version specific versions. Because you can't know which interfaces are used by the C-extensions.
A simple example is the `numpy` package: https://pypi.org/project/numpy/1.20.1/#files
Each major release has it's own download, on each platform.

**Comment by BenjV** [comment]
Another problem arised.
Pure Python applications which could run on python3.7 or higher cannot have a python dependency in the INFO file anymore.
It must be either Pyton3 (which is Python3.7) or Python38 and so the only solution is no dependency anymore.
The package name in the INFO file should be in both cases python3 and not python3/python38 to avoid this problem

This naming is becoming a real mess.

**Comment by Safihre** [comment]
Can you give an example of a pure Python SPK on SynoCommunity?

**Comment by BenjV** [comment]
SickBeard-Custom, Subliminal, PlexPy Custom  and maybe more
And there are other package sources who use Python from the SynoCommunity.

I still think a Python3 (with the latest version) version should be made available along with python3.7, python3.8 etc.
Now Python3 = Python3.7

**Comment by hgy59** [comment]
as starting with Python 3.10 (#4937) we will definitivly avoid to use a single python3 package.
