### ISSUE TITLE
SynoCli File Tools v2.1-6: DS115j / DSM 7.0-41222 - invalid package privilege content

### ISSUE THREAD

**Issue by zibous** [SynoCommunity/spksrc#4442]
### Setup
_Package Name:_  SynoCli File Tools 
_Package Version:_ v2.1-6

_NAS Model:_ DS115j
_NAS Architecture:_ 
_DSM version:_ DSM 7.0-41222 

### Expected behavior
Can I make a setting with which I can install the package SynoCli File Tools v2.1-6? 

### Actual behavior
During the installation I get the following error message:
```
2021-02-18T18:38:57+01:00 DSNAS2018 synoscgi_SYNO.Core.Package.Installation.Download_1_check[19553]: 
 pkgverify.cpp:278 Failed to verify package, 
 spk=[/volume1/@tmp/@synopkg/@download/synocli-file/@SYNOPKG_DOWNLOAD_synocli-file] 
 result=[{"action":"prepare","beta":false,"betaIncoming":false,"error":
  {"code":319,
   "description":"invalid package privilege content"
  },
  "installReboot":false,
  "package":"synocli-file",
  "packageName":"SynoCli File Tools",
  "stage":"prepare","success":false}]
```
### Steps to reproduce
_1._ Install with Package APP

![Bildschirmfoto 2021-02-18 um 18 29 16](https://user-images.githubusercontent.com/30198737/108399325-465abd00-721a-11eb-9f28-27ea2d36c011.png)

**Comment by hgy59** [comment]
Packages in the synoommunity package center are not updated for DSM 7. Please see [READMME.rst](https://github.com/SynoCommunity/spksrc/blob/master/README.rst).
