### ISSUE TITLE
[Update] Jackett

### ISSUE THREAD

**Issue by JeremieBergeron** [SynoCommunity/spksrc#4443]
### Setup
_Package Name:_ Jackett
_Package Version:_ 0.16.1340-12

_NAS Model:_ DS418
_NAS Architecture:_ 64 bits ??
_DSM version:_ 6.2.3-25426

Hi,

I am not sure if I can ask that, but would it be possible to update Jackett?
The last update was a long time ago, so there is a lot if indexer that does not work anymore.

Thank you very much

**Comment by hgy59** [comment]
Jackett was just updated with #4207 to version 0.17.474, but it seems that this is not uploaded to the synocommunity package repository yet.

@publicarray shall we upload jackett to the repo?
_there are 7 updates in the last 12 days. Is it worth to update this package again, before publishing?_
We must at least increment the `SPK_REV` for publishing.

**Comment by JeremieBergeron** [comment]
Ok, thank you very much.
I will wait 👍

**Comment by publicarray** [comment]
@hgy59 I've already bumped the revision on master in a followup commit (`SPK_REV`) and tried to publish 6 days ago but hit this error: https://github.com/SynoCommunity/spkrepo/issues/65

Yes, I think we  should bump the version and checksums again before publishing. The releases contain small changes nearly every day (Github bot). So I wouldn't worry about it too much in the future though

**Comment by publicarray** [comment]
Thanks @hgy59. I've just updated and published the package.

It should be live in approx. 48 hours.

@JeremieBergeron FYI Jackett has an inbuilt auto updater. (Click on the yellow "check for updates" button)

**Comment by JeremieBergeron** [comment]
Ok, thank you :)
