### ISSUE TITLE
Failure to run Jackett package

### ISSUE THREAD

**Issue by Landaro546** [SynoCommunity/spksrc#4446]
### Setup
Jackett 
0.17.568.-13

Synology DS418
DSM 6.2.3-25426 Update 3

### Expected behavior
After successful Installation package should run.

### Actual behavior
After successful installation, package does not run. After a few moment system gives message "Failed to run package service"

### Steps to reproduce
After installation, system produces message
or
Clicking on "Run" button, produces message

#### Package log
[jackett_install.log](https://github.com/SynoCommunity/spksrc/files/6021982/jackett_install.log)
[jackett.log](https://github.com/SynoCommunity/spksrc/files/6021983/jackett.log)

**Comment by hgy59** [comment]
This is already reported [here](https://github.com/SynoCommunity/spksrc/pull/4207#issuecomment-782941617).

The .NET version of Jacket is now deactivated in the package center.
I assume it will only be available with DSM7.

**Comment by Wuszek** [comment]
@hgy59 not sure, if it will be in this form as https://github.com/dotnet/runtime/issues/33384#issuecomment-629996376
Now, this package requires 6.0.28 lib, but in DSM7 it will be 6.0.24.

**Comment by hgy59** [comment]
@Wuszek I have build a dotnet-sdk package some time ago. 
On DSM 6 I got always the message about missing version information for `libstdc++.so.6` (but the simple hello world app was running just fine).
On DSM 7 such a message for `libstdc++.so.6` is gone (verified with dotnet-sdk v5.0.102).

**Comment by Wuszek** [comment]
@hgy59 you are right, thats why I deleted my post before your answer.

**Comment by jeremymeyers** [comment]
FWIW, I'm on a DS216+II (Braswell chip) which is not listed as a compatible Syno https://synocommunity.com/package/jackett .  Just updated to the latest Syno package (0.16.1340-12) and the updated in-app to 0.17.x.  It seems to work just fine. Not sure if that means @m4tt075 can add Braswell to the 0.17 release but wanted to give a data point. Happy to give more info/logs/etc

**Comment by Wuszek** [comment]
@jeremymeyers  Package 0.16.1340-12 is still mono version. This topic is about first try to move jackett to .NET core (that was tagged Version 0.17.568-13, from february), which was failed, and that package was disabled in repo. 

Here [https://github.com/SynoCommunity/spksrc/pull/4485](url) you can find PR with updated .NET jackett, that worked for me.
