### ISSUE TITLE
[Package Request] at, batch, atq, atrm

### ISSUE THREAD

**Issue by stephane-archer** [SynoCommunity/spksrc#4447]
* Name: at, batch, atq, atrm
* Description: executes commands at a specified time.
* Software documentation: https://linux.die.net/man/1/at

I would like to execute a script tomorow on my Synology Nas.
I don't find a way to do that.
I usually use `at`
Do you know any other way or can you make a package containing `at`?
Thank you

**Comment by hgy59** [comment]
@stephane-archer you don't need an additional command for this. You can use the DSM integrated Task Scheduler.

Within DSM `Control-Panel` / `Task Scheduler` select `Create` / `Scheduled Task` / `User-defined script`
Aside of the run command you can select email notification, the task name, the user to run with, and more...

You even can create tasks triggered by shutdown or boot-up event.

**Comment by stephane-archer** [comment]
@hgy59 you are right and it's doing exactly what I want.
The only inconvinience is, it cannot be done from the cli.
I will use the DSM integrated Task Scheduler but I think the `at` cli can be a great addition for a NAS as it's more convinient and stardard.

**Comment by hgy59** [comment]
I could not find any source code for `at` commands. It is part of the posix base system and should be provided by synology.
