### ISSUE TITLE
DSM7: fail to compile packages: /mnt/c/Program: no such file or directory

### ISSUE THREAD

**Issue by Marcoevich** [SynoCommunity/spksrc#4448]
Hello,

I see that you have updated the DSM7 branch. I have removed my local spksrc directory and cloned it again.

Unfortunately I get compile errors now with a lot of packages. For example with ffmpeg:

===>  Processing dependencies of ffmpeg
env: ‘Files/WindowsApps/TheDebianProject.DebianGNULinux_1.3.0.0_x64__76v4gfsz19hv4:/mnt/c/Program’: No such file or directory
make[2]: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 127
make[2]: Leaving directory '/home/admin/spksrc/cross/ffmpeg'
make[1]: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 2
make[1]: Leaving directory '/home/admin/spksrc/spk/ffmpeg'
make: [../../mk/spksrc.spk.mk:464: arch-evansport-7.0] Error 2 (ignored)

Also with Python38:

LIBFFI_INCLUDEDIR=/home/admin/spksrc/spk/python3/work-evansport-7.0/install/var/packages/python3/target/include/ wget https://bootstrap.pypa.io/get-pip.py -O - | build-python
/bin/sh: 2: export: Files/WindowsApps/TheDebianProject.DebianGNULinux_1.3.0.0_x64__76v4gfsz19hv4:/mnt/c/Program: bad variable name
make[2]: *** [Makefile:90: python3_post_install] Error 2
make[2]: Leaving directory '/home/admin/spksrc/cross/python3'
make[1]: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 2
make[1]: Leaving directory '/home/admin/spksrc/spk/python3'
make: [../../mk/spksrc.spk.mk:464: arch-evansport-7.0] Error 2 (ignored)

I guess it's searching for a path in C:\Program Files\ which needs to be quoted due to the space in the pathname. I'm working in a Debian 10 installation on WSL2.

Can you check what's causing this error?

**Comment by Marcoevich** [comment]
Solved it locally by changing line 53 of spksrc/mk/spksrc.depend.mk from:

`env $(ENV) $(MAKE) -C ../../$$depend ; \`

to

`env $("ENV") $(MAKE) -C ../../$$depend ; \`

**Comment by hgy59** [comment]
@Marcoevich your solution looks strange, can you try `env "$(ENV)" $(MAKE) -C ../../$$depend ; \` ?

**Comment by Marcoevich** [comment]
Hi @hgy59 that one doesn't work. After changing that line the error becomes:

===>  Processing dependencies of ffmpeg
env: ‘-I/home/admin/spksrc/spk/ffmpeg/work-evansport-7.0/install//var/packages/ffmpeg/target/include’: No such file or directory
make[1]: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 127
make[1]: Leaving directory '/home/admin/spksrc/spk/ffmpeg'
make: [../../mk/spksrc.spk.mk:464: arch-evansport-7.0] Error 2 (ignored)

**Comment by Marcoevich** [comment]
But as you said, my own solution is also not a real solution. ffmpeg continues to build, but python38 generates the same error

**Comment by hgy59** [comment]
Thanks for trying. We might add your workaround (with further testing), but as WSL is not an officially supported environment, I doubt we will do this.

We recommend to use the docker image synocommunity/spksrc, a debian VM or a real debian installation.

**Comment by Marcoevich** [comment]
Thanks for checking this @hgy59 I'll create a Debian VM for now.
