### ISSUE TITLE
Compile error for cross/libtorrent

### ISSUE THREAD

**Issue by DigitalBox98** [SynoCommunity/spksrc#4468]
### Setup
_Package : cross/libtorrent
_Package Version: 1.1.14

_NAS Model: DS716+II
_NAS Architecture: braswell 
_DSM version: 6.1 

I'm trying to compile Deluge, but before I need to compile the libtorrent library. 
Unfortunately I have the issue described below. 

I will try to investigate deeper the reason, but if you have some clues it would be great.

### Expected behavior
The cross/libtorrent should compile without error

### Actual behavior
The compilation phase is raising an error relative to Python library

### Steps to reproduce
_1. cd cross/libtorrent
_2. make arch-braswell

#### Other logs
configure
configure: error:
Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LIBS environment variable.
  Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"

ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.

See `config.log' for more details
make[1]: *** [../../mk/spksrc.configure.mk:50 : configure_target] Erreur 1

**Comment by hgy59** [comment]
cross/libtorrent is built as python-wheel. You cannot build a python wheel in cross folder by its own. 
You can compile wheels only in the context of an spk package as it needs python as build dependency.
AFAIK this was always the case.

If I want to build only one python wheel package with minimal dependencies I temp. created a diyspk Makefile that depends on such a cross package and has build dependeny of the respective cross/python package.
