### ISSUE TITLE
Synology Package Center failed to run SABnzbd package after update

### ISSUE THREAD

**Issue by wahteva** [SynoCommunity/spksrc#4470]
### Setup
_Package Name:_ SABnzbd
_Package Version:_ 3.1.1-46

_NAS Model:_ DS916+
_NAS Architecture:_ INTEL Pentium N3710
_DSM version:_ DSM 6.2.3-25426 Update 3

### Expected behavior
SABnzbd package should start running

### Actual behavior
SABnzbd package doesn't run. The package center displays an error that the package fails to run.

### Steps to reproduce
_1._ Install latest SABnzbd package, ver 3.1.1-46
_2._ Run package from Package Center
_3._ Package fails to run

#### Package log
_find logfiles in `/var/packages/{package}/var/`, for DSM7: `/var/log/packages/{package}.log`, for DSM < 6.0: protocol in Package Center.
_
```
Fri Mar  5 12:08:14 AEDT 2021
Starting sabnzbd command env LANG=en_US.UTF-8 /volume1/@appstore/sabnzbd/env/bin/python3 /volume1/@appstore/sabnzbd/share/SABnzbd/SABnzbd.py -f /volume1/@appstore/sabnzbd/var/config.ini --pidfile /volume1/@appstore/sabnzbd/var/sabnzbd.pid -d
Not all required Python modules are available, please check requirements.txt
Missing module: Cheetah
You can read more at: https://sabnzbd.org/python3
If you still experience problems, remove all .pyc files in this folder and subfolders

```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
Workaround is to install cheetah yourself with this command.
Login to the commandline of your Nas as admin
Make yourself root and install cheetah.
This are the command to use
```
sudo -i
cd /var/packages/sabnzbd/target/env/bin
pip install cheetah3

```

**Comment by publicarray** [comment]
@Safihre can  you look at this? Is cheetah a new dependency?

**Comment by Safihre** [comment]
No it's not, and it's a core dependency so I am very surprised. If this failed I would have expected many people complaining about this already.
@wahteva Can you try to re-install SABnzbd?

**Comment by jaserodley** [comment]
I don't want to clutter up this thread but I'm also having this issue. If there's any helpful info I can supply to you @Safihre, please let me know.

**Comment by BenjV** [comment]
You could check if cheetah is present.
It is this file:

> /var/packages/sabnzbd/target/env/bin/cheetah

**Comment by jaserodley** [comment]
> You could check if cheetah is present.
> It is this file:
> 
> > /var/packages/sabnzbd/target/env/bin/cheetah

Yes it is present.

**Comment by BenjV** [comment]
Kijk eens in

>  /var/packages/sabnzbd/target/env/lib/python3.8/site-packages/Cheetah

En zoek de naam van de _namemapper eens op, die moet voor de juiste CPU zijn.
Voor mijn DS116 (Arm cpu) heet hij:

> _namemapper.cpython-38-arm-linux-gnueabihf.so

**Comment by jaserodley** [comment]
Mine is a DS916+. Filename is:

> _namemapper.cpython-38-x86_64-linux-gnu.so

**Comment by BenjV** [comment]
Seems all ok

**Comment by publicarray** [comment]
Maybe it has todo with the python version the package was compiled with vs the python version its running on?

**Comment by Safihre** [comment]
@jaserodley have you tried uninstalling it and then reinstalling it?

**Comment by CatStarwind** [comment]
Is there any work around currently for getting SABNZBD back online in DSM7?

**Comment by CatStarwind** [comment]
I'm having the same issue now too. SABNZBD refuses to repair on DSM7.

**Comment by jaserodley** [comment]
@CatStarwind AFAIK it's not supported at this time. I've switched everything over to Docker. It's a pain but should be trouble free moving forward.

**Comment by wahteva** [comment]
> @CatStarwind AFAIK it's not supported at this time. I've switched everything over to Docker. It's a pain but should be trouble free moving forward.

Yes I did the same. Was not able to resolve this issue.

**Comment by BenjV** [comment]
The native package runs fine here both on DSM 6 as on DSM7

**Comment by mreid-tt** [comment]
Hi @wahteva, it looks like this issue has been open for some time without any recent updates. Since then, a new version of SABnzbd (v4.1.0-66) has been released which may have resolved this issue. Can you please test with the latest version and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!

**Comment by wahteva** [comment]
Thanks for the follow up. I ended up running the package from a docker container. I'll close this thread.
