### ISSUE TITLE
packages.synocommunity.com is unavailable

### ISSUE THREAD

**Issue by tchimper** [SynoCommunity/spksrc#4472]
Hello, 
Just trying to add https://packages.synocommunity.com in DSM's package sources fails. 

Manually opening the URL gives a 400 Bad Request Error : 

Bad Request

The browser (or proxy) sent a request that this server could not understand.

Would the repository be down ?

**Comment by timi137137** [comment]
Me too! I have found the previous issues. It seems that there were similar issues long ago. Looking forward to a quick fix.
