### ISSUE TITLE
Request for additional LG integration for Home Assistant Core

### ISSUE THREAD

**Issue by Szeryff** [SynoCommunity/spksrc#4480]
1. LG webOS Smart TV: https://www.home-assistant.io/integrations/webostv/
2. LG Soundbars: https://www.home-assistant.io/integrations/lg_soundbar/
3. LG Netcast: https://www.home-assistant.io/integrations/lg_netcast/

**Comment by rs1gg** [comment]
There is a good chance that those integrations are indeed packaged (they come with HA core), but just don't show up in the GUI (in the list of integrations to choose from when adding integrations). I am neither a packaging nor a HA core expert, but encountered the same with other integrations. See #4475.

However, manual configuration of HA core needs SSH access - if you are not familiar with that this workaround is not for you.

If after manual configuration the log shows missing python dependencies, there is a good chance that they can be added to the corresponding python virtual environment using using https://github.com/SynoCommunity/spksrc/issues/4458#issuecomment-787063570

**Comment by Szeryff** [comment]
You are absolutely right. Integrations are shown in:
/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components
and worked like a charm :)
The only disadvantage, you need to add them manually.

**Comment by Szeryff** [comment]
With new HA Core 2021.9.7-15 some dependencies for integrations are missing but can be easily installed with PIP.
However for `webostv` integration that is available in components `aiopylgtv` dependency is missing.
Unfortunately installing this over PIP fails on building wheels for numpy with following error:
```
  File "numpy/core/setup.py", line 666, in get_mathlib_info
      raise RuntimeError("Broken toolchain: cannot link a simple C program")
  RuntimeError: Broken toolchain: cannot link a simple C program
  ----------------------------------------
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```
Could you please advise?

**Comment by hgy59** [comment]
numpy==1.21.1 is already included in the homeassistant package.
Numpy shoult not be built - maybe it is a version conflict?

**Comment by Szeryff** [comment]
Runnin `/volume1/@appstore/python38/bin/pip install aiopylgtv`
For numpy dependency it show something like this:
`Collecting numpy>=1.17.0
  Using cached numpy-1.21.4.zip (10.6 MB)
  Installing build dependencies`
So it seems that version 1.21.1 should be enought. 

However how can I check if numpy is indeed available?
When I run `/volume1/@appstore/python38/bin/pip show numpy`
I get: `WARNING: Package(s) not found: numpy`

If I search for package in components directory with `ls /volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components | grep numpy`
I get no results.

**Comment by hgy59** [comment]
with `/volume1/@appstore/homeassistant/env/bin/pip freeze` you get a list of all installed packages of the homeassistant virtual python environment.

**Comment by Szeryff** [comment]
Didn't know there is separate python for HA. Using PIP from HA works like a charm and numpy dependency is satisfied.
Thank you, closing the topic. I hope this hint will also be useful to other people.
