### ISSUE TITLE
Media folder in Home Assistant Core

### ISSUE THREAD

**Issue by Szeryff** [SynoCommunity/spksrc#4481]
Is there a default media folder pre-configured?

I tried setting up in **configuration.yaml**, as per documentation, following:
```
homeassistant:
  media_dirs:
    local: /volume1/video
```
but I'm getting an error trying to load such config into HA:

`Not a directory for dictionary value @ data['media_dirs']['media']`

**Comment by BenjV** [comment]
https://www.home-assistant.io/more-info/local-media/setup-media/

**Comment by Szeryff** [comment]
Thanks @BenjV. 
There is a problem with custom folders but creating media folder here
`/var/packages/homeassistant/target/var/config/`
works perfect.

**Comment by ymartin59** [comment]
@Szeryff care not to store large volume in `/var/packages/homeassistant/target/var/` because it is backup/restore during upgrade and your DSM temporary space location may be too short for operation to succeed.
A location like `/volume1/video` should work as far as service `sc-homeassistant` is granted read-access on share folder. Please refer to https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by Szeryff** [comment]
I confirm that adding in config this:
`homeassistant:
  media_dirs:
    local: /volume1/video`
and adding read permissions to `sc-homeassistant` service make it work.
Thanks!

**Comment by Szeryff** [comment]
I've set the media_dir as stated above and works fine.
However when I open media-browser in HA, go into the media directory and then from there I try to click `Local Media` button on top to return back home I get following error:
![image](https://user-images.githubusercontent.com/5165008/111055439-282d5900-8476-11eb-9280-25ee4c39892e.png)

**Comment by BenjV** [comment]
https://www.home-assistant.io/integrations/media_source/

**Comment by Szeryff** [comment]
Unfortunately this doesn't help. It seems it's know bug when multiple `media_dirs` are added in configuration:
[https://github.com/home-assistant/frontend/issues/7209](url)

**Comment by BenjV** [comment]
I this case make a new issue on the home-assistant github.
The SynoCom package has no influence over this.
