### ISSUE TITLE
Cannot Find ImageMagick - Inotify and other packages

### ISSUE THREAD

**Issue by vekexasia** [SynoCommunity/spksrc#4500]
Hello, I've managed to add synocommunity but i am unable to install inotify-tools which is a package listed in the website.

My NAS is DS920+ with DSM 6.2.4.

**Comment by publicarray** [comment]
Did you follow the instructions on https://synocommunity.com/ and used `https://packages.synocommunity.com/` as the URL and allowed 3rd party packages? In the package center do you see any packages on the `community` tab?

**Comment by hgy59** [comment]
Those packages are not yet built and published for the geminilake (and v1000) archs.
