### ISSUE TITLE
/dev/ttyACM0 access not ok for homeassistant/TI ZNP

### ISSUE THREAD

**Issue by mdeweerd** [SynoCommunity/spksrc#4513]
### Setup
_Package Name:_ Home Assistant Core
_Package Version:_ 2021.1.5-13

_NAS Model:_ DS415Play
_NAS Architecture:_ 
_DSM version:_ DSM 6.2.3-25426 Update 3 

### Expected behavior
/dev/ttyACM0 port should be available for HA.

### Actual behavior
Only root has access.

### 
While the https://github.com/SynoCommunity/spksrc/blob/c97be329eb56438cd56ae38c3ab6f2be9087fa3d/spk/homeassistant/src/60-synocommunity.homeassistant.rules exists on github, I can not find this in @appstore/homeassistant/* .

As a workaround, I perform the following command, which adds a rule for specific Zigbee devices:
```bash
cat > /lib/udev/rules.d/50-usb-zigbee.rules << 'EOF'
ATTRS{idVendor}=="04d8" , ATTRS{idProduct}=="000e", MODE="0666"
ATTRS{idVendor}=="04d8" , ATTRS{idProduct}=="0e00", MODE="0666"
ATTRS{idVendor}=="0451" , ATTRS{idProduct}=="16ae", MODE="0666"
ATTRS{idVendor}=="0451" , ATTRS{idProduct}=="16a8", MODE="0666"
EOF
```

With the above, the device has acceptable access rights (`ls -lrat /dev | grep ACM0`):
```
crw-rw-rw- 1 root   root  166,   0 Mar 21 23:42 ttyACM0
```

Some further info regarding my device:
```
|__usb1          1d6b:0002:0302 09  2.00  480MBit/s   0mA 1IF  (ehci_hcd 0000:01:0d.0) hub
  |__1-1         0451:16a8:0009 02  2.00   12MBit/s  50mA 2IFs (Texas Instruments TI CC2531 USB CDC __0X00124B00016A410C)
```

**Comment by ymartin59** [comment]
@th0ma7 As a kernel module expert, do you have any recommendation to set proper permission for device to sc-homeassistant service account?

**Comment by th0ma7** [comment]
@ymartin59 Well there are a few options but the most obvious one in my point of view would be to create a new group such as `sc-kernel`, assigning it to packages require `udev` device file access (ex. page 86: https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/7.0/enu/DSM_Developer_Guide_7_0_Beta.pdf).

Lastly modify the start-stop-status script in order to install a new udev rule (such as above) with the added `GROUP="sc-kernel"` and then access could probably be restricted to `MODE="0664"` or plain `MODE="0660"`.  An example is available in my PR https://github.com/SynoCommunity/spksrc/pull/4420/files#diff-e96d637c91bd05d3c5bfc796f44182132e8ed8a140c237a84121d0d6efd12479

Long story-short, I guess we should settle on the `sc-kernel` group, to be or not to be.  Document that then expose it.

**Comment by hgy59** [comment]
@mdeweerd you might find the solution [here](https://github.com/SynoCommunity/spksrc/issues/4651#issuecomment-850561562)

**Comment by mdeweerd** [comment]
> @mdeweerd you might find the solution [here](https://github.com/SynoCommunity/spksrc/issues/4651#issuecomment-850561562)

Thank you for the link.
However, I already mentionned a solution in my initial message above:
> ### Setup
> _Package Name:_ Home Assistant Core
> _Package Version:_ 2021.1.5-13
> 
> _NAS Model:_ DS415Play
> _NAS Architecture:_
> _DSM version:_ DSM 6.2.3-25426 Update 3
> 
> ### Expected behavior
> /dev/ttyACM0 port should be available for HA.
> 
> ### Actual behavior
> Only root has access.
> 
> While the 
> As a workaround, I perform the following command, which adds a rule for specific Zigbee devices:
> 
> ```shell
> cat > /lib/udev/rules.d/50-usb-zigbee.rules << 'EOF'
> ATTRS{idVendor}=="04d8" , ATTRS{idProduct}=="000e", MODE="0666"
> ATTRS{idVendor}=="04d8" , ATTRS{idProduct}=="0e00", MODE="0666"
> ATTRS{idVendor}=="0451" , ATTRS{idProduct}=="16ae", MODE="0666"
> ATTRS{idVendor}=="0451" , ATTRS{idProduct}=="16a8", MODE="0666"
> EOF
> ```


the issue is that this is not persistant accross DSM updates, and it is not a solution easy to manage for *any* user - one has to set up ssh access, etc.

**Comment by hgy59** [comment]
@mdeweerd There will be no easier solution as you need root access for such a configuration.

**Comment by mdeweerd** [comment]
Well, th0ma7 suggested a solution for this, he also refers to a pull request.

https://github.com/SynoCommunity/spksrc/pull/4420/files#diff-6e40c0dbeee530feed2003b51c7a1935d5792f35a98043bfb6dc3d361abffbd0  shows a concrete example of a usbrules source file.

I went through the code, it requires some effort to see the complete precise picture, but it seems to me that it is quite possible (and done in this PR) to add privileges to access USB devices.

So I do think that this will be done by the package(s) themselves in the future thanks to great work from th0ma7 and others.

**Comment by mdeweerd** [comment]
Closing this - I moved away from running HA on Synology.
