### ISSUE TITLE
[Package Request] slide (integration of Home Assistant)

### ISSUE THREAD

**Issue by dontinelli** [SynoCommunity/spksrc#4518]
Name: slide
Description: The slide implementation allows you to integrate your slide.store devices in Home Assistant using the official API.
Website: https://www.home-assistant.io/integrations/slide/
Software documentation: https://www.home-assistant.io/integrations/slide/ and https://documenter.getpostman.com/view/6223391/S1Lu2pSf?version=latest
Build/Installation documentation:
Source Code: https://github.com/home-assistant/core/tree/dev/homeassistant/components/slide
License: OSS

**Comment by rs1gg** [comment]
There is a good chance that those integrations are indeed packaged (they come with HA core), but just don't show up in the GUI (in the list of integrations to choose from when adding integrations). I am neither a packaging nor a HA core expert, but encountered the same with other integrations. See #4475.

However, manual configuration of HA core needs SSH access - if you are not familiar with that this workaround is not for you.

If after manual configuration the log shows missing python dependencies, there is a good chance that they can be added to the corresponding python virtual environment using using https://github.com/SynoCommunity/spksrc/issues/4458#issuecomment-787063570

**Comment by dontinelli** [comment]
Thank you for this workaround. With it I could implement the dependency (goslide-api). Unfortunately I do not know the version of the slide integration and cannot find it on github. Do you know, where I can find the version number?

By the way, without version number, the installation (not unexpectedly fails):
`admin@malimaki:/var/packages/homeassistant/target/env/bin$ sudo ./pip install slide
Password: 
ERROR: Could not find a version that satisfies the requirement slide (from versions: none)
ERROR: No matching distribution found for slide
WARNING: You are using pip version 20.0.2; however, version 21.0.1 is available.
You should consider upgrading via the '/volume1/@appstore/homeassistant/env/bin/python -m pip install --upgrade pip' command.`

**Comment by hgy59** [comment]
you need to install `goslide-api`, current version is `0.6.4`
you can find this requirement in the [manifest.json](https://github.com/home-assistant/core/blob/dev/homeassistant/components/slide/manifest.json) file for the homeassistant slide integration.

**Comment by rs1gg** [comment]
@dontinelli OT, do you operate slide.store hardware yourself? Are you happy with it? I was looking for curtain motors myself, low-prio though. They seem to be quite versatile and easy to install, but have quite a price tag. I wonder how much noise the motor makes. Can you hear it over the noise of the curtain sliders themselves?

**Comment by dontinelli** [comment]
> you need to install `goslide-api`, current version is `0.6.4`
> you can find this requirement in the [manifest.json](https://github.com/home-assistant/core/blob/dev/homeassistant/components/slide/manifest.json) file for the homeassistant slide integration.

according to the manifest.json in github the version of goslide-api is 0.5.1, which I also installed. I now updated to 0.6.4. For slide itself, the version seems to be a different one, at least the installation with 0.6.4 did not work for me:
`admin@malimaki:/var/packages/homeassistant/target/env/bin$ sudo ./pip install slide==0.6.4
Password: 
ERROR: Could not find a version that satisfies the requirement slide==0.6.4 (from versions: none)
ERROR: No matching distribution found for slide==0.6.4
`

**Comment by hgy59** [comment]
you need to install goslide-api==0.6.4 NOT slide
```
admin@malimaki:/var/packages/homeassistant/target/env/bin$ sudo ./pip install goslide-api==0.6.4 
```

**Comment by dontinelli** [comment]
> @dontinelli OT, do you operate slide.store hardware yourself? Are you happy with it? I was looking for curtain motors myself, low-prio though. They seem to be quite versatile and easy to install, but have quite a price tag. I wonder how much noise the motor makes. Can you hear it over the noise of the curtain sliders themselves?

Yes, I just bought and received them last week. 
The installation with my (swiss) u-rails is not that straight away as expected (which was also due to the fact that my curtain is sewed to the gliders, so that I could not easily detach and re-attach them as shown in the installation video). Furthermore I had to screw one mount to get better stability. The installation guide itself is well done.
The motor is not too loud but you clearly can hear it. It has about the same loudness as my watch winder. As I expect to use it only at day this does not really bother me.

**Comment by dontinelli** [comment]
> you need to install goslide-api==0.6.4 NOT slide
> 
> ```
> admin@malimaki:/var/packages/homeassistant/target/env/bin$ sudo ./pip install goslide-api==0.6.4 
> ```

Ok, I have installed goslide-api (as written above) and now also restarted Home Assistant. I still cannot find slide in the web-interface. Do I have to do anything else (e.g. manually update config)? If yes, where is the configuration.yaml located on Synology? Or do I have to configure the integration manually over SSH?

**Comment by rs1gg** [comment]
If there are no python dependency errors left in your `homeassistant.log`, you need to follow the instructions of the Home Assistant slide integration itself: https://www.home-assistant.io/integrations/slide/

(FYI the `configuration.yaml` and `homeassistant.log` files are both located in your configuration directory, which is at `/var/packages/homeassistant/target/var/config` for the spksrc install of Home Assistant Core.)

**Comment by dontinelli** [comment]
I added slide and my username and password in configuration.yaml. After restart of HA, I got an error, that slide requires goslide-api 0.5.1 (which makes sense based on the manifest.json). As @hgy59 mentioned above, I should use 0.6.4, I changed the version in manifest.json. Now HA did start without complaining and even a new card with my (currently only) slide has been added to the dashboard. 
Thank you both for your swift support, very much appreciated! I guess the ticket can be closed as resolved.

**Comment by rs1gg** [comment]
Happy that it works. Just out of curiosity, in which manifest.json (full path) did you change the goslide-api version from 0.5.1 to 0.6.4? (or did I misunderstand your latest comment?)

**Comment by dontinelli** [comment]
> Happy that it works. Just out of curiosity, in which manifest.json (full path) did you change the goslide-api version from 0.5.1 to 0.6.4? (or did I misunderstand your latest comment?)

Here: `/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/slide`

**Comment by rs1gg** [comment]
Ok, I see where some confusion comes from.

Current HA Core indeed requires goslide-api 0.6.4, as can be seen from manifest.json (link provided before). hgy59 most probably wanted to point the finger on the library name, since you initially tried to install 'slide' instead of 'goslide-api'.

The HA Core version currenty delivered with spksrc is _2021.1.5_, which depends on goslide-api 0.5.1, see https://github.com/home-assistant/core/blob/2021.1.5/homeassistant/components/slide/manifest.json

Since it works for you, 0.5.1 and 0.6.4 seem to be interface-compatible. Else, you would not be able to run HA Core 2021.1.5 with goslide-api 0.6.4...

**Comment by Starf0x** [comment]
2023-10-10 14:04:33.008 ERROR (MainThread) [goslideapi.goslideapi] RES: API=https://api.goslide.io/api/slides/overview, type=GET, HTTPCode=429, Data={"message":"Too Many Attempts."}
2023-10-10 14:04:33.009 ERROR (MainThread) [goslideapi.goslideapi] Missing key 'slides' in JSON=null
2023-10-10 14:04:33.009 ERROR (MainThread) [homeassistant.components.slide] Slide API does not work or returned an error

Up to date with the version that exists today. HASS Yellow.

**Comment by chickenandpork** [comment]
@Starf0x since this issue has been closed over two years, I would suggest creating a new one, linked to this one, and at-tag dontinelli for their attention to provide suggestions (I'm not tagging them to avoid drawing attention away form the issue you'll file)

**Comment by dontinelli** [comment]
> 2023-10-10 14:04:33.008 ERROR (MainThread) [goslideapi.goslideapi] RES: API=https://api.goslide.io/api/slides/overview, type=GET, HTTPCode=429, Data={"message":"Too Many Attempts."}
> 2023-10-10 14:04:33.009 ERROR (MainThread) [goslideapi.goslideapi] Missing key 'slides' in JSON=null
> 2023-10-10 14:04:33.009 ERROR (MainThread) [homeassistant.components.slide] Slide API does not work or returned an error
> 
> Up to date with the version that exists today. HASS Yellow.

I assume this has to do with the interval restriction that was introduced by slide to reduce traffic. Setting the scan_interval to 300 (with subsequent restart and some waiting) as described [https://github.com/home-assistant/core/issues/100702](here) resolved the issue for me.
