### ISSUE TITLE
[Transmission] New Issue. Labels for torrents

### ISSUE THREAD

**Issue by klivenn** [SynoCommunity/spksrc#4523]
### Setup
Package Name: Transmission
Package Version: 3.00-19

NAS Model: DS918+
NAS Architecture:
DSM version: DSM 6.2.3-25426 Update 3

Something to sort torrents in list.

When acting with 10,000 - 15,000 torrents you can sort them by adding a label in a name, but you need to rename every one of them.
Some feature to create labels and to select 1 label for a group of torrents in context menu

**Comment by publicarray** [comment]
I think this is a feature request for [upstream](https://github.com/transmission/transmission). Does the [transmission web](https://github.com/transmission/transmission/wiki/Web-Interface) interface on the desktop have this feature?

**Comment by publicarray** [comment]
@kited I suggest you open the feature request with [transmission](https://github.com/transmission/transmission) not with us. We package the software but don't develop transmission. Thanks for your suggestion anyway.
