### ISSUE TITLE
Sonarr only listening to localhost

### ISSUE THREAD

**Issue by mrkics** [SynoCommunity/spksrc#4534]
### Setup
_Package Name:_ Sonarr 
_Package Version:_v20210329-19

_NAS Model:_ ds218j
_NAS Architecture:_ armada385
_DSM version:_ DSM 6.2.3-25426 Update 3

### Expected behavior
Sonarr does not run after updating.

### Actual behavior
Updated sonarr to v20210329-19 and can't access web ui, no process seems to be running.

### Steps to reproduce
_1._ Restart NAS, (sonarr says it's not running on package center - click on run says its running, try to access web ui with no success.
_2._ Stop sonarr and start it again try to access web ui with no success
_3._ Check if port is enabled in services in control panel / info center / services and is not enabled. Enable and try again step 1 and 2 with no success.
_4._Can't re-install mono with out uninstalling sonarr... (mono Version 5.20.1.34-16)

#### Package log
_find logfiles in `/var/packages/{package}/var/`, for DSM7: `/var/log/packages/{package}.log`, for DSM < 6.0: protocol in Package Center.
_
```
Insert the package log here
```
Tue Mar 30 20:09:59 MST 2021
Starting nzbdrone command env PATH=/var/packages/mono/target/bin:/volume2/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume2/@appstore/nzbdrone/var LD_LIBRARY_PATH=/volume2/@appstore/nzbdrone/lib /var/packages/mono/target/bin/mono /volume2/@appstore/nzbdrone/share/Sonarr/Sonarr.exe
[Info] Bootstrap: Starting Sonarr - /volume2/@appstore/nzbdrone/share/Sonarr/Sonarr.exe - Version 3.0.5.1144
[Info] Router: Application mode: Interactive
[Info] MigrationLogger: *** Migrating data source=/volume2/@appstore/nzbdrone/var/.config/Sonarr/sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLogger: *** Migrating data source=/volume2/@appstore/nzbdrone/var/.config/Sonarr/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://127.0.0.1:8989/
[Info] OwinHostController:   http://localhost:8989/
[Info] SonarrBootstrapper: Starting Web Server
[Warn] MonoDebugCheck: Mono is not running with --debug switch
[Info] RssSyncService: Starting RSS Sync
[Info] DownloadDecisionMaker: Processing 219 releases
[Info] RssSyncService: RSS Sync Completed. Reports found: 219, Reports grabbed: 0
Tue Mar 30 20:17:55 MST 2021
Stopping nzbdrone service 27616

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by publicarray** [comment]
I found the error:
```
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController: http://127.0.0.1:8989/
[Info] OwinHostController: http://localhost:8989/
```

You won't be able to access anything since it's not listening on any interface except 127.0.0.1 / localhost. It should be set to  `http://*:8989/` by default, so you can use a network connection to open the GUI.

**Comment by publicarray** [comment]
You can use ssh/nano to edit `/var/packages/nzbdrone/target/var/.config/Sonarr/config.xml`

```
<BindAddress>*</BindAddress>
```

**Comment by mrkics** [comment]
what about this log:  Stopping nzbdrone service 27616 ??

i reinstalled same version of mono, since it was not running, making the corrections on to bind address and now works..

**Comment by publicarray** [comment]
From the time stamp it was logged about 10 minutes after starting, so it's possible the DSM did not detect it as running due to the port not being bind to the correct interface and killed the process, or you stopped it.

I'm glad you got it working :+1:
