### ISSUE TITLE
dependancy problem with flex

### ISSUE THREAD

**Issue by denis-b** [SynoCommunity/spksrc#454]
Hello, I'm trying to create a package for seafile. It needs libzdb, which depends on cross/flex, but libzdb lib doesn't compile, failing with 

/home/denis/synology/spksrc/toolchains/syno-cedarview/work/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/4.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lfl
collect2: ld returned 1 exit status

I noticed that my debian system provides a libfl.so, which is just a loader for libfl_pic.a
I modified flex package for generating it, but it doesn't change anything. 

Any advice will be welcome

Thanks,

Denis
##

**Comment by aquila** [comment]
Any news on this?
