### ISSUE TITLE
[Package Request] Proxmox backup server

### ISSUE THREAD

**Issue by sanderc85** [SynoCommunity/spksrc#4540]
Name: Proxmox backup server
Description: Proxmox Backup Server is an enterprise backup solution, for backing up and restoring VMs, containers, and physical hosts. 
Website: https://proxmox.com
Software documentation: https://www.proxmox.com/en/proxmox-backup-server
Build/Installation documentation: https://pbs.proxmox.com/wiki/index.php/Main_Page
Source Code: https://git.proxmox.com/
License: GNU Affero General Public License v3 (GNU AGPL, v3)

**Comment by hgy59** [comment]
As `Proxmox Backup` installations are only supported as full server installation (from ISO) or on top of an existing debian installation (Proxmox ships as a set of Debian packages which can be installed on top of a standard Debian installation), there is very little chance to get this running on synology diskstations.

```
Install Proxmox Backup with the Installer

Download the ISO from https://www.proxmox.com/downloads. It includes the following:

    The Proxmox Backup server installer, which partitions the local disk(s) with ext4, xfs or ZFS, and installs the operating system
    Complete operating system (Debian Linux, 64-bit)
    Proxmox Linux kernel with ZFS support
    Complete tool-set to administer backups and all necessary resources
    Web based management interface
```
