### ISSUE TITLE
No update Cover Status in Velux integration

### ISSUE THREAD

**Issue by Dragoniacs16** [SynoCommunity/spksrc#4543]
### Setup
_Package Name:_ HOMEASSISTANT / VELUX
_Package Version:_ 

_NAS Model:_ 
_NAS Architecture:_ 
_DSM version:_ 

### Expected behavior
Rollershutters (declared as "cover") should be updated when I use physical command

### Actual behavior
When I use physical command, status of the shutter is not updated in Hass-IO. When I use Hass-IO, update is OK.

### Steps to reproduce
_1._ Open HassIO - Velux items
_2._ Modify Velux shutter position with the physical command
_3._ Check in Hass-IO status of the shutter : no update

#### Package log
_find logfiles in `/var/packages/{package}/var/`, for DSM7: `/var/log/packages/{package}.log`, for DSM < 6.0: protocol in Package Center.
_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
AFAICT this is not related to the synocommunity package for homeassistant core.
So you sould ask this querstions to the home assistant community.
