### ISSUE TITLE
Syncthing v1.15.1 on DSM 7-Beta VMM | "sc-syncthing" not in DSM

### ISSUE THREAD

**Issue by Kaelber** [SynoCommunity/spksrc#4573]
On my DS1815+ the new Syncthing SPK v1.15,1 is running in a VMM on DSM 7-Beta, Build 41222. The problem is, that the group name "sc-yncthing" doesnt arise in the DSM, but the entrance is in the file "group". If I want to set up the group name in DSM, I got a fault, that the name is given.

![image](https://user-images.githubusercontent.com/12963736/115699780-46844f80-a366-11eb-8582-8a8b11205460.png)

**Comment by Kaelber** [comment]
I think, I have located the problem in the class of group. The entrances in DSM 6.2.4 vs. DSM 7 are different in the group:

DSM 6.2.4
sc-syncthing:x:65569:sc-syncthing

DSM 7 Beta
sc-syncthing:x:114670:

Therefor with 114670 the groupname is not visible.

**Comment by Kaelber** [comment]
If I modify that manually from 114670 to 65569 and reboot the DS, is visible:

![image](https://user-images.githubusercontent.com/12963736/115776092-064bbe00-a3b4-11eb-8bec-bb77a8f8d629.png)

**Comment by publicarray** [comment]
Thanks since packages don't have root access any more, I recommend going with the changes in DSM7 rather than "fixing" the group:
https://github.com/SynoCommunity/spksrc/wiki/DSM-7.0-Beta#permission-migration

**Comment by Kaelber** [comment]
This way is good with some shares, but not, If you have a lot of them.

**Comment by Kaelber** [comment]
Why that difference between DSM 6 and DSM 7. In DSM 6 is possible to give permissions in the user or group area, if you want you can activate or deactivate for all folders "Read/Write". In DSM 7 now is planned to use internal users. Is not good for smoothly set up.

**Comment by publicarray** [comment]
It's Synology's platform they can whatever they wish, I think it's because they want more security. If you like you can ask Synology about it. For DSM 7 developers however we  have to work with what we got.

You can also look at what changed here: https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/7.0/enu/DSM_Developer_Guide_7_0_Beta.pdf

**Comment by publicarray** [comment]
> **DSM 7.0, packages are forced to lower the privilege by applying privilege mechanism explicitly.**
> Packages will not be able to use run-as system in conf/privilege. Instead, all packages should run as package.

> ## Package User / Group Visibility On UI
>Package users and groups will not appear on most UI settings, but there are some exceptions:
>[x] Application privilege permission viewer
>[x] FTP chroot user selector
>[x] File Station
>[x] Change owner
>[x] Shared Links Manager -> Enable secure sharing
>[o] Control Panel > Shared Folder > Edit > Permission > System internal user
>[o] ACL editor

**Comment by hgy59** [comment]
Please note the strange syntax in the whole developer guide
[o] = yes/visible/available
[x] = no/not visible/not available

## Package User / Group Visibility On UI
Package users and groups will not appear on most UI settings, but there are some exceptions:
```
[x] Application privilege permission viewer
[x] FTP chroot user selector
[x] File Station
    -  [x] Change owner
    -  [x] Shared Links Manager -> Enable secure sharing
[o] Control Panel > Shared Folder > Edit > Permission > System internal user
[o] ACL editor
```
