### ISSUE TITLE
[Package Request] Overseerr

### ISSUE THREAD

**Issue by moi15moi** [SynoCommunity/spksrc#4582]
* Name: Overseerr
* Description: Overseerr is a free and open source software application for managing requests for your media library. It integrates with your existing services, such as Sonarr, Radarr, and Plex!
* Website: https://overseerr.dev/
* Software documentation: https://docs.overseerr.dev/
* Build/Installation documentation: https://docs.overseerr.dev/
* Source code:  https://github.com/sct/overseerr
* License: MIT License (I think, but I am not 100% sure)

I know you already have a lot of work, so I am not sure if it would interest you or not.
Thank you very much

**Comment by hgy59** [comment]
As installation methods on linux only snap and docker are supported. So I doupt that it is possible with reasonable effort to create a synology installation package.
> The Overseerr snap is the only officially supported Linux install method aside from Docker. Currently, the listening port cannot be changed, so port 5055 will need to be available on your host. To install snapd, please refer to the Snapcraft documentation.

**Comment by moi15moi** [comment]
Ok, thank you for your reply :)
It's a shame, but there's nothing we can do about it.

**Comment by hgy59** [comment]
You can run it in docker. But this is limitted to intel archs, so not for diskstations with an ARM (or PPC) processor.

**Comment by moi15moi** [comment]
Yes, I know it.
It is why I was asking, because I have a DS418 (it  have an ARM processor).

**Comment by hgy59** [comment]
Overserr is still beta, so maybe upon user requests they will document installation from source code.

**Comment by moi15moi** [comment]
So, if I undertand correctly, I should create an issue on their github and ask them if they can create a installation  documentation from the source code?

**Comment by hgy59** [comment]
There is already such an [issue](https://github.com/sct/overseerr/pull/550) and it is merged.
Maybe the github repo contains more that the install instruction page tells.

**Comment by moi15moi** [comment]
It seems that they updated the doc here: https://github.com/sct/overseerr/pull/550/commits/1b28101664e93cd16d269d398f0938dae0ac6086

But, from the lasted doc version, it seems that there not any instruction: https://github.com/sct/overseerr/blob/develop/docs/getting-started/installation.md

**Comment by moi15moi** [comment]
Hi,
If we can install snap on the synology, it could work, no? https://snapcraft.io/docs/installing-snap-on-raspbian

**Comment by mreid-tt** [comment]
hey @moi15moi, I've gotten a near final version of Seerr (merge of Overseerr and Jellyseerr) in PR #6905 which is now available for testing. If you have some time I'd really appreciate your feedback before we publish this to the repo. You can find details on installing pre-release packages in our [wiki](https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#download-development-and-pre-release-packages-created-by-github-build-action).

**Comment by moi15moi** [comment]
I dont use a synology nas anymore, so in cant do anything.
