### ISSUE TITLE
[Package Request] SynoCli Network tools missing autofs

### ISSUE THREAD

**Issue by cocoonkid** [SynoCommunity/spksrc#4587]
* Name: autofs
* Description:  manage sshfs automatic mounts
* Website: https://www.kernel.org/doc/html/latest/filesystems/autofs.html
* Software documentation: https://www.kernel.org/doc/html/latest/filesystems/autofs.html
* Build/Installation documentation: 
* Source code:  
* License:

Thanks so much!

**Comment by hgy59** [comment]
IMHO autofs is a kernel module and not a CLI tool.
As the build of kernel modules must match the kernel version and the toolkit of the diskstation this cannot be integrated into synocli-net, as we do not want to break the generic archs package delivery here.

@th0ma7 (the kernel specialist here) is there any chance to create a working `autofs` package?

**Comment by cocoonkid** [comment]
Thank you so much for the in depth explanation @th0ma7 and @hgy59.

This long shot is then definitely not worth it :-)

Thanks again for taking the time to look into this.
