### ISSUE TITLE
Updating Mercurial to the latest version 5.7.1?

### ISSUE THREAD

**Issue by dataCobra** [SynoCommunity/spksrc#4590]
Hello,

Would it be possible to provide Mercurial in the current version 5.7.1?
If this is possible, what would be the steps that would have to be taken for the package to be updated?

Even though my knowledge on the subject is very limited, I am happy to assist in updating it.

Regards,
Ben

**Comment by hgy59** [comment]
@dataCobra you can download the packages under Artifacts of the [latest build](https://github.com/SynoCommunity/spksrc/actions/runs/800376756) for manual installation.
I have successfully tested this package with DSM 7.0 beta, DSM 6.2.4 and DSM 5.2 (on x64, armv7 and ppc853x)
For DSM 7 you have to manually install python 3.8 as most packages are not yet availabale.

My tests where very basic:
1. which hg (test whether hg is found in PATH)
2. hg version
3. hg help

**Comment by dataCobra** [comment]
Thank you! :-)

I'll test that as soon as possible.

Regards,
Ben
