### ISSUE TITLE
Update ffmpeg to 4.4

### ISSUE THREAD

**Issue by ts65** [SynoCommunity/spksrc#4607]
Hi, it would be nice if you could update ffmpeg to version 4.4 that was released in April. Thanks in advance

**Comment by th0ma7** [comment]
There is work undergoing to provide both an update to 4.3.2 (latest on 4.3 branch) and also compatibility with DSM7.  A 4.4 update may have to wait for a few more cycles until we iron things up with current release.

**Comment by ts65** [comment]
Thanks for the info. The feature I need isn't in 4.3.2 unfortunately, but I'll be patient and look forward to the progress. Thank you for all your work!

**Comment by th0ma7** [comment]
@ts65 release of 4.3.2 is now complete for both DSM6-7.
I'll let the dust settle before starting any work on 4.4.x to shake any DSM7 remaining bugs.
So I know what to look for, what feature are you looking for exactly?

**Comment by ts65** [comment]
Thanks for the info. The feature I'm interested in is AAXC support.

**Comment by AlfredJ73** [comment]
Hm, just updated ffmpeg from 4.3.1 to 4.3.2-37 on my DS1821+ with DSM 6.2.4-25556 and now video station (2.4.10-1632) with BenjaminPoncet's ffmpegwrapper (https://gist.github.com/BenjaminPoncet/bbef9edc1d0800528813e75c1669e57e) does not transcode eac3 and dts anymore (so it doesnt play the video at all). 
How to revert to 4.3.1 ?
