### ISSUE TITLE
[Package Request] jpegoptim

### ISSUE THREAD

**Issue by GodHunter** [SynoCommunity/spksrc#4609]
* Name: jpegoptim
* Description: Optimize jpeg Images
* Website: https://github.com/tjko/jpegoptim
* Software documentation: https://github.com/tjko/jpegoptim
* Build/Installation documentation: https://github.com/tjko/jpegoptim
* Source code:  https://github.com/tjko/jpegoptim
* License: GNU

**Comment by hgy59** [comment]
This is such a small utitlity, so I vote to integrate this eigther into imagemagick or create a new synocli-graphics package.

**Comment by hgy59** [comment]
jpegoptim is integrated in the current imagemagick package.
