### ISSUE TITLE
Calibre (ebook management on Windows) failing updating DB on Synology 

### ISSUE THREAD

**Issue by Flyingdishes** [SynoCommunity/spksrc#4620]
Hi,
Since a few weeks Calibre fails in adding new books on the epub repositoy (and database) installed on my SYNOLOGY NAS.

Contacting Calibre team, they push back, arguing that Calibre is not suoorted on NAS installations.

I wonder if this is an issue between Calibre , COPS or DSM file management system.

Anybody facing that issue ?

Thanks for any educated feedback.

DSM version:  6.2.4-25556
COPS version 1.1.3
calibre, version 5.17.0
Window10 Family 20H2

LOG capture:
ERREUR : Erreurs pendant l'ajout: Échec à l'ajout de n'importe quels livres, cliquez sur "Afficher les détails" pour plus d'information.

Échec à ajouter le livreUn mal pour un bien
D:/Telechargements/Danielle Steel - Un mal pour un bien 2019 2021.epub
Avec l'erreur :
Traceback (most recent call last):
File "calibre\gui2\add.py", line 457, in add_book
File "calibre\db\legacy.py", line 334, in create_book_entry
File "calibre\db\cache.py", line 72, in call_func_with_lock
File "calibre\db\cache.py", line 1686, in create_book_entry
File "calibre\db\cache.py", line 1399, in set_metadata
File "calibre\db\cache.py", line 1223, in update_path
File "calibre\db\backend.py", line 1665, in update_path
File "calibre\db\tables.py", line 134, in set_path
File "calibre\db\backend.py", line 920, in execute
apsw.CantOpenError: CantOpenError: unable to open database file

**Comment by hgy59** [comment]
> Since a few weeks Calibre fails in adding new books on the epub repositoy (and database) installed on my SYNOLOGY NAS.

If those `few weeks` correspond with the DSM update to version 6.2.4 I suppose this is a permission issue.
DSM 6.2.4 introduced some security `features`, e.g. it warns when you login as admin.
So make sure you do not use the `admin` user to access the calibre folder on your NAS.

**Comment by Flyingdishes** [comment]
Hi Hgy59,
You were spot on !
I used to grant access to the Calibre folder on my NAS via my admin account. 
Based on your advice, I created a "Calibre" account, having no admin but R/W access granted to the NAS Calibre folder.

Everything went perfect immediately.

You made my day !

Best regards,
Flying
