### ISSUE TITLE
TVHeadend on Synology Ds213+ 6 :  CA not working

### ISSUE THREAD

**Issue by openschwall** [SynoCommunity/spksrc#4632]
Hi,

your current package 4.3. is running fine, but Conditional Access to Oscam is not possible. I checked all possible connection methods with no sucess. It connects  but no decrambling. 
For comparison, I tested TVH 3.8 on raspi using the same connection methods with success. So I assume something is wrong with CA access in the newest Synology version.

**Comment by th0ma7** [comment]
Sorry for the really late reply.  I have no clue what means "Conditional Access to Oscam".  Is this still an issue?

**Comment by th0ma7** [comment]
Please open-up a new issue if this problem still exists, closing this one due to lack of activity.
