### ISSUE TITLE
unable to install mosh

### ISSUE THREAD

**Issue by tomhoover** [SynoCommunity/spksrc#4635]
### Setup
_Package Name:_ mosh
_Package Version:_ 1.3.2-1

_NAS Model:_ DS1821+
_NAS Architecture:_ AMD Ryzen V1500B
_DSM version:_ DSM 6.2.4-25556

### Expected behavior
Mosh is listed as a package at https://synocommunity.com/package/mosh and should appear in the package center.

### Actual behavior
Mosh is missing from the package center.

### Steps to reproduce
_1._ Install SynoCommunity packages per instructions at https://synocommunity.com/#easy-install
_2._ Mosh doesn't appear in community tab of package center, although other SynoCommunity packages appear and are installable.
_3._ Logs are N/A, as the package is never selectable for installation.

**Comment by jpnn80** [comment]
Hi,
I am having the same problem with the package for Nzbget

**Comment by hgy59** [comment]
> 
> 
> Hi,
> I am having the same problem with the package for Nzbget

There is already an issue for nzbget with #4631.

**Comment by tomhoover** [comment]
Updated info: Mosh is now available for `7.0 v1000` architecture, but not for `7.0 r1000`. Thank you for making the package available for my DS1821+. Do you have any idea when it will be available for my DS1522+ (r1000)?

**Comment by mreid-tt** [comment]
@tomhoover, an update for mosh-1.4.0 is being worked on and is currently available for testing at https://github.com/SynoCommunity/spksrc/pull/5615. You can download one of the test packages from https://github.com/SynoCommunity/spksrc/actions/runs/4225178716 to try it out.
