### ISSUE TITLE
SickChill: Github API not saved / accepted

### ISSUE THREAD

**Issue by bartmans** [SynoCommunity/spksrc#4638]
### Setup
_Package Name:_ Inital SickChill for Synology
_Package Version:_  20210329-1

_NAS Model:_ 
_NAS Architecture:_ DS216+II
_DSM version:_ DSM 6.2.4-25556

### Expected behavior
I got a mail from Github to refresh my API key for SickChill. I regenerated one, tried to save it within SickChill but key is not saved.

### Actual behavior
I want to save the new key

### Steps to reproduce
_1._ Regeneratie Github API key
_2._ Go to settings - advanced - github - token and copy/paste new key
_3._ save

From SickChill logs
2021-05-20 12:31:42 Unable to contact github, can't check for update: AttributeError("'NoneType' object has no attribute 'get_organization'")

2021-05-20 11:37:41 Unable to setup GitHub properly with your github token. Please check your credentials. Error: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}

Mail from Github:
We noticed your personal access token, SickChill, has an outdated format and was used to access the GitHub API on May 19th, 2021 at 17:31 (UTC) with a user-agent header of SickChill.
 
We recently updated the format of our API authentication tokens, providing additional security benefits to all our customers.

In order to benefit from this new format, please regenerate your personal access token, SickChill, using the button below.

To understand more about this change and why it's important, visit https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats.

**Comment by samip5** [comment]
Please specify the architecture of your nas.

Easiest way to check is to ssh to the nas and paste the output of  `uname -m`.

**Comment by bartmans** [comment]
That's:
DS216+II - synology_braswell_216+II

**Comment by bartmans** [comment]
As a temporary workout I edited the config.ini manually with the new, longer key.

cp config.ini config.ini.date
/volume1/@appstore/sickchill/var
vi config.ini

I can now at least run the update function.

**Comment by BKSteve** [comment]
This one's a little old now but `save changes` in the `GitHub` area and then `save changes` in the main darker grey `General` area will ensure the token is saved into the `config.ini` file.

SickChill issues can be raised on it's own GitHub site https://github.com/SickChill/SickChill

**Comment by mreid-tt** [comment]
Hey there, @bartmans! Just wanted to check in on this issue. Are you still experiencing the problem? We haven't heard back from you regarding the suggestions provided. Before we close the issue, please let us know if there's anything else we can do to assist you.

**Comment by bartmans** [comment]
Well issue is from 2021. Never encountered it again.

**Comment by mreid-tt** [comment]
Thank you for your feedback. Based on your input, I will proceed to resolve and close this issue. If the problem resurfaces in the future, please feel free to reopen it at any time.
