### ISSUE TITLE
[Package Request] mtr

### ISSUE THREAD

**Issue by samip5** [SynoCommunity/spksrc#4640]
* Name: mtr
* Description: Full screen ncurses and X11 traceroute tool
* Website: https://github.com/traviscross/mtr
* Software documentation: http://www.bitwizard.nl/mtr/
* Build/Installation documentation: https://github.com/traviscross/mtr
* Source code:  https://github.com/traviscross/mtr
* License: GPL-2

**Comment by hgy59** [comment]
@samip5 see #4642 for my inital commit.
you must build mtr yourself under /spksrc/diyspk/mtr for your arch until mtr is added to synocli-net.
There is no X11 on the diskstations, so only ncurses and CLI interaction is supported.

**Comment by hgy59** [comment]
Now as I have integrated mtr in synocli-net you can download packages built by github action as artifatcs here:
https://github.com/SynoCommunity/spksrc/actions/runs/866353759
