### ISSUE TITLE
TVHeadend: after installing, web ui prompts for user and password

### ISSUE THREAD

**Issue by martin3000** [SynoCommunity/spksrc#4641]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ TVHeadend
_Package Version:_ 4.3.20201011

_NAS Model:_ DS215j
_NAS Architecture:_ ARM
_DSM version:_ 6.2.4

I installed TVHeadend through the diskstation web ui (community packages), not on the command line.

### Expected behavior
On http://diskstation:9981 I expected the web ui of tvheadend. I expect that there is no default user or password.

### Actual behavior
I went to http://diskstation:9981 and was prompted for a user and password. This was surprising because I had no clue what user and password to use. After googling around, I did not find the solution. Then I found a hint to look into /usr/local/tvheadend/var/passwd/* and there I found the user "admin". So the user and password is admin/admin.

### Steps to reproduce
_1._ install tvheadend from the community store.
_2._ go to diskstation:9981

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Sat May 22 09:43:26 CEST 2021
Starting tvheadend command /volume1/@appstore/tvheadend/bin/tvheadend -f -u sc-tvheadend -g tvheadend --http_port 9981 --htsp_port 9982 -c /volume1/@appstore/tvheadend/var -p /volume1/@appstore/tvheadend/var/tvheadend.pid
```

**Comment by publicarray** [comment]
During installation, you are prompted to set a password and the defaults are provided: https://github.com/SynoCommunity/spksrc/blob/0be1d162287871f18f73efae6f629e82a9b7cc1e/spk/tvheadend/src/wizard/install_uifile#L2-L5

What else is there for us to do?

**Comment by martin3000** [comment]
Maybe this prompt for password is only for users installing tvheadend in the command line of the NAS? In the DSM web ui there is no prompt for a admin password. Normally, tvheadend prompts the user after installing if you start it the first time on localhost:9981. The you have to make some settings.

**Comment by publicarray** [comment]
If you don't see the wizard asking to set a password during a fresh installation (from the web GUI) than that is a bug.

**Comment by martin3000** [comment]
I tested the installation again and I was prompted for the password. So I close this.
