### ISSUE TITLE
DSM 7.0 ffmpeg install failed

### ISSUE THREAD

**Issue by cedricbrx** [SynoCommunity/spksrc#4666]
### Setup
_Package Name:_ ffmpeg
_Package Version:_ 4.3.1-35

_NAS Model:_ DS1817+
_NAS Architecture:_ x64
_DSM version:_ DSM 7.0-41882

### Expected behavior
ffmpeg should be installed

### Actual behavior
Error message while installing:
Invalid file format. Please contact the package developer

### Steps to reproduce
_1._ uninstall ffmpeg / install DSM 7.0-41882
_2._ add synocommunity repository
_3._ install ffmpeg

#### Package log
No log while installing
```

**Comment by hgy59** [comment]
please regard #4524. ffmpeg is not yet published for DSM7
