### ISSUE TITLE
Feature request: Automatic updating instructions added to documentation

### ISSUE THREAD

**Issue by ibex-are-goats** [SynoCommunity/spksrc#4668]
Hello, since the Synology Package Center says SynoCommunity packages can't be autoupdated, I'd like to script their automatic updates into the Task Scheduler. 

Can the commands to autoupdate a given package be added to the documentation? Perhaps an "Automatic Updates" page on the wiki. Thanks!

**Comment by BenjV** [comment]
Adding the following line to the INFO file will allow the selection of auto update of that package in the package center.
> silent_upgrade="yes"

The INFO file can be found here:

> /var/package/<name of the package>/INFO

This is intended to be used by CMS to update packages.
I don't know if without CMS this autoupdate will take place at all.

**Comment by ibex-are-goats** [comment]
It's /var/packages/, but I got it and it seems to have worked! The checkbox now shows up in the updater settings. Well done! I think that would be a great addition to the documentation. Keep up the good work!

**Comment by hgy59** [comment]
@ibex-are-goats which are the packages you use the autoupdate feature? 
I suppose that packages with an update wizard might disable the auto update.

**Comment by ibex-are-goats** [comment]
> @ibex-are-goats which are the packages you use the autoupdate feature?
> I suppose that packages with an update wizard might disable the auto update.

I enabled it on all the SynoCommunity packages I have installed. FFMPEG and like 5 others.

**Comment by hgy59** [comment]
@ibex-are-goats if you modified the INFO file of the installed packages, this will be lost on the update as the INFO file will be replaced by the one in the update package.
For real autoupdate capability the packages must be published with this option to the synocommunity package center.

**Comment by ibex-are-goats** [comment]
> @ibex-are-goats if you modified the INFO file of the installed packages, this will be lost on the update as the INFO file will be replaced by the one in the update package.
> For real autoupdate capability the packages must be published with this option to the synocommunity package center.

OH LOL! Then that's not a solution, nevermind. Is there a way to script the update like I asked in the original post?

**Comment by hgy59** [comment]
The real solution would be to add `silent_upgrade="yes"` to all packages when silent upgrade is supported.
Therefore we need to know whether this option conflicts for packages with upgrade wizard or whether DSM manages this by disabling the autoupdate when such a wizard is included.

And - it will take some time to validate this, as we need two times a new versions of a package published to the synocommunity package repository.

**Comment by hgy59** [comment]
And there is another point that we should regard:
When we add the autoupdate feature for packages, there will we a peak load for updated packages as we have one repository server only and cannot schedule availablility as synology does for different regions.

@ymartin59  what is your opinion?

**Comment by BenjV** [comment]
This is not a solution for what @ibex-are-goats wants.

The setting silent_upgrade="yes" only allow the package to be updated from CMS.
The packages are not update by the package center.
You can force the update from the commandline with this command (emulating what CMS does).

> sudo synopkg chkupgradepkg

But this only works for packages from Synology themselves.
Apparently it can only check against their server.

**Comment by ibex-are-goats** [comment]
I didn't realize autoupdates would be so contentious! ;) I'm sorry that I don't have more to contribute than the idea! ;)

**Comment by hgy59** [comment]
> The setting silent_upgrade="yes" only allow the package to be updated from CMS.
> The packages are not updated by the package center.

This is not true:

from Developer documentation:
```
Field Name: silent_upgrade
Description: If set to “yes”, your package is allowed to be upgraded without the package wizard in the background. End user
cannot modify any information for upgrading. This allows not only your package to be upgraded automatically but also for CMS
(Central Management System) to distribute package upgrades to other NAS connected.
Value: "yes"/"no"
Default Value: "no"
Example:
silent_upgrade="yes"
DSM Requirement: 5.0-4458
```

Only `silent_install` and `silent_uninstall` options are for `CMS` only.


I just have built `diyspk/mc` with `silent_upgrade="yes"` and published to my own test repository.
With this I can select autoupdate in the package manager in DSM. 
![Autoupdate MidnightCommander](https://user-images.githubusercontent.com/12009964/120900459-3930d500-c635-11eb-8714-fc0e99178bba.png)

Then I created and published an ugrade package.
Unfortunately the update is not done until now. This might be an issue as I was not able to sign the package or the auto-installation will be delayed an amount of time. (we will see....).

**Comment by ibex-are-goats** [comment]
Great work! So it does work then. About the timing of the update, I do personally notice that the OS will wait a long time before doing an automatic update. Which is fine, I just don't want to go years with outdated packages.

I assumed that there was an explicit reason why silent_upgrade was disabled in SynoCommunity packages. But if it's not, or at least if nobody remembers why it's set this way, then maybe now's the time to start a conversation about having everybody set silent_upgrade="yes" by default?

The OS GUI itself lets you enable or disable any auto-update you want, so I'm not sure what the reason would be for NOT enabling it by default.

**Comment by BenjV** [comment]
I tested it with two packages, Download Station and flexget.
I changed the INFO of the flexget package and set both packages to autoupdate
Non of the packages updated automatic.

When I gave the sudo synopkg chkupgradepkg command on the commandline only DownloadStation updated but flexget not.

**Comment by hgy59** [comment]
Now I have configured CMS on another  Diskstation to manage the one with the Midnight Commander Package.
It is possible to monitor the package (but the update is not visible here, so I will wait some days to see whether the update will be shown).
![CSM-packet-list-of-ds-kt2](https://user-images.githubusercontent.com/12009964/120903263-7e5d0300-c645-11eb-8d32-8525ccbd0a1e.png)
_Sorry, this one has german UI_

**Comment by BenjV** [comment]
In the mean time my Nas updated DownloadStation automatically but flexget not.
So my guess is it can only update packages from the Synology Servers.
I will keep monitoring it to see if it get updated in the near future

**Comment by hgy59** [comment]
Nothing happened. Even after more than 3 days an automatic update was not executed.
Sofar my findings are the same as of @BenjV: automatic updates do not work with the synocommunity package repository.

**Comment by BenjV** [comment]
Here the same the flexget package still did not update.

**Comment by mietzen** [comment]
> Hello, since the Synology Package Center says SynoCommunity packages can't be autoupdated, I'd like to script their automatic updates into the Task Scheduler.

I'd did just that: 
https://gist.github.com/mietzen/e9b823006cf241662cb41fd3ab353d01
