### ISSUE TITLE
Bad Request  The browser (or proxy) sent a request that this server could not understand.

### ISSUE THREAD

**Issue by GreedyBastard** [SynoCommunity/spksrc#4672]
Cannot add a new package source in my DSM.

Trying to add:
Name:SynoCommunity
Location:https://packages.synocommunity.com/
results in "Invalid location " mesg.

And trying to actually access the site via browser:
https://packages.synocommunity.com/
->
Bad Request  The browser (or proxy) sent a request that this server could not understand.

**Comment by Bagestu** [comment]
I noticed the same behaviour as well. All my community packages had disappeared, so I tried removing and adding the source again. Removing was no problem, but I'm unable to add SynoCommunity again.

Tried following url's:
- https://packages.synocommunity.com
- http://packages.synocommunity.com
- packages.synocommunity.com

**Comment by hgy59** [comment]
The only valid URL is https://packages.synocommunity.com
This is for the Package Center within DSM. With a browser you always get `bad request`, as this is an API and not a web page.
I just successfully added the synocommunity package repository with this URL on a new diskstation that had never configured a package source before.

**Comment by GreedyBastard** [comment]
It doesn't work.. :(
![Screenshot 2021-06-09 at 07 52 17](https://user-images.githubusercontent.com/74423366/121300954-c86d0f80-c8f7-11eb-8901-5c6b331b0e30.png)

**Comment by hgy59** [comment]
you can use curl to validate whether the synocommunity package center API is working.

```
curl --location --request GET 'https://packages.synocommunity.com/?build=24922&language=enu&arch=noarch' --header 'REFERER: -' --header 'USER_AGENT: test agent' --data-raw ''
```

The request above will get the whole list of available packages for the given arch and build number (as json).
You can run this command on every system that has `curl` available and internet connection, not only on your diskstation. I hope this helps to find the real cause of the `invalid localtion` error.

You can play with the language parameter above (enu=english) or you can change the language of DSM to english (as this is the only difference I can see so far).

What is the three letter code of your language? (it might be missing in the available languages on sc repository).

**Comment by GreedyBastard** [comment]
The system language is set to Polish.

`root@Tiburon:~# curl --location --request GET 'https://packages.synocommunity.com/?build=24922&language=enu&arch=noarch' --header 'REFERER: -' --header 'USER_AGENT: test agent' --data-raw ''

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Backend is unhealthy</title>
  </head>
  <body>
    <h1>Error 503 Backend is unhealthy</h1>
    <p>Backend is unhealthy</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-ams21042-AMS 1623221085 1070288180</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>`

**Comment by hgy59** [comment]
I get the following error response when I do a request for my private package repository (based on spkrepo) with a language that is not in the package database:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>422 Unprocessable Entity</title>
<h1>Unprocessable Entity</h1>
<p>The request was well-formed but was unable to be followed due to semantic errors.</p>
```

**Comment by hgy59** [comment]
please try again, I just got the 503 too.

**Comment by hgy59** [comment]
The error depends not on Polish language (plk). as I successfully run the following command:
```
curl --location --request GET 'https://packages.synocommunity.com/?build=24922&language=plk&arch=noarch' --header 'REFERER: -' --header 'USER_AGENT: test agent' --data-raw ''
```

**Comment by GreedyBastard** [comment]
curl --location --request GET 'https://packages.synocommunity.com/?build=24922&language=plk&arch=noarch' --header 'REFERER: -' --header 'USER_AGENT: test agent' --data-raw ''

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Backend is unhealthy</title>
  </head>
  <body>
    <h1>Error 503 Backend is unhealthy</h1>
    <p>Backend is unhealthy</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-ams21058-AMS 1623223256 592219745</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

**Comment by drafoon** [comment]
I think it has probably something to do with the outage yesterday by Fastly (big fat red logo on the SynoCommunity site, providing the CDN)
https://www.fastly.com/blog/summary-of-june-8-outage

**Comment by Bagestu** [comment]
Same issue for me. All was working fine before.
![2021-06-09 12_16_07-Window](https://user-images.githubusercontent.com/81232367/121337667-0fb9c700-c91d-11eb-8951-a96146a35275.png)
![2021-06-09 12_18_12-Window](https://user-images.githubusercontent.com/81232367/121337671-10525d80-c91d-11eb-9998-aa3918fe9e30.png)

**Comment by drafoon** [comment]
It's working for me again

**Comment by publicarray** [comment]
I'm still glad that fastly is there. I'm sure the backend server would not manage serving the ever-increasing traffic.
