### ISSUE TITLE
DSM7 Invalid file format for synocli-disk and synocli-monitor

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spksrc#4677]
From @arch1mede  https://github.com/SynoCommunity/spkrepo/issues/74

Getting this on the following:
Synocli disk tools
Synocli monitor tools

![image](https://user-images.githubusercontent.com/2196184/121800350-86aed280-cc31-11eb-902d-aaac1b24baa4.png)

The others Synocli packages updated fine.

**Comment by hgy59** [comment]
@arch1mede please add some info:
_NAS Model:_ 
_NAS Architecture:_ 
_DSM Version:_

**Comment by hgy59** [comment]
@arch1mode `synocli-disk` and `synocli-monitor` are not yet published for DSM7 as you can find in #4524. 
You have to build those packages by yourself for DSM7.

**Comment by rodalpho** [comment]
Same issue here, I do hope they get added. 

NAS Model: DS920+
NAS Architecture: x86-64
DSM Version: 
productversion="7.0"
buildphase="RC"
buildnumber="41882"

**Comment by Lylrok** [comment]
Same issue here, I do hope they get added too, thank you very much

NAS Model: DS416j
NAS Architecture: MARVELL Armada 388 88F6828 (Armada38x)
DSM Version: DSM 7.0-41890
