### ISSUE TITLE
Add requests to python3 package

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#4678]
### Setup
_Package Name:_ python3/python38

_NAS Model:_ 918+
_NAS Architecture:_  apollolake (x86_64)
_DSM version:_ 6.2.3

### Expected behavior
Using an EPG grabber in python I'm getting the following error:
```
ModuleNotFoundError: No module named 'requests'
```

### Actual behavior
It work on my default Ubuntu setup but fails under Synology DSM

**Comment by th0ma7** [comment]
@hgy59 working on integrating https://github.com/edit4ever/script.module.zap2epg/pull/37 directly to tvheadend package instead of the zap2it previous work I was on (https://github.com/SynoCommunity/spksrc/pull/4608).

Seems I would require an added pip to be included in the default package...
```
2021-06-13 09:18:05.683 spawn: Executing "/usr/local/bin/tv_grab_zap2epg"
2021-06-13 09:18:06.028 spawn: Traceback (most recent call last):
2021-06-13 09:18:06.028 spawn:   File "", line 18, in 
2021-06-13 09:18:06.028 spawn: ModuleNotFoundError: No module named 'requests'
```

**Comment by hgy59** [comment]
Are you planning to create an edit4ever (or zwap2epg) package for spkrepo?

IMHO the python packages include only additional python wheels/modules that are required by pure python spks (i.e. arch=noarch).

**Comment by th0ma7** [comment]
@hgy59 I'm planning to replace `cross/zap2it` with a `cross/zap2epg` (or `edit4ever`) where I'll simply do a `make install` under the right epg path of tvheadend i.e. `bin` and `var/epggrab/*`.  Script will then become part of the standard tvheadend package instead of needing a side package for this.  PR #4608 will simply be canceled.

Should the requirement be added directly in the `python3` package?  or can I simply add a sort of `pip` in `spk/tvheadend` for that (there probably is an example I can follow if that's the case).

**Comment by th0ma7** [comment]
Found well documented proper method of adding to my local package the needed python wheel.
https://github.com/SynoCommunity/spksrc/wiki/Using-wheels-to-distribute-Python-packages
Closing issue.
