### ISSUE TITLE
SabNZBD - DSM7 Invalid File Format

### ISSUE THREAD

**Issue by Drubadix** [SynoCommunity/spksrc#4700]
### Setup
_Package Name:_ Sabnzbd
_Package Version:_ 3.2.1.48

_NAS Model:_ Syno 218+
_NAS Architecture:_ 
_DSM version:_ 7.0-41890

### Expected behavior
Tell us what should happen
Sabnzbd dosent start anymore. Update and new install dosent work because "wrong file format" message

### Actual behavior
Tell us what happens instead
Installation and Updates ending with "wrong file format" 

### Steps to reproduce
_1._ install
_2._ update
_3._ 

### Setup
_Package Name:_ 
![Unbenannt](https://user-images.githubusercontent.com/86649614/123752002-a9d7b400-d8b8-11eb-8d0f-db2ecab158b2.JPG)

_Package Version:_ 

_NAS Model:_ 
_NAS Architecture:_ 
_DSM version:_ 

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Installer log: find logfile `/var/log/packages/{package}.log`, for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` and protocol in Package Center.
You find service log and other log files in `/var/packages/{package}/target/var`.
_
```
Insert the package log(s) here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by sam43434** [comment]
have to wait with the rest of us for it to be updated and released for DSM 7

you can see the packages that are 7 ready in the following
https://github.com/SynoCommunity/spksrc/issues/4524

**Comment by Drubadix** [comment]
Did not see this before. Thanks for the hint.

**Comment by hgy59** [comment]
just updated the Readme as DSM 7 is now released.

**Comment by spock99** [comment]
Hope we get sabnzbd to work not that dsm7 release would like stop using docker.
