### ISSUE TITLE
Deluge 2.0.3 not compatible with 3rd party plugins because it uses python 2.7 instead of 3.7

### ISSUE THREAD

**Issue by thijsvanderkraan** [SynoCommunity/spksrc#4701]
### Setup
_Package Name: deluge_ 
_Package Version: 2.0.3-13_ 

_NAS Model: DS120j_ 
_DSM version: DSM 6.2.4-25556_ 

### Expected behavior
Deluge uses python 3.7, which allows third party extension (build for deluge 2.x) to be installed.

### Actual behavior
Deluge 2.0.3 uses python uses Python 2.7. Third party extensions for deluge 2.x (packaged in egg format and build on python 3.x) do not work. The egg packages cannot be installed via the thin client, because the client compares the python version of deluge with the python version of the extension. The thin client version check can be circumvented by changing the version in the filename of the extension egg file from 3.x to 2.7. This allows the extension to be installed, but it won't work. python version differences.

### Steps to reproduce
_1. Download extension from https://dev.deluge-torrent.org/wiki/Plugins_ 
_2. In thin client: Preferences -> Plugins click Install plugin, locate the downloaded plugin egg and select it to install._

**Comment by hgy59** [comment]
This is WIP in #4153

**Comment by th0ma7** [comment]
New version of deluge is being published.  Please reopen the issue if its still occurring.  Thnx in advance.
