### ISSUE TITLE
DSM7 Invalid file format for tvheadend

### ISSUE THREAD

**Issue by sibbl** [SynoCommunity/spksrc#4705]
* I just upgraded my DS218+ (apollolake) to DSM 7 today.
* When trying to repair tvheadend, I get a "invalid file format" error message.
* According to https://synocommunity.com/package/tvheadend the package tvheaded should be already published for DSM7 and apollolake
* Downloading the "7.0 apollolake" spk and manually installing also doesn't work. DSM says it conflicts with the already installed package and it cannot update it without uninstalling it first.
* Upgrading other packages (ffmpeg) from this repo worked fine on the same device.

I'd be happy to provide a log, but don't know where to get it from.
Also, I'm not sure whether there are other upgrade paths without losing any tvheadend data?

**Comment by sibbl** [comment]
It seems like a first reboot of the Synology fixed it... repaired properly now. Seems like DSM7 is still a tiny bit buggy, who knows.

(yes I know, should have tried turning it off and on before posting the issue. Sorry for the inconvenience :D )

**Comment by th0ma7** [comment]
Interesting problem and method of solving it... 
Synology DSM is linux based and normally do not require unnecessary reboots.
Thnx for sharing as this might help others.

Cheers!

**Comment by sibbl** [comment]
Yup, very interesting. I assume it still did some upgrade stuff in the background. I also was about to finish repairing quite a few packages (including beta packages) and before repairing the final beta package, I had to go to the beta tab and reconfirm and reenable beta package sources before having the "repair" button enabled again. Who knows what went wrong there...

But no issues since the reboot regarding the packages. The sundtek dvb driver isn't recognized but should be tvheadend package related as it's also missing when accessing it in the shell. 

Thanks for your quick reply anyway and thanks for the great work regarding tvheadend! 🙏
