### ISSUE TITLE
Sonarr and DSM 7

### ISSUE THREAD

**Issue by c0heed** [SynoCommunity/spksrc#4706]
### Setup
_Package Name:_ Sonarr
_Package Version:_ 3.0.5.1144

_NAS Model:_ DS918+
_DSM version:_ 7.0

### Expected behavior
I was hoping it would run on DSM 7, but I was wrong.

### Actual behavior
Doesn't run on DSM 7, is there going to be an update for Sonarr?

**Comment by sam43434** [comment]
keep an eye on the following post to see when DSM 7 packages are updated
https://github.com/SynoCommunity/spksrc/issues/4524

**Comment by c0heed** [comment]
> keep an eye on the following post to see when DSM 7 packages are updated
> #4524

Thank you very much!

**Comment by publicarray** [comment]
Mono has just been published https://github.com/SynoCommunity/spksrc/pull/4669#issuecomment-881737801
So I've published Sonarr with same delay of up to 48 hours for the CDN to catch up. Also note that the permissions have changed: https://github.com/SynoCommunity/spksrc/wiki/Permission-Management#dsm-7-migration

**Comment by the7shfun** [comment]
> Mono has just been published [#4669 (comment)](https://github.com/SynoCommunity/spksrc/pull/4669#issuecomment-881737801)
> So I've published Sonarr with same delay of up to 48 hours for the CDN to catch up. Also note that the permissions have changed: https://github.com/SynoCommunity/spksrc/wiki/Permission-Management#dsm-7-migration

Cant wait!Where can i get the sonarr package now!

**Comment by hgy59** [comment]
@the7shfun you can manually install the downloaded packaage from https://synocommunity.com/package/mono

**Comment by the7shfun** [comment]
> @the7shfun you can manually install the downloaded package from https://synocommunity.com/package/mono

I already install mono package by manually. But i still need sonarr.

**Comment by publicarray** [comment]
@the7shfun you can find it here: https://synocommunity.com/package/nzbdrone

**Comment by hgy59** [comment]
sonarr was published already for DSM7 on 2021-03-29 as  v20210329-19, only mono was missing for DSM7.
Doesn't this package work?

**Comment by publicarray** [comment]
Hi @hgy59, I only published sonarr [yesterday](https://github.com/SynoCommunity/spksrc/issues/4706#issuecomment-881783371) (you can also check by logging in and looking at the synocommunity builds)

**Comment by hgy59** [comment]
> 
> 
> Hi @hgy59, I only published sonarr [yesterday](https://github.com/SynoCommunity/spksrc/issues/4706#issuecomment-881783371) (you can also check by logging in and looking at the synocommunity builds)

@publicarray _I should have known_ 💭

**Comment by the7shfun** [comment]
> @the7shfun you can find it here: https://synocommunity.com/package/nzbdrone

I check the date was v20210329-19 i thought i was older version. But yes. I download it and installed it work! Thank!

**Comment by hgy59** [comment]
Yes, the repository shows the date the first package of a specific version is uploaded. 
This can be misleading in the rare case of uploading new packages of an old version...

**Comment by DieterC1984** [comment]
Hi Guys, 
I don't know how about you, but Sonarr is really eating up my Disk utilization AND Volume on my Synology. Both running constantly at 98% and a NAS that is nearly inaccessible. As soon as I stop the Sonarr service everything is calming down and staying below 20%.
DS216Play and 2 Ironwolf 4TB drives installed so should be compatible all the way.

Any suggestions?

**Comment by publicarray** [comment]
@DieterC1984 do you have log files you can share with us. It lets us know what Sonarr is doing. It could just be indexing the file system for TV shows and once it's done would calm down

**Comment by PaloloWeather** [comment]
Thanks for all the hard work on these packages! I realize these all take a ton of time and effort. I'm not sure if this is the right place to post, but here's what I'm seeing...

I haven't been able to get Sonarr running on my DS118 running DSM 7 yet. I've tried using the mono package linked on [Mono 6.12 for DSM 7.0 #4669](https://github.com/SynoCommunity/spksrc/pull/4669) ([mono_aarch64-7.0_5.20.1.34-17.spk](https://github.com/hgy59/spksrc/releases/tag/mono-5.20.1.34-17dsm7)) and the package on synocommunity ([mono.v17.f40000[rtd1296-armada37xx-aarch64].spk](https://synocommunity.com/package/mono)) without success.

I'm using the Sonarr package linked above ([nzbdrone.v19.f40000[rtd1296-armada37xx-aarch64].spk](https://synocommunity.com/package/nzbdrone)). I initially tried this with Sonarr v2 still installed, then from scratch. No dice.

Wondering if I'm missing something - seems like Sonarr should be working at this point based on the [Meta: DSM7 package status #4524](https://github.com/SynoCommunity/spksrc/issues/4524) thread. The only other data point that I can think of that might be helpful is that I had trouble updating Sonarr to v3 even before DSM7. Something about the latest update broke it and I had to downgrade several versions to get it working again.

**Comment by DieterC1984** [comment]
> @DieterC1984 do you have log files you can share with us. It lets us know what Sonarr is doing. It could just be indexing the file system for TV shows and once it's done would calm down

[sonarr.0.txt](https://github.com/SynoCommunity/spksrc/files/6944032/sonarr.0.txt)

@publicarray , logfile attached.

**Comment by altanir84** [comment]
Sonarr is running on my DS418 with DSM7, however it's impossible to select download station as a client. It gives a 400 bad request response when I try to test it. User is with proper permissions, firewall is ok. Could it be a bug?

[v3.0.6.1265] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://192.168.1.129:6251/webapi/query.cgi?api=(removed)&version=1&method=query&query=SYNO.API.Auth%2CSYNO.DownloadStation.Task]
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T] (NzbDrone.Common.Http.HttpRequestBuilder requestBuilder, System.String operation, NzbDrone.Core.Download.Clients.DownloadStation.DiskStationApi api, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x000e8] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:125 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.UpdateApiInfo (NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x0005e] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:207 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.GetApiInfo (NzbDrone.Core.Download.Clients.DownloadStation.DiskStationApi api, NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00022] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:234 
  at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.GetApiInfo (NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationSettings settings) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:248 
  at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.ValidateVersion () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:392 
  at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.TestConnection () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:356 
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>

**Comment by bakerboy448** [comment]
> Sonarr is running on my DS418 with DSM7, however it's impossible to select download station as a client. It gives a 400 bad request response when I try to test it. User is with proper permissions, firewall is ok. Could it be a bug?
> 
> [v3.0.6.1265] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://192.168.1.xxx:PORT/webapi/query.cgi?api=(removed)&version=1&method=query&query=SYNO.API.Auth%2CSYNO.DownloadStation.Task]
> at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T]

this is fixed in sonarr nightly and due to not setting download paths in download station and sonarr

**Comment by timrettop** [comment]
Sorry to follow up on an old thread but I wanted to check if the issues that plagued Sonarr and Mono 5.20 on DSM6 still exist with DSM7?  I've been running Mono5.8 so that Sonarr could work with my indexers.

**Comment by bschraa** [comment]
Hi,

Can someone confirm that Sonarr/Radarr are working on a syngology DS418 with DSM7, before I upgrade?

Thanks

**Comment by mreid-tt** [comment]
> DS216Play and 2 Ironwolf 4TB drives installed so should be compatible all the way.

hey @DieterC1984, I've been trying to solicit feedback to confirm compatibility with .NET builds of Radarr, Lidarr and Sonarr v4 running on ARMv7 architectures. If you have the time perhaps you can check out https://github.com/SynoCommunity/spksrc/issues/5574 and add your feedback on the test packages I've shared. Appreciate the support.
