### ISSUE TITLE
Docker container usable on Synology NAS

### ISSUE THREAD

**Issue by asteele4** [SynoCommunity/spksrc#4708]
I'd like to see the docker container updated to be usable on a Synology NAS.

(I'll admit I'm not a Docker expert)

I'm running Docker on my NAS so I thought that would be the best place to run this however there's two issues I've run into:

1. The container is intended to run from the command line rather than via the DSM docker interface as the command line shown in the readme starts bash - which I don't believe is accessible if run from the DSM web interface.

2. If I try to run the container from the NAS command line it returns an error because the Docker installation on the NAS doesn't create a a docker group and the /var/run/docker.sock has a group ownership of "root".  I'm not keen to put my user into that group.

To me the simple solution would be to have the container include and run sshd so you could remotely connect to the container.  But those with more Docker on Synology skills than me may have a better solution.

With a solution implemented, could the README be updated to include how to use it via the DSM web interface.

Thanks

**Comment by hgy59** [comment]
> I'd like to see the docker container updated to be usable on a Synology NAS.

@asteele4 do I understand your issue right❓ you want to run a container with the `synocommunity/spksrc` image on the Diskstation❓❓❓
This use case is absolutly out of scope, as the docker image it is ment to provide a cross build develompent environment on a **host** system to create spk packages for different targets (Diskstations).

The host OS must be `linux` (i.e. debian) but MacOS might work too.
Differnt linux OS might work too, but are not officially supported.

**Comment by publicarray** [comment]
One thing I like to add that to be able to compile code in a reasonable amount of time a powerful CPU is needed. IMHO NASs are under-powered for these sorts of things. For comparison to compile transmission to (x64 6.1 and x64 7.0) with an i7-10750H and an SSD takes 2 minutes.

**Comment by asteele4** [comment]
The responses have focused in me wanting to run this on my NAS. I understand why people say this is a bad idea that they won't fix.

Can I re-frame this in a way that is hopefully more acceptable.

I'm simply asking for the image be updated to include sshd so the container can be accessed on a different host from where it's being used.

This is not a container I would want to keep on a storage constrained laptop.  Having it available on a server that I can access when needed I wouldn't think is unreasonable.

**Comment by hgy59** [comment]
It is finally not an issue to add sshd into the development environment to create spk packages.
Btw. [Running sshd inside a container is discouraged](https://docs.docker.com/samples/running_ssh_service/)

But you can create your own docker image based on synocommunity/spksrc.

hints:
- https://dev.to/s1ntaxe770r/how-to-setup-ssh-within-a-docker-container-i5i
- https://stackoverflow.com/questions/27860506/openssh-server-doesnt-start-in-docker-container

With the hints above _(and your additional remarks)_ I ended up in the following `Dockerfile` that uses the `entrypoint.sh` file below:

`Dockerfile`
```dockerfile
FROM synocommunity/spksrc:latest

COPY entrypoint.sh /entrypoint.sh

RUN apt-get update && apt-get install --no-install-recommends -y openssh-server sudo && \
    chmod +x /entrypoint.sh && \
    useradd -rm -s /bin/bash -g root -G sudo -u 1000 test && \
    echo 'test:test' | chpasswd && \
    apt-get clean && rm -rf /tmp/* /var/tmp/*

EXPOSE 22

ENTRYPOINT ["bash", "/entrypoint.sh"]

# THIS PART WILL BE REPLACED IF YOU PASS SOME OTHER COMMAND TO docker RUN
CMD while true; do echo "default arg" && sleep 1; done
```


`entrypoint.sh`

```bash
#!/bin/bash
service ssh restart
exec "$@"
```

After the creation of a docker image with docker build, you can run such a container with:
```
docker run -d -p 22:22 -v ~/spksrc:/spksrc  {your-custom-docker-image}
```

TODO:
- use the name of your custom docker image
- use an alternate port if tcp/22 is already in use like -p 222:22
- adjust the localtion of  ~/spksrc to your local clone of the repository
