### ISSUE TITLE
Problem with the Radarr Package

### ISSUE THREAD

**Issue by Kurchunk** [SynoCommunity/spksrc#4711]
I wasn't sure where to report this issue, but the SynoCommunity Radarr package has an issue where it doesn't restore from a backup. Instead, it will say that the backend has disconnected (not sure of the exact wording), and reloading - or shutting down the app and restarting doesn't fix the issue. I've just been setting everything up from scratch, but that is definitely not a long-term solution...

**Comment by publicarray** [comment]
@Kurchunk did you have any log files? Without one, I can't do much. I did not have such an issue in my tests with the latest Radarr version.
