### ISSUE TITLE
[Package Request] UsbSerialDrivers

### ISSUE THREAD

**Issue by Jopand** [SynoCommunity/spksrc#4714]
* Name: UsbSerialDrivers
* Description: In DSM 6.x UsbSerialDrivers package was needed in order to get some zigbee-dongles (like the popular CC2652) to work. This package is not avaliable in DSM 7, so these dongles cannot be mounted properly. The package contains several modules (usbserial.ko, ti_usb_3410_5052.ko, pl2303.ko, ftdi_sio.ko, cp210x.ko, ch341.ko), a few of them are present in DSM 7, but not all. Compilation of these modules would be a big help for many "Smart Home"-users
* Website: http://www.jadahl.com/drivers_6.2/
* Software documentation: 
* Build/Installation documentation: 
* Source code:  
* License:

**Comment by BenjV** [comment]
On DSM 7 it is not longer possible to install things that need root privs.
If you need kernel mods you have to install them from the command line yourself.

**Comment by Jopand** [comment]
I know I have to "insmod" the modules manually, but that's doable. But I have no idea how to compile them

**Comment by BenjV** [comment]
You could download the package from jadahl for you Nas and extract the kernel mods from it.

**Comment by Jopand** [comment]
No, it doesn't work. The modules are compiled for DSM 6.2 and cannot be used for 7.0.

**Comment by BenjV** [comment]
That is possible but not likely.
They are kernel mods and so only dependent on the linux.
DSM is only a layer on top of linux and I doubt that the linux version is changed when upgrading to DSM 7.

But I agree that compiling new mods would be nicer, but they cannot be distributed and installed as a package.
Just the compiled mods and a install script would be ideal.

**Comment by Jopand** [comment]
I tried it... Don't remember the exact error message, but I cannot use the module built by jadahl in the DSM 6.2 package. Possibly because of a newer Linux kernel?

**Comment by BenjV** [comment]
Which device do you have and which kernel module do you think you need.
Most of the modules in the jadahl package are already default available on linux.

**Comment by Jopand** [comment]
I have a DS216+II. The needed module is cp210x. I am aware of it it being a part of the linux kernel, but maybe Synology chose to exclude from their system (it isn't in either DSM 6.2 or 7.0)

**Comment by BenjV** [comment]
You are unlucky.
I use a aeontec zwave stick and the acm drivers(cdc-acm) are still available on DSM 7 just as on DSM6.

**Comment by hgy59** [comment]
@th0ma7 can we close this? 
Since #6089 we have `SynoKernel USB Serial drivers v1.2-9` and it contains `cp210x.ko` (among others) for DSM 6.2, DSM 7.1 and DSM 7.2.

**Comment by th0ma7** [comment]
Yup
