### ISSUE TITLE
transmission: Invalid file format on DSM7

### ISSUE THREAD

**Issue by Ryan-Xu** [SynoCommunity/spksrc#4718]
Setup
Package Name: transmission
Package Version: 3.00-19

NAS Model: DS218+
NAS Architecture: x86
DSM version: DSM 7.0-41890

Expected behavior
Package would install

Actual behavior
Error is shown:

Invalid file format. Please contact the package developer.

Steps to reproduce
1. Try to install any package

Package log
None that I could find.

**Comment by hgy59** [comment]
Transmission is not yet available for DSM 7, see #4524
