### ISSUE TITLE
Mosquitto package repair doesn't work on DSM 7.0

### ISSUE THREAD

**Issue by ThierryM** [SynoCommunity/spksrc#4720]
Hi,
I have updated to DSM 7.0 (version DSM 7.0-41890) on a DS 713+ and there is a problem with Mosquitto package.

### Setup
_Package Name:_ Mosquitto
_Package Version:_ 1.6.15-12

_NAS Model:_ DS 713+
_NAS Architecture:_ Intel Atom D2700
_DSM version:_ 7.0-41890

### Expected behavior
Normal installation of the package.

### Actual behavior
When the package repair of Mosquitto is launched, error message telling that it's impossible to repair : 
![Sélection_428](https://user-images.githubusercontent.com/1470067/124874733-5ce69280-dfc8-11eb-99e6-24d9d2a11e91.png)

Regards,

Thierry

**Comment by BenjV** [comment]
Repairing of old (pre DSM 7) packages does not work and there is no documentation from Synology what that function does.
You have to install a DSM 7 version.

**Comment by ThierryM** [comment]
Hi,
Thanks for your help @BenjV. 
I've uninstalled and reinstalled Mosquitto and same issue.
So as the Mosquitto package doesn't yet exist for DSM 7 version, we have to wait a new one.
Where can I ask a request for that ? Is it here ?
Regards,

Thierry

**Comment by hgy59** [comment]
But mosquitto v1.6.15-12  is built for DSM7 and it runs on my DS918+.

@ThierryM can you please download the DSM7 version for your DS and try to manually install it?

**Comment by ThierryM** [comment]
@hgy59, I don't understand I've the version 1.6.15-12 of Mosquitto and DSM7 and it doesn't work.
![Sélection_431](https://user-images.githubusercontent.com/1470067/125207098-b7167a80-e28a-11eb-9131-d172dec81041.png)

**Comment by ThierryM** [comment]
I removed the package with erasing old configuration files (I've personnalized Mosquitto like here : https://gist.github.com/ajumalp/0ad2517d15c999cfc440cdf3d623fab8) and now it's working.
Thanks for your help.
Sorry for the noise.
