### ISSUE TITLE
TvHeadend Port Conflict

### ISSUE THREAD

**Issue by bolsover** [SynoCommunity/spksrc#4722]
### Setup
_Package Name:_  TvHeadend
_Package Version:_ 4.3.20210612-29

_NAS Model:_ DS1515+
_NAS Architecture:_ x64 Intel Atom C2538
_DSM version:_ 7..0-31890

### Expected behavior
Recently updated to DSM 7.0 but unable to install TvHeadend

### Actual behavior
Install fails with the message 'Port 9981 configured for this package is either used by another service or reserved for system use....'

I have not been able to establish what other service or reservation is causing the issue.

**Comment by BenjV** [comment]
You can check which package is using port 9981 with this command:
`servicetool --conf-port-conflict-check --tcp 9981`

**Comment by thierolm** [comment]
Hi @BenjV, I'm getting, but tvheadend is NOT installed and running anymore ...
```bash
thierolm@THIEROLF-NAS:/etc$ servicetool --conf-port-conflict-check --tcp 9981
IsConflict: true        Port: 9981      Protocol: tcp   ServiceName: tvheadend
```

**Comment by hgy59** [comment]
It seems that the uninstallation of tvh did not complete successfully as the firewall port configuration for thv is still active.

If you still find the file `/usr/local/etc/services.d/tvheadend.sc` on your diskstation your problem might be solved by just deleting this file.

_or use `servicetool --remove-configure-file --package /usr/local/etc/services.d/tvheadend.sc`_

**Comment by BenjV** [comment]
You had most likely tvheadend installed before you upgraded to DSM 6.
Synology did nothing to migrate DSM 6 packages to DSM 7, so it is still installed but not visible nor usable in the DSM 7 gui.

Login to the commandline as admin and give this command:
`dir /usr/local/etc/services.d`
If there is a file .sc file from tvheadend remove it with
`sudo rm /usr/local/etc/services.d/tvheadend.sc`

After this you should be able to install a new DSM 7 capable version of tvheadend

**Comment by thierolm** [comment]
Yay :-) Thx for your support!

**Comment by hgy59** [comment]
This solution was working in #4731

**Comment by thierolm** [comment]
Hi @BenjV , @hgy59 , I installed tvheadend again, but trying to login with the new configured adnmin password I'm getting `403 Forbidden` response (tried it already with 3 installs ...). Do U have an idea?
![image](https://user-images.githubusercontent.com/77847348/125200185-0f895000-e26a-11eb-998a-91310e99cd27.png)

**Comment by hgy59** [comment]
@thierolm pleasse create a new issue, as the port conflict issue is solved.

**Comment by thierolm** [comment]
> pleasse create a new issue, as the port conflict issue is solved

Done: #4733

**Comment by bolsover** [comment]
Thanks for all the comments and assistance..
Initially I ran:
 servicetool --conf-port-conflict-check --tcp 9981
This reported: (I assume form previous install)
IsConflict: true        Port: 9981      Protocol: tcp   ServiceName: tvheadend
Then..
sudo rm /usr/local/etc/services.d/tvheadend.sc

Finally installed TVHeadend from community files.
:-)
