### ISSUE TITLE
DS920 DSM7 Transmission wont be repaired

### ISSUE THREAD

**Issue by Waffelparty** [SynoCommunity/spksrc#4732]
### Setup
_Package Name:_  Transmission
_Package Version:_ 3.00-19

_NAS Model:_  Synology DS920
_NAS Architecture:_  x64
_DSM version:_  DSM 7.0-41890

### Expected behavior
After the upgrade to DSM 7 just a few updates and start transmission again

### Actual behavior
It says repair needed.  After the start of the repair, the NAS starts the download of the package and gives the error. Download and manual upgrade provides the same error.

Invalid file format. Please contact the package developer.

### Steps to reproduce
_1._ Install Transmission on DSM6
_2._ Upgrade to DSM7
_3._ Try to repair the package

#### Package log
_Installer log: find logfile `/var/log/packages/{package}.log`, for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` and protocol in Package Center.
You find service log and other log files in `/var/packages/{package}/target/var`.
_
```
Insert the package log(s) here
```
#### Other logs
2021/07/11 18:45:58 Installing flag of [transmission] exists.
2021/07/11 18:45:58 upgrade transmission: start version 3.00-19 failed, result 0
2021/07/11 18:45:58 upgrade transmission from 3.00-19 to 3.00-19 failed
2021/07/11 18:45:58 (system) trigger transmission 3.00-19 Begin start-stop-status stop
2021/07/11 18:45:58 (system) trigger transmission 3.00-19 End start-stop-status stop ret=[0]
2021/07/11 18:45:58 Release port-config for transmission when 0x0000 (ready)
2021/07/11 18:45:58 Release port-config for transmission when 0x0000 (done)
2021/07/11 18:46:05 download transmission https://packages.synocommunity.com/transmission/19/transmission.v19.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=geminilake&build=41890 Begin download
2021/07/11 18:46:05 download transmission https://packages.synocommunity.com/transmission/19/transmission.v19.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=geminilake&build=41890 End download
2021/07/11 18:47:50 start transmission: begin to stop due to abnormal status
2021/07/11 18:49:02 download transmission https://packages.synocommunity.com/transmission/19/transmission.v19.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=geminilake&build=41890 Begin download
2021/07/11 18:49:02 download transmission https://packages.synocommunity.com/transmission/19/transmission.v19.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=geminilake&build=41890 End download
2021/07/11 18:53:11 download transmission https://packages.synocommunity.com/transmission/19/transmission.v19.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=geminilake&build=41890 Begin download
2021/07/11 18:53:11 download transmission https://packages.synocommunity.com/transmission/19/transmission.v19.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=geminilake&build=41890 End download

**Comment by hgy59** [comment]
As you can see in #4524 transmission is not available for DSM7 yet.  It is still work in progress #4719.
