### ISSUE TITLE
Jellyfin images are not displayed correctly 

### ISSUE THREAD

**Issue by marcinek34** [SynoCommunity/spksrc#4738]
### Setup
_Package Name:_ Jellyfin
_Package Version:_ 10.7.6-2

_NAS Model:_ DS218+
_NAS Architecture:_ x64
_DSM version:_ DSM 7.0-41890

### Actual behavior
Images from generated URL (http://SERVER_NAME:8096/Images/Remote?imageUrl=http%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FeDnHgozW8vfOaLHzfpHluf1GZCW.jpg) are not showing at all.
When I copy the url to browser i recieve 404. The image part of the image (http://image.tmdb.org/t/p/original/eDnHgozW8vfOaLHzfpHluf1GZCW.jpg) works correctly. 
P.S. Decoded URL (http://SERVER_NAME:8096/Images/Remote?imageUrl=http://image.tmdb.org/t/p/original/eDnHgozW8vfOaLHzfpHluf1GZCW.jpg) does not works too.
When I select any of the "black" covers it is loaded and displayed correctly but I can't see the image I choose.

### Steps to reproduce
_1._ Create any library (movies or series)
_2._ On any element try to change cover image - the list displays without covers.

**Comment by publicarray** [comment]
Hi @marcinek34!

From a quick test I can confirm this. It looks like the endpoint was removed due to this advisory: https://github.com/jellyfin/jellyfin/security/advisories/GHSA-rgjw-4fwc-9v96

**Comment by publicarray** [comment]
@joshuaboniface Is this a known issue? I wasn't able to find it in the jellyfin issues.
![jellyfin](https://user-images.githubusercontent.com/5497998/125733439-8fc04817-43b4-4c91-bd54-bc8167ebd035.png)

**Comment by marcinek34** [comment]
Today I installed jellyfin with docker (jellyfin/jellyfin -> latest)
The images in docker-jellyfin container are displayed correctly but the url different. It's pointing direct to image (http://image.tmdb.org/t/p/original/eDnHgozW8vfOaLHzfpHluf1GZCW.jpg). The url's are build without the redirection part (http://SERVER_NAME:8096/Images/Remote...).

**Comment by publicarray** [comment]
Thanks for the info, I'll have to look at it tomorrow.

**Comment by publicarray** [comment]
Ah I found the issue. when releasing I missed to update the jellyfin-web. Sorry, will release a fix soon.
