### ISSUE TITLE
Sickbeard custom  Failed to run package service

### ISSUE THREAD

**Issue by Richardgriff** [SynoCommunity/spksrc#474]
I am running DSM4.2 on my DS112J and have installed the following packages.

GIT from SYNOCOMMUNITY
PYTHON from SYNOCOMMUNITY

When I come to install the SICKBEARD CUSTOM package I get the error 
FAILED TO RUN PACKAGE SERVICE.

The custom sickbeard git I am using is 

git://github.com/junalmeida/Sick-Beard.git

branch

torrent_1080_subtitles.

unsure why this is not working

![SICK](https://f.cloud.github.com/assets/4070138/344585/cda3373a-9e04-11e2-9498-6b6ed4b0ad9b.png)

**Comment by ruipires** [comment]
Hi, I am having the exact same issue on a DJ213J.
I connected via SSH (with root), but there is no /var/packages/sickbeard-custom yet. Package failed on install, maybe thats why its not there ?
