### ISSUE TITLE
Boost upgrade to 1.76 possible ?

### ISSUE THREAD

**Issue by ohnoohweh** [SynoCommunity/spksrc#4746]
### Setup
_Package Name:_  boost
_Package Version:_  1.66

_NAS Model:_  DS918+
_NAS Architecture:_  apollolake
_DSM version:_  7

### Expected behavior
I have a linux application based on Boost 1.76 (Websockets / SSL) that I would love to natively run on Synology.
DSM7 comes with Boost 1.68, however some SSL related functionalities in boost aren't developed yet, so compilation fails.

There is a boost lib in spksrc for boost, however using version 1.66. This compiles well.

### Actual behavior
I tired to change to 1.76 and compile, however compilation fails

./boost/core/cmath.hpp:141:12: error: ‘std::isfinite’ has not been declared
 using std::isfinite;
            ^~~~~~~~
./boost/core/cmath.hpp:142:12: error: ‘std::isnan’ has not been declared
 using std::isnan;
            ^~~~~
./boost/core/cmath.hpp:143:12: error: ‘std::isinf’ has not been declared
 using std::isinf;
            ^~~~~
./boost/core/cmath.hpp:144:12: error: ‘std::isnormal’ has not been declared
 using std::isnormal;
            ^~~~~~~~
./boost/core/cmath.hpp:145:12: error: ‘std::fpclassify’ has not been declared
 using std::fpclassify;
            ^~~~~~~~~~
./boost/core/cmath.hpp:153:12: error: ‘std::signbit’ has not been declared
 using std::signbit;

It seems to have some trouble with the c++ 2011 definitions above.

Is the currently used GCC 7.3.0 fresh enough for this task ?

### Steps to reproduce
_1._  Download develop environment
_2_. Change version to PKG_VERS = 1.76.0 in Makefile
        Change checksums in digest file to
        boost_1_76_0.tar.bz2 SHA1 8064156508312dde1d834fec3dca9b11006555b6
        boost_1_76_0.tar.bz2 SHA256 f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41 
        boost_1_76_0.tar.bz2 MD5 33334dd7f862e8ac9fe1cc7c6584fb6d 
_2._  cd /spksrc/cross/boost
_3._ make arch-apollolake-7.0

[boost_1_76_0_buildlog.txt](https://github.com/SynoCommunity/spksrc/files/6841016/boost_1_76_0_buildlog.txt)

Did anyone ever attempt to upgrade the lib ? Don't like to reinvent the wheel in case someone did it before ;-)

**Comment by hgy59** [comment]
for DSM7 those errors might disappear with definitions like:
```
include ../../mk/spksrc.common.mk

ifeq ($(call version_ge, ${TCVERSION}, 7.0),1)
# fix compilation with newer compilers
ADDITIONAL_CPPFLAGS = -D_GLIBCXX_USE_C99_MATH -D_GLIBCXX_HAVE_OBSOLETE_ISNAN -D_GLIBCXX_HAVE_OBSOLETE_ISINF
ADDITIONAL_CXXFLAGS = $(ADDITIONAL_CPPFLAGS)
endif
```

**Comment by hgy59** [comment]
There are issues with 32 bit archs (#4069)

**Comment by ohnoohweh** [comment]
@hgy59: Thanks a lot for your very helpful responses (as usual).

I was able to compile the boost-1.78 using the attached files in cross/boost.

I did not try the 32bit variants, apollolake-7.0 is a 64bit variant.

I don't know how you like to handle this variant in this repository. 
Is it foreseen to support multiple version of the same lib ?
Shall it remain on a branch ?

Anyway I hope the provided solution helps others facing the same problem:
[cross_boost_1_76.zip](https://github.com/SynoCommunity/spksrc/files/6847064/cross_boost_1_76.zip)

**Comment by ohnoohweh** [comment]
In respect to the 32bit version.

I do have a DS216j as well.
I was able to compile the boost 1.76 using make arch-armada38x-7.0 and arch-armada38x-6.2.4 as well

**Comment by hgy59** [comment]
@ohnoohweh a pull request of your work would be welcome 🎉

**Comment by ohnoohweh** [comment]
Well this is my first time ever contributing on GitHub. 
So I created a fork
Tried to merge - ended up doing in on the web page as git push did not upload
@hgy59 Additional instructions welcome ;-)

**Comment by hgy59** [comment]
1. make a fork of https://github.com/SynoCommunity/spksrc/
2. make a local clone of your fork (https://github.com/{your-gh-user}/spksrc/)
3. in your local repo checkout a new (working) branch
4. make and commit your changes
5. push your branch (to your fork)
6. In https://github.com/SynoCommunity/spksrc/ create a PR (request to pull your branch)
7. Make further changes in your local repo, commit and push, so the commit will be pushed to your PR too.

**Comment by hgy59** [comment]
@ohnoohweh what is the reason you want an update of the boost library?
None of the currently supported packages require a newer version of boost.
The toolchains from synology (and the kernels of the NAS devices) are very old and it is not possible, to use the newest libraries in any case.
This will get _a little bit_ better with DSM7, but we do not want to drop the support for DSM 6 now.

If you want to build a package that depends on a newer boost version, you are welcome to create a PR here.

**Comment by ohnoohweh** [comment]
Hi,
I have been interested to collect some stock data (buy / sell) values to develop some buy / sell strategies.
I found a great online bank broker called TradeRepublic. They offer stock from Lang&Schwarz Exchange. Using the TR application you can see some charts about the actual sell price however the buying part is missing.
I went to the L&S page and found there is a static HTML page and some JavaScript that connects to Websocket to get periodic updates.
I analyzed the webtraffic and wrote a C++ boost based program that connects to the L&S servers to capture this pushed information and store it to some excel files.

Now I got the idea to have this program running in background all time. So I thought about using my NAS. I tried with some virtual machine on it, however I envisioned something less computational expensive. Docker container could have been another option, I decided to look into the feasibility of developing my own NAS service for that.

At a certain time I found the existing Synology NAS C++ Boost lib did not support the interface for SSL based Websockers so I finally I ended up on upgrading the SynoCommunity Boost and finally I was able to compile the capture program natively on the DSM7 DS916+.

I tought in general maybe someone else has for whatever reason the need for an updated Boost Lib and so it would be beneficial to share the work I did - especially as are providing an excellent starting point.

From this perspective there is no need to merge the upgrade into the repro, however I think it is a give and take and I like to say thank you for all your work you have been doing in a form that I like to share the progress on upgrading the lib.
