### ISSUE TITLE
Download Station Magnet incompatible with DSM 7.0

### ISSUE THREAD

**Issue by CozaMcCoza** [SynoCommunity/spksrc#4760]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Download Station Magnet
_Package Version:_ 1.0-2

_NAS Model:_ DS918+
_NAS Architecture:_ INTEL Celeron J3455 
_DSM version:_ 7.0-41890

### Expected behaviour
Unable to repair following upgrade to DSM 7.0.

### Actual behaviour
When trying to repair, error message produced "Invalid file format"

### Steps to reproduce
_1._ Update to DSM 7.0
_2._ Attempt to repair Download Station Magnet
_3._ Clear error message

**Comment by hgy59** [comment]
As you find in #4524 this package is not yet ported to DSM7

**Comment by publicarray** [comment]
I've tested and pushed the syno-magnet package (if you get `Your browser is not supported.` make sure to use `https://` as the URL handler can only be installed on secure sites.)
