### ISSUE TITLE
'Home Assistant' is not repairing/installing on DS220j after upgrade to DSM 7.0

### ISSUE THREAD

**Issue by BlueWhaleSEO** [SynoCommunity/spksrc#4761]
### Setup
_Package Name:_ [Home Assistant ](https://synocommunity.com/package/homeassistant)
_Package Version:_ 2021.1.5-13

_NAS Model:_ [DS220j](https://global.download.synology.com/download/Document/Hardware/DataSheet/DiskStation/20-year/DS220j/enu/Synology_DS220j_Data_Sheet_enu.pdf?_ga=2.211685909.1610306812.1605904614-1003422424.1605904614&_gl=1*2o7ql3*_ga*MTAwMzQyMjQyNC4xNjA1OTA0NjE0*_ga_9Q8XT3X20D*MTYwNTk2Njg4NC41LjAuMTYwNTk2Njg4NC4w) 
_NAS Architecture:_ rtd1296 
_DSM version:_ DSM 7.0-41890

### Expected behaviour
After the upgrade from DSM 6.2.4-25556 Update 2 it should continue working on DSM 7.0 as well, ~~especially that there are people having it working on 7.0 beta version~~. 

### Actual behaviour
After the upgrade HA made it to 'Repair' list together with Python packages. Whilst Python packages have been "repaired" just fine, repairing or re-installing HA ends up with **"Home Assistant Core: Invalid file format. Please contact the package developer."** error.  

Same error appeared for 'htop' and 'vim' packages, but I can live without them. 

### Steps to reproduce
_1._ Upgrade existing DSM 6 with HA installed and running to DSM 7.
_2._ Try to 'Repair' or re-install HA.

**Comment by BenjV** [comment]
At the moment there is no DSM 7 version of Home Assistance.

Nobody knows what DSM is trying to do when you choose repair, but it is not able to convert a DSM 6 package to a DSM 7 capable package.

**Comment by BlueWhaleSEO** [comment]
> At the moment there is no DSM 7 version of Home Assistance.
> 
> Nobody knows what DSM is trying to do when you choose repair, but it is not able to convert a DSM 6 package to a DSM 7 capable package.

Thank you @BenjV. In that case I will simply leave this issue open as there's no way I'm upgrading until HA is working with DSM 7. Also, I haven't done any research yet, but does that mean that my [CC2531 Zigbee USB adapter](https://www.amazon.co.uk/gp/product/B085MFRK9W/) will also stop working with DSM 7 just as all the other Wi-Fi/Bluetooth adapters?

**Comment by Lylrok** [comment]
Hello

I've the same problem :( 

NAS Model: DS416j
NAS Architecture: MARVELL Armada 388 88F6828 (Armada38x)
DSM Version: DSM 7.0-41890

![2021-08-05_14h49_47](https://user-images.githubusercontent.com/87832950/128354920-19933fd7-78b5-454e-859c-9c08ab613b39.png)

**Comment by Lylrok** [comment]
@ymartin59 Do you think you can help us ?🙄 
 Thank you 😄

**Comment by hgy59** [comment]
HA for DSM7 is still in progress  #4580
