### ISSUE TITLE
Transmisson on DSM7 (v1000) invalid

### ISSUE THREAD

**Issue by sztridaa** [SynoCommunity/spksrc#4764]
### Setup
_Package Name:_  Transmission
_Package Version:_ 3.00-19

_NAS Model:_ DS1821+
_NAS Architecture:_ v1000
_DSM version:_ 7.0-41890

### Expected behavior
Tell us what should happen: install proprtly

### Actual behavior
Tell us what happens instead: Invalid file format

### Steps to reproduce
_1._ Install / update from package center
_2._ or install manually from spk
_3._ 

#### Package log
No fresh install or package  log

#### Other logs
synopkg.log:
2021/08/06 17:01:02 download transmission https://packages.synocommunity.com/transmission/19/transmission.v19.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=v1000&build=41890 Begin download
2021/08/06 17:01:02 download transmission https://packages.synocommunity.com/transmission/19/transmission.v19.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=v1000&build=41890 End download

**Comment by hgy59** [comment]
transmission is not yet available for DSM7, see #4524
