### ISSUE TITLE
NZBGet unable to Repair after DSM 7 upgrade

### ISSUE THREAD

**Issue by EmjayGitHub** [SynoCommunity/spksrc#4765]
### Setup
_Package Name:_ NZBGet
_Package Version:_ 20210607-27

_NAS Model:_ Synology DS1817+
_NAS Architecture:_ INTEL Atom C2538 ?
_DSM version:_ DSM 7.0-41890

### Expected behavior
I am able to update the package.

### Actual behavior
After the new DSM 7 upgrade, I can't repair the NZBGet package, due to "Invalid file format" of the package, according to DSM.

### Steps to reproduce
_1._ Have NZBGet installed on DSM v 6.x
_2._ Upgrade to DSM v 7.x
_3._ Press the Repair button in DSM package center

Regards.

**Comment by BenjV** [comment]
There is not yet a DSM 7 version released.
See https://github.com/SynoCommunity/spksrc/issues/4524

**Comment by McEnnes** [comment]
NZBget is used by a lot of people, is anybody working on this package?

**Comment by BenjV** [comment]
Download Station uses NZBget for usenet downloads.
Maybe you can use that instead.

**Comment by McEnnes** [comment]
Thanks BenjV! 
I have NZBget currently running in a Docker container, but not exactly the way i want it to.
I cannot get NZBget scripts for Series and Movies working like i want them to due to Docker Mounting points.
For now i have workarounds, but i hope to use NZBget again as a "normal" package.

**Comment by EmjayGitHub** [comment]
I have moved to Download Station as well, after seeing it could do nzb. It works just fine. As long as you only use 1 newshost, it is sufficient.

Regards.
