### ISSUE TITLE
uMurmur

### ISSUE THREAD

**Issue by MrMars72** [SynoCommunity/spksrc#4774]
### Setup
_Package Name:_ uMurmur
_Package Version:_ 0.2.17-7

_NAS Model:_ DS220J
_NAS Architecture:_ Realtek RTD1296 SoC
_DSM version:_ DSM 7.0-41890

### Expected behavior
uMurmur installation

### Actual behavior
Invalid file format error on installing after upgrade to DSM7

### Steps to reproduce
_1._ Go to Package Center
_2._ Search for uMurmur
_3._ Click Install

#### Package log
_Installer log: find logfile `/var/log/packages/{package}.log`, for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` and protocol in Package Center.
You find service log and other log files in `/var/packages/{package}/target/var`.
_
```
Insert the package log(s) here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
As you cam see in #4524 uMurmur is not yet updated for DSM7.

**Comment by MrMars72** [comment]
Thank you for pointing that out. Couldn't find it myself.
