### ISSUE TITLE
Impossible to download sabnzbd on Synology ds416j

### ISSUE THREAD

**Issue by oliverspike** [SynoCommunity/spksrc#4791]
### Setup
_Package Name:_ sabnzbd
_Package Version:_ 

_NAS Model:_ Synolog< D416J
_NAS Architecture:_ Marvell Armada 388 88F6828
_DSM version:_ DSM 7.0-41890

### Expected behavior
Download and install of the package sabnzbd

### Actual behavior
After i did upgrade my NAS to the version 7 of the DSM i had to repair all my packages. it did worked for Sonar and radar
but for sabnzbd it tells me Unable to download "sabnzbd".

### Steps to reproduce
_1._ Open Package center
_2._ community
_3._ sabnzbd click install

**Comment by publicarray** [comment]
sabnzbd is still in development here: https://github.com/SynoCommunity/spksrc/pull/4748

Please read our README https://github.com/SynoCommunity/spksrc#dsm-7

Current development status of DSM7 packages: https://github.com/SynoCommunity/spksrc/issues/4524
