### ISSUE TITLE
[Package Request] Home Assistant Core DSM7.0

### ISSUE THREAD

**Issue by Dragoniacs16** [SynoCommunity/spksrc#4792]
* Name: Home Assistant Core
* Description: Version avalaible in SynoCommunity packages is 2021.1.5-13 refuse to install on my DS218play (under DSM7). It was working when my NAS was in version DSM6.2
* Website: 
* Software documentation: 
* Build/Installation documentation: 
* Source code:  
* License:

**Comment by Dragoniacs16** [comment]
Author of the package is 'ymartin59'
@ymartin59 

thanks :)

**Comment by hgy59** [comment]
this is WIP in #4580

**Comment by Dragoniacs16** [comment]
Thanks !
I'll follow it closely because I can't command anymore my Velux since I have made the DSM7 update :(

**Comment by hgy59** [comment]
Homeassistant is a beast with all it's dependencies. I have spent hours to resolve those, but so far I succeeded for x64 and aarch64 only (pycryptodomex wheel fails to run with armv7l). So you are lucky with DS218play (aarch64).

_and they just released version 2021.8.7 yesterday and I my latests tests were for 2021.8.1, .3, .4, .5, .6..._

**Comment by Dragoniacs16** [comment]
Do you mean you have a version which can be installed on my NAS ?
Incredible, that's the 1st time something is working on mine and not others :D (like Docker, VM,....)
Could you please send me the .spk for manual installation?

**Comment by Dragoniacs16** [comment]
@hgy59 Thanks for the pushs, but I'm only beginner so I'll need help from you :) Sorry to bother you again.
If I understand well, you send me list of files to be manually updated in my NAS. But I've uninstalled the HomeAssistant application (I though it will help to reinstall it from scratch since it was not starting). And I can't install it again because my NAS says that the version avalaible on the store (2021.1.5-13) is not compatible with my DSM version.
I think I need a "homeassistant_v2021_xxx.spk" file, for a manual installation.
I hope my explainations are clear :)
Thanks again for your support.

**Comment by hgy59** [comment]
Yes I will publish prerelease spk file on my spksrc fork, just hold on...

**Comment by v120fr** [comment]
hi, got the package for ds116 (homeassistant_armv7-7.0_2021.8.7-14.spk), but after installation, erro on start:
yarl not found in the log
-> on the web i can see it's module of phtyon, i must do something on my nas or missing in package home assistant ?

**Comment by Dragoniacs16** [comment]
It's perfectly working on my NAS (DS218play) with the package homeassistant_aarch64-7.0_2021.8.7-14.spk
Thanks a lot @hgy59  !

**Comment by hgy59** [comment]
> hi, got the package for ds116 (homeassistant_armv7-7.0_2021.8.7-14.spk), but after installation, erro on start:
> yarl not found in the log

currently armv7 arch is known to fail on installation...

**Comment by Dragoniacs16** [comment]
I've seen many releases. But none is '.spk'. And DSM package manager do not suggest me any of those updates.
How can I update my HomeAssistant ?
(remember I do not have docker....)

**Comment by hgy59** [comment]
@Dragoniacs16 you can try the packages built with github action of #4580
