### ISSUE TITLE
TRANSMISSION for DSM 7.0

### ISSUE THREAD

**Issue by Fandaor** [SynoCommunity/spksrc#4799]
* Name:  Transmission BT Client
* Description: BT Client
* Website: https://synocommunity.com/package/transmission
* Software documentation: https://synocommunity.com/package/transmission
* Build/Installation documentation: https://synocommunity.com/package/transmission
* Source code:  
* License:

The actual version v3.00-19 is not DSM 7.0 comppliant and when trying to install it, generates an error (Format file non-valid please contact the package developer)
Could you please provide a working package ?

Thank you in advance

**Comment by publicarray** [comment]
ALL CAPS only gets you a link: https://github.com/SynoCommunity/spksrc/pull/4719
