### ISSUE TITLE
[Package Request] Prowlarr

### ISSUE THREAD

**Issue by hurricaneporter** [SynoCommunity/spksrc#4800]
* Name: Prowlarr
* Description: Prowlarr is an indexer manager/proxy built on the popular *arr .net/reactjs base stack, to integrate with your various PVR apps.
* Website: https://prowlarr.com/
* Software documentation: https://wiki.servarr.com/en/prowlarr
* Build/Installation documentation: https://wiki.servarr.com/prowlarr/installation
* Source code:  https://github.com/Prowlarr/Prowlarr
* License: GPL 3

**Comment by SheepKid12** [comment]
Here's my spksrc branch with Prowlarr (everything appears to compile & run without any errors): https://github.com/SheepKid12/spksrc/tree/add_prowlarr

**Comment by hgy59** [comment]
duplicate of #4780
