### ISSUE TITLE
[Package Request] Readarr

### ISSUE THREAD

**Issue by hurricaneporter** [SynoCommunity/spksrc#4801]
* Name: Readarr
* Description: Readarr is an eBook collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new books and will interface with clients and indexers to grab, sort, and rename them.
* Website: https://readarr.com/
* Software documentation: https://wiki.servarr.com/readarr
* Build/Installation documentation: https://wiki.servarr.com/readarr/installation
* Source code:  https://github.com/readarr/readarr
* License: GPL 3

**Comment by SheepKid12** [comment]
Just like the Prowlarr request, here's a working build for Readarr (versions are correct at time of comment): https://github.com/SheepKid12/spksrc/tree/add_readarr
