### ISSUE TITLE
Error 503 on architecture 5.2ppc853x

### ISSUE THREAD

**Issue by fredoule2k** [SynoCommunity/spksrc#4802]
### Setup
_Package Name:_ 
Python3.8, SickBeard, SabNzbd, Transmission, ...
_Package Version:_ 
Any version

_NAS Model:_ 
DS110+
_NAS Architecture:_ 
ppc853x
_DSM version:_ 
5.2

### Expected behavior
I am trying to download and install the packages

### Actual behavior
The repository returns an error 503 for this arch while I could directly download without any problem SPKs for the same package on the repo

**Comment by hgy59** [comment]
This might be a temp. issue with the server. Maybe the same as reported in https://github.com/SynoCommunity/spksrc/issues/4071#issuecomment-903142148

**Comment by fredoule2k** [comment]
Indeed, it is solved now
