### ISSUE TITLE
Radarr and Sonarr packages are very old

### ISSUE THREAD

**Issue by MakeTheFuture** [SynoCommunity/spksrc#4809]
Why are the Radarr and Sonarr packages so very old these days? Why are these packages not designed in such a way they pull the latest stable from the net every time they start?

**Comment by publicarray** [comment]
The reason why we don't to X is usually lack of time. In this case there is no improvement from doing it your way other than the perceived newer version number. If you like to contribute feel free to create or review pull requests.
