### ISSUE TITLE
Beets :Invalid package format on install

### ISSUE THREAD

**Issue by Data-007** [SynoCommunity/spksrc#4818]
### Setup
_Package Name:_  Beets
_Package Version:_ 14 9-5

_NAS Model:_ DS220j
_NAS Architecture:_ 
_DSM version:_ 7

### Expected behavior Package should install
Tell us what should happen

### Actual behavior Invaild package format
Tell us what happens instead

### Steps to reproduce
_1._  Install package 100% everytime falure
_2._ 
_3._ 
![Beets](https://user-images.githubusercontent.com/53057579/131241978-fe637fe7-7646-4897-a44b-73f87c84f53c.PNG)

### Setup
_Package Name:_ 
_Package Version:_ 

_NAS Model:_ 
_NAS Architecture:_ 
_DSM version:_ 

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Installer log: find logfile `/var/log/packages/{package}.log`, for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` and protocol in Package Center.
You find service log and other log files in `/var/packages/{package}/target/var`.
_
```
Insert the package log(s) here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Data-007** [comment]
Also getting this from other synocommunity installs to.

**Comment by BenjV** [comment]
See #4524
