### ISSUE TITLE
SyncThing installation via Package Center fails on DSM 7.0-41890 due to port 8384 being used

### ISSUE THREAD

**Issue by sergeifilippov** [SynoCommunity/spksrc#4832]
### Setup
_Package Name:_  Syncthing
_Package Version:_ 1.17.0-22

_NAS Model:_ DS1817+
_NAS Architecture:_ INTEL Atom C2538
_DSM version:_ DSM 7.0-41890

### Expected behavior
Package installs as expected and is started.

### Actual behavior
Package downloads.
Begins installation process.
Error modal is shown advising that port  8384 (default syncthing web ui port is used)

![modal error screen](https://www.synoforum.com/attachments/1624359749_erkrp-jpg.3910/)

This issue originally has come up on DSM 6 but since then I have upgraded to DSM 7.

As a test, I tried to stand up a nginx docker container on port 8384, as got same modal.
I've checked the admin as much as possible and could not find anything that would take the port.

`sudo netstat -tulpn | grep 8384` returns nothing.

### Steps to reproduce
_1._ Try to install via Package Center
_2._ 
_3._ 

#### Package log
_Installer log: find logfile `/var/log/packages/{package}.log`, for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` and protocol in Package Center.
You find service log and other log files in `/var/packages/{package}/target/var`.
_
```
/var/log/synopkg.log
2021/09/02 14:31:35 download syncthing https://packages.synocommunity.com/syncthing/22/syncthing.v22.f40000%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=avoton&build=41890 Begin download

2021/09/02 14:31:36 download syncthing https://packages.synocommunity.com/syncthing/22/syncthing.v22.f40000%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=avoton&build=41890 End download
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Nothing of interest :(
```

**Comment by BenjV** [comment]
Verwijder dit bestand even.

> /usr/local/etc/services.d/syncthing.sc

**Comment by sergeifilippov** [comment]
@BenjV you legend! Thank you!
