### ISSUE TITLE
FFMPEG package not built with libzvbi option

### ISSUE THREAD

**Issue by pcoulombeau** [SynoCommunity/spksrc#4834]
### Setup
_Package Name:_ ffmpeg
_Package Version:_ 4.3.2-37

_NAS Model:_ DS418
_NAS Architecture:_ 
_DSM version:_ 

### Expected behavior
Hi there,
I am intensively using ffmpeg to convert videos, including TV records using DVB teletex subtitle encoding.
For this reason, I use the ffmpeg libzvbi-teletext specific features and options.
I wrote scripts to run these conversion automatically by night, moving videos from the recorder (if any) to the NAS, and reprocessing it afterwards. I was running those scripts on laptops until now, but would like to migrate it directly to the NAS. Everything sounds fine but the subtitle specific activities, because the ffmpeg seems not to have been configured and built with --enable-libzvbi option.

### Actual behavior
Unrecognized option 'txt_format' error message when using this option

### Steps to reproduce
_1._ Get a video that feature some DVB teletext embedded streams (I can provide one short video if useful or needed)
_2._ ffmpeg -y -nostdin -txt_format text -fix_sub_duration -i video.m2ts video.srt

### Execution log
ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 4.9.4 (crosstool-NG crosstool-ng-1.22.0-169-g87eb166) 20150629 (prerelease)
  configuration: --target-os=linux --cross-prefix=/home/spksrc/all-supported-fix/spksrc/toolchain/syno-aarch64-6.1/work/aarch64-unknown-linux-gnueabi/bin/aarch64-unknown-linux-gnueabi- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/home/spksrc/all-supported-fix/spksrc/spk/ffmpeg/work-aarch64-6.1/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/home/spksrc/all-supported-fix/spksrc/spk/ffmpeg/work-aarch64-6.1/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/home/spksrc/all-supported-fix/spksrc/toolchain/syno-aarch64-6.1/work/aarch64-unknown-linux-gnueabi/bin/aarch64-unknown-linux-gnueabi-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-version3 --enable-fontconfig --enable-avresample --disable-debug --disable-doc --disable-static --enable-debug=1 --extra-cflags=-DSYNO_VIDEOSTATION --extra-cflags=-fno-if-conversion --extra-cflags=-O3 --extra-cflags=-Wno-deprecated-declarations --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libbluray --enable-libspeex --enable-libtheora --enable-libvorbis --enable-gnutls --enable-libopus --enable-libsoxr --enable-libx264 --enable-libx265 --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvpx --enable-libzmq --enable-libshine --enable-libfdk-aac --enable-nonfree --enable-libass --enable-libaom --enable-libsvtav1 --arch=arm64 --enable-neon --enable-thumb --disable-yasm --disable-asm
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Unrecognized option 'txt_format'.
Error splitting the argument list: Option not found

**Comment by arnebjarne** [comment]
Suggestion: https://github.com/SynoCommunity/spksrc/pull/4864

**Comment by arnebjarne** [comment]
Not sure it works 100% but at least zvbi is included:

```
/var/packages/ffmpeg/target/bin/ffmpeg -y -nostdin -txt_format text -fix_sub_duration -i big_buck_bunny_eac3_4.m2ts video.srt
ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
  configuration: --target-os=linux --cross-prefix=/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-version3 --enable-fontconfig --enable-avresample --disable-debug --disable-static --disable-doc --extra-cflags=-DSYNO_VIDEOSTATION --extra-cflags=-fno-if-conversion --extra-cflags=-O3 --extra-cflags=-Wno-deprecated-declarations --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libbluray --enable-libspeex --enable-libtheora --enable-libvorbis --enable-gnutls --enable-libopus --enable-libsoxr --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-libx265 --enable-libvpx --enable-libshine --enable-libzmq --enable-libzvbi --enable-libfdk-aac --enable-nonfree --enable-libass --enable-libaom --enable-libsvtav1 --enable-libsvthevc --arch=x86_64 --enable-vaapi --enable-libmfx
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mpegts @ 0x23cd700] start time for stream 2 is not set in estimate_timings_from_pts
Input #0, mpegts, from 'big_buck_bunny_eac3_4.m2ts':
  Duration: 00:02:00.12, start: 2.008333, bitrate: 1208 kb/s
  Program 1
    Stream #0:0[0x1e1]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 640x360 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 90k tbn, 48 tbc
    Stream #0:1[0x20](eng): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 100 kb/s
    Stream #0:2[0x1cc](eng): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
Codec AVOption txt_format (format of the subtitles (bitmap or text or ass)) specified for input file #0 (big_buck_bunny_eac3_4.m2ts) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some decoder which was not actually used for any stream.
Output #0, srt, to 'video.srt':
Output file #0 does not contain any stream
bjarne@dsm6:~$
```
