### ISSUE TITLE
Python Not Installing

### ISSUE THREAD

**Issue by patrickoleary1977** [SynoCommunity/spksrc#4837]
Synology DSM 7.0

I am trying to install GateOne.  it says it needs Python.  When it tries to install Python, it says invalid file format.

**Comment by BenjV** [comment]
You can ot i stall gateone.
There is no Dsm 7 for it yet.

**Comment by patrickoleary1977** [comment]
Thank you, I am new to the repo and Synology in general.

**Comment by BenjV** [comment]
No problem
