### ISSUE TITLE
[Bad Request] Can't add SynoCommunity repo

### ISSUE THREAD

**Issue by dima2306** [SynoCommunity/spksrc#4838]
Is repo https://packages.synocommunity.com/ down again, or for just me?

I'm trying to add on DSM v6.2.4-25556 and getting an invalid location error.

I've pinged `curl --location --request GET 'https://packages.synocommunity.com/?build=24922&language=enu&arch=noarch' --header 'REFERER: -' --header 'USER_AGENT: test agent' --data-raw ''` and got response:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Backend is unhealthy</title>
  </head>
  <body>
    <h1>Error 503 Backend is unhealthy</h1>
    <p>Backend is unhealthy</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-vie6367-VIE 1630756506 4138655096</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by BenjV** [comment]
It is not a website so your curl command is not valid and useless.
The package server of the SynoCommunity is not down, I can install packages from it without problems.

So the issue is on your own network or your service provider.

**Comment by dima2306** [comment]
Hey @BenjV,

Thanks for confirming that packages server works well.
I'll try to debug on my end.

**Comment by publicarray** [comment]
@dima2306 It's not you. There was a spike of errors that appears to have cleared itself in a matter of minutes. Please try again later if that happens.
![Screenshot from 2021-09-05 00-04-09](https://user-images.githubusercontent.com/5497998/132097238-62b65e3a-be06-4afb-956d-e03517b19154.png)

**Comment by dima2306** [comment]
@publicarray Got it, thanks for the information.

I've tried but it still was throwing invalid location error, then I went to the Network tab in my DSM and updated DNS server. Then I was able to add the repo.

**Comment by hgy59** [comment]
@TorstenC the URL you posted is not the homepage - the correct URL is https://synocommunity.com/packages
(https://packages.synocommunity.com is the address you have to use for the DSM package center - this is an API, not a homepage).
