### ISSUE TITLE
"Error 503 Backend is unhealthy"

### ISSUE THREAD

**Issue by itf56** [SynoCommunity/spksrc#4841]
I saw SabNZBD is now OK for DSM 7.0 so went to install it - the repair failed with "invalid file format" so I went to download the package manually (7.0 geminilake), which I think is the URL below  

https://packages.synocommunity.com/sabnzbd/49/sabnzbd.v49.f41890[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64].spk

It fails with "Error 503 Backend is unhealthy"

**Comment by BenjV** [comment]
You mean that the download of the package failed?
Try again later.

**Comment by jaspov** [comment]
I had the same on a different Synology. An hour later it did work.
