### ISSUE TITLE
Python 3 v 38 - from typing import Protocol error

### ISSUE THREAD

**Issue by BKSteve** [SynoCommunity/spksrc#4861]
Incompatibility between using Pythhon3 (3.7.11-18) and Python38 (3.8.11-4) in compiled package causes installation failure.

File 
`/var/packages/python3/target/lib/python3.7/site-packages/importlib_metadata/_compat.py`
and
`/var/packages/python38/target/lib/python3.8/site-packages/importlib_metadata/_compat.py`
both have 
```
try:
    from typing import Protocol
except ImportError:  # pragma: no cover
    """
    pytest-mypy complains here because:  error: Incompatible import of "Protocol" (imported name has type "typing_extensions._SpecialForm", local name has type "typing._SpecialForm")
    """
    from typing_extensions import Protocol
```
However Py3 typing.py
`/var/packages/python3/target/lib/python3.7/typing.py` has 
`class _Protocol(Generic, metaclass=_ProtocolMeta):` at line 1168 has underscore prefix and thus cannot be found and thus installation fails.
whereas Py38 typing.py
`/var/packages/python38/target/lib/python3.8/typing.py` has in line with _compat.py `class Protocol(Generic, metaclass=_ProtocolMeta):` is without underscore prefix in front at line 1026 is found and works for installation.

Here's my log of using installed Python 3.7.11-18
```
2021/09/14 12:52:59	Begin service_postinst
2021/09/14 12:53:00	Traceback (most recent call last):
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/importlib_metadata/_compat.py", line 8, in <module>
2021/09/14 12:53:00	    from typing import Protocol
2021/09/14 12:53:00	ImportError: cannot import name 'Protocol' from 'typing' (/var/packages/python3/target/lib/python3.7/typing.py)
2021/09/14 12:53:00	During handling of the above exception, another exception occurred:
2021/09/14 12:53:00	Traceback (most recent call last):
2021/09/14 12:53:00	  File "/var/packages/python3/target/bin/virtualenv", line 5, in <module>
2021/09/14 12:53:00	    from virtualenv.__main__ import run_with_catch
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/virtualenv/__init__.py", line 3, in <module>
2021/09/14 12:53:00	    from .run import cli_run, session_via_cli
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/virtualenv/run/__init__.py", line 13, in <module>
2021/09/14 12:53:00	    from .plugin.activators import ActivationSelector
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
2021/09/14 12:53:00	    from .base import ComponentBuilder
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/virtualenv/run/plugin/base.py", line 9, in <module>
2021/09/14 12:53:00	    from importlib_metadata import entry_points
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 17, in <module>
2021/09/14 12:53:00	    from . import _adapters, _meta
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/importlib_metadata/_meta.py", line 1, in <module>
2021/09/14 12:53:00	    from ._compat import Protocol
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/importlib_metadata/_compat.py", line 15, in <module>
2021/09/14 12:53:00	    from typing_extensions import Protocol  # type: ignore
2021/09/14 12:53:00	ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by BKSteve** [comment]
Is this even the right place to raise such an issue?
[https://github.com/SynoCommunity/spksrc/pull/4604](https://github.com/SynoCommunity/spksrc/pull/4604)

**Comment by BenjV** [comment]
You should ask this upstream at the developers of importlib_metadata

**Comment by BKSteve** [comment]
What's really interesting in my logs is that 
typing_extensions is loaded with the Old 20210329-1 SickChill package on 2021-07-30
```
2021/07/30 19:13:44	Begin service_postinst
created virtual environment CPython3.7.10.final.0-64 in 2254ms
  creator CPython3Posix(dest=/volume1/@appstore/sickchill/env, clear=False, global=True)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Looking in links: /volume1/@appstore/sickchill/share/wheelhouse
...
Processing /volume1/@appstore/sickchill/share/wheelhouse/typing_extensions-3.7.4.3-py3-none-any.whl
```
But the package now does not get loaded after switching back from 20210729-2 version.

**Comment by BKSteve** [comment]
resolution is to 
`/var/packages/python3/target/bin/pip install -U typing-extensions`
then install

**Comment by BenjV** [comment]
If you do that you remove that module from the python3 release and any other application that uses that module will fail.
The whole purpose of using an virtual environment is to prevent this.

**Comment by BKSteve** [comment]
typing-extensions wasn't there in Py3.
The last time I installed SC 20210329-1 July 30, it was loaded and existed as a wheel per the log but now it doesn't load after reverting from 20210729-2 in SynoCommunity to 20210329-1 also at the same time there have been updates to Py3 so wondering how this older version now no longer loads?

I don't know where you get the idea I am removing typing-extensions from Py3. The importlib_metadata _compat.py is the one that calls it in the except part of the try. So I went looking for it. It didn't exist in SickChill wheels like before and it didn't exist in Py3 site-packages. Thus adding it into Py3 gets the 20210329-1 version to load on x64 devices, I haven't asked anybody else to try it because I'm working on getting the Py38 based version of SickChill to load and installed on ARM based architectures.
But yes, I'll be very careful not to remove core parts of other packages.

**Comment by BenjV** [comment]
Sorry is misread the statement.
I thought I saw an pip uninstall command.

Be aware that you now add it to the site-packages of python3 and not to the virtual environment of SickChill.
It should be added tot wheelhouse folder of the SickChill package.

**Comment by BKSteve** [comment]
I was just trying to get the old-1 package to work as it wasn't and it previously had.

Am focusing on Py38 package so waiting for feedback from those with ARM machines after the additions to build depends by hgy59.
