### ISSUE TITLE
iperf CSV timestamp wrong

### ISSUE THREAD

**Issue by thr-4** [SynoCommunity/spksrc#4862]
### Setup
_Package Name:_ SynoCli Monitor Tools
_Package Version:_ 1.1-3

_NAS Model:_ DS218j
_NAS Architecture:_ 
_DSM version:_ 6.2.4-25556

### Expected behavior
Correct timestamp shown when exporting iperf2 results into CSV file

### Actual behavior
Timestamp returned as 1/1/1970 `19700101100000`

### Steps to reproduce
_1._ run iperf2 with CSV output flag, example: `iperf2 -y C -c 192.168.0.xxx`
_2._ output: `19700101100000,192.168.0.xxx,41703,192.168.0.xxx,5001,1,0.0-10.0,1112670268,8872877541`

**Comment by BenjV** [comment]
You should ask this upstream at the developers of iperf2.

**Comment by thr-4** [comment]
> 
> 
> You should ask this upstream at the developers of iperf2.

It does work properly with all other installations of iperf2 though - Debian linux, windows, mac OS. Issue seems to be unique to the package available for Synology.

**Comment by BenjV** [comment]
Same version iperf version?
Did you look at the date settings in the control panel of DSM and the system date of your Nas?

Packages from the SynoCommunity do not change the applications, they are just build from the original source.

**Comment by thr-4** [comment]
> 
> 
> Same version iperf version?

OK, it looks like it's an issue with the 2.1.x branch as a whole. Other distros I am working with are still including 2.0.xx; I have not noticed this.
Thank you for your help.
