### ISSUE TITLE
SynoCli File Tools - mc fails to start on DS414j after upgrading to DSM7

### ISSUE THREAD

**Issue by thebogusman** [SynoCommunity/spksrc#4871]
### Setup
_Package Name:_ SynoCli FileTools
_Package Version:_ 2.3-10

_NAS Model:_ DS414j
_NAS Architecture:_ Comcerto2k
_DSM version:_ 7.0-41890

### Expected behavior
mc works normally

### Actual behavior
mc fails to start with the following error:
```mc: /lib/libc.so.6: version `GLIBC_2.25' not found (required by /var/packages/synocli-file/target/lib/libcrypto.so.1.1)```

### Steps to reproduce
_1._ run `mc` from cli

The error started to appear after upgrading to DSM7.

Similar issues with some other tools provided by this package:
```mg: /lib/libc.so.6: version `GLIBC_2.26' not found (required by mg)```

```lzip: /lib/libstdc++.so.6: no version information available (required by lzip)```
```lzip: relocation error: lzip: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference```
(same with plzip)

```rnm: /lib/libstdc++.so.6: no version information available (required by rnm)```
```rnm: /lib/libstdc++.so.6: no version information available (required by /var/packages/synocli-file/target/lib/libgmpxx.so.4)```
```rnm: relocation error: rnm: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference```

Same issue with other packages from SynoCli * family.

**Comment by BenjV** [comment]
Login to the commandline and give this command:

> /lib/llibc.so.6

This will return information about which GLIBC version available is on your Nas.

**Comment by thebogusman** [comment]
@BenjV 
```GNU C Library (crosstool-NG 1.20.0) stable release version 2.20-2014.11, by Roland McGrath et al.
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.9.3 20150311 (prerelease).
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE```

**Comment by BenjV** [comment]
As you can see Synology put an old libc.so.6 on your Nas.
Version 2.26 is needed and your version is 2.20

**Comment by thebogusman** [comment]
Ok, I see. So any workarounds to get mc working? Or should I wait and hope that newer version of DSM will have libc.so.6  updated?

**Comment by BenjV** [comment]
Not very likely that Synology will upgrade this, otherwise the would have done that in the upgrade to DSM 7.
I don't think that upgrading yourself is an option, but maybe somebody else has an opinion on that?

If you used the SynoCli package on DSM 6, then it should be possible to build a version against your libc.so.6.
At the moment the website of the SynoCommunity has a problem, so I cannot download complete packages, but when it is back I could change the package for DSM 6 to be able to run on DSM 7 without recompiling it.

**Comment by publicarray** [comment]
@thebogusman Thanks for the report.
Once https://github.com/publicarray/spksrc/actions/runs/1257452151#artifacts is build can you try downloading the resulting Artifact, unzip and install the package manually? Please let me know if this fixes the issue. Thanks.

**Comment by publicarray** [comment]
@BenjV Thanks for diagnosing the issue :+1:

**Comment by publicarray** [comment]
Hm, I found an issue with the build system maybe this will fix it? https://nightly.link/publicarray/spksrc/actions/runs/1259786825

Just in case I've also started a build on my machine with the comcerto2k toolchain: https://seby.io/download/synocli-file_comcerto2k-7.0_2.3-10.spk

**Comment by thebogusman** [comment]
@publicarray good news, both versions work perfectly fine! 💪🎉

**Comment by thebogusman** [comment]
@publicarray I can also confirm that the fix also works for SynoCLI Monitor Tools. I've managed to build it from your branch and run iperf3 without any issues :)

**Comment by publicarray** [comment]
@thebogusman Thanks, for the feedback. Did you have the same problem with iperf3 before?

**Comment by thebogusman** [comment]
@publicarray Yes, same or similar issues with iperf2 and iperf3.

**Comment by BenjV** [comment]
For the DS414j (Comcerto2k) the same problem is found for the git package.
