### ISSUE TITLE
Cannot upgrade muut in DSM 7

### ISSUE THREAD

**Issue by L10n3l** [SynoCommunity/spksrc#4872]
### Upgrade Mutt
_Package Name:_ Mutt
_Package Version:_ 2.0.3-6

_NAS Model:_ DS218
_NAS Architecture:_ 
_DSM version:_ DSM 7.0-41890

### Expected behavior
Trying to repare mutt installation from DSM 6 Tto DSM 7

### Actual behavior
Cannot upgrade muut with DSM7
File format not valid (format de fichier non valide)

### Steps to reproduce
_1._ connect to DSM (muut should be instllated first in DMS 6)
_2._ go to the software center and click repare on Mutt

#### Package log
_Installer log: find logfile `/var/log/packages/{package}.log`, for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` and protocol in Package Center.
You find service log and other log files in `/var/packages/{package}/target/var`.
_
```
2021/09/20 08:17:29	(system) trigger mutt 2.0.3-6 Begin start-stop-status stop
2021/09/20 08:17:29	(system) trigger mutt 2.0.3-6 End start-stop-status stop ret=[0]
2021/09/20 08:20:59	(system) trigger mutt 2.0.3-6 Begin start-stop-status start
2021/09/20 08:20:59	(system) trigger mutt 2.0.3-6 End start-stop-status start ret=[0]
2021/09/20 08:34:51	(system) trigger mutt 2.0.3-6 Begin start-stop-status stop
2021/09/20 08:34:51	(system) trigger mutt 2.0.3-6 End start-stop-status stop ret=[0]
2021/09/20 08:39:24	(system) trigger mutt 2.0.3-6 Begin start-stop-status stop
2021/09/20 08:39:24	(system) trigger mutt 2.0.3-6 End start-stop-status stop ret=[0]

```

**Comment by BenjV** [comment]
for status see:https://github.com/SynoCommunity/spksrc/issues/4524

**Comment by L10n3l** [comment]
thx
