### ISSUE TITLE
[SynoCli File Tools] rg throws "error while loading shared libraries: libpcre2-8.so.0"

### ISSUE THREAD

**Issue by screendriver** [SynoCommunity/spksrc#4878]
### Setup
_Package Name:_ SynoCli File Tools
_Package Version:_ v2.3-10

_NAS Model:_ DS920+
_NAS Architecture:_ INTEL Celeron J4125
_DSM version:_ DSM 7.0-41890

### Expected behavior
`rg` should search for a regex pattern

### Actual behavior

```sh
rg: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
```

### Steps to reproduce
_1._ just type `$ rg`

**Comment by publicarray** [comment]
I can reproduce, It's Interesting because when I build it locally (diyspk/) the lib is statically linked.

**Comment by publicarray** [comment]
If you want you can download the build with the fix from the CI here: [packages.zip](https://nightly.link/publicarray/spksrc/actions/runs/1257302819/packages.zip)
