### ISSUE TITLE
installing minio on DSM 7 from repo fails

### ISSUE THREAD

**Issue by fgma** [SynoCommunity/spksrc#4881]
### Setup
_Package Name:_ minio
_Package Version:_  v2021.09.18-9 

_NAS Model:_ 216j
_NAS Architecture:_ armada-38x 
_DSM version:_ 7

### Expected behavior
Minio should install as expected.

### Actual behavior
Package gets downloaded but before the installation stops with: "Invalid file format Please contact the package developer."

My self-compiled package can be manually installed without any problems.

### Steps to reproduce
_1._ Update DSM to 7
_2._ Add synocommunity repo
_3._ Install minio from repository

**Comment by hgy59** [comment]
After publishing it takes up to 48 hours until the repo delivers the updated package.
To ensure the published package is installable you can manually download from https://synocommunity.com/package/minio or wait another 24 h.

**Comment by fgma** [comment]
Tested it again. Today installation finally works!
