### ISSUE TITLE
patches for native and toolchain packages do not work

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#4884]
@th0ma7 to get patches work for native and toolchain Makefiles we need to fix `spksrc.patch.mk`.
- the patches do not work when `ARCH` or `TCVERSION` is not defined (as for noarch packages, we can call `make` without any parameter in native and toolchain folders).
- to get toolchain patches working, the `fix` target must be applied before the `patch` target in spksrc.tc.mk. Otherwise the source files are readonly and patches cannot be applied.
- when patching toolchain files, the patch file is not found, as the working folder is not in the toolchain/syno-* folder (this might be an issue with native patches too).

There is currently no toolchain patch file defined, but it will be required for #4852.

There are two native packages with patches: `native/nasm/` and `native/mono` 
Those patches are currently not applied (at least by `make` in the related native folder).

**Comment by hgy59** [comment]
it might be easy to solve this issue by creating `spksrc.native-patch.mk` and `spksrc.toolchain-patch.mk` files.

**Comment by th0ma7** [comment]
I first thought a `native-patch` or similar would be needed but I may have found something.  Want to give that a try (I haven't had coffee yet so this may well break something else, but lgtm)?  PR #4885
