### ISSUE TITLE
Allow parallel make execution

### ISSUE THREAD

**Issue by Diaoul** [SynoCommunity/spksrc#49]
This is possible with the make -j option.
I tried but it fails at some points of the code because not all targets can be parallelized.

I see two solutions to that:
- Build our own parallel stuff (by adding PARALLEL=1 to local.mk for example) and make the code parallel ourselves in the code
- Use the builtin -j option that comes with `make` but we have to specify .NOTPARALLEL where needed

I recommend the second option, that's the "standard" way.
##

**Comment by ymartin59** [comment]
Even if "make" sequence for each package/architecture cannot be parallelized easily, I find it possible/interesting to parallelize "per architecture" build to speed up at least `make all-supported`.

**Comment by Dr-Bean** [comment]
Parallel make is supported with all rules (iirc anyway), _except_ `make all-supported` ;) Unless you know a way to check if `REQ_KERNEL` is set in dependencies and filtering out a subset of arches based off of that without a loop.

**Comment by Safihre** [comment]
Seems not to be super applicable anymore. We tried in #3171, but it doesn't work well for all packages.
