### ISSUE TITLE
where  can I get the information about .pat file packing tools?

### ISSUE THREAD

**Issue by 380121850** [SynoCommunity/spksrc#4900]
update failed ,when repacking .pat file with tar;

**Comment by BenjV** [comment]
It is Synology proprietary format so that info is not available.

**Comment by 380121850** [comment]
its format is tar,which file command"file *.pat"; 
needed something like signature inside?  i just want to make some modify on the pat;

**Comment by 380121850** [comment]
> tar itself is not proprietary but the content.. As far as I know only Synology knows the answer to your question.

Thank you for your response！
