### ISSUE TITLE
can't find DSM7 kernel 

### ISSUE THREAD

**Issue by beyondkmp** [SynoCommunity/spksrc#4904]
There are only syno-geminilake-6.2.2 and syno-geminilake-6.2.3 in kernel dir. I can't find syno-geminilake-7.0. And I want to compile kernel module in 7.0.

**Comment by beyondkmp** [comment]
@BenjV  The toolchain is DSM7. But in https://github.com/SynoCommunity/spksrc/tree/master/kernel, there is no 7.0 version.

**Comment by timrettop** [comment]
Isn't this the kernel source code? 
https://archive.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source/7.0-41890

e.g. https://global.download.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source/7.0-41890/v1000/linux-4.4.x.txz

**Comment by th0ma7** [comment]
@timrettop yes it is, you have to look for `linux-<version>-.x.txz` matching your NAS architecture.  It depends which hardware you're using.  On top you mentionned Intel `geminilake` but the source file you refer to is for AMD `v1000`.  You can find a complete list of archs per NAS model here: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model

Lastly, the spksrc framework now provides kernel module functionality which could help you depending of what you are trying to achieve.  Documentation is still a bit rough but bits are starting to be made available here: https://github.com/SynoCommunity/spksrc/wiki/FAQ-SynocliKernel-(usbserial,-linuxtv)

Have a look at `synokernel-cdrom` which provides a "basic" package containing cdrom kernel modules.

**Comment by th0ma7** [comment]
Please open-up a new issue if this problem still exists, closing this one due to lack of activity.
