### ISSUE TITLE
OpenJDK 11 broken on armada38x

### ISSUE THREAD

**Issue by albrechtf** [SynoCommunity/spksrc#4912]
### Setup
_Package Name:_ Java 11 OpenJDK
_Package Version:_ 11.0.12.7-1

_NAS Model:_ DS216j
_NAS Architecture:_ ARMv7L / armada38x
_DSM version:_ 6.2.4

### Expected behavior
The Java Runtime works and does not break Java software.

### Actual behavior
The Java Runtime breaks Java software because of (I think so) some wrong compile options for this platform. It has flaws when performing operations on long`volatile` values.

### Steps to reproduce
_1._ Make sure that you have the correct Java on PATH (on the NAS) by executing `java -version`. Should output `openjdk version "11.0.12" 2021-07-20 LTS` as first line.
_2._ Create a test file on the NAS, `Test.java`, with the following contents:
```java
public class Test {

  private static volatile long x;

  public static void main(String[] args) {
	x = 10;
	long test = x - 11;
	System.out.println(test);
  }
}
```
_3._ Compile the class: `javac Test.java`
_4._ Run the class: `java Test`
_5._ Expected output: `-1`. Actual output (on my NAS): `8529707040688282461`

This is not academic; it breaks e.g. Java's `ScheduledThreadPoolExecutor`, which is e.g. used by openHAB, so openHAB stalls on startup (yeah, guess how many hours it took me to trace this down).

This is not a bug in OS or processor; I manually downloaded another OpenJDK 11 for ARM via adoptopenjdk, which works perfectly fine here and returns the expected output.

**Comment by hgy59** [comment]
@albrechtf  we have now PR #5610 for java 17 OpenJDK.  As I do not have a Diskstation with 32-bit ARM and DSM 7.1 (yet) I cannot verify whether this issue is solved. If you are still looking for java on your DS216j you could test it with the packages generated by github build action.

**Comment by hgy59** [comment]
@albrechtf  we have now PR #5610 for java 17 OpenJDK.  As I do not have a Diskstation with 32-bit ARM and DSM 7.1 (yet) I cannot verify whether this issue is solved. If you are still looking for java on your DS216j you could test it with the packages generated by github build action.

**Comment by arnebjarne** [comment]
> ### Setup
> _Package Name:_ Java 11 OpenJDK _Package Version:_ 11.0.12.7-1
> 
> _NAS Model:_ DS216j _NAS Architecture:_ ARMv7L / armada38x _DSM version:_ 6.2.4
> 
> ### Expected behavior
> The Java Runtime works and does not break Java software.
> 
> ### Actual behavior
> The Java Runtime breaks Java software because of (I think so) some wrong compile options for this platform. It has flaws when performing operations on long`volatile` values.
> 
> ### Steps to reproduce
> _1._ Make sure that you have the correct Java on PATH (on the NAS) by executing `java -version`. Should output `openjdk version "11.0.12" 2021-07-20 LTS` as first line. _2._ Create a test file on the NAS, `Test.java`, with the following contents:
> 
> ```java
> public class Test {
> 
>   private static volatile long x;
> 
>   public static void main(String[] args) {
> 	x = 10;
> 	long test = x - 11;
> 	System.out.println(test);
>   }
> }
> ```
> 
> _3._ Compile the class: `javac Test.java` _4._ Run the class: `java Test` _5._ Expected output: `-1`. Actual output (on my NAS): `8529707040688282461`
> 
> This is not academic; it breaks e.g. Java's `ScheduledThreadPoolExecutor`, which is e.g. used by openHAB, so openHAB stalls on startup (yeah, guess how many hours it took me to trace this down).
> 
> This is not a bug in OS or processor; I manually downloaded another OpenJDK 11 for ARM via adoptopenjdk, which works perfectly fine here and returns the expected output.

https://htmlpreview.github.io/?https://raw.githubusercontent.com/openjdk/jdk/master/doc/building.html#cross-compiling-with-debian-sysroots

It could be that armada38x is not supported in the "server" build, but only supported if Java was compiled as "zero".

**Comment by arnebjarne** [comment]
>OpenJDK 11 for ARM via adoptopenjdk

Could you please try a java --version and post the output so we can see if its a "server", "hotspot" or a "zero" platform build ?

**Comment by albrechtf** [comment]
This is the output of the Java version I installed manually (which works fine on the DS216j):

```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
```

I refrain from installing the "buggy" package again to check that output as well, as this issue is really quite old and I do not know what I potentially destroy in manual settings. But the output clearly shows that "Server" seems not to be the issue.
