### ISSUE TITLE
Home Assistent + Reverse Proxy = Bad Time

### ISSUE THREAD

**Issue by AstraLuma** [SynoCommunity/spksrc#4926]
### Setup
_Package Name:_ Home Assistant Core
_Package Version:_ 2021.8.8-14

_NAS Model:_ RS2421+
_NAS Architecture:_ x86
_DSM version:_ 6.2.4-25556 Update 2

### Expected behavior

Use of the Synology Reverse Proxy (Control Panel > Application Portal > Reverse Proxy) should allow the use of a specific domain (eg, `ha.myhouse.net`) for Home Assistant.

### Actual behavior
Have to dig into YAML to enable it, and then sign in breaks.

### Steps to reproduce
_1._ Install Home Assistant Core
_2._ Configure Reverse Proxy to point to Home Assistant
_3._ Observe the 400 error when trying to access Home Assistant via reverse proxy
_4._ Observe HA log: "A request from a reverse proxy was received from 127.0.0.1, but your HTTP integration is not set-up for reverse proxies"
_5._ Stop Home Assistant
_6._ Follow https://www.home-assistant.io/integrations/http to configure reverse proxies
_7._ Start Home Assistant
_8._ Access Home Assistant via reverse proxy, observe you now get a log in screen
_9._ Try to log in, observe the mysterious error.
_10._ With the developer console open, try to log in again. Observe the new 400 error.

I've reached my yak shave limit for trying to diagnose why the second 400 happens or how to fix it.

**Comment by chickenandpork** [comment]
@AstraLuma can you confirm that this process at https://community.home-assistant.io/t/reverse-proxy-through-synology/274660 works for you ?

**Comment by daxcore** [comment]
I can confirm, reverse proxy is running like described there!
