### ISSUE TITLE
I"'m getting Invalid location" when trying to add the repository

### ISSUE THREAD

**Issue by tdse13** [SynoCommunity/spksrc#4931]
I"'m getting Invalid location" when trying to add the repository. I checked the points of your FAQs:
- No VPN
- Changing the DNS server does not change the result
- nslookup packages.synocommunity.com returns:
Server:		8.8.4.4
Address:	8.8.4.4#53

Non-authoritative answer:
packages.synocommunity.com	canonical name = d.sni.global.fastly.net.
Name:	d.sni.global.fastly.net

**Comment by lemon99ee** [comment]
我在 DSM 6.2.4-25556 Update 7 上遇到同样的错误
