### ISSUE TITLE
Beets

### ISSUE THREAD

**Issue by ucki** [SynoCommunity/spksrc#4934]
### Setup
_Package Name:_ beets
_Package Version:_ 1.4.9-5

_NAS Model:_ DS918+
_NAS Architecture:_ Intel
_DSM version:_ DSM 7.0-41890

### Expected behavior
Beets package is working under the new dsm version

### Actual behavior
unfortunatly beets is not working in the new dsm version. 

### Steps to reproduce
_1._ 
_2._ 
_3._ 

### Setup
_Package Name:_ 
_Package Version:_ 

_NAS Model:_ 
_NAS Architecture:_ 
_DSM version:_ 

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Installer log: find logfile `/var/log/packages/{package}.log`, for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` and protocol in Package Center.
You find service log and other log files in `/var/packages/{package}/target/var`.
_
```
Insert the package log(s) here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by publicarray** [comment]
Done with #4946
