### ISSUE TITLE
Domoticz packagage on synology DS118 not installing

### ISSUE THREAD

**Issue by mhe869** [SynoCommunity/spksrc#4952]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Domoticz
_Package Version: 4.0.10717-8 

_NAS Model: DS118 
_NAS Architecture: 64 Bit
_DSM version: 7.0.1-42218 

### Expected behavior
install package

### Actual behavior
![image](https://user-images.githubusercontent.com/47392933/140060611-7bbcc089-2a76-4dc6-862e-9f10d48e102a.png)

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
unable to reproduce log
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
There is no rtd1296 package for DSM 7 so the package center tries to install the DSM 6 version and fails.

**Comment by hgy59** [comment]
@mhe869 There is  Domoticz v2020.2-10 for DSM 7 available in the synocommunity repository (since 06/20/2021).
You could try to download and install the spk manually under https://synocommunity.com/package/domoticz

**Comment by BenjV** [comment]
Hmm... I am starting to go old I assume, I looked for the rtd1296 and could not find it on the SynoCommunity packages site but now I looked again and saw it is available (also for DSM 7).

Sorry for the confusion I created.

**Comment by publicarray** [comment]
Package version ` 4.0.10717-8` is not available from https://synocommunity.com/package/domoticz where did you get it from?
