### ISSUE TITLE
SynoCliFile enhancement request [busybox]

### ISSUE THREAD

**Issue by Ranbato** [SynoCommunity/spksrc#4960]
I'd like to see ionice added to SynoCliFile package.

It is already part of Sabnzbd, pulled in through busybox but I don't use it and it seems a waste to install it for ionice.

**Comment by hgy59** [comment]
As we already have busybox in `spksrc/synocli-monitor` I propose to add ionice to that package.
Currently synocli-monitor includes only the procutils i.e. lsof, iostat, pgrep, pmap, watch (and pstree on DSM5) but it would be easy to add ionice there.

**Comment by Ranbato** [comment]
That seems fine to me as I believe I have that one installed anyway.
