### ISSUE TITLE
SABnzbd on Synology DSM 7

### ISSUE THREAD

**Issue by niekniek89** [SynoCommunity/spksrc#4962]
Hello,

I have an issue with sabnzbd on my NAS.
it "seems" since the last Python/Sabnzbd upgrade.

it starts a new download, but stops after +-200MB.
the python process then rises immediately to the 50% CPU.

I have already reinstalled Python/Sabnzbd.
also rebooted the nas several times.

I don't see any errors.
after restarting the package it completes 1 full download, then it stops after +-200MB
![sab1](https://user-images.githubusercontent.com/48858098/141067593-695ae28e-aade-4725-acec-3fafcff907f2.png)
![sab2](https://user-images.githubusercontent.com/48858098/141067594-ab7c4859-c0ee-4018-a491-e7b10d61bd3c.png)

**Comment by BenjV** [comment]
This is not a SynoCommunity issue, you should aks it the developers of SabNzbd.
Open an issue here:
https://github.com/sabnzbd/sabnzbd/issues
