### ISSUE TITLE
[Package Request] HomeAssistant Tuya Integration

### ISSUE THREAD

**Issue by Szeryff** [SynoCommunity/spksrc#4969]
Is the Tuya integration in the package the same as:
[https://www.home-assistant.io/integrations/tuya/](https://www.home-assistant.io/integrations/tuya/)

Integration configuration in HA looks different (no API key required) and also files in components/Tuya are different than in:
[https://github.com/home-assistant/core/tree/dev/homeassistant/components/tuya](https://github.com/home-assistant/core/tree/dev/homeassistant/components/tuya)

What integration is this and can it be updated to this one?

**Comment by hgy59** [comment]
Tuya integration will come with homeassistant 2021.10.x.
Before we can create further homeassistant updates, we need to update cross/cryptography to v3.4 that needs python setuptools_rust (i.e. build wheels with rust @th0ma7).

**Comment by hgy59** [comment]
And there is another issuer with homeassistant.
As Python 3.8 is deprecated and not all homeassistant integrations are ready for Python 3.10 they recommend Python 3.9 that we skipped in synocommunity.
So do not expect a new homeassistant package version before 2022.1.

**Comment by th0ma7** [comment]
> we need to update cross/cryptography to v3.4 that needs python setuptools_rust (i.e. build wheels with rust @th0ma7).

I am willing to revisit that but I need to first close other active PR (including python310 & spk-var) before taking a stab at it.

**Comment by hgy59** [comment]
@th0ma7 yea, don't hurry, will not need it before end of January 2022...
I know we have a lot to cleanup first.

**Comment by v120fr** [comment]
(I'm interesting tuya for : Garage Door Opener, Release 2021.11 ).
So for the next version HA on synology, which version 2021.10.x or 2021.11.x ? or more 2022.x ?
