### ISSUE TITLE
ps3netsrv not installing, "Invalid file format"

### ISSUE THREAD

**Issue by the0remora** [SynoCommunity/spksrc#4979]
### Setup
_Package Name:_ ps3netsrv
_Package Version:_ 1.47.26-6

_NAS Model:_ DS416j
_NAS Architecture:_ MARVELL Armada 388 88F6828
_DSM version:_ DSM 7.0.1-42218

### Expected behavior
ps3netsrv should install. Then run

### Actual behavior
After Clicking install it attempts to download then displays a popup with "Invalid file format. Please contact the package developer."

### Steps to reproduce
_1._ Open Package Center.
_2._ Search for ps3.
_3._ Click on ps3netsrv.
_4._ Click on Install

#### Package log
_Installer log: find logfile `/var/log/packages/{package}.log`, for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` and protocol in Package Center.
You find service log and other log files in `/var/packages/{package}/target/var`.
_
```
Insert the package log(s) here
```
`/var/log/packages/{package}.log`
This log dates back to October before I updated to DSM 7
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```
'/var/log/synopkg.log'
2021/11/26 01:04:02 install synocli-net 2.0-11 successfully
2021/11/26 01:05:21 download ps3netsrv https://packages.synocommunity.com/ps3netsrv/6/ps3netsrv.v6.f15047%5Barmada370-armada375-armada38x-alpine-alpine4k-armadaxp-comcerto2k-monaco%5D.spk?arch=armada38x&build=42218 Begin download
2021/11/26 01:05:21 download ps3netsrv https://packages.synocommunity.com/ps3netsrv/6/ps3netsrv.v6.f15047%5Barmada370-armada375-armada38x-alpine-alpine4k-armadaxp-comcerto2k-monaco%5D.spk?arch=armada38x&build=42218 Begin download

No other logs exist or hold relative information (var/log/messages)

**Comment by hgy59** [comment]
As you can see in #4524, ps3netsrv ist not yet available for DSM7.

**Comment by hgy59** [comment]
@the0remora you can use the packages built by github build action of #4984 

download the artefacts of https://github.com/SynoCommunity/spksrc/actions/runs/1513588120 unzip packages.zip and install the spk manually in the package center of your diskstation (for DS416j use `ps3netsrv_armv7-7.0_1.47.37-7.spk`

**Comment by the0remora** [comment]
Working
