### ISSUE TITLE
pyhon wheel not a supported on this platform - armv5tel

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#4980]
### Setup
_Package Name:_ python310
_Package Version:_ not released yet

_NAS Model:_ synology_88f6282_213air
_NAS Architecture:_ armv5tel
_DSM version:_ 

### Issue
With the recent changes to how the wheel name are being managed it was expected that using `uname -m` as identifier in the naming was solving issues for `armv5tel`, `armv7` and `armv7l` but it seems original testing feedbacks wasn't sufficient to confirm that this change was working ok.

Issue currently being discussed here: https://github.com/SickChill/SickChill/issues/7672
Raised here in particular: https://github.com/SickChill/SickChill/issues/7672#issuecomment-980395077

Current wheel name example after being copied + renamed to staging:
```
$ find work*/staging/share/wheelhouse/lxml-*.whl
work-88f6281-6.1/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-arm_marvell_linux_armv5tel.whl
work-aarch64-6.1/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-aarch64_unknown_linux_aarch64.whl
work-aarch64-7.0/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-aarch64_unknown_linux_aarch64.whl
work-armv7-6.1/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-arm_unknown_linux_armv7.whl
work-armv7-7.0/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-arm_unknown_linux_armv7.whl
work-evansport-6.1/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-i686_pc_linux_i686.whl
work-hi3535-6.1/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-arm_cortexa9_linux_armv7l.whl
work-kvmx64-6.1/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-x86_64_pc_linux_x86_64.whl
work-kvmx64-7.0/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-x86_64_pc_linux_x86_64.whl
work-qoriq-6.1/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-powerpc_e500v2_linux_ppc.whl
work-x64-6.1/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-x86_64_pc_linux_x86_64.whl
work-x64-7.0/staging/share/wheelhouse/lxml-4.6.3-cp310-cp310-x86_64_pc_linux_x86_64.whl
```

python wheel naming convention: https://www.python.org/dev/peps/pep-0491/#file-name-convention

**Comment by th0ma7** [comment]
I'm also in the process of purchasing an old armv7 and armv5tel so I can locally test things up but this will take a few cycles before I receive my <s>new</s> old gear.

**Comment by hgy59** [comment]
@th0ma7 just built python310 (current master) for aarch64-6.1 and got similar error:

from /var/log/packages/python310.log:
```
2021/11/27 14:13:13     ERROR: MarkupSafe-2.0.1-cp310-cp310-aarch64_unknown_linux_aarch64.whl is not a supported wheel on this platform.
```

the command `python3 -m pip debug --version` gives a list of 151 compatible tags.
The list does not contain `cp310-cp310-aarch64_unknown_linux_aarch64` but has
```
cp310-cp310-manylinux_2_20_aarch64
cp310-cp310-manylinux_2_19_aarch64
cp310-cp310-manylinux_2_18_aarch64
cp310-cp310-manylinux_2_17_aarch64
cp310-cp310-manylinux2014_aarch64
cp310-cp310-linux_aarch64
cp310-abi3-manylinux_2_20_aarch64
cp310-abi3-manylinux_2_19_aarch64
cp310-abi3-manylinux_2_18_aarch64
cp310-abi3-manylinux_2_17_aarch64
p310-abi3-manylinux2014_aarch64
cp310-none-linux_aarch64
```

So I suppose we must fix the names of cross compiled wheels for Python 3.10 (remove `aarch64_unknown_` in the wheels name?).

**Comment by hgy59** [comment]
I successfully installed manually MarkupSave and cffi after removing `aarch64_unknown_` from the whl file name.

**Comment by th0ma7** [comment]
@hgy59 woot!  great news!
So if I get this right, for instance the following `lxml-4.6.3-cp310-cp310-aarch64_unknown_linux_aarch64.whl` would now be:
* `lxml-4.6.3-cp310-cp310-linux_aarch64.whl`

With this in mind, `lxml-4.6.3-cp310-cp310-arm_marvell_linux_armv5tel.whl` would in theory become:
* `lxml-4.6.3-cp310-cp310-linux_armv5tel.whl`

If that's the case then this should be really easy to solve as the post-install code for all wheels (cp + rename) now sits under `spksrc.wheel-env.mk` (perhaps that could be renamed to `spksrc.wheel-functions.mk` and leave the `env` alone).

I'll draft a PR later today or tomorrow.
