### ISSUE TITLE
[Request] GUI for mkvtoolnix

### ISSUE THREAD

**Issue by mesquitafmr** [SynoCommunity/spksrc#4991]
Hello everyone and @cytec ,

Is it possible to have a GUI for mkvtoolnix? I believe the docker option has the GUI accessible through the web https://hub.docker.com/r/jlesage/mkvtoolnix (unfortunately a NAS with Docker support is way too expensive in my country)

The GUI docs from the developer are here https://mkvtoolnix.download/doc/mkvtoolnix-gui.html

Me and some folks aren't that good with code to access and do commands to the NAS via SSH and the GUI would be great.

Thanks in advance for the wonderful work you guys do here. My DS218 is great because of you all.

**Comment by publicarray** [comment]
Hi, unfortunately the GUI isn't a web gui but uses the QT framework. So AFAIK it requires X11
