### ISSUE TITLE
[Package Request] SynoCli xxxxx add extra commands

### ISSUE THREAD

**Issue by B3rt** [SynoCommunity/spksrc#4999]
Please add to one of the SynoCli tools the following commands or create a new SynoCli tool for it:
 
- telnet
- whois
- dig

**Comment by hgy59** [comment]
These tools match for synocli-net.
@B3rt I suppose your request is for telnet client only (and not for the daemon telnetd).

**Comment by B3rt** [comment]
Yes a telnet client.. 
So you can telnet from the cli (commandline) to an other device. Mostly used to check if ports are open and responding on other devices.

The binaries are already in the optware of dsm 6 and work also on dsm 7, but sadly you cannot install optware anymore on DSM7.....
So if these kind of commands would be available in the SynoCli tools that would be great!
