### ISSUE TITLE
Node.js V16

### ISSUE THREAD

**Issue by Leavoh** [SynoCommunity/spksrc#5013]
* Name: Ivo 't Hart (Livo)
* Description: https://nodejs.org/en/about/
* Website: https://nodejs.org
* Software documentation: https://nodejs.org/en/docs/
* Build/Installation documentation: https://nodejs.org/dist/latest-v16.x/docs/api/synopsis.html
* Source code:  https://nodejs.org/dist/v16.13.1/node-v16.13.1.tar.gz
* License: https://github.com/nodejs/node/blob/master/LICENSE

**Comment by BenjV** [comment]
Node.js is maintained by Synology but their latest release is node.js V14.
You should ask Synology via a support ticket for Node.js V16

**Comment by Leavoh** [comment]
yeah I already did that, multiple times over the course of months.. I heard you guys make custom packages?

**Comment by hgy59** [comment]
we already have a node.js package in spksrc/spk/nodejs/ but is is outdated (10.15.3) and not published anymore.
I updated this some time ago to node.js v14, but never created a pull request, as synology provides node.js v14.

I am now trying to update to v16.
- WARNING: C++ compiler (CXX=/spksrc/toolchain/syno-x64-7.0/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-g++, 7.3.0) too old, need g++ 8.3.0 or clang++ 8.0.0
- DSM 6 toolchains have too old compiler (g++ <= 4.9.3) to build node v16
- g++ compiler of DSM 7 toolchains are 7.3.0 and too old regarding the requirements, but it seems that compilation does not fail (still compiling)
- compilation of node.js needs a lot of time (~ 2 hours on my 2 core i5 for x64 arch)

**Comment by Leavoh** [comment]
Alright, thank you, looking out for an update :)

**Comment by hgy59** [comment]
finally the compilation needed 3 h 20 min, but I have to adjust the configure step. So maybe tomorrow I will push the branch.

**Comment by Leavoh** [comment]
Alright no worries! Take your time :), Am looking forward to it!

**Comment by hgy59** [comment]
@Leavoh you can manually download the packages of the github build action in #5037 (for Diskstation with ARM64 CPU you have to wait for a successful build, hopefully fixed with b842f59a55966ecdb44d4194300a7b68883ed582).

**Comment by Leavoh** [comment]
Thank you so much, Tested it and it worked!

**Comment by Leavoh** [comment]
@hgy59, if you have a donate link, I'd like to offer a few dollars!

**Comment by hgy59** [comment]
> @hgy59, if you have a donate link, I'd like to offer a few dollars!

Thanks, I don't have a personal donate link, but you can sponsor the synocommunity project by one of the given link on the github page. We are always thankful for donations to pay at least the synocommunity repo hosting.
