### ISSUE TITLE
Broken link to pkg for mono 5.8 armada370 arch

### ISSUE THREAD

**Issue by piejanssens** [SynoCommunity/spksrc#5024]
See https://synocommunity.com/package/mono
5.8 armada370 points to this broken link: https://packages.synocommunity.com/mono/11/mono.v11.f15047%5Barmada370%5D.spk

**Comment by piejanssens** [comment]
@hgy59

**Comment by hgy59** [comment]
probably I did somthing wrong when cleaning up outdated versions of mono (as we had no space left on the server).
so I will have to rebuild and publish mono 5.8 

@publicarray are the files like `mono.v11.f15047%5Barmada370%5D.spk` gone on the server?

**Comment by publicarray** [comment]
Yea @hgy59 the file is indeed missing. I tried to compile from 8b01fbbe559094679d7ea48c37b8e8acbdb22d03 but the toolchains had a different name/path

**Comment by hgy59** [comment]
@publicarray I have a label `mono_5-8` on my repo that I will use to rebuild the packages.
And I will use generic archs, so the number of spk files will be less than before...

**Comment by publicarray** [comment]
Thanks!

**Comment by hgy59** [comment]
@piejanssens I have uploaded packages for DSM 6.x for generic x86_64, ARMv7 and aarch64 (armv8)  archs.
The link for your model is https://packages.synocommunity.com/mono/11/mono.v11.f15047%5Balpine-alpine4k-armada370-armada375-armada38x-armadaxp-comcerto2k-monaco%5D.spk

Unfortunatley the toolchains for ARMv5 (88f6281-6.1), ARMv7L (hi3535-6.1) and for DSM 5.x did not work.

**Comment by hgy59** [comment]
@piejanssens I have updated mono 5.8 again (uploads from yesterday are replaced).

As I am currently working on adjustments to build packages for DSM 5.2 again, i have rebuilt the Mono 5.8 with current spksrc environment. With this the ARMv5 and ARMv7L packages are build successfully.

Improvements
- avoid build of static libraries and mcs docs (reduces the spk files from about 140MB to about 80 MB)

**Comment by hgy59** [comment]
And I have successfully tested mono 5.8 with Radarr Radarr Ver. 0.2.0.1293 on DS-215j (armada370).

**Comment by piejanssens** [comment]
Thanks @hgy59, I was able to install this version.
