### ISSUE TITLE
[Package Request] s3backer

### ISSUE THREAD

**Issue by michael-newsrx** [SynoCommunity/spksrc#5031]
Name: s3backer
Description: FUSE-based single file backing store via Amazon S3
Website: https://github.com/archiecobbs/s3backer
Software documentation: https://github.com/archiecobbs/s3backer/wiki/ManPage
Build/Installation documentation: https://github.com/archiecobbs/s3backer/wiki/Build-and-Install
Source Code: https://github.com/archiecobbs/s3backer/wiki/Downloads
License: https://github.com/archiecobbs/s3backer/blob/master/COPYING

Ideally having the S3 backed file9s) show up as available disks would be nice.

**Comment by hgy59** [comment]
@michael-newsrx are you still looking for s3backer on synology diskstations? Please give feedback in #5032.
