### ISSUE TITLE
Native Teamspeak [Package Rquest]

### ISSUE THREAD

**Issue by aigors** [SynoCommunity/spksrc#5033]
* Name: TeamSpeak server 
* Description: chatting server for gaming 
* Website: https://www.teamspeak.com/
* Software documentation: 
* Build/Installation documentation: inside distribution file 
* Source code:  nope, nopt open source 
* License:https://www.teamspeak.com/en/features/licensing/

**Comment by hgy59** [comment]
This software is not open source, and it is available for x64 archs only.
It's not worth to build an spk for teamspeak.
You can install this package by yourself as provided by teamspeak.

**Comment by aigors** [comment]
> This software is not open source, and it is available for x64 archs only. It's not worth to build an spk for teamspeak. You can install this package by yourself as provided by teamspeak.

Thanks, another question, is there some package where i can look to try to make by myself? 

Happy end of the year!

**Comment by publicarray** [comment]
Why not use mumble or discord?

**Comment by publicarray** [comment]
@aigors Our wiki is our go to place on how to build your own packages: https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO

**Comment by aigors** [comment]
> @aigors Our wiki is our go to place on how to build your own packages: https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO

Hi, thanks, yes i have already read wiki, in this case package is not in source form, so compilation ia a unneeded step.

**Comment by publicarray** [comment]
@aigors Ah the demo package might be what you are looking for than: https://github.com/SynoCommunity/spksrc/tree/master/spk/demoservice

**Comment by publicarray** [comment]
If you need help you can still reply here, but I'm closing this as the software only works on one arch and the one it does work one have docker support anyway: https://hub.docker.com/_/teamspeak/
