### ISSUE TITLE
Debian Chroot for DSM6

### ISSUE THREAD

**Issue by MarcS1975** [SynoCommunity/spksrc#5036]
* Name: Debian Chroot
* Description: used to work for DSM5, needed for phpredis to be installed
* Website: https://synocommunity.com/packages
* Software documentation: 
* Build/Installation documentation: 
* Source code:  
* License:

**Comment by hgy59** [comment]
It is an old issue, that packages with ExtJS integrated configuration UI run on DSM 5 only.

We require either a new solution for the DSM integrated configuration of such packages or migrate to another kind of configuration (as WIP for haproxy in #5020).

As with the chroot packages for debian and gentoo the DSM can be broken, those are for advanced users only (and were removed in the synocommunity repo 4 years ago, until demanded again see #3055).

Probably a guide on "how to manually install debian chroot on DSM 6" helps users like you.

Any help for such a guide is welcome.


PS
As we already have a redis package, probably a phpredis package would solve your issue?

**Comment by MarcS1975** [comment]
Hi. Thanks
The Redis is package works but it does not allow other applications to use
Redis. For example Nextcloud needs phpredis to connect to Redis.
And that can only be installed with Deviam Chroot (at least its the only
way I found on Google).
There is a really good instruction posting but it requires Deviam Chroot.

**Comment by ymartin59** [comment]
@MarcS1975 Setup a chroot is really complex and require root access... meaning that any procedure either written for manual operation or automated as a package is expected to fail/require rework on DSM 7.
I guess your DSM model does not have Docker support.

**Comment by ymartin59** [comment]
By curiosity, @MarcS1975 may you please share your Nextcloud setup instructions on DSM 6?

**Comment by MarcS1975** [comment]
I used Marius instructions.

https://mariushosting.com/how-to-install-nextcloud-on-your-synology-nas/
