### ISSUE TITLE
[Package Request] Update Bazarr v1.0.2

### ISSUE THREAD

**Issue by protectxme** [SynoCommunity/spksrc#5049]
* Name: 
* Description: 
* Website: 
* Software documentation: 
* Build/Installation documentation: 
* Source code:  
* License:

**Comment by hgy59** [comment]
bazarr is already updated to v1.0.2 with  95fe355fbab4426b6e81a937b35a01894a6d2d15
it is only a matter of testing and publishing (@th0ma7)

**Comment by th0ma7** [comment]
indeed, matter of a few days.  Just a matter of merging #5046 fix in before I can publish.

**Comment by th0ma7** [comment]
published: https://synocommunity.com/package/bazarr
