### ISSUE TITLE
DSM 7.0.1-42218: No "Trust Level" setting, and ALL community packages grayed out :(

### ISSUE THREAD

**Issue by MrPeteH** [SynoCommunity/spksrc#5058]
### Setup
_NAS Model:_ 720+
_NAS Architecture:_ Intel 64
_DSM version:_ 7.0.1-42218

### Expected behavior
Docs say configure Synology+others in "Trust Level" on general tab
Then add this as an external source and install.

### Actual behavior
_1._ The General tab doesn't have Trust Level in DSM 7 (https://kb.synology.com/en-global/DSM/help/DSM/PkgManApp/configure?version=7)
_2._ I _can_ add SynoCommunity as a source.
_3._ However, _all such packages_ have non-clickable / grayed out install buttons

**Comment by publicarray** [comment]
You are right DSM7 users can skip step 1.
I followed the instructions using the demo: https://demo.synology.com/en-global/dsm and was able to install a package

> However, all such packages have non-clickable / grayed out install buttons

Do you have a networking problem? Did you try and restart your NAS?

**Comment by publicarray** [comment]
@MrPeteH do you still experience this issue?

**Comment by MrPeteH** [comment]
Sorry... medical issues. I'm back. Will test later tonight :)

**Comment by publicarray** [comment]
@MrPeteH how did it go?
