### ISSUE TITLE
Building on Fedora with Podman - mount directory permission denied

### ISSUE THREAD

**Issue by ohnoohweh** [SynoCommunity/spksrc#5062]
Dear all,

I am using Fedora linux. This uses podman instead of docker. Eventhough you run docker command it redirects to docker under the hood.
Running the command given on https://github.com/SynoCommunity/spksrc\README.md yields in following behavior

`docker run -it -v $(pwd):/spksrc ghcr.io/synocommunity/spksrc /bin/bash`
`root@0d0de41e77a3:/spksrc# ls`
`ls: cannot open directory '.': Permission denied`
`root@0d0de41e77a3:/spksrc#`

It took me a while - however I found a solution that works for me there:
https://stackoverflow.com/questions/62094602/mount-directory-to-container-wont-work-with-podman

so following command line works for me
`docker run -it -v $(pwd):/spksrc:Z ghcr.io/synocommunity/spksrc /bin/bash`
`root@46ce7fdac04c:/spksrc# ls`
`spksrc`
`root@46ce7fdac04c:/spksrc#`

I hope I can reduce the research time for others may facing the same issue.

**Comment by publicarray** [comment]
I use the following:

```
podman run -it --rm --name spksrc --userns keep-id -v "$PWD":/spksrc ghcr.io/synocommunity/spksrc
```

source: https://www.redhat.com/sysadmin/user-flag-rootless-containers

**Comment by ohnoohweh** [comment]
I am not so familiar with GIT. I updated my forked repository. There I do have the boost 1.76 changes as well.
Attempting starting a pull request to update the README.md yields in a pull request taking over both. Any suggestions how to start a pull request for the README.md alone ?

**Comment by publicarray** [comment]
Typically, you create a new branch from master, you add your work to it and make a pull request from your new branch to our main branch. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches#working-with-branches

https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#pull-requests
