### ISSUE TITLE
Support for capabilities

### ISSUE THREAD

**Issue by fgma** [SynoCommunity/spksrc#5074]
I'm currently toying around creating a new package. I need support for capabilities which is new to DSM 7. So far I added a new variable to makefile in spk/package/Makefile:

`SPK_CAPABILITIES = bin/abc123:cap_net_admin,cap_sys_module bin/abc456:cap_net_admin`

Afterwards I tried to add those to the privilege file (see https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/7.0/enu/DSM_Developer_Guide_7_0_Beta.pdf page 78) by updating spksrc.service.mk:

```
ifeq ($(call version_ge, ${TCVERSION}, 7.0),1)
	@jq '."groupname" = "synocommunity"' $@ | sponge $@
else
	@jq '."groupname" = "sc-$(SPK_USER)"' $@ | sponge $@
endif
ifneq ($(strip $(SPK_CAPABILITIES)),)
	@echo "$(SPK_CAPABILITIES)" | tr " " "\n" | tr ":" " " | while read RELPATH CAPABILITIES ; \
	do \
	  jq --arg relpath "${RELPATH}" --arg caps "${CAPABILITIES}" '.tool += [{"relpath":$$relpath,"capabilities":$$caps}]' $@ | sponge $@ ; \
	done
endif
```

I always end up with something like this:

```
{
  "defaults": {
    "run-as": "package"
  },
  "username": "sc-mypackage",
  "groupname": "synocommunity",
  "tool": [
    {
      "relpath": "",
      "capabilities": ""
    },
    {
      "relpath": "",
      "capabilities": ""
    }
  ]
}
```

I expected 

```
{
  "defaults": {
    "run-as": "package"
  },
  "username": "sc-mypackage",
  "groupname": "synocommunity",
  "tool": [
    {
      "relpath": "bin/abc123",
      "capabilities": "cap_net_admin,cap_sys_module"
    },
    {
      "relpath": "bin/abc456",
      "capabilities": "cap_net_admin"
    }
  ]
}
```

I've already added debug output statements which show the variables inside the loop are empty. Can anyone point out my mistake?

**Comment by fgma** [comment]
I finally got it to work. I had to escape variable access inside the scripting part: ${RELPATH} becomes $${RELPATH}.

Now I'm able to build a package using capabilities as described in the DSM developer guide. The problem is DSM will not allow me to install those packages anymore because they "run with root prvileges". Any workaround or is this a dead end?

**Comment by hgy59** [comment]
> I had to escape variable access inside the scripting part: ${RELPATH} becomes $${RELPATH}.

Oh yes, I remember - wasn't this an issue in the minio wizard file `upgrade_uifile.sh`? - not only for variables but for special characters too.

**Comment by fgma** [comment]
Any ideas concerning the privilege/capabilities problem? It is documented but looks like we can't use it.

**Comment by BenjV** [comment]
You should escape this by using quotes otherwise the variable expansion does not function correctly
It should be "${RELPATH}"

And no on DSM 7 it is no longer possible to run scripts as root, the scripts will only run as user.

The capabilities you are referring to are for the tool only, not for the package scripts or the application.
I don't know if that actually works, because if the installation script does only has user privileges, I don't see how it could grant more privileges to a tool.
