### ISSUE TITLE
Update Lidarr to use other TMP directory like Radarr

### ISSUE THREAD

**Issue by bakerboy448** [SynoCommunity/spksrc#5081]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Lidarr

### Package Version

v20210322-7

### Device Model

Agnostic

### Device Architecture

x86_64

### Firmware Version

DSM7

### What happened?

USE_ALTERNATE_TMPDIR = 1 Is required  to be added due to the small /tmp directory causing update and database issues

https://github.com/Lidarr/Lidarr/issues/2583

Radarr Syno fix https://github.com/SynoCommunity/spksrc/commit/5a174ae655388df9bbbf6d9bb19a8f16662a9fcb

Radarr updater issue

https://github.com/SynoCommunity/spksrc/issues/4755
https://github.com/SynoCommunity/spksrc/issues/4621

### Reproduction steps

```bash
Known  issue

```

### Install Log

```log
Known issue
```

**Comment by mreid-tt** [comment]
hey @bakerboy448, I went ahead and created PR https://github.com/SynoCommunity/spksrc/pull/5446 which implements this fix for an alternate TMP directory as it also resolves an issue with in-app updates (https://github.com/SynoCommunity/spksrc/issues/5303). The PR also brings the version of Lidarr up to the latest release (version 1.0.2).

**Comment by hgy59** [comment]
Closed by #5446
