### ISSUE TITLE
Radarr not able to set Download Station

### ISSUE THREAD

**Issue by giospud** [SynoCommunity/spksrc#5083]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Radarr

### Package Version

20210708-15

### Device Model

DS216j

### Device Architecture

ARMv7

### Firmware Version

DSM 7.0.1-42218

### What happened?

I am trying to configure the download client and specifically Download Station and when saving I get the following errors

Unknown exception: Failed to login. Reason: The requested method does not exist
Failed to get the list of torrents: Failed to login. Reason: The requested method does not exist

I am giving administrator login credentials

### Reproduction steps

```bash
I am trying to configure the download client and specifically Download Station and when saving I get the following errors

Unknown exception: Failed to login. Reason: The requested method does not exist
Failed to get the list of torrents: Failed to login. Reason: The requested method does not exist

I am giving administrator login credentials
```

### Install Log

```log
cannot access to the file
```

**Comment by publicarray** [comment]
Can you try without tls/ssl?

**Comment by bakerboy448** [comment]
DownloadStation's upgraded version  (which what's on DSM7) is not supported by Radarr's master branch (v3.2.2) it is only supported in v4 (develop)

**Comment by publicarray** [comment]
Thanks @bakerboy448 :+1:

**Comment by BenjV** [comment]
Synology changed the API of Downloadstation as of version  3.8.16.-3566 so this is not a DSM 7 problem but also occurs on DSM 6.
Radarr is very slow on adapting this because they only fixed this in development and that is a major version release (V4) that takes a long time to get production ready.

**Comment by bakerboy448** [comment]
v4 is stable; this can be closed

**Comment by publicarray** [comment]
Closing as v4 is now available as an update

**Comment by giospud** [comment]
Yes, but it is not available trough 
https://synocommunity.com/package/

**Comment by bakerboy448** [comment]
> Yes, but it is not available trough
> https://synocommunity.com/package/

https://github.com/SynoCommunity/spksrc/issues/5114

Correct.

but the \*Arrs update in-app, so it's not an issue.

the only time SynoCommumity's outdated package becomes an issue is if users upgrade and then uninstall/reinstall  without purging appdata since the v4 database is not compatible with v3
