### ISSUE TITLE
how to update FFmpeg 5.0

### ISSUE THREAD

**Issue by stevenliuit** [SynoCommunity/spksrc#5085]
The official website has been updated with ffmpeg5.0, when will we update it?

**Comment by publicarray** [comment]
@th0ma7 Already answered this in discord: https://discord.com/channels/732558169863225384/732559466721181738/932827652824395806 Thanks for letting us know, but please be patent.

> when will we update it?

Since you say "we"... When you or someone else provides a PR that can be reviewed tested and merged than we pull publish it.

**Comment by publicarray** [comment]
Why do you need v5 so soon anyway?

**Comment by th0ma7** [comment]
There currently is no intent in packaging ffmpeg 5.0 as none of the dependent software are yet compatible to the new version (`tvheadend`, `chromaprint` and `comskip`).  Unless this changes it will take quite some time before packaging a version 5.0 or I may end-up creating a parallel ffmpeg5 package someday.

**Comment by th0ma7** [comment]
packages now available for testing in the artifact icon top-right 
https://github.com/SynoCommunity/spksrc/pull/5620/checks

**Comment by stevenliuit** [comment]
![image](https://user-images.githubusercontent.com/4044994/228487344-e077a31a-36ae-4a25-960f-607057e57909.png)
Already installed, tested without any problems
![image](https://user-images.githubusercontent.com/4044994/228487853-e3c68d5e-23ec-4d24-bd97-9de540b43064.png)
I configured jellyfin's ffmpeg6 video to decode normally
this is play info
![image](https://user-images.githubusercontent.com/4044994/228488066-783a7fb9-9f14-4900-bb4c-e16f288b481b.png)
![image](https://user-images.githubusercontent.com/4044994/228488471-5eb8893b-fa82-4504-9f32-c2bd9f69bee5.png)
An error will be reported in the log that the path cannot be found：
"Could not find a part of the path '/\"/var/packages/ffmpeg6\"'". URL "GET" "/Environment/DirectoryContents".

**Comment by th0ma7** [comment]
Packages are being published now.  It will take between 24-48h for official repository to be updated.

Once available on synocommunity.com please uninstall your local version and reinstall using the package center.

**Comment by nyanmisaka** [comment]
@stevenliuit 

> **Important**
> 6.0 version is NOT fully compatible with Jellyfin 10.8.9, which means Jellyfin 10.8.10 or newer is required.

https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v6.0-1
