### ISSUE TITLE
Python package unable to install: Invalid file format. Please contact the package developer.

### ISSUE THREAD

**Issue by cjil** [SynoCommunity/spksrc#5087]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Python

### Package Version

2.7.18-25

### Device Model

DS920+

### Device Architecture

x86_64

### Firmware Version

7.0.1-42218

### What happened?

Tried to install a few packages including:
* NZBHydra
* Deluge
* Mylar
During the installation, it needed to install the "Python" package. 
The python package failed to install with the error message: Invalid file format. Please contact the package developer.

### Reproduction steps

```bash
1. Click to install the "Python" package from SynoCommunity by Safihre
2. Installation failed with the message: Invalid file format. Please contact the package developer.
```

### Install Log

```log
The package was unable to be installed and therefore the log file is not available.
```

### Service Log

```log
The package was unable to be installed and therefore the log file is not available.
```

### Other Logs

```log
2022/01/19 13:09:02 download python https://packages.synocommunity.com/python/25/python.v25.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=geminilake&build=42218 Begin download
2022/01/19 13:09:03 download python https://packages.synocommunity.com/python/25/python.v25.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=geminilake&build=42218 End download
```

**Comment by BenjV** [comment]
Those packages are not available for DSM 7.

**Comment by hgy59** [comment]
Those packages are about to be migrated to DSM 7 and Python 3.10. You find an overview of the progress in #5043.

We do not plan to support our python 2 package for DSM 7 (except we publish the python2 based ffsync package some day for DSM 7, #3849).

**Comment by BenjV** [comment]
As far as I know needs NzbHydra Python2 and does not run under Python 3
About the others I don't know

**Comment by hgy59** [comment]
Nzbhydra is outdated and not supported anymore.
There is a successor nzbhydra2 available, but this one runs on x64 only and requires Java Runtime. Therefore I propose to use the docker version of nzbhydra2 on synology diskstations.
We will probably never support a nzbhydra nor a nzbhydra2 package.
