### ISSUE TITLE
DSM 6.2 can't see the Community packages anymore

### ISSUE THREAD

**Issue by Yasston** [SynoCommunity/spksrc#5102]
Hello, I seem to have the lost the ability to list all available synocommunity packages, and also I cannot upgrage existing packages anymore (for example I use the 'sslh' package in its 1.19 version, I know there is a new version availbale but the Package Manager never proposes to update the package, neither any other community package). Here is a screenshot of a weird error asking me to check my network and date/hour (which I did and they are fine, I'm using NTP) :
![image](https://user-images.githubusercontent.com/33063733/151058462-fed4ebde-2fbe-41f7-811c-8f913b387cb0.png)

(sorry it's in french)

What steps do you recommend I take to troubleshoot the problem ?

Many thanks in advance

**Comment by hgy59** [comment]
Please try to (re-) add the synocommunity repository. Probably duplicate of #4897.

**Comment by Yasston** [comment]
never mind... it's crazy, I went to Control Panel, Regional parameters, and although Date and Time were fine I clicked on "Update now", without even clicking "Apply" (because nothing was changed). The package manager was instantly fixed and notified me of a few updates available, and then I could see the community packages again...
![image](https://user-images.githubusercontent.com/33063733/151059328-aab34837-4b43-4641-be8f-7375b6260765.png)

**Comment by hgy59** [comment]
@Yasston if the time of your device differs > 5 minutes from the server it's common that an ssl connection cannot be established.

Great you got this solved.

**Comment by Yasston** [comment]
Thank you @hgy59 , it's good to know, but I assure you the time was spot on, I checked before opening this ticket. I think it has maybe something to do with an automatic update of DSM that happened last weekend, I've been having issues with some other packages like Plex since then...

**Comment by Yasston** [comment]
I see you're the maintainer of the Mono package ! I'm using that, thank you very much for it !

**Comment by hgy59** [comment]
@Yasston if you want to see an error message, you could find it in one of the log files in the `/var/log` folder.
- /var/log/messages
- /var/log/synopkg.log

or any other file that was updated before you fixed it.

**Comment by Yasston** [comment]
I'm seeing a lot of these :
![image](https://user-images.githubusercontent.com/33063733/151063120-187432c4-9f97-4173-9221-3c37904b0909.png)

**Comment by Yasston** [comment]
and lo and behold, same error again when I go back to the package manager : something is definitely wrong...
![image](https://user-images.githubusercontent.com/33063733/151063304-f56870cb-0127-4ec8-aa05-a9ec6ef91425.png)

**Comment by Yasston** [comment]
One possible answer : there was one repository that appears to be no longer reachable and seems to have generated all those errors : 
![image](https://user-images.githubusercontent.com/33063733/151064969-329bedca-7d5a-4a97-9b06-b130b21c236b.png)

I wanted to try Emby a few years ago, that particular URL probably was decommissioned recently... What's surprising though is that it was just one entry in the list of third-party repositories, and it appears to have brought down the display for all the other packages when looking at the 'Community' tab in package Manager (cf. first screnshot...). Anyway, I removed that entry from the "Sources", everything seems to be back to normal now
