### ISSUE TITLE
Problem with instalation

### ISSUE THREAD

**Issue by Scoofer4** [SynoCommunity/spksrc#5105]
I tried install package to my synology (v DSM 7.0.1-42218 Update 2 - INTEL Celeron J3455) and each attempt ended with error, something like "Invalid format filr. Contact package developer." Whast wrong, pls? Thanx Roman

![image](https://user-images.githubusercontent.com/82614547/151240703-b762ef40-9a81-441e-8dce-b247c944a125.png)

**Comment by hgy59** [comment]
bicbucstream is not yet released for DSM7
Please read the readme (start page) here in github project.
you find the package states in #4524
