### ISSUE TITLE
Support for environment-only settings for minio

### ISSUE THREAD

**Issue by ananace** [SynoCommunity/spksrc#5107]
The minio package as built from here works quite well for most use-cases, but I've come to the point where I need it to support vhost-style buckets. This can be done in minio by [exporting the right environment variable when starting it](https://docs.min.io/docs/minio-server-configuration-guide.html);
```console
export MINIO_DOMAIN=mydomain.com
minio server /data
```

The package has no way - that I can find - to add such an export though, at least not in any way that won't be overwritten on the next upgrade.

**Comment by hgy59** [comment]
minio service is started with
```
/var/packages/minio/target/bin/minio server --quiet --console-address :9001 --anonymous <path-from-install-wizard>
```

If you want custom environment variables, you can add those to the installer-variables file
```
/var/packages/minio/etc/installer-variables
```

default content of installer-variables file:
```
GROUP=sc-minio
SHARE_PATH=<same-as-WIZARD_DATA_DIRECTORY>
WIZARD_DATA_VOLUME=<volume-selected-in-install-wizard>
WIZARD_DATA_DIRECTORY=<shared-folder-directory-entered-in-install-wizard>
WIZARD_ROOT_USER=<user-entered-in-install-wizard>
WIZARD_ROOT_PASSWORD=<password-entered-in-install-wizard>
```

just add
```
MINIO_DOMAIN=mydomain.com
```

to this file.


unfortunately this file is recreated upon package update and manually added values are lost. (probably you already tried this, as you mentioned the overwriting on package upgrade).

So this is for a temporary workaroud.

A permanent solution would use a custom file in the var folder that is handled the same way as installer-variables before service start.
