### ISSUE TITLE
Update Radarr to v4 & remove armada support

### ISSUE THREAD

**Issue by bakerboy448** [SynoCommunity/spksrc#5114]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Radarr

### Package Version

agnostic

### Device Model

agnostic

### Device Architecture

x86_64

### Firmware Version

agnostic

### What happened?

Radarr v4 is now stable. Thus if users attempt to install the current package (i.e. roll back to v3) after updating then their installation will no longer function.

### Reproduction steps

```bash
N/A
```

### Install Log

```log
N/A
```

### Service Log

```log
N/A
```

### Other Logs

```log
N/A
```

**Comment by FreekVR** [comment]
Would love to see it, as it also seems the built-in update to v4 isn't working as per https://github.com/SynoCommunity/spksrc/issues/4621#issuecomment-1014425556

At least on my DS215J running DSM 6

**Comment by bakerboy448** [comment]
> Would love to see it, as it also seems the built-in update to v4 isn't working as per https://github.com/SynoCommunity/spksrc/issues/4621#issuecomment-1014425556
> 
> 
> 
> At least on my DS215J running DSM 6

The built in updater works.

The referenced issued never had any logs provided to indicate the issue so presumably OP did something or has some unique configuration that causes the updater to fail.

**Comment by permster** [comment]
The update issue mentioned in #4621 is specific to DSM6.  I've tried the update on two DS218j models and they both have the same issue.  I also tested the update to 4.0.4.5922 on DSM7 using a DS218j and a DS220j and it works fine.

So the armada architecture isn't supported anymore?  When did that happen?  I've been running Radarr for years on DS218j models with no problems.  If that's true they should put a model check into the package itself with a warning.

**Comment by bakerboy448** [comment]
Armada is not supported due to it having odd .net incompatibles.

This was known with v3 switching to .net

**Comment by Casuallynoted** [comment]
I'm unable to update Radarr on my DS918+. It's running the latest version of the package (according to Package Center) and is on version 3.0.2.4552. I was asking on Radarr's support discord channel and they said it should be a more recent version, but there's no update available.

**Comment by ta264** [comment]
@FreekVR can you come by the Radarr discord and we can try to debug the upgrade?  I fear something is up with .net 6 on your hardware, need to dig into exactly what.  https://radarr.video/discord

**Comment by ta264** [comment]
> The update issue mentioned in #4621 is specific to DSM6. I've tried the update on two DS218j models and they both have the same issue. I also tested the update to 4.0.4.5922 on DSM7 using a DS218j and a DS220j and it works fine.
> 
> So the armada architecture isn't supported anymore? When did that happen? I've been running Radarr for years on DS218j models with no problems. If that's true they should put a model check into the package itself with a warning.

Just for the record, that Nas should be fine, @bakerboy448 is extrapolating armada too far. Come by the radarr discord if you want to help get it working again.

**Comment by mreid-tt** [comment]
@bakerboy448, a new version of Radarr (v20230215-19) has been [published](https://synocommunity.com/package/radarr). This version includes Radarr 4.3.2.6857 and removes support for `armada370` which is not dotnet 6 compatible as well as `armv7` archs running under DSM 6 (as it does not have the required libraries).

I'll be closing this issue in a few days if there is no objection.
