### ISSUE TITLE
syncthing: URGENT, package update deletes user config on DSM7.

### ISSUE THREAD

**Issue by acolomb** [SynoCommunity/spksrc#5116]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

syncthing

### Package Version

v1.19.0-24

### Device Model

DS218j and others

### Device Architecture

AArch64 (ARMv8)

### Firmware Version

DSM 7.0.1

### What happened?

Reported on the [Syncthing forum](https://forum.syncthing.net/t/synocommunity-syncthing-package-update-1-19-0-24-for-synology/17961):

> Just registered to report that the package update above appears to have wiped the Syncthing config (other than the device ID) on my DS920+ running DSM7 and I have to recreate the shares etc. A word of caution to other users.
> 
> Just to clarify, Syncthing’s internal update mechanism had updated the binary to version 1.19.0 without any issue but a subsequent package update published by SynoCommunity and available from within DSM’s package center caused the problem.

PLEASE UNPUBLISH THE v1.19.0 UPDATE ASAP until this has been investigated.

### Reproduction steps

```bash
1. Update from previous SPK version v1.17.0-22 on DSM 7
2. Find the config file missing.
3. Have to recreate everything manually
```

### Install Log

```log
Dunno
```

**Comment by acolomb** [comment]
CC @publicarray you offered testing on DSM 7 recently in #4930.  Could you please help with this one?  I still don't have any device with DSM 7 for testing.

**Comment by acolomb** [comment]
Just tested on DSM 6.2 and the problem definitely does not occur there.

**Comment by acolomb** [comment]
Could this be affected by commit a1187e2b3c04c2d064399c82af7432bf3f8c8462?

**Comment by hgy59** [comment]
> Could this be affected by commit [a1187e2](https://github.com/SynoCommunity/spksrc/commit/a1187e2b3c04c2d064399c82af7432bf3f8c8462)?

No this can not be, it was only required to build the arch-armv7-1.2 (SRM) packages. Other published packages were built without this fix.

**Comment by acolomb** [comment]
I meant could it be that #5115 does already fix this problem?  On DSM7 the privilege file seems more important than on DSM6, so I guessed it might be related.  Otherwise I don't have a clue how Syncthing's config file could have disappeared during the upgrade, but the certificate files in the same directory (`.../var`) survived.

**Comment by hgy59** [comment]
I have now deleted version v1.19.0-24 in the synocommunity package center.
