### ISSUE TITLE
DSM 7 Installer validation

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#5119]
DSM 7 installers created after 15 Dec 2021 delete configurations on upgrade of installed packages created before that date.

This is fixed with #5117.

So every package that meet the following criterias must be updated as soon as possible for DSM 7
- package installs configuration data into the var folder
- any version was published before 15 Dec 2021 and an update package was created after that date

| PACKAGE | published before 2021-12-15 | published after 2021-12-15 | Update required | Update published | COMMENT |
|-----------|------|--------|---------|------------|-------------|
| boxbackup-client |  |  |- |  | not published for DSM7  |
| comskip | 2021-10-25 |  |- |  |   |
| couchpotatoserver |  |  |- |  | not published for DSM7  |
| couchpotatoserver-custom |  |  |- |  | not published for DSM7  |
| dante-sockd |  |  |- |  | not published for DSM7  |
| darkstat |  |  |- |  | not published for DSM7  |
| deluge |  |  |- |  | not published for DSM7  |
| demoservice |  |  |- |  | never published |
| domoticz | 2021-06-20 |  |-|  |   |
| ejabberd | 2021-11-07 |  |-|  |   |
| fengoffice |  |  |- |  | not published for DSM7  |
| ffsync |  |  |- |  | not published for DSM7  |
| fishnet |  |  |- |  | not published for DSM7  |
| gateone |  |  |- |  | not published for DSM7  |
| haproxy |  |  |- |  | not published for DSM7  |
| headphones |  |  |- |  | not published for DSM7  |
| headphones-custom |  |  |- |  | not published for DSM7  |
| horde |  |  |- |  | not published for DSM7  |
| htpcmanager |  |  |- |  | not published for DSM7  |
| icecast |  |  |- |  | not published for DSM7  |
| jackett | 2021-03-15 |  |-|  |   |
| kiwix | 2021-12-06 |  |-|  |  |
| lazylibrarian |  |  |- |  | not published for DSM7  |
| maraschino |  |  |- |  | not published for DSM7  |
| monit |2021-08-31 |  |-|  |  |
| mosquitto |2021-06-20 |  |-|  |  |
| mtproxy |  |  |- |  | not published for DSM7  |
| mutt |2021-10-25 |  |-|  |  |
| mylar |  |  |- |  | not published for DSM7  |
| ntopng |  |  |- |  | not published for DSM7  |
| nzbget | - | 2021-12-21 |- |  | initial DSM 7 package  |
| nzbhydra |  |  |- |  | not published for DSM7  |
| nzbmegasearch |  |  |- |  | not published for DSM7  |
| octoprint |2021-11-06 |  |-|  |  |
| owncloud |  |  |- |  | not published for DSM7  |
| plexivity |  |  |- |  | not published for DSM7  |
| plexpy-custom |  |  |- |  | not published for DSM7  |
| ps3netsrv |2021-12-12 |  |-|  |  |
| rabbitmq |2021-10-15 |  |-|  |  |
| redis |2021-07-10 |  |-|  |  |
| rsnapshot |2022-01-01 |  |-|  |  |
| rutorrent |  |  |- |  | not published for DSM7  |
| sabnzbd | 2021-10-31 | 2022-01-30 | ✔️ | ✔️2022-02-04  |  |
| salt-master |  |  |- |  | not published for DSM7  |
| saltpad |  |  |- |  | not published for DSM7  |
| selfoss |  |  |- |  | not published for DSM7  |
| shairport-sync |  |  |- |  | not published for DSM7  |
| sickbeard-custom |  |  |- |  | not published for DSM7  |
| sickchill |2021-11-17 |  |- |  |   |
| sickrage |  |  |  |  | not published  |
| squidguard |  |  |- |  | not published for DSM7  |
| sslh |2021-07-18 |  |- |  |   |
| stockfish |  |  |- |  | not published for DSM7  |
| syncthing | 2021-06-19  |  |  |✔️2022-02-03 |   |
| transmission |2020-11-01 |  |- |  |   |
| tt-rss |  |  |-|  | not published for DSM7  |
| tvheadend |2021-12-12 |  |- |  |   |
| umurmur |2021-12-04 |  |- |  |   |
| znc |2021-09-26 |2022-01-22 |✔️ |✔️2022-02-04 |   |

**Comment by hgy59** [comment]
The list above tells that the latest updates of `sabnzbd` and `znc` might have overwritten configuration files.

**Comment by hgy59** [comment]
@Safihre didn't you have any issues with overwriting the config.ini file on upgrade the sabnzbd package with the release of #5109?

**Comment by Safihre** [comment]
Yeah exactly! Users have reported exactly that, but just didn't have time to look into it why it happend.

**Comment by hgy59** [comment]
no further action required...
