### ISSUE TITLE
Tvheadend: Package build stops at pngquant with error for DSM 6.2.x

### ISSUE THREAD

**Issue by mmkt1** [SynoCommunity/spksrc#5121]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Tvheadend

### Package Version

latest

### Device Model

DS3615

### Device Architecture

x86_64

### Firmware Version

6.2.3

### What happened?

Hi,
the package building prozess from tvheadend stops with an error from building pngquant for DSM 6.2.2. The parallel build for DSM7 is working for pngquant.
The error for building pgnquant is:
```
/home/kw/Kompilieren/spksrc/toolchain/syno-bromolow-6.2.2/work/x86_64-pc-linux-gnu/bin/../x86_64-pc-linux-gnu/sys-root/lib64/libpthread.so.0: undefined reference to `h_errno@GLIBC_PRIVATE'
/home/kw/Kompilieren/spksrc/toolchain/syno-bromolow-6.2.2/work/x86_64-pc-linux-gnu/bin/../x86_64-pc-linux-gnu/sys-root/lib64/libpthread.so.0: undefined reference to `__libc_dl_error_tsd@GLIBC_PRIVATE'
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:30: pngquant] Fehler 1
make[5]: Verzeichnis „/home/kw/Kompilieren/spksrc/spk/tvheadend/work-bromolow-6.2.2/pngquant-2.17.0“ wird verlassen
make[4]: *** [../../mk/spksrc.compile.mk:44: compile_target] Fehler 2
make[4]: Verzeichnis „/home/kw/Kompilieren/spksrc/cross/pngquant“ wird verlassen
make[3]: *** [../../mk/spksrc.depend.mk:51: depend_target] Fehler 2
make[3]: Verzeichnis „/home/kw/Kompilieren/spksrc/cross/tvheadend“ wird verlassen
make[2]: *** [../../mk/spksrc.depend.mk:51: depend_target] Fehler 2
make[2]: Verzeichnis „/home/kw/Kompilieren/spksrc/spk/tvheadend“ wird verlassen
make[1]: Verzeichnis „/home/kw/Kompilieren/spksrc/spk/tvheadend“ wird verlassen
```
[log.txt](https://github.com/SynoCommunity/spksrc/files/8004929/log.txt)

Maybe something wron with the config.mk which is generated by ./configure (attached as txt)?
[config.txt](https://github.com/SynoCommunity/spksrc/files/8004946/config.txt)

I'm not able to find the reason what is going wrong with it.
I use a Linux Mint Debian Edition OS for building and last building whith success was back in november 01  2021

Hopefully someone can lookt at it and fix it.
Thanks, mmkt1

### Reproduction steps

```bash
1. fresh github checkout
2. Modify Makefile for parallel build of DSM 6.2.2 and DSM 7
2. make setup
3. changing to /spk/tvheadend
4. make arch-bromolow
```

### Install Log

```log
due to packaging error: no log at this point
```

**Comment by mmkt1** [comment]
I've tried it on a virtual Linux Lite machine and there it works...
Must be something specific with my Laptop.

**Comment by th0ma7** [comment]
you have to be using either a docker or lxc image to get things through.
For future use-cases have a look at Setup Development Environment section at the main page https://github.com/SynoCommunity/spksrc

I'm glad it now works, closing.
