### ISSUE TITLE
Syncthing v1.19.0-25 - JS error after update via Package Centre

### ISSUE THREAD

**Issue by surkie7** [SynoCommunity/spksrc#5127]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Syncthing

### Package Version

1.19.0-25

### Device Model

DS720+ NAS

### Device Architecture

x86_64

### Firmware Version

7.0.1-42218 Update 2

### What happened?

After updating to Syncthing v1.19.0-25 via Package Centre, JS errors pop up within 1 - 2 minutes we loading the GUI.

### Reproduction steps

```bash
1. Open Syncthing GUI
2. Wait a 1 - 2 minutes
3. JS error pops up at top of screen: DEV   JS: errors 1  warn 0
4. Sometimes there are 2 or 3 errors
```

### Install Log

```log
Please assist.
```

**Comment by camaz** [comment]
I updated and now the service will not run, how did you resolve?
