### ISSUE TITLE
RADARR SONAR and JACKETT

### ISSUE THREAD

**Issue by giospud** [SynoCommunity/spksrc#5130]
There is any plan to release an update of working RADARR and SONARR and JACKETT for DSM 7.0.1-42218 Update 2  on  MARVELL Armada 385 88F6820 ?

**Comment by BenjV** [comment]
Radarr and Sonarr are using .net for their new release and their software is not compatible with the .net implementatie for ARM processors.
So there will be not a release for their new versions.

**Comment by Casuallynoted** [comment]
> Radarr and Sonarr are using .net for their new release and their software is not compatible with the .net implementatie for ARM processors.
> So there will be not a release for their new versions.

Is this also the case on the DS118? I can't seem to update it either.

**Comment by BenjV** [comment]
Yes the DS118 has a rtd1296 cpu which is also an 32bit ARM cpu

**Comment by hgy59** [comment]
rtd1296 is aarch64 (ARMv8) i.e. 64 bit ARM.

**Comment by Bart368** [comment]
Are there plans for releasing an update for the DS214play?

**Comment by bakerboy448** [comment]
> DS214play

https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model#evansport-x86
https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures#x14-series

No - Your nas is x86 and not supported

**Comment by ta264** [comment]
Yes, there are plans to support x86 in radarr 4.2

**Comment by hgy59** [comment]
> Yes, there are plans to support x86 in radarr 4.2

This will be hard, as MS does not provide .NET 6 for x86 for linux (neigher runtime nor SDK). 
Is the radarr team building .net 6 for x64 from source?

**Comment by ta264** [comment]
Yes we are, and potentially for the older armv7 arches too if I can find some testers

**Comment by ta264** [comment]
PS Radarr x86 support is live, will be added to the other (non-Sonarr) *arr apps soon

**Comment by hgy59** [comment]
> Yes we are, and potentially for the older armv7 arches too if I can find some testers

I have a DS-115j with armada370 if this needs testing.

**Comment by Rel0ne** [comment]
I have a DS214play with evansport x86 processor if needs testing

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/synology-packages  beta servarr packages that may work for some folks

**Comment by bakerboy448** [comment]
x86 support is has also been live and simply requires the synocommunity to update the package to add it
https://github.com/Radarr/Radarr/releases/tag/v4.2.4.6635

**Comment by Rel0ne** [comment]
In my case Sonarr v20210329-19 from SynoCommunity works well on DSM 7.1.1-42962 Update 1 on DS214play and is dependent on Mono which, in my case i run the version 5.20.1.34-18

**Comment by mreid-tt** [comment]
For those who commented requesting [evansport (x86)](https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model#evansport-x86) compatibility for your DS415play or DS214play, I've run a test build for Radarr as an experiment. If you are willing to test it out you can download from the build https://github.com/SynoCommunity/spksrc/actions/runs/3893060275.

Look for the files entitled: [Packages for evansport-6.1](https://github.com/SynoCommunity/spksrc/suites/10308109384/artifacts/506918011) or [Packages for evansport-7.0](https://github.com/SynoCommunity/spksrc/suites/10308109384/artifacts/506918014). Curious if this works for you guys. If so I'll do a few other experiments with other `*arr` packages.

**Comment by Rel0ne** [comment]
Hello, I managed to install the package for DSM version 7.0 on my ds214play with a bit of workaround. 
The provided package gives an error of "invalid file format. please contact package developer". 
I extracted the contents of the zip file and repackaged with the following comand run in the folder containing the extracted zip file: 

tar -cvf radarr.spk *

Now Radarr works on my ds214play 🍾
Thank you!

**Comment by mreid-tt** [comment]
> Hello, I managed to install the package for DSM version 7.0 on my ds214play with a bit of workaround. The provided package gives an error of "invalid file format. please contact package developer". I extracted the contents of the zip file and repackaged with the following comand run in the folder containing the extracted zip file:
> 
> tar -cvf radarr.spk *

Thanks for the feedback. Actually, the zip file `Packages for evansport-7.0.zip` should be extracted first and within it you should have the package with the name `radarr_evansport-7.0_20230111-20.spk`. It is this file you should use for the installation. If this file doesn't work for installing then I'd need to take a closer look at that.

> Now Radarr works on my ds214play 🍾 Thank you!

Nice! Do let me know if there are any problems using the package. Let me know if there are any other packages you'd like me to do test x86 builds for.

**Comment by Rel0ne** [comment]
I extracted the zip on a macbook with "archive utility" which extracts by default the spk as well 😂

I've tried now a different unzip app and extracts the spk as you mentioned above.

I have Sonarr as well running on the ds214play, version 3.x which was working out of synocommunity all the time

**Comment by mreid-tt** [comment]
For those who are also interested in Lidarr with [evansport (x86)](https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model#evansport-x86) compatibility for your DS415play or DS214play, I've run a test build #5563 (like the one [above](https://github.com/SynoCommunity/spksrc/issues/5130#issuecomment-1378736213) for Radarr). If you are willing to test it out you can download from the build artefacts at https://github.com/SynoCommunity/spksrc/actions/runs/3919159589.

Look for the files entitled: [Packages for evansport-6.1](https://github.com/SynoCommunity/spksrc/suites/10371514370/artifacts/511563084) or [Packages for evansport-7.0](https://github.com/SynoCommunity/spksrc/suites/10371514370/artifacts/511563085) depending if you are running DSM6 or DSM7. Unzip the file to get the package (ending in `.spk`) and deploy using that.

**Comment by Rel0ne** [comment]
@mreid-tt can you package the last version of Jackett v 0.20.1171-15 in this way for evansport chipset? current package runs on evansport only with mono v 5.20.1.34-17 and it fails with latest mono version v 5.20.1.34-18.
I noticed that in your packages mono is embedded and there is no dependency to mono which is more flexible and you're not running the risk of newer version on mono coming and not working

**Comment by Rel0ne** [comment]
i did an installation check for lidarr package and it worked on ds214play

**Comment by mreid-tt** [comment]
> @mreid-tt can you package the last version of Jackett v 0.20.1171-15 in this way for evansport chipset? current package runs on evansport only with mono v 5.20.1.34-17 and it fails with latest mono version v 5.20.1.34-18. I noticed that in your packages mono is embedded and there is no dependency to mono which is more flexible and you're not running the risk of newer version on mono coming and not working

I'm not sure that is possible. The `evansport` architecture is x86 and I don't see a binary that looks like it would be x86 in the latest release here: https://github.com/Jackett/Jackett/releases/tag/v0.20.2679. From what I can tell they have binaries for AMDx64, ARM32 and ARM64. These seem to be built with dotNet included (so mono should not be required) but without a build with x86 in the name it doesn't look like it would work on your platform.

**Comment by mreid-tt** [comment]
As some ARMv7 architectures were mentioned on this thread, I've started a new issue for the specific testing of dotNET ***arr** packages with this architecture. If you'd like to help with testing please review the new issue here: https://github.com/SynoCommunity/spksrc/issues/5574

**Comment by mreid-tt** [comment]
@Rel0ne, I've been building a new Jackett version under https://github.com/SynoCommunity/spksrc/pull/5597 and you noted before, these `evansport` CPUs require Mono to run. Perhaps you can share some additional detail on what happens when you try to run Jackett? Maybe open a separate issue so this I can try to troubleshoot this with you?

**Comment by mreid-tt** [comment]
A new version of Radarr (v20230215-19) has been [published](https://synocommunity.com/package/radarr). 

- @giospud, if you are running on DSM 7.1 you should be able to install this on your `Armada38x` CPU
- @Casuallynoted, if you are running on DSM 7.1 you should be able to install this on your `rtd1296` CPU
- @Rel0ne, @Bart368, this version includes the x86 version so you should be able to run on your `Evansport` CPU

**Comment by Rel0ne** [comment]
i installed the new version of Radarr (v20230215-19) on the Evansport CPU directly from the Package center and it worked well

**Comment by Rel0ne** [comment]
> @Rel0ne, I've been building a new Jackett version under #5597 and you noted before, these `evansport` CPUs require Mono to run. Perhaps you can share some additional detail on what happens when you try to run Jackett? Maybe open a separate issue so this I can try to troubleshoot this with you?

Jackett works on my configuration (Evansport CPU) and is dependent on Mono package. If i install latest version of Mono (5.20.1.34-19) then Jackett will fail starting while if I keep Movo version 5.20.1.34-17 all works well

**Comment by mreid-tt** [comment]
> Jackett works on my configuration (Evansport CPU) and is dependent on Mono package. If i install latest version of Mono (5.20.1.34-19) then Jackett will fail starting while if I keep Movo version 5.20.1.34-17 all works well

@Rel0ne, thanks for this feedback. I'd really appreciate it if you can lodge a new issue for this so I can work with you to diagnose and hopefully resolve it.
