### ISSUE TITLE
DSM7 repair required for Radarr, Lidarr on reboot

### ISSUE THREAD

**Issue by mreid-tt** [SynoCommunity/spksrc#5133]
I don't know if you guys are experiencing this but every time I reboot my NAS the *arr packages do not start. When I check in the package manager they all report that they require repair. I repair them and all is okay. While this is not a big deal it does add a bit of overhead which I didn't have under DSM6. Note that other community packages like SABnzbd and Transmission do not require such a repair on reboot.

**Comment by mreid-tt** [comment]
> I face the same issue but it only happens with radarr. Sonarr never does it.

Unfortunately for me all three apps do it. Experienced it after the latest DSM update which came out.

**Comment by mastervol** [comment]
I have the same problem:

DSM 7.0.1-42218 Update 3
Radarr 3.0.2.4552
Synology DS216play

Also update within Radarr does not work.

**Comment by mastervol** [comment]
A manual update to the latest Radarr version works now after installing v20220515-18 from here (Monaco Build) :
https://synocommunity.com/package/radarr

**Comment by synofan** [comment]
Lidarr still has the same tmp directory fault in it. Please build new fixed version on Synocommunity

**Comment by IAfanasov** [comment]
I have the same issue with Radarr, Sonarr, and Prowlarr. 
My version of Radarr is v20220515-18. I tried to install manually the same version - no change. 

NAS: DS218J
DSM: 7.1-42661 Update 4
Sonarr: 20210717-19
Radarr: 20220515-18
Prowlarr: 20220513-2

Pressing repair a few times resolves the issue. It makes it really inconvenient to turn off NAS every night.

**Comment by nieroivan** [comment]
I 'solved' this issue by creating a scheduled task that initialize both Sonarr and Radarr minutes after reboot (via Control Panel). However I'm still facing the issue on SkyHook on Sonarr when I try to search for a new thread. :(
NAS: DS218J
DSM: 7.1-42661 Update 4
Sonarr: 20210329-19
Radarr: 20220515-18

**Comment by mastervol** [comment]
Can you post the commands then we can use them as well.
Thanks.

**Comment by nieroivan** [comment]
On DSM, access Control Pannel > Task Schedulle > Create > Schedulled Task > Service > Task configuration > Set Start Service > select Radarr on the app list > on Schedule, set the time when this task will start.

**Comment by mreid-tt** [comment]
Team, any update on this? I had to do a reboot over the weekend following a power failure and the issue reoccured and my apps weren't running until I remembered to check it today.

Current config:
NAS: DS916+
DSM: 7.1-42661 Update 4
Sonarr: 3.0.9.1549 (20210717-19)
Lidarr: 1.0.1.2578 (20210322-7)
Radarr: 4.2.4.6635 (20220515-18)

**Comment by mreid-tt** [comment]
hey @farfromrefug, I took another look at this issue by simulating a fresh install of the apps in VirtualDSM and found that Sonarr did not exhibit this issue. Lidarr also did not exhibit the issue on a fresh install but at the same time Lidarr cannot update so I cannot test with the latest binaries if I reinstall.

So I then took the following steps on the main NAS:

1. Within `Sonarr > System > Backup` trigger a manual backup
2. Download the new backup to my local machine
3. Within `Package Center > Installed`, uninstall the Sonarr package
4. Select **Erase all of the package data files** for the uninstall
5. Re-install Sonarr from the `Package Center > Community` packages
6. Stop the package (got the error _The DataMapper was unable to load the following field: ‘Languages’_ on the Sonarr webpage)
7. SSH to the NAS and login as admin user
8. Navigate to the app data using `cd /volume1/@appdata`
9. Move the old app data (which should have been erased) using `sudo mv nzbdrone nzbdrone.old`
10. Start the Sonarr package navigate to `Sonarr > System > Updates`
11. Run the update to version 3.0.9.1549
12. Stop the Sonarr package
13. In the SSH session move the new app data using `sudo mv nzbdrone nzbdrone.new`
14. Move the old app data back in place using `sudo mv nzbdrone.old nzbdrone`
15. Start the Sonarr package to confirm all settings were still present

I got the idea for resolving the error in step 6 from the [Sonarr forums](https://forums.sonarr.tv/t/can-not-start-sonarr-after-reinstall-the-datamapper-was-unable-to-load-the-following-field/29799). If you don't get this error when loading the Sonarr website, then the old app data is not present and you can proceed to simply update to the latest version (step 10-11) and restore from your backup.

With this sequence completed, I was able to reboot the NAS and confirmed that the Sonarr package started successfully on boot-up.

I've updated the description of this issue since there is a workaround for Sonarr.

**Comment by farfromrefug** [comment]
@mreid-tt thanks for the deep explanation i ll try it!

**Comment by mreid-tt** [comment]
> @mreid-tt thanks for the deep explanation i ll try it!

You should not need to do anything since you said this does not happen for you with Sonarr. I was just sharing for those who it was happening for.

**Comment by farfromrefug** [comment]
@mreid-tt you are right i did say that :D Thanks for pointing it out :P

**Comment by SWu** [comment]
I fixed it for Radarr by editing the start-stop-status script to use a default timeout of 60 seconds instead of 20. Seems like on reboot Radarr doesn't start up fast enough for the 20 second timeout.

**Comment by wasyl00** [comment]
I have the same issue with Sonarr. Everytime after reboot I need to manually go to package center and press repair to make it work. I tried setting up the scheduled task to start the service every hour but that doesn't seem to work. 

DS215+
DSM 7.1.1-42962 Update 1
Sonarr version 3.0.9.1549
Mono Version 5.20.1.34

**Comment by hgy59** [comment]
> I fixed it for Radarr by editing the start-stop-status script to use a default timeout of 60 seconds instead of 20. Seems like on reboot Radarr doesn't start up fast enough for the 20 second timeout.

@mreid-tt, @wasyl00, did you try to increase the timeout? If this fixes the issue, we could use a timeout of 60 sec for *arr packages.

**Comment by wasyl00** [comment]
> > I fixed it for Radarr by editing the start-stop-status script to use a default timeout of 60 seconds instead of 20. Seems like on reboot Radarr doesn't start up fast enough for the 20 second timeout.
> 
> @mreid-tt, @wasyl00, did you try to increase the timeout? If this fixes the issue, we could use a timeout of 60 sec for *arr packages.
Yep changing to 60 from 20 fixed the problem for me. Many thanks for your help.

**Comment by Jwarburt** [comment]
> editing the start-stop-status script

Please could someone link to instructions on how to do this?

**Comment by mreid-tt** [comment]
> DS215+
> DSM 7.1.1-42962 Update 1

hey @wasyl00, I've been trying to solicit feedback to confirm compatibility with .NET builds of Radarr, Lidarr and Sonarr v4 running on ARMv7 architectures. If you have the time perhaps you can check out https://github.com/SynoCommunity/spksrc/issues/5574 and add your feedback on the test packages I've shared. Appreciate the support.

**Comment by mreid-tt** [comment]
> DSM 7.0.1-42218 Update 3
> Synology DS216play

hey @mastervol, I've been trying to solicit feedback to confirm compatibility with .NET builds of Radarr, Lidarr and Sonarr v4 running on ARMv7 architectures. If you have the time perhaps you can check out https://github.com/SynoCommunity/spksrc/issues/5574 and add your feedback on the test packages I've shared. Appreciate the support.
