### ISSUE TITLE
Would it be possible to update the Darkstat package?

### ISSUE THREAD

**Issue by Zialus** [SynoCommunity/spksrc#5144]
The current available version is really old, and doesn't seem to work on DSM7, but a new version just got released.

Would an update to the package be feasible?

https://synocommunity.com/package/darkstat

https://github.com/emikulic/darkstat/releases/tag/3.0.721

**Comment by hgy59** [comment]
@Zialus I am working on an update, but darkstat will never run under DSM 7+, as it requires root permissions to capture network traffic. (see #4524).
