### ISSUE TITLE
GateOne on DSM 4.2 (DS109J) needs Python

### ISSUE THREAD

**Issue by BRIOTPatrick** [SynoCommunity/spksrc#5148]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Python

### Package Version

2.7.6-8

### Device Model

DS109J

### Device Architecture

PPC

### Firmware Version

4.2

### What happened?

I want to install GateOne on my DS109J on DSM 4.2.
When i try, a popup inform me i've to install Python 2.7.6-8, but this package isn't in your repository.

Could you help me to find it ?

Best Regard.
Bigvivi

### Reproduction steps

```bash
1.
2.
3.
...
```

### Install Log

```log
.
```

### Service Log

```log
.
```

### Other Logs

```log
.
```

**Comment by hgy59** [comment]
@BRIOTPatrick are you sure you have DSM 4.2 ? The latest DSM for DS108J on the synology download pages is Version 4.0-2265 (2014-09-10).

**Comment by BRIOTPatrick** [comment]
Sorry for the big mistake, effectively a DS109J ! And yes i'm on DSM 4.2-3259.

**Comment by hgy59** [comment]
@BRIOTPatrick i was able to build python2 (2.7.18-26) for powerpc-4.2, but I had to exclude wheel for audio (cross/pyalsa, cross/pyaudio) and the zmq and uwsgi wheels (cross/pyzmq, cross/uwsgi).
I'm currently no aware whether gateone depends on one of those cross compiled wheels.
If you are interested, I can upload such a python2 package.
