### ISSUE TITLE
Is it possible to install postgresql alone?

### ISSUE THREAD

**Issue by RMHogervorst** [SynoCommunity/spksrc#5190]
This feels like a stupid question but is it possible to install postgresql alone? 
It seems some packages depend on postgres, and synology uses it in the background too, but can I create a postgres instance that is accessable on the lan?

**Comment by hgy59** [comment]
There is a postgresql package in progress in #4267.
To download the packages built by github action (available for 90 days from build) go to checks  - select one of the _details_ - summary - artifacts
or use this link https://github.com/SynoCommunity/spksrc/actions/runs/2004773941

NB the package must use a non standard port (5433) as 5432 is used by the pgsql of DSM.

**Comment by RMHogervorst** [comment]
that seems to install! nice one!

**Comment by RMHogervorst** [comment]
Not so sure how to connect to it yet. 
`# Error: FATAL:  no pg_hba.conf entry for host "192.168.178.20", user "pgadmin", database "pgadmin", SSL off`

**Comment by hgy59** [comment]
So far I only connected to pgsql on DSM 7 with Adminer
![grafik](https://user-images.githubusercontent.com/12009964/161444270-13e72dbb-d419-44e4-9dc4-fc5813df7d3a.png)

If you connect from another client (not localhost on the NAS), you have to configure such clients (as the error message shows).
Sorry but I have no further experiance with configuration of pgsql.

**Comment by RMHogervorst** [comment]
Yeah adminer was something I tried too, but adminer is giving me 404. (Not related to postgres).

**Comment by hgy59** [comment]
you find the pg_hba.conf file at
`/var/packages/postgresql/var/data/ph_hba.conf`

Default only localhost is trusted 
```
# Put your actual configuration here
# ----------------------------------
#
# If you want to allow non-local connections, you need to add more
# "host" records.  In that case you will also need to make PostgreSQL
# listen on a non-local interface via the listen_addresses
# configuration parameter, or via the -i or -h command line switches.

# CAUTION: Configuring the system for local "trust" authentication
# allows any local user to connect as any PostgreSQL user, including
# the database superuser.  If you do not trust all your local users,
# use another authentication method.


# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust
```

**Comment by RMHogervorst** [comment]
yes, thanks! When I modified the file everything works!
