### ISSUE TITLE
[DSM7][transmission]: invalid file format

### ISSUE THREAD

**Issue by farfromrefug** [SynoCommunity/spksrc#5205]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

transmission

### Package Version

3.0.0-20

### Device Model

ds918+

### Device Architecture

x86_64

### Firmware Version

7.0

### What happened?

I cant install the package i end up with
<img width="448" alt="Screenshot 2022-04-11 at 19 03 23" src="https://user-images.githubusercontent.com/655344/162792586-c166d592-dd01-44f7-b845-a89c50f4a85e.png">
 I also tried to manually download the package from here  https://synocommunity.com/package/transmission and i get the same error. Feels like something is wrong with the package

### Reproduction steps

```bash
1. try to install the package
```

### Install Log

```log
Nothing
```

### Other Logs

```log
I only see this in /var/log/messages

2022-04-11T18:58:03+02:00 DiskStation transmissiond[26452]: 1.kill sigterm
```
```

**Comment by hgy59** [comment]
I have a DS218+ with DSM 7.0.1-42218 Update 3 that is almost the same regarding the CPU arch.
And I have no such problems.
This error typically is shown, when you try to install a package for DSM6 under DSM7.
This should not happen with the DSM integrated package center.
For manual installation, are you sure you downloaded the file `transmission.v20.f41890[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64].spk`?

**Comment by farfromrefug** [comment]
@hgy59 i confirm this is the file that i used and it wont install on DSM 7.0.1-42218  (not on update 3)
And the error happens with manual spk and package center

**Comment by hgy59** [comment]
If you have the original spk file, the only thing I would try, is to restart the Diskstation.

**Comment by farfromrefug** [comment]
@hgy59 my Nas is restarted every day. and itis still happening

**Comment by farfromrefug** [comment]
@hgy59 thanks a lot for your help really ! i ll try and investigate this further

**Comment by Ettemlevest** [comment]
Think this invalid/corrupt torrent file error is caused by Transmission's incorrect v2 file format handling. Only occurs with hybrid torrent files. It is fixed in nightly builds:  https://github.com/transmission/transmission/pull/1964

**Comment by hgy59** [comment]
> Think this invalid/corrupt torrent file error is caused by Transmission's incorrect v2 file format handling. Only occurs with hybrid torrent files. It is fixed in nightly builds: [transmission/transmission#1964](https://github.com/transmission/transmission/pull/1964)

The reported error is not about an invalid torrent file, but an invalid synology installation package (spk) file.

**Comment by Ettemlevest** [comment]
Reading through the post you right. Sorry for the mislead.

**Comment by hgy59** [comment]
@farfromrefug this should be fixed with the latest releases. Can you confirm this works now?

**Comment by farfromrefug** [comment]
@hgy59 indeed I can confirm it is fixed. Tjank you

**Comment by farfromrefug** [comment]
@hgy59 it is failing again. Tried to manually download the spk for DS918+ here https://packages.synocommunity.com/transmission/27/transmission.v27.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk And i get invalid format error. Any idea?

**Comment by mreid-tt** [comment]
@farfromrefug, this error is usually associated with an incompatible DSM version. Are you running DSM 7.1 or higher?

**Comment by farfromrefug** [comment]
> @farfromrefug, this error is usually associated with an incompatible DSM version. Are you running DSM 7.1 or higher?

Thanks yes i am running DSM 7.2.1-69057 Update 1. Should work right?

**Comment by mreid-tt** [comment]
> Thanks yes i am running DSM 7.2.1-69057 Update 1. Should work right?

Hmm, yes you are correct. I'm running DSM 7.2.1 on a DS916+ which is a similar unit to yours with the same package.

Are there any logs worth reviewing? Perhaps at `/var/log/synopkg.log`?

Just as a comparison the SHA-256 checksum of the file should be as follows:

```
shasum -a 256 transmission.v27.f42661\[apollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000\].spk
```
```
24689030e62ddd985c4f72925bad46989458ebeecfa6beb7a5f5ead6d46a2df6
```

This will tell you if the download is somehow corrupt.

I have also seen issues where if the wizard script syntax is a bit off it can complain. As an experiment I've modified the wizard installer script based on another package I was working on.

If you can download this package and try a manual installation it would help determine if this is a possible cause. Don't install the package, just see if you get the install screen or if it complains about invalid package. https://drive.google.com/file/d/1Lg2M9Ct2HB1jO0tjeD5pgDDCiHXj5L4W/view?usp=sharing

**Comment by farfromrefug** [comment]
@mreid-tt Thanks for your answer.
The only thing i see in my log is:
```
2024/09/25 09:58:38 download transmission https://packages.synocommunity.com/transmission/27/transmission.v27.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk?arch=apollolake&build=69057 Begin download
2024/09/25 09:58:39 download transmission https://packages.synocommunity.com/transmission/27/transmission.v27.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk?arch=apollolake&build=69057 End download
2024/09/25 09:58:40 Use given volume to install, volume=[]
2024/09/25 09:58:40 Use any available volume to install, volume=[/volume1]
```
Now i tried with your test package and it gave the same error
Anything else i can try?

**Comment by mreid-tt** [comment]
@farfromrefug, that does sound unusual. I’ve tested the same DSM version on my unit and haven’t encountered this issue. Have you verified the SHA-256 hash of the downloaded file? While file corruption is unlikely, it’s worth double-checking.

From your earlier messages, it seems Transmission is already installed. Are you trying to upgrade? If so, what happens if you manually download and install the previous version you had? Do you encounter the same error during installation or upgrade?

**Comment by farfromrefug** [comment]
@mreid-tt Yes i check the sha. I am.sure it is good.
No transmission is not installed anymore. I must jave removed it last year. 
Now I am trying to install it again. 
Could that error come from a broken, not correctly uninstalled package?

**Comment by mreid-tt** [comment]
@farfromrefug, it might be helpful to try reinstalling the exact version you previously installed from the download page to see if that works.

If no version is working, have you tried installing other packages manually? Do packages manually downloaded from the Synology [Download Center](https://www.synology.com/en-uk/support/download/DS918+?version=7.2#packages) install successfully?

**Comment by farfromrefug** [comment]
@mreid-tt I tried almost all versions from the community dating back to 2022.
Will check other packages to see if the issue come.from my nas.
Thanks

**Comment by farfromrefug** [comment]
@mreid-tt i can confirm it works with other community packages

**Comment by farfromrefug** [comment]
@mreid-tt sadly still got the same error with the action package. 
The package i tested from the community was selfoss. Hope it is a good one to test with

**Comment by mreid-tt** [comment]
@farfromrefug, I’m stuck on this issue, mainly due to the lack of logs to investigate. I’m not sure if `/var/log/messages` would provide any additional insights. For reference, Selfoss is a good example of an installer with a similar wizard. You might also want to check out this complex ownCloud installer: [GitHub Action](https://github.com/SynoCommunity/spksrc/actions/runs/11012253169).

**Comment by mreid-tt** [comment]
For comparison my `/var/log/synopkg.log` looks like this for a regular install:

```
2024/09/26 16:41:32 download transmission https://packages.synocommunity.com/transmission/27/transmission.v27.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk?arch=kvmx64&build=69057 Begin download
2024/09/26 16:41:35 download transmission https://packages.synocommunity.com/transmission/27/transmission.v27.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk?arch=kvmx64&build=69057 End download
2024/09/26 16:41:38 Use given volume to install, volume=[]
2024/09/26 16:41:38 Use any available volume to install, volume=[/volume1]
2024/09/26 16:41:46 Use given volume to install, volume=[]
2024/09/26 16:41:46 Use any available volume to install, volume=[/volume1]
2024/09/26 16:41:57 Use given volume to install, volume=[]
2024/09/26 16:41:57 Use any available volume to install, volume=[/volume1]
2024/09/26 16:41:58 Use given volume to install, volume=[]
2024/09/26 16:41:58 Use any available volume to install, volume=[/volume1]
2024/09/26 16:41:58 Acquire data-share for transmission when 0x0001 (ready)
2024/09/26 16:41:58 Acquire data-share for transmission when 0x0001 (done)
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin preinst
2024/09/26 16:42:00 install transmission 4.0.6-27 End preinst ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/mkdir -p /volume1/@appstore/transmission -m 755
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/mkdir -p /volume1/@appstore/transmission -m 755 ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/rm -rf /volume1/@appstore/transmission
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/rm -rf /volume1/@appstore/transmission ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/mv -f /volume1/@tmp/synopkg/install.brVTe5/package /volume1/@appstore/transmission
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/mv -f /volume1/@tmp/synopkg/install.brVTe5/package /volume1/@appstore/transmission ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/rm -rf /var/packages/transmission
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/rm -rf /var/packages/transmission ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/mkdir -p /var/packages/transmission -m 755
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/mkdir -p /var/packages/transmission -m 755 ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/touch /var/packages/transmission/installing
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/touch /var/packages/transmission/installing ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/mv -f /volume1/@tmp/synopkg/install.brVTe5/INFO /var/packages/transmission/INFO
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/mv -f /volume1/@tmp/synopkg/install.brVTe5/INFO /var/packages/transmission/INFO ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/rm -rf /var/packages/transmission/scripts
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/rm -rf /var/packages/transmission/scripts ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/mv -f /volume1/@tmp/synopkg/install.brVTe5/scripts /var/packages/transmission/scripts
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/mv -f /volume1/@tmp/synopkg/install.brVTe5/scripts /var/packages/transmission/scripts ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/rm -rf /var/packages/transmission/WIZARD_UIFILES
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/rm -rf /var/packages/transmission/WIZARD_UIFILES ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/mv -f /volume1/@tmp/synopkg/install.brVTe5/WIZARD_UIFILES /var/packages/transmission/WIZARD_UIFILES
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/mv -f /volume1/@tmp/synopkg/install.brVTe5/WIZARD_UIFILES /var/packages/transmission/WIZARD_UIFILES ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/rm -rf /var/packages/transmission/conf
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/rm -rf /var/packages/transmission/conf ret=[0]
2024/09/26 16:42:00 install transmission 4.0.6-27 Begin /bin/mv -f /volume1/@tmp/synopkg/install.brVTe5/conf /var/packages/transmission/conf
2024/09/26 16:42:00 install transmission 4.0.6-27 End /bin/mv -f /volume1/@tmp/synopkg/install.brVTe5/conf /var/packages/transmission/conf ret=[0]
2024/09/26 16:42:02 Acquire systemd-unit for transmission when 0x0001 (ready)
2024/09/26 16:42:03 Acquire systemd-unit for transmission when 0x0001 (done)
2024/09/26 16:42:03 Acquire data-share for transmission when 0x0001 (ready)
2024/09/26 16:42:03 Acquire data-share for transmission when 0x0001 (done)
2024/09/26 16:42:03 Acquire port-config for transmission when 0x0001 (ready)
2024/09/26 16:42:03 Acquire port-config for transmission when 0x0001 (done)
2024/09/26 16:42:04 install transmission 4.0.6-27 Begin postinst
2024/09/26 16:42:04 install transmission 4.0.6-27 End postinst ret=[0]
2024/09/26 16:42:04 install transmission: begin to start version 4.0.6-27
2024/09/26 16:42:05 Acquire data-share for transmission when 0x0001 (ready)
2024/09/26 16:42:05 Acquire data-share for transmission when 0x0001 (done)
2024/09/26 16:42:05 Acquire port-config for transmission when 0x0001 (ready)
2024/09/26 16:42:05 Acquire port-config for transmission when 0x0001 (done)
2024/09/26 16:42:05 install transmission 4.0.6-27 Begin start-stop-status start
2024/09/26 16:42:06 install transmission 4.0.6-27 End start-stop-status start ret=[0]
2024/09/26 16:42:08 install transmission: start version 4.0.6-27 successfully, result 0
2024/09/26 16:42:08 install transmission 4.0.6-27 successfully
```

**Comment by hgy59** [comment]
If there are errors in the INFO file or the wizard, those are logged in a log file named like synocgi*.log (sorry I am out of my environment and can't verify the name).

just search for updated log files in /var/log

**Comment by mreid-tt** [comment]
@farfromrefug, were you able to look into the logs while installing to get further information? The specific log which may contain useful debug information is `/var/log/synoscgi.log`.

**Comment by hgy59** [comment]
@farfromrefug do you really have DSM 7.0? you need at least DSM 7.1 for most of the DSM 7 packages of SynoCommunity (and for current jellyfin DSM 7.2).

**Comment by hgy59** [comment]
OK this issue was for Transmission 3.0.0-20 that is outdated.
Please open a new issue when you still have troubles with Transmission 4.

**Comment by farfromrefug** [comment]
@hgy59 yes i have DSM 7.2 :D 
And the issue still persists with Transmission 4. Can you reopen this issue please?
Here is finally a log from `/var/log/synoscgi.log` . Thanks @mreid-tt 
```
2024-10-11T11:17:43+02:00 DiskStation synoscgi_SYNO.Core.Package.Installation.Download_1_check[9812]: SYNOPKGMGR: Failed to verify package, spk=[/volume1/@tmp/synopkg/download.s6ai1K/@SYNOPKG_DOWNLOAD_transmission] result=[{"action":"prepare","beta":false,"betaIncoming":false,"error":{"code":289,"description":"spk is not from synology"},"installReboot":false,"package":"transmission","packageName":"Transmission","stage":"prepare","success":false,"version":"4.0.6-27"}]
2024-10-11T11:17:43+02:00 DiskStation synoscgi_SYNO.Core.Package.Installation.Download_1_check[9812]: SYNOPKGMGR: User sc-transmission is reservered for system
2024-10-11T11:17:43+02:00 DiskStation synoscgi_SYNO.Core.Package.Installation.Download_1_check[9812]: SYNOPKGMGR: Failed to revise files before running wizard, pkg=[transmission]
2024-10-11T11:17:43+02:00 DiskStation synoscgi_SYNO.Core.Package.Installation.Download_1_check[9812]: SYNOPKGMGR: Failed to load wizard, pkg=[transmission]

```

**Comment by mreid-tt** [comment]
> 2024-10-11T11:17:43+02:00 DiskStation synoscgi_SYNO.Core.Package.Installation.Download_1_check[9812]: SYNOPKGMGR: User sc-transmission is reservered for system

This line is definitely a problem. I would first interrogate the user with the following command:
```
$ sudo /usr/syno/sbin/synouser --get sc-transmission
```
My output looked like this:
```
User Name   : [sc-transmission]
User Type   : [AUTH_LOCAL]
User uid    : [177169]
Primary gid : [207066]
Fullname    : []
User Dir    : [/var/packages/transmission/home]
User Shell  : [/sbin/nologin]
Expired     : [false]
User Mail   : []
Alloc Size  : [127]
Member Of   : [2]
(207066) synocommunity
(999) synopkgs
```
Then we can do a cleanup of everything belonging to this user by first finding what files and folders they own, like this:
```
$ sudo find / -user sc-transmission
```
My output looked like this (ignoring errors):
```
/volume1/@appdata/transmission
/volume1/@apphome/transmission
/volume1/@appshare/transmission
/volume1/@appconf/transmission
/volume1/downloads/watch-transmission
```
I then removed all these folders like this:
```
$ sudo rm -rf /volume1/@appdata/transmission
$ sudo rm -rf /volume1/@apphome/transmission
$ sudo rm -rf /volume1/@appshare/transmission
$ sudo rm -rf /volume1/@appconf/transmission
$ sudo rm -rf /volume1/downloads/watch-transmission
```
Then finally, I removed the user like this:
```
$ sudo /usr/syno/sbin/synouser --del sc-transmission
$ sudo /usr/syno/sbin/synouser --rebuild all
```

**Comment by farfromrefug** [comment]
output of `sudo /usr/syno/sbin/synouser --get sc-transmission`
```
User Name   : [sc-transmission]
User Type   : [AUTH_LOCAL]
User uid    : [108]
Primary gid : [65536]
Fullname    : []
User Dir    : [/var/packages/transmission/target]
User Shell  : [/sbin/nologin]
Expired     : [false]
User Mail   : []
Alloc Size  : [129]
Member Of   : [1]
```

as for `sudo find / -user sc-transmission` it does not 'return', runs endlessly. Will try to find why

**Comment by mreid-tt** [comment]
> as for `sudo find / -user sc-transmission` it does not 'return', runs endlessly. Will try to find why

This is mainly a cleanup suggestion to give you a clean slate upon reinstallation—it's not strictly necessary. The command scans your entire DiskStation for files owned by that user, which might take some time if there are many files. However, if you let it run, it should complete without issues.

**Comment by farfromrefug** [comment]
@mreid-tt strange i cant remove the user!
```
sudo /usr/syno/sbin/synouser --del sc-transmission
Lastest SynoErr=[file_get_section.c:83]
synouser.c:803 SYNOLocalAccountUserDelete failed. synoerr=[0x0000]
```

**Comment by farfromrefug** [comment]
@mreid-tt crazy whe i try to remove i get `SYNOLocalAccountUserDelete failed. synoerr=[0xB800]`
It could be (looking on the web) that those user ids are reserved `ERR_RESERVED_USER 	0xB800 	The uid is less than UID_MIN.`
I am trying to see if i can remove user another way (like manually)

**Comment by farfromrefug** [comment]
@mreid-tt I got it! And you were right it was due to sc-transmission/transmission users which were already existing
I had to remove them manually but it worked!
I did then managed to install the package.

Thanks a lot for the time you spent trying to help me!

@hgy59 i ll close that issue now thanks to you too
