### ISSUE TITLE
When will the 1.8.0 beta version of jellyfin be updated?

### ISSUE THREAD

**Issue by stevenliuit** [SynoCommunity/spksrc#5231]
The jellyfin official website has been updated to the latest version 1.8.0 beta2, when will we update it?

**Comment by hgy59** [comment]
You mean 10.8.0 beta2?
After we started to release a package, we only release stable versions. 

You are welcome to create a PR for jellyfin 10.8 and start with beta2.
So interested users could test it.
But such a PR will not be merged and released before a stable version is available.

_Sorry, we all have limited resources available here._
