### ISSUE TITLE
PLIST.auto broken

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#5233]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

n/a

### Package Version

n/a

### Device Model

any

### Device Architecture

any

### Firmware Version

any

### What happened?

I recently noticed that the `PLIST.auto` seems broken, to investigate.  Might be due to a change I did a little while ago.

### Reproduction steps

```bash
1.
2.
3.
...
```

### Install Log

```log
n/a
```

**Comment by hgy59** [comment]
@th0ma7 I fixed this in 6871dac4c88e336a744b1d154bbe1c369ff12108 for the dotnet runtime package.
Probably this is not in your branch or it has some side effects?

**Comment by th0ma7** [comment]
Just a thought, the PLIST generation may benefit from being reviewed where there would be a plist.`pre` and `post` so we can clearly determine a `auto` out of the two instead of using the `.tmp` as we do currently.
