### ISSUE TITLE
Missing documentation: Using just the TC

### ISSUE THREAD

**Issue by IngwiePhoenix** [SynoCommunity/spksrc#5292]
Hello!

Whilst building and making new cross-compile packages is pretty easy to follow, all I wanted was to have the cross-compile toolchain so I could compile small programs across - not make a whole package. It's just for testing things and seing how what I would like to use actually performs.

Hence this is kind of a request for documentation *and* a feature request: Provide a method for simple, little compiles for testing by creating a small wrapper script. I.e. `syno-88f6281-6.2.4-gcc` and friends.

I want to see if I can cross-compile something like supervisord or alike to act as a "userspace service manager" for little things like opening port forwarding via SSH connections et cetera.

Thank you in advance!

Kind regards,
Ingwie

**Comment by hgy59** [comment]
@IngwiePhoenix you need to create a cross/package file to build your tool and you can find the build targets in the work-_arch_-_dsmvers_/install folder.
If your package contains shared libraries that must be found at runtime, it is better to use the spk infrastructure that adjusts the dependencies for the target install folder.
If you want a minimal spk, you can find examples in the `/spksrc/diyspk` folder. 

Take cross/tree and diyspk/tree as an example. 
A simple command line tool without icon or any package configuration.

The diyspk folder (do it yourself spk) was introduced for the tools that are included in the synocli-* packages and are not published as dedicated packages. It shortens the build time when updating such tools.

**Comment by IngwiePhoenix** [comment]
Thanks! But all I want to do is just to `gcc -static *.c -o out` a few simple programs so I can transfer them over via `scp` and see how they behave before I sit down and get into the nitty-gritty of using the whole infrastructure.
