### ISSUE TITLE
[Package Request] 

### ISSUE THREAD

**Issue by IngwiePhoenix** [SynoCommunity/spksrc#5293]
### Software Name

Comskip

### Brief Description

Comskip is a free commercial remover from DVR recordings.
It can be used together with TVHeadend which is already provided by SynoCommunity.

Support forum is here: http://www.kaashoek.com/comskip/

Since ffmpeg is already within spksrc as well, building comskip against that should be trivial. I don't know about libargtable though as I have never heared of it before. Also since the GUI is not needed, libsdl1 can be omitted too.

### Website

https://github.com/erikkaashoek/Comskip

### Build/Installation documentation

https://github.com/erikkaashoek/Comskip

### Source code

https://github.com/erikkaashoek/Comskip

### OpenSource License

GPLv2

**Comment by hgy59** [comment]
We already support comskip. https://synocommunity.com/package/comskip

**Comment by IngwiePhoenix** [comment]
Oh. I didn't see it in the repo, so I assumed it wasn't available.

Well that, or I flat out overlooked it...
