### ISSUE TITLE
[Package Request] MEGAcmd

### ISSUE THREAD

**Issue by rsbrux** [SynoCommunity/spksrc#5308]
### Software Name

megacmd

### Brief Description

The megacmd package has been included in the SynoCommunity library for many years, but appears to be out of date.  I requested an update from meganz (see [here](https://github.com/meganz/MEGAcmd/issues/666#issuecomment-1135377055)) but did not receive a response there.  Can someone here update the version in the SynoCommunity library?

### Website

https://github.com/meganz/MEGAcmd

### Documentation

https://github.com/meganz/MEGAcmd#readme

### Build/Installation documentation

https://github.com/meganz/MEGAcmd#readme

### Source code

https://github.com/meganz/MEGAcmd

### OpenSource License

GPLv3

### Other License

https://github.com/meganz/MEGAcmd/blob/master/LICENSE

**Comment by hgy59** [comment]
@rsbrux this package was never provided by SynoCommunity.
Is is an official Thirdparty package from Synology, developped by Mega Ldt.
https://www.synology.com/en-us/dsm/packages/MEGAcmd

And as the link above displays `Mega Ltd. 1.4.0-1000`. This version is from 2020.

**Comment by hgy59** [comment]
corrigenda
you can download the package on https://archive.synology.com/download/Package/MEGAcmd
- for DSM 6 the version is 1.0.0 (this one is really outdated)
- version 1.4.0-1000 is for DSM 7 only

**Comment by rsbrux** [comment]
That’s my problem then.  Although my DS1513+ can theoretically run DSM 7, everything I’ve read indicates that I will have significant performance problems if I upgrade, so I am still using DSM 6.2.

**Comment by hgy59** [comment]
@rsbrux do not give up so fast _(I am trying to build megacmd...)_
