### ISSUE TITLE
Compiling jellyfin 10.8.0 error problem

### ISSUE THREAD

**Issue by stevenliuit** [SynoCommunity/spksrc#5309]
I modified jellyfin 10.8.0 version
Upgraded zsh 5.9 version
donet upgraded to 6.0.300

error when compiling

root@3b09a724d943:/spksrc/spk/jellyfin# make V=1 arch-apollolake-7.0
===> Building package for arch apollolake-7.0
make[1]: Entering directory '/spksrc/spk/jellyfin'
===> Processing dependencies of jellyfin
make[2]: Entering directory '/spksrc/cross/libstdc++'
make[2]: Nothing to be done for 'default'.
make[2]: Leaving directory '/spksrc/cross/libstdc++'
make[2]: Entering directory '/spksrc/cross/jellyfin'
make[2]: Nothing to be done for 'default'.
make[2]: Leaving directory '/spksrc/cross/jellyfin'
make[2]: Entering directory '/spksrc/cross/jellyfin-web'
===> Processing dependencies of jellyfin-web
make[3]: Entering directory '/spksrc/native/nodejs'
make[3]: *** No targets specified and no makefile found. Stop.
make[3]: Leaving directory '/spksrc/native/nodejs'
make[2]: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 2
make[2]: Leaving directory '/spksrc/cross/jellyfin-web'
make[1]: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 2
make[1]: Leaving directory '/spksrc/spk/jellyfin'
make: [../../mk/spksrc.spk.mk:474:arch-apollolake-7.0] Error 2 (ignored)

my fork url:https://github.com/stevenliuit/spksrc

**Comment by publicarray** [comment]
Are you on the correct branch? Works for me on the master branch.

**Comment by stevenliuit** [comment]
> Are you on the correct branch? Works for me on the master branch. The error means that it can't find the native nodejs Makefile

I have solved the nodejs problem, it should be an error in the network download npm dependency, delete it and start again to fix it.

**Comment by publicarray** [comment]
I'm glad you got it sorted 👍
