### ISSUE TITLE
Add iconv to the SynoCli File Tools package.

### ISSUE THREAD

**Issue by BaukeZwart** [SynoCommunity/spksrc#5319]
### Software Name

SynoCli/iconv

### Brief Description

The iconv program converts the encoding of characters in inputfile from one coded character set to another.

### Website

https://linux.die.net/man/1/iconv

### Documentation

https://linux.die.net/man/1/iconv

### Build/Installation documentation

https://github.com/processone/iconv

### Source code

https://github.com/processone/iconv

### OpenSource License

Apache

**Comment by hgy59** [comment]
@BaukeZwart do you request the GNU iconv tool of the linked website/documentation (https://linux.die.net/man/1/iconv) or the iconv tool for erlang/elixir from https://github.com/processone/iconv?

**Comment by hgy59** [comment]
BTW the package `tvheadend` already installs GNU iconv in /var/packages/tvheadend/target/bin:
_so it would be easy to include this in synocli-file_

```
/var/packages/tvheadend/target/bin$ ./iconv --version
iconv (GNU libiconv 1.16)
Copyright (C) 2000-2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Bruno Haible.

/var/packages/tvheadend/target/bin$ ./iconv --help
Usage: ./iconv [OPTION...] [-f ENCODING] [-t ENCODING] [INPUTFILE...]
or:    ./iconv -l

Converts text from one encoding to another encoding.

Options controlling the input and output format:
  -f ENCODING, --from-code=ENCODING
                              the encoding of the input
  -t ENCODING, --to-code=ENCODING
                              the encoding of the output

Options controlling conversion problems:
  -c                          discard unconvertible characters
  --unicode-subst=FORMATSTRING
                              substitution for unconvertible Unicode characters
  --byte-subst=FORMATSTRING   substitution for unconvertible bytes
  --widechar-subst=FORMATSTRING
                              substitution for unconvertible wide characters

Options controlling error output:
  -s, --silent                suppress error messages about conversion problems

Informative output:
  -l, --list                  list the supported encodings
  --help                      display this help and exit
  --version                   output version information and exit

Report bugs to <bug-gnu-libiconv@gnu.org>.
```

**Comment by BaukeZwart** [comment]
> @BaukeZwart do you request the GNU iconv tool of the linked website/documentation (https://linux.die.net/man/1/iconv) or the iconv tool for erlang/elixir from https://github.com/processone/iconv?

I didn't realize there was a difference between the two.
If you can add the package already in `tvheaden` would be great.
