### ISSUE TITLE
phpMemcachedAdmin not accesible

### ISSUE THREAD

**Issue by MarcS1975** [SynoCommunity/spksrc#5343]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

MemCached

### Package Version

1.6.15-3

### Device Model

DS3617xs

### Device Architecture

x86_64

### Firmware Version

6.2-23739

### What happened?

I installed Memcache and the phpMemcahceAdmin icon appears in DSM.
Upon clicking a web page opens on http://[myIP]/phpMemcachedAdmin
and results in a 404 error (see screenshowt below)

### Reproduction steps

```bash
1.Install Memcache
2. Click on phpMemcacheAdmin icon
3.
...
```

### Install Log

```log
Installer.log not available.

ls /var/packages/memcached/target/var/ shows:

memcached.log  
memcached.pid  
phpmemcachedadmin.config
```

**Comment by smaarn** [comment]
Hello,

Thanks for reaching out and sorry for the issue you're facing.

Would you be able to tell us the contents of the `/var/services/web` folder ?

If it's what I believe you wouldn't be seeing anything such as `phpmemcachedadmin` folder... :( Working on a fix

**Comment by smaarn** [comment]
Hello, I may have a fix proposal (currently under review).

In the mean time could you check https://github.com/smaarn/spksrc/releases/tag/memcache-1.6.15-4-rc-1 to test it would fix your issue ?

**Comment by MarcS1975** [comment]
Hello - thanks for the quick reply. The folder web has the following content:
bbs  @eaDir  index.html  nctest  nextcloud  nextcloud-23.0.0.zip  phpMyAdmin  rutorrent  tropeaweb  web_images

**Comment by MarcS1975** [comment]
> Hello, I may have a fix proposal (currently under review).
> 
> In the mean time could you check https://github.com/smaarn/spksrc/releases/tag/memcache-1.6.15-4-rc-1 to test it would fix your issue (I don't have a DSM 6 available to test unfortunately) ?

Wonderful. That worked !! Thank you very much.
So it seems I did not use the latest version. Just for future reference, how do I ensure that my Synology Package Center always pulls the latest version?

**Comment by hgy59** [comment]
@MarcS1975 can you please provide the full DSM version of your DS3617xs? (like DSM 6.2.4-25556 Update 6) and not only '6.2'.

**Comment by MarcS1975** [comment]
6.2-23739

**Comment by MarcS1975** [comment]
Hi - sorry, the error s back.
I installed manually Memcache 1.6.15.4 on DSM7 and accessing the admin panel does not work.

**Comment by MarcS1975** [comment]
I installed Memcache (manually) and the phpMemcahceAdmin icon appears in DSM.
Upon clicking a web page opens on http://[myIP]/phpMemcachedAdmin
and results in a 503 error
