### ISSUE TITLE
Redis useless without Chroot

### ISSUE THREAD

**Issue by MarcS1975** [SynoCommunity/spksrc#5344]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Redis and Chroot

### Package Version

Redis 7.0.2.11

### Device Model

DS36

### Device Architecture

x86_64

### Firmware Version

6.2

### What happened?

Redis installs fine but needs Debian Chroot to be able to connect via phpredis.
Where is chroot?

### Reproduction steps

```bash
1.install Redis
2. looking to install Chroot
3.
...
```

### Install Log

```log
not avail
```

**Comment by hgy59** [comment]
redis is a key value store that provides it's service on the port 6379. 
This service works as expected.
I can even access the redis service running on my diskstation with RedisInsight from my PC.
And redis-benchmark tests run sucessfully on the diskstation.

I have no idea why phpredis needs chroot, but this is not related to redis, but to phpredis.

So may be you have to build (or ask for) a phpredis package.

This is definitely not a bug of redis.
