### ISSUE TITLE
nnn 4.5 is not inside SynoCli File Tools v2.6-15 package as it is supposed to be

### ISSUE THREAD

**Issue by jducaud** [SynoCommunity/spksrc#5351]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

SynoCli File Tools

### Package Version

2.6-15

### Device Model

Synology DS218+

### Device Architecture

x86_64

### Firmware Version

DSM 6.2.4 build 25556 update 6

### What happened?

nnn 4.5 is supposed to be inside the SynoCli File Tools v2.6-15 package, but it is not.

### Reproduction steps

```bash
1. Install SynoCli File Tools v2.6-15
2. Run a shell
3. Type "nnn"
```

### Install Log

```log
I have no longer the install log since I uninstalled SynoCli File Tools v2.6-15 and reinstalled SynoCli File Tools v2.5.13 (to get back "nnn")
```

**Comment by hgy59** [comment]
@jducaud thanks for reporting this.

**Comment by jducaud** [comment]
@hgy59 you're welcome.
