### ISSUE TITLE
SynoCli File Tools - Failed to download "synocli-file".

### ISSUE THREAD

**Issue by vjayer** [SynoCommunity/spksrc#5359]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

synocli-file

### Package Version

2.6-15

### Device Model

DS415+

### Device Architecture

x86_64

### Firmware Version

DSM 6.2.4-25556 Update 6

### What happened?

When trying to download / update to synocli-file version 2.6-15 I receive this error notification:
 Failed to download "synocli-file".

I previously had synocli-file 2.5-13 and could not update. Unfortunately I uninstalled it, and now I cannot reinstall with this latest version. I can install other packages such as synocli-monitor during this time btw.

There is nothing in /var/log/synopkg.log , but this is from /var/log/messages (see raw msg below)

https://packages.synocommunity.com/synocli-file/15/synocli-file.v15.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellntbap-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=avoton&build=25556

- does not exist

### Reproduction steps

```bash
1. Update or install synocli-file 2.6-15
2. Check notifications
```

### Install Log

```log
/var/log/packages/synocli-file.log
-----------------------------------
    ...
2022/07/07 01:09:33 Begin reload_inst_variables
2022/07/07 01:09:33 End reload_inst_variables
2022/07/07 01:09:33 Begin initialize_variables
2022/07/07 01:09:33 End initialize_variables
2022/07/07 01:09:33 ===> Step postuninst. USER= GROUP= SHARE_PATH=
2022/07/07 01:09:33 uninstall synocli-file 2.5-13 End postuninst ret=[0]

- END -
- No indication of download error for synocli-file 2.6-15
```

### Service Log

```log
/var/packages/synocli-file/ ...
does not exist since I uninstalled it
```

### Other Logs

```log
/var/log/messages
-----------------
    ...
2022-07-09T06:57:05-07:00 ds415plus synoscgi_SYNO.Core.Package.Installation_1_install[32744]: pkgserver.cpp:715 Failed to download package, httpResponseCode=404, url=https://packages.synocommunity.com/synocli-file/15/synocli-file.v15.f15047%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellntbap-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-v1000-x86-x86_64%5D.spk?arch=avoton&build=25556, mode=install
2022-07-09T07:10:41-07:00 ds415plus SecurityScan.py: /usr/syno/bin/securityscan/FuncAPI.py:873:moduleImport(): Failed to import module 'ruleDB.User.Guest.disable_guest'
```

**Comment by hgy59** [comment]
synocli-file 2.6-15 does not exist anymore, current version is 2.6-16 (2.6-15 was missing nnn and rnm, fixed by #5352).
probably you have to wait some time, until the current version is visible in your diskstation (mine shows 2.6-16 since yesterday) or you can download and manually install the current version (https://synocommunity.com/package/synocli-file)

**Comment by vjayer** [comment]
Thanks a lot for the quick reply!
Alright, it's now available in my DSM and I'm able to successfully install 2.6-16

**Comment by vjayer** [comment]
resolved with update
