### ISSUE TITLE
[Package Request] HomeAssistant new update for Synology community

### ISSUE THREAD

**Issue by Dragoniacs16** [SynoCommunity/spksrc#5366]
### Software Name

HomeAssistant

### Brief Description

Hi guys !
I know you're doing an amazing work, but I face some bugs with my HomeAssistant & Velux package (KLF connection losts 3 times per week...). I'm on DSM7 and can't install docker. 
Is it possible to have an updated package released via the SynoCommunity ?
Thanks a lot for your support.

### Website

https://synocommunity.com/package/homeassistant

### Build/Installation documentation

https://synocommunity.com/package/homeassistant

### Source code

https://synocommunity.com/package/homeassistant

### OpenSource License

other (please specify below)

**Comment by hgy59** [comment]
Closed by #5385
