### ISSUE TITLE
BicBucStriim: - Invalid file format

### ISSUE THREAD

**Issue by mwcem** [SynoCommunity/spksrc#5372]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

BicBucStriim

### Package Version

1.3.6

### Device Model

Synology DS418play

### Device Architecture

x86_64

### Firmware Version

DSM 7.3

### What happened?

When youn want to install BicBucStriim from package center the download starts alright, then afterwards you get an error message saying "Wrong file-format, please contact the developer".

### Reproduction steps

```bash
1. Try to install BitBucStriim from the package-center
```

### Install Log

```log
- not available -
```

**Comment by BenjV** [comment]
There is no BicBucStriim package for DSM 7.

**Comment by mwcem** [comment]
Then this is the error. If DSM 7 is installed BicBucStriim should either not be available as a package or - the better solution - upgrade the package, so it can work again correctly.
Thanks

**Comment by BenjV** [comment]
That is just not possible.
If there is only a DSM 6 package available then DSM wil try to install that one an fail the way you saw happen.
Synology did not provide a way to do that in a package center.

And if you desperately need that package for DSM 7, I would suggest that you create it yourself and create a pull request so it cab be added to the package center.

**Comment by mwcem** [comment]
Nice suggestion, but I'm just a user, no programmer.
Would be nice if one of the programmers who did the software would provide this solution.

**Comment by hgy59** [comment]
> Then this is the error. If DSM 7 is installed BicBucStriim should either not be available as a package or - the better solution - upgrade the package, so it can work again correctly.

You can read on the main page (README.md):
> Despite you see packages of SynoCommunity in the Package Center of your Diskstation with DSM 7, some of the packages are not compatible with DSM 7.

It is still not possible to hide DSM 6 packages from DSM 7 package center. 
This is a pending issue in https://github.com/SynoCommunity/spkrepo/issues/63
