### ISSUE TITLE
Wallabag - update to version 2.5.1 from 2.3.8

### ISSUE THREAD

**Issue by j4w0r** [SynoCommunity/spksrc#5380]
### Software Name

Wallabag

### Brief Description

Latest version (2.5.1) of Wallabag has vastly improved saving webpages engine, added mass operations on articles and has many other features and bugfixes since 2.3.8.
It now requires PHP 7.4. Other upgrade info / requirements can be found here: https://github.com/wallabag/wallabag/releases
It would be great if new package would work on Dsm 6.2.
Thanks in advance!

### Website

https://github.com/wallabag/wallabag

### Build/Installation documentation

https://doc.wallabag.org/en/admin/installation/installation.html

### Source code

https://github.com/wallabag/wallabag

### OpenSource License

MIT

**Comment by hgy59** [comment]
@j4w0r this is a not so easy task. You have to update php to 7.4 in the dev environment. I tried to build with composer, but got some errors:
```
PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Console\mb_detect_encoding() in /usr/share/php/Symfony/Component/Console/Application.php:1178
```

any php freak around here?

**Comment by j4w0r** [comment]
Does anyone dare to take the challenge? ;)

Thanks in advance!

**Comment by j4w0r** [comment]
The current version of Wallabag is 2.6.7
https://github.com/wallabag/wallabag/releases/tag/2.6.7

Requirements have not changed:
https://doc.wallabag.org/en/admin/installation/requirements

**Comment by firewalkwithmetotwinpeaks** [comment]
Hello everyone!

I'd like to take advantage of this thread, especially as it's the most recent wallabag version, to ask you a quick question. 
Is it possible to install it on my old DS213J? In fact, my research suggests that the use of docker and docker compose is poorly/not at all supported by my NAS....

What do you think?

Kind regards

**Comment by hgy59** [comment]
> I'd like to take advantage of this thread, especially as it's the most recent wallabag version, to ask you a quick question. Is it possible to install it on my old DS213J? In fact, my research suggests that the use of docker and docker compose is poorly/not at all supported by my NAS....
> 

If you are still on DSM 6, you can try.
The Wallabag package was never migrated to DSM 7 (mariadb 10).

**Comment by firewalkwithmetotwinpeaks** [comment]
Thanks a lot !

I'm on DSM7..... Too bad....

Best regards

**Comment by j4w0r** [comment]
@mreid-tt, thanks a lot for making an upgrade for Wallabag!

I am running it on DSM 7.2.
One thing, I had to enable additional php-extension "zlib" for the export function (epub, pdf etc.) to work.

**Comment by mreid-tt** [comment]
@j4w0r, thanks for the feedback! I can enable that in a revision or the next release. Did you upgrade from a previous version or perform a fresh install? I'm particularly interested in hearing from anyone who upgraded, as I wasn't able to fully test that scenario.

**Comment by j4w0r** [comment]
It was a fresh install. Thanks again :)

**Comment by j4w0r** [comment]
I found another PHP extension that should be enabled: openssl.
Without it functionality "Credentials for paywall websites" crashes.

**Comment by mreid-tt** [comment]
> I found another PHP extension that should be enabled: openssl. Without it functionality "Credentials for paywall websites" crashes.

Hmm, this is worrisome since neither of these are in the [documentation](https://doc.wallabag.org/en/admin/installation/requirements). I've created a new PR #6251 to fix this. Will keep it open a few days in case you find any others missing.
