### ISSUE TITLE
Multiple packages unable to start

### ISSUE THREAD

**Issue by IzaacJ** [SynoCommunity/spksrc#5381]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Radarr, Sonarr, CouchPotato, GateOne and probably others

### Package Version

The version provided through Package Center

### Device Model

DS411j

### Device Architecture

ARMv5

### Firmware Version

DSM 6.2.4-25556 Update 6

### What happened?

Fresh install of DSM6 and update to latest after having the DS411j unused for way to long.
Pretty much all packages that I've installed fails to run after successful installation.

Logs attached below:
- Radarr
  - [/var/log/packages/radarr.log](https://github.com/SynoCommunity/spksrc/files/9233469/varlogpackagesradarr.log)
  - [/volume1/@appstore/radarr/var/radarr.log](https://github.com/SynoCommunity/spksrc/files/9233477/volume1appstoreradarrvarradar.log)
  - [/volume1/@appstore/radarr/var/radarr_install.log](https://github.com/SynoCommunity/spksrc/files/9233478/volume1appstoreradarrvarradar_install.log)
- Sonarr
  - [/var/log/packages/nzbdrone.log](https://github.com/SynoCommunity/spksrc/files/9233468/varlogpackagesnzbdrone.log)
  - [/volume1/@appstore/nzbdrone/var/nzbdrone.log](https://github.com/SynoCommunity/spksrc/files/9233475/volume1appstorenzbdronevarnzbdrone.log)
  - [/volume1/@appstore/nzbdrone/var/nzbdrone_install.log](https://github.com/SynoCommunity/spksrc/files/9233476/volume1appstorenzbdronevarnzbdrone_install.log)
- CouchPotato
  - [/var/log/packages/couchpotatoserver.log](https://github.com/SynoCommunity/spksrc/files/9233464/varlogpackagescouchpotatoserver.log)
  - [/volume1/@appstore/couchpotatoserver/var/couchpotatoserver.log](https://github.com/SynoCommunity/spksrc/files/9233470/volume1appstorecouchpotatoservervarcouchpotatoserver.log)
  - [/volume1/@appstore/couchpotatoserver/var/couchpotatoserver_install.log](https://github.com/SynoCommunity/spksrc/files/9233472/volume1appstorecouchpotatoservervarcouchpotatoserver_install.log)
- GateOne
  - [/var/log/packages/gateone.log](https://github.com/SynoCommunity/spksrc/files/9233467/varlogpackagesgateone.log)
  - [/volume1/@appstore/gateone/var/gateone.log](https://github.com/SynoCommunity/spksrc/files/9233473/volume1appstoregateonevargateone.log)
  - [/volume1/@appstore/gateone/var/gateone_install.log](https://github.com/SynoCommunity/spksrc/files/9233474/volume1appstoregateonevargateone_install.log)

Installed Packages:
- Universal Search 1.5.1-0316
- Mono 5.20.1.34-18
- Python 2.7.18-25
- Git 2.37.0-23
- File Station 1.2.8-0293
- OAuth Service 1.0.4-0031

Installed Non-working Packages:
- Radarr 20200921-11
- Sonarr 20210329-19
- CouchPotato 20200804-8
- GateOne 20171125-8

### Reproduction steps

```bash
1. Install packages from SynoCommunity in Package Center
```

### Install Log

```log
Attached above
```

### Service Log

```log
Attached above
```

### Other Logs

```log
Attached above
```

**Comment by publicarray** [comment]
Newer Radarr might no longer run on that CPU or DSM version natively: `Aborted                 (core dumped)` 
You can downgrade, update to dsm7 or use official beta packages: https://wiki.servarr.com/synology-packages

Sonarr has a TLS error:
```
Error: SecureChannelFailure (Authentication failed, see inner exception.): 'https://services.sonarr.tv/v1/time' --->
System.Net.WebException: Error: SecureChannelFailure (Authentication failed, see inner exception.) --->
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. --->
System.DllNotFoundException: /volume1/@appstore/mono/lib/../lib/libmono-btls-shared.so

at (wrapper managed-to-native) Mono.Btls.MonoBtlsSslCtx.mono_btls_ssl_ctx_new()
```

Downgrading mono has helped some people: https://github.com/SynoCommunity/spksrc/wiki/Radarr-Sonarr-Lidarr-Jackett

CouchPotato has an issue finding python: `/volume1/@appstore/couchpotatoserver/env/bin/python: No such file or directory`

Same with GateOne: `/volume1/@appstore/gateone/env/bin/python: No such file or directory`

**Comment by hgy59** [comment]
@IzaacJ I am closing this, as several package updates are published meanwhile.
If you are missing some, please create a dedicated issue for each affected package.
Thank you.
