### ISSUE TITLE
Deluge

### ISSUE THREAD

**Issue by foXaCe** [SynoCommunity/spksrc#540]
The project spk deluge is it stop? I am looking for an alternative to transmission and the official client synology

**Comment by schumi2004** [comment]
@Diaoul
Do you know if anything has changed that would give compiling this package a second chance or is it still useless like last year?

**Comment by Diaoul** [comment]
I think if we stick to 5.1 toolchains we can add libtorrent to Python SPK and/or use wheels. So I'd say yes, we can give this package a second chance.

**Comment by Bon3** [comment]
@Diaoul How long time u think it will be before a beta of Deluge will appear in SynoCommunity repo?

**Comment by schumi2004** [comment]
Any progress made already, maybe toolchain 5.2 is easier?

**Comment by schumi2004** [comment]
I accidentally run against these packages, someone already tried them or know them?
Would it be possible to decrypt them and create compile code for it?

http://ssd.dlinkddns.com/pub/synology/deluge/

**Comment by Dr-Bean** [comment]
Success ;) Got a Deluge package with a standalone version of libtorrent (as in: it relies on the Python SPK, but doesn't include Python, as the linked packages above seem to do).
DSM5.0+ only because of multiprocessing in libtorrent.

Unfortunately, I can't get PPC-based arches (qoriq and ppc853x) to work at this time...it seems there's something between boost and libtorrent that just won't work properly with PPC. @Diaoul Do you recall if libtorrent/deluge could be compiled for PPC in the past?

**Comment by Diaoul** [comment]
Nope it couldn't, that's why I didn't want to include libtorrent in Python SPK.

**Comment by Dr-Bean** [comment]
Right. Well, you can take a look at #1911. I'll probably merge/build it in a couple of days, if you don't see anything standing out.
Fyi, we need to swap over the alpine toolchain, the current one is broken when compiling boost/libtorrent.

**Comment by Dr-Bean** [comment]
Merged the PR with 0279f415ad63a7d4030a45d11c33b20c44ca0e43
deluge 1.3.12-2 has been published on the repository as a beta package.

Seeing as this is quite an old ticket, I'm closing it. Let us know if the package works as expected (you can do that in this issue), that way the package has a chance to move out of beta at some point.

Please [open a new issue](https://github.com/SynoCommunity/spksrc/issues/new) if you encounter problems.
If you do, describe which problems you run into, what you did, and what you expected. Consider adding the logfiles (the one shown in Package Center is located at `/usr/local/deluge/var/deluged.log` and the webinterface has a separate log located at `/usr/local/deluge/var/deluge-web.log`. Note that both logs are cleaned after restarting the package.
