### ISSUE TITLE
version_gcc nested using version_* within ifeq not working

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#5401]
### What happened?

The following does not work as expected and always turns into `else`:
```
ifeq ($(call version_ge, $(call version_gcc), 4.9),0)
...
else
...
fi
```

### Reproduction steps

```bash
ifeq ($(call version_ge, $(version_gcc), 7.5),1)
        @$(MSG) 7.5+
else ifeq ($(call version_ge, $(call version_gcc), 4.9),0)
        @$(MSG) 4.9+
else
        @$(MSG) -4.9
endif
```

While playing with the code I came out with a newer version of `version_gcc` that always works such as:
```
version_gcc = $(lastword $(shell grep TC_GCC $(PWD)/work-$(lastword $(subst =, ,$(filter ARCH=%,$(MAKEFLAGS))))-$(lastword $(subst =, ,$(filter TCVERSION=%,$(MAKEFLAGS))))/tc_vars.mk 2>/dev/null))
```

Note that the following call works as expected, making this more strange as it seems to only affect it under `ifeq`:
```
        @$(MSG) check 4.9: [$(call version_ge, $(version_gcc), 4.9)]
        @$(MSG) check 7.5: [$(call version_ge, $(version_gcc), 7.5)]
```

**Comment by th0ma7** [comment]
@hgy59 have you encountered this?

**Comment by hgy59** [comment]
AFAICR I saw such an issue when inverting the if...
My concern, for definition of gcc version dependent package support or gcc version related package dependencies, this solution does not work, as it requires the build (i.e. extraction) of the toolchain is done before.

**Comment by th0ma7** [comment]
Indeed there is such a case but the weird part here is that a direct calls as expected:
```
@$(MSG) check 4.9: [$(call version_ge, $(version_gcc), 4.9)]
```
But when used within a `ifeq` it doesn't anymore...
```
ifeq ($(call version_gcc), 4.9.3)
```

**Comment by th0ma7** [comment]
I found out why... the `ifeq` statement is being re-evaluated multiple times until the actual execution of that specific piece of code.  Playing with debugging output I was able to gather theses states during runtime:
```
1  MAKEFLAGS:  MAKECMDGOALS: spkclean TCVERSION: 5.2 ARCH:  WORK_DIR: /home/spksrc/deluge-th0ma7/spksrc/spk/deluge/work-all  4.9
1  MAKEFLAGS:  MAKECMDGOALS: arch-x64-6.1 TCVERSION: 5.2 ARCH:  WORK_DIR: /home/spksrc/deluge-th0ma7/spksrc/spk/deluge/work-all  4.9
1  MAKEFLAGS: w MAKECMDGOALS: dependency-list TCVERSION: 5.2 ARCH:  WORK_DIR: /home/spksrc/deluge-th0ma7/spksrc/spk/deluge/work-all  4.9
1  MAKEFLAGS: sw MAKECMDGOALS: dependency-flat TCVERSION: 5.2 ARCH:  WORK_DIR: /home/spksrc/deluge-th0ma7/spksrc/spk/deluge/work-all  4.9
1  MAKEFLAGS: w MAKECMDGOALS: build-arch-x64-6.1 TCVERSION: 5.2 ARCH:  WORK_DIR: /home/spksrc/deluge-th0ma7/spksrc/spk/deluge/work-all  4.9
1  MAKEFLAGS: w MAKECMDGOALS:  TCVERSION: 6.1 ARCH: x64 WORK_DIR: /home/spksrc/deluge-th0ma7/spksrc/spk/deluge/work-x64-6.1  4.9
1  MAKEFLAGS: w MAKECMDGOALS:  TCVERSION: 6.1 ARCH: x64 WORK_DIR: /home/spksrc/deluge-th0ma7/spksrc/spk/deluge/work-x64-6.1  4.9
1  MAKEFLAGS: w -- TCVERSION=6.1 ARCH=x64 MAKECMDGOALS:  TCVERSION: 6.1 ARCH: x64 WORK_DIR: /home/spksrc/deluge-th0ma7/spksrc/spk/deluge/work-x64-6.1  4.9
```
In the end finding the appropriate way to always catch the arch & version to assemble the working directory isn't an easy thing (is it even possible?)

**Comment by th0ma7** [comment]
Using the following after `include ../../mk/spksrc.cross-cc.mk` (or `../../mk/spksrc.spk.mk`) works out:
```
ifeq ($(call version_ge, ${TC_GCC}, 7.5),1)
...
else
...
endif
```
