### ISSUE TITLE
Setting SynoCommunity-MONO on the Synology Nas DSM 6.0

### ISSUE THREAD

**Issue by Melania95** [SynoCommunity/spksrc#5403]
Hi everyone, I have installed SynoCommunity-Mono version v5.20.1.34-18, on a Nas Synology DSM 6.0 and the service is ok and working. I would like to try running a simple "Hello word" created with Visual Studio in like "Webapplication1.aspx". Where should I put this file inside MONO? In which folder? Besides, what default port does this version of Mono run on? If I open the file station of the Nas Syology I do not see any folder related to Mono but the service is running perfectly. Maybe I should copy the aspx file with PUTTY software? Help me please I'm confused ... Thanks everyone.
Melania.

**Comment by hgy59** [comment]
The mono package contains the mono runtime only. There is no service provided.
see https://www.mono-project.com/docs/web/aspnet/ for futher information on how to host asp.net applications with mono.

BTW: For new applications you should consider to use dotnet (core).

**Comment by Melania95** [comment]
Thank you for your reply....then i can't run a web application on Synology Nas?
