### ISSUE TITLE
Deluge not supporting https trackers.

### ISSUE THREAD

**Issue by mhertz** [SynoCommunity/spksrc#5420]
I'm relaying an issue with the deluge 2.1.1-15 package reported by 2 synology DSM 7 users on the deluge forum here: https://forum.deluge-torrent.org/viewtopic.php?f=7&t=56270

I'm thinking if there is certificates available under /etc/ssl or not, since everything else seems in check i.e. openssl built with --openssldir=/etc/ssl and libtorrent with crypto=openssl I believe from looks of it, unless mistaken. 

Tracker status error from https trackers in deluge are reported as "Unspecified system error" or "Certificate verify failed", which I can reproduce upon non DSM package whenever not having certificates available or not having built openssl with correct path to them or not supplying env-var pointing to them(SSL_CERT_FILE/DIR)

First responses from me in above linked forum thread I misunderstood the situation and thought you used a libtorrent wheel from pypi as there is well known issue with such(has static openssl where need set env-var yourself to find certificates), but after finding this repo here, then could tell otherwise, sorry.

Thanks alot in advance!

**Comment by th0ma7** [comment]
Can you please provide an example I can test out on my various platforms to reproduce the issue?
Also, can you confirm whether this was a new install or if you tried updating from a previous installation?

**Comment by mhertz** [comment]
I really appreiate your help firstly! :)

It's all https trackers, so easy test is to log into deluge web-UI and add a popular linux iso like latest arch-linux iso, so copy/paste this magnet into deluge: magnet:?xt=urn:btih:c4769d7000244e4cae9c054a83e38f168bf4f69f&dn=archlinux-2022.09.03-x86_64.iso

Then rightclick it and select 'Edit trackers' > 'Add' > 'https://tracker.nanoha.org'. Then with the torrent selected, the bottom status-tab states under 'Tracker status' : 'Unspecified system error'.

Do you see the certificates in place under '/etc/ssl/certs' when ssh'ing into the NAS?

Sorry i'm forwarding this report from 2 others from deluge forum, and so will edit in the answer to your other question(new or updated install) when getting back from them.

Thanks again!

**Comment by th0ma7** [comment]
I'll give that a shot later on over the week-end.  In the meantime, can you please provide the exact DSM7 build number you're running on?  Could it be 7.1.1-42951?

**Comment by mhertz** [comment]
I'll ask and edit in when get answer, as i'm not DSM user. Thanks alot, no rush, when time and motivation permits of-course, and very much appreciated!

I just saw your edit, yes that was one of the error messages, and other is as said 'Unspecified system error'.

As said, i'm suspecting the /etc/openssl/certs dir is missing ca-certificates.crt or other file there - On my distro, then openssl provides that dir empty and then it is ca-certificates-utils that provides ca-certificates and ca-bundle.crt etc. I also read a DSM 6.1 user stating ca-certificates package not included by DSM, but as said 6.1.

**Comment by th0ma7** [comment]
Found a working fix for this, package update upcoming.

**Comment by th0ma7** [comment]
Package now published.  Should show up within the next 24-48h or you can download manually from here: https://synocommunity.com/package/deluge

**Comment by mhertz** [comment]
Thank you so much th0ma7, appreciate you!

**Comment by th0ma7** [comment]
And please confirm that it does solve your issue :)

**Comment by JSWolf** [comment]
> Package now published. Should show up within the next 24-48h or you can download manually from here: https://synocommunity.com/package/deluge

Which version is for Windows?

**Comment by hgy59** [comment]
> Can you please create a Windows version?

Sorry, SynoCommunity is providing packages for Synology Diskstation Devices. Those run a custom Linux by Synology. 
Windows is out of scope here.

**Comment by mhertz** [comment]
@th0ma7 I can confirm now after getting requested feedback and at the risk of repeating myself then i'm really gratefull for your help and I say thank you so much! :)

**Comment by th0ma7** [comment]
A pleasure and glad it works out!  cheers!
