### ISSUE TITLE
ffmpeg download not working

### ISSUE THREAD

**Issue by vespino** [SynoCommunity/spksrc#5421]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

ffmpeg

### Package Version

4.4.2-46

### Device Model

DS1821+

### Device Architecture

x86_64

### Firmware Version

7.1.1-42962

### What happened?

I use ffmpeg to download tv show streams. On DSM 7.1-42661 this used to work fine, but recently I upgraded to 7.1.1-42962 and files downloaded won't play on Kodi.

### Reproduction steps

```bash
/volume1/@appstore/ffmpeg/bin/ffmpeg -y -i "https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Manifest(video,format=m3u8-aapl,filter=Quality,encryption=cbc)" -i "https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Manifest(audioname,format=m3u8-aapl,filter=Quality,encryption=cbc)" -c copy "test2.mp4"

I ran this command on a Synology with DSM 7.1-42661 and on one with 7.1.1-42962. The first does play on Kodi 19.3, the second doesn't.
```

### Install Log

```log
From DSM 7.1-42661
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin preinst
2022/09/09 11:33:03     Begin reload_inst_variables
2022/09/09 11:33:03     End reload_inst_variables
2022/09/09 11:33:03     Begin initialize_variables
2022/09/09 11:33:03     End initialize_variables
2022/09/09 11:33:03     ===> Step preinst. USER= GROUP= SHARE_PATH=
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End preinst ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/mkdir -p /volume1/@appstore/ffmpeg -m 755
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/mkdir -p /volume1/@appstore/ffmpeg -m 755 ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/rm -rf /volume1/@appstore/ffmpeg
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/rm -rf /volume1/@appstore/ffmpeg ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/mv -f /volume1/@tmp/synopkg/install.lQMni6/package /volume1/@appstore/ffmpeg
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/mv -f /volume1/@tmp/synopkg/install.lQMni6/package /volume1/@appstore/ffmpeg ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/rm -rf /var/packages/ffmpeg
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/rm -rf /var/packages/ffmpeg ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/mkdir -p /var/packages/ffmpeg -m 755
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/mkdir -p /var/packages/ffmpeg -m 755 ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/touch /var/packages/ffmpeg/installing
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/touch /var/packages/ffmpeg/installing ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/mv -f /volume1/@tmp/synopkg/install.lQMni6/INFO /var/packages/ffmpeg/INFO
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/mv -f /volume1/@tmp/synopkg/install.lQMni6/INFO /var/packages/ffmpeg/INFO ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/rm -rf /var/packages/ffmpeg/scripts
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/rm -rf /var/packages/ffmpeg/scripts ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/mv -f /volume1/@tmp/synopkg/install.lQMni6/scripts /var/packages/ffmpeg/scripts
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/mv -f /volume1/@tmp/synopkg/install.lQMni6/scripts /var/packages/ffmpeg/scripts ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/rm -rf /var/packages/ffmpeg/WIZARD_UIFILES
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/rm -rf /var/packages/ffmpeg/WIZARD_UIFILES ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/mv -f /volume1/@tmp/synopkg/install.lQMni6/WIZARD_UIFILES /var/packages/ffmpeg/WIZARD_UIFILES
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/mv -f /volume1/@tmp/synopkg/install.lQMni6/WIZARD_UIFILES /var/packages/ffmpeg/WIZARD_UIFILES ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/rm -rf /var/packages/ffmpeg/conf
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/rm -rf /var/packages/ffmpeg/conf ret=[0]
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 Begin /bin/mv -f /volume1/@tmp/synopkg/install.lQMni6/conf /var/packages/ffmpeg/conf
2022/09/09 11:33:03     install ffmpeg 4.4.2-46 End /bin/mv -f /volume1/@tmp/synopkg/install.lQMni6/conf /var/packages/ffmpeg/conf ret=[0]
2022/09/09 11:33:05     install ffmpeg 4.4.2-46 Begin postinst
2022/09/09 11:33:05     Begin reload_inst_variables
2022/09/09 11:33:05     End reload_inst_variables
2022/09/09 11:33:05     Begin initialize_variables
2022/09/09 11:33:05     End initialize_variables
2022/09/09 11:33:05     ===> Step postinst. USER= GROUP= SHARE_PATH=
2022/09/09 11:33:05     Begin save_wizard_variables
2022/09/09 11:33:05     End save_wizard_variables
2022/09/09 11:33:05     Begin syno_sync_var_folder
2022/09/09 11:33:05     End syno_sync_var_folder
2022/09/09 11:33:05     Begin service_postinst
2022/09/09 11:33:05     End service_postinst
2022/09/09 11:33:05     install ffmpeg 4.4.2-46 End postinst ret=[0]
2022/09/09 11:33:05     install ffmpeg 4.4.2-46 Begin start-stop-status start
2022/09/09 11:33:05     install ffmpeg 4.4.2-46 End start-stop-status start ret=[0]

From 7.1.1-42962
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin preinst
2022/09/09 11:29:00     Begin reload_inst_variables
2022/09/09 11:29:00     End reload_inst_variables
2022/09/09 11:29:00     Begin initialize_variables
2022/09/09 11:29:00     End initialize_variables
2022/09/09 11:29:00     ===> Step preinst. USER= GROUP= SHARE_PATH=
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End preinst ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/mkdir -p /volume4/@appstore/ffmpeg -m 755
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/mkdir -p /volume4/@appstore/ffmpeg -m 755 ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/rm -rf /volume4/@appstore/ffmpeg
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/rm -rf /volume4/@appstore/ffmpeg ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/mv -f /volume4/@tmp/synopkg/install.4NOhp0/package /volume4/@appstore/ffmpeg
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/mv -f /volume4/@tmp/synopkg/install.4NOhp0/package /volume4/@appstore/ffmpeg ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/rm -rf /var/packages/ffmpeg
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/rm -rf /var/packages/ffmpeg ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/mkdir -p /var/packages/ffmpeg -m 755
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/mkdir -p /var/packages/ffmpeg -m 755 ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/touch /var/packages/ffmpeg/installing
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/touch /var/packages/ffmpeg/installing ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/mv -f /volume4/@tmp/synopkg/install.4NOhp0/INFO /var/packages/ffmpeg/INFO
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/mv -f /volume4/@tmp/synopkg/install.4NOhp0/INFO /var/packages/ffmpeg/INFO ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/rm -rf /var/packages/ffmpeg/scripts
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/rm -rf /var/packages/ffmpeg/scripts ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/mv -f /volume4/@tmp/synopkg/install.4NOhp0/scripts /var/packages/ffmpeg/scripts
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/mv -f /volume4/@tmp/synopkg/install.4NOhp0/scripts /var/packages/ffmpeg/scripts ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/rm -rf /var/packages/ffmpeg/WIZARD_UIFILES
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/rm -rf /var/packages/ffmpeg/WIZARD_UIFILES ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/mv -f /volume4/@tmp/synopkg/install.4NOhp0/WIZARD_UIFILES /var/packages/ffmpeg/WIZARD_UIFILES
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/mv -f /volume4/@tmp/synopkg/install.4NOhp0/WIZARD_UIFILES /var/packages/ffmpeg/WIZARD_UIFILES ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/rm -rf /var/packages/ffmpeg/conf
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/rm -rf /var/packages/ffmpeg/conf ret=[0]
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 Begin /bin/mv -f /volume4/@tmp/synopkg/install.4NOhp0/conf /var/packages/ffmpeg/conf
2022/09/09 11:29:00     install ffmpeg 4.4.2-46 End /bin/mv -f /volume4/@tmp/synopkg/install.4NOhp0/conf /var/packages/ffmpeg/conf ret=[0]
2022/09/09 11:29:01     install ffmpeg 4.4.2-46 Begin postinst
2022/09/09 11:29:01     Begin reload_inst_variables
2022/09/09 11:29:01     End reload_inst_variables
2022/09/09 11:29:01     Begin initialize_variables
2022/09/09 11:29:01     End initialize_variables
2022/09/09 11:29:01     ===> Step postinst. USER= GROUP= SHARE_PATH=
2022/09/09 11:29:01     Begin save_wizard_variables
2022/09/09 11:29:01     End save_wizard_variables
2022/09/09 11:29:01     Begin syno_sync_var_folder
2022/09/09 11:29:01     End syno_sync_var_folder
2022/09/09 11:29:01     Begin service_postinst
2022/09/09 11:29:01     End service_postinst
2022/09/09 11:29:01     install ffmpeg 4.4.2-46 End postinst ret=[0]
2022/09/09 11:29:01     install ffmpeg 4.4.2-46 Begin start-stop-status start
2022/09/09 11:29:01     install ffmpeg 4.4.2-46 End start-stop-status start ret=[0]
```

**Comment by th0ma7** [comment]
It's interesting that migrating to a newer DSM version resulted in issues with known working `ffmpeg` package.

1. Can you provide the output of `file test2.mp4`
2. Also `ffmpeg -version`
3. Out of curiosity, can you also provide a `ls -la /etc/ssl`
4. And also can you please provide command output of `ffmpeg` call?
I gave it a try on my ubuntu and it didn't worked out:
```
th0ma7@localhost:~$ ffmpeg -y -i "https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Manifest(video,format=m3u8-aapl,filter=Quality,encryption=cbc)" -i "https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Manifest(audioname,format=m3u8-aapl,filter=Quality,encryption=cbc)" -c copy "test2.mp4"
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[hls @ 0x555f7434b780] Skip ('#EXT-X-VERSION:4')
[hls @ 0x555f7434b780] Skip ('#EXT-X-ALLOW-CACHE:NO')
[hls @ 0x555f7434b780] Skip ('#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z')
[hls @ 0x555f7434b780] Opening 'https://keydelivery.rtl.nl/aes/?kid=d3fd85c5-dc30-4703-b8c7-a084ddfc3a7f' for reading
[https @ 0x555f74357cc0] HTTP error 403 Forbidden
[hls @ 0x555f7434b780] Unable to open key file https://keydelivery.rtl.nl/aes/?kid=d3fd85c5-dc30-4703-b8c7-a084ddfc3a7f
[hls @ 0x555f7434b780] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Fragments(video=0,format=m3u8-aapl,encryption=cbc)' for reading
[hls @ 0x555f7434b780] Error when loading first segment 'https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Fragments(video=0,format=m3u8-aapl,encryption=cbc)'
https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Manifest(video,format=m3u8-aapl,filter=Quality,encryption=cbc): Invalid data found when processing input
```

**Comment by vespino** [comment]
1) test2.mp4: ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]

2:

ffmpeg version 4.4.2-46 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 7.5.0 (GCC)
configuration: --target-os=linux --cross-prefix=/github/workspace/toolchain/syno-x64-7.0/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/github/workspace/spk/ffmpeg/work-x64-7.0/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/github/workspace/spk/ffmpeg/work-x64-7.0/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/github/workspace/toolchain/syno-x64-7.0/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-version3 --enable-avresample --disable-debug --disable-static --disable-doc --extra-version=46 --extra-cflags=-DSYNO_VIDEOSTATION --extra-cflags=-fno-if-conversion --extra-cflags=-O3 --extra-cflags=-Wno-deprecated-declarations --enable-libcodec2 --enable-libxml2 --enable-demuxer=dash --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libopenjpeg --enable-libmp3lame --enable-libbluray --enable-libspeex --enable-libtheora --enable-libcaca --enable-libdc1394 --enable-libvorbis --enable-libwebp --enable-libzmq --enable-gnutls --enable-libopus --enable-libsoxr --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librabbitmq --enable-libzvbi --enable-libx264 --enable-libx265 --enable-libvpx --enable-libshine --enable-chromaprint --enable-libdav1d --enable-frei0r --enable-librist --enable-libzimg --enable-libfdk-aac --enable-nonfree --enable-libaom --enable-libsvtav1 --enable-libsvthevc --arch=x86_64 --enable-vaapi --enable-libmfx --enable-libdrm
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100

3)

total 32
drwxr-xr-x  4 root root  4096 Sep  6 11:52 .
drwxr-xr-x 52 root root  4096 Sep 10 00:00 ..
drwxr-xr-x  2 root root 16384 Sep  6 11:53 certs
-rw-r--r--  1 root root  3563 May 12  2020 openssl.cnf
drwxr-xr-x  2 root root  4096 May 12  2020 private

4)

/volume4/@appstore/ffmpeg/bin/ffmpeg -y -i "https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Manifest(video,format=m3u8-aapl,filter=Quality,encryption=cbc)" -i "https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Manifest(audioname,format=m3u8-aapl,filter=Quality,encryption=cbc)" -c copy "test2.mp4"
ffmpeg version 4.4.2-46 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 7.5.0 (GCC)
  configuration: --target-os=linux --cross-prefix=/github/workspace/toolchain/syno-x64-7.0/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/github/workspace/spk/ffmpeg/work-x64-7.0/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/github/workspace/spk/ffmpeg/work-x64-7.0/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/github/workspace/toolchain/syno-x64-7.0/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-version3 --enable-avresample --disable-debug --disable-static --disable-doc --extra-version=46 --extra-cflags=-DSYNO_VIDEOSTATION --extra-cflags=-fno-if-conversion --extra-cflags=-O3 --extra-cflags=-Wno-deprecated-declarations --enable-libcodec2 --enable-libxml2 --enable-demuxer=dash --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libopenjpeg --enable-libmp3lame --enable-libbluray --enable-libspeex --enable-libtheora --enable-libcaca --enable-libdc1394 --enable-libvorbis --enable-libwebp --enable-libzmq --enable-gnutls --enable-libopus --enable-libsoxr --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librabbitmq --enable-libzvbi --enable-libx264 --enable-libx265 --enable-libvpx --enable-libshine --enable-chromaprint --enable-libdav1d --enable-frei0r --enable-librist --enable-libzimg --enable-libfdk-aac --enable-nonfree --enable-libaom --enable-libsvtav1 --enable-libsvthevc --arch=x86_64 --enable-vaapi --enable-libmfx --enable-libdrm
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[hls @ 0x1dfe700] Skip ('#EXT-X-VERSION:4')
[hls @ 0x1dfe700] Skip ('#EXT-X-ALLOW-CACHE:NO')
[hls @ 0x1dfe700] Skip ('#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z')
[hls @ 0x1dfe700] Opening 'https://keydelivery.rtl.nl/aes/?kid=d3fd85c5-dc30-4703-b8c7-a084ddfc3a7f' for reading
[hls @ 0x1dfe700] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Fragments(video=0,format=m3u8-aapl,encryption=cbc)' for reading
Input #0, hls, from 'https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Manifest(video,format=m3u8-aapl,filter=Quality,encryption=cbc)':
  Duration: 01:12:28.28, start: 0.080000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
[hls @ 0x1e3cc00] Skip ('#EXT-X-VERSION:4')
[hls @ 0x1e3cc00] Skip ('#EXT-X-ALLOW-CACHE:NO')
[hls @ 0x1e3cc00] Skip ('#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z')
[hls @ 0x1e3cc00] Opening 'https://keydelivery.rtl.nl/aes/?kid=d3fd85c5-dc30-4703-b8c7-a084ddfc3a7f' for reading
[hls @ 0x1e3cc00] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Fragments(audioname=0,format=m3u8-aapl,encryption=cbc)' for reading
Input #1, hls, from 'https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Manifest(audioname,format=m3u8-aapl,filter=Quality,encryption=cbc)':
  Duration: 01:12:28.33, start: 0.000000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
  Stream #1:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'test3.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls @ 0x1dfe700] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[hls @ 0x1e3cc00] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[hls @ 0x1e3cc00] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Fragments(audioname=100266666,format=m3u8-aapl,encryption=cbc)' for reading
[hls @ 0x1dfe700] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Fragments(video=200000000,format=m3u8-aapl,encryption=cbc)' for reading
[hls @ 0x1e3cc00] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Fragments(audioname=200533333,format=m3u8-aapl,encryption=cbc)' for reading
[hls @ 0x1e3cc00] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Fragments(audioname=300800000,format=m3u8-aapl,encryption=cbc)' for reading
[hls @ 0x1dfe700] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Fragments(video=400000000,format=m3u8-aapl,encryption=cbc)' for reading
[hls @ 0x1e3cc00] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Fragments(audioname=401066666,format=m3u8-aapl,encryption=cbc)' for reading
[hls @ 0x1e3cc00] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Fragments(audioname=501333333,format=m3u8-aapl,encryption=cbc)' for reading
[hls @ 0x1dfe700] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(5859744)/Fragments(video=600000000,format=m3u8-aapl,encryption=cbc)' for reading
[hls @ 0x1e3cc00] Opening 'crypto+https://cdn-rtlvod-h8.akamaized.net/ba232bae-2341-4e1d-a8c7-2908f7620cab/8fc709e3-4fdd-4bf3-967e-2ac75e8062a2.ism/QualityLevels(125368)/Fragments(audioname=601600000,format=m3u8-aapl,encryption=cbc)' for reading
frame= 1578 fps=807 q=-1.0 Lsize=   45785kB time=00:01:03.01 bitrate=5951.7kbits/s speed=32.2x
video:44772kB audio:985kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.060881%
Exiting normally, received signal 2.

I have tried to save the output to a file, but this somehow isn't working, so I have added the first rows, but most of them are the same.

Hope this helps. If you need anything else, let me know.

**Comment by th0ma7** [comment]
At first glance everything is looking good.  I was able to generate a mp4 file using the exact same ffmpeg on my syno box running on DSM 6.2.x.  The file played perfectly well on my ubuntu linux afterwards.

Can you please try to read the resulting file from another player?

**Comment by vespino** [comment]
I did, some did, some didn't play the file. Have you also tried on DSM 7.1.1

**Comment by th0ma7** [comment]
@vespino seems this thread was stalled from my part since quite a while.  Is the issue still existing?  And/or have you looked for answers from upstream ffmpeg project?

**Comment by vespino** [comment]
@th0ma7 yes, I’m still facing this issue.

**Comment by vespino** [comment]
Now running Kodi 20.1 and my issue seems to be resolved.

**Comment by th0ma7** [comment]
Well, glad you found a workaround.  thnx for reporting.

**Comment by vespino** [comment]
@th0ma7 no workaround, I did exactly the same thing I did before and now it works. So I guess there was something with the file Kodi couldn’t handle and they fixed it in the latest version. Can’t say what caused it, could be ffmpeg, could be Kodi.

**Comment by vespino** [comment]
Back again to report I’m having the same issue again. Don’t know what could be causing this, Kodi, the stream, ffmpeg.

**Comment by vespino** [comment]
@th0ma7 when can I expect this to be rolled out on Synology? Currently I'm only seeing version 4.4.3-47.

**Comment by th0ma7** [comment]
I haven't finished the publishing yet.  That should be available within the next 24-48h

**Comment by vespino** [comment]
Still no success.
