### ISSUE TITLE
Jellyfin doesn't start on DS116 (armada385)

### ISSUE THREAD

**Issue by nerojdn** [SynoCommunity/spksrc#5432]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Jellyfin

### Package Version

v10.8.4-7

### Device Model

DS116 (armada 385)

### Device Architecture

ARMv7

### Firmware Version

DSM 6.2.2-24922

### What happened?

Expected behavior
When started, the package status should show status "Installed".

Actual behavior
The package doesn't start and always shows status "Launch" in Package Center.
No Jellyfin process visible using ps -aux

### Reproduction steps

```bash
1. Install Jellyfin package
2. Launch the package
```

### Install Log

```log
<<<< /var/packages/{package}/target/var/{package}_installer.log >>>>

Tue Apr 27 00:17:48 CEST 2021
===> Step preuninst. USER=jellyfin GROUP=sc-media SHARE_PATH=
Tue Apr 27 00:17:53 CEST 2021
===> Step postuninst. USER=jellyfin GROUP=sc-media SHARE_PATH=
Thu Apr 29 17:36:38 CEST 2021
===> Step preinst. USER=jellyfin GROUP=sc-media SHARE_PATH=
Thu Apr 29 17:36:38 CEST 2021
===> Step postinst. USER=jellyfin GROUP=sc-media SHARE_PATH=
Installing service configuration /var/packages/jellyfin/conf/jellyfin.sc
Adding 'sc-jellyfin' to 'sc-media'
Group Name: [sc-media]
Group Type: [AUTH_LOCAL]
Group ID:   [65537]
Group Members: 
0:[admin]
1:[sc-jellyfin]
```

### Service Log

```log
Starting jellyfin command env LD_LIBRARY_PATH=/volume1/@appstore/jellyfin/lib /volume1/@appstore/jellyfin/share/jellyfin --service  --package-name synology  -d /volume1/@appstore/jellyfin/var/data  -C /volume1/@appstore/jellyfin/var/cache  -c /volume1/@appstore/jellyfin/var/config  -l /volume1/@appstore/jellyfin/var/log  -w /volume1/@appstore/jellyfin/web  --ffmpeg /var/packages/ffmpeg/target/bin/ffmpeg
```

**Comment by BenjV** [comment]
On my DS116 with DSM 7.1 Jellyfin is running fine with version 10.8.4-7

**Comment by nerojdn** [comment]
Hi, I've jyst updated my DS116 to DSM 7.1 and everything is okay with last version.
Thanks a lot!

**Comment by mreid-tt** [comment]
With the release of [Jellyfin 10.8.9](https://synocommunity.com/package/jellyfin) to the SynoCommunity repository, it removes all support for 32-bit architectures (includes all ARMv7 archs). As such, I recommend that this ticket be closed as these platforms will no longer be supported moving forward.
