### ISSUE TITLE
[Package Request]  Update borgbackup to borg version 1.2.2

### ISSUE THREAD

**Issue by nylocx** [SynoCommunity/spksrc#5436]
### Software Name

borgbackup

### Brief Description

Borg version 1.2.1 is available as community package. This is only an update request. Thanks for making this package available.

### Website

https://github.com/borgbackup/borg/releases

### Documentation

https://borgbackup.readthedocs.io/en/stable/changes.html#change-log

### Build/Installation documentation

https://borgbackup.readthedocs.io/en/stable/

### Source code

https://github.com/borgbackup/borg

### OpenSource License

other (please specify below)

### Other License

BSD-3-clause

**Comment by peeter123** [comment]
+1, maybe one could also have a look at the msgpack version as borg is complaining:

> Sat 08 Oct 2022 11:33:43 AM CEST Starting backup
> Remote: Using a pure-python msgpack! This will result in lower performance.

Apperantly it makes a lot of performance difference: https://github.com/borgbackup/borg/issues/5219#issuecomment-966686692
