### ISSUE TITLE
Documentation on "Meta: DSM 7 package status" has a typo in a code reference.

### ISSUE THREAD

**Issue by WoosterInitiative** [SynoCommunity/spksrc#5442]
The footnotes on issue #4524 mention using the `mariadb-10` package but have a typo calling it `mariydb-10` instead. To prevent anyone from getting lost, that should probably be fixed.

![image](https://user-images.githubusercontent.com/11821718/193893670-df197eef-3faa-46d6-8834-634dc8928f29.png)

**Comment by hgy59** [comment]
thanks, fixed.
