### ISSUE TITLE
Now Jellyfin decoding is too slow. . .

### ISSUE THREAD

**Issue by zhangbo8418** [SynoCommunity/spksrc#5445]
### Software Name

jellyfin-ffmpeg

### Brief Description

can add
--enable-gmp
--enable-libplacebo
--enable-libshaderc
--enable-opencl
--enable-vulkan?

Now Jellyfin decoding is too slow. . .

### Website

https://github.com/jellyfin/jellyfin-ffmpeg

### Build/Installation documentation

https://github.com/jellyfin/jellyfin-ffmpeg

### Source code

https://github.com/jellyfin/jellyfin-ffmpeg

### OpenSource License

GPLv3

**Comment by th0ma7** [comment]
Can you please explain what your request is about?
- what's your NAS arch?
- version of ffmpeg?
- version of jellyfin
- why do you require opencl & vulkan options?

**Comment by zhangbo8418** [comment]
> Can you please explain what your request is about?
> - what's your NAS arch?
> - version of ffmpeg?
> - version of jellyfin
> - why do you require opencl & vulkan options?

My NAS is 918+
arch x86_64
ffmpeg 4.4.2-46
jellyfin 10.8.5
Because the hardware decodes 3fps, I see jellyfin official ffmpeg official enable opencl & vulkan options

**Comment by zhangbo8418** [comment]
> Can you please explain what your request is about?
> 
> * what's your NAS arch?
> * version of ffmpeg?
> * version of jellyfin
> * why do you require opencl & vulkan options?

fmpeg version 5.1.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers  built with gcc 10 (Debian 10.2.1-6)  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc

**Comment by th0ma7** [comment]
But this is totally unrelated, how are your expecting theses options to enhance x264/hevc decoding or what ever you're trying to decode?

Can you explain what is exactly your trying to do?  what was the prior state and what is the issue you are encoutering now?

**Comment by zhangbo8418** [comment]
> But this is totally unrelated, how are your expecting theses options to enhance x264/hevc decoding or what ever you're trying to decode?
> 
> Can you explain what is exactly your trying to do?  what was the prior state and what is the issue you are encoutering now?

You can try, Jellyfin on Docker and the effect here. . .

**Comment by zhangbo8418** [comment]
> But this is totally unrelated, how are your expecting theses options to enhance x264/hevc decoding or what ever you're trying to decode?
> 
> Can you explain what is exactly your trying to do?  what was the prior state and what is the issue you are encoutering now?

The ffmpeg here is only 30fps using Jellyfin, the ffmpeg replacement of emby is 140fps, and Jellyfin10.8.5 is only 3fps using the ffmpeg here

**Comment by th0ma7** [comment]
can you please explaine what is "here" what setup are you comparing it to?

**Comment by zhangbo8418** [comment]
> can you please explaine what is "here" what setup are you comparing it to?

IQS
![IQS](https://user-images.githubusercontent.com/46797568/196083745-6f1c38b7-af62-4c02-bc7e-a86960752b6a.png)
![FFmpeg For SynoCommunity IQS](https://user-images.githubusercontent.com/46797568/196083780-380655b0-5e50-4069-9699-c953919dde13.png)
![FFmpeg For Emby IQS](https://user-images.githubusercontent.com/46797568/196083820-5aad467a-8bdb-43a4-83f1-a2759d68b703.png)

VAAPI
![VAAPI](https://user-images.githubusercontent.com/46797568/196083896-3fb678c1-ce6c-4e78-a3f7-a2b893435833.png)
![FFmpeg For SynoCommunity VAAPI](https://user-images.githubusercontent.com/46797568/196083927-5128a8f1-3675-47cb-ad14-dfefa55f826b.png)
![FFmpeg For Emby VAAPI](https://user-images.githubusercontent.com/46797568/196083960-a61df992-3f46-45ca-8c71-689643eb1178.png)

Jellyfin10.8.5
![FFmpeg For SynoCommunity](https://user-images.githubusercontent.com/46797568/196084007-2bcdcee0-77a0-4f62-9f6f-177c928c2b4f.png)

**Comment by kuai410022283** [comment]
> Jellyfin10.8.5

Jellyfin10.8.5 
The above problems do exist, and the hard solution of ffmpeg does not take effect in the new version

**Comment by kuai410022283** [comment]
> 您能解释一下“这里”是什么，您正在将其与什么设置进行比较吗？

The above problems do exist, and the hard solution of ffmpeg does not take effect in the new version

**Comment by publicarray** [comment]
@kuai410022283 there is a new ffmpeg version out that may fix this. Are you able to have a look and determine if the problem is still there or fixed ?

**Comment by publicarray** [comment]
Did you try VAAPI? I think it's more stable

**Comment by th0ma7** [comment]
@kuai410022283 for your awareness, there are now new releases of SynoCommunity ffmpeg version 4, 5 and 6 that includes Jellyfin specific patches.

Also, jellyfin package now has proper GPU driver access which should resolve issue in regards to performance when using SynoCommunity ffmpeg.

I invite you to try out output of latest pull request to confirm wether it solves your issue or not:
https://github.com/SynoCommunity/spksrc/actions/runs/4870614890?pr=5711
