### ISSUE TITLE
Rdiff-backup package not installing

### ISSUE THREAD

**Issue by aitecc** [SynoCommunity/spksrc#5460]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

rdiff-backup

### Package Version

2.0.5-4

### Device Model

Synology RS1221RP+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 1

### What happened?

As i try to install the package it says :
rdiff-backup: file format invalid.

### Reproduction steps

```bash
1.i add synocommunity in tha packages repositories
2.i install python
3.i install rdiff-backup and it gives the error
...
```

### Install Log

```log
i don't have any since the package doesn't get installed
```

**Comment by th0ma7** [comment]
Thnx for reporting, It looks like the `x86_64` package for DSM7.x never made it online.  I'll have a look at it and publish the missing packages.

**Comment by th0ma7** [comment]
Updated `rdiff-backup` packages now online https://synocommunity.com/package/rdiff-backup
They should show up in your package center within 48h or you can download & install it manually.
Closing the issue but feel free to reopen if it doesn't work out, cheers!
