### ISSUE TITLE
Failure to publish online

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#5461]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

rdiff-backup

### Package Version

2.x

### Device Model

na

### Device Architecture

x86_64

### Firmware Version

7

### What happened?

While trying to publish missing package for https://github.com/SynoCommunity/spksrc/issues/5460 I've been getting `Internal Server Error` when manually publishing using `make publish-<arch>-<version>.
```
$ http --verify=no --ignore-stdin --auth <mykey>: POST https://api.synocommunity.com/packages @/home/spksrc/master/spksrc/packages/rdiff-backup_x64-7.0_2.0.5-4.spk
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 141
Content-Type: text/html
Date: Fri, 21 Oct 2022 11:01:02 GMT
Server: nginx/1.21.6

<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

### Reproduction steps

```bash
na
```

### Install Log

```log
na
```

**Comment by th0ma7** [comment]
@publicarray you may have a hint on this... is there a filesystem full or something else going on with the server online?

**Comment by publicarray** [comment]
@th0ma7 can you try again? I've updated the server and rebooted.

**Comment by hgy59** [comment]
@th0ma7 remember that there is an error when publishing x64 packages for DSM 7, since the generated filename is too long (I always remove broadwllnkv2 in toolchain/syno-x64-7.0/Makefile from the list of archs as workaround).
see https://github.com/SynoCommunity/spkrepo/issues/86

_@publicarray if you have a free slot: please enlarge the path field in the repo db_

**Comment by publicarray** [comment]
Thanks @hgy59 i totally forgot about that. I'll work on it

**Comment by publicarray** [comment]
@hgy59 @th0ma7 the path length is now a varchar(2048)

**Comment by th0ma7** [comment]
This worked out perfectly fine!  Thnx for the fix @publicarray !
Updated `rdiff-backup` packages now online https://synocommunity.com/package/rdiff-backup
