### ISSUE TITLE
bug in rtd1296-linux-4.4.x.txz

### ISSUE THREAD

**Issue by kursk140** [SynoCommunity/spksrc#5465]
compiling a package  for this arch (in my case "synokernel-usbserial" but I guess this may happen for others) produce this error message:
**/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here**
[build-rtd1296-6.2.4.log](https://github.com/SynoCommunity/spksrc/files/9853936/build-rtd1296-6.2.4.log)
after modifying the file (suppress the 2nd definition of 'yylloc')
/spksrc/distrib/kernel/6.2.4/linux-4.4.x/scripts/dtc/dtc-parser.tab.c_shipped
all is OK and my package runs well on my ds118

Is it the right place to signal this ??

**Comment by th0ma7** [comment]
It is a really good place to start with although cycles are currently limited.  When I'll do have more time I'll convert this into working patch and release a new package.  Thnx for sharing your findings as it may actually solve other archs builds.

**Comment by kursk140** [comment]
I spent so much time trying to communicate via USB between my ds118 and relay cards... 
Reading ttyUSBx was OK, but nothing was writing, despite no error message !
Your driver was compiled with kernel 4.4.59 and I needed **4.4.59+**
So I decided to compile it, and I find spksrc very convenient 
I join the package if it can help
[synokernel-usbserial_rtd1296-6.2.4_1.0-8.spk.gz](https://github.com/SynoCommunity/spksrc/files/9858219/synokernel-usbserial_rtd1296-6.2.4_1.0-8.spk.gz)
Yannick - another french guy...

**Comment by th0ma7** [comment]
That is odd as it should have been 4.4.59+ so there must be something wrong somewhere making this an issue.  I'll follow-up on it.  And Yannick, feel free to join our discord channel where there is also a french channel which can be used as needed.  Cheers!

**Comment by scrapix** [comment]
To anyone who will run into this problem. 

1. open /spksrc/kernel/syno-geminilake-7.0/work/linux/scripts/dtc/dtc-parser.tab.c
2. go to line 1195: "YYLTYPE yylloc"
3. Comment it out or delete it.

This will solve the double definition.

I've encountered the same problem while trying to do:

```
cd /spksrc
make setup
cd /spksrc/kernel/syno-geminilake-7.0
make
cd /spksrc/toolchain/syno-geminilake-7.0
make
cd /spksrc/kernel/syno-geminilake-7.0/work/linux
make prepare
make modules_prepare
```

**Comment by th0ma7** [comment]
@kursk140 and @scrapix you seems to be solving a somewhat similar issue
1. `YYLTYPE yylloc` definition being a) removing the second definition (on `rtd1296`) or b) "uncommenting" the definition (although after testing is actually comment out that definition so it looks like similar to the first approach
2. having an issue with a module not being built for `4.4.59+` kernel.  Although while looking into the details its magic number looks all right `vermagic=4.4.59+ SMP mod_unload aarch64`

**Comment by th0ma7** [comment]
@kursk140 and @scrapix I've now opened-up a PR to patch rtd1296 and geminilake kernels to address this.

**Comment by th0ma7** [comment]
@kursk140  and @scrapix btw just wanted to say thnx as your finding allowed me to fix many other archs.  Next time you use the framework it should be simpler.

**Comment by DougTea** [comment]
It solves my compile problem on kernal modules build.Thks
