### ISSUE TITLE
Package nzbdrone_armada37xx-6.2_20201116-19 won't install on DS120j

### ISSUE THREAD

**Issue by sfreek76** [SynoCommunity/spksrc#5473]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

nzbdrone_armada37xx-6.2_20201116-19

### Package Version

6.2_20201116-19

### Device Model

DS120j

### Device Architecture

ARMv7

### Firmware Version

DSM 7.1.1-42962 Update 2

### What happened?

Can't install this package, it throws error "Invalid File Format"...

### Reproduction steps

```bash
1.Open Package Center
2.Do a manual install of package
3.Error occurs
...
```

### Install Log

```log
since i can't install, there's no log
```

**Comment by bakerboy448** [comment]
Invalid file format makes it sound like you tried downloading the pkg manually and it is corrupt?

**Comment by hgy59** [comment]
> Invalid file format makes it sound like you tried downloading the pkg manually and it is corrupt?

Imvalid file format here indicates, that you want to install a DSM 6.* package on DSM 7.*.

**Comment by bakerboy448** [comment]
Seems this can be closed as a non-bug then given a very old Sonarr EOL unsupported v2 package for DSM6 is attempting to be installed on DSM7?

sonarr v2 (fka nzbdrone) is also very broken and non-functional besides being unsupported and end of life
