### ISSUE TITLE
Unable to install SynoCli Network Tools

### ISSUE THREAD

**Issue by tomhoover** [SynoCommunity/spksrc#5474]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

SynoCli Network Tools

### Package Version

v2.1-12

### Device Model

DS1522+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1-42661 Update 4

### What happened?

**Expected behavior**
Mosh is listed as a package at https://synocommunity.com/package/mosh and should appear in the package center.

**Actual behavior**
Mosh is missing from the package center.

### Reproduction steps

```bash
1. Install SynoCommunity packages per instructions at https://synocommunity.com/#easy-install
2. 'SynoCli Network Tools' doesn't appear in community tab of package center, although other SynoCommunity packages appear and are installable.

NOTE: The package is available for the quad-core Ryzen architecture (v1000), but not for the dual-core Ryzen (r1000) used by the DS1522+.
```

### Install Log

```log
Logs are N/A, as the package is never selectable for installation.
```

**Comment by hgy59** [comment]
similar to #4635, packages must be rebuilt to support the new arch r1000.
