### ISSUE TITLE
[Package Request] 

### ISSUE THREAD

**Issue by Crouchey** [SynoCommunity/spksrc#5482]
### Software Name

Sonarr on DSM7

### Brief Description

Current synocommunity package is out of data and not allowing package to run for Sonarr

When launching, it is throwing this error

The DataMapper was unable to load the following field: 'Languages' value: '[ { "language": 30, "allowed": false }, { "language": 29, "allowed": false }, { "language": 28, "allowed": false }, { "language": 13, "allowed": false }, { "language": 0, "allowed": false }, { "language": 17, "allowed": false }, { "language": 14, "allowed": false }, { "language": 3, "allowed": false }, { "language": 11, "allowed": false }, { "language": 18, "allowed": false }, { "language": 12, "allowed": false }, { "language": 15, "allowed": false }, { "language": 24, "allowed": false }, { "language": 21, "allowed": false }, { "language": 8, "allowed": false }, { "language": 5, "allowed": false }, { "language": 9, "allowed": false }, { "language": 22, "allowed": false }, { "language": 27, "allowed": false }, { "language": 23, "allowed": false }, { "language": 20, "allowed": false }, { "language": 4, "allowed": false }, { "language": 2, "allowed": false }, { "language": 19, "allowed": false }, { "language": 16, "allowed": false }, { "language": 1, "allowed": true }, { "language": 7, "allowed": false }, { "language": 6, "allowed": false }, { "language": 25, "allowed": false }, { "language": 10, "allowed": false }, { "language": 26, "allowed": false } ]'. ID does not match a known language Parameter name: id

### Website

https://synocommunity.com/package/nzbdrone

### Build/Installation documentation

https://synocommunity.com/package/nzbdrone

### Source code

https://synocommunity.com/package/nzbdrone

### OpenSource License

other (please specify below)

### Other License

unknown

**Comment by hgy59** [comment]
@Crouchey please use the "Bug report"  template to create a bug report (and not the "Package request" as you did).

The bug report asks you for relavant information (DSM Version, Arch, etc.) and has prepared fields for error message.
And please provide a meaningfull title.
