### ISSUE TITLE
[Package Request] 

### ISSUE THREAD

**Issue by babyafne** [SynoCommunity/spksrc#5483]
### Software Name

Python

### Brief Description

Whatever Python version half of the packages require that won't install on DSM 7

### Website

https://www.python.org/

### Documentation

https://www.python.org/

### Build/Installation documentation

https://www.python.org/doc/

### Source code

https://www.python.org/downloads/source/

### OpenSource License

BSD-2-clause

**Comment by publicarray** [comment]
This doesn't seam particular helpful. What problem are you having? Maybe fill out the bug ticket instead as there are already multiple python versions available in synocommunity. Mabye try the latest version below?

https://synocommunity.com/package/python
https://synocommunity.com/package/python3
https://synocommunity.com/package/python38
https://synocommunity.com/package/python310
