### ISSUE TITLE
Unable to add SynoCommunity to Package Sources

### ISSUE THREAD

**Issue by ccwillia** [SynoCommunity/spksrc#5503]
When i try to add package source [SynoCommunity](https://packages.synocommunity.com) i get "Invalid Location".  I am using DSM 6.2.3-25426.

**Comment by hgy59** [comment]
Please update to the latest DSM Version (see our [FAQ](https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions))

**Comment by ccwillia** [comment]
Thanks!

**Comment by lemon99ee** [comment]
我在 DSM 6.2.4-25556 Update 7 上遇到同样的错误
