### ISSUE TITLE
[Package Request] add Git LFS to the Git package

### ISSUE THREAD

**Issue by master-hax** [SynoCommunity/spksrc#5528]
### Software Name

Git

### Brief Description

Git LFS (Large File Storage) is an extension for Git that handles large files.

It would be nice to either include this with the current Git package or add it as a separate package. I have tested that it works on my synology with the existing Git package using the binary released [here](https://github.com/git-lfs/git-lfs/releases/tag/v3.3.0)

### Website

https://git-lfs.com/

### Documentation

https://github.com/git-lfs/git-lfs/tree/main/docs?utm_source=gitlfs_site&utm_medium=docs_link&utm_campaign=gitlfs

### Build/Installation documentation

https://github.com/git-lfs/git-lfs/blob/main/README.md

### Source code

https://github.com/git-lfs/git-lfs

### OpenSource License

MIT

**Comment by hgy59** [comment]
@master-hax can you please test the build by github on #5532?

**Comment by master-hax** [comment]
may be a dumb question but how do i do that?

**Comment by hgy59** [comment]
> may be a dumb question but how do i do that?

you can manually install the spk created by github build action.
in the PR #5532 navigate to "Checks - Build - Artifacts" and download the packages for your arch and DSM version (6.x / 7.x). You find the arch of your model in the wiki page [Package-Architectures](https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures). For most of the models we build the package for the `generic` archs `x64` (x86_64), `armv7` and `aarch64`.
Then you unpack the downloaded zip file and in the package center of DSM you install the spk from the file system with "Manual Installation".

The github build artifacts are available for 90 days.
