### ISSUE TITLE
[tvheadend] Can't reinstall package: port already in use

### ISSUE THREAD

**Issue by mattmary** [SynoCommunity/spksrc#5538]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

tvheadend

### Package Version

latest one

### Device Model

DSM918+

### Device Architecture

x86_64

### Firmware Version

7.1.1

### What happened?

Hello,

I try to reinstall the tvheadend package.
I removed it within the package center, and try to install it back from this way.
Unfortunately, after downloading the package I have a popup which tells me that the 9981 port is already in use, either by another service or a system service.
I tried a:
`netstat -anop | grep 9981` but it returned nothing.
I guess something has not been removed when uninstalling the package, but what? 
Can edit my synology, I have root access.
Please help
Kind regards

### Reproduction steps

```bash
1.Install tvheadend package from the package center
2.Uninstall it from the package center
3.Install it back from the package center
...
```

### Install Log

```log
/var/log/packages/tvheadend.log is empty
```

### Service Log

```log
/var/packages/tvheadend/var/tvheadend.log does not exist.
```

### Other Logs

```log
/var/log/synopkg.log

2022/12/27 11:41:35 download tvheadend https://packages.synocommunity.com/tvheadend/34/tvheadend.v34.f41890%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk?arch=apollolake&build=42962 Begin download
2022/12/27 11:42:30 download tvheadend https://packages.synocommunity.com/tvheadend/34/tvheadend.v34.f41890%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk?arch=apollolake&build=42962 End download
2022/12/27 11:42:38 Use given volume to install, volume=[]
2022/12/27 11:42:38 Use any available volume to install, volume=[/volume1]
```
generated log lines when downloading the package
```
022-12-27T10:44:24+13:00 host [Logout MyDS Account] Run Config Backup logout hook
2022-12-27T10:44:24+13:00 host synoactiveinsight[23667]: [Logout MyDS Account] Run ActiveInsight logout hook.
2022-12-27T10:44:26+13:00 host synorelayd[23675]: webvhost.cpp:920 PHP Profile 40e4d6cb-bf06-418d-90cd-57eb89 is not available
2022-12-27T10:44:26+13:00 host synorelayd[23675]: webvhost.cpp:353 Host a2c276f8-4770-406b-afc8-9f0 content is not valid
2022-12-27T10:47:45+13:00 host [Login MyDS Account] Run Config Backup login hook
2022-12-27T10:47:50+13:00 host license_server_login[25037]: api.cpp:436 Required field for decrypt is missing: {"data":{},"errno":0,"status":true}
2022-12-27T10:47:50+13:00 host license_server_login[25037]: user.cpp:43 Failed to logout
2022-12-27T11:04:23+13:00 host synocgid[13260]: session/timeout.cpp:74 admin has session timeout.
2022-12-27T11:12:24+13:00 host secure_login_logger[5837]: prepare.cpp:23 quickconnect is not enabled

```
```

**Comment by hgy59** [comment]
If no service is listening on this port, there is probably a firewall rule still active.
Firewall rule files are name {packagename}.sc.
To solve this, see our [FAQ](https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions) in the wiki and nativgate to the title
**Where are the firewall rule files (*.sc) located and what are there for (Advanced, requires ssh)?**

**Comment by hgy59** [comment]
@publicarray, @th0ma7 we should have an eye on the installer/uninstall functions, as such issues become more frequent.

**Comment by publicarray** [comment]
> @publicarray, @th0ma7 we should have an eye on the installer/uninstall functions, as such issues become more frequent.

If if the firewall rule again I suggest to raise a ticket with Synology. AFAIR on DSM7 and on the DSM6.x it is documented that it will be removed by the system. If thats not the case than they should fix it. It might also be a flaw in one of the scripts when we transitioned to DSM7. Unfortunately it's hard to pinpoint because the scrips evolve and depending on when the package was build it might have gotten a bad script from quite a while ago. I can look if this is still a problem on current master though, so that new builds work as designed.

**Comment by mattmary** [comment]
> If no service is listening on this port, there is probably a firewall rule still active. Firewall rule files are name {packagename}.sc. To solve this, see our [FAQ](https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions) in the wiki and nativgate to the title **Where are the firewall rule files (*.sc) located and what are there for (Advanced, requires ssh)?**

Hello,

Thank you!
I had this firewall .sc file and using your wiki page to remove it solved my problem!
Great reactivity !
thanks

**Comment by mattmary** [comment]
I let you closing this issue (if you want to raise an issue to Synology...)

**Comment by BenjV** [comment]
This is a long standing issue that the uninstaall by the package center now and then leaves this configuration file behind.
Adding this line to every package to be executed during the uninstall phase would solve this for every package.
`servicetool --remove-configure-file --package "${SYNOPKG_PKGNAME}.sc" `

**Comment by mreid-tt** [comment]
> This is a long standing issue that the uninstall by the package center now and then leaves this configuration file behind. So I doubt that Synology will fix this.

It should still be raised as a ticket with them though. With enough  attention and evidence, things do eventually get fixed.

> Adding this line to every package to be executed during the uninstall phase would solve this for every package. `servicetool --remove-configure-file --package "${SYNOPKG_PKGNAME}.sc" `

But wouldn't that require `sudo` privileges? If so doesn't DSM7 restrict `root` access to 3rd party packages? Even more reason for Synology to address this.

**Comment by BenjV** [comment]
The problem is, is that it is not reproduceble, so Synology does not act on this issue.
The normal  behavoir is that the package centrum does it correctly.

I am not sure if you need root privs to use the servicetool command, but if you encounter this issue, you could use the command on the commandline.

**Comment by hgy59** [comment]
nothing planned beside the documentation on how to fix this.
