### ISSUE TITLE
SRM version of Cloudflared not working

### ISSUE THREAD

**Issue by leguennecj** [SynoCommunity/spksrc#5548]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Cloudflared

### Package Version

v2022.12.1-5

### Device Model

MR2200ac

### Device Architecture

ARMv7

### Firmware Version

SRM 1.3.1-9316

### What happened?

I can install the cloudflared package but impossible to start after the token validation.

Package ask for update

### Reproduction steps

```bash
1. Install package
2. Token
3. Try to start
...
```

### Install Log

```log
N/A
```

**Comment by karasevm** [comment]
I validated the built executable runs successfully, so it's probably an issue with SRM specifically. I do not have access to an SRM device and it doesn't seem like I can run it in a VM, so my debugging capabilities are limited. On DSM the logs are stored in `/volume1/@appdata/cloudflared/cloudflared.log`, but I have no idea about the SRM file system. If you could find the logs, I guess they could point us in the right direction.

**Comment by publicarray** [comment]
I narrowed down the problem. In a previous PR arrays where introduced in the startup script. However, this courses problems with the busybox ash shell. @th0ma7 can we keep POSIX support in the scripts (no bashisms)?

```
var/packages/cloudflared/scripts/start-stop-status: line 41: syntax error: bad substitution
/var/packages/cloudflared/scripts/start-stop-status: line 209: declare: not found
```

https://github.com/SynoCommunity/spksrc/pull/5398/commits/7bd6c4c2c92b3e3329ff00c341f850a4ba7fece2

**Comment by th0ma7** [comment]
We probably could but the changes where allowing to manage multiple daemons start, stop and status.  Personally i'd just enforce using bash on srm instead which would be much simpler at no cost and no changes to the adapted logic.

**Comment by publicarray** [comment]
@th0ma7 if bash was installed on the SRM I would be with you but the SRM only has the busybox shell installed by default. :cry:

**Comment by th0ma7** [comment]
That's a pain... because all the reworked logic allows managing multi-daemons and a lot of testing went to ensure it always worked.  The code could probably be adapted to be more POSIX compliant but this functionality must be kept.

Reading a bit, the array structure can be POSIX declared using `set` where it becomes part of the global arg.  Found some interesting info here:  https://www.baeldung.com/linux/posix-shell-array

**Comment by publicarray** [comment]
I guess my question is if supporting the SRM worth it verses the maintenance cost?
Hm :thinking: maybe we can create a bash as a dependency package and ask every SRM owner to install it first.

Thanks @th0ma7, I created a PR here #5570, and I've confirmed that deluge works with this

**Comment by th0ma7** [comment]
Just a thought, could we instead have a start-stop-status specific to srm?

**Comment by publicarray** [comment]
Maybe, wouldn't that just duplicate work?
