### ISSUE TITLE
minio update strategy for new data format

### ISSUE THREAD

**Issue by fgma** [SynoCommunity/spksrc#5549]
I just tried to update the minio package to the current release.  Current versions of minio have changed the way data is stored. Old data will not be accepted when starting as seen in my log an also according to https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html. 

The official migration strategy is described here: https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html

According to this documentation you need to setup a completely new instance with the new backend and transfer your data/users/permissions to the new instance manually using mc.

Currently I have no idea how to handle this for a regular user.

```
Tue Jan  3 23:54:04 CET 2023
Starting minio command /volume1/@appstore/minio/bin/minio server --quiet --console-address :9001 --anonymous /volume1/minio
ERROR Unable to use the drive /volume1/minio: Drive /volume1/minio: found backend type fs, expected xl or xl-single - to migrate to a supported backend visit https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html: Invalid arguments specified
```

**EDIT:** I just tested the latest minio release by creating a new bucket and adding some files on a new installation. The new file format is different and there is no direct mapping of a single file inside a bucket to a single file in the filesystem anymore. So one can't use minio as a simple upload interface reusing the raw bucket data from another program anymore.

**Comment by hgy59** [comment]
We now have published the latest package version  `v2022.10.24-16` that works with deprecated "fs" mode.
Future updates will not work without migration, documented in our wiki: https://github.com/SynoCommunity/spksrc/wiki/MinIO.
