### ISSUE TITLE
[irssi] invalid file format during install

### ISSUE THREAD

**Issue by carnifex82** [SynoCommunity/spksrc#5564]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

irssi

### Package Version

1.2.3-3

### Device Model

DS720+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 1

### What happened?

Trying to install the package, after the download, a popup informs me that the file format is invalid.

![grafik](https://user-images.githubusercontent.com/15661866/212683084-c57cad07-5429-407a-91ce-90d34f0f0bca.png)

### Reproduction steps

```bash
1.Search for irssi in community packages
2.click install, wait
```

### Install Log

```log
There is none (probably because the install never really started?)
```

**Comment by BenjV** [comment]
There is no irssi package for DSM 7, so you are tring to install the DSM 6 version, with this result.

**Comment by carnifex82** [comment]
Oooh .. thank you. 


I don't see any DSM version info in the package center, after your comment I checked the package here: https://synocommunity.com/package/irssi and it indeed just lists dsm 6 Version with the latest release.

So it's not even tagged wrongly it seems DSM7 package center just ignore this somehow.
