### ISSUE TITLE
[Package Request] Subversion Server

### ISSUE THREAD

**Issue by cpm1** [SynoCommunity/spksrc#5565]
### Software Name

Subversion

### Brief Description

Subversion revision control system.

It was officially part up to DSM 6.2.4, but got dropped with DSM 7.0, which is the reason, why [many people](https://community.synology.com/enu/forum/10/post/139090) including myself didn't yet upgrade to DSM 7.0. SVN is still a vital piece of software for many users, so IMO it would be more than worth becoming a package of SynoCommunity.

Many thanks in advance.

### Website

https://subversion.apache.org

### Documentation

https://subversion.apache.org/docs/

### Build/Installation documentation

https://svn.apache.org/repos/asf/subversion/trunk/INSTALL

### Source code

https://svn.apache.org/repos/asf/subversion/

### OpenSource License

Apache

**Comment by hgy59** [comment]
this is WIP in #5296

**Comment by cpm1** [comment]
Ah, cool! Didn't come up in my search for whatever reason, sorry. Will close this issue as duplicate then. Looking forward to SVN on DSM 7 then! 👍
