### ISSUE TITLE
transmission:  no package for r1000 #5561 

### ISSUE THREAD

**Issue by mjpieters** [SynoCommunity/spksrc#5568]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

transmission

### Package Version

 v3.00-20

### Device Model

DS1522+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 3

### What happened?

I was hoping to install transmission, but there is no package for the R1000 arch. I see there is a package for V1000, so presumably it's just because the R1000 arch is newer?

### Reproduction steps

```bash
n/a
```

### Install Log

```log
n/a
```

**Comment by BenjV** [comment]
Yes the R1000 is not(yet) added to the repositary.
You could use Download Station from Synology, that is for torrents also transmission under the hood.

**Comment by hgy59** [comment]
This is published now. Wait up to 48h to see it in the DSM Package Center or download manually
