### ISSUE TITLE
http://packages.synocommunity.com down ?

### ISSUE THREAD

**Issue by dutchdude1966** [SynoCommunity/spksrc#560]
Hi it seems http://packages.synocommunity.com is not available !

Greeting Bart

**Comment by ElCapitano** [comment]
Repo is down . .

**Comment by ScarAce1989** [comment]
Cannot add repo... :/

**Comment by Dr-Bean** [comment]
@ScarAce1989, this is a two year old issue, and it's closed for a reason.
Check https://synocommunity.com/#easy-install for instructions on how to add the repository. If that does not work for you, feel free to open a new issue with proper feedback on what went wrong. If you do, follow the guidelines when reporting an issue: https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issue-content

Locking the issue to prevent further comments.
