### ISSUE TITLE
[Package Request] Java 17 OpenJDK - New LTS Version of Java

### ISSUE THREAD

**Issue by jumafuse** [SynoCommunity/spksrc#5605]
### Software Name

Java 17 OpenJDK

### Brief Description

OpenJDK version 17.0.6+10. OpenJDK 17 is the open-source reference implementation of version 11 of the Java SE Platform as specified by by JSR 392 in the Java Community Process.

Please download the latest JDK17 for x64 Linux from https://adoptium.net/ here: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.6%2B10/OpenJDK17U-jdk_x64_linux_hotspot_17.0.6_10.tar.gz

I would expect that the current Java 11 OpenJDK package is a very good foundation for the JDK17 and only the binaries need to be swapped + links to the new bin applications updated since some have changed.

### Website

http://openjdk.java.net/

### Build/Installation documentation

https://openjdk.org/groups/build/doc/building.html

### Source code

https://github.com/openjdk/jdk

### OpenSource License

GPLv2

**Comment by fuentesjuan** [comment]
@mreid-tt

**Comment by mreid-tt** [comment]
@arnebjarne, @publicarray... looking at the original deployment in #4784 and the subsequent patches in #4858, what would it take to implement this? seems like a lot of patches went into making the build work.

**Comment by arnebjarne** [comment]
Hmm thats 1 1/2 year ago I made the Java11 package, so I cannot remember much. As far as I remember I "just" took a SRPM from Fedora and Synologyzed it.
If no one takes up the task, I can boot up my Synology build system and make a Java 17 package.

**Comment by fuentesjuan** [comment]
I would greatly appreciate if you take on the task @arnebjarne . Is probably going to be to just swap the package and link the new binary tools. I would be more than happy to show some love and provide a bounty.

**Comment by arnebjarne** [comment]
Now I remember why I did not jump into making the Java 17 package. You can only use the same version or the version before to build the version you want. So in order to build Java 17 I need to do this:

Build Java 12.0.1.12 using Java 11
Build Java 13.0.0.27 using Java 12.0.1.12
Build Java 14.0.0.36 using Java 13.0.0.27
Build Java 15.0.0.36 using Java 14.0.0.36
Build Java 16.0.0.36 using Java 15.0.0.36
Build Java 17.0.1.0.12 using Java 16.0.0.36

Can be done. I did it for CentOS 8 armv7hl, but it takes alot of time.

**Comment by fuentesjuan** [comment]
I'm sad to hear is so involved. Hopefully since you know the process I hope is more tedious than difficult.
Here is the mentioned bounty: https://app.bountysource.com/orders/136601

**Comment by hgy59** [comment]
@fuentesjuan it is not so bad. We use the same Java version to build the packages (configure argument `--with-boot-jdk`)
we can build it for DSM >= 7 only, since gcc in the DSM 6 toolchains are too old (requires gcc >= 5.0).

What is your DSM version and arch?

**Comment by fuentesjuan** [comment]
@hgy59 I totally agree, this needs to be done for DSM >= 7.0 and arch x86_64 to have a little bit of bulletproofing and that more people can benefit from this. In my case I have a DS916+ x86_64 Braswell, running 7.1.1 right now. But I may upgrade and of course it will be to another x86_64.

**Comment by mreid-tt** [comment]
hey @fuentesjuan, I've tested the package from @hgy59 and it seems to be working fine (see: https://github.com/SynoCommunity/spksrc/pull/5610#issuecomment-1435954885). You can try it yourself by going to the [Artifacts](https://github.com/SynoCommunity/spksrc/actions/runs/4213666929) in https://github.com/SynoCommunity/spksrc/pull/5610 and downloading the package for your architecture (should be [Packages for x64-7.1](https://github.com/SynoCommunity/spksrc/suites/11067459944/artifacts/562884940)). Once you download it, unzip and install. Let us know how it goes.

**Comment by fuentesjuan** [comment]
I download it and deploy it on my NAS without problems.
I have try do start some JDK17 servers and they seem to work just fine.
As some would say: It works on my computer!

When it will be published?

**Comment by jumafuse** [comment]
An update regarding the ETA to be published would be greatly appreciated. I don't mind it takes weeks, just want to know when you expect it to happen. Thanks in advance for working on this so quickly @arnebjarne @mreid-tt @hgy59 
 rocket rocket rocket rocket rocket rocket rocket rocket rocket rocket rocket rocket rocket rocket rocket rocket rocket rocket

**Comment by hgy59** [comment]
@jumafuse still some testing in progress. I tend to finish it next weekend - if no new issues appear....
