### ISSUE TITLE
[Package Request] mosh-1.4.0

### ISSUE THREAD

**Issue by powerje** [SynoCommunity/spksrc#5614]
### Software Name

Mosh (x64 update)

### Brief Description

Mosh already exists but does not show up for the 1522+ given its arch is R1000 (x64). Please update the mosh package to support x64.

Please see discussion in [Discord](https://discord.com/channels/732558169863225384/732559466721181738/1077255261535871046) for further information.

### Website

https://mosh.org/

### Documentation

https://github.com/mobile-shell/mosh

### Build/Installation documentation

https://github.com/mobile-shell/mosh

### Source code

https://github.com/mobile-shell/mosh

### OpenSource License

GPLv3

**Comment by mreid-tt** [comment]
@powerje, I've created a new PR for mosh-1.4.0 at https://github.com/SynoCommunity/spksrc/pull/5615. You can download one of the test packages from the [Artifacts](https://github.com/SynoCommunity/spksrc/actions/runs/4225178716) section to try it out.
