### ISSUE TITLE
[Package Request] MegaCMD

### ISSUE THREAD

**Issue by skaldenhoven** [SynoCommunity/spksrc#5661]
### Software Name

MegaCMD

### Brief Description

Mega-cmd is the commandline client tool to backup/sync files from your Synology DS to Mega.nz Cloud storage provider.

### Website

https://mega.nz

### Documentation

https://github.com/meganz/MEGAcmd/

### Build/Installation documentation

https://github.com/meganz/MEGAcmd/tree/master/build/SynologyNAS

### Source code

https://github.com/meganz/MEGAcmd

### OpenSource License

GPLv2

**Comment by skaldenhoven** [comment]
I know this has been requested before a couple of times but since Synology is holding back the provided binaries from mega.nz in their own repository it would be very convenient if could be added to the SynoCommunity repo.

**Comment by hgy59** [comment]
@skaldenhoven I already started to build megacmd some time ago.
The current version 1.6.0 does build for DSM 7+ only.
Do you expect to get packages for DSM 6?

**Comment by skaldenhoven** [comment]
@hgy59 for me personally DSM v7+ is sufficient.

**Comment by publicarray** [comment]
Isn't Megacmd already provided through the official package store?

**Comment by skaldenhoven** [comment]
> Isn't Megacmd already provided through the official package store?

Yes but only version 1.4.0 which is from 2021. Since there are quite some fixes in the versions in between and the lack of progress on Synology side of approving the binaries it would be great to have them included in Synocommunity.
See following issues in the meganz project for more clarification that it is difficult to get pre-built packages from Mega or Synology.
https://github.com/meganz/MEGAcmd/issues/619
https://github.com/meganz/MEGAcmd/issues/712

**Comment by romanr** [comment]
Is Synology withholding Mega package 1.6.1? Mega support replied about month ago that package was handed over to Synology.

**Comment by dyuste** [comment]
Hello,
MEGAcmd for NAS (including Synology) can now be found here: https://mega.io/nas

**Comment by skaldenhoven** [comment]
> Hello, MEGAcmd for NAS (including Synology) can now be found here: https://mega.io/nas

Hi Dyuste. Check my comment above. The package is there yes but a really old version and even though newer versions have been submitted to Synology no change yet. So again that is why it would be great to have it included in Synocommunity because of the speed of updates.

**Comment by skaldenhoven** [comment]
You were right that it is now on Mega's site directly. However didn't see it at first since the localized versions of the pages weren't updated yet. When switching manually to English it is there.
So no real need anymore to include it here. Thanks to all for participating.
