### ISSUE TITLE
Dotnet site sub-folder

### ISSUE THREAD

**Issue by Unimbecille** [SynoCommunity/spksrc#5663]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Dotnet

### Package Version

6.0.14-4

### Device Model

DS 920+

### Device Architecture

x86_64

### Firmware Version

7.1.1 42962 Update 4

### What happened?

I have publish a basic site made with Visual Studio asp .net core and launched the string to start the server.
The server goes up at the address I wrote, but the site don't find (and use)the subfolder like the CSS, JS etc..
The string is `/usr/local/bin/dotnet /var/services/homes/admin/Publish/WebTest.dll --urls "http://192.168.0.43:5100"`

### Reproduction steps

1. installed the last version of the package
2. Published the site on a folder in the NAS
3. Creata a task with the string to initialize the site and execute it

### Install Log

```log
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin preinst
2023/03/15 15:24:08	Begin load_variables_from_file
2023/03/15 15:24:08	End load_variables_from_file
2023/03/15 15:24:08	Begin initialize_variables
2023/03/15 15:24:08	End initialize_variables
2023/03/15 15:24:08	===> Step preinst. STATUS=INSTALL USER= GROUP= SHARE_PATH=
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End preinst ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/mkdir -p /volume1/@appstore/dotnet-runtime -m 755
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/mkdir -p /volume1/@appstore/dotnet-runtime -m 755 ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/rm -rf /volume1/@appstore/dotnet-runtime
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/rm -rf /volume1/@appstore/dotnet-runtime ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.i6DHC4/package /volume1/@appstore/dotnet-runtime
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/mv -f /volume1/@tmp/synopkg/install.i6DHC4/package /volume1/@appstore/dotnet-runtime ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/rm -rf /var/packages/dotnet-runtime
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/rm -rf /var/packages/dotnet-runtime ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/mkdir -p /var/packages/dotnet-runtime -m 755
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/mkdir -p /var/packages/dotnet-runtime -m 755 ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/touch /var/packages/dotnet-runtime/installing
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/touch /var/packages/dotnet-runtime/installing ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.i6DHC4/INFO /var/packages/dotnet-runtime/INFO
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/mv -f /volume1/@tmp/synopkg/install.i6DHC4/INFO /var/packages/dotnet-runtime/INFO ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/rm -rf /var/packages/dotnet-runtime/scripts
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/rm -rf /var/packages/dotnet-runtime/scripts ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.i6DHC4/scripts /var/packages/dotnet-runtime/scripts
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/mv -f /volume1/@tmp/synopkg/install.i6DHC4/scripts /var/packages/dotnet-runtime/scripts ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/rm -rf /var/packages/dotnet-runtime/WIZARD_UIFILES
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/rm -rf /var/packages/dotnet-runtime/WIZARD_UIFILES ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.i6DHC4/WIZARD_UIFILES /var/packages/dotnet-runtime/WIZARD_UIFILES
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/mv -f /volume1/@tmp/synopkg/install.i6DHC4/WIZARD_UIFILES /var/packages/dotnet-runtime/WIZARD_UIFILES ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/rm -rf /var/packages/dotnet-runtime/conf
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/rm -rf /var/packages/dotnet-runtime/conf ret=[0]
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.i6DHC4/conf /var/packages/dotnet-runtime/conf
2023/03/15 15:24:08	install dotnet-runtime 6.0.14-4 End /bin/mv -f /volume1/@tmp/synopkg/install.i6DHC4/conf /var/packages/dotnet-runtime/conf ret=[0]
2023/03/15 15:24:11	install dotnet-runtime 6.0.14-4 Begin postinst
2023/03/15 15:24:11	Begin load_variables_from_file
2023/03/15 15:24:11	End load_variables_from_file
2023/03/15 15:24:11	Begin initialize_variables
2023/03/15 15:24:11	End initialize_variables
2023/03/15 15:24:11	===> Step postinst. STATUS=INSTALL USER= GROUP= SHARE_PATH=
2023/03/15 15:24:11	Begin save_wizard_variables
2023/03/15 15:24:11	End save_wizard_variables
2023/03/15 15:24:11	Begin syno_sync_var_folder
2023/03/15 15:24:11	End syno_sync_var_folder
2023/03/15 15:24:11	install dotnet-runtime 6.0.14-4 End postinst ret=[0]
2023/03/15 15:24:12	install dotnet-runtime 6.0.14-4 Begin start-stop-status start
2023/03/15 15:24:12	install dotnet-runtime 6.0.14-4 End start-stop-status start ret=[0]
```

**Comment by mreid-tt** [comment]
I'm not deeply familiar with dotNET and website publishing with this technology. One of the challenges is identifying the problem area. From the one log you have provided, there was no installation error present. There may be some additional detail in the `/var/log/messages` file or in log files specific to dotNET.

Would you be able to provide some more details or sample files for the setup? If so I can try to reproduce the issue on my NAS and examine some of the other log files to help diagnose the issue.

**Comment by Unimbecille** [comment]
> I'm not deeply familiar with dotNET and website publishing with this technology. One of the challenges is identifying the problem area. From the one log you have provided, there was no installation error present. There may be some additional detail in the `/var/log/messages` file or in log files specific to dotNET.
> 
> Would you be able to provide some more details or sample files for the setup? If so I can try to reproduce the issue on my NAS and examine some of the other log files to help diagnose the issue.

[Site.zip](https://github.com/SynoCommunity/spksrc/files/11068851/Site.zip)

This that I have upload is a basic auto-genereted site made with Visual Studio 2022. It work in visual studio and in IIS. If you use the package and run it, the site go up but with error couse don't find the subfolder for CSS, Js and so on...
I connect the NAS with putty and browse to the package folder but haven't find any further log.

Thanks again for the help

**Comment by hgy59** [comment]
@Unimbecille  After updating the appsettings.json to use another port (5002 is already in use on my diskstation) I have no problems running your test app:

added to appsettings.json:
```json
  "Kestrel": {
    "EndPoints": {
      "Http": {
        "Url": "http://0.0.0.0:6002"
      }
    }
  }
```

```
~/dotnet/Sito$  dotnet TestApp.dll
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://0.0.0.0:6002
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /volume1/homes/{myusername}/dotnet/Sito/
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
```

```
$ dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.14
  Architecture: arm64
  Commit:       2a90daa2cc

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/volume1/@appstore/dotnet-runtime/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/volume1/@appstore/dotnet-runtime/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by hgy59** [comment]
@Unimbecille I suppose you need to run the application in the application folder

instead of `/usr/local/bin/dotnet /var/services/homes/admin/Publish/WebTest.dll --urls "http://192.168.0.43:5100"`

use `cd  /var/services/homes/admin/Publish/ && /usr/local/bin/dotnet /var/services/homes/admin/Publish/WebTest.dll --urls "http://192.168.0.43:5100"`

or shorter: `cd /var/services/homes/admin/Publish/ && dotnet ./WebTest.dll --urls "http://192.168.0.43:5100"`

**Comment by Unimbecille** [comment]
> @Unimbecille I suppose you need to run the application in the application folder
> 
> instead of `/usr/local/bin/dotnet /var/services/homes/admin/Publish/WebTest.dll --urls "http://192.168.0.43:5100"`
> 
> use `cd /var/services/homes/admin/Publish/ && /usr/local/bin/dotnet /var/services/homes/admin/Publish/WebTest.dll --urls "http://192.168.0.43:5100"`
> 
> or shorter: `cd /var/services/homes/admin/Publish/ && dotnet ./WebTest.dll --urls "http://192.168.0.43:5100"`

Thanks a lot... Now work everything Perfect :)
