### ISSUE TITLE
[Package Request] Tailscale

### ISSUE THREAD

**Issue by sindastra** [SynoCommunity/spksrc#5664]
### Software Name

Tailscale

### Brief Description

Tailscale lets you easily manage access to private resources, quickly SSH into devices on your network, and work securely from anywhere in the world.

Note: While Synology provides a Tailscale package, they don't provide it for all devices (e.g., in my case, the NVR1218).

### Website

https://tailscale.com/

### Documentation

https://tailscale.com/kb/

### Build/Installation documentation

https://tailscale.com/kb/installation/

### Source code

https://github.com/tailscale/tailscale

### OpenSource License

other (please specify below)

### Other License

BSD-3-Clause

**Comment by kcgthb** [comment]
Tailscale directly provides packages for Synology systems (including ARM7-based ones) for DSM 6 and DSM 7:
https://pkgs.tailscale.com/stable/#spks

**Comment by sindastra** [comment]
Thanks, their download page wasn't so obvious. :D

Their package is broken on my device, but I reported it upstream.

I guess that means this issue can be closed for now. 🙂
