### ISSUE TITLE
SPK Request : Firefox Sync Package

### ISSUE THREAD

**Issue by Nonobis** [SynoCommunity/spksrc#567]
Hi,

Could you add a package to FirefoxSync? As a lot of people, I want to reduce my use of Google services ....

As i saw on the blog of Diaoul, you can install it manually on synology FirefoxSync but a package could be great.

Thanks
##

**Comment by vinpel** [comment]
i've worked on something : 
https://github.com/vinpel/gaspSync

it has the token, sync part and assertion validation. 
Pure PHP.

You still need a Firefox Account, but the rest is stored on you'r server.
i've tested with the desktop version, and it's really experimental and it's as i see it ...

I will be more than happy to have help if you find bug :p

**Comment by Nonobis** [comment]
@Dr-Bean : Hi, any news on FirefoxSync package ?

**Comment by Dr-Bean** [comment]
Firefox Sync Server 1.5.1-1 has been published as a beta package. A wiki article with the most important information is available over [the wiki](https://github.com/SynoCommunity/spksrc/wiki/Firefox-Sync-Server-1.5).
