### ISSUE TITLE
Deluge missing chardet dep.

### ISSUE THREAD

**Issue by mhertz** [SynoCommunity/spksrc#5674]
I'm relaying a report from marcun from the deluge forum, about a plugin not working(yarss2) because errors out with missing chardet dep. On other distro's like arch and ubuntu etc, then python(3)-chardet is a deluge dep, as per directly listed in requirements.txt from upstream. I built a version of the plugin with chardet included directly, but thought to also report here, hope you don't mind.

Thanks in advance.

https://forum.deluge-torrent.org/viewtopic.php?p=236192#p236192 (Includes debug log with the missing dep referenced)

**Comment by th0ma7** [comment]
@mhertz I've created a PR to fix this.  Once the build pipeline finishes would you mind testing out the updated package to confirm it's all good?  https://github.com/SynoCommunity/spksrc/pull/5676/checks

**Comment by mar-cun** [comment]
Hey, a month late and a dollar short, so sorry. But I can confirm (for what it's worth) that this did indeed fix the issue. I was the original reporter that @mhertz helped out! Sorry I didn't see this sooner!
