### ISSUE TITLE
rutorrent settings not saving and always resets back to default

### ISSUE THREAD

**Issue by voidfel** [SynoCommunity/spksrc#5675]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

rutorrent

### Package Version

3.10-13

### Device Model

DS920+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 4

### What happened?

All rutorrent settings (e.g. ports and bandwidth caps) keep resetting back to default if you close the browser tab or restart the app. It's like the settings are not even changing in the first place. I want to track the conf files but I do not even know where they are.

### Reproduction steps

```bash
1. Click Settings blue icon
2. Make any change
3. Close browser window
4. Open ruTorrent again
5. Click Settings blue icon
6. The values are back to the default!
...
```

### Install Log

```log
Nothing wrong with installation..
```

**Comment by smaarn** [comment]
Hello,

This is actually a known limitation with rutorrent which is documented here: https://github.com/Novik/ruTorrent/wiki#some-non-obvious-points

In a nutshell: some settings are actually `rtorrent` settings and are not saved to drive when saving the settings (they are only applied to the currently running instance).

If you want to update those you would need to update the configuration file which is under `/var/packages/rutorrent/var/.rtorrent.rc` or `/var/services/web_packages/rutorrent/conf/rtorrent.rc` (the former being usually a link to the latter).

**Comment by voidfel** [comment]
yes, it worked after updating rtorrent.rc

thanks a lot!
