### ISSUE TITLE
Per folder permissions on DSM 7 for Transmission

### ISSUE THREAD

**Issue by aerojun** [SynoCommunity/spksrc#5683]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Transmission

### Package Version

v4.0.2-21

### Device Model

DS920+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 4

### What happened?

Following the wiki guide for DSM 7 permissions https://github.com/SynoCommunity/spksrc/wiki/Permission-Management giving the Shared folder works just making, making the **sc-transmission** system internal user access the files just fine, but when giving read/write access to only a folder inside the shared folder, tranmission returns an error:
`No data found! Ensure your drives are connected or use "Set Location". To re-download, remove the torrent and re-add it.`

### Reproduction steps

1. Remove permissions for shared folder if it has
2. Give full read/write access to a folder inside the shared folder recursively
3. Error is displayed

### Install Log

```log
Sun Apr  2 20:48:23 CDT 2023
Starting transmission command /volume1/@appstore/transmission/bin/transmission-daemon -g /volume1/@appdata/transmission -x /volume1/@appdata/transmission/transmission.pid -e /volume1/@appdata/transmission/transmission.log
```

**Comment by aerojun** [comment]
Should the `Option 2 - Per folder access` part of the wiki be removed?

> If you give the permission on the share level, all folders created below that share will inherite this permission during creation.

Yeah, I have the downloads folder like that as I posted before.

**Comment by BenjV** [comment]
Not sure, if you do it via the DSM gui like in the wiki I assume it should work also work.
But anything you do on the commandline will not work.

If you start Transmission via the commandline and not from the DSM gui you also get this kind of problems.

**Comment by aerojun** [comment]
> 2\. If you give only traverse and list folders on `downloads` and full read/write on `torrents` to `sc-transmission`, the application gives an error message

It seems that this was the issue. DSM was not saving the shared folder traverse permissions. Restarted the synology and now the permissions were saved and it works.

I'll close the the issue. Thank you.
