### ISSUE TITLE
LIVISI Smart Home Integration for Synology

### ISSUE THREAD

**Issue by hanshorstink** [SynoCommunity/spksrc#5699]
### Software Name

LIVISI Smart Home

### Brief Description

The LIVISI Smart Home integration allows you to connect your LIVISI Smart Home Controller (SHC) to Home Assistant. The SHC can control compatible devices from RWE/innogy connected to it.
See: https://www.home-assistant.io/integrations/livisi/
https://github.com/home-assistant/core/pull/76863

### Website

https://community.livisi.de/lsh-en/

### Documentation

https://community.livisi.de/?l=2

### Build/Installation documentation

https://community.livisi.de/forum/board/59-home-assistant/?l=2

### Source code

https://github.com/home-assistant/core/tree/dev/homeassistant/components/livisi

### OpenSource License

MIT

### Other License

noidea

**Comment by hgy59** [comment]
LIVISI Smart Home is supported with the latest spk release 2023.1.7-20
