### ISSUE TITLE
Home Assistant Core on Synology: Restart stops process and never starts it automatically.

### ISSUE THREAD

**Issue by DarthSonic** [SynoCommunity/spksrc#5704]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Home Assistant Core

### Package Version

2023.1.7

### Device Model

Synology DS216j

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 5

### What happened?

I changed configuration.yaml and restarted Home Assistant Core through the UI. Process on Synology stopped after that but does not restart even after some minutes. I have to start it manually each time.

### Reproduction steps

```bash
1. Click restart in UI
2. Wait until process is stopped on NAS
3. See if process will restart automatically
```

### Install Log

```log
x
```

### Service Log

```log
x
```

### Other Logs

```log
x
```

**Comment by hgy59** [comment]
That is caused by HA it self and cannot be fixed.
You always have to restart HA in the DSM package center.
see https://github.com/SynoCommunity/spksrc/wiki/FAQ-HomeAssistant (Troubleshooting).
