### ISSUE TITLE
Transmission did not remove file from index after delete

### ISSUE THREAD

**Issue by NickNevzorov** [SynoCommunity/spksrc#5705]
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

transmission

### Package Version

4.0.3-22

### Device Model

DS118

### Device Architecture

ARMv5

### Firmware Version

7.1

### What happened?

After downloading torrent via transmission DLNA (via synoindex) updated by new file. 

But after delete torrent and file via transmission index did not updated and in DLNA deleted file are shown

I propose to add runing command "synoindex -d filename" after deleting file

Now I make it by cron one a day:

`synoindex -R type_video`

Tnx

### Reproduction steps

```bash
1. Download torrent via transmission
2. Delete torrent and file via transmission
3. DLNA showing deleted file in index
```

### Install Log

```log
cat transmission.log return empty result
```

**Comment by BenjV** [comment]
This is not posible.
The delete is done by Transmission who does not known anything about synoindex.

**Comment by NickNevzorov** [comment]
@BenjV Tnx, understand
