### ISSUE TITLE
synokernel-usbserial spk to support more ch34x devices

### ISSUE THREAD

**Issue by Ozonys** [SynoCommunity/spksrc#5712]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

synokernel-usbserial

### Package Version

1

### Device Model

ds923+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 5

### What happened?

My ch34x serial device (VID 1a86 PID 7522) is not recognized by this driver, the product id is not in the list in the kernel source file.
I found that the last 4.4.y kernel supports my serial device product id.
The change is minor, could you please add a patch to support these :
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/drivers/usb/serial/ch341.c?id=refs/tags/v4.4.302&id2=refs/tags/v4.4.180
Thanks 
Oz

### Reproduction steps

1. plug ch34x serial with VID 1a86 PID 7522
2. ch341.ko is not loaded
3. the serial device is not available
...

### Install Log

```log
...
```

**Comment by Ozonys** [comment]
Yes I know, but driver source from kernel doesn't support the VID PID I need. More recent kernel sources has it. I just want to apply the patch for the kernel source before building "package".

**Comment by BenjV** [comment]
Ok, so you looking for somebody who can build the kernel module for a AMD Ryzen R1600?

**Comment by Ozonys** [comment]
If the kernel source for R1600 are avaible I can build it myself, but I am not sure yet.

**Comment by BenjV** [comment]
Maybe this helps.
https://github.com/SynoCommunity/spksrc/wiki/FAQ-SynocliKernel-(usbserial,-linuxtv)

**Comment by Ozonys** [comment]
I was successfull building with another method.
https://github.com/robertklep/dsm7-usb-serial-drivers/
It doesn't need the kernel (maybe no dependencies), but directly driver source.
Of course the modification are minors and only about VID / PID.
Also discovered my CP210x devices where not supported...
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/drivers/usb/serial/cp210x.c?id=refs/tags/v4.4.302&id2=refs/tags/v4.4.180

**Comment by hgy59** [comment]
Closing this. @Ozonys found a solution (we still have #5772 open)
