### ISSUE TITLE
[Package Request] xstow

### ISSUE THREAD

**Issue by afoglia** [SynoCommunity/spksrc#5714]
### Software Name

xstow

### Brief Description

xstow is a utility to track package installations easily. It is an alternative to GNU stow.

It's only two command-line executables, so it might not be big enough to warrant its own package. I made a pass at adding it to the synocli-misc package (https://github.com/SynoCommunity/spksrc/compare/master...afoglia:spksrc:xstow). Another possible place is as part of synocli-file. Once you determine where is best for it, I can update my changes.

I tried packaging GNU stow, but I could not figure out how to install the generated perl modules. xstow is smaller and faster anyway.

### Website

https://xstow.sourceforge.net/

### Documentation

https://github.com/majorkingleo/xstow

### Build/Installation documentation

https://github.com/majorkingleo/xstow

### Source code

https://github.com/majorkingleo/xstow

### OpenSource License

GPLv2

**Comment by hgy59** [comment]
@afoglia sorry to tell you, but this is off topic for SynoCommunity. DSM has its own package system and we are providing such (spk) packages.
Other package systems will not work and will always be lost on DSM updates.

**Comment by afoglia** [comment]
I think you are overly scared by the term "package manager". It really just manages symlinks. That's it. To quote the original GNU stow docs "stow is a symlink farm manager." There's no magic stored state. It does not download packages. It just creates and deletes symlinks in a directory.

A non-root user could use it entirely in their own home directory and not touch the system files. In fact, that's how I normally use it. It does not touch system files.

Updates to DSM would not break it when used by normal users, in their home directories.

My apologies for making it sound much bigger than it is.

**Comment by hgy59** [comment]
@afoglia don't give up so fast ... _(you are right, the term **package manager** dazzled me)_ ... feel free to reopen this request.

I have now successfully built xstow (for all archs having a toolchain with c++11 support).

Remarks and Questions
- to include ncurses support I had to patch the configure file (we only support ncursesw but the configure script detects curses and ncurses libs only)
- shall we create the static version? (if yes, I suppose we need xstow-static binary only, what is the merge-info binary for?)
- since this is a very small tool, it is prefered to add it to an existing synocli package. I am unsure whether we should add xstow to synocli-file, synocli-disk or synocli-misc. What would you expect?

**Comment by hgy59** [comment]
> * since this is a very small tool, it is prefered to add it to an existing synocli package. I am unsure whether we should add xstow to synocli-file, synocli-disk or synocli-misc. What would you expect?

OK, you already proposed the synocli-misc package!

**Comment by afoglia** [comment]
For the package, yes, I initially proposed synocli-misc, but I now think synocli-file would be a better fit. Whichever you think fits better.

(Note: My original goal was to use GNU stow, not xstow, but I had problem getting the perl modules packaged. xstow seemed simpler, but it has features I'm unfamiliar with. If you wanted to use stow instead--you probably know how to properly package perl scripts for spks--that would be fine.)

Merge-info looks like it's for merging Info files (e.g. /usr/share/info/dir). This isn't a feature I've ever used, nor is it part of xstow. Few packages use info files anymore. You can drop it until someone else requests it.

As for static vs. dynamic, again, I'll defer to your judgement. I got the dynamic version compiled and running on my device. It doesn't include ncurses, but that's seems to only affect the line wrapping of the --help output. The other dependencies are all low-level.

```
$ ldd /usr/local/bin/xstow                                                                                       
        linux-vdso.so.1 (0x00007ffda1f4b000)
        libstdc++.so.6 => /lib/libstdc++.so.6 (0x00007fcd2db5c000)
        libm.so.6 => /lib/libm.so.6 (0x00007fcd2d857000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00007fcd2d646000)
        libc.so.6 => /lib/libc.so.6 (0x00007fcd2d2a1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fcd2de4d000)
```

I don't see a strong argument for either.

PS: I don't have see option to re-open the issue. Perhaps only contributors can.

**Comment by afoglia** [comment]
Thanks for listening to my request and adding the package.
