### ISSUE TITLE
[owncloud v10.12-9] Can't download 7.0 noarch package

### ISSUE THREAD

**Issue by CrazyJasonwell** [SynoCommunity/spksrc#5717]
### Software Name

owncloud

### Brief Description

I can't download your owncloud package on synology NAS,so want to give me the owncloud spk file to install manully.

### Website

synocummunity.com

### Build/Installation documentation

none

### Source code

none

### OpenSource License

MIT

**Comment by mreid-tt** [comment]
At times the server does not respond due to high load. The dev team is aware of this. You can try again at the location: https://synocommunity.com/package/owncloud

**Comment by CrazyJasonwell** [comment]
thanks for your response, but this link seems   disable ! my synology DSM is 7.0.
Not Found!

SynoCommunity <https://synocommunity.com/package/owncloud>

**Comment by mreid-tt** [comment]
Thanks for the clarification. I'm able to confirm that while the [6.1 noarch](https://packages.synocommunity.com/owncloud/9/owncloud.v9.f15047%5Bnoarch%5D.spk) is available for download the [7.0 noarch](https://packages.synocommunity.com/owncloud/9/owncloud.v9.f40000%5Bnoarch%5D.spk) reports "Not Found". I'll see if we can republish the version and get back to you.

**Comment by mreid-tt** [comment]
@CrazyJasonwell, the package has been re-published and should now be available for download.

**Comment by CrazyJasonwell** [comment]
I got it and finished installation, thank you very much!  but it seems that db is sqlite? how to convert to mysql/mariadb? 

and how to config with webdav access from public network? what is the work port of owncloud server? 

Best regards!


2023年4月30日 04:24，Michael Reid ***@***.***> 写道：

**Comment by mreid-tt** [comment]
> I got it and finished installation, thank you very much! but it seems that db is sqlite? how to convert to mysql/mariadb? and how to config with webdav access from public network? what is the work port of owncloud server?

I'm glad you got the installation to work. Yes, the installation will default to SQLite. The SynoCommunity primarily packages open source software for use on Synology platforms. It does not have the resources to provide application support. I would suggest that you consult with the resources from the original software developer. Here are some links to get you started:

https://doc.owncloud.com/server/10.12/admin_manual/configuration/database/db_conversion.html
https://doc.owncloud.com/webui/next/classic_ui/files/access_webdav.html

**Comment by CrazyJasonwell** [comment]
thanks you again！发自我的 iPhone在 2023年5月1日，13:03，Michael Reid ***@***.***> 写道：﻿
Closed #5717 as completed.
