### ISSUE TITLE
Dotnet 7 package

### ISSUE THREAD

**Issue by evilz** [SynoCommunity/spksrc#5723]
### Software Name

.NET

### Brief Description

@hgy59 can you make a package for .NET 7 version ?

🙏Thank

### Website

https://dotnet.microsoft.com/en-us/download/dotnet/7.0

### Documentation

https://dotnet.microsoft.com/en-us/download/dotnet/7.0

### Build/Installation documentation

https://dotnet.microsoft.com/en-us/download/dotnet/7.0

### Source code

https://dotnet.microsoft.com/en-us/download/dotnet/7.0

### OpenSource License

MIT

**Comment by hgy59** [comment]
@evilz is there a special reason you request .NET 7?
I personally do not want to build a package for .NET 7 but wait for .NET 8 the, next LTS version.

So I could build a package for .NET 8 preview 3.

**Comment by hgy59** [comment]
.NET 7 and .NET 8 will not be supported for DSM 6
The minimal glibc version is 2.23 and DSM 6 devices (and toolchains) have glibc 2.20 only.

**Comment by evilz** [comment]
Oki this why I got issue on manual installation. It it possible to update this dependency?

**Comment by evilz** [comment]
Oki this why I got issue on manual installation. It it possible to update this dependency?

**Comment by evilz** [comment]
Not cool cause even when I compile to native some std lib are requirand it
should come from the same issue.

thank

**Comment by mreid-tt** [comment]
@evilz, is this still a request you wish to pursue or are you okay with waiting for .NET 8 as proposed?

**Comment by evilz** [comment]
Oki to wait for version 8 WE Can close it👍
