### ISSUE TITLE
SynoCLI Network Tools fails to repair/install on DSM 7

### ISSUE THREAD

**Issue by starlilyth** [SynoCommunity/spksrc#5725]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

SynoCLI Network Tools 

### Package Version

2.2-16

### Device Model

DS920+

### Device Architecture

x86_64

### Firmware Version

DSM 7.0-41890

### What happened?

Upgraded from DSM6 to DSM7, SynoCLI Network Tools required repair but fails with the "invalid file format" error. Tried removing and reinstalling, fails with the same error. This package is marked as working with DSM7 on the Meta page. 

### Reproduction steps

1. Attempt to install SynoCLI Network Tools on DSM 7

### Install Log

```log
2023/05/08 07:15:59	(system) trigger synocli-net 2.2-16 Begin start-stop-status stop
2023/05/08 07:15:59	(system) trigger synocli-net 2.2-16 End start-stop-status stop ret=[0]
2023/05/08 13:26:30	uninstall synocli-net 2.2-16 Begin preuninst
2023/05/08 13:26:30	Begin load_variables_from_file
2023/05/08 13:26:30	End load_variables_from_file
2023/05/08 13:26:30	Begin initialize_variables
2023/05/08 13:26:30	End initialize_variables
2023/05/08 13:26:30	===> Step preuninst. STATUS=UNINSTALL USER= GROUP= SHARE_PATH=
2023/05/08 13:26:30	uninstall synocli-net 2.2-16 End preuninst ret=[0]
2023/05/08 13:26:31	uninstall synocli-net 2.2-16 Begin /bin/rm -rf /volume1/@appstore/synocli-net
2023/05/08 13:26:32	uninstall synocli-net 2.2-16 End /bin/rm -rf /volume1/@appstore/synocli-net ret=[0]
2023/05/08 13:26:32	uninstall synocli-net 2.2-16 Begin /bin/rm -rf /volume1/@apptemp/synocli-net
2023/05/08 13:26:32	uninstall synocli-net 2.2-16 End /bin/rm -rf /volume1/@apptemp/synocli-net ret=[0]
2023/05/08 13:26:33	uninstall synocli-net 2.2-16 Begin postuninst
2023/05/08 13:26:33	Begin load_variables_from_file
2023/05/08 13:26:33	End load_variables_from_file
2023/05/08 13:26:33	Begin initialize_variables
2023/05/08 13:26:33	End initialize_variables
2023/05/08 13:26:33	===> Step postuninst. STATUS=UNINSTALL USER= GROUP= SHARE_PATH=
2023/05/08 13:26:33	uninstall synocli-net 2.2-16 End postuninst ret=[0]
```

**Comment by hgy59** [comment]
@starlilyth you need at least DSM 7.1 - otherwise the synocommunity package repository will deliver the package for DSM 6.

@mreid-tt, @Diaoul here is another usecase that for that we should fix https://github.com/SynoCommunity/spkrepo/issues/63 (there are packages of synocli-net for DSM 7.0, but there are newer versions and the repo will deliver the newest package for DSM 6.1 instead of one that is for DSM 7.0)

**Comment by starlilyth** [comment]
> @starlilyth you need at least DSM 7.1 - otherwise the synocommunity package repository will deliver the package for DSM 6.

Sure enough, once I installed the DSM update to 7.1 presented after the upgrade, this package installed without errors.
