### ISSUE TITLE
ffprobe symlink

### ISSUE THREAD

**Issue by gmillerd** [SynoCommunity/spksrc#5729]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

ffmpeg

### Package Version

6.0-2

### Device Model

Synology DS3717xs

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 5

### What happened?

Please include ffprobe in the symlink during install

### Reproduction steps

```ls -l /usr/local/bin | grep /var/packages/ffmpeg6
lrwxrwxrwx  1 root root       39 May 13 22:50 ffmpeg -> /var/packages/ffmpeg6/target/bin/ffmpeg
lrwxrwxrwx  1 root root       40 May 13 22:50 ffmpeg6 -> /var/packages/ffmpeg6/target/bin/ffmpeg6
lrwxrwxrwx  1 root root       39 May 13 22:50 vainfo -> /var/packages/ffmpeg6/target/bin/vainfo
```

#

```ls -l /var/packages/ffmpeg6/target/bin/ff*
-rwxr-xr-x 1 sc-ffmpeg6 synocommunity 312480 May  7 07:00 /var/packages/ffmpeg6/target/bin/ffmpeg
lrwxrwxrwx 1 sc-ffmpeg6 synocommunity      6 May  7 07:00 /var/packages/ffmpeg6/target/bin/ffmpeg6 -> ffmpeg
-rwxr-xr-x 1 sc-ffmpeg6 synocommunity 164344 May  7 07:00 /var/packages/ffmpeg6/target/bin/ffprobe
```

### Install Log

```log
n/a
```

**Comment by th0ma7** [comment]
@gmillerd good idea.  I'll add this during my next round of updates to ffmpeg, probably at the release of 6.0.1 or 6.1.

**Comment by th0ma7** [comment]
@gmillerd sorry for the delay in answering to your request (thnx for @hgy59 for notifying me)

Would you mind testing out latest build of ffmpeg https://github.com/SynoCommunity/spksrc/actions/runs/9587187128
