### ISSUE TITLE
Domoticz failing to run after install

### ISSUE THREAD

**Issue by david284** [SynoCommunity/spksrc#5731]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Domoticz

### Package Version

v2020.2-10

### Device Model

DS216j

### Device Architecture

ARMv7

### Firmware Version

6.2.4-25556 Update 7

### What happened?

The package installs fine, but when selected to run, it just reports it fails to run
I have tried uninstalling, rebooting the NAS, and re-installing, with the same results

[domitcz.edited.log](https://github.com/SynoCommunity/spksrc/files/11485248/domitcz.edited.log)

### Reproduction steps

1. 
2. 
3. 
...
Install Domoticz

### Install Log

```log
Installation log: /var/log/packages/domoticz.log
```

**Comment by hgy59** [comment]
@david284 thanks for reporting this. 
I found and fixed the bug. It is related to DSM 6 (i.e. all DSM <7).
Updated packages will be available as github action artifacts in #5732 before publishing to the SynoCommunity repository.
