### ISSUE TITLE
Synokernel-usbserial not working on Armada38x DSM6.2.4

### ISSUE THREAD

**Issue by david284** [SynoCommunity/spksrc#5743]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Synokernel-usbserial

### Package Version

1.0-7

### Device Model

DS216j

### Device Architecture

ARMv7

### Firmware Version

6.2.4-25556 Update 7

### What happened?

Synokernel-usbserial installs fine, but doesn't appear to actually install any of the expected USB drivers

The expected modules do appear to exist....

root@Synology:/var/packages/synokernel-usbserial/target/lib/modules/armada38x-6.2.4/3.10.105/drivers/usb/serial# ls
ch341.ko  cp210x.ko  ftdi_sio.ko  pl2303.ko  ti_usb_3410_5052.ko  usbserial.ko

But they don't appear in /lib/modules, so don't appear to be loaded

More info that might help...

root@Synology:/etc# uname --all
Linux Synology 3.10.105 #25556 SMP Tue Mar 21 22:22:28 CST 2023 armv7l GNU/Linux synology_armada38x_ds216j

root@Synology:/etc# cat VERSION
majorversion="6"
minorversion="2"
major="6"
minor="2"
micro="4"
productversion="6.2.4"
buildphase="GM"
buildnumber="25556"
smallfixnumber="7"
nano="0"
base="25556"
builddate="2023/04/21"
buildtime="19:34:48"

### Reproduction steps

Install Synokernel-usbserial from package center

### Install Log

```log
2023/05/23 10:34:41     install synokernel-usbserial 1.0-7 Begin preinst
2023/05/23 10:34:41     Begin reload_inst_variables
2023/05/23 10:34:41     End reload_inst_variables
2023/05/23 10:34:41     Begin initialize_variables
2023/05/23 10:34:41     End initialize_variables
2023/05/23 10:34:41     ===> Step preinst. USER= GROUP= SHARE_PATH=
2023/05/23 10:34:41     install synokernel-usbserial 1.0-7 End preinst ret=[0]
2023/05/23 10:34:41     install synokernel-usbserial 1.0-7 Begin /bin/rm -rf /volume1/@appstore/synokernel-usbserial
2023/05/23 10:34:41     install synokernel-usbserial 1.0-7 End /bin/rm -rf /volume1/@appstore/synokernel-usbserial ret=[0]
2023/05/23 10:34:41     install synokernel-usbserial 1.0-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/synokernel-usbserial
2023/05/23 10:34:41     install synokernel-usbserial 1.0-7 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/synokernel-usbserial ret=[0]
2023/05/23 10:34:41     install synokernel-usbserial 1.0-7 Begin /bin/rm -rf /var/packages/synokernel-usbserial
2023/05/23 10:34:41     install synokernel-usbserial 1.0-7 End /bin/rm -rf /var/packages/synokernel-usbserial ret=[0]
2023/05/23 10:34:41     install synokernel-usbserial 1.0-7 Begin /bin/mkdir -p /var/packages/synokernel-usbserial
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 End /bin/mkdir -p /var/packages/synokernel-usbserial ret=[0]
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/synokernel-usbserial/INFO
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/synokernel-usbserial/INFO ret=[0]
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 Begin /bin/rm -rf /var/packages/synokernel-usbserial/scripts
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 End /bin/rm -rf /var/packages/synokernel-usbserial/scripts ret=[0]
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/synokernel-usbserial/scripts
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/synokernel-usbserial/scripts ret=[0]
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 Begin /bin/rm -rf /var/packages/synokernel-usbserial/conf
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 End /bin/rm -rf /var/packages/synokernel-usbserial/conf ret=[0]
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/synokernel-usbserial/conf
2023/05/23 10:34:42     install synokernel-usbserial 1.0-7 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/synokernel-usbserial/conf ret=[0]
2023/05/23 10:34:46     install synokernel-usbserial 1.0-7 Begin postinst
2023/05/23 10:34:46     Begin reload_inst_variables
2023/05/23 10:34:46     End reload_inst_variables
2023/05/23 10:34:46     Begin initialize_variables
2023/05/23 10:34:46     End initialize_variables
2023/05/23 10:34:46     ===> Step postinst. USER= GROUP= SHARE_PATH=
2023/05/23 10:34:46     Begin save_wizard_variables
2023/05/23 10:34:46     End save_wizard_variables
2023/05/23 10:34:46     install synokernel-usbserial 1.0-7 End postinst ret=[0]
2023/05/23 10:34:58     install synokernel-usbserial 1.0-7 Begin start-stop-status start
2023/05/23 10:34:58     install synokernel-usbserial 1.0-7 End start-stop-status start ret=[0]
2023/05/23 10:34:59     install synokernel-usbserial 1.0-7 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2023/05/23 10:35:00     install synokernel-usbserial 1.0-7 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
```

### Other Logs

```log
After install..
```

**Comment by th0ma7** [comment]
@david284 there is documentation available here: https://github.com/SynoCommunity/spksrc/wiki/FAQ-SynocliKernel-(usbserial,-linuxtv)

It probably isn't perfect and loading script would benefit receiving a bit more attention (something I've postponed too often in recent time).

Globally, the SynoCommunity kernel modules cannot be installed in normal `/lib/modules` nor they can be automagically loaded when installed.  This is due to permissions limitations and too high risk of breaking things off.

Therefore, the `usb-serial` modules are located under:
`/var/packages/synokernel-usbserial/target/lib/modules/<cpu>-<dsm-version>/<kernel-version>`

There is a helper script `synocli-kernelmodule.sh` available from the synocli-kernel package available under (along with a few other helper scripts and binaries) `/var/packages/synocli-kernel/target/bin/synocli-kernelmodule.sh`

As you're using DSM 6.2.4 modules should be readily available for you.  Once you've played with the module loading script and obtained what you're looking for you may want to auto-load your modules at boot time.  This can be done with the task schedular using boot-up event to launch the script with needed parameters.

Hope this helps for a start.

**Comment by david284** [comment]
@th0ma7 
Thanks for the reply - I wasn't aware of the FAQ, so will try that - it sounds like it will do what I need

I'm not a linux expert, so don't understand the problems around why the modules aren't loaded in /lib/modules - is there any info on the web explaining this?
I ask as to get the usb working I've manually copied & installed the modules in /lib/modules, and manually changed the permissions on /dev/ttyUSB0 - this now has domoticz up and running with my RFLink module, so would be interested in why this isn't a suitable approach for automatic installation
However, this manual install obviously won't survive a reboot/restart of the NAS - hopefully your FAQ will resolve that issue
I appreciate there must be a good reason, as the Jadahl build of domoticz I was previously using had the USB modules as part of domoticz, and installed the modules into /lib/modules itself, so the modules where lost when I uninstalled that version of domoticz and upgraded to the community version of domoticz

**Comment by david284** [comment]
@th0ma7 
Thanks for the detail explanation - that makes sense
And thanks for supporting this package
I'll try to provide some screenshots when I try it, but it might be a little while, as I have another project that needs attention for a presentation

**Comment by th0ma7** [comment]
@david284 is this still an issue or can this be closed?

**Comment by david284** [comment]
Yes, please close this, I understand the reason
