### ISSUE TITLE
Add bsblk

### ISSUE THREAD

**Issue by leonpano2006** [SynoCommunity/spksrc#5747]
Please add bsblk into synocli-misc package

**Comment by hgy59** [comment]
@leonpano2006 i suppose you mean `lsblk` from bsblk in util-linux? This is now added in #5748

**Comment by leonpano2006** [comment]
Ok
I created because someone told me to create a issue here

**Comment by hgy59** [comment]
> Ok
> I created because someone told me to create a issue here

Ok, the original request in discord was for lsblk by a user called leonpano (I thought this was you).
