### ISSUE TITLE
[Package Request] zramctl

### ISSUE THREAD

**Issue by leonpano2006** [SynoCommunity/spksrc#5749]
### Software Name

unsure (on exist package)

### Brief Description

zramctl is not exist on synology but zram exists on synology
add zramctl

### Website

N/A

### Build/Installation documentation

i am not sure

### Source code

i am not sure

### OpenSource License

GPLv2

**Comment by publicarray** [comment]
Documentation: https://www.man7.org/linux/man-pages/man8/zramctl.8.html
Source: https://www.kernel.org/pub/linux/utils/util-linux/
Name: util-linux

**Comment by hgy59** [comment]
@leonpano2006 what do you need `zramctl` for?

Just to mention that there is no systemctl (systemd) running on DSM. 
What is it worth for to have `zramctl` as command line tool?

**Comment by leonpano2006** [comment]
> @leonpano2006 what do you need `zramctl` for?
> 
> 
> 
> Just to mention that there is no systemctl (systemd) running on DSM. 
> 
> What is it worth for to have `zramctl` as command line tool?
> 
> 

Synology have zram but there is no really a tool to see info
