### ISSUE TITLE
SABnzbd resets port number in Syno config file

### ISSUE THREAD

**Issue by zaadstra** [SynoCommunity/spksrc#5752]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

SABnzbd

### Package Version

4.0.1-61

### Device Model

DS213+, DS218+

### Device Architecture

x86_64

### Firmware Version

DSM 6.2.4-25556 Update 7

### What happened?

I have changed the port from 8080 to 9200.  When installing an update, the port number is reset to 8080 in the syno environment.
I have to edit /volume1/@appstore/sabnzbd/app/config every time after update, to repair the correct starting of SAB from Package Mamangement (button "Open") and DSM main menu (upper left corner).

Is it possible that the installer checks for a valid config and then reads the configured port, before writing out /volume1/@appstore/sabnzbd/app/config?

### Reproduction steps

1. install an update
2. klick Open or via Main menu
3. port has been reset to 8080, despite SABnzbd still running on it's own configured port
...
fix: edit /volume1/@appstore/sabnzbd/app/config to change port number

### Install Log

```log
* not found in all folders in /var/packages/sabnzbd
no sensible other file spotted or install remarks in sabnzbd.log :-/
```

**Comment by hgy59** [comment]
@zaadstra no, this is not possible. You must use the port that the package is built for. 
The package installs a firewall definition file for this port. If you activate the firewall in DSM you must update the port in this file too (/usr/local/etc/services.d/sabnzbd.sc).
The DSM installer checks whether the port(s) of a package is not already in use (or refuses to install).

If you must use another port, for what reason ever, you can create a virtual host in DSM webstation.

This is by design. All packages have predefined port(s) that cannot be changed without modification of the package itself.

**Comment by zaadstra** [comment]
How is it possible that I change the port then in the SABnzbd program itself, in the user interface (config)? And this just works.
I think SAB works fine on any port, but misses the Syno url setting.

The DS is only visible on local lan, both on default and new port. Not sure if here is a firewall in play.
In DSM (Control Panel - Security) I have the firewall disabled (no tick on the page).

**Comment by BenjV** [comment]
The apps are not made only for DSM so they have often the possibility to change the used port.
The problem is that Synology has its own rules and they decided that it must be fixed per package so DSM can uses it as it sees fit.
The firewall is one of them but there are more and could be extended in the future.
So it is not wise to change the port within an app,"just go with the flow"

**Comment by mreid-tt** [comment]
@zaadstra, can you share your motivation for changing the port number from 8080 to 9200?

**Comment by zaadstra** [comment]
Yes, 8080 is a common port, And I always change ports from common ports.
The package allows it, it all works fine, only a syno config file is reset every time. 
Don't change it if it is already there or just update it correctly. Of course it is a nice to have but ptobably only needs a few lines of code. So it is a suggestion to improve the package. A fix isn't a big deal but the package will be better.
I am not aware of firewall settings or common package restrictions, I thought this was a Synology Community and we all know of the syno quirks. Again, the package works very well and it is just a tiny installer detail to look at. The SABnzbd source is open but it community packages isn;'t afaik.
Perhaps @Safihre knows about the details.

**Comment by mreid-tt** [comment]
If the motivation is to allow for external access to SABnzbd but not to use a common port over the Internet then a more sustainable way would be use the reverse proxy in the DSM. For example, my setup has it publishing my internal server (http://localhost:8080) externally via a domain name (https://nas.mydomain.com:9898).

To set this up you would first have to have your domain pointed to your external IP using DNS and then setup a reverse proxy in the [Login Portal -> Advanced] section. Create a new proxy that looks something like this:

<img width="602" alt="Screenshot 2023-05-28 at 10 26 39 PM" src="https://github.com/SynoCommunity/spksrc/assets/943378/c9ac1666-6941-45eb-afd7-b2336763f352">

This has a number of advantages including leveraging the HTTPS certificate already assigned to the DSM and not having to set this up and maintain it within SABnzbd itself.

While you can edit the port in the package itself there are a few disadvantages. DSM as mentioned above requires each package to declare a fixed port it is associated with. DSM checks this declaration on package installation to ensure that the port is available and not duplicated with other packages. This can be seen in the following line in the SynoCommunity code:

https://github.com/SynoCommunity/spksrc/blob/298e58d2e77b85f8af702b79c02159939e60a2af/spk/sabnzbd/Makefile#L28

If you choose to modify the configuration, the associated firewall declarations will not match and will not work if the firewall is enabled. This is why for each of the SynoCommunity packages, the package port declaration is always set to match the internal application configuration. This can be seen in the following default config code:

https://github.com/SynoCommunity/spksrc/blob/298e58d2e77b85f8af702b79c02159939e60a2af/spk/sabnzbd/src/config.ini#L5

I hope this better explains what is happening with the package as well as the internal SABnzbd application.

**Comment by Safihre** [comment]
Indeed the configuration inside SABnzbd does not get saved to the SynoCommunity configuration. It's not SABnzbd specific, it's the case for every package here. If it was changed, it would have to be fixed for every application seperatly.
I wonder if we even can update that installer file without invalidating the package checksum? I always assumed it's a static file that's not allowed to be dynamic.

**Comment by BenjV** [comment]
Please don't even try to do that!

During installatie DSM is propagating that port number from the installer INFO file to all kinds of locations and use, not only for the firewall.
This will only function correct if after a port change the package is updated and that could only be done by hand via the package center.
 
And with every update of DSM Synology seems to use it for more things.

PS
Of course there is no such thing as a common used port, and changing ports for security reasons is a false security reason and for a hacker no problem at all.

**Comment by hgy59** [comment]
> Indeed the configuration inside SABnzbd does not get saved to the SynoCommunity configuration. It's not SABnzbd specific, it's the case for every package here. If it was changed, it would have to be fixed for every application seperatly. 

Every package should use the user specific settings and keep those on package updates, but the package must overwrite the settings of:
- service port(s)
- log file name and location
- pid file name and location
- ...

If sabnzbget is built like this, a port change like @zaadstra did, would not be possible. To change the port, you would have to manually edit the service-setup file in the installed scripts folder of the package.
And this file gets intentionally overrwriten at each package update.

> I wonder if we even can update that installer file without invalidating the package checksum? I always assumed it's a static file that's not allowed to be dynamic.

You can't. You have to unpack the spk file, update the INFO file and recreate the spk file with the correct checksum.
Or change the spk Makefile and recreate the package...

The repackaging does not work for packages from Synology for DSM 7 anymore, as the spk files are not unpackable anymore (those are encrypted, or signed).

**Comment by Safihre** [comment]
So @zaadstra as I expected it's unfortunately not possible. We get this feature request also often on our forums from Synology users.

**Comment by zaadstra** [comment]
Thanks @Safihre , @hgy59 , @BenjV for the digging and the discussion.
It has shed some light on the internals of the package (system),  I understand.

**Comment by mreid-tt** [comment]
@zaadstra, should we go ahead and close this issue?

**Comment by zaadstra** [comment]
Yup, there are so many no's, this is not going to happen ;-)

**Comment by zaadstra** [comment]
.
