### ISSUE TITLE
[Package Request] Fish (update request)

### ISSUE THREAD

**Issue by b4rlw** [SynoCommunity/spksrc#5753]
### Software Name

Fish

### Brief Description

The last update Fish had was in 2021. There's some CLI options `fish_config theme` for example, that newer versions have.
Would be good to have a newer version available!

### Website

https://fishshell.com

### Build/Installation documentation

https://fishshell.com

### Source code

https://github.com/fish-shell/fish-shell

### OpenSource License

other (please specify below)

### Other License

Multiple, specified in the Github repo.

**Comment by hgy59** [comment]
There is already an update in progress (#5360)
May be it can be bumped to the latest version of fish.

**Comment by b4rlw** [comment]
Cheers, didn't see this!

**Comment by mreid-tt** [comment]
@b4rlw with the publishing of fish v3.6.1-6, could this issue now be closed?
