### ISSUE TITLE
Please add DSM 7.2 kernel

### ISSUE THREAD

**Issue by wsjq5477** [SynoCommunity/spksrc#5756]
After upgrading to 7.2, v2raya cannot be used (there is a dependency on iptables and netfilter, which needs to be recompiled)
So add 7.2 kernel please ~

**Comment by hgy59** [comment]
synology does not provide the sources for DSM 7.1 and DSM 7.2 yet

The newest sources published are 
- 7.0-41890
- 6.2-25556

see: https://archive.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source

**Comment by th0ma7** [comment]
FYI, earlier this week I asked Synology to make available GPL sources, including kernel sources.  The answer I received was positive and (fingers crossed) would include both DSM-7.1 and 7.2.

But don't hold your breath on this as normally they don't provide GPL sources for the latest release until a new release comes in, in which case they may only provide DSM-7.1 sources like they used to in the past.

Let's wait & see.

**Comment by 380121850** [comment]
include synobios ？-------- 原始邮件 --------发件人： Vincent Fortier ***@***.***>日期： 2023年5月28日周日 22:08收件人： SynoCommunity/spksrc ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [SynoCommunity/spksrc] Please add DSM 7.2 kernel (Issue #5756)
FYI, earlier this week I asked Synology to make available GPL sources, including kernel sources.  The answer I received was positive and (fingers crossed) would include both DSM-7.1 and 7.2.
But don't hold your breath on this as normally they don't provide GPL sources for the latest release until a new release comes in, in which case they may only provide DSM-7.1 sources like they used to in the past.
Let's wait & see.

**Comment by sjtuross** [comment]
@th0ma7 It looks like Synology makes 7.2 GPL source available - https://archive.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source/7.2-64570

**Comment by Windman1320** [comment]
This pr #5790 by @th0ma7  may sovle your problem, but not merged yet. Maybe you can checkout the branch and compile it yourself.

**Comment by hgy59** [comment]
@sjtuross, @Windman1320 The PR #5790 is now updated with the real 7.2 Kernel sources that are created on 5 Oct 2023.
Before the PR used the 7.1.1 Kernel sources (and used a patch to adjust the kernel version for 4.4.x kernels).

The PR still needs some validation before merging.
