### ISSUE TITLE
[Package Request] 

### ISSUE THREAD

**Issue by ursus-the-bear** [SynoCommunity/spksrc#5761]
### Software Name

PiHole

### Brief Description

Network-wide ad blocking via your own Linux hardware

### Website

https://pi-hole.net

### Build/Installation documentation

https://github.com/pi-hole/pi-hole/#one-step-automated-install

### Source code

https://github.com/pi-hole/pi-hole

### OpenSource License

other (please specify below)

### Other License

This software is licensed under the European Union Public License (EUPL)

**Comment by hgy59** [comment]
Duplicate of #2501
