### ISSUE TITLE
[Package Request] duperemove

### ISSUE THREAD

**Issue by ChengYen-Tang** [SynoCommunity/spksrc#5787]
### Software Name

duperemove

### Brief Description

Duperemove is a simple tool for finding duplicated extents and submitting them for deduplication.

### Website

https://github.com/markfasheh/duperemove

### Documentation

http://markfasheh.github.io/duperemove/duperemove.html

### Build/Installation documentation

https://github.com/markfasheh/duperemove/blob/master/Makefile

### Source code

https://github.com/markfasheh/duperemove

### OpenSource License

GPLv2

### Other License

https://github.com/markfasheh/duperemove/blob/master/LICENSE.xxhash

**Comment by hgy59** [comment]
@ChengYen-Tang did you see that we already have `jdupes` and `fdupes` tools in our `synocli-file` package?

**Comment by ChengYen-Tang** [comment]
Thank you for your notice

**Comment by ChengYen-Tang** [comment]
Hi @hgy59 ,
I see a [`pr`](https://github.com/SynoCommunity/spksrc/pull/5792) for a new version of SynoCli File Tools, but synocommunity.com is still the [`old package`](https://synocommunity.com/package/synocli-file). When does synocommunity.com usually update packages?

Thanks.

**Comment by hgy59** [comment]
> Hi @hgy59 , I see a [`pr`](https://github.com/SynoCommunity/spksrc/pull/5792) for a new version of SynoCli File Tools, but synocommunity.com is still the [`old package`](https://synocommunity.com/package/synocli-file). When does synocommunity.com usually update packages?

@ChengYen-Tang got errors when building synocli-file. This is fixed now in #5821
