### ISSUE TITLE
[Package Request] bees

### ISSUE THREAD

**Issue by ChengYen-Tang** [SynoCommunity/spksrc#5788]
### Software Name

bees

### Brief Description

bees is a block-oriented userspace deduplication agent designed for large btrfs filesystems. It is an offline dedupe combined with an incremental data scan capability to minimize time data spends on disk from write to dedupe.

### Website

https://github.com/Zygo/bees

### Documentation

https://github.com/Zygo/bees/tree/master/docs

### Build/Installation documentation

https://github.com/Zygo/bees/blob/master/docs/install.md

### Source code

https://github.com/Zygo/bees

### OpenSource License

GPLv3

**Comment by hgy59** [comment]
There is little chance to build bees for DSM.
- min DSM version is 7.1 (gcc 8)
- most toolchains are lacking dependent header file `btrfs_tree.h` (found in x64 and aarch64 toolchains only)
- cross compilation is not supported (there is only a Makefile and no configure step nor autotools provided; build for aarch64 fails with errors, see below)
- meson build support (that probably fixes the cross build) is proposed 1.5 years ago by a PR (but never merged/approved) (see https://github.com/Zygo/bees/pull/211)

Cross compilation errors:
```
/bin/sh: 1: ./crc64: Exec format error
/bin/sh: 1: ./chatter: Exec format error
```

**Comment by ChengYen-Tang** [comment]
okay, thank you.
Do I need to close this issue?

**Comment by rylos** [comment]
You can use bees as a docker container in Synology NAS using root privileges. I'm using it since 1 year ago also in production systems. No issue so far.

**Comment by ChengYen-Tang** [comment]
@rylos, Thanks

**Comment by ChengYen-Tang** [comment]
Hi @rylos,
I see your repository. https://github.com/rylos/bees-docker
Is it possible to directly docker-compose up -d?
My container keeps crashing.
![image](https://github.com/SynoCommunity/spksrc/assets/32535494/48932c4e-a4ff-442b-b8d5-47f806c3c5e8)

**Comment by rylos** [comment]
Hi there,
yes it is possible, have you configured in docker-compose.yml your correct
cachedev device? If you have only one volume it should
be CACHEDEV=cachedev_0

Il giorno ven 21 lug 2023 alle ore 11:53 Kenneth Tang <
***@***.***> ha scritto:

**Comment by ChengYen-Tang** [comment]
Hi rylos,
Thank you for your reminder.
I still get the same error, do I need to set volume in yml?

RyLoS ***@***.***> 於 2023年7月21日 週五 下午8:21 寫道：

**Comment by ChengYen-Tang** [comment]
Thank you, it can be executed normally

**Comment by ChengYen-Tang** [comment]
![image](https://github.com/SynoCommunity/spksrc/assets/32535494/5d10baf6-ac99-47ff-8eb6-9e751f7218b8)

It seems that the encrypted storage space of DSM7.2 is not supported

**Comment by rylos** [comment]
Yes it only works with native btrfs filesystem. I use it with my principal
volume on Synology (not encrypted). Its one year I use it with no problems

Il Sab 22 Lug 2023, 15:54 Kenneth Tang ***@***.***> ha
scritto:
