### ISSUE TITLE
[Package Request]  Firebird DB server

### ISSUE THREAD

**Issue by vitkabele** [SynoCommunity/spksrc#5795]
### Software Name

Firebird

### Brief Description

Firebird is a relational database offering many ANSI SQL standard features that runs on Linux, Windows, MacOS and a variety of Unix platforms. Firebird offers excellent concurrency, high performance, and powerful language support for stored procedures and triggers. It has been used in production systems, under a variety of names, since 1981.

### Website

https://firebirdsql.org/

### Documentation

https://firebirdsql.org/en/firebird-rdbms/

### Build/Installation documentation

https://www.firebirdsql.org/en/building-the-code/

### Source code

https://github.com/FirebirdSQL/firebird

### OpenSource License

other (please specify below)

### Other License

Mozilla Public License

**Comment by hgy59** [comment]
@vitkabele I already tried to build firebird, but it failed to cross compile:
```
checking build system type... i686-pc-linux-gnu
checking for /proc/self/maps... configure: error: cannot check for file existence when cross compiling
make[2]: *** [../../mk/spksrc.configure.mk:57: configure_target] Error 1
```

So instead of building a package for x64 archs only, it would be better to use docker images for firebird.

**Comment by vitkabele** [comment]
Oh yes, I am already past this issue. What you encountered happens when you configure target with `GNU_CONFIGURE = 1`, i.e. if you provide --target and --host options to `./configure`.
Firebird itself has cross builds for e.g. android on aarch64, but you must use `./configure --with-cross-build=...`.
It already works for me, but I still have to install libtomcrypt-dev and libtommath-dev to the container. I work on porting these to native/libtomcrypt and native/libtommath. Then it shouldn't be problem to build at least for x64 and aarch64 models.
Feel free to check my progress at https://github.com/vitkabele/spksrc/tree/firebird

**Comment by vitkabele** [comment]
Hello,
the latest commit in my branch ([b67ab17](https://github.com/vitkabele/spksrc/commit/b67ab174387a29512272f684aa66c01ead6793c8)) now builds the firebird spk fox x64-7.1 architecture. I unfortunately do not posses any x64 Synology, so it would be nice if someone could test the spk before I find some.

**Comment by vitkabele** [comment]
The progress continues in PR #5837
