### ISSUE TITLE
nano package update

### ISSUE THREAD

**Issue by mpalermo73** [SynoCommunity/spksrc#5796]
### Software Name

nano

### Brief Description

`nano` is currently a VERY old version.  Current is `7.2`

```
palermo@nas:~$ nano --version
 GNU nano, version 2.9.8
 (C) 1999-2011, 2013-2018 Free Software Foundation, Inc.
 (C) 2014-2018 the contributors to nano
 Email: nano@nano-editor.org	Web: https://nano-editor.org/
 Compiled options: --disable-libmagic --disable-utf8
```

My Synology DS1019+ now( running DSM 7.2-64570) has been saying the package is "incompatible" with my DSM since 7.0. 

![Screenshot 2023-06-30 at 11 26 27 AM](https://github.com/SynoCommunity/spksrc/assets/133884516/b8f6c39f-d1bf-40cc-b7fc-5bda9437230f)

`nano` still works on the CLI, but obviosuly it not upgrable at all.

### Website

https://www.nano-editor.org

### Documentation

https://www.nano-editor.org/docs.php

### Build/Installation documentation

https://git.savannah.gnu.org/cgit/nano.git/tree/README.hacking

### Source code

https://git.savannah.gnu.org/cgit/nano.git/tree/

### OpenSource License

GPLv3

**Comment by hgy59** [comment]
@mpalermo73 nano 7.2 is already on the way in #5792

**Comment by mpalermo73** [comment]
Sorry about that...  Thank you for the super fast update to my inquiry!
