### ISSUE TITLE
[Package Request] add netcat to synocli-misc

### ISSUE THREAD

**Issue by samip5** [SynoCommunity/spksrc#5805]
### Software Name

synocli-misc

### Brief Description

Add netcat to the package

### Website

https://netcat.sourceforge.net

### Build/Installation documentation

https://netcat.sourceforge.net

### Source code

https://netcat.sourceforge.net

### OpenSource License

other (please specify below)

### Other License

no idea

**Comment by hgy59** [comment]
netcat is candidate to add to synocli-net package.

**Comment by hgy59** [comment]
BTW we already have socat in synocli-net (and I will add `ncat` too)

**Comment by samip5** [comment]
> BTW we already have socat in synocli-net (and I will add `ncat` too)

virt-manager expects netcat to exist for SSH tunneling.
