### ISSUE TITLE
CouchPotato Premissions Error

### ISSUE THREAD

**Issue by scottwio** [SynoCommunity/spksrc#581]
For some reason the renamer will only run once and then I start getting the error 

    [tato.core.plugins.renamer] Download of xxxxxxx.cp(tt1045658) completed!
    [tato.core.plugins.renamer] Renamer is already running, if you see this often, check the logs above for errors.

There's is one error that's showing up a lot in the logs

    [tato.core.plugins.renamer] Failed setting permissions for file:/volume2/Raphael/Films/xxxxx)/xxxxx.mkv, Traceback (most recent call last):
      File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/renamer/main.py", line 515, in moveFile
        os.chmod(dest, Env.getPermission('file'))
    OSError: [Errno 1] Operation not permitted: '/volume2/Raphael/Films/xxxxxx/xxxxx. mkv'

Have I missed something do I need to create a user with the correct permissions or something. Any help would be amazing thanks.

**Comment by Dr-Bean** [comment]
Due to the age of this issue, my own experience with CP, and an apparent lack of 'me too' responses (either here or in the CP thread), I'm going to close this.
