### ISSUE TITLE
COPS

### ISSUE THREAD

**Issue by jlaidlaw86** [SynoCommunity/spksrc#5831]
I have  a synology dsm418 (arm cpu). I Installed COPS and dependencies but i get  a 503 error when i try to launch the web app. what do i need to do?

**Comment by hgy59** [comment]
cops is currently beeing updated in #5817

please provide more info for this issue (DSM version, log files, )
why not using the regular issue template?

**Comment by jlaidlaw86** [comment]
Hey sorry. I dont really know what i am doing. should i post over on #5817? wheres the issue template, and how do I get a log file from my synology?

**Comment by mreid-tt** [comment]
Please log a bug report and not an issue and you will see the template with all the instructions.
