### ISSUE TITLE
sabnzb requesting Python 3.11 when downloading and doesn't find it

### ISSUE THREAD

**Issue by SunDoWneR667** [SynoCommunity/spksrc#5846]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

sabnzb

### Package Version

4.0.3-64

### Device Model

DS-418

### Device Architecture

x86_64

### Firmware Version

DSM 7.2-64570 Update 3

### What happened?

![Screenshot 2023-08-13 184701](https://github.com/SynoCommunity/spksrc/assets/16042418/e4af80a5-08c2-4480-8eb6-b49f8660605b)

When trying to install sabnzb it requires Python 3.11 and can't find it, even when it's already installed (which works fine btw).

### Reproduction steps

1. open Package Center
2. click on the Community tab
3. scroll down to Sabnzb
4. click install
5. error occures

### Install Log

```log
no installation, so no log for that
```

### Service Log

```log
no installation, so no log for that
```

### Other Logs

```log
no installation, so no log for that
```

**Comment by mreid-tt** [comment]
Hmm, provided you have the SynoCommunity setup correctly it should be able to find it. Have you tried [manually downloading](https://synocommunity.com/package/python311) for [your arch](https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model) and installing?

**Comment by olssonlars** [comment]
I had this issue just earlier today as well. Maybe I'm holding it wrong, but SynoCommunity seems to be fine in my setup (DS-1522+). I can see 3.11.4-6, and it installs just fine. But attempting to install sabnzbd fails with the same error @SunDoWneR667 has.

**Comment by SunDoWneR667** [comment]
Think i found the issue ... trying to install sabnzb manually asked me specifically for Python v3.11.4-7 or higher. The Python version available at the repo is Python 3.11 v3.11.4-6

**Comment by hgy59** [comment]
Python  v3.11.4-7 is not yet uploaded and not yet available in the repository.
This will be done soon and is by intention to avoid breaking packages when the python update is installed before the package update is available.

/cc @th0ma7

**Comment by monkiibiz** [comment]
@SunDoWneR667 I can confirm I experience the same behavior. Updating sabnzbd from 4.0.2-62 to 4.0.3-64 using the built-in updater results in the error
`The following packages are missing in the package server. Please contact the Synology support team for help. 
python 311`

Manually installing 4.0.3-64 from the synocommunity repository yields
`Please install the following package(s) before installing this package:
- Pythin 3.11 version 3.11.4-7 or later`

**Comment by Genesis1969** [comment]
Same behavior here also, can't installed due missing Python 3.11 version.

**Comment by th0ma7** [comment]
Now published, should be available within the next 24-48h in your package center or you can download & install manually.

**Comment by SunDoWneR667** [comment]
thx for all the attention to this topic! it was a simple version mismatch python<>sabnzb
