### ISSUE TITLE
Sonarr v3.0.10.1567 loses all configuration details and wipes all files.

### ISSUE THREAD

**Issue by JimBobSquarePants** [SynoCommunity/spksrc#5848]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Sonarr

### Package Version

v3.0.10.1567

### Device Model

DS920+

### Device Architecture

x86_64

### Firmware Version

DSM 7.2-64570 Update 3

### What happened?

as far as I understand it Sonarr updated itself. This has led to two incidences so far where all configuration data has been removed and all media removed also in an unrecoverable manner.

### Reproduction steps

1. Leave the application running
2. Wait
3. Lose 10 years worth of media
...

### Install Log

```log
Weirdly no install log.
```

### Service Log

```log
No service log either
```

**Comment by mreid-tt** [comment]
> OK. Looks like this was triggered by the update to DSM 7.2 v3 is not compatible but nether stopped not was a warning shown.

Okay, so I setup a test environment to replicate this issue. I installed Sonarr v3 (20230217-22) and imported a media library. Then I ran the internal updater to update Sonarr to 3.0.10.1567. Then I did a DSM upgrade from 7.2-64570 Update 1  to 7.2-64570 Update 3 . The NAS rebooted and Sonarr v3 started up without issue and the library was in tact. As such, I could not replicate the issue.

Did you have a chance to look at the log files I mentioned above?

**Comment by JimBobSquarePants** [comment]
Sorry I should have been clearer.

I went from 6.2.4-25556 Update 7. 

I should have been more careful and stopped all the services, but I didn't have any warnings from the DSM. 
I thought Sonarr had performed an update as there was a backup config file created on the same date but now, I'm not so sure as there are no folders under packages called nzbdrone.

**Comment by mreid-tt** [comment]
Thanks for the updated feedback. So I re-created the test first starting with DSM 6.2.4-25556 Update 7 and installed Sonarr v3 (20230217-22) and imported a media library after the internal updater moved to Sonarr to 3.0.10.1567. The DSM would not allow me to perform a direct upgrade to DSM 7.2 and I first had to upgrade to DSM 7.0.1-42218 Update 6. At this point the Sonarr and Mono apps needed repair but this could not be completed (because the newer packages require DSM 7.1). So I continued along performing another upgrade to DSM 7.2-64570 Update 3. At this point the app repair for Sonarr and Mono completed successfully and I was able to run Sonarr. On launch the media library was in tact. I am still unable to replicate the issue.

Were you able to locate the logs I mentioned?

**Comment by hgy59** [comment]
> Sorry I should have been clearer.
> 
> I went from 6.2.4-25556 Update 7.
> 
> I should have been more careful and stopped all the services, but I didn't have any warnings from the DSM. I thought Sonarr had performed an update as there was a backup config file created on the same date but now, I'm not so sure as there are no folders under packages called nzbdrone.

@JimBobSquarePants while the update from DSM 6 to DSM 7 did you ever press `repair` in DSM Package Center?

For such manual repair it is known to loose the package data. See the following Note in our project page https://github.com/SynoCommunity/spksrc:
> ATTENTION: As reported, package configuration settings may be lost following the upgrade to DSM 7 and the execution of a Package repair. Make sure to backup your settings and configuration for your SynoCommunity packages before installation of DSM 7 to facilitate restoration if needed.

As this is done outside of the packages, there is no chance to warn the user by our packages.

@mreid-tt did you press the `repair` button, or did you continue without pressing it?

**Comment by mreid-tt** [comment]
> @mreid-tt did you press the `repair` button, or did you continue without pressing it?

When I landed on DSM 7.0.1 there was an option to repair and I pressed one of the apps (can't recall if it was Mono or Sonarr) but when it failed I remember that we need > DSM 7.1. After upgrading to DSM 7.2 I did repair both apps and all was fine.

**Comment by JimBobSquarePants** [comment]
😔 That "repair" button was the ticket I'm sure. I definitely did that. 

I'm going to have a pour through the source code for Sonarr now to see if I can find the relevant logic that triggered the delete. Missing config or not, performing mass deletes without any form of confirmation is dangerous. 

I'll close this now. Thanks for your help.

**Comment by hgy59** [comment]
> I'm going to have a pour through the source code for Sonarr now to see if I can find the relevant logic that triggered the delete. Missing config or not, performing mass deletes without any form of confirmation is dangerous.

I suppose the code that deleted the data is not in sonnarr but in the spk i.e. the spksrc installer.
If you press retry for a DSM 6 package under DSM 7, it tries to install again. IMO the retry on a DSM 6 package, that is not aware of the new location of the var folder under DSM 7, will delete the previous var folder with all the package data,,,
