### ISSUE TITLE
Transmission download speed have decreased since update to 4.0.4-23

### ISSUE THREAD

**Issue by fixsssator** [SynoCommunity/spksrc#5867]
Since updating to 4.0.4, download speeds have decreased significantly.
I downgraded to the previous version 4.0.3, and it works fine now.

**Comment by mreid-tt** [comment]
@fixsssator, as you have already noted on https://github.com/transmission/transmission/issues/5952, this likely needs to be investigated in the main project. Our wrapping of transmission into an SPK file would have little to do with the behaviour of the application in most cases. As you will note from the PR https://github.com/SynoCommunity/spksrc/pull/5863, the changes from v4.0.3 are literally incorporating the new version along with the changelog and nothing more. As such, we will follow the discussion in https://github.com/transmission/transmission/issues/5952 for a resolution to this.

**Comment by mreid-tt** [comment]
@fixsssator, the upstream issue was reported as completed and based on [this comment](https://github.com/transmission/transmission/pull/5263#issuecomment-1808443684), there should be a v4.0.5 in the first weeks of next month. Once available we will incorporate the update here in SynoCommunity so you can test to confirm if the issue has been resolved.

**Comment by fixsssator** [comment]
@mreid-tt, thank you. 
Amazing news. I hope everything will be fine and it will fixed.
