### ISSUE TITLE
myenergi integration for Home Assistant [Package Request] 

### ISSUE THREAD

**Issue by PaulBrouwers** [SynoCommunity/spksrc#5883]
### Software Name

MyEnergi

### Brief Description

Myenergi is a provider of car chargers (zappi) batterys (libbi) and hotwather boilers (eddi)

### Website

https://github.com/CJNE/ha-myenergi

### Documentation

https://github.com/CJNE/ha-myenergi

### Build/Installation documentation

https://github.com/CJNE/ha-myenergi

### Source code

https://github.com/CJNE/ha-myenergi

### OpenSource License

MIT

**Comment by hgy59** [comment]
@PaulBrouwers  you have to install the HACS integration in HA. Then within HACS you can add the myenergi repository. You need to give HACS access to github repositories therefore (you have to enter a code after providing your github account).
If you have done the above, then you can add myenergi intergration in HA.

Let us know if you need further guidance.
