### ISSUE TITLE
[Package Request] firefox

### ISSUE THREAD

**Issue by master-hax** [SynoCommunity/spksrc#5907]
### Software Name

firefox

### Brief Description

firefox is a browser. it would be cool to have a browser accessible inside the syno web UI. (browser-ception)

### Website

https://www.mozilla.org/en-US/firefox

### Build/Installation documentation

https://firefox-source-docs.mozilla.org/setup/linux_build.html

### Source code

https://hg.mozilla.org/mozilla-central/

### OpenSource License

other (please specify below)

### Other License

MPL 2.0 https://www.mozilla.org/en-US/MPL/

**Comment by hgy59** [comment]
It makes no sense to create a firefox package.
You need a browser to access the DSM UI. Why would you need a web browser within a web browser?

**Comment by master-hax** [comment]
DSM is also accessible via SSH. Firefox can easily be used over SSH using X window forwarding.

**Comment by hgy59** [comment]
> DSM is also accessible via SSH. Firefox can easily be used over SSH using X window forwarding.

There is no X window system available on DSM.
If you want a browser for SSH, you could try the text mode browser [Links](http://links.twibright.com/) that is included in synocli-net.
