### ISSUE TITLE
[Package Request] MKVToolNix - Update from v22 on DSM7 to latest release

### ISSUE THREAD

**Issue by develop7** [SynoCommunity/spksrc#5924]
### Software Name

mkvtoolnix

### Brief Description

MKVToolNix v53 doesn't show up in Package Center, while being advertised as the last available on DSM7, v22 shows (and installs) instead:

![image](https://github.com/SynoCommunity/spksrc/assets/89889/0d22c08e-fbac-434e-bb9c-ca45a4c646c0)

My platform: DS220+ (x86_64) running DSM 7.2-64570 Update 1

**Comment by mreid-tt** [comment]
@develop7, this isn't a bug, the last version of this package published is v22.0.0-2 as per https://synocommunity.com/package/mkvtoolnix. I'll convert this to a request for an updated version of the package

**Comment by hgy59** [comment]
@develop7, sorry for not publishing v53. Meanwhile I have updated to v58 (needs DSM 7.1).
This will be the final version for DSM. Newer versions depend on the QT libraries that do not suit into the spksrc framework.

**Comment by develop7** [comment]
Ohh, I must've misread comments in mkvtoolnix', uh, makefile
