### ISSUE TITLE
[Framework] Install failures for Python packages

### ISSUE THREAD

**Issue by mreid-tt** [SynoCommunity/spksrc#5926]
I've observed some recent issues with Python-based package installations, wherein the installation process fails, but erroneously signals successful completion to users (refer to issues #5884 and #5915). Looking into this, we use wheels to distribute Python packages and based on the [wiki page](https://github.com/SynoCommunity/spksrc/wiki/Using-wheels-to-distribute-Python-packages) there are two steps in the `postinstall` which are executed:

```
    # Create a Python virtualenv
    install_python_virtualenv

    # Install the wheels
    install_python_wheels
```

Digging into each of these functions in turn we find them constructed as follows:

https://github.com/SynoCommunity/spksrc/blob/6d0935e9c7bd16cf0b3a912f80091e5f0306bae3/mk/spksrc.service.installer.functions#L74-L78

I've seen some [evidence](https://github.com/SynoCommunity/spksrc/issues/5915#issuecomment-1805196889) that the pip upgrade fails and this can have a cascading effect on the rest of the install. It may be prudent to add some code to replace the last line:

```
if ! python3 -m pip install --upgrade pip; then
    echo "Error: Python upgrade failed"
    exit 1
fi
```

For the second function we see the following:

https://github.com/SynoCommunity/spksrc/blob/6d0935e9c7bd16cf0b3a912f80091e5f0306bae3/mk/spksrc.service.installer.functions#L93-L102

As with the above recommendation, some error checking may be prudent so that the user is not incorrectly informed of a successful installation.

```
if [ -s ${requirements} ]; then 
    echo "Install packages from wheels [${requirements}]"
    pip install $([ $# -gt 0 ] && echo $*) \
                --force-reinstall \
                --cache-dir ${cachedir} \
                --find-links ${wheelhouse} \
                --requirement ${requirements} \
    || { echo "Error: Python package installation failed"; exit 1; }
fi
```

@hgy59, what do you think of this approach?

**Comment by hgy59** [comment]
> ```
> if [ -s ${requirements} ]; then 
>    echo "Install packages from wheels [${requirements}]"
>    pip install $([ $# -gt 0 ] && echo $*) \
>                --force-reinstall \
>                --cache-dir ${cachedir} \
>                --find-links ${wheelhouse} \
>                --requirement ${requirements} \
>    || { echo "Error: Python package installation failed"; exit 1; }
>fi
> ```
>
> @hgy59, what do you think of this approach?

@mreid-tt did you test the error reporting? I suppose that you have to echo to stderr (`1>&2`)  to display the message at installation time (otherwise it will go to the installer log only).

---

Another issue: probably it is not good to update pip to the latests version at installation time, since pip might have breaking changes since the a package or python is published. To suppress warnings we should use pip parameter `--disable-pip-version-check` then. (/cc @th0ma7).

**Comment by th0ma7** [comment]
Also while at it, if i recall caching only works on dsm7 so it could be disabled (or fixed) for dsm6.

**Comment by mreid-tt** [comment]
@hgy59 @th0ma7, I lack expertise in wheels and Python distributions. I kindly request assistance from someone more knowledgeable to open a pull request for this matter. My intention was solely to propose an approach to enhance the framework's resilience against network download issues when using pip.

**Comment by th0ma7** [comment]
Sigh... Python wheel packaging is a real pain until hopefully one day the python community comes up with some format and tool people agree on...

Anyhow, I may be able to find spare cycles in the coming week to have a look at it and come up with a pr, should be relatively straightforward (@mreid-tt you're already pretty close already).  But in the meantime feel free to take a stab at it and I'll certainly review and test.

Also note that most failures comes up with the lack of support for armv5 and ppc archs which culminated in a few bugs entries.  I still have hope to fix ppc, time will tell.

**Comment by mreid-tt** [comment]
> Anyhow, I may be able to find spare cycles in the coming week to have a look at it and come up with a pr, should be relatively straightforward (@mreid-tt you're already pretty close already). But in the meantime feel free to take a stab at it and I'll certainly review and test.

I've made a PR based on the some of the conversation above. Welcome you your review and amendments.
