### ISSUE TITLE
[Package Request] iPerf

### ISSUE THREAD

**Issue by stephane-archer** [SynoCommunity/spksrc#5940]
### Software Name

iPerf

### Brief Description

iPerf3 is a tool for active measurements of the maximum achievable bandwidth on IP networks

### Website

https://iperf.fr/

### Build/Installation documentation

https://iperf.fr/iperf-download.php

### Source code

https://iperf.fr/iperf-download.php

### OpenSource License

MIT

**Comment by hgy59** [comment]
We already have iperf2 and iperf3 tools in the `synocli-monitor`  package.

The tools within ths package are listed on https://github.com/SynoCommunity/spksrc/wiki/FAQ-SynoCliMonitor

**Comment by stephane-archer** [comment]
sorry @hgy59 I didn't see it. searching for iperf did not show any results in the Synology Package Center. I don't know if we can change anything in the package metadata so it shows up.
<img width="1057" alt="Screenshot 2023-11-26 at 06 37 32" src="https://github.com/SynoCommunity/spksrc/assets/2981437/b0d2f5e4-b429-4701-a424-1a880baf4429">

**Comment by hgy59** [comment]
Seems to be an issue of DSM 7 package center
in DSM 6 searching for iperf works:
![PackageCenter_iPerf_DSM6](https://github.com/SynoCommunity/spksrc/assets/12009964/e35467f0-fead-424b-a14b-205bd5397557)

but in DSM 7 searching for iperf does not find any package as your screenshot shows, but searching for synocli does:
![PackageCenter_synocli_DSM7](https://github.com/SynoCommunity/spksrc/assets/12009964/d33b96c0-82bc-4306-9062-1b1bee210cc7)


My findings so far: on DSM 7+ the package description is not parsed for search terms. Only package Title, package name and package developer are.
I think that we cannot fix this. Even the Synology Packages are not found by words of the package description.
If you search for _microsoft_ it only finds "Active Backup for Microsoft 365". It does not find the "Document Viewer" Package that contains "Microsoft Office" in the package description.

So search for _synocli_ and you will find the synocli monitor package. In the description it lists all tools of the package.

**Comment by stephane-archer** [comment]
maybe we should ask for a change to DSM 7 if we can't make a change on our side?

**Comment by hgy59** [comment]
@stephane-archer reported in [[Feature Request] Fix Package Center to search in Package Description](https://community.synology.com/enu/forum/1/post/185258)

Report is ready for thumbs up 😃

**Comment by stephane-archer** [comment]
@hgy59 you are the best!

**Comment by mreid-tt** [comment]
Closing this older request as it was already fulfilled.
