### ISSUE TITLE
I'm getting "Invalid location" when trying to add the repository DSM 6.2.4-25556 Update 7

### ISSUE THREAD

**Issue by lemon99ee** [SynoCommunity/spksrc#5947]
I tried the following:

1：Both the ping command and the nslookup are successful, and they're returning IP 

2：The NTP server was also synchronized successfully

3：Changed different public DNS to no avail.

4：I've also used putty to run commands to upgrade certificates.

5：Can also be accessed normally  https://synocommunity.com/packages

### **but I still continue to get "invalid location" or "unable to save" when trying to add a repository”**
my dsm version DSM 6.2.4-25556 Update 7    DS1819+

**Comment by NoAdO** [comment]
Same with 7.2 918+

**Comment by hgy59** [comment]
Currently the server is down as reported in https://github.com/SynoCommunity/spkrepo/issues/107
Manual downloads do not work either (Internal Server Error).

**Comment by hgy59** [comment]
"Invalid location" is shown when there is an error establishing the https connection. This was the case for older DSM Versions (outdated CA trusted certificates), but this time it is a problem on the server side.

The server still serves the "home" and "packages" page, but navigation to a specific package shows "Internal Server Error".

**Comment by lemon99ee** [comment]
> "Invalid location" is shown when there is an error establishing the https connection. This was the case for older DSM Versions (outdated CA trusted certificates), but this time it is a problem on the server side.
> 
> The server still serves the "home" and "packages" page, but navigation to a specific package shows "Internal Server Error".

Meaning that everyone is experiencing the same as me as in the title glitch? So please let me know you're working on it. 
thanks

**Comment by NoAdO** [comment]
> @lemon99ee, can you confirm that this issue has been resolved?

Fixed for me, managed to add repo successfully.
