### ISSUE TITLE
Sab to sick Category settings

### ISSUE THREAD

**Issue by sledgehammer40** [SynoCommunity/spksrc#595]
I have just updated to the new version of sab on my ds112+ and cant seem to set up the Processing and scripts as its changed from the last version.

i used to have sabtosickbeard.py in the script box, but its not there anymore.

Please could someone offer a newbie a little advice on what i need to do to get this back to normal, i dont want to have to put the old version back on if i can help it..

**Comment by Dr-Bean** [comment]
Closing due to age.
