### ISSUE TITLE
[Package Request] Kavita Book Reader

### ISSUE THREAD

**Issue by asticore** [SynoCommunity/spksrc#5967]
### Software Name

Kavita

### Brief Description

its a cleaner more modern version of Calibre which in my opinion is out dated. It makes it look and act more like plex. 

### Website

https://www.kavitareader.com/

### Documentation

https://wiki.kavitareader.com/en

### Build/Installation documentation

https://wiki.kavitareader.com/en/install/linux-install

### Source code

https://github.com/Kareadita/Kavita

### OpenSource License

GPL-3.0

**Comment by mreid-tt** [comment]
Got a basic install working on x86. Had to change port number from the default 5000 but otherwise seems like a simple enough build. Will work on a PR for a package over the next few days/weeks.

**Comment by mreid-tt** [comment]
@m-peterman, I've built a basic package over at #5978. If you wish to help test it you can download the version for your platform under the Checks tab and clicking the Build section. From there you can manually install on your platform if you feel up to testing.

**Comment by hgy59** [comment]
@mreid-tt IHMO we should stop to add (such) large packages until we have more storage available.

assuming 3 releases of each package, this one will need another 2GB.

**Comment by mreid-tt** [comment]
> Hi I'm the maintainer of Kavita. I noticed this package is lagging behind the latest. I was wondering who I can reach out to ensure there are no issues updating to the latest version of Kavita?

Hi @majora2007, thanks for reaching out and for the nudge. I'll work on getting a PR for the new version over the coming weekend.

As for long-term sustainability, the SynoCommunity is run by volunteers so activity levels as well as time to contribute will vary. What I can recommend is that if we are lagging that an issue be opened in GitHub requesting an update. It can be labelled `update` and you can tag me for my attention.

**Comment by majora2007** [comment]
Thanks @mreid-tt. I wasn't aware these packages were manually updated and thought there was some GA that keeps it up to date. I'll keep an eye and nudge whenever there is a big update that really matters.
