### ISSUE TITLE
cloudflared - update?

### ISSUE THREAD

**Issue by luckman212** [SynoCommunity/spksrc#5976]
### Software Name

cloudflared

### Brief Description

Last spk version published is [`2023.7.1`][2], current upstream [release][1] is `2024.1.1`

Would be awesome to get a version bump here! @karasevm 

[1]: https://github.com/cloudflare/cloudflared
[2]: https://github.com/karasevm/spksrc/blob/master/spk/cloudflared/Makefile

### Website

https://github.com/cloudflare/cloudflared

### Build/Installation documentation

download the go toolchain by running ./.teamcity/install-cloudflare-go.sh and follow the output. Then run make cloudflared

### Source code

https://github.com/cloudflare/cloudflared

### OpenSource License

Apache

### Other License

https://github.com/cloudflare/cloudflared/blob/master/LICENSE

**Comment by karasevm** [comment]
Releases were blocked by the upstream lack of support for go 1.21, and 2024.1.1 requires more changes than usual, you can monitor the progress at https://github.com/SynoCommunity/spksrc/pull/5850.

**Comment by luckman212** [comment]
Ah I see. Thanks for that pointer! Will keep an eye 👀

**Comment by luckman212** [comment]
@karasevm Thanks for your help here! I just did a manual compile with your fork of the spksrc toolchain, and got 2024.1.3 up and running on my DS1621 (V1000), DSM 7.2 🚀 

![image](https://github.com/SynoCommunity/spksrc/assets/1992842/6a24e6de-b8e9-4547-a28c-aec30c34694f)
