### ISSUE TITLE
[Package Request] new version of `dig` in SynoCli Network Tools

### ISSUE THREAD

**Issue by huangyxi** [SynoCommunity/spksrc#5984]
### Software Name

DiG

### Brief Description

The DNS lookup utility DiG now offers support for DNS over TLS and DNS over HTTPS in the latest version ([v9.19.19](https://github.com/isc-projects/bind9/releases/tag/v9.19.19)), while the currently published version, [v9.16.28](https://github.com/isc-projects/bind9/releases/tag/v9.16.28), does not include these features.

DNS over TLS support was introduced in [v9.17.7](https://github.com/isc-projects/bind9/releases/tag/v9.17.7):5531 with the following syntax:
```
dig +tls example.com @1.1.1.1
```
Similarly, DNS over HTTPS support was added in [v9.17.11](https://github.com/isc-projects/bind9/releases/tag/v9.17.11):5596 with the following command:
```
dig +https example.com @1.1.1.1
```

### Website

https://www.isc.org/bind/

### Build/Installation documentation

https://github.com/isc-projects/bind9/blob/main/doc/arm/build.inc.rst

### Source code

https://github.com/isc-projects/bind9

### OpenSource License

other (please specify below)

### Other License

Mozilla Public License, version 2.0

**Comment by hgy59** [comment]
@huangyxi I have updated bind to v9.16.45 in #5985

unfortunately the latest version of bind are v9.16.45 and v9.17.1 that successfully build with spksrc and the toolchains provided by Synology.

Versions >= 9.17.2 and any 9.18.x or 9.19.x versions of bind 9 fail to compile. 
The errors are cross compilation or linker issues.

**Comment by hgy59** [comment]
@huangyxi it was possible in #5984 to update bind to v9.17.22 (except for ARMv5 archs, where the max version is 9.16.x).
As soon as the build is completed (and for 90 days) you can download and manually install packages created by the github build action.

**Comment by huangyxi** [comment]
Appreciate the update! Looking forward to trying out the latest version of Bind. Thanks for your efforts in keeping things up-to-date.
