### ISSUE TITLE
Can't connect to Synology package center with 1513+

### ISSUE THREAD

**Issue by ktryhard** [SynoCommunity/spksrc#6010]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Update center

### Package Version

DSM 4.3-3810

### Device Model

DS1513+

### Device Architecture

x86_64

### Firmware Version

DSM 4.3-3810

### What happened?

My /var/log/message log :
Feb 11 06:52:02 Ocean upgrade.cgi: smallupdate.cpp:288 Error server http://update.synology.com/smallupdate/3810/synology_cedarview_1513+/DSM-Security.json
Feb 11 06:52:02 Ocean upgrade.cgi: upgrade.cpp:267 Fail to check new update
Ocean> ping update.synology.com
PING update.synology.com (52.84.187.203): 56 data bytes
64 bytes from 52.84.187.203: seq=0 ttl=247 time=36.185 ms

### Reproduction steps

1. In the Control pannel > System > DSM Update : connection failed, verify internet connection

### Install Log

```log
Tries http and https wget but same result : HTTP 404 occurred :

Ocean> wget --no-check-certificate  http://update.synology.com/smallupdate/3810/synology_cedarview_1513+/DSM-Security.json
--06:56:19--  http://update.synology.com/smallupdate/3810/synology_cedarview_1513+/DSM-Security.json
           => `DSM-Security.json'
Resolving update.synology.com... 52.84.187.203
Connecting to update.synology.com|52.84.187.203|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://update.synology.com/smallupdate/3810/synology_cedarview_1513+/DSM-Security.json [following]
--06:56:19--  https://update.synology.com/smallupdate/3810/synology_cedarview_1513+/DSM-Security.json
           => `DSM-Security.json'
Connecting to update.synology.com|52.84.187.203|:443... connected.
WARNING: Certificate verification error for update.synology.com: self signed certificate in certificate chain
HTTP request sent, awaiting response... 404 Not Found
06:56:20 ERROR 404: Not Found.

Ocean> wget --no-check-certificate  https://update.synology.com/smallupdate/3810/synology_cedarview_1513+/DSM-Security.json
--06:56:35--  https://update.synology.com/smallupdate/3810/synology_cedarview_1513+/DSM-Security.json
           => `DSM-Security.json'
Resolving update.synology.com... 52.84.187.203
Connecting to update.synology.com|52.84.187.203|:443... connected.
WARNING: Certificate verification error for update.synology.com: self signed certificate in certificate chain
HTTP request sent, awaiting response... 404 Not Found
06:56:35 ERROR 404: Not Found.
```

**Comment by ymartin59** [comment]
Hello
This SynoCommunity project is not the official channel to report troubles with Synology services.
Please post at https://community.synology.com
Best regards

**Comment by mreid-tt** [comment]
@ktryhard, if you are trying to update your Synology DSM version you can always do so manually at https://www.synology.com/support/download/DS1513+. Otherwise, as mentioned above this is not a problem that the SynoCommunity can resolve directly.

**Comment by mreid-tt** [comment]
@ktryhard, were you successful in manually updating your NAS? As previously stated, this matter does not pertain to SynoCommunity, and we anticipate closing the issue within a few days.
