### ISSUE TITLE
[jellyfin/ffmpeg] OpenCL missing from FFmpeg disables hardware acceleration on Intel

### ISSUE THREAD

**Issue by WesSouza** [SynoCommunity/spksrc#6017]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

jellyfin

### Package Version

10.8.13-13

### Device Model

DS718+

### Device Architecture

x86_64

### Firmware Version

DSM 7.2.1-69057 Update 4

### What happened?

Playing a video on Jellyfin with hardware acceleration enabled produces a very slow outcome compared to the same setup on a Docker container on the same machine.

It's also slower than software.

### Reproduction steps

1. Configure transcoding hardware acceleration
2. Play a video that should be able to be remuxed
3. Transcoding happens at 8fps (150fps expected)

### Install Log

```log
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin preinst
2024/02/20 15:29:01	Begin initialize_variables
2024/02/20 15:29:01	End initialize_variables
2024/02/20 15:29:01	===> Step preinst. STATUS=INSTALL USER=jellyfin GROUP=sc-media SHARE_PATH=
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End preinst ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/mkdir -p /volume1/@appstore/jellyfin -m 755
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/mkdir -p /volume1/@appstore/jellyfin -m 755 ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/rm -rf /volume1/@appstore/jellyfin
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/rm -rf /volume1/@appstore/jellyfin ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/mv -f /volume1/@tmp/synopkg/install.QbEjjq/package /volume1/@appstore/jellyfin
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/mv -f /volume1/@tmp/synopkg/install.QbEjjq/package /volume1/@appstore/jellyfin ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/rm -rf /var/packages/jellyfin
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/rm -rf /var/packages/jellyfin ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/mkdir -p /var/packages/jellyfin -m 755
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/mkdir -p /var/packages/jellyfin -m 755 ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/touch /var/packages/jellyfin/installing
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/touch /var/packages/jellyfin/installing ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/mv -f /volume1/@tmp/synopkg/install.QbEjjq/INFO /var/packages/jellyfin/INFO
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/mv -f /volume1/@tmp/synopkg/install.QbEjjq/INFO /var/packages/jellyfin/INFO ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/rm -rf /var/packages/jellyfin/scripts
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/rm -rf /var/packages/jellyfin/scripts ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/mv -f /volume1/@tmp/synopkg/install.QbEjjq/scripts /var/packages/jellyfin/scripts
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/mv -f /volume1/@tmp/synopkg/install.QbEjjq/scripts /var/packages/jellyfin/scripts ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/rm -rf /var/packages/jellyfin/WIZARD_UIFILES
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/rm -rf /var/packages/jellyfin/WIZARD_UIFILES ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/mv -f /volume1/@tmp/synopkg/install.QbEjjq/WIZARD_UIFILES /var/packages/jellyfin/WIZARD_UIFILES
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/mv -f /volume1/@tmp/synopkg/install.QbEjjq/WIZARD_UIFILES /var/packages/jellyfin/WIZARD_UIFILES ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/rm -rf /var/packages/jellyfin/conf
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/rm -rf /var/packages/jellyfin/conf ret=[0]
2024/02/20 15:29:01	install jellyfin 10.8.13-13 Begin /bin/mv -f /volume1/@tmp/synopkg/install.QbEjjq/conf /var/packages/jellyfin/conf
2024/02/20 15:29:01	install jellyfin 10.8.13-13 End /bin/mv -f /volume1/@tmp/synopkg/install.QbEjjq/conf /var/packages/jellyfin/conf ret=[0]
2024/02/20 15:29:08	install jellyfin 10.8.13-13 Begin postinst
2024/02/20 15:29:08	Begin initialize_variables
2024/02/20 15:29:08	End initialize_variables
2024/02/20 15:29:08	===> Step postinst. STATUS=INSTALL USER=jellyfin GROUP=sc-media SHARE_PATH=
2024/02/20 15:29:08	Begin save_wizard_variables
2024/02/20 15:29:08	End save_wizard_variables
2024/02/20 15:29:08	Begin syno_sync_var_folder
2024/02/20 15:29:08	End syno_sync_var_folder
2024/02/20 15:29:08	Begin service_postinst
2024/02/20 15:29:08	End service_postinst
2024/02/20 15:29:08	install jellyfin 10.8.13-13 End postinst ret=[0]
2024/02/20 15:29:09	install jellyfin 10.8.13-13 Begin start-stop-status start
2024/02/20 15:29:09	install jellyfin 10.8.13-13 End start-stop-status start ret=[0]
2024/02/20 15:36:28	stop jellyfin 10.8.13-13 Begin start-stop-status stop
2024/02/20 15:36:29	stop jellyfin 10.8.13-13 End start-stop-status stop ret=[0]
2024/02/20 15:36:39	start jellyfin 10.8.13-13 Begin start-stop-status start
2024/02/20 15:36:39	start jellyfin 10.8.13-13 End start-stop-status start ret=[0]
2024/02/20 16:52:25	start jellyfin 10.8.13-13 Begin start-stop-status stop
2024/02/20 16:52:25	start jellyfin 10.8.13-13 End start-stop-status stop ret=[0]
2024/02/20 16:52:29	start jellyfin 10.8.13-13 Begin start-stop-status start
2024/02/20 16:52:29	start jellyfin 10.8.13-13 End start-stop-status start ret=[0]
```

### Other Logs

Here's the ffmpeg logs from both installations, indicating a big speed difference:

- [ffmpeg-docker.log](https://github.com/SynoCommunity/spksrc/files/14352188/ffmpeg-docker.log)
- [ffmpeg-syno.log](https://github.com/SynoCommunity/spksrc/files/14352405/ffmpeg-syno.log)

### Additional Information

I also tried to install ffmpeg5 and ffmpeg6 update the `--ffmpeg` arg on `/var/packages/jellyfin/scripts/service-setup` but the results were almost identical.

I followed [this guide to setup the Docker container](https://drfrankenstein.co.uk/jellyfin-in-container-manager-on-a-synology-nas-hardware-transcoding/).

**Comment by mreid-tt** [comment]
@WesSouza, out of curiosity, on the same hardware what was the conversion rate in Docker?

**Comment by WesSouza** [comment]
I just reenabled the Docker project and realized the videos are being _remuxed_. I believe there's something wrong somewhere that prevents the SynoCommunity version of Jellyfin not to remux.

The conversion seems equally slow unfortunately.

**Comment by WesSouza** [comment]
I've edited the title and description to reflect my recent findings.

**Comment by WesSouza** [comment]
@mreid-tt Added two ffmpeg logs to the description (one from this package, one from the docker instance), showing the differences.

So far:
- ffmpeg version is different (I tried with 5.1.3-2 from the SynoCommunity and got the same results)
- The JSON on docker sets `"IsAVC": true` and `"NalLengthSize": "4"` versus `false` and `"0"`

I also reenabled the same hardware acceleration settings on both instances and the ffmpeg command has two differences:

```
# Present on Docker, missing from Syno
-hwaccel_output_format vaapi

# Docker
-vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,deinterlace_vaapi=rate=frame,scale_vaapi=format=nv12:extra_hw_frames=24,hwmap=derive_device=qsv,format=qsv"

# Syno
-vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,yadif=0:-1:0,scale=trunc(min(max(iw\,ih*a)\,min(1920\,1080*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(1920/a\,1080))/2)*2,format=nv12"
```

Both playbacks were attempted on the same video on the same browser (Safari on macOS), and Jellyfin's display version is the same on both instances.

**Comment by WesSouza** [comment]
The lack of `-hwaccel_output_format vaapi` seems to be caused by Syno's ffmpeg not providing the `opencl` hardware acceleration and filters.

From Jellyfin's code:

1. The code that adds `-hwaccel_output_format vaapi` checks `hwSurface` [(here)](https://github.com/jellyfin/jellyfin/blob/08b830ae7122193ae75f230a2bea008e72a7cbfd/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L5749-L5750)
2. `hwSurface` requires `isIntelVaapiOclSupported`, which requires `IsOpenclFullSupported()`
3. `isIntelVaapiOclSupported ` requires both `opencl` hardware acceleration, `scale_opencl` filter and specific filters `tonemap_opencl` and `overlay_opencl` [(here)](https://github.com/jellyfin/jellyfin/blob/08b830ae7122193ae75f230a2bea008e72a7cbfd/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L230-L236)

All of these are available on the Docker compose instance, but absent from Syno's ffmpeg.

**Comment by mreid-tt** [comment]
@WesSouza, thank you for providing additional detail.

@th0ma7, I remember you working with the `ffmpeg` package before. Could you share any insights that might help resolve this issue?

**Comment by th0ma7** [comment]
@WesSouza there are a few caveats when using ffmpeg on you nas, your user must be part of the videodriver group.

`vainfo` will confirm what access you do have from your user account in use when accessing ffmpeg. See: https://github.com/SynoCommunity/spksrc/wiki/FAQ-FFmpeg

**Comment by th0ma7** [comment]
@WesSouza at first read it wasn't that obvious that you where referring to opencl missing requirements.  Indeed, opencl is not integrated currently in SynoCommunity's ffmpeg.  It's on my todo list but didn't got to it yet.

**Comment by WesSouza** [comment]
@th0ma7 is there an open issue for it I should be watching? Or something I could do to help?

**Comment by WesSouza** [comment]
@th0ma7 done!

**Comment by reykjalin** [comment]
[Jellyfin uses a modified version of FFMPEG](https://jellyfin.org/docs/general/administration/hardware-acceleration/#supported-acceleration-methods): https://github.com/jellyfin/jellyfin-ffmpeg. Maybe that's what's missing here?

**Comment by th0ma7** [comment]
> [Jellyfin recommends a modified version of FFMPEG](https://jellyfin.org/docs/general/administration/hardware-acceleration/#supported-acceleration-methods): https://github.com/jellyfin/jellyfin-ffmpeg. Maybe that's what's missing here?

Yes and no. All jellyfin ffmpeg patches are included in our default build.  What's missing are
1. Including opengl intel drivers (currently missing from build)
2. Updating both ffmpeg and use latest snapshot of the jellyfin patches.

It is on my todo list but cycles have been rather limited lately.

**Comment by th0ma7** [comment]
@WesSouza and @reykjalin would you mind testing out new ffmpeg release?  Artifacts are available here https://github.com/SynoCommunity/spksrc/issues/6017

I've now created a sub-package calle synocli-videodriver which has all the necessary bits for OpenCL and allows sharing the drivers amongst all ffmpeg versions (thus will allow me to look into publish a ffmpeg7 shortly thereafter).

Most importantly, can you provide the vainfo and clinfo outputs from this new driver package, confirming all is now taking shape.

**Comment by th0ma7** [comment]
@WesSouza and @reykjalin here's is the new output for both ffmpeg5 and ffmpeg6:

### ffmpeg5
```
$ ./ffmpeg5 -hide_banner -hwaccels
Hardware acceleration methods:
vaapi
qsv
drm
opencl

$ ./ffmpeg5  -hide_banner -filters | grep opencl
 ... avgblur_opencl    V->V       Apply average blur filter
 ... boxblur_opencl    V->V       Apply boxblur filter to input video
 ... colorkey_opencl   V->V       Turns a certain color into transparency. Operates on RGB colors.
 ... convolution_opencl V->V       Apply convolution mask to input video
 ... deshake_opencl    V->V       Feature-point based video stabilization filter
 ... dilation_opencl   V->V       Apply dilation effect
 ... erosion_opencl    V->V       Apply erosion effect
 ... nlmeans_opencl    V->V       Non-local means denoiser through OpenCL
 ... overlay_opencl    VV->V      Overlay one video on top of another
 ... pad_opencl        V->V       Pad the input video.
 ... prewitt_opencl    V->V       Apply prewitt operator
 ... program_opencl    N->V       Filter video using an OpenCL program
 ... remap_opencl      VVV->V     Remap pixels using OpenCL.
 ... roberts_opencl    V->V       Apply roberts operator
 ... scale_opencl      V->V       Scale the input video size through OpenCL.
 ... sobel_opencl      V->V       Apply sobel operator
 ... tonemap_opencl    V->V       Perform HDR to SDR conversion with tonemapping.
 ... transpose_opencl  V->V       Transpose input video
 ... unsharp_opencl    V->V       Apply unsharp mask to input video
 ... xfade_opencl      VV->V      Cross fade one video with another video.
 ... openclsrc         |->V       Generate video using an OpenCL program
```

### ffmpeg6
```
$ ./ffmpeg6 -hide_banner -hwaccels
Hardware acceleration methods:
vaapi
qsv
drm
opencl

$ ./ffmpeg6  -hide_banner -filters | grep opencl
 ... avgblur_opencl    V->V       Apply average blur filter
 ... boxblur_opencl    V->V       Apply boxblur filter to input video
 ... colorkey_opencl   V->V       Turns a certain color into transparency. Operates on RGB colors.
 ... convolution_opencl V->V       Apply convolution mask to input video
 ... deshake_opencl    V->V       Feature-point based video stabilization filter
 ... dilation_opencl   V->V       Apply dilation effect
 ... erosion_opencl    V->V       Apply erosion effect
 ... nlmeans_opencl    V->V       Non-local means denoiser through OpenCL
 ... overlay_opencl    VV->V      Overlay one video on top of another
 ... pad_opencl        V->V       Pad the input video.
 ... prewitt_opencl    V->V       Apply prewitt operator
 ... program_opencl    N->V       Filter video using an OpenCL program
 ... remap_opencl      VVV->V     Remap pixels using OpenCL.
 ... roberts_opencl    V->V       Apply roberts operator
 ... scale_opencl      V->V       Scale the input video size through OpenCL.
 ... sobel_opencl      V->V       Apply sobel operator
 ... tonemap_opencl    V->V       Perform HDR to SDR conversion with tonemapping.
 ... transpose_opencl  V->V       Transpose input video
 ... unsharp_opencl    V->V       Apply unsharp mask to input video
 ... xfade_opencl      VV->V      Cross fade one video with another video.
 ... openclsrc         |->V       Generate video using an OpenCL program
```

**Comment by WesSouza** [comment]
```
wesley@WexDrive:~$ ffmpeg6 -hide_banner -hwaccels
Hardware acceleration methods:
vaapi
qsv
drm
opencl

wesley@WexDrive:~$ ffmpeg6  -hide_banner -filters | grep opencl
 ... avgblur_opencl    V->V       Apply average blur filter
 ... boxblur_opencl    V->V       Apply boxblur filter to input video
 ... colorkey_opencl   V->V       Turns a certain color into transparency. Operates on RGB colors.
 ... convolution_opencl V->V       Apply convolution mask to input video
 ... deshake_opencl    V->V       Feature-point based video stabilization filter
 ... dilation_opencl   V->V       Apply dilation effect
 ... erosion_opencl    V->V       Apply erosion effect
 ... nlmeans_opencl    V->V       Non-local means denoiser through OpenCL
 ... overlay_opencl    VV->V      Overlay one video on top of another
 ... pad_opencl        V->V       Pad the input video.
 ... prewitt_opencl    V->V       Apply prewitt operator
 ... program_opencl    N->V       Filter video using an OpenCL program
 ... remap_opencl      VVV->V     Remap pixels using OpenCL.
 ... roberts_opencl    V->V       Apply roberts operator
 ... scale_opencl      V->V       Scale the input video size through OpenCL.
 ... sobel_opencl      V->V       Apply sobel operator
 ... tonemap_opencl    V->V       Perform HDR to SDR conversion with tonemapping.
 ... transpose_opencl  V->V       Transpose input video
 ... unsharp_opencl    V->V       Apply unsharp mask to input video
 ... xfade_opencl      VV->V      Cross fade one video with another video.
 ... openclsrc         |->V       Generate video using an OpenCL program
```

Looking at `vainfo` and `clinfo` outputs look similar to yours on the other issue.

**Comment by WesSouza** [comment]
[vainfo-clinfo.txt](https://github.com/user-attachments/files/17075238/vainfo-clinfo.txt)

**Comment by WesSouza** [comment]
[vainfo-clinfo.txt](https://github.com/user-attachments/files/17075246/vainfo-clinfo.txt)

**Comment by reykjalin** [comment]
Can’t provide it now, but happy to check when I’m able to in October. Sorry for the delay, I won’t be able to run my Jellyfin server until October.

I’m happy to trust @WesSouza’s results here though. Thank you @th0ma7 !

**Comment by th0ma7** [comment]
FYI - Updated packages now published and should be available within 24-48h.
Note that I had to bump the package version once more due to minor meta data info needing fixing.
Thnx again for testing.

**Comment by jmqm** [comment]
@th0ma7 only works on SynoCommunity Jellyfin eh? Not Docker?

**Comment by th0ma7** [comment]
Most probably as i don't know how you would pass it through docker .. ?
