### ISSUE TITLE
[Package Request] GNU patch inside SynoCli File Tools

### ISSUE THREAD

**Issue by pheudo** [SynoCommunity/spksrc#6030]
### Software Name

GNU patch

### Brief Description

Patch takes a patch file containing a difference listing produced by the diff program and applies those differences to one or more original files, producing patched versions.

### Website

https://savannah.gnu.org/projects/patch/

### Documentation

https://git.savannah.gnu.org/cgit/patch.git/tree/README

### Build/Installation documentation

https://git.savannah.gnu.org/cgit/patch.git/tree/README-hacking

### Source code

https://savannah.gnu.org/git/?group=patch

### OpenSource License

GPLv3

**Comment by hgy59** [comment]
@pheudo you're in luck, I'm already working on an updated synocli-file package

**Comment by pheudo** [comment]
Amazing!

I tested it with the latest artifact and it works perfectly. 
Thank you very much indeed!
