### ISSUE TITLE
Mosh won't install

### ISSUE THREAD

**Issue by mwshook** [SynoCommunity/spksrc#6033]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

mosh

### Package Version

1.4.0-3

### Device Model

DS224+

### Device Architecture

x86_64

### Firmware Version

7.2.1-69057

### What happened?

I am in the package manager, search for Mosh, and click "install" as per usual. A dialog box appears asking me if I want to install PERL and I click yes. A progress bar clicks by, closes and it appears nothing is changed. The mosh page still says "install." I get the same behavior (normal-looking progress bar, then no apparent change) when I try to install PERL
![Screenshot from 2024-03-10 23-51-46](https://github.com/SynoCommunity/spksrc/assets/30010467/04fc6024-a270-4080-8045-5e10645bf856)
. 

Expected behavior: The "install" button would change to "open" or "installed" or something similar. I would be able to use mosh.

### Reproduction steps

1. Login to DSM via web browser
2. open Package Center
3. Search for mosh
4. Click install
5. When asked to install PERL, click yes.
6. After the progress bar goes to 100% and closes, note that the button still says "install" and mosh is not present on  my machine.
...

### Install Log

```log
No pertinent logs found. No entry for mosh
```

### Service Log

```log
No entry for mosh.
```

**Comment by mreid-tt** [comment]
@mwshook, thanks for the report. It may be helpful to try a manual install of the package to get more details. You can try downloading the package directly from the website at [7.1 geminilake](https://packages.synocommunity.com/mosh/3/mosh.v3.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk) and then installing it using the manual install option. Let me know if it provides any more error messages or logs that could be useful for diagnosis.

**Comment by hgy59** [comment]
@mwshook this seems to be an issue with the synology perl package.
You can try to download and manually install the [perl package](https://global.synologydownload.com/download/Package/spk/Perl/5.34.1-0301/Perl-x86_64-5.34.1-0301.spk) from synology.
If you don't see the thirdparty warning dialog, the installer of mosh is ot involved.

**Comment by mwshook** [comment]
I manually installed the SPK and it gave me the error that my system partition is full. And it is (8GB). For some reason the regular Package Center install did not give the error message.

I will report back after I figure out what I need to do to free up some space. 

FWIW, installing perl from Package Center also starts the install process, then stops without an error message

**Comment by mreid-tt** [comment]
@mwshook the absence of error messages seems to be a Synology issue if the Perl package is doing the same thing. You can always manually download perl from https://www.synology.com/en-uk/support/download/DS224+?version=7.2#packages and try to install it to verify.

**Comment by mwshook** [comment]
Sorry to bother you about this. The solution was comically difficult to track down and had nothing to do with mosh at all.
I have a USB drive plugged in and had been putting files in /volumeUSB1
Little did I know the drive was ACTUALLY mounted at /volumeUSB1/usbshare 
Any files I put in the first directory were sitting in the system partition.
`sudo du -chx -d 3 -t 100M / | sort` was the magic incantation. "-x" limited the search to the root filesystem.

Thanks for being helpful!
Closing.
