### ISSUE TITLE
> @hgy59 I'm now ready to merge this PR. I cannot test publishing although code in theory did not change. This will then allow me to pursue work on the python311 update (#6040).

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#6053]
> @hgy59 I'm now ready to merge this PR. I cannot test publishing although code in theory did not change. This will then allow me to pursue work on the python311 update (#6040).
> 
> Note that I expect that something, somehow, will not work as expected as this PR is quite invasive. Although the current `make test all` which build 25GB+ with no error is a good indicative that problems, if any, should be relatively minor.
> 
> Any objections before I merge this?

@th0ma7 thanks for your huge and great work. 
The only issue i found so far, is that after a make native-clean (or clean in native/rust-qoriq) it does not build rust-qoriq when building a package depending on rust for qoriq.
It probably depends on the rust installation related to building the toolchain(s). I often face this issue because I cache the toolchains for all my different work copies but do not cache the native packages. And it was an issue when testing dedicated versions of rust in #6050. 
This is all related to rust and should be addressed in a dedicated PR.

BTW I didn't figure out what you really solved with _"allow `DEPENDS` from `toolchain`"_

_Originally posted by @hgy59 in https://github.com/SynoCommunity/spksrc/issues/6002#issuecomment-2029257742_

**Comment by mreid-tt** [comment]
@hgy59, should this have a better title? I'm not sure what this was meant to capture.

**Comment by hgy59** [comment]
@mreid-tt this is a closed issue and replaced by #6054

It was my first try to create an issue from a comment, ...
