### ISSUE TITLE
missing native/rust-qoriq dependency for qoriq

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#6054]
After `make native-clean` the native/rust-qoriq dependency is not built when building rust dependent packages for qoriq.

This is related to the installation of rust in the development environment. The installation of rust must not be coupled to the installation of the toolchains.
This seems to be an issue too, when a package requires a dedicated version of rust (nightly or a specific version instead of stable)

see https://github.com/SynoCommunity/spksrc/pull/6002#issuecomment-2029257742

**Comment by th0ma7** [comment]
some randomd thoughts... why not moving it under `toolchain/syno-qoriq-6-2.4-rust` ... as this is a toolchain, no?  Further that may allow to later do a `toolchain/syno-qoriq-6.2.4-llvm` (something else I got pending with missng cycles).

**Comment by th0ma7** [comment]
Looking at what is being cached (considering there lie the issue), there are `toolchain` and `distrib` (from `.github/workflows/build.yml).  Native does not seems to be cached.

Further thinking this through question is, considering `toolchain` got cached, would this entail that the toolchain skips its dependencies?  Looking at `toolchain/syno-qoriq-6.2.4/work/.depend_done` cookie, absolutely - this results in the skiping of the `native/rust-qoriq`.

Although looking at my precedent post https://github.com/SynoCommunity/spksrc/issues/6054#issuecomment-2029792302, using `toolchain/syno-qoriq-6-2.4-rust` solves that as both `toolchain` and `distrib` are cached.

@hgy59 I'll create a PR with this in mind to have your thoughts on.
