### ISSUE TITLE
[Package Request] Flaresolverr

### ISSUE THREAD

**Issue by CorentinWicht** [SynoCommunity/spksrc#6060]
### Software Name

Flaresolverr

### Brief Description

FlareSolverr is a proxy server to bypass Cloudflare protection. Nowadays, many indexers usually accessed by [Radarr](https://synocommunity.com/package/radarr) and [Sonarr](https://synocommunity.com/package/sonarr) (which are supported as packages by SynoCommunity) are hidden behind Cloudflare Captcha pages.

FlareSolverr starts a proxy server, and it waits for user requests in an idle state using few resources. When some request arrives, it uses [Selenium](https://www.selenium.dev/) with the [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) to create a web browser (Chrome). It opens the URL with user parameters and waits until the Cloudflare challenge is solved (or timeout). The HTML code and the cookies are sent back to the user, and those cookies can be used to bypass Cloudflare using other HTTP clients.

### Website

https://github.com/FlareSolverr/FlareSolverr

### Documentation

https://github.com/FlareSolverr/FlareSolverr/wiki

### Build/Installation documentation

https://github.com/FlareSolverr/FlareSolverr?tab=readme-ov-file#installation

### Source code

https://github.com/FlareSolverr/FlareSolverr/archive/refs/tags/v3.3.16.tar.gz

### OpenSource License

MIT

**Comment by publicarray** [comment]
I don't know, they already have good docker images https://hub.docker.com/r/flaresolverr/flaresolverr I recommend using the docker container if at all possible. If your NAS doesn't already support docker, I would think it would not be powerful enough to run a web browser reliably. It might be possible, however. 

> NOTE: Web browsers consume a lot of memory. If you are running FlareSolverr on a machine with few RAM, do not make many requests at once. With each request a new browser is launched
