### ISSUE TITLE
synokernel-* build is broken

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#6085]
Since #6002 the build of synokernel-* packages is broken.

This seems to be related to the framework changes in mk/*.mk files.

synocli-kernel still succeeds to build but

synokernel-cdrom and synokernel-usbserial fail with:
```
===>  Creating target installation dir of synokernel-cdrom
===>  [DSM6] Copy target to staging
/bin/bash: line 1: cd: /spksrc/spk/synokernel-cdrom/work-aarch64-6.2.4/install/var/packages/synokernel-cdrom/target: No such file or directory
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
make[2]: *** [../../mk/spksrc.copy.mk:58: copy_target] Error 2
make[2]: Leaving directory '/spksrc/spk/synokernel-cdrom'
```

and
```
===>  Creating target installation dir of synokernel-usbserial
===>  [DSM6] Copy target to staging
/bin/bash: line 1: cd: /spksrc/spk/synokernel-usbserial/work-aarch64-6.2.4/install/var/packages/synokernel-usbserial/target: No such file or directory
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
make[2]: *** [../../mk/spksrc.copy.mk:58: copy_target] Error 2
make[2]: Leaving directory '/spksrc/spk/synokernel-usbserial'
```

**Comment by hgy59** [comment]
@th0ma7 so far I tested builds for aarch64-6.2.4 only.

Don't know whether it is realated, but with #6002 the build log files changed from `build-aarch64-6.2.4.log` to `build-aarch64-6.2.4-kernel-modules.log`

My intention was to create a `synokernel-hwmon` package for #6084 since I discoverd that the existing synokernel-* packages can no longer be built.

**Comment by hgy59** [comment]
related to #5790

**Comment by th0ma7** [comment]
Indeed this is a regression, currently having a look at things, seems calls to kernel sub-routines are being skipped.
