### ISSUE TITLE
[TVHeadend v4.3.20230408-36] Package cannot be started anymore after update of Pyhton 3.10 (to v3.10.14-20)

### ISSUE THREAD

**Issue by iHaveAstream** [SynoCommunity/spksrc#6087]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

TVHeadend

### Package Version

4.3.20230408-36

### Device Model

DS 216+ II

### Device Architecture

x86_64

### Firmware Version

7.2-64570 Update 3

### What happened?

I'm running TVH v4.3.20230408-36 from SynoCommunity since long on my DS 216+ II.
Today I made an update of the installed Python 3.10 package to v3.10.14-20 as the package center told me that there's and update available.
The update of Python 3.10 went thru fine, however, afterwards TVH couldn't be started anymore and even some repair is not possible.
Before I fully uninstall and re-install TVH, I wanted to see if there might be another way to make it work again since re-configuring TVH from scratch is kinda big effort...

### Reproduction steps

1. Update installed Python 3.10 package to 3.10.14-20 via Package Center in DSM
2. After the update has finished, it tries to also start TVH again, but it fails all the time
3. 
...

### Install Log

```log
2024/04/29 08:34:25     (system) trigger tvheadend 4.3.20230408-36 Begin start-stop-status stop
2024/04/29 08:34:28     (system) trigger tvheadend 4.3.20230408-36 End start-stop-status stop ret=[0]
2024/04/29 08:34:52     (system) trigger tvheadend 4.3.20230408-36 Begin start-stop-status start
2024/04/29 08:35:12     (system) trigger tvheadend 4.3.20230408-36 End start-stop-status start ret=[1]
2024/04/29 08:35:13     (system) trigger tvheadend 4.3.20230408-36 Begin start-stop-status stop
2024/04/29 08:35:13     (system) trigger tvheadend 4.3.20230408-36 End start-stop-status stop ret=[0]
2024/04/29 09:04:23     start tvheadend 4.3.20230408-36 Begin start-stop-status start
2024/04/29 09:04:43     start tvheadend 4.3.20230408-36 End start-stop-status start ret=[1]
2024/04/29 09:04:43     start tvheadend 4.3.20230408-36 Begin start-stop-status stop
2024/04/29 09:04:43     start tvheadend 4.3.20230408-36 End start-stop-status stop ret=[0]
2024/04/29 09:05:21     start tvheadend 4.3.20230408-36 Begin start-stop-status start
2024/04/29 09:05:41     start tvheadend 4.3.20230408-36 End start-stop-status start ret=[1]
2024/04/29 09:05:41     (system) trigger tvheadend 4.3.20230408-36 Begin start-stop-status stop
2024/04/29 09:05:41     (system) trigger tvheadend 4.3.20230408-36 End start-stop-status stop ret=[0]
2024/04/29 09:06:38     start tvheadend 4.3.20230408-36 Begin start-stop-status start
2024/04/29 09:06:58     start tvheadend 4.3.20230408-36 End start-stop-status start ret=[1]
2024/04/29 09:06:58     (system) trigger tvheadend 4.3.20230408-36 Begin start-stop-status stop
2024/04/29 09:06:58     (system) trigger tvheadend 4.3.20230408-36 End start-stop-status stop ret=[0]
2024/04/29 09:12:02     start tvheadend 4.3.20230408-36 Begin start-stop-status start
2024/04/29 09:12:22     start tvheadend 4.3.20230408-36 End start-stop-status start ret=[1]
2024/04/29 09:12:22     (system) trigger tvheadend 4.3.20230408-36 Begin start-stop-status stop
2024/04/29 09:12:22     (system) trigger tvheadend 4.3.20230408-36 End start-stop-status stop ret=[0]
2024/04/29 09:19:12     start tvheadend 4.3.20230408-36 Begin start-stop-status start
2024/04/29 09:19:32     start tvheadend 4.3.20230408-36 End start-stop-status start ret=[1]
2024/04/29 09:19:32     (system) trigger tvheadend 4.3.20230408-36 Begin start-stop-status stop
2024/04/29 09:19:32     (system) trigger tvheadend 4.3.20230408-36 End start-stop-status stop ret=[0]
2024/04/29 09:33:20     start tvheadend 4.3.20230408-36 Begin start-stop-status start
2024/04/29 09:33:41     start tvheadend 4.3.20230408-36 End start-stop-status start ret=[1]
2024/04/29 09:33:41     (system) trigger tvheadend 4.3.20230408-36 Begin start-stop-status stop
2024/04/29 09:33:41     (system) trigger tvheadend 4.3.20230408-36 End start-stop-status stop ret=[0]
```

### Service Log

```log
Mon Apr 29 09:33:21 CEST 2024
Starting tvheadend command tvheadend -f -C -u sc-tvheadend -g tvheadend --http_port 9981 --htsp_port 9982 -c /volume1/@appdata/tvheadend -p /volume1/@appdata/tvheadend/tvheadend.pid -l /volume1/@appdata/tvheadend/tvheadend.log --debug ""
tvheadend is not running
```

**Comment by iHaveAstream** [comment]
Hi @th0ma7 

would be awesome if you could take a look into this.

Many thanks in advance!

**Comment by iHaveAstream** [comment]
when I do `systemctl status tvheadend.service`, result is: 
`● tvheadend.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
`

**Comment by th0ma7** [comment]
I'm using on a daily basis the exact same version at home (which makes me realize an update is overdue).  I did updated python310 this morning as offered from the package center and all went smooth, same arch x86_64.

Can you provide me with your `/var/packages/tvheadend/var/tvheadend.log` file?  Also a listing of the files right after a restart tentative:
```
$ ls -la /var/packages/tvheadend/var/tvheadend*
-rw-r--r-- 1 sc-tvheadend sc-media   1723 Aug  2  2019 /var/packages/tvheadend/var/tvheadend_install.log
-rw-r--r-- 1 sc-tvheadend sc-media  51762 Apr 29 06:41 /var/packages/tvheadend/var/tvheadend.log
-rw-r--r-- 1 sc-tvheadend tvheadend     6 Apr 29 06:36 /var/packages/tvheadend/var/tvheadend.pid
```

**Comment by iHaveAstream** [comment]
> Can you provide me with your `/var/packages/tvheadend/var/tvheadend.log` file? Also a listing of the files right after a restart tentative:
> 
> ```
> $ ls -la /var/packages/tvheadend/var/tvheadend*
> -rw-r--r-- 1 sc-tvheadend sc-media   1723 Aug  2  2019 /var/packages/tvheadend/var/tvheadend_install.log
> -rw-r--r-- 1 sc-tvheadend sc-media  51762 Apr 29 06:41 /var/packages/tvheadend/var/tvheadend.log
> -rw-r--r-- 1 sc-tvheadend tvheadend     6 Apr 29 06:36 /var/packages/tvheadend/var/tvheadend.pid
> ```

Thanks for your fast reply. Actually I also have no clue why this has happened.
But strangely, the output of `ls -la /var/packages/tvheadend/var/tvheadend*` in my case only returns:

```
-rw-r--r-- 1 sc-tvheadend sc-media 293 Apr 29 12:51 /var/packages/tvheadend/var/tvheadend.log
```

It means, the others are missing.

this is the content of `tvheadend.log`:
```
Mon Apr 29 12:50:40 CEST 2024
Starting tvheadend command tvheadend -f -C -u sc-tvheadend -g tvheadend --http_port 9981 --htsp_port 9982 -c /volume1/@appdata/tvheadend -p /volume1/@appdata/tvheadend/tvheadend.pid -l /volume1/@appdata/tvheadend/tvheadend.log --debug ""
tvheadend is not running
```

**Comment by iHaveAstream** [comment]
ok, luckily I could make it back working again by just by first uninstalling the app via package manager (I had selected "keep my files") and afterwards re-installing it.
Everything is now as it used to be before - I think we can close this one here.

Thanks again for your time.

**Comment by th0ma7** [comment]
Excellent but still weird.  Thnx for the follow up
