### ISSUE TITLE
[Package Request] blu-hawaii BluOS Scrobbler

### ISSUE THREAD

**Issue by SatanicMechanic** [SynoCommunity/spksrc#6091]
### Software Name

blu-hawaii

### Brief Description

There are several scrobblers supporting bluOS players, but this is the most actively maintained.

### Website

https://github.com/jliuhtonen/blu-hawaii

### Build/Installation documentation

https://github.com/jliuhtonen/blu-hawaii

### Source code

https://github.com/jliuhtonen/blu-hawaii

### OpenSource License

MIT

**Comment by algora-pbc** [comment]
💎 **morey** is offering a **$25** bounty for this issue
👉 Got a pull request resolving this? Claim the bounty by adding `@algora-pbc /claim #6091` in the PR body and joining algora.io

**Comment by hgy59** [comment]
What about using docker (i.e. synology container manager) to run blu-hawaii?

**Comment by SatanicMechanic** [comment]
I did look into that and may return to it, but from what I've gathered the additional overhead of docker on the lower end Synology units isn't recommended.

**Comment by SatanicMechanic** [comment]
I got the container running and doesn't seem to be causing any resource exhaustion.  Will reopen if it hampers sleep at all.
