### ISSUE TITLE
Jellyfin is Out of Date

### ISSUE THREAD

**Issue by QuentinDOS** [SynoCommunity/spksrc#6125]
The current version of Jellyfin is 10.9.5 as for what's released, SynoCommunity version is still on 10.8.13-13. I just generally am wanting to see the version updated if possible as it hasn't been updated in several months and a lot of bug fixes are in the newer versions.

Thank you.

**Comment by hgy59** [comment]
It is on the way #6101

**Comment by QuentinDOS** [comment]
Thank you for letting me know!
