### ISSUE TITLE
Jellyfin Upgrade Request 

### ISSUE THREAD

**Issue by TRUNKSNEO** [SynoCommunity/spksrc#6138]
### Software Name

Jellyfin

### Brief Description

The last SPK version published is 10.8.13; the current upstream release is 10.9.6

It would be awesome to get a version upgrade @stevenliuit 

Jellyfin is the volunteer-built media solution that puts you in control of your media. Stream to any device from your own server, with no strings attached. Your media, your server, your way.

### Website

https://jellyfin.org/

### Documentation

https://jellyfin.org/docs/

### Build/Installation documentation

https://jellyfin.org/docs/general/installation/source

### Source code

https://github.com/jellyfin/jellyfin

### OpenSource License

GPLv2

### Other License

https://github.com/jellyfin/jellyfin?tab=GPL-2.0-1-ov-file

**Comment by TRUNKSNEO** [comment]
Apologies for giving extra work... I looked it up in Issues, but now I know its a pull request, will have that in to account next time, thank you.

**Comment by hgy59** [comment]
@TRUNKSNEO so I reopened this to have an open issuer that links to the PR...
