### ISSUE TITLE
lcdproc - LCD display driver daemon and clients

### ISSUE THREAD

**Issue by Rogger** [SynoCommunity/spksrc#614]
Hi,

I would like to get lcdproc working on the synology. It can be used to print system status information (cpu,ram,network,..) onto a simple LCD display connect using usb and ftdi.

Dependency tree needed:
lcdproc
  libftdi
   libusb
   libconfuse

I successfully created a package cross/libconfuse, but I'm struggling to compile the package cross/libftdi, it needs cmake. I adapted cross/musek+/Makefile, but I always get the error message:
make[1]: Entering directory `/home/michael/spksrc/cross/libftdi/work/libftdi1-1.0'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/home/michael/spksrc/cross/libftdi/work/libftdi1-1.0'
make: *** [compile_target] Error 2

cross/libftdi
----
PKG_NAME = libftdi1
PKG_VERS = 1.0
PKG_EXT = tar.bz2
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.intra2net.com/en/developer/libftdi/download/

DEPENDS =

HOMEPAGE = http://www.intra2net.com/en/developer/libftdi/
COMMENT  = LIBFTDI
LICENSE  =

CONFIGURE_TARGET = myConfigure
INSTALL_TARGET = myInstall
ENV += CMAKE_INCLUDE_PATH="$(STAGING_INSTALL_PREFIX)/include" CMAKE_LIBRARY_PATH="$(STAGING_INSTALL_PREFIX)/lib"

include ../../mk/spksrc.cross-cc.mk

.PHONY: myConfigure
myConfigure:
        $(RUN) cmake -DPREFIX=$(INSTALL_PREFIX) ./

.PHONY: myInstall
myInstall:
        $(RUN) $(MAKE) install DESTDIR=$(INSTALL_DIR)

---

Any idea what I am doing wrong?

Thanks

**Comment by Dr-Bean** [comment]
I'll close this issue, as the original problem has been resolved. 
PR #652 has developed some merge conflicts over time, so it would need a review and probably some updates to get it back to merge-able.
