### ISSUE TITLE
Transmission update

### ISSUE THREAD

**Issue by kgyuri1973** [SynoCommunity/spksrc#6146]
### Software Name

Transmission

### Brief Description

Please update transmission software.
Thank you.

### Website

https://transmissionbt.com/

### Build/Installation documentation

https://github.com/transmission/transmission/blob/main/docs/Building-Transmission.md

### Source code

https://github.com/transmission/transmission

### OpenSource License

GPLv3

**Comment by hgy59** [comment]
This is already work in progress in #6126
