### ISSUE TITLE
kiwix comminty app not working 

### ISSUE THREAD

**Issue by wonderingStars** [SynoCommunity/spksrc#6150]
the kiwix  app loads but there is no content it just ask you choose lang and search bar when i search nothing is found the nas is connected to the internet i also tried to load the zim file in to the folder from my desktop machine that didnt work either

**Comment by hgy59** [comment]
@wonderingStars please read https://github.com/SynoCommunity/spksrc/wiki/Kiwix

**Comment by mreid-tt** [comment]
@wonderingStars, just circling back on some older tickets. Do you still require assistance or should this issue be closed?

**Comment by mreid-tt** [comment]
Since there haven't been any updates on this ticket for a while, we'll go ahead and close it. Feel free to reopen if you need further assistance!
