### ISSUE TITLE
[Package Request] expect

### ISSUE THREAD

**Issue by digi74** [SynoCommunity/spksrc#6169]
### Software Name

expect

### Brief Description

Expect is a tool for automating interactive applications such as telnet, ftp, passwd, fsck, rlogin, tip, etc. Expect is also useful for testing these same applications.

### Website

https://packages.debian.org/bookworm/expect

### Documentation

https://sourceforge.net/projects/expect/

### Build/Installation documentation

https://sourceforge.net/projects/expect/

### Source code

https://sourceforge.net/projects/expect/

### OpenSource License

MIT

**Comment by hgy59** [comment]
@digi74 what do you need `expect` for?
AFAICS expect requires tcl and is hard to cross compile.

**Comment by digi74** [comment]
Thanks for asking!
A backup script that connects to switches via telnet and pulls a configuration backup. Unfortunately these devices do not support ssh.
I thought it might be easy, not in this case, no problem
:)

**Comment by hgy59** [comment]
> Thanks for asking! A backup script that connects to switches via telnet and pulls a configuration backup. Unfortunately these devices do not support ssh. I thought it might be easy, not in this case, no problem :)

Don't give up so fast, I have done some progress, I tend to include `expect` in the synocli-misc package.

**Comment by digi74** [comment]
I think you really don't need the examples.
an example of my telnet part of the script:

`expect - <<EOF
	set timeout 10
	spawn ssh -l$username "$hostname"
	expect "password"
	send $password
	send "\r"
	expect "continue"
        send "\r"
	expect "#"
	send "copy startup-config tftp fs1 $tftpfolder/$filename pc\r"
	sleep 3

	send "exit\r"
	expect "#"
	send "exit\r"
	expect ">"
	send "quit\r"
	expect "log out"
	send "y"
EOF`

regards us gsiberg

**Comment by hgy59** [comment]
@digi74 you can download the synocli-misc package created by github build action 
https://github.com/SynoCommunity/spksrc/actions/runs/9847463175

you need to extract the spk file from the artifacts-zip-file for the arch of you model, then you can manually install the spk File in the DSM package center.

**Comment by digi74** [comment]
I am thrilled!
It works after changing from "#!/bin/bash" to "#!/bin/sh" in the script.
THANKS

**Comment by hgy59** [comment]
@digi74 thanks for the feedback.

Indeed, the example scripts use `/bin/sh` too 

```
#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
exec tclsh "$0" ${1+"$@"}

package require Expect

...
```
