### ISSUE TITLE
[Package Update Request] rdiff-backup and Python 3.11 for DSM 7.2

### ISSUE THREAD

**Issue by seb-stien** [SynoCommunity/spksrc#6173]
### Software Name

rdiff-backup

### Brief Description

Reverse differential backup tool, over a network or locally.
Uses Python Programming Language 3.11
rdiff-backup and Python 3.11 exist for DSM 7.1 but not for 7.2
https://synocommunity.com/package/rdiff-backup
https://synocommunity.com/package/python311
That block me from upgrading my DSM
Thanks for help ! ;)

### Website

https://rdiff-backup.net/

### Build/Installation documentation

https://github.com/rdiff-backup/rdiff-backup#installation

### Source code

https://github.com/rdiff-backup/rdiff-backup

### OpenSource License

GPLv2

**Comment by hgy59** [comment]
@seb-stien you don't need a dedicated package for DSM 7.2. All DSM 7.1 packages run on DSM 7.2 too.

**Comment by seb-stien** [comment]
Hi !
Thanks for your answer and work !
I found some packets that have been specificly updated with dsm 7.2 version packet ... so I didn't understand why to propose the 2 versions : 7.1 and 7.2 if 7.1 is enough and working on dsm 7.2
That is the case for SynoKernel  : https://synocommunity.com/package/synokernel-cdrom
But if 7.1 packet version is working on dsm 7.2 that is good news
Before upgrading my dsm does anyone validated this with rdiff-backup and python 3.11 on dsm 7.2 ?
@hgy59 do you have an idea of the https://github.com/SynoCommunity/spksrc/pull/6049 finalization / availability date ?
Thank you very much and wich you a sunny day (raining here in paris :-/ )
Seb

**Comment by hgy59** [comment]
> @hgy59 do you have an idea of the #6049 finalization / availability date ?

As noted in #6049 it depends on #6040

**Comment by seb-stien** [comment]
Just a feedback after upgrade from DSM 7.1 to 7.2 : all still working (python 3.11 and rdiff-backup) :+1: 
If not installed, you can install on DSM 7.2 this 2 packets even if packaged for DSM 7.2 
Hope it will help some of you guys

**Comment by hgy59** [comment]
@seb-stien #6040 is now ready for testing.

**Comment by seb-stien** [comment]
Hey;
Thanks for working on that :)
I'm not able to test it for now but will keep it in mind as soon as that's possible
For now I do have 7.1 packet working fine on DSM 7.2 
Have a nice week,

**Comment by hgy59** [comment]
> For now I do have 7.1 packet working fine on DSM 7.2

We do not publish addtional packages for DSM 7.2 , when DSM 7.1 package runs on 7.2.
So far we only publish jellyfin for DSM 7.2 since it does not work on DSM 7.1,

And for the synokernel-* packages, since those must match the DSM Version, we publish DSM 7.1 and 7.2 packages.
