### ISSUE TITLE
jellyfin_armv7-7.0_10.7.0-1 crashing on start in synology ds218j

### ISSUE THREAD

**Issue by R3dWolfie** [SynoCommunity/spksrc#6182]
![image](https://github.com/user-attachments/assets/522d9f8c-2f9e-45b3-8778-9ef3514607c4)
when trying to run jelly fin it just runs for a bit then get manually stopped, assuming a crash, where can i find the logs to send?

**Comment by hgy59** [comment]
I guess that jellyfin does not run on armada38x.
We don't support this old version of jellyfin.
jellyfin is not supported on 32 bit cpu models since 10.9.6-14

_for future issues: please use the bug report issue template and provide DS model, DSM version and other info in the predefined form._

**Comment by mreid-tt** [comment]
Since there haven't been any updates on this ticket for a while, we'll go ahead and close it. Feel free to reopen if you need further assistance!
