### ISSUE TITLE
[Package Feature Request]  Cloudflare Tunnel option

### ISSUE THREAD

**Issue by freitasm** [SynoCommunity/spksrc#6184]
### Software Name

Cloudflare Tunnel

### Brief Description

Cloudflared connects to IPv4 edge by default. There's an option _--edge-ip-version auto_ that will pick IPv4 or IPv6 depending on available networks on the running machine.

Is it possible to have this option by default when running the Cloudflare Tunnel package https://synocommunity.com/package/cloudflared?

More information: https://github.com/cloudflare/cloudflared/issues/842#issuecomment-1358156950

### Website

https://www.cloudflare.com

### Documentation

https://github.com/cloudflare/cloudflared/issues/842#issuecomment-1358156950

### Build/Installation documentation

N/A

### Source code

N/A

### OpenSource License

MIT

**Comment by hgy59** [comment]
@karasevm as a primary feature the package should install a config.yml file and run cloudflared with the option --config.

**Comment by freitasm** [comment]
@karasevm thanks!

**Comment by freitasm** [comment]
@karasevm do you see the options screen when updating the package or only at install time?

**Comment by karasevm** [comment]
@freitasm only during the initial install

**Comment by freitasm** [comment]
@karasevm Ok, so would have to uninstall the package and install again, with the same tunnel key.

Thank you, and thanks for your work.

**Comment by freitasm** [comment]
This is now available through the SynoCommunity repo. Removed the previous version and installed again (to use the new config screen).

All working now, connected via IPv6.

Thanks @karasevm 

![image](https://github.com/user-attachments/assets/0bd508e6-18ec-4773-bfe9-79c5e830162d)
