### ISSUE TITLE
[Package Request] 

### ISSUE THREAD

**Issue by icegood** [SynoCommunity/spksrc#6188]
### Software Name

gdb

### Brief Description

We need gdb at least somwhere. Toochains are missed them like
https://global.synologydownload.com/download/ToolChain/toolchain/7.1-42661/Marvell%20Armada%20370%20Linux%203.2.101/armada370-gcc850_glibc226_hard-GPL.txz
at it is not possible to properly debug programs for now

### Website

https://sourceware.org/gdb/

### Build/Installation documentation

???

### Source code

https://sourceware.org/gdb/

### OpenSource License

GPLv2

### Other License

???

**Comment by th0ma7** [comment]
gdb is available part of the `synocli-devel` package which includes various development tools.
Ref.: https://synocommunity.com/package/synocli-devel

**Comment by icegood** [comment]
yes. thx
