### ISSUE TITLE
[Package Update] borg to v1.4 and borgmatic to v1.8.13

### ISSUE THREAD

**Issue by rmeissn** [SynoCommunity/spksrc#6195]
### Software Name

borgbackup

### Brief Description

This is an update request to update borg from 1.2.6 to 1.4.0 to gain software (security) fixes and borgmatic from 1.8.2 to 1.8.13 to support additional monitoring services (like uptime kumo) and gain software (security) fixes.

Borgmatic: https://github.com/borgmatic-collective/borgmatic/releases

I guess it's a simple version update, as no breaking changes are listed either of the changelogs.

### Website

https://github.com/borgbackup/borg/releases

### Documentation

https://borgbackup.readthedocs.io/en/stable/changes.html#borg-1-2-x-to-1-4-x

### Build/Installation documentation

https://borgbackup.readthedocs.io/en/stable/

### Source code

https://github.com/borgbackup/borg/tree/1.4-maint

### OpenSource License

other (please specify below)

### Other License

BSD-3-Clause

**Comment by jens-arnold** [comment]
I support this update request. Borgmatic 1.8.5 and again 1.8.10 contain important updates for repository checks. See upstream issue tracker: https://projects.torsion.org/borgmatic-collective/borgmatic/issues/779

**Comment by tony1661** [comment]
Borgmatic 1.9.0 has now been released. It would be great to have this merged as support for Zabbix monitoring has been added.
