### ISSUE TITLE
DSM 7.x x86_64 packages?

### ISSUE THREAD

**Issue by MKV76** [SynoCommunity/spksrc#6196]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Sabnzbd

### Package Version

Any

### Device Model

DS1019+

### Device Architecture

x86_64

### Firmware Version

7.0

### What happened?

After finally migrating to DSM 7, many packages that worked before like SABNzbd, now say “incompatible”. So I tried to reinstall with the right 7.x package but don’t see the x86_64 version anywhere in architectures. Only the 6.2 versions. This is in many packages, just chose the SABNzbd as an example. Is this by design? Can I pick another arch package?

<img width="877" alt="image" src="https://github.com/user-attachments/assets/331ba0dc-bcb0-46a6-b2f4-f866e5d1e943">

### Reproduction steps

1. Install dsm 7
2. 
3. 
...

### Install Log

```log
N/a
```

**Comment by hgy59** [comment]
@MKV76 If you add synocommunity to the DSM package center you always get the available packages for you model in the package center (this is the prefered way).

If you manually download the package(s) from https://synocommunity.com/packages you have to download the package for a specific arch.
The _generic_ archs `aarch64`, `armv7` and `x64` do not have a button for download (but we had _aarch64_ buttons until #5240).

The generic arch is `x64` (not x86_64) and all specific archs of a specific generic arch download the same package. E.g for sabnzbd the latest spk file for `x64` is:
https://packages.synocommunity.com/sabnzbd/70/sabnzbd.v70.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk

_unfortunately I can't tell why we have x86_64 in generic x64 for DSM 6_

BTW we do not support DSM 7.0 anymore, you have to update at least to DSM 7.1.
For DSM 7.0 the latest Sabnzbd package is v3.7.1-59.

**Comment by MKV76** [comment]
Thanx so much for your elaborate response. I feel kinda silly now, as I did see after your message that my initial upgrade of DSM got upto 7.0 and there was still the 7.2 update waiting for install. After I did that just now, the buttons to “repair” appeared for most of the broken packages.

So I’ll try them first and not bother with the manual packages for now. I think I was put off by the different mentioned archs from 6.2 to 7.x so I misconcluded.

This helps a lot, thank you.🙏🏼

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: hgy59 ***@***.***>
Verzonden: Sunday, August 18, 2024 7:20:45 PM
Aan: SynoCommunity/spksrc ***@***.***>
CC: MKV76 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [SynoCommunity/spksrc] DSM 7.x x86_64 packages? (Issue #6196)


@MKV76<https://github.com/MKV76> If you add synocommunity to the DSM package center you always get the available packages for you model in the package center (this is the prefered way).

If you manually download the package(s) from https://synocommunity.com/packages you have to download the package for a specific arch.
The generic archs aarch64, armv7 and x64 do not have a button for download (but we had aarch64 buttons until #5240<https://github.com/SynoCommunity/spksrc/pull/5240>).

The generic arch is x64 (not x86_64) and all specific archs of a specific generic arch download the same package. E.g for sabnzbd the latest spk file for x64 is:
https://packages.synocommunity.com/sabnzbd/70/sabnzbd.v70.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk

unfortunately I can't tell why we have x86_64 in generic x64 for DSM 6

BTW we do not support DSM 7.0 anymore, you have to update at least to DSM 7.1.
For DSM 7.0 the latest Sabnzbd package is v3.7.1-59.
