### ISSUE TITLE
[Package Request] moreutils ts

### ISSUE THREAD

**Issue by martinjonsson01** [SynoCommunity/spksrc#6199]
### Software Name

`moreutils`

### Brief Description

SynoCLI misc. Tools already includes some `moreutils` programs, but not `ts`. It's a program which adds timestamps to standard input:

```bash
$ (echo a; sleep 1; echo b; sleep 3; echo c; sleep 2; echo d; sleep 1) | ts
Feb 09 14:34:51 a
Feb 09 14:34:52 b
Feb 09 14:34:55 c
Feb 09 14:34:57 d
```

This can be used to improve logging for programs which do not include their own timestamps by piping them into `ts`.

### Website

https://joeyh.name/code/moreutils/

### Documentation

https://joeyh.name/code/moreutils/

### Build/Installation documentation

```
$ gmake
```

### Source code

`git://git.joeyh.name/moreutils`

### OpenSource License

GPLv2

**Comment by hgy59** [comment]
@martinjonsson01 ts is easy to include in the synocli-misc package.
`ts` is a perl script so you must install the Perl package by synology.

My intention is to not add perl as a package dependency and you must know by your own that you have to install perl to use ts.

**Comment by martinjonsson01** [comment]
Sounds good, thanks!
