### ISSUE TITLE
[Package Request] Auditd

### ISSUE THREAD

**Issue by bigrck64** [SynoCommunity/spksrc#6203]
### Software Name

Auditd

### Brief Description

I know we already have https://synocommunity.com/package/inotify-tools to monitor filesystem change, but we can't know what is the process who deleted one folder for example.
If we can have Auditd for DSM7, it would be awesome :)

### Website

https://github.com/linux-audit/audit-userspace

### Documentation

https://github.com/linux-audit/audit-userspace

### Build/Installation documentation

https://github.com/linux-audit/audit-userspace

### Source code

https://github.com/linux-audit/audit-userspace

### OpenSource License

GPLv2

**Comment by hgy59** [comment]
@bigrck64 audit-userspace requires systems with linux kernel >= 5.x
So only very few models are supported.

All archs with 5.x kernel
- epyc7002 (Toolchain 7.1 and 7.2)
- rtd1619b (Toolchain 7.1 and 7.2)

Supported Diskstation Models (rtd1619b)
- DS124, DS223, DS423, DS223j

Supported High Scalability Models (epyc7002)
- SA6400

**Comment by bigrck64** [comment]
Thanks for your input, I didn't check that Auditd required linux 5.x :(
I'm running some SA3600 (4.4.302+), RS818RP+ (3.10.108), DS720+ (4.4.302+), and one DS423+ (4.4.302+ ?!)
So you are right, not enough model would support Auditd, it doesn't worth the work.
