### ISSUE TITLE
[Package Request] Jellyfin for armada38xx

### ISSUE THREAD

**Issue by stake143** [SynoCommunity/spksrc#6214]
### Software Name

Jellyfin

### Brief Description

The Free Software Media System. It is an alternative to the proprietary Emby and Plex.
Earlier **in 2022, Jellyfin** from your repository **worked perfectly on DS216j** (armada38xx, DSM 6), but after the transition to DSM 7, Jellyfin was no longer released for armada38xx. Taking into account that there is a Jellyfin package for armada37xx in your repository for DSM 7 version, **please**, if you can, **build a Jellyfin package for armada38xx on DSM 7.2**.
Thanks in advance!

### Website

https://jellyfin.org

### Build/Installation documentation

https://jellyfin.org/docs/general/administration/building.html

### Source code

https://github.com/jellyfin/jellyfin

### OpenSource License

GPLv3

**Comment by stake143** [comment]
Or at least put in the repository the latest version of Jellyfin, available on an x32 processor (if I'm not mistaken, version Jellyfin 10.8.5-8) compiled for DSM 7. This would help a lot

**Comment by hgy59** [comment]
You will be sad if you run jellyfin on a 32 bit CPU.

**Comment by hgy59** [comment]
duplicate of #6182
