### ISSUE TITLE
ffmpeg with x264 and faac support

### ISSUE THREAD

**Issue by cytec** [SynoCommunity/spksrc#623]
would be really nice if someone could add ffmpeg and ffprobe with x264 and faac support

**Comment by fn002449** [comment]
@cytec Is this package (ffmpeg) removed?

**Comment by cytec** [comment]
@fn002449 nope, there is a ffmpeg SPK available on SynoCommunity and also there is a new Work in Progress PR for an updated version of ffmpeg here: https://github.com/SynoCommunity/spksrc/pull/1662

**Comment by fn002449** [comment]
Ah!! Thx.. its working!! :)
