### ISSUE TITLE
tvheadend can't find libva.so.2

### ISSUE THREAD

**Issue by redmilan4102** [SynoCommunity/spksrc#6240]
### Is this a new Bug?

- [x] I checked that the bug hasn't been reported before

### Package Name

tvheadend

### Package Version

4.3.20240623-37

### Device Model

DS220+

### Device Architecture

x86_64

### Firmware Version

7.2.1-69057

### What happened?

I installed tvheadend from the repo and everything was working fine until i tried to upload a .m3u wich was to big to handle. The webgui became lazy and i tried to stop the package and restart but it didn't help the webgui wasn't loading anymore. I decided to delete the package and reinstall. But since then i can't even start tvheadend anymore and the Synology Package manager want's to repair the package but without any luck.

### Reproduction steps

1. 
2. 
3. 
...

### Install Log

```log
This is the log from tvheadend when i try to start it.
I reinstalled synocli video driver and ffmpeg6 and libva.so.2 is present in the video driver package but tvheadend won't find it? I tried to creato a symlink to the tvheadend folder but this dindn't help either.
```

### Service Log

```log
Starting tvheadend command tvheadend -f -C -u sc-tvheadend -g synocommunity --http_port 9981 --htsp_port 9982 -c /volume1/@appdata/tvheadend -p /volume1/@appdata/tvheadend/tvheadend.pid -l /volume1/@appdata/tvheadend/tvheadend.log --debug ""
tvheadend: error while loading shared libraries: libva.so.2: cannot open shared object file: No such file or directory
tvheadend is not running
```

**Comment by christianloerner** [comment]
I have the same issue here too. Today I upgraded the packages on the Synology and now TVHeadend is not starting

**Comment by redmilan4102** [comment]
> I have the same issue here too. Today I upgraded the packages on the Synology and now TVHeadend is not starting

Ok, somehow glad i am not the only one.
What i have tried so far is using older tvheadend versions with ffmpeg 5 and 4 an no one is working.

all of them depend since 4.3.20240904-38 on _Update to FFMPEG 6.0.1 using new synocli-videodriver package_
Maybe this has something to do with it

**Comment by th0ma7** [comment]
It does, have you also updated to latest ffmpeg6 and installed synocli-videodriver package?

**Comment by christianloerner** [comment]
Yes I did upgrade latest ffmpeg6 and installed synocli-videodriver package.

**Comment by th0ma7** [comment]
Could someone install `synocli-devel` package and run `libtree` over ffmpeg and tvheadend binaries?

<details> <summary>Such as for ffmpeg</summary>
<pre><code>
$ /var/packages/synocli-devel/target/bin/libtree -p /var/packages/ffmpeg6/target/bin/ffmpeg6 
/var/packages/ffmpeg6/target/bin/ffmpeg6 
├── /var/packages/ffmpeg6/target/lib/libavdevice.so.60 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libavfilter.so.9 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libswscale.so.7 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   │   │   │   ├── /var/packages/synocli-videodriver/target/lib/libva-drm.so.2 [rpath]
│   │   │   │   │   ├── /var/packages/synocli-videodriver/target/lib/libva.so.2 [rpath]
│   │   │   │   │   └── /var/packages/synocli-videodriver/target/lib/libdrm.so.2 [rpath]
│   │   │   │   ├── /var/packages/synocli-videodriver/target/lib/libOpenCL.so.1 [rpath]
│   │   │   │   ├── /var/packages/synocli-videodriver/target/lib/libmfx.so.1 [rpath]
│   │   │   │   ├── /var/packages/synocli-videodriver/target/lib/libdrm.so.2 [rpath]
│   │   │   │   ├── /var/packages/synocli-videodriver/target/lib/libva.so.2 [rpath]
│   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libpostproc.so.57 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libfreetype.so.6 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   │   └── /var/packages/ffmpeg6/target/lib/libpng16.so.16 [rpath]
│   │   │       └── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libfontconfig.so.1 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libfreetype.so.6 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libexpat.so.1 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libavformat.so.60 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libavcodec.so.60 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libswresample.so.4 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libsoxr.so.0 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libopenh264.so.7 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libSvtHevcEnc.so.1 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libx265.so.209 [rpath]
│   │   │   │   │   ├── /lib/libmvec.so.1 [default path]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libx264.so.164 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libwebp.so.7 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libsharpyuv.so.0 [rpath]
│   │   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libvorbisenc.so.2 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libvorbis.so.0 [rpath]
│   │   │   │   │   │   └── /var/packages/ffmpeg6/target/lib/libogg.so.0 [rpath]
│   │   │   │   │   │       └── /lib/librt.so.1 [default path]
│   │   │   │   │   └── /var/packages/ffmpeg6/target/lib/libogg.so.0 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libvorbis.so.0 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libtwolame.so.0 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libtheoradec.so.1 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libtheoraenc.so.1 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libogg.so.0 [rpath]
│   │   │   │   │   └── /lib/librt.so.1 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libSvtAv1Enc.so.2 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libspeex.so.1 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libshine.so.3 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libopus.so.0 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libopenjp2.so.7 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libopencore-amrnb.so.0 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libmp3lame.so.0 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libfdk-aac.so.2 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libcodec2.so.1.1 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libaom.so.3 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libvpx.so.9 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libzvbi.so.0 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libpng16.so.16 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libopencore-amrwb.so.0 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libdav1d.so.7 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/liblzma.so.5 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libiconv.so.2 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libwebpmux.so.3 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libwebp.so.7 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libsharpyuv.so.0 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/synocli-videodriver/target/lib/libva.so.2 [rpath]
│   │   │   │   ├── /var/packages/synocli-videodriver/target/lib/libmfx.so.1 [rpath]
│   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libiconv.so.2 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libzmq.so.5 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libsodium.so.26 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/librist.so.4 [rpath]
│   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/librabbitmq.so.4 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libssl.so.1.1 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libcrypto.so.1.1 [rpath]
│   │   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libcrypto.so.1.1 [rpath]
│   │   │   │   ├── /lib/libpthread.so.0 [default path]
│   │   │   │   └── /lib/librt.so.1 [default path]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libgnutls.so.30 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libunistring.so.5 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libgmp.so.10 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libhogweed.so.6 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libnettle.so.8 [rpath]
│   │   │   │   │   └── /var/packages/ffmpeg6/target/lib/libgmp.so.10 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libnettle.so.8 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libtasn1.so.6 [rpath]
│   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libbluray.so.2 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libxml2.so.2 [rpath]
│   │   │   │   │   └── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libfontconfig.so.1 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libfreetype.so.6 [rpath]
│   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libchromaprint.so.1 [rpath]
│   │   │   │   └── /var/packages/ffmpeg6/target/lib/libfftw3.so.3 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libxml2.so.2 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libzimg.so.2 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libzmq.so.5 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libavcodec.so.60 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libass.so.9 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libfreetype.so.6 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libfontconfig.so.1 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libharfbuzz.so.0 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libfreetype.so.6 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libglib-2.0.so.0 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libiconv.so.2 [rpath]
│   │   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libpcre2-8.so.0 [rpath]
│   │   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libfribidi.so.0 [rpath]
│   │   │   └── /var/packages/ffmpeg6/target/lib/libiconv.so.2 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libfribidi.so.0 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libswresample.so.4 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   │   ├── /var/packages/synocli-videodriver/target/lib/libmfx.so.1 [rpath]
│   │   ├── /var/packages/synocli-videodriver/target/lib/libOpenCL.so.1 [rpath]
│   │   ├── /var/packages/synocli-videodriver/target/lib/libva.so.2 [rpath]
│   │   └── /lib/libpthread.so.0 [default path]
│   ├── /var/packages/ffmpeg6/target/lib/libavformat.so.60 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libcaca.so.0 [rpath]
│   │   └── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libdc1394.so.26 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libavcodec.so.60 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   ├── /var/packages/synocli-videodriver/target/lib/libdrm.so.2 [rpath]
│   └── /lib/libpthread.so.0 [default path]
├── /var/packages/ffmpeg6/target/lib/libavfilter.so.9 [rpath]
├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
├── /var/packages/ffmpeg6/target/lib/libswscale.so.7 [rpath]
├── /var/packages/ffmpeg6/target/lib/libswresample.so.4 [rpath]
├── /var/packages/ffmpeg6/target/lib/libpostproc.so.57 [rpath]
├── /var/packages/ffmpeg6/target/lib/libavcodec.so.60 [rpath]
├── /var/packages/ffmpeg6/target/lib/libavformat.so.60 [rpath]
└── /lib/libpthread.so.0 [default path]
</code></pre>
</details>

<details> <summary>And for tvheadend</summary>
<pre><code>
$ /var/packages/synocli-devel/target/bin/libtree -p /var/packages/tvheadend/target/bin/tvheadend 
/var/packages/tvheadend/target/bin/tvheadend 
├── /var/packages/tvheadend/target/lib/libhdhomerun.so [rpath]
│   ├── /lib/libpthread.so.0 [default path]
│   └── /lib/librt.so.1 [default path]
├── /var/packages/tvheadend/target/lib/libiconv.so.2 [rpath]
├── /var/packages/tvheadend/target/lib/libdvbcsa.so.1 [rpath]
├── /var/packages/tvheadend/target/lib/libssl.so.3 [rpath]
│   ├── /var/packages/tvheadend/target/lib/libcrypto.so.3 [rpath]
│   │   └── /lib/libpthread.so.0 [default path]
│   └── /lib/libpthread.so.0 [default path]
├── /var/packages/tvheadend/target/lib/libcrypto.so.3 [rpath]
├── /var/packages/tvheadend/target/lib/libz.so.1 [rpath]
├── /var/packages/tvheadend/target/lib/liburiparser.so.1 [rpath]
├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   ├── /var/packages/synocli-videodriver/target/lib/libva-drm.so.2 [rpath]
│   │   ├── /var/packages/synocli-videodriver/target/lib/libva.so.2 [rpath]
│   │   └── /var/packages/synocli-videodriver/target/lib/libdrm.so.2 [rpath]
│   ├── /var/packages/synocli-videodriver/target/lib/libOpenCL.so.1 [rpath]
│   ├── /var/packages/synocli-videodriver/target/lib/libmfx.so.1 [rpath]
│   ├── /var/packages/synocli-videodriver/target/lib/libdrm.so.2 [rpath]
│   ├── /var/packages/synocli-videodriver/target/lib/libva.so.2 [rpath]
│   └── /lib/libpthread.so.0 [default path]
├── /var/packages/ffmpeg6/target/lib/libavformat.so.60 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libavcodec.so.60 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libswresample.so.4 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libsoxr.so.0 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libopenh264.so.7 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libSvtHevcEnc.so.1 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libx265.so.209 [rpath]
│   │   │   ├── /lib/libmvec.so.1 [default path]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libx264.so.164 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libwebp.so.7 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libsharpyuv.so.0 [rpath]
│   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libvorbisenc.so.2 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libvorbis.so.0 [rpath]
│   │   │   │   └── /var/packages/ffmpeg6/target/lib/libogg.so.0 [rpath]
│   │   │   │       └── /lib/librt.so.1 [default path]
│   │   │   └── /var/packages/ffmpeg6/target/lib/libogg.so.0 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libvorbis.so.0 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libtwolame.so.0 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libtheoradec.so.1 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libtheoraenc.so.1 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libogg.so.0 [rpath]
│   │   │   └── /lib/librt.so.1 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libSvtAv1Enc.so.2 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libspeex.so.1 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libshine.so.3 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libopus.so.0 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libopenjp2.so.7 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libopencore-amrnb.so.0 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libmp3lame.so.0 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libfdk-aac.so.2 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libcodec2.so.1.1 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libaom.so.3 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libvpx.so.9 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libzvbi.so.0 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libpng16.so.16 [rpath]
│   │   │   │   └── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libopencore-amrwb.so.0 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libdav1d.so.7 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/liblzma.so.5 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libiconv.so.2 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libwebpmux.so.3 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libwebp.so.7 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libsharpyuv.so.0 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/synocli-videodriver/target/lib/libva.so.2 [rpath]
│   │   ├── /var/packages/synocli-videodriver/target/lib/libmfx.so.1 [rpath]
│   │   └── /lib/libpthread.so.0 [default path]
│   ├── /var/packages/ffmpeg6/target/lib/libiconv.so.2 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libzmq.so.5 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libsodium.so.26 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   └── /lib/libpthread.so.0 [default path]
│   ├── /var/packages/ffmpeg6/target/lib/librist.so.4 [rpath]
│   │   └── /lib/libpthread.so.0 [default path]
│   ├── /var/packages/ffmpeg6/target/lib/librabbitmq.so.4 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libssl.so.1.1 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libcrypto.so.1.1 [rpath]
│   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libcrypto.so.1.1 [rpath]
│   │   ├── /lib/libpthread.so.0 [default path]
│   │   └── /lib/librt.so.1 [default path]
│   ├── /var/packages/ffmpeg6/target/lib/libgnutls.so.30 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libunistring.so.5 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libgmp.so.10 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libhogweed.so.6 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libnettle.so.8 [rpath]
│   │   │   └── /var/packages/ffmpeg6/target/lib/libgmp.so.10 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libnettle.so.8 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libtasn1.so.6 [rpath]
│   │   └── /lib/libpthread.so.0 [default path]
│   ├── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libbluray.so.2 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libxml2.so.2 [rpath]
│   │   │   └── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libfontconfig.so.1 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libfreetype.so.6 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libz.so.1 [rpath]
│   │   │   │   └── /var/packages/ffmpeg6/target/lib/libpng16.so.16 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libexpat.so.1 [rpath]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libfreetype.so.6 [rpath]
│   │   └── /lib/libpthread.so.0 [default path]
│   ├── /var/packages/ffmpeg6/target/lib/libchromaprint.so.1 [rpath]
│   │   └── /var/packages/ffmpeg6/target/lib/libfftw3.so.3 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libxml2.so.2 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   └── /lib/libpthread.so.0 [default path]
├── /var/packages/ffmpeg6/target/lib/libswscale.so.7 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   └── /lib/libpthread.so.0 [default path]
├── /var/packages/ffmpeg6/target/lib/libswresample.so.4 [rpath]
├── /var/packages/ffmpeg6/target/lib/libavfilter.so.9 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libswscale.so.7 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libpostproc.so.57 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   │   └── /lib/libpthread.so.0 [default path]
│   ├── /var/packages/ffmpeg6/target/lib/libfreetype.so.6 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libfontconfig.so.1 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libavformat.so.60 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libzimg.so.2 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libzmq.so.5 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libavcodec.so.60 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libass.so.9 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libfreetype.so.6 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libfontconfig.so.1 [rpath]
│   │   ├── /var/packages/ffmpeg6/target/lib/libharfbuzz.so.0 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libfreetype.so.6 [rpath]
│   │   │   ├── /var/packages/ffmpeg6/target/lib/libglib-2.0.so.0 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libiconv.so.2 [rpath]
│   │   │   │   ├── /var/packages/ffmpeg6/target/lib/libpcre2-8.so.0 [rpath]
│   │   │   │   └── /lib/libpthread.so.0 [default path]
│   │   │   └── /lib/libpthread.so.0 [default path]
│   │   ├── /var/packages/ffmpeg6/target/lib/libfribidi.so.0 [rpath]
│   │   └── /var/packages/ffmpeg6/target/lib/libiconv.so.2 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libfribidi.so.0 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libswresample.so.4 [rpath]
│   ├── /var/packages/ffmpeg6/target/lib/libavutil.so.58 [rpath]
│   ├── /var/packages/synocli-videodriver/target/lib/libmfx.so.1 [rpath]
│   ├── /var/packages/synocli-videodriver/target/lib/libOpenCL.so.1 [rpath]
│   ├── /var/packages/synocli-videodriver/target/lib/libva.so.2 [rpath]
│   └── /lib/libpthread.so.0 [default path]
├── /var/packages/ffmpeg6/target/lib/libavcodec.so.60 [rpath]
├── /var/packages/synocli-videodriver/target/lib/libva-drm.so.2 [rpath]
├── /var/packages/synocli-videodriver/target/lib/libva.so.2 [rpath]
├── /lib/libpthread.so.0 [default path]
└── /lib/librt.so.1 [default path]
</code></pre>
</details>

**Comment by redmilan4102** [comment]
welp my bad even tough i was on the synocommunity tvheadend side and saw -38 i didn't notice my Package manager was only showing -37 version.

After manually downloading and installing -38 it works like a charm again.

thank you very much
![tvheadend](https://github.com/user-attachments/assets/f54e04d8-10ea-4005-b6cb-e80e68790120)

**Comment by th0ma7** [comment]
I'm so glad of that, I just couldn't figure out where the issue was, further as I am myself running that same version.  thnx!

**Comment by redmilan4102** [comment]
hehe at least it's an easy 'fix' you can rename the issue if you wan't to make it more specific. Since it's only about tvheadend was not starting.

have a nice day

**Comment by christianloerner** [comment]
Sorry for the stupid question.....which package should I download for my DS423+ ? I didn´t find a way to figure out, which one is the right one. 
Thank you all!

**Comment by redmilan4102** [comment]
DS423+ is geminilake refresh too. So in the synocummunity tvheadend site you click on the green DSM7x geminilake button to download it manually and install it on your Syno.

Here you go
[https://packages.synocommunity.com/tvheadend/38/tvheadend.v38.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk](url)

**Comment by th0ma7** [comment]
if that can help, more info on model and archs: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model

**Comment by th0ma7** [comment]
closing as no one else has hit the issue (at least for now).  thnx for reporting.

Also note, I'm already working on ffmpeg7 + tvheadend update https://github.com/SynoCommunity/spksrc/pull/6239
My personal testing worked well and intent to merge probably over the weekend.  Although having additional testers would be appreciated.  cheers!
