### ISSUE TITLE
[Package Request] Update Bazarr to latest and to use latest current available FFMPEG on the Synology (ffmpeg 6/7 as required by Media managers)

### ISSUE THREAD

**Issue by tjinn** [SynoCommunity/spksrc#6257]
### Software Name

Bazarr

### Brief Description

Tracks Sonarr/Radarr subtitles and downloads them.

### Website

https://www.bazarr.media/

### Build/Installation documentation

https://wiki.bazarr.media/Getting-Started/Installation/Windows/source/

### Source code

https://github.com/morpheus65535/bazarr

### OpenSource License

GPLv3

**Comment by smaarn** [comment]
@tjinn just to be sure I understand your point: bazarr is currently supposed to use the existing install ffmpeg install. So this issue is mostly about updating bazarr itself, right ? From 1.4.2 to 1.4.5 ?

**Comment by tjinn** [comment]
I am not sure. Its not on 1.4.5 but also any time I WANT to install it, its forcing an install of FFMPEG4 as a direct dependency so that probably has to be updated as well
![bazzar](https://github.com/user-attachments/assets/53d451e0-7981-4191-9720-38b739f19f53)

**Comment by smaarn** [comment]
I see. Indeed there are two things here:

1. The update of bazarr
2. The change of the dependency from ffmpeg Synology package (which is the version 4) to ffmpeg7.

Unfortunately we're currently stuck for bazarr build and update (here: https://github.com/SynoCommunity/spksrc/pull/6164) but I will try to integrate the ffmpeg switch inside.
