### ISSUE TITLE
[Package Request] FFmpeg7 with SynoCli Video Drivers

### ISSUE THREAD

**Issue by dateno1** [SynoCommunity/spksrc#6266]
### Software Name

FFmpeg7 with SynoCli Video Drivers

### Brief Description

FFmpeg is a complete, cross-platform solution to record, convert and stream audio and video. It includes libavcodec - the leading audio/video codec library. 

This package needs SynoCli Video Drivers for work

### Website

https://ffmpeg.org

### Documentation

https://ffmpeg.org/documentation.html

### Build/Installation documentation

https://trac.ffmpeg.org/wiki/CompilationGuide

### Source code

https://git.ffmpeg.org/ffmpeg.git

### OpenSource License

GPLv2

**Comment by th0ma7** [comment]
Can you please describe what your issue is?  NAS model? package version installed?

**Comment by dateno1** [comment]
> Can you please describe what your issue is? NAS model? package version installed?

DSM7.2.2.72861@DS918+

Currently used FFmpeg6 6.0.1-5 + Jellyfin 10.9.7-15

New Jellyfin 10.9.11-17 required ffmpeg7

**Comment by mreid-tt** [comment]
> New Jellyfin 10.9.11-17 required ffmpeg7

You can download ffmpeg7 from the Package Center or manually from the website https://synocommunity.com/package/ffmpeg7. If manually, you would choose Apollolake to match your DS918+

**Comment by dateno1** [comment]
> > New Jellyfin 10.9.11-17 required ffmpeg7
> 
> You can download ffmpeg7 from the Package Center or manually from the website https://synocommunity.com/package/ffmpeg7. If manually, you would choose [Apollolake](https://packages.synocommunity.com/ffmpeg7/1/ffmpeg7.v1.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk) to match your DS918+. Is it that you have an error when trying to install ffmpeg7?

I don't want to 'FFmpeg7' I needs 'FFmpeg7 with Video Drivers'

Normal ffmpeg7 maybe not work with VAAPI (Old (without Video driver) FFmpeg6 not worked and FFmpeg7 is maybe same)

**Comment by mreid-tt** [comment]
> I don't want 'FFmpeg7' I needs 'FFmpeg7 with Video Drivers'
> 
> Normal ffmpeg7 maybe not work with VAAPI (Old (without Video driver) FFmpeg6 not worked and FFmpeg7 is maybe same)

The ffmpeg7 package is now separate from the SynoCli Video Drivers. These are separate packages which allow for easier maintenance and faster development. You will first need to install the SynoCli Video Drivers from the Package Center or manually from https://synocommunity.com/package/synocli-videodriver. Once done, you can then install FFmpeg 7.

**Comment by dateno1** [comment]
> > I don't want 'FFmpeg7' I needs 'FFmpeg7 with Video Drivers'
> > Normal ffmpeg7 maybe not work with VAAPI (Old (without Video driver) FFmpeg6 not worked and FFmpeg7 is maybe same)

FFmpeg7 package isn't update at first time and Video Driver is release at recently

FFmpeg7 hasn't any defendancy like Video driver

> The FFmpeg 7 package is now independent of the SynoCli Video Drivers, allowing for easier maintenance and quicker updates. To install FFmpeg 7, first, download and install the SynoCli Video Drivers from the Package Center or manually from [this link](https://synocommunity.com/package/synocli-videodriver). After that, proceed with the installation of FFmpeg 7.
> 
> EDIT: I successfully use the new Jellyfin 10.9.11-17 with VAAPI on my DS916+. As you have a DS918+ with Apollolake you may also be able to use it with QSV.

How many codecs tested? FFmpeg6 (old version) work with H.264 8bit but not work well with so many codecs

If FFmpeg 7 work well with H.264 8bit + H.264 10bit + H.265 8bit + H.265 10bit It will support almost videos (I will close request)

**Comment by dateno1** [comment]
> Ffmpeg7 supports more codecs than ffmpeg6. It does support all the ones you are looking for.

Are they work with iGPU?

Software En/Decoding is too heavy for NAS CPU (**It most important**)

It over 5 years old one

I will waiting mreid-tt's reply

**Comment by mreid-tt** [comment]
@dateno1, you're more likely to run into CPU (and iGPU) limitations rather than software limitations with FFmpeg 7. In my setup, I can only transcode H.264, and I stick to HD rather than 4K. The [NAS Compatibility](https://docs.google.com/spreadsheets/d/1MfYoJkiwSqCXg8cm5-Ac4oOLPRtCkgUxU0jdj3tmMPc/) sheet provided by Plex is a great resource for understanding hardware-accelerated transcoding capabilities. Comparing my model to yours, here's how they stack up:

| Manufacturer | Model | SD (480p / 576p) | HD (720p) | HD (1080p) | H264 (2160p) | HEVC SDR (2160p) | HEVC HDR (2160p) |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Synology | DS916+ | Yes | Yes | Yes | No | No | No |
| Synology | DS918+ | Yes | Yes | Yes | Yes | H.264 Output | H.264 Output |

As you can see, my model only supports up to 1080p with H.264, while your model can handle 4K with H.264 and also supports H.265 HDR. The notes in the sheet for this column specifically state:

> Supports decoding 4K HEVC (H.265) & 4K H.264 SDR (8-bit)
> Encoding is limited to 1080p output

I suggest installing it and adjusting the playback settings to enable hardware decoding for H.264 and HEVC. Test your Jellyfin performance with these settings, then enable HEVC 10-bit and test again, checking the transcode logs for any errors. For instance, when I try HEVC 10-bit on my model, I get an error because my iGPU doesn't support it:

```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[hevc @ 0x7f966ff6cd00] No support for codec hevc profile 2.
[hevc @ 0x7f966ff6cd00] Failed setup for format vaapi: hwaccel initialisation returned error.
```

**Comment by dateno1** [comment]
> @dateno1, you're more likely to run into CPU (and iGPU) limitations rather than software limitations with FFmpeg 7. In my setup, I can only transcode H.264, and I stick to HD rather than 4K. The [NAS Compatibility](https://docs.google.com/spreadsheets/d/1MfYoJkiwSqCXg8cm5-Ac4oOLPRtCkgUxU0jdj3tmMPc/) sheet provided by Plex is a great resource for understanding hardware-accelerated transcoding capabilities. Comparing my model to yours, here's how they stack up:
> Manufacturer 	Model 	SD (480p / 576p) 	HD (720p) 	HD (1080p) 	H264 (2160p) 	HEVC SDR (2160p) 	HEVC HDR (2160p)
> Synology 	DS916+ 	Yes 	Yes 	Yes 	No 	No 	No
> Synology 	DS918+ 	Yes 	Yes 	Yes 	Yes 	H.264 Output 	H.264 Output
> 
> As you can see, my model only supports up to 1080p with H.264, while your model can handle 4K with H.264 and also supports H.265 HDR. The notes in the sheet for this column specifically state:
> 
> > Supports decoding 4K HEVC (H.265) & 4K H.264 SDR (8-bit)
> > Encoding is limited to 1080p output
> 
> I suggest installing it and adjusting the playback settings to enable hardware decoding for H.264 and HEVC. Test your Jellyfin performance with these settings, then enable HEVC 10-bit and test again, checking the transcode logs for any errors. For instance, when I try HEVC 10-bit on my model, I get an error because my iGPU doesn't support it:
> 
> ```
> Stream mapping:
>   Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_vaapi))
>   Stream #0:1 -> #0:1 (eac3 (native) -> aac (libfdk_aac))
> Press [q] to stop, [?] for help
> [hevc @ 0x7f966ff6cd00] No support for codec hevc profile 2.
> [hevc @ 0x7f966ff6cd00] Failed setup for format vaapi: hwaccel initialisation returned error.
> ```

Other codecs (exclude HEVC 10bit) work?

**Comment by mreid-tt** [comment]
> Other codecs (exclude HEVC 10bit) work?

For my older DS916+, I primarily use the H.264 format in HD, and it handles transcoding well, as shown in the following log:

```
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (dts (dca) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[hls @ 0x7f5b83455840] Opening '/volume1/@appdata/jellyfin/cache/transcodes/6f6a98f50d30790640ac8f5d862719e2-1.mp4' for writing
Output #0, hls, to '/volume1/@appdata/jellyfin/cache/transcodes/6f6a98f50d30790640ac8f5d862719e2.m3u8':
  Metadata:
    encoder         : Lavf61.1.100
  Stream #0:0: Video: h264 (High), vaapi(bt709, progressive), 640x268 [SAR 1:1 DAR 160:67], q=2-31, 544 kb/s, 23.98 fps, 13978 tbn (default)
      Metadata:
        encoder         : Lavc61.3.100 h264_vaapi
  Stream #0:1: Audio: aac, 48000 Hz, stereo, s16, 256 kb/s (default)
      Metadata:
        encoder         : Lavc61.3.100 libfdk_aac
```

However, most clients connected to my server can play videos natively, with about 96% of the playtime being DirectPlay. Of the remaining content that requires transcoding, less than a third involves video transcoding, usually for low-powered Android phones. Since I don’t use H.265 or HDR content, transcoding isn’t a significant need for my setup.

**Comment by th0ma7** [comment]
@dateno1 please refer to our wiki at https://github.com/SynoCommunity/spksrc/wiki/FAQ-FFmpeg

**Comment by dateno1** [comment]
> @dateno1 please refer to our wiki at https://github.com/SynoCommunity/spksrc/wiki/FAQ-FFmpeg

FFmpeg for DSM is not normal enviroments

FFmpeg6 (old version) work with H.264 8bit but not work well with so many codecs

Lastest (with Video Drivers) was fixed it

**Comment by dateno1** [comment]
> > Other codecs (exclude HEVC 10bit) work?
> 
> For my older DS916+, I primarily use the H.264 format in HD, and it handles transcoding well, as shown in the following log:
> 
> ```
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_vaapi))
>   Stream #0:1 -> #0:1 (dts (dca) -> aac (libfdk_aac))
> Press [q] to stop, [?] for help
> [hls @ 0x7f5b83455840] Opening '/volume1/@appdata/jellyfin/cache/transcodes/6f6a98f50d30790640ac8f5d862719e2-1.mp4' for writing
> Output #0, hls, to '/volume1/@appdata/jellyfin/cache/transcodes/6f6a98f50d30790640ac8f5d862719e2.m3u8':
>   Metadata:
>     encoder         : Lavf61.1.100
>   Stream #0:0: Video: h264 (High), vaapi(bt709, progressive), 640x268 [SAR 1:1 DAR 160:67], q=2-31, 544 kb/s, 23.98 fps, 13978 tbn (default)
>       Metadata:
>         encoder         : Lavc61.3.100 h264_vaapi
>   Stream #0:1: Audio: aac, 48000 Hz, stereo, s16, 256 kb/s (default)
>       Metadata:
>         encoder         : Lavc61.3.100 libfdk_aac
> ```
> 
> However, most clients connected to my server can play videos natively, with about 96% of the playtime being DirectPlay. Of the remaining content that requires transcoding, less than a third involves video transcoding, usually for low-powered Android phones. Since I don’t use H.265 or HDR content, transcoding isn’t a significant need for my setup.

Thanks for help

I will try to upgrade (And add result on here)

Client codec support is not problem at almost time

Mobile network han't enough speed for Big Size Original Files like BDRip

**Comment by dateno1** [comment]
Test Complete

I will close thread

Thanks for help
