### ISSUE TITLE
ownCloud error: Incorrect MySQL 'root' password

### ISSUE THREAD

**Issue by tbc0309** [SynoCommunity/spksrc#6278]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

ownCloud 

### Package Version

v10.15.0-18

### Device Model

DS920+

### Device Architecture

x86_64

### Firmware Version

DSM7.2.1

### What happened?

Install error, I have already reset the root password for MDB10.

### Reproduction steps

1. new install ownCloud v10.15.0-18, MDB10 root password I test like: qaz@WSX123456

### Install Log

```log
2024/10/13 22:35:13	Begin initialize_variables
2024/10/13 22:35:13	End initialize_variables
2024/10/13 22:35:13	===> Step preinst. STATUS=INSTALL USER=owncloud GROUP= SHARE_PATH=
2024/10/13 22:35:13	Begin validate_preinst
2024/10/13 22:35:13	install owncloud 10.15.0-18 End preinst ret=[1]
```

### Other Logs

```log
synopkgmgr.log

2024/10/13 17:45:13 Failed to install package, spk=[/volume1/@tmp/upload_tmp.36110] result=[{"action":"install","beta":false,"betaIncoming":false,"error":{"code":276,"description":"failed to run preinst script"},"finished":true,"installReboot":false,"installing":true,"language":"chs","last_stage":"preinstall","package":"owncloud","packageName":"ownCloud","pid":12800,"scripts":[{"code":1,"message":"Incorrect MySQL 'root' password\n","type":"preinst"}],"spk":"/volume1/@tmp/upload_tmp.36110","stage":"install_failed","status":"non_installed","status_code":255,"status_description":"failed to locate given package","success":false,"username":"mrtbc","version":"10.15.0-18"}]
2024/10/13 22:34:40 Failed to verify package, spk=[/volume1/@tmp/upload_tmp.278380] result=[{"action":"prepare","beta":false,"betaIncoming":false,"error":{"code":289,"description":"spk is not from synology"},"installReboot":false,"package":"owncloud","packageName":"ownCloud","stage":"prepare","success":false,"version":"10.15.0-18"}]
2024/10/13 22:35:04 Failed to verify package, spk=[/volume1/@tmp/upload_tmp.278380] result=[{"action":"prepare","beta":false,"betaIncoming":false,"error":{"code":289,"description":"spk is not from synology"},"installReboot":false,"package":"owncloud","packageName":"ownCloud","stage":"prepare","success":false,"version":"10.15.0-18"}]
2024/10/13 22:35:13 Failed to run preinst script for owncloud, 1
```

**Comment by mreid-tt** [comment]
@tbc0309, during the pre-install, the following command is run to verify the correct root password was supplied:

```
/usr/local/mariadb10/bin/mysql -u root -p"mypass" -e quit > /dev/null
```

If the password is correct there will be no output but if the password is incorrect you should see the following:
```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

Can you try to run the same command via SSH substituting your root password (rather than mypass) and tell me what you get?

**Comment by hgy59** [comment]
@mreid-tt did you test this?
I guess the parameter must be `-pmypass` (without double quotes)

**Comment by mreid-tt** [comment]
> @mreid-tt did you test this? I guess the parameter must be `-pmypass` (without double quotes)

Yes @hgy59, I've tested this multiple times across various packages which use the same code. I've just run the same test using the same password the user supplied above with success on my local VirtualDSM:
```
/usr/local/mariadb10/bin/mysql -u root -p"qaz@WSX123456" -e quit > /dev/null
```

**Comment by tbc0309** [comment]
> @tbc0309, during the pre-install, the following command is run to verify the correct root password was supplied:
> 
> ```
> /usr/local/mariadb10/bin/mysql -u root -p"mypass" -e quit > /dev/null
> ```
> 
> If the password is correct there will be no output but if the password is incorrect you should see the following:
> 
> ```
> ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
> ```
> 
> Can you try to run the same command via SSH substituting your root password (rather than mypass) and tell me what you get?

root@sa6400-72:~# /usr/local/mariadb10/bin/mysql -u root -p"qaz@WSX123456" -e quit
root@sa6400-72:~#

**Comment by mreid-tt** [comment]
@tbc0309, based on your feedback, the first password is correct.

**Comment by tbc0309** [comment]
> @tbc0309, based on your feedback, the first password is correct.

![1728836332225](https://github.com/user-attachments/assets/a3a44c66-8332-4555-975a-4fc08d5add86)

The error persists with the installation; others in my Telegram community have also reported this error, so I tested it.

**Comment by mreid-tt** [comment]
@tbc0309, thanks for the feedback, let me re-test on my setup.

**Comment by mreid-tt** [comment]
@tbc0309, I’ve identified the issue. It occurred in the install wizard where the root password variable was unintentionally overwritten. This oversight happened during the transition from SQLite to MariaDB, causing the pre-install script to receive a blank root password.

If you have a moment, please test the build available in my repository: [GitHub Actions Run](https://github.com/mreid-tt/spksrc/actions/runs/11317801325). Let me know if it resolves the problem, and I’ll proceed with updating the website.

**Comment by tbc0309** [comment]
The login interface is only visible during the first installation, but a 500 error will occur after entering the correct account and password. 
![1728866144850](https://github.com/user-attachments/assets/c95a4ad0-7c8b-4031-b1a7-5fab46351562)
![1728866171848](https://github.com/user-attachments/assets/c8417c6d-9375-433d-9de7-7086191040e3)

For the second fresh installation (after deleting the owncloud/data sharefolder), database parameters need to be filled in, otherwise login is not possible.

![1728866208279](https://github.com/user-attachments/assets/a26e2e33-d20b-4187-9601-ff1e420cd239)

**Comment by mreid-tt** [comment]
@tbc0309, this seems to be a different issue. Please create a new ticket for it. Regarding the second installation, did you uninstall the first one beforehand, or did you install it over the existing instance?

**Comment by mreid-tt** [comment]
@tbc0309, as mentioned earlier, please open a new ticket for this separate issue.
