### ISSUE TITLE
[Package Request] paperless-ngx

### ISSUE THREAD

**Issue by MAngel666** [SynoCommunity/spksrc#6286]
### Software Name

paperless-ngx

### Brief Description

Paperless-ngx is a community-supported open-source document management system that transforms your physical documents into a searchable online archive so you can keep, well, less paper.
Paperless-ngx is the official successor to the original [Paperless](https://github.com/the-paperless-project/paperless) & [Paperless-ng](https://github.com/jonaswinkler/paperless-ng) projects and is designed to distribute the responsibility of advancing and supporting the project among a team of people.

### Website

https://docs.paperless-ngx.com/

### Documentation

https://docs.paperless-ngx.com/setup/

### Build/Installation documentation

https://docs.paperless-ngx.com/setup/#bare_metal

### Source code

https://github.com/paperless-ngx/paperless-ngx

### OpenSource License

GPLv3

**Comment by MAngel666** [comment]
It could replace: https://github.com/SynoCommunity/spksrc/issues/3472

**Comment by hgy59** [comment]
paperless-ngx would be a huge package with many dependencies.

We recommend installing paperless-ngx in a Docker environment (called "Container Manager" by Synology).

**Comment by MAngel666** [comment]
hmm there was already one with paperless (not ngx), have the requirements increased so much?

**Comment by hgy59** [comment]
> hmm there was already one with paperless (not ngx), have the requirements increased so much?

This was another request...

As I said, bare metal installation has too many dependencies
- MySQL (MariaDB 10 by Synology)
- imagemagick (package exists)
- python (package exists, at least v3.10 and 3.11)
- redis (package exists)
- OCRmyPDF (too many dependencies in it, already recommended to run as docker container, and we do not support builds with qt-library/tools required for qpdf)
- Tesseract (package does not exist yet, package would be too large to host on synocommunity repository)
There might be more, didn't look into paperless-ngx for six months...

Finally, only DSM 7 (or 7.2?) would be supported (c++17) and I guess only aarch64 and x64, models that have Container Manager support.

---
The bare metal installation is exotic, the recommended installation is with Docker containers anyway.

**There is plenty of documentation on the web about setting up and running Paperless-NGX in containers on Synology devices.**

**Comment by MAngel666** [comment]
I've already working paperless-ngx in docker but it would be nice to have it as an app (security, rights etc.)

**Comment by hgy59** [comment]
Sorry, we can't do this
