### ISSUE TITLE
[Package Request] calibre

### ISSUE THREAD

**Issue by MAngel666** [SynoCommunity/spksrc#6298]
### Software Name

calibre

### Brief Description

calibre is a powerful and easy to use e-book manager. Users say it’s outstanding and a must-have. It’ll allow you to do nearly everything and it takes things a step beyond normal e-book software. It’s also completely free and open source and great for both casual users and computer experts.

### Website

https://calibre-ebook.com/

### Documentation

https://manual.calibre-ebook.com/

### Build/Installation documentation

https://github.com/kovidgoyal/calibre/blob/master/bypy/README.rst

### Source code

https://github.com/kovidgoyal/calibre/releases/tag/v7.20.0

### OpenSource License

GPLv3

**Comment by hgy59** [comment]
AFAICT Calibre is an application an can't be run on DSM.
We have COPS that can be used to provide access to a calibre database.

On DSM only web applications and services can be run, but no desktop applications.
