### ISSUE TITLE
COPS package must be restricted to DSM 7.2

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#6339]
COPS v3.2.2-11 was published for DSM 7.0 but it can't be installed on DSM 7.1.1 (lacking PHP 8.2)

The framework must be adjusted to create (and publish) noarch packages for DSM 7.2 when defined as `REQUIRED_MIN_DSM = 7.2`

spk/COPS/Makefile still defines `REQUIRED_MIN_DSM = 7.0` that must be adjusted, but the issue is, that `REQUIRED_MIN_DSM = 7.2` is not handled as expected yet.

**Comment by hgy59** [comment]
@mreid-tt is there any other package that depends on PHP 8.2?

**Comment by hgy59** [comment]
> @mreid-tt is there any other package that depends on PHP 8.2?

ok, found same issue with bicbucstriim

**Comment by mreid-tt** [comment]
> > @mreid-tt is there any other package that depends on PHP 8.2?
> 
> ok, found same issue with bicbucstriim

Correct, those are the only packages.

**Comment by mreid-tt** [comment]
> COPS v3.2.2-11 was published for DSM 7.0 but it can't be installed on DSM 7.1.1 (lacking PHP 8.2)
> 
> The framework must be adjusted to create (and publish) noarch packages for DSM 7.2 when defined as `REQUIRED_MIN_DSM = 7.2`
> 
> spk/COPS/Makefile still defines `REQUIRED_MIN_DSM = 7.0` that must be adjusted, but the issue is, that `REQUIRED_MIN_DSM = 7.2` is not handled as expected yet.

This is an interesting use case. Currently, users may encounter a package in the Package Center that cannot be installed due to a missing prerequisite on their system. With a fix, the package simply wouldn’t appear in the Package Center, streamlining the user experience. While not a critical issue, addressing this could be beneficial for future noarch packages.

**Comment by hgy59** [comment]
> While not a critical issue, addressing this could be beneficial for future noarch packages.

Don't agree, this ***is*** a critical issue. The repository must not deliver packages that are not installable.
The user is presented this message:
![grafik](https://github.com/user-attachments/assets/f928e588-1482-4972-8e3b-31558de4fcf3)

**Comment by mreid-tt** [comment]
> Don't agree, this _**is**_ a critical issue. The repository must not deliver packages that are not installable.
> The user is presented this message:

Wow! Synology could have treated with this a bit differently. I now understand the concern you raise.

**Comment by hgy59** [comment]
> Wow! Synology could have treated with this a bit differently. I now understand the concern you raise.

We could have requested PHP 8.2 for DSM 7.1.1, but I think the Synology support team will ignore this.

**Comment by hgy59** [comment]
@mreid-tt just created a support ticket at Synology to request PHP 8.2 for DSM 7.1.1 (for my DS115j).

just wait and see... 🤞
