### ISSUE TITLE
NAS DS715   JELLYFIN  

### ISSUE THREAD

**Issue by jpma-syno** [SynoCommunity/spksrc#6342]
je n'ai pas trouvé  le package jellyfin pour une architecture nas ds 715     alpine   bien  que le FFmepg  lui existe en alpine  
 what can i do  ?  
thank you very  much

**Comment by mreid-tt** [comment]
> je n'ai pas trouvé le package jellyfin pour une architecture nas ds 715 alpine bien que le FFmepg lui existe en alpine

Des tests précédents de .NET 6 avec des processeurs Alpine dans le cadre de #5574 ont révélé des incompatibilités entraînant des plantages. De plus, en raison des performances limitées des processeurs 32 bits et de leur absence de prise en charge du transcodage, ces processeurs ont été retirés des builds de Jellyfin il y a quelque temps.

**Comment by jpma-syno** [comment]
merci beaucoup   pour cette réponse rapide  je m'en doutais un peu   bonne continuation
