### ISSUE TITLE
add a mosh package

### ISSUE THREAD

**Issue by CircleCode** [SynoCommunity/spksrc#643]
[mosh](http://mosh.mit.edu/) (mobile shell) is a remote terminal application that allows roaming, supports intermittent connectivity, and provides intelligent local echo and line editing of user keystrokes.

Mosh is a replacement for SSH. It's more robust and responsive, especially over Wi-Fi, cellular, and long-distance links.

**Comment by paour** [comment]
I've been looking for mosh on Syno for a while, this would rock!

**Comment by alx** [comment]
I've created a proper package request: #2483

**Comment by cytec** [comment]
Duplicate https://github.com/SynoCommunity/spksrc/issues/2483 Closed
