### ISSUE TITLE
Package for NZBDrone [Request]

### ISSUE THREAD

**Issue by EvtK** [SynoCommunity/spksrc#671]
Hi there,

I don't know if it is even possible to request here, but I would really like to install NZBDrone as package on my synology NAS. Can this be added to the repository?

I read NZBDrone is build on mono, and I have seen an official synology mono package. But I'm no expert and would not know how to use this package to run NZBDrone.

Many thanks!

**Comment by Dr-Bean** [comment]
Mono v3.10.0-2 and Sonarr v20150101-3 have been published on the repository. Note that the packages are still in beta for now, so you'll need to enable seeing beta packages in the Package Center settings.

For people using the last packages as provided by @maxrogers in [this comment](https://github.com/SynoCommunity/spksrc/issues/671#issuecomment-68173062), the update won't show up via Package Center, as it's basically the same version. No need to reinstall. If a package update is released, it'll be recognized automatically.

Please report problems in a [new issue](https://github.com/SynoCommunity/spksrc/issues/new): this one will be closed (finally, yay)
Thanks @maxrogers for your work and being patient with us until spksrc was up for the task :)

**Comment by Diaoul** [comment]
Awesome :tada: 
@maxrogers Once the new spkrepo version will be in production I'll give you permission to publish updates to mono and sonarr. This should happen this month.

**Comment by Stanzilla** [comment]
Looks like the icon is missing though: http://i.imgur.com/ktjDaEM.png

**Comment by maxrogers** [comment]
@Dr-Bean Thanks!

@Diaoul, that will be so awesome!  :+1: Let me know

@Stanzilla, good catch! Fixed here: https://github.com/SynoCommunity/spksrc/pull/1422

**Comment by SpiderDice** [comment]
I'm on Sonarr Ver. 2.0.0.2594 and all of my shows are displaying an air time of 12:00am. Anyone else seeing this?

**Comment by derik0709** [comment]
@SpiderDice Yeah, it is because Sonarr switched to using theTVDB instead of Trakt. theTVDB doesn't have air times for shows. Everything else that has changed is explained here https://forums.sonarr.tv/t/sonarr-now-with-tvdb/3314

**Comment by SpiderDice** [comment]
@derik0709 Ahh..okay. Guess it's not that big of a deal since it's still picking up showing when they are released.

**Comment by schumi2004** [comment]
I thought I saw a list of architectures mono is working for in the past but can't seem to find it. What is current status for Sonarr + Mono, what architectures are excluded?

**Comment by maxrogers** [comment]
@schumi2004, the architectures not on this list:
bromolow cedarview evansport x86 armada370 88f6281 armadaxp comcerto2k avoton armada375 alpine x64

**Comment by schumi2004** [comment]
This is the working list right? (got confused since my arch is in the list and i mentioned excluded so not sure if you mean working or not ;) )

**Comment by maxrogers** [comment]
@schumi2004, correct. It is the current working list. The architectures not mentioned are not compatible.

**Comment by SickPotato** [comment]
Can someone update the Synology Mono package to 3.12.0?

''Mono 3.12.0 is the result of about 3 months of work, featuring over 600 commits and 68 fixes. It was the work of 70 contributors.''

http://www.mono-project.com/docs/about-mono/releases/3.12.0/

**Comment by markus101** [comment]
At this point I'd recommend sticking with 3.10, 3.12 introduced an bug that prevented Sonarr from starting up properly. We have implemented a workaround, but recommend erring on the side of caution.

**Comment by maxrogers** [comment]
@SickPotato @markus101, I will update the Mono package as soon as the outstanding 3.12 bug is resolved with a new release.

**Comment by Diaoul** [comment]
@maxrogers: do you think sonarr can hit the repo (non-beta)?

**Comment by maxrogers** [comment]
@diaoul, absolutely! Should I go ahead and remove the beta flag?

**Comment by maxrogers** [comment]
Also mono I would think?

**Comment by Diaoul** [comment]
Yes, both. However I have a problem when cross compiling mono:

```
install -m 755 -d /spksrc/spk/mono/work-armadaxp-5.1/staging/lib
tar -cpf - -C /spksrc/spk/mono/work-armadaxp-5.1/../../../native/mono/work-native/install/usr/local/lib . | tar -xpkf - -C /spksrc/spk/mono/work-armadaxp-5.1/staging/lib
tar: ./libmonoboehm-2.0.a: Cannot open: File exists
```

Do you have this issue? If possible I'd like to put latest Mono online.

**Comment by Taloth** [comment]
Just a heads up, be careful which mono version you put as non-beta, there have been some unstable ones. atm we have 3.10 as stable, coz there seems to be a problem on some OS with 3.12, nothing concrete, just random reports.

**Comment by Dr-Bean** [comment]
I suppose that we could release mono3.10 as-is as a stable package, and put up a beta mono3.12 on the repository (might be helpful from a troubleshooting pov?)

**Comment by Diaoul** [comment]
OK so 3.10 as stable and 3.12 as beta.

**Comment by Taloth** [comment]
Sounds good. That way some daredevils can run 3.12 and see if it's stable. We had problems with it on atleast OSX.

If you compile 3.10 and 3.12 straight from their respective branches in the mono repo it will include some security vulnerabilities.

Ref: http://www.mono-project.com/news/2015/03/07/mono-tls-vulnerability/

**Comment by maxrogers** [comment]
Here are the pull requests with beta flags removed. I also removed that redundancy in ```cross/mono/Makefile``` 

Mono: https://github.com/SynoCommunity/spksrc/pull/1605
Sonarr: https://github.com/SynoCommunity/spksrc/pull/1606

**Comment by danfozzy** [comment]
Looking at replacing my ds212+ with the new ds715. Is it to early to say if these packages will be supported on there, as I know some archs aren't able to run certain apps.

it's running on a Alpine AL-314

**Comment by Diaoul** [comment]
Too early to say. Please follow #1703

**Comment by fredguy** [comment]
Hi guys, 
Wondering if you could share with me the following. 
Sonarr tends to crash from time to time. So i'm triggering an alert with monit. 
Best would be to restrat the service when necessary, but i couldn't figure out the proper start command line. 
/usr/local/mono/bin/mono --debug /usr/local/nzbdrone/share/NzbDrone/NzbDrone.exe => failed
/var/packages/nzbdrone/scripts/start-stop-status start => failed.

I guess i'm missing some ENV details but can't figure them out. Any help appreciated. 
I'm on DSM5 (not planing to migrate jst yet coz Zarafa is running)
Cheers.

**Comment by Dr-Bean** [comment]
@fredguy Please ask your question in a new issue. Take a look at the guidelines too: https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issues.

For new readers, I've reported this before: This issue is closed, and questions should be reported in a new issue.
To prevent new comments from being made, I'm locking the conversation: this issue is too large and too many people will be pinged when comments are made.
