### ISSUE TITLE
TVheadend 3.4.27-6 not recording after boot

### ISSUE THREAD

**Issue by samukas** [SynoCommunity/spksrc#677]
I just got both DVB-T and DVB-S tuners for my Synology DS3612xs and decided to try Tvheadend as it seems much more powerfull than Synology's VideoStation.
Btw, VideoStation has to be always running otherwise no tuners are recognized.
For the most part the setup is working fine, but I have problems each time I reboot DSM.

I'm running the last DSM 4.3-3776 and my tuners are:
2x DVB-T PCTV nano Stick 
1x DVB-S2 PCTV Stick

Tvheadend will detect the tuners, but will not actually "tune in". Here's an example of me trying to record a programm on DVB-T and DVB-S after I've done a reboot:

	Oct 09 10:53:40.685 dvr: Configuration '(default)' not found
	Oct 09 10:53:40.686 dvr: "Teste" on "TDT RTP1" starting at 2013-10-09 10:40:00, scheduled for recording by "user"
	Oct 09 10:53:40.698 dvr: "Teste" on "TDT RTP1" recorder starting
	Oct 09 10:53:40.698 subscription: No transponder available for subscription "DVR: Teste" to channel "TDT RTP1"
	Oct 09 10:53:40.698 dvr: Recording unable to start: "Teste": No hardware present
	Oct 09 10:54:15.504 dvr: Configuration '(default)' not found
	Oct 09 10:54:15.504 dvr: "Test2" on "RTP Internacional" starting at 2013-10-09 10:48:00, scheduled for recording by "user"
	Oct 09 10:54:15.504 dvr: "Test2" on "RTP Internacional" recorder starting
	Oct 09 10:54:15.504 subscription: No transponder available for subscription "DVR: Test2" to channel "RTP Internacional"
	Oct 09 10:54:15.504 dvr: Recording unable to start: "Test2": No hardware present

If I stop Tvheadend in Package Center and start it again, the WebInterface won't even show-up/respond.
To get it working again, I have to stop Tvheadend, reboot Synology and then start Tvheadend.

	Oct 09 11:23:14.531 dvr: Configuration '(default)' not found
	Oct 09 11:23:14.531 dvr: "Test" on "RTP Internacional" starting at 2013-10-09 11:18:00, scheduled for recording by "user"
	Oct 09 11:23:14.546 dvr: "Test" on "RTP Internacional" recorder starting
	Oct 09 11:23:15.107 subscription: "DVR: Test" subscribing on "RTP Internacional", weight: 300, adapter: "NXP TDA10071", network: "EUTELSAT 13E", mux: "EUTELSAT 13E: 10,722,880 kHz Horizontal (HotBird LNB)", provider: "Arqiva", service: "RTPi", quality: 100
	Oct 09 11:23:15.208 TS: NXP TDA10071/EUTELSAT 13E: 10,722,880 kHz Horizontal (HotBird LNB)/RTPi: MPEG2VIDEO @ #1003: Continuity counter error
	Oct 09 11:23:15.267 dvr: /volume1/PVR_Recordings/TVHeadEnd/RTP-Internacional-Test.2013-10-09.11-25.ts from adapter: "NXP TDA10071", network: "EUTELSAT 13E", mux: "EUTELSAT 13E: 10,722,880 kHz Horizontal (HotBird LNB)", provider: "Arqiva", service: "RTPi"
	Oct 09 11:23:15.267 dvr:  #  type              lang  resolution  aspect ratio  sample rate  channels
	Oct 09 11:23:15.267 dvr:  1  MPEG2VIDEO              ?           ?                                    
	Oct 09 11:23:15.267 dvr:  2  TELETEXT                                                                 
	Oct 09 11:23:15.267 dvr:  3  MPEG2AUDIO        por                             ?            ?        

If DSM boots with Tvheadend started then it won't work. Would you happen to have some light on this issue? I'll try to keep my reboots to a minimum, but it is an annoyance, and I really don't want to go back to VideoStation.

Hopefully you'll be able to help me! Thanks so much.

**Comment by Dr-Bean** [comment]
Solved? Great, time to close the issue :)
