### ISSUE TITLE
TVHeadend with Video Station not running

### ISSUE THREAD

**Issue by Ecrelinf** [SynoCommunity/spksrc#682]
I made a little modification in the launch script of TvHeadEnd in order to load kernel modules whitout having video station running. I used the scripts from vide station so i must have the video station package installed but no need to run it. 
Here the modifications in /var/packages/tvheadend/scripts/start-stop-status : 
 1 - add the path to video station package in the top of the script : 
     VIDEO_PACKAGE_DIR="/var/packages/VideoStation"
 2 - add loading of modules in start section
3 - add unload modules in stop section

#!/bin/sh

# Package
PACKAGE="tvheadend"
DNAME="Tvheadend"
VIDEO_PACKAGE_DIR="/var/packages/VideoStation"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
PATH="${INSTALL_DIR}/bin:/usr/local/bin:/bin:/usr/bin:/usr/syno/bin"
USER="tvheadend"
TVHEADEND="${INSTALL_DIR}/bin/tvheadend"
PID_FILE="${INSTALL_DIR}/var/tvheadend.pid"

start_daemon ()
{
        echo Chargement des modules dvb ...
        [ -e "${VIDEO_PACKAGE_DIR}/target/scripts/DVB_Admin.sh" ] && ${VIDEO_PACKAGE_DIR}/target/scripts/DVB_Admin.sh "start" "${VIDEO_PACKAGE_DIR}"
        Starting ${DNAME} ...
    ${TVHEADEND} -f -u ${USER} -c ${INSTALL_DIR}/var -p ${PID_FILE}
}
 
stop_daemon ()
{
    kill `cat ${PID_FILE}`
    wait_for_status 1 20
    rm -f ${PID_FILE} 
    [ -e "${VIDEO_PACKAGE_DIR}/target/scripts/DVB_Admin.sh" ] && ${VIDEO_PACKAGE_DIR}/target/scripts/DVB_Admin.sh "stop" "${VIDEO_PACKAGE_DIR}"
}
....<no changes after> .....

It works like a charme for me,  enjoy ;o)

**Comment by Dr-Bean** [comment]
Closing due to age. If it's still necessary/useful, please open a pull request for this (although I don't know exactly what the state of the package is, and since I don't use it, I can't test it either)
