### ISSUE TITLE
RuTorrent Beta

### ISSUE THREAD

**Issue by Nonobis** [SynoCommunity/spksrc#691]
Hi,

Has someboy use the PluginRPC with this package ?
I can't find the right url to use with sickbeard or couchpotato ..

**Comment by capkokoon** [comment]
You better use SickRage, which has a built-in support for rTorrent. Couchpotato has it as well

Considering that you're using the stock version of the rutorrent spk, here are the settings for Couchpotato .

!(Settings)[http://i.imgur.com/slNq7Ne.png]

**Comment by Dr-Bean** [comment]
Should be solved then. If not, let us know.
