### ISSUE TITLE
Compiling Zabbix

### ISSUE THREAD

**Issue by RustyPixel** [SynoCommunity/spksrc#716]
Hi, just a quick question.
I have been trying to compile zabbix server but keep getting and error which I'm unable to solve the output i get is 

```
make[5]: *** No rule to make target `../../src/libs/zbxsysinfo/cedarview/libspecsysinfo.a', needed by `zabbix_server'.  Stop.
make[5]: Leaving directory `/root/spksrc/cross/zabbix/work-cedarview/zabbix-2.2.0/src/zabbix_server'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/root/spksrc/cross/zabbix/work-cedarview/zabbix-2.2.0/src/zabbix_server'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/root/spksrc/cross/zabbix/work-cedarview/zabbix-2.2.0/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/spksrc/cross/zabbix/work-cedarview/zabbix-2.2.0'
make[1]: *** [compile_target] Error 2
make[1]: Leaving directory `/root/spksrc/cross/zabbix'
make: [arch-cedarview] Error 2 (ignored)
```

I don't require you to do the donkey work for me, just some advise as we all have to learn :) thx

**Comment by JvdW** [comment]
I cloned your repo for your zabbix work and it compiled and runs fine on my DS214play (cedarview). Had to adjust the Makefile for this ARCH and also upgraded to zabbix-2.4.3. All works fine. Would be nice to see your work in the official spksrc :-)
Thanks again for your work!

Joop

**Comment by RustyPixel** [comment]
@JvdW #1119 and #1120 sat here for six months, so I pulled them as it felt it wasn't wanted, along with #1101 and #1099, I have spent some to time over the holidays and change MySQL to mariadb, which is sitting on my build system. I have also be mainly focus on SOGo for synology which my work is on the synology main forum.

**Comment by Diaoul** [comment]
@RustyPixel: sorry, very little time available to review all the PR. As you can see we have a lot of them. I recently merged Mosquitto which was sitting there for quite some time too.

Just leave them open, we'll review them but I cannot say when. It happens faster when there is high demand (see Mono & Sonarr) but still takes some time.

**Comment by Dr-Bean** [comment]
If memory serves, one of the reasons we could not merge Zabbix earlier was because it required the DSM5 toolchains, right? Thought that was mentioned in the previous PR's at least. Those toolchains have finally been merged about two weeks ago, which is why we could get going with Sonarr too, for instance.

**Comment by RustyPixel** [comment]
@Dr-Bean Sorry but that incorrect, zabbix,  zabbix agents and the other two packages where done with 4.3 toolchain, the package that needed DSM5 was xbmx server only mode

**Comment by Dr-Bean** [comment]
My bad, guess I remembered that wrong :)
