### ISSUE TITLE
Boost package not compiling (and libtorrent obsolete?)

### ISSUE THREAD

**Issue by gizmocuz** [SynoCommunity/spksrc#732]
It seems libtorrent is at this moment the only one requiring boost. (besides my package domoticz)
compilation stops because the cross/boost depends on Python, python stops with '_struct' not found

From what i see, 'libtorrent' is not used anymore.
It also stops compiling with '.deps/GeoIP.Tpo' not found (tested only with arch-88f6281)

Is it possible to:
- cross/boost/Makefile -> remove all python references
- maybe remoce libtorrent

With the above boost patch i can successfully compile my package (with some modifications, committing soon)

/Rob

**Comment by jorikcaljouw** [comment]
I think this issue can also be closed. Domoticz package does indeed use boost and it can be cleanly compiled for a while now.

**Comment by Dr-Bean** [comment]
Agree, let's do that :)
