### ISSUE TITLE
rutorrent SPK

### ISSUE THREAD

**Issue by davida72** [SynoCommunity/spksrc#75]
I use rutorrent as a bittorrent client. It's a front end to rtorrent. I've been running it for a year or so and it's rock solid but a pain to set up.

http://code.google.com/p/rutorrent/

**Comment by rewozz** [comment]
Guys, do yourselves a favor and bootstrap your boxes and use the new Qnapware:

http://forum.synology.com/enu/viewtopic.php?f=40&t=95346

There's an rtorrent-easy-install package that's way better than this, it's up to date and easy to maintain with okpg update and okpg upgrade command. You'll need to follow the instructions but it's no biggie, plus you learn something valuable.

If you need help just ask in the thread I linked.

Cheers!

**Comment by Diaoul** [comment]
GUI and CLI are two different things and I wouldn't say one is better than another. That's just not comparable. In terms of features I don't see how a package installed with Entware would be any better and you don't give any details. Consider this a gentle warning, further opinionated messages to make your own advertisement will be deleted.

@Dr-Bean: can we close this issue?

**Comment by Dr-Bean** [comment]
Agree, at least to prevent this issue from becoming a dumping ground for unrelated stuff.

At readers:
The rutorrent package is in beta, and as such, there might be problems with it. You can report those problems in a new issue. Before doing so, check existing (open) issues. Please be patient if you do not get an immediate response.

If you'd like to contribute, and make improvements to the package, you're welcome to open a pull request.

**Comment by rewozz** [comment]
The benefit is that the CLI is stable and not a beta. I didnt mean to offend anyone, I appreciate the work you guys have done!

**Comment by Dr-Bean** [comment]
No offense taken. You're free to choose any installation method you prefer, be it manual, optware or package. However, considering optware is off topic for this repository, please refrain from discussing it here.
