### ISSUE TITLE
Mystic BBS

### ISSUE THREAD

**Issue by takashi1** [SynoCommunity/spksrc#769]
hi - the mystic bbs project is again quite active, they have now also a ARM and linux based installation available. would be great to run this on the synology. It looks simple to install (scripted) however not yet sure if there is the ability to make a web interface for the configuration. 

anyone else interested to run a telnet BBS on the synology? Since I'm not able to create packages (lack of knowledge) it would be great if that can be done through the community.

thanks
##

**Comment by SuperDOS** [comment]
would like to see this happen as well :)

**Comment by hgy59** [comment]
Since Mystic BBS is not open source anymore, the chance is very low that someone will merge a linux installer into an spk...
_I did not find any source but the hint [here](https://github.com/fidosoft/mysticbbs)_
