### ISSUE TITLE
Darkstat doesn't work with bonded NICs.

### ISSUE THREAD

**Issue by cul8rmom1** [SynoCommunity/spksrc#770]
I can stop the process and start it with bond0 and it works fine.  Cant seem to figure out where the config is for darkstat or where it is started with the eth0.  Any help would be appreciated.  A feature enhancement for future version to run on enabled interfaces would be nice as well.

Running DS1812 and DS1813. 
Currently only installed on the 1813.  
DS1813+
CPU clock rate
2.13 GHz
CPU cores
2
Total Physical Memory
4096 MB
DSM version
DSM 4.3-3810 Update 2

**Comment by MMD70** [comment]
"A feature enhancement for future version to run on enabled interfaces would be nice as well"

+1
