### ISSUE TITLE
Status of Disk Utils (e2fsprogs) spk

### ISSUE THREAD

**Issue by moneytoo** [SynoCommunity/spksrc#784]
I was trying the new version of e2fsprogs 1.42.9 and realized there's already e2fsck, mkfs and other binaries in `/sbin` from Synology (currently 1.42.6). Is the spk needed for something that isn't available in the Synology build?
##

**Comment by endelight** [comment]
Hello moneytoo,

can you please tell me how you get to run e2fsprogs v1.42.9?

Regards,
endelight
