### ISSUE TITLE
Rutorrent - Torrents added in "stopped" state

### ISSUE THREAD

**Issue by Schiznit** [SynoCommunity/spksrc#790]
Using watch folder, RSS or manually adding torrent adds the torrent but in status "stopped" and I need to start it manually. I have not checked the box "do not start download". All ways I have added torrents makes this happen. I use the latest beta package from synocommunity on a Synology Ds212j NAS.

**Comment by Dr-Bean** [comment]
Probably fixed with the newly released package, seeing as I can't reproduce it (although there's a new option to disable the open-basedir from the start, that would seem related).
Seeing as you've been able to solve it yourself, I'm closing this issue.
