### ISSUE TITLE
Debian Chroot DS713+  WARNING SETLOCALE

### ISSUE THREAD

**Issue by ghost** [SynoCommunity/spksrc#820]
Hello
I have install on my DS713+  new beta DSM 5.0. Aftre that i installed Debian Chroot from synocommunity. When i go from cmd to debian i have a warning...

Synology_DS713> chroot /volume1/@appstore/debian-chroot/var/chroottarget /bin/bash
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
root@Synology_DS713:/#

I try this:

root@Synology_DS713:/# dpkg-reconfigure locales
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = "en_US.utf8",
        LANG = "en_US.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
dpkg-query: package 'locales' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: locales is not installed
root@Synology_DS713:/#

How i can solved this problem ?
On my old DS213 i have not this problem...

Please help me. I am beginner.

**Comment by EZS-JD** [comment]
This link no longer works. new link?
