### ISSUE TITLE
sabnzd not cross-compiling on Raspberry PI

### ISSUE THREAD

**Issue by andreashouben** [SynoCommunity/spksrc#828]
Hi there, I'm using a raspberry for my linux-stuff and now I'm trying to create myself an actual sabnzd with spksrc. The make process stops at:

/home/andi/Synology/spksrc/toolchains/syno-armadaxp/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-gcc: Kann die Datei nicht ausführen. (cannot execute file)

I tried executing the bin file manually, but the same error occurs. Any advice?

**Comment by digitalbox94** [comment]
You can patch spksrc toolchain by adding a "syno-rpi-6.1" for instance, which is linked to the RPI toolchain from Raspberry (https://github.com/raspberrypi/tools)
It works fine for compiling tools like "unzip" or other libs
