### ISSUE TITLE
apt-get on qoriq giving illegal instruction

### ISSUE THREAD

**Issue by stefaanbolle** [SynoCommunity/spksrc#834]
When running apt-get in debian-chroot on a DS213+ I always get illegal instruction without any additional information.

I'm running debian-chroot version 7.3-4 (compiled myself from spksrc)

Anyone who knows how to solve?
Thanks!

**Comment by devaudio** [comment]
so, if this is a known issue, whis does it still allow you to install qoriq from syno community, and still list it in packages... shouldn;t it be removed?
