### ISSUE TITLE
Can't install owncloud on DSM 4.0

### ISSUE THREAD

**Issue by Baden2014** [SynoCommunity/spksrc#856]
hello
after a successful download over the packagemanager the installation fail.
this is the error:
ar  2 19:46:52 PkgMan.cgi: pkgtool.cpp:2013 Failed to run preinst script for owncloud
Mar  2 20:54:31 PkgMan.cgi: pkgtool.cpp:1954 Failed to extract package INFO from /volume1/@tmp/@synopackage/owncloud/@SYNOPKG_DOWNLOAD_owncloud

i have a synology 108j with DSM 4.0 2262

thanks for your help

**Comment by Dr-Bean** [comment]
Closing. DSM4.0 isn't supported anymore, and along with that, up-to-date versions of Owncloud can't run on older version of DSM due to PHP limitations (see #1827)
