### ISSUE TITLE
Nagios/Ichinga?

### ISSUE THREAD

**Issue by sshaikh** [SynoCommunity/spksrc#859]
For monitoring?

Seems to be open source and packages already exist:

http://blogger.smorg.co.uk/2014/01/synagios-nagios-for-synology-nas-boxes.html
http://nagrestconf.smorg.co.uk/installguides/synology.php

**Comment by SeppPenner** [comment]
> Well, if packages already exist, there's not much use in redoing that, right?
> Besides: this link and that link indicate the developer plans to have the packages included as official Synology packages.

Doesn't seem to be available. I opened a new request here https://github.com/SynoCommunity/spksrc/issues/2542 a time ago.

**Comment by m4tt075** [comment]
Following some of the older links indicates that at least Synagios packages (Nagios for Synology) are available. It even seems they are still maintained. [Here](http://nagrestconf.smorg.co.uk/downloads.php) the download link. Have you tried those?

**Comment by SeppPenner** [comment]
> Following some of the older links indicates that at least Synagios packages (Nagios for Synology) are available. It even seems they are still maintained. Here the download link. Have you tried those?

This looks quite interesting. I will try to test it whenever I manage to 👍 (Time is always an issue :D)
