### ISSUE TITLE
Chromaprint tools

### ISSUE THREAD

**Issue by rednoah** [SynoCommunity/spksrc#902]
Has anyone managed to compile fpcalc (and the  ffmpeg dependencies) with the DSM toolchains?

http://acoustid.org/chromaprint

**Comment by rednoah** [comment]
Added bounty for contributing a Chromaprint fpcalc command-line utility make instructions to spksrc so that packages we can get it as package from SynoCommunity and all Synology platform.

[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=2981816)](https://www.bountysource.com/issues/2981816-chromaprint-tools?utm_source=2981816&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by cytec** [comment]
@rednoah if ffmpeg is the only dependence that should be doable

**Comment by rednoah** [comment]
Lukas, the developer of fpcalc, already got it working specifically for arm7hf just to see if it's feasible. Works fine here, but only for DS213J and the likes. I don't know exactly how he did it though. I never got it compiling with spksrc with any of the toolkits. If there was packages for all platforms that would be really nice.

**Comment by cytec** [comment]
well there is already a `boost` package in `cross` and also an `ffmpeg` seems like the only missing depend is `taglib` and then it _should_ be working ;)

**Comment by rednoah** [comment]
Sure, let me know if you need help with testing. Lukas is also really nice in helping, as long as you generally know what you're doing I guess. :D

**Comment by isujinx** [comment]
There was some good explanation of the compiling process for chromaprint on the Bliss site, but this is way over my head programming wise.  I'd just like to see a fpcalc package!  Not sure how to add the bounty thing like rednoah - but I'd throw in $20 to see it done.

**Comment by cytec** [comment]
I'll probably/hopefully have access to my VM tomorrow... hopefully i can give it a try then.
keep you updated

**Comment by cytec** [comment]
@rednoah good news got it working on my DS1513+ (cedarview):

	daenerys> /usr/local/chromaprint/bin/fpcalc
	usage: /usr/local/chromaprint/bin/fpcalc [OPTIONS] FILE...
	
	Options:
	  -version      print version information
	  -length SECS  length of the audio data used for fingerprint calculation (default 120)
	  -raw          output the raw uncompressed fingerprint
	  -algo NAME    version of the fingerprint algorithm

**Comment by cytec** [comment]
seems that somehow rlink is not working correctly but i don't know how to set it correctly for cmake... maybe @Diaoul or @Dr-Bean have an idea on that?

**Comment by Diaoul** [comment]
@cytec: IDK but [this](http://www.cmake.org/Wiki/CMake_RPATH_handling) seems to explain a lot of variables involved in the RPATH stuff.

**Comment by cytec** [comment]
got it thanks :)

**Comment by cytec** [comment]
@Diaoul is there a way to make a PLIST file for spk also? seems like there is a lot of stuff generated which isn't needed at all (ffmpeg binaries etc)

**Comment by Diaoul** [comment]
Filtering out some stuff can be done in a extra install rule like python.
PLIST filtering for SPK is not implemented yet. If you want you can give it
a shot.

**Comment by rednoah** [comment]
If you need some testing for armada370  builds let me know.

**Comment by isujinx** [comment]
Not that I'll be terribly helpful in troubleshooting, but let me know if you need Intel testing.

Glad you got it working!

**Comment by cytec** [comment]
i've compiled a version for armada370 and currently doing a x64 compile.
Test SPK's will be available here:
https://cytec.us/syno/test-spk/chromaprint/

this only installs `fpcalc` to `/usr/local/chromaprint/bin/fpcalc` atm any feedback is welcome

**Comment by cytec** [comment]
@Diaoul @rednoah asked to link `fpcalc` to `/usr/local/bin` or `/usr/bin` what do you think? personally i'm not really a fan of linking binaries and would leave that to the user...

**Comment by rednoah** [comment]
Works well on armada370.

If you don't wanna link the binary into the $PATH thats fine for me. I can hardcode `/usr/local/chromaprint/bin/fpcalc` into my lookup path.

**Comment by cytec** [comment]
Nice!
yeah i think that'll be the prefered way, lets wait for @Diaoul to comment his thoughts on that but i'm pretty sure he doesn't like linking it anywhere :D

**Comment by Diaoul** [comment]
Well for command line only utilities it's accepted to link binaries into /usr/local/bin. For example `mc` and `nano` (PR pending) do that.

**Comment by cytec** [comment]
ok i'll change the link to `/usr/local/bin` then

**Comment by isujinx** [comment]
x64 Build works great!  I ran filebot's sysinfo, it found my old version of fpcalc, deleted it and ran sysinfo, and it failed fpcalc.  Then installed the spk from the test site, modified filebot.sh back to the original place it looked for fpcalc, ran sysinfo and it found the new version of fpcalc!

Great work!

**Comment by cytec** [comment]
seems like i can rename my PR and remove the WIP? anyone getting any errors/problems so far?

**Comment by rednoah** [comment]
No problems on my DS213J (armada370) so far.

**Comment by Dr-Bean** [comment]
Chromaprint 1.2-1 has been published on the repository on the beta channel. I'll leave this issue open for feedback, for now.

**Comment by Diaoul** [comment]
@cytec: you can also claim that bounty I believe

**Comment by rednoah** [comment]
I'm not sure how Bounty Source works, but I think it's linked to this GitHub issue, so if this issue is closed then the bounty should be claimable.
