### ISSUE TITLE
Updating to 6.0.2-3 flushes the content !

### ISSUE THREAD

**Issue by sgrienen** [SynoCommunity/spksrc#905]
Hi,

A friend of mine, already using ownCloud on his Synology NAS told me to be careful, because updating the package would probably flush the content stored in ownCloud, he already had this issue earlier with a previous version. I did the test, stored very few content first, waited for the next release to come, and I did the update yesterday : all the content was set back to default, and I lost everything I stored there... Is there an option to avoid that for next update ? Is there a bug in the update process ?

Thanks !
Stéphane

**Comment by Dr-Bean** [comment]
I'm thinking about closing this issue. I can't see how the problem could pop up, with one exception: if you store your data in the /web/owncloud dir. That dir is replaced on upgrade, and except for the config file, everything is removed. Thoughts?

**Comment by Dr-Bean** [comment]
No thoughts? :/ 
As a reminder for future readers, don't store your data in the web folder, that's a bad idea. Place your data in a normal shared folder instead.
