### ISSUE TITLE
Problem from compilation TVHeadend 3.9 from git

### ISSUE THREAD

**Issue by PiterEL** [SynoCommunity/spksrc#922]
When i use this configuration in cross/tvheadend/makefile
PKG_NAME = tvheadend
PKG_VERS = 3.9~git6482d3
PKG_EXT = tar.gz
PKG_DOWNLOAD_METHOD = git
PKG_GIT_HASH = 6482d33ba9
PKG_DIST_NAME = tvheadend.git
PKG_DIST_SITE = https://github.com/tvheadend
PKG_DIST_FILE = $(PKG_NAME)-git$(PKG_GIT_HASH).$(PKG_EXT)
PKG_DIR = $(PKG_NAME)-git*

DEPENDS = cross/openssl

HOMEPAGE = https://www.lonelycoder.com/tvheadend/
COMMENT  = Tvheadend is a TV streaming server for Linux supporting DVB-S, DVB-S2, DVB-C, DVB-T, ATSC, IPTV, and Analog video (V4L) as input sources
LICENSE  =

GNU_CONFIGURE = 1
CONFIGURE_ARGS = --disable-avahi --release

i have this problem:
/work-cedarview/install//usr/local/tvheadend/include 
  Build for arch:                          cedarview

Binaries:
  Using PYTHON:                            python

Options:
  cwc                                      yes
  v4l                                      no
  linuxdvb                                 yes
  iptv                                     yes
  tsfile                                   yes
  dvbscan                                  yes
  timeshift                                yes
  trace                                    yes
  imagecache                               no
  avahi                                    no
  zlib                                     yes
  libav                                    no
  inotify                                  no
  curl                                     no
  epoll                                    yes
  uriparser                                no
  ccache                                   no
  bundle                                   no
  dvbcsa                                   no
  kqueue                                   no
  execinfo                                 yes
  mmx                                      yes
  sse2                                     yes
  getloadavg                               yes
  atomic32                                 yes
  atomic64                                 yes
  py_gzip                                  yes
  bin_bzip2                                yes
  ssl                                      yes
  dvbapi                                   yes
  mpegts                                   yes
  mpegps                                   no

Packages:
  openssl                                  1.0.0l
  zlib                                     1.2.8

Installation paths:
  Prefix:                                  /usr/local/tvheadend
  Binaries:                                ${prefix}/bin
  Libraries:                               ${prefix}/lib
  Data files:                              ${prefix}/share
  Man pages:                               ${datadir}/man

Final Binary:
  /home/piotrek/spksrc/spk/tvheadend/work-cedarview/tvheadend-git6482d33ba9/build.linux/tvheadend

Tvheadend Data Directory:
  /usr/local/tvheadend/share/tvheadend

===>  Compiling for tvheadend
make[3]: Wejście do katalogu `/home/piotrek/spksrc/spk/tvheadend/work-cedarview/tvheadend-git6482d33ba9'
CC              src/version.o
CC              src/main.o
CC              src/tvhlog.o
CC              src/idnode.o
CC              src/prop.o
CC              src/utils.o
CC              src/wrappers.o
CC              src/access.o
CC              src/dtable.o
CC              src/tcp.o
src/tcp.c: In function 'tcp_server_loop':
src/tcp.c:492: warning: dereferencing type-punned pointer will break strict-aliasing rules

CC              src/url.o
CC              src/http.o
CC              src/notify.o
CC              src/file.o
CC              src/epg.o
CC              src/epgdb.o
CC              src/epggrab.o
CC              src/spawn.o
CC              src/packet.o
CC              src/streaming.o
CC              src/channels.o
CC              src/subscriptions.o
CC              src/service.o
CC              src/htsp_server.o
CC              src/htsmsg.o
CC              src/htsmsg_binary.o
CC              src/htsmsg_json.o
CC              src/htsmsg_xml.o
CC              src/misc/dbl.o
CC              src/misc/json.o
CC              src/settings.o
CC              src/htsbuf.o
CC              src/trap.o
CC              src/avg.o
CC              src/htsstr.o
CC              src/tvhpoll.o
CC              src/huffman.o
CC              src/filebundle.o
CC              src/config2.o
CC              src/lang_codes.o
CC              src/lang_str.o
CC              src/imagecache.o
CC              src/tvhtime.o
CC              src/descrambler/descrambler.o
CC              src/service_mapper.o
CC              src/input.o
CC              src/http/http_client.o
CC              src/fsmonitor.o
CC              src/api.o
CC              src/api/api_status.o
CC              src/api/api_idnode.o
CC              src/api/api_input.o
CC              src/api/api_channel.o
CC              src/api/api_service.o
CC              src/api/api_mpegts.o
CC              src/api/api_epg.o
CC              src/api/api_epggrab.o
CC              src/api/api_imagecache.o
CC              src/parsers/parsers.o
CC              src/parsers/bitstream.o
CC              src/parsers/parser_h264.o
CC              src/parsers/parser_latm.o
CC              src/parsers/parser_avc.o
CC              src/parsers/parser_teletext.o
CC              src/epggrab/module.o
CC              src/epggrab/channel.o
CC              src/epggrab/module/pyepg.o
CC              src/epggrab/module/xmltv.o
CC              src/plumbing/tsfix.o
CC              src/plumbing/globalheaders.o
CC              src/dvr/dvr_db.o
CC              src/dvr/dvr_rec.o
CC              src/dvr/dvr_autorec.o
CC              src/dvr/dvr_cutpoints.o
CC              src/webui/webui.o
CC              src/webui/comet.o
CC              src/webui/extjs.o
CC              src/webui/simpleui.o
CC              src/webui/statedump.o
CC              src/webui/html.o
CC              src/webui/webui_api.o
CC              src/muxer.o
src/muxer.c: In function 'muxer_cache_update':
src/muxer.c:461: warning: implicit declaration of function 'posix_fadvise'
src/muxer.c:461: error: 'POSIX_FADV_DONTNEED' undeclared (first use in this function)
src/muxer.c:461: error: (Each undeclared identifier is reported only once
src/muxer.c:461: error: for each function it appears in.)
make[3]: *** [/home/piotrek/spksrc/spk/tvheadend/work-cedarview/tvheadend-git6482d33ba9/build.linux/src/muxer.o] Błąd 1
make[3]: Opuszczenie katalogu `/home/piotrek/spksrc/spk/tvheadend/work-cedarview/tvheadend-git6482d33ba9'
make[2]: *** [compile_target] Błąd 2
make[2]: Opuszczenie katalogu `/home/piotrek/spksrc/cross/tvheadend'
make[1]: *** [depend_target] Błąd 2
make[1]: Opuszczenie katalogu `/home/piotrek/spksrc/spk/tvheadend'
make: [arch-cedarview] Błąd 2 (zignorowany)
piotrek@debian:~/spksrc/spk/tvheadend$ 

What i must do ? Is my config makefile is ok ?

**Comment by Dr-Bean** [comment]
Closing, #931 is where the testing package is at. PR's to update the main TVHeadend package are welcome, I suppose ;)
