### ISSUE TITLE
Update kernels for DSM5

### ISSUE THREAD

**Issue by bru7us** [SynoCommunity/spksrc#939]
This is an item for tracking and discussion of the pending update to the kernels used in spksrc.

As far as I know, there is only one released package that depends directly on the kernel sources (LIRC), however it seems some other people like to have access to the kernel sources for some non-provided driver compilation (@jdierkse?) and PR #664 will also depend on it.

One concern that I have is moving forward with DSM5 kernels will block backwards compatibility for DSM4, because packages with drivers that depend on the particular kernel version will not be able to load.

Thoughts @Diaoul ? Perhaps I can just roll and publish a final "LIRC_DSM4" package, then migrate the tip to DSM5?

**Comment by Dr-Bean** [comment]
Added DSM5 (and 5.1) kernels while adding the multiple toolchain support. I think that's about all that's needed for this to be completed?

**Comment by bru7us** [comment]
Yeah I think so! Multi-version/toolchain support negates the back-compatibility issue I was concerned with.
