### ISSUE TITLE
Add HDHomeRun driver packages

### ISSUE THREAD

**Issue by jdierkse** [SynoCommunity/spksrc#958]
I'm currently in the process of making a HDHomerun driver package.
I've created packages for DSM 4.3 (1.0.0) and DSM 5.0 (1.0.1) for just about every relevant architecture, and they can be found on http://syno.dierkse.nl
If there are people who can test these packages, that would be awesome.
Meanwhile I'll finalize the creation and create a pull request once done.

**Comment by frjtrifork** [comment]
I had the same issue as @winno - hdhomerun driver not starting after reboot because resources existed in the filesystem.

By adding the 

    rm -rf /dev/hdhomerun_*
    rm -rf /dev/dvb/*

lines in the beginning of the start_daemon function in /var/packages/hdhomerun/scripts/start-stop-status  the driver now starts consistently instead of failing when restarting the NAS. 

For me the problem was triggered after a power failure - which would explain why the stop_daemon function did not delete the dev/hdhomerun_* and  /dev/dvb/* files - it was not executed. 

So it might be more reliable to put the deletes in the start function - in case of the NAS not getting shut down properly.

**Comment by joensson** [comment]
I had the same issue as @winno - hdhomerun driver not starting after reboot because resources existed in the filesystem.

By adding the 

    rm -rf /dev/hdhomerun_*
    rm -rf /dev/dvb/*

lines in the beginning of the start_daemon function in /var/packages/hdhomerun/scripts/start-stop-status  the driver now starts consistently instead of failing when restarting the NAS. 

For me the problem was triggered after a power failure - which would explain why the stop_daemon function did not delete the /dev/hdhomerun_* and  /dev/dvb/* files - it was not executed. 

So it might be more reliable to put the deletes in the start function - in case of the NAS not getting shut down properly. Currently - once the shutdown has not happened properly a single time - the driver cannot start - not even a reinstall will fix the issue since the /dev/hdhomerun_* and  /dev/dvb/* files are still there.

**Comment by Mr-MarQuez** [comment]
i'm experiencing some strange problems with timeshift on my DS214play (DSM 5.1-5021 Update 2). When I start the tvheadend 3.9.2479-1 service timeshift is working without a problem, but when I the stop live tv and then start it again I get an error in the logs that the buffer is full.

DiskStation> tail -f tvheadend.log | grep timeshift
2015-02-22 18:55:45.440 [  DEBUG]:htsp: using timeshift buffer (60 mins)
2015-02-22 18:58:54.370 [  DEBUG]:timeshift: ts 0 remove /volumeUSB1/usbshare/buffer/0/tvh-7
2015-02-22 18:58:54.370 [  DEBUG]:timeshift: ts 0 remove /volumeUSB1/usbshare/buffer/0/tvh-8
2015-02-22 18:58:54.370 [  DEBUG]:timeshift: ts 0 remove /volumeUSB1/usbshare/buffer/0/tvh-9
2015-02-22 18:58:55.842 [  DEBUG]:timeshift: ts 0 remove /volumeUSB1/usbshare/buffer/0/tvh-10
2015-02-22 18:59:20.408 [  DEBUG]:htsp: using timeshift buffer (60 mins)
2015-02-22 18:59:21.353 [  DEBUG]:timeshift: ts 1 buffer full
2015-02-22 19:00:30.684 [  DEBUG]:htsp: using timeshift buffer (60 mins)
2015-02-22 19:00:31.673 [  DEBUG]:timeshift: ts 2 buffer full

My config for timeshift is currently like shown below but i tried already all possibilities which are possible.

{
	"enabled": 1,
	"ondemand": 0,
	"path": "/volumeUSB1/usbshare",
	"unlimited_period": 0,
	"max_period": 3600,
	"unlimited_size": 0,
	"max_size": 1808,
	"ram_size": 0,
	"ram_only": 0
}

Does someone else experience the same problem or can help to resolve this?

Thanks

**Comment by zzo** [comment]
lame question but the x86 version of hdhomerun isn't compatible with the 415+?  Am I screwed or can I just edit the INFO file to add my cpu (forget what it's called 'avotom' or something like that)?
thanks!

**Comment by Trippleblack** [comment]
@zzo : don't think it is a lame question. Just tried to do so but no luck.

I have a DS415+ (DSM .1) and would really like to install the HDH driver OR the TVH which includes it.

Where do I start?

**Comment by Smiggel** [comment]
@Trippleblack Add http://syno.dierkse.nl to your package sources in the nas. The latest TVH with the HDH driver included can be installed.

**Comment by Trippleblack** [comment]
WOW, perfect!

It is installed and sees the hdhomerun tuner, looks great so far, many thanks!

**Comment by lemsayblam** [comment]
Thanks for your comment @Smiggel just got HDHomerun in the mail and was able to get my 215J to recognize it.  Thanks @jdierkse

**Comment by prdubois** [comment]
I got the error "Failed to install Tvheadend-testing" on my 215j with DSM 5.1-5022 Update 5.

**Comment by Smiggel** [comment]
Anyone else here who is having EPG problems? Since the last update, my EPG is not fully loading anymore. It always seems to stop with programs that are aired between 1am and 6 am. All programs before and after that are loaded normally.

Also Kodi can not load the EPG data correctly anymore.

**Comment by schumi2004** [comment]
Noticed it also but only once.
I also doubt this is a HDHomerun thing, i would blame TVH for this.

**Comment by Smiggel** [comment]
@schumi2004 I think it's TVH too. It worked fine all the time. Ever since I upgraded to the latest package it's not working correctly. Also can not downgrade without having to delete everything. :-(

**Comment by KlausStoertebeker** [comment]
Help!
I'm newbee to this and I just want to know where I can download ready-build spk's for my DS213air (look here for more details: http://forum.synology.com/wiki/index.php/What_kind_of_CPU_does_my_NAS_have).
I'm running System DSM5.2 (latest version)

**Comment by IamDan77** [comment]
Hey guys Im having an issue where my NAS wont find my 2 HDHomeruns. Ive tried installing the HDHomerun package but it fails to start.

It was working flawlessly and now this!! Any ideas?

**Comment by Peter-77** [comment]
Did you upgrade to DSM 6.0?

**Comment by IamDan77** [comment]
DSM 5.2-5644 Update 1

**Comment by Smiggel** [comment]
Hmmm sounds strange that is suddenly stopped working. If you restart the hdhomerun?

**Comment by IamDan77** [comment]
Restarted everything NAS, switches, router, tuners, htpc. 
Unfortunately my linux skills are not that good and cant make out much from the outputs above.
I have even deleted both the hdhomerun and tvheadend packages and re-installed (with the hdhomeun package unable to run)

**Comment by hlennaerts** [comment]
Tvheadend has hdhomerun support built in. So you don't need the hdhomerun package anymore. Could you try without it? Maybe you need manually to remove the kernel modules as described in one of the posts above, over a year ago

**Comment by IamDan77** [comment]
OK so remove them then re-install tvheadend?

**Comment by hlennaerts** [comment]
Yes. Note that you need tvheadend 4.0 or newer. I use the latest version from syno.dierkse.com with hdhomerun tuners and I'm very happy about it.

Another note about the latest tvheadend testing version: you might want to disable "use running state" in the recorder settings, if your recordings are incomplete. This is a new feature that doesn't work on all providers. Just some free advice ;-)

**Comment by Smiggel** [comment]
Just add syno.dierkse.com to your package center in the NAS.

Then you will see tvheadend-testing as an version you can download and install. His version has the hdhomerun driver build into it.

That should work.

**Comment by IamDan77** [comment]
Does TVHeadend leave any traces behind when I uninstall? Are there any folders/files I need to delete to get a completely clean install?

**Comment by hlennaerts** [comment]
Actually, if videostation can't find your hdhomeruns, I think you have a different problem. Can you find them using the config gui tool on a windows pc? You can download the setup from the silicondust website

**Comment by IamDan77** [comment]
Yes the hdhomeruns work perfectly with any windows or mac software i have thrown at it. Including the hdhomerun software. Its just the NAS that will not see them!
Again is there anyway to check the drivers or completely remove any existing footprint of tvheadend?

**Comment by Smiggel** [comment]
Beware when upgrading. 4.1.988 (ArmadaXP) is running fine. 

The latest package 4.1.1207 does not start when you update to this version.

When doing a clean install, you have to set a username and password for the default account. No matter what username and password you set, you can not login after that. :-(

Had to downgrade yesterday to .988. Bad thing is that I had to manually restore all my settings as there is nog easy way to backup and restore the settings.

**Comment by tocks53** [comment]
hello, can you help me the driver is not compil for my arch : avolon on 1815+

Can you compil the driver please ?

**Comment by jowandijkhuis** [comment]
Can anyone verify if the HDHomeRun 4DC works with DS414? Diskstation is running DSM 5.2-5644 Update 1. Tried installing HDHomeRun 1.0.1-1 but it the package doesn't run after installation. Do I really need to install this or does it come with compatible drivers included?

**Comment by helio58** [comment]
Hi, Using a sinology 415play , yesterday update to DSM6.0  , update tvheadend-testing to 4.1.1898-1 and -2.Using tvheadend with HDhomerun.
Axess the webpage , try to change Configuration DVB Inputs the page came up but just the word adapters. And as soon as i open this page tvheadend crashes.
Try to look at the log file, but no data.
I can use tvheadend-testing just now but unable to add a mux. Please is there a way to solve this? Thanks

**Comment by Dr-Bean** [comment]
@helio58 We do not provide a `tvheadend-testing` package, or a hdhomerun package for that matter. Report your problems to the person/repository where you got the package(s) from.

**Comment by Dr-Bean** [comment]
On that note, I'm going to close this issue. 
@jdierkse It looks like you're maintaining your own package repository. That's fine, but then I guess this particular issue won't be going anywhere. Feel free to open a PR if you reconsider.
