### ISSUE TITLE
[Request] Add MKVToolNix spk

### ISSUE THREAD

**Issue by Celeamas** [SynoCommunity/spksrc#974]
MKVToolNix shall be usefull for syno users who wants to merge srt to mkv through script.
##

**Comment by Brontoloo** [comment]
You can simply use ffmpeg(which is already included in dsm):
to add sub.srt to movie.mp4 just use
"ffmpeg -i "movie.mp4" -i "sub.srt" -c copy -map 0 -map 1 "movie.mkv"

**Comment by fn002449** [comment]
Ah!!! That is nice!! Thank you! I tried it and it works flawless.

Here is a code to add more than one subtitle to one mkv file
ffmpeg -i "old.movie.mp4" -i "dut.srt" -i "eng.srt" -c copy -map 0 -map 1 -map 2 -metadata:s:s:0 language=dut -metadata:s:s:1 language=eng "muxed.movie.mkv"

you can set -v (verbose level) and -y (if you want to overwrite the existing-file with output-file

Thx.

**Comment by BenjV** [comment]
I tested this on my i7 PC with a 1080 .mkv file.
With mkvmerge it took 45 sec to merge the subtitle and vidfeo into one file.
With ffmpeg it took about 45 minutes to do the same.

I don't think it will work on my DS414, it will take forever to do this with ffmpeg.

**Comment by BenjV** [comment]
It sure is faster but ffmpeg keep crashing with "unknown entry" while mkvmerge does it's job fine.
So still no luck.

**Comment by Brontoloo** [comment]
@BenjV You simply forgot or misspelled the ffmpeg option "-c copy" (without quotes).
That option means that the audio, video and subtitles streams will not be encoded, but copied over the new file

**Comment by BenjV** [comment]
@Brontoloo 
I thought that I dit a copy paste of the command from your posting but I tried it again today en now it was much faster.  So your probably right about that.
Not as fast as mkvmerge that did it in 29 sec and ffmeg in 55 sec but ffmpeg crashed when it was 95% finised.
So still no luck. Fast enough but crashing.

**Comment by aqzina** [comment]
Hi, I would like to second this request. Can someone say anything about the latest status for this package? Can the boost compilation issue have a workaround?

**Comment by M0UL** [comment]
any progress on this?

**Comment by kratz00** [comment]
I gave it a shot. One problem is compiler support, from the official MKVToolNix [README.md](https://github.com/mbunkus/mkvtoolnix/blob/master/README.md#21-requirements)

> A C++ compiler that supports several features of the C++11 standard: initializer lists, range-based "for" loops, right angle brackets, the "auto" keyword, lambda functions, the "nullptr" key word, tuples and alias declarations. For GCC this means at least v4.7.0; for clang v3.3 or later.

There are only a few tool chains which fulfil this requirement.
In my case,  DS214+ aka armadaxp, the compiler is too old. The only version of MKVToolNix which should work with this compiler version is version 7.7.0. The current MKVToolNix version is 8.5.2.
I am not sure if it makes sense to support such an *old* version (version 7.7.0 was released end of February this year).

**Comment by cytec** [comment]
seems like DSM6 toolchains come with gcc 4.9 which should finally add C++11 support...

**Comment by cytec** [comment]
just in case someone want's to fiddle with DSM6 Toolchains already, this may be a starting point.

	PKG_NAME = mkvtoolnix
	PKG_VERS = 8.9.0
	PKG_EXT = tar.xz
	PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
	PKG_DIST_SITE = https://mkvtoolnix.download/sources
	PKG_DIR = $(PKG_NAME)-$(PKG_VERS)
	
	DEPENDS  = cross/libogg cross/libvorbis cross/zlib cross/curl cross/flac cross/boost
	
	HOMEPAGE = https://mkvtoolnix.download/index.html
	COMMENT  = MKVToolNix is a set of tools to create, alter and inspect Matroska files under Linux, other Unices and Windows.
	LICENSE  = GPLv2
	
	GNU_CONFIGURE = 1
	
	COMPILE_TARGET = myCompile
	INSTALL_TARGET = myInstall
	
	ADDITIONAL_CXXFLAGS = -std=c++11
	
	include ../../mk/spksrc.cross-cc.mk
	
	CONFIGURE_ARGS = --with-boost-libdir=$(STAGING_INSTALL_PREFIX)/lib --prefix=$(STAGING_INSTALL_PREFIX) --enable-gui=no
	
	
	.PHONY: myCompile
	myCompile:
		$(RUN) ./drake
	
	.PHONY: myInstall
	myInstall:
		$(RUN) ./drake install

**Comment by GoodOmens83** [comment]
You look at optware-ng?  It's the new bootstrap.  They seem to have mkvtoolnix 8.8.0 working...

Checkout https://github.com/Optware/Optware-ng/blob/master/make/mkvtoolnix.mk

**Comment by cytec** [comment]
@Dr-Bean nope, didn't know about that... thanks i'll have a look.
The main problem with newer versions (at least for me) was that it depends on `nlohmann-json` which needs at least `GCC 4.8` to build and therefor was not building successfully in any of my tests... see https://github.com/mbunkus/mkvtoolnix/tree/master/lib/nlohmann-json

**Comment by GoodOmens83** [comment]
@cytec mkvtoolnix 4.2.0?  

No:

`synology> ipkg install mkvtoolnix`
`Installing mkvtoolnix (8.8.0-1) to /opt/...`
....
`synology> mkvextract --version`
`mkvextract v8.8.0 ('Wind at my back') 32bit`

But I'm on a x86 Synology nas

**Comment by goblix** [comment]
@GoodOmens83 

o.O
x86 Synology here too: DS1513+
Maybe there's a newer optware feed you're going off of ?

root@Diskstation:/# ipkg list | grep mkvtoolnix
mkvtoolnix - 4.2.0-1 - A set of tools to create, alter and inspect Matroska files
root@Diskstation:/# ipkg update
Downloading http://ipkg.nslu2-linux.org/feeds/optware/syno-i686/cross/unstable/Packages.gz
Inflating http://ipkg.nslu2-linux.org/feeds/optware/syno-i686/cross/unstable/Packages.gz
Updated list of available packages in /opt/lib/ipkg/lists/cross
Successfully terminated.
root@Diskstation:/#


Can you link your ipkg feed location?

**Comment by fn002449** [comment]
I just tried it on my DS214play (by opkg) and it installed version 4.2.0.

```
opkg install mkvtoolnix
Installing mkvtoolnix (4.2.0-3)
```

So for me its still not working.. sadly ;)

**Comment by balazsnyitray** [comment]
Ok i installed mkvtoolnix via ipkg optware-ng. whats next? is there a gui? or command line only? what commands are possible?

**Comment by Diaoul** [comment]
Please use a forum for discussion unrelated to SynoCommunity, this is a bug tracker.

**Comment by hgy59** [comment]
closed by #4622
