### ISSUE TITLE
Package UPnP Server with transcoding

### ISSUE THREAD

**Issue by Diaoul** [SynoCommunity/spksrc#98]
Probably Mediatomb, I don't want a Java dependency so Serviio is not an option

**Comment by 14buddy** [comment]
Yup

**Comment by 14buddy** [comment]
Can u help me get a free phone number

**Comment by 14buddy** [comment]
And how I can hook my internet from phone to my x box as well thanks and welcome back to the dark side Luke

**Comment by cytec** [comment]
@Diaoul @Dr-Bean is this still considered? i mean there is Plex and soon (hopefully) emby... but transcoding etc on ARM devices... personally i think thats not really a good idea

**Comment by Diaoul** [comment]
We can close this.
