### ISSUE TITLE
Add support for multiple major DSM versions in spksrc framework

### ISSUE THREAD

**Issue by bru7us** [SynoCommunity/spksrc#983]
@Diaoul has historically been pretty keen to just support the tip of released DSM versions (with updated toolchains/packages/etc), with backwards compatibility available when possible. If compatibility comes up, we always favoured the latest release and older releases potentially lost access to our packages.

There is some discussion in #939 and #982 about how we can handle situations where backwards compatibility is broken, but we still want to provide support for a large portion of the user base who haven't update yet.

I propose that we could implement some version handling in the framework and keep toolchain/kernel/package makefiles for several versions. There are many ways to pull this off, so it would be good to see a bit of discussion and a few different suggestions/angles before anyone tackles code.

One method that comes to mind is pushing makefiles one directory level deeper into a version folder (naming convention of synology DSM version, or synology "branch" number) with a symlink "latest" always pointing to the current latest supported version. We could then implement some variables to track what version of an SPK we want at compile time (latest, 4.3 [or 3776], all).

If DSM and the repo supports multiple versions of the same SPK (base on different FIRMWARE variable restrictions) then this could potentially appear seamless to the users - if not, we could provide "archived" direct download links on the spkrepo front end website)

@SynoCommunity/developers

**Comment by Dr-Bean** [comment]
Some optimizations are still to be merged via #1366 (I'm holding off on merging until spkrepo has x64 support, I think, and the PR needs a rebase/squash anyway), but in the meantime, spksrc currently supports multiple toolchain versions now. So, let's close this.
